### ISSUE TITLE
Feature Request: ExpireManager getting player

### ISSUE THREAD

**Issue by darknightcore** [IntellectualSites/PlotSquared#1001]
Please add a way to get the player from a purged plot through ExpireManager.

**Comment by MattBDev** [comment]
What you are asking for seems like it can be accomplished already through listening to events. I am closing this. Feel free to comment and elaborate on this if you aren't satisfied.

**Comment by boy0001** [comment]
Sorry, this was readded a while ago.
ExpireManager.getTimestamp(UUID uuid)
