### ISSUE TITLE
Good practice version naming

### ISSUE THREAD

**Issue by manuelgu** [IntellectualSites/PlotSquared#1002]
I am creating this ticket because I'm running into several issues with the way the plugin gets updated and versions are named.

A couple of weeks ago you have released version `3.3.1` including many bug fixes and improvements. Starting from that date, every other day you made commits to the repository without changing the version to `3.3.2-SNAPSHOT` or similiar. This is generally bad behaviour.

This causes major issues for example if you do method renamings, method movings etc etc.
Once you release a version, this one should not be touched anymore, except for any very important bug fixes. If you are however working on new features to implement, bugs to fix or anything else, you should start with a new version and tag it as `SNAPSHOT`.

It would be greatly appreciated if this (not too hard to do) could be done in the future to prevent developers heads from exploding ;)

**Comment by MattBDev** [comment]
Agreed. I noticed awhile after 3.3.1 was released. I will be pushing an update that begins 3.3.3-SNAPSHOT

**Comment by MattBDev** [comment]
fixed in 93ef066d7bdf2f206626567dd400b0e637278f11
