### ISSUE TITLE
Issues with claiming 3.3.1

### ISSUE THREAD

**Issue by fatboy2380** [IntellectualSites/PlotSquared#1004]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/zopaweweye
**Description of the problem:**
Cannot claim plots via /plot claim or /plot auto
**How to replicate**:
/plot claim /plot auto

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [X] Made sure you're using an updated version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by boy0001** [comment]
What is the output?

**Comment by fatboy2380** [comment]
@boy0001 
http://hastebin.com/fuvibuyimu

**Comment by boy0001** [comment]
Thanks. Updating the plugin should fix that.

**Comment by fatboy2380** [comment]
Thanks for the information
