### ISSUE TITLE
Converting Plotme>Plotsquared

### ISSUE THREAD

**Issue by sandmonkey** [IntellectualSites/PlotSquared#1009]
**Debug paste link**:
http://hastebin.com/evabuhezor
**Description of the problem:**
http://i.imgur.com/D33adqd.png
**How to replicate**:
I've managed to create the plotsquared tables in mysql db, but it says it cant convert the plots.db even though i have deleted plotme.jar... am i missing a step?
Make sure you've completed the following steps (put an X between of brackets):
- [X] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [X] Made sure you're using an updated version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by boy0001** [comment]
Can you attach your PlotMe config.yml ?

**Comment by sandmonkey** [comment]
[config.zip](https://github.com/IntellectualSites/PlotSquared/files/191865/config.zip)

**Comment by boy0001** [comment]
@MattBDev 
config.yml is missing the PlotMe version. Is that normal for some versions?

**Comment by boy0001** [comment]
@sandmonkey 
Can you verify that your plotme database file exists?

**Comment by sandmonkey** [comment]
[plots.zip](https://github.com/IntellectualSites/PlotSquared/files/193118/plots.zip)

**Comment by MattBDev** [comment]
@boy0001 That's normal for versions I believe 1.5.2 plotme is the first version with the version tag.

**Comment by sandmonkey** [comment]
@boy0001 @MattBDev What is the verdict?

**Comment by boy0001** [comment]
I'll test with your config/db in a sec

**Comment by sandmonkey** [comment]
@boy0001 Thank you

**Comment by boy0001** [comment]
Converted fine for me:
[PlotSquared.zip](https://github.com/IntellectualSites/PlotSquared/files/193995/PlotSquared.zip)
Note: Since I am missing your playerdata files it will show unknown until the owner logs in for you.

**Comment by boy0001** [comment]
@MattBDev 
There's no plot height for the PlotMe config.yml, does the road height control both, or is the plot height not configurable?

**Comment by boy0001** [comment]
Assuming fixed and that it was a version mismatch issue.
