### ISSUE TITLE
END OF FILE while parsing JSON

### ISSUE THREAD

**Issue by manuelgu** [IntellectualSites/PlotSquared#1010]
# Bug report
**Debugpaste**:
http://hastebin.com/neyibusuva

**Description of the problem:**
Every now and then the following stacktrace occurs in the console. http://hastebin.com/zamomefiro.avrasm

[See code](https://github.com/IntellectualSites/PlotSquared/blob/master/Bukkit/src/main/java/com/plotsquared/bukkit/uuid/SQLUUIDHandler.java#L130)

This might or might not be related to a problem that tab-completion for online players does not work for commands like `/plot home`.

Make sure you've completed the following steps (put an X between of brackets):
- [X] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [X] Made sure you're using an updated version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by boy0001** [comment]
It's the UUID fetcher, always a chance mojang's auth servers are down or some other connection problem.

**Comment by manuelgu** [comment]
I have seen this error come up multiple times in the last days. Don't pin me down to that, but I think it was since upgrading from 3.2.26 to 3.3.1 couple of days ago. [See diff](https://www.diffchecker.com/kchmj9il)

**Comment by boy0001** [comment]
Code hasn't changed, that's just some formatting.
