### ISSUE TITLE
reset plot to first stage

### ISSUE THREAD

**Issue by Eyalthesolo** [IntellectualSites/PlotSquared#1011]
hi,
how can i reset a plot to its first stare?
if i do '/plot reset' or '/plot delete' i'm getting a big hole and not the flat land i had.

**Comment by boy0001** [comment]
Updating the plugin should fix that issue.

**Comment by Eyalthesolo** [comment]
i`m on PlotSquared v3.3.2

**Comment by boy0001** [comment]
Can you provide a `/plot debugpaste` then?

**Comment by MattBDev** [comment]
@Eyalthesolo Do you still need help? This issue will be closed if not replied to after awhile
