### ISSUE TITLE
/plot reset giving me a big hole

### ISSUE THREAD

**Issue by Eyalthesolo** [IntellectualSites/PlotSquared#1013]
hi,
how can i reset a plot to its first stare?
if i do '/plot reset' or '/plot delete' i'm getting a big hole and not the flat land i had.
i`m on PlotSquared v3.3.2

**Comment by manuelgu** [comment]
`/plot clear` should work. If it doesn't, please provide a `/plot debugpaste`.

**Comment by MattBDev** [comment]
Please provide a `/plot debugpaste` or this issue will be closed in 24 hours
