### ISSUE TITLE
Plot move & copy not working properly

### ISSUE THREAD

**Issue by manuelgu** [IntellectualSites/PlotSquared#1014]
# Bug report
**Debug paste link**:
http://hastebin.com/tuzifonama

**Description of the problem:**
The `/plot move` and `/plot copy` command are not working properly. Moving a plot to a different location will remove all the blocks, unclaim the origin plot (not change the plot border and only clear but not remove the plot sign), claim the new plot but not change the border, set plot sign or move the blocks.

Copying works a little bit better. It copies all the blocks, leaves the origin plot untouched but does not change the border and set a sign at the new plot.

Another note: Entities wont get moved/copied.

**How to replicate**:
- Setup new plotworld
- Claim a plot, build random stuff on it
- Go to another plot and obtain the plot id via `/plot info`
- Go back to the origin plot and type either `/plot move X;Y` or `/plot copy X;Y`

Make sure you've completed the following steps (put an X between of brackets):
- [X] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [X] Made sure you're using an updated version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment]
Are entities copied? You mention they aren't moved but are they copied?

**Comment by manuelgu** [comment]
Neither copied nor moved

**Comment by manuelgu** [comment]
Update: https://github.com/IntellectualSites/PlotSquared/commit/ef4438889b369d6c82658d71495845f995171081 fixed blocks not moving for `/plot move`, sign and plot border are still not set.

**Comment by manuelgu** [comment]
This was mostly fixed in recent commits. Tested with latest version of PlotSquared (https://github.com/IntellectualSites/PlotSquared/commit/fab60a0d539d76e310ec60014d962dd2ab199997). The only issue that occurs is that moved/swapped/copied entities only show up once you leave the area and re-enter it again.

**Comment by boy0001** [comment]
That's a separate issue. Happens with `/plot set floor` as well. Need to also send packets for the entities but I'm too lazy.
