### ISSUE TITLE
Unable to reset custom home location to default home location

### ISSUE THREAD

**Issue by manuelgu** [IntellectualSites/PlotSquared#1015]
# Bug report

**Description of the problem:**
Using `/plot sethome none` will not reset the home location of the plot to its default home location

**How to replicate**:
- Claim a plot
- Move to a different location
- `/plot sethome`
- `/plot sethome none`
- `/plot home`

**Comment by MattBDev** [comment]
have you tested this fix?

**Comment by manuelgu** [comment]
Yes I have

**Comment by MattBDev** [comment]
KK. I'll pull
