### ISSUE TITLE
World edit doesn't support schematic file

### ISSUE THREAD

**Issue by sandmonkey** [IntellectualSites/PlotSquared#1017]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://pastebin.com/PSFZWJbj
**Description of the problem:**
http://goo.gl/pmMmxW
**How to replicate**:
Tried importing the schematic file using world edit which Plotsquared generated and result in this error. 

Make sure you've completed the following steps (put an X between of brackets):
- [] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [x] Made sure you're using an updated version of PlotSquared
- [] Made sure the bug/error isn't caused by any other plugin

**Comment by manuelgu** [comment]
Please provide a valid `/plot debugpaste`.
How did you generate the schematic file?
Do you mind sharing the schematic file with us for further testing?

**Comment by sandmonkey** [comment]
i also tried importing on mcedit, returned an unhandled exception
http://pastebin.com/qYmmLnNB

[PlotSquared.zip](https://github.com/IntellectualSites/PlotSquared/files/191941/PlotSquared.zip)

**Comment by MattBDev** [comment]
PlotSquared does not support MCEdit 2 schematic files.

**Comment by sandmonkey** [comment]
Do you have any idea why world edit returned an error though?

**Comment by MattBDev** [comment]
@sandmonkey I revised my comment. try regenerating the schematic. the data in the file is invalid.

**Comment by manuelgu** [comment]
@sandmonkey How did you generate the schematic?
I'm having no issues with `/plot schematic save`, moving the file to worldedit schematics folder and then loading `//schem load` and `//paste`.

**Comment by sandmonkey** [comment]
@MattBDev could you take my schematic file and regenerate plot.schematic for me? @manuelgu I recovered data after it was deleted last night and now it doesn't seem to be working. Please help me.

**Comment by MattBDev** [comment]
@sandmonkey I can't do that because I am very busy.

**Comment by sandmonkey** [comment]
@MattBDev Is there perhaps someone else who could help me with the problem I have?

**Comment by MattBDev** [comment]
@sandmonkey you can't generate the schematic again yourself?

**Comment by MattBDev** [comment]
@sandmonkey :point_left: *poke* anyone home

**Comment by sandmonkey** [comment]
@MattBDev How may I ask?

**Comment by MattBDev** [comment]
@sandmonkey do you not know how you did it the first time?

**Comment by sandmonkey** [comment]
@MattBDev Well you see you the schematic i originally saved was done so using world edit in the plots server which i lost too, however you could be referring to the generated schematic by plotsquared which is corrupt unfortunately. It's a lose lose situation for me.

**Comment by MattBDev** [comment]
That's why you should be using getting a new schematic. You keep bringing up worldedit which really isn't relevant.

**Comment by sandmonkey** [comment]
I know it's irrelevant to this section.. maybe i shouldn't complain here. But, i used schematics to build a bridge over the bridges template (because it looked appalling) and there onwards /plot debugregen to make the entire world better... it's just a lost alot of progress *sighs*

**Comment by boy0001** [comment]
Tested with PS 3.3.2, no issues exporting / downloading schematics. Those files you attached are corrupt (just 0s) and can't be recovered.

@MattBDev 
PlotSquared can use mcedit schematics fine, it just skips tile entity info (sign text etc).

**Comment by MattBDev** [comment]
@boy0001 I was referring to mcedit 2.0 schematics which use a different structure than the standard being used currently.

**Comment by codewarrior0** [comment]
Schematics exported from MCEdit 2.0 can be imported in MCEdit 1.0. 

The file structure is only changed in a backward-compatible way. Extra data is added to allow importing and exporting between Minecraft Forge worlds with different sets of block ID mappings, and the data can be safely ignored when dealing with only Vanilla blocks or importing into the same Forge world where it was exported.
