### ISSUE TITLE
Lighting in Schematics Broken

### ISSUE THREAD

**Issue by AnHonorableHobo** [IntellectualSites/PlotSquared#1020]
There is no bug info in console
[--Hastebin--](http://hastebin.com/fovodotoqa)

Issue: When i use a road schematic the lighting never transfers over (using lanterns and even tried glowstone) but they dont produce light unless you physically replace them).

Replicate: Just create a road with any object that makes light and use the commands to make it into a road for everything

Make sure you've completed the following steps (put an X between of brackets):
- [X] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [X] Made sure you're using an updated version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by augesrob** [comment]
This also occurs after world edit. Lighting will be glitched.

**Comment by manuelgu** [comment]
Would you mind enabling `random-light-updates` in the spigot.yml and test if this issue still occurs?

**Comment by augesrob** [comment]
@manuelgu I turned this setting to true. Same issues. 

https://i.gyazo.com/ae0e92e23d19b7011c0d03791edbc614.jpg

**Comment by sandmonkey** [comment]
I can say too i expeience this issue with the bridges template, the only reason why i still use glowstone.

**Comment by boy0001** [comment]
Spigot is meant to do the lighting for world generation, I already have an open ticket on the jira for that. I can add a relight command for the plots. Any idea how it gets messed up there?

**Comment by MattBDev** [comment]
Anyone able to confirm if this is still an issue? @boy0001 @manuelgu @augesrob @AnHonorableHobo

**Comment by boy0001** [comment]
Supposedly fixed in spigot a while ago, I haven't tested:
https://hub.spigotmc.org/jira/browse/SPIGOT-1753
