### ISSUE TITLE
Issue when removing/clearing/unclaiming plots

### ISSUE THREAD

**Issue by HeyMan7** [IntellectualSites/PlotSquared#1027]
**Debug paste link**:
http://hastebin.com/tibenubimu

**Description of the problem:**
I find that me (as the server owner) and my players, when clearing or unclaiming a plot, a huge hole appears in the middle of the plot. I am running the latest version according to /plots update
http://i.imgur.com/FcnPapJ.png

**How to replicate**:
I don't know how you would replicate this, but the hole appears every time a plot owner is removed.

**Comment by manuelgu** [comment]
You are running version `version: 3.3.0`. Please update to `3.3.2` and test again. https://www.spigotmc.org/resources/plotsquared.1177/update?update=79296

**Comment by HeyMan7** [comment]
@manuelgu The issue still exists in 3.3.3. http://i.imgur.com/vKiQJv4.png

**Comment by boy0001** [comment]
Don't use `/reload`, actually restart your server

**Comment by HeyMan7** [comment]
Bug has been fixed with updated version.
