### ISSUE TITLE
PlayMoveEvent

### ISSUE THREAD

**Issue by darkdragonxxxx** [IntellectualSites/PlotSquared#1029]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
When I try and do the command it says there's an internal problem.
**Description of the problem:**
I get this error in console, not sure what's it's doing.
http://pastebin.com/vesDYY2f

**How to replicate**:

Make sure you've completed the following steps (put an X between of brackets):
- [] Include `/plot debugpaste`
- [] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [] Made sure you're using an updated version of PlotSquared
- [] Made sure the bug/error isn't caused by any other plugin

**Comment by manuelgu** [comment]
Please provide a `/plot debugpaste`.

**Comment by darkdragonxxxx** [comment]
As I said, The plugins broken and doesn't say anything.

**Comment by manuelgu** [comment]
Cannot reproduce. Can you try to setup a second server and only run *the same* version of PlotSquared and see if you can replicate? Just drag the jar file over.

**Comment by boy0001** [comment]
PlotSquared failed to start. Check your full startup (post it here if you can't see anything). Things to check:
 - Database / plugin is configured correctly
 - Plugin compatibility

**Comment by darkdragonxxxx** [comment]
And this happened
**http://pastebin.com/ChS0MUL2**

**Comment by manuelgu** [comment]
The error message hints at [PlotArea:218](https://github.com/IntellectualSites/PlotSquared/blob/master/Core/src/main/java/com/intellectualcrafters/plot/object/PlotArea.java#L218). This is where the biome gets loaded.

Could you provide your `config/settings.yml` so we can troubleshoot a little bit more?

**Comment by darkdragonxxxx** [comment]
http://pastebin.com/c58CHXKh

**Comment by boy0001** [comment]
@darkdragonxxxx
> Check your full startup
Want to attach that here?

**Comment by darkdragonxxxx** [comment]
Might want to close this post and the second one I did, I made one just for all the errors I got.
