### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Johandrex** [IntellectualSites/PlotSquared#1030]
Debug paste link: http://hastebin.com/hunuquhuho

The server is crashing when a player confirms that they want their plot cleared or deleted their plots.

Example crash log: http://hastebin.com/upinavihez.avrasm

Version: 3.3.3 & 3.3.2

Spigot version: git-Spigot-a1b8bf3-f01861f

**Comment by boy0001** [comment]
Spigot bug. You can also replicate this issue using WorldEdit's regen: https://hub.spigotmc.org/jira/browse/SPIGOT-2118

Added a temporary workaround in a recent dev build:
ci.xephi.fr/job/PlotSquared/
