### ISSUE TITLE
some errors on clearing

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#1034]
http://pastebin.com/w9H8hmK6

**Comment by MattBDev** [comment]
Has this happened on multiple occasions or just this once? If it has only happened once I think we can just let it go, treat it as a one time thing, and move forward.

**Comment by PhanaticD** [comment]
the skulls was quite often, the other error once

**Comment by boy0001** [comment]
fastmode clearing.

**Comment by MattBDev** [comment]
Added better debug error message. I'll mark this as resolved for now.
