### ISSUE TITLE
Plot un-claimable

### ISSUE THREAD

**Issue by BackSlashM** [IntellectualSites/PlotSquared#1036]
# Bug report template (Follow this template unless you are making a feature request.)
http://hastebin.com/efizirapav

The plot is unclaimable, and cant be cleared or deleted

Try to claim the plot and it doesn't claim, just gives this error in the console:
http://hastebin.com/goneluqehe.avrasm

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by boy0001** [comment]
Update the plugin
