### ISSUE TITLE
Players interacting with everything on other player's plots.

### ISSUE THREAD

**Issue by VinexAx789** [IntellectualSites/PlotSquared#1039]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**: http://hastebin.com/hanicoxuwe

**Description of the problem:** Players are allowed to access other players chests, beacons, furnaces they can use everything.

**How to replicate**: It's not world guard or anything to do with the other plugins.

Make sure you've completed the following steps (put an X between of brackets):
- [X] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [X] Made sure you're using an updated version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by manuelgu** [comment]
Intended behavior, isn't it?
You can change that using the `use` flag. [Wiki](https://github.com/IntellectualSites/PlotSquared/wiki/Flag:-use)

**Comment by VinexAx789** [comment]
No, it's not intended. I'll try the use flag.

**Comment by VinexAx789** [comment]
Nvm thanks man. Anyway players can open doors? On other's plots.

**Comment by VinexAx789** [comment]
Nvm. I still need help.

**Comment by VinexAx789** [comment]
Everything works just players can't sell to the other players sell signs.

**Comment by boy0001** [comment]
Assumed to be fixed.

**Comment by VinexAx789** [comment]
I got a question

**Comment by boy0001** [comment]
Ask

**Comment by VinexAx789** [comment]
My roads I was messing with them and though the debug was a debug but now I can't reset them back.

**Comment by boy0001** [comment]
There's no undo command.

**Comment by VinexAx789** [comment]
So how will I fix this please don't tell me I have to reset the plots if I do I will lose everyone on my server.
