### ISSUE TITLE
Can't role back Plot Debug Road Schematic

### ISSUE THREAD

**Issue by VinexAx789** [IntellectualSites/PlotSquared#1040]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/foxumuyato
**Description of the problem:** I did what the instructions told me and I can't role back the roads without resetting the plots people will be pissed if I do that.

**How to replicate**:

Make sure you've completed the following steps (put an X between of brackets):
- [X] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [X] Made sure you're using an updated version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by boy0001** [comment]
If you want to change the schematic back you can delete the file in `plugins/PlotSquared/schematics/<world>/GEN_ROAD_SCH`, then use `/plot reload`

Note, this will not change existing road, you either need to redo debugroadregen, do a world trim, or a plot regenallroads

**Comment by VinexAx789** [comment]
sideroad or intersection what file is it?

**Comment by boy0001** [comment]
Both

**Comment by VinexAx789** [comment]
Ok done. Now should I do /plot regenallroads PlotsNew ?

**Comment by boy0001** [comment]
You'll need to set a schematic if you want to use the regenallroads.

**Comment by VinexAx789** [comment]
Ok and it should be the default one right?

**Comment by boy0001** [comment]
Yes

**Comment by VinexAx789** [comment]
Ok it keeps saying this
03.04 23:17:47 [Server] INFO If no schematic is set, the following will not do anything
03.04 23:17:47 [Server] INFO - To set a schematic, stand in a plot and use /plot createroadschematic
03.04 23:17:47 [Server] INFO Potential chunks to update: 284672
03.04 23:17:47 [Server] INFO Estimated time: 278 seconds
03.04 23:17:47 [Server] INFO Cannot schedule mass schematic update! (Is one already in progress?)

**Comment by VinexAx789** [comment]
Nvm, I got it rolling every time I tried doing this it hasn't worked so hopefully it does.
