### ISSUE TITLE
Doesn't let me come out of my plot

### ISSUE THREAD

**Issue by astrophylite** [IntellectualSites/PlotSquared#1043]
**Description of the problem:** I try to walk out onto the road but it teleports me to inside the plot.

**How to replicate**: Delete all configuration files and create a new plot world and try to walk on to the road.

Make sure you've completed the following steps (put an X between of brackets):
- [] Include `/plot debugpaste` - "That is not a valid subcommand, did you mean: /plot paste"
- [x] Made sure there aren't duplicates of this report
- [x] Made sure you're using an updated version of PlotSquared (does 1.7.10 count?)
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by manuelgu** [comment]
Cannot replicate. Which version of PlotSquared are you using? Any errors in console?

**Comment by astrophylite** [comment]
I am using the 1.7.10 version (v.2.3.3 - upgrading it now) and no.
I will get back to you if upgrading to the latest 1.7.10 version works ;3

**Comment by astrophylite** [comment]
Yes, that fixed the issue - I didn't realize I was using such an old version.
