### ISSUE TITLE
Well someing not right here

### ISSUE THREAD

**Issue by dgibbs3196** [IntellectualSites/PlotSquared#1046]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://pastebin.com/VhYUdwPZ
**Description of the problem:**
well i do /mv create plots normal -g PlotSquared and i get "FAIL" then i restatrt the server and get this here is my setup...
**How to replicate**:
You can use my setup to do testing! https://db.tt/DmPdIqh4

HERE IS MY VIRUS SCAN TO SEE NO HARM TO YOUR COMPUTER!
https://www.virustotal.com/en/file/8755a77ffa7f770073a55c47af85b0fca7381dc2a82152f0c5a5b6d05153279b/analysis/1460153572/
Make sure you've completed the following steps (put an X between of brackets):
- [] Include `/plot debugpaste`
- [] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [] Made sure you're using an updated version of PlotSquared
- [] Made sure the bug/error isn't caused by any other plugin

**Comment by RoboMWM** [comment]
So, you also didn't check any of the stuff up there in the template. Anyways, from your log:

> [16:47:38] [Server thread/ERROR]: [Multiverse-Core] The world 'Plots' could NOT be loaded because it contains errors!
> [16:47:38] [Server thread/ERROR]: [Multiverse-Core] Try using Chukster to repair your world! 'Plots'

Sounds like your world is corrupt perhaps?

You also should probably update spigot to 1.9.2

**Comment by MattBDev** [comment]
You are 200 Spigot versions behind the latest patch and are running an outdated Multiverse. Of course there is going to be issues!

**Comment by dgibbs3196** [comment]
I just got that Multiverse from spigot and I just build that spigot build 4 days ago

**Comment by EvilOlaf** [comment]
This is way outdated. Grab a new MV build here: http://ci.onarandombox.com/job/Multiverse-Core/

**Comment by dgibbs3196** [comment]
Thanks I did not know of that place to download Multiverse and Ill build a new spigot build..
