### ISSUE TITLE
Can't pass ChunkLoad and ChunkUnload events to PlotSquared

### ISSUE THREAD

**Issue by MCAlagaesia** [IntellectualSites/PlotSquared#1048]
"/plot debugpaste" can be found at [http://hastebin.com/inuraqifep](http://hastebin.com/inuraqifep)

**Issue:**
Bit of a strange issue that happened out of the blue. The server is crashing on join (of any player). It happens within the first few seconds.

It seems to be related to: **10.04 07:02:39 [Server] ERROR Could not pass event ChunkLoadEvent to PlotSquared v3.3.3**

The issue first occured in PlotSquared 3.3.1, we updated to see if there would be any change. We have also updated to the latest Spigot and Plot2Dynmap.

I can get you any additional information if requested.

Crash: [http://pastebin.com/yfRng4tK](http://pastebin.com/yfRng4tK)
Full Startup and Crash Log: [http://pastebin.com/MeFHgYzz](http://pastebin.com/MeFHgYzz)

**How to replicate**: Unknown, we'll keep looking into it though.

**Comment by boy0001** [comment]
You have corrupt chunks, PlotSquared just happens to be the first plugin to try to do anything with the chunk. If you disable the PlotSquared chunk processor it will probably delay crashing until you try to build etc in the chunk.

I haven't had much experience fixing corrupt chunks before, so here's this:
https://www.spigotmc.org/wiki/using-the-minecraft-region-fixer/
