### ISSUE TITLE
Plot size changing during reload not honored on server restart

### ISSUE THREAD

**Issue by paul-palmer** [IntellectualSites/PlotSquared#1049]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**: The logs show "HTTP response code: 503 for URL: http://hastebin.com/documents"

**Description of the problem:**
When I created my server I set the plot size to 90 blocks. At some point, the plot size changed to 128 blocks. We can change settings.yml to set the plot size back to 90 and perform a /plots reload and the size change is honored. However, if we restart the server, the size reverts back to 128 blocks in settings.yml.

**How to replicate**:

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
Logs show that the command was accepted, but it produced no output. 
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by boy0001** [comment]
Check your multiverse configuration, it's creating the world with the wrong configuration.

**Comment by paul-palmer** [comment]
Thank you for the feedback.

We don't use multiverse, but your feedback pointed us in the correct direction. Our world configuration was in bukkit.yml, where the size was indeed set to 128 (nobody recalls when this happened, but it had to have been a change on our part).
