### ISSUE TITLE
`use` flag not respecting pressure plates

### ISSUE THREAD

**Issue by manuelgu** [IntellectualSites/PlotSquared#1050]
# Bug report
**Debug paste link**: http://hastebin.com/iyifativoz

**Description of the problem:**
The `use` flag does not properly respect pressure plates. You are able to activate both types, regardless of what is set to be usable in the `use` flag. It works fine for other tested materials, buttons in my case.

**How to replicate**:
- Set flag `use:70`
- Place down two pressure plates (wooden, stone)
- Get another player (not added nor owner) and see that you can activate both types of pressure plates

[![](http://img.youtube.com/vi/htRm44TeDHY/0.jpg)](http://www.youtube.com/watch?v=htRm44TeDHY)

Make sure you've completed the following steps (put an X between of brackets):
- [X] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [X] Made sure you're using an updated version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by EvilOlaf** [comment]
Confirmed. Looking forward for a release.
