### ISSUE TITLE
Remove armor from armor stands in other plots

### ISSUE THREAD

**Issue by CullanP** [IntellectualSites/PlotSquared#1051]
Description of the problem: We had an issue where players could steal armor off of armor stands on other plots and then I checked the github and didn't see the event "PlayerArmorStandManipulateEvent"

How to replicate**: Right click armor stands with armor on them in other plots that you don't own

**Comment by manuelgu** [comment]
Cannot reproduce.
Try latest stable dev build:
http://ci.xephi.fr/job/PlotSquared/115/
