### ISSUE TITLE
Feature Request: Individual Permission For /plot debugroadregen

### ISSUE THREAD

**Issue by wilsondc15** [IntellectualSites/PlotSquared#1054]
It would really help out a lot if there were an individual permission for /plot debugroadregen because I do not want my Mods to have Admin permissions, I just want them to be able to use that command when I, the owner, am not online.

When I run the PermissionsEx permission debug while running that command, it only checks for "*" the OP permission.

**Comment by MattBDev** [comment]
The permission is "plots.debugroadregen"
