### ISSUE TITLE
"/plot setup" issue

### ISSUE THREAD

**Issue by CatMe0w** [IntellectualSites/PlotSquared#1055]
**Debug paste link**:
http://hastebin.com/agahadegas

**Description of the problem:**
/plot setup cannot work normally
http://pastebin.com/9hqWCzj9

**How to replicate**:
Use /plot setup command and set the plot height. Enter "/p setup 64", PlotSquared will start generate a new world named "64".

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [X] Made sure you're using an updated version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment]
@CatMe0w You are two versions behind. The current version is 3.3.3

**Comment by CatMe0w** [comment]
Oh no I was wrong, PlotSquared didn't inform me to update plugin. This issue is no longer exist in 3.3.3 now. Sorry.
