### ISSUE TITLE
Lava and water left on the road when generating augmented world

### ISSUE THREAD

**Issue by jessefjxm** [IntellectualSites/PlotSquared#1057]
Spigot version: 1.8.7
PlotSquared version: 3.3.3

When generating an augmented road type world, everthing's work well except lava and water will float in the air, if they used to be storaged in stones. This problem will occured every time I generated this type of world.

I used following commands in game:
plot setup
plot setup PlotSquared
plot setup AUGMENTED
plot setup ROAD
plot setup 64
plot setup 100
plot setup 1
plot setup 2
plot setup 44
plot setup 44:1
plot setup 19
plot setup 64
plot setup 173
plot setup 1
plot setup 64
plot setup true
plot setup Exam_nature

**Comment by dordsor21** [comment]
is this still an issue?

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
