### ISSUE TITLE
Player can't buy plots buy but lose their money

### ISSUE THREAD

**Issue by Vinc0682** [IntellectualSites/PlotSquared#1058]
**Debug paste link**:
http://hastebin.com/cuvegitoge

**Description of the problem:**
When someone tries to buy a plot, their money get's withdrawed, but
they got no plot :disappointed: 

**How to replicate**:
See above

**Comment by manuelgu** [comment]
Please update PlotSquared to the [latest version](https://github.com/IntellectualSites/PlotSquared/releases/tag/v3.3.3) and create the `/plot debugpaste` immediately after someone tried to buy plot.

**Comment by Vinc0682** [comment]
Thanks, it seems to be working now, the misterious thing is that i ran /ps update which told me that no updates are available.

**Comment by MattBDev** [comment]
@Vinc0682 The updater broke between 3.3.0 and 3.3.2 due to a formatting error in the code. It is always best to check on the plugins webpage every so often.
