### ISSUE TITLE
Creepers Exploding On Plots Outside

### ISSUE THREAD

**Issue by QUIQUELHAPPY** [IntellectualSites/PlotSquared#1060]
When somebody walk into another plot where there are creepers, the user that came into the plot, can explode them.

This completly brakes the protection of the plot!
Creepers also explode on a plot if you're the owner.

It's possible to block other players from exploding creepers on plots outside?

-Sorry for my english, I'm spanish.

**Comment by MattBDev** [comment]
you can use the explosion flag and set it to false.
