### ISSUE TITLE
servers with plotsquared drops tps

### ISSUE THREAD

**Issue by JugadorNinja** [IntellectualSites/PlotSquared#1061]
https://timings.spigotmc.org/?url=15904466

**Comment by boy0001** [comment]
You have too many tile entities. Several things you could do:
 - switch to paperspigot and optimize your server configuration
 - set stricter blockstate limits for the PlotSquared chunk processor

here's an alright guide:
https://www.spigotmc.org/threads/guide-optimizing-spigot-remove-lag-fix-tps-improve-performance.21726/
download paperspigot:
https://tcpr.ca/downloads/paperspigot

**Comment by JugadorNinja** [comment]
thanks!
