### ISSUE TITLE
Plugin 'Plotsquared' does not exist

### ISSUE THREAD

**Issue by bambusbo** [IntellectualSites/PlotSquared#1065]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/ukipobirac plot debug
http://hastebin.com/xologeroxu server log
**Description of the problem:**
When i start my server or attempt to set the generator for my plotworld, it gives me this error, and none of the plots has protection, /plot info outputs: you are not in a plot
[15:45:41 INFO]: Could not set generator for world 'Plots': Plugin 'Plotsquared' does not exist
I use multiverse and the latest version of plotsquared, everything had been working fine, just until i restarted my server.

**How to replicate**:
It gives me the error everytime i restart the server, rendering the plotworld useless

**Comment by boy0001** [comment]
The plugin's name is `PlotSquared` not `Plotsquared` (case sensitive)
