### ISSUE TITLE
Plots are not in creative!

### ISSUE THREAD

**Issue by lucatunes** [IntellectualSites/PlotSquared#1066]
Hi can someone help me! I don't have multiverse and my plots are not in creative! Everything else works fine! Please help!

**Comment by manuelgu** [comment]
Please provide a `/plot debugpaste`

**Comment by lucatunes** [comment]
# Welcome to this paste
# It is meant to provide us at IntellectualSites with better information about your problem

# We will start with some informational files
links.settings_yml: 'http://hastebin.com/gogevorava'
links.latest_log: 'http://hastebin.com/efoturiray'

# YAAAS! Now let us move on to the server info
version.server: '[1, 8, 8]'
online_mode: com.plotsquared.bukkit.uuid.DefaultUUIDWrapper@53731304;true
plugins:
  CoreProtect:
    version: '2.12.0'
    enabled: true
  CrashRestarter:
    version: '3.1'
    enabled: true
  WorldEdit:
    version: 'unknown'
    enabled: true
  TimTheEnchanter:
    version: '3.0'
    enabled: true
  Essentials:
    version: 'TeamCity'
    enabled: true
  GroupManager:
    version: 'Pre2.14.1.3 FINAL (Phoenix)'
    enabled: true
  ClearLag:
    version: '2.9.0'
    enabled: true
  AutoBroadcaster:
    version: '0.4'
    enabled: true
  ForcedGrammar:
    version: '1.8.4'
    enabled: true
  HolographicDisplays:
    version: '2.1.12'
    enabled: true
  ActionHealth:
    version: '2.5'
    enabled: true
  Votifier:
    version: '1.9'
    enabled: true
  WorldGuard:
    version: '6.1'
    enabled: true
  CClearChat:
    version: '1.9'
    enabled: true
  NoCheatPlus:
    version: '3.13.7-RC-sMD5NET-b925'
    enabled: true
  MasterVanish:
    version: '1.0'
    enabled: true
  EssentialsKitManager:
    version: '1.0.4'
    enabled: true
  EasyItemRename:
    version: '1.1.4'
    enabled: true
  iDisguise:
    version: '5.1.2'
    enabled: true
  FakeJoin:
    version: '1.0'
    enabled: true
  ObsidianBreaker:
    version: '2.1'
    enabled: true
  EssentialsChat:
    version: 'TeamCity'
    enabled: true
  mcMMO:
    version: '1.5.05-SNAPSHOT-b134'
    enabled: false
  CustomCrates:
    version: '1.7.10'
    enabled: true
  JoinMessage:
    version: '1.0'
    enabled: true
  StaffChat:
    version: '1.0'
    enabled: true
  Tablist:
    version: '1.3.0.2'
    enabled: true
  AntiSignHack:
    version: '1.1'
    enabled: true
  GAListener:
    version: '1.3.2'
    enabled: true
  Vault:
    version: '1.5.6-b49'
    enabled: true
  EssentialsSpawn:
    version: 'TeamCity'
    enabled: true
  Rollback-Explosion:
    version: '1'
    enabled: true
  ChatColor:
    version: '2.1'
    enabled: true
  MassiveCore:
    version: '2.8.7Beta'
    enabled: true
  EnjinMinecraftPlugin:
    version: '2.7.7'
    enabled: true
  HolographicScoreboard:
    version: '1.4.1'
    enabled: true
  ItemHover:
    version: '1.7'
    enabled: true
  EnderPearlCoolDown:
    version: '1.5.0'
    enabled: true
  Unscramble:
    version: '4.0'
    enabled: true
  PlotSquared:
    version: '3.3.0'
    enabled: true
  WarpPortals:
    version: '5.6.3'
    enabled: true
  AuctionHouse:
    version: '1.0'
    enabled: true
  Factions:
    version: '1.8.2'
    enabled: true
  RandomTeleport:
    version: '5.0.2'
    enabled: true
  CS-CoreLib:
    version: '1.5.3'
    enabled: true
  CombatLog:
    version: '1.8.11-hack'
    enabled: true
  FactionChat:
    version: '1.9.15'
    enabled: true
  SilkSpawners:
    version: '3.7.1'
    enabled: true

# YAY! Now, let's see what we can find in your JVM
memory.free: 163653560
memory.max: 988282880
java.specification.version: '1.8'
java.vendor: 'Oracle Corporation'
java.version: '1.8.0_72'
os.arch: 'amd64'
os.name: 'Linux'
os.version: '3.14.32-xxxx-grs-ipv6-64'

# Okay :D Great. You are now ready to create your bug report!
# You can do so at https://github.com/IntellectualSites/PlotSquared/issues

**Comment by manuelgu** [comment]
You can just post the hastebin link that you have in your chat ;)

You also have a world called `<world>` which may cause issues.
Which world is the one you are not getting set to creative mode? Can you confirm that it is detected as a plotworld? (Run /plot claim on a plot or something)

**Comment by lucatunes** [comment]
Yes it works
Do I need to type a command or something? Other players have used it but they are using them as survival plots

**Comment by lucatunes** [comment]
but I need them creative

**Comment by lucatunes** [comment]
If youd like to come on my server and experiment I can op you and give you console

**Comment by manuelgu** [comment]
> If youd like to come on my server and experiment I can op you and give you console

You better don't do that to random players on the internet, ever, at all.

What is the world you are having the issue in called?

**Comment by MattBDev** [comment]
You're using an outdated version of plotsquared

**Comment by lucatunes** [comment]
really?

**Comment by lucatunes** [comment]
whats the link for the new one

**Comment by EvilOlaf** [comment]
https://www.spigotmc.org/resources/plotsquared.1177/

**Comment by lucatunes** [comment]
thank you :D does the world delete when you un install the plugin

**Comment by manuelgu** [comment]
No. You have to delete the world folder from your root directory and also the part in the PlotSquared settings.yml

**Comment by lucatunes** [comment]
cool thanks
