### ISSUE TITLE
PlotSquared is not loading plots' ratings

### ISSUE THREAD

**Issue by diecode** [IntellectualSites/PlotSquared#1067]
I am using the latest PlotSquared ( Updated from an older version ) and the plugin is not loading the plots' ratings.

I am using Spigot 1.9.2 and MySQL

**Comment by MattBDev** [comment]
Please follow the issue template. You provided very little to no details to help solve this issue. Please reply with a '/plots debugpaste' link.

**Comment by diecode** [comment]
Sorry for this. The link: http://hastebin.com/exirulolig

**Comment by diecode** [comment]
I am debugging this, because the ratings is very important to me.

Atm: The **hasRatings()** function in Plot Object returning false, bacause **base.settings.ratings == null**

**Comment by MattBDev** [comment]
If you can make a fix and submit a PR I will review and merge it. I just don't have time at the moment to fix it myself.

**Comment by diecode** [comment]
When I change the `public HashMap<UUID, Integer> ratings;` in the **PlotSettings** class to `public HashMap<UUID, Integer> ratings = new HashMap<>();`then the problem solved.

**Comment by manuelgu** [comment]
> If you can make a fix and submit a PR I will review and merge it

**Comment by diecode** [comment]
#1095
