### ISSUE TITLE
Feature Request - Block Interactions

### ISSUE THREAD

**Issue by wilsondc15** [IntellectualSites/PlotSquared#1072]
A way for permissions to add per block interactions on plots. Like how plots.admin.interact.other
 works but for specific blocks like plots.admin.interact.other.7

**Comment by boy0001** [comment]
There's the flag system for that.

You can set default flags in the settings.yml:
https://github.com/IntellectualSites/PlotSquared/wiki/Usage:-Plot-flags#default-flags

**Comment by wilsondc15** [comment]
I know there is, but I do not want every player to have the same block permissions. How can I do that?
