### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by Suhhh** [IntellectualSites/PlotSquared#1073]
[Picture of what I want](http://i.imgur.com/foOKlKg.png?1)
Notice how there's the same tree on every plot, like it replicates the same blocks. How do you do that? Like I know how to change the block type for each layer, but I would like to know how to replicate terrain on every plot.

**Comment by manuelgu** [comment]
https://github.com/IntellectualSites/PlotSquared/wiki/Usage:-Schematic-on-claim

**Comment by Suhhh** [comment]
I think you misunderstood me. I meant like every plot, and not having to claim each plot individually and paste it. I would like it to be generated on each plot, could you walk me through it?

**Comment by boy0001** [comment]
https://github.com/IntellectualSites/PlotSquared/wiki/Installation#optional-generate-a-world-with-a-schematic-already-in-the-plot
