### ISSUE TITLE
How to use /plot chat? (not a bug)

### ISSUE THREAD

**Issue by OrlandoLaCrue** [IntellectualSites/PlotSquared#1075]
I want to know how to use the /plot chat, when I do /plot chat all it says is "plot chat on" I see no change in username or plugin. I have searched around the web and found nothing. Anyway thanks!

**Comment by MattBDev** [comment]
Plot chat allows you to have a chat that is only visible to people in your plot. If you turn it back off then any message you send will be sent in the global chat.
