### ISSUE TITLE
Player Crash on /p claim

### ISSUE THREAD

**Issue by AidanFogarty** [IntellectualSites/PlotSquared#1077]
**Description of the problem:**
The plugin seems to set up perfectly fine, I can load up a world with all the correct configs. However, when a user does /p claim, this causes the user to be kicked from the server. When the user tries to log back in it instantly kicks them off again. The only way they can log back onto the server is if I delete the playerdata but this still doesnt fix the plot claim problem. Any help would be appreciated, thanks!!!
Server Version: 1.9

**Comment by manuelgu** [comment]
Please attach a `/plot debugpaste`

**Comment by MattBDev** [comment]
@AidanFogarty If you do not provide a `/plot debugpaste` within 24 hours, this issue will be closed for not properly reporting the issue.

**Comment by QUIQUELHAPPY** [comment]
is your natural mob spawn enabled? This may be the case, on some spigot versions entity interact generate client crashes. Please, update your spigot or provide more info
