### ISSUE TITLE
Question: Add ability to have /plot unclaim command, but make toggleable in config?

### ISSUE THREAD

**Issue by VoxaDub** [IntellectualSites/PlotSquared#1078]
Is it possible that the /plot unclaim command could be added as an alias or just a toggle in the config, but set to disabled by default? Or just be an alias for /plot setowner none with a set permission? Since I cant just give someone the permission to do "/plot setowner none"

**Comment by JackDn** [comment]
Please stop creating new issues about this.

**Comment by VoxaDub** [comment]
No, I can create a suggestion. No reason I shouldnt be able to.

**Comment by JackDn** [comment]
You can't create 3 issues about the same suggestion which has already been denied.

**Comment by VoxaDub** [comment]
I created one issue?

**Comment by VoxaDub** [comment]
This is an entirely different suggestion.

**Comment by JackDn** [comment]
#1059

**Comment by VoxaDub** [comment]
Thats one, learn to count. And its not the same issue, learn to read as well.

**Comment by MattBDev** [comment]
Duplicate of #1059
