### ISSUE TITLE
plot home needs plots.visit since update from 3.2.26

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualSites/PlotSquared#1079]
I updated from 3.2.26 to 3.3.3 yesterday and since then `plot home ` or `p h` in short does not work for my players anymore as they are `lacking of permission node plots.visit`.
The permission system or the permissions itself have not been changed so I assume this is an issue with P^2 since >3.2.26.

**Comment by boy0001** [comment]
The home command was removed, use visit instead. It has home as an alias so the command syntax will be the same.

**Comment by EvilOlaf** [comment]
Hm I do not really understand why this happened, because visit would allow player to teleport themselves to other plots rather than their own as well (?)....guess I missed the discussion about that ^^

Thanks anyways.

**Comment by boy0001** [comment]
It has permissions for the type of plot you can visit. Only real difference is supports a lot more syntax than just home.
plots.visit.unowned
plots.home or plots.visit.owned
plots.visit.shared
plots.visit.other

**Comment by EvilOlaf** [comment]
I see. Yeah that's pretty cool. Also that you left an alias for `plots.home` permission to fit when `plots.visit` is added to make `plot home` work again.

Thanks again.
