### ISSUE TITLE
Glitchy merging

### ISSUE THREAD

**Issue by Blue-Guy** [IntellectualSites/PlotSquared#1082]
# Bug report template (Follow this template unless you are making a feature request.)

**Debug paste link**:
http://hastebin.com/umakaquvuq

**Description of the problem:**
On merge, roads are "glitchy", and leaves seem "leak" outside the plot

**How to replicate**:
1. Create augmented plot world
2. Merge four plots to create megaplot

![image](https://cloud.githubusercontent.com/assets/16492168/14901722/e866408a-0d64-11e6-9b8a-d609976731ca.png)

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by CullanP** [comment]
To add on to this bug report, trees also break when you merge plots. You can't grow trees on the plot you merged with.

**Comment by dordsor21** [comment]
likely fixed.
