### ISSUE TITLE
Database Switch Question

### ISSUE THREAD

**Issue by itismejoey** [IntellectualSites/PlotSquared#1083]
Not really a bug per se, just asking a question that got passed over on Spigot. Any help would be appreciated!

> Hello! Love the plugin (and so do my players)! 

> I wanted to move my data from the sqlite database to a mysql database. Is this something that you can just set to true and it will transfer over or are there steps I should take?

**Comment by MattBDev** [comment]
https://github.com/IntellectualSites/PlotSquared/wiki/Commands#database
