### ISSUE TITLE
Trees do not grow with bonemeal in merged plots

### ISSUE THREAD

**Issue by alchemistmatt** [IntellectualSites/PlotSquared#1085]
There is no debug information shown at console

**Debugpaste Link**
http://hastebin.com/tolizateru

**Description of the problem**

As previously reported in #1021 after merging two (or more) plots together, we cannot grow trees using bonemeal.  The previous issue was closed with tag Cannot Replicate, partially because the OP had not performed a test with other plugins removed.  I have removed every single plugin except for PlotSquared and I can still replicate the issue.

We're running Spigot 1.9.2, built from commit [5a403651d2b] (https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/commits/5a403651d2b6da681d7aba14e3b1df8171fc5249) along with BungeeCord built from commit [b6b015f] (https://github.com/SpigotMC/BungeeCord/commit/b6b015fe1f5b4ed62bb0f09c03cafda3efe82ac0). And we're using PlotSquared 3.3.3, and Java 1.8.0_66.

**How to replicate**

On a single, unmerged plot that you own, enter creative mode, then place a sapling.  Now right click with bone meal and after several clicks a tree will grow.  Next, merge the plot using either `/plot merge auto` or `/plot merge <direction>`.  Place a new sapling and again try to grow with bone meal.  You'll find that it will only grow in one of the original two merged plots.  Merge together more plots and, again, the sapling will only grow in one of the original plot areas.  Unmerge the plots, and now saplings can be grown into trees in any of the plots.

**Checklist**
- [x] Include `/plot debugpaste`: above
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [x] Made sure you're using an updated version of PlotSquared: v3.3.3
- [x] Made sure the bug/error isn't caused by any other plugin: Unloaded all other plugins

**Comment by CullanP** [comment]
Confirmed on our server as well.

**Comment by ES-Vodoo** [comment]
I have the same but if I merge 4 plots (2x2), I can use bonemeal on the 1 plot area (on 3 others not work).

**Comment by manuelgu** [comment]
Confirmed also for Mushroom -> Huge Mushroom.
