### ISSUE TITLE
Server crashes

### ISSUE THREAD

**Issue by Goldentoenail** [IntellectualSites/PlotSquared#1086]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
None, not sure on how to make one. I have included the server crash log.
**Description of the problem:**
Occasionally when a player clears a plot the server crashes
**How to replicate**:
Not sure.
Make sure you've completed the following steps (put an X between of brackets):
- [] Include `/plot debugpaste`
- [] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

Although the latest update says that this can often happen when Light-Sensors were in a plot.
My crash log appears to suggest there is another cause. Such as block generation properties.
[crash-2016-04-30_08.53.28-server.txt](https://github.com/IntellectualSites/PlotSquared/files/244109/crash-2016-04-30_08.53.28-server.txt)

**Comment by EvilOlaf** [comment]
Simple enter `/plot debugpaste` and then copy the output link here ;)

**Comment by boy0001** [comment]
Update spigot, you're running a bugged version. Using WorldEdit to `//regen` the plot would have also resulted in a crash.

**Comment by Goldentoenail** [comment]
Thanks, I have just updated spigot to the very latest build and hope that does solve the problem.

I have noticed that there are lot of lighting glitches on many of the plots from the world generator.
This was a totally new generated world when 1.9 came out. 

I was thinking about using FAWE to fix some of them.
