### ISSUE TITLE
Question: Use lighter in plots

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualSites/PlotSquared#1089]
Since updating from 3.2.26 to 3.3.3 a lighter can no longer be used to put fire on a block.
No console or ingame output when trying to ignite something.

How to reenable this?

**Comment by boy0001** [comment]
block-ignition flag

**Comment by EvilOlaf** [comment]
Thank you.

**Comment by EvilOlaf** [comment]
When setting `block-ignition` to true will everyone be allowed to ignite a block on every plot?
It would be useful if the plot owner or added/trusted can use this only.
