### ISSUE TITLE
World export to a new server

### ISSUE THREAD

**Issue by maxlehot1234** [IntellectualSites/PlotSquared#1090]
I have nothing about this, but if someone can explain to me how I can export plots from a world to put it on another server I have it could be very nice :)

I export the plots world and plotsquared folder with sqlite  .db but all plots have unknown owner...

**Comment by maxlehot1234** [comment]
Any help please?

**Comment by MattBDev** [comment]
GitHub is not a place to expect immediate help. If you need immediate help you should use our IRC channel.
This issue is the same problem that causes #781
