### ISSUE TITLE
WorldEdit can bypass Plot restrictions.

### ISSUE THREAD

**Issue by cervinakuy** [IntellectualSites/PlotSquared#1091]
Here is the link to the Debug paste:
http://hastebin.com/behitoxexe

Description of the problem:

Hello,

So recently, I received a message from a player on my server saying another player was hacking. Thinking to myself that we have hack protection, and overall our server is hack-free, I logged onto the server expecting the worst. When I arrived, a Donor hadn't used any clients, but found a loophole in the PlotSquared system. Upon using the WorldEdit command //copy, and copying a region of wood, and using the //paste command, the player was able to move a few blocks forward, type //paste again, and repeat the cycle. When the player reached the end of the plot, and typing the command //paste once more, you can see in this screenshot the selected region bypasses the Plot restriction area, and onto the road.

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [X] Made sure you're using an updated version of PlotSquared
Ignore the version that it says on the hastebin, that was created before I updated. Even though I updated, the issue persisted.

- [X] Made sure the bug/error isn't caused by any other plugin | Well, it's being caused by WorldEdit, but this is similar to the issue I hope and can be solved.

**Comment by manuelgu** [comment]
Try updating your PlotSquared.

Latest stable dev build:
http://ci.xephi.fr/job/PlotSquared/115/changes
Releases:
https://github.com/IntellectualSites/PlotSquared/releases

**Comment by boy0001** [comment]
Assuming fixed.
