### ISSUE TITLE
Players Can Open Other Players Chests

### ISSUE THREAD

**Issue by QUIQUELHAPPY** [IntellectualSites/PlotSquared#1092]
Players Can Open Other Players Chests!
I don't know if it has something in common with this: https://github.com/IntellectualSites/PlotSquared/issues/1081

Is there any way to fix this for the moment?

**Comment by MattBDev** [comment]
Make sure you are using version 3.3.3 and this shouldn't be a problem. Reply back and I will reopen this if it is still an issue.
