### ISSUE TITLE
Task #161000 Exception - Plot road schematic fails

### ISSUE THREAD

**Issue by DragonbornCommunity** [IntellectualSites/PlotSquared#1093]
Staktrace Pastebin: http://pastebin.com/R6sLbcj1

When performing /plot createroadschematic, this error comes up in console and then if /plot debugroadregen is performed, the road will not be generated.

I built all around the plot before performing both commands.

DebugPaste: http://hastebin.com/xavunimacu

I do not think that another plugin is interfering with PlotSquared.

**Comment by manuelgu** [comment]
What is the content of your `plugins/PlotSquared/schematics/`?
Are you sure that the error comes up when doing `/plot createroadschematic` ?



****

FFR: It tries to access the `GEN_ROAD_SCHEMATIC/worldname/plot.schematic` [here](https://github.com/IntellectualSites/PlotSquared/blob/master/Core/src/main/java/com/intellectualcrafters/plot/generator/HybridPlotWorld.java#L180)
