### ISSUE TITLE
Does not load schematic on claiming

### ISSUE THREAD

**Issue by wasder** [IntellectualSites/PlotSquared#1094]
**http://pastebin.com/x6y7up90**

**How to replicate**:
`plot auto` or `plot claim` causes the error.

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste` http://hastebin.com/yavedoridi
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [x] Made sure you're using an updated version of PlotSquared - [Latest build](http://ci.athion.net/job/PlotSquared/130/)
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by manuelgu** [comment]
PlotSquared failed to create the schematic in `/var/www/schematics`.
Make sure the user that your Minecraft Server is running under has write permissions for this directory

**Comment by boy0001** [comment]
Change the schematic directory to "schematics", unless you specifically need it set to somewhere else.
