### ISSUE TITLE
item-drop issue #1: Inverted boolean values

### ISSUE THREAD

**Issue by zombachu** [IntellectualSites/PlotSquared#1101]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/adesowiciv

**Description of the problem:**
When item-drop is set to false it allows items, and when it's set to true it prevents them.

**How to replicate**:
Do /p flag set item-drop true. It should prevent you from dropping items. Having an unset flag or it being set to false will allow you to drop items.

Make sure you've completed the following steps (put an X between of brackets):
- [X] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [X] Made sure you're using an updated version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment]
Should be fixed in the new flag implementation.
