### ISSUE TITLE
item-drop issue #2: Inverted check for added players

### ISSUE THREAD

**Issue by zombachu** [IntellectualSites/PlotSquared#1102]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/adesowiciv

**Description of the problem:**
Players who are added to a plot when drops are turned off (See #1101 for the bug on that) will be prevented from dropping items, while those that are not added will be allowed to drop items.

**How to replicate**:
Go to your own plot and do /p flag set item-drop true (See #1101), then you should not be able to drop items on your own plot. Do the same to a plot that you are not added to/own, and you should be able to drop items there.

Make sure you've completed the following steps (put an X between of brackets):
- [X] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [X] Made sure you're using an updated version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment]
Would the intended behavior be to prevent everyone from dropping items when it is set to false?

**Comment by zombachu** [comment]
Up to you whether to let added players bypass the flag or not, but right now it *only* affects people who are added (having no effect on not-added, probably the intended target, players)

**Comment by MattBDev** [comment]
It should probably affect everyone.
