### ISSUE TITLE
item-drop issue #3: Admin bypassing does not work

### ISSUE THREAD

**Issue by zombachu** [IntellectualSites/PlotSquared#1103]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/adesowiciv

**Description of the problem:**
Even if you have admin bypass permissions, you will still be prevented from dropping items on a plot with the flag set (See #1101 for a bug on that)

**How to replicate**:
Give yourself the "admin interact other" permission then try to drop items on a plot where it is disabled.

Make sure you've completed the following steps (put an X between of brackets):
- [X] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [X] Made sure you're using an updated version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

All three ( #1101, #1102, and this ) of these issues are caused by [this](https://github.com/IntellectualSites/PlotSquared/blob/1bce69d28865711dbb9645275b96535b16dd4754/Bukkit/src/main/java/com/plotsquared/bukkit/listeners/PlotPlusListener.java#L134) if statement, I believe.

**Comment by MattBDev** [comment]
This permission does not apply to this flag.
