### ISSUE TITLE
Add option to load uuid from Bukkit (using DefaultUUIDWrapper)

### ISSUE THREAD

**Issue by lucasdidur** [IntellectualSites/PlotSquared#1104]
On my server, I created a plugin that allows original player has his own uuid, using the forwardIP of bungeecord.

I would ask to add an option to not use UUIDWrapper options, but the standard DefaultUUIDWrapper, which is not possible to activate at plugin configuration.

**Comment by MattBDev** [comment]
@lucasdidur just changing the setting to allow online uuid's for plotsquared should do this already?

**Comment by lucasdidur** [comment]
But in this mode, the plugin does not get the uuid using the mojang API? I need to use the player.getUniqueId() method of bukkit.

**Comment by MattBDev** [comment]
The DefaultUUIDWrapper (for the Bukkit Module) uses the Bukkit API to handle UUID stuff. Bungeecord by default has its own way of forwading IP's and UUID's by default. PlotSquared should have no issue with it and no extra steps. If you want to override the UUIDWrapper implementation, you can do so by setting the implementation variable to a different object.
Having OfflineMode in the settings.yml file set to instantiates loads the DefaultUUIDWrapper

**Comment by lucasdidur** [comment]
But I was analyzing the code, and DefaultUUIDWrapper option is only used in versions 1.7.6 and earlier.

https://github.com/IntellectualSites/PlotSquared/blob/master/Bukkit/src/main/java/com/plotsquared/bukkit/BukkitMain.java#L504

**Comment by boy0001** [comment]
No, it's used 1.7.6 and above.

**Comment by lucasdidur** [comment]
That's odd, because had tried and had not worked. I had to create a module to force the use of it to work.

I will test again.
