### ISSUE TITLE
Spigot NMS support for 1_9_R2

### ISSUE THREAD

**Issue by MattBDev** [IntellectualSites/PlotSquared#1105]
I haven't tested anything but I would have to guess the plugin's NMS code doesn't work for 1.9.4 . It would be appreciated if someone could confirm if everything works fine or if there is a reflection error.

**Comment by AshourAziz** [comment]
http://pastebin.com/1Xm1M7fa

**Comment by frizzbee30** [comment]
yup, it's not happy  :)

**Comment by MattBDev** [comment]
Fixed in 3.3.4 branch.
