### ISSUE TITLE
Banner and flower pod bypassing place permissions

### ISSUE THREAD

**Issue by ES-Vodoo** [IntellectualSites/PlotSquared#1109]
**Debug paste link**:
http://hastebin.com/holegatixu

**Description of the problem:**
Banner and flower pod can be placed on someone's plot (without permission to plot).

**How to replicate**:
Remove all privileges (op, permissions etc.) and try to place banner/flower pod on the someone's plot.

Make sure you've completed the following steps (put an X between of brackets):
- [] Include `/plot debugpaste`
- [] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [] Made sure you're using an updated version of PlotSquared
- [] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment]
I can't replicate this issue. Since you are using the dev builds, make sure you stay up to date with them.
