### ISSUE TITLE
NPE /Plots Unmerge North

### ISSUE THREAD

**Issue by Pangamma** [IntellectualSites/PlotSquared#1111]
**Debug paste link**:
http://hastebin.com/suqaxonuyu

https://github.com/IntellectualSites/PlotSquared/blob/master/Core/src/main/java/com/intellectualcrafters/plot/commands/Unlink.java#L46

**Description of the problem:**
Null pointer exception when you do /plot unmerge north
**How to replicate**:
Null pointer exception when you do /plot unmerge north

13.05 19:07:31 [Server] INFO [19:07:31 INFO]: [Slog] Pierates /plot unlink
13.05 19:07:26 [Server] INFO ... 15 more
13.05 19:07:26 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
13.05 19:07:26 [Server] INFO at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:27) ~[?:?]
13.05 19:07:26 [Server] INFO at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:140) ~[?:?]
13.05 19:07:26 [Server] INFO at com.intellectualcrafters.plot.commands.MainCommand.execute(MainCommand.java:207) ~[?:?]
13.05 19:07:26 [Server] INFO at com.plotsquared.general.commands.Command.execute(Command.java:332) ~[?:?]
13.05 19:07:26 [Server] INFO at com.intellectualcrafters.plot.commands.SubCommand.execute(SubCommand.java:27) ~[?:?]
13.05 19:07:26 [Server] INFO at com.intellectualcrafters.plot.commands.Unlink.onCommand(Unlink.java:46) ~[?:?]
13.05 19:07:26 [Server] INFO Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
13.05 19:07:26 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
13.05 19:07:26 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
13.05 19:07:26 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
13.05 19:07:26 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
13.05 19:07:26 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
13.05 19:07:26 [Server] INFO at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
13.05 19:07:26 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
13.05 19:07:26 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
13.05 19:07:26 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
13.05 19:07:26 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
13.05 19:07:26 [Server] INFO at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
13.05 19:07:26 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
13.05 19:07:26 [Server] INFO at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) [spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
13.05 19:07:26 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
13.05 19:07:26 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
13.05 19:07:26 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.9.2.jar:git-Spigot-e000104-4cb3258]
13.05 19:07:26 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'plot' in plugin PlotSquared v3.3.3
13.05 19:07:26 [Server] INFO [19:07:26 ERROR]: null
13.05 19:07:26 [Server] INFO [19:07:26 INFO]: [Slog] Pangamma /plot unmerge north
13.05 19:07:17 [Server] INFO [19:07:17 INFO]: [Slog] Pangamma /plot merge north

**Comment by manuelgu** [comment]
Directional _unmerging_ is not supported. It expects a boolean whether to re-create a road or just leave it untouched.

See wiki https://github.com/IntellectualSites/PlotSquared/wiki/Commands#unlink

**Comment by MattBDev** [comment]
Also, I would like to point out that the code link you provided does not match with line 46 of 3.3.3. Learn how GitHub commits and versioning works.
