### ISSUE TITLE
Plot claim issue

### ISSUE THREAD

**Issue by RyuZockt** [IntellectualSites/PlotSquared#1113]
Problem: player cant calim plots --> [P2] You cant claim more Plots!
but the player have the permissions:
- plots.use
-plots.plot.1
-plots.permback.basic
-plots.claim
-plots.auto

Need help

**Comment by manuelgu** [comment]
> `plots.plot.1`

This limits the max plots of a player to 1´.

**Comment by RyuZockt** [comment]
But a player cant claim 1 plot! he canot claim any plots

**Comment by manuelgu** [comment]
What does `/plot list <playername>` give you?
Please provide a `/plot debugpaste` (as already requested in issue template)

**Comment by RyuZockt** [comment]
[P2] Found no plots with your search query

http://hastebin.com/ejugeyarar

**Comment by manuelgu** [comment]
Could you also hastebin your permissions file? Redact usernames if needed.

**Comment by boy0001** [comment]
In the settings.yml, change:
max_plots: -1
to (default value) 127
