### ISSUE TITLE
Players can break any block

### ISSUE THREAD

**Issue by EmpireEddy** [IntellectualSites/PlotSquared#1114]
Players of any rank/group can break any block including roads, unclaimed plots and plots claimed by other players.

**How to replicate**:
Any player can break any block period.

P.S. We switched from plotme to plotsquared

**Comment by manuelgu** [comment]
Sounds like your permissions aren't setup correctly.

Please provide a `/plot debugpaste` and your permissions file.

**Comment by EmpireEddy** [comment]
[permissions.txt](https://github.com/IntellectualSites/PlotSquared/files/264240/permissions.txt)
http://hastebin.com/famokuheda

**Comment by boy0001** [comment]
In the settings.yml, change:
max_plots: -1
to (default value) 127

**Comment by boy0001** [comment]
Remove PlotMe, you still have it installed. 

PlotSquared also caches permissions. If you derank yourself (in the above file all three players would have the admin bypass perm), you then need to relog for it to take effect. 

Let us know if you resolve the problem.

**Comment by EmpireEddy** [comment]
Well i deleted plotme completely but i really dont understand you boy0001 can you give a more detailed explanation of what i have to do?

**Comment by AshourAziz** [comment]
It 100% is an issue on 1.9.4 servers, no error in logs.

**Comment by AshourAziz** [comment]
[00:48:02] [Server thread/INFO]: BukkitPlotGenerator does not fully support: null[m

**Comment by AshourAziz** [comment]
Stripped it down to 1.9.4 + ProtocolLib + Multiverse + ProtocolSupport and it's still occurring. here is a p2 dump

http://hastebin.com/paligoduji

**Comment by AshourAziz** [comment]
Narrowed it down, It seems to be simply allowing people to access CHESTS/Furnaces and such. Building/Breaking blocks doesn't seem to work.

I'm assuming something was changed with Chests in 1.9.4?

**Comment by manuelgu** [comment]
Which part did you not understand?
Remove the PlotMe jar completely and follow the steps to disable plotme conversion (settings.yml -> plotme-convert set to false). Restart the server and see if the problem still occurs.

**Comment by EmpireEddy** [comment]
Fixed it thanks
