### ISSUE TITLE
1.9.4 Chest/Furnace access allowed

### ISSUE THREAD

**Issue by AshourAziz** [IntellectualSites/PlotSquared#1116]
http://hastebin.com/paligoduji

Anyone can access anyone's plots Chests/Furnaces, bypassing protection.
They cannot Mine/Build on plots they should not have access too though

1.9.4 + plotsquared + someoneelses plot + open there chests

I'm assuming something was changed with Chests in 1.9.4?

**Comment by AshourAziz** [comment]
I've also tried a few random builds that where older, without any change.

**Comment by boy0001** [comment]
http://ci.xephi.fr/job/PlotSquared/115/changes is probably the latest stable build.

**Comment by AshourAziz** [comment]
The bug is not present in that build.

**Comment by QUIQUELHAPPY** [comment]
any news about that...?

**Comment by manuelgu** [comment]
@QUIQUELHAPPY It was fixed on the 14th of May.

**Comment by QUIQUELHAPPY** [comment]
I found the error.
Idk the plugin didn't generate the default flags (use deny and place deny).
