### ISSUE TITLE
NPE  at com.plotsquared.sponge.SpongeMain.setGenerator(SpongeMain.java:337)

### ISSUE THREAD

**Issue by ryantheleach** [IntellectualSites/PlotSquared#1117]
http://pastie.org/private/vqlf1esrfeqpz3jxjs4pa

Someone on #Sponge was getting a NPE, I checked the source and found the problem.

https://github.com/IntellectualSites/PlotSquared/blob/master/Sponge/src/main/java/com/plotsquared/sponge/SpongeMain.java#L337

world is being referenced outside of the null checking if block, but considering the else above it should be throwing an exception, I have no idea what's going on.

```
5:56 PM <Mickimo> Hello, I have an error with PlotSquared on sponge:
5:56 PM <Mickimo> http://pastie.org/private/vqlf1esrfeqpz3jxjs4pa
6:06 PM → Unh0ly_Tigg and agowa338 joined  •  Corjaantje|Offline → Corjaantje  
7:04 PM <ryantheleach> Mickimo: If you don't get a response here, you might try #IntellectualCrafters the channel for plotsquared
7:05 PM <Mickimo> I think I worked out a solution, it seems forcing the world den in the sponge config might do it
7:05 PM <ryantheleach> Having a look, without knowing anything about plotsquared, or what version you are using, it looks like a plotsquared bug
7:05 PM → Yoje4li joined (webchat@5ED56506.cm-7-6b.dynamic.ziggo.nl)
7:05 PM <Mickimo> I'll let you know if what I did works c:
7:05 PM <+Tzk> you could also ask on the plotsquared thread on the forums :)
7:05 PM <Yoje4li> Hey, how can I send a player to another server? (sponge + bungee)
7:05 PM <+Tzk> and report your solution there
7:06 PM <ryantheleach> I've spotted the bug btw
7:07 PM <Mickimo> ah
7:08 PM <ryantheleach> Mickimo: https://github.com/IntellectualSites/PlotSquared/issues/1117
7:08 PM <ryantheleach> If you have a github account feel free to follow up with any details you might have
7:08 PM <ryantheleach> It looks like it should be a relatively easy fix, once they get around to it
New messages since you tabbed out
7:09 PM <Mickimo> My testing has returned a positive result, thanks to 4 hours of time wasted xD
```

**Comment by Mickimoo2** [comment]
(I was the person)

It seems that a temporary fix is to force the plotsquared geneneration under the world specific config:

/config/sponge/worlds/overworld/world
```
    world-generation-modifiers=[
        PlotSquared
    ]
```

My findings also found that it occurred ONLY when being used on the overworld, all the other worlds that were created by plotsquared contained that generation modifier

**Comment by MattBDev** [comment]
I want to wait for Sponge 5.0 for this to due to World Generation stuff being changed. It seems like every update Sponge makes has a breaking change for World Generation and to fix it now and just have it break kinda sucks.

**Comment by Mickimoo2** [comment]
Is it not possible to just add the line into the config?
