### ISSUE TITLE
Non-op player can place boats&carts on public roads (BUG report)

### ISSUE THREAD

**Issue by kunxian888** [IntellectualSites/PlotSquared#1123]
# Bug report.
**Debug paste link**:
http://hastebin.com/qadebogeru

**Description of the problem:**
player with only 
plots.permpack.basic  
plots.permpack.basicinbox 
plots.plot.1 
plots.set.flag.pvp.* 
plots.use plots.visit.other
permission was able to place boats and minecarts on public roads (they cant destroy nor ride it)

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by manuelgu** [comment]
Unable to reproduce. The boat gets removed from the inventory (when in survival mode) but not actually placed.

**Comment by kunxian888** [comment]
what about player place the boat inside his/her plot and drive it into the road? Since boat can be drove on land on 1.9

**Comment by manuelgu** [comment]
See `kill_road_vehicles` in settings.yml

**Comment by kunxian888** [comment]
got it, thanks
