### ISSUE TITLE
Plot Download Maximum Size not configurable

### ISSUE THREAD

**Issue by Quicksteve** [IntellectualSites/PlotSquared#1124]
Using the latest version from Spigot (3.3.3), I can't download plots larger than 512x512 using the /plot download command. As this is not configurable but instead hardcoded I can't download plots in my bigplots world.

I'm not quite sure why this value is hardcoded (technical limitations with schematics?) but I would love to see this issue get resolved by making it configurable in the config.

**Comment by boy0001** [comment]
The command needs to be optimized since there's some performance issues with larger plots. Try downloading as a world file `/plot download world`
