### ISSUE TITLE
Remove titles and put it in chat instead. 

### ISSUE THREAD

**Issue by Danielh90** [IntellectualSites/PlotSquared#1125]
Hello I would like to remove my title with the owned (Player) and put it in chat instead is that possible?

**Comment by boy0001** [comment]
You can disable titles per plot using `/plot flag set titles false` or globally in the `settings.yml` by changing `titles: false`.

To have a greeting message in chat, you can use the greeting flag. `/plot flag set greeting <value>` or set it globally in the settings.yml:
https://github.com/IntellectualSites/PlotSquared/wiki/Usage:-Plot-flags#default-flags

**Comment by Danielh90** [comment]
How would I set the greeting globally in the settings? Do I put it under flag and say greeting: "Message" also do you guys support %player% variables?

**Comment by boy0001** [comment]
Yes
%id%, %alias%, %num%, %desc%, %biome%, %owner%, %members%, %player%, %trusted%, %helpers%, %denied%, %expires%, %flags%, %build%, %desc%, %rating%

**Comment by Danielh90** [comment]
@boy0001 you did not answer my first question" How would I set the greeting globally in the settings? Do I put it under flag and say greeting: "Message""

**Comment by boy0001** [comment]
> Do I put it under flag and say greeting: "Message"

Yes

**Comment by Danielh90** [comment]
Thank you

**Comment by Danielh90** [comment]
Can we delete this issue please?

**Comment by boy0001** [comment]
no
