### ISSUE TITLE
no perms

### ISSUE THREAD

**Issue by Jacksharkben** [IntellectualSites/PlotSquared#1128]
no one can do anything? they have the perms

**Comment by Jacksharkben** [comment]
?

**Comment by MattBDev** [comment]
@Jacksharkben You didn't provide any information whatsoever to solve the problem. the most likely cause of this "Bug" is that you didn't provide the permissions even though you think that you did. This is a simple case of User Error.

**Comment by Jacksharkben** [comment]
it says it is added to the right group

**Comment by MattBDev** [comment]
This is still user error. I recommend using the plugin PEX for managing your permissions.
