### ISSUE TITLE
Admin bypass of plot trust limit

### ISSUE THREAD

**Issue by AshourAziz** [IntellectualSites/PlotSquared#1130]
Administrators/operators should have the ability to bypass the configured amount of max trustable people to a plot.

**Comment by MattBDev** [comment]
The default limit is very high already (128 players). Additionally, this limit is configurable.I don't think this really something that needs to be added. Although I would still like to hear of a use case for it.

**Comment by AshourAziz** [comment]
Our max member limit is set to 2, we don't want people housing lots of players on one plot for various reasons.

But when administrators want to add more people to a plot, we're unable to bypass this limit. Even as operators.

So the idea is for the general public 2 is our max (as defined in configuration) but we want to manually for certain people add 5, 10 or more people. Bypassing the normal limit of "max-members"

The reason for this, is the ability to limit people and sell the additional "add a person" through tokens/shops.
