### ISSUE TITLE
Issue with PerWorldPlugin

### ISSUE THREAD

**Issue by TheChampTF** [IntellectualSites/PlotSquared#1136]
http://paste.yu8.me/?11275e50be055ffd#Xp/vyJnkS05e5/UsAOnYG5Y0vsRsvT75f8ErcukHo2U=

I think this might be caused by PerWorldPlugin but sending it your way just to be sure.

And using latest build released

**Comment by boy0001** [comment]
You can ignore it. It's fixed in the dev builds.
