### ISSUE TITLE
[00:33:13] [Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to PlotSquared v3.3.3

### ISSUE THREAD

**Issue by PabloGamer380YT** [IntellectualSites/PlotSquared#1138]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**: [00:33:13] [Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to PlotSquared v3.3.3

**Description of the problem:** 
I have a problem when installing the plugin plotsquared always gives me this error
[00:33:13] [Server thread / ERROR]: Could not pass event PlayerCommandPreprocessEvent to PlotSquared v3.3.3
and that is not already tried everything and nothing could help me please is urgent

**How to replicate**:

Make sure you've completed the following steps (put an X between of brackets):
- [] Include `/plot debugpaste`
- [] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] Made sure you're using an updated version of PlotSquared
- [] Made sure the bug/error isn't caused by any other plugin

**Comment by manuelgu** [comment]
Can you manually upload your settings.yml and the log/latest.log file to hastebin.com?

**Comment by MattBDev** [comment]
@PabloGamer380YT If it was urgent you should have went to the IRC or reported the issue properly.

**Comment by PabloGamer380YT** [comment]
Plotsquared generator isn't creating Plotworld, plotsquared generator is creating a normal world with random seeds what is wrong?

**Comment by PabloGamer380YT** [comment]
log/lastes.log      http://hastebin.com/epohoqasuq.coffee
settings.yml    http://hastebin.com/tobiceseto.sm

**Comment by MattBDev** [comment]
@PabloGamer380YT You have several things wrong with your server:

1. You are using an outdated version of Java. Update to Java 8.
2. You are using an outdated version of WorldEdit. Use WorldEdit 6. 
3. You have other plugin errors!
4. You're settings.yml is missing the world information. 
5. This issue is closed and the information you are seeking is for a completely unrelated issue. Open a new ticket if you need more help.
