### ISSUE TITLE
Why won't my custom template work?

### ISSUE THREAD

**Issue by dumbninja22** [IntellectualSites/PlotSquared#1143]
I get these errors:

http://romulan.xyz/i/GzmNQrawH7.png
http://romulan.xyz/i/Enb21raePA.png
And a few others, especially Access Denied ones for whatever reason.

I'm trying to use this template file that I made myself: https://www.dropbox.com/s/ho0jvwe2umu5pkj/jail.template?dl=1

**Comment by manuelgu** [comment]
How did you create the template file?
Please provide a `/plot debugpaste`.

**Comment by MattBDev** [comment]
Since the bug report guidelines were not followed, this issue will be closed in 24 hours if a `/plot debugpaste` is not provided and the question @manuelgu is not answered.

**Comment by boy0001** [comment]
The error is "Access denied", the server needs read permission for that directory. You can use e.g. `chmod 777 <dir>` to change it for `plugins/PlotSquared/plugins

**Comment by dumbninja22** [comment]
@boy0001 I'm using windows, and I even thought of that by selecting "allow all" under windows file permissions. No other plugins are having this issue.

@manuelgu @MattBDev http://hastebin.com/bijipogeto

**Comment by manuelgu** [comment]
Your debugpaste is missing the required part of the settings.yml. Did you manipulate any of the files? If not, can you manually upload your `settings.yml` to hastebin.com?



> How did you create the template file?

**Comment by manuelgu** [comment]
Does the error also occur when you import one of the provided templates? (See template folder for names)

**Comment by dumbninja22** [comment]
That's the thing. I don't get the error (most of the time) when importing provided templates.

Which is why this is more of a "what did i do wrong" question.

I created 3 schematics, plot sideroad and intersection (following the lead of the unzipped default templates). I included the yml (copied from the others) zipped it up, renamed to .template, and it didn't work.

**Comment by MattBDev** [comment]
In the future please use `/plots debugpaste` for reporting issues. Screenshots do not always provide information that is useful or relevant. The link you provided after the fact did not contain the error you shared in the screenshot. 
As for your issue, it seems to be an issue with your file system not allowing the server to read/write files. For Windows you can right click the file/folder and modify read and write access in the security tab. In the General tab make sure "Read-Only" is not selected.
