### ISSUE TITLE
PlotSquared generating the plots world problem with BiomesOPlenty Mod

### ISSUE THREAD

**Issue by ghost** [IntellectualSites/PlotSquared#1144]
**Debug paste link**:
http://hastebin.com/yebiqafuto

**Description of the problem:**
Thermos 1.7.10 can not create a plots world.

**How to replicate**:
Use `mv create plotworld normal -g PlotSquared` command to create a new plots world, can not be created properly. When created a world, it is still a normal world.

2016-05-31 22:07:22 Same problem: #771 
2016-05-31 22:17:30 Same problem: #699

**Comment by sourcepowered** [comment]
Oh oh oh I find the problem:
I installed the BiomesOPlenty Mod, so...
PlotSquared can not support BiomesOPlenty Mod...

**Comment by MattBDev** [comment]
I don't believe it is possible or at least easy to support the BiomesOPlenty mod, they aren't even supporting their 1.7 version of their mod anymore.

**Comment by MattBDev** [comment]
It should also be brought to light that 1.7.10 was released almost 2 years ago.

**Comment by AuthMe** [comment]
I got this too, in Sponge 1.8.9 with PlotSquared.
So I think we should to change something.

**Comment by MattBDev** [comment]
@AuthMe a fix for 1.8.9 or 1.9 is more realistic if the issue is still occurring there

**Comment by CappyT** [comment]
Can confirm this, 1.7.10 on thermos, BOP breaks PlotSquared generation. Interenstingly, plotme still works.
Also, I want to point out that 1.7.10 il used by the 90% of modded servers, so if you don't support 1.7.10, you're basically cutting off the whole modded community.

**Comment by MattBDev** [comment]
@CappyT the modded community needs to understand that you can't stay 3 versions behind. Forge Dev Leads said that once you update to 1.8 code changes should be largely reduced. They also said that mods should have already updated if they haven't already. If they are still only 1.7.10 then those mod developers are LAZY

**Comment by MattBDev** [comment]
1.7 will no longer be supported.
