### ISSUE TITLE
Plot merge bug

### ISSUE THREAD

**Issue by xDacon** [IntellectualSites/PlotSquared#1149]
**Debug Paste Link**
http://hastebin.com/zizaradoxa

**Description of the problem:**
When a player merges a plot with another players plot, it says it sends a merge request, and causes that player to instantly accepting it, allowing anyone to merge with any plot. 

After testing with some permissions, I removed every perm except for plots.merge, and it would no longer merge w/o permission, however when the other account would type /plot confirm to confirm the merge - nothing would happen. Tested multiple times

**How to replicate**:

1) Claim one plot with one account
2) Claim a plot next to that one with another account
3) Have one account merge with the other plot 

If it doesn't merge instantly w/o permission of the other account, it won't merge either after the other account confirms the request.

**Comment by xDacon** [comment]
Bump

**Comment by MattBDev** [comment]
@xDacon 👈 *poke*

**Comment by boy0001** [comment]
Permissions issue.
It merges instantly if you have: `plots.merge.confirm.bypass`
