### ISSUE TITLE
wont convert 1 of my servers

### ISSUE THREAD

**Issue by mcraftpete** [IntellectualSites/PlotSquared#1152]
http://pastebin.com/fR6GRW46

I have done this with 3 other servers so know the routine pretty well , I stopped server , deleted plotme plugins , uploaded plotworld plugin and started server. The above is what you see at this point , I have run the process serveral times now in different ways 1st restoring my server back to what it started as and restarting the whole process to be sure I am not missing something.

What happens is 1 plot does convert at end as if I do /plot list all I can see 1 , there are about 35,000 plots to convert so shouldn't be so bad.

I have even tried leaving plotme convert on and restarting server again to see if it will trigger but just doesn't want to.

Any ideas would be great :)

**Comment by MattBDev** [comment]
Your server keeps running into a garbage collection issue. I recommend you allocate more memory to the server or disabling other plugins during the conversion.

**Comment by mcraftpete** [comment]
http://pastebin.com/XfsXEPTT

16gb of ram now allocated , as I said I have run through this with high ram disable plugins etc, it simply converts 1 only which makes me think its the plotme db , do you see any errors in the new paste ?

**Comment by boy0001** [comment]
No errors, it only finds one plot. Can you attach a zip of your PlotMe folder here?

**Comment by mcraftpete** [comment]
I have a drop box here ...https://www.dropbox.com/s/a97inmf5dh8wq8z/plots.db?dl=0

Its weird as there are no errors just simply doesn't let it load.

**Comment by boy0001** [comment]
In your plotme config set the version to 0.16

You had tried using PlotMe 0.17 at some point and had 1 plot on that version. Changing the version in the config will convert the 0.16 tables.

**Comment by mcraftpete** [comment]
works thank you for your help :)
