### ISSUE TITLE
Huge Worldedit Problem 

### ISSUE THREAD

**Issue by Bobcatsss** [IntellectualSites/PlotSquared#1153]
People can use the worldedit (/brush sphere grass 5) on other players plots.

**Comment by MattBDev** [comment]
Didn't follow bug report template and probably gave users the wrong permissions

**Comment by Bobcatsss** [comment]
I gave them the right permissions. Fist time posting on here so sorry for not doing it right. Ive just tested it on another version of the plugin with the same permissions and they can't use it on other plots
