### ISSUE TITLE
/ps toggle titles does not work

### ISSUE THREAD

**Issue by dordsor21** [IntellectualSites/PlotSquared#1155]
using /ps toggle titles does not toggle hotbar plot titles. The message "Disabled setting: titles" is sent, but titles are still shown.

Titles enabled in config. No errors in console.

spigot 1.9.4 P2 v3.3.3

**Comment by boy0001** [comment]
Titles are the large text that appears on screen. What message is appearing over the hotbar?

**Comment by dordsor21** [comment]
titles is what I mean. When doing /ps toggle titles, titles continue to show.

**Comment by MattBDev** [comment]
Can't replicate and we are now at 3.4.4 so I am going to close this issue. If it is still a problem it can be reopened.
