### ISSUE TITLE
Chunks no longer re-sent to players on biome change

### ISSUE THREAD

**Issue by dordsor21** [IntellectualSites/PlotSquared#1156]
Players need to manually reload chunks when changing a plot's biome in 1.9 whereas in 1.8 chunks are resent to players and biome changes happen without needing to relog.

spigot 1.9.4 P2 v3.3.3

**Comment by MattBDev** [comment]
@boy0001 Correct me if I'm wrong but isn't this more of an issue with bukkit and something with a memory leak?

**Comment by MattBDev** [comment]
Cannot reproduce using latest development build. Did not follow bug report format.

**Comment by dordsor21** [comment]
I'm unable to use the latest dev build because it creates incompatibilities with a number of other plugins that need to be compiled using P2
