### ISSUE TITLE
Outsource title toggling to per-plotworld

### ISSUE THREAD

**Issue by manuelgu** [IntellectualSites/PlotSquared#1158]
Currently you can only toggle `titles` globally. It would be great to have the option to toggle this per-plotworld.

**Comment by boy0001** [comment]
Would need to set the meta based on the world:
```Java
toggle(player, area + "disabletitles")
```
And also a check for using the command outside a plot area.

**Comment by boy0001** [comment]
Closing as already possible with the config option, just set titles:false under the plot world's flag section in the config.
