### ISSUE TITLE
#build 193 onwards Could not pass event WorldInitEvent to PlotSquared spigot 1.9.4

### ISSUE THREAD

**Issue by frizzbee30** [IntellectualSites/PlotSquared#1161]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://pastebin.com/8b5TngXa

**Description of the problem:**

Updating to 193 causes the plugin to fail, rolled back plugin and full p2 folder to build #190 to resolve

we run multiverse with the latest dev build of multiverse core

Spigot is the latest commit as of today

/p debug paste is an unrecognised command

**How to replicate**:

Make sure you've completed the following steps (put an X between of brackets):
- [] Include `/plot debugpaste`
- [] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] Made sure you're using an updated version of PlotSquared
- [] Made sure the bug/error isn't caused by any other plugin

Hi, this is just for information as I'm aware it's not release code.

 This is the first time we have had an issue with loading the plugin (in test), although we have skipped some iterations.

If you require the full log etc, please let me know.

(Thanks for all the hard work put into the plugin!)

**Comment by manuelgu** [comment]
@boy0001 was in the middle of upgrading to a new configuration.

Fix: Rollback Plotsquared to a previous version, then try latest dev build.

**Comment by frizzbee30** [comment]
Thanks, latest version was fine in test. Only quirk was the holoplot signs seemed to have moved randomly around the borders and in the plots, so will hang back :)
