### ISSUE TITLE
Players Can Open Other Players Chests and Can Place Blocks On Other Plots

### ISSUE THREAD

**Issue by QUIQUELHAPPY** [IntellectualSites/PlotSquared#1162]
Players Can Open Other Players Chests and Can Place Blocks On Other Plots!

Debug: http://hastebin.com/piqixiriba

**Comment by manuelgu** [comment]
Likely to be caused by your permission setup.

Check your permissions and consider switching to PermissionsEx.

**Comment by QUIQUELHAPPY** [comment]
Players can't break blocks any way.
I'll send my permission setup in a moment

**Comment by MattBDev** [comment]
User error. Not valid

**Comment by QUIQUELHAPPY** [comment]
so, it's a plugin-caussed issue?

**Comment by QUIQUELHAPPY** [comment]
is not user-error... .-.

**Comment by QUIQUELHAPPY** [comment]
Default:
    default: true
    permissions:
    - plots.plot.1
    - plots.auto
    - plots.claim
    - plots.clear
    - plots.comment
    - plots.use
    - plots.inbox
    - plots.help
    - plots.home
    - plots.info
    - plots.kick
    - plots.music
    - plots.rate
    - plots.visit
    - plots.visit.other
    - nte.default
    - wannatrade.trade
    - trade.sneaktrade
    - essentials.home
    - essentials.home.bed
    - essentials.tpa
    - essentials.tpaccept
    - essentials.sethome
    - trade.trade
    - trade.ignore
    - trade.accept
    - essentials.pay
    - essentials.afk.auto
    - essentials.afk
    - essentials.msg
    - chestcommands.open.shop.yml
    - chestcommands.open.menu.yml
    - plots.add
    - bm.command.report
    inheritance: []
    info:
      prefix: ''
      build: true
      suffix: ''
