### ISSUE TITLE
I have error in conlose. when start server

### ISSUE THREAD

**Issue by jomjonejame** [IntellectualSites/PlotSquared#1163]
# Bug report template (Follow this template unless you are making a feature request.)

**Debug paste link**:
http://pastebin.com/hhMqfFpk

**Description of the problem:**
MC 1.8.8
I have error in conlose. when start server

**How to replicate**:

Make sure you've completed the following steps (put an X between of brackets):
- [] Include `/plot debugpaste`
- [] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] Made sure you're using an updated version of PlotSquared
- [] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment]
We need a debug paste link. A pastebin of an error is not the same or as helpful as a `/plots debugpaste`. Please provide a debug paste in 24 hours or the issue may be closed.

**Comment by MattBDev** [comment]
I also recommend testing the latest dev release to verify the issue hasn't already been resolved.

**Comment by boy0001** [comment]
You have a corrupt player data file:
<world>/playerdata/2397ad50-e086-3413-bde0-11c39c7fb62d.dat

**Comment by jomjonejame** [comment]
`We need a debug paste link. A pastebin of an error is not the same or as helpful as a /plots debugpaste. Please provide a debug paste in 24 hours or the issue may be closed.`

Today I installed on the server, then it is an error. I took out the plugin PlotSquared server. For fear that it would affect my server and install the plugin by tomorrow, I do as you say.

**Comment by jomjonejame** [comment]
```
You have a corrupt player data file:
/playerdata/2397ad50-e086-3413-bde0-11c39c7fb62d.dat
```

Then what do I do?

**Comment by MattBDev** [comment]
You delete the corrupted data file or try to fix it using an NBT Editor. Nothing we can do for you.
