### ISSUE TITLE
 It is possible PURGE plots fo specific Time

### ISSUE THREAD

**Issue by RPGMais** [IntellectualSites/PlotSquared#1165]
it is possible a command. /plot purge 50 days (Exemple)

It would be a useful command old servers

I can pay for a version so.

**Comment by boy0001** [comment]
Use the expire manager. If you don't want any complexity cutoff threshold you can just set `threshold: -1`, Also set `days: 50`.

**Comment by boy0001** [comment]
https://github.com/IntellectualSites/PlotSquared/wiki/World-reduction#plot-expiry
