### ISSUE TITLE
Documentation Request

### ISSUE THREAD

**Issue by Samistine** [IntellectualSites/PlotSquared#1167]
Documentation for the following example would be beneficial.

Plugins that allow the player to do something that in turn edits the blocks.
A simple example showing how to check whether a player is allowed to build at a specific location.

**Comment by manuelgu** [comment]
```java
Plot plot = player.getCurrentPlot();

if (pot.isAdded(UUIDHandler.getUUID(player.getName(), null)) {
    // is added
}
```

**Comment by MattBDev** [comment]
@manuelgu just answered the question. things like this are better to be asked on the irc.
