### ISSUE TITLE
[Request] Blacklist Use Flag

### ISSUE THREAD

**Issue by Samistine** [IntellectualSites/PlotSquared#1169]
Ability to blacklist vs whitelist "use" flag.

Implementation:
Add a new flag, example: "use-blacklist"
Set use flag to "0:0"
Set use-blacklist flag with "54"

This would allow for the ability to easily whitelist all normal blocks whilst adding the ability to blacklist common "private blocks" such as chests.

The main problem I am having on my server is manually whitelisting every single non container/specialty block.

This should help reduce spam (YOU DON"T HAVE PERMISSION) to players who like to right click on everything, me included.

**Comment by MattBDev** [comment]
Definition of whitelist:
a list of people or products viewed with approval. 

Every block is "blacklisted" by default. I don't see major use of this except for lazy people.

**Comment by Samistine** [comment]
It's just very inconvenient to have to whitelist 100's of blocks when you
want to allow access to everything except a few blocks

**Comment by boy0001** [comment]
Remove the message from the translations file if you don't want the message being sent.
