### ISSUE TITLE
[Feature] Settings: Add setting to reduce messages

### ISSUE THREAD

**Issue by Samistine** [IntellectualSites/PlotSquared#1170]
Accidently clicking on a plot sends you two messages, neither of which help the guest of the plot much. There should be a way to instead of saying you are lacking permission and should ask the owner to add use/break flags, just say something along the lines of "You don't have permission to this plot". You should also be able to fully disable this message, and for the majority rate-limiting this message would be beneficial.

![image](https://cloud.githubusercontent.com/assets/7032358/15945281/9ec07632-2e5f-11e6-9839-71f0c3933026.png)

**Comment by manuelgu** [comment]
This can already be achieved with editing the `translations/PlotSquared.use_THIS.yml`.

`flag_tutorial_usage`
`no_permission`
`no_permission_event`
