### ISSUE TITLE
Old bug- Using Milk bukkit on no Perm. plot can make animals goes back to baby stage

### ISSUE THREAD

**Issue by kunxian888** [IntellectualSites/PlotSquared#1172]
# Bug report template (Follow this template unless you are making a feature request.)
**http://hastebin.com/elepofepek**:

**Description of the problem:**
This Bug can be traced back to PlotMe Plugin. If a player don't have trust nor add permission. It can use a milk bukkit to make animals and Villagers goes back to baby stage.
**How to replicate**:
By holding a milk bukkit and right click a grow-up animals.

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by boy0001** [comment]
There's no cancellable event for this, so it's a bit of a hacky solution.
