### ISSUE TITLE
Cant undeny players

### ISSUE THREAD

**Issue by Ac3dUd3** [IntellectualSites/PlotSquared#1174]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:

**Description of the problem:**
I or my players cannot undeny anyone on a plot once we have denied them. they have the permission plot.undeny
**How to replicate**:
not sure but here is a screenshot http://prntscr.com/beq40f

Make sure you've completed the following steps (put an X between of brackets):
plotsquared version 3.4.0-0147690
spigot version 1.9.4-R0.1-Snapshot

**Comment by manuelgu** [comment]
The permission is `plots.remove`.
