### ISSUE TITLE
[Bug] Redstone repeaters and piston physics broken in merged plots

### ISSUE THREAD

**Issue by SupremeMortal** [IntellectualSites/PlotSquared#1175]
# Redstone on merged plots broken
**Debug paste link**:
http://hastebin.com/xewiyacaro
**Description of the problem:**
When two or more plots are merged, most redstone functionality becomes disabled.
All redstone works perfectly on single plots
**Video**
[Youtube Link](https://youtu.be/bcGz8ICl0lg)
**How to replicate**:
1. Create two plots next to each other.
2. Place a redstone torch with a redstone repeater infront. (The redstone repeater should not light up)
- [x] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] Made sure you're using an updated version of PlotSquared (Using latest development build)
- [X] Made sure the bug/error isn't caused by any other plugin (Thought it was RedstoneClockPreventer but I then removed it)

**Comment by Sauilitired** [comment]
This is not the case in the latest version at the very least (tried replicating with your settings). This can be re-opened if you experience the same issues after the next release :cow:

**Comment by Maxetto** [comment]
I'm reopening this as I have this exact issue too. Merged plots disable redstone repeaters in a portion of the plot (seems like in north-east)

I'm using PlotSqured 3.4.5.

http://hastebin.com/uzaqexubaf
