### ISSUE TITLE
I have question

### ISSUE THREAD

**Issue by jomjonejame** [IntellectualSites/PlotSquared#1176]
**Description of the problem:**
I have questions for road floor and member can't use command /plot sethome

1. Member of my plot can't use command /plot sethome
![zxcasd](https://cloud.githubusercontent.com/assets/19164029/15983522/68c024f8-2fd4-11e6-998a-2a4f8079a1be.jpg)
![2559-06-11_12 52 23](https://cloud.githubusercontent.com/assets/19164029/15983533/c85dc974-2fd4-11e6-8974-93e3d651ad83.png)

2. use /plot merge But center point have road floor
![2559-06-11_12 46 29](https://cloud.githubusercontent.com/assets/19164029/15983535/d72a6156-2fd4-11e6-86b3-18ffc3342e9a.png)
![2559-06-11_13 01 57](https://cloud.githubusercontent.com/assets/19164029/15983534/d7268022-2fd4-11e6-8b94-c56b02b6378d.png)

3. New players can claim a plot for free one time. ?

**Comment by MattBDev** [comment]
"I have a question" --- Thanks for the extremely detailed issue title.

**Comment by MattBDev** [comment]
1. The message in the screenshot gave you the answer already.
2. Accomplishing something like that isn't possible.
3. Not possible yet. WIP
