### ISSUE TITLE
how to undeny

### ISSUE THREAD

**Issue by ridalarry** [IntellectualSites/PlotSquared#1178]
I am having dev build version 208 and it seems like the command "/plot undeny" is removed

**Comment by MattBDev** [comment]
We don't know what dev version 208 is. Are you referring to http://ci.athion.net/job/PlotSquared/208/ ?
Use /plot remove <player> to undeny a player. Undeny is also an alias and can be configured in the commands.yml

**Comment by ridalarry** [comment]
yes that what I meant, but there is a player have denied * not he cant undeny it

**Comment by manuelgu** [comment]
Look in your commands.yml if `undeny` is an alias of /plot remove
