### ISSUE TITLE
Non of the command working (including world creation)

### ISSUE THREAD

**Issue by holywater456** [IntellectualSites/PlotSquared#1179]
# Bug report template (Follow this template unless you are making a feature request.)
**Sorry, i dont know what debug means :/

**All  Command not working, World Creating "/mv create Plots normal -g PlotSquared" FAILED
  And Im Using Spigot 1.8 for my private server.

**No Idea what's the problem :/

Make sure you've completed the following steps (put an X between of brackets):
- [] Include `/plot debugpaste`
- [] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] Made sure you're using an updated version of PlotSquared
- [] Made sure the bug/error isn't caused by any other plugin

**Comment by EvilOlaf** [comment]
Check your console output for errors. If in doubt post a FULL startup log here including your tries to run a command from P^2.

**Comment by holywater456** [comment]
it wont let me send text document here, and i tried to paste the log here but its too much (Google chrome lagged and i killed it)

**Comment by EvilOlaf** [comment]
Then there is no way to help you out as no one here has a second sight to know what's wrong.

**Comment by MattBDev** [comment]
User doesn't understand anything about a server. can't help.
