### ISSUE TITLE
Plants don't grow on merged plots

### ISSUE THREAD

**Issue by Dooleylabs** [IntellectualSites/PlotSquared#1183]
**Issue:** Trees do not grow past the original plot which was merged with other plots.

**Replicate:** Merge a 3 x 3 plot.

**Debug:** [http://hastebin.com/rimuredihi](http://hastebin.com/rimuredihi)

**Comment by manuelgu** [comment]
Duplicate of #1021.

Will be fixed with 3.4.0.
