### ISSUE TITLE
Player Keeps Fly after unclaiming Plot

### ISSUE THREAD

**Issue by pedroo21** [IntellectualSites/PlotSquared#1191]
**Debug paste link**:
- None

**Description of the problem:**
- You can fly in every plot in the world

**How to replicate**:
- Claim a plot
- Activate the fly flag in a plot
- Unclaim the plot
- You can now fly everywhere

**Comment by manuelgu** [comment]
Latest **development versions** have a fix for that.

http://ci.xephi.fr/job/PlotSquared/221/artifact/target/PlotSquared-Bukkit-3.4.1-SNAPSHOT.jar
