### ISSUE TITLE
Claiming bug

### ISSUE THREAD

**Issue by ILoveAMac** [IntellectualSites/PlotSquared#1192]
Players can't claim plots
**Plugin tells players that the can't claim more plots, but they haven't claimed any plots and I have made sure that they have all the perms like plots.plot.4 and every other one you can think of**

- [ ] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)]
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment]
That's nice. But you didn't give us all the required information. Please resubmit the ticket with a debugpaste.
