### ISSUE TITLE
Claiming bug

### ISSUE THREAD

**Issue by ILoveAMac** [IntellectualSites/PlotSquared#1193]
**Debug paste link**: http://hastebin.com/mevuhihahe

**Players can't claim land, even with the correct terms like plots.plot.4 and plots.use but all other permission nodes work**

**To replicate, give players the permissions they need, have them claim a plot, they are not alowwed to do so because it said: "You can't claim any more plots"   **

- [x] debugpaste
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by boy0001** [comment]
If you gave them more than 127, you need to raise max_plots in the settings.yml

**Comment by ILoveAMac** [comment]
Did not work
