### ISSUE TITLE
Database prefix is final, making everything incompatible when moving from 3.4.0 to 3.4.1 etc..

### ISSUE THREAD

**Issue by alekso56** [IntellectualSites/PlotSquared#1196]
**Description of the problem:**
This [line](https://github.com/IntellectualSites/PlotSquared/blob/master/Core/src/main/java/com/intellectualcrafters/plot/config/Storage.java#L7) is final.

[Blamee](https://github.com/IntellectualSites/PlotSquared/commit/951a6b82a274b07afb6579cd279891c7c2548a34#diff-fb6714633684e32d2c2ebbc29a987ca8R29)

**Comment by Sauilitired** [comment]
It seems that jesse forgot to remove the final modifier for that field, when he removed the other ones
