### ISSUE TITLE
3.4.1 can not support Thermos 1.7.10

### ISSUE THREAD

**Issue by MultiverseCore** [IntellectualSites/PlotSquared#1199]
There are too many problems.
Can not properly claim, can not clear, too many problems.
And IC2's rubber tree will generates in plots world. And clear command is useless.

**Comment by sourcepowered** [comment]
I just want to submit this issue, you preempted...
I can confirm this, there are too many problems with thermos.
And the IC2 experimental problem, Long before there.

**Comment by MultiverseCore** [comment]
@sourcepowered YES! I'm talking about this! And the latest 3.4.1 can not normally use.

**Comment by AuthMe** [comment]
Oh my god! I thought only I have these problems, because of my negligence, so I did not submit. But I did not expect that you all have.

**Comment by sourcepowered** [comment]
The problem is that the latest version can not normally use, with thermos.

**Comment by MattBDev** [comment]
Can you guys be more descriptive and use better grammar to explain the issue? It is really hard to tell what exactly is going on.

**Comment by MattBDev** [comment]
Seriously? none of you guys want to respond? We can't fix things if you will not explain in a way we understand.

**Comment by sourcepowered** [comment]
@MattBDev Please see #1221 .

**Comment by Sauilitired** [comment]
I'll close this then, let's use #1221 🍐
