### ISSUE TITLE
Plot Trust or Plot Add BUG

### ISSUE THREAD

**Issue by killkillsito** [IntellectualSites/PlotSquared#1203]
I was using TacoSpigot that is the same as PaperSpigot but a little bit modified. My server were running perfectly with another version, but when i update to the new version, the command /p trust or /p add send me crashes to the console. I tried to change TacoSpigot to PaperSpigot or Spigot, and changing the version but still the same error... I can't restore all because is in a very huge network and i would lose a lot of people...
Here is the crashes:
https://gyazo.com/7470d7cf284bdbe66a9ce3b34395a9fe
https://gyazo.com/f43d11e9723fd6bd90a71804d90f5f01

**Comment by Sauilitired** [comment]
Please provide a `/plot debugpaste`, as instructed when creating the issue report.

**Comment by killkillsito** [comment]
Here you go!
http://hastebin.com/sohoyovigo

**Comment by MattBDev** [comment]
Your PlotSquared version is outdated. Update to 3.4.2
