### ISSUE TITLE
Roads regenerating with only grass

### ISSUE THREAD

**Issue by tinylegend2016** [IntellectualSites/PlotSquared#1204]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:

**Description of the problem:**
My plots are 64x64..From my spawn point if I go in any direction after about 5 plots all the roads are grass not the standard quartz block...
**How to replicate**:

Make sure you've completed the following steps (put an X between of brackets):
- [] Include `/plot debugpaste`
- [] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] Made sure you're using an updated version of PlotSquared
- [] Made sure the bug/error isn't caused by any other plugin

**Comment by Sauilitired** [comment]
I quote: "Include `/plot debugpaste`". We are good, sure, but we are not able to magically know how you've got your server setup.
