### ISSUE TITLE
I don't have a worlds.yml

### ISSUE THREAD

**Issue by YepImRobbie** [IntellectualSites/PlotSquared#1210]
I don't have a worlds.yml, I only have settings.yml. I have checked absolutely every folder since I am attempting to set global flags.

worlds:
  plots:
    plot:
      size: 41
      height: 48
      biome: FOREST
      filling:
      - '1:0'
      auto_merge: false
      bedrock: true
      create_signs: true
      floor:
      - '2:0'
    road:
      width: 11
      height: 48
      block: '155:0'
    wall:
      filling: '43:0'
      height: 48
      block_claimed: '44:1'
      block: '44:0'
    home:
      default: side
      allow-nonmembers: false
    schematic:
      specify_on_claim: false
      on_claim: false
      file: 'null'
      schematics: []
    economy:
      prices:
        merge: 100
        sell: 100
        claim: 100
      use: false
    chat:
      enabled: false
    limits:
      max-members: 128
    world:
      max_height: 256
      gamemode: survival
      min_height: 1
      border: false
    event:
      spawn:
        egg: true
        breeding: true
        custom: true
    natural_mob_spawning: true
    mob_spawner_spawning: true
    flags: {}

I tried adding the flags bit to this, but it no workie. Can you demonstrate how I use the global flags feature with the settings.yml?

**Comment by YepImRobbie** [comment]
I am running the latest 1.8.8 spigot and using 3.3.3 plotsquared

**Comment by boy0001** [comment]
worlds.yml is for 3.4.0, in your version they are both in the settings.yml
