### ISSUE TITLE
PS.getPlots(PlotFilter...) always returns all plots

### ISSUE THREAD

**Issue by Pokechu22** [IntellectualSites/PlotSquared#1211]
**Debug paste link**: http://hastebin.com/qiqinekaci

**Description of the problem:**

The method [`PS.getPlots(PlotFilter... filters)`](https://github.com/IntellectualSites/PlotSquared/blob/2ff4e0791926b11de5fd6206a6ea0a26abdb2d88/Core/src/main/java/com/intellectualcrafters/plot/PS.java#L1068-L1096) doesn't actually correctly use the filers.  Instead, it always returns all plots, effectively ignoring the functions used in the filter.

This happens because `continue` ends up continuing the loop where it iterates through the filters, rather than the outer loops.  It could instead use a `return` on the first loop and a labeled continue for the second loop, like this:

```java
public Set<Plot> getPlots(final PlotFilter... filters) {
	final HashSet<Plot> set = new HashSet<>();
	foreachPlotArea(new RunnableVal<PlotArea>() {
		@Override
		public void run(PlotArea value) {
			for (PlotFilter filter : filters) {
				if (!filter.allowsArea(value)) {
					return;
				}
			}
			entryLoop: for (Entry<PlotId, Plot> entry2 : value.getPlotEntries()) {
				Plot plot = entry2.getValue();
				for (PlotFilter filter : filters) {
					if (!filter.allowsPlot(plot)) {
						continue entryLoop;
					}
				}
				set.add(plot);
			}
		}
	});
	return set;
}
```

This bug doesn't seem to effect normal usage of the plugin (there's only one place where this method is used) but it is causing trouble for me since I'm planning on using it in an extension.

**How to replicate**:

If the following snippet is run, one would expect no plots to be printed:

```java
Set<Plot> plots = PS.get().getPlots(new PlotFilter() {
	@Override
	public boolean allowsArea(PlotArea area) {
		return false;
	}
	
	@Override
	public boolean allowsPlot(Plot plot) {
		return false;
	}
});
logger.info(plots);
```

Instead, it prints all plots.

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] Made sure you're using an updated version of PlotSquared
    - Claims that there is a new update available for 3.4.2 but still seems to download 3.4.1-f5e7d08 (even when done manually)
    - Still seems to be present in the code
- [x] Made sure the bug/error isn't caused by any other plugin
    - Close enough for what the issue is

**Comment by MattBDev** [comment]
@Pokechu22 just a warning that I plan on refactoring this to use Java 8 stuff in the near future. Shouldn't happen for awhile though.
