### ISSUE TITLE
Plot World Lighting

### ISSUE THREAD

**Issue by dumbninja22** [IntellectualSites/PlotSquared#1216]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
N/A not needed. All you need to know is I DID set the random-light-updates to true in spigot.yml.

**Description of the problem:**
The lighting of a plot world, when using a template that has the sky closed off, does not render properly.

**How to replicate**:
http://romulan.xyz/i/MsAmBraQMy.png

As you can see, my custom template closes off the sky but it also has plenty of glowstone, which should look fine but doesn't in a plot world.

**Comment by MattBDev** [comment]
A debug paste IS needed no matter what. It isn't an optional thing.

**Comment by dumbninja22** [comment]
http://hastebin.com/oyepitipin

As you wish
