### ISSUE TITLE
`

### ISSUE THREAD

**Issue by TerminathanYT** [IntellectualSites/PlotSquared#1218]
Hey! I need help with plotsquared but I'm not sure where to post it. So imma post it here.

so I do the command /plot regenallroads plotworld in console and it gives me these error

25.06 03:26:23 [Server] WARN java.lang.RuntimeException: Could not find worlds folder: ./plotworld/region ? (no read access?)
25.06 03:26:23 [Server] WARN at com.intellectualcrafters.plot.util.ChunkManager.getChunkChunks(ChunkManager.java:190)
25.06 03:26:23 [Server] WARN at com.plotsquared.bukkit.util.BukkitChunkManager.getChunkChunks(BukkitChunkManager.java:650)
25.06 03:26:23 [Server] WARN at com.intellectualcrafters.plot.commands.RegenAllRoads.onCommand(RegenAllRoads.java:74)
25.06 03:26:23 [Server] WARN at com.intellectualcrafters.plot.commands.RegenAllRoads.onCommand(RegenAllRoads.java:38)
25.06 03:26:23 [Server] WARN at com.intellectualcrafters.plot.commands.MainCommand.handle(MainCommand.java:450)
25.06 03:26:23 [Server] WARN at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:303)
25.06 03:26:23 [Server] WARN at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:40)
25.06 03:26:23 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
25.06 03:26:23 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
25.06 03:26:23 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:640)
25.06 03:26:23 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:626)
25.06 03:26:23 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:411)
25.06 03:26:23 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
25.06 03:26:23 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653)
25.06 03:26:23 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556)
25.06 03:26:23 [Server] WARN at java.lang.Thread.run(Thread.java:745)
25.06 03:26:37 [Server] INFO CONSOLE issued server command: /list 
25.06 03:26:37 [Server] INFO Admins: [OWNER]Terminathan[YouTube]

Debug: http://hastebin.com/zigajobapa
Im sorry if this was not the right place to post it :s

Thanks

**Comment by MattBDev** [comment]
If you don't know what you are posting to, it is better to not post. Especially if you name the title :
> '
That is not a proper title name.
Anyways, this bug was fixed the other day.
