### ISSUE TITLE
Random White Stained Clay

### ISSUE THREAD

**Issue by TerminathanYT** [IntellectualSites/PlotSquared#1220]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
N/A

**Description of the problem:**
For some reason, there is random white stained clay in my plotworld :(
I'm not sure why this happened or how to fix it.
pls help
Ive tried to reload all roads, but it didnt do anything after hours of waiting for it to complete :(
**How to replicate**:
No idea

**Comment by RayDaAsian** [comment]
Is it similar to my issue? http://prntscr.com/bgnhy1

**Comment by MattBDev** [comment]
How is a debug paste "N/A" you just use the command to generate it. It can contain important information on how to reproduce this bug.

**Comment by MattBDev** [comment]
Please submit a debug paste or this issue will be closed.
