### ISSUE TITLE
Entering a Plot with Fly: False prevents you from flying in the roads.

### ISSUE THREAD

**Issue by trustinlies** [IntellectualSites/PlotSquared#1224]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**: http://hastebin.com/cinelefega

**Description of the problem:** When leaving a plot with the fly flag set to false, you will lose the ability to fly every time you leave a plot whether flying is allowed in world or not.

**How to replicate**:
1. Join Server that has flight allowed.
2. Enter a plot with Fly: False
3. Leave plot (note you can no longer fly on the road)
4. Enter plot with Fly: True (you can fly inside the plot)
5. Leave plot (again, you can no longer fly)

If this was intentional can you please add the ability to have the plugin NOT do this? We use this on our creative server and it is creating quite a bit of discontent. Some players are even going so far as to purposely set fly to false to troll other players.

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment]
Not intentional and clearly a bug.
