### ISSUE TITLE
PlotSquared Thermos BUG

### ISSUE THREAD

**Issue by sourcepowered** [IntellectualSites/PlotSquared#1225]
Only use Thermos and PlotSquared.
Please see this:
![aaa](https://cloud.githubusercontent.com/assets/17511838/16362870/43bda59e-3bec-11e6-9ee4-ac3ccbe9117b.png)
![bbb](https://cloud.githubusercontent.com/assets/17511838/16362871/43c2fada-3bec-11e6-9706-3bfa06f18644.png)
![ccc](https://cloud.githubusercontent.com/assets/17511838/16362872/43c3985a-3bec-11e6-8a21-eaea428492dd.png)

... I don't know what happend ... Use claim and clear command.

**Comment by MattBDev** [comment]
Please stop continuously using "PlotSquared Thermos Bug" it is coming to the point where it can be considered spam. Anyways, the template to report a bug was not followed so this issue is closed. It seems like your world generation was messed up possibly due to a size issue in your config.

**Comment by sourcepowered** [comment]
@MattBDev NO, not my fault, this is a bug, I have tested it several times.
Please see this: http://hastebin.com/doyiqivoza
Then, in your PlotMe plugin, I have not encountered any problems like this, including the IC2 mod's rubber tree problem, I do not know why you give up PlotMe. :(

**Comment by boy0001** [comment]
@MattBDev The debugpaste was included in the previous issue that was closed.

**Comment by boy0001** [comment]
@sourcepowered 
Build #.269 or above should work:
http://ci.athion.net/job/PlotSquared/

Also recommended to use FAWE (forge mod) which has the NMS classes for forge 1.7.10
http://ci.athion.net/job/FastAsyncWorldEdit/
