### ISSUE TITLE
Multiple values for self-registered flags

### ISSUE THREAD

**Issue by manuelgu** [IntellectualSites/PlotSquared#1226]
# Bug report
**Description of the problem:**
Custom registered flags can be instantiated multiple times with multiple values.
See `xvs-interact`
![](http://i.imgur.com/9ymN6bW.png)

The `xvs-interact:false` was set using a plugin,
the `xvs-interact:true` was set using `/plot flag set xvs-interact true`

**How to replicate**:
```java
BooleanFlag INTERACT = new BooleanFlag("xvs-interact");
Flags.registerFlag(INTERACT);

[..]

plot.setFlag(BOOLEAN, false);

// now run command from ingame
```

This cannot be reproduced with PlotSquared flags, used `grass-grow` to test.

**Comment by manuelgu** [comment]
Occured to be an issue with only on specific plot. Tested on fresh installation and it works fine. Will re-open if reproducable method was found.

**Comment by manuelgu** [comment]
Can't fully reproduce it but occurs to be an issue more than only once.

The plot had the flag `xvs-interact` set to true and false when I looked at it. I removed the flag with value `false` via code and still had `xvs-interact:true`.

This `xvs-interact:true` was also present in the plot_settings row under "flags". I was unable to delete it with `/plot flag remove xvs-interact` because it returned "That flag could not be removed".

The flag with value `true` seems to be stuck in the database, I can manually add/remove the flag once more with the ingame command.

**Comment by manuelgu** [comment]
Found a way to reproduce it.

1. Set your custom flag via code to `true`
2. Restart the server
3. Set your custom flag via code to `false`

After you've done that you will have the flag twice added to your plot, once with value `true` and once with value `false`.

**Comment by manuelgu** [comment]
> This cannot be reproduced with PlotSquared flags, used grass-grow to test.

With both code and commands this issue only occurs when there is a custom flag used.

**Comment by boy0001** [comment]
It also wouldn't load reserved flags from the database.
