### ISSUE TITLE
End Crystal do not count towards entity limit

### ISSUE THREAD

**Issue by manuelgu** [IntellectualSites/PlotSquared#1227]
# Bug report

**Description of the problem:**
You can place end crystal on a plot even if the entity cap was reached.
![](http://i.imgur.com/HRX1JJ7.png)
All good, all filled up. Can't place any more entities except for End Crystals (infinite amount)

**How to replicate**:
1. Fresh installation of latest P2 version and Spigot 1.10
2. Set the flags as shown in the screenshot for any plot and get a similar setup like shown on screenshot
3. Try to place end crystal on bedrock blocks and see that they can be placed as often as you wish

**Comment by MattBDev** [comment]
Can we fix it? Yes we can!
