### ISSUE TITLE
Signs don't show text when a user does /p claim or /p auto

### ISSUE THREAD

**Issue by starwarsfreak219** [IntellectualSites/PlotSquared#1228]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**: http://hastebin.com/gobitufupe

**Description of the problem:** When a user does /p auto or /p claim, it doesn't show anything on the sign and the sign is just blank.

**How to replicate**: Doing /p auto or /p claim

Make sure you've completed the following steps (put an X between of brackets):
- [X] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] Made sure you're using an updated version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by frizzbee30** [comment]
hi, if you are on spigot 1.10.(x) there was a bug with spigot and signs, that has now been fixed. Just needs a recompile :)

**Comment by starwarsfreak219** [comment]
So do I just get the latest Spigot build?
