### ISSUE TITLE
please fix the / plot clear !!! giving this error in the console

### ISSUE THREAD

**Issue by jaopedropvp** [IntellectualSites/PlotSquared#1232]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:

**Description of the problem:**

**How to replicate**:

Make sure you've completed the following steps (put an X between of brackets):
- [] Include `/plot debugpaste`
- [] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] Made sure you're using an updated version of PlotSquared
- [] Made sure the bug/error isn't caused by any other plugin

**Comment by jaopedropvp** [comment]
please fix the / plot clear !!! giving this error in the console

**Comment by EvilOlaf** [comment]
Missing the "error" as well as the debugpaste.

**Comment by MattBDev** [comment]
I fixed issue _blank_

**Comment by Sauilitired** [comment]
@MattBDev ninja closing issues :(
