### ISSUE TITLE
/p auto won't work 

### ISSUE THREAD

**Issue by OwningProds** [IntellectualSites/PlotSquared#1233]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/ugideyiqef
**Description of the problem:**
https://www.spigotmc.org/threads/plotsquared-help.160532/
**How to replicate**:
Replicate by overloading your server (too much memory) then it will eventually break a bunch of your plugins. (look @ spigot post)
Make sure you've completed the following steps (put an X between of brackets):
- [] Include `/plot debugpaste`
- [] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] Made sure you're using an updated version of PlotSquared
- [] Made sure the bug/error isn't caused by any other plugin

**Comment by manuelgu** [comment]
Please update your version of PlotSquared (you are still on 3.3.0) and Spigot (you are 337 versions behind)
