### ISSUE TITLE
API Methods

### ISSUE THREAD

**Issue by checkplys** [IntellectualSites/PlotSquared#1235]
What method should I use to get the plot where's a location
like api.getPlotInLoc(Location loc).
I want to use that to check in what plot a block is, and to make some type of secure command blocks in plots

**Comment by manuelgu** [comment]
You can use `Plot#getPlot( Location )`, but there is already a plugin for what you want to achieve https://www.spigotmc.org/resources/command-block.12512/

**Comment by checkplys** [comment]
Thanks. But that plugin is not really what I want, for example, I will not allow @e to kill players, block /op obviously, make setblock only work inside the plot, and those things.

**Comment by manuelgu** [comment]
Exactly what the plugin is doing :-) All actions are limited to the plot.
`/op` is disabled in command blocks on server level already, setblock only works inside of the plot with this plugin.

**Comment by MattBDev** [comment]
Answered by @manuelgu
