### ISSUE TITLE
[BUG] You are not in a Plot AREA

### ISSUE THREAD

**Issue by NickFirenzo** [IntellectualSites/PlotSquared#1238]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://prntscr.com/bolf59
http://hastebin.com/haxepanixa

**Description of the problem:**
After restart the server I'm typing /p home or /p claim and getting "you are not in a plot area" or "you are not in a plot", but in the PlotSquared folder PlotWorld is added in worlds.yml
worlds.yml: http://pastebin.com/xQ5hMjAG
PlotWorld: http://prntscr.com/bolgra

**Comment by manuelgu** [comment]
Make sure the generator is set to `PlotSquared` in the worlds.yml of **MultiVerse**

**Comment by NickFirenzo** [comment]
http://prntscr.com/bom1kz
Already set

**Comment by MattBDev** [comment]
1. You are using an outdated version of Java. You should be using Java 8.
2. You are using WorldEdit 5 when the stable version is WorldEdit 6.
3. Follow this link to set the generator the for world: https://github.com/IntellectualSites/PlotSquared/wiki/Manual-generator-setting
That should fix the issue.
