### ISSUE TITLE
World border issue  (spigot 1.10.2)

### ISSUE THREAD

**Issue by frizzbee30** [IntellectualSites/PlotSquared#1239]
build #283

Hi, I know it isn't a release build. just to make you aware if your not already.  :)

When I try the latest dev build, it restricts me to my own plot. Any movement outside gives a map border error. i can tp to other plots, but then on moving I am thrown back with an outside border error.

if I roll back to  he current version I'm using (PlotSquared v3.4.2-ce7468e), the world runs as normal.

Thanks

**Comment by frizzbee30** [comment]
I believe this is from build #247  (after testing various builds) adding the border at plotworld setup.
 i can successfully use versions prior to this. it may be others are not having issues on established plotworld, as they do not enable this option, which we like  (in fact, 90% of users are probably totally unaware of it's existence!). I don't know if this is in any way linked to the unknown plots issue and it doesn't recognise those plots (prob not )??

Obviously we can use 3.4.4 builds if we disable the world border function, which we may have to do. I'm presuming totally new worlds wouldn't be affected as the border would be set as detailed!

**Comment by MattBDev** [comment]
I have no comment on the status of this issue right now but I just wanted to point out that using the # sign before a number refers to an issue on here. It may ping someone on accident when it's used so just try to avoid it if possible.

**Comment by frizzbee30** [comment]
Thanks, I din't realise it had that effect and will avoid.

**Comment by MCAlagaesia** [comment]
Same issue on build 288, but it seems a bit more random - I can visit some plots that I don't own. "/p auto" puts me in a plot outside of the world border. I tried disabling and re-enabling the world border feature, however that did not resolve the problem.
Shall I create a new issue? If you want any more information, just ask. :-)

**Comment by frizzbee30** [comment]
we did find that removing the border option did appear to fix on later versions, and if we were to update that would probably be the only way currently. (We have held off updating as holoplots and plot signs seem to be a random issue int he later builds)

**Comment by frizzbee30** [comment]
latest release 3.4.5 _seems_ to fix this in our test server.  Thanks
