### ISSUE TITLE
Error: You're not in a plot. (Plot World not recognized any longer)

### ISSUE THREAD

**Issue by Robulus77** [IntellectualSites/PlotSquared#1241]
Debuug Paste:
http://hastebin.com/jazisukubo
Description:
My Plot2 plugin just doesn't recognize the plotworld any longer. 
THe plot information related to that world is still available in the SQL DB but when being in the plotworld using for example /plot info it keeps telling:" You're not in a plot"
Very strange.

I didn't change any plugins or anything lately on this server.
I tried different versions of Plot2 as well to verify that it is not an issue with this exact version.
Hopefully you can help. :-)

Replication:
Hopefully no one will be able to replicate this....!!

**Comment by manuelgu** [comment]
Please update your version of PlotSquared and see if this is still an error

**Comment by Robulus77** [comment]
I already tried the 3.4.4 build and got the same issue,..but thanks for the advise.
Any other ideas?

**Comment by MattBDev** [comment]
The method should exist but I'll try adding some debugging stuff for it.

**Comment by MattBDev** [comment]
Please produce a debugpaste using the latest version of plotsquared

**Comment by Robulus77** [comment]
Hej, now pastebin info with new version.
http://hastebin.com/axebeyelef
Thanks a lot for your help by the way! ;-)

**Comment by Robulus77** [comment]
Still not working by the way,..;-)

**Comment by GrantSommer** [comment]
Same problem

**Comment by Robulus77** [comment]
I found out that this happens when P2 doesn't recognize the world as a world actually managed by P2.
Non P2 world's have the same behavior when I use the /plot info command there.
Is there anything I can check in regards to world management?

**Comment by mason0958** [comment]
I'm having this problem but even worse. Any new worlds I create are automatically detected as a plot world ;( so I can't augment them.

- love this plugin btw and am looking forward to seeing this issue resolved

**Comment by mason0958** [comment]
This is a BIG problem btw. I would prioritize this one. I can't do anything and my server is at a stand still ;(

**Comment by mason0958** [comment]
# Welcome to this paste
# It is meant to provide us at IntellectualSites with better information about your problem

# We will start with some informational files
links.settings_yml: http://hastebin.com/ocawaqasic
links.worlds_yml: http://hastebin.com/qizinaxoze
links.commands_yml: http://hastebin.com/yuziyapulo
links.latest_log: http://hastebin.com/busiqubone

# Server Information
version.server: 1.10.2
online_mode: com.plotsquared.bukkit.uuid.DefaultUUIDWrapper@753bfbda;true
plugins:
  WorldBorder:
    version: '1.8.5'
    enabled: true
  PlugMan:
    version: '2.1.1'
    enabled: true
  WorldEdit:
    version: 'unknown'
    enabled: true
  NoCheatPlus:
    version: '3.13.7-RC-sMD5NET-b925'
    enabled: true
  Vault:
    version: '1.5.6-b49'
    enabled: true
  PermissionsEx:
    version: '1.23.4'
    enabled: true
  Votifier:
    version: '1.9'
    enabled: true
  testPlugin:
    version: '1.0'
    enabled: true
  WorldGuard:
    version: 'unknown'
    enabled: true
  IPCheck:
    version: '1.2'
    enabled: true
  Essentials:
    version: '2.0.1-b370'
    enabled: true
  PlotSquared:
    version: '3.4.4-SNAPSHOT-cf5d2a5'
    enabled: true
  PerWorldInventory:
    version: '1.7.8'
    enabled: true
  EssentialsSpawn:
    version: '2.0.1-b375'
    enabled: true
  1vs1:
    version: '1.6.7 #217'
    enabled: true
  EssentialsChat:
    version: '2.0.1-b375'
    enabled: true
  Multiverse-Core:
    version: '2.4-b527'
    enabled: true
  GriefPrevention:
    version: '14.8.1'
    enabled: true
  HolographicDisplays:
    version: '2.2'
    enabled: true
  EnjinMinecraftPlugin:
    version: '2.7.7'
    enabled: true
  Multiverse-SignPortals:
    version: '2.4-b523'
    enabled: true
  SignShop:
    version: '2.11.0'
    enabled: true

# YAY! Now, let's see what we can find in your JVM
memory.free: 5481317456
memory.max: 6379536384
java.specification.version: '1.7'
java.vendor: 'Oracle Corporation'
java.version: '1.7.0_101'
os.arch: 'amd64'
os.name: 'Linux'
os.version: '4.4.14-24.50.amzn1.x86_64'

# Okay :D Great. You are now ready to create your bug report!
# You can do so at https://github.com/IntellectualSites/PlotSquared/issues

**Comment by mason0958** [comment]
I've narrowed it down to one thing.  Here's the series of events I'm doing to reproduce this bug:

- Create a server and make a world with multiverse then create augment the world with plot squared
- delete the server and delete plot squared
- Create a new server make a new mv world and then augment the world with plot squared (This doesn't work though) (I get "This world is already a plot squared world")

So there's some database or file somewhere that is corrupt and causing the plugin to think that all worlds are plot worlds.

I'm kinda at a standstill with my server and my players are a bit frustrated. Any help would be appreciated! Thanks.

**Comment by manuelgu** [comment]
Paths were world configuration is saved:

- `plugins/Multiverse-Core/worlds.yml`
- `bukkit.yml` (maybe)
- `plugins/PlotSquared/config/worlds.yml`

**Comment by manuelgu** [comment]
Also, according to your debug paste PlotSquared doesn't even load. You downloaded the wrong version (`-Core`), but you need `-Bukkit`.

**Comment by mason0958** [comment]
Even after deleting all of the 3 files containing world information, the problem still exists. 

I also used the bukkit jar instead. I deleted core.

**Comment by mason0958** [comment]
The problem persists even on new machines with entirely new everything.

**Comment by manuelgu** [comment]
> delete the server and [..] Create a new server

---

> (I get "This world is already a plot squared world")

This is technically not possible. If you wipe all files ("the server") it is **impossible** that the world is already a plotsquared world

**Comment by mason0958** [comment]
Believe me, i thought the same. I tried with different servers and it's STILL saying this.

**Comment by mason0958** [comment]
I've actually tried on 4 different servers now. Including a separate dedicated server a buddy of mine has.

**Comment by mason0958** [comment]
I'm creating a new world (keep in mind I'm doing a random series of numbers and letters). Then i'm doing /plot area create WorldName type=1 terrain=2

and bam (This world is already a plotworld)

**Comment by mason0958** [comment]
Video Proof: [https://youtu.be/59ckq3iv3yI]

**Comment by Robulus77** [comment]
Don't want to be rude, but please create a new thread.
Mine is different from this and hasn't been solved so far.
I will nevertheless Close this one to not mix Things.
@manuelgu I would really appreciate if you could identify a possible reason why this happened. It is a hell lot of work to copy all plots and paste them to a new "working" plot world.
But I would as well like to thank you for the active Support.
Some Things just seem to happen....hopefully only once ;-)
Greetings
Rob
*closed*
