### ISSUE TITLE
Custom Generator asks for name twice

### ISSUE THREAD

**Issue by UltraX3** [IntellectualSites/PlotSquared#1242]
**Debug paste link**:
http://hastebin.com/nikavipega
**Description of the problem:**
As of a couple of versions ago, when generating a plotworld with /plot setup, my custom generator ChunkMarkGen asks for the name twice and then spews out several stacktraces.

Here is the Generator:
[Generator](https://github.com/OneShotMC/ChunkMarkGen)

**How to replicate**:
Compile the generator and create a plotworld with it.

**Comment by MattBDev** [comment]
You need to compile against 3.4.X of the plugin.
