### ISSUE TITLE
Support for END worlds?

### ISSUE THREAD

**Issue by Squawkers13** [IntellectualSites/PlotSquared#1247]
I'm attempting to use the plugin in an END world. I find that it generates, but the exit portal will generate at 0,0 every server restart no matter what you do to it. The dragon hotbar also persists even though it shouldn't be spawning in the first place, and I have to claim and merge a 4x4 area before it appears and I can kill it. (Default plot/road sizes)

When the dragon dies the new 1.9 portal appears just as it shouldn't, and actually functions. Thankfully the chunks it takes me to are plots, but still, these portals shouldn't be generating. 

After a server restart after defeating the dragon, the dragon actually RESPAWNS and the exit portal is respawned deactivated. The new 1.9 portal is nowhere to be found.

However, I tested NETHER and found no issues at all.

Could you add support for END  worlds generating properly?

**Comment by MattBDev** [comment]
Plotworlds are meant to be in the overworld. Anywhere else cannot and will not be supported.
