### ISSUE TITLE
Merge Schematics and Reset Feature Request + Bug

### ISSUE THREAD

**Issue by TheRedMelon** [IntellectualSites/PlotSquared#1248]
I have a plot world that has a default plot schematic and an onclaim schematic.  When you merge the plots, they remove the paths and replace them with what I set as the ground block but at the bottom of the world because I have to do that so I can use the default plot schematic.  I was wondering if you could add a feature that when you merge, it sets the corner plots to a schematic and the middle plots as another schematic.  This or have a schematic that it would replace the path with.

Also, when you /plot reset, it resets to the default plot instead of the claimed plot, you you add an option to reset to the claimed schematic and a separate one for when you delete it.  When you reset or 
delete a plot that has a default plot schematic, it will flash the whole plot for a split second then only end up replacing the chunks that fit in the plot boundaries.  Please fix.

Thanks and I hope you add the suggestion!

**Comment by MattBDev** [comment]
Do not combine feature requests and bugs into one issue.
