### ISSUE TITLE
Plot keeps saying "Height limit for building is 256 blocks."

### ISSUE THREAD

**Issue by thebeastgamer25** [IntellectualSites/PlotSquared#1250]
**Debug paste link**:
http://hastebin.com/acuqayanif
**Description of the problem:**
When ever i try to build, it says "Height limit is 256 blocks"
**How to replicate**:
idk.....
Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment]
You set the height to 265 which is impossible. User error.
