### ISSUE TITLE
PlotSquared wont update when i do /plot update or manually update

### ISSUE THREAD

**Issue by TheMonkeyMaster** [IntellectualSites/PlotSquared#1251]
When i log onto my Creative server world it shows in chat that there is an update for PlotSquared so i type /plot update but it then says that its failed to update. Tells me to manually update the plugin so i do that as well and after restarting the server etc, it still says there is an update available. It even still says the version is 3.4.1 when it should be updating to 1.4.2 or higher. Is there something im doing wrong here or am i being plain stupid

Here is a pastebin of my console
http://pastebin.com/Pttug7nm
Its messy and full of errors from other things i know but im working on them. 

I hope someone can help me and if you need more info on anything then please ask

**Comment by MattBDev** [comment]
Known issue caused by @boy0001 just wait until 3.4.4 is ready and it will eventually fix itself.
