### ISSUE TITLE
immobility wall glitch 2.0 w/(template filled)

### ISSUE THREAD

**Issue by ghost** [IntellectualSites/PlotSquared#1254]
**Description of the problem:**
So I have run into an issue. Upon a player trying to walk onto the road or onto another plot the walls glitch them from continuation. This is a huge issue for my players are spawning on the border block and are unable to move. (more information added on bottom)

**How to replicate**:
I have no idea what this means. From context walk into a wall border perhaps rather than flying over it.

http://hastebin.com/ozokogivik
Latest Version
No way of testing what plugin is doing so. I notice my plugins are in the debug however I did not write code for plotsquared so I have no idea what could be messing with its functionality. There are no bugs in the console plotsqaured related either. My apologize I just figured that latest version would be a given and that if I had a console bug I would have put it here. However for the hastebin that is completely my bad doing.

EDIT: As Operator this Glitch does not occur.

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
