### ISSUE TITLE
Armor Stands + Redstone

### ISSUE THREAD

**Issue by Zaino60** [IntellectualSites/PlotSquared#1255]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/iserudewum
**Description of the problem:**
People can use pistons, redstone and slime blocks to push armor stands outside their plots and in the roads and plots of other players! 
**How to replicate**:
1- Create a Machine like this: https://gyazo.com/871f7e029d96a7f34928d111dddbeeda
2- Operate it and Armor stands will fly outside the plot!
Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] Made sure you're using an updated version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by manuelgu** [comment]
Enable `kill-road-mobs` and `kill-road-vehicles` in your settings.yml and see if it fixes it

**Comment by Zaino60** [comment]
I did, but doesn't that kill the entities in the roads? With this glitch u can even get an armor stand in other player's plots! And I don't think that will also kill those...

**Comment by manuelgu** [comment]
They cross the road before entering another plot, and there they will be killed. Cannot prevent them from leaving a plot.

**Comment by boy0001** [comment]
kill-road-vehicles definitely works for armorstands. Make sure you are using the latest version and have the setting enabled.
