### ISSUE TITLE
All New Multiverse Worlds Recognized as Plotworld

### ISSUE THREAD

**Issue by mason0958** [IntellectualSites/PlotSquared#1256]
**Debug paste link**:
In comments below.

**Description of the problem:**

I can't augment any worlds in my server because all of them say they are already a plot world.

**How to replicate**:
I've narrowed it down to one thing. Here's the series of events I'm doing to reproduce this bug:

1) Create a server
2) make a new NORMAL world with multiverse 
3) Augment the world with plot squared
4) delete the server, and delete plot squared
5) Create a new server
6) make a new mv world and then augment the world with plot squared (doesn't work) (I get "This world is already a plot squared world")

I've replicated this issue on multiple AWS ec2 instances. And a separate dedicated server of a friend of mine.
 
I tried different builds and it worked with all of them. I even tried using craftbukkit instead of spigot... no difference(although i didn't expect one).

***My take on the issue ***
Here's my take: there's some database or file somewhere that is corrupt and causing the plugin to think that all worlds are plot worlds.

**Comment by mason0958** [comment]
links.settings_yml: http://hastebin.com/ocawaqasic
links.worlds_yml: http://hastebin.com/qizinaxoze
links.commands_yml: http://hastebin.com/yuziyapulo
links.latest_log: http://hastebin.com/busiqubone

Server Information

version.server: 1.10.2
online_mode: com.plotsquared.bukkit.uuid.DefaultUUIDWrapper@753bfbd;true
plugins:
WorldBorder:
version: '1.8.5'
enabled: true
PlugMan:
version: '2.1.1'
enabled: true
WorldEdit:
version: 'unknown'
enabled: true
NoCheatPlus:
version: '3.13.7-RC-sMD5NET-b925'
enabled: true
Vault:
version: '1.5.6-b49'
enabled: true
PermissionsEx:
version: '1.23.4'
enabled: true
Votifier:
version: '1.9'
enabled: true
testPlugin:
version: '1.0'
enabled: true
WorldGuard:
version: 'unknown'
enabled: true
IPCheck:
version: '1.2'
enabled: true
Essentials:
version: '2.0.1-b370'
enabled: true
PlotSquared:
version: '3.4.4-SNAPSHOT-cf5d2a5'
enabled: true
PerWorldInventory:
version: '1.7.8'
enabled: true
EssentialsSpawn:
version: '2.0.1-b375'
enabled: true
1vs1:
version: '1.6.7 #217'
enabled: true
EssentialsChat:
version: '2.0.1-b375'
enabled: true
Multiverse-Core:
version: '2.4-b527'
enabled: true
GriefPrevention:
version: '14.8.1'
enabled: true
HolographicDisplays:
version: '2.2'
enabled: true
EnjinMinecraftPlugin:
version: '2.7.7'
enabled: true
Multiverse-SignPortals:
version: '2.4-b523'
enabled: true
SignShop:
version: '2.11.0'
enabled: true

YAY! Now, let's see what we can find in your JVM

memory.free: 5481317456
memory.max: 6379536384
java.specification.version: '1.7'
java.vendor: 'Oracle Corporation'
java.version: '1.7.0_101'
os.arch: 'amd64'
os.name: 'Linux'
os.version: '4.4.14-24.50.amzn1.x86_64'

Okay :D Great. You are now ready to create your bug report!

You can do so at https://github.com/IntellectualSites/PlotSquared/issues

**Comment by mason0958** [comment]
Video of me replicating bug: [https://youtu.be/59ckq3iv3yI](https://youtu.be/59ckq3iv3yI)

**Comment by Sauilitired** [comment]
`IToldYouSo`, really? You might want to consider a nicer attitude, when asking for help.

**Comment by mason0958** [comment]
Seriously? It was a joke. Chill. I appreciate yall's help - I was just proving that I could replicate the bug.

**Comment by mason0958** [comment]
Just a reminder that this is a major bug. I have a few buddies of mine who have the same bug preventing them from developing their server.

**Comment by mason0958** [comment]
Thanks guys for getting to this one. I really appreciate it.

**Comment by mason0958** [comment]
Any1 there?

**Comment by mason0958** [comment]
This bug is still a problem.

**Comment by MattBDev** [comment]
The issue is still open. We aren't ignoring you, we just have lives and other things to do first.

**Comment by mason0958** [comment]
No worries, I was just making sure this doesn't get forgotten. I wish I could help you guys out and greatly appreciate what y'all are doing.

**Comment by boy0001** [comment]
@mason0958 
Sorry, I haven't looked at this issue until now.

With type 1 (augmented), using the area command will only work when the world doesn't exist already. If the world does exist, you need to use plot setup: https://github.com/IntellectualSites/PlotSquared/wiki/TerrainControl

It's only type 2 (partial) that works with `/plot area` and existing worlds.
