### ISSUE TITLE
Bug? and issue.

### ISSUE THREAD

**Issue by Ragatokk** [IntellectualSites/PlotSquared#1257]
I got two issues, one is (possebly) bug.
Players with plots.admin.build.road, plots.admin.destroy.road and plots.admin.interact.road
are able to destroy, but not place blocks on the road.

And by defult you bypass WorldEdit restriction. so players can bug the server by spawning sapplings as they are no longer blacklisted.

**Comment by MattBDev** [comment]
Cannot reproduce and the bug template was not followed
