### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by rErEaT** [IntellectualSites/PlotSquared#1258]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:

http://hastebin.com/zinukazaku

**Description of the problem:**

http://pastebin.com/xcGEDCCd

**How to replicate**:

I dont know why crash I hope u can helps me

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment]
FAWE error. Not caused by plotsquared
