### ISSUE TITLE
Need people to be able to open doors and use buttons on other peoples plots

### ISSUE THREAD

**Issue by grandmen123** [IntellectualSites/PlotSquared#1259]
Using flags hasnt worked nor perms the title says the rest

**Comment by manuelgu** [comment]
Please properly fill out an issue template in the future.

You can apply a default flag `use` for your worlds in the worlds.yml to allow interaction with buttons and doors

`worlds:
  world:
    flags:
      use: 143,77,324`

Add additional IDs if you need.

**Comment by grandmen123** [comment]
Thank you
