### ISSUE TITLE
SpongeAPI

### ISSUE THREAD

**Issue by boy0001** [IntellectualSites/PlotSquared#126]
Side note: We want to hold off on this until the plugin is mostly bug free.

# Goals
 - Ability to port generator to any API
 - Ability to port plot management system to any API

# Updating objects (Step 1)
### org.bukkit.entity.Player
Replace all instances of Player with UUID
 - Updating all the commands will be a pain but must be done
Add utility class to convert UUID to Bukkit player / playername / Sponge player

### org.bukkit.World
Replace as many instances with a String (world name)
Some methods must still use the world object
 - Add a bukkit utility class to change blocks / get chunks etc

### Location
(3D location)
Replace with our own Location object
 - String world
 - int x
 - int y
 - int z

Add a method to convert a Bukkit location to our location object
I'm not sure if yaw or pitch are ever used, but we could have another object which will have this

### Chunk
Same as Location object, replace with our own Chunk object (We can rename it if we decide later with a simple refactor)
 - String world
 - X
 - Z

*I think we might have an object for this already.

### YamlConfiguration
 - We will use some free YAML library instead of Bukkit's

# Initialization (Step 2)
We will want a new Main class which will have all the non Bukkit specific methods etc.
 - We will then move as much as we can away from the PlotMain class (which will be renamed)

We will then want an Interface which the (formerly PlotMain) Bukkit initialization class must implement. The Bukkit initialization class must also tell the (new PlotMain) class that it is enabled. This will trigger all the database stuff (which should be made abstract). 

The Bukkit class is responsible for registering the events and such (more work on it will be done in a later step).

# World generation (Step 3)
This one is going to be a pain. Hopefully sponge has something similar enough to Bukkit's world generation, so we could just use mostly the same base class.

We will want to allow people to do the following:
 - Build a generator that works for Sponge/Bukkit
 - Build a generator that only works for Bukkit or Sponge

# Utils (Step 4)
We will want to make interfaces for all utility classes which have Bukkit specific code.
These utility classes will then need to implement these interfaces

# Linking the utility classes (Step 5)
All these Bukkit utility classes will then be managed by the Bukkit main init class. A method to get each Util must be added to the interface in which the main class implements.

This will mean you can go through PlotMain (the new main class) to use the Utils, or you can go through the Bukkit main class.

# Events (Step 6)
We will have an EventUtil class which will contain core event stuff that must be met by the Bukkit classes:
 - Player move
 - Player change world
 - Player teleport
 - Block place
 - Block destroy
 - Player interact block
 - Player interact entity
 - Entity spawn
+ More

This EventUtil class will be fed parameters (e.g. for player move,  the positions and the UUID) and it will return a boolean value which will indicate if the event needs to be cancelled or not.

# Sponge (Step 7)
Now we will want to start creating counterpart classes for Sponge (or any other implementation)

**Comment by Sauilitired** [comment]
@boy0001 Can this be closed now? Or updated? We really need to get some tickets removed :package:
