### ISSUE TITLE
Merging plots creates Road Bug

### ISSUE THREAD

**Issue by pedroo21** [IntellectualSites/PlotSquared#1260]
Version: 3.4.4
(Issue was already closed but confirmed today as not fixed)

![bug0](http://image.prntscr.com/image/35c9b7839401421dbe14e7778c330a88.png)

**Debug paste link**:
http://hastebin.com/ilutisozum

**Description of the problem:**

**How to replicate**:
**(This is how players explained me, apparently it doesn't happen everytime)**
**(It happened to me on the second time I did it)**
(Do this steps in the same circle direction clock-wise or counter-clock-wise)
1. Claim 4 plots one by one
2. Merge two like this:
![bug4](https://cloud.githubusercontent.com/assets/12183954/16358290/004194b4-3b07-11e6-9718-087bc2262985.png)
3. Merge the big one with a 3rd one
![bug5](https://cloud.githubusercontent.com/assets/12183954/16358296/0e31357a-3b07-11e6-8c2e-685bf8862272.png)
4. This is where the bug generally happens, sometime it fails, sometimes it works. 
4.1 Place yourself facing the remaining road, not pointing to the center, but front
4.2 Merge the big one with the last remaining one
![bug](https://cloud.githubusercontent.com/assets/12183954/16358301/32d73a78-3b07-11e6-8ea9-68079a0accad.png)
After disposing:
![bug8](https://cloud.githubusercontent.com/assets/12183954/16358309/44a75814-3b07-11e6-96af-b739468914a3.png)

**Comment by manuelgu** [comment]
Are you sure you are using a version of 3.4.4 where this fix is already implemented?

http://ci.athion.net/job/PlotSquared/lastSuccessfulBuild/artifact/target/PlotSquared-Bukkit-3.4.4-SNAPSHOT-76bce7c.jar

**Comment by pedroo21** [comment]
Well, you can see in the first image it says: Version: 3.4.4
Unless versioning system was wrong, I was using that snapshot.

My thoughts about this is, it fixed the bug in the middle, but it happened in that relative side. This is critical.

**Comment by manuelgu** [comment]
The reason for my asking is that there are multiple 3.4.4 versions, all with different hashss at the end. Please update to the latest version of 3.4.4 and see if the issue still occurs.

**Comment by pedroo21** [comment]
Thanks. I will proceed to test it again. If in a week there's no answer from me, it should probably be fixed.

**Comment by pedroo21** [comment]
Hello,

While testing it today, this happened: http://prntscr.com/bujigv

I'm not sure of the causes.

**Comment by krusic22** [comment]
I also get this bug in 3.4.5 last release. But I also get this bug (posting it here since it's somewhat related):
https://www.youtube.com/watch?v=1hip13UghB0
The Title spam happens after crossing a road of a merged plot. Unlinking and remerging it dosen't help. The only way I found to "fix" this is with "/plot flag add titles deny"

**Comment by xion87** [comment]
Same here, i add also sometimes merged plots are automatic "unlinking" and need to merged again, it dont generate the roads and destroy the builds, but it still "unlink".

**Comment by MattBDev** [comment]
When I find the time, the next thing I want to do is fix the issues with merged plots.

**Comment by MegaNarwhal** [comment]
Any news on this?

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
