### ISSUE TITLE
Plot worlds messed up

### ISSUE THREAD

**Issue by Typhome** [IntellectualSites/PlotSquared#1262]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/uresanixog

I'll provide another debug when server restart is comming & done (ETA 7 hours).

**Description of the problem:**
I delete plotworld, plotworld2 and test (worlds) with Multiverse command: /mv delete (world name)
Once these worlds are deleted, then I remove these worlds from worlds config (PlotSquared). I'll just reload PlotSquared plugin and /plot debug says "Plot Worlds: pood, cm", so it's all OK, no bugs etc.
I have 2 worlds with PlotSquared generator (named "pood" and "cm").
After all I just restart server and PlotSquared generates worlds named "plotworld2", "plotworld" and "test".
When I teleport to "pood" world and type /plot debug, it says "Plot Worlds: plotworld". There was no plots in "pood" and "cm" worlds etc... only in "plotworld" world. So I have to remove these worlds and from config to fix this problem... every time when I have to restart server... How I can remove permanently "plotworld2", "plotworld" and "test", so plugin won't generate these worlds if these don't exist?

**How to replicate**:
Look at description of the problem.

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] Made sure you're using an updated version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by Sauilitired** [comment]
Are the worlds still in your multiverse files?

**Comment by Typhome** [comment]
It was, but then also deleted these worlds from Multiverse-Core config. After server restart these worlds were again back...
"Plot Worlds: plotworld2"
New debug: http://hastebin.com/ulodidokuz

**Comment by manuelgu** [comment]
To properly delete a plotsquared world you do the following:

- Stop server
- Delete the directory in the root dir of your server
- Remove the entire entry from the `plugins/Multiverse-Core/worlds.yml`
- Remove the entire entry from the `plugins/PlotSquared/config/worlds.yml`
- Start the server again
