### ISSUE TITLE
Huge generation issue.

### ISSUE THREAD

**Issue by zythium** [IntellectualSites/PlotSquared#1265]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/ewunawazol
**Description of the problem:**
Massive areas of land have either stopped generating, or disapeared after generation, //regen just regens it with the same holes in them, each plot is 64x64 so you can see the size of the issue in the screenshots below
https://gyazo.com/3f8b2f81916b486039b787955b2bbc01    <<< map of plot holes
https://gyazo.com/3e0d2d6bd7ff99d9bda6da7c5a5e550b
**How to replicate**:

Make sure you've completed the following steps (put an X between of brackets):
- [] Include `/plot debugpaste`
- [] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] Made sure you're using an updated version of PlotSquared
- [] Made sure the bug/error isn't caused by any other plugin

**Comment by zythium** [comment]
after rebooting the server this happened https://gyazo.com/b3de1ede3c8e01493b4c52b6d0cb18b3

**Comment by manuelgu** [comment]
You are using a *very* outdated version of PlotSquared. Please update.

**Comment by zythium** [comment]
updating has fixed appearance of new holes but the area were it stopped generating is still not fixed, i flew for another 10000 blocks in to areas never loaded and it didnt start generating again,https://gyazo.com/c6d0cc64fc8130b8d7f57e84a72daad8    is there anything i can do to fix this?

**Comment by manuelgu** [comment]
You probably want generate a new plot world.

**Comment by zythium** [comment]
is there a way to import the plots from the old one?
