### ISSUE TITLE
Modded blocks support

### ISSUE THREAD

**Issue by tomcraft** [IntellectualSites/PlotSquared#1266]
Hello, I own a modded server (with modded blocks), I really love your plugin (wich is sooo powerful), but when I tested the schematic feature I was sad to see that modded blocks are not supported :( (they are 'randomly' replaced by others). Please, could you do anythings for this ? :(

**Comment by MattBDev** [comment]
Modded blocks are not supported for optimization and NBT data issues. Eventually modded blocks will be supported but only for the Sponge version of the plugin.

**Comment by tomcraft** [comment]
Can you make an "experimental" option for these who really need this
feature ??? :(

**Comment by MattBDev** [comment]
No.

**Comment by tomcraft** [comment]
Why don't you use WorldEdit to create the "blocks" schematic file and a separated file to store plot informations ? It would allow users to properly save and load their plots when there is modded blocks. Don't you think ?

**Comment by MattBDev** [comment]
Depending on worldedit limits future development of the plugin. This matter is closed and modded blocks will not be supported for Bukkit, Spigot, or any forks of those projects.
