### ISSUE TITLE
Player Names not showing up on the sings

### ISSUE THREAD

**Issue by rajwii64** [IntellectualSites/PlotSquared#1269]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:

**Description of the problem:**
I'm not getting any errors in console but the player names on the sings are not working at all. could someone tell me whats going on?

**How to replicate**:

Make sure you've completed the following steps (put an X between of brackets):
- [] Include `/plot debugpaste`
- [] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] Made sure you're using an updated version of PlotSquared
- [] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment]
Nope, you provided no information so we can't tell you what is going on.
