### ISSUE TITLE
.template

### ISSUE THREAD

**Issue by CptSkiperro** [IntellectualSites/PlotSquared#1272]
How I can create a custom plot? Eg. avalibe Skyblock.template, which has unusual plot's.

**Comment by MattBDev** [comment]
https://github.com/IntellectualSites/PlotSquared/wiki/templates

**Comment by manuelgu** [comment]
That does not answer his question. He is asking for creating templates

**Comment by boy0001** [comment]
Templates are created from EXISTING worlds using the `/plot template` command. The installation page contains information about creating new worlds. See the section about using a schematic in the plot, and roads: https://github.com/IntellectualCrafters/PlotSquared/wiki/Installation#initial-setup
