### ISSUE TITLE
p2 auto??

### ISSUE THREAD

**Issue by timeist** [IntellectualSites/PlotSquared#1273]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/inutesimub
**Description of the problem:**
When doing p2 auto it sends me to a voided plot (nothing in it, completely empty, no grass, no bedrock)
**How to replicate**:
MY best guess is doing /p2 auto
Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)]
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

Another one I have is that plot clear makes the plot a void, or just miss a huge chunk (not a minecraft chunk, i mean it takes a part out of the plot and makes it void)
check
check
check
check

Description: Doing /plot clear makes the plot a void
How to Replicate: doing /plot clear

**Comment by timeist** [comment]
Another one I have is that plot clear makes the plot a void,
check
check
check
check

Description: Doing /plot clear makes the plot a void
How to Replicate: doing /plot clear

**Comment by manuelgu** [comment]
You have three plot worlds, `plotworld`, `plotworld2` and `test`. Properly delete the ones you dont need.

**Comment by MattBDev** [comment]
Also, they are running an outdated version of the plugin.
