### ISSUE TITLE
Mobs Do Not Spawn?

### ISSUE THREAD

**Issue by Kwright02** [IntellectualSites/PlotSquared#1274]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/norezetude
**Description of the problem:**
Mobs Don't Spawn From Spawners In Claimed Plots And I Need them To
**How to replicate**:
Download Latest Version And Create Plot World. Then Place Spawners And they Don't Work
Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by manuelgu** [comment]
You need to enable mob spawning in your worlds.yml

```
worlds:
  YourWorld:
    event:
      spawn:
        egg: true
```
