### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Memermint** [IntellectualSites/PlotSquared#1277]
ERROR]: [PlotSquared] Plugin PlotSquared v3.4.4-SNAPSHOT-30d18c9 has failed to register events for class com.plotsquared.bukkit.listeners.EntitySpawnListener because org/bukkit/event/entity/EntitySpawnEvent does not exist.

Plugin is working but when server starts I see the error in console

**Comment by manuelgu** [comment]
Use Spigot  :)

**Comment by Memermint** [comment]
@manuelgu  Doesn't it work on bukkit? WAT ?

**Comment by manuelgu** [comment]
@MattBDev @boy0001 the event comes from a spigot patch, talked about that on irc

**Comment by MattBDev** [comment]
I'm working on a fix to suppress the error. The error can just be ignored for now. Functionality should be fine.
