### ISSUE TITLE
Teleport delay bug

### ISSUE THREAD

**Issue by PabloMA98** [IntellectualSites/PlotSquared#1282]
**Debug paste link**: http://hastebin.com/vayakojobo

**Description of the problem**: I have configured the teleport delay, and when a player is falling out of the world and type "/plot home", and discconects and connects, he apperars on his plot.

**How to replicate**: Type "/plot home" when you're falling out of the world, for example in the End world, if you disconnect and connect, you will appear in your plot.

- [x] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] Made sure you're using an updated version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by Sauilitired** [comment]
That makes no sense, as
```java
if (player.isOnline()) {
   MainUtil.sendMessage(player, C.TELEPORTED_TO_PLOT);
   player.teleport(location);
}
```

Or am I missing something? 😕

**Comment by manuelgu** [comment]
You actually have to enable it for either `on-login` or `on-death`.

**Comment by MattBDev** [comment]
I am assuming that it is intended for the player to die instead?
