### ISSUE TITLE
[Java 8] UUID Resolver

### ISSUE THREAD

**Issue by Sauilitired** [IntellectualSites/PlotSquared#1284]
Oi! I just played around with some pretty big UUID caching services, and decided to make this little resolver: https://gist.github.com/Sauilitired/ac423bc7a15134073b25535e224f296e

Is this something we'd want to implement? It's not the fastest thing ever, but at least it'd remove some pesky unknown UUIDs + It offers some redundancy, as it would be easy to switch between services

**Comment by boy0001** [comment]
The sql-uuidhandler already does that, though with the mojang API. Doing bulk requests of up to 100 uuids is faster than single requests and less likely to hit any rate limit.

**Comment by Sauilitired** [comment]
@boy0001 How is the rate limit however? I haven't been very active in the Minecraft community, but it was a major concern last time I was around?

**Comment by boy0001** [comment]
It's a huge problem if you do single requests but at 100 each you can do 60,000/10 min
