### ISSUE TITLE
Plot#getAllCorners offset

### ISSUE THREAD

**Issue by manuelgu** [IntellectualSites/PlotSquared#1285]
# Bug report

**Description of the problem:**
The call `Plot#getAllCorners` returns a list of 4 locations which are supposed to be the 4 corner locations of the plot. As shown in the image below, that is not the case.

![](http://i.imgur.com/F4XhJds.png)
Black = Plot border
Red = Corner location
Purple = Plot sign

**How to replicate**:
```java
for (Location corner : plot.getAllCorners()) {
    BukkitUtil.getWorld(plot.getCenter().getWorld()).getBlockAt(corner.getX(), 66, corner.getZ()).setType(Material.BRICK);
}
```

**Comment by MattBDev** [comment]
@manuelgu can you provide the coordinates for the red and purple blocks? (numbering the corners might help for this)

**Comment by manuelgu** [comment]
Purple block (plot sign) is located at -46 65 2.
```
1: "plotsquaredlocation":{"x":-45,"y":0,"z":4,"yaw":0.0,"pitch":0.0,"world":"testworld"}
2: "plotsquaredlocation":{"x":-45,"y":0,"z":46,"yaw":0.0,"pitch":0.0,"world":"testworld"}
3: "plotsquaredlocation":{"x":-3,"y":0,"z":46,"yaw":0.0,"pitch":0.0,"world":"testworld"}
4: "plotsquaredlocation":{"x":-3,"y":0,"z":4,"yaw":0.0,"pitch":0.0,"world":"testworld"}
```

It starts at the bottom right corner and goes counter clock wise.
![](http://i.imgur.com/ZmsKztR.png)

**Comment by MattBDev** [comment]
@manuelgu Thanks 😃

**Comment by boy0001** [comment]
Might be useful: `/2 plotworld;1;3 $ PlotPlayer.getCurrentPlot().getAllCorners()`
