### ISSUE TITLE
Augmented Generation Bug

### ISSUE THREAD

**Issue by coveys** [IntellectualSites/PlotSquared#1287]
Im about to give up on this plugin - ive tried 10 different versions on bukkit, spigot, all different server conditions... Augmented feature for world generation DOES NOT WORK. it will generate the world and once you teleport to the world it will fail to continue generating and crashes. Here is a pastebin of the error. Please fix this or im moving on from this plugin, from reading a different post on here im not the only one experiencing this.

http://pastebin.com/mhJ31XGb

**Comment by MattBDev** [comment]
Did not provide a debug paste. A pastebin of the error is useful but only if we know what version of the plugin is being used and the other plugin/server configurations.

**Comment by coveys** [comment]
bro you have the error now just fix it. a debug paste doesnt work because whenever you enter the world the console freezes and the server crashes

**Comment by coveys** [comment]
and the error doesnt show up until a user enters the world

**Comment by MattBDev** [comment]
@coveys being rude gets you nowhere.
