### ISSUE TITLE
[PSA] Infrastructure Coming Back!

### ISSUE THREAD

**Issue by Sauilitired** [IntellectualSites/PlotSquared#1288]
Oi! Just wanted to inform ya'll about some good shizzle. McVerge (http://mcverge.com/) are sponsoring us with a VPS, and I got some free credits on dynadot = 1 year domain renewal. 

I think this is a great reason to switch the package names over as well ;)

**Comment by manuelgu** [comment]
That means there is going to be a proper repo and build server again? Awesome :+1:

**Comment by Sauilitired** [comment]
Yes, indeed. I had $12 in credit, so I decided to renew plotsquared.com rather than IntellectualSites (because I'm really nice and all). Which means that the package names for all my other projects will make no sense, however 😆 

If it wasn't for the inconvenience of redirecting git connections I would have liked to rename the organization to PlotSquared. Oh well.

**Comment by manuelgu** [comment]
You renamed the org from IntellectualCrafters to IntellectualSites in the past, so wouldn't hurt too much if there was a final renaming ;) Also GitHub redirects links to the correct URI if it was changed, only change required is the upstream of the local git setups.

**Comment by Sauilitired** [comment]
That was literally the most hated change in the history of PlotSquared. I'd rather not do anything like that :p Oh well, confusing organization names are fun, as long as we get rid of that nasty IntellectualCrafters package names.


Fun trivia: IntellectualCrafters was a bilingual Minecraft server ran roughly 3 years ago (Spanish & English), and had the worst custom coded minigames in the history of Minecraft.

**Comment by manuelgu** [comment]
Fun, so lets get rid of the `IntellectualSOMETHING` forever :stuck_out_tongue: 

At the end of the day it's your decision :+1:

**Comment by Sauilitired** [comment]
Status Update:
Got jenkins working. However, it's incredibly slow 😆 Oh well, better than nothing, I suppose.

**Comment by chamunks** [comment]
Well the CI on https://ci.Athion.net is still pretty solid in case the VPS isn't working out.  We also got letsencrypt enabled on the domain as well just so that can be updated in references anywhere as we're going to likely soon be deprecating/redirecting any http to https.

**Comment by Sauilitired** [comment]
Well, this was a disappointment.
