### ISSUE TITLE
Global Chat not working?

### ISSUE THREAD

**Issue by CakeLady** [IntellectualSites/PlotSquared#1289]
http://www.hastebin.com/ujiwebicub
**Description of the problem:**
when we use the /plot chat command you do not toggle between plot chat and global chat, the players stay stuck in plot chat. 
**How to replicate**:
this happens everytime for every player
Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by manuelgu** [comment]
Do you use `/plot chat on` and `/plot chat off`?

**Comment by CakeLady** [comment]
yes i have tried that, and /plot chat toggle, they all say "Enabled plot chat" or "disabled plot chat" but that doesn't actually change anything, chat stays the same

**Comment by NotoriousNemo** [comment]
Please fix this, its been a ongoing issue, the only way to talk is to stand in the roads to global chat, the plot chat is broken

**Comment by boy0001** [comment]
Disabling forced plot chat in the `worlds.yml` should have fixed it.
