### ISSUE TITLE
How to allow a player to get another plot using console

### ISSUE THREAD

**Issue by OrlandoLaCrue** [IntellectualSites/PlotSquared#1290]
How do I do this?

**Comment by Sauilitired** [comment]
https://github.com/IntellectualSites/PlotSquared/wiki/Commands#grant 
`/plot grant add <Player>`

**Comment by OrlandoLaCrue** [comment]
When I do this, it says I am lacking the permission node IN THE CONSOLE

**Comment by AndrewB6** [comment]
I am also having this issue.
