### ISSUE TITLE
Fences Gate are not in good way when debugroadregen

### ISSUE THREAD

**Issue by jewome62** [IntellectualSites/PlotSquared#1291]
**Debug paste link**: http://hastebin.com/rogokedizo (World Edit 6.1.3)
and world config for this world : http://hastebin.com/bidilemugu.sm

**Description of the problem:**
The fences gates aren't copy well for roadregen

**How to replicate**:
First i create schematic with /plot createroadschematic
![2016-08-06_14 51 39](https://cloud.githubusercontent.com/assets/472429/17456854/74ac66ae-5be5-11e6-8361-d578f3517f6e.png)

Secondly I go to another plot (with ugly stone) and make /plot debugroadregen
![2016-08-06_14 51 58](https://cloud.githubusercontent.com/assets/472429/17456855/781d058c-5be5-11e6-9c84-2d179c1569a6.png)

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste` **in head of topic**
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue) **search road or fence keyword**
- [x] Made sure you're using an updated version of PlotSquared **Yes, 3.4.4-Snapshot**
- [x] Made sure the bug/error isn't caused by any other plugin **For a copy problem, maybe World edit ? but it is updated to last version**

**Comment by jewome62** [comment]
I retry with version 3.4.5-SNAPSHOT-c99dd1e and I have same problem

**Comment by jewome62** [comment]
I verify the schematic, and it is good.
I think the block aren't rotate when he create road.

I dont understand, the id block of fence gate are in rotate function (block id : 107) : https://github.com/IntellectualSites/PlotSquared/blob/30d18c917d61c88ab924cbe8234309d56c98cc6c/Core/src/main/java/com/intellectualcrafters/plot/generator/HybridPlotWorld.java#L51

And the stairs are well rotated

**Comment by jewome62** [comment]
I make some test with data id. My reference is the spruce stair because it's work with it !
And they are the same algorythm

![2016-08-06_16 37 13](https://cloud.githubusercontent.com/assets/472429/17457281/20377a6e-5bf4-11e6-85de-a763d64235fd.png)
![2016-08-06_16 37 16](https://cloud.githubusercontent.com/assets/472429/17457282/2156f21c-5bf4-11e6-8ce3-14a730ce6b02.png)
![2016-08-06_16 37 20](https://cloud.githubusercontent.com/assets/472429/17457283/227d2e36-5bf4-11e6-8c9a-a8e35cfafa63.png)
![2016-08-06_16 37 24](https://cloud.githubusercontent.com/assets/472429/17457284/23951130-5bf4-11e6-844f-3f27371148bb.png)

**Comment by jewome62** [comment]
I try a solution, the fences gate work as pumkin or bed : some example
![2016-08-06_16 49 19](https://cloud.githubusercontent.com/assets/472429/17457351/e70745ba-5bf5-11e6-84ce-413558a7ca9c.png)
![2016-08-06_16 49 24](https://cloud.githubusercontent.com/assets/472429/17457352/e81bb7c4-5bf5-11e6-8457-fde99c76ecea.png)
![2016-08-06_16 49 30](https://cloud.githubusercontent.com/assets/472429/17457353/e94489c8-5bf5-11e6-8268-1b99479049c0.png)
![2016-08-06_16 49 34](https://cloud.githubusercontent.com/assets/472429/17457354/eab962e2-5bf5-11e6-981b-fe4a30fe9647.png)

Sorry for this monolog, i like explain all my reflexion

**Comment by jewome62** [comment]
This is the same thing for other plank type

![2016-08-06_16 57 39](https://cloud.githubusercontent.com/assets/472429/17457386/ec2ba6d4-5bf6-11e6-8029-ee6522be21cd.png)
![2016-08-06_16 57 41](https://cloud.githubusercontent.com/assets/472429/17457387/ed3f917a-5bf6-11e6-8fac-6c39798e8b6e.png)
![2016-08-06_16 57 44](https://cloud.githubusercontent.com/assets/472429/17457388/ee6b75fa-5bf6-11e6-964c-7bc562556747.png)
![2016-08-06_16 57 47](https://cloud.githubusercontent.com/assets/472429/17457389/ef8d569c-5bf6-11e6-92eb-3a953c1085f0.png)

**Comment by jewome62** [comment]
The pumpkin are the same problem when i use /plot debugroadregen

I think the algorythm is invalid for this block

**Comment by jewome62** [comment]
Someone can check this ? @boy0001 ?

That just need review, test solution and merge it.

**Comment by jewome62** [comment]
I take some of my time for help this plugin, but I feel that you do not care.
I speak alone

**Comment by EvilOlaf** [comment]
https://github.com/IntellectualSites/PlotSquared/issues/1303

**Comment by boy0001** [comment]
@EvilOlaf 
Not related

@jewome62 
We've been busy. Regarding this issue, you also moved the door ids, I'm guessing you meant for those to be the other fence gate ids? I'll look into fixing the problem, but this commit breaks rotation for those incorrect ids.

**Comment by EvilOlaf** [comment]
@boy0001 The issue itself is not related, that is true. However the discussion about developer response delay fits.

**Comment by jewome62** [comment]
@boy0001 Thanks. Sorry if my fix isn't good

@EvilOlaf I'm no make an up every four days as you example. I wait 2 weeks. And i see others issues most recent has been responded.
