### ISSUE TITLE
Idle thread sleeping in SQLManager

### ISSUE THREAD

**Issue by AlfieC** [IntellectualSites/PlotSquared#1294]
Hey,

After spending some time profiling, I've noticed that SQLManager spends a lot of time sleeping for 50ms - would it not be better to have it in a tasktimer that runs every 50ms? On servers that are running close to 100% CPU it really gets the performance down.

**Comment by YoloxPanda** [comment]
:+1:

**Comment by MattBDev** [comment]
@boy0001 👈

**Comment by AlfieC** [comment]
Any update on this? I restructured it and simply stuck it in an async repeating task and it works perfectly.

**Comment by MattBDev** [comment]
I'm not gonna touch anything in there since @boy0001 has a better understand of that class than I do.

**Comment by boy0001** [comment]
You can't simply stick it in an async repeating task, you'll get concurrency issues for high volume transactions i.e. one task extends into the start of the next one.

Do you have any timings which show the performance concerns?

**Comment by AlfieC** [comment]
That's the thing - it wouldn't show on timings, as timings are for sync operations.

Could it not be averted by having a volatile boolean called `inProgress` and not run if it's true? The save task runs with a 50ms delay anyway so any behavioral changes would be minute.

**Comment by boy0001** [comment]
> That's the thing - it wouldn't show on timings, as timings are for sync operations.

Profile data, whatever. You said specifically that you profiled it and found that the idle thread is causing performance issues?

This still doesn't make any sense for an idle thread to be using cpu, unless it's some ancient hardware or non standard jvm. And creating a new thread every 50ms doesn't seem like a great solution either.

**Comment by boy0001** [comment]
Closing this until more information can be provided.
