### ISSUE TITLE
Plots won't clear!!

### ISSUE THREAD

**Issue by DLDOLPHIN** [IntellectualSites/PlotSquared#1296]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://pastebin.com/NQcF9tP6

Error in console:
http://pastebin.com/W0fXSsb2

**Description of the problem:**
When a player tries to /plot clear, it asks them to /plot confirm, but in doing so, nothing happens.

**How to replicate**:
don't understand??

Make sure you've completed the following steps (put an X between of brackets):
- [X] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] Made sure you're using an updated version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment]
Your plotsquared is out of date.
