### ISSUE TITLE
EchoPet bypass plot deny

### ISSUE THREAD

**Issue by AshourAziz** [IntellectualSites/PlotSquared#1297]
Hello, 

It seems like if you're riding a pet (echopet) and run into a plot that you're denied in you're not kicked and can roam freely while riding the plot. anyway to resolve this?

**Comment by MattBDev** [comment]
There is no fix for this but EchoPet was discontinued anyways.

**Comment by ridalarry** [comment]
not really they made 2 forks for it.

**Comment by MattBDev** [comment]
@ridalarry that's the whole issue. If there are two forks why should we support the forks? They are now two different projects with different code.

**Comment by ridalarry** [comment]
@MattBDev they probably use similar code or placeholders
