### ISSUE TITLE
world edit in a plot

### ISSUE THREAD

**Issue by tryolivier** [IntellectualSites/PlotSquared#1299]
hello :)

I want VIP User can use some worldedit on their plot (ONLY ON THEIR PLOT) but not all commands
only //set copy paste and maybe others
and command don't execute if right or left click is not on plot

I see : 

 plots.worldedit.bypass  Bypass Worldedit restriction 

but what is this ? to have all world edit on the plot ? or for all the server ?
and can we just put only some commands and not all ?

thanks ! :)

**Comment by MattBDev** [comment]
Unless you want users to be able to worldedit other people's plots I don't suggest giving them this permission.

**Comment by tryolivier** [comment]
I don't understand what you say sorry :(

I need that only VIP can use World edit and only in their plot

thanks

**Comment by MattBDev** [comment]
The permission you mentioned is not something you need. What you are looking to do is not something plotsquared related. You should be looking at permission plugins for this.

**Comment by tryolivier** [comment]
I search the permission on http://plotsquared.empcraft.com/commands.html

and I cand put world edit permissions for VIP ( http://wiki.sk89q.com/wiki/WorldEdit/Permissions )

If I put world edit permission they will do worldedit on the every server not only in his plot (for exemple right click on the road or on other plot) ??

thanks to help me :)

**Comment by MattBDev** [comment]
You aren't understanding. You do not need a plotsquared permission for this. This is not plotsquared related. End of story.

**Comment by EvilOlaf** [comment]
To clarify this: Get yourself a permission management plugin (like PermissionsEx) that supports per world permissions. Add permissions for WorldEdit to your VIP group in your plot world. In theory your VIPs are now able to use WorldEdit anywhere in your plot world, but will be restricted by PlotSquared to plots which belong to them/have build privileges.

**Comment by MrBuzzzz** [comment]
This does not work. Players still cannot world-edit in their own plots. Perms have been added for worldedit into LuckPerms for that rank. Seems to be plotsquared related to me. Having a plotsquared.worldedit.bypass command for admins seems to indicate that world edit is restricted somehow.

> > Get yourself a permission management plugin (like PermissionsEx) that supports per world permissions. Add permissions for WorldEdit to your VIP group in your plot world. In theory your VIPs are now able to use WorldEdit anywhere in your plot world, but will be restricted by PlotSquared to plots which belong to them/have build privileges.
