### ISSUE TITLE
An event when a player is removed from a plot

### ISSUE THREAD

**Issue by MisterErwin** [IntellectualSites/PlotSquared#1300]
I was wondering why there is a `PlayerPlotTrustedEvent`, but no `PlayerPlotRemovedEvent`. (or a similar name)

And as a small help: the event [calling part in the Add command](https://github.com/IntellectualSites/PlotSquared/blob/30d18c917d61c88ab924cbe8234309d56c98cc6c/Core/src/main/java/com/intellectualcrafters/plot/commands/Add.java#L74).

And the (not event calling part) in the [Remove command](https://github.com/IntellectualSites/PlotSquared/blob/30d18c917d61c88ab924cbe8234309d56c98cc6c/Core/src/main/java/com/intellectualcrafters/plot/commands/Remove.java#L79).

**Comment by manuelgu** [comment]
Such an event should also store the previous role of that player (trusted, added, denied).

Feel free to PR :)

**Comment by MisterErwin** [comment]
Working on it :)

The PlayerPlotTrustedEvent,... do have an added field. I am using this right now.

By doing so: Is there a special reason behind [this extra check](https://github.com/IntellectualSites/PlotSquared/blob/30d18c917d61c88ab924cbe8234309d56c98cc6c/Core/src/main/java/com/intellectualcrafters/plot/commands/Remove.java#L78)?

(It is not there for the "all-player" check)

**Comment by manuelgu** [comment]
It's there so you can call the respective `removeTrusted`, `removeMember` and `removeDenied`

**Comment by MisterErwin** [comment]
@manuelgu And Line [74](https://github.com/IntellectualSites/PlotSquared/blob/30d18c917d61c88ab924cbe8234309d56c98cc6c/Core/src/main/java/com/intellectualcrafters/plot/commands/Remove.java#L74)? :stuck_out_tongue:

**Comment by manuelgu** [comment]
Because otherwise the players wouldn't be removed. `DBFunc.everyone` is * which means remove all trusted, all members and all denied.

**Comment by MisterErwin** [comment]
Oh.. my bad. I did not look at the source correctly.

**Comment by MisterErwin** [comment]
Just noticed that I forgot to close this, as the PR is merged
