### ISSUE TITLE
Augmented Generation Bug

### ISSUE THREAD

**Issue by coveys** [IntellectualSites/PlotSquared#1303]
Attached is a pastebin, which contains your # **Plot Debugpaste** and a log of my console 

The issue with plot debug paste is, that the console and server has to be responsive for the command to go through. The console once the error starts, forbids the command from going through, spams the console with 1000 lines of error codes, and then crashes the server. This only happens once you generate an augmented world, and then once you try and go onto the world. Please fix this. I Cant provide you any more information then i have through plot debug paste. You have the error and the debugpaste told you everything about what im using and such etc. I cant open my server until you guys fix this, please make your plugin work. This is a very big feature that you guys advertised and I've had 5 other people try doing this and all of them have experienced it themselves. Thank you. 

http://pastebin.com/ABVgwr6z

**Comment by coveys** [comment]
why has no dev responded to this?

**Comment by MattBDev** [comment]
Do we have to respond? We have lives and are busy with things other than just PlotSquared.

**Comment by coveys** [comment]
okay then don't fix your plugin

**Comment by coveys** [comment]
this isnt just an issue im having, its been ignored on your thread recently and i had 4 friends with all different servers try it also and have the same issue.

**Comment by coveys** [comment]
and makes your plugin unusable

**Comment by EvilOlaf** [comment]
It will not help to blame the devs for having a real live. They do this in their free time for no reward whatsoever. Think about it.

**Comment by MattBDev** [comment]
@coveys As you can see by all the other issues in our project, this issue has not even been assigned a priority. I haven't even been able to test or reproduce it yet. The plugin works and is usable but that does not mean there aren't any bugs in the plugin. I suggest you stop attacking us for not fixing this issue.

**Comment by coveys** [comment]
@MattBDev @EvilOlaf Well.. its a very advertised part of your plugin, and Its not just me experiencing this bug. If one third of your plot generation options don't work, how do you consider that plugin useable? I've had 6 people at this point all on different panels and servers try to generate an augmented world like me and have all had the same problem, which is that the second you step onto the world the server becomes unresponsive and crashes. If you're trying to make PlotSquared a simple plugin like PlotMe then thats one thing, but for you to promote that it does all this other stuff when it isn't working and to then be very rude and make me open multiple threads about this after you have a lot of people waiting on this, for example I've invested $750 into this surivival server and can't open it until this is finished because the plots are a big part of it. If none of you don't have time to fix major errors like this on the plugin then don't be a developer for it, I apologize if I've come off as rude its just very frustrating when I saw something as exciting as this augmented world and how promoted it was on your spigot page, and it doesn't even work. I've looked through the code myself, It should be a pretty simple fix, and if you do fix it, ill donate to you guys $50, because as of now i can't even use the plugin, and i have a community of people waiting on this to be fixed. Thank you.

**Comment by Sauilitired** [comment]
@coveys `then be very rude and make me open multiple threads about this`: You are indeed coming off as rude. PlotSquared is an open source, non-profit project, that some of us are working on in our spare time. We ask for nothing in return, besides a little respect. `If none of you don't have time to fix major errors like this on the plugin then don't be a developer for it`, we never asked for you to use the plugin; it is your choice. If you can find an alternative out there, which covers the features you need, and is actively supported, then please - use that instead. If that's not an option, then fix your disastrous attitude and take a god damn chill pill. 

Oh, and by the way, you were never forced to open multiple threads about the issue. You were just impatient.

**Comment by coveys** [comment]
After easily 12-13 hours of time trying to fix this myself and waiting for a month for it to be fixed, you can only expect someone would begin to get a salty attitude about this, because im not the only person who has come to you guys with this error and its been ignored, non-profit or profit you guys are still running something, and im gonna donate to you all big time if this can just be fixed. As i said, i apologize if I've come off as rude, I just would really like to see this plugin do what you guys said it would when promoting it on the plugin forums.

**Comment by MattBDev** [comment]
Can you please provide the entire latest.log file from start to finish? I couldn't find the start of the error in your pastebin or in the debug paste log provided. I did find other errors from other plugins though.

**Comment by boy0001** [comment]
Fixed if using [FAWE](https://www.spigotmc.org/resources/13932/), which I'd recommend using anyway since augmented generation can be somewhat slow.

**Comment by boy0001** [comment]
@coveys 
Latest build can be downloaded from here:
ci.athion.net/job/PlotSquared/

**Comment by coveys** [comment]
@boy0001 Thank you very much for fixing the plugin, i really appreciate it

**Comment by MattBDev** [comment]
@coveys Correction, fixing the _BUG_. The plugin did work.
