### ISSUE TITLE
farewell & greeting spam since updating to the latest dev build

### ISSUE THREAD

**Issue by Platinteufel** [IntellectualSites/PlotSquared#1304]
Since I've updated to the latest dev-build yesterday my players reporting bugs with spammy farewell & greeting messages. It doesn't happen all the time, but fortunately I could just make a video to show you the issue when it happens.

https://youtu.be/7cEcPZv5JXo

I've updated from build 283 to build 311.

**Comment by MattBDev** [comment]
Thanks for the video but build numbers mean nothing. You need to follow the bug reporting template when creating an issue. The debug paste that is required in the template contains information such as bukkit version, minecraft version, and the plotsquared version.
If a `/plots debugpaste` link is not provided soon, I will be closing this issue.

**Comment by Platinteufel** [comment]
Sorry. Here we go: http://hastebin.com/yalutuzame

**Comment by L4BORG** [comment]
We have exactly the same issue but it only happens with merged plots.

Running b#314 (12.8.2016 19:09:05) from http://ci.athion.net/job/PlotSquared/

**Comment by jewome62** [comment]
same with the merged plots

**Comment by MattBDev** [comment]
fixed in  e4408d5
