### ISSUE TITLE
Deny bypass

### ISSUE THREAD

**Issue by ridalarry** [IntellectualSites/PlotSquared#1305]
Using the latest version of plotsquared on 1.10.2 server players can bypass the deny by a glitch if the plot has a stair case made of slabs the player can try to break it and enter the plot like the picture in here
https://gyazo.com/01013932803467b69b12ec2a52eee387
I am uploading a video to youtube and will post it here when the video is uploaded. I will probably post it tomorrow as my wifi is so slow and I need to sleep in a bit.

**Comment by MattBDev** [comment]
Thanks for the report but you haven't provided us any real information for us to work off of. You need to follow the bug reporting template when creating an issue. The debug paste that is required in the template contains information such as bukkit version, minecraft version, and the plotsquared version.
If a `/plots debugpaste` link is not provided soon, I will be closing this issue.

**Comment by ridalarry** [comment]
this is the /plot debugpaste http://hastebin.com/citumoqebi
and this is the video https://www.youtube.com/watch?v=MvdZlYf2jio

**Comment by ridalarry** [comment]
@MattBDev anything about this?

**Comment by Sauilitired** [comment]
@ridalarry Be patient.

**Comment by boy0001** [comment]
They also can't be kicked, since as far as p2 is concerned, they never entered the plot.
