### ISSUE TITLE
Spawn entities on other plots without permission

### ISSUE THREAD

**Issue by manuelgu** [IntellectualSites/PlotSquared#1306]
# Bug report

**Description of the problem:**
You are able to spawn entities when the block you are shift-clicking at while holding a spawn egg is added to the "use" flag even though you are not added, trusted or have admin permission.

**How to replicate**:
Setup your plotworld and allow entity spawning on plots. Add chest (Id: 54) to the use flag. Shift click on this chest with a different player who's neither added nor trusted nor has bypass permission while holding a spawn egg in your hand. You will see that you are able to spawn the entity. This is only the case when you shift click that is added to the use flag, not for any other blocks.

**Comment by MattBDev** [comment]
I need to check where the player interact event is failing.

**Comment by manuelgu** [comment]
Other plugin likely interfering and breaking this, not caused by PlotSquared.
