### ISSUE TITLE
Leaves growing outside of a plot when using /tree

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/PlotSquared#1308]
**Bug report**

**Debug paste link**: http://hastebin.com/emuqudemuf.vala

**Description of the problem:** Players are able to place trees next to slabs which causes the leaves to grow outside of the plot and then they are unable to remove the leaves which are outside the border.

**How to replicate**: Use /tree right next to the border
![2016-08-12_07 31 31](https://cloud.githubusercontent.com/assets/10485646/17614748/bc27aa00-6060-11e6-928e-f422d9bc7c0d.png)

**Comment by MattBDev** [comment]
I am gonna leave this to @boy0001 since he has more experience dealing with worldedit than I do.

**Comment by CoolLord22** [comment]
This only happens for me when I have my /p wea setting enabled. (Correct me if I'm wrong) That allows you to use worldedit even on the roads.
