### ISSUE TITLE
Can't claim any plots at all

### ISSUE THREAD

**Issue by redshadus** [IntellectualSites/PlotSquared#1309]
Hi, for hours long I have been trying to get the plugin to work. This all worked fine in the beginning. But I wanted to put the nodes in myself instead of doing plots.use , I wanted this so I could prevent normal members from using /p auto and accidentally getting a donator plot in another world. So I removed plots.use permission and put all of the permissions in that are needed. The problem is, after that it keeps saying: You can't claim more plots. Now the only way to override this is by being OP. And I don't want that. I already did plots.claim.2 and even higher but nothing worked, I removed both MultiVerse and PlotSquared completely from the server multiple times and nothing. I even remade the entire server but the issue was still not resolved. I had made a completely new groupmanager file and that didn't work either. I asked my staff members to test it and they couldn't claim either. Now I'm not the type of guy that doesn't try anything before he seeks help. I have tried so much. I looked at every related post, every video I could find and every single permission/command I could find. This is my last hope. I'm even okay with it if I HAVE to use plots.use .

**Comment by manuelgu** [comment]
The permission isn't `plots.claim.2` it is `plots.plot.2`. Check the [wiki](https://github.com/IntellectualSites/PlotSquared/wiki) for further information on that.
