### ISSUE TITLE
PlotSquared crashing on biome change

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/PlotSquared#1311]
**Bug report**

**Debug paste link**: http://hastebin.com/emuqudemuf.vala

**Description of the problem:** For some reason biomes seem to be crashing the server, here's a log: http://hastebin.com/ayeyejobaf.coffee I suspect that "window456123 issued server command: //setbiome ice_mountains" triggered it.

**How to replicate**: I'm not quite sure, I guess setting biomes on large plots may be the cause? My plot sizes are 516x516.

**Comment by MattBDev** [comment]
This is a FAWE error.

**Comment by EvilOlaf** [comment]
Probably fawe parts that are included in P^2? In the Debugpaste it seems he is using (a very old version of) AsyncWorldEdit, but not FAWE?

Anyway @SecretlyJealous you may want to get rid of AsyncWorldEdit and grab https://www.spigotmc.org/resources/free-fast-async-worldedit-voxelsniper-%CE%B2eta.13932/

**Comment by MattBDev** [comment]
@EvilOlaf the crash log provided had references to FAWE and we don't use that as a dependency.
