### ISSUE TITLE
Command Alias: New /plot alias not working.

### ISSUE THREAD

**Issue by TagCraftMC** [IntellectualSites/PlotSquared#1314]
**Debug paste link**: http://hastebin.com/odotuqisis

**Description of the problem:** 
I have set up a new alias called 'market'. This alias is not working, either with just /market or /market info (as an example).
I get the generic "not a vaild command" from bukkit.
I am running the latest build of the CI server, thanks!

**How to replicate**:
Add the alias market.
Restart the server.
Try to use the alias.

Make sure you've completed the following steps (put an X between of brackets):
- [X] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] Made sure you're using an updated version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by boy0001** [comment]
Unzip the PlotSquared.jar and modify the plugin.yml to set the main alias (limitation of bukkit)
