### ISSUE TITLE
How to make plot worth money

### ISSUE THREAD

**Issue by ThunderBuddy34** [IntellectualSites/PlotSquared#1315]
So I cant find out how to make plots worth money for players to buy them instead of them getting it for free plz help not high priority Thanks!!!

**Comment by EvilOlaf** [comment]
Either give players the permission to use the `price` flag so they can set their plot "for sale" with the price the player offering.
And/or get to your world config and set  prices for buy/claim and sell.

In both cases economy needs to be activated. You find this setting in your world config as well.

**Comment by MattBDev** [comment]
The settings can be found in both the settings.yml and the worlds.yml
