### ISSUE TITLE
Custom flags default to "null"

### ISSUE THREAD

**Issue by manuelgu** [IntellectualSites/PlotSquared#1316]
# Bug report

**Description of the problem:**
If you register custom flags (as previously described in #1226) their value will be "null" at some point even if the value has never been set or only one custom flag has been set a value.

**How to replicate**:
Can't really replicate. Register custom flags, set values on some plots, restart server, ... At some point it will happen.

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
