### ISSUE TITLE
3.4.5 exception with spigot 1.10.2

### ISSUE THREAD

**Issue by frizzbee30** [IntellectualSites/PlotSquared#1317]
Hi, we are using the latest commit of spigot and just loaded 3.4.5 (release) into live. Although the plugin loads and seems to execute commands, getting and exception message on server boot up?

http://pastebin.com/zXnDb7jR

Thanks

plot debug paste

http://pastebin.com/Rj1TMkh8

**Comment by boy0001** [comment]
Updater is failing

**Comment by boy0001** [comment]
Not a PlotSquared bug, reported the issue to the Spigot Jira: https://hub.spigotmc.org/jira/browse/SPIGOT-2629

Also, (not really related), you should switch from AWE to FAWE.
