### ISSUE TITLE
Modifying item frames on done plots

### ISSUE THREAD

**Issue by manuelgu** [IntellectualSites/PlotSquared#1318]
# Bug report

**Description of the problem:**
You can add, rotate and remove items from plots that are marked as done even if `restrict-building` is enabled. This is only the case when you are the owner of the plot. For others the "plots.admin.destroy.other" permission will be checked first.

**How to replicate**:
Mark a plot as done, make sure your config file is setup correctly and get an account (owner of plot) and try to rotate, add or remove items from the item frame.

``` yaml
done:
  restrict-building: true
```

**Comment by dordsor21** [comment]
If you still have this issue, reopen.

**Comment by manuelgu** [comment]
I still experience this issue

**Comment by MattBDev** [comment]
@Sauilitired that's my bad. I forgot to say the magic words.

**Comment by MattBDev** [comment]
@manuelgu Still an issue? If so, I'll make it high priority.

**Comment by AeSix** [comment]
@MattBDev I can confirm this is still an issue. 

with "restrict-building" set to true,
the plot set to 'done'
added players, and owner can still manipulate items in item frames
This includes removing, rotating and adding.

This is done with P2 4.184 on Paper 1.13.2

It looks like this might be a good place to start looking... but yeah, you know me :P
https://www.spigotmc.org/threads/cancel-removing-items-from-a-itemframe.277837/
