### ISSUE TITLE
Trim not working

### ISSUE THREAD

**Issue by TheChampTF** [IntellectualSites/PlotSquared#1319]
Using command: plot trim all plotworld

For some reason it keep saying it's not a valid world.

As shown below it's right name of the world.

22.08 09:21:31 [Server] INFO plotworld - NORMAL 
22.08 09:21:31 [Server] INFO ====[ Multiverse World List ]==== 
22.08 09:21:26 [Server] INFO That is not a valid world (case sensitive)

**Comment by boy0001** [comment]
`all` is not a valid world world. Use `/plot trim plotworld`
