### ISSUE TITLE
Claim Issue

### ISSUE THREAD

**Issue by Zacory** [IntellectualSites/PlotSquared#1320]
# Bug report template (Follow this template unless you are making a feature request.)

**Debug paste link**: http://hastebin.com/palaguyicu

Description of the problem:
I've never once had this issue before but upon a user typing /plot auto. It takes them to the default world "world" without failure everytime.

We have 2 plot worlds setup:
- Creative
- PlotWorld.

When I type /plot list "user" it says their plots are claimed in the world "plotworld" and upon going to their plot, it takes me to the default "world" instead of plotworld.

**How to replicate**: ?

Make sure you've completed the following steps (put an X between of brackets):
- [X] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] Made sure you're using an updated version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by xion87** [comment]
i confirm the bug, happen with the latest version of plotsquared, using plot auto it claim a claimed plot sometimes, happened 4-5 times to my players.

**Comment by dordsor21** [comment]
still occurring?

**Comment by Sauilitired** [comment]
No response for over a year, closing in good faith.
