### ISSUE TITLE
Error with number usernames

### ISSUE THREAD

**Issue by PabloMA98** [IntellectualSites/PlotSquared#1323]
Players can't visit the plot of a user that names "4444". For example, when they put "/plot visit 4444", appears "That's not a valid number with the range (1, 1)".

I use PlotSquared 3.4.5 in Spigot 1.10.2.

**Comment by manuelgu** [comment]
You can use `/plot visit 4444 1`, which will teleport you to the first plot of the user `4444`

**Comment by MattBDev** [comment]
I am pretty sure the issue here is resolved. Although the lesson should be: don't use only numbers for a user_NAME_
