### ISSUE TITLE
Ideas: Commands

### ISSUE THREAD

**Issue by renzotom** [IntellectualSites/PlotSquared#1324]
Hello, I have idea. You can add:

- [ ] Disabled commands in other plots

- [ ] Enabled commands only in own plot
This is useful, if we want enable command, ex. //tree only in players own plot.

- [ ] Can you add, when player create plot, it execute command?

**Comment by SupremeMortal** [comment]
All of these can probably be achieve by using the Plotsquare API.

**Comment by renzotom** [comment]
I am not developer :/

**Comment by MattBDev** [comment]
> Disabled commands in other plots
There is already the flag "blocked-cmds" for this.
> Enabled commands only in own plot
This sounds like something a permissions plugin would do. If not, it can be easily be made as an add-on instead of being added into the core plugin.
