### ISSUE TITLE
Bug with road generation,.

### ISSUE THREAD

**Issue by zythium** [IntellectualSites/PlotSquared#1325]
# Bug report template (Follow this template unless you are making a feature request.)

**Debug paste link**:
**http://hastebin.com/imevifokib**
**Description of the problem:**
Strange issue with roads, appears to only happen when a plot merges and un merges, or you run debugroadregen, the bottom few layers of the roads and plot walls dont generate, doing debugroadregen makes them apear for about half a second then it returns to its broken state

https://gyazo.com/3f600c478f3a88a54d3f3343a1edfa73
https://gyazo.com/b3e8b2464c636b1f3bc09151def56685
https://gyazo.com/6a8d3db2b79d5fe06f2c3734bcef3a53
**How to replicate**:
see above ^^
Make sure you've completed the following steps (put an X between of brackets):
- [] Include `/plot debugpaste`
- [] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] Made sure you're using an updated version of PlotSquared
- [] Made sure the bug/error isn't caused by any other plugin

**Comment by dordsor21** [comment]
likely redundant issue
