### ISSUE TITLE
Idea: TradeMe support

### ISSUE THREAD

**Issue by renzotom** [IntellectualSites/PlotSquared#1327]
Please, can you add support for TradeMe plugin? https://www.spigotmc.org/resources/trademe-bungeecord-trading-support.7544/

**Comment by boy0001** [comment]
Set the player-interact flag globally:
https://github.com/IntellectualSites/PlotSquared/wiki/Usage:-Plot-flags#default-flags

**Comment by renzotom** [comment]
Yes, but in TradeMe we can set taxes, there is waiting time, it is in GUI and next.... Please

**Comment by boy0001** [comment]
You can use TradeMe if you set the player-interact flag, see the example above for setting a default flag value.

**Comment by renzotom** [comment]
And is there way to use it within click on player? I mean via command.
