### ISSUE TITLE
Error on p reload

### ISSUE THREAD

**Issue by M9GLiquid** [IntellectualSites/PlotSquared#1328]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/wonekewoge

The Error in Console:
http://pastebin.com/0GtgsCzc

**Description of the problem:**
Error on /p reload, same with console

**How to replicate**:
type the command /p reload

Make sure you've completed the following steps (put an X between of brackets):
- [] Include `/plot debugpaste`
- [] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] Made sure you're using an updated version of PlotSquared
- [] Made sure the bug/error isn't caused by any other plugin

**Comment by boy0001** [comment]
You probably broke the config, error doesn't occur normally.

**Comment by manuelgu** [comment]
http://www.yamllint.com/
