### ISSUE TITLE
PlotSquared for 1.8.8 (java 7) 

### ISSUE THREAD

**Issue by loveGhb** [IntellectualSites/PlotSquared#1331]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
https://www.spigotmc.org/threads/plotsquared.29970/page-181#post-1862060

**Description of the problem:**
Get error version Spigot 1.8.8 (java 7) 

**How to replicate**:
The error persists after some time

Make sure you've completed the following steps (put an X between of brackets):
- [] Include `/plot debugpaste`
- [] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] Made sure you're using an updated version of PlotSquared
- [] Made sure the bug/error isn't caused by any other plugin

**Comment by manuelgu** [comment]
attach a debug paste please

**Comment by loveGhb** [comment]
Updated to java 8 error was
