### ISSUE TITLE
2 PlotSquared Worlds At Once

### ISSUE THREAD

**Issue by AquariusCam** [IntellectualSites/PlotSquared#1333]
Hello! I was wondering if there was a way to have 2 plotsquared worlds going at once? I would like to have my default plotworld and my donator plot world. I know how to restrict access, but whenever I make a new plotworld, it focuses on that one and won't work with the previous ones. If you could let me know, I would greatly appreciate it. Thanks!

**Comment by manuelgu** [comment]
You can just create a new world like you would do for the primary (plot setup, mv create, ..) and can then teleport between the worlds with multiverse or essentials warps or any other plugin that allows world teleportation.

Comfiguration is to be found in `worlds.yml`

**Comment by AquariusCam** [comment]
Thank you!

**Comment by L4BORG** [comment]
But can we allow (with permission) per world plot claiming? I think so far permissions are global and you can not restrict players per world with permissions.

**Comment by boy0001** [comment]
@L4BORG 
Most permission plugins support per world permissions.
