### ISSUE TITLE
Grant command

### ISSUE THREAD

**Issue by renzotom** [IntellectualSites/PlotSquared#1334]
Hello, what do Grant command? There isn´t any description :( . And when I have * permissions (I also tried add plots.grant.add or plots.grant.check it still write me,: You are lacking the permission node.... Why?

**Comment by boy0001** [comment]
Fixed the perm check. It can give someone extra plots, though I'm not entirely sure why it's needed when you can do the same with permissions already.

**Comment by renzotom** [comment]
And what about perm add, it also doesn´t work? 

>  It can give someone extra plots, though I'm not entirely sure why it's needed when you can do the same with permissions already.

I don´t know, what you mean.
