### ISSUE TITLE
plot download empty schematic/broken

### ISSUE THREAD

**Issue by dordsor21** [IntellectualSites/PlotSquared#1336]
When using /plot download schematic on very large plots (1000x1000) an empty schematic file is given. Possibly largen max to 20MB as long as errors aren't caused? Also @boy0001 you said you increased to 5MB, that change possibly hasn't been put in place yet?

When using /plot download world an empty schematic is given

@chamunks here's your tag :)

**Comment by boy0001** [comment]
The `http://empcraft.com/fawe` interface was increased to 5mb, try using that.

**Comment by dordsor21** [comment]
fawe interface failed to generate link and using P2 interface causes errors when trying to load into MCEdit as shown below

![image](https://cloud.githubusercontent.com/assets/10080017/18198143/e613c11c-70f2-11e6-809c-5866b1855ab1.png)

**Comment by dordsor21** [comment]
#1131
