### ISSUE TITLE
Mob breeding does not work

### ISSUE THREAD

**Issue by Geranospiza** [IntellectualSites/PlotSquared#1341]
# Bug report template (Follow this template unless you are making a feature request.)

**Debug paste link**:  http://hastebin.com/nukomabexe

**Description of the problem:**  Mob breeding does not work. Used cows and wheat for testing. When I removed the plotsquared plugin, it worked flawlessly. Used Sponge version from this link http://ci.athion.net/job/PlotSquared/ (latest snapshot avaliable).

**How to replicate**: I'm using a FORGE 1.10.2 modded server. Though waterfall (bungeecord). Using spongeforge to link server to waterfall network. Put sponge version from the link above.
Create a plot with this command: /plot area create world:0 type=2 terrain=3 
Claim the plot
Close the server and change the config file worlds.yml from plotsquared folder to match mine from the debug paste link.
Open server.
Try to breed ANYWHERE in the world. Outside and inside the plot.

Make sure you've completed the following steps (put an X between of brackets):
- [X] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] Made sure you're using an updated version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by Geranospiza** [comment]
- Also, anyone can open any chest from inside the plot, only block placing and block breaking are enabled.
So basically, in order to protect my chests I need to use "dirt blocks" as a door, this way, since they cant break them, they cant entry and take the stuff from inside the chests.

- Also, I cannot create another plot that matches X or Z coordinates from another plot, even if it's 3000 blocks away. So, in order to create plots in the world, I need to make them in diagonal from each other.

- Also, if I create a plot and I try to create a plot anywhere else in the world afterwards, an error comes up (from plot plugin). I need to stop the server after creating a plot before creating anotherone.

- Also, plot size does not work, you can only do 42x42 squared plots at height 64. When I do "/plot area create pos1" and then "/plot area create pos2", the border of the plot does not appear until I do "/plot claim" and it's always a 42x42 squared plot at height 64. No matter what.

- Also, since there are no permissions mod for 1.10.2 forge yet (forgeessentials will hopefully be working soon for 1.10.2) non opped users cannot claim or trust anyone. So the only way to fix this is by me being the owner of all the plots and then trusting people individually in their plots. Maybe allow "/plot home" "/plot claim" "/plot trust" "/plot untrust" "/plot deny" "/plot undeny" for all users (without permissions needed). 

- Also, teleport delay does not work. I've changed the value from 0 to 5 and does not make me wait 5 seconds to go back to my plot.

**Comment by MattBDev** [comment]
The Sponge port is NOT feature complete. not everything works and the sponge api has changed a lot.

**Comment by Geranospiza** [comment]
Thanks for the response. I was wondering if you would make any progress with plotsquared towards the use in forge servers anytime soon.

Thank you :D

**Comment by MattBDev** [comment]
Progress will be made but the speed of it is unclear.

**Comment by dordsor21** [comment]
forge and sponge support exists now
