### ISSUE TITLE
New Feature idea? 

### ISSUE THREAD

**Issue by Danielh90** [IntellectualSites/PlotSquared#1342]
Hello I'm was wondering if you guys could put it making your own custom flags? or adding more flags and more in powerful flags. One of the flags I would like to see if a player can allow other players to use a button with out being added to their plot. or a addon plugin maybe could be created?

**Comment by boy0001** [comment]
Set the `use` flag to allow button interaction:
https://github.com/IntellectualSites/PlotSquared/wiki/Usage:-Plot-flags
