### ISSUE TITLE
Cauldron water not restricted

### ISSUE THREAD

**Issue by dordsor21** [IntellectualSites/PlotSquared#1346]
Cauldrons can be filled/drained with water on other people's plots using water bottles/buckets

worlds.yml: http://hastebin.com/femonuzifo
settings.yml: http://hastebin.com/wegacejebi

**Comment by MattBDev** [comment]
Thanks for both those files but we need a '/plots debugpaste'. Please read/follow the template before you post.

**Comment by MattBDev** [comment]
Cannot reproduce.

**Comment by dordsor21** [comment]
@MattBDev cannot reproduce = closed...?

**Comment by dordsor21** [comment]
I found a stray permissions which may have been the problem after some searching, but that's not really a reason to close something...also for this problem a list of plugins and console log/CPU/RAM status would hardly be needed anyway

**Comment by manuelgu** [comment]
Don't complain about the issue being closed for "Cannot reproduce" when you write a text which was more effort to write than properly filling out the issue template?

**Comment by dordsor21** [comment]
I wasn't attacking you...smh. The plugin list on the server I work in is NDA'd, and nothing else from debug paste would be needed anyway.
