### ISSUE TITLE
Item and Block disappear

### ISSUE THREAD

**Issue by azbh111** [IntellectualSites/PlotSquared#1348]
I put some items into a chest.Then I stay away from the chest for a short time and go back.What I put into the chest were disappeared.
I think the block reverted to it's previous state
I put items into a container.Then the container reverts.The items disappears.
I place a block.It reverts.The block disappears.
And so on.

**Comment by MattBDev** [comment]
Not enough information. Did not provide information required from the bug report template. Also, "thinking" is not good enough. It's likely a permissions/client sync problem.
