### ISSUE TITLE
DebugClaimTest throws Error

### ISSUE THREAD

**Issue by Aberzhulan** [IntellectualSites/PlotSquared#1350]
DebugPaste: http://hastebin.com/uwidumonot

I ran a /plot debugclaimtest and got this error: http://pastebin.com/7BPgM5WA, even when setting parameters to "0,1 0,2" or "1 50".

**Comment by MattBDev** [comment]
You should have received a message saying something like the following: "Invalid min/max values. The values are to Plot IDs in the format X;Y where X;Y are the plot coords. The conversion will only check the plots in the selected area."

**Comment by Aberzhulan** [comment]
Ah, that makes sense. The syntax message is a little confusing as to what "PlotID" means. Wasn't sure if it meant the actual Plot ID, from the database or from in-game or what.

That worked wonderfully, thank you. :)
