### ISSUE TITLE
Reloading plugins that add flags causes data corruption

### ISSUE THREAD

**Issue by MisterErwin** [IntellectualSites/PlotSquared#1351]
(I know, you should never reload plugins, but well...)
When reloading only a plugin which adds external Flags to PS, some flags corrupt their data.

When we have the following data:
> Flags: test-flag: [a,b]   

The size is 2

And after reloading the plugin which adds __test-flag__
>Flags: test-flag [[a-b]]

The size is 1

(test-flag is a StringListFlag in this case)

[Line 172 of Flags](https://github.com/IntellectualSites/PlotSquared/blob/a95b68b73c87c465a6294d4e30cd47ee68f6fc76/Core/src/main/java/com/intellectualcrafters/plot/flag/Flags.java#L172) appears to be the cause for that
`flag.parseValue("" + remove)`

I am unsure if a fix is reasonable, but I will make a PR nonetheless.

P.S.: I am too lazy to add the debugpaste/version, as it's visible in the (at this time) last commit `a95b68b73c87c465a6294d4e30cd47ee68f6fc76`

**Comment by MisterErwin** [comment]
See PR #1352

**Comment by boy0001** [comment]
I'll merge with some modifications.
