### ISSUE TITLE
Bug with road generating

### ISSUE THREAD

**Issue by Gumpah** [IntellectualSites/PlotSquared#1354]
**Description of the problem:**
I want to change the roads of my map but, have a look:
The second picture is the result of the command "/plot debugroadregen"
[How it should be](http://image.noelshack.com/fichiers/2016/37/1473840244-bug2.png)
[Issue](http://image.noelshack.com/fichiers/2016/37/1473840239-bug1.png)

**Comment by MattBDev** [comment]
Not enough information provided.

**Comment by boy0001** [comment]
You didn't build the whole road.
