### ISSUE TITLE
/plot auto no longer working 

### ISSUE THREAD

**Issue by xDacon** [IntellectualSites/PlotSquared#1357]
**Debug Paste**: http://hastebin.com/recigijuti

**Description of the problem:**

When trying to claim a plot with /plot auto, this error is given:
http://image.prntscr.com/image/60d2e75e26db44cf8f4fe7daa252f5e5.png

Error in console:  http://hastebin.com/imozebevak.md

Also had this error spammed earlier today: http://hastebin.com/owacupokuv.vbs

**How to replicate**:

Not sure

**Comment by manuelgu** [comment]
Probably wrong permission setup.

Make sure the player **only** has `plots.plot.#` # being replaced with the amount of plots the user may have.

**Comment by xDacon** [comment]
I'm trying to do /plot auto on my account, which has * permission and is opped - same error. Also we haven't changed anything to permissions in a couple months

**Comment by xDacon** [comment]
Issue resolved, corrupted chunks causing it
