### ISSUE TITLE
Enchancement: Plot Chat

### ISSUE THREAD

**Issue by ItsAZZA** [IntellectualSites/PlotSquared#1359]
This enhancement is about the Plot Chat feature.

There should be an option to enable colors in the Plot Chat for players. Maybe this could be a separate permission, or perhaps a config option. This would allow players to chat in color, even when using the Plot Chat. At the moment, when you type in a color code, it shows up as text in plot chat.

Also, the Plot Chat spying messages should be configurable. Instead of "playername blah blah" it could be changed to something like "[PlotChat] playername blah blah", for example. This could be its own section in the translation files.

**Comment by oasis9** [comment]
Not only that, but also check if the event has been cancelled before processing it. For some reason, the chat event has ignoreCancelled set to true in its eventhandler annotation. I went ahead and removed it for my own purposes, however this didn't fix the issue, even though I was cancelling at priority LOWEST, while P2's event looks like this: `@EventHandler(priority = EventPriority.LOW, ignoreCancelled = true)
    public void onChat(AsyncPlayerChatEvent event) {`
I suggest adding `if (event.isCancelled()) return;` to the top of the method body.
