### ISSUE TITLE
Redstone does not work in merged plots

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#1362]
https://github.com/IntellectualSites/PlotSquared/commit/9e5af7a64242ed05466c0be2fc8f8c64d255a2e9

this didnt fix it

**Comment by boy0001** [comment]
I tested and it fixed it for me. What specifically isn't working about redstone in merged plots?

It should be disabled as soon as no players are inside the plot or the owner is offline according to your configuration.

**Comment by PhanaticD** [comment]
repeaters arent working

**Comment by MattBDev** [comment]
I feel like the change in 1.11 with redstone being updated might help resolve this issue but we won't know until it is released.

**Comment by TNTUP** [comment]
Reproduced it, @PhanaticD have you tried the redstone in someone else plot? The trust list in the player's plot is empty causes this, if you trust a player, the redstone works (repeater). Done with P^2 3.5.0 

But the issue I found is not in merged plots, have you checked if the merged plots has trusted players?

**Comment by dordsor21** [comment]
wasn't reproduced with merged plots^
