### ISSUE TITLE
Method get.Owners not found / Events do not perform

### ISSUE THREAD

**Issue by GlobooX** [IntellectualSites/PlotSquared#1368]
**Description of the problem:**
Bug1: I use the API to build an addition to the PlotSquared.
Event "on plot delete" and "a plot clear" do not perform despite the fact that the compilation is not an error.

Bug2: 
Method get.Owners not found despite the fact that the compilation is not an error.
I can use this method in practice but in game i have errors.

Here is console error: http://pastebin.com/psTbXx0d
Here is java code: http://pastebin.com/kxmUXfW4

**Version**:
3.4.5v

My english broken...

**Comment by MattBDev** [comment]
The method returns a `Set<UUID>` not a `HashSet<UUID>`

**Comment by MattBDev** [comment]
I don't understand what you are asking. I have bene able to make an addon fine using events. The other issue, you should make sure you are importing the `Set` class too. `getOwners()` returns a `Set` and the error mentions a `HashSet`

**Comment by piter909** [comment]
He probably wants to say that PlotDeleteEvent and PlotClearEvent are not being called when plot have been deleted on cleared.
I have tested PlotDeleteEvent and it does not work. On plot delete, listener does nothing.

Also, method plot.getOwners() throws an exception - same as in his code.

Hope it will be fixed.
