### ISSUE TITLE
Is this possible?

### ISSUE THREAD

**Issue by Wearwolfy** [IntellectualSites/PlotSquared#1371]
How do i make my plots like this? Is this possible i can't figure out how to do it? plz help 
![2016-09-23_21 01 39](https://cloud.githubusercontent.com/assets/21149078/18807612/11dc97dc-824c-11e6-8733-08824323fe26.png)
I tried doing it with roadschematic but then only the roads are copied? is there a way to do it like this??

**Comment by dordsor21** [comment]
It _is_ called a road schematic for a reason

**Comment by Wearwolfy** [comment]
Ik that but i am asking for advise to do it like this and i was not asking for rude people to comment on this

**Comment by MattBDev** [comment]
This really isn't a discussion forum. This is for bug reports and sometimes questions. I'll leave this up for now but in the future you can't do this.

**Comment by boy0001** [comment]
https://github.com/IntellectualSites/PlotSquared/wiki/Installation#adding-road-schematics

**Comment by Wearwolfy** [comment]
This isn't a discusion either if this is not possible then i would like to suggest this as a feature
