### ISSUE TITLE
Denied plots and elytra

### ISSUE THREAD

**Issue by Autom3** [IntellectualSites/PlotSquared#1372]
**Description of the problem:** Players can get inside of denied plots by flying into the "wall" with elytra.

**How to replicate**: Equip elytra, fly into a denied plot, log out right before you get pushed back. Then fly up (creative mode), spam space to engage elytra and log out when you advance a bit.

Potential fix: whenever a person logs in, run the method that pushes them out of potential denied plots.

**Comment by manuelgu** [comment]
Already happening https://github.com/IntellectualSites/PlotSquared/blob/master/Bukkit/src/main/java/com/plotsquared/bukkit/listeners/PlayerEvents.java#L443

**Comment by pmf-berlin** [comment]
Same if you haven an Animal on your had (other plugin) and sneak.

**Comment by dordsor21** [comment]
still an issue?

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
