### ISSUE TITLE
Plot title does not fade out of existence smoothly.

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/PlotSquared#1376]
PlotSquared dev 357
FAWE dev 332
Paper dev 881 (Spigot 1.10.2)

Settings
http://paste.ubuntu.com/23253696/

Plot titles do not fade out of existence. They appear slowly / transition in smoothly but then cut off abruptly when entering an owned plot region. Shouldn't the fade-out match the fade-in so the appearance of the title display is smooth?

**Comment by MattBDev** [comment]
I'm not sure what you mean by "PlotSquared dev 357" If you gave us a `/plots debugpaste` it would help.

**Comment by mibby** [comment]
From the jenkins..?
http://ci.athion.net/job/PlotSquared/

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
