### ISSUE TITLE
Missing permissions in plugin.yml.

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/PlotSquared#1379]
PlotSquared dev 357
FAWE dev 332
Paper dev 881 (Spigot 1.10.2)
PermissionsEx dev 1.23.5-SNAPSHOT

I gave a group the permission nodes ```plots.admin.interact.other```,  ```plots.admin.build.road```, ```plots.admin.destroy.road```, and ```plots.admin.interact.road``` but they were unable to place down items in the road area. Only until I gave them wildcard permissions were they able to build and destroy in the road area. 

```
plots.admin.build.*
plots.admin.interact.*
plots.admin.destroy.*
```

I suspect this is because there are various permission nodes missing from the plugin.yml itself, thus being unable to register / hook. 
https://github.com/IntellectualSites/PlotSquared/blob/177b33154fb39285ea36daf1920f06baf9cd2346/Bukkit/src/main/resources/plugin.yml

Cross referencing it with the wiki perms list. Many not included.
https://github.com/IntellectualSites/PlotSquared/wiki/Commands-and-Permissions#admin-bypass-permissions

**Comment by boy0001** [comment]
`plots.admin.interact.other` It should instead be `plots.admin.interact.road`

**Comment by mibby** [comment]
I included both permissions but it did not work. Again, suspect because the perms are missing from the plugin.yml.

**Comment by boy0001** [comment]
It's not related to the plugin.yml, adding them would do nothing.

What permission did it say they lacked?

**Comment by mibby** [comment]
Directly from the player.

```
[17:01:56] [Async Chat Thread - #0/INFO]: player: plots.admin.interact.road
```

Yet the group was given all of these.
```
plots.admin.interact.other
plots.admin.build.road
plots.admin.destroy.road
plots.admin.interact.road
```

**Comment by boy0001** [comment]
If you had permission caching enabled, they might need to use a plot command or relog for changes to take effect.
