### ISSUE TITLE
Merging plots using the bridge template cuts off the bridge and leaves blocks leftover.

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/PlotSquared#1380]
PlotSquared dev 357
FAWE dev 332
Paper dev 881 (Spigot 1.10.2)

Settings
http://paste.ubuntu.com/23253696/

Using the bridge template on a fresh new world; merging plots breaks the bridge itself and leaves odd block placement.
![link](http://i.imgur.com/m0kiL2V.jpg)

**Comment by boy0001** [comment]
That's normal.
