### ISSUE TITLE
Changed world of primary and support for shops

### ISSUE THREAD

**Issue by rodnicho** [IntellectualSites/PlotSquared#1384]
Hello how to change the destination of the "/ p auto", it sends players on "plotworld" I would send my players on the "Plot"?

This is what flag for players to use the shops?

**Comment by MattBDev** [comment]
https://github.com/IntellectualSites/PlotSquared/wiki/ChestShop-Compatibility

**Comment by rodnicho** [comment]
Thank you to give me her but the flag was writing in-game so that the player can buy or sell, I added his in the config and mainte ago that I who can buy or sell.

If I was you called me, must ecri of in-game as the next "/ p flag add 63 true"?
