### ISSUE TITLE
[ Question ] I want to sell my plot for other players can buy ?

### ISSUE THREAD

**Issue by jomjonejame** [IntellectualSites/PlotSquared#1385]
[ Question ] I want to sell my plot for other players can buy ?

i must use command ??

**Comment by EvilOlaf** [comment]
Set price flag. This will allow others to use plot buy.

**Comment by jomjonejame** [comment]
@EvilOlaf  Thank you for answer.

**I have one more question.**
I want to give players open doors But not add Trusted and Members.
I want [ /plot flag set use allow ] but it's not work

When others players open the door in my plot it alerts [P2] Have an admin set the flag: use

**Comment by EvilOlaf** [comment]
`use` is does not need booleon. It needs an array.
Add the item ids of stuff you want all players on your plot to can interact with.

For doors and shop signs this would be `63,68,193,194,195,196,197,64`

**Comment by jomjonejame** [comment]
add item ids to ???

**Comment by MattBDev** [comment]
You add it to the use flag

**Comment by jomjonejame** [comment]
@MattBDev  Oh Thank you

@EvilOlaf  Thank you
