### ISSUE TITLE
PlotSquared v3.4.6-SNAPSHOT-5978c9c generated an exception while executing task 1965

### ISSUE THREAD

**Issue by maxlehot1234** [IntellectualSites/PlotSquared#1386]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/ilodorovih

**Description of the problem:**
When I join the server with a completely new world, I see this in the console: http://pastebin.com/ky1JHCUe

Make sure you've completed the following steps (put an X between of brackets):
- [X] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] Made sure you're using an updated version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by maxlehot1234** [comment]
@MattBDev Everytime a player join the server, I have this issue...

**Comment by MattBDev** [comment]
@maxlehot1234 thx for the info.

**Comment by maxlehot1234** [comment]
@MattBDev No problems, it's just weird that I see this in the console, everything works fine, but this spam the console for no reason :P

**Comment by maxlehot1234** [comment]
@MattBDev Any ETA when the fix was release? Because with 20-30 players all the time that leave and newone join simply spam the console... Thganks in advance

**Comment by MattBDev** [comment]
No ETA but a tip for the future, never ask a dev for an ETA. It makes them cringe.

**Comment by maxlehot1234** [comment]
Ok :P Because it is bad to have this spamming my console all the day. My logs file become really big, cause of this error at each player join :(
