### ISSUE TITLE
PlotSquared - Limit plots on each world per rank.

### ISSUE THREAD

**Issue by Lobsang1** [IntellectualSites/PlotSquared#1387]
Hi!
Got problem because I'm trying to configurate my creative server and I don't know how exacly PlotSquared works. 
I'm creating few worlds for different ranks:
- rank1 got access to main world1 with small plots
-rank2 got access to world1 and world2 with small and medium plot
etc.
My main problem is how to write in settings.yml to limit plots for rank1 to 1 plot at beggining and when he reach rank2 he will get access to world2 and he should get new limit of another for plot there. 
For example player with rank2 can have 2 plots in world1 and 1 plot in world2 - how to make it in premissionsex or plugin settings?

**Comment by SupremeMortal** [comment]
This is a problem with your permissions and not this actual plugin. You should try searching up about "per world permissions"

**Comment by MattBDev** [comment]
We are not a permissions plugin. This is done with permissions.
