### ISSUE TITLE
PlotSquared - claiming more plots after finishing them.

### ISSUE THREAD

**Issue by Lobsang1** [IntellectualSites/PlotSquared#1388]
Got problem with PlotSquared when we test if we configurate it and claim 5 of 5 plots after /plot done anyone couldnt claim any more plots. I know its because this plots still owned by one player but is there any way to done plot and allow player to claim more after finishing them, for example I finished plot writing plot done and it still shows its my but i can claim another one to build more.

**Comment by SupremeMortal** [comment]
There is an option in the config along the lines of "counts-towards-limit" Set this to false.
