### ISSUE TITLE
[Nukkit] Plot walls destroyed

### ISSUE THREAD

**Issue by SupremeMortal** [IntellectualSites/PlotSquared#1389]
**Debug paste link**:
http://hastebin.com/mabiveyaho
**Description of the problem:**
Nukkit
Blocks which have physics such as Pistons are able to move blocks out the plot or water destroy carpet.

**How to replicate**: 
Install PlotSquared on Nukkit and place water next to carpet plot walls

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report (https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment]
We cannot fix pistons moving plot borders. unfortunately Nukkit does not have an event we can use to stop pistons.

**Comment by AGTInformous** [comment]
Can't you set the walls as "unmovable" so you can't move them? Like obsidian

**Comment by MattBDev** [comment]
@AGTInformous I believe that was possible in Forge. (Not sure if it still is) Forge and Nukkit are EXTREMELY different.

**Comment by MattBDev** [comment]
Pistons aren't even in Nukkit yet so this issue is not possible.

**Comment by SupremeMortal** [comment]
"or water"

**Comment by MattBDev** [comment]
@SupremeMortal I'll re-open and look at water stuff.

**Comment by NycuRO** [comment]
so fixed?

**Comment by dordsor21** [comment]
If you still have this issue, reopen.

**Comment by NycuRO** [comment]
3 years later gg
