### ISSUE TITLE
NPE ExpireManager.handleJoin

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#1390]
using dev build 368 and paperspigot 1.10.2

http://pastebin.com/raw/xv4dRgBa

**Comment by PhanaticD** [comment]
does not occur prior to this commit https://github.com/IntellectualSites/PlotSquared/commit/5d3e0965011c3c91fb440db54ec5c98224002a50

**Comment by MattBDev** [comment]
Duplicate of #1386 which I fixed a little bit before you submitted this.

**Comment by PhanaticD** [comment]
I made this report after trying your fix, please re-open

**Comment by MattBDev** [comment]
Use the commit number which is found towards the end of the plugin version in the future. I can't keep track of build numbers that constantly change.

**Comment by maxlehot1234** [comment]
I confirm, Same error with the commit: PlotSquared-Bukkit-3.4.6-SNAPSHOT-a05fd2d

**Comment by maxlehot1234** [comment]
Same issue again with commit:
PlotSquared v3.4.6-SNAPSHOT-e594227

Are you able toi fix the issue please? It spam my console each time a player join the server.

Thanks again

@MattBDev

**Comment by maxlehot1234** [comment]
Any update for this? 10 days later, no fix but multiples updates?
PlotSquared v3.4.6-SNAPSHOT-93c4854
