### ISSUE TITLE
Cluster and Idea

### ISSUE THREAD

**Issue by AgentCortez** [IntellectualSites/PlotSquared#1393]
I execute /plot cluster regen name and nothing happens except for the plugin showing a valid list of subcommands. On the wiki it says it's a valid command though.

I also would request a feature where this would link into Worldedit and we can select a plot to make a plot in an existing world. This would help greatly since I don't want to have to regenerate a flat plot world. It would also help since I can't get clustering to work right at all. Is there any way to define an area where the cluster spawns and not just randomly?

**Comment by boy0001** [comment]
https://github.com/IntellectualSites/PlotSquared/wiki/Augmented-Plot-Worlds
