### ISSUE TITLE
Can't create Skyblock template in Nukkit

### ISSUE THREAD

**Issue by Adam1609** [IntellectualSites/PlotSquared#1395]
# Bug report template (Follow this template unless you are making a feature request.)

**Debug paste link**:
No debug!
**Description of the problem:**
Skyblock can't be generated in Nukkit, it turned out as normal world
**How to replicate**:
Just use /plot template import skyblock skyblock
Make sure you've completed the following steps (put an X between of brackets):
- [] Include `/plot debugpaste`
- [] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment]
If you don't provide a '/plots debugpaste' link it limits our ability to help resolve issues. Please don't just write "no debug".

**Comment by NycuRO** [comment]
@Adam1609 You can fix that man. Schematics have buggy blocks ( rail and other ). For fix ,you need paste schematics , fix blocks and add new schematics :)
Templates is for pc, not for pocket edition man. :) You need fix blocks. For me,i'm edited bridge and work perfectly :)
