### ISSUE TITLE
Too long server start

### ISSUE THREAD

**Issue by Sitmobedaf** [IntellectualSites/PlotSquared#1396]
Look time

http://pastebin.com/L8DCNisq

**Comment by dordsor21** [comment]
Doubt this has anything to do with P2. Check all your plugin's versions against the version of spigot/bukkit.

**Comment by EvilOlaf** [comment]
Also missing plot debugpaste

**Comment by dordsor21** [comment]
can't use debugpaste if the server never actually starts, which seems to be the case

**Comment by MattBDev** [comment]
It doesn't seem like plotsquared is an issue.
