### ISSUE TITLE
worldedit/voxel permission after deleting plot

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/PlotSquared#1399]
PlotSquared dev 370
FAWE dev 347
Paper dev 889 (Spigot 1.10.2)

Settings
http://paste.ubuntu.com/23253696/

FAWE Config
http://paste.ubuntu.com/23338603/

Buying a plot and then deleting it still allows you to use worldedit/voxel operations in that plot with restriction enabled, despite not being the owner of it. Allowed region cache not cleared when the plot is deleted?

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
