### ISSUE TITLE
PlotSquared problem with the plugin to create a world with my own schematics

### ISSUE THREAD

**Issue by JuanDouCore** [IntellectualSites/PlotSquared#1401]
Hello mate! Gladly, my name is John, good as I really come for some little problems I have with your plugin PlotSquared, I explain I want to create a world of plots with the plot, the intersection and sideroad to my taste, which is what I did because believes all identical in a flat world the three things and keep a schematic for everyone, because then I'll plugins / PlotSquared / Schematics / GEN_ROAD_SCHEMATIC / create a folder named world called plots entered it and move the three schematics to her, when I go to the game and puts / mv create regular plots -g PlotSquared, a world clearly is generated with the schematics I got all messed up but do not go as they should go and do not understand how to fix that, if I could please help. (It is something like the bridge template that you give option to download)

Here you can download the three schematics so prove it: http://www.mediafire.com/file/aegmvvb8d1kq9od/schematics.rar

**Comment by boy0001** [comment]
Use the command `/plot createroadschematic` to have PlotSquared create the schematics for you in the correct orientation.

See here:
https://github.com/IntellectualSites/PlotSquared/wiki/Installation#adding-road-schematics
