### ISSUE TITLE
Problem with world generation

### ISSUE THREAD

**Issue by stuvanya** [IntellectualSites/PlotSquared#1402]
# Bug report template (Follow this template unless you are making a feature request.)

**Debug paste link**:
http://hastebin.com/ufuvakisol

**Description of the problem:**
http://imgur.com/a/QMdAW
It happens just when i started server with not generated world

**How to replicate**:

Make sure you've completed the following steps (put an X between of brackets):
- [X] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] Made sure you're using an updated version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by RedstoneFuture** [comment]
Currently the world generator is correctly.
