### ISSUE TITLE
Random holes

### ISSUE THREAD

**Issue by CrabMustard** [IntellectualSites/PlotSquared#1403]
(nothing in console)

These holes keep appearing in the same places in various plot worlds. 
[Pic](https://i.gyazo.com/b50c934a7b8a6fb41c1bcb61bd70d397.jpg)

my [debugpaste](http://hastebin.com/sogebasipa)

I am confident this is a PlotSquared issue, as this only happens in plot worlds.

**Comment by dordsor21** [comment]
can confirm this is an issue, has happened to me on occasion

**Comment by Sauilitired** [comment]
Because of @dordsor21's label spam, I'm going to assume that this cannot be replicated in newer versions of the plugin.
