### ISSUE TITLE
Roads do not support Forge blocks.

### ISSUE THREAD

**Issue by Flenix** [IntellectualSites/PlotSquared#1405]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/vecezasare

**Description of the problem:**
As it says on the tin- roads do not support Forge blocks. I believe this is a problem with how PS reads the schematics, as mods that create schematics such as WorldEdit will load and paste the blocks just fine. I also tried creating the schematic using worldedit, and got the same results when loading it as a road.

Image:
http://ctrlv.in/869904

It is worth noting that weirdly, the yellow triangle blocks are a forge block - but simply aren't the RIGHT block. Also, none of the blocks used are special in any way - they're standard blocks, some have metadata some don't.

**How to replicate**:
Try and create and then generate a road using Forge mod blocks.

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin (WorldEdit pastes them fine)

**Comment by MattBDev** [comment]
Read the comment listed here:
https://github.com/IntellectualSites/PlotSquared/blob/master/Bukkit/src/main/java/com/plotsquared/bukkit/util/BukkitSchematicHandler.java#L277-L287

**Comment by Flenix** [comment]
Ah, makes sense - so if I simply fork it and uncomment that little snippet, will forge blocks work then? I'm happy to take a small performance hit, especially as none of the blocks being used have NBT :)

Sent from my iPhone

On 24 Oct 2016, at 19:47, Matt <notifications@github.com<mailto:notifications@github.com>> wrote:


Read the comment listed here:
https://github.com/IntellectualSites/PlotSquared/blob/master/Bukkit/src/main/java/com/plotsquared/bukkit/util/BukkitSchematicHandler.java#L277-L287

-

**Comment by MattBDev** [comment]
@Flenix I can't say if that code would fix it or not but feel free to try it and let me know. If it does, I can do some of my own testing and reopen this for others.

**Comment by Flenix** [comment]
Alright, if I get it working I'll commit in a default-off config option? That way people who want it can turn it on without having to edit things other than a config :D

Having some trouble installing right now though. I've only ever used gradle for Forge projects which includes a .bat file for Windows but this doesn't have one, I tried throwing it on my ubuntu server but it won't run there either. The Maven pom can't find Spigot either... any ideas? :P

**Comment by MattBDev** [comment]
Odd. I thought I generated the wrapper. I'll fix that right now so you can test.
