### ISSUE TITLE
Problem with blocks on the plots

### ISSUE THREAD

**Issue by JuanDouCore** [IntellectualSites/PlotSquared#1406]
Hello friends! Well, I just had a problem with the plugin, it was trying to work everything right in the plots and I find that in the world you can build up anywhere (Up) But when clean or remove the plot only 15 blocks are removed (up) and others that are going on these 15 blocks are not deleted, do not quite understand because this happens, if I could help I would appreciate!

Here the picture of the plot owner:
![sin titulo](https://cloud.githubusercontent.com/assets/22947314/19628031/3b81d1a6-992b-11e6-8ec2-10960b17ede3.png)

Here the plot removed without owner:
![2](https://cloud.githubusercontent.com/assets/22947314/19628040/5ce76d38-992b-11e6-9301-ca7c6c6f5f8b.png)

**Comment by pmf-berlin** [comment]
Confirm. But for me it looks only like an refresh or drawing error. Because Users with no permissions can brick this blocks with one hit.

**Comment by RedstoneFuture** [comment]
We must test it, but i guess if you used a world-max_height lower than 256 block (definition in the worlds.yml) and you can build over here you have admin permission.

**Comment by RedstoneFuture** [comment]
> ... but i guess if you used a world-option with max_height lower than 256 block (option in the worlds.yml) and you can build over here you have admin permission.


Its not a bug. I think your plot is lower than 256 blocks.
