### ISSUE TITLE
PS and Grief Prevention

### ISSUE THREAD

**Issue by angiebobb** [IntellectualSites/PlotSquared#1407]
When I create the map, it is fine. It has all the squares and whatnot. I type /p auto to claim the closest square and it works just fine. 

I am using GriefPrevention for my anti-grief and Multiverse for creation/other stuff. Now, when I try to build in my claimed area, I get the notification that I don't have permission to build.

I have even disabled GriefPrevention in the config file, so it doesn't load on the PlotsSquared map. When I do that, PlotSquared doesn't protect anything. It doesn't show who owns what and it just allows me to break all the blocks in the area. 

The map is also suppose to be in creative mode but it's not changing. It is staying in survival.

I don't know what I am doing wrong. Could someone please help me?

**Comment by MattBDev** [comment]
We cannot help if you ignore the template and provide none of the information it asks.

**Comment by angiebobb** [comment]
Where is the template that I am suppose to use?

**Comment by MattBDev** [comment]
It shows up in the text box after you click new issue.

**Comment by boy0001** [comment]
https://github.com/IntellectualSites/PlotSquared/blob/master/.github/ISSUE_TEMPLATE.md
