### ISSUE TITLE
[Minor] Just wondering if /plot clear is supposed to echo [id] or a specific plot ID

### ISSUE THREAD

**Issue by chamunks** [IntellectualSites/PlotSquared#1408]
# Bug report template (Follow this template unless you are making a feature request.)
One of the latest versions from Jenkins 

**Description of the problem:**
Just a minor issue if you do /plot clear the message response is just ![this](http://i.imgur.com/0IAvW2u.png)
Just figured where it says [id] it is trying to either suggest that it can be targeted or that a variable that is supposed to indicate the plot you're on is not being passed correctly.

**Comment by MattBDev** [comment]
It looks like this is intended but I can't be sure unless there is a change @boy0001 made that I missed.

**Comment by boy0001** [comment]
In your `commands.yml` change the usage message for the clear command if you want. The current commands.yml does not have that argument, so it's probably from a previous version.
