### ISSUE TITLE
Can't delete plots with /plot delete

### ISSUE THREAD

**Issue by Volfoxy** [IntellectualSites/PlotSquared#1410]
Debug: http://hastebin.com/afisilufep

Problem: When a player or even admin does /plot delete, that plot looks as if it's deleted for a moment. However if ANYONE does /plot claim on that plot, it reverts to it's previous owner. I can't seem to figure out how to keep the plots deleted after a /plot delete.

Replicate; I'm not honestly sure what to say here, I guess /plot delete, then /plot claim, then it reverts to the old owner?

I can't honestly tell if the error is caused by a diff plugin or not, and don't know how to tell. I do assume it's a plots issue though.

Make sure you've completed the following steps (put an X between of brackets):
- [X] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] Made sure you're using an up-to-date version of PlotSquared
- [] Made sure the bug/error isn't caused by any other plugin

**Comment by Volfoxy** [comment]
Fixed the problem on my own, thanks anyways.

**Comment by azbh111** [comment]
My server has the same problem.Can you tell me how do you fix it?
