### ISSUE TITLE
Plot Swaps Revert Upon Server Restart

### ISSUE THREAD

**Issue by TheMattVid** [IntellectualSites/PlotSquared#1411]
http://hastebin.com/vozejivefo

When two players swap plots, the swap will undo after a server restart.

Take two separate players, use the /p swap command to swap the positions of their two plots, stop the server, start the server, then check.
- [x] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] Made sure you're using an up-to-date version of PlotSquared
- [] Made sure the bug/error isn't caused by any other plugin

**Comment by YepImRobbie** [comment]
I can also testify to this occurring.

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
