### ISSUE TITLE
Denied Players teleport in ground

### ISSUE THREAD

**Issue by avsterbone** [IntellectualSites/PlotSquared#1413]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/owuhumecuw

**Description of the problem:**
When a player is denied from a plot they are teleported into the ground at the world's spawn.  They used to teleport outside the player's plot, but now they don't

**How to replicate**:
Deny an non-op player from your plot while they are still in it.

**Comment by boy0001** [comment]
Cannot replicate, it teleports them to the world spawn. Use the following commands to set the spawn:
`/mvss` - multiverse
`/setspawn` - most other plugins

You can also use an NBT editor to modify the spawn set in the level.dat if you lack a plugin to do so.
