### ISSUE TITLE
Feature Request: Open Plot Flag

### ISSUE THREAD

**Issue by Divine7** [IntellectualSites/PlotSquared#1416]
Please add a flag that allows anyone to build on the plot. So you don't have to individually add members to it. Since you can't individually add every block for place/break flag to many characters in text field. Since I would like to have a community plot for my guests that is open to anyone.

**Comment by boy0001** [comment]
`/plot trust *`

**Comment by Divine7** [comment]
Thanks, was looking for that.

Is there a way to allow only certain groups from permissions access to the plot by setting a flag? For example I want there to be a plot flag that trusts only players in the Donators group with that certain permission.

**Comment by boy0001** [comment]
Not currently.
