### ISSUE TITLE
Error: PlotSquared database is locked

### ISSUE THREAD

**Issue by Panossa** [IntellectualSites/PlotSquared#1420]
**Debug paste link**:
http://hastebin.com/xeyojuqifo

**Description of the problem:**
Hello, I have a strange problem with the database of PlotSquared. Since I got myself FAWE and BlocksHub additionally to PlotSquared, WE and VS... Sometimes after reloads or restarts of the server the database of PlotSquared is locked. (see latest.log)
This causes that nobody on the server can use WE and VS anymore. And there are not plots claimed, too.
EDIT: It seems to happen more often on reloads then on server start.

**How to replicate**:
Have FAWE, BlocksHub, CoreProtect, PlotSquared and maybe to much other plugins together, then do a reload.

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] Made sure you're using an up-to-date version of PlotSquared
- [?] Made sure the bug/error isn't caused by any other plugin

**Comment by boy0001** [comment]
Don't use the `/reload` command
