### ISSUE TITLE
PlotSquared suddenly changes worlds.yml

### ISSUE THREAD

**Issue by Panossa** [IntellectualSites/PlotSquared#1421]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/wejediluju (after the change and after another restart)

**Description of the problem:**
I have at least one plot world with standard sized plots and at least 2 plot worlds with big plots (one with 200x200 and one with 256x256).
After several restarts PlotSquared suddenly read the data of the 200x200 plot world completely wrong or simply changed it. All worlds have a plot size of 42 now in the config. Also the road size of every world is 7 now. No matter if it was greater or smaller before. Even though, like I said, there were plots with a size of 200 e.g. yesterday.

**How to replicate**:
Maybe try making a few big plot worlds (my plots are 200x200 in the "error world"), then /reload and restart the server.

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] Made sure you're using an up-to-date version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by boy0001** [comment]
If you edit the `worlds.yml` to  something invalid it may reset the file. Also `/reload` isn't a safe command to use.

**Comment by Panossa** [comment]
1. I did not edit or open worlds.yml since ~2 weeks!
2. How do /reloads affect the reading and writing of configs if that command simply reloads all plugins (without shutting it down forcefully)?
3. The chance of the configs happened after a reload OR start of my server. It was probably one of the first (or maybe THE first) reload or startup after the update from PS v.3.2.26 to the newest snapshot.

~Panossa

**Comment by boy0001** [comment]
The reason why `/reload` is unsafe is that it leaves behinds classes from before the reload. Any reference to old classes will completely break. Worlds and anything in them are not reloaded at all from the command, meaning PlotSquared needs to go out of its way to hackily replace all old references. E.g. Reflection to modify the generator fields of loaded worlds.

The command `/plot reload` exists to safely reload plot configuration. 

You can fix the settings in the `worlds.yml` and start the server. To delete any incorrectly generated chunks you can use `/plot trim` or `/plot trimchunks`.

**Comment by Panossa** [comment]
Ok. Thx for the explanation of the /reload command!
What about plugins like PluginManager (Plugman)? They have also the commands to reload complete plugins. Do they also leave objects/classes behind?

(Btw: I knew about the /plot reload command but i needed the reloads for plugins that didn't have reload commands.)

Editing the worlds.yml (we had a backup) helped. Thx for the help!

~Panossa

**Comment by MattBDev** [comment]
assuming this issue is resolved.
