### ISSUE TITLE
Look into disabling the reload command

### ISSUE THREAD

**Issue by MattBDev** [IntellectualSites/PlotSquared#1422]
Note for self: look into removing the reload command from servers when PlotSquared is installed. I'm sure it can be done with reflection if possible.

**Comment by boy0001** [comment]
I'm not sure if it can be verified whether `/reload` or bad configuration was the problem. Either way I don't think we should go out of our way to disable the command. Spigot already prints a message saying the command is unsafe.

Anyway, there are two ways to achieve this:
 - Edit the `commands.yml` to null the command
 - Use reflection to modify the SimpleCommandMap

**Comment by MattBDev** [comment]
It prevents users from being stupid if we can remove it with reflection.

**Comment by MattBDev** [comment]
We could also use reflection to make it only print out a message explaining that it can't be used when PlotSquared is enabled.

**Comment by MattBDev** [comment]
Not gonna pursue this
