### ISSUE TITLE
Translation...

### ISSUE THREAD

**Issue by c7w** [IntellectualSites/PlotSquared#1423]
Hello,
PlotSquared is really an excellent plug-in which provides features that are way then other plug-ins with similar function. However, the only thing that bothered is the current terribly translated Chinese version.
As a Chinese translator who devote in translating plugins-related document, I’ve finished a new Chinese translation of your plug-in, which you may use it to displace the old one. It is a pleasure if you accept my translation as the official one.
↓
https://github.com/c7w/PlotSquared---Translation-into-ChineseSimplified

**Comment by manuelgu** [comment]
Feel free to submit a pull request :+1:

**Comment by MattBDev** [comment]
Please submit this as a pull request and I will merge it.

**Comment by c7w** [comment]
i am a newbie in github and i dont know how to do that :c

**Comment by c7w** [comment]
and this is a download link 
http://c7w.idcnet.top/files/chinese.yml

**Comment by c7w** [comment]
[http://c7w.idcnet.top/files/chinese.yml](url)

**Comment by c7w** [comment]
I have sent it
