### ISSUE TITLE
Plot clear bug

### ISSUE THREAD

**Issue by DerpyEdgy** [IntellectualSites/PlotSquared#1425]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:http://hastebin.com/yoripebuya

**Description of the problem:**Whenever players use the /plot reset command or the /plot clear command it only resets the inner 16 blocks leaving the outer blocks as they were. Plot size is 42 btw. Here is a screenshot of what I mean:
![2016-11-12_23 25 26](https://cloud.githubusercontent.com/assets/23428272/20243853/653e8958-a92f-11e6-860a-85aebb018ed5.png)

**How to replicate**: /plot reset or /plot clear

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] Made sure you're using an up-to-date version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin- Pretty sure it isn't another plugin but I'm no developer so I can't say for sure

**Comment by RedstoneFuture** [comment]
Currently not anymore.
