### ISSUE TITLE
Furnace stop working / Chests open no sound

### ISSUE THREAD

**Issue by kleinesgumi** [IntellectualSites/PlotSquared#1427]
i use the latest PlotSquared version, spigot latest.

sometimes complete randome Furnace's on plots stoping working and open chests make no sound.

why?

**Comment by MattBDev** [comment]
Did not follow template. This issue wouldn't have anything to do with P2

**Comment by kleinesgumi** [comment]
P2 has fault, not any another plugins, after i break and place the furnace again, furnace works but not for all.

**Comment by dordsor21** [comment]
So if P2 is not installed on the server, it does not happen?

**Comment by MattBDev** [comment]
Still not a plot squared issue.

**Comment by EvilOlaf** [comment]
Fawe installed? If so try to increase max physics.
