### ISSUE TITLE
1.11 Bukkit

### ISSUE THREAD

**Issue by MattBDev** [IntellectualSites/PlotSquared#1428]
Incompatibilities should be highly expected. 
Task List for full 1.11 support:
- [ ] Add Shulker Box support.
- [ ] Make sure Observer Blocks work as intended.
- [ ] Add support for new Entities (Evoker, Vex, Llama)
- [ ] Deprecate and rename current EntityWrapper to LegacyEntityWrapper for use in versions <= 1.10.2
- [ ] Create new EntityWrapper class for versions >= 1.11
- [ ] Make sure flowers cannot be stolen from flowerpots by pressing use.

**Comment by manuelgu** [comment]
Anything you can think of already?

**Comment by MattBDev** [comment]
Horses for sure.
I'm not sure what the new blocks are and their behavior so I need to look into those.

**Comment by MattBDev** [comment]
Looks like all code compiles fine against Bukkit 1.11
Deprecated API's need to be looked at due to possible removal in 1.12

**Comment by dordsor21** [comment]
P2 loads up fine with 1.11 spigot

**Comment by MattBDev** [comment]
It may load fine but there is bound to be some issues with the new blocks and entities.

**Comment by MattBDev** [comment]
- [ ] Add Shulker Box support.
- [ ] Make sure Observer Blocks work as intended.
- [ ] Add support for new Entities (Evoker, Vex, Llama)
- [ ] Deprecate and rename current EntityWrapper to LegacyEntityWrapper for use in versions <= 1.10.2
- [ ] Create new EntityWrapper class for versions >= 1.11
- [ ] Make sure flowers cannot be stolen from flowerpots by pressing use.

**Comment by Legoman99573** [comment]
Observer blocks dont work on plots. I guess it wasnt added yet?

**Comment by MattBDev** [comment]
@Legoman99573 thanks for the report 😃

**Comment by SecretlyJealous** [comment]
Not sure what causes this error but it seems to be on my console a lot: http://hastebin.com/nigavovowo.bash

**Comment by TNTUP** [comment]
I have a suggestion for the /chatspy function in PS2, there's no prefix when someone talks in /plot chat, can I sort it myself by adding something in the config or translations files? I've looked at it and I couldn't find it. Maybe I can fork and add it, but my java coding skills sucks badly :/

**Comment by Sikatsu** [comment]
Most of it works.. the error is annoying tho

**Comment by TNTUP** [comment]
@MattBDev Thanks for deleting my comment without warning! Expected a comment from you about the chatspy feature...

**Comment by MattBDev** [comment]
@TNTUP This wasn't the place to discuss it.

**Comment by TNTUP** [comment]
It could be for a feature for the 1.11 build... I find it very disappointing from you without warning...

**Comment by Legoman99573** [comment]
Great, now its becoming the spigot community on github. Take a chill pill man.

**Comment by MattBDev** [comment]
@TNTUP This wasn't about features, this was for 1.11 Server Support. You aren't understanding that features are not the topic of this issue. Listen to @Legoman99573 and take the chill pill.

**Comment by Legoman99573** [comment]
I was saying because im getting a useless notifications for it.

**Comment by TNTUP** [comment]
@Legoman99573 "useless" noticifations? Wow thanks for that.,,, very appreciated

**Comment by Legoman99573** [comment]
Clean all posts up to the closed issue please
