### ISSUE TITLE
ps cluster delete does not delete

### ISSUE THREAD

**Issue by dordsor21** [IntellectualSites/PlotSquared#1434]
/ps cluster delete without specifying a name, but when within a cluster returns "successfully deleted cluster" but does nothing
/ps cluster delete <name> specifying a correct cluster returns "successfully deleted cluster" but does nothing
otherwise it acts normally i.e. if not within cluster/not specifying a cluster/too many args it says so

**Comment by MattBDev** [comment]
Can't confirm.
