### ISSUE TITLE
Road generation bug

### ISSUE THREAD

**Issue by kemmeo** [IntellectualSites/PlotSquared#1436]
**Debug paste link :** 
http://hastebin.com/juweruyiki
![2016-11-20_20 47 07](https://cloud.githubusercontent.com/assets/16295563/20465789/5b77b326-af66-11e6-9fc8-0abfbe98832a.png)

**Description of the problem:** 
When setting the road fill block to 166:0 (Barrier blocks) on Hybrid generator, I get these weird world terrain generation artifacts. Using 1.11 dev build.

**How to replicate**:
Generate a new plotworld using the AUGMENTED option with the ROADS parameter set. Then make the road fill block 166:0 (barrier block).

p setup AUGMENTED
p setup ROADS
p setup 166:0 (for road fill block)

Make sure you've completed the following steps (put an X between of brackets):
- [X] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] Made sure you're using an up-to-date version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by Legoman99573** [comment]
Did you delete the world and let a new one generate? Happens if you dont do that.

**Comment by kemmeo** [comment]
I delete the old world folders any time I make changes to PlotSquared.

**Comment by kemmeo** [comment]
Pressed the wrong button (sorry)

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
