### ISSUE TITLE
ChatSpy suggestions

### ISSUE THREAD

**Issue by TNTUP** [IntellectualSites/PlotSquared#1437]
Suggestion feature for the ChatSpy in PlotSquared

When it is enabled, there's no prefix knowing its from PlotSquared, I've checked in the lang files or configs, I coudn't find that string to add it myself like "[P^2]" or P2. 

and having it logged in the console when someone talks in their plot, logging incase if something goes wrong (advertising, insults or whatever problem idk) could be nice.

**Comment by MattBDev** [comment]
There is a format that tells you the message is from PlotSquared:
`plot_chat_format: '$2[$1Plot Chat$2][$1%plot_id%$2] $1%sender%$2: $1%msg%'`
That is in the language files under the chat label. Is this what you are looking for?

**Comment by TNTUP** [comment]
Already there, not for ChatSpy function enabled. Thats for the plot chat internally, not for admins. There's no prefix to us so its confusing to determine if its from PlotSquared or another chatspy plugin. 

I'd ask for that feature for the console logging and the prefix (CS) but I'm guessing it wont be accepted, I'm the only one who asks that suggestion xD

**Comment by MattBDev** [comment]
I misread the code. The word format is used twice in this area of code. I'll add this format to the chatspy tomorrow. We can discuss console logging later.

**Comment by TNTUP** [comment]
Last time I tried the CS feature, when someone talks in their plot, myself being admin I only see "<rank> <playername>: <text>. As a player, the prefix is there. Not for admins though.

**Comment by MattBDev** [comment]
You're right. That's why I said I would add it tomorrow. I made a mistake in reading the code and what you are asking for is not there despite my belief that it was there.

**Comment by TNTUP** [comment]
Okay. Sorry for earlier if I was "harsh" my day was the worst, I was mad and I kept trying being calm at things :P

**Comment by boy0001** [comment]
Fixed in 5642fd3899c5ed772af9a88f070c249b3f135b6a
