### ISSUE TITLE
Feature request: A flag to enable Frost Walker

### ISSUE THREAD

**Issue by zombachu** [IntellectualSites/PlotSquared#1438]

**Comment by MattBDev** [comment]
It really isn't possible to detect the Frost Walker enchant at the moment. We can't uniquely distinguish it from other events.

**Comment by zombachu** [comment]
That sucks. Hopefully for a future version of minecraft then.

**Comment by MattBDev** [comment]
I can attempt to create a PR for Bukkit that allows this type of detection. The feature will be restricted to 1.11 though.

**Comment by boy0001** [comment]
@zombachu 
Try the new `frost-walker` flag.

@MattBDev
`EntityBlockFormEvent`. AFAIK we only added a listener for that when frost walker was added. Do you know if anything else calls it?

**Comment by zombachu** [comment]
@boy0001 
Freezing works great, but the ice appears to refuse to thaw out. Also, iirc, snow from snowmen also trigger EntityBlockFormEvent.

**Comment by boy0001** [comment]
@zombachu
I renamed it to `ice-form`, there's also an `ice-melt` flag you can try.

**Comment by zombachu** [comment]
Doesn't seem to affect frost-walker ice. Frosted ice is a different block than ice, so I think the fix is to add the new material [here](https://github.com/IntellectualSites/PlotSquared/blob/2b561f2efa2f048845e73f93d2d0b72d24c1d6c5/Bukkit/src/main/java/com/plotsquared/bukkit/listeners/PlayerEvents.java#L943).

**Comment by boy0001** [comment]
@zombachu 
Anything not on that list is already allowed...

**Comment by zombachu** [comment]
Welp, I'm retarded. Probably not a good idea for me to respond to issues late at night. I also realized that I tested the frosted ice at night in game, which is why it didn't melt.

In that case, everything is looking fine unless you still want to have ice-melt handle frosted ice.
