### ISSUE TITLE
Players who are not opp'd or added/trusted can use //up on any plot and on the roads

### ISSUE THREAD

**Issue by Legoman99573** [IntellectualSites/PlotSquared#1444]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**: http://hastebin.com/ehujokovip

**Description of the problem:** Players can use the WorldEdit command //up without being added. Even on roads. I am hoping i dont have to take the perm away as it is helpful and can be abused in servers as long as the bug is current.

**How to replicate**: Just use //up or /up and it works.

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] Made sure you're using an up-to-date version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by boy0001** [comment]
It's fixed if you use FastAsyncWorldEdit

**Comment by MattBDev** [comment]
@boy0001 Is this an issue because of AsyncWorldEdit or is PlotSquared the actual issue?

**Comment by boy0001** [comment]
@MattBDev 
It's a technicality of WorldEdit's up command not going through the proper channel for changing blocks (EditSession) and just setting the block directly. The only way to fix it in PlotSquared is to replcate the entire command.

**Comment by Legoman99573** [comment]
I have purchased ASyncWorldEdit. Idk if it is that plugin. I get no errors when using the //up command.

**Comment by MattBDev** [comment]
@boy0001 Maybe it would be best for at part of FAWE to be moved over to P2 instead of requiring FAWE to fix this issue?

**Comment by Legoman99573** [comment]
@MattBDev I actually agree with you on that.

**Comment by MattBDev** [comment]
I understand the reasoning for @boy0001 for wanting people to use FAWE. It's his plugin and in my opinion it does work a lot better than AWE. Some people just won't switch so we should try to fix it here instead.

**Comment by Legoman99573** [comment]
I dont use it as it disables AsyncWorldEdit and overrides his over the plugin someone bought for me. If he fixed it where it would work with it, I wouldn't mind adding it back and never rated on the plugin page as i wasnt going to do it based off of a plugin that is popularly used.

**Comment by boy0001** [comment]
@MattBDev 
Well a solution is a bit complicated. The best way to solve `//up` would be to modify the behavior by listening to the `PlayerCommandPreprocessEvent`. (Can't really do the same thing as FAWE since it replaces classes during startup, and doing the same in P2 would break FAWE/AWE). 

But it's not just up, there's the same issue with `//regen` and `//superpickaxe` (+others) which can't simply be solved in the same way.

**Comment by boy0001** [comment]
@Legoman99573 
Sunk cost fallacy. Paying for something doesn't mean you have to use it.

**Comment by MattBDev** [comment]
Maybe we should describe AWE as incompatible?

**Comment by Legoman99573** [comment]
@MattBDev It works ok with it, it was the //up command that could be used even if i dont give them the admin perms to override road check and other plot check.

**Comment by Legoman99573** [comment]
and it resolves the problem and now shows that they are missing the perm.
