### ISSUE TITLE
Cannot disable Tnt!

### ISSUE THREAD

**Issue by ICauseDarkDays** [IntellectualSites/PlotSquared#1447]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/gomoriyore
**Description of the problem:**

_I cannot seem to disable tnt for any plot. I tried /plot flag explosion false and it did nothing. please help?_ 

**How to replicate**:

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] Made sure you're using an up-to-date version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment]
You are running an extremely outdated version of PlotSquared. Please do not check the box "Made sure you're using an up-to-date version of PlotSquared" without actually checking.
