### ISSUE TITLE
Generic chat filter incompatibility

### ISSUE THREAD

**Issue by oasis9** [IntellectualSites/PlotSquared#1454]
I don't believe an extension I made on an a somewhat relevant issue earlier was resolved in its resolving commit, so I'll mention this as its own issue.
Check if the event has been cancelled before processing it. For some reason, the chat event has ignoreCancelled set to true in its eventhandler annotation. I went ahead and removed it for my own purposes, however this didn't fix the issue. I was cancelling at priority LOWEST, but even with ignoreCancelled removed, it continued to fire the event handler. This is essentially causing P2 to ignore any sort of chat filter's decision as to whether to allow a chat message or not. P2's event currently looks like this:
```java
@EventHandler(priority = EventPriority.LOW, ignoreCancelled = true)
public void onChat(AsyncPlayerChatEvent event) {...}
```
However, I had removed `ignoreCancelled = true`. Investigating whether isCancelled defaults to true or is ignored. To resolve, I suggest removing
```java
ignoreCancelled = true
```
and adding
```java
if (event.isCancelled()) {
  return;
}
```
to the top of the method body.

**Comment by boy0001** [comment]
Did you check to see if this resolved the issue, or just an assumption?
```Java
if (event.isCancelled()) {
  return;
}
```

**Comment by oasis9** [comment]
It resolved it for me.

**Comment by oasis9** [comment]
Bump.

**Comment by MattBDev** [comment]
@oasis9 We have 108 issues open as of writing this reply. Bumping doesn't help speed it up. We are always actively working on issues. We also have personal lives and actual jobs.

**Comment by oasis9** [comment]
Sorry, I didn't mean to offend. I was responded to very quickly originally, so I was confused when I saw almost immediate action being taken over another issue I gave a word in, but not this one after being actively responded to. Once again, sorry.

**Comment by MattBDev** [comment]
@oasis9 No problem. Bugs suck (the chat ones pop up way to much and annoy me a lot) and we want them to be fixed. Unfortunately waiting is hard to do, I can speak from experience.

**Comment by oasis9** [comment]
Yeah. Glad to be on the same page. Great job so far; I love how readable the code is (rewriting for Aeva Network's purposes).
