### ISSUE TITLE
Custom road schematics

### ISSUE THREAD

**Issue by NDruce** [IntellectualSites/PlotSquared#1455]
Hello. How to make plots look like this?

![2016-11-29_14 07 24](https://cloud.githubusercontent.com/assets/3519015/20746540/36b15838-b6f7-11e6-9d0e-63beafc61327.png)
![2016-11-30_12 17 21](https://cloud.githubusercontent.com/assets/3519015/20746541/36b2789e-b6f7-11e6-8879-81b46e15cda2.png)
![rbo0efgvbes](https://cloud.githubusercontent.com/assets/3519015/20746549/3d181bc6-b6f7-11e6-8807-e41385e962b7.jpg)

**Comment by boy0001** [comment]
Not possible. The roads must be fixed width.

If you want to setup a fixed width road schematic, see here: 
https://github.com/IntellectualSites/PlotSquared/wiki/Installation#adding-road-schematics

**Comment by NDruce** [comment]
But... how it realised on 3 screenshot?
