### ISSUE TITLE
Plots Unclaim on Restart

### ISSUE THREAD

**Issue by TedClubberlang** [IntellectualSites/PlotSquared#1456]
http://hastebin.com/cuyuwobope

Basically if I restart my server, even when everything is saved before hand, all plots end up unclaiming themselves by the time you join back.

I can replicate it by saving everything, then simply restarting the server. When you join all plots were unclaimed but all builds remain as they were.

Make sure you've completed the following steps (put an X between of brackets):
- [X] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] Made sure you're using an up-to-date version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by boy0001** [comment]
You have the database disabled in your settings.yml (line 17). Enable it to have persistent plot information.
