### ISSUE TITLE
A bug relate to saving world

### ISSUE THREAD

**Issue by azbh111** [IntellectualSites/PlotSquared#1457]
This bug can cause the plot to recover after the modify
the video:
https://youtu.be/Ep9uqXLUgLQ

server:KCauldron-1.7.10-1614.201
plot:  3.1.8
plugins: plotsquared  AutoSaveWorld   Essentials

steps:
1. save in plotworld
2.go to another world
3.save 
4.go back to plotworld
5.clear the plot
6.go to another world
7.save
8.go back to plotworld

the major content starts at 01:00
there is no exception in console

**Comment by azbh111** [comment]
the major content starts at 01:00

**Comment by MattBDev** [comment]
can you please share the `/plots debugpaste` information?

**Comment by azbh111** [comment]
when shuold I performe `/plots debugpaste`?

**Comment by azbh111** [comment]
[08:56:29 INFO]: Uploaded a full debug to: http://hastebin.com/ahiwejusah

**Comment by azbh111** [comment]
ths latest.log for the video : 
http://hastebin.com/umafekibuy
