### ISSUE TITLE
plot gets cleared when surrounding plots are empty after restart

### ISSUE THREAD

**Issue by aaa8881** [IntellectualSites/PlotSquared#1459]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/xiqarukoqe

**Description of the problem:**

Let's say there is a plot looks like 
A A A
A B A
A A A
If all plots are claimed ( sometimes doesn't require all to be claimed too ) 
All A plots are empty ( although they are claimed )
Somebody claimed B and built something .
After restart, everything he built in B is cleared. 
Whoever owned the plot is still the owner, and database is fine. 

**How to replicate**:

Claim 9 lands like above somewhere far from 0,0. For my server, it usually happens at 800+ both x and z.
Don't build anything on A plots,build something on B. Leave that place and restart server.
Check if plot B is cleared. 

Make sure you've completed the following steps (put an X between of brackets):
- [X] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] Made sure you're using an up-to-date version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin -> I mean I'm not 100% sure with it.. if it is sorry ..

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
