### ISSUE TITLE
Issue with Changing plot biomes

### ISSUE THREAD

**Issue by Tubaee** [IntellectualSites/PlotSquared#1461]
Ive gone over plots to change their biomes, but they dont adjust. This has happened since the newest update to plotsquared. 

If theres a simple fix, ill be more then happy to use that if anyone knows it.

Best

**Comment by boy0001** [comment]
Does relogging show the new biome?

**Comment by MattBDev** [comment]
No reply and little details provided. Assuming that relogging will switch it like it normally does (in cases where it doesn't)

**Comment by Tubaee** [comment]
@MattBDev actually after testing, my biomes do switch after a relog - having to relog right afterwards for every plot i change a biome. but the issue that I had which i figured a biome switch would fix is that in cold biomes my ice and snow keep melting. doesnt matter the cold biome - because i have tried multiple, the snow and ice still melt.
