### ISSUE TITLE
dsadasdas

### ISSUE THREAD

**Issue by TioLucas1552** [IntellectualSites/PlotSquared#1463]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:

**Description of the problem:**

**How to replicate**:

Make sure you've completed the following steps (put an X between of brackets):
- [] Include `/plot debugpaste`
- [] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] Made sure you're using an up-to-date version of PlotSquared
- [] Made sure the bug/error isn't caused by any other plugin

**Comment by boy0001** [comment]
huh?

**Comment by MattBDev** [comment]
@boy0001 You didn't understand what he was asking? He made it pretty obvious.
