### ISSUE TITLE
MYSQL Error on restart of server

### ISSUE THREAD

**Issue by Rocologo** [IntellectualSites/PlotSquared#1464]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:

**Description of the problem:**
It seems that you are not in control with your connections to the3 MySQL Error. 
I often get this error when i restart my server:
http://pastebin.com/mgVYyEYc

I know from my own development that this error occurs when you keep connections open to the MySQL database. MySQL disconnects these connections after a while, if they are not used. So you will need to close ALL connections when you are finished reading/writing from/to the database.

**How to replicate**:

Make sure you've completed the following steps (put an X between of brackets):
- [] Include `/plot debugpaste`
- [] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] Made sure you're using an up-to-date version of PlotSquared. I DO.
- [] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment]
Are you using /restart ? Unless I missed something, all SQL statements are closed after executing. Also, the connection is closed on disabling the plugin.

**Comment by Rocologo** [comment]
I use the restart feature in Multicraft. The same error would have happened if i used stop.

You have to close the dataSource after use as well. MySql disconnects the dataSource connection if it is not used frequently.

**Comment by boy0001** [comment]
Should be fixed now.
