### ISSUE TITLE
Players cannot open chests on their plots!

### ISSUE THREAD

**Issue by Koogle1000** [IntellectualSites/PlotSquared#1465]
http://hastebin.com/ivuriqaqip

So I am having this issue where players cannot open chests on their own plots. I have tried setting /plot flag set use allow, however they still can't open them. I'm using worldgaurd, zpermissions, and the latest version of plotsqaured. 

**How to replicate**: Make plots and try it

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] Made sure you're using an up-to-date version of PlotSquared
- [] Made sure the bug/error isn't caused by any other plugin

**Comment by boy0001** [comment]
Any message sent?

**Comment by Koogle1000** [comment]
If you mean in the console, no there are not any there.

**Comment by boy0001** [comment]
I mean to the player. PlotSquared would normally send a message if it's cancelling anything. My guess is it's another plugin e.g. WorldGuard.

**Comment by Koogle1000** [comment]
Yes, it sends a message to the player: https://gyazo.com/20504fa628889f09f31ba809db62106d    I have tried adding use to the plot but it did not work.

**Comment by boy0001** [comment]
The flag for chests are `/plot flag set use 54`, however are you sure those messages were sent to a player who was trusted or owner on the plot?

Note: If you aren't trusted/owner but are a member, the plot owner needs to be online for you to do anything.

**Comment by Koogle1000** [comment]
The players are the owners of thier plot, and I issues that exact same command and they still cannot open the chests on their plots. Maybe something from world guard is causing it, any ideas?
