### ISSUE TITLE
/plot Update When Latest Version Of Plotsquared Is Installed

### ISSUE THREAD

**Issue by urbea97** [IntellectualSites/PlotSquared#1466]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:

**Description of the problem:**
It Keeps Saying There Is A Update When I Have The Latest Version Installed
**How to replicate**:
/plot update
Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] Made sure you're using an up-to-date version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment]
Please submit a debug paste in the future. this is important when you report an issue like you describe.

**Comment by JackDn** [comment]
I have the same issue.
Here's a debug paste: http://hastebin.com/ifusamogos

**Comment by MattBDev** [comment]
I'm investigating the issue.

**Comment by urbea97** [comment]
Here this is my debug paste http://hastebin.com/hubijunopo

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
