### ISSUE TITLE
'Plot auto claim' deducts money from your account but doesn't provide you with a plot.

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/PlotSquared#1467]
PlotSquared dev 417
http://ci.athion.net/job/PlotSquared/417/

When you type ```/plot auto claim```, it deducts money from your balance but doesn't provide you with a plot in the world since it is trying to claim a plot automatically based on a specific schematic name. This was pointed out to me by a player who tried to claim a plot automatically but it took their money and didn't give them a plot. (Their fault for not using the actual command ```/plot auto```.)

Shouldn't it not take money if it can't generate a plot for a player? 

![link](http://i.imgur.com/ZqyKP7M.png)

**Comment by MattBDev** [comment]
You're right. It should check for the schematic before deducting money.
