### ISSUE TITLE
Plots only changing half of their biomes after relogging and additional biome issues

### ISSUE THREAD

**Issue by Tubaee** [IntellectualSites/PlotSquared#1468]
after testing, my biomes do switch after a relog - having to relog right afterwards for every plot i change a biome. but the issue that I had which i figured a biome switch would fix is that in cold biomes my ice and snow keep melting. doesnt matter the cold biome - because i have tried multiple, the snow and ice still melt. 

In addition i notice now that on some of my plots, only half of the biome changes and is now part plains biome and part ice flats

![2016-12-06_19 48 04](https://cloud.githubusercontent.com/assets/19367287/20950315/fe13b264-bbec-11e6-96a9-c6af663cdd3e.png)
![2016-12-06_19 48 14](https://cloud.githubusercontent.com/assets/19367287/20950316/0099fc6e-bbed-11e6-95cf-1496f9b11eda.png)

notice that its the same plot, but two biomes

**Comment by MattBDev** [comment]
Please follow the issue reporting template in the future. We need a `/plots debugpaste` if you want this to be fixed.

**Comment by Tubaee** [comment]
debugpaste - http://hastebin.com/eqaxejemih 

apologizes - still new to reporting bugs, wont happen again

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
