### ISSUE TITLE
Proposal: Remove support for versions lower than 1.7.10

### ISSUE THREAD

**Issue by MattBDev** [IntellectualSites/PlotSquared#1469]
According to MCStats only 16 servers run a version below 1.7.10
![game version borderless](https://cloud.githubusercontent.com/assets/4009945/21001890/e10bc03a-bcf0-11e6-86d2-6c037b9b23a0.png)
MCStats also groups versions below 1.7.10 under Unknown or Other as a very small group. 
![game version borderless2](https://cloud.githubusercontent.com/assets/4009945/21001971/4830085c-bcf1-11e6-9f13-6c0ccb56e9c1.png)

**Comment by boy0001** [comment]
ok
