### ISSUE TITLE
hi ! i donated 20$ =)

### ISSUE THREAD

**Issue by firebl0od** [IntellectualSites/PlotSquared#1470]
no bugs over here, juste wanted to suport you and your amazing plugin !
as you mentionned you could advertise my server above 15$.
here are the info:
name: Orah
ip: 94.23.32.105
we have a platform with survival, skywars, skyblocks, creative and soonly a big MMORPG 
here is our banner
https://scontent.xx.fbcdn.net/v/t34.0-12/15281077_1799165373658690_1263239105_n.jpg?oh=a6406158e8926521830bd7be2103b904&oe=584CE2FD

ps we are french ;)

**Comment by MattBDev** [comment]
Thanks for the donation! We appreciate your support.
