### ISSUE TITLE
Fly Flag Bug

### ISSUE THREAD

**Issue by avsterbone** [IntellectualSites/PlotSquared#1471]
Debug: http://hastebin.com/focotiquco

Description of the problem: When you use plot fly every time you drag something into your hotbar, your fly breaks then you need to warp to someone else plot and back or relog. This has been in the game forever and is really annoying. Also there is a fly glitch if you delete your plot and have plot fly enabled you can fly in the plot world.

How to replicate: Read above

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] Made sure you're using an up-to-date version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment]
I can't reproduce the hotbar issue but I can fix the fly glitch. @boy0001 or anyone else can you reproduce the hotbar issue? Otherwise this issue will be closed.

**Comment by avsterbone** [comment]
When will this be patched?

**Comment by MattBDev** [comment]
@avsterbone Do not ask for an ETA.

**Comment by boy0001** [comment]
Can't replicate the hotbar issue. I'd assume it's something other than PlotSquared

**Comment by avsterbone** [comment]
What about the fly part?

**Comment by manuelgu** [comment]
@avsterbone was fixed in https://github.com/IntellectualSites/PlotSquared/commit/3240fc95591292cb628f3bafc57fb5c225097ed6
