### ISSUE TITLE
Roads are able to get blocks placed on.

### ISSUE THREAD

**Issue by hugeblank** [IntellectualSites/PlotSquared#1472]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/tukihehuzu
**Description of the problem:**
Simply put as above, you can place blocks on spots that were specified as roads. (*The only thing is, you can't break them, until you whip a command block out and use fill or setblock or the like.*) <--When removing more plugins that I forgot were plugins, apparently you can break 
**How to replicate**:
- Make a plot world (/plot setup is how I did it)
- Make sure you have basic permissions, and do not have op status of any kind (Even though I'm 99% sure the same issue occurs when op).
- Place any old block, and witness the bug:
![2016-12-09_20 54 17](https://cloud.githubusercontent.com/assets/16393543/21071379/52eb35e2-be53-11e6-9891-a2c15da15653.png)

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] Made sure you're using an up-to-date version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by chistian95** [comment]
I'm having the same issue, Currently I'm using The 6af964f4 snapshot of PlotSquared, Sponge 5.1.0 2020 and Permissionmanager 2.5.3

**Comment by lofivo** [comment]
I'm having the same issue,how to fix it???
Minecraft1.10.2 
So

**Comment by chistian95** [comment]
No fix yet I'm afraid. I have made a quick dirty plugin that cancels the event when building on the road and it's working fine. It's just a temporary solution, but hey, it works :P

**Comment by lofivo** [comment]
chistian95, Can you give me your plugin?I can't write plugins,I sincerely hope you'll help me.

**Comment by chistian95** [comment]
Sure! I'll send you an email

**Comment by hugeblank** [comment]
hmnmnmnmmmm I may want it too...
@lofivo I can't either... which is why I report issues, and nag the living f*ck out of plugin devs XD

@chistian95 So all it does is cancel all events occurring on the road? could you make it so that people with total permission can edit the road? I would like admins on my server to be able to manipulate roads.
I would be very grateful, and you would save an entire server. thanks in advance, no matter if you can or can't do it :P

**Comment by chistian95** [comment]
Sure! I'll send you an email. And yea, all it does is check of the block is placed or not in the road using some simple math.

**Comment by chistian95** [comment]
@hugeblank I've realized that I don't have your email hahaha. Mine is linked to my GitHub profile, so just send me you and email and I'll be glad to help you. And about using modded items in other players plots... I have no idea, I'll have to check that out to see if I could fix it :P

**Comment by hugeblank** [comment]
@chistian95 hugeblank@gmail.com should work

**Comment by WorseWaif** [comment]
Hey @chistian95 I don't mean to be too much of a bother, but it seems you managed to solve the issue that I am also having. Would it be too much to ask if you could send me the fix you created as well? My email is worsewaif@gmail.com

**Comment by WorseWaif** [comment]
also, is it just me, or does it prevent dropping items only on roads? when anyone tries dropping items on the road it just dissapears completely, was wondering if there was a fix to that as well, seeing how an accidental press of the q could mean the loss of an important item..

**Comment by hugeblank** [comment]
@WorseWaif I haven't bothered testing since I reported this issue. If a protection plugin doesn't work, what good is it to be used. A guy by the username of lur is helping me out rewriting the class that's the issue, and may be able to help everyone that has commented on this report.

**Comment by chistian95** [comment]
@WorseWaif I'll send you an email :P

**Comment by boy0001** [comment]
Was fixed

**Comment by hugeblank** [comment]
yay!
