### ISSUE TITLE
Worldedit still anabled after being removed from the plot

### ISSUE THREAD

**Issue by xion87** [IntellectualSites/PlotSquared#1473]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/faxefebese

**Description of the problem:**
People with worldedit, if they create a selection on a added plot and being removed, they still able to change blocks
**How to replicate**:
- add somesone with worldedit in your plot
- the builder use pos1 and pos2 or axe
- remove him plots,
- the builder use //set stone and  he can use all WE commands until he create a new selection or logout
Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] Made sure you're using an up-to-date version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by RedstoneFuture** [comment]
Right ... this a problem.

**Comment by AeSix** [comment]
I have tested this with 1.13.2 / P2 4.184 - I am unable to replicate the results. 

I however do have my server set to where only trusted, not added players may use worldedit on non-own plots.  (So only plot owner and trusted can worldedit)

I ensured the trusted player could worldedit, and then removed the player from the plot and to test worldedit - which worldedit was not able to function (0 blocks changed)

So... fixed?

**Comment by Sauilitired** [comment]
Indeed, @AeSix, but with more information. I guess I'll close the other one.

**Comment by RedstoneFuture** [comment]
testet with:
> FastAsyncWorldEdit (Bukkit) 1.13.17
> PlotSquared 4.292



After a remove of the player he can't use //set.

Same with //undo, //redo, but I get the message:

![2019-06-26_22 35 08](https://user-images.githubusercontent.com/4140635/60213053-f53ad000-9862-11e9-8879-0758c17596cb.png)

**Comment by AeSix** [comment]
I'm calling this fixed.  
Proper behavior has been experienced with multiple versions of P2, Minecaraft and different servers - Bukkit, Spigot and Paper.
