### ISSUE TITLE
Disabling redstone not working properly

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#1474]
With this settings:
```
  # Disable redstone when all owners/trusted/members are offline
  disable-offline: true
```

redstone still does not work, I am not sure if it not detecting the plot owner from entering the plot correctly, but changing both of those settings to false and then doing /plot reload immediately fixed the problem

here is a screenshot from a user named Xyor who complained about the issue, as you can see he is obviously online and in his plot: https://i.gyazo.com/6c77706228aa086bace3299a4aa1ce04.jpg

I am using paperspigot 1.10.2 and plotsquared as of https://github.com/IntellectualSites/PlotSquared/commit/7b1c4a504273d45131a568a30727e280c5487dab

**Comment by RedstoneFuture** [comment]
Hello. After this long time: have you still a problem with this? I have tested this and currently it works good.
