### ISSUE TITLE
again about the  donation

### ISSUE THREAD

**Issue by firebl0od** [IntellectualSites/PlotSquared#1475]
hi, it's me again, was just wandering when will you put my server on the plosquared page ? =)

**Comment by firebl0od** [comment]
well well well, that's a shame that the few people that give you money are ignored, that's not how things work, and don't expect more people to make donation if you don't keep up with the "price"

**Comment by boy0001** [comment]
Sorry, there isn't a plotsquared website anymore (`www.plotsquared.com`). It was hosted by citymonstret who isn't part of the project anymore. There weren't enough donations to pay for the hosting anyway.
