### ISSUE TITLE
chunk are not loading correctly 

### ISSUE THREAD

**Issue by xahmedxx** [IntellectualSites/PlotSquared#1485]
in the world chunk are not loading correctly 
some plots are bigger than the other 
the border of the plot goes in and out

**Comment by dordsor21** [comment]
screenshots and /plot debugpaste will be needed

**Comment by xahmedxx** [comment]
i did the /plot debugpaste but nothing happens
here is a screenshot of what is happening 
![2016-12-23_11 15 07](https://cloud.githubusercontent.com/assets/24593813/21460044/586700c4-c901-11e6-91bf-5fe477856308.png)

**Comment by RedstoneFuture** [comment]
Currently the world generator is correctly.
