### ISSUE TITLE
Searching how to improve ChunkListener$1:

### ISSUE THREAD

**Issue by IlPicasso** [IntellectualSites/PlotSquared#1486]
# Bug report template 

**Debug paste link:** 

I can't use plot debugpaste because of

>plot debugpaste
Caused by: java.lang.RuntimeException: Couldn't read response!

**Description of the problem:** 
I have low TPS on a I7 machine with 150 players  

While seeing the Timings I get this 

http://top.mvdw-software.be/?id=23670695
 where ChunkListener$1: has a really high load 
![image](https://cloud.githubusercontent.com/assets/5110242/21443341/59f1965a-c872-11e6-9ffc-85df97d2c5c9.png)

**How to replicate:** 

**Checklist**:

- [] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by IlPicasso** [comment]
bump

**Comment by RedstoneFuture** [comment]
Hallo. After this ling time: have you still a problem with this?
