### ISSUE TITLE
regenallroads TPS threshold WAY too high

### ISSUE THREAD

**Issue by dordsor21** [IntellectualSites/PlotSquared#1489]
as title suggests, it needs lowering a LOT. ~19.6 TPS  is too low to do it, and thus regenallroads takes way too long because the TPS is too low almost all the time.

**Comment by CoolLord22** [comment]
Same thing happens to me :(((

**Comment by YepImRobbie** [comment]
Hope this gets resolved, it keeps rescheduling for me.

**Comment by dordsor21** [comment]
ought to be fixed as of build 488

**Comment by Fader-GumGum** [comment]
This is still happening.
