### ISSUE TITLE
merge only works in one direction the 2.nd merge on a plot will fail and destroy parts of your paths between the plots and unlink stairs problems

### ISSUE THREAD

**Issue by manuk0202** [IntellectualSites/PlotSquared#149]
1. Awesome plugins but there are 2 Bugs i found. The first one is when you use /plot merge (direction). it only works once for a plot. if you try to merge in another direction it will fail and destroy parts of your paths (see Picture 1.) 
   ![2015-02-13_20 30 34](https://cloud.githubusercontent.com/assets/10981356/6193976/5d105524-b3c0-11e4-8934-106c6c6c5dd4.png)
   Second issue: if you use /plot unlink and you have stairs on your paths they all have the same direction. (sry for bad english ^^) see Picture 2. I know /plot unlink is not fully implemented yet. also when i use the /plot unlink i will fall from the Server and i can join again after about a Minute.
   ![2015-02-13_20 32 53](https://cloud.githubusercontent.com/assets/10981356/6193995/82f4e71e-b3c0-11e4-9619-0bb3182cffae.png)
   Still I hope this plugin is going to have a future :D i realy like it the Basics worke fine.

**Comment by boy0001** [comment]
Are you using AdvPlots?

**Comment by manuk0202** [comment]
Yes i used AdvPlots with schematics.

**Comment by dordsor21** [comment]
this is probably redundant
