### ISSUE TITLE
Plot Border Issue 

### ISSUE THREAD

**Issue by Koogle1000** [IntellectualSites/PlotSquared#1490]
Whenever attempting to change the plot  walls (the slabs) claimed it breaks the plot world and changes it back to the default sandstone. Basically if I try to change the plot claimed perimeter slab it breaks the plots world and put's it back to the default settings. Here is what I have in the world settings https://hastebin.com/jocitezuhe.cs    I have tried changing the claimed to 44:0 and it does not work.

**How to replicate:** 
Make a plot world and try changing the on claim borders.

**Comment by RedstoneFuture** [comment]
Currently the generator is correctly: the claim border was generate if I claim the plot. I think it was fixed in this long time.
