### ISSUE TITLE
could not pass PlayerTeleportEvent

### ISSUE THREAD

**Issue by WilliamEstrela** [IntellectualSites/PlotSquared#1491]
![image](https://cloud.githubusercontent.com/assets/5386302/21468752/42e418c0-ca0c-11e6-97ce-e00bb2659ff5.png)

Debug error
![image](https://cloud.githubusercontent.com/assets/5386302/21468759/862c1d1c-ca0c-11e6-8caf-4dabbeaf98ca.png)

**Comment by RedstoneFuture** [comment]
When do you get this error?
