### ISSUE TITLE
Plot flag broken / bug

### ISSUE THREAD

**Issue by Flarium** [IntellectualSites/PlotSquared#1493]
The plot flag 'deny-exit' does not work properly. When you fly into the border it teleports you back once, then you can proceed to fly straight through the border onto other players plots. I have heard that it is just because of fly speed, but it cannot be because I was flying at the default fly speed. This bug makes/breaks my server and would be great if you could fix this flag. Other than that the plugin is great :)

How to replicate:
Go to plot with 'deny-exit' flag 'true' and simply fly into the border, you'll fly right through it after it denies you once.

I am using the most recent and up to date version of PlotSquared.

Thanks,
Flarium

**Comment by Gonsda** [comment]
This still has not been fixed?

Any chance of that happening?

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
