### ISSUE TITLE
Cannot paste schematic

### ISSUE THREAD

**Issue by Time6628** [IntellectualSites/PlotSquared#1495]
# Bug report template 

**Debug paste link:** (Couldn't get one because it threw an exception https://gist.github.com/Time6628/5fee0948ab099674e51cbaf37f537678 )

**Description of the problem:** Schematics cannot be pasted properly onto plots with sponge. 
Here's the error it throws: https://gist.github.com/Time6628/ab1e11fac293f9f4890f1fe18b1f9226 

**How to replicate:** 
Generate an empty world(set walls, plots, roads, etc to 0), change the schematic options in the config or paste the schematic via commands. 

**Checklist**:

- [Z] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
