### ISSUE TITLE
bug plot delete and press tab

### ISSUE THREAD

**Issue by comdarksider** [IntellectualSites/PlotSquared#1496]
I use recommend build 430 PlotSquared-Sponge-3.5.1-SNAPSHOT-6af96f4.jar.
Error and bug in spongeforge-1.10.2-2171-beta-API5.1.0-2010

**My sponge and PlotSquared**
http://prnt.sc/dqvr05  and   http://prnt.sc/dqvr68

**Detail Error**
1. run command /plot delete.  have error log in console.  
Bug after player delete plot.  Plot display unknown owner.  command /plot delete can not delete plot of unknown owner.  link picture bug after delete  http://prnt.sc/dqvwi3.
 Problem player can not cliam plot again.  New player can not cliam plot.
2. when press tab on keyborad for display next command on chat in game.

**Full error code link (New linked)  :**
1.  http://pastebin.com/y5eU9FVY
2.  http://pastebin.com/MWXVQ935

**Description of the problem:**  https://gist.github.com/comdarksider/4ce4f222e0d23a25dd99d7fa283bbb7b

**Please fix error and bug plugin for spongeforge-api5.1.0.  Thank you very much for read and working.**

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
