### ISSUE TITLE
Move from normal BungeeCord to CloudSystem -> Migration issues

### ISSUE THREAD

**Issue by GalatheasUncharted** [IntellectualSites/PlotSquared#1498]
As i said in your IRC-Chan...
I moved the whole Plot server into the CloudSystem of DevCubeHD and got many trouble....

So, step by setp in ordering.....
- Shutdown the old server
- copy the whole Server directory as backup to my Computer
- upload the Worlds (includes the Plotworlds) and plugins to the wrapper
- no MySQL config correction cause i use an external Cluster
- change the config of server.properties and spigot.yml to get spigot run in the cloud
- start the server through the wrapper

When i loggin into the Plot Server, no plots are avail.
The world is shown correctly (all buildings at the Plot)
If i try to teleport me to my home plot i got the message:
"no plots found in your search query"
If i'm standing on a Plot and type in: /plot info i got the message:
"you are not in a plot"

If i run the backup on my computer, all plots are loadet correctly...
If i run the old Plot Server on the root.... its also everything fine and correct....

Just when i start it through the Cloud/Wrapper i got this issue....

There're no errors on the console.
Here are the Plotsuquared Startup messages:
http://pastebin.com/7UKbAFae

Debugpaste Link:
https://hastebin.com/pedufihiha

Hope you can help to figure out what the problem is....
Kind regards
Gala

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by manuelgu** [comment]
Update to latest dev version to get the `/plot debugpaste` working. http://ci.athion.net/job/PlotSquared/lastSuccessfulBuild/artifact/target/PlotSquared-Bukkit-3.5.1-SNAPSHOT-6af96f4.jar

**Comment by GalatheasUncharted** [comment]
Update the issue report... 
Insert the debugpaste link:
https://hastebin.com/pedufihiha

**Comment by RedstoneFuture** [comment]
Hallo. After this long time: have you still a poblem with this? ^^ I hope it. sorry, we have much to do.

I think its only a databse problem e.g. with the new firewall connection. Check exactly this connection and claim for the test a plot, restart the server and check this plotowner. Is this still claimed?
