### ISSUE TITLE
Road schematic create error --> Road gen not working properly + Low TPS reschedule

### ISSUE THREAD

**Issue by Bobobaal** [IntellectualSites/PlotSquared#1504]
# Bug report template 

**Debug paste link:** 
http://pastebin.com/BXGeaf45

**Description of the problem:** 
This error pops up when wanting to create a roadschematic

**How to replicate:** 
I downloaded the following build when updating our creative server to 1.11: http://ci.athion.net/job/PlotSquared/432/
Not shortly I got a report that there was a problem with the roads generation which didn't place any border around the plot and also the materials of the roads itselves were not the same as the normal roads configuered in the beginning of the server. After using /plot createroadschematic this error comes in the console. And if you debugroadregen a plot only the border of the plot gets pasted.

Also the TPS detector is some kind of pissing me of, for the smallest fluctuation of the TPS it instantly reschedules the regenallroads action.

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by F4ith93** [comment]
Still an issue on Build #440 and 1.11.2
http://ci.athion.net/job/PlotSquared/440/

**Comment by ertagon2** [comment]
Still an issue on PlotSquared 3.5.0u2

**Comment by Fader-GumGum** [comment]
Detecting Low TPS reschedule is still a issue. Using latest Spigot and PlotSquared builds.
