### ISSUE TITLE
Worldedit on other plots

### ISSUE THREAD

**Issue by ThePopcornNoob** [IntellectualSites/PlotSquared#1505]
I have PlotSquared-Bukkit-3.4.4-SNAPSHOT;-817a5bc and worldedit-bukkit-6.1 (copied from the files) and I see players have the ability to use worldedit on other plots, I want to let them use only worldedit on the plots their allowed to build and his own plots

**Comment by Noiknez** [comment]
Hi, i have the same problem and i tested also with AWE

**Comment by RedstoneFuture** [comment]
https://github.com/IntellectualSites/PlotSquared/wiki/WorldEdit-processing

By default it works perfect with FAWE or AWE.

**Comment by Noiknez** [comment]
With fawe it is blocked, but when player do left click with the worldedit axe in the road it destroy the blocks

**Comment by RedstoneFuture** [comment]
He can break blocks only with the axe? Stupid.

**Comment by Noiknez** [comment]
What i can only say is left click only with WorldEdit wand on the road
There is some solution to this like creating a script to cancelled the left click with an wooden axe event

**Comment by RedstoneFuture** [comment]
At normally its a fail with P² or FAWE. I have this problem.

**Comment by RedstoneFuture** [comment]
My user get a message that he hasn't the permissions: plots.admin.interact.road
Check pls the permissions  for your user.

**Comment by boy0001** [comment]
Try updating WorldEdit, you are using an outdated version.

**Comment by CakeLady** [comment]
i too have only been able to solve this problem by switching to FAWE, and yes it doesnt work at all with regular worldedit, unfortunately
