### ISSUE TITLE
How do I allow players to drop Items?

### ISSUE THREAD

**Issue by avsterbone** [IntellectualSites/PlotSquared#1506]
This isn't a bug report, but rather a question. How do I allow players to drop items on the road without them instantly despawning?

**Comment by Johandrex** [comment]
It's an bug, which I'd like fixed aswell.

**Comment by ghacproductions** [comment]
I've just created a pull request to fix this:
https://github.com/IntellectualSites/PlotSquared/pull/1570

**Comment by boy0001** [comment]
Set `misc_spawn_unowned` to true in the `worlds.yml`.
