### ISSUE TITLE
Cannot generate debug output with /plot debugpaste

### ISSUE THREAD

**Issue by MrPNutts** [IntellectualSites/PlotSquared#1508]
# Bug report template 

No link available. /plot debugpaste generates an error.

Cannot generate debug output. Error is below:

4201 [22:18:07] [Craft Scheduler Thread - 1689/WARN]: [PlotSquared] Plugin PlotSquared v3.5.0-SNAPSHOT-95f8aaa generated an exception while executing task 29892
4202 java.lang.RuntimeException: Couldn't read response!
4203     at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:43) ~[?:?]
4204     at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:60) ~[?:?]
4205     at com.intellectualcrafters.plot.commands.DebugPaste$1.run(DebugPaste.java:29) ~[?:?]
4206     at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot.jar:git-Spigot-7d78b81-775f1e1]
4207     at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [Spigot.jar:git-Spigot-7d78b81-775f1e1]
4208     at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_111]
4209     at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_111]
4210     at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]

**How to replicate:** 

/plot debugpaste 

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
It's fixed in the current version, you just need to update.
