### ISSUE TITLE
BUG: Plot Visit Error

### ISSUE THREAD

**Issue by ItsAZZA** [IntellectualSites/PlotSquared#1509]
# Bug report template 

**Debug paste link:** https://hastebin.com/govatelani

**Description of the problem:** Plot visit commands gives an error on console whenever some special characters are used in the world name. We have a world called "creative-premium" and using the command **/plot visit creative-premium;1;1** for example, PlotSquared gives an error on console. Here's the error paste: https://pastebin.com/1LULcAcF The plot visit command works fine with our other world called just "creative".

**How to replicate:** Have world name that includes pretty much any non-alphanumeric character, such as a dash. Then use /plot visit/home/tp command with that world.

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by ItsAZZA** [comment]
Bump, this is still a problem!

**Comment by ItsAZZA** [comment]
Any news on this problem? Still having this annoying issue.

**Comment by RedstoneFuture** [comment]
I have test it with "Testworld-1" and "Testworld_2": it works currently. I thinks it was fixed in this long time.
