### ISSUE TITLE
Feature Request: Disable claiming

### ISSUE THREAD

**Issue by Mikgreg** [IntellectualSites/PlotSquared#1510]
Hello, I've read the documentation and can't seem to find a feature relating to this.

I have recently created a new plotworld on my creative server as the old one has become too big and is hitting the world border, and thought it would jsut be better to start off new. However, I have left the old world accessible for people who already had plots there so that they wouldn't lose the stuff that they had built.

My question is:

Is there a way to disable claiming plots in that old world, and if they run /plot auto in that world is it possible for it to create a new plot for them in our current plot world?

**Comment by jaboy** [comment]
You could just remove the permission plots.claim and plots.auto from everyone in that world, 
then they would not be able to claim any plots there :)

**Comment by Mikgreg** [comment]
Yep, I've already done that. Was kinda aiming towards the idea of it claiming in the other world when you did /plot auto though. If thats not something the developers are interested in doing right now thats fine though.

**Comment by RedstoneFuture** [comment]
Yes, e.g. a default "/plot-auto-World" would  great. My default-spawn-world is not a plotworld an so the player can't use the "plot auto" command.

**Comment by boy0001** [comment]
As mentioned above, you can disable claiming with permissions.

Usually, with per world permissions, you need to first teleport the player there before you are able to check them. This would mean if you have different claiming perms, P2 would need to teleport the player multiple times before able to determine where they could claim. This won't be done.

I'll look into an alternative solution.

**Comment by boy0001** [comment]
Build `#462` or above: https://ci.athion.net/job/PlotSquared/
Make sure vault is installed and remove the permission `plots.atuo` from all other plot worlds.
