### ISSUE TITLE
p deny continues bug?

### ISSUE THREAD

**Issue by SliderKP** [IntellectualSites/PlotSquared#1513]
i'm using the version: PlotSquared 3.5.0u2 and when a users type p deny to user and he is in the denied plot, he died... i see old reports for this bug in 2015 but not actually

sorry for my ignorance if i'm wrong, really good job with this plugin, PlotSquared rulz!

Edit (i'm downloading the latest dev build to test)

**Comment by MattBDev** [comment]
Can't reproduce.
