### ISSUE TITLE
/plot createroadschematic doesn't work

### ISSUE THREAD

**Issue by Mario359** [IntellectualSites/PlotSquared#1514]
**Debug paste link:** 
https://hastebin.com/vasicevaxo

**Description of the problem:** 
On /plot debugroadregen <world> for regenerating the roads in the entire map
``Updating .mcr: 0, 0 (aprrox 1024 chunks)
 [P2] Finished road conversion``
It's supposed to regenerate the roads of my world
But it didn't : [https://image.noelshack.com/fichiers/2017/04/1485542083-plot.png](https://image.noelshack.com/fichiers/2017/04/1485542083-plot.png)

With Minecraft 1.11.2 Spigot 1.11.2 and [PlotSquared](http://ci.athion.net/job/PlotSquared/440/) (DevBuild)

**How to replicate:** 
Make a new world with Multiverse : /mv create <world> normal -g PlotSquared:s=31,g=7,h=63,f=82,m=1,w=155,b=155
Create a road around a plot
Do : /plot createroadschematic; /plot debugroadregen and /plot regenallroads <world>
Wait ...

**Checklist**:
- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by frizzbee30** [comment]
I have to admit, whenever I've tried this, it hasn't worked.

**Comment by CosmicPyrex** [comment]
Yes me too. I need help on this ASAP!

**Comment by RedstoneFuture** [comment]
I think after this long time its fixed. I tested it and can't replicate this.

**Comment by NextdoorPsycho** [comment]
Can Replicate with latest
