### ISSUE TITLE
Blocks removed,and strange massive stone structures bug

### ISSUE THREAD

**Issue by netbiosxx** [IntellectualSites/PlotSquared#1515]
# Bug report template 

**Debug paste link:** 

**Description of the problem:** 

**How to replicate:** 

**Checklist**:

- [] I included a `/plot debugpaste` link
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [] I Made sure the bug/error is not caused by any other plugin

Hi, 15-16 days ago we updated plotsquared (3.5.0) and spigot (build 1.11.2R01) to the latest version,and we switched from multiverse core to the generator in bukkit.yml.

Can't do debugpaste,error on console regarding task 131379
Can't reproduce Issue

When we started the server,we found out that somewhere in the world (i can't remember where) A MASSIVE stone structure (maybe a bugged chunk?) appeared,and with large worldedit selections,we fixed it.
But today,we find out that some plots in an area of about 15 plots 64x64, the blocks, starting from Y 66 up to Y 70 were gone,and this area is very distant from the stone bug area
Why? was it plotsquared?

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
