### ISSUE TITLE
Merging and unmerging a plot does not restore the road from schematic. Similarly, plot centers are not reloaded from schematic when deleted.

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/PlotSquared#1517]
PlotSquared dev 440 (3.5.1-SNAPSHOT-88f5e5b)
FastAsyncWorldEdit dev 480 (17.01.15-708ac6e-475-10.3.7)

@boy0001 I believe this problem may be caused by this commit https://github.com/IntellectualSites/PlotSquared/commit/6af96f43d4e2ba01e076bc3ce62a707f95edca55

![link](http://i.imgur.com/JRF2HzB.jpg)

I use the interaction, plot, and sideroad schematic in the example provided on spigot. It use to generate and restore from schematic fine until recently when updating. Now plots deleted don't respawn the tree and roads aren't restored properly when unmerging.

**Comment by mibby** [comment]
@boy0001 Bump. :( This issue really sucks and is turning my plots world ugly.

**Comment by mibby** [comment]
@boy0001 I manually compiled the latest source with this specific commit reverted https://github.com/IntellectualSites/PlotSquared/commit/6af96f43d4e2ba01e076bc3ce62a707f95edca55 and it fixes the problem. So that commit breaks schematic restoring.

**Comment by xion87** [comment]
I confim this issue
