### ISSUE TITLE
nukkit bug

### ISSUE THREAD

**Issue by endbajsn** [IntellectualSites/PlotSquared#1519]
schematics: false The road can't edit /plot debugroadregen There is no change
![s70203-023324](https://cloud.githubusercontent.com/assets/13681768/22584161/da0639f6-ea2b-11e6-9085-3e4319d549b4.jpg)
![s70202-230218](https://cloud.githubusercontent.com/assets/13681768/22584163/db60480a-ea2b-11e6-85f5-915720f48e74.jpg)
![Uploading S70203-155100.jpg…]()

**Comment by endbajsn** [comment]
![Uploading S70203-155100.jpg…]()

**Comment by endbajsn** [comment]
![Uploading S70203-155100.jpg…]()

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
