### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by biggucci** [IntellectualSites/PlotSquared#1520]
Plugin works just fine, how do i make it so every plot has walls around it
and so people cant fly to other peoples plots

**Comment by dukedase** [comment]
First off, this is for issues, not questions.
Second, you can generate the world like that (sort of) if you want with the path walls (slabs by default)

Otherwise the people in the plots can simply build a wall or force survival mode.

**Comment by boy0001** [comment]
The walls and other generator settings can be changed in the `worlds.yml`, however you will need to regenerate the world to see the new walls.

You could also try something like: https://www.spigotmc.org/resources/plot-hider.20701/
