### ISSUE TITLE
2 worlds of

### ISSUE THREAD

**Issue by TheIntelloBox** [IntellectualSites/PlotSquared#1521]
**Description of the problem:** 
Hello ! :D

I have 2 worlds with Plot Squared : the creative world and the shop world where the players create their own shops.
When we do /plot home on the shop world, we already are teleport to the creative world. But I don't want it. I want : when the player writes /p h in the world shop, he is teleported to his plot.

Thanks to help me !

**Comment by boy0001** [comment]
Enable `per-world-visit` (line 77 in `settings.yml).
