### ISSUE TITLE
Oven, Redstone, Hopper stops to work.

### ISSUE THREAD

**Issue by pmf-berlin** [IntellectualSites/PlotSquared#1523]
**Debug paste link:** 
[17:54:00 WARN]: Exception in thread "Craft Scheduler Thread - 705"
[17:54:00 WARN]: org.apache.commons.lang.UnhandledException: Plugin PlotSquared v3.5.0-SNAPSHOT-95f8aaa generated an exception while executing task 1808
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Couldn't read response!
        at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:43)
        at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:60)
        at com.intellectualcrafters.plot.commands.DebugPaste$1.run(DebugPaste.java:29)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

**Description of the problem:** 
From time to time the ovens, hopper, dropper, redstone circuits stop to work.
Examples:
Oven
You visit your plot. Look into your ofen for example and there is coal and cobble stone but nothing happen. You have to break it. All drops, you install an fill aggain an every thing works finde.
Hopper
Autamatic farm with 8 Hopper which are arranged in a line for finaly fill an chest. Every thing works fine for an not defined time. But than it happen. The items will not absorbed an if you do by hand imtes in on of the hopper it will not transported.

**How to replicate:** 
Sadly it is not really replicatedable. It looks like for me that it will not depand if plot owner is on plot or not, if he is online or not. There is no fix time when this happen.

**Checklist**:
- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin <- deinstall all other Plugins

**Comment by alexmarkey** [comment]
Encountering this as well,
Recently reset our Survival server, updating PlotSquared in the process.
Since the update, we have experienced this issue.

**Comment by boy0001** [comment]
Using an outdated version of PlotSquared, please update.

There are some relevant options in the `settings.yml`
 - `redstone.disable-unoccupied`
 - `redstone.disable-offline`

**Comment by pmf-berlin** [comment]
Both are Disabled!
And I used the last Version. 

redstone:
  # Disable redstone in unoccupied plots
  disable-unoccupied: false
  # Disable redstone when all owners/trusted/members are offline
  disable-offline: false

**Comment by alexmarkey** [comment]
Can confirm the same findings,
3.5.0u2
disable-unoccupied: false
disable-offline: false

Issue is still present

**Comment by LecraM2003** [comment]
The issue ist still present. Would someone help me?

**Comment by RedstoneFuture** [comment]
@LecraM2002 You habe thill the problem, right?

**Comment by N7NobodyCats** [comment]
why was this closed?? it was not and still is not fixed.

**Comment by N0tMyFaultOG** [comment]
Because the issue is almost 3 years old. If you encounter the same issue, open a new ticket.

**Comment by N7NobodyCats** [comment]
this issue was pinged last year, but they closed it and labelled it a duplicate, however they didnt seem to make a fix even 3 years ago for it. so why did they close it then? plus im not the owner of the server, so i cant check the errors/settings. however the description of whats happening is exactly what is going on with me. hoppers work fine for awhile then just stop entirely.

**Comment by N0tMyFaultOG** [comment]
If your server owner can confirm it's an issue, he can open a new issue, but normally we don't look into ancient stuff.

**Comment by MattBDev** [comment]
This issue is not related to PlotSquared
