### ISSUE TITLE
Invisible falling Sand

### ISSUE THREAD

**Issue by Linebeck** [IntellectualSites/PlotSquared#1524]
# Bug report template 

**Debug paste link:** 

09.02 18:18:54 [Server] WARN Plugin PlotSquared v3.5.0-SNAPSHOT-95f8aaa generated an exception while executing task 116 09.02 18:18:54 [Server] INFO java.lang.RuntimeException: Couldn't read response! 09.02 18:18:54 [Server] INFO at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:43) ~[?:?] 09.02 18:18:54 [Server] INFO at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:60) ~[?:?] 09.02 18:18:54 [Server] INFO at com.intellectualcrafters.plot.commands.DebugPaste$1.run(DebugPaste.java:29) ~[?:?] 09.02 18:18:54 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.11.2.jar:git-Paper-1054] 09.02 18:18:54 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.11.2.jar:git-Paper-1054] 09.02 18:18:54 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.11.2.jar:git-Paper-1054] 09.02 18:18:54 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_71] 09.02 18:18:54 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_71] 09.02 18:18:54 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71] 09.02 18:18:56

&

09.02 18:20:23 [Server] WARN Plugin PlotSquared v3.5.0-SNAPSHOT-95f8aaa generated an exception while executing task 126 09.02 18:20:23 [Server] INFO java.lang.RuntimeException: Couldn't read response! 09.02 18:20:23 [Server] INFO at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:43) ~[?:?] 09.02 18:20:23 [Server] INFO at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:60) ~[?:?] 09.02 18:20:23 [Server] INFO at com.intellectualcrafters.plot.commands.DebugPaste$1.run(DebugPaste.java:29) ~[?:?] 09.02 18:20:23 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.11.2.jar:git-Paper-1054] 09.02 18:20:23 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.11.2.jar:git-Paper-1054] 09.02 18:20:23 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.11.2.jar:git-Paper-1054] 09.02 18:20:23 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_71] 09.02 18:20:23 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_71]

&

09.02 18:21:33 [Server] WARN Plugin PlotSquared v3.5.0-SNAPSHOT-95f8aaa generated an exception while executing task 132 09.02 18:21:33 [Server] INFO java.lang.RuntimeException: Couldn't read response! 09.02 18:21:33 [Server] INFO at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:43) ~[?:?] 09.02 18:21:33 [Server] INFO at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:60) ~[?:?] 09.02 18:21:33 [Server] INFO at com.intellectualcrafters.plot.commands.DebugPaste$1.run(DebugPaste.java:29) ~[?:?] 09.02 18:21:33 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.11.2.jar:git-Paper-1054] 09.02 18:21:33 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [patched_1.11.2.jar:git-Paper-1054] 09.02 18:21:33 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [patched_1.11.2.jar:git-Paper-1054] 09.02 18:21:33 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_71] 09.02 18:21:33 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_71] 09.02 18:21:33 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]

**Description of the problem:** 

So, I have noticed sand has been acting up for me. So everytime I put 2 x 1 sand pillar, and break the bottom sand block. The sand on top glitches and goes invisible. Then once you attempt to walk through it, it glitches you out. 

**How to replicate:** 

I believe it may be my config file. However, I do not want to have to recreate it everytime this error occurs.

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
If you have physics disabled it will do that on Spigot for some reason. It's client side. Enabling physics will have the block fall normally.
