### ISSUE TITLE
resetting or clearing lot

### ISSUE THREAD

**Issue by L0rdRav3n** [IntellectualSites/PlotSquared#1527]
when i issue /p reset or /p clear, it unlocks the plot but doesn't clear the land.  
also when i try to do the debugpaste i get the following

 CONSOLE: [INFO] L0rdRav3n issued server command: /plot debugpaste
 CONSOLE: [WARN]: [PlotSquared] Plugin PlotSquared v3.5.0-SNAPSHOT-95f8aaa generated an exception while executing task 26914
 CONSOLE: read response!
 CONSOLE: Source) [?:1.8.0_111]
 CONSOLE: Source) [?:1.8.0_111]
 CONSOLE: Source) [?:1.8.0_111]

**Comment by RedstoneFuture** [comment]
After this long time: have you still this problem? This problem is not normal. ^^
