### ISSUE TITLE
Some plots fail to clear 

### ISSUE THREAD

**Issue by hamhamfreak** [IntellectualSites/PlotSquared#1533]
![2017-02-16_22 50 31](https://cloud.githubusercontent.com/assets/9193367/23055505/02ef2836-f49b-11e6-95e6-48d0bb07ccdb.png)
# Bug report template 

**Debug paste link:** 

doesnt seem to work console errors about that command
**Description of the problem:** some of the plots Dont clear correctly when u p clear 
while others are cleared correctly

**How to replicate:** 

/p clear /p reset
**Checklist**:

- [] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

the Photo i attached is one of the plots that doesnt clear right as i tested using world edit to make the hole it didnt clear it all

**Comment by hamhamfreak** [comment]
Help Would Be Appercated

**Comment by boy0001** [comment]
Using an outdated version of PlotSquared, please update:
ci.athion.net/job/PlotSquared/

**Comment by hamhamfreak** [comment]
but Heres the thing i downgraded for now because the newer version has the ISSUE
