### ISSUE TITLE
Please change the behavior of adding/removing the wildcard (*) node to/from your plot

### ISSUE THREAD

**Issue by zombachu** [IntellectualSites/PlotSquared#1534]
Right now, the behavior of adding/removing the wildcard node makes it affect everyone else in your plot trusted/member/denied list as well. This is annoying for whenever someone changes their mind or when they only wish to deny everyone from their plot temporarily, as removing the wildcard node removes everyone you have previously added to the plot and adding back the wildcard node overwrites the access level of everyone previously added to the plot.

This behavior in action for denying * then removing *:
https://imgur.com/a/8woPw

A better behavior, in my opinion (and how PlotMe used to handle it iirc), is to treat the * node as just another player and to not modify the rest of the player list.

**Comment by MattBDev** [comment]
This behavior was chosen to provide a more consistent and sometimes faster experience for users. I may add this back but right now it is a low priority thing to decide. If I made my final decision now, it would be a no.

**Comment by boy0001** [comment]
It's not going to change to the PlotMe behavior, but I've tweaked it so that if you've specifically added `*` it'll remove that first.
