### ISSUE TITLE
Items dropped on road dissapears

### ISSUE THREAD

**Issue by Johandrex** [IntellectualSites/PlotSquared#1535]
Debug: https://hastebin.com/fonusamive
It's not possible to drop any items on the road, they just dissapear. It's however possible to drop the items in the plots. This issue doesn't exist on 3.5.0u2. But it exists on 3.5.1-SNAPSHOT-aa7b770. I've also attempted to test with the recent version that came out, the 31st January.

**Checklist**:
- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by i9hdkill** [comment]
Same issue here:
https://hastebin.com/afovukaxon
Can be """fixed""" by installing worldguard and deying item-drops.

**Comment by Johandrex** [comment]
@i9hdkill Well, I'd prefer if the developers for this plugin fixed it since it've worked before.

**Comment by i9hdkill** [comment]
Yeah sure. That is why it put it into quotionmarks. But that is an easy hotfix. Many players on our server lost valuable items due to this. That is why I mentioned it:)

**Comment by shada124** [comment]
oh I sorry but thank you sure

2017-02-21 17:54 GMT+02:00 John <notifications@github.com>:

**Comment by boy0001** [comment]
Set `misc_spawn_unowned` to true to allow spawning in unowned areas. It's not a bug to be disabled by default.
