### ISSUE TITLE
Memory leak!

### ISSUE THREAD

**Issue by Xayanix** [IntellectualSites/PlotSquared#1540]
http://i.imgur.com/Wr38Fz1.png

**Comment by Xayanix** [comment]
http://scr.hu/0duk/ejx4b

**Comment by kangarko** [comment]
@Xayanix may I ask you what program did you use to discover the memory leak ? Thank you.

**Comment by Xayanix** [comment]
Eclipse memory analyzer

**Comment by kangarko** [comment]
Thank you!
