### ISSUE TITLE
GenerateBiome spills out of plot

### ISSUE THREAD

**Issue by dukedase** [IntellectualSites/PlotSquared#1541]
# Bug report template 

**Debug paste link:** 
 I get a console error when trying to do this:  https://i.gyazo.com/206c0a767131f877b0289544bb3cb6d2.png

**Description of the problem:** 
When I do /plot generatebiome it generates the biome, but some stuff spills out, such as trees, etc into other plots, and sometimes destroys the road.

**How to replicate:** 

GO into plot, type /plot generatebiome biomeofchoice and voila
**Checklist**:

- [X?] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by c0wg0d** [comment]
I have this problem with the BiomeGenerator plugin spilling into other plots also, however I do not get an error like you.

There is a config option for BiomeGenerator called populator-inset that people on the Spigot forums say to set at 15 to fix this issue, but that seems to have no effect for me (I tried several values from 0 to 15 and none of them made a difference).

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
