### ISSUE TITLE
Why is SAVE in BASIC while LOAD is not?

### ISSUE THREAD

**Issue by 837951602** [IntellectualSites/PlotSquared#1543]
That'd be some inconvenient to ask for admin for restoring every time the map break

**Comment by dordsor21** [comment]
I believe plot load allows you to load any saved plot provided you know the name of the schematic, thus you can effectively steal other's claimed plots. Not sure though

**Comment by 837951602** [comment]
Can't you only load your own saved plot?

**Comment by dordsor21** [comment]
Maybe, maybe not. It was a passing thought

**Comment by jaboy** [comment]
Just a note on that, then you would be able to "destroy" a schematic when you know the name of it, just save another plot with the same name.

**Comment by boy0001** [comment]
Plot load lets you load your own plots from the configured web interface. By default you are using the public one which can be used by anyone to upload anything.

If you setup and configure a new web interface they will only be able to load plots saved from the servers you allow to connect to it.

**Comment by 837951602** [comment]
Does http://empcraft.com/plots/ save the plot as the uploading name instead of create a new name?

**Comment by boy0001** [comment]
It uses the uploading name but does not replace existing files.
