### ISSUE TITLE
Sponge-1.10.2 Bug road

### ISSUE THREAD

**Issue by comdarksider** [IntellectualSites/PlotSquared#1547]
# Bug report template 

**Debug paste link:** 

**Description of the problem:** 

**How to replicate:** 

**Checklist**:

- [] I included a `/plot debugpaste` link
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [] I Made sure the bug/error is not caused by any other plugin

**Comment by comdarksider** [comment]
Player can place block on road and all corner of plot.  Please fix biggest bug.

**Comment by boy0001** [comment]
Fixed
