### ISSUE TITLE
Chest/Sign data not carrying through on schematic plots

### ISSUE THREAD

**Issue by Cobwebster** [IntellectualSites/PlotSquared#1548]
# Bug report template 

**Debug paste link:** 

**Description of the problem:** 

When using schematics, it doesn't correctly copy chest/sign data. I've made sure that the schematic its self has the data, to which it does. Only when plotsquared uses the schematic on the plot does it remove the items in chests and text off signs.

**How to replicate:** 

**Checklist**:

- [] I included a `/plot debugpaste` link
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [] I Made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
Didn't follow the checklist and didn't even provide replication instructions
