### ISSUE TITLE
How to Remove a plot world

### ISSUE THREAD

**Issue by Tzzzt123** [IntellectualSites/PlotSquared#1549]
Hi PlotSquared,
I have made some plot worlds on my server but some of them aren't the thing i wanted so i'd like to remove them. I did /mv delete <worlds>
and /mvconfirm.
That deleted the worlds but in next server restart they reappeared.
Please help me.
Is there like a /plot removeworld command?
Thanks for quick help.
Tzzzt123

Plugins i use who could affect that:
Multiverse
Multiworld
AutoSaveWorld
PlotSquared

**Comment by Tzzzt123** [comment]
Why does no one help me?

**Comment by braceyourself07** [comment]
If you haven't tried this, go into /plugins/PlotSquared/config/ and remove your world from the file worlds.yml

**Comment by boy0001** [comment]
You also need to remove it from the multiverse worlds.yml

**Comment by Tzzzt123** [comment]
Okay thanks

**Comment by lantren** [comment]
I case some else run across this. It's sufficient to /mv delete the world and then go into /plugins/PlotSquared/config/ and remove your world from the file worlds.yml
