### ISSUE TITLE
Players can build everywhere all of a sudden

### ISSUE THREAD

**Issue by chromodorisannae** [IntellectualSites/PlotSquared#1550]
# Bug report template 

**Debug paste link:** 

I cannot do /plot debugpaste, because plot commands don't work.

**Description of the problem:** 
The server has been working fine for a while now, but all of a sudden players could build anywhere, and plot commands don't bring up anything in chat. There haven't been any changes to the permissions file, or any new plugins added. Making a new world works temporarily, but the same thing happens after a few months, so I have to make a new one again. I tried to update the plugin, but it made the server crash while starting it up.

**How to replicate:** 

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Can you attach your startup log?

**Comment by chromodorisannae** [comment]
http://pastebin.com/NsneWXvW
The indentation didn't copy over :/

**Comment by xion87** [comment]
dude it was your permission plugin broken file.... no permission ---> no vault ---> no plotsquared loaded

**Comment by chromodorisannae** [comment]
Do you have any idea about how I could resolve it? I put my permissions.yml through a couple of parsers, but they didn't say there were any problems. The "unable to load file backend" thing is still there, though.

**Comment by chromodorisannae** [comment]
I fixed it so that it doesn't say that it failed to load the permissions backend, but it's still not working.  When I do /plots I don't get any output, but plotsquared is on my plugins list if I do /plugins.

**Comment by chromodorisannae** [comment]
I've fixed up a couple of things, but the problem persists. I made a new pastebin with the new startup log:
http://pastebin.com/UaFzxvXb
Anymore help would be much appreciated, thanks.

**Comment by xion87** [comment]
Please fix all plugins, all are not for your server version

**Comment by chromodorisannae** [comment]
I fixed it, it works now! I just needed to delete LWC. Thank you for your help!

**Comment by dordsor21** [comment]
@boy0001 can be closed
