### ISSUE TITLE
Spongeforge-1.10.2-5.1.0-2099 bug road

### ISSUE THREAD

**Issue by comdarksider** [IntellectualSites/PlotSquared#1551]
Bug in spongeforge-1.10.2-5.1.0-2099.  Problem player can place block every road and every corner of plot.

Please fix this bug biggest bug.

**Comment by braceyourself07** [comment]
I am also having this issue. 

My plot debugpaste:  https://hastebin.com/afukogibos

No errors in console or on screen.  Players cannot break blocks, but they can place them on the road and plot borders.

**Comment by boy0001** [comment]
Fixed
