### ISSUE TITLE
Regenallroads Error 

### ISSUE THREAD

**Issue by Koogle1000** [IntellectualSites/PlotSquared#1552]
So,
I created a plot schematic, did the plot debugroadregen and then it was good. I went to my console and issued /plot regenallroads plots 65, it then started but says: 

"09.03 22:49:15 [Server] INFO [P2] Detected low TPS. Rescheduling in 30s" I don't understand how the TPS is low, it's never ever below 19.65 which is not bad. I also have about 4,000 MB of free memory so that couldn't be the issue either. Please help.

**Comment by dordsor21** [comment]
#1489 duplicate

**Comment by ertagon2** [comment]
Duplicate. But I don't see a solution.

**Comment by dordsor21** [comment]
well that doesn't mean you duplicate..... It's not as if you're paying for P2 so you shouldn't wine and be annoying about it. Comment on OG issue saying "me too" or sth.
