### ISSUE TITLE
Check plot merge limit before sending confirmation message to the other player

### ISSUE THREAD

**Issue by Platinteufel** [IntellectualSites/PlotSquared#1553]
This commit makes it possible that you can limit merged plots to a specific size (e.g. plots.merge.2 <- you can't merge 3 or more plots). 
https://github.com/IntellectualSites/PlotSquared/commit/f2d56ec2316af0f83d376ea02fc17e3381b6ead2

My users reported that they are still able to send a merge request, even if they are standing on an already merged plot and the other player will get the confirmation message that he have to confirm. Also it will take the merge costs, but nothing will happen because it's limited to 2 merged plots.

It only occurs if you want to merge with another person, if you try to merge your own plots it will tell you that you're _"not allowed to merge to the required size"_.

https://hastebin.com/muwexuceci

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
