### ISSUE TITLE
Feature Request:  Forge/Sponge version of PlotSquared awareness of Chisels n' Bits

### ISSUE THREAD

**Issue by braceyourself07** [IntellectualSites/PlotSquared#1554]
Not a bug, just a suggestion.  Is it possible for the forge/sponge version of PlotSquared to be aware of the Chisels n' Bits mod blocks?

**Comment by lurquhar1221** [comment]
https://github.com/IntellectualSites/PlotSquared/commit/491cc50440cc9ad0d3360a63265185c44de14086 may have fixed this.

**Comment by braceyourself07** [comment]
Thanks!  I upgraded and it does work except now shift-right-clicking will allow you to place chisels and bits blocks on someone else's plot.  You can left-click to break the block, but it doesn't break it server-side (it looks broken, but if you warp out and then back in the blocks reappear).
