### ISSUE TITLE
plots fail to clear on newest version 

### ISSUE THREAD

**Issue by hamhamfreak** [IntellectualSites/PlotSquared#1558]
# Bug report template 

**Debug paste link:** 

**Description of the problem:** 
THe plots On the latest build fail to clear properly and i downgraded to a lower version to fix it 

**How to replicate:** 
/Plot clear
**Checklist**:

- [] I included a `/plot debugpaste` link
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared (im using a lower version which fixes the plot issue )
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Debugpaste?

**Comment by hamhamfreak** [comment]
It didn't let me do command

**Comment by boy0001** [comment]
@hamhamfreak 
You probably weren;t on the latest version then:
http://ci.athion.net/job/PlotSquared/

**Comment by hamhamfreak** [comment]
I was on the Latest Version And that one Wouldnt issue that Debugpaste command i downgraded for nowe cus the lower version fixed it
