### ISSUE TITLE
Sponge 1.10.2 2099 - Bug plot delete

### ISSUE THREAD

**Issue by comdarksider** [IntellectualSites/PlotSquared#1559]
bug /plot delete.  error log in console.  This problem plot delete is complete but another player not claim plot at plot delete when player after /plot delete.  please fix this problem.

Link error code :  http://pastebin.com/29aC78Mu

**Comment by comdarksider** [comment]
Fix this problem now.  Bigest problem

**Comment by RedstoneFuture** [comment]
Hello. Have you still the problem after this long time?
