### ISSUE TITLE
Wildcard * & roads

### ISSUE THREAD

**Issue by andreas180319** [IntellectualSites/PlotSquared#1561]
https://hastebin.com/diluletafe

I can't remove "Everyone" from any plots, and can't remove a player from a plot:
https://gyazo.com/b255663f7219fef7e333b9b26908580b
https://gyazo.com/e5d1c8ee39223aa1e7402a75e2dbe6bb

And when i use the command for creation of a new road, and use the debugroadgenerate thingy, it just pastes quartz blocks.

When I try to paste the schematics from the folder in, it is the right schematic.

**Comment by boy0001** [comment]
Is it a merged plot?

**Comment by andreas180319** [comment]
Yes

**Comment by andreas180319** [comment]
The one with everyone has been fixed. The plot wasn't merged correct.

**Comment by PaddyWagon** [comment]
@andreas180319 Which version are you using? Which dev-build?

**Comment by andreas180319** [comment]
@PaddyWagon 3.5.1-SNAPSHOT-aa7b770

**Comment by PaddyWagon** [comment]
Have you tried the most recent dev-build? http://ci.athion.net/job/PlotSquared/463/

**Comment by andreas180319** [comment]
Thanks, that helped! ;)
