### ISSUE TITLE
Feature Request: Ability to add plots to player's limit.

### ISSUE THREAD

**Issue by smartin1018** [IntellectualSites/PlotSquared#1563]
Goes with title. I'm requesting a command that will add a plot to the players plot limit.
e.i. /plot limit add <player> <amount of plots> or something along those lines.
Thanks ;)

**Comment by dordsor21** [comment]
plot limiting is done with permissions.

If the player's group has the permission plots.plot.5 and you want to increase to 7, the player must be given the permission plots.plot.7

**Comment by smartin1018** [comment]
Hm, alright. I was aware of the permissions, but was also wondering if they could allow it to be changed via command.

**Comment by MattBDev** [comment]
You can change it with permissions plugins. Those offer commands and some allow you to create your own shortcut commands.

**Comment by smartin1018** [comment]
Yes, but you see, I can't _add_ to a permission, only set it.

**Comment by boy0001** [comment]
There's the `/plot grant` command for that.

Also you can add a permission, there's a script you can use:
 - https://github.com/IntellectualSites/PlotSquared/wiki/Allowing-a-player-to-claim-more-plots
 - https://github.com/IntellectualSites/PlotSquared/wiki/Scripting
