### ISSUE TITLE
Feature Request: Delete Plots from Console

### ISSUE THREAD

**Issue by lasercar** [IntellectualSites/PlotSquared#1564]
Would be useful to be able to specify plot id in the plot clear / plot delete commands, so that plots can be deleted from console (as far as I know it isn't possible currently, correct me if I'm wrong).

This would help in the situation of a plot that causes extreme client lag so that it is very difficult for an admin to visit the plot in game to delete it.

**Comment by boy0001** [comment]
You can specify the plot as the first argument using `/plot <plot> <command>`

e.g. `/plot plotworld;3;-7 delete`
