### ISSUE TITLE
All plots become unclaimed when the server restarts?

### ISSUE THREAD

**Issue by chromodorisannae** [IntellectualSites/PlotSquared#1566]
# Bug report template 

**Debug paste link:** 

Debug paste didn't return anything when I entered it. It just acted like I never put in a command at all.
**Description of the problem:** 
When players try to do /plot home, it says that they don't have any plots. They can do /plot claim to get it back, and it usually fixes the issues for a while, but it still unclaims them after a server restart. This is affecting all players on the server, including OPed players.
I would appreciate any help or ideas, thanks.

**How to replicate:** 

It seems to unclaim everyone's plots ever time the server is restarted.

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Please to attach your config.yml and startup log if the debugpaste isn't working.

**Comment by chromodorisannae** [comment]
Startup log: https://pastebin.com/pe2S4egt
PlotSquared doesn't have a config.yml file.

**Comment by boy0001** [comment]
I meant `settings.yml`.

**Comment by chromodorisannae** [comment]
settings.yml: https://pastebin.com/znqhraX6

**Comment by boy0001** [comment]
Can you attach a complete startup log? The one above is missing parts and the formatting is messed up. You should be able to attach files directly to your response here.

**Comment by RedstoneFuture** [comment]
@chromodorisannae 
Hello. After this long timt: have you fix this problem? Sorry, we have many to do. Maybe its a databse problem. But this is not normal. Use you mysql?
