### ISSUE TITLE
Encoding and letter problem

### ISSUE THREAD

**Issue by cengiz77** [IntellectualSites/PlotSquared#1568]
Hi! The plugin settings.yml and storage.yml is broken after starting the server their encoding turns to ANSI and letter i turns to ı, but when i reload the plugin encoding turns to UTF-8 and letter ı turns to i and this deletes all settings that I made.  Could you fix this? Here some screenshots about the problem:

http://i67.tinypic.com/5yw84g.png

And the log:

https://paste.ubuntu.com/24287500/

**Comment by cengiz77** [comment]
I found the solution! Could you make the config setting with lower case letters? This will solve the problem.

**Comment by boy0001** [comment]
It's already lowercase. Don't save with the wrong encoding and it'll work fine.
