### ISSUE TITLE
My plot world got wiped

### ISSUE THREAD

**Issue by wasder** [IntellectualSites/PlotSquared#1569]
https://hastebin.com/payajudoza
![](http://i.imgur.com/N1BBnlh.jpg)
My players complained that some chunks got missing, I restarted the server and after found this.
**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by wasder** [comment]
I still got such problem regularly, but not so much catastrophic. Sometimes server is starting to lag, TPS is getting below 18. I try to restart it normally and it hangs during world save.
https://hastebin.com/vilehuqimi
I have no choice but to kill the process. After force restart some shit like this happens:
![](http://i.imgur.com/xTT8M0V.png)
My guess that it is happening because of WordEdit (FAWE). It always loses chunks on regions which were edited with WE.
Latest debug log: https://hastebin.com/ozaqijavoy

**Comment by dordsor21** [comment]
are you saving world regularly?

**Comment by dordsor21** [comment]
See reply in boy0001/FastAsyncWorldedit#571
