### ISSUE TITLE
/plot grant appears to not work

### ISSUE THREAD

**Issue by lovettbp** [IntellectualSites/PlotSquared#1572]
Version: 3.5.0u2

Using /plot grant add <player> does nothing except return possible syntaxes, however, /plot grant check does work and doesn't behave the same way as the former.

Additionally, the wiki provides no info on this command.

No errors in console or in debug. It simply just does not function.

**Comment by StealthBravo** [comment]
@boy0001

**Comment by BlackBeltPanda** [comment]
Also not working for me. Same as above.

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
