### ISSUE TITLE
Feature Request: Mob Spawning

### ISSUE THREAD

**Issue by ClankyPoo** [IntellectualSites/PlotSquared#1574]
Able to disable natural spawning but enable only spawning from mob spawners for the plot world only.

**Comment by MattBDev** [comment]
This is already added I believe. Use the option `mob_spawner_spawning` in either the settings file or worlds file. I don't remember which though. I believe it would be in the worlds file.

**Comment by ClankyPoo** [comment]
It was in the worlds file
