### ISSUE TITLE
can't set time flag

### ISSUE THREAD

**Issue by braceyourself07** [IntellectualSites/PlotSquared#1577]
**Debug paste link:** 
https://hastebin.com/ivanazoluq

**Description of the problem:** 
/plot set time does not fix time in freebuild worlds (worlds: true) on plotsquared in SPONGE version.  Likely this hasn't been implemented yet.

Console error:  https://hastebin.com/obehiyedeg.sql

Also, after setting the time, if you use a plot command it says you're not in a plot.  After moving a little bit and you do /plot info, it does not show the time flag set.

**How to replicate:** 
Create new freebuild world (/plot auto), /plot set time 6000.  Time still continues.  Console error occurs.

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
Hello. After this long time: have you still a problem with this?
