### ISSUE TITLE
plugin can't delete world *

### ISSUE THREAD

**Issue by braceyourself07** [IntellectualSites/PlotSquared#1578]
**Debug paste link:** 
https://hastebin.com/nihikorala

**Description of the problem:** 
When on a world (*) if you type /plot delete, it says "Delete Completed!" but does not tp you out of the world and world remains.  It will be removed from the database however.  It won't show up on /plot list, but I can manually tp to it via /plot *;-1;2 home (for example).

Console error: https://hastebin.com/odezetekos.sql
This error isn't directly produced by the /plot delete command, but occurs after it has been deleted.

**How to replicate:** 
Create a * world then do /plot delete.

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by braceyourself07** [comment]
Also after deleting, I'm unable to teleport to any other worlds.  I get the "You have been teleported" message, but nothing happens.  Also unable to use /warps.  Relogging seems to correct this though.

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
