### ISSUE TITLE
plot delete bug spongeforge latest

### ISSUE THREAD

**Issue by comdarksider** [IntellectualSites/PlotSquared#1580]
I use spongeforge-1.10.2-2281-5.2.0-BETA-2274
I use plot delete bug have error log in console.  This is big problem of this plugin.  after plot delete in plot unknown owner because another player can not claim in plot after plot delete.  I am seriorus in my server.

Please fix this bug and problem.  Thank you very much and working.

Picture Problem Unknown Owner in plot Link :
http://prntscr.com/ewa47c

Full link error code :  
1.  In pastebin -  https://pastebin.com/adtg9Pi4
2.  In github -  https://gist.github.com/comdarksider/1e73df072846c8121967bb64ea6eaad6

**Comment by RedstoneFuture** [comment]
Hello. After this long time: have you still this problem? ^^
