### ISSUE TITLE
Permissions don't update until relog - Broken Permissions

### ISSUE THREAD

**Issue by Zenoxez** [IntellectualSites/PlotSquared#1581]
# Bug report template 

14.04 15:08:03 [Server] WARN [PlotSquared] Plugin PlotSquared v3.5.0-SNAPSHOT-95f8aaa generated an exception while executing task 90
14.04 15:08:03 [Server] INFO java.lang.RuntimeException: Couldn't read response!
14.04 15:08:03 [Server] INFO at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:43) ~[?:?]
14.04 15:08:03 [Server] INFO at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:60) ~[?:?]
14.04 15:08:03 [Server] INFO at com.intellectualcrafters.plot.commands.DebugPaste$1.run(DebugPaste.java:29) ~[?:?]
14.04 15:08:03 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-d276ab1-d219213]
14.04 15:08:03 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-d276ab1-d219213]
14.04 15:08:03 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
14.04 15:08:03 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
14.04 15:08:03 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

***********Error Message on Server Startup:*************
14.04 14:43:39 [Server] WARN [PlotSquared] Plugin PlotSquared v3.5.0-SNAPSHOT-95f8aaa generated an exception while executing task 62
14.04 14:43:39 [Server] INFO java.lang.RuntimeException: Couldn't read response!
14.04 14:43:39 [Server] INFO at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:43) ~[?:?]
14.04 14:43:39 [Server] INFO at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:60) ~[?:?]
14.04 14:43:39 [Server] INFO at com.intellectualcrafters.plot.commands.DebugPaste$1.run(DebugPaste.java:29) ~[?:?]
14.04 14:43:39 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-d276ab1-d219213]
14.04 14:43:39 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-d276ab1-d219213]
14.04 14:43:39 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
14.04 14:43:39 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
14.04 14:43:39 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Description of the problem:** 
I am using PermissionsEX.
I am not an OP. I cannot build in plots, even though I have given myself the plots.admin.interact.unowned permission and have also added it to the PEX group I am in. I restart the server and now I can build in plots, but I can also build on roads, when I couldn't before, and I have NO permissions to bypass the road protection. Also, when logging in, it says plotsquared has an update, even though I just downloaded a fresh copy of the plugin from spigot.

Proof of Issue: https://gyazo.com/9ca893ba27c84c93239d142c2bde572c
Plugins: https://gyazo.com/8243d5eb5b84b3e1055c9ffd0a04d652
PermissionsEX yml: https://pastebin.com/AUTTrCGx
PlotSquared Settings: https://pastebin.com/YXsekYTQ

**I am also running the server on BungeeCord (Offline Mode).**

**How to replicate:** 

**I also set up a brand new server and only installed spigot and PlotSquared, no other plugins. The same type of issue persisted. After creating a plot world, when I am not OP, I can not build on roads, when I give myself OP, I still cannot build on roads until I relog. When I relog and can build again, and take away OP, I can still build (until I again relog, then I can't). I also downgraded to an earlier version and the problem persists. My question is, why hasn't anyone else reported this?**

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
