### ISSUE TITLE
plugin.yml - Invalid LOC - zip exception

### ISSUE THREAD

**Issue by TehGreekGamerJIM** [IntellectualSites/PlotSquared#1582]
https://hastebin.com/melayadide.md
https://hastebin.com/pidehupoja.sql

**Comment by TehGreekGamerJIM** [comment]
Even with an older version of PlotSquared
https://hastebin.com/ulewisilil.sql

Server Version
![image](https://cloud.githubusercontent.com/assets/11886483/25063266/51a7051e-21e8-11e7-9a1b-bea39c7a9817.png)

**Comment by manuelgu** [comment]
Where did you download the file from?

**Comment by TehGreekGamerJIM** [comment]
Ah, my bad, I forgot to close the issue.

It was an issue with my internet connection while uploading it on FTP. Connection would drop and upload would restart corrupting the file. All good now

I was downloading it from Spigot.
