### ISSUE TITLE
plotsquare can not throw pokemon

### ISSUE THREAD

**Issue by comdarksider** [IntellectualSites/PlotSquared#1584]
I use plotsquared latest build 477.  I can not throw pokemon in road and corner plot but in plot can throw pokemon.
please fix bug for pixelmon mod.

**Comment by RedstoneFuture** [comment]
Hello. After this long time, I think I cant help. But you can set a option in 
"**\plugins\PlotSquared\config**\settings.yml" :

```
  # Kill mobs on roads
  kill-road-mobs: false
```

Or have you interaction-permission-problems in the road? I down't know this mod, but this is not the problem of Plotsquared. for this you can use the Plotsquared API and write a plotsquared-addon for your pokemon-system.

**Comment by kxjhwbb** [comment]
same question..
kill-road-mobs: false   can't slove..
