### ISSUE TITLE
No Commands Appearing Bukkit + Nukkit

### ISSUE THREAD

**Issue by HGardener** [IntellectualSites/PlotSquared#1590]
**Debug paste link:** 
No errors displayed on console.

**Description of the problem:** 
None of the commands are showing, on either bukkit or nikki version. (To use bukkit i am using a plugin that translates bukkit code into nukkit, called pokkit) I have installed the nikki version and it generates all the nessary files, however when i try to use commands in game/through the console it throws the unknown command message. The command prompt doesn't even show any recognition that theres any valid commands. However,  when i do /plugins it still shows up. (Its the exact same when i install the bukkit version) 

**How to replicate:** 
Install plugin on nikkit pe / through pokkit with bukkit and run the server.

**Checklist**:
- [] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [unsure] I Made sure the bug/error is not caused by any other plugin

**Comment by GoldRushCoding** [comment]
I have the same problem, I tried using it with no other plugins and it still wont work.

**Comment by GoldRushCoding** [comment]
This may be why: 
Requirements:
SQL drivers: http://nukkit.ru/resources/dblib.14/
WorldEdit: http://nukkit.ru/resources/worldedit.103/

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
