### ISSUE TITLE
Sponge PlotSquared does not contain water flow

### ISSUE THREAD

**Issue by braceyourself07** [IntellectualSites/PlotSquared#1592]
# Bug report template 

**Debug paste link:** 
https://hastebin.com/awocunaqen

**Description of the problem:** 
http://prntscr.com/f128fo
Water flows (and I assume lava too) over the plot border.  This may be related to #1573 but this is occuring on the Sponge version.

**How to replicate:** 
Build adjacent to plot border.  Stand outside plot, place water bucket on top of build adjacent to plot border.  Water will flow over plot border into plot road.  

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
Right, #1573 for all serversoftwares
