### ISSUE TITLE
Bug duplicate plot in MC 1.8.8

### ISSUE THREAD

**Issue by jomjonejame** [IntellectualSites/PlotSquared#1594]
MC 1.8.8
Plot Version 3.5.0

**Description of the problem:** 

>  XCiller players claimed plot on 2017-03-07, but JamTDM player use command "/plot auto" on 2017-04-26.

> JamTDM players say that can building a house one day and the next day can not build a house. Due to enter in the plot it not named him.

> I am not good at English May be described as not understood. Can see pictures to understand.

duplicate plot 22;28 : http://imgur.com/KaUxWl0
photo 2 : http://imgur.com/aMmeCLI
photo 3 :http://imgur.com/TQIbmKG

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
