### ISSUE TITLE
Bug Chat

### ISSUE THREAD

**Issue by BlackLottus** [IntellectualSites/PlotSquared#1597]
Hi.

Some previous versions had in the chat the possibility of being able to write with colors, and I have noticed that the new versions do not have this option or it gives errors, at least in my server.

Could you help me?

**Comment by dordsor21** [comment]
post the error, a /ps debugpaste and exactly what was done

**Comment by BlackLottus** [comment]
not a error, but, before you can use for exemple &6Hola in /plot chat

Now, you can't use this, not work the colour.

**Comment by dordsor21** [comment]
Are permissions for using colour in chat normally given?

**Comment by BlackLottus** [comment]
Yes, I have op and * and can't use colours.

**Comment by dordsor21** [comment]
does the message sent include the "&"?

**Comment by BlackLottus** [comment]
yes.

**Comment by BlackLottus** [comment]
if you send &6Hi in chat appears &6Hi and not show any colour.

**Comment by BlackLottus** [comment]
![sin titulo](https://cloud.githubusercontent.com/assets/23360221/25565712/e32175f2-2dcc-11e7-8afd-6239499342e1.png)

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
