### ISSUE TITLE
Bug Unknown Owner in spongeforge 1.10.2 lastest

### ISSUE THREAD

**Issue by comdarksider** [IntellectualSites/PlotSquared#1598]
I use spongeforge-1.10.2-5.2.0-BETA-2308
Please fix bug unknown owner in plot.  Boy0001 no fix this bug and problem.  Unknown owner in plot another player can not claim in plot.  I post this bug many rounds.  You not fix.

Link error code :
https://gist.github.com/comdarksider/1e73df072846c8121967bb64ea6eaad6

Picture link Detail :  
http://prnt.sc/ewa47c

**Comment by RedstoneFuture** [comment]
A workflow for unknown owner was great, but this is a problem of the database. Any UID or username was not found I think. I know this problem myself.
