### ISSUE TITLE
//forest generates parts of trees on the road.

### ISSUE THREAD

**Issue by Maxetto** [IntellectualSites/PlotSquared#1600]
# Bug report template 

**Debug paste link:** 

https://hastebin.com/wimokomuvi

**Description of the problem:** 
When doing //forest inside a plot part of the tree can be generated outside (only the trunk is forcefully inside the plot).
May has something to do with FAWE.

**How to replicate:** 

- Claim plot
- Do //forest (near the border is easier to replicate)

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [ ] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
