### ISSUE TITLE
Update of your addons PlotRankup ?

### ISSUE THREAD

**Issue by fabien91** [IntellectualSites/PlotSquared#1602]
Hello,

Could you update [PlotRankup](https://www.spigotmc.org/resources/plotrankup.1571/) please, it doesn't work with last version of plot squared ?
I'm sorry to post here but on spigot topic i've no answer.

Sincerely yours,
Fabien

**Comment by Sauilitired** [comment]
It looks like that plugin has been abandoned. @boy0001 can re-open if he ever feels like continuing it.
