### ISSUE TITLE
any way to delete all roads?

### ISSUE THREAD

**Issue by SliderKP** [IntellectualSites/PlotSquared#1603]
Any way to reset all roads to default or i don't know maybe only quartz, because when i try;
1- /plot createroadschematic with all clear road (only quartz in floor)
2- /plot regenallroads city 64
only changes the floor and not up

sorry for my bad english

**Comment by dordsor21** [comment]
does the schematic include the air above the road? Not sure if this'll work, but give it a try if you haven't

**Comment by SliderKP** [comment]
Yes i need to replace all up the road for air, any way to do this?

**Comment by ertagon2** [comment]
Still an issue. As  I write this comment no help whatsoever was provided and it was posted 13 days ago!

**Comment by dordsor21** [comment]
@ertagon2 stop drudging around being an ass. It's not helpful to anyone on a _free_ resource....

**Comment by ertagon2** [comment]
You're taking it too personally. It's called constructive criticism.

**Comment by dordsor21** [comment]
fixed in latest commit
