### ISSUE TITLE
Plot Chat Spy

### ISSUE THREAD

**Issue by CoolLord22** [IntellectualSites/PlotSquared#1606]
# Bug report template 

**Running /plot debugpaste just claims "Exception in thread "Craft Scheduler Thread - 242""** 

**I was just wondering if there's away to change the format for the plot chat spy. The following location says it's an option, https://github.com/IntellectualSites/PlotSquared/blob/5642fd3899c5ed772af9a88f070c249b3f135b6a/Core/src/main/java/com/intellectualcrafters/plot/config/C.java if you just scroll till you find "PLOT_CHAT_SPY_FORMAT("$2[$1Plot Spy$2][$1%plot_id%$2] $1%sender%$2: $1%msg%", "Chat"),
" on line 627 but I added that to my own config, and upon restarting the server it just got rid of it.** 

**How to replicate:** 

**Checklist**:

- [?] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)] (https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
I found the "enhancement" issue which was to make it look like global chat, but I want to reverse that.
- [X] I Made sure the bug/error is not caused by any other plugin

- [X] I made sure I am using an up-to-date version of PlotSquared

**Comment by RedstoneFuture** [comment]
Currently it work.

1. Define the chat-spy-style in the language-config e.g. `PlotSquared.use_THIS.yml` :

`  plot_chat_spy_format: '$2[$1Plot Spy$2][$1%plot_id%$2] $1%sender%$2: $1%msg%'`

2. /p reload

3. UserA aktivate the plot-chat (/p chat) and write

4. UserB with permissions aktivate the chat-spion (/p toggle chatspy)

=> UserB see the chat of the plot-chat writed by UserA in the "plot_chat_spy_format".
