### ISSUE TITLE
Server crashes on deleting plot

### ISSUE THREAD

**Issue by wasder** [IntellectualSites/PlotSquared#1607]
Debug paste: https://hastebin.com/urotulacur

**Description of the problem:** 
I have finally made auto-clear task to work, but now faced with another problem - server is randomly crashing when someone's plot is being deleted.
It always leaves the same crash-reports:
https://hastebin.com/logivusera - latest.log.
https://hastebin.com/opuzakivah - crash report.
https://hastebin.com/genoyurupe - crash report.
https://hastebin.com/vajocidaki - crash report.

**Checklist**:

- [*] I included a `/plot debugpaste` link
- [*] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [*] I made sure I am using an up-to-date version of PlotSquared
- [*] I Made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
Can it be closed?

**Comment by wasder** [comment]
Yes.

**Comment by RedstoneFuture** [comment]
^^ You can close your own issues. You you do, please? (I can't it.)

**Comment by RedstoneFuture** [comment]
https://nucleuspowered.org/ For Sponge, right? And with a other teleport and warpplugin?
