### ISSUE TITLE
/p dispose causes to stop working furnaces

### ISSUE THREAD

**Issue by Xayanix** [IntellectualSites/PlotSquared#1608]
https://hastebin.com/evocuyuqav

**Description of the problem:** 
/p dispose causes to stop working furnaces

**How to replicate:** 
Place furnace on any plot, then type /p dispose on another

**Comment by dordsor21** [comment]
what exactly do you mean?

**Comment by Xayanix** [comment]
Check that video: https://youtu.be/9D7inwYYXiw

**Comment by Xayanix** [comment]
BUMP

**Comment by Xayanix** [comment]
Finally, lol!
