### ISSUE TITLE
How to set up "extra plot" package on buycraft

### ISSUE THREAD

**Issue by ShadowDelux** [IntellectualSites/PlotSquared#1609]
I wanted to create an extra plot package on buycraft where if you buy it, it gives you an extra plot.

Say if someone who has permission to own 1 plot buys one they will now be allowed to claim 2 but if someone who has permission to own 5 plots buy one they will now be allowed to claim 6

I have done this before but cannot remember how and cannot find an answer

**Comment by dordsor21** [comment]
use a separate permissions track which has ranks "plot1", "plot2" etc with plots.plot.1 plots.plot.2 permissions, then promote people along that track when they purchase new plots. Should be possible in most permissions plugins.

**Comment by ShadowDelux** [comment]
Also though they can win an extra plot in a chest, so if they win it multiple times how would I allow them to claim 1 extra plot each time

**Comment by dordsor21** [comment]
in the chest you execute the promote command as well. Every time they get promoted they from plot# to plot(#+1) if you set the track up right. Regardless of where the command is executed, it'll work

**Comment by ShadowDelux** [comment]
This is a mates server and he uses groupmanager.... which is crap, there was some sort of other way to do it tht I remember doing about a year ago, can't remember it now

**Comment by dordsor21** [comment]
./manpromote - it's perfectly possible, just learn how GM works properly
