### ISSUE TITLE
I found error in console, Help me plz

### ISSUE THREAD

**Issue by jomjonejame** [IntellectualSites/PlotSquared#1610]
# Error in console on command /plot delete
# Paste : https://pastebin.com/LD2mr2JE

**Description of the problem:** 
> Because of my server. I have a virus that causes the mysql file to be lost, so I'm using an old mysql file. But the world is still perfect. And when I got back to my plot, I could not. Destroy / place items any longer.
> 
>So I deleted my plot and claim it again. it error show on console and After this error. I can not claim any other plot until I restart the server.
> 
>P.S. Can / plot claim is normal but the system does not insert plot to mysql
> 

Plugin : PlotSquared 3.5.0u2
Sorry for my english is not good

**Comment by dordsor21** [comment]
use latest build from http://ci.athion.net/job/PlotSquared/ and see if it keeps happening

**Comment by dordsor21** [comment]
how old is the SQL file, and did you replace all of the old DBs or just one DB.
