### ISSUE TITLE
[P2] Detected low TPS. Rescheduling in 30s

### ISSUE THREAD

**Issue by ertagon2** [IntellectualSites/PlotSquared#1612]
# Bug report template 
[P2] Detected low TPS. Rescheduling in 30s

**Debug paste link:** 
[P2] Detected low TPS. Rescheduling in 30s

**Description of the problem:** 
[P2] Detected low TPS. Rescheduling in 30s

I'm sure you're familiar with the problem. 

**How to replicate:** 
[P2] Detected low TPS. Rescheduling in 30s

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [ ] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
what did you do? Please learn bug reporting....

**Comment by ertagon2** [comment]
Ok. So I used the template provided on you spigot page bridges.template. It does correctly create a world as described but for some strange reason glowstone does not emit light. If you place a new glowstone near the ones that are not working it fixes the problem. So I did that for one plot and then tried to change the roads for all plots. It doesn't do it correctly. It only updates few roads not always the whole way around and I get this error [P2] Detected low TPS. Rescheduling in 30s.
[PlotSquared.zip](https://github.com/IntellectualSites/PlotSquared/files/1016867/PlotSquared.zip)
[Multiverse-Core.zip](https://github.com/IntellectualSites/PlotSquared/files/1016868/Multiverse-Core.zip)
[Logs.zip](https://github.com/IntellectualSites/PlotSquared/files/1016869/Logs.zip)

**Comment by ertagon2** [comment]
![2017-05-21_12 49 23](https://cloud.githubusercontent.com/assets/28691446/26283625/f92384dc-3e23-11e7-9dc9-703b0f21d78b.png)
![2017-05-21_12 50 20](https://cloud.githubusercontent.com/assets/28691446/26283633/14ca8b7c-3e24-11e7-86c4-1985033e9af4.png)

**Comment by ertagon2** [comment]
I'm not even going to start complaining about how buggy your plugin is. Especially the roads. I wasted 8h trying to fix it. ROADS DO NOT REGEN CORRECTLY.

**Comment by dordsor21** [comment]
It's a free resource, you can't expect instant bug fixes from the _one_ main dev. Pay for your own plugin if you want instant bug fixes.

**Comment by ertagon2** [comment]
Not once I complained about not having "instant bug fixes".

**Comment by dordsor21** [comment]
you complained that it hadn't been fixed yet.

**Comment by ertagon2** [comment]
Well, It's been a problem for a while and I see that I'm not the first person saying it. So yeah. I complained that it hadn't been fixed since the beginning of this year.

**Comment by MinecraftAdmin** [comment]
All the TPS-related issues with road regeneration have now been closed without any explanation of why. If the author of the plugin is indisposed, at the very least consider retaining the active status of pending issues for the author to inspect them once back from hiatus.

**Comment by dordsor21** [comment]
duplicate issues. Try reading up
