### ISSUE TITLE
Unable to download any plots

### ISSUE THREAD

**Issue by LazoYoung** [IntellectualSites/PlotSquared#1613]
# Bug report template 

**Debug paste link:** There is no error log for this problem.

**Description of the problem:** At some point, /plot download feature has broken.
I'm still able to get the download link through the command, however,
the webpage I went through the link says that the file was deleted.
[And here's the image I got.](https://www.spigotmc.org/threads/plotsquared.29970/page-207#post-2424733)

I've also tried to replicate this in a completely different server and I could see the issue persists.

**How to replicate:** Type /plot download in your plot and then click the download link you would get.

**Checklist**:

- [ ] I included a `/plot debugpaste` link -> no error output
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
your plots are too large and the schematics created are larger than the max file size.

#1479 duplicate

**Comment by LazoYoung** [comment]
I tried on 46(w)x46(l)x64(h) plot and it still didn't let me download the plot.
The file will not be larger than a megabyte :(

**Comment by dordsor21** [comment]
are you using the latest version of the web interface? And if so, post your configuration files here.

**Comment by LazoYoung** [comment]
[plotupload.zip](https://github.com/IntellectualSites/PlotSquared/files/1033534/plotupload.zip)
Besides, this issue remains even if I don't use my own web interface.

**Comment by highasshiit** [comment]
I too am having this same issue.

**Comment by dordsor21** [comment]
fixed
