### ISSUE TITLE
Inaccurate Low TPS warning

### ISSUE THREAD

**Issue by MinecraftAdmin** [IntellectualSites/PlotSquared#1614]
# Bug report template 

**Debug paste link:** 

https://pastebin.com/raw/p35908Jn
**Description of the problem:** 
Regenerating all roads prints Low TPS warning in console despite server having 20.00 tps and delays road regeneration.

I understand there are other bug reports for this problem, but it seems the issue hasn't been fixed yet so I decided to make another ticket.

Thank you for reading!

**How to replicate:** 

1. /plot createroadschematic
2. (in console) /plot regenallroads

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by ertagon2** [comment]
I have the same issue.

**Comment by dordsor21** [comment]
#1489 duplicate.
