### ISSUE TITLE
Users set to Survival after claiming plot

### ISSUE THREAD

**Issue by SpitfireGO** [IntellectualSites/PlotSquared#1615]
https://hastebin.com/ohopapexec.md

When ever any user that isn't myself (OP) claims a plot their game mode is set to survival. I have to manually set them to creative.

**Comment by LazoYoung** [comment]
You can find the default gamemode setting for your plot world in PlotSquared/config/worlds.yml

**Comment by dordsor21** [comment]
Likely you've set the world gamemode to survival/default gamemode flag to survival
