### ISSUE TITLE
PLOT 654 in `plot` is a duplicate. Delete this plot or set `auto-purge: true` in the settings.yml.

### ISSUE THREAD

**Issue by DKing328** [IntellectualSites/PlotSquared#1616]
# Bug report template 

**Debug paste link:** 

https://pastebin.com/zzXbAZUY 

**Description of the problem:** 
Errors when my server starts up. It's been happening for many months now, and the error seems to be getting bigger and bigger the more time that goes by. 
Errors: http://imgur.com/a/0X00r

**How to replicate:** 

Don't know what's causing it. 

**Checklist**:

- [] I included a `/plot debugpaste` link
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [] I Made sure the bug/error is not caused by any other plugin
>version plotsquared
[04:38:42 INFO]: PlotSquared version 3.5.0-SNAPSHOT-95f8aaa
[04:38:42 INFO]: Easy, yet powerful Plot World generation and management.
[04:38:42 INFO]: Authors: Citymonstret, Empire92 and MattBDev

**Comment by dordsor21** [comment]
set enabled-components.database-purger to true in config
