### ISSUE TITLE
Fixed scripts

### ISSUE THREAD

**Issue by Leomixer17** [IntellectualSites/PlotSquared#1617]
2 scripts were bugged in this page: https://github.com/IntellectualSites/PlotSquared/wiki/Scripting
So I've fixed it:
Fix plot borders: https://pastebin.com/zKzPTkti
Set all signs: https://pastebin.com/Q1HJEUQW

**Comment by CoolLord22** [comment]
This just gets spammed:
[11:56:05 WARN]: [PlotSquared] Task #9405 for PlotSquared v17.11.18-f27b12a-1938 generated an exception
java.lang.NullPointerException
