### ISSUE TITLE
Redstone on plots

### ISSUE THREAD

**Issue by bbruno5** [IntellectualSites/PlotSquared#1620]
There is a way to deactivate redstone circuits always that the players be outside their own plots?
I ask this, because some circuits, like minecart clocks isn't possible to disallow without prejudice other functions on game, and the presence of that circuits running constantly on server causes big lag and consequent crash.
Would be possible to have an option like this in a future release?

**Comment by dordsor21** [comment]
Look in settings.yml there are settings for redstone

**Comment by bbruno5** [comment]
Yes, there are two settings, that deactivate redstone for unnocupied plots, and plots where owners/members/trusteds are offline. But when player is online but on another world, the circuits remain working :/

**Comment by dordsor21** [comment]
so you're saying when `redstone.disable-unoccupied` is true, the redstone is not disabled when o#no-one is in the plot?

**Comment by bbruno5** [comment]
Yes, `redstone_wire` are disabled, since as `piston`, `sticky_piston` but other redstone blocks, like `golden_rail` and `activator_rail` remains working, since as `redstone_torch` remains on, permiting minecarts clocks like the video below. I'm OP, and the owner from the plot where's the circuit, is offline.

https://youtu.be/4vObfV-Fhzs

This circuits take a lot of ram, something about 60% in 30 minutes and 100% in an hour (server has 2gb ram), causing server's crash, even without any players online. The same problem don't occurs on worlds with survival mode.

![image](https://cloud.githubusercontent.com/assets/23748196/26755454/f7c8530c-4863-11e7-850f-5f4f21953e58.png)

I'm working for now on a skript that block activity from these specific blocks when nobody is nearby. Maybe it work for me.

**Comment by dordsor21** [comment]
everything seems to be working fine for me. Are you definitely using the latest P2 from http://ci.athion.net/job/PlotSquared/
