### ISSUE TITLE
"Could not pass event ChunkLoadEvent to PlotSquared" followed by crash

### ISSUE THREAD

**Issue by dordsor21** [IntellectualSites/PlotSquared#1623]
https://hastebin.com/homobaqiro.vbs

above was outputted before an eventual server crash

P2 build 483

**Comment by dordsor21** [comment]
happened again

**Comment by RedstoneFuture** [comment]
https://github.com/IntellectualSites/PlotSquared/issues/1048

**Comment by RedstoneFuture** [comment]
I think I can't help after this long time, but the problem is maybe a wrong chunk. If you check the world with a external minecraft chunk-scan tool, you find and can repair this.
