### ISSUE TITLE
Crashing on restart

### ISSUE THREAD

**Issue by L4BORG** [IntellectualSites/PlotSquared#1624]
# Bug report template 

**Debug paste link:** 

https://hastebin.com/hosayucuta

https://pastebin.com/s1B0dB8h

**Description of the problem:** 
P2 is crashing on restart (build 484)

**How to replicate:** 

Restart the server.

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
