### ISSUE TITLE
giving unknown owners after plotme data import

### ISSUE THREAD

**Issue by zSolitario** [IntellectualSites/PlotSquared#1625]
Hi, I would like to know if to resolve the plugin bug that when importing ends up giving unknown owners and when I put the / plots debugpaste command I get an error https://hastebin.com/icumejufeq.md

I would like to know what happened and if there is a solution.

My jar: http://i.imgur.com/jBG1ucm.png (git-PaperSpigot-1f7d532 (1.7.10-R0.1-SNAPSHOT))

**Comment by RedstoneFuture** [comment]
This error after plots debug paste was fixed.

**Comment by RedstoneFuture** [comment]
I think after this long time I can't help you, but if you have the plotme data still you can send this and we can replicate this import problem.
