### ISSUE TITLE
working for 1.12?

### ISSUE THREAD

**Issue by Jay9519** [IntellectualSites/PlotSquared#1628]
can't seem to find anywhere if this works or not for 1.12 bukkit

**Comment by dordsor21** [comment]
it works, did you evne try it?

**Comment by Jay9519** [comment]
No I haven't tried it yet, that's why I came here to ask the question before I do

**Comment by dordsor21** [comment]
I can't even

**Comment by chibill** [comment]
Possible adding 1.12 to the list of supported versions would have prevented this issue. fyi
