### ISSUE TITLE
Modded Server Issue with PlotSquared

### ISSUE THREAD

**Issue by DeCypherCR** [IntellectualSites/PlotSquared#1631]
Aloha. Have issue setting up PlotSquared on our modded server, (Conquest Reforged). Basically, we can set up a plot world, but, when we do a road design and test it, the road shows up as Red Brick. Also, a region around central point doesn't change up when doing /plot regenallroads , so have to use /plot debugroadregen to change that chunk.

Another big issue is the fact that when you moved away from the unchange chunk, the borders of plots are removed and the roads are all Red Brick. These issues can be seen in the attached images. We have updated to the latest version of PlotSquared, after having the issues, have even rolled back a couple of versions, with same results. Any help with this issue would be great. 

Debug log:
[https://hastebin.com/cupuqeyonu](url)

![1](https://user-images.githubusercontent.com/29430783/27132096-dfc03cd4-5150-11e7-8e4e-e3fe4cdf0ad6.JPG)
![2](https://user-images.githubusercontent.com/29430783/27132097-dfc44748-5150-11e7-849e-9cac9e5deaf5.JPG)

**Comment by dordsor21** [comment]
make sure there's no config change between restarts, if you're using different data values, 1.g. 1:2 instead of 1, I think it ought to be '1:2'

**Comment by DeCypherCR** [comment]
Hmm, not sure exactly what you are referring to exactly with the data values? I don't believe there is any change between restarts. Just delete anything associated to PlotSquared and attempt it again.

**Comment by dordsor21** [comment]
Not sure what it's called, but the bit after the colon. If the configs get regenerated, then it'll switch back to defaults. That^^ tends to happen if the config changes, and the chunks are generated for the first time.

**Comment by DeCypherCR** [comment]
It's happening before doing a restart. 

Right now, I just created another plot world. Everything looks exactly as it should. The issues happen after I design the custom road and make schem of it.

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
