### ISSUE TITLE
players sending minecarts into adjacent plots

### ISSUE THREAD

**Issue by Sidious82** [IntellectualSites/PlotSquared#1633]
# Bug report template 

**Debug paste link:** 

**Description of the problem:** 
players can build a small track and allow mine carts to fly across the road and into another players claim

**How to replicate:** 

**Checklist**:

- [] I included a `/plot debugpaste` link
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [] I Made sure the bug/error is not caused by any other plugin

**Comment by GloriousYellow** [comment]
Go to settings.yml and change
```
  kill-road-mobs: true
  kill-road-vehicles: true
```
