### ISSUE TITLE
Fast auto-clear task

### ISSUE THREAD

**Issue by wasder** [IntellectualSites/PlotSquared#1635]
I am requesting an alternative way for auto-clear task. 
It should just unclaim plots, not clear them. After that admin could just run ``/plot trim`` to delete most of them.
I got a very big world (50GB) with mostly empty plots, so auto-clear task will take forever to complete now. That's why I am requesting this. It will be very useful for me and I hope others.

**Comment by dordsor21** [comment]
enabled-components.plot-expiry - set to true
