### ISSUE TITLE
Need better documentation

### ISSUE THREAD

**Issue by Junior1544** [IntellectualSites/PlotSquared#1636]
I have been trying for several hours now to get this plugin to work, but the documentation is only half done on the wiki so I am having an extreemly hard time...   The documentation explains from the middle of some steps forward, and just skips large sections of what is needed to make this work...

Any and all help would be appreciated...  a better website with more complete instructions would be nice, or if someone that uses this would want to help directly would be great too.

Thanks

**Comment by dordsor21** [comment]
it's really not that complicated, and the wiki is perfectly adequate for everyone else. What's your issue

**Comment by Junior1544** [comment]
the /plot setup command needs to be explained a bit more..  I did that and what it said didn't make sence..  I figured it out by watching some youtube videos about this plugin.

**Comment by dordsor21** [comment]
I mean the /plot setup command is perfectly self-explanatory. What is it you're not sure of, because, no offence, it's a you problem.
