### ISSUE TITLE
Could not pass event PlayerInteractEvent to PlotSquared

### ISSUE THREAD

**Issue by MinecraftAdmin** [IntellectualSites/PlotSquared#1639]
# Bug report template 

https://hastebin.com/ehameyavea 

**Description of the problem:** 
Console error message, nothing critical it seems.
https://hastebin.com/hidonohoci.vbs

**How to replicate:** 

Just a console error.

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
