### ISSUE TITLE
/ps debugroadregen (and possible /ps regenallroads by extension) issue with merged plots

### ISSUE THREAD

**Issue by dordsor21** [IntellectualSites/PlotSquared#1644]
![2017-06-24_15 52 03](https://user-images.githubusercontent.com/10080017/27509459-321d218a-58f5-11e7-8d09-21e64b2b88b5.png)

2x2 merged plots, whichever of the four plots debugroadregen is executed from, the road on that plot (north-western-most) get regenerated.

**Comment by RedstoneFuture** [comment]
I get after `/ps debugroadregen` the messages 'The plot cannot be merged'. But the plot is already merged. 

![2019-01-27_18 35 22](https://user-images.githubusercontent.com/4140635/51804530-59c91300-2262-11e9-9a35-2a68b23ead4e.png)

**Comment by dordsor21** [comment]
We disabled debugroadregen on merged plots because there's no need for it.

**Comment by RedstoneFuture** [comment]
But a better messages would be good.
