### ISSUE TITLE
Worldedit issue

### ISSUE THREAD

**Issue by pedrocarcamo** [IntellectualSites/PlotSquared#1647]
If a VIP has permissions to worldedit, one plot is on 1,1 and the other one is really far far away. If he selects posotion 1 in one plot and position 2 in the other one it changes everything. including plots he has no access to and roads.

**Comment by dordsor21** [comment]
Are you using FAWE? If so, can you provide a /fawe debugpaste as well as a /p2 debugpaste ?

**Comment by TortillaSquad** [comment]
If you're not using it already, the best way to restrict WorldEdit to plots is using FAWE instead of just normal WorldEdit as they have permission nodes specifically for this purpose.
