### ISSUE TITLE
PlotSquared  home fix

### ISSUE THREAD

**Issue by Zaris24** [IntellectualSites/PlotSquared#1648]
Im Useing PlotSquared + This Template
https://proxy.spigotmc.org/1d68aac79861331665e8ec06de596800543ed22d?url=http%3A%2F%2Fi.imgur.com%2FOUkbrtM.jpg
My Problem is Every Time Players Use /plot home they are instantly
teleported up to the Bridge

Is there a small fix for this

**Comment by TortillaSquad** [comment]
I believe there is an option for this in the worlds.yml file.

**Comment by boy0001** [comment]
In the `worlds.yml` change the default home position:
```yml
    home:
      default: center
```
You can use relative coordinates e.g. `5,7` which will offset the home 5x and 7z from the corner of the plot

**Comment by Zaris24** [comment]
Sweet sorry havent replied thank you very much this helped alot

Den 10. aug. 2017 09.01 skrev "Jesse Boyd" <notifications@github.com>:
