### ISSUE TITLE
PlotAPI??? How does it work???

### ISSUE THREAD

**Issue by ElmarTVG** [IntellectualSites/PlotSquared#1649]
Hello guys,

Does someone of you got some experiences with the PlotAPI. I need to get the PlotOwner where the player is standing on. But how????

Please tell me!!!

**Comment by dordsor21** [comment]
https://github.com/IntellectualSites/PlotSquared/wiki/Developer-documentation-(WIP) -> https://github.com/IntellectualSites/PlotSquared/blob/master/Core/src/main/java/com/intellectualcrafters/plot/object/Plot.java

outlines all methods to do with plots.
