### ISSUE TITLE
WorldEdit bug

### ISSUE THREAD

**Issue by LudnicaKiller** [IntellectualSites/PlotSquared#1651]
On my server anyone with worldedit permissions etc //sphere //hsphere //set etc. can use that on every plot and roads (everywhere) on the server and this is the settings.yml https://pastebin.com/vhxDr8bs

**Comment by dordsor21** [comment]
Using FAWE? Are you sure they don't have bypass permissions?

**Comment by LudnicaKiller** [comment]
FAWE?
They don't have bypass permission

**Comment by dordsor21** [comment]
enabled-components.worldedit-restrictions set to true?

**Comment by LudnicaKiller** [comment]
I have updated worldedit and now works everything fine. But players can wand only on their plots, can't wand on plots where they are trusted, how to fix this?

**Comment by TortillaSquad** [comment]
FAWE has a permission node for that, it's fawe.plotsquared.member

FAWE is Fast Async WorldEdit, it uses less memory and processor than normal WorldEdit.
