### ISSUE TITLE
How do I generate plots in the same world?

### ISSUE THREAD

**Issue by VolcanicArts** [IntellectualSites/PlotSquared#1652]
**Description of the problem:** 
I have generated a plot world and I have a separate world with my prison mines on. I have multi-world inventories and it messes up the things you can take between worlds (a new inventory per world)

Can I generate a specific number of plots in the same world? Because I followed the tutorial and I gave a new world.

**How to replicate:** 

**Checklist**:

- [N/A] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report
- [x] I made sure I am using an up-to-date version of PlotSquared
- [N/A] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
https://github.com/IntellectualSites/PlotSquared/wiki/Augmented-Plot-Worlds
