### ISSUE TITLE
When i enter a plot it shows who owns it { plot owned by {player} how do i disable this message?

### ISSUE THREAD

**Issue by Kommanderkaleb** [IntellectualSites/PlotSquared#1655]
# Bug report template 

**Debug paste link:** 

i did /plot debugpaste and nothing happened i just really want this problem fixed :/ 

**Description of the problem:** 
So for my server i have creative plots and when you goto spawn and walk around because spawn was built on 4 plots it keeps saying who owns it witch would be me that owns it and i want to disable that message in that plot i tried /plot flag remove greeting but idk if thats what i do and if so it didnt work 

thankyou.

**How to replicate:** 

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by lurquhar1221** [comment]
`/p toggle titles`

There is a config option.
