### ISSUE TITLE
Gamemode 3 (Spec) and /plot deny

### ISSUE THREAD

**Issue by OnlyATiger** [IntellectualSites/PlotSquared#1656]
When I ban a player from my plot, the player can on my plot with Gamemode 3.

**Comment by RedstoneFuture** [comment]
@boy0001 Is this still a bug of spigot like this https://github.com/IntellectualSites/PlotSquared/issues/861 ?

**Comment by RedstoneFuture** [comment]
No, currently it work great. Sorry.
