### ISSUE TITLE
[1.11.2-Sponge] SpongeLocalUtil.regenChunk not implemented

### ISSUE THREAD

**Issue by lurr** [IntellectualSites/PlotSquared#1657]
P2 Version: Latest commit, f6540bb

**Debug paste link:** 
https://hastebin.com/edovusolaf

**Description of the problem:** 
/plot clear does not work, as SpongeLocalUtil.regenChunk is not implemented.
https://github.com/IntellectualSites/PlotSquared/blob/master/Sponge/src/main/java/com/plotsquared/sponge/util/block/SpongeLocalQueue.java#L416

[https://i.imgur.com/pPeG7Pir.png](https://i.imgur.com/pPeG7Pir.png)
**How to replicate:** 
1. Go to any plot
2. Do /plot clear
3. Note it doesn't clear the plot, and the regenChunk throws an error in console.
**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
