### ISSUE TITLE
Moving Plots

### ISSUE THREAD

**Issue by whitelily36** [IntellectualSites/PlotSquared#1664]
Plots disappearing when we move them.  The plot does move, but there is nothing on it.  Only happens if there are several beds on the plot

**How to replicate:** 
Move a plot with several beds on it

**Comment by TortillaSquad** [comment]
Did you try copying the plot instead? Then you can just go back and delete the old one.

**Comment by dordsor21** [comment]
Still an issue @whitelily36 ?

**Comment by RedstoneFuture** [comment]
On my server "/p move" work greatfully. Even with mobs.

@whitelily36 Have you still this problem?
