### ISSUE TITLE
PlotSquared Road Generation

### ISSUE THREAD

**Issue by Drirton** [IntellectualSites/PlotSquared#1667]
Everything's pretty much explained in this album: http://imgur.com/a/MUb2l

**Comment by TortillaSquad** [comment]
Did you build the roads all around the plots then take the schematic? I found that to be the easiest way.

**Comment by Drirton** [comment]
Yes. I built the all four roads and intersections surrounding the plot before creating the road schematic.

**Comment by TortillaSquad** [comment]
It wouldn't look as nice but maybe you could try a single lane road, then it wouldn't matter how it's copied.

**Comment by Drirton** [comment]
That's my current work-around but that doesn't resolve the issue.

**Comment by dordsor21** [comment]
It's not really a bug per se. It's reflectrotated about the corners, rather than rotated four times about the centre of the plot, which is the behaviour you're looking for. This is more of a feature request for two ways of rotating the roads about the plot.

**Comment by Drirton** [comment]
Any way for me to put this in as a feature request then, please?

**Comment by RedstoneFuture** [comment]
Hello. Have you till this problem?
I think you don't like the red AND the blue circled street-line. Then its a bug in your schematic or the generator.
