### ISSUE TITLE
Maps don't work in plot squared worlds

### ISSUE THREAD

**Issue by dwgr8ergolfer** [IntellectualSites/PlotSquared#1669]
# Bug report template 

**Debug paste link:** 
23.07 14:27:52 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
23.07 14:27:52 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_111]
23.07 14:27:52 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_111]
23.07 14:27:52 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [Spigot.jar:git-Spigot-99c2a37-c1b8cac]
23.07 14:27:52 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot.jar:git-Spigot-99c2a37-c1b8cac]
23.07 14:27:52 [Server] INFO at com.intellectualcrafters.plot.commands.DebugPaste$1.run(DebugPaste.java:29) ~[?:?]
23.07 14:27:52 [Server] INFO at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:60) ~[?:?]
23.07 14:27:52 [Server] INFO at com.intellectualcrafters.plot.util.HastebinUtility.upload(HastebinUtility.java:43) ~[?:?]
23.07 14:27:52 [Server] INFO java.lang.RuntimeException: Couldn't read response!
23.07 14:27:52 [Server] WARN Plugin PlotSquared v3.5.0-SNAPSHOT-95f8aaa generated an exception while executing task 162694

**Description of the problem:** 

**How to replicate:** 
Try and use a map in a plotsquared world

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
I can't replicate this. Please update the plugin and include a `/plot debugpaste`.
