### ISSUE TITLE
Plot is claimed by "Everyone" bug

### ISSUE THREAD

**Issue by ShadowDelux** [IntellectualSites/PlotSquared#1671]
# Bug report template 

**Debug paste link: https://gyazo.com/2a72a4e7f085e9ffd6a56414f39393d0** 

**Description of the problem:** 
Some plots say they are claimed by "Everyone", players are unable to claim these plots as it says they are already claimed.

**How to replicate:** 

**Checklist**:

- [ ] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [ ] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by TortillaSquad** [comment]
@ShadowDelux are these new plots that have never been claimed or are they plots that have been claimed/deleted?
Also, could you post screenshots of what exactly the /p info command returns? Thanks

**Comment by RedstoneFuture** [comment]
@ShadowDelux After this long time, have ou still a problem linke this? Can you get more informations?

**Comment by ShadowDelux** [comment]
@RedstoneFuture Sorry man, Don’t even play MC anymore.

**Comment by RedstoneFuture** [comment]
:D No problem. I close this issue. If someone have the same problem he can open a new post.
