### ISSUE TITLE
Plot debugexec show-expired

### ISSUE THREAD

**Issue by SrLeojaco** [IntellectualSites/PlotSquared#1673]
# Bug report template 

**Debug paste link:**  https://hastebin.com/fedanusuti.bash (the p debugpaste didn't work so i uploaded manually)

**Description of the problem:** 
Can't use plot debugexec show-expired it shows this error https://hastebin.com/coqazijafa.md

**Other** I was trying to delete plots which have less than 2changes per column (when i do plot debugexec analyze it shows changes/column 2.0 so i guess is that). It is properly configured? I read the wiki but i dind't understood well that

**How to replicate:** Use /p debugexec show-expired or anything realted to "expired"

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
It's been changed to. `/plot list expired` and I forgot to change that message.

**Comment by SrLeojaco** [comment]
/p list expired doesn't show expired plots despite i have plot-expiry set to true and i've configured the task to remove them
