### ISSUE TITLE
Unexpected Schematic Behavior

### ISSUE THREAD

**Issue by Tisawesomeness** [IntellectualSites/PlotSquared#1674]
**Debug paste link:** 
https://hastebin.com/ebavizuzok

**Description of the problem:** 
Saving a plot, then pasting it will put the plot in a different location.
Before:
![2017-07-30_22 12 50](https://user-images.githubusercontent.com/17386338/28760765-69f9f562-7577-11e7-8483-322715fcc04e.png)
After:
![2017-07-30_22 15 02](https://user-images.githubusercontent.com/17386338/28760769-6db564f2-7577-11e7-87cf-15f54e6a4f5a.png)

**How to replicate:** 
1. Claim an empty plot
2. Do `/plot schematic save`
3. Do `/plot load <the file you just saved>`
4. Use `/plot home` since you probably just got stuck in a block.

**Comment by TortillaSquad** [comment]
Could you post exactly what you're doing to replicate this problem? I.E. more screenshots showing what position you are in when you issue the commands. Using the debugpaste it's hard to figure out exactly what you are doing. Thanks

**Comment by Tisawesomeness** [comment]
@TortillaSquad The location doesn't matter as long as you are inside the same plot.
1. Here's the plot beforehand.
![2017-07-30_22 12 50](https://user-images.githubusercontent.com/17386338/28760765-69f9f562-7577-11e7-8483-322715fcc04e.png)
2. Doing `/plot schematic save` inside the plot.
![2017-08-14_20 25 23](https://user-images.githubusercontent.com/17386338/29299184-e6ed703e-813a-11e7-8abb-552d7f0f5728.png)
3. Doing `/plot load 1` in the same location.
![2017-08-14_21 47 49](https://user-images.githubusercontent.com/17386338/29299183-e6eac334-813a-11e7-9cf7-bc937a5d2c92.png)
4. End result
![2017-07-30_22 15 02](https://user-images.githubusercontent.com/17386338/28760769-6db564f2-7577-11e7-87cf-15f54e6a4f5a.png)

**Comment by Maxetto** [comment]
Second this. Hope we can have this fixed real quick.

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
