### ISSUE TITLE
PS can't find plots after a restart.

### ISSUE THREAD

**Issue by Panossa** [IntellectualSites/PlotSquared#1675]
**Debug paste link:** 
https://hastebin.com/anofodaves

**Description of the problem:** 
After one normal server restart without changes to the config being made the bug mentioned in the title occured. 

**How to replicate:** 
I have no idea :/
(Using MC 1.12, multi server system, SQL db, the world I'm using is called plotworld_new, the DB has also info about an old plotworld which wasn't an issue for a long time)
EDIT: The cluster info command you see in the log returned "You're not in a plot world" in chat.

**Checklist**:
- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by Panossa** [comment]
Update: I enabled the "purge" setting once to get rid of old plot data and then updated Plotsquared to the newest build. Still the same. Here's the new debugpaste:
https://hastebin.com/okikifixec

**Comment by boy0001** [comment]
It look like the world isn't using the PlotSquared generator. The `bukkit.yml` may have reset somehow. See here: https://github.com/IntellectualSites/PlotSquared/wiki/Manual-generator-setting

Also you should check that the database has the plots.

**Comment by Panossa** [comment]
You were right. The bukkit.yml was reset. Any idea why that could happen? As far as I know nobody even opened the file in a long time o.O

**Comment by boy0001** [comment]
> Any idea why that could happen?

Server crash when the file was being saved?
It had an option set which was invalid in newer spigot versions?
Someone accidentally opened the file and did something invalid?
