### ISSUE TITLE
Plot Schematic Wont Load In

### ISSUE THREAD

**Issue by NollerBear** [IntellectualSites/PlotSquared#1676]
Debug paste link: Nothing will show up when i do the command

**Description of the problem: I tryed loaded 1 plot in and it does not load at all. When i tryed loading a diffrent on in it says "Task is already running."

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)]
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by TortillaSquad** [comment]
So it sounds like you're trying to create a plot schematic and then load it into a plot? Is that correct? If so, could you list the exact commands you are using to accomplish this? Thanks

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
