### ISSUE TITLE
number of plot

### ISSUE THREAD

**Issue by tryolivier** [IntellectualSites/PlotSquared#1677]
hello,

in permission I put for exemple : 
    - plots.plot.1

so only 1 plot

but they do /plot done like that they can take 2 plot 3  4 or more !

but I don't want they take too much plot

I put

    - plots.use
    - plots.claim
    - plots.unclaim
    - plots.plot.1
    - plots.info
    - plots.auto
    - plots.home
    - plots.clear
    - plots.delete
    - plots.list
    - plots.set.home
    - plots.add
    - plots.trust
    - plots.deny
    - plots.remove
    - plots.untrust
    - plots.undeny
    - plots.kick
    - plots.visit
    - plots.permpack.basic

I don't put a permission for done

thanks

**Comment by TortillaSquad** [comment]
The permission plots.done is included in plots.permpack.basic

You could either negate plots.done or you could grant each permission you want players to have

**Comment by SrLeojaco** [comment]
Maybe you have **counts-towards-limit: false** in settings.yml
