### ISSUE TITLE
/plot delete/reset/clear bug

### ISSUE THREAD

**Issue by Potanz** [IntellectualSites/PlotSquared#1678]
*/plot debugpaste*
https://pastebin.com/3vnewpHE

Basically the issue I have is when I do /plot delete, /plot clear, or /plot reset random terrain blocks spawn out of no where.

Normally, it's a beautiful when I delete a plot and it spawns a tree right in the middle, as shown in the photo below.
![2017-08-01_19 00 29](https://user-images.githubusercontent.com/14229338/28854384-b804d8e2-76eb-11e7-9c98-165e1801301f.png)

For whatever reason, now it's all ugly when I delete a plot and it spawns a bunch of random things out of nowhere, as shown in the photo below.
![2017-08-01_19 01 08](https://user-images.githubusercontent.com/14229338/28854443-f8fbc6ee-76eb-11e7-8741-7f84448e1f65.png)

**Comment by TortillaSquad** [comment]
Is it the same thing every time? If so, the schematic or the generator could be messed up in some way.

**Comment by Potanz** [comment]
@TortillaSquad No, it's random everytime... I deleted the schematics folder in hopes that it would fix itself, but it did not.

**Comment by TortillaSquad** [comment]
What if you claim a plot, build on it, and reset/clear/delete it, then repeat. Does it place the same random terrain on the same plot?

Also, does it generate new chunks properly?

It may also be helpful if you could upload timings.

**Comment by boy0001** [comment]
See here: https://github.com/IntellectualSites/PlotSquared/wiki/Manual-generator-setting
