### ISSUE TITLE
Incompadability with Glowstone

### ISSUE THREAD

**Issue by funniray** [IntellectualSites/PlotSquared#1680]
**Debug paste link:** https://gist.github.com/funniray/5947d1755e27dcf90882cbe8761889bf

**Description of the problem:** 
Server crashes when you try to use Glowstone instead of Spigot to load Plotsquared. The plugin should be comparable, however it seems to have a problem when trying to load the SQLite library.

**How to replicate:** 

Use Glowstone.
**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
You need to add the sqlite-jdbc to glowstone (it's bundled with spigot but not glowstone).
See: https://github.com/GlowstoneMC/Glowstone/wiki/Library-Management
https://bitbucket.org/xerial/sqlite-jdbc/downloads/
