### ISSUE TITLE
PlotRankup will not run on 1.12 Server. 

### ISSUE THREAD

**Issue by hoop281** [IntellectualSites/PlotSquared#1683]
My server is running the latest version of buildtools that is compatible with the latest version of PlotSquared. I desperately would like this plugin to work, but the plugin does not generate any files or have any commands in game.

**Comment by TortillaSquad** [comment]
@hoop281 have you used PlotRankup previously? Or did you just install it?

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
