### ISSUE TITLE
Make the plot chat moderarable by other plugins

### ISSUE THREAD

**Issue by xion87** [IntellectualSites/PlotSquared#1684]
Plot chat is ignorated by other moderation plugin

**Description of the problem:** 
I use chatcontrol that use a configurable listener priority, the problem seem plot chat don't use any listener so chatcontrol don't work with it. Fix for code is described here https://github.com/kangarko/ChatControl-Pro/wiki/Listener-Priorities

**Checklist**:
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Use LOWEST priority.

**Comment by xion87** [comment]
Thank you it worked!
