### ISSUE TITLE
VoxelSniper plotsquared bypass

### ISSUE THREAD

**Issue by aaa8881** [IntellectualSites/PlotSquared#1685]
# Bug report template 

**Debug paste link:** 
https://hastebin.com/adajoniboh

**Description of the problem:** 
Player without correct permission can use voxelsniper in other people's plots and in road

**How to replicate:** 

1. bungeecord #1258 ( if it matters ), spigot 1.12, run server
2. 
put
WE 6.1.7.2 
VoxelSniper 5.171.0 
FAWE - 17.8.10 version
FAVS - 17.8.10 version 
PlotSquared - 17.8.10 version
in server

3. 
set some brush, like /b b
set some range like /b 5
**set material with data value(important) , like /v 5:5**

4. try to use voxel outside of allowed plot. You can build - which should not be allowed.

5. only works on material with data value, no data value works fine. 

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [-] I Made sure the bug/error is not caused by any other plugin , **not sure which is problem FAWE FAVS or plotsquared.. but same person would probably check this anyways so I'll leave here. If this needs to be moved to FAWE issue tracker, I'll do that if asked.

**Comment by boy0001** [comment]
Fixed, please update FAVS.
