### ISSUE TITLE
Issues with names with different cases

### ISSUE THREAD

**Issue by xion87** [IntellectualSites/PlotSquared#1689]
# Bug report template 

**Debug paste link:** 
https://hastebin.com/gidosihiru

**Description of the problem:** 
So i have a guy called "iwolfgamer" he buyed the premium called him iWolfGamer, this guy got some plots, i transfered them with success, but i noticed in /plot info it keep to say the plot is owned by "iwolfgamer", also that guy can /p trust people, but when he try to use /p add name, that person can't build in the plot

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
/ps add does not give the player permission to build/WorldEdit when the owner is offline

**Comment by xion87** [comment]
the owner was online and he can't do anything to his plos, because capitalization error

**Comment by TortillaSquad** [comment]
@xion87 what exactly do you mean when you say "he buyed premium" What did he buy?

And, did you use /p setowner to transfer ownership?

**Comment by xion87** [comment]
@tortillasquad the server is cracked... He was using a cracked username until he buyed the legal account from mojang. And yes I used p setowner
