### ISSUE TITLE
MySQL Error Bug.

### ISSUE THREAD

**Issue by DutchUser** [IntellectualSites/PlotSquared#1690]
**Description of the problem:** 
When the server close it spam a error

**How to replicate:** 
Set a MySQL database and close the server.

**Checklist**:

- [] I included a `/plot debugpaste` link
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
**- [] I Made sure the bug/error is not caused by any other plugin

**PlotSquared version:** PlotSquared v3.5.0-SNAPSHOT-95f8aaa
**ERROR: https://pastebin.com/LzFBSuwF**

--

**Comment by boy0001** [comment]
Make sure your MySQL database is functional.

**Comment by dordsor21** [comment]
If you're using something like db4free, expect this.
