### ISSUE TITLE
argument priorisation problem for /p tp

### ISSUE THREAD

**Issue by khlfkk** [IntellectualSites/PlotSquared#1691]
**Bug report **

paste link:
https://pastebin.com/Wg27wNnq

Description of the problem:
when visit the player claim  /p tp 7005151678
it caused exeception:(  java.lang.NumberFormatException: For input string: "7005151678" )

**Comment by boy0001** [comment]
Is that meant to be a player name?

**Comment by samueleycw** [comment]
yup, it is a player name called "7005151678". May i know is it don't support full number IGN?

**Comment by RedstoneFuture** [comment]
Yes. I get a error too. ^^
"An error occured: For input string: 005151678"

https://namemc.com/profile/7005151678.1

**Comment by Opachl** [comment]
I will have a look to this. :)

Bug is reproducible. I try to find a Solution.

I will try change the code in that way that it always asumes this fallbackorder:
-> Playername -> Alias -> world -> id

Additional as the Player is unkown (means never played on the Server) will result assuming it as id. See Fallbackorder. For this special case we will catch the NumberFormatException and convert it to a normal console warning message.
