### ISSUE TITLE
Feature Request: Configurable Center (x0, z0)

### ISSUE THREAD

**Issue by mrcoffee1026** [IntellectualSites/PlotSquared#1694]
Problem: Every "world" generates with the first plot having it's upper left most corner being at x0, z0.  This is unfortunate.  If you are to create a map (take blank map and head to center of plot and right click it), it will create a 128x128 image of what's underneath it.  This plot plugin would be ideal for setting up plots/claims to very large areas such as 128x128 plots, but without being able to adjust the "center" point, a world created with 128x128 plots creates maps that slices every plot into four pieces.

**How to replicate:** 
Set plot size + 1/2 road size = 128x128 and generate new world.  Stand at x0, z0 and right click an empty map and notice the giant "+" that you've just created.

*Need to be able to offset the plot 0:0 corner generation point to x-64, z-64 So players can claim entire plots that are the appropriate map-size and placement, and then this world would be dedicated to the art maps and... there'll always be enough room since it just keeps generating more of them. 

Thanks for you r consideration.

**Comment by boy0001** [comment]
Set the `road.offset.x` and `road.offset.z`.

**Comment by mrcoffee1026** [comment]
Since this is not a value included in this file, where does it go?  Under roads?  Like this?

    road:
      width: 0
      height: 0
      block: 0:0
      road.offset.x: -64
      road.offset.y: -64

**Comment by boy0001** [comment]
```yml
    road:
      width: 0
      height: 0
      block: 0:0
      offset:
        x: -64
        z: -64
```

**Comment by mrcoffee1026** [comment]
Perfect, thank you very much :D
