### ISSUE TITLE
Plot Owners Reset After Server Restart

### ISSUE THREAD

**Issue by bluedevils462** [IntellectualSites/PlotSquared#1695]
**Debug paste link:** 
https://pastebin.com/FnYQmzwa

**Description of the problem:** 
After restarting or reloading the server, all plot's owners are reset and the plot will then have no owner. Merged plots stay merged and builds don't disappear but the user has to re-claim the plot each time.

**How to replicate:** 
To check to see if the bug was still prevalent after reinstalling, I created a plotworld, claimed a plot, reloaded, and the plot owner was missing.

**Comment by boy0001** [comment]
Do not use `/reload`

**Comment by bluedevils462** [comment]
"After restarting OR reloading". It still has the same problem after a server restart.

**Comment by boy0001** [comment]
Please update the plugin and run debugpaste again.

**Comment by Cobwebster** [comment]
We have the same issue, latest version. 

We get this error on restarting but no actual errors ingame, plot owners will randomly switch but usually gets fixed upon restarting..

31.08 00:55:44 [Server] WARN java.lang.NullPointerException
31.08 00:55:44 [Server] WARN at com.intellectualcrafters.plot.database.SQLManager.validateAllPlots(SQLManager.java:3070)
31.08 00:55:44 [Server] WARN at com.intellectualcrafters.plot.database.DBFunc.validatePlots(DBFunc.java:79)
31.08 00:55:44 [Server] WARN at com.intellectualcrafters.plot.PS.disable(PS.java:1576)
31.08 00:55:44 [Server] WARN at com.plotsquared.bukkit.BukkitMain.onDisable(BukkitMain.java:236)
31.08 00:55:44 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
31.08 00:55:44 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344)
31.08 00:55:44 [Server] WARN at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424)
31.08 00:55:44 [Server] WARN at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417)
31.08 00:55:44 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:350)
31.08 00:55:44 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:486)
31.08 00:55:44 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:701)
31.08 00:55:44 [Server] WARN at java.lang.Thread.run(Thread.java:748)

**Comment by RedstoneFuture** [comment]
Still a issue?

**Comment by RedstoneFuture** [comment]
@Cobwebster @bluedevils462 After this long time: is this fixed? Have you find a solution?
