### ISSUE TITLE
People are stealing items from chests with lightning

### ISSUE THREAD

**Issue by kamileks999** [IntellectualSites/PlotSquared#1696]
**Debug paste link:** https://hastebin.com/anazojinax

**Description of the problem:** 
People are stealing items from chests with lightning.

**How to replicate:** 
When thief find chest, he click on them with lighter and can steal items.

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by kamileks999** [comment]
Hi, what about my problem?

**Comment by dordsor21** [comment]
I think it'd help if you were a bit more explicit as to what's happening

**Comment by Opachl** [comment]
Hi i try to reproduce it serveral times. I cant replicate it.
Can you try to reproduce it in a clean install without any other addons.

Is your problem still available in the latest version? Update if you are not running the latest version see this link: https://ci.athion.net/job/PlotSquared/lastStableBuild/

**Comment by RedstoneFuture** [comment]
@kamileks999 Hello. Have you still this problem.
