### ISSUE TITLE
It is possible to disable some plots for claiming?

### ISSUE THREAD

**Issue by Behoston** [IntellectualSites/PlotSquared#1698]
I have creative server and I want to disable 4 plots from claiming because I use they as spawn and minigames. Already I claimed this plots and works fine for spawn but not for minigames -players can't build, use, etc on spawn area. 
Even workaround like make region using WorldGuar will be enough for me.

**Comment by RedstoneFuture** [comment]
No, I think the best way for this situation is to develop a plotsquared addon (baded of the plotsquared API) for you minigame plot.

**Comment by RedstoneFuture** [comment]
But sorry for this long time without a answere. The developer of P² have many to do.
