### ISSUE TITLE
Save world before unloading

### ISSUE THREAD

**Issue by braceyourself07** [IntellectualSites/PlotSquared#1704]
**Debug paste link:** 
https://hastebin.com/ebayebusaz

**Description of the problem:** 
This is for PlotSquared with worlds enabled.  When players place blocks and immediately log out, the blocks do not get saved when the world unloads if no one is in them.  Could you trigger a world save before unloading?

**How to replicate:** 
Place blocks and immediately log out.  When you return, the blocks are not there.

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
Cannot replicate, tried P2 plotworld, server without P2, and P2 managed flatworld. Does it happen with everyone on the server? Possibly lag/another plugin that deals with world loading. It's likely the block-place isn't getting placed into memory to be flushed/saved to disk whenever the next world save is scheduled. If it's after using an anvil command, try a /save-all and retry.

**Comment by braceyourself07** [comment]
It's rare and so far it's been 2-3 of the same people complaining.  Doesn't occur with the vast majority of players so it may be lag related.  PlotSquared flatworlds are the only world management that we have.  I'll keep investigating and actively asking players if they are experiencing this.  Thanks, dords, for being thorough in trying to replicate it.  Hopefully I can report back with more concise information.

**Comment by braceyourself07** [comment]
I had one of the players this happens to attempt to replicate it.  The first time, he placed several blocks in a row very quickly, then logged out.  Upon returning, 15 blocks or so were missing.  The second time he did it, all of the blocks saved. 

Here is a log of the two attempts to replicate: https://hastebin.com/ujinudivux.md

I don't see any difference between the two, so I'm kind of at a loss what situations cause it.  He says he has a <90ms ping.

**Comment by braceyourself07** [comment]
Running PlotSquared v17.09.01-24b3b60-1908 (build 506).  This issue still occurs.  It's hard to reproduce and notice since it only affects the most recently placed blocks and immediately quitting or switching servers.  Player said that it seemed that 'random' chunks were not saved before unloading.  Player was building and went to go check something by switching bungee servers and came back and parts of his build were missing.

Could FAWE be holding some chunks in memory after a worldedit while the world unloads before it can save? Although the player who reported it said that things were missing that were both hand placed and worldedited. Could there be a way to add an unload delay or force a world save?

**Comment by dordsor21** [comment]
Not seen this happening^

Are you using paperspigot?

**Comment by braceyourself07** [comment]
Yep, it's paperspigot build 1192.  Will be updating to latest build soon.

**Comment by dordsor21** [comment]
hmm, not sure why you're seeing it and I'm not then.

**Comment by braceyourself07** [comment]
That's what is so difficult tracking this down.  I have not be able to reproduce it myself, just reporting when it happens to certain players.  The last one who reported it though, today, was not one of the original who reported the bug.

**Comment by boy0001** [comment]
I could try an additional world save

**Comment by braceyourself07** [comment]
Maybe that would work, just to force a save before unloading.  I don't suppose doing that would be detrimental to server performance  unless there are a huge number of unloadings occuring which seems unlikely unless it's the busiest of servers.  Or could make it a configurable option in settings.yml?

**Comment by boy0001** [comment]
It would be detrimental. Currently it unloads and saves only a few chunks at a time, whereas a full world save has to save everything at once.

**Comment by braceyourself07** [comment]
Could you add that as an option in settings.yml and I could try it?  When I do /save-all I don't see any decrease in performance.
