### ISSUE TITLE
World plots as principal

### ISSUE THREAD

**Issue by xclaudioh** [IntellectualSites/PlotSquared#1706]
Hi, I have a problem

The problem is that I can not operate my world of plots as the main world. I tried changing the name of the world in the server.properties but the plugin no longer works when doing that. But if I return to the world of plots as a secondary if it works and that's what I do not understand. 

I would appreciate it if you could help me.

Sorry for my english.

**Comment by dordsor21** [comment]
Not really something fixable in P2. Add the world in bukkit.yml under worlds.<world> then add worlds.<world>.generator: PlotSquared . For help see https://bukkit.gamepedia.com/Bukkit.yml
