### ISSUE TITLE
ArrayIndexOutOfBoundsException when generating road

### ISSUE THREAD

**Issue by mariolars** [IntellectualSites/PlotSquared#1707]
# Bug report template 

**Debug paste link:** 

https://hastebin.com/uzovoqesot

**Description of the problem:** 

Problem appers when i'm trying to generate custom road. Not sure if this problem is generated by custom plot schamtic but i wanted to mention that.

**How to replicate:** 

Following wiki instruction how to generate road. I can post plot schamtic somewhere if it's important.

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
