### ISSUE TITLE
WorldEdit can affect roads between two plots owned by the same player after unlinking them

### ISSUE THREAD

**Issue by BlackBeltPanda** [IntellectualSites/PlotSquared#1708]
# Bug report template 
**Debug paste link:**
https://pastebin.com/raw/HcQXFU9p

**Description of the problem:** 
Players can use worldedit to alter the roads between two plots they own after merging and then unlinking them.
Screenshot 1: https://i.gyazo.com/a2e1b0210105c4d76bb1fa7dab4fc869.png
Screenshot 2: https://i.gyazo.com/9fa1f0b42c910041fe9ca2a85e5716b7.png

**How to replicate:** 
Claim two plots next to each other. Merge them and then unlink them. Select an area that spans both plots. Then, use worldedit to perform some action, like setting the area to air.

**Checklist**:
- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
