### ISSUE TITLE
31.08 00:55:44 [Server] WARN java.lang.NullPointerException 

### ISSUE THREAD

**Issue by Cobwebster** [IntellectualSites/PlotSquared#1709]
Latest PlotSquared, when restarting.

31.08 00:55:44 [Server] WARN java.lang.NullPointerException
31.08 00:55:44 [Server] WARN at com.intellectualcrafters.plot.database.SQLManager.validateAllPlots(SQLManager.java:3070)
31.08 00:55:44 [Server] WARN at com.intellectualcrafters.plot.database.DBFunc.validatePlots(DBFunc.java:79)
31.08 00:55:44 [Server] WARN at com.intellectualcrafters.plot.PS.disable(PS.java:1576)
31.08 00:55:44 [Server] WARN at com.plotsquared.bukkit.BukkitMain.onDisable(BukkitMain.java:236)
31.08 00:55:44 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
31.08 00:55:44 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344)
31.08 00:55:44 [Server] WARN at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424)
31.08 00:55:44 [Server] WARN at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417)
31.08 00:55:44 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:350)
31.08 00:55:44 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:486)
31.08 00:55:44 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:701)
31.08 00:55:44 [Server] WARN at java.lang.Thread.run(Thread.java:748)

**Comment by Cobwebster** [comment]
We also get plot owners randomly switching on occasion. Any support would be appreciated.

**Comment by Cobwebster** [comment]
bump

**Comment by Sauilitired** [comment]
Replicated on Xisuma's plot server. In that case it was accompanied by
```[12:20:10] [Server thread/INFO]: All DB transactions during this session are being validated (This may take a while if corrections need to be made)
[12:20:10] [Server thread/INFO]: PLOT #22213(null;-44;70) in `plot` is a duplicate. Delete this plot or set `database-purger: true` in the settings.yml.
[12:20:10] [Server thread/INFO]: PLOT #23567(null;-37;12) in `plot` is a duplicate. Delete this plot or set `database-purger: true` in the settings.yml.```

Solution would be to ignore the null values gracefully, as they have already been validated.

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
