### ISSUE TITLE
Bone Meal bug

### ISSUE THREAD

**Issue by DeveloperMaD** [IntellectualSites/PlotSquared#1712]
# Bug report template 

**Debug paste link: https://hastebin.com/ucukumelub 

**Description of the problem: I have a problem with bone meal. I'am Admin and I have OP, so I have all permissions. I decide to build spawn on plot world. I didn't find any command to delete for ever specific plot, so I just change visual look of plots for the needs of my spawn. I can build on it everything is okay, but I can't use bone meal on them. I mean: I can't make grass on grass block, I can't make trees grow up with bone meal. I see only animation while I'm using bone meal. Is it bug, or I have to use command/change something in plugin files?

**How to replicate:** 

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
Have you still this problem? Or can it closed?

**Comment by DeveloperMaD** [comment]
Yes, I still have it :p
I don't found any line in config files which can be the problem :/

2017-11-19 0:57 GMT+01:00 Robert Rauh <notifications@github.com>:

**Comment by RedstoneFuture** [comment]
And if you disable all other plugins? With a permission system you haven't wit guarantee all permissions with only op. What messages do you get?

**Comment by Luskaas** [comment]
I'm here to save your lives!
Just you are inside a plot claimed =D.

**Comment by DeveloperMaD** [comment]
Hello,
Sorry for no reply, I was checking without plugins one by one ;)
I will try this on claimed plot, nonclaimed and on the road and I will
message You ;)

22.11.2017 5:02 PM "Luskaas" <notifications@github.com> napisał(a):

**Comment by DeveloperMaD** [comment]
Okay it working :D
Thanks for help, You can close my ticket on GitHub.

22.11.2017 5:21 PM "Maciek Działo" <mdzialo05@gmail.com> napisał(a):
