### ISSUE TITLE
Worldedit not working on plots!

### ISSUE THREAD

**Issue by HFinner** [IntellectualSites/PlotSquared#1715]
**Description of the problem:** 
Hi! So my server has an issue where people can't use WorldEdit in their plot. All it gives them is, "You are not permitted to do that, are you sure you are in the right mode?" I don't have worldedit.* taken away from people in my PEX, but I don't want to give them the perm because I also run a survival world on the same server. I also tried giving them the worldedit bypass perm for PlotSquared but nothing. Please help!

**Comment by bonnedav** [comment]
I think that you do need to grant worldedit.* in PEX. But you can use per word perms so that they only have it in the plot world and not in the survival world.

**Comment by RedstoneFuture** [comment]
https://github.com/boy0001/FastAsyncWorldedit/wiki/Permissions
