### ISSUE TITLE
Tile Entities freezing in Plotworld - Reproduced!

### ISSUE THREAD

**Issue by alexmarkey** [IntellectualSites/PlotSquared#1716]
# Bug report template 

https://hastebin.com/wukixafigu

When a player clears a plot which has tile entities on it, it causes all other tile entities in the plotworld in loaded chunks to freeze (Hoppers stop transferring items, furnaces stop smelting, spawners stop spawning, beacons stop working, etc).
The only way to unfreeze the tile entities is by unloading then reloading the chunks.  

According to the changelogs, this bug was fixed in Dev Build #493 http://ci.athion.net/job/PlotSquared/493/ however we are still reproducing in #506.

https://www.youtube.com/watch?v=9D7inwYYXiw&feature=youtu.be
- Claim 2 plots next to each other,
- On plot 1 place a furnace smelting some ores
- On plot 2 place some more random furnaces
- Use /plot clear whilst standing on plot 2 (Ensure plot 1 is in loaded chunks)
- The furnace on Plot 1 has now frozen, along with all other tile entities in loaded chunks in the plotworld (hoppers, spawners, beacons, etc)

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
