### ISSUE TITLE
./ps create/setup completely broken - crashes server.

### ISSUE THREAD

**Issue by dordsor21** [IntellectualSites/PlotSquared#1719]
https://hastebin.com/dotixaxuli.sql

(the usual `/ps setup PlotSquared` rather than `PlotSquared:single` doesn't exist)

**Comment by dordsor21** [comment]
If you delete the world folder, then restart the server, you can enter it just fine, but it's all default values (there's no way to setup a plot world from in-game anymore)

**Comment by dordsor21** [comment]
Config: https://hastebin.com/videhuyuxe.bash
Worlds: https://hastebin.com/xedesafeta.sql

**Comment by Sauilitired** [comment]
Is this still a problem? Because I cannot seem to replicate it.

**Comment by dordsor21** [comment]
I would presume this doesn't happen anymore
