### ISSUE TITLE
/plot rate next sends you to plots you've already rated

### ISSUE THREAD

**Issue by dordsor21** [IntellectualSites/PlotSquared#1720]
What titles says. In order to continue from where you left off, you need to hit `plot rate #` which tells you you've rated the plot already be able to `plot rate next`. You then have to go and do this as many times as you've done it before to get to plots you've not before rated without flying around randomly.

**Comment by AeSix** [comment]
I'm not sure this is an issue any longer. 
I've been testing it and have not revisited a plot. 

Tested with build 136 for 1.13.2

**Comment by AeSix** [comment]
I've re-tested this and after about 20 plots, did not come across one which I had already rated.

1.13.2 / P2 4.184

**Comment by RedstoneFuture** [comment]
@dordsor21 Is this still a issue?

**Comment by AeSix** [comment]
I don't believe this is an issue any longer, and if it is it's a new issue affecting builds newer than what I'm using.  Closing.
