### ISSUE TITLE
Worldedit in other worlds

### ISSUE THREAD

**Issue by SteveKitten** [IntellectualSites/PlotSquared#1721]
The plots work amazingly and players with Builder rank are able to use worldedit just like I intended. I am moving a world from my second server that many players have built on (flatworld) and I would like Builders to be able to use worldedit in that world as well.

I have done multiple things but from what I can tell, the plots permissions are global and make it so that players are not able to use world edit in non-plot worlds.

Thank you for your help if you can help me!

**How to replicate:** 
Nothing to replicate.

**Checklist**:

- [<3] I included a `/plot debugpaste` link
- [<3] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [<3] I made sure I am using an up-to-date version of PlotSquared
- [<3] I Made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
https://github.com/boy0001/FastAsyncWorldedit/wiki/Permissions

**Comment by RedstoneFuture** [comment]
Have you still a problem? Or would you like close this issues?
