### ISSUE TITLE
Can't warp after deleting plot

### ISSUE THREAD

**Issue by DeCypherCR** [IntellectualSites/PlotSquared#1725]
**Debug paste link:** 
https://hastebin.com/odemesatud

**Description of the problem:** 
Players can't /warp, /world tp, or use /spawn after deleting plots. To correct this issue, one needs to disconnect and reconnect to be able to warp.

**How to replicate:** 
1. Claim plot (/plots claim).
2. Delete plot (/plots delete)
3. Try warping.

**Edit:**
On a related note, when a plot is deleted, players become invisible.

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
It's no normal and I think this is not a problem of Plotsquared. Have you no errors?
