### ISSUE TITLE
Enabling spawn eggs and breading on plots

### ISSUE THREAD

**Issue by Dinoosawruss** [IntellectualSites/PlotSquared#1727]
# Bug report template 

**Debug paste link:** 
None (Not needed)

**Description of the problem:** 
I am woundering if it is possible for me to allow spawn eggs and breading on people's plots. If it is that would be amazing but if not then please could you add it

**How to replicate:** 

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
You can allow or disabled the using of eggs or define the Flag "mob-cap", "animal-cap" / "hostile-cap" or "hostile-interact".

Does it help you?

https://github.com/IntellectualSites/PlotSquared/wiki/Flag:-mob-cap
https://github.com/IntellectualSites/PlotSquared/wiki/Flag:-animal-cap
https://github.com/IntellectualSites/PlotSquared/wiki/Flag:-hostile-cap
https://github.com/IntellectualSites/PlotSquared/wiki/Flag:-hostile-interact
https://github.com/IntellectualCrafters/PlotSquared/wiki/Flag:-use

**Comment by RedstoneFuture** [comment]
@Dinoosawruss Any questions or would can it closed?
