### ISSUE TITLE
Signs high above plot and redstone flag

### ISSUE THREAD

**Issue by elderlabs** [IntellectualSites/PlotSquared#1730]
**Description of the problem:** 
Signs are spawning in the air a few dozen blocks above the plot, and upon running /p claim, the player is teleported to the level of the sign. I think there's a typo in commit `92f94ecedc712425b7bcb94d6f811134d142be7c`

**How to replicate:** 
Use build 518, commit `92f94ecedc712425b7bcb94d6f811134d142be7c`.

**Checklist**:

- [ ] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by braceyourself07** [comment]
Mine started doing that too, but I haven't updated to the latest build yet.

https://shareit.d3v.no/storage/uploads/4/ApplicationFrameHost_2017-09-30_18-36-19.png

**Comment by braceyourself07** [comment]
Updated to latest build, still spawns plot signs a block higher than normal

**Comment by elderlabs** [comment]
Mine spawned at block 160. The version before that they spawned the way you're describing, which I can live with. What I can't live with is the fact that the redstone flags break all redstone on the server, but that's an error for another day. Seems to not be able to "see" the difference between online and offline.On Oct 1, 2017 4:22 PM, Mike <notifications@github.com> wrote:Updated to latest build, still spawns plot signs a block higher than normal

**Comment by RedstoneFuture** [comment]
Hi. Have you still this problem with the sign (or the redstone)?

**Comment by braceyourself07** [comment]
I'm using version PlotSquared-17.11.18-f27b12a-1938 and the sign appears to be working normally.

**Comment by RedstoneFuture** [comment]
So all works? Would you like close the issues?

**Comment by RedstoneFuture** [comment]
And at @elderlabs  ?

**Comment by braceyourself07** [comment]
Fine with me, I'm not OP so I can't close the issue.

**Comment by RedstoneFuture** [comment]
I will test the redstone flag at soon.

**Comment by RedstoneFuture** [comment]
The redstone flag work good.
