### ISSUE TITLE
No free plots. (/p auto not working)

### ISSUE THREAD

**Issue by kamkom21** [IntellectualSites/PlotSquared#1734]
Description of the problem:
When player uses command /p auto, he gets "[P2] There are no free plots available".
Only plot with id 11;11 is free and can be claimed using this command.
All free plots can be claimed using command /p claim.
In database there are no claimed plots (and when using command /p info there is info that the plot is not claimed).

**Comment by boy0001** [comment]
Please follow the issue template and include a `/plot debugpaste`.
