### ISSUE TITLE
No free plots. (/p auto not working)

### ISSUE THREAD

**Issue by kamkom21** [IntellectualSites/PlotSquared#1736]
**Debug paste link:** 
https://hastebin.com/ihacoyoxel

**Description of the problem:** 
Description of the problem:
When player uses command /p auto, he gets "[P2] There are no free plots available".
Only plot with id 11;11 is free and can be claimed using this command.
All free plots can be claimed using command /p claim.
In database there are no claimed plots (and when using command /p info there is info that the plot is not claimed).
**Checklist**:

- [x] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
have you still this problem?
