### ISSUE TITLE
AutoMerge + Merge command bug

### ISSUE THREAD

**Issue by Legoman99573** [IntellectualSites/PlotSquared#1738]
**Debug paste link:** 
https://hastebin.com/aqogekavug

**Description of the problem:** 
AutoMerge doesnt work when you go up 1 and when you try to merge from where you are facing, it only removes that part of the road and doesn't check surrounding plots.

**How to replicate:** 
Video shows how to replicate it.
https://youtu.be/ssKtTBLqJNI

**Checklist**:
- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by MegaNarwhal** [comment]
I have `auto_merge` set to false for all my worlds and this still happens.

**Comment by RedstoneFuture** [comment]
Hello. I have test it and currently `auto_merge` is working. With `false` it will not merge automatically and with `true` it merge automatically.
Can you test it at your server with the currently version?

**Comment by RedstoneFuture** [comment]
@MegaNarwhal Have you still a problem with this?

**Comment by RedstoneFuture** [comment]
Reopen it or open a new issue, if you have still a problem. :)
