### ISSUE TITLE
PlotMergeEvent and PlotDeleteEvent never get called

### ISSUE THREAD

**Issue by Jonodonozym** [IntellectualSites/PlotSquared#1739]
# Bug report template 

Description:
It seems like the PlotMergeEvent and PlotDeleteEvents never get called on bukkit servers.

How to replicate:
Create a new plugin depending on PlotSquared, add a new listener which listens to those two events and prints something to the console when those events are called. Then merge or delete plots, and notice the print message never happens.

I looked through the source code of PlotSquared to make sure it wasn't me stuffing it up. In the Plot class, EventUtils.manager.callMerge or callDelete aren't called when the plot is merged, automerged or deleted, unlike the claim event for example which is called using callClaim

debugPaste:
https://hastebin.com/iyopajeyuw

**Comment by Legoman99573** [comment]
Automerge may be linked to the issue with #1738 where its not called in plotsquared itself. Had this issue several builds ago.

**Comment by dordsor21** [comment]
Fixed in 446c47d
