### ISSUE TITLE
/p h teleports players to a different world

### ISSUE THREAD

**Issue by MAnoDew** [IntellectualSites/PlotSquared#1741]
Hi P2,

I'm having an issue with P2.
When players want to go to their plot on world 'Creative',
they will be teleported to world 'world'. 
I don't have any plugins which are causing this error.

Regards,
MAnoDew

(idk but I was to lizy to follow the issue template 😋)

**Comment by Sauilitired** [comment]
As you didn't submit a `/plot debugpaste` it is impossible to know whether you have a plot area setup in "world" as well. In that case:
