### ISSUE TITLE
¿signs? 1.12

### ISSUE THREAD

**Issue by NeruFox** [IntellectualSites/PlotSquared#1742]
Hi, i have a problem with PlotSquared, the word that i created to do the Plots, when i try to claim, the sign doesn't appear, i wanna use the sign instead of the title, How can i make the sign appear?

**Comment by Legoman99573** [comment]
Make sure title is set to false and signs are set to true.

When you visit the plot, should be on your right at the end like plotme does.

**Comment by NeruFox** [comment]
I already have the titles disabled, but I do not see any option to activate the signs.

**Comment by Sauilitired** [comment]
In `worlds.yml`:

```yaml
worlds:
  <world name>:
       create_signs: true
```
