### ISSUE TITLE
Saving and Loading Merged Plots Not Working

### ISSUE THREAD

**Issue by BlackBeltPanda** [IntellectualSites/PlotSquared#1747]
**Debug paste link:** 
https://pastebin.com/raw/CFX3wb5U

**Description of the problem:** 
Saving and loading merged plots doesn't seem to work.
If you save a merged plot, unmerge the plot, then re-merge the plot and attempt to re-load it, it results in the error, "Schematic is too large. (50,119,257) is bigger than (49,118,256)"
If you save a merged plot and immediately re-load it, it results in this error: https://pastebin.com/raw/ge6yKbfF and prints "That is not a valid schematic. Reason: non-existent or not in gzip format" in-game.
Sometimes when using "/plot load #", it just prints "Please use /plot load to get a list of schematics", even with a valid number given.

**How to replicate:** 
1. Merge two plots.
2. Use "/plot save" to save them.
3. Unmerge the plots.
4. Merge the plots again.
5. Use "/plot load #" to load the saved plot.
or
1. Merge two plots.
2. Use "/plot save" to save them.
3. Use "/plot load #" to load the saved plot.

**Checklist**:
- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by IAlekseyI22** [comment]
Cool!

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
