### ISSUE TITLE
mobspawner in plot

### ISSUE THREAD

**Issue by SkelletonX** [IntellectualSites/PlotSquared#1748]
how can I activate mob for generators to be born in the plot world?

**Comment by SkelletonX** [comment]
my world guard config world plot

regions:
    __global__:
        members: {}
        flags: {invincible: allow, mob-spawning: allow}
        owners: {}
        type: global
        priority: 0

**Comment by boy0001** [comment]
In `plugins/PlotSquared/config/worlds.yml`, change `mob_spawner_spawning` to true.
