### ISSUE TITLE
Schematics In Plots

### ISSUE THREAD

**Issue by GalHorowitz** [IntellectualSites/PlotSquared#1752]
Hey, I have a question. How could I go about configuring plotsquared so that plots would be generated with a schematic on them. So that they would have the schematic on them before someone claims the plot. Also, I need to be able to support multiple schematics that would be chosen randomally for each plot. Is there built in functionality for this? Are there addons/world generators which add this functionality? If not, should I create a custom world generator, and if yes, how would I go about creating one, is there an API for this sort of thing?

**Comment by GalHorowitz** [comment]
Hey @Sauilitired would you know the answer?

**Comment by Gohu29** [comment]
https://github.com/IntellectualSites/PlotSquared/wiki/Usage:-Schematic-on-claim

**Comment by Sauilitired** [comment]
> Also, I need to be able to support multiple schematics that would be chosen randomally for each plot. Is there built in functionality for this?

No. But, instead of creating a custom world generator it'd be easier to just add an option for this. If you're up for it, then feel free to create a pull request :smile:
