### ISSUE TITLE
Vehicles cancel out PlotLeave and PlotJoin events

### ISSUE THREAD

**Issue by Legoman99573** [IntellectualSites/PlotSquared#1754]
**Debug paste link:** 
https://hastebin.com/yelegamelo

**Description of the problem:** 
When you ride a minecart off of a plot and onto another plot, it doesnt trigger PlotLeave or PlotJoin events until you hop out of a vehicle and move around on another plot.

**How to replicate:** 
Video shows how to reproduce, but its really easy to replicate.
https://youtu.be/LSPWk3AFM8k

*In before i get the allow killing road vehicles, i do have a plugin that requires it to be disabled.*

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by Legoman99573** [comment]
Plus @boy0001, would like to request a feature involving vehicle enter/leave plot events as it would be cool to have plots cancel vehicles from leaving if they are in a vehicle or minecart.

**Comment by Sauilitired** [comment]
This could probably be fixed by just replicating the behavior of `playerMove(PlayerMoveEvent` in `PlayerEvents` for `VehicleMoveEvent` 🐮 

Though, according to (old) bukkit, PlayerMoveEvent is supposed to fire when a player moves inside of a vehicle as well.

**Comment by Legoman99573** [comment]
PlayerMoveEvent has had a lot of issues in the past. Should have been deprecated by now for vehicles as they don't fire properly.
