### ISSUE TITLE
Multiple PlotSquared worlds on same server

### ISSUE THREAD

**Issue by ethamitc** [IntellectualSites/PlotSquared#1755]
# Bug report template 

**Debug paste link:**  It would print, running the command dosnt do anything

**Description of the problem:** 
I have an Aternos server that is going to have to creative plot worlds, however, when I'm in cFire, and i say /p h, it most of the time takes me to my owned plot on cWater, i do own a plot in cFire!

**How to replicate:** create two worlds, claim a plot in both, then go to the one that you created second, then run /p h

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by Sauilitired** [comment]
The command (`/plot h`) is able to take in an extra argument, that specifies the plot area (in this case; world). Like: `/plot h <world> [#]`. This allows you to teleport to plots in other worlds/plot areas.
