### ISSUE TITLE
wrong plot ID after plot auto

### ISSUE THREAD

**Issue by iTaeyeonKim** [IntellectualSites/PlotSquared#1758]
Hello. I am a moderator on one server with plotsquared.* permission. When I wanter another 37th plot, I just did /plot auto and then my plot ID was -7434;17383 for no reason. I don't even know how did this happend. Our server didn't even go after 400;400 plots, so this is weird

**Comment by Sauilitired** [comment]
Has anyone else been able to replicate this issue? There is very little information provided and I cannot seem to replace it myself.
