### ISSUE TITLE
Interaction flag with item_frame

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquared#1761]
Hi. I search the flag for the interaction with a item_frame. Have PlotSquared a flag for this?

**My normal player would like allow the interaction of a item_frame in your plots.**

with or without the flag Flag "use": -> "You down't have permission **plots.admin.interact.other**"

**How to replicate:** 

1. /p claim
2. set a item_frame of this plot
3. a second user will interact with this item_frame -> "You down't have permission **plots.admin.interact.other**"

**Checklist**:

Serversoftware: Paper version git-Paper-1209 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by Sauilitired** [comment]
Try the flag `misc-interact`

**Comment by RedstoneFuture** [comment]
Ah, thanks. What allow all "misc-interact" ? The Wiki-side is still in works. https://github.com/IntellectualSites/PlotSquared/wiki/Flag:-misc-interact

**Comment by RedstoneFuture** [comment]
EDIT: No, the flag `misc-interact` dons't allowd the interaction with item_frame at me. :(

**Comment by Opachl** [comment]
I solved the problem as suggested above. The feature is now bound to the flag misc-interact

Pull Request is pending:
[https://github.com/IntellectualSites/PlotSquared/pull/1766](url)

**Comment by Opachl** [comment]
@boy0001 can we close this Issue or is there more work todo ?
i can fix it too

**Comment by RedstoneFuture** [comment]
@Opachl I will test it soon und if it works I close this report.

**Comment by RedstoneFuture** [comment]
Ok, it works! :)
