### ISSUE TITLE
shulker-teleport in a other plot

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquared#1762]
Problem: **A user can teleport shulker from your plot to a next plot.**

**How to replicate:** 

1. spawn shulker on the border in your plot
2. remove the block under the shulker
--->  the shulker will teleport to a random position and thus in other plots
         (Currently the plugin can't remove the shulker, because ge down't go over the road.)

**Checklist**:

Serversoftware: Paper version git-Paper-1209 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by Legoman99573** [comment]
What version of plotsquared are you using, plus forgot to paste the debug paste. That helps developers alot.

Use `/p debugpaste`
