### ISSUE TITLE
player can destroy armor stands with fireworks (e.g. by elytra-flying)

### ISSUE THREAD

**Issue by xion87** [IntellectualSites/PlotSquared#1764]
Hi, i see that you make a bugfix about this issue, but players stil are able to destroy armor stand by using fireworks...

**Comment by RedstoneFuture** [comment]
At my server my user can't use fireworks in other plots, because fireworks are not listerd in the use-flag b default.

**Comment by RedstoneFuture** [comment]
Have you a link of the bugfix-post in github, that you mean, please?

**Comment by RedstoneFuture** [comment]
Can you test it with the latest version, please?

**Comment by RedstoneFuture** [comment]
If the user can build fireworks too ... the amorstands will not break in the latest version.

**Comment by RedstoneFuture** [comment]
![2018-07-01_11 33 53](https://user-images.githubusercontent.com/4140635/42132996-c4e09f68-7d22-11e8-8fd8-44a689fecfb8.png)

**Comment by xion87** [comment]
do this. https://www.youtube.com/watch?v=K1JOM9GoDT8&feature=youtu.be

**Comment by RedstoneFuture** [comment]
Oh, yes. With elytra you can activate rockety in minecraft and ... and destroy amor stands. Thanks.

**Comment by RedstoneFuture** [comment]
By the Way: you have this protection problem without PlotSquared too. :/

**Comment by xion87** [comment]
i don't know since i run only 1 creative server with 1.12.2, other server use old version of minecraft

**Comment by AeSix** [comment]
Using Paper 1.13.2 and P2 4.184, I am unable to replicate this.  I tested similar to original poster.  
Perhaps WorldGuard is protecting the stands.  

https://incendo.org/paste/view/01da0fa40e5443db87b4351fb1a570dd

**Comment by AeSix** [comment]
@RedstoneFuture @xion87 - is this still an issue for 1.12.2, and are either of you able to replicate the issue with 1.13.2/1.14.4? 
As I stated previously, I'm not getting the same result.  Maybe I'm doing it wrong.  Testing by someone who fully understands how to do it would be preferable.  

Thanks :)

**Comment by MattBDev** [comment]
I believe this is fixed so I will be closing this for now. I will reopen it if @RedstoneFuture or @xion87 say that they are still experiencing it.
