### ISSUE TITLE
Problems/Bugs with SlimeFun plugin

### ISSUE THREAD

**Issue by Ex-Infinityy** [IntellectualSites/PlotSquared#1765]
**_The slimefun plugin addons tree goes outside of plots._**
![2017-11-11_23 06 10](https://user-images.githubusercontent.com/33577181/32691275-abfca254-c737-11e7-9c6a-e76d9ba6b87d.png)

**Comment by RedstoneFuture** [comment]
https://dev.bukkit.org/projects/slimefun is not us project, but the restriction problem at trees are knowned.

https://github.com/IntellectualSites/PlotSquared/issues/1861
