### ISSUE TITLE
Generating world with schematic

### ISSUE THREAD

**Issue by DJIronic** [IntellectualSites/PlotSquared#1771]
Hello, 

I was linked here form Spigot to get support, co I will post my Question here.

I think it´s pretty simple. I need to generate a world with plots and schematic town. Just a flat plot world with town schematic as roads. How can I do it? And is it possible to regen the main world with it?

Thanks

**Comment by RedstoneFuture** [comment]
You must create a "plugins/PlotSquared/schematics/GEN_ROAD_SCHEMATIC/<worldname>" file with 2 schematics:

- intersection.schematic (= only one intersection; the generator; the hight must not 256 blocks ... use only the schematic-build hight e.g. 5 blocks)
- sideroad.schematic (= only one road between the schematics and between the intersection)

And than you use the "/plot debugroadregen" command.

Does it work that way?

**Comment by RedstoneFuture** [comment]
Other way: https://github.com/IntellectualSites/PlotSquared/wiki/Usage:-Schematic-on-claim

**Comment by Sauilitired** [comment]
https://github.com/IntellectualSites/PlotSquared/wiki/Installation#adding-road-schematics
