### ISSUE TITLE
Entitys on specific positions will not deleted after Plot clear

### ISSUE THREAD

**Issue by Opachl** [IntellectualSites/PlotSquared#1773]
# Entity not deleted after Plot clear

**Description of the problem:** 
After confirm Plot Clear some entitys will stay.

**How to replicate:** 
/p claim an plot
*you will be teleportet looking to the claimed plot
*move in sightdirection to the end of the plot
*place an entity i used shulkers in the last row. see below

X means plot border
P means Player position after claim
E means Entity (shulker)

XXXXXXXXXXXXXXX
X+++E+E+E++XX
X++++++++++X
X++++++++++X
XXXXXXPXXXXXXXX

now execute /p clear
and /p confirm the placed shulkers will not be deleted

The bug is located in BukkitChunkManager.java -> clearAllEntities(Location pos1, Location pos2)

Note after installing the plugin FastAsyncWorldEdit.jar it worked.

**Checklist**:
Serversoftware: Paper version git-Paper-1209 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Used Plugins: 
LuckPerms-Bukkit-3.4.15
Multiverse-Core-2.5.0
PlotSquared-Bukkit-17.11.19-27c2c6a-1939

- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
