### ISSUE TITLE
Users getting more plots than allowed

### ISSUE THREAD

**Issue by SrLeojaco** [IntellectualSites/PlotSquared#1781]
# Bug report template 

**Debug paste link:** 
https://hastebin.com/inuhaqineg

**Description of the problem:** 
When a user removes its plot, he can claim another new plot (because he has not more plots) but sometimes, at next startup, he'll have 2 plots (the removed one and the claimed one). Using this, I found an user with more that 100plots (max is 2)

**How to replicate:** 

1. Claim plot
2. Build
3. Delete/dispose
4. Claim new one (different)
5. Restart several times
6. Do /p list and you'll see 2 or more plots

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
I can't replicate this problem on my server.

**Comment by SrLeojaco** [comment]
It happens sometimes, but i had an user which got 127 plots and have lots of users (probably more than 10k) which have more than 2 plots

**Comment by SrLeojaco** [comment]
It isn't something that happens too much often so it's difficult to replicate.

Now I made a quick count on DB and have more than 1000 users having 4 plots... (maximum for user was 2 and i think i didn't have 1000 vips...) so it may not be solved.

Last time i had a report from server staff that received more plots was arround 1 month ago... Can't tell exactly if its happening now (i updated p2 a few days ago)

**Comment by SrLeojaco** [comment]
I get an easy way to do this...
https://youtu.be/fKDJQU2fTg8


I will add a command-delay to prevent it on my server, but that is not a good solution and must be fixed.


PS: Despite i opened the issue with another version, before trying this, i tested on 
PlotSquared-Bukkit-18.06.23-79e1ea9-2017

PS2: I tried on 3 different servers and it works
