### ISSUE TITLE
VoxelSniper painting on road/other plots

### ISSUE THREAD

**Issue by GuusLieben** [IntellectualSites/PlotSquared#1782]
**Debug paste link:** 
https://hastebin.com/igoqudofet

**Description of the problem:** 
Users are able to use VoxelSniper to paint outside of their plots, most other VoxelSniper actions are restricted, but the painting is not.

**How to replicate:** 
Execute /be e lift, /b e melt, /b over, etc.
Paint outside the plots (both claimed and unclaimed)

**Checklist**:
- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Versions:**
_Plugin-VoxelSniper-8.4.0
_Plugin-PlotSquared-Sponge-17.11.14-734c4bb-1937
_Mod-spongeforge-1.10.2-2477-5.2.0-BETA-2731
_Forge-1.10.2-12.18.3.2477-universal

**Comment by KourisBP** [comment]
Have you tried using FAVE? http://empcraft.com/fawe/latest.php?favs Pretty sure this controlls the voxel sniper not plot squared.

**Comment by KourisBP** [comment]
It's basically a FAWE addon

**Comment by guuslieben** [comment]
@KourisBP FAVE doesn't work on Sponge. It's a Spigot/Bukkit built plugin. I looked into it, tested it, no results.

**Comment by guuslieben** [comment]
> FAWE & FAVS for Bukkit/Spigot (All MC versions)

As seen here : https://github.com/boy0001/FastAsyncWorldedit/releases

**Comment by dordsor21** [comment]
If you still have this issue, reopen.

**Comment by GuusLieben** [comment]
Still experiencing this issue as FAVE is not yet compatible with Sponge, and thus VS still brushes outside Plot areas

**Comment by AeSix** [comment]
Does using WorldGuard help to prevent this?
AFAIK No one is working on Sponge related code for P2 or FAWE/FAVS.
