### ISSUE TITLE
NumberFormatted Exception

### ISSUE THREAD

**Issue by UnioDex** [IntellectualSites/PlotSquared#1785]
# Bug report template 

**Debug paste link:** 

https://hastebin.com/mabiyahatu

**Description of the problem:** 

> GuiSaCriFice issued server command: /p h : 2 LauraLive123
> [14:48:58 WARN]: java.lang.NumberFormatException: For input string: "LauraLive123"
> [14:48:58 WARN]:        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
> [14:48:58 WARN]:        at java.lang.Integer.parseInt(Integer.java:580)
> [14:48:58 WARN]:        at java.lang.Integer.parseInt(Integer.java:615)
> [14:48:58 WARN]:        at com.intellectualcrafters.plot.commands.Visit.execute(Visit.java:59)
> [14:48:58 WARN]:        at com.plotsquared.general.commands.Command.execute(Command.java:337)
> [14:48:58 WARN]:        at com.intellectualcrafters.plot.commands.MainCommand.execute(MainCommand.java:260)
> [14:48:58 WARN]:        at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:135)
> [14:48:58 WARN]:        at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:30)
> [14:48:58 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
> [14:48:58 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143)
> [14:48:58 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
> [14:48:58 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1194)
> [14:48:58 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1006)
> [14:48:58 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
> [14:48:58 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
> [14:48:58 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
> [14:48:58 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [14:48:58 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [14:48:58 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
> [14:48:58 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
> [14:48:58 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
> [14:48:58 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
> [14:48:58 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
> [14:48:58 WARN]:        at java.lang.Thread.run(Thread.java:748)

**How to replicate:** 

Use " /p h : 2 LauraLive123 " command.

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [ ] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by Sauilitired** [comment]
Fixed in PR #1778
