### ISSUE TITLE
Flag "no-worldedit" down work

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquared#1786]
**Description of the problem:** 
At my server I have problems with the flag "no-worldedit".

**How to replicate:** 
/p flag set no-worldedit true
=> all user can still work with WE

**Checklist**:
- Serversoftware: PaperSpigot 1.12.2
- [X] I made sure there are no duplicates of this report
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by Gonsda** [comment]
@boy0001

I am also having this issue as well!

**Comment by Raphy123** [comment]
same bug here
