### ISSUE TITLE
p visit issue in latest builds

### ISSUE THREAD

**Issue by Platinteufel** [IntellectualSites/PlotSquared#1791]
Since build https://github.com/IntellectualSites/PlotSquared/commit/06208696db6e3e050193206e309d0f864a12eeb7 the format `/p visit world;x;y` doesn't work anymore. `/p visit x;y` still works fine, but the first one is used by `/p list expired`.
Thanks so far!

**Comment by RedstoneFuture** [comment]
Right. We (I and @Opachl) rework this command. With the old syntax the command down't work alwasy with all corrects inputs. But it is not finish.

https://github.com/IntellectualSites/PlotSquared/pull/1778


use: /p h <world> + /p h <coordnate>

**Comment by Opachl** [comment]
Will work in the Next commit sorry for this issue

**Comment by RedstoneFuture** [comment]
It work at now. Would you like close this issues?

**Comment by Platinteufel** [comment]
Sure. Thanks! :)
