### ISSUE TITLE
Bad plot generation

### ISSUE THREAD

**Issue by HackerGamingCZ** [IntellectualSites/PlotSquared#1800]
Hello,
I was trying to make 5x5 plot world, but this happened. I tried this many times, getting the same result. Everything seems to work at sizes 6x6 or greater. Could you please fix it or say what I'm doing wrong? 

![2017-12-09_11 23 52](https://user-images.githubusercontent.com/31445261/33794827-f2c565a2-dcd3-11e7-9c3b-1e09f52b0cf7.png)

Thanks :)

**Comment by RedstoneFuture** [comment]
Ok.

May I ask: what you would like create? For which project do you use 5x5 plot? XD

**Comment by HackerGamingCZ** [comment]
That doesn't really matter. I think that everything should be possible. :)

**Comment by RedstoneFuture** [comment]
At my it works:

![2018-05-19_03 08 53](https://user-images.githubusercontent.com/4140635/40263404-0b96f4a8-5b12-11e8-8561-89b6207ed34e.png)



>   Test2:
>     plot:
>       height: 64
>       biome: FOREST
>       size: 5
>       filling:
>       - '1:0'
>       auto_merge: false
>       bedrock: true
>       create_signs: true
>       floor:
>       - '2:0'
>     wall:
>       filling: '1:0'
>       block_claimed: '44:1'
>       height: 64
>       block: '44:0'
>     misc_spawn_unowned: false
>     road:
>       block: '155:0'
>       height: 64
>       width: 7
>     home:
>       nonmembers: side
>       default: side
>     schematic:
>       specify_on_claim: false
>       on_claim: false
>       file: 'null'
>       schematics: []
>     economy:
>       prices:
>         merge: 100
>         sell: 100
>         claim: 100
>       use: false
>     chat:
>       enabled: false
>     limits:
>       max-members: 128
>     world:
>       max_height: 256
>       gamemode: creative
>       min_height: 1
>       border: false
>     event:
>       spawn:
>         egg: true
>         breeding: false
>         custom: true
>     natural_mob_spawning: false
>     mob_spawner_spawning: false
>     flags: {}
