### ISSUE TITLE
The /plot command conflicts with Towny's /plot command

### ISSUE THREAD

**Issue by Leomixer17** [IntellectualSites/PlotSquared#1802]
**Description of the problem:** 
The title says all.

**How to replicate:** 
- Install the plugin Towny
- Use the /plot command

**Comment by RedstoneFuture** [comment]
1. plotsquared use only the "/plotsquared" command:

- /plotsquared claim
- /plotsquared unclaim


2. For the towny command try it with the commands.yml definition:

Code (Text):
command-block-overrides: []
aliases:
  icanhasbukkit:
  - version $1-
  townyplots:
  -  towny:plot $1-
 

If I'm right (I havn't towny thus I can't test it.) than "/townyplots" owerride the "/plot"-command of towny!

- /townyplots claim
- /townyplots unclaim

**Comment by Sauilitired** [comment]
I don't quite understand what issue you're trying to report? Indeed, both plugins are using the `/plot` command. However, PlotSquared also uses `/plots` (actually the main command, all other versions are aliases), `/p`, `/ps`, `/plotsquared`, `/p2`, `/2`, `/plotme`.

And, as @RedstoneFuture mentioned, you are able to use the Bukkit command mapping to remap the commands if you want.

**Comment by Leomixer17** [comment]
@Sauilitired the problem is that PlotSquared uses the /plot command in the clickable text in chat
