### ISSUE TITLE
Baby ocelots spawn from eggs even if it is disabled

### ISSUE THREAD

**Issue by wasder** [IntellectualSites/PlotSquared#1803]
**Debug paste link:** 
https://hastebin.com/onivufesox

**Description of the problem:** 
Baby ocelots spawn from eggs even if  it is disabled in worlds.yml  ``` event.spawn.egg: false```

**How to replicate:** 
https://dl.dropboxusercontent.com/s/y2g94nmc9lwuazb/2017-12-10_17-50-23.mp4

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
Right. But this is the only one.
