### ISSUE TITLE
Roads non reseting on /p delete

### ISSUE THREAD

**Issue by xion87** [IntellectualSites/PlotSquared#1806]
People can't ruins road by:
1) Claim some plots and merge until you will see the road into plots. Edit the roaad with WE and do /p delete, road will stay as edited, and not reseted.

**Comment by RedstoneFuture** [comment]
Hi. I can't reproduce this problem. Can you get more information? Serversoftware, P²-Version, ... 

1. I claim 2 plots
2. after the merge the road has the plot-style
3. after the plot-reset all is as before


Can you get screenshots? :)

**Comment by xion87** [comment]
Using:
Paperspigot 1.12.2, latest protocollib, Plotsquared 543 from jenskin:
For reproduce the bug you have to claim  more than 2 plots
Here there is a screenshot when it happened
![index](https://user-images.githubusercontent.com/3611852/33875330-3d100900-df22-11e7-88ec-0c1383cedf11.jpg)

**Comment by braceyourself07** [comment]
That looks like an incomplete merge of 4 plots, not 2.

**Comment by RedstoneFuture** [comment]
You must use 3x the /merge command and than the complete plot is without a road. Than the regeneration after the delete-command is working.

**Comment by RedstoneFuture** [comment]
0. get 4 plots

![2018-04-28_21 53 50](https://user-images.githubusercontent.com/4140635/39400340-da088fa2-4b2e-11e8-8a5e-bf00afb34b94.png)

1. merge command

![2018-04-28_21 54 10](https://user-images.githubusercontent.com/4140635/39400345-e1e08806-4b2e-11e8-877f-82c131ebc38f.png)


2. merge command

![2018-04-28_21 54 30](https://user-images.githubusercontent.com/4140635/39400347-e5ceaf74-4b2e-11e8-9831-3e27bedf9fa7.png)

3. merge command

![2018-04-28_21 54 42](https://user-images.githubusercontent.com/4140635/39400348-ebe1ef02-4b2e-11e8-98ea-bbb2b493c052.png)
