### ISSUE TITLE
Teleport from sky

### ISSUE THREAD

**Issue by Feerko** [IntellectualSites/PlotSquared#1808]
Hello,
i have an issue with /p2 auto
when i type this i get fall from y: 256

[code]
    home:
      default: 49,8
      allow-nonmembers: true
      nonmembers: 49,8
[/code]

https://pastebin.com/raw/3nppzArX

/p2 home works normal and i get teleported to normal height.

**Comment by RedstoneFuture** [comment]
With "/p auto" plotsquared would like you teleport you to a valid position. But the complete world is consists of air.

**Comment by RedstoneFuture** [comment]
https://github.com/IntellectualSites/PlotSquared/issues/1369
