### ISSUE TITLE
Can't purge plots in deleted world

### ISSUE THREAD

**Issue by MrEminent42** [IntellectualSites/PlotSquared#1809]
Hello! 

**Debug paste link:** 
PlotSquared debug paste: https://hastebin.com/dexukujafa
Error when stopping server: https://pastebin.com/yunESnq8
Error when doing /p purge world:<deleted world>: https://pastebin.com/Y2c7t8xf

**Description of the problem:** 
I deleted a plotworld, but apparently the world is still in the plotsquared database. Unfortunately, when I use /p purge world:<deleted world>, it throws a NPE. The plugin also warns me (and throws an errror) about this deleted world still existing in the database. See pastebins above.

**How to replicate:** 
Untested, but here is what happened (I think):
- Create a plot-world
- Claim some plots
- Delete the plotworld using multiverse and then actually deleting the folder
- Try to purge using /p purge world:<world you deleted>

**Comment by braceyourself07** [comment]
Have you tried re-adding the world, purging, then deleting?

**Comment by MrEminent42** [comment]
I've tried creating a normal world then doing as you said but that didn't work. 

I'll try setting up a new Plotworld with the same name as the old world and doing that and see if it works.

**Comment by MrEminent42** [comment]
That worked! Thanks for the tips.
