### ISSUE TITLE
MoveEntityEvent error spam in console

### ISSUE THREAD

**Issue by GuusLieben** [IntellectualSites/PlotSquared#1810]
**Debug paste link:** 
https://hastebin.com/qeninifawi

**Description of the problem:** 
When chunks are loaded (also when they already exist) the console generates the following error :
https://pastebin.com/BHv4XR3a

**How to replicate:** 
Update to P2 version 17.12.09-59557cf-1945 (latest at the time of post)
Generate chunks by walking/flying around
Check console for said error message

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
