### ISSUE TITLE
Plot removing makes people die in void

### ISSUE THREAD

**Issue by xXBlazeCraftXx** [IntellectualSites/PlotSquared#1811]
https://hastebin.com/enisisegax

My players remove someone from their plot and the player who gets removed is teleported into the void and dies.

**Comment by RedstoneFuture** [comment]
Have you still this problem? Can you send a new hastebin-link, please?

**Comment by boy0001** [comment]
It should be teleporting them to the world spawn. If you have multiverse, try using `/mv setspawn`.
