### ISSUE TITLE
1 Beacon PER Plot

### ISSUE THREAD

**Issue by Inspectiver** [IntellectualSites/PlotSquared#1812]
Hi, to stop lag on my creative server, is there any way to only let players place one beacon per plot?

**Comment by RedstoneFuture** [comment]
mmh ... Currently you can define only a cap for mobs, animals, hostiles, vehicles or entitys in a plot. :/

**Comment by boy0001** [comment]
Performance reasons. Let's say you have a plot that's 512x512, or an entire world (using PlotSquared's world option). 

Checking for blocks is a lot more expensive than checking entities.

**Comment by RedstoneFuture** [comment]
@Inspectiver But you can set a world-flag like "place <block-id>" (https://github.com/IntellectualSites/PlotSquared/wiki/Flag:-place) and you can remove the permission to redefine this flag on her plot for the user.
