### ISSUE TITLE
Plots limit permissions doesn't work.

### ISSUE THREAD

**Issue by TheIntelloBox** [IntellectualSites/PlotSquared#1813]
Plots limit permissions doesn't work.

I gave the permissions : plots.plot.1000

**Comment by RedstoneFuture** [comment]
And I have never problems with the permission. What is wrong? More informations, please. :)

**Comment by TheIntelloBox** [comment]
If I set plots.plot.1000, the player cannot do /plot claim on 1000 plots.

**Comment by RedstoneFuture** [comment]
Can you test from when the permission system failed? (100, 500, or only at 1000+) At my server the permission is only to max. of 4 plots in a world. ^^

**Comment by boy0001** [comment]
It needs to be lower than the `max-plots` value in the settings.yml (line 98). So if you want players to be able to claim 1000 plots, then raise the value in the config.
