### ISSUE TITLE
Is sponge development abandonded?

### ISSUE THREAD

**Issue by lurr** [IntellectualSites/PlotSquared#1814]
As it currently looks, sponge development of PlotSquared is currently not underway. It also has many issues that occur; and need fixing. Is there any hope for a touchup in the near future?

This could include an update to SpongeAPI 7.0.0-SNAPSHOT in order to support newer builds of sponge (e.g. 1.12.2)

**Comment by N0tMyFaultOG** [comment]
@MattBDev are you on our discord? https://discord.gg/ngZCzbU 
CityMom wanted to know

**Comment by AeSix** [comment]
Closing due to question being answered.
