### ISSUE TITLE
server crash on /plot auto

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#1818]
using plotsquared build 536, FAWE 944, paperspigot build 1283

not sure if this is a plotsquared or FAWE issue so im putting issues for both

this has happened twice now: https://pastebin.com/fn4pAq4N

**Comment by RedstoneFuture** [comment]
Have you still this problem?

**Comment by PhanaticD** [comment]
not in a long time

**Comment by RedstoneFuture** [comment]
Good :)
