### ISSUE TITLE
Free and Paid limits

### ISSUE THREAD

**Issue by recon88** [IntellectualSites/PlotSquared#182]
I would like to suggest a new feature.
People on my server currently have a limit of 1 free plot (plots.plot.1 + economy disabled). I want them to be able to buy (not just autoclaim) additional plots but it looks like that's not possible currently.
I either have to give them all plots for free or charge for all plots.

**Comment by MattBDev** [comment]
On plotme this was as easy as a permission change and I know of a few servers that do this already. I don't think this should remain open since just using a permissions plugin solves this issue. PlotSquared isn't a permission plugin and therefore should not need to handle this in the code (even though it is already technically supported).

**Comment by chamunks** [comment]
We have this on our server but I don't recall the node at the moment I doubt that its documented.  plots.plot.# I would imagine it was if I remember correctly.

**Comment by boy0001** [comment]
https://github.com/IntellectualSites/PlotSquared/issues/987

**Comment by recon88** [comment]
How is #987 related to this issue? I can't seem to find a fix in the commit there.

**Comment by recon88** [comment]
Sorry for digging this out but I just got back to PlotSquared after more than a year and there were a lot of changes.   
I can't seem to figure out how to achieve what I requested. I currently have the perm node "plots.plot.1" set for everyone and the example claim price of "100*{arg}+50" but am not able to claim more that a single plot because of the permission node.

So how would I give everyone a single free plot and infinite paid plots?

**Comment by boy0001** [comment]
The price can't be configured per group. To allow people to claim infinite plots, give them `plots.plot.*`

To have the first plot free, set the price to `{arg}==0?0:100`, where 100 is the normal price.

You could just give people money when you change their rank. Or claim a plot for them.

**Comment by recon88** [comment]
It's not about the price per group, it's about free plots per group.
Default group can claim one free plot and another group can claim 4 free plots.
It would require a separate permission node like plot.free.# where # is the number of free plots. You then have an extra fied in the database which stores the amount of free plots a user has claimed already. Compare that with the node when an user tries to claim and charge money of the limit was reached.
