### ISSUE TITLE
why player can’t  throw things 

### ISSUE THREAD

**Issue by 631504445** [IntellectualSites/PlotSquared#1820]
# Bug report template 

**Debug paste link:** 

**Description of the problem:** 

**How to replicate:** 

**Checklist**:

- [] I included a `/plot debugpaste` link
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [] I Made sure the bug/error is not caused by any other plugin

**Comment by lurr** [comment]
Please follow the template, and describe the issue.

**Comment by dordsor21** [comment]
Either have a flag set, or nothing to do with PlotSquared.
