### ISSUE TITLE
PlotMergeEvent not called

### ISSUE THREAD

**Issue by bicrypt** [IntellectualSites/PlotSquared#1821]
Paste: https://hastebin.com/awosobayew.rb

In my plugin I tested several events (e.g. PlotFlagAddEvent, PlotFlagRemoveEvent, PlotUnlinkEvent, ...) and printed out "hi + event class name" into the console. But PlotMergeEvent seems to be the only one that is not being called. 

**I really need to check some things when plots are merged** so please fix asap or tell me if I am doing anything wrong. Listeners registered, no errors in console. 

Kind Regards,
bicrypt

**Comment by bicrypt** [comment]
Okay.

**Comment by bicrypt** [comment]
Please notice me @boy0001.

**Comment by RedstoneFuture** [comment]
Hello. Sorry, we have a lot to do at here. Have you still this problem? Can you send a nwe hastebin link? The old is currently invalid.

**Comment by wumptrax** [comment]
Hello! I have the same issue: The PlotMerveEvent is not called. There are only issues with this single event... all other events work perfect for me. Some example code: https://hastebin.com/akitoxiriy.css

**Comment by dordsor21** [comment]
#1739
