### ISSUE TITLE
setting plot alias to "2" screws everyones home up

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#1822]
when a player has his plot alias set as "2" players who type /plot home 2 to go to their second plot end up at the plot named 2

Only started happening after updating to recent builds, currently using plotsquared as of https://github.com/IntellectualSites/PlotSquared/commit/59557cf8898755a334aec36a43ccc7a2bf340652

**Comment by PhanaticD** [comment]
same for higher numbers

**Comment by RedstoneFuture** [comment]
Why any player named a plod "2"? ^^ Somehow we must prioritize this.

**Comment by RedstoneFuture** [comment]
Bit right. I think its bad.
