### ISSUE TITLE
/plot home "not a valid number in range" showing wrong range

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#1823]
https://gyazo.com/937eebfd91a112af6391dc22cb5de714

I have three plots, not "1 to 0" plots, /plot home 3 shows ^

if I type /plot home 4 it shows this
https://gyazo.com/f6e8e5872233cf9d7f7a95ec420d8ef8

I do have three plots https://gyazo.com/b67de0475115aee96c1cd53ad23fc6b7

**Comment by RedstoneFuture** [comment]
Ok. At my server i havn't a problem with this command.

- which plotsqaured version?
- serversoftware?
- why you have in the list a "&4&lOwnerLand" instead of the worldname and the coordinates? ^^

**Comment by PhanaticD** [comment]
latest, thats what i named it

**Comment by lurr** [comment]
@PhanaticD A `/plot debugpaste` would be appreciated to help here; as it'd allow us to pinpoint what server software, what version, etc. you are running.

**Comment by PhanaticD** [comment]
im using paperspigot 1.12.2

**Comment by RedstoneFuture** [comment]
... And why you have in the list a "&4&lOwnerLand" instead of the worldname and the coordinates?

**Comment by PhanaticD** [comment]
why not? thats the plot alias

**Comment by RedstoneFuture** [comment]
ah ok, right.

**Comment by lurr** [comment]
@PhanaticD A `/plot debugpaste` is still appreciated.

**Comment by boy0001** [comment]
I've reverted the offending commit.
