### ISSUE TITLE
Implement an abstract database adapter and support other storage alternatives than SQL

### ISSUE THREAD

**Issue by Foorack** [IntellectualSites/PlotSquared#1825]
YAML, JSON, and MongoDB are examples alternatives.

**Comment by Sauilitired** [comment]
We decided against flatfile storage for performance reasons. MongoDB is a good option.

The database classes are already abstract.

**Comment by Foorack** [comment]
Closing this in favour of https://github.com/IntellectualSites/PlotSquared/issues/19 as an abstracdt adapter is already implemented.
