### ISSUE TITLE
/plot regenallroads <world> [height] - Height variable does not add air above road

### ISSUE THREAD

**Issue by Erlpil** [IntellectualSites/PlotSquared#1826]
**Debug paste link:** 
[https://hastebin.com/pamirolabi](https://hastebin.com/pamirolabi)

**Description of the problem:** 
We created Christmas roads stretching 19 blocks above the road. It generated as intended.
When trying to generate new roads, it does not remove the previous road above ground level.
[The Doc states: ](https://github.com/IntellectualSites/PlotSquared/wiki/Installation#adding-road-schematics)

> /plot regenallroads <world> [height] 
> The height option, if specified, changes the amount of air to paste above the schematic.

No matter what height variable is used, it does not add the air above the road to remove the old road.

How it looks after /plot debugroadregen:
[https://i.imgur.com/FLDneyJ.png](https://i.imgur.com/FLDneyJ.png)

How it looks after /plot regenallroads <world> 90:
[https://i.imgur.com/pLXjbqT.png](https://i.imgur.com/pLXjbqT.png)

**How to replicate:** 
1. Create a plot world and generate a road that stretches +19 blocks from base level.
2. Create a new normal one-block high road.
3. /plot debugroadregen (Will look as intended)
4. `/plot regenallroads <world> 90`

The road only replaces the ground level and does not add air above to remove the old road as intended.

**Checklist**:
- [x] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
You're missing the world argument. The correct sytnax is `/plot regenallroads <world> <height>`.

**Comment by Erlpil** [comment]
@boy0001 This was added in the issue, but was mistaken for text-syntax. My bad. This is now corrected. The issue was found when using the correct syntax described by you. This is still an issue.

Please reopen this issue.

**Comment by xion87** [comment]
i dont think is working is  not regening the roads

**Comment by RedstoneFuture** [comment]
mmh .. If I use '/p createroadschematic' and than '/plot regenallroads Test1 90' I get the correctly road:

![2018-06-24_17 28 33](https://user-images.githubusercontent.com/4140635/41820573-0a212eca-77d4-11e8-94f8-89e6f28b16cf.png)

**Comment by dordsor21** [comment]
You need to set the road height to below the position of the lowest air block, i.e. if you've got a block of air at y = 32, then the road height must be 31 or lower.
