### ISSUE TITLE
Support uuids

### ISSUE THREAD

**Issue by JavituRec** [IntellectualSites/PlotSquared#1833]
**Description of the problem:** 
I have a problem with the plots related to the uuids. I have two bungee cord, one is premium and the other is not pemium. If a non-premium and premium user has the same names they have the same plot.

Is there a way to solve that?

**Comment by boy0001** [comment]
Make sure you have ip-forwarding enabled in the spigot.yml, and haven't set PlotSquared to offline mode.

**Comment by JavituRec** [comment]
In bungee:
ip_forward: true

In spigot:
  bungeecord: true

In PlotSquared:
  # The UUID cacher is used to resolve player names
  uuid-cache: true
uuid:
  # Force using offline UUIDs (it usually detects the right mode)
  offline: false
  # Force using lowercase UUIDs
  force-lowercase: false
  # Use a database to store UUID/name info
  use-sqluuidhandler: false

**Comment by JavituRec** [comment]
I need fix this, If you help me I appreciate very much.
