### ISSUE TITLE
Custom Command Support

### ISSUE THREAD

**Issue by Elxafil** [IntellectualSites/PlotSquared#1835]
Hi, Could you please add in the ability to modify the command /plot to something else? I for example want to make a farming game so would love if I could do /farm instead of /plot

**Comment by boy0001** [comment]
You can change the main command by editing the `plugin.yml`, which is located inside the jar. Use a program like 7-zip to access it.

**Comment by Elxafil** [comment]
What part do I edit? I tried aliases and nothing.

**Comment by boy0001** [comment]
It's working for me. Make sure you re-add it to the zip once you are done modifying the file. Also if you want to change the command used in the help messages, that's in the `plugins/PlotSquared/config/commands.yml`
