### ISSUE TITLE
Help at PlotMe to PlotSquared conversion 

### ISSUE THREAD

**Issue by dasedris** [IntellectualSites/PlotSquared#1840]
Hey!
i have a problem with the plotsquared conversion from plotme to plotsquared. i dont really know whats wrong. when i do the conversion 2 of 3 worlds are ok but it says every plot is not yet claimed. one worlds is totally bugged and all plots are empty but the plots are claimed.

how to replicate:
i exactly followed the manual on your website!
note: we have 3 worlds on our server (size:(60x60),(100x100)(250x250)). each world has approximately 3000 plots. the 60x60 is the bugged world which is empty.

informations:
debugpaste: https://hastebin.com/kucutaxexa
screenshot from one world
![2018-01-14_18 22 40](https://user-images.githubusercontent.com/35429387/34918796-2794a0b2-f959-11e7-9a4d-81a08c91e17c.png)

i tried the conversion on a small test server with only one claimed plot and it worked. i might thing there are too many plots claimed and 3 worlds are too much. but we want to use your plugin instead of plotme.

im sorry for my bad englisch and i hope you can help me with my problem

**Comment by RedstoneFuture** [comment]
Have you still this problem?
Than stop the server, delete the world and restart the server. Than all world-chunks will regenerate. How look the world than?

**Comment by dasedris** [comment]
hey, i solved the problem ^^ apparently there were two world folders for every world (one called "plotworld" and one called "Plotworld". i think one of them was generated from plotsquared, i dont know how and why \(._.)/. so after deleting one of them the conversion worked fine and everything was normal. no more issues :P
