### ISSUE TITLE
Custom Vehicles, like plugins, dont trigger plot join/leave events

### ISSUE THREAD

**Issue by Legoman99573** [IntellectualSites/PlotSquared#1841]
**Debug paste link:** https://hastebin.com/ibunazuxot

**Description of the problem:** Custom plugin vehicles, like https://www.spigotmc.org/resources/%E2%9C%88%EF%B8%8Fvehicles-no-resourcepacks-needed.12446/ which uses armorstands, dont trigger plot join/leave events allowing players, if denied from a plot, to bypass it.
Video proof: https://youtu.be/IT1AeY__KyA

**How to replicate:** 

1. Get a plugin that uses custom vehicles as described above
2. Go on the road/other plot
3. Basically what happened in #1754, you can bypass being denied on someones plot.

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
The vehicle plugin needs to call either a PlayerMoveEvent, or VehicleMoveEvent.

**Comment by Legoman99573** [comment]
@boy0001 the only issue is that it doesnt work with entities, like armorstands.

**Comment by shada124** [comment]
hey .....
i dont  have server
but i have problem
with you
you sind me everyday the same things
But  hope you to stop that
And thank you


بتاريخ 2018/01/15 10:24 ص، كتب "Legoman99573" <notifications@github.com>:

**Comment by Legoman99573** [comment]
@shada124 thanks for the useless response that has nothing to do with the issue that was opened or help in any way.
