### ISSUE TITLE
/plot delete | /plot auto | world border issue

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#1845]
I am using Nukkit for this issue, when a player does /plot delete, then /plot auto they get sent to a new plot outside of the border instead of the plot they just deleted. Ideally with plot auto they should be getting sent to one closest to the the center of the world. Either /plot delete is not registering the plot as available correctly, or the world border is not expanding correctly, or both

**Comment by shada124** [comment]
Hey please shut up yoy send alot of messages and i hate you so much and
thank you

بتاريخ 2018/01/17 6:00 م، كتب "Josh" <notifications@github.com>:

**Comment by PhanaticD** [comment]
lol what the fuck

**Comment by shada124** [comment]
shut up !!!!!

بتاريخ 2018/01/17 6:04 م، كتب "Josh" <notifications@github.com>:

**Comment by shada124** [comment]
why send that

بتاريخ 2018/01/17 6:05 م، كتب shada12345671@gmail.com:

**Comment by shada124** [comment]
you

بتاريخ 2018/01/17 6:05 م، كتب "Šhādā & ÑAÐÅ" <shada12345671@gmail.com>:

**Comment by DeadMaster121** [comment]
LOL

**Comment by boy0001** [comment]
@shada124
If you are receiving any emails, you must have subscribed to the repository. Click unsubscribe or change your https://github.com/settings/notifications

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
