### ISSUE TITLE
Offline Players

### ISSUE THREAD

**Issue by Bobcatsss** [IntellectualSites/PlotSquared#1846]
Debug: https://hastebin.com/epigapupol

Problen: So this just randomly happened where players can no longer visit offline players plots it just says it can't find any plots for that player. Works just fine if the Owner of the plot is online

**Comment by RedstoneFuture** [comment]
Right. I've had that at times too. But not often. This is a very crazy bug.

**Comment by boy0001** [comment]
If the server just started, it could still be caching the uuids. Anywho, you should still be able to use `/plot list <uuid>`. 

Get the uuid from e.g.: https://mcuuid.net/

**Comment by RedstoneFuture** [comment]
I know the situation, that the user is with username still a owner of the plot if I check the plot. But he can't build.
But yes, I can check "p list <uuid>" at the next time.

**Comment by RedstoneFuture** [comment]
@Bobcatsss If you have still a problem wit this please check `/plot list <uuid>`. Reopen this issue if you have more infos. I will this too.
