### ISSUE TITLE
Lacking permission outputs twice when right clicking with item in your off-hand.

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/PlotSquared#1847]
PlotSquared dev 553

When you right click with an item in your off-hand inside a plot you are not an owner of, it outputs

```
[P2] You are lacking the permission node:
plots.admin.interact.unowned
```

twice in a row. Possibly because you are listening for any hand interaction rather than specified main hand or off-hand?

**Comment by RedstoneFuture** [comment]
is was fixed
