### ISSUE TITLE
[SOLVED] /plot auto, /plot claim, other commands won't work

### ISSUE THREAD

**Issue by Tapiture** [IntellectualSites/PlotSquared#1848]
Debug paste link: https://hastebin.com/akajodutey

Description of the problem: Whenever I type /plot auto, /plot claim, or other similar commands there is no response and no console errors or info, even with the appropriate permissions assigned.

One strange message on startup regarding "creativeplot," the world I setup using the /plot setup system.

> 20.01 02:50:50 [Server] INFO `creativeplot` was not properly loaded - PlotSquared will now try to load it properly: 
20.01 02:50:50 [Server] INFO - Are you trying to delete this world? Remember to remove it from the settings.yml, bukkit.yml and multiverse worlds.yml
20.01 02:50:50 [Server] INFO - Your world management plugin may be faulty (or non existent)

**Comment by Tapiture** [comment]
Solved, PlotSquared was attempting to connect to a database that didn't exist.

**Comment by User3794739** [comment]
Close your solved issues. You can do so by clicking the button next to "Comment".
