### ISSUE TITLE
Plotflag weather doesn't change

### ISSUE THREAD

**Issue by N0tMyFaultOG** [IntellectualSites/PlotSquared#1850]
**Debug paste link:** 
https://hastebin.com/qugozoseta

**Description of the problem:** 
If you enter a plot which has the weather flag on rain, the rain doesn't turn off by leaving the plot. It's still there and moves on if you enter the road or other plots.
Below a gyazo gif of what I mean:
[https://i.gyazo.com/e45a09c1c90f19e0b1cf5bda441dabed.mp4](url)

**How to replicate:** 
Claim a plot, run /p f set weather rain and leave the plot. The rain wont stop.

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
https://github.com/IntellectualSites/PlotSquared/issues/1857
