### ISSUE TITLE
WorldEdit/P2 Road Issue

### ISSUE THREAD

**Issue by N0tMyFaultOG** [IntellectualSites/PlotSquared#1852]
**Debug paste link:** 
PlotSquared: https://hastebin.com/guxegepudu
FAWE: https://hastebin.com/pohitobure

**Description of the problem:** 
If you have 2 or more plots merged and unmerge them while having parts of the road selected, you are able to perform WorldEdit commands over there e.g. //set 0

**How to replicate:** 
Merge a couple of plots or more, select parts of the plot where the road goes, unmerge the plot and you are still able to build on the road while having the area selected.

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
