### ISSUE TITLE
Flag Based Permissions

### ISSUE THREAD

**Issue by Elxafil** [IntellectualSites/PlotSquared#1855]
Is it possible to use permissions on a per player basis to add the ability to players to use some plot flags? For example being able to limit users on a per permission basis to use and mine certain blocks in public mines.

**Comment by boy0001** [comment]
You can set the use and break flag to allow interaction, and breaking of specific blocks:
https://github.com/IntellectualSites/PlotSquared/wiki/Flag:-use
https://github.com/IntellectualSites/PlotSquared/wiki/Flag:-break
