### ISSUE TITLE
[Spigot 1.8] /plot delete not deleting worlds when „worlds“ enabled in config

### ISSUE THREAD

**Issue by User3794739** [IntellectualSites/PlotSquared#1856]
# Bug report template 

**Debug paste link:** 

**Description of the problem:** 
/plot delete doesn‘t properly delete worlds. A folder with .mca files is left. The problem only appears when working with Spigot 1.8. Spigot 1.12 works perfectly.

**How to replicate:** 
- Spigot 1.8
- entry „worlds“ in the config enabled

**Checklist**:

- [ ] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
