### ISSUE TITLE
rain does not stop outside plot

### ISSUE THREAD

**Issue by CodeMuscleExerciser** [IntellectualSites/PlotSquared#1857]
# Bug report template 

https://hastebin.com/afavasavus

**Description of the problem:** 
when enter a plot with weather set to rain, it goes raining. When leaving that plot it keeps raining... 
also on unclaimed plots. (it think its a bug).

**How to replicate:** 
claim plot: /plot claim
set weather to rain: /plot set weather rain
leave that plot: it keeps raining.... on other and unclaimed plots also..
if you enter a plot where weather is set to clear. it stop raining. (but only then)

(i checked it also on play.ajgaming.net and there was also the bug)

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)]
mikedmd - vandaag om 17:38
@Roufar Can you make a post at https://git.io/v5eMA so Emp can take a look at it(gewijzigd)
(https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin
(i checked it also on play.ajgaming.net and there was also the bug)

**Comment by rumplepusscat** [comment]
Can confirm this is happening for me too: https://hastebin.com/muhoxupuho

**Comment by RedstoneFuture** [comment]
fixed https://github.com/IntellectualSites/PlotSquared/commit/5f9bd853ec4d58e82b2e6c5ec3a6cdac259ef960
