### ISSUE TITLE
Issues with UUID cache

### ISSUE THREAD

**Issue by dordsor21** [IntellectualSites/PlotSquared#1858]
A player who had not been on the server for a long time changed their name from X to Y, and someone else changed their own username to the old one of the old player, X. Upon the new X logging in, they assumed ownership of all of Y's plots, but Y does not appear in the UUID cache having not logged in for a while (did they get replaced?) so I cannot change ownership of the plot.

**Comment by AeSix** [comment]
If the UUIDs did not match, this shouldn't had been an issue.  **Unless:**
1) you are using offline mode UUIDs, which are generated via the username by the server.  There's nothing you can really do for that, aside from require a password auth to use the server, or some other method of ensuring the user/username pair is always a match. 

2) The plugin is not handling user accounts by UUID but by username instead. Which P2 uses UUIDs for newer versions (and has for years?) 

3) Your UUID cache somehow got mangled in a way which allowed the username to assume the old UUID.  This should be impossible if your are not blocking Mojang UUID lookups.

**Comment by Sauilitired** [comment]
Hi @dordsor21, thanks for reporting the issue. Can you confirm that this is still a problem, in more up-to-date versions of the plugin?

Cheers,
Citymonstret.

**Comment by dordsor21** [comment]
It's such a terribly specific scenario, who knows tbh
