### ISSUE TITLE
Option to teleport to plot in current world.

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/PlotSquared#1859]
Would it be possible to have a command to teleport players to their plot in the world they are currently in? I have 2 plot worlds, one for worldedit, one for creative. I also have an npc that automatically runs the command ```/plot home``` when a player right clicks him. However, if a player has a plot in both worlds, it always teleports him to his first plot. Thus would it be possible to have a command to teleport players to their first plot home in _that_ world, unless they otherwise have multiple plots in that world?

**Comment by boy0001** [comment]
`per-world-visit` in the `settings.yml`

**Comment by mibby** [comment]
@boy0001 I have that turned on already but it doesn't separate ```/plot home``` based on per world.

* Player buys a plot in ```build1```.
* Player buys a plot in ```build2```.
* Player is in the build2 world and types ```/plot home```.
* Player gets teleport to their 'first' plot, in build1 world.

As far as I know, there is no simple command players can type to visit their owned plot in that world without having to specify the plot ID with the command as well. So you can't have a simple npc in each world that teleports players to their plot home in that world.
