### ISSUE TITLE
Please add a Plot restore command or addon to recover accidental clears or deletes 

### ISSUE THREAD

**Issue by hamhamfreak** [IntellectualSites/PlotSquared#1860]
I was Trying to delete a Plot on my server as the plot i removed had bad things on it and instead even tho i was on the target plot the /plot delete command thought i was on one of my plots for some reason please make a way to recover plots

**Comment by RedstoneFuture** [comment]
You can use the //restore command of FastAsyncWorldedit https://github.com/boy0001/FastAsyncWorldedit/wiki/Commands#snapshot-commands-edittop

For this you must define a snapshot / backup file in /plugins/worldedit:

config.yaml:
```
snapshots:
    directory: '/home/redstoneworld/testserver/PerfectBackup'
```
