### ISSUE TITLE
/tree grows leaves outside of plot

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/PlotSquared#1861]
**PlotSquared Version**
PlotSquared-18.1.25-c577813-1958

**Description of the problem:** 
Players are able to use /tree acacia for example and the leaves grow outside of the plot.
![2018-01-28_11 10 55](https://user-images.githubusercontent.com/10485646/35481492-7a70ce00-041c-11e8-8e94-3a3241b873c5.png)

**How to replicate:** 
Use /tree acacia on the edge of a plot.

**Comment by xion87** [comment]
I confirm the issue

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
