### ISSUE TITLE
Schematic Bugs

### ISSUE THREAD

**Issue by doitliketyler** [IntellectualSites/PlotSquared#1865]
**Debug paste link:** 
https://hastebin.com/mixuzaxite

**Description of the problem:** 
When using the schematic on claim feature there are a few things not working properly. 
1. Custom head blocks are transparent
2. Chests are transparent until opened.
3. Chest items from the schematic are not included inside of the chest.

**How to replicate:** 
By following the instructions listed on the "Schematic on claim" page.

**Comment by boy0001** [comment]
Install [FastAsyncWorldEdit](https://www.spigotmc.org/resources/fast-async-worldedit.13932/) for proper support of schematics.
