### ISSUE TITLE
Plots Merging/Clearing without Trigger

### ISSUE THREAD

**Issue by rumplepusscat** [IntellectualSites/PlotSquared#1866]
# Plots Merging/Stacking without Trigger

**Debug paste link:** "Plugin PlotSquared v3.5.0-SNAPSHOT-95f8aaa generated an exception while executing task 1280844"

**Description of the problem:** 
Plots merge/stack randomly with no real pattern or reset without warning. There has been no input to trigger this, and only started happening last night, clearing/resetting two plots and stacking one in two directions, overlapping roads and adjacent plots. However, this has now stopped.

**Comment by 615283** [comment]
Rumple, let's say that SL is getting the backup :) ?

**Comment by rumplepusscat** [comment]
I know but I just wanted to see whether this was a known bug or whether we did anything accidentally etc.

**Comment by boy0001** [comment]
Try updating PlotSquared, you are running an outdated version of the plugin.
