### ISSUE TITLE
Water/lava and redstone bug

### ISSUE THREAD

**Issue by Niketion** [IntellectualSites/PlotSquared#1868]
**Debug paste link:** https://hastebin.com/oxolixuguq

**Description of the problem:** When player place water/lava and he take it back fluid remaining. Furthermore, redstone doesn't work

**How to replicate:** 

**Checklist**:
- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Line `151` of your `settings.yml` you have set `disable-physics: false`. Set that to `true`.
