### ISSUE TITLE
Can't change setting in "world.yml"

### ISSUE THREAD

**Issue by AkiraTsubasa** [IntellectualSites/PlotSquared#1870]
# Bug report template 

**Debug paste link:** 

**Description of the problem:** 
Hi, I made my plot world with the bridge template, and everything was ok until I realized that I couldn't drop items outside of a plot or in an unclaimed plot. So I figured out that I could fix it adding "misc_spawn_unowned" to true in the world.yml file, but I'm  having a serious problem with world.yml file that everything I change or add in that file, It doesn't change nothing, Even if I do it with the server turned off, or reload the plugin, I can't change anything in the world.yml, I know it because I tried changing other setting and it didn't work. The changes that I did still being on the world.yml but it doesn't seem to work in the server, so I basically want to add "misc_spawn_unowned" to true in the world.yml, but I don't know how.

**How to replicate:** 

**Checklist**:

- [] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
I can't replicate the issue. If you are doing it over FTP or some web panel, make sure it's uploading correctly.
