### ISSUE TITLE
[Feature Request] Move events in the API jar

### ISSUE THREAD

**Issue by Legoman99573** [IntellectualSites/PlotSquared#1871]
This isn't really a bug report for the plugin itself, but when I tried to make an add-on for a plugin, I see no reference to Player or Vehicle movement in the server API jar. This is somewhat an API request for something that I can't hardcore myself. I was hoping we could add a tag to a random object and that tag is tracked per block, like riding armorstands or arrows.

Hope this won't be a problem and you may close this if you don't like the request.

**Comment by boy0001** [comment]
If you're referring to ArmorStand, it usually isn't an issue because in vanilla players don't ride moving armor stands. 

Which is why the plugin using them as vehicles needs to call the event:

Option 1: Use VehicleMoveEvent
```Java
ArmorStandVehicle armorStandVehicle = new ArmorStandVehicle(armorStand); // Simple delegate class which implements Vehicle and overrides getPassenger (you need to create this class)
VehicleMoveEvent event = new VehicleMoveEvent(armorStandVehicle, from, to);
Bukkit.getPluginManager().callEvent(event);
from = event.getFrom();
to = event.getTo();
```

Option 2: Use PlayerMoveEvent
```Java
PlayerMoveEvent event = new PlayerMoveEvent(player, from, to);
Bukkit.getPluginManager().callEvent(event);
if (!event.isCancelled()) {
    from = event.getFrom();
    to = event.getTo();
}
```
