### ISSUE TITLE
plot pvp

### ISSUE THREAD

**Issue by DeniseBRGlobal** [IntellectualSites/PlotSquared#1874]
Even with the flag pvp false.
People added to the plot take damage.
But they do not die.
They are using this bug to raise levels in the mcmmo.

**Comment by RedstoneFuture** [comment]
@DeniseBRGlobal At my server without the permission "plots.admin.pvp.other" the user can attack a other user in a plot with the flag "pvp = false".

**Comment by RedstoneFuture** [comment]
Can you test it with a newer version or without any second pvp plugins?
