### ISSUE TITLE
Unable to use the reset and clear commands, and drop things on the road will disappear

### ISSUE THREAD

**Issue by KangYee** [IntellectualSites/PlotSquared#1880]

**Comment by KangYee** [comment]
version:PlotSquared-Sponge-18.02.15-1cd30b8-1966

**Comment by TheJackah** [comment]
Same issue here. /plot clear says that a setblock timer is bound, thus not clearing the plot.

**Comment by Arasple** [comment]
I can't see drop things or any entity on the road and somewhere either...

**Comment by RedstoneFuture** [comment]
https://github.com/IntellectualSites/PlotSquared/issues/1931

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
