### ISSUE TITLE
use-flag command check

### ISSUE THREAD

**Issue by gerardvanschip** [IntellectualSites/PlotSquared#1882]
**Debug paste link:** 
https://hastebin.com/ixoripulat

**Description of the problem:** 
Using the "/plot flag set use true" gives me a "Successfully added flag" message but nothing changes. People cant use signs and buttons

**How to replicate:** 
Claim a plot, run the flag command for use and have others try to use buttons.

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
Hello. Thanks for the report.
You need a ID or a block-name. E.g. with `/plot flag set use wool` or `/plot flag set use 35` you find a new block under the use-flag with `/p i`.


**Bug-Description of the problem:** 

After a `/plot flag set use ...` command the player get always a "Successfully added flag" messages. If i use a wrong block-ID too.

**How to replicate:** 


1. claim a plot
2. use the command '/plot flag set use wrongID'

3. with '/p i' the wrong ID is not added, only the messages "Successfully added flag" is wrong



- Tested with: build 598
- serversoftware: Spigot
- errors: no
- only a plotsquared-problem: yes

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
