### ISSUE TITLE
database error

### ISSUE THREAD

**Issue by GameModeOnX** [IntellectualSites/PlotSquared#1884]
# Bug report template 

**Debug paste link:** 

I can't find :cry: 
**Description of the problem:** 
I have an error
https://pastebin.com/94BFrUfD
I using FAWE could it be related?
**How to replicate:** 

**Checklist**:

- [] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
Have you still this problem? Check you storage.yml of plotsquared.
Tip: Restart the server without e.g. FAWE and check the console. Get you still this error?

**Comment by boy0001** [comment]
This has been fixed.
