### ISSUE TITLE
Ghost player can walk in banned plots + wrong heal-flag value

### ISSUE THREAD

**Issue by Deannord** [IntellectualSites/PlotSquared#1885]
When Place A Flag Call heal,Set It To 1 100,It Heals,But If In Version 1.10 Spawn In Survival Mode A Crystal Of End,It Kill,And Makes A Player Like A "Ghost",It Can Walk In Banned Plots And Can't Banned,But Its Can't Type A Commands And Not Shows In Chat.

**Comment by Deannord** [comment]
(Also If Leave An Minecart's With Chest,And Deleting Plot,It Leaves With Not Deleting.)

**Comment by RedstoneFuture** [comment]
**With the command `/p flag set heal 100` the `/p i` shows:**

![2019-01-27_18 52 39](https://user-images.githubusercontent.com/4140635/51804787-5d11ce00-2265-11e9-83d1-503fd0e28e32.png)

A argument check would be good at here.

The bug with the gost player I can't replicate in 1.13.2, but maybe it's only a 1.10 bug.

**Comment by AeSix** [comment]
@Deannord Hi.
I've confirmed that the heal flag issue is still ongoing.  I have created a new ticket, as issue reports should be one issue per report.   Please keep this in mind when reporting issues for *any* software, as it will greatly help the developers to manage their tickets better.  

You can keep track of that issue by going to the ticket here:  https://github.com/IntellectualSites/PlotSquared/issues/2302

**Comment by AeSix** [comment]
@Deannord 
If this is still an issue, please update your plugins and the ticket.  Reopen if it's still an issue.
