### ISSUE TITLE
Admin Untrust Permission Not Working

### ISSUE THREAD

**Issue by SioWolf** [IntellectualSites/PlotSquared#1887]
# Bug report template 

**Debug paste link:** 

https://hastebin.com/oloratamuj

**Description of the problem:** 
I have given myself the "plots.admin.command.untrust" permission and I am unable to untrust people from plots that I do not own. When I try to use the command I am given an error "I must be the plot owner to use this". When I give myself any other "plots.admin.command.<command>" permissions they work just fine, in fact with the trust permission I can trust myself on any plot, but the untrust command does not work.

**How to replicate:** 
Just give yourself the permission.

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
`plots.admin.command.remove` is the correct permission. /ps untrust is an alias of /ps remove

**Comment by SioWolf** [comment]
@dordsor21 The wiki should be updated, it lists the wrong permission.
