### ISSUE TITLE
[ViaRewind+Plotsquared] Client disconect

### ISSUE THREAD

**Issue by xion87** [IntellectualSites/PlotSquared#1888]
Using latest plotsquared and viarewind: when a player in creative mode (not-op) try to "steal" a head with shift+mid click, it cause disconection "it look like the server is down" instead is just a client crash. 
Using Protocolsupport instead, it work fine.
Server version 1.12.2 Paperspigot + Viaversion + ViaBackard + ViaRewind

**Comment by Legoman99573** [comment]
console logs may help

**Comment by xion87** [comment]
there is no logs

Il dom 4 mar 2018, 16:40 Legoman99573 <notifications@github.com> ha scritto:

**Comment by Legoman99573** [comment]
Client logs may help out why the crash occured. Could be the NBT that crashes the client

**Comment by xion87** [comment]
I mean the client is kicked from the server like it will be turned off... it don't crash the client

**Comment by xion87** [comment]
I got finally a error on bungee console (dunno if is is a plotsquared bug or viaversion)
https://hastebin.com/holabikoca.go

**Comment by RedstoneFuture** [comment]
But I think its a problem of ViaRewind or client or bungeecord ?!

**Comment by xion87** [comment]
viarewins told that is a plotsquared issue...

Il sab 28 apr 2018, 00:30 Robert Rauh <notifications@github.com> ha scritto:

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
