### ISSUE TITLE
Plot Music Flag Join/Leave Bug + Music Duplication

### ISSUE THREAD

**Issue by Legoman99573** [IntellectualSites/PlotSquared#1889]
# Bug report template 

**Debug paste link:** 

https://hastebin.com/siwamodoxe

**Description of the problem:** 
When someone enters a plot, the music is suppose to cover the whole plot, but instead, it only covers the Plot Enter Event was triggered at and does not stop on Plot Leave Event as well, which allows you to hear it on others plots next to that plot.

**How to replicate:** 

https://youtu.be/rotQ-rvo39w Enter and leave like crazy

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
