### ISSUE TITLE
On Join Console Error

### ISSUE THREAD

**Issue by doitliketyler** [IntellectualSites/PlotSquared#1891]
**Description of the problem:** 
This error shows in the console when a player joins:

https://pastebin.com/raw/PWMkgkwN

Thoughts?

**Comment by RedstoneFuture** [comment]
Have you still this problem? Only at a specify user?

**Comment by boy0001** [comment]
Not directly related to the player joining, but rather the `kill-road` option trying to kill an entity that has already been killed. I assume the relevant entities were in the chunks loaded when the player spawns. 

This has since been fixed.
