### ISSUE TITLE
Merged Plots: Break Roads with W/E

### ISSUE THREAD

**Issue by ItzAntony** [IntellectualSites/PlotSquared#1892]
**Debug paste link:** 
https://hastebin.com/cayavujeka

**Description of the problem:** 
When players merge their plot, use W/E or FAWE to break the strip of road and then unlink the plots, they can still use W/E or FAWE to break the roads within the world. I'm not sure if this is a PlotSquared issue but it must be a combination between the two.

**How to replicate:** 
**1.** Claim two plots next to eachother
**2.** Merge the plots
**3.** Use a worldedit brush, //br sphere 0 5
**4.** Break the part where the road was using it
**5.** Unlink the plots
**6.** Use the worldedit brush tool to once again break the actual road

**Checklist**:
- [✓] I included a `/plot debugpaste` link
- [✓] I made sure there are no duplicates of this report
- [✓] I made sure I am using an up-to-date version of PlotSquared
- [✓] I Made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
Have you still this problem? I can't use the brush after the "/p unlink" at the break road.

![2018-04-27_23 50 52](https://user-images.githubusercontent.com/4140635/39386668-fe6397ca-4a75-11e8-9089-8d7f363b09b0.png)

**Comment by boy0001** [comment]
This has been fixed. I haven't tested without FAWE, but we can reopen this if that's not fixed as well.
