### ISSUE TITLE
The plot world is "delete/unload" to restart the server

### ISSUE THREAD

**Issue by GuerreroCraft61** [IntellectualSites/PlotSquared#1898]
# Bug report template 

**Debug paste link: [https://hastebin.com/cocuburimo](url) ** 

**Description of the problem: The plot world is "delete/unload" to restart the server** 

**How to replicate: Restart the server and automatic unload the world** 

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [] I Made sure the bug/error is not caused by any other plugin

**Comment by GuerreroCraft61** [comment]
And this generate 2 diferent world (I have "Builder" and "Creativo1.12/1.8" world) and generate a Creativo1 and Builder1
The wolrds to unload are "Creativo1.12/1.8"

**Comment by DeadMaster121** [comment]
I would guess this would be a bug with the plugin, could you try to get another debug link?

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
