### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by DeniseBRGlobal** [IntellectualSites/PlotSquared#1900]
# Bug report template 

**Debug paste link:** 

debug:
https://hastebin.com/nisoxupeca
**Description of the problem:** 
When we load the server he is using 25% of ram, after some time of use the command /plot home:2 :3 plot home etc 
The ram goes up and does not goes down I tried everything more ram less ram, change things in the config.
I dedicated now 14 gigs of ram because if a dedicate less the server overload after 20 30 minutes.

**How to replicate:** 

Enter the game and type ./plot home multiple times. /plot home:2 : 3 : 4 etc
The Memory ram goes up and not goes down.
After some time doing this the server oveload and crash.
**Checklist**:

- [] I included a `/plot debugpaste` link
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [] I Made sure the bug/error is not caused by any other plugin

**Comment by DeniseBRGlobal** [comment]
I'll remove plot squared too much lag. :(

**Comment by boy0001** [comment]
Plot home just teleports the player. No-one else if having this issue. It might be a conflict with some other plugin doing something when a player teleports.

**Comment by RedstoneFuture** [comment]
Have you still this problem?

**Comment by Sauilitired** [comment]
No response in months. Closing.
