### ISSUE TITLE
Error when deleting a plot with SpongeVanilla

### ISSUE THREAD

**Issue by Lachney** [IntellectualSites/PlotSquared#1902]
# Bug report template 

**Debug paste link:** 

https://hastebin.com/oxeyojibep

**Description of the problem:** 
Cannot clear or delete plots and returns an error in the console
https://hastebin.com/pimabupuxu

**How to replicate:** 

Just claim a plot and attempt to clear or delete the plot.
**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
#1912
