### ISSUE TITLE
weather and time flag bug

### ISSUE THREAD

**Issue by Sillysheep165** [IntellectualSites/PlotSquared#1903]
Not sure if anyone else is having this problem or if there is a fix, if a player has set the time or weather on their plot then anyone who visits the plot and then leaves still has the weather for example rain with them. They can only get rid of it by leaving the server and rejoining. Any solutions to this would be helpful.complete reports might be marked as invalid. -->

**Comment by RedstoneFuture** [comment]
Right, the weather-flag is still buggy. But the problem with the time was fixed.

https://github.com/IntellectualSites/PlotSquared/issues/1723
