### ISSUE TITLE
my furnace and my funnil don't work

### ISSUE THREAD

**Issue by Stonck** [IntellectualSites/PlotSquared#1904]
# Bug report template 

**Debug paste link:** 

**Description of the problem:** 

**How to replicate:** 

**Checklist**:

- [] I included a `/plot debugpaste` link
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [] I Made sure the bug/error is not caused by any other plugin

**Comment by Stonck** [comment]
who can help me ?
e use plotsquared, but my furnace and my funnil don't work
what i do ?

**Comment by RedstoneFuture** [comment]
Have you still this problem? The discription is very small. What ist "funnil"?

**Comment by RedstoneFuture** [comment]
* funnel
