### ISSUE TITLE
nukkit database error

### ISSUE THREAD

**Issue by XDqrkneZ** [IntellectualSites/PlotSquared#1905]
# Bug report template 

**Debug paste link:** 

**Description of the problem:** 
got this database error when i used /p auto command
https://pastebin.com/SjXZ8K5Q

**How to replicate:** 

**Checklist**:

- [] I included a `/plot debugpaste` link
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
