### ISSUE TITLE
enable to drop in the stree

### ISSUE THREAD

**Issue by HaXiiis** [IntellectualSites/PlotSquared#1906]
Hi 

How i can enable to drop in the street ???
Pls help

**Comment by RedstoneFuture** [comment]
Open the plugins\PlotSquared\config and redefine the settings.yml

```
  # Kill mobs on roads
  kill-road-mobs: false
```

**Comment by RedstoneFuture** [comment]
https://github.com/IntellectualSites/PlotSquared/issues/1906

**Comment by RedstoneFuture** [comment]
https://github.com/IntellectualSites/PlotSquared/issues/1931

**Comment by boy0001** [comment]
See the response by @RedstoneFuture for your current version. 
Update PlotSquared, and change `kill-road-items` to `false` in the PlotSquared `settings.yml`
