### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by 1434967947** [IntellectualSites/PlotSquared#1907]
Well the server can not start

java.lang.NoClassDefFoundError: Could not initialize class com.plotsquared.sponge.util.SpongeUtil
	at com.plotsquared.sponge.SpongeMain.log(SpongeMain.java:203)
	at com.intellectualcrafters.plot.PS.log(PS.java:334)
	at com.intellectualcrafters.plot.PS.loadWorld(PS.java:1200)
	at com.plotsquared.sponge.generator.SpongePlotGenerator.modifyWorldGenerator(SpongePlotGenerator.java:99)
	at net.minecraft.world.WorldServer.updateWorldGenerator(WorldServer.java:1887)
	at net.minecraft.world.WorldServer.handler$onConstruct$zlm000(WorldServer.java:1720)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:125)
	at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:798)
	at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:766)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3530)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.plotsquared.sponge.SpongeMain.log(SpongeMain.java:203)
	at com.intellectualcrafters.plot.PS.log(PS.java:334)
	at com.intellectualcrafters.plot.PS.loadWorld(PS.java:1200)
	at com.plotsquared.sponge.generator.SpongePlotGenerator.modifyWorldGenerator(SpongePlotGenerator.java:99)
	at net.minecraft.world.WorldServer.updateWorldGenerator(WorldServer.java:1887)
	at net.minecraft.world.WorldServer.handler$onConstruct$zlm000(WorldServer.java:1720)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:125)
	at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:798)

-- Sponge PhaseTracker --
Details:
	Cause Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjg000(MinecraftServer.java:3987)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:887)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:370)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:556)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows Server 2008 R2 (amd64) version 6.1
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 203661424 bytes (194 MB) / 1171259392 bytes (1117 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 4 total; -Xms512M -Xmx2048M -XX:+AggressiveOpts -XX:+UseCompressedOops
	IntCache: cache: 0, tcache: 0, allocated: 14, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 44 mods loaded, 44 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID                    | Version                     | Source                                          | Signature                                |
	|:------- |:--------------------- |:--------------------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJAA | minecraft             | 1.12.2                      | minecraft.jar                                   | None                                     |
	| UCHIJAA | mcp                   | 9.42                        | minecraft.jar                                   | None                                     |
	| UCHIJAA | FML                   | 8.0.99.99                   | start.jar                                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAA | forge                 | 14.23.2.2611                | start.jar                                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAA | micdoodlecore         |                             | minecraft.jar                                   | None                                     |
	| UCHIJAA | spongeapi             | 7.1.0-SNAPSHOT-06016f2      | spongeforge-1.12.2-2611-7.1.0-BETA-2990.jar     | None                                     |
	| UCHIJAA | sponge                | 1.12.2-2611-7.1.0-BETA-2990 | spongeforge-1.12.2-2611-7.1.0-BETA-2990.jar     | None                                     |
	| UCHIJAA | baubles               | 1.5.2                       | Baubles-1.12-1.5.2.jar                          | None                                     |
	| UCHIJAA | botania               | r1.10-353                   | Botania r1.10-353.jar                           | None                                     |
	| UCHIJAA | buildcraftlib         | 7.99.15                     | buildcraft-7.99.15.jar                          | None                                     |
	| UCHIJAA | buildcraftcore        | 7.99.15                     | buildcraft-7.99.15.jar                          | None                                     |
	| UCHIJAA | buildcraftbuilders    | 7.99.15                     | buildcraft-7.99.15.jar                          | None                                     |
	| UCHIJAA | buildcraftenergy      | 7.99.15                     | buildcraft-7.99.15.jar                          | None                                     |
	| UCHIJAA | buildcraftfactory     | 7.99.15                     | buildcraft-7.99.15.jar                          | None                                     |
	| UCHIJAA | buildcraftrobotics    | 7.99.15                     | buildcraft-7.99.15.jar                          | None                                     |
	| UCHIJAA | buildcraftsilicon     | 7.99.15                     | buildcraft-7.99.15.jar                          | None                                     |
	| UCHIJAA | buildcrafttransport   | 7.99.15                     | buildcraft-7.99.15.jar                          | None                                     |
	| UCHIJAA | codechickenlib        | 3.1.6.339                   | CodeChickenLib-1.12.2-3.1.6.339-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAA | redstoneflux          | 2.0.1                       | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJAA | cofhcore              | 4.3.10                      | CoFHCore-1.12.2-4.3.10.5-universal.jar          | None                                     |
	| UCHIJAA | cofhworld             | 1.1.1                       | CoFHWorld-1.12.2-1.1.1.12-universal.jar         | None                                     |
	| UCHIJAA | cfm                   | 4.2.0                       | furniture-4.2.0-1.12.2.jar                      | None                                     |
	| UCHIJAA | ic2                   | 2.8.70-ex112                | industrialcraft-2-2.8.70-ex112.jar              | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJAA | mantle                | 1.12-1.3.1.21               | Mantle-1.12-1.3.1.21.jar                        | None                                     |
	| UCHIJAA | tconstruct            | 1.12.2-2.9.1.65             | TConstruct-1.12.2-2.9.1.65.jar                  | None                                     |
	| UCHIJAA | galacticraftcore      | 4.0.1.166                   | GalacticraftCore-1.12.2-4.0.1.166.jar           | None                                     |
	| UCHIJAA | galacticraftplanets   | 4.0.1.166                   | Galacticraft-Planets-1.12.2-4.0.1.166.jar       | None                                     |
	| UCHIJAA | flammpfeil.slashblade | mc1.12-r12                  | SlashBlade-mc1.12-r12.jar                       | None                                     |
	| UCHIJAA | thermalfoundation     | 2.3.10                      | ThermalFoundation-1.12.2-2.3.10.6-universal.jar | None                                     |
	| UCHIJAA | thermalexpansion      | 5.3.10                      | ThermalExpansion-1.12.2-5.3.10.15-universal.jar | None                                     |
	| UCHIJAA | twilightforest        | 3.6.345                     | twilightforest-1.12.2-3.6.345-universal.jar     | None                                     |
	| UCHIJAA | nucleus               | 1.3.1-S7.0                  | 插件_ess必备Nucleus-1.3.1-S7.0-MC1.12.2-plugin.jar  | None                                     |
	| UCHIJAA | npcs                  | 2.0.2-API7                  | 插件_NPCs-2.0.2-API7.jar                          | None                                     |
	| UCHIJAA | pjc                   | 0.2.1                       | 插件_pj核心projectcore-7.0.0-0.2.1.jar              | None                                     |
	| UCHIJAA | worldedit             | 6.1.9-SNAPSHOT              | 插件_WEworldedit-sponge-6.1.9-SNAPSHOT-dist.jar   | None                                     |
	| UCHIJAA | pjp                   | 0.14.3                      | 插件_传送门projectportals-7.1.0-0.14.3.jar           | None                                     |
	| UCHIJAA | redprotect            | 7.3.0                       | 插件_保护RedProtect-7.3.0-b68-Universal.jar         | None                                     |
	| UCHIJAA | universalmarket       | 1.0                         | 插件_全球市场universvalmarket.jar                     | None                                     |
	| UCHIJAA | payday                | 1.4.0                       | 插件_在线送钱PayDay-1.4.0.jar                         | None                                     |
	| UCHIJAA | plotsquared           | 3.5.0-SNAPSHOT              | 插件_地皮PlotSquared.jar                            | None                                     |
	| UCHIJAA | stackban              | 0.3.0                       | 插件_封禁物品stackban-7.1.0-0.3.0.jar                 | None                                     |
	| UCHIJAA | luckperms             | 4.1.16                      | 插件_权限luckPerms-Sponge-4.1.16.jar                | None                                     |
	| UCHIJAA | economylite           | 2.13.0                      | 插件_经济EconomyLite-7.0.0-2.13.0.jar               | None                                     |
	| UCHIJAA | virtualchest          | @version@                   | 插件_菜单VirtualChest.jar                           | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.166.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
SpongeCoremod (spongeforge-1.12.2-2611-7.1.0-BETA-2990.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
