### ISSUE TITLE
not in a plot area problem

### ISSUE THREAD

**Issue by ALetsPlayYT** [IntellectualSites/PlotSquared#1908]
**Debug paste link:** 
https://hastebin.com/elelekodaq

**Description of the problem:** 
Hey everyone,

I have a little problem.
I created a new PlotWorld with /p setup and followed all steps. In the end a world was created and we changed the street design to an own one. As last step we made the world as standard world via Multiverse Core. Today I wanted to test if everything works fine. But when I try to use /p auto I get the error "You are not in a plot area!" But why? I'm in the world I created via /p setup.
Here is the worlds.yml:
https://hastebin.com/enirenivag.cs

I hope you can help me.

With best regards,

ALetsPlay

**Comment by boy0001** [comment]
See: https://github.com/IntellectualSites/PlotSquared/wiki/Manual-generator-setting
