### ISSUE TITLE
Chunk issue?

### ISSUE THREAD

**Issue by xion87** [IntellectualSites/PlotSquared#1909]
**Debug paste link:** 

https://hastebin.com/toqayisawa

**Description of the problem:** 
I got these massive spam on console when chunk loading sometimes: 
https://hastebin.com/pizekonade.md

**How to replicate:** 
Dunno happen often, sometimes is really spammy and kill the server

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by M1SM4TCH** [comment]
It happens the same here, randomly

**Comment by xion87** [comment]
it was fixed i think

**Comment by RedstoneFuture** [comment]
Great. :)
