### ISSUE TITLE
permission  problem

### ISSUE THREAD

**Issue by sdsbfanFTW** [IntellectualSites/PlotSquared#1910]
I have a server running this plugin using Bukkit, and when someone goes to do `/plot auto` they get a message saying something about permission nodes.  I'm not sure how to edit this because my server is new.

**Comment by RedstoneFuture** [comment]
plugins/PlotSquared/translations/PlotSquared.use_THIS.yml
-->


`permission:
  no_schematic_permission: $2You don't have the permission required to use schematic $1%s
  no_permission: '$2You are lacking the permission node: $1%s'`

**Comment by sdsbfanFTW** [comment]
I now know where that file is but what exactly do I do with it?

**Comment by RedstoneFuture** [comment]
You would like "edit this" ... you can edit this. In the language configuration.

If you would like fix this permission problem check the P² permission list and give the player the specify permission.

**Comment by RedstoneFuture** [comment]
https://github.com/IntellectualSites/PlotSquared/wiki/Commands-and-Permissions
Help this?

**Comment by RedstoneFuture** [comment]
Have you still this problem?
