### ISSUE TITLE
Not able to delete a plot 

### ISSUE THREAD

**Issue by N0tMyFaultOG** [IntellectualSites/PlotSquared#1912]
**Debug paste link:** 
https://hastebin.com/ajayinetol

**Description of the problem:** 
While trying to delete a plot on PS-Sponge it printed this in the console, I wasn't able to delete the plot
This is the error it showed in console: https://hasteb.in/uqupuzik.yaml

**How to replicate:** 
Use the latest build for sponge, claim a plot and try to delete it via /p del

**Checklist**:
- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by AokuYuki** [comment]
Hey there, i got the same problem.

My debug log: https://hastebin.com/xawacacoku
I am using PlotSquared-Sponge-18.07.06-ae1e58c-2021.jar

How to replicate:
I Claim a plot and try to delete it via /plot delete

**Comment by N0tMyFaultOG** [comment]
```
java.lang.UnsupportedOperationException: Not Supported/Not implemented yet
```
Some of the functions of the spigot PlotSquared aren't implemented in the sponge build yet.

**Comment by AokuYuki** [comment]
Then its not possible for a player to get rid of a plot he claimed, yet?

**Comment by ThornsOfire** [comment]
Subscribed for updates thanks @N0tMyFaultOG
