### ISSUE TITLE
Integrating an own moneyapi

### ISSUE THREAD

**Issue by dlimerick** [IntellectualSites/PlotSquared#1917]
Hello,
I have a question is there a way that I can integrate my own money api? If I can do this, where are the files for the Vault manager?
Thanks for help, sorry for my bad english!

**Comment by RedstoneFuture** [comment]
API Documentation: https://github.com/IntellectualSites/PlotSquared/wiki/Developer-documentation-(WIP)

**Comment by boy0001** [comment]
PlotSquared hooks with Vault, so as long as your plugin is Vault compatible it will work. 
i.e.
Implement Vault's [Economy](https://github.com/MilkBowl/VaultAPI/blob/master/src/main/java/net/milkbowl/vault/economy/Economy.java
) API, then register it:
```Java
Bukkit.getServicesManager().register(Economy.class, instanceExtendingEconomy, vaultInstance, ServicePriority.Normal);
```
