### ISSUE TITLE
WARN java.lang.NullPointerException

### ISSUE THREAD

**Issue by Cobwebster** [IntellectualSites/PlotSquared#1919]
https://pastebin.com/du4k5P44

Latest plot squared and server version 1.12.2

**Comment by RedstoneFuture** [comment]
Have you still this problem?

**Comment by Cobwebster** [comment]
haven't seen it in awhile, i'll let you know if it occurs again. not sure what caused it.

**Comment by RedstoneFuture** [comment]
Ok, thank you.
