### ISSUE TITLE
Banned people can still "talk" in plot chat on banned plots

### ISSUE THREAD

**Issue by xion87** [IntellectualSites/PlotSquared#1922]
**Debug paste link:** 
https://hastebin.com/xukawujohu

**Description of the problem:** 
Banned poeple can still "talk on people where they are banned

**How to replicate:** 
1)go in plot angle like this
![image](https://user-images.githubusercontent.com/3611852/38773062-9c8c80ec-4044-11e8-8bb6-e8dd10a24712.png)

2) write something, you will see nothing in chat, but people into plots will see the  the local chat from the banned player

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
hey @xion87 
Is this still an issue with newer builds for 1.12.2 and/or P2 4 for 1.13.2?
If it is, can you give us a new /plot debugpaste  please?

**Comment by AeSix** [comment]
I did some testing, Spigot 1.13.2 / P2 4.305:
Player1 is in plot, has /p chat enabled
Player2 is in plot, has /p chat enabled as well. 
Player1 /p deny player2
player2 stands on plot border wall
player2 sends chat, does not see the chat
player1 sees player2 plot chat

It would appear to me that either plot chat includes the plot wall where plot deny does not (allowing players on the plot wall when denied)  -or- chat sending back from the server to players is being canceled for the wrong recipients (chat should be sent back to the denied player, but NOT to other players)

Thus, denying a player from one's plot does not prevent the players on that plot from seeing the denied player's chat - even though they cannot see their own chat.
