### ISSUE TITLE
Permpack permissions not giving perms

### ISSUE THREAD

**Issue by ShawnPR1** [IntellectualSites/PlotSquared#1924]
Hi there. I'm having some issues with the basic permpack permissions. I have given the default group the following permissions using PEX:
• plots.use
• plots.plot.1
• plots.permpack.basic
• plots.permpack.basicflags
• plots.permpack.basicinbox

Yet the default group cannot use any commands regarding PlotSquared. I have reloaded PermissionsEx (seeing as it has to be done at times for permissions to take effect) to no avail. I can just add the individual permissions and it'll work as I have tested it, but why do the permpack permissions not work?

I hope I supplied enough info and I also hope that I'm doing everything right. This plugin is amazing and would just be a tad better if the permpack permissions could work. Would be way more convenient.

**Comment by RedstoneFuture** [comment]
Plotsquared send you a ingame-messages with the missiong permission. What is missing? E.g. "`plots.permpack.basicflags`" include not all flags-permissions. And not all permission systems have never problems with a group permission like "`plots.permpack.basic`". At my server I know problems with this. But currently it worked. ^^

**Comment by RedstoneFuture** [comment]
And a tip: restart the server if you test plotsquared permissions or redefine the permission-chache-option in the /plugins\PlotSquared\config/settings.yml :
```

  # Optimizes permission checks
  permission-cache: true
```

**Comment by RedstoneFuture** [comment]
No, you have a other problem: with PEX

```
  Mitglied:
    permissions:
    - plots.use
    - plots.plot.1
    - plots.permpack.basic
    - plots.permpack.basicflags
    - plots.permpack.basicinbox
```

I can use plotsquared. Can I see (a part of) the permissions.yml ?

**Comment by ShawnPR1** [comment]
Hi there. Sorry for my absence I was busy with a lot of other stuff. I've tested it again and it seems everything is working fine. I might do further intensive testing, but I think restarting solved the issue. Thanks for your help!

**Comment by RedstoneFuture** [comment]
Great! :)
