### ISSUE TITLE
Issue with the Use Flag

### ISSUE THREAD

**Issue by MamaBeau** [IntellectualSites/PlotSquared#1926]
**Debug paste link:** 
https://hastebin.com/xewuhodigu

**Description of the problem:** 
When using /plot flag set use <item id>, it does not allow the player to use the item specified in the region. In this case doors of any kind.

**How to replicate:** 
In game do /plot flag set use 324 and have a visitor test opening the door on your plot.

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
324 is the item id. You need to use the block id for the door:
https://minecraft-ids.grahamedgecombe.com/
