### ISSUE TITLE
Nukkit World possible already loaded

### ISSUE THREAD

**Issue by nilsbrychzy** [IntellectualSites/PlotSquared#1927]
# Bug report template 

**Debug paste link:** 
```
[P2] latest.log is too big to be pasted, will ignore
```
latest.log doesn't exist in Nukkit. It's called server.log.

https://hastebin.com/ahunutaheq

**Description of the problem:** 
```
[INFO] Preparing level "plot"
[INFO] [P2] Detected world load for 'plot'
[INFO] [P2]  - generator: PlotSquared>PlotSquared
[INFO] [P2]  - plotworld: com.intellectualcrafters.plot.generator.HybridPlotWorld
[INFO] [P2]  - manager: com.plotsquared.nukkit.NukkitMain
[INFO] [P2]  - schematic: false
[INFO] World possibly already loaded: plot
[INFO] World possibly already loaded: plot
[INFO] World possibly already loaded: plot
[INFO] World possibly already loaded: plot
[INFO] World possibly already loaded: plot
[INFO] World possibly already loaded: plot
[INFO] World possibly already loaded: plot
[INFO] World possibly already loaded: plot
[INFO] World possibly already loaded: plot
[INFO] World possibly already loaded: plot
[INFO] World possibly already loaded: plot
[INFO] World possibly already loaded: plot
```

**How to replicate:** 
```
Create a plot with Nukkit and load some chunks.
```

**Checklist**:
- [X] I included a `/plot debugpaste` link 
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Can be ignored. Happens because nukkit initializes the generator with multiple threads.
