### ISSUE TITLE
Players spawn under the ground

### ISSUE THREAD

**Issue by maxlehot1234** [IntellectualSites/PlotSquared#1932]
**Debug paste link:** 
https://hastebin.com/nanerepade

**Description of the problem:** 
Why players spawn in the plot 1;1 all the time under the ground and not in the ./warp plots, mvspawn I set??

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by maxlehot1234** [comment]
Now I get this error when player join the server and they are teleported to the lobby/disconnect completly

https://paste.powerplugins.net/omecujuzav.php

Simply can't join the server even after a server full reset and the plots world reset...

**Comment by DeadMaster121** [comment]
Hey,

I replied to what you said in the discussion section on Spigot, try doing what I said there, from what I see in that error when a player joins I can tell you that PlotSquared should not have anything related to this. Would be more related to MutliCraft. I have noticed that your PlotSquared is not the latest version, I would update if I was you to fix other bugs.

**Comment by maxlehot1234** [comment]
Fix now. Thanks again
