### ISSUE TITLE
Question about /plot area create

### ISSUE THREAD

**Issue by topthat177** [IntellectualSites/PlotSquared#1936]
# Question:

When I do /plot area create world:test [<Modifier>=<value>]... it doesn't use the world test im standing in and it creates the world 'world' and teleports me to it. Am I doing something wrong? Using the latest version of P2 on 1.12.2 Spigot Server.

Appologies if this is in the wrong place.

**Comment by RedstoneFuture** [comment]
`/plot area create [world[:id]] [<modifier>=<value>]...`

Write: "/p area create test"

**Comment by RedstoneFuture** [comment]
Do you have any other questions?

**Comment by topthat177** [comment]
Yer I tried your suggestion and it just told me that 'that world already exists'. I have a world already imported onto my server which has some terrain and features so its not completely boring and flat and I wan't to put plots on it. Whats the best way to do this? Thanks.

**Comment by RedstoneFuture** [comment]
Have you Mulstiverse? Than you can import this world with "/mv import <worldname> normal -g PlotSquared"

**Comment by topthat177** [comment]
This happened

https://gyazo.com/8c78848a697017c1aa694631334605ba

**Comment by topthat177** [comment]
Then if I do /plot area regen it tells me to stop server and delete the Test/region. Then it just generates a flat world with plots and no terrain.

**Comment by DeadMaster121** [comment]
Try this:

/mv create Plots normal -g PlotSquared:s=42

This will create a world with the name "Plots" and the size will be "42x42" per plot.
If this does not work, then it could be another plugin that creates/handles world creating interfering.

**Comment by RedstoneFuture** [comment]
> https://gyazo.com/8c78848a697017c1aa694631334605ba

In this situation I stop the server, delete all world-chnks of this plot-world, restart the server. Than the generator of the plotworld is correctly and plotsquared will override all minecraft generators for this definded plotworld (and not to generate a flatworld - plotworld mix).

**Comment by topthat177** [comment]
@DeadMaster121 I generated a world just using the minecraft single player which is flat but just has a few trees and stuff scattered around so its not completely boring and flat. Im then trying to generate plots in this world but so far no luck.

**Comment by topthat177** [comment]
@RedstoneFuture I did that, stopped the server and deleted everything from inside the Region File and restarted the server. It deleted everything in the world and generated it as a default PlotSquared world.

**Comment by RedstoneFuture** [comment]
@topthat177 

> I generated a world just using the minecraft single player which is flat but just has a few trees and stuff scattered around so its not completely boring and flat. Im then trying to generate plots in this world but so far no luck.

What kind of design you would like? If you would like get trees in your plots you can use the schematic-function of plotsquared.

> I did that, stopped the server and deleted everything from inside the Region File and restarted the server. It deleted everything in the world and generated it as a default PlotSquared world.

Right. And then it must work. But your solution is like the picture?

**Comment by RedstoneFuture** [comment]
Status?

**Comment by topthat177** [comment]
@RedstoneFuture Nothing I tired from your instructions worked. It always ended up like the picture with bits of plots and chunks everywhere. If I deleted the info from the region file it wiped everything and generated basic plotsquared world completely flat. Default Plots.

**Comment by topthat177** [comment]
The only thing with the schematic function is that it would be the same trees in every plot. I had a flat word generated with random trees.

**Comment by RedstoneFuture** [comment]
And if you create a new world with mutliverse (/mv create Test1 normal -g Plotsquared) and copy&paste step by step the old world-configuration-options in the Test1? Check every time with "/p reload" and "/p regenallroads" the style of the new generated chunks in the distance of this world. (!! If you have after a step a problem you show the wrong confuguration-part and can fix it.) And at the end stop the server, delete the worldfile of Test1 and the old-plotworld; reconfigurate your multiverse and the worlds.yml of plotsquared and start the server. Then Test1 named now like th eold world, the old world is deleted and all chunks are correctl.

**Comment by topthat177** [comment]
@RedstoneFuture Thanks so much for you help. I've given up for now and am just using default plots with nothing in them. Maybe one day ill look into it again and see if I can get it to work. Too much effort and stuffing around for a small gain atm. As I said, thanks heaps, you have been very prompt and supportive. 👍

**Comment by RedstoneFuture** [comment]
Okay :) Reopen or open a new issue if you work again at this problem and need help.

**Comment by boy0001** [comment]
wrong issue tagged
