### ISSUE TITLE
NukkitPlotGenerator does not work properly

### ISSUE THREAD

**Issue by nilsbrychzy** [IntellectualSites/PlotSquared#1937]
**Debug paste link:** 
https://hastebin.com/nolutisuyu

**Description of the problem:** 
https://puu.sh/Aez1y/bce4e4aa6f.jpg

**How to replicate:** 
1. Create a plot world with a schematic for roads
2. Create a new world and enter it
3. World is detected as plot world but it isn't
4. World generator from first world is reset to default values

**Checklist**:
- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by lhochbaum** [comment]
The world name does not seem to be updating if I switch back to the plot world, which causes the plugin to use the new world's generator for my plot world.

I have added a debug message inside of the `loadWorld` method of `PS.java`:
This was printed when I flew around in my plot world first.
```
21:23:28 [INFO] Current world: world
21:23:28 [INFO] Current world: world
21:23:28 [INFO] Current world: world
21:23:28 [INFO] Current world: world
21:23:28 [INFO] Current world: world
21:23:28 [INFO] Current world: world
21:23:28 [INFO] Current world: world
21:23:28 [INFO] Current world: world
21:23:28 [INFO] Current world: world
21:23:28 [INFO] Current world: world
21:23:28 [INFO] Current world: world
```
When I flew around in my newly created `test` world, nothing was printed?

And finally, when I went back to `world`:
```
21:24:31 [INFO] Current world: test
21:24:31 [INFO] [P2] Detected world load for 'test'
21:24:31 [INFO] [P2]  - generator: PlotSquared>PlotSquared
21:24:31 [INFO] [P2]  - plotworld: com.intellectualcrafters.plot.generator.HybridPlotWorld
21:24:31 [INFO] [P2]  - manager: com.plotsquared.nukkit.NukkitMain
21:24:31 [INFO] [P2]  - schematic: false
21:24:31 [INFO] Current world: test
21:24:31 [INFO] Current world: test
21:24:31 [INFO] Current world: test
21:24:31 [INFO] Current world: test
21:24:31 [INFO] Current world: test
21:24:32 [INFO] Current world: test
21:24:33 [INFO] Current world: test
```

This looks a bit weird if you ask me :D

**Comment by dordsor21** [comment]
If you still have this issue, reopen.

**Comment by WapitiAcht2777** [comment]
Have the same issue
