### ISSUE TITLE
Not changing gamemode after relog

### ISSUE THREAD

**Issue by N0tMyFaultOG** [IntellectualSites/PlotSquared#1938]
**Debug paste link:** 
https://hastebin.com/difijorine

**Description of the problem:** 
If you set the flag `gamemode:survival`, players are able to bypass it if they just relog. Once they logged back in, they can fly around and can use creative

**How to replicate:** 

**1.** /p f set gamemode survival
**2.** Log off the server and log back in
**3.** You are in creative, 

**Checklist**:
- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
Right. And after other teleport events e.g. /tp command.

**Comment by boy0001** [comment]
It's changing my gamemode fine, you must have some other plugin which is setting the gamemode when a player joins.

**Comment by RedstoneFuture** [comment]
@N0tMyFaultOG Interesting. Then I think it's maybe Multiverse Core.
