### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by Lurreisper** [IntellectualSites/PlotSquared#1940]
> [17:17:10 WARN]: java.lang.NullPointerException
> [17:17:10 WARN]: at com.plotsquared.bukkit.BukkitMain$4$1.run(BukkitMain.java:470)
> [17:17:10 WARN]: at com.plotsquared.bukkit.BukkitMain$4$1.run(BukkitMain.java:307)
> [17:17:10 WARN]: at com.intellectualcrafters.plot.PS.foreachPlotArea(PS.java:1801)
> [17:17:10 WARN]: at com.plotsquared.bukkit.BukkitMain$4.run(BukkitMain.java:307)
> [17:17:10 WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
> [17:17:10 WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)
> [17:17:10 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783)
> [17:17:10 WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
> [17:17:10 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
> [17:17:10 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
> [17:17:10 WARN]: at java.lang.Thread.run(Thread.java:748)

What's this error?

**Comment by RedstoneFuture** [comment]
1. include a `/plot debugpaste` link
2. Whan you get the warn?
3. It this the full warn messages?

**Comment by Lurreisper** [comment]
https://hastebin.com/cukedokezo

**Comment by boy0001** [comment]
Update the plugin.
