### ISSUE TITLE
Everybody can build on any plot??? The claimed plots too! Please help

### ISSUE THREAD

**Issue by enriquesw** [IntellectualSites/PlotSquared#1941]
# Bug report template 

**Debug paste link:** 

**Description of the problem:** 

**How to replicate:** 

**Checklist**:

- [] I included a `/plot debugpaste` link
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [] I Made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
Check this side. The permission system of P² work great. You have only a fail in your permission configuration, I think. https://github.com/IntellectualSites/PlotSquared/wiki/Commands-and-Permissions

**Comment by enriquesw** [comment]
Yes Thanks I had a permissions problem!

**Comment by RedstoneFuture** [comment]
Good. :)
