### ISSUE TITLE
Metrics & plot download

### ISSUE THREAD

**Issue by SrLeojaco** [IntellectualSites/PlotSquared#1946]
# Bug report template 

**Debug paste link:** https://hastebin.com/esagohizem

**Description of the problem:** 
If you disable metrics, but you HOST THE PLOT WEB INTERFACE, it is still showing the message:

"Please enable metrics in order to use this command - Or host it yourself if you don't like the free service"

**How to replicate:** Disable metrics and set a different plot web interface

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
= a small messages bug?

**Comment by boy0001** [comment]
Please update PlotSquared. You shouldn't need to enable metrics for any functionality.
