### ISSUE TITLE
Dispenser throws lava/water over plot border

### ISSUE THREAD

**Issue by N0tMyFaultOG** [IntellectualSites/PlotSquared#1950]
**Debug paste link:** 
https://hastebin.com/aqegacefop

**Description of the problem:** 
Placing a dispenser behind and above the plot border and dispense water or lava. It will float over the plot border.

**How to replicate:** 
1. Claim a plot
2. Place a dispenser with water/lava in 1 block behind above the plot border (check image below)
3. Activate the dispenser
![](https://i.imgur.com/f2lwp3V.png)

**Checklist**:
- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
duplicate issues
