### ISSUE TITLE
Unable to claim any new plots after today's update

### ISSUE THREAD

**Issue by NerdyBirder** [IntellectualSites/PlotSquared#1953]
**Debug paste link:** 
https://hastebin.com/qomoqavode

**Description of the problem:** 
After the plugin automatically updating this morning, No one is able to claim plots in our plot worlds anymore. The problem was not there yesterday and I left the server last night after a restart for a new world with no problems. I do not think that another plugin could be causing this problem as it seems to be plotsquared specific and nothing has changed with other plugins in the past 24 hours.

When a player is trying to claim a plot in either the new plot world or our existing one they get the message: "you can not claim any more plots" even if the player has no claimed plots at all. The permission to claim plots (plots.claim.1 and plots.claim.2) are true for everyone on the server and right now only admins can claim plots for players.

**How to replicate:** 
Not sure if this problem is able to be replicated because i do not know the specific source of the issue.

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
Use only "`plots.claim.2`".

**Comment by NerdyBirder** [comment]
I made sure that the default group only has the permission plots.claim.2 and i am still getting the same error: "You can't claim more plots...." even though this account has no plots at all.

**Comment by RedstoneFuture** [comment]
Maybe because https://github.com/IntellectualSites/PlotSquared/commit/550df7f232e48f4db39ac5abfc3dcec1fdc1de26

**Comment by RedstoneFuture** [comment]
And if you use "`plots.plot.1`" ?

> plots.plot.4 | Limit to 4 claimed plots
> -- | --

https://github.com/IntellectualSites/PlotSquared/wiki/Commands-and-Permissions




> Other
> 
>     plots.plot.<#>
>     plots.claim." + schemati
>     plots.claim.<arg>
>     plots.admin.command.schematic

**Comment by NerdyBirder** [comment]
We use "plots.plot.2" to allow players to get 2 plots per world. Also, I am sorry but i am not sure what you mean by "Maybe because 550df7f".

**Comment by RedstoneFuture** [comment]
This was a information about the last change.
Use mean you use "plots.claim.2"? Have you still this problem with "plots.plot.2"?

**Comment by NerdyBirder** [comment]
Both plots.claim.2 and plots.plot.2 are true in permissions for players. Should we just be using 1 of them?

**Comment by NerdyBirder** [comment]
Ok. I have fixed that permissions problem.
