### ISSUE TITLE
dispenser und dropper can't drop a item

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquared#1956]
Since the last updates dispenser and dropper can't drop someone item in the plot.

Maybe because: https://github.com/IntellectualSites/PlotSquared/issues/1573

**EDIT:** because 5cb94f3

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report
- [X] I made sure I am using an up-to-date version of PlotSquared

**Comment by N0tMyFaultOG** [comment]
If I place them on the plot they work, placing them on the edge like on the reference above doesn't work.
Running latest P2 build

**Comment by RedstoneFuture** [comment]
@N0tMyFaultOG Yes. I use the last version. And no, it doesn't work. Only water or lava block will spawn or respawn, but the item-drop is stopped.

**Comment by RedstoneFuture** [comment]
With the change #589 -> #590

**Comment by RedstoneFuture** [comment]
With this fix:
https://github.com/IntellectualSites/PlotSquared/commit/5cb94f3e45f4555c424524e7a3a7e79b92b0379e

![2018-05-21_06 01 32](https://user-images.githubusercontent.com/4140635/40290142-72e9da5c-5cbc-11e8-876f-0dc6d0d7ced5.png)

**Comment by IAlekseyI22** [comment]
Yes, when it will be fixed??

**Comment by RedstoneFuture** [comment]
I think currently the devs have many to do. We must wait.

**Comment by CraigStr** [comment]
I'm also having this issue, but considering that 1.13 is coming out soon, it'll probably be merged into that update. But hopefully it'll happen sooner than later.

**Comment by RedstoneFuture** [comment]
@boy0001 
fast to fix: IF you undoing #5cb94f3 it will work I think.

**Comment by dextonanderson** [comment]
Also having this issue

**Comment by RedstoneFuture** [comment]
Fixed in the last version (tested in 1.13)
