### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by Manolo8** [IntellectualSites/PlotSquared#1959]
I just want to share some code to improve the performance of the plugin, it will not be easy to use them, but it would be useful

Gerenate an unique ID based on xx and zz position
`    public static int generate(int xx, int zz) {
        int id = 1;
        int x = 0;
        int z = 0;
        boolean isZLeg = false;
        boolean isNeg = false;
        int length = -1;
        int current = 0;

        while (true) {
            if (current < length)
                current++;
            else {
                current = 0;
                isZLeg ^= true;
                if (isZLeg) {
                    isNeg ^= true;
                    length++;
                }
            }

            if (isZLeg) z += (isNeg) ? -1 : 1;
            else x += (isNeg) ? -1 : 1;

            if (x == xx && z == zz) return id;

            id++;
        }
    }`

reverse process:
`public static PosXY generate(int id) {
        int x = 0;
        int z = 0;
        boolean isZLeg = false;
        boolean isNeg = false;
        int length = -1;
        int current = 0;

        while (id > 0) {
            id--;
            if (current < length)
                current++;
            else {
                current = 0;
                isZLeg ^= true;
                if (isZLeg) {
                    isNeg ^= true;
                    length++;
                }
            }

            if (isZLeg) z += (isNeg) ? -1 : 1;
            else x += (isNeg) ? -1 : 1;
        }

        return new PosXY(x, z);
    }`

I got this code from some other plugin (WorldBorder '-') Have other ways, but that is more easy...
after the 1 million plot, you may have a performance problem when creating a plot, but, you can just limit that...

And... How to find an new plot from the database:

`"SELECT pos +1 FROM plots WHERE worldId=? AND pos + 1 NOT IN (SELECT pos FROM plots WHERE worldId=?) LIMIT 1;";`

The plot column will need and new column, if you implement that...

https://i.imgur.com/9KlFXmn.png

**Comment by boy0001** [comment]
Uh, a while loop like that isn't efficient at all. PlotSquared uses a PlotId object which is just a pair of the x,z position. 

btw, to combine numbers, you'd use a pairing function, which is fairly easy to do:
https://en.wikipedia.org/wiki/Pairing_function
Here are some examples of pairing various types:
https://github.com/boy0001/FastAsyncWorldedit/blob/master/core/src/main/java/com/boydti/fawe/util/MathMan.java#L163

**Comment by Manolo8** [comment]
Well, after 100.000.000 of plotid generated, the code will need 250 milliseconds to generate an new id...
Or you can use spiral format, and 100.000.000 will take fell nanoseconds, but will create a circle of plots

I created this issue because, with that code, to create an "auto plot", it would be nescessary only to run an query in the db and execute that (bad code '-'), not being necessary to store any other information, but if my idea is bad, sorry
