### ISSUE TITLE
Road not visible

### ISSUE THREAD

**Issue by MinisBett** [IntellectualSites/PlotSquared#1965]
# Bug report template 

**Debug paste link:*I get an error when I execute /plot debugpaste(https://hastebin.com/xesafeluzo.md)* 

https://hastebin.com/xesafeluzo.md

**Description of the problem:** 
When I create an augmented world the road is not visible

**How to replicate:** 

Create a augmented plot world

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by MinisBett** [comment]
`Console.WriteLine("test");`

**Comment by RedstoneFuture** [comment]
By default you have not a problem with this. Use you the addon "PlotHider"? / Have the testuser all permissions (admin)?

And after a restart too? It the world correctly?

**Comment by MinisBett** [comment]
I dont use any addon. My testuser is an operator. Yes, I use an up-to-date version

**Comment by MinisBett** [comment]
Redstone I think wenn we reden on german dann we cannen uns besser understanden xD
Also ich nutze keine Addos, bin Operator und nutze die neuste Version... Ne Idee?

**Comment by RedstoneFuture** [comment]
:D Okay.

Aber für Ideen weiß ich wohl noch zu wenig. Also ein Adminerstellt eine Plotwelt und dann sieht es wie aus? Zeig mal ein Screenshot. Vielleicht liegt es einfach an den Einstellungen der Welt in der `config/worlds.yml`.
