### ISSUE TITLE
Nukkit road schematic randomly stops working + defaults to default settings

### ISSUE THREAD

**Issue by Cobwebster** [IntellectualSites/PlotSquared#1969]
latest nukkit and plotsquared nukkit, using road schematics seems to have a limited effect. It randomly just goes back into the default schematic, even despite running plot regenallroads.

https://gyazo.com/60ed9b9b576adb9e15f213a397a2db89

not sure why it'd do this, no errors.

EDIT*

looks like it goes beyond just roads, https://gyazo.com/1d82ba4bc3306878d5d162f8ba974acb

just resets to the default world generator despite the options never changing.

**Comment by Cobwebster** [comment]
Bump, this issue makes the nukkit port over unusable for any server.

**Comment by Cobwebster** [comment]
??

**Comment by dordsor21** [comment]
Not been able to replicate with server restarts/etc locally, albeit over a short period of time

**Comment by AeSix** [comment]
@Cobwebster Any changes on this?

**Comment by GamerDaniel3000** [comment]
I have this issue too ._.
