### ISSUE TITLE
PlotSqared Welt importieren

### ISSUE THREAD

**Issue by Spark61** [IntellectualSites/PlotSquared#1973]
Hallo,
ich habe mir heute eine ganz schöne Plotwelt aus den Internet gedownloadet die habe ich einmal als Welt und einmal als schematik. Wie kann ich die nun in PlotSqared importieren so das sie auch geht?

LG Spark61

**Comment by RedstoneFuture** [comment]
https://github.com/IntellectualSites/PlotSquared/issues/1974

Ansonsten einfach /mv create <Weltname> -gPlotSquared, dann den Server stopen und die gedownloadete Welt ersetzen.
