### ISSUE TITLE
Welt gebaut noch importieren | Still built world import

### ISSUE THREAD

**Issue by Spark61** [IntellectualSites/PlotSquared#1974]
Hallo ich habe gerade bei einen Plot die straße verändert und möchte jetzt auch haben das die straße überall so wie wie kann ich das machen?

----------------------------------------------------------------------------------------------------------------------
Hello I have just changed the street with a plot and now would like to have the street everywhere so how can I do that?

**Comment by N0tMyFaultOG** [comment]
Follow these steps https://github.com/IntellectualSites/PlotSquared/wiki/Installation#adding-road-schematics
