### ISSUE TITLE
Plotnachricht auschalten  Switch off plot message

### ISSUE THREAD

**Issue by Spark61** [IntellectualSites/PlotSquared#1975]
Hallo,
ich möchte bei meinen Spawnplot die Nachricht deaktivieren wenn man drauf von wen das Plot ist. Aber nur bei den Plot.

Hello,
I would like to deactivate the message at my Spawnplot if you know who the plot is from. But only at the plot.

**Comment by RedstoneFuture** [comment]
`/p flag set titles false`
