### ISSUE TITLE
CloudNetAPI permission problem | "You can't claim more plots." | plots.plot.<x> problem

### ISSUE THREAD

**Issue by MatrixSystemPVP** [IntellectualSites/PlotSquared#1976]
Plot debugpaste --> https://hastebin.com/zamuganure

Hey,
I have a creative server and nobody can claim plots the player rank have the right permission to claim but it doesnt work. when a player tries to claim a plot then this message comes "You can't claim more plots." but the player doesnt have any plot. When i do /plot list <playername> the comes "Found no plots with your search query" thet means that the player doesnt have a plot.
Alle players have the permissions:
      - plots.use
      - plots.info
      - plots.auto
      - plots.home
      - plots.clear
      - plots.delete
      - plots.list
      - plots.list.mine
      - plots.visit
      - plots.visit.*
      - plots.chat
      - plots.confirm
      - plots.denied
      - plots.add
      - plots.trust
      - plots.deny
      - plots.remove
      - plots.untrust
      - plots.undeny
      - plots.kick
      - plots.claim
      - plots.plot.1

i hope somebody can help me thanks :=)

**Comment by RedstoneFuture** [comment]
Hello. Can you try it with this permissions:

    - plots.use
    - plots.plot.1
    - plots.permpack.basic
    - plots.permpack.basicflags
    - plots.permpack.basicinbox
    - plots.chat.color


At my testserver it works: The user can use `/p claim` for one plot.


tested with:
- PlotSquared-Bukkit-18.05.18-4063525-2001.jar
- Spigot 1.12.2

**Comment by MatrixSystemPVP** [comment]
It worked at the beginning but at some point it was not anymore working.
when yoi will you can come and test with me on my server --> matrixgaming.ddns.net

**Comment by RedstoneFuture** [comment]
Any errors?

**Comment by MatrixSystemPVP** [comment]
you cant claim more plots

Spigot Version 1.8.8

**Comment by MatrixSystemPVP** [comment]
and i use cperms from cloud net for the permissions

**Comment by RedstoneFuture** [comment]
I mean any stack trace in the console. Ok. ....

**Comment by MatrixSystemPVP** [comment]
no nothing in the log

**Comment by MatrixSystemPVP** [comment]
you can come on my server to creative and test to claim if you want

**Comment by MatrixSystemPVP** [comment]
the players can only claim when they have plots.plot.* but i want that all players can only claim 1 plot

**Comment by MatrixSystemPVP** [comment]
:/

**Comment by MatrixSystemPVP** [comment]
I think i know the problem. I think that the permission plots.plot.1 dont work with permission plugin but with the permission.yml from the server it works. I dont know why.

**Comment by RedstoneFuture** [comment]
Maybe your permission system have a problem with the permission-packs.


It work great with only:

```
    - plots.visit
    - plots.info
    - plots.plot.1
    - plots.claim
    - plots.use
    - plots.delete
    - plots.clear
    - plots.visit.owned
```

**Comment by MatrixSystemPVP** [comment]
I use the Cloud net Permission System Cperms

**Comment by JoshuaPvP** [comment]
I also use CPERMS form CloudNet and it dosent work ...

**Comment by MatrixSystemPVP** [comment]
See what i said the permission node "plots.plot.X" dont work with cperms

**Comment by RedstoneFuture** [comment]
I think this is not a problem of PlotSquared, because with other permission system it works.

**Comment by RedstoneFuture** [comment]
https://github.com/IntellectualSites/PlotSquared/issues/2099

**Comment by RedstoneFuture** [comment]
@boy0001 Must we support CloudNet separate?

**Comment by JoshuaPvP** [comment]
Many Users use CloudNet ...
It will be better when a seperate CloudNet supportet

**Comment by JoshuaPvP** [comment]
@RedstoneFuture,

If you need help with CPerms / CloudNet Support I will help you.
I develop a own Server...
If you want help write a massage here.

Thanks
MySQLInjection |  Systemadministrator

**Comment by RedstoneFuture** [comment]
@JoshuaPvP Currently I don't develope for PlotSquared (I support only at here). The main developer ist boy0001. If you find the problem with CPerms you can help this developer team to fix this or you write and send a pull-request to plotsquared. I find the first option better, because I think its maybe a permission system bug, than a bug of plotsquared and a only-permission-system-support is not the best way to fix this problem. Other plugins have maybe the same problem with CPerms.

Whatever: each help is great! :)

**Comment by dordsor21** [comment]
PlotSquared works fine with every other permissions plugin. If CPerms does things in a silly way we shouldn't need to make a workaround for it.

**Comment by MatrixSystemPVP** [comment]
@dordsor21 The permission "plots.plot.1" also doesn't work in bungeeperms plugin as i heared from others.

For People that want to fix it:
Just set the permission "plots.plot.1" in the permissions.yml of the server --> https://pastebin.com/dQ1TDFVg and all others normaly :D
