### ISSUE TITLE
Plot Merge Request Bypassed When Players Online

### ISSUE THREAD

**Issue by TerraPrimal** [IntellectualSites/PlotSquared#1980]
Greetings Masters Of Thy Plots,

**Description of the problem:** 
Just reporting an issue a player has made me aware of where people are able to force merge a players plot if they're online with out the request being accepted.
Below you will find a rough outline on how to do it, a short video showing the process as well as the debug report that's requested for all Issues.
Before submitting, I made sure we were running the latest DEV build (#598).

If this is due to a simple config error on my behalf, please point and laugh at me as well as letting me know what I have wrong.

Video: https://streamable.com/xiz5q
Debug: https://hastebin.com/owijapejij

**How to replicate:** 
1. Have a plot claimed by you and another person.
2. Look in the direction you want to force merge.
3. Make sure the person of the plot is online, make sure to be standing in your plot facing it.
4. Use the command /p merge.
5. A message will show that a request was made/accepted but it wasn't.

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
Currently I can't replicate this at my testserver with you settings.yml and worlds.yml.

**Comment by TerraPrimal** [comment]
I think you might me onto something with the permissions. Seems I may have lazily added 
    - plots.merge.*
    - plots.unlink.*
If that's the case, I am really sorry for wasting your time, should have checked and at the very least uploaded the perms.

Sorry and thanks RedstoneFuture.

**Comment by RedstoneFuture** [comment]
You need only:

```
plots.merge
plots.merge.<amount>
plots.unlink
```

**Comment by RedstoneFuture** [comment]
Fixed?

**Comment by Sauilitired** [comment]
No response in 25 days. Closing. This issue can be reopened if the issue still persists.
