### ISSUE TITLE
problems with Spawn eggs and spawner

### ISSUE THREAD

**Issue by TomekkStorm** [IntellectualSites/PlotSquared#1981]
# Bug report template 

**Debug paste link:** 

https://hastebin.com/ocukuhanev

**Description of the problem:** 
Spawn eggs, spawner not usable

**How to replicate:** 

It doesn*t work
**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

I can create animals by /spawnmob, but not by egg or spawner

    Server Properties has Animal, Monster and NPC spawning enabled.
    WorldGuard has it enabled, the plot has a region that also has mob-spawning enabled.
    Plots config, Spawn: has breeding, egg and custom set to true.
    Plots config, natural_mob_spawning set to true.
    Plots config, default flags, mob-cap: 50
    The plot it's self has mob-cap: 50 animal-cap: 50 entity-cap: 50 mob-place: true

I hope you can help me

**Comment by RedstoneFuture** [comment]
At my server its work. I will test your config at the next time. But can you test: have you this problem only in y plot world?

**Comment by TomekkStorm** [comment]
Yes it is only in the plotworld 
Am 06.06.18, 19:57, Robert Rauh <notifications@github.com> schrieb:
At my server its work. I will test your config at the next time. But can you test: have you this problem only in y plot world?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/IntellectualSites/PlotSquared/issues/1981#issuecomment-395158935","url":"https://github.com/IntellectualSites/PlotSquared/issues/1981#issuecomment-395158935","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/IntellectualSites/PlotSquared","title":"IntellectualSites/PlotSquared","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/IntellectualSites/PlotSquared"}},"updates":{"snippets":[{"icon":"PERSON","message":"@RedstoneFuture in #1981: At my server its work. I will test your config at the next time. But can you test: have you this problem only in y plot world?"}],"action":{"name":"View Issue","url":"https://github.com/IntellectualSites/PlotSquared/issues/1981#issuecomment-395158935"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [IntellectualSites/PlotSquared] problems with Spawn eggs and spawner (#1981)",
"sections": [
{
"text": "",
"activityTitle": "**Robert Rauh**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@RedstoneFuture",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"IntellectualSites/PlotSquared\",\n\"issueId\": 1981,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"IntellectualSites/PlotSquared\",\n\"issueId\": 1981\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/IntellectualSites/PlotSquared/issues/1981#issuecomment-395158935"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 343025447\n}"
}
],
"themeColor": "26292E"
}

**Comment by RedstoneFuture** [comment]
You don't must use WorldGuard for this in this plotworld.

Would you like test the follow: create a new plotworld, activate in this world eggs too (plotsquared world-config), use "/p reload" and test it.

**Comment by RedstoneFuture** [comment]
Still a problem with the last version?

**Comment by RedstoneFuture** [comment]
And check the multiverse config.
