### ISSUE TITLE
Using the latest version of PlotSquared flag use is invalid. 1.12.2

### ISSUE THREAD

**Issue by qq591692157** [IntellectualSites/PlotSquared#1982]
Flag: use MOD data ID is not supported!

After adding flag, the player still has no permission!

**Comment by RedstoneFuture** [comment]
Can you use the "New Issue" template, please for more details?


> # Bug report template 
> 
> 
> 
> **Debug paste link:** 
> 
> 
> **Description of the problem:** 
> 
> 
> **How to replicate:** 
> 
> 
> **Checklist**:
> 
> - [] I included a `/plot debugpaste` link
> - [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
> - [] I made sure I am using an up-to-date version of PlotSquared
> - [] I Made sure the bug/error is not caused by any other plugin
> 
>

**Comment by qq591692157** [comment]
When I use /plot flag set use 4012 (pokemon PC data id)
Players still don't have access to PC on my land.

**Comment by MattBDev** [comment]
Not enough information and sponge development is a low priority. It could be an issue with the large block id used but again, too complicated to look into at the moment.
