### ISSUE TITLE
Upgrade system of plot (API finction-request)

### ISSUE THREAD

**Issue by Feerko** [IntellectualSites/PlotSquared#1987]
Hello!

There is way to create an upgrade system using your P2 Api? 
I want to allow player to build only for 50x50 on their 200x200 islands

And allow upgrade to 60x60, 70x70 etc.

**Comment by RedstoneFuture** [comment]
Interesting idea. What you need for this in the API?

**Comment by Feerko** [comment]
Because I'm using a P2 instead ASkyBlock and I need to create island upgrades. 
I did this using flags.
