### ISSUE TITLE
Monsters can't deal damage

### ISSUE THREAD

**Issue by Feerko** [IntellectualSites/PlotSquared#1988]
Monsters can't deal damage to players. Fall damage, Lava damage works but not damage caused by monsters. On other worlds everything works great. It's not caused by world guard. 

I'm set pve flag to true, issue still occurs

can anyone help me? thanks a lot!

**Comment by TerraPrimal** [comment]
I had a report for this as well since updating to the latest build.
Made sure PVE was enabled, INVINC was disabled.
Debug: https://hastebin.com/hositarehe

**Comment by Feerko** [comment]
is chance that it will be fixed in the near future? I really need it to make sky block.

**Comment by Feerko** [comment]
@boy0001 is chance that it will be fixed today? It's last thing what I need to make sky block.

**Comment by Feerko** [comment]
@boy0001 is chance that it will be fixed today? It's last thing what I need to make sky block.

**Comment by RedstoneFuture** [comment]
> @boy0001 is chance that it will be fixed today? It's last thing what I need to make sky block.

@Feerko Please, no spam! You delete and write this message every time! He will fix this, if he has the time.

**Comment by Feerko** [comment]
Tested on server with p2 only and bug still exists.

**Comment by Feerko** [comment]
ddsadsa

**Comment by Platinteufel** [comment]
@boy0001 It seems like after recent changes the pve flag needs to be set for mob-damage. Is it possible to add an option that pve is enabled by default? Otherwise i need to set the pve flag for all of my plots, i guess. 😩
