### ISSUE TITLE
regenallroads bug

### ISSUE THREAD

**Issue by WhyNotMrt** [IntellectualSites/PlotSquared#1989]
# Bug report template 

**Debug paste link:** 

https://hastebin.com/akajiwolap
**Description of the problem:** 
The /plot regenallroads command don't place air block so there is still block of the previous schematic on the road. 

I got this : http://prntscr.com/jue7zl
Instead of this : http://prntscr.com/jue8b4

I tried with and without FAWE
**How to replicate:** 

Create a road and replace it by an other.
**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
Currently I can't replicate this problem.

![2018-06-24_16 40 38](https://user-images.githubusercontent.com/4140635/41820160-6b8c2a72-77cd-11e8-80a7-449cb62aa3ab.png)

**Comment by NextdoorPsycho** [comment]
> Currently I can't replicate this problem
Other people seem to be able to

**Comment by RedstoneFuture** [comment]
Still a problem with on of the newest versions?

**Comment by dordsor21** [comment]
You need to set the road height to below the position of the lowest air block, i.e. if you've got a block of air at y = 32, then the road height must be 31 or lower.
