### ISSUE TITLE
Plot flags problem

### ISSUE THREAD

**Issue by LoXR** [IntellectualSites/PlotSquared#1992]
# Bug report template 

**Debug paste link:** 
https://hastebin.com/aduzidesax

**Description of the problem:** 
A player (possibly more) has been trying to set a flag to allow players to use levers, buttons, pressure plates, etc. but not break things in their plot. Unfortunately they've tried all flags but get hit with an "invalid flag" As quoted "I tried /plot set flag use 77, it says That is not a valid flag. Did you mean: use"

**How to replicate:** 

Tried /plot set flag use 77, it says That is not a valid flag. Did you mean: use

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared: PlotSquared version 18.06.12-6ed6f60-2010
- [X] I Made sure the bug/error is not caused by any other plugin: No errors or anything in console.

**Comment by LoXR** [comment]
I think I may of been lacking the permissions to give players. Gave them plots.set.flag.use.*

**Comment by N0tMyFaultOG** [comment]
If this isn't resolved yet, you can try using `/plot flag set use 77` .
(Maybe it's just me, but /p set flag <arg> ain't working with a flag)

**Comment by LoXR** [comment]
Yeah managed to get it working, had to give the permission.
