### ISSUE TITLE
PlotSquared for GoMin MC:BE?

### ISSUE THREAD

**Issue by captainleviftw** [IntellectualSites/PlotSquared#1998]
PlotSquared for GoMin MC:BE? Just like Nukkit? GoMint is still under dev but I'm pretty sure you can still make PlotSquared with its current features

**Comment by Sauilitired** [comment]
It is very unlike that we'll add support for an in-dev server implementation, especially targeting bedrock edition. This might be reconsidered were the platform to gain popularity in the future.
