### ISSUE TITLE
Leaving Plots

### ISSUE THREAD

**Issue by Walvinnie** [IntellectualSites/PlotSquared#2000]
Is there a way to disallow leaving the plot globally

**Comment by RedstoneFuture** [comment]
Not directly. You can use a border with e.g. barrier blocks.

**Comment by boy0001** [comment]
You can set the `exit-deny` flag to true:
For more info about setting default flags:
https://github.com/IntellectualSites/PlotSquared/wiki/Usage:-Plot-flags#default-flags

**Comment by RedstoneFuture** [comment]
Oh, right.
