### ISSUE TITLE
Walls not fully spawning

### ISSUE THREAD

**Issue by Frostfire25** [IntellectualSites/PlotSquared#2006]
# Bug report template 

**Debug paste link:** 

https://hastebin.com/jolepepasu
**Description of the problem:** 

**How to replicate:** 

**Checklist**:

- [] I included a `/plot debugpaste` link
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [] I Made sure the bug/error is not caused by any other plugin

I do not know why, but on my cannoning server, my plots walls do not fully spawn in

https://imgur.com/a/6Lc5ZsW

**Comment by RedstoneFuture** [comment]
In which world? (for a world-config test)

**Comment by Frostfire25** [comment]
real

**Comment by RedstoneFuture** [comment]
fixed?
