### ISSUE TITLE
disallow to take water and lava from plot

### ISSUE THREAD

**Issue by TomekkStorm** [IntellectualSites/PlotSquared#2007]
Hello,

how can i disallow that other players can take water and lava from my plot ?

Best regards
Tomekk

**Comment by RedstoneFuture** [comment]
Mmh ... try this:

```
/p flag remove use 8
/p flag remove use 9
/p flag remove use 10
/p flag remove use 11
```

**Comment by TomekkStorm** [comment]
And how can I remove use 8,9,10,11 by default?

**Comment by RedstoneFuture** [comment]
with the self flag-definition in the **worlds.yml** for this specify world:

```
     flags:
       use: <id without this lava and water ids>
```

**Comment by TomekkStorm** [comment]
After the use command i have only the ID's for Chestshop ans everything works fine.

**Comment by TomekkStorm** [comment]
Ich habe gesehen das du aus Deutschland kommst, das macht es einfacher ;-)

Also ich habe nach dem use nur die beiden ID's für die Schilder, damit der Chestshop funktioniert. Sonst stehen da keine IDs und trotzdem kann man den Spielern Lava und Wasser wegnehmen. Ich habe gedacht, das es vielleicht eine Einstellung gibt, die das verbietet.

**Comment by RedstoneFuture** [comment]
![2018-07-07_14 04 30](https://user-images.githubusercontent.com/4140635/42410717-bac87d2c-81ee-11e8-9677-e134c46c4152.png)


Als Testspieler habe ich bei mir mit einem Eimer auf einem fremden Plot daüfr keine Rechte, weil die Flag "use" definiert ist.

**Comment by TomekkStorm** [comment]
Hi,

wie sieht denn deine "flags" Zeile aus in der Konfiguration ?

**Comment by RedstoneFuture** [comment]
Ich hab jetzt eine komplett neue Welt angelegt. Da ist nichts in der Use-Flag drinne.

**Comment by TomekkStorm** [comment]
Hmm okay.

Bei mir haben die Default User die Permission:

plots.use       Allows user to use commands

Kann es daran liegen ?

In meiner std. Flag Konfiguration steht nur das stehende und hängende Schild.

**Comment by TomekkStorm** [comment]
Wenn ich also die Permission entferne, sollte es funktionieren ? Die Spieler denen ein Plot gehört dürfen ja sowieso Schalter etc. benutzen.

**Comment by RedstoneFuture** [comment]
Es wird nichts ändern.

**Comment by TomekkStorm** [comment]
Okay und wie bekomm ich es nun hin ? Es handelt sich um mein Plot und ein Freund, der keine Rechte hat kann Wasser und Lava nehmen aber nicht zurückfüllen.

**Comment by RedstoneFuture** [comment]
> Nutzt du eine aktuelle Version? Teste es doch mal auf einem Testserver mit zb nur Multiverse und Plotsquared.

**Comment by TomekkStorm** [comment]
Ok werde ich mal probieren.

**Comment by Sauilitired** [comment]
Has the issue been resolved?
