### ISSUE TITLE
Players Cant do /p home

### ISSUE THREAD

**Issue by Bagsdto75** [IntellectualSites/PlotSquared#2010]
Players are unable to do /p home. Im Positive no other plugins are messing with this, Its either an Error or a Glitch. They Have already Claimed a Plot. Please Help

**Comment by N0tMyFaultOG** [comment]
It it throwing a  error? If so please attach it. Also paste a `/plot debugpaste` below.

**Comment by RedstoneFuture** [comment]
I know that you get a error with the command '/p home <with a "ID">' if you are not in a plotworld. But what is your command?

**Comment by RedstoneFuture** [comment]
In the last version you get not a error, if you are not in a plotworld.
