### ISSUE TITLE
MinecartHopper Stealing

### ISSUE THREAD

**Issue by kleinesgumi** [IntellectualSites/PlotSquared#2012]
I have activate the Flag "Vehicle use allow" as default.

If players other plugins moving Minecarts with Hopper to Plots. They can Move the Minecart under Chests and the Minecart with Hopper takes the items out of the chest and then players open the Minecart and done.

**Comment by RedstoneFuture** [comment]
You can activate the deletion of minecarts in roads.

**Comment by RedstoneFuture** [comment]
settings.yml


```
enabled-components:
[...]
  # Kill vehicles on roads
  kill-road-vehicles: true
```

**Comment by RedstoneFuture** [comment]
The descripes problem with the item-transfer is a normal minecraft feature and I think we mustn't need to restrict this.

**Comment by RedstoneFuture** [comment]
Or we add a flag for this item-transfer restriction, but I don't know really the need.


> You can activate the deletion of minecarts in roads.

I think this is enough.
