### ISSUE TITLE
Bug with the Addplots script

### ISSUE THREAD

**Issue by Stalk3r77** [IntellectualSites/PlotSquared#2013]
**Debug paste link:** 

https://hastebin.com/bafetojesi

**Description of the problem:**

Hello, I'm simply trying to use the Addplots script that you suggested here : 
https://github.com/IntellectualSites/PlotSquared/wiki/Allowing-a-player-to-claim-more-plots

When I run the script, here for example I tried to add 3 plots, I get the following error : 
https://hastebin.com/qacuzizejo.md

As you see, it detects perfectly that the player needs the plots.plot.4 permission, but it bugs when trying to add the permission to the player. I don't know if I need to edit the script myself, but if it's given I believe it should work without editing needed. So I think this is a bug.
Thanks in advance

**How to replicate:** 

Simply run the script as recommended with the following command for example: `/plot debugexec runasync addplots.js Player 3` and you will get the same error as me.

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
Has this script been updated to properly function now?

**Comment by AeSix** [comment]
@Stalk3r77  the hastebin has expired.  Please update the ticket using code blocks for pasting the error:
``` \`\`\`like this\`\`\````
