### ISSUE TITLE
Cloud net permission problem

### ISSUE THREAD

**Issue by MrJgamer1000** [IntellectualSites/PlotSquared#2014]
Dies ist das beste Plotsystem Plugin das ich kenne.Ich habe aber leider einen kleinen Fehler bei den Permissions.Ich benutze die Cloudnet Permission.Mann kann mit plots.plot.* alle plots claimen aber mit plots.plot.4 gar keine.Könntest du mir vtl den Fehler sagen.Wäre echt liebt.Lg Justin

/plot debugpaste

https://hastebin.com/uxavoyawis

**Comment by RedstoneFuture** [comment]
Maybe ts a problem of the permission management of https://www.spigotmc.org/resources/cloudnet-the-cloud-network-environment-technology.42059/

**Comment by HerrWookie** [comment]
Das Problem liegt an der aktuellen CloudNet Version. Bitte joint auf den Discord von CloudNet: https://t.co/Z7RnRJtBKh und fragt nach der Version, die kompatibel ist. Zukünftig sollte das aber mit jeder Version funktionieren.
