### ISSUE TITLE
Can not use Dropper

### ISSUE THREAD

**Issue by Marvin10911** [IntellectualSites/PlotSquared#2016]
# Bug report template 

**Debug paste link:** 
 

https://hastebin.com/junaxukisu

**Description of the problem:** 

I can not use a Dropper on the Plot world.
Only Lava and Water works..
I Hope you can help me..

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
this problem? https://github.com/IntellectualSites/PlotSquared/issues/1956

**Comment by Marvin10911** [comment]
Oh yes, but how can I fix it ?

**Comment by RedstoneFuture** [comment]
Its still a bug, but you can use a build older than Build 590. Then it works.
