### ISSUE TITLE
Skeletons cannot damage players - arrows rebound

### ISSUE THREAD

**Issue by Goonhaven** [IntellectualSites/PlotSquared#2018]
Hello, this is my first issue report on Github, so please forgive any errors.

**Debug paste link:** 
Unable to create a debug file due to the following error: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

**Description of the problem:** 
Skeleton arrows cannot damage players in either our prison server or creative server when in Survival Mode.

**How to replicate:** 
Spawn a skeleton with the PlotSquared plugin enabled on a Bungee server, and wait for it to fail to damage you while in game mode 0, with the latest dev build (PlotSquared-Bukkit-18.07.06-ae1e58c-2021.jar).

Plugins on Creative Server: `AutoSaveWorld, dynmap, FastAsyncWorldEdit, PermissionsEx, Hub, ViaVersion, Chat, Bans, Vault, WorldEdit, St0rmIRC, Essentials, LogBlock, PlotSquared, EssentialsSpawn, Multiverse-Core, WorldGuard, TitleManager.`

On Prison Server: `WorldEdit, Essentials, LogBlock, ClearLag, Hub, WorldBorder, Chat, Votifier, RandomItems, WorldGuard, ProtocolLib, ColoredSignss, AutoSaveWorld, PermissionsEx, CS-CoreLib, InfoBook, Vault, GAListener, EssentialsSpawn, PrisonGems, St0rmIRC, SpawnerShop, EZRanksLite, LWC, PlotSquared, SilkSpawners, Multiverse-Core, ServerSigns, MineResetLite, HolographicDisplays.`

**Checklist**:
- This issue has been reported numerous times before to no avail from a Google search, and the last issue posted (#643) on 27 Sep 2015 was closed because there was no testing done.

- I have eliminated what I believe are any WorldGuard, PEx, Essentials, and Multiverse issues and concluded it must be PlotSquared, but I'm happy to post any config files if you need them.

I appreciate what you do, cheers!

**Comment by dordsor21** [comment]
Please reopen with required information if there is still the issue.
