### ISSUE TITLE
Not possible to break main world block.

### ISSUE THREAD

**Issue by AceGamer45** [IntellectualSites/PlotSquared#2021]
Hello, 

the mod plotsquared has problems with the latest build of SpongeForge. It is not possible to break the blocks on the main world, the world that has no plot. 

With the recommended version of SpongeForge it works fine but I had to upgrade to the latest version due to problems that are only fixed in its versions. 

Would it be possible to have a plotsquared update or would it have to be SpongeForge that fixes the problem?

Thank.

**Comment by AeSix** [comment]
@AceGamer45  is this still an issue? 
I can't promise it will be addressed, but if it has been, it would be nice to close the ticket. 

This is over a year old, and as far as I know, no one has picked up PlotSquared development for Sponge.
