### ISSUE TITLE
Teleported to another world using /p home/visit/tp

### ISSUE THREAD

**Issue by sdkrocks** [IntellectualSites/PlotSquared#2022]
When using the command for /p home,tp,vist or teleport it sends the player to another world.
Creating a /plot debugpaste creates an exception in the console.

**Comment by RedstoneFuture** [comment]
It's not a bug. Your user have a list of plots and with `/p home` he get to the first plot.

But, yes. The visit command (and the similar commands) with the argument options are not so good. 
This was discussed at here in the last time: https://github.com/IntellectualSites/PlotSquared/issues/1691

**Comment by RedstoneFuture** [comment]
But you can redefine this option:

```
  # The visit command is ordered by world instead of globally
  per-world-visit: false
```

in the settings.yml

**Comment by Sauilitired** [comment]
This has been answered.
