### ISSUE TITLE
/plot schematic paste url:<key>  Problem with position Y

### ISSUE THREAD

**Issue by xCraftRayX** [IntellectualSites/PlotSquared#2023]
When I use /p download and get schematic next I upload schematic and get command with key. When I used this command to pasting schematic the schema position of Y was starting from plot height setted in config. So Y = 1 position in schema was equals Y=64 because I have setted that height of plot in my config.

Image with problem: https://scr.hu/eDzOz3

**Comment by dordsor21** [comment]
plot schematic paste is to be used with schematics from /plot schematic save or /plot save, not standard schematics.
