### ISSUE TITLE
Problems with the hoppers, furnaces, brewing stand....

### ISSUE THREAD

**Issue by Weark** [IntellectualSites/PlotSquared#2034]
**Debug paste link:** 
Dont show nothing...

**Description of the problem:** 
Hoppers, furnace, brewing stand ... are locking or locking for no reason.

**How to replicate:** 

I will try to explain as best I can ...
I have a FullPvP server that plays on average 120 players per day, I always used the PlotMe plugin but it consumed a lot of memory, so I decided to convert to PlotSquere, and in that there were more than 15 thousand converted plots, so far it worked very well , only that most of the server uses cactus farms and in all plots the hoppers caught, and in that we realized that the furnaces and brewing stand also caught.
We did some crashing tests and putting them back on, so they worked again, but after a while or for some unknown reason they crashed again.

Note: I'm using the version: PlotSquared-Bukkit-18.07.21-aaa7088-2022.jar
Server: PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar

Could you please help me.

**Checklist**:
- [] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
https://github.com/IntellectualSites/PlotSquared/issues/2035
