### ISSUE TITLE
with pve=true also not added players can attack animals

### ISSUE THREAD

**Issue by Platinteufel** [IntellectualSites/PlotSquared#2038]
Because hostile mobs didn't attack players anymore I've set the pve flag as default for all plots according to #1988. Now I got the problem that players can kill animals even on foreign plots where they are not added.
Also reported in PR #2003.

**Comment by AeSix** [comment]
@Platinteufel is this still an issue?  I do not allow mobs on my creative server, and thus cannot test this.  If it is still an issue, please update the ticket with P2 version/build, Minecraft server distro and version/build.

**Comment by MattBDev** [comment]
Closing since this is super old and no one else has reported this issue.
