### ISSUE TITLE
Can't delete plot (1.13) dev.

### ISSUE THREAD

**Issue by sixamscrew** [IntellectualSites/PlotSquared#2039]
/plot delete doesn't work, it says: [P2] A setblock timer is bound to either the current plot or you. Please wait for it to finish.

Although nothing happens next :/
I'm using a development build of the plugin. Also /plot biome doesn't work. The same sentence shows to /plot clear /plot reset
Thank you for your time.

**Comment by MothGirlMusic** [comment]
thank you. is replacing FAWE with WorldEdit ok? and/or is there a known working async replacement?

**Comment by N0tMyFaultOG** [comment]
You can use WorldEdit in the meantime the issue is being fixed, but idk how stable it is on the current P2 build.

**Comment by MothGirlMusic** [comment]
well all the current P2 addons like Houses say they require FAWE and/or WE.. and FAWE is obviously async. so thats why i chose it. here's hoping its fixed soon.

**Comment by MerlinK11** [comment]
that Problem it is in the Lagecy version not Fixed
