### ISSUE TITLE
Plotsquared Overwriting Templates

### ISSUE THREAD

**Issue by Elxafil** [IntellectualSites/PlotSquared#2041]
Anytime you try to update and then reload the "PLOTSQUARED_USE_THIS.yml" fo the custom chat colors and messages upon reload the plugin overwrites it to default and you lose all of your customizations.

**Comment by boy0001** [comment]
Using `/plot reload` ?

I can't replicate, unless you are setting invalid yaml? 
https://yaml-online-parser.appspot.com/
