### ISSUE TITLE
Fix maven link

### ISSUE THREAD

**Issue by Takee24** [IntellectualSites/PlotSquared#2042]
# Bug report template 

**Debug paste link:** 

**Description of the problem:** 
just please fix the maven link. i use maven and i wanna create a plugin with the api, which i cant. 

**How to replicate:** 

**Checklist**:

- [] I included a `/plot debugpaste` link
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [] I Made sure the bug/error is not caused by any other plugin

**Comment by Sauilitired** [comment]
Maven repo published by jenkins can be found at `http://ci.athion.net/job/PlotSquared/ws/mvn/com/plotsquared/plotsquared-api/`
