### ISSUE TITLE
Cant reset / delete plot spawns stone chunks

### ISSUE THREAD

**Issue by BBoyJD10** [IntellectualSites/PlotSquared#2043]
# Bug report template 

**Debug paste link:** 

**Description of the problem:** 
Cant reset / delete plot spawns stone chunks

**How to replicate:** 

Delete or reset a plot in 1.13 using a 1.12 server

**Checklist**:

- [] I included a `/plot debugpaste` link https://hastebin.com/iqicukizut
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared yes
- [] I Made sure the bug/error is not caused by any other plugin yes

**Comment by Sauilitired** [comment]
Should be fixed.
