### ISSUE TITLE
Can‘t teleport ！！！

### ISSUE THREAD

**Issue by Dacxy** [IntellectualSites/PlotSquared#2045]
# Can‘t teleport ！！！
I use PlotSquared-Sponge-18.07.27-cd9d22c-2026.jar
Once the players on the server died, and then use the/plot visit series instruction, will show you have been teleport, but the player did not move
My server is 1.12.2 sponge.
I add projectcore,projectworlds,projectportals,Nucleus
I add my plugins.
I'm Chinese,my English is poor,sry and thx!!!

**Comment by Dacxy** [comment]
![qq 20180802004202](https://user-images.githubusercontent.com/41190242/43535719-515a7814-95ed-11e8-9f94-5e1268ef2738.png)

**Comment by Dacxy** [comment]
Only quit and enter the server again,we can be teleport

**Comment by MattBDev** [comment]
@Dacxy Some other plugin must be messing teleporting because when using sponge, plugins can disable teleporting.
