### ISSUE TITLE
Item Frame item stealing bug

### ISSUE THREAD

**Issue by UnioDex** [IntellectualSites/PlotSquared#2050]
# Bug report template 

**Debug paste link:** 

https://hastebin.com/arumutuyor

**Description of the problem:** 
You can steal items from other players's item frames from their plots.

**How to replicate:** 

https://youtu.be/dpZC0R_COJY

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
And if you deactivate the "hanging-break" flag?

**Comment by UnioDex** [comment]
Couldn't reproduce with latest build.
