### ISSUE TITLE
There are trees from mods in the plot.

### ISSUE THREAD

**Issue by Kastino** [IntellectualSites/PlotSquared#2051]
# Bug report template 

**Debug paste link:** 
https://hastebin.com/efovubixut

**Description of the problem:** 
&nbsp;&nbsp;&nbsp;&nbsp;The tree from mod will be generated in the plot.
&nbsp;&nbsp;&nbsp;&nbsp;Such as rubber tree in **Industrial Craft 2**, sakura tree in **Bamboo Mod**.
&nbsp;&nbsp;&nbsp;&nbsp;As for I installed **Multiworld** and **Realistic Terrain Generation**,  I use /plot setup cannot create the world correctly, there will be vanilla trees in the world, so I delete the world folder and restart the server to let the **Multiworld** generate the world again. Finally the world is OK, however the issues before happened, it is confusing.

Neither default nor augmented + none can create a world without trees.
After I regenerated the world, there doesn't exist vanilla trees but mod trees.

**How to replicate:** 
1. Install **Industrial Craft 2**, **Multiworld**, **PlotSquared**
2. Use /plot setup to complete the configuration.
3. Use /mw delete PlotSquared to remove the world.
4. Delete the world folder manually.
5. Use /mw create PlotSquared PLUGIN:PlotSquared to generate the world.
6. Use /mw load PlotSquared to load the world.
7. Use /mw goto PlotSquared to goto the world.
8. You can see the issues. The rubber tree in the plot.

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [ ] I Made sure the bug/error is not caused by any other plugin

**Comment by Kastino** [comment]
![github_issue_1](https://user-images.githubusercontent.com/16457636/43697959-122aa6ce-997a-11e8-969e-d7e6669c7899.png)

**Comment by Sauilitired** [comment]
What seems to be going on here, is that the trees are not added in the same way as vanilla decorations are, but are instead added after chunk generation (and thus, after PlotSquared has touched the chunks). 

Is there any way to disable the mods in certain worlds?

**Comment by MattBDev** [comment]
This is a behavior that is specific to the mod and may be too time consuming and annoying to fix. Other people used this mod (Maybe older versions) and didn't have this issue before.

**Comment by MattBDev** [comment]
Will not fix.
