### ISSUE TITLE
Plot Schematic

### ISSUE THREAD

**Issue by fede1132** [IntellectualSites/PlotSquared#2052]
# Bug report template 

**Debug paste link:** 

**Description of the problem:** 
When i put the schematic named plot.schematic into rootFolder/plugins/PlotSquared/schematics and i generate the world, the plots doesn't already had the schematic

**How to replicate:** 

Simply put a schematic into the folder and generate the world.

**Checklist**:

- [x] I included a `/plot debugpaste` link (https://hastebin.com/uhojemilof)
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by Kastino** [comment]
Such as my world named PlotWorld.
The intersection file is 
/plugins/PlotSquared/schematics/GEN_ROAD_SCHEMATIC/PlotWorld/intersection.schematic

and road file
/plugins/PlotSquared/schematics/GEN_ROAD_SCHEMATIC/PlotWorld/sideroad.schematic

**Comment by Sauilitired** [comment]
Unfortunately the hastebin seems to be expired (we really have to move to a separate pasting service), but did you follow the instructions on how to configure the schematic? They can be found [here](https://github.com/IntellectualSites/PlotSquared/wiki/Usage:-Schematic-on-claim)
