### ISSUE TITLE
com.intellectualcrafters.plot.api.PlotAPI not found in maven repository

### ISSUE THREAD

**Issue by 615283** [IntellectualSites/PlotSquared#2053]
I'm using the maven repo @ http://ci.athion.net/job/PlotSquared/ws/mvn/ on version `latest`. Packages show up except the com.intellectualcrafters.plot.api package.

**Comment by Sauilitired** [comment]
Reproduce: Download latest jar from http://ci.athion.net/job/PlotSquared/ws/mvn/com/plotsquared/plotsquared-api/latest/ and trace files. No API package present in `/com/intellectualcrafters/plot`

**Comment by dev-braini** [comment]
Any solutions or workarounds?

**Comment by Eizock** [comment]
@Sauilitired Any Updates on this?
Problem seems to still exist.

**Comment by Sauilitired** [comment]
It used to be in the Bukkit module. In PlotSquared 4 it's a part of the core API.
