### ISSUE TITLE
PlotSquared bridge template issue

### ISSUE THREAD

**Issue by ABioGen** [IntellectualSites/PlotSquared#2054]
# Bug report template 

**Debug paste link:** 
https://hastebin.com/unugofecej

**Description of the problem:** 
i am using the bridge.template for plotsquared.
If my players using the command /p auto their wiill spawn in the plotworld on the a fence on top of the bridge and their stuck there after teleporting. what can i do ? can i change the spawnpoint below the bridge ?

**How to replicate:** 
like in the descritption above

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by ABioGen** [comment]
/solved....by my self...thnx for "No" Support!

**Comment by BlaackZero** [comment]
how did you fix the problem
