### ISSUE TITLE
Players hack plot limit with macro mod

### ISSUE THREAD

**Issue by andris155** [IntellectualSites/PlotSquared#2059]
# Bug report template 

**Debug paste link:** 

**Description of the problem:** 
Players hack plot limit with macro mod

**How to replicate:** 

Create macro with /p auto x10 and use this.
https://imgur.com/4dxJaJZ

**Checklist**:

- [x] I included a `/plot debugpaste` link: https://hastebin.com/mezizavuka
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by boy0001** [comment]
Has been fixed, please update:
http://ci.athion.net/job/PlotSquared/631/artifact/target/PlotSquared-Bukkit-18.08.12-4b8c434-2035.jar
