### ISSUE TITLE
Problems using the /plot purge command (Not cleaning plot)

### ISSUE THREAD

**Issue by Weark** [IntellectualSites/PlotSquared#2062]
**Description of the problem:** 

I am experiencing problems using the: /plot purge
I have a FullPvP server which I need to remove all plots from unknown owners.
But using the command: /plot purge world:plotworld unknown:true
It removes the owners without cleaning the buildings, so any other player can go to the plot and revindicates it taking a ready construction.

**How to replicate:** 

To replicate is very easy, simply have a world of plotworld which contains innumerable plots with "unknown owners" which have constructions in it, shortly after typing the command:  plot purge world:plotworld unknown:true
That way it will remove all the "Unknown Owners" but the buildings will stay there.

Is there any other solution for me to remove all plots with "Unknown Owners"?
Well I've tried to use auto-clear but it only removes plots which have some Owner.
I urgently need to remove all plots with "Unknown Owners" deleting next to the contruction it contains.

**Checklist**:
- [] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by Weark** [comment]
When using the "/plot purge world:plotworld unknown:true" command it freezes the server from numerous errors on the console and restarts the server, and soon after connecting the plots that were with unknown owners are now owners, but the constructions are in it.
This may have happened because I have more than 16,000 plots with unknown owners, and I need to clean and delete all of them, but for this I would need to put a cleaning delay for each plot so the server does not freeze and crash.

**Comment by Espantonius** [comment]
I have the same problem. More than 60k plots can not remove.

**Comment by dordsor21** [comment]
Please provide a /plot debugpaste if the issue still occurs
