### ISSUE TITLE
Can't Restore My Plot

### ISSUE THREAD

**Issue by collinator24** [IntellectualSites/PlotSquared#2065]
# Bug report template 

**Debug paste link:** 

**Description of the problem:** 
I Can Not Restore My Plot from a Saved Schematic file, when I try to import it says its too big. I am using 1.13 building blocks, and I can't use MCEdit because they are focusing on bedrock edition, so I need to cut the last layer. I also can't use a /p save internal saved file, as it says in console its too big aswell.
Here is the /plot debugpaste link https://hastebin.com/jojofivaco
**How to replicate:** 

use plot commands to generate a Schematic file, and download it. clear your plot, and then try to import it again.
**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)] (Could Not Find A Similar one Under The Same Condition.)(https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
Please reopen with required information if there is still the issue.
