### ISSUE TITLE
PlotSquared Permissions buggen Rum... (You can't Claim more Plots)

### ISSUE THREAD

**Issue by JustinSGD** [IntellectualSites/PlotSquared#2068]
# Bug report template 

**Debug paste link:** 

**Description of the problem:** 

**How to replicate:** 

**Checklist**:

- [√] I included a `/plot debugpaste` link (https://hastebin.com/kazasayigi)
- [√] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [√] I made sure I am using an up-to-date version of PlotSquared
- [√] I Made sure the bug/error is not caused by any other plugin

Ich habe schon alles versucht mit den Permissions "plots.plot.4" oder auch "plots.claim.4"

**Comment by RedstoneFuture** [comment]
https://github.com/IntellectualSites/PlotSquared/issues/2097

**Comment by RedstoneFuture** [comment]
https://github.com/IntellectualSites/PlotSquared/issues/1976
