### ISSUE TITLE
Problem with /plot v 

### ISSUE THREAD

**Issue by TheIntelloBox** [IntellectualSites/PlotSquared#2069]
# Bug report template 

**Debug paste link:** 

**Description of the problem:** 

1) Write /plot visit nickname
2) It says: "You can't build here".
Debug paste: https://hastebin.com/yomazeneho.php

**How to replicate:** 

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by Sauilitired** [comment]
Has anyone been able to replicate this? I'd image it would be an issue with WorldGuard, as the only messages sent by PlotSquared in the visit command are permission related, i.e "$2You are lacking the permission node: $1%s"

**Comment by N0tMyFaultOG** [comment]
>Has anyone been able to replicate this?

No. PlotSquared doesn't bring up this message. It seems more like a WorldGuard issue.

**Comment by TheIntelloBox** [comment]
I had to give them the permission plots.visit.other. You should add it to the wiki. :)
