### ISSUE TITLE
World generation under 1.13

### ISSUE THREAD

**Issue by x1p** [IntellectualSites/PlotSquared#2070]
Generation a new world under paperspigot 1.13
Used version: 
**Debug paste link:** 
https://hastebin.com/gukaqekaza

**Description of the problem:** 
1. Plot setup generator does not accept bukkit material names but wants numbers instead.
2. Signs are not placed on the plots
3. Script for placing signs is not working anymore.

**How to replicate:** 
Made a new server running:
Paperspigot 1.13 (recent build)
PlotSquared-Bukkit-18.08.12-4b8c434-2035.jar
Made a plot world by /plot setup wizard.
Setup only accepts numbers for the fields
    wall:
      block: '44:3'
      block_claimed: '44:2'
The rest of the fields accept materials, but write it down using numbers

The plots are made quite well. But signs seem to be missing.
Plot claiming/deleting does not bring the sign back.
I found the script for fixing the signs, but this runs into errors:
https://hastebin.com/ipihuqutur.md

**Comment by andris155** [comment]
same problem
