### ISSUE TITLE
Players can //undo, plot delete, then //redo in order to put blocks onto an unowned plot

### ISSUE THREAD

**Issue by braceyourself07** [IntellectualSites/PlotSquared#2071]
**Debug paste link:** 
https://hastebin.com/geganihako

**Description of the problem:** 
In a standard plotworld, players can set blocks onto an unowned plot by using the //redo command on a plot they used to own.

**How to replicate:** 
Step 1. Claim a plot
Step 2. Select an area and //set it to something (or any other FAWE edit)
Step 3. Type //undo to remove the worldedit that was done
Step 3. Delete the plot with /plot delete
Step 4. After the plot is cleared and deleted, do //redo and the blocks will reappear even though it is not owned.

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by Sauilitired** [comment]
This cannot be be replicated using WorldEdit, and so it seems to be a FAWE issue. Please report this in the appropriate FAWE repository.
