### ISSUE TITLE
Multiworld /p h

### ISSUE THREAD

**Issue by HotelMakar** [IntellectualSites/PlotSquared#2072]
**Description of the problem:** 
When i have many plotworlds example prison and creative
when i claim a plot on priosn and i claim a plot on creative i do /p h it brings me to my opprison plot and i have to do /p h 2 to get to my creative plot

**Comment by Sauilitired** [comment]
In your `plugins/PlotSquared/config/settings.yml` set `teleport: per-world-visit` to `true`.
