### ISSUE TITLE
Plot owner: unknown

### ISSUE THREAD

**Issue by LoXR** [IntellectualSites/PlotSquared#2073]
# Bug report template 

**Debug paste link:** 

https://hastebin.com/iyixoyobid

**Description of the problem:** 
Basically going into a plot it'll show the title but no ones owns the plot apparently, but on the sign it has the original owner of the plot.

**How to replicate:** 

Quite possibly on restart where I have the plots to clear for inactivity?

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
Please reopen with required information if there is still the issue.
