### ISSUE TITLE
Road tree leaves disappear and the /p debugroadsregen command does not work

### ISSUE THREAD

**Issue by Mario359** [IntellectualSites/PlotSquared#2076]
**Debug paste link:** I can't: Error 503 for hastebin.com
Spigot 1.13, PlotSquared 632, FAWE 1.13, Multiverse-Core 6, No WorldGuard

**Description of the problem:** 
When I go on the road, the decorative leaves disappear, the road is not frozen as in the old versions of the plugin

When I type /p debugroadsregen nothing happens, only two messages in the chat:
"[P2] Regenerating plot south/east roads: 0;0
\- Result: Success"
No console errors, and no regenerated roads
/p regenallroads work but leaves will disappear

**How to replicate:** 

Create a plot world
Make a road with leaves on it with /p createroadschematic
Do /p regenallroads

**Checklist**:

- [ ] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by partyp770** [comment]
To be more specific, are the leaves decaying, or are they just not pasting?

**Comment by dordsor21** [comment]
I've not seen this issue with my testing for the P2 4 update,
