### ISSUE TITLE
No plots suddenly

### ISSUE THREAD

**Issue by Jaffaaaa** [IntellectualSites/PlotSquared#2078]
Server Version: PaperSpigot-1.8.8
https://hastebin.com/etahocimev

I restarted my server and now no plots work. The plugin works but there are no plots apparently. Plot hole doesn't work and my players can break all blocks in the plot world.

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by partyp770** [comment]
Is the world listed in Plugins/Plotsquared/Config/Worlds.yml?

**Comment by partyp770** [comment]
If you tried to delete the plot world, it might have broken it in the process. Also, what is "plot hole?"

**Comment by BrainStone** [comment]
I'm having the exact same issue on Sponge. Weirdly enough even older versions seem to have this issue suddenly after updating and reverting back. Looks like recent versions break something in the config.

**Comment by dordsor21** [comment]
If someone is having this issue please provide a debugpaste.
