### ISSUE TITLE
Error when deleting a merged plot I hack-copied to a different world

### ISSUE THREAD

**Issue by dordsor21** [IntellectualSites/PlotSquared#2079]
```
[19:25:46 INFO]: dordsor21 issued server command: /ps delete
[19:25:46 INFO]: Fixing invalid merge: Tutorials;0;0
[19:25:46 INFO]: Ignoring invalid merged plot: Tutorials;0;-1 | null
[19:25:46 INFO]: Ignoring invalid merged plot: Tutorials;-1;-1 | null
```
Copying code:
```
Plot plot2 = MainUtil.getPlotFromString(BukkitUtil.getPlayer(player), "Tutorials;" + plot1.getId().toString(), false);
plot1.copy(plot2, () -> {...
```

**Comment by dordsor21** [comment]
Unable to get all the two plot IDs of the original plot, but it would have been 0;0 and a single adjacent plot.

**Comment by Sauilitired** [comment]
Hi there! We appreciate you making this issue report. Is this still an issue in current versions of PlotSquared?

**Comment by dordsor21** [comment]
oof

**Comment by dordsor21** [comment]
I'd have to do a lot of updating to test it :(

**Comment by AeSix** [comment]
closing due to un-replicatable edge case scenario.
@dordsor21 when you have the time to replicate this, if it's still an issue, re-open the ticket. :)
