### ISSUE TITLE
Regenallroads and debugroadregen not working (sponge vanilla)

### ISSUE THREAD

**Issue by ThornsOfire** [IntellectualSites/PlotSquared#2084]
**Debug paste link:** 
https://hastebin.com/ugapahehot

When a privileged user attempts to debugroadregen console throws an error with an ingame "success" notification. When regenallroads is run on console it outputs the change % and active .mcr file but on completion no roads are regenerated with no errors in console.

Console error on "/plot debugroadregen": https://pastebin.com/4ux9Tjav

**How to replicate:** 
1. Build a custom road around a plot.
2. Type "/plot crs"
3. Travel to another plot type "/plot debugroadregen"
4. Observe console output
5. On console run command "/plot regenallroads"
6. Observe console and wait for process to complete
7. Travel to plot world
8. Observe changes to roads

**Comment by boy0001** [comment]
Fixed in https://github.com/IntellectualSites/PlotSquared/commit/906f16d07570baf47ea6305d3977494233e51082
