### ISSUE TITLE
p deny * overtake the added members to plot

### ISSUE THREAD

**Issue by xion87** [IntellectualSites/PlotSquared#2085]
Debug paste link:
https://hastebin.com/eyilapacug

Description of the problem:
If player do p deny *, and they want remove soemsone by banned people, or add new builder, it can't be do it. 
Also if the owner will change, the p deny still block also the plot owner to enter in the plot..

Checklist:

  [x] included a /plot debugpaste link
  [x] made sure there are no duplicates of this report (Use Search)
  [x] made sure I am using an up-to-date version of PlotSquared
  [x] Made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
I think this was expected behavior, 
but any named entry should take precedence over asterisk,
with the exception of "/p kick *"

The asterisk is also abusable with economy, by allowing owners to /p trust * and paying only 1 time.  This would probably get fixed with touching this issue.

**Comment by MattBDev** [comment]
@AeSix are you saying that the preferred behavior would be the asterisk replaced by individual player names?

**Comment by AeSix** [comment]
I think preferred behavior would be to permission it, and make a note in the config in the economy section to warn that adding/trusting "*" pretty much bypasses economy for that.

As for kick & deny, it should be that * is anyone currently on the plot who is not owner or trusted.

Remove functions well, as it will remove members first, a second go-around removes trusted.

A confirm should be added if economy is enabled.

</$0.02>

**Comment by MattBDev** [comment]
I'll work on making all behavior more consistent

**Comment by MattBDev** [comment]
I believe this behavior should be kept but open a suggestion if you feel otherwise.
