### ISSUE TITLE
Plot border and merging issues when FAWE is installed

### ISSUE THREAD

**Issue by chedadmin** [IntellectualSites/PlotSquared#2086]
**Debug paste link:** 

Sorry, cannot get /plot debugpaste to work either!

**Description of the problem:** 
Plot border does not change on /claim. Roads do not disappear on /merge.

**How to replicate:** 

Server running Spigot 1.13.1. The above problems occur only when FAWE is installed.

**Checklist**:

- [] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [?] I Made sure the bug/error is not caused by any other plugin

**Comment by andris155** [comment]
same problem

**Comment by N0tMyFaultOG** [comment]
Fixed, update your Fawe to the latest version
