### ISSUE TITLE
VoxelSniper overlapping with plotsquared

### ISSUE THREAD

**Issue by prettyinaccurate** [IntellectualSites/PlotSquared#2093]
# Bug report template 

**Debug paste link:** 

https://pastebin.com/ZipTggyV

**Description of the problem:** 
/p home overlaps with the /p in VoxelSniper, the sniper brush.

**How to replicate:** 

Have VoxelSniper installed
Have PlotSquared installed
Use /p home, if you have no voxel permission, it will tell you that you don't have permission. If you have voxel permission, it will tell you "this brush does not accept add-ons" or something similar. Is there any way to make plotsquared the dominant command?

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [] I Made sure the bug/error is not caused by any other plugin

**Comment by MedicOP** [comment]
Set it in bukkit commands.yml in the server folder

**Comment by RedstoneFuture** [comment]
Or use command-control plugins like https://www.spigotmc.org/resources/commandcontrol.76/
