### ISSUE TITLE
Plot2 | Cant claim more Plots

### ISSUE THREAD

**Issue by JoshuaPvP** [IntellectualSites/PlotSquared#2097]
**Debug paste link:** 
https://hastebin.com/wikajokolo

**Description of the problem:** 
Hello,

my users can´t claim plots. Error: You can´t claim more plots.
I have already gave the Permission plots.plot.2
The limit in the config file is set to 2.
Pleas help me with the problem.

Thank You, Best regards:
MySQLInjection.

**How to replicate:**

**Comment by RedstoneFuture** [comment]
https://github.com/IntellectualSites/PlotSquared/issues/2097
