### ISSUE TITLE
1.13.1 Crash 

### ISSUE THREAD

**Issue by FrankHeijden** [IntellectualSites/PlotSquared#2100]
**Debug paste link:** 
https://hastebin.com/ninanoteba.makefile

**Description of the problem:** 
https://paste.md-5.net/mujenasida.avrasm

**How to replicate:** 
Server on 1.12.2, load, stop, forceupgrade to 1.13.1 and then fly to the end of the world (where the chunks have not been generated yet)

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by ItsAZZA** [comment]
Having the same error/issue in 1.13.2 and the world is unplayable. The chunks load slowly or not at all.

**Comment by N0tMyFaultOG** [comment]
@FrankHeijden 
- Use Java 8
- Download the latest PlotSquared build [here](http://empcraft.com/plots/latest.php?Bukkit)
- Use the latest version of 1.13.2
- [P2 is currently in development for 1.13 so things will not work as expected]
