### ISSUE TITLE
PlotSquared Piston - Edge Bug

### ISSUE THREAD

**Issue by byCxde** [IntellectualSites/PlotSquared#2103]
**Debug paste link:** 
https://hastebin.com/tayukanobi

**Description of the problem:** 
The Problem is u can push blocks from the custom Street schematic with pistons into ur plot if u have no edge.

**How to replicate:** 
Step 1: Remove the rand with command or not it's doesn't matter.
Step 2: Activate Sticky Piston - it will be pushed to the edge.
Step 3: Deactivate Sticky Piston - now it will get pushed back.

I also have made a Video:
https://youtu.be/pBt9jNO4kw8

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
With the latest version of PlotSquared and Spigot 1.13.2 (and without FAWE) the bug down't work.

**Comment by AeSix** [comment]
@byCxde 
This did not work for me in 1.12.2 (with P2 legacy and FAWE) nor in 1.13.2 (with P2 v4 and WorldEdit 7 beta 5)

Please update to a newer build of P2 and test
1.12.2: https://ci.athion.net/view/Everything/job/PlotSquared/
1.13.2: https://ci.athion.net/view/Everything/job/PlotSquared-breaking/

Please test,  generate a new /plot debugpaste and update the ticket. Be sure you're not using FAWE with PlotSquared 4, you should be using WorldEdit 7.  P2 v4 is built using WorldEdit, and FAWE is not 100% compatible yet.

**Comment by MattBDev** [comment]
We couldn't reproduce this.

**Comment by Chazotu** [comment]
Sticky Piston can Push a block out if plot boarder is missing , but not push it back
