### ISSUE TITLE
Hoppers, furnaces, beacons BUG - PlotSquared

### ISSUE THREAD

**Issue by Lutarcy** [IntellectualSites/PlotSquared#2105]
# Bug report template 

**Debug paste link:https://hastebin.com/ayadunitol

**Description of the problem: Hoppers, piston, beacons, furnaces stop working. There is no clue of why this is happening. 

**How to replicate:** 

**Checklist**:

- [] I included a `/plot debugpaste` link
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [] I Made sure the bug/error is not caused by any other plugin

**Comment by SrLeojaco** [comment]
Stop working = never work or it works but it doesn't finish?

**Comment by RedstoneFuture** [comment]
Still a problem with on of the newest versions?
