### ISSUE TITLE
PlotSquared and Holographic Displays [Spigot v1.12.2]

### ISSUE THREAD

**Issue by Digital-Beast** [IntellectualSites/PlotSquared#2106]
Hello, I have encountered an issue between PlotSquared and Holographic Displays. 

**Server:**  This server is running CraftBukkit version git-Spigot-642f6d2-fbe3046 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
**Plugins Involved:** 
PlotSquared: Version: 18.09.09-eab918b-2040
Holographic Displays: Version: 2.2.6
Protocollib: Version: 4.4.0-SNAPSHOT-b403
_(Citizens2: Version: 2.0.22-SNAPSHOT (build 1493))_

**Heres the link for the Debug:**
https://hastebin.com/qawiyugemo

**Description of the problem:** 
Holograms will not load properly when PlotSquared is present. I've tested with a few versions of all 3 of the involved plugins, All tests with the same result. 

(I'm not sure what triggered the issue, at the beginning we thought it was because we had many holograms, and the plugin was poorly written, but today I found a post on the internet where one pointed out the exact same issue and mentioned it was between Plotsquared and Holographic Displays. So I began some testing as I wanted to resolve the issue myself, instead of bothering you guys.
But as my attempts with different plugin versions did not work, and the proof that it loaded fine as I removed the plotsquared from my plugin folder, I see no other option than to make a ticket here. 
Don't know if it is of any use, but I have 160 holograms - just in case, it's depending on the amount. 
_(Also an admin of mine pointed out that some NPC's from citizens tend to disappear - I'm not sure its linked to this at all and I did not test, just wanted to mention. )_

**How to replicate:** 
To reproduce the error, I start with having the 3 plugins mentioned as involved plugins on my server, as the newest available versions for server version 1.12.2 in my plugin folder.
I Start up my server and get these errors: **https://pastebin.com/4a9Z2zZK** (_line 980_)
I remove PlotSquared, and boot my server up again: **https://pastebin.com/QAE5bB5F** (_line 1132_)

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
Note: I mis-read MC version at first and compiled a tested results for such.  It is provided below for additional information.  However: P2, HD and PL all work on both of my 1.12.2 and 1.13.2 servers:

1.12.2 results (in production, none the less):
![image](https://user-images.githubusercontent.com/5191757/51196547-57a7a180-18bd-11e9-8cb8-a5a97de00a29.png)

ProtocolLib 4.4.0-SNAPSHOT-b398
HolographicDisplays 2.3.3-SNAPSHOT
PlotSquared 18.11.15-0252cf7-2052
Spigot-642f6d2-fbe3046 (MC: 1.12.2

I believe newer versions of PL are aimed at 1.13, and so using an OLDER version of ProtocolLib may be in order.  However, HolographicDisplays and PlotSquared are both newer than the original author's.  Of course there's no version / build difference for Spigot, as it's the last 1.12.2 version. 

Solution: Downgrade PL, upgrade HD and P2. Report success/failure results. 

--- --- --- --- --- --- --- --- --- ---
1.13.2 results (also actually in production use as well):
(As you can see, I'm a bit outdated on this server, but it's stable, and so am leaving it)
![image](https://user-images.githubusercontent.com/5191757/51196033-49a55100-18bc-11e9-8d08-66159c9ee813.png)

ProtocolLib 4.4.0-SNAPSHOT-b414  (Oddly enough, this is *newer* - I was sure I was using a much older version)
HolographicDisplays 2.3.0-SNAPSHOT
PlotSquared 18.11.15-0252cf7-2052
Spigot git-Spigot-a1f2566-a4c555b (1.13.2)

I'd say this could probably be closed, provided original author has no additional issues once his software is updated and test.
