### ISSUE TITLE
PlotSquared not protect Turtle egg dropped items and entitys

### ISSUE THREAD

**Issue by andris155** [IntellectualSites/PlotSquared#2107]
# Bug report template 

**Debug paste link:** 

https://hastebin.com/togeziqune

**Description of the problem:** 
PlotSquared not protect Turtle egg dropped items

**How to replicate:** 

1. place turtle egg my plot.
2. Other player drop items to turtle egg.
3. Turtle egg destroyed.

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
Update to PlotSquared 4.

https://github.com/IntellectualSites/PlotSquared/wiki/Installation#updating-to-113

https://ci.athion.net/job/PlotSquared-Breaking/

**Comment by andris155** [comment]
PlotSquared 4 not fixed this bug.

**Comment by Sauilitired** [comment]
I'm going to assume that it was fixed. Re-open if not :)
