### ISSUE TITLE
Road Schematic Issue in 1.13.1

### ISSUE THREAD

**Issue by HeckiYT** [IntellectualSites/PlotSquared#2108]
**Debug paste link:** 
https://hastebin.com/vubuyijuyi

**Description of the problem:** 
When I want t create a road schematic i get this error:
`[P2] An error occurred: %s`

**How to replicate:** 
- Create a 1.13.1 Server
- Try to save a road schematic

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by OrionP1023** [comment]
Also having this issue. Any progress on this? It doesn't seem to have been assigned.
