### ISSUE TITLE
plots nor clearing or deleting under 1.13

### ISSUE THREAD

**Issue by makemp1997** [IntellectualSites/PlotSquared#2112]
# Bug report template 

**Debug paste link:** 

https://hastebin.com/ufacemilew
**Description of the problem:** 
Hello<
I have an issue in 1.13 that the plot do not cleared or not deleted correclty, how can fix this?

**How to replicate:** 

already claimed:
1. got to plot that I wanted to cleared
2. do /plot clear
3. /plot confirm (plot didn't clear so I did the next step)
4. /plot delete
5. /plot confirm (again the plots didn't clear
not claimed (also tested om a test server)
1. go to an empty plot
2. /plot claim
3. place some blocks
4. do /plot clear
5. /plot confirm (plot also didn't clear so I did the next step)
6. /plot delete
7. /plot confirm (also didn't as it should)

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Remove FastAsyncWorldEdit and FastAsyncVoxelSniper. That's a know  bug

**Comment by makemp1997** [comment]
Hello,

Ok againg thx for the swift answer wel wel then I have to figure out what to do with worldedit and voxel.
Considering I need both, plugins.

**Comment by makemp1997** [comment]
Hello,
Sorry for my late and short reply because I had other oplications.
Anyway I hop this would be fixed, considering I am now in progrees to update my server to 1.13.1 though. 
So I try to use that latest builds for fawe and fasw, build 1206 and 1207, with both version cashing my server so I do not know if issue is fixed. 

So can you suggest if there is any where I can use atleast gopaint preferable voxel as well though in conjuction with that I do not have those isuue with PlotSquared and we?

Greetings,

makemp2014
aka makemp1997

**Comment by N0tMyFaultOG** [comment]
The issue isn't fixed yet, you cannot delete/clear plots still if fawe is installed. GoPaint depends on fawe and voxel does as well. We will need to wait until this gets fixed

**Comment by Sikatsu** [comment]
Will it be fixed though? Simply removing fawe to fix it sounds weird.. i'd like to use both ofcourse.

**Comment by N0tMyFaultOG** [comment]
At some point sure, but Jesse has a real life as well so patience is our key to success. IronApollo and me opened some PR's recently with some fixes of the long bugreport I made. We can't change the world, but small minors are a good start ;)
