### ISSUE TITLE
Error happens when pasting

### ISSUE THREAD

**Issue by DeadIntermediate** [IntellectualSites/PlotSquared#2117]
**Description of the problem:** 
I guess when pasting commends with WE. I see this error, which contains with PlotSquared. Not sure if it's PlotSquared or WorldEdit.

Here is the Pastebin: 
https://pastebin.com/60nPqNgY

PlotSqured Debug:
https://hastebin.com/fabojogoki

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [] I Made sure the bug/error is not caused by any other plugin

**Comment by Sauilitired** [comment]
Solved in PlotSquared 4.
