### ISSUE TITLE
Errors with WorldEdit

### ISSUE THREAD

**Issue by DeadIntermediate** [IntellectualSites/PlotSquared#2118]
# Bug report template 

**Debug paste link:** 
https://hastebin.com/rawesemafu

**Description of the problem:** 
I get errors in the plot worlds when using the latest version on WorldEdit that just came out.  
It's WorldEdit Build #3874

Spigot Version
Spigot 1.13.1

**How to replicate:** 

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by IronApollo** [comment]
Looks like an issue you may want to bring up with the author of ReWorld. It seems their plugin is having trouble handling an event. I would send them the link labeled "latest.log".

**Comment by x1p** [comment]
Could be the same as mine (2122) but not sure because no errors were provided.
That would eliminate ReWorld as a source because I don't have that.

**Comment by Sauilitired** [comment]
Most likely solved in PlotSquared 4.
