### ISSUE TITLE
"/plot delete" deletes multiple plots

### ISSUE THREAD

**Issue by hyWse** [IntellectualSites/PlotSquared#2120]
**Debug-Paste:**
https://hastebin.com/lidocecoqo

**Description of the problem:** 
This has happened three times so far. We haven't been able to reproduce the bug yet. 
Sometimes, when a plot is deleted, a plot in a completely different location is also deleted.
The console will show that the plot has been deleted and no other error.

**Comment by SrLeojaco** [comment]
The plot is deleted physically (restored to default model) or it is only deleted from db (plot info only)?

**Comment by Sauilitired** [comment]
This couldn't be replicated. If the issue persists, please re-open.
