### ISSUE TITLE
"Unknown" plot creator

### ISSUE THREAD

**Issue by JustTalDevelops** [IntellectualSites/PlotSquared#2123]
**Description of the problem:** 
PlotSquared seemed to be working fine on our NukkitX server, though later, I realized the plot names had become corrupted, they were displaying "Unknown." I really don't wanna reset the plots, so I do hope you can come up with a solution. Debug paste: https://hastebin.com/udeqawobiv

**How to replicate:** 
Can't reproduce, don't know how it happened in the first place.

**Checklist**:
- [x] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by TalhaAzeem37** [comment]
Update:
I’ve seen this issue (https://github.com/IntellectualSites/PlotSquared/issues/781), but it dosent seem to help with anything, I’m already using sqluuid handler, and the only resolution I can find temporarily is to just disable titles.
It would make my life so much easier if you tell me what I’m doing wrong, thanks!

**Comment by AeSix** [comment]
a) Is this still an issue with newer builds?
b) Did you change UUID storage after the plots were created? Did you enable sqluuid after, or before the plots were claimed?
c) Do you have the ability to check the SQL db to see if there are UUIDs stored for the plots? 
d) Did player UUIDs change some how between the time the plots were created and when the issue began?

And most importantly, does the plot owner have the ability to access the plot?

**Comment by WapitiAcht2777** [comment]
> And most importantly, does the plot owner have the ability to access the plot?

the plot owner does have access to the plot for other people it is showing unknown but not for the plot owner on his own plot

**Comment by AeSix** [comment]
I'm going to be setting up a nukkitx server and working with one of the devs for fixes in the near future.  Right now, there's been limited updates for nukkit.  I'll try to remember to keep you posted on any advancements we make, but keep an eye out too :)

**Comment by dordsor21** [comment]
Testing locally I can't replicate this (using SQLite)

**Comment by AeSix** [comment]
This isn't an issue on my nukkitx test server.  Perhaps this is a storage corruption issue, not a p2 issue.  Closing.
