### ISSUE TITLE
Signs are not automatically placed on the side of plot on creation

### ISSUE THREAD

**Issue by cuddylier** [IntellectualSites/PlotSquared#2124]
Hi

I'm running Spigot 1.13.1 along with plotsquared dev build 635 (2040).

When I create a new world with Multiverse 2.6.0 (dev build 738) using the command /mv create <world> normal -g PlotSquared and claim a plot in this world, a sign is not created on the side of one of the slabs of the plot to show the owner, no plots have any signs at all on them.

I would show the output of '/plot debugpaste' but sadly it doesn't work anymore:

08.10 21:08:00 [Server] WARN java.io.IOException: Server returned HTTP response code: 503 for URL: https://hastebin.com/documents

Let me know if you need any commands issued.

Thanks

**Comment by DoreK333** [comment]
Same problem 😢

**Comment by Sauilitired** [comment]
Solved in PlotSquared 4.
