### ISSUE TITLE
Error in road schematics

### ISSUE THREAD

**Issue by 25cody123** [IntellectualSites/PlotSquared#2125]
# Bug report template 

**Debug paste link:** 
**

 08.10 16:03:58 [Server] INFO Successfully updated database with local data.
08.10 16:03:58 [Server] INFO Sending local data to database...
08.10 16:03:48 [Server] WARN at java.lang.Thread.run(Unknown Source)
08.10 16:03:48 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
08.10 16:03:48 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
08.10 16:03:48 [Server] WARN at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
08.10 16:03:48 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900)
08.10 16:03:48 [Server] WARN at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
08.10 16:03:48 [Server] WARN at java.util.concurrent.FutureTask.run(Unknown Source)
08.10 16:03:48 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
08.10 16:03:48 [Server] WARN at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
08.10 16:03:48 [Server] WARN at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
08.10 16:03:48 [Server] WARN at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
08.10 16:03:48 [Server] WARN at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1479)
08.10 16:03:48 [Server] WARN at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1644)
08.10 16:03:48 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:696)
08.10 16:03:48 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
08.10 16:03:48 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
08.10 16:03:48 [Server] WARN at com.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:30)
08.10 16:03:48 [Server] WARN at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:135)
08.10 16:03:48 [Server] WARN at com.intellectualcrafters.plot.commands.MainCommand.execute(MainCommand.java:260)
08.10 16:03:48 [Server] WARN at com.plotsquared.general.commands.Command.execute(Command.java:337)
08.10 16:03:48 [Server] WARN at com.intellectualcrafters.plot.commands.SubCommand.execute(SubCommand.java:27)
08.10 16:03:48 [Server] WARN at com.intellectualcrafters.plot.commands.CreateRoadSchematic.onCommand(CreateRoadSchematic.java:32)
08.10 16:03:48 [Server] WARN at com.intellectualcrafters.plot.generator.HybridUtils.setupRoadSchematic(HybridUtils.java:304)
08.10 16:03:48 [Server] WARN at com.intellectualcrafters.plot.generator.HybridUtils.get_ey(HybridUtils.java:338)
08.10 16:03:48 [Server] WARN java.lang.NullPointerException**
**Description of the problem:** 

**How to replicate:** 

**Doing /plot createroadschematic
Gives an error occurred %s**
**Checklist**:

- [] I included a `/plot debugpaste` link
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [] I Made sure the bug/error is not caused by any other plugin

**Comment by DoreK333** [comment]
Same problem :<

**Comment by OrionP1023** [comment]
Also having this issue. Any progress on this? It doesn't seem to have been assigned.

**Comment by Sauilitired** [comment]
Fixed in PlotSquared 4.
