### ISSUE TITLE
Plot delete /plot reset does NOTHING.

### ISSUE THREAD

**Issue by BBoyJD10** [IntellectualSites/PlotSquared#2126]
# Bug report template 

**Debug paste link:** 

**Description of the problem:** 
Plot delete /plot reset does NOTHING.

**How to replicate:** 

Plot delete /plot reset does NOTHING.

**Checklist**:

- [ ] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Can you get a `/plot debugpaste` ?

**Comment by BBoyJD10** [comment]
Without FAWE works fine :)

**Comment by N0tMyFaultOG** [comment]
Yeah, that's a known issue which is being worked on
