### ISSUE TITLE
The flag deny-teleport doesn't works

### ISSUE THREAD

**Issue by Nakamia** [IntellectualSites/PlotSquared#2128]
In the code is not checking the flag "deny-teleport" but in the wiki is implemented this flag.

**Comment by N0tMyFaultOG** [comment]
The flag exists - clearly - in the code ? Did you look on the right class?

**Comment by Nakamia** [comment]
Thanks N0tMyFaultOG, I know that, but that class, for example the method "allowsTeleport(..." is never used in the code, so the flag is only created but the checks for that flag works is not implemented in the code.

**Comment by Sauilitired** [comment]
(I hope the fix actually works as intended :cow:)
