### ISSUE TITLE
Placeholder problem

### ISSUE THREAD

**Issue by DoreK333** [IntellectualSites/PlotSquared#2129]
**Debug paste link:** 
https://hastebin.com/sozehimiwa

**Description of the problem:** 
This placeholder nothing returns: %plotsquared_currentplot_alias%

**How to replicate:** 
/papi parse me %plotsquared_currentplot_alias%
execute this command on claimed plot
https://i.imgur.com/zxwx3YU.png
**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by AllMyDreamsAreMemes** [comment]
Make sure the plot has an alias. It is normal to return nothing if the plot doesn't have an alias.

**Comment by Sauilitired** [comment]
The PlotSquared hook is a third party plugin.
