### ISSUE TITLE
error in creating plots

### ISSUE THREAD

**Issue by chris998** [IntellectualSites/PlotSquared#2132]
error log https://pastebin.com/gNPvegEr

**Comment by Sauilitired** [comment]
`[18:18:49] [Server thread/WARN]: java.lang.IllegalArgumentException: Invalid type for multi-area world. Expected 2, got 1`
See installation instructions [here](https://github.com/IntellectualSites/PlotSquared/wiki/Installation#initial-setup). I recommend using `/plot setup` whenever possible.

**Comment by chris998** [comment]
I am using MC 1.12.2 when I got that error.

Not using 1.13.x waiting for stable release for MC.

**Comment by Sauilitired** [comment]
The installation instructions are the same for 1.12.2 and 1.13.x. The current release is as stable as it will get for a couple of weeks. The 1.12.2 version of PlotSquared will get very limited support.

**Comment by chris998** [comment]
Okay thanks for the update.
