### ISSUE TITLE
/plot uuidconvert [mode] not available on Sponge

### ISSUE THREAD

**Issue by GuusLieben** [IntellectualSites/PlotSquared#2137]
# Bug report template 
**Debug paste link:** 
https://hastebin.com/qoguyokuna

**Description of the problem:** 
/plot uuidconvert doesn't exist on Sponge, making it so you cannot convert to offline/online/lowercase mode without basically all plot ownerships/trusts going lost.

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
Merging with #1814
