### ISSUE TITLE
%size% placeholder doesn't work in translations config under plot info section

### ISSUE THREAD

**Issue by Dad3** [IntellectualSites/PlotSquared#2139]
Debug: https://hastebin.com/oyunipasac

******How to replicate:****** 
Use the %size% placeholder in the translations config.

http://prntscr.com/l8qzgq

Should show plot size widthxlength
For example 2 merged plots would be 80x40 (not a single number)
And a 50 block wide plot would be 50x50
(replace "x" with "*"  multiplication symbol (I used x because it changes formatting)

But it shows up as %size% in game. 

**Checklist**:
- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by Sauilitired** [comment]
This "placeholder" is not a part of the message, and it's not going to be (re-)added. It gets too messy when dealing with oddly shaped megaplots.
