### ISSUE TITLE
[Sponge] World no longer compatible.

### ISSUE THREAD

**Issue by AceGamer45** [IntellectualSites/PlotSquared#2145]
DEBUGPASTE : https://hastebin.com/etareraqod

I am currently using the 18.07.06-ae1e58c-2021 version of plotsquared for the spongeforge version 1.12.2-2705-7.1.0-BETA-3206, when I want to update sponge (e. g. sponge 3392, 3481, 3364, etc) my plot world no longer works at all. When I delete the folder from the plot world, I find the players' plots, but in a totally empty world, when I want to put back the world I had, there is no more plot, so there is no more protection for example.

So I try to update PlotSquared but despite all my attempts and the different versions try between PlotSquared and SpongeForge, it is impossible for me to reuse my current world.

What works with my current versions if I have the problem of the fact that no more plots and therefore protection exists, is to rename the folder of the plot world, to restart the server so that it creates a new world then shut down the server and copy the "region" folder from the old plot world to the new folder and at the end everything works correctly again, I have the players' constructions as well as the plots and therefore the protections but I can do this manipulation on all the other recent versions, nothing works to recover the world.

Depending on the versions I can receive this message: That is not a valid plot area (case sensitive).

Do you have a solution? Thank you.

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
This honestly seems like user error and not following appropriate steps to upgrade/update the server.

This is almost 10 moths old, and no one else has added to this ticket or opened similar tickets.  
As such, I am closing this ticket.

@AceGamer45 if you feel the update instructions for Sponge need to be corrected, please work to identify the correct method and update or add the instructions on the wiki.
