### ISSUE TITLE
/plot merge will merge all connected plots with same owner

### ISSUE THREAD

**Issue by Aberzhulan** [IntellectualSites/PlotSquared#2149]
# Bug report template 

**Debug paste link:** https://hastebin.com/juvoyeheji

**Description of the problem:** 
A player only wants to merge a few of their plots in the middle of a line of 10. The "/plot merge" command merges all 10 plots. The "/plot merge direction" command will merge all of them in a line, from the direction they specified.

**How to replicate:** 
1) Stand in a plot where you own several on both sides of it.
2) Run /plot merge
3) Watch as it merges all of them.

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by AllMyDreamsAreMemes** [comment]
Did this just start occurring or is it new? I believe this is normal behavior as I have had this happen to me a number of times on my servers and others. I do agree it is annoying.

**Comment by Aberzhulan** [comment]
I honestly have no idea.

**Comment by Sauilitired** [comment]
https://github.com/IntellectualSites/PlotSquared/wiki/worlds.yml
Set `auto_merge` to `false`.

**Comment by Aberzhulan** [comment]
Is it set to false, but okay then.
