### ISSUE TITLE
Chunks not loading properly in converted plot worlds

### ISSUE THREAD

**Issue by ItsAZZA** [IntellectualSites/PlotSquared#2151]
**Debug paste link:** 
https://hastebin.com/omobiregeb

**Description of the problem:** 
Server lags severely when trying to load chunks in converted (from 1.12.2) plot worlds. Most of the time it doesn't load the chunks at all and crashes the server. The issue doesn't occur in newly generated plot worlds or with non-plot worlds. It was also tested the error doesn't occur without PlotSquared. 

Here's a server thread dump: https://hastebin.com/asuxemifas.md

We're using the latest dev version of PlotSquared and Paper.

**How to replicate:** 

Load a plot world converted from 1.12.2 into 1.13.2. When a player travels in the world the chunks take ages to load usually ending with a server crash.

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by Bobcat00** [comment]
I experienced the same thing running a 1.8.8 plot world that had been upgraded to 1.13.1 with forceUpgrade.  If I flew around the server without PlotSquared, I could visit those chunks with plotSquared without any problem.  But as soon as I visited an upgraded chuck for the first time with plotSquared loaded, the server would crash.

**Comment by MiroTcz** [comment]
The same issue as described above.

**Comment by ItsAZZA** [comment]
Any updates on this issue?

**Comment by Sauilitired** [comment]
Is this still an issue with PlotSquared 4?

**Comment by RedstoneFuture** [comment]
@ItsAZZA Still a issue with the last versions of P²?

**Comment by AeSix** [comment]
Yup. I can confidently say this is confirmed.
Same thing happened with me.  Small area, and some persistent "log on, load chunks, crash" for a while eventually forced all the bad chunks to be converted. 

My solutions:
Updated server & plugins (no fix)
checked configs (no fix)
started with --forceUpdate (no fix, and took 6 hours)
Limited client view distance to 2, logged on, moved about slowly until crashed.  I was looking for a bad area that I could home in on.  After 4 crashes, I spent 30 minutes looking around the same area - nothing. Enlarged my view to 8, nothing, to 16 and 32 - ntohing.  Magically fixed itself.

This server was originally a 1.11 server that had been updated to 1.12, .1 and .2 over time.  The world is 3 years old, there abouts.  So, I'm not sure if a brand new 1.12.2 Spigot generated world would have this issue when converting to 1.13.x or not. 

But there is an issue.  And the solution may just be to brute-force the chunks to load and resolve.  

Maybe the devs can find a more... civilized way of handling this though.

**Comment by AeSix** [comment]
I recently had this same issue on a non-p2 server, a mostly generic spigot survival server. Spigot handled all world generation. 
I'd take a guess that the issue is not PlotSquared dependant, but is rather an issue either with the server itself, or possibly with the host os filesystem (I'm on Ubuntu 18.04, using LXC for this server)

**Comment by ItsAZZA** [comment]
This seems to have been fixed in the latest version of P2. At least the problem doesn't occur anymore in our world.
