### ISSUE TITLE
Issues with generating custom roads in 1.13

### ISSUE THREAD

**Issue by michelmans** [IntellectualSites/PlotSquared#2152]
**Debug paste link:** 
https://hastebin.com/yupolopiro

**Description of the problem:** 
I've created a roadschematic in 1.13, in the schematic itself it was fine, but once it's being generated in the 1.13 server it is not showing some cobblestone walls correctly, cobblestairs and ironbars aren't snapped together and beacons aren't showing light. 

I'm asuming it has something to do with blockupdates. if I place a block beside the not showing cobblestone walls it's magically appearing, the same is for the rest of blocks showing incorrectly. 

If I join using 1.12 using ProtocolSupport, it's showing everything fine. So Any thoughts?

We're using the latest 1.13.2 build and latest dev plotsquared

**How to replicate:** 
Create a custom road with a pole of cobblestone walls, some stairs around a corner, make a nice fence with ironbars and some beacons. Let the world regenerate, and behold. This is only in the 1.13 and higher clients, in a 1.12 client it's showing just fine.

**Checklist**:
- [x] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Try reproducing without FastAsyncWorldEdit

**Comment by michelmans** [comment]
> Try reproducing without FastAsyncWorldEdit

I did, still not showing up properly.

**Comment by michelmans** [comment]
Have you had time to look into this?
