### ISSUE TITLE
/tree and /bigtree essentialX commands bypass plots and roads

### ISSUE THREAD

**Issue by Dad3** [IntellectualSites/PlotSquared#2153]
**Debug paste link:** 
https://hastebin.com/utobijiyen
[1.12.2 spigot]

**Description of the problem:** 
A player without any permissions except /tree command can bypass the road and other player's plots by using the tree command of EssentialsX

**How to replicate:** 
Give a player essentials.tree or essentials.bigtree and they can use /tree (tree) on anywhere they want on the plotworld without any plot permissions at all.
Once this issue is fixed, there is also another issue, these tree commands will probably still go over the road once used, should be fixed like bonemeal saplings.

**Checklist**:
- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by AllMyDreamsAreMemes** [comment]
WorldEdit and FAWE both have very similar commands and they should integrate properly with PlotSquared.

**Comment by Dad3** [comment]
> WorldEdit and FAWE both have very similar commands and they should integrate properly with PlotSquared.

what are the commands? because //tree is just alias for essentials /tree

**Comment by AllMyDreamsAreMemes** [comment]
Sorry, I should have been more clear. It's actually a tool, read this [https://github.com/boy0001/FastAsyncWorldedit/wiki/Commands#tool-tree-type](url)

**Comment by Sauilitired** [comment]
PlotSquared checks BlockPlaceEvent. It'd be more sane for essentials to test if the event gets cancelled, than for us to modify the plugin to work with essentials.
