### ISSUE TITLE
Can't import with Maven

### ISSUE THREAD

**Issue by SpawnChunks** [IntellectualSites/PlotSquared#2156]
# Bug report template 

**Debug paste link:** 

Not Applicable

**Description of the problem:** 
Hello!
I am trying to work with the PlotSquare API, however there is a problem. I can't seem to be able to include the Maven repository in my project. I am using IntelliJ Idea, and I get an error.

**How to replicate:** 
What I am trying to do is the following:
Open IntelliJ Idea, make a blank Spigot plugin.
Press Ctrl+Alt+S and under Build, Execution, Deployment click Remote Jar Repositories. Add http://ci.athion.net/job/PlotSquared/ws/mvn/ to both of them.
Press Ctrl+Shift+Alt+S, go to Libraries, click on the + icon. Click "from Maven" and I have pasted in `com.plotsquared:plotsquared-api:latest` as written in your [documentation](https://github.com/IntellectualSites/PlotSquared/wiki/Developer-documentation-(WIP)). It will look through some files like WorldEdit, .pom, etc. but I will get an error that "No files were downloaded for com.plotsquared:plotsquared-api:latest".

**Checklist**:
- [Not Applicable] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Not Applicable] I made sure I am using an up-to-date version of PlotSquared
- [Not Applicable] I Made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
I couldn't reproduce and our official placeholder add-on uses maven just fine.
