### ISSUE TITLE
Destroy item frame with boat

### ISSUE THREAD

**Issue by DakirDEV** [IntellectualSites/PlotSquared#2169]
**Debug paste link:** 
https://hastebin.com/inimuhaviz

**Description of the problem:** 
If a player runs against a boat on another plot and hangs item frames near that boat, they will be destroyed because the boat touches them.

**How to replicate:** 
Build a wall with an item frame and put a boat in front of it. If a player, no matter if plotowner or unauthorized user, runs against the boat and pushes it against the wall, the item frames are broken.

**Solution:**
I used the VehicleEntityCollisionEvent in my own plugin to prevent this. 
Code:
`public class VehicleEntityCollision implements Listener {

	@EventHandler
	public void onVehicleEntityCollision(VehicleEntityCollisionEvent e) {
		if(e.getVehicle().getType() == EntityType.BOAT) {
			if(e.getEntity() instanceof Player) {
				Player p = (Player) e.getEntity();
				if(PlotPlayer.get(p.getName()).getLocation().isPlotRoad() == false && PlotPlayer.get(p.getName()).getLocation().isUnownedPlotArea() == false) {
					if(PlotPlayer.get(p.getName()).getCurrentPlot() != null) {
						if(PlotPlayer.get(p.getName()).getCurrentPlot().isOwner(p.getUniqueId()) == false) {
						//Here the event is only canceled if the player is not the owner 
						//of the property on which he is located. 
						e.setCancelled(true);
						}
					}
				} else {
					e.setCancelled(true);
				}
			} else {
				//Here the event is aborted anyway, otherwise you can move the 
				//boot with EchoPets or other mobs running around on the plot. 
				e.setCancelled(true);
			}
		}
	}
}`

**Checklist**:
- [x] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
Right. Tested with lily_pad.

- tested with 1.13.2
- last P² version
