### ISSUE TITLE
Non-op players cannot access plugin

### ISSUE THREAD

**Issue by Scabista** [IntellectualSites/PlotSquared#2172]
Debug:
https://hastebin.com/iduyosejur

I'm running over 100 plugins, and just started experiencing an issue with PlotSquared. Players who are not op have no access to the plugin commands, instead they get the following error:
"[Your Prefix] You dont have permission to use this commands. Set to 'none' for no Output"
As far as I can tell, the permissions are configured correctly, and players cannot access the commands in any world. I've spent a good three hours looking for plugins that may conflict, and had no luck. I'd just like players to be able to use the plugin. :v
-
PermissionsEX Perms:
https://gist.github.com/Scabista/73720e4abdd6271e9fe94edcc8431980

**Comment by N0tMyFaultOG** [comment]
>You dont have permission to use this commands. Set to 'none' for no Output

If that's your output it doesn't belong to plotsquared directly as it's not a message from it.

**Comment by Scabista** [comment]
Hey, thanks for the super fast response. So that would mean it must be a problem with conflicting plugins? I'm guessing there's no real errors in how I've got my perms, nor in the debug?

**Comment by N0tMyFaultOG** [comment]
Most likely

**Comment by DevJoey** [comment]
which flag i must add wehn i will allow player to use vilagers
