### ISSUE TITLE
Plot downloading fails [empcraft.com is down]

### ISSUE THREAD

**Issue by Geo25rey** [IntellectualSites/PlotSquared#2184]
**Debug paste link:** 
N/A

**Description of the problem:** 
"/plot download" fails since it relys on https://empcraft.com which is down.

**How to replicate:** 
Run "/plot download" in-game

**Checklist**:
- [N/A] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by Geo25rey** [comment]
Using https://web.archive.org/web/20180327083407/https://empcraft.com/ in the config file instead of empcraft.com may be a temporary fix

**Comment by Sauilitired** [comment]
It's up again.
