### ISSUE TITLE
[WIP] Version 4 Changes

### ISSUE THREAD

**Issue by Sauilitired** [IntellectualSites/PlotSquared#2185]
- Complete restructure of API
- (Possible temporarily) removed Nukkit and Sponge modules
- Added `/schematic list` command (plots.schematic.list)
- remove BO3
- Dropped support for old versions
- Added new BlockBucket system
- Updated to WE7 (hard dependency, fight me on discord if you dislike this 🤷‍♂️ )
- Uses BlockBucket in place of BLOCKLIST and BLOCKS (i.e PlotBlock and PlotBlock[]) everywhere
- Updated generator for new API
- Use WE7 to handle schematics
- Change plot schematics to paste from Y=1.
- Removed PlotMe converter
- Fixed flag permissions
- Fixed schematic based generation

**Comment by MattBDev** [comment]
I know I've been absent for awhile but I'm happy to continue contributing so the plugin is once again in a working state.
Will removing support for older versions mean everything below Minecraft 1.13.x?
I've taken a look at sponge and I think I can get some of it working as soon as Bukkit is fixed.

**Comment by Sauilitired** [comment]
We are writing for 1.13+ as of now, where older versions will be supported in a separate branch. 1.13 changed far too much for us to keep legacy support while still keeping the plugin updated. That said, if anyone wants to maintain the legacy branch, then they're more than welcome to.

Sponge support is something I would ultimately like to keep. But we are prioritizing Bukkit support as of now. If you want to give the Sponge module a go, then that would be awesome :)

**Comment by AeSix** [comment]
I understand the want to use Bukkit, however there may be stuff available to you through Spigot or Paper to make PS more capable & efficient. 

At this point, I'd be happy with a 'lite' version with basic plot functions.  I'm very happy to see work going though and will wait patiently since I cannot contribute more than testing. 

Also, welcome back Matt! :D

**Comment by dordsor21** [comment]
By Bukkit, we mean Spigot/Paper.... It's all the Bukkit "platform"

**Comment by AeSix** [comment]
Thank You for clarifying that! :D

**Comment by Sauilitired** [comment]
It's worth adding that the Bukkit generators are the things holding us back the most. The generator API changed in 1.13, so we'll have to remake all of them.

**Comment by Sauilitired** [comment]
A lot of progress has been made, and the generator is almost working perfectly now. There are still some generation problems where there'll be random holes in the world, and certain rows of chunks have problems with bedrock generation (see album(s) below). There is still an issue where augmented generation doesn't properly clear popular spilling but we should be able to port the code from the legacy version. 

What still needs to be tested more is configuration conversion and configuration using multiverse arguments. Schematics may need more testing and we should look into road schematics to see if there's a way to convert them to the new format. This isn't a whole lot and we're not far from a working release.

https://imgur.com/gallery/FC069qj <-- Proper generation and some bedrock issues
https://imgur.com/a/ya8h1Za <-- Random error

**Comment by Sauilitired** [comment]
The generator seems to work fine and I haven't been able to recreate the previous issues. Augmented generation works. Multiverse creation has been fixed. Schematics have been fixed (and improved). I don't think there's much left to do.
