### ISSUE TITLE
Playerinteractevent error

### ISSUE THREAD

**Issue by mibibini77** [IntellectualSites/PlotSquared#2187]
Could not pass event PlayerInteractEvent to PlotSquared v18.11.15-0252cf7-2052
and /plot debugpaste doesnt work
https://pastebin.com/Am1kanGe

when i interact anything this error is then coming

**Comment by Sauilitired** [comment]
Should be fixed in the newest release, but very little information was provided. Please open a new issue if this is still a problem, but make sure to include server version and error logs.
