### ISSUE TITLE
Can't teleport after respawn.

### ISSUE THREAD

**Issue by Zapic233** [IntellectualSites/PlotSquared#2191]
Player can't teleport with P2 commands after respawn.
If player respawn,when he execute commands that could teleport them to some where such as "/p home""/p auto",he will stand on where he execute commands and receive a message such as "[P2]You has been teleported.".But other functions work correct,player will claim a free plot with"/p auto",but will not be teleported to his new plot.
If player rejoin server,everything goes right,like nothing happened.When he died again,problem again!
I'm on Minecraft 1.12.2 with SpongeForge-1.12.2-2768-7.1.4,and using PlotSquared-Sponge-18.12.12-be48507-2053.

**Comment by MattBDev** [comment]
I'll do my best to get to this issue as soon as I can but be prepared to wait awhile. The sponge port is very broken.

**Comment by 3269199948** [comment]
It’s been a long time, I really want to know if this problem has been solved.
He still bothers me

**Comment by MattBDev** [comment]
Not fixed and won't be for awhile.
