### ISSUE TITLE
Error using latest version on 1.13.2

### ISSUE THREAD

**Issue by TheIntelloBox** [IntellectualSites/PlotSquared#2197]
https://hastebin.com/medewuduke.pl

**Comment by AeSix** [comment]
Did you try grabbing the latest versions of WorldEdit 7?

**Comment by Sauilitired** [comment]
Hastebin is acting up again. We really have to find another paste service :laughing: Uhm, could you possibly upload the stack trace again? 

As I've understood it from @AeSix it was related to WorldEdit. P² 4 requires the latest available version of WE 7.

**Comment by TheIntelloBox** [comment]
Yeah and FastASyncWorldEdit doesn't work with plot squared. There is a problem with vectors

**Comment by Sauilitired** [comment]
FAWE hasn't updated yet. That's why the wiki specifically mentions WE and not FAWE.

**Comment by AeSix** [comment]
https://gist.github.com
It does seem to require a login, but I believe posting issues does too?

It would be nice if github put a newtab or hover window link (like new mail in gmail) on the issues creation page.  But I digress.

**Comment by Sauilitired** [comment]
@AeSix I've thought about that, but they are linked to your account and it gets cluttered. I might create a custom solution, similar to Aikar's timings :man_shrugging:
