### ISSUE TITLE
Cant interact with moded entities sometimes

### ISSUE THREAD

**Issue by evernife** [IntellectualSites/PlotSquared#2198]
**Description of the problem:**  I cant interact with CustomNPCs entities, even with all the interact flags turned on

**How to replicate:** 

Use thermos, install CustomNPCs and try to allow players to interact to CustomNPCs inside your plot.

Minecraft: 1.7.10

**Comment by RedstoneFuture** [comment]
Still a issue? Thank you for the merged pull request.

**Comment by evernife** [comment]
Nop, if merged, is working great :D
