### ISSUE TITLE
PlotSquared generates horrible lags.

### ISSUE THREAD

**Issue by TheIntelloBox** [IntellectualSites/PlotSquared#2204]
Look my timing: https://timings.aikar.co/?id=0a92b111a21c49439af67b99869d8ac0

729,52%...

**Comment by RedstoneFuture** [comment]
I included a `/plot debugpaste` link, please.

**Comment by TheIntelloBox** [comment]
https://hastebin.com/efubowoxuq

**Comment by TheIntelloBox** [comment]
They are from Engine hub

**Comment by dordsor21** [comment]
I assume this timings paste is from the very first 3 minutes of the server having loaded. Please run the timings over a much longer period (or over a 3+ minute period of normal server operation). Server startup has very little correlation with plugin performance in general usage, especially as P2 does a lot during the server startup.

**Comment by TheIntelloBox** [comment]
This was 2 hours after the server loaded.
