### ISSUE TITLE
user can place water and lava on your donned plots

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquared#2205]
**Description of the problem:** 

The DONE system is a big destriction difference to the normal plot-distriction. If anyone set a plot as "DONE", the owner lose a many permissions too. Good conzept, but this down't work completely: For example I found the bug, that the user can place and break lava and bucket blocks in your donned plots.

**How to replicate:**

1. Build this:

![2018-12-28_15 57 53](https://user-images.githubusercontent.com/4140635/50519067-5acb2100-0ab9-11e9-99d9-a5f85800b7a1.png)

2. `/p done`

3. Interact with a bucket -> You get a water or lava bucket and clear the hole.

4. You can place water and lava too.

**Tested with**:

- Spigot 1.13.2
- PlotSquared-Bukkit-4.18.12.28-6292bff-2124

**Checklist**:
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
I'll be attempting to fix this in a different branch of the project. Hopefully I'll be able to push and merge it in one night that way this issue can get closed.

**Comment by Chazotu** [comment]
Currently you dont loose any permission when you mark it as done
