### ISSUE TITLE
/p debugroadregen does not work properly with PlotSquared 4.18.12

### ISSUE THREAD

**Issue by Mario359** [IntellectualSites/PlotSquared#2207]
**Debug paste link:** https://hastebin.com/colificafe

**Description of the problem:** The road between the plots is correctly generated, but /p debugroadregen does not regenerate the road correctly
The road seems shifted, but only on one side
Before:
![2018-12-28_19 06 17](https://user-images.githubusercontent.com/20285750/50524211-c8387b00-0ad4-11e9-9ce4-69430b3c0459.png)
![2018-12-28_19 06 31](https://user-images.githubusercontent.com/20285750/50524214-cb336b80-0ad4-11e9-9744-8a088b90c0c9.png)

Using /p debugroadregen:
![2018-12-28_19 07 04](https://user-images.githubusercontent.com/20285750/50524235-dbe3e180-0ad4-11e9-9c0e-2647ea621420.png)
![2018-12-28_19 07 15](https://user-images.githubusercontent.com/20285750/50524238-de463b80-0ad4-11e9-99af-0d2528902688.png)
![2018-12-28_19 07 34](https://user-images.githubusercontent.com/20285750/50524242-e0a89580-0ad4-11e9-93f6-69c96ed65967.png)

**How to replicate:** 
Create a world with PlotSquared
Make a custom road and save it with /p createroadschematic
Use /p debugroadschematic

**Checklist**:
- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin
*Maybe WorldEdit 7-beta 4 ?*

**Comment by Mario359** [comment]
intersection.schematic: https://cdn.discordapp.com/attachments/229601755468398592/528565321540435968/intersection.schematic
sideroad.schematic: https://cdn.discordapp.com/attachments/229601755468398592/528565327764652043/sideroad.schematic
I replaced the wall block with stone_slab to see what's going on
![2018-12-29_14 23 19](https://user-images.githubusercontent.com/20285750/50538828-8102c680-0b76-11e9-8797-a95520185003.png)
I don't have this problem with smaller plots on another server

**Comment by dordsor21** [comment]
Ensure your schematics are the correct size and the like, as this is confirmed to be working by several people.

**Comment by dordsor21** [comment]
Fixed in 29868bd
