### ISSUE TITLE
Plot move WE issues

### ISSUE THREAD

**Issue by x1p** [IntellectualSites/PlotSquared#2209]
# Bug report template 

**Debug paste link:** 

https://hastebin.com/tufogukitu
**Description of the problem:** 
Plot move destroys the roofs of houses. These blocks are mostly stairs and slabs.

**How to replicate:** 
/plot move

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin
![screenshot_20181229_163936](https://user-images.githubusercontent.com/28690790/50539905-6e918880-0b88-11e9-97be-af41a5edae02.png)

**Comment by x1p** [comment]
It also happens to signs, flower pots, flowers, torches, glass panes, doors. The usual WE errors with 1.13 ;-)

**Comment by MattBDev** [comment]
@x1p can you share some more screenshots please so I can get a better sense of what blocks are being deleted, rotated improperly, placed in the wrong spot, or possibly be the completely wrong block.

**Comment by x1p** [comment]
Doors
![screenshot_20181230_113145](https://user-images.githubusercontent.com/28690790/50546344-b23acf80-0c26-11e9-8557-ed5d63fd3155.png)
![screenshot_20181230_113206](https://user-images.githubusercontent.com/28690790/50546345-b23acf80-0c26-11e9-99bb-ed74423070fe.png)

**Comment by x1p** [comment]
Glasspanes
![screenshot_20181230_113556](https://user-images.githubusercontent.com/28690790/50546413-1a89b100-0c27-11e9-994d-27c6166e556a.png)

**Comment by x1p** [comment]
Signs are placed rotated or against the wrong side which lead to placed in the air. Pictures are Original, moved, detail.
![screenshot_20181230_114224](https://user-images.githubusercontent.com/28690790/50546481-99cbb480-0c28-11e9-8e0e-fd7fef455ee7.png)
![screenshot_20181230_114335](https://user-images.githubusercontent.com/28690790/50546482-99cbb480-0c28-11e9-9323-5ac2a4056ab4.png)
![screenshot_20181230_114419](https://user-images.githubusercontent.com/28690790/50546484-99cbb480-0c28-11e9-9b05-0f88b1559b41.png)

**Comment by x1p** [comment]
Torches (and rotated signs). Pictures are original vs moved
![screenshot_20181230_114916](https://user-images.githubusercontent.com/28690790/50546521-1c547400-0c29-11e9-9096-3d9797a7f363.png)
![screenshot_20181230_114952](https://user-images.githubusercontent.com/28690790/50546522-1ced0a80-0c29-11e9-8600-aa8b96cb6d8a.png)

**Comment by x1p** [comment]
Stairs completely missing. Pictures are original vs moved
![screenshot_20181230_115151](https://user-images.githubusercontent.com/28690790/50546546-8a993680-0c29-11e9-8573-d21d53934398.png)
![screenshot_20181230_115313](https://user-images.githubusercontent.com/28690790/50546547-8a993680-0c29-11e9-9452-275671fbade9.png)

**Comment by x1p** [comment]
Blocks of leaves missing, sign gone. Doors shut
![screenshot_20181230_115457](https://user-images.githubusercontent.com/28690790/50546567-f67b9f00-0c29-11e9-8016-57a7baa06a74.png)
![screenshot_20181230_115538](https://user-images.githubusercontent.com/28690790/50546568-f67b9f00-0c29-11e9-896b-e0eb0d29edd3.png)

**Comment by x1p** [comment]
Fences not connected, fence gates sometimes rotated. North south is placed, east west.
![screenshot_20181230_115816](https://user-images.githubusercontent.com/28690790/50546634-0fd11b00-0c2b-11e9-9821-99c895092567.png)
![screenshot_20181230_115847](https://user-images.githubusercontent.com/28690790/50546635-0fd11b00-0c2b-11e9-8954-ef5fa5ef229b.png)
![screenshot_20181230_120233](https://user-images.githubusercontent.com/28690790/50546636-0fd11b00-0c2b-11e9-8709-04b932b01637.png)

**Comment by x1p** [comment]
Special heads, skin structure gone and placed to the wrong side of the air.
![screenshot_20181230_120706](https://user-images.githubusercontent.com/28690790/50546659-b87f7a80-0c2b-11e9-99da-11322d689c7f.png)
![screenshot_20181230_120758](https://user-images.githubusercontent.com/28690790/50546660-b87f7a80-0c2b-11e9-816b-757bf5d3bf39.png)

**Comment by x1p** [comment]
Trapdoors forget their position
![screenshot_20181230_121229](https://user-images.githubusercontent.com/28690790/50546699-4a878300-0c2c-11e9-81e2-59bde3482a7c.png)
![screenshot_20181230_121253](https://user-images.githubusercontent.com/28690790/50546700-4a878300-0c2c-11e9-8366-c0413d931821.png)

**Comment by x1p** [comment]
Piston heads rotated into horizontal
![screenshot_20181230_121845](https://user-images.githubusercontent.com/28690790/50546742-2ed0ac80-0c2d-11e9-83e5-86cd43a3977c.png)
![screenshot_20181230_121908](https://user-images.githubusercontent.com/28690790/50546743-2f694300-0c2d-11e9-99f9-fb4d55a699fe.png)

**Comment by x1p** [comment]
Banners rotated
![screenshot_20181230_122950](https://user-images.githubusercontent.com/28690790/50546844-cd114200-0c2e-11e9-9941-d2f3baff2f1b.png)
![screenshot_20181230_123035](https://user-images.githubusercontent.com/28690790/50546845-cd114200-0c2e-11e9-911d-79c6d5871d8c.png)

**Comment by x1p** [comment]
Water from the cauldron missing, cobble wall not conn
![screenshot_20181230_123528](https://user-images.githubusercontent.com/28690790/50546879-8708ae00-0c2f-11e9-9efb-982bb2b2f67c.png)
![screenshot_20181230_123601](https://user-images.githubusercontent.com/28690790/50546880-87a14480-0c2f-11e9-8a5c-d4c7aa5d68d1.png)

ected

**Comment by x1p** [comment]
I could probably go on for hours. It just looks like an old version of WE was used for plot copy/move.
I hope you have enough information for this moment ;-)

**Comment by Sauilitired** [comment]
I would like to propose a new way of moving plots, as people have complained previously about big plots being corrupted if something happened during the move. We already have schematic saving and pasting in place, what would work is to save schematics of both plots, clear them and then paste the schematics. If something were to happen during the process, nothing would be corrupted. This would also mean that everything would use the same system, which makes maintenance way easier.

dor has been doing most of the schematic stuff this update, so I’ll him do the braining
