### ISSUE TITLE
Plot merge // plot home

### ISSUE THREAD

**Issue by x1p** [IntellectualSites/PlotSquared#2211]
# Bug report template 

**Debug paste link:** 

https://hastebin.com/tufogukitu
**Description of the problem:** 
If 2 separate plots with each a different owner, the plot is merged and the 2 owners are both owner of that merged plot. Only 1 of them can do `/plot home` and the other one must use `'plot home hisownplayername`
If a plot has 2 owners, both are to be allowed to do `plot home`.

**How to replicate:** 

1. 2 owners having both a plot of their own
2. Plot merge by an admin to override 2 different plot owners to be merged
3. Both players try plot home
4. The one that is second named in `plot info` gets the error message:
`  invalid.not_valid_number: '$2That''s not a valid number within the range: %s'`
5. The second owner needs to do `/plot home 1`. Even if he has only 1 plot.

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by x1p** [comment]
Maybe an idea if `plot home` (without arguments) automatically can be translated by the plugin to execute `plot home 1`?

**Comment by AeSix** [comment]
I attempted to test this, but was unable to merge 2 plots from two owners.  I ensured I had the permissions.

However, as a workaround for @x1p - perhaps a commandhelper script to do what he's suggested:

```
/p h = >>>
    /p h:1
<<<
/p home = >>>
    /p h:1
<<<
```

The problem with this is if CH isn't currently in use, the use of a third party plugin, and if the command changes at a later time.

**Comment by x1p** [comment]
> I attempted to test this, but was unable to merge 2 plots from two owners. I ensured I had the permissions.

Make sure both owners are online
About the workaround: I have something similar. But it would be nice if it would not be necessary.

**Comment by RedstoneFuture** [comment]
At my test I can't replicate this:

**1.** 2 user get 2 difference plots
**2.** /p merge

= booth users are owner in the plot (linke `/p i`) and can use the `p h 1` command



- teted without FAWE
- Spigot 1.13.2
- PlotSquared v4.13

**Comment by x1p** [comment]
Just tested with all the latest builds. It still happens. The first owner can do `plot home`, the second player (as stated in plot info) gets the error when he executes `plot home`. This second player has to execute `plot home 1`
