### ISSUE TITLE
Constant NullPointerException errors on server start

### ISSUE THREAD

**Issue by AccountToReportABug** [IntellectualSites/PlotSquared#2214]
**Debug paste link:** 
`/plot debugpaste` gives no output when the error described below is spamming the console. I searched `latest.log` to ensure I wasn’t simply missing the output because of the spam.

**Description of the problem:** 
I created a plot world using the most recent build of PlotSquared, then a custom road schematic that used 1.13 blocks (coral blocks, coral fans, and waterlogged wooden slabs). I then did `/plot regenallroads` in the console, and that worked fine; the roads were all correctly regenerated using the custom road schematic. But then I restarted the server, and the error that begins on line 146 of [this log](https://hastebin.com/ezazamotag.md) began endlessly spamming the console, and I was unable to login to the server again.

The only plugins on the server (it’s a testing server) are PlotSquared, WorldEdit, WorldGuard, and MultiverseCore. Latest version of PaperSpigot.

Thanks for any assistance you can give!

**How to replicate:** 
Create a plot world that uses 1.13 blocks in the road schematic, then restart the server.

**Checklist**:

- [ ] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by Sauilitired** [comment]
See [this](
https://github.com/IntellectualSites/PlotSquared/releases/tag/4.0-pre-breaking) for 1.13.
