### ISSUE TITLE
ArrayIndexOutOfBoundsException: 2 on startup, but plugin seems to work otherwise

### ISSUE THREAD

**Issue by almateoskott** [IntellectualSites/PlotSquared#2215]
# Bug report template 

**Debug paste link:** 

First what happens with /plot debugpaste:

Debugpaste actually fails now, it did not in the previous version.  Here is what it says:

`
03.01 10:46:26 [Server] WARN at java.lang.Thread.run(Unknown Source) 03.01 10:46:26 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) 03.01 10:46:26 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) 03.01 10:46:26 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) 03.01 10:46:26 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) 03.01 10:46:26 [Server] WARN at com.github.intellectualsites.plotsquared.plot.commands.DebugPaste$1.run(DebugPaste.java:25) 03.01 10:46:26 [Server] WARN at com.github.intellectualsites.plotsquared.plot.util.HastebinUtility.upload(HastebinUtility.java:62) 03.01 10:46:26 [Server] WARN at com.github.intellectualsites.plotsquared.plot.util.HastebinUtility.upload(HastebinUtility.java:32) 03.01 10:46:26 [Server] WARN at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source) 03.01 10:46:26 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) 03.01 10:46:26 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) 03.01 10:46:26 [Server] WARN java.io.IOException: Server returned HTTP response code: 503 for URL: https://hastebin.com/documents 03.01 10:46:13 [Server] WARN at java.lang.Thread.run(Unknown Source) 03.01 10:46:13 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) 03.01 10:46:13 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) 03.01 10:46:13 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) 03.01 10:46:13 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) 03.01 10:46:13 [Server] WARN at com.github.intellectualsites.plotsquared.plot.commands.DebugPaste$1.run(DebugPaste.java:25) 03.01 10:46:13 [Server] WARN at com.github.intellectualsites.plotsquared.plot.util.HastebinUtility.upload(HastebinUtility.java:62) 03.01 10:46:13 [Server] WARN at com.github.intellectualsites.plotsquared.plot.util.HastebinUtility.upload(HastebinUtility.java:32) 03.01 10:46:13 [Server] WARN at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source) 03.01 10:46:13 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) 03.01 10:46:13 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) 03.01 10:46:13 [Server] WARN java.io.IOException: Server returned HTTP response code: 503 for URL: https://hastebin.com/documents
`

Now what is in the logs on startup.
`
03.01 10:39:44 [Server] INFO Version is PlotSquared-0.0.0-SNAPSHOT 03.01 10:39:44 [Server] WARN at java.lang.Thread.run(Unknown Source) 03.01 10:39:44 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) 03.01 10:39:44 [Server] WARN at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:214) 03.01 10:39:44 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:345) 03.01 10:39:44 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:431) 03.01 10:39:44 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) 03.01 10:39:44 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) 03.01 10:39:44 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) 03.01 10:39:44 [Server] WARN at com.github.intellectualsites.plotsquared.bukkit.BukkitMain.onEnable(BukkitMain.java:180) 03.01 10:39:44 [Server] WARN at com.github.intellectualsites.plotsquared.plot.PlotSquared.<init>(PlotSquared.java:126) 03.01 10:39:44 [Server] WARN at com.github.intellectualsites.plotsquared.plot.PlotSquared.setupConfigs(PlotSquared.java:1778) 03.01 10:39:44 [Server] WARN at com.github.intellectualsites.plotsquared.plot.PlotSquared.setupConfig(PlotSquared.java:1705) 03.01 10:39:44 [Server] WARN at com.github.intellectualsites.plotsquared.plot.PlotVersion.tryParse(PlotVersion.java:35) 03.01 10:39:44 [Server] WARN at com.github.intellectualsites.plotsquared.plot.PlotVersion.<init>(PlotVersion.java:23) 03.01 10:39:44 [Server] WARN java.lang.ArrayIndexOutOfBoundsException: 2
`

Information that /debugpaste might have grabbed:
Spigot:  CraftBukkit version git-Spigot-a1ba5fe-3359cb1 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
PlotSquared: PlotSquared-Bukkit-4.86.jar
Plugins (33): LagAssist, WorldEdit, Essentials, VoidWorld, PlaceholderAPI, Votifier, ProtocolLib, DeathMessagesPrime, LibsDisguises, VotingPlugin, BlowableObsidians, ProjectileDamage, EssentialsChat, PermissionsEx, EssentialsAntiBuild, PandoraChatFilter, mcMMO, Vault, xInventories, EssentialsSpawn, MassiveCore, MyWarp, Stickers, Jobs, LWC, PlotSquared, HolographicDisplays, PreciousStones, Multiverse-Core, Factions, Multiverse-Portals, HolographicExtension, ChestShop

**Description of the problem:** 
Errors on startup.  However, other things work that didn't before.  For example, /plot reset works now and it didn't in PlotSquared-Bukkit-18.12.28-9d3edcf-2039.jar the one I was running most recently.  Also, WorldEdit now doesn't throw out errors when used in PlotSquared.  Also, road borders now change correctly when a plot is claimed.  In short, I have no actual complaints--it is working better now in 1.13.2 than ever before.  But I wanted to share the startup log thing in case it is useful or could affect something I haven't discovered yet.  The only command not working, strangely, is /debugpaste .

**How to replicate:** 

Restart the server.
**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
The debugpaste issue belongs to a hastebin outage. You can safely ignore it, sooner or later it fixes itself
