### ISSUE TITLE
World option kill-road-items kills items on the plot, too.

### ISSUE THREAD

**Issue by DeepRobin** [IntellectualSites/PlotSquared#2216]
# Bug report: Item Despawning after dropping in a plot world

**Game Version:** 1.13.2
**Server Type:** Spigot
**Server Version:** git-Spigot-518206a-c4a67ee
**API Version:** 1.13.2-R0.1-SNAPSHOT
**Config:** https://ghostbin.com/paste/7o5uq
**Debug paste link:** https://hastebin.com/wubikafahu

**Description of the problem:** If I drop an item somewhere in the PlotSquared world (even on my own plot), the item will be removed after about 500 milliseconds. In all other worlds it won't despawn.

**How to replicate:** 
Make a plot world with the same config like me.

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by IronApollo** [comment]
Will you provide a link to your latest.log after you've dropped an item in the world, as well as a list of your plugins? A debugpaste is preferable, but hopefully those should help with identifying the issue.

**Comment by AeSix** [comment]
Two questions:
1) Have you confirmed it's not "kill-road-items" in your settings.yml causing this?
2) Have you confirmed it's not another protection plugin, such as WorldGuard, or even your server config causing this?

Might want to check these, then do as IronApollo suggested :)

**Comment by DeepRobin** [comment]
Now /plot debugpaste is working: https://hastebin.com/wubikafahu

**Comment by DeepRobin** [comment]
@AeSix kill-road-items is enabled, but my items are killed on my own plot true

**Comment by AeSix** [comment]
Yes, I understand.  The step I was asking you to take is to disable that function and validate that it is not causing the issue on the plot.  If it is, then then the devs will know more along the lines of what is going on.  If you disable 'kill-road-items' and your items drop without despawning, then it's an issue.  Otherwise, if they continue to despawn, then it's more likely not P2 causing the issue. 

Could the issue be caused by SkyPvP or PAC?  I have no familiarity with these plugins, or their functions.

**Comment by DeepRobin** [comment]
@AeSix SkyPvP is self-made and i am sure there is nothing with the plotsquared world. PAC isn't it too, because in other worlds its working. (Sorry for my bad english)
But I check kill-road-items

**Comment by DeepRobin** [comment]
@AeSix Yes it works with kill-road-items: false.
I think thats an issue.

**Comment by dordsor21** [comment]
Use PlotSquared 4. If the issue continues, reopen.
