### ISSUE TITLE
Make Reload Command working with PlotSquared

### ISSUE THREAD

**Issue by DeepRobin** [IntellectualSites/PlotSquared#2217]
# Reload don't work with PlotSquared

**Debug paste link:** I don't need it 
**Game Version: ** 1.13.2
**Server Type:** Spigot

**Database Type:** SQLite
**Description of the problem:** 
An database connection error occured: the file is already opened.

**How to fix:**
Close the database connection in JavaPlugin#onDisable

**How to replicate:** 
Do /reload instead of /stop or /restart

**Checklist**:

- [] I included a `/plot debugpaste` link
- [x] I made sure there are **no opened duplicates** of this report [(Use Search)] (https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue) 
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
Reload is highly unrecommended by every plugin, and you should never use it, as it's also dangerous without using plugins.

**Comment by Sauilitired** [comment]
No.
