### ISSUE TITLE
Chunk errors on all my plot servers.

### ISSUE THREAD

**Issue by GTA5Racer** [IntellectualSites/PlotSquared#2219]
**Debug paste link:** https://hastebin.com/ojobiridov

**Description of the problem:** 
This has been happening on all my plot servers, everytime someone tries to claim a plot, the roads are missing, basically its just bedrock on the floor 

[https://prnt.sc/m3ehle](url)

**How to replicate:** 

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by Sauilitired** [comment]
Update to PlotSquared 4.
