### ISSUE TITLE
Regenallroads Doesn't Paste Air

### ISSUE THREAD

**Issue by JoeDon16** [IntellectualSites/PlotSquared#2221]
**Debug paste link:** 
https://hastebin.com/ovilazorox

**Description of the problem:** 
"/Plot regenallroads (world) (height)" only regenerations the ground level, and doesn't paste any air above it. The first time I ran this command, it worked. But now I only have 1 layer, instead of little arches on the road, and it's only working on newly generated chunks, but it won't fix the current roads.

/plot debugroadregen DOES WORK perfectly

**How to replicate:** 
- Regenallroads with more than 1 layer (like lampposts/arches in the road)
- Create a new roadschematic and regenallroads and try to use the height argument

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report (there are - none are solved)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

Worked fine on first time, works fine on newly generated roads, but won't replace the old, multi-layered roads.

**Comment by PinoyLifeCraft** [comment]
>> PlotSquared (Version: PlotSquared-19.1.3-b288a2d-2044)

/plot createroadschematic Then Success, but no I didn't see any schematic folder. 
/plot debugroadregen not working :disappointed:

**Comment by JoeDon16** [comment]
> > > PlotSquared (Version: PlotSquared-19.1.3-b288a2d-2044)
> 
> /plot createroadschematic Then Success, but no I didn't see any schematic folder.
> /plot debugroadregen not working 😞

For me, the debug does work perfectly. It's just the regenall

**Comment by dordsor21** [comment]
You need to set the road height to below the position of the lowest air block, i.e. if you've got a block of air at y = 32, then the road height must be 31 or lower.

**Comment by JoeDon16** [comment]
> You need to set the road height to below the position of the lowest air block, i.e. if you've got a block of air at y = 32, then the road height must be 31 or lower.

My road is at y: 64 so I set the height to 65. The air still doesn't paste.

**Comment by dordsor21** [comment]
That's... Not what I said

**Comment by JoeDon16** [comment]
> That's... Not what I said

I am extremeley confused, the wiki says the argument for height is supposed to be how much air to paste on top, and you're talking about the actual road.

**Comment by JoeDon16** [comment]
I have roads like this: [![Screenshot from Gyazo](https://gyazo.com/f484391e261674c1f8e273a132b18bd9/raw)](https://gyazo.com/f484391e261674c1f8e273a132b18bd9)

That I need to override with this:
[![Screenshot from Gyazo](https://gyazo.com/918d48e77fc461e6ee4556c0c9354792/raw)](https://gyazo.com/918d48e77fc461e6ee4556c0c9354792)

but only the ground level is pasting, so the arches are still there.

**Comment by JoeDon16** [comment]
> That's... Not what I said



> I have roads like this: [![Screenshot from Gyazo](https://camo.githubusercontent.com/c359951caba7bfe6d11ad67bb5ab58f81125f363/68747470733a2f2f6779617a6f2e636f6d2f66343834333931653236313637346331663865323733613133326231386264392f726177)](https://gyazo.com/f484391e261674c1f8e273a132b18bd9)
> 
> That I need to override with this:
> [![Screenshot from Gyazo](https://camo.githubusercontent.com/fb6c81f9230032daabcbde44bec0bdc4f4c8de02/68747470733a2f2f6779617a6f2e636f6d2f39313864343865373766633436316536656534353536633063393335343739322f726177)](https://gyazo.com/918d48e77fc461e6ee4556c0c9354792)
> 
> but only the ground level is pasting, so the arches are still there.

Maybe I misunderstood, but according to the wiki the height argument is how much air is pasted above the road schematic. For my road schematic, it is now 1 block high. When I put 10 as the height, it should paste 10 air blocks above that 1 road, thus removing the arches. But this doesn't happen.

**Comment by dordsor21** [comment]
Use the latest build

**Comment by JoeDon16** [comment]
> Use the latest build

I am. The only newer one is for 1.13 as far as I can see because of WorldEdit. How can I work around this issue because the plugin is not working. Is there like a way to transfer all plots to a new world with the correct roads?

**Comment by dordsor21** [comment]
Fixed in P2 legacy as well

**Comment by JoeDon16** [comment]
> Fixed in P2 legacy as well

What do you mean? I'm using the most recent build off Spigot for my version that works. Is regenallroads not pasting air a known bug and something that was going to be fixed in the 1.13 update?

**Comment by AeSix** [comment]
@JoeDon16 grab a copy of the latest build from the Jenkins. 
Any build from #666 on up. 
https://ci.athion.net/job/PlotSquared/

If it's still broken, let 'em know :)

**Comment by dordsor21** [comment]
Should definitely be fixed in latest build
