### ISSUE TITLE
liquid-flow flag ineffective 

### ISSUE THREAD

**Issue by Data-Corruption** [IntellectualSites/PlotSquared#2222]
**Debug paste link:** 
https://hastebin.com/xawefehoke

**Description of the problem:** 
liquid-flow set to false by default in world "dwave", and yet when water or lava is placed via any method it flows. Here are the perms i have set https://hastebin.com/cixusugake.diff so no issue there p sure
Here are the plugins i'm using 
- fawe
- luckperms
- [magibridge](https://ore.spongepowered.org/Eufranio/MagiBridge)
- [meem](https://ore.spongepowered.org/killjoy/MeeM)
- nucleus
- plot^2 (duh)
- [project worlds](https://ore.spongepowered.org/TrenTech/ProjectWorlds)
- [spark](https://ore.spongepowered.org/Luck/spark)
- [prism](https://forums.spongepowered.org/t/prism-official-thread-v3-0-beta/1137)

The only plugin that i think might have the potential to be the causing this was prism. So i removed it and restarted everything and the problem was still there.

**How to replicate:** 
Sponge Version - 1.12.2-7.1.4
PlotSquared Version - 19.01.03-b288a2d-2044
1: I built the server
2: went through the the /plot setup (made a default plot world using PlotSquared generator)
3: edited the world config with the default flag "liquid-flow: false" and a few others. (liquid flow is the only one that isn't working)
4: restarted the server to put edited config into effect and realized the flag had was not working

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
As of at least March 2nd (and well before), Sponge support is not maintained for P2.
If you would like to contribute to the project, that would be wonderful. The devs actively take PRs and merge code.
