### ISSUE TITLE
PlotSquared How Can I Build OFF

### ISSUE THREAD

**Issue by CLGNTURK** [IntellectualSites/PlotSquared#2224]
Description of the problem:

I Have a Problem PlotSquared in 1.8
Hello Guys. I Need to Build off in my own plot World.Anybody Can Build or Break Somethink. I Want to just Place and Break one of item its Sign for Player.How Can I Do it. Thanks For Your Help.

**Comment by dordsor21** [comment]
absolutely no idea what you're asking here
