### ISSUE TITLE
Plot always covered in bedrock

### ISSUE THREAD

**Issue by Matt4499** [IntellectualSites/PlotSquared#2225]
Debug Paste: https://hastebin.com/igemuwituc

**Description of the problem:** 

Top layer of plot is always covered in bedrock. Tried plot world creation multiple times with MultiVerse Core and each time the top of all plots are covered in bedrock. Tried /plot setup as a last resort and still bedrock. 

Tried:
/mv create plots normal -g PlotSquared:size=64
/mv create plots normal -g PlotSquared:h=100,main=2,s=32
/mv create plots normal -g PlotSquared:h=100,main=2,g=5,s=100
/mv create plots normal -g PlotSquared:h=64,main=2,floor=2,gap=7
/plot setup

Results in:

https://imgur.com/a/Cacgunz

**How to replicate:** 
Create a plot world using the above commands.

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
What happens if you use P2's built-in multi world function for your plot worlds and mvc for non-plot worlds?

**Comment by AeSix** [comment]
it's explained pretty well in the wiki. It's 11:30pm and I'm going to bed, otherwise I would post the link. 

You should skim the wiki and read the parts you need. 

As for the issue reported, the devs will decide if it's worth pursuing.

**Comment by Matt4499** [comment]
Setting the floor to something besides bedrock resolves the problem, but causes the whole underneath of the world to be open to the void. 
![2019-01-06_23 09 23](https://user-images.githubusercontent.com/33269887/50750144-17835780-1209-11e9-88e3-8e499ea6f887.png)
![2019-01-06_23 09 01](https://user-images.githubusercontent.com/33269887/50750147-19e5b180-1209-11e9-97d4-966e4d302315.png)

**Comment by dordsor21** [comment]
You are using a very outdated multiverse. Try updating ( https://ci.onarandombox.com/job/Multiverse-Core/ ), though I'm not sure if that'll fix anything. Do any of your other plugins have anything to do with world generation? Cannot reproduce this issue.

**Comment by AeSix** [comment]
@Matt4499 
I'm sorry I didn't get back to you sooner.  I just verified that additional worlds can be created with PlotSquared alone, without multiverse or multiworld. 

The instructions for doing so are on the wiki as I said:
https://github.com/IntellectualSites/PlotSquared/wiki/Installation#option-3-using-the-area-create-command.  There are many possible options.  The config file can be modified with the server stopped, but you will have to manually delete that world's data files in order for some of the changes to take affect (such as plot/road size/schematics/materials, etc).  May be easier to set it up with the command right the first time :)

```
a basic second world setup command may look like:
/p area create plotworld size=24

You can then use 
/p area tp <world-name> to go between the worlds.
```
I would set up some kind of automated teleporter or at least warp commands for the players.

**Comment by Matt4499** [comment]
> 
> 
> You are using a very outdated multiverse. Try updating ( https://ci.onarandombox.com/job/Multiverse-Core/ ), though I'm not sure if that'll fix anything. Do any of your other plugins have anything to do with world generation? Cannot reproduce this issue.

I updated to the version of Multiverse you suggested, and attempted to make the plot world, only to result in plots still being filled with bedrock.
![2019-01-15_23 51 41](https://user-images.githubusercontent.com/33269887/51229176-0d580c00-1921-11e9-83a5-6a4def37f136.png)





> 
> 
> @Matt4499
> I'm sorry I didn't get back to you sooner. I just verified that additional worlds can be created with PlotSquared alone, without multiverse or multiworld.
> 
> The instructions for doing so are on the wiki as I said:
> https://github.com/IntellectualSites/PlotSquared/wiki/Installation#option-3-using-the-area-create-command. There are many possible options. The config file can be modified with the server stopped, but you will have to manually delete that world's data files in order for some of the changes to take affect (such as plot/road size/schematics/materials, etc). May be easier to set it up with the command right the first time :)
> 
> ```
> a basic second world setup command may look like:
> /p area create plotworld size=24
> 
> You can then use 
> /p area tp <world-name> to go between the worlds.
> ```
> 
> I would set up some kind of automated teleporter or at least warp commands for the players.
> 
> > <img alt="" width="48" src="https://avatars0.githubusercontent.com/u/11821084?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/4908d9947135e4536ef61d61512ee575f869bf6f/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e2e69636f"> GitHub**[IntellectualSites/PlotSquared](https://github.com/IntellectualSites/PlotSquared)**PlotSquared - Reinventing the plotworld. Contribute to IntellectualSites/PlotSquared development by creating an account on GitHub.

Running /plot area create plotworld size=24 created the correct plotworld, not filled with bedrock on the top. Thank you.
![2019-01-15_23 55 16](https://user-images.githubusercontent.com/33269887/51229223-34aed900-1921-11e9-8d81-5718ffead8b5.png)
