### ISSUE TITLE
What does /plot done do?

### ISSUE THREAD

**Issue by Pangamma** [IntellectualSites/PlotSquared#2226]
**Description of the problem:** 
I've checked the wiki and I've even tried checking the code and I still don't have a full understanding of everything /plot done can do. 

Does it protect plots from automatic disposal?
Does it do other things? 
I've (low-key) wondered this for years now.

**Comment by dordsor21** [comment]
Basically, what's in the settings.yml for "done":
```done:
  # Require a done plot to download
  required-for-download: false
  # Only done plots can be rated
  required-for-ratings: false
  # Restrict building when a plot is done
  restrict-building: false
  # The limit being how many plots a player can claim
  counts-towards-limit: true```
