### ISSUE TITLE
"/plot debugroadregen" is buggy

### ISSUE THREAD

**Issue by DeepRobin** [IntellectualSites/PlotSquared#2228]
# "/plot debugroadregen" is buggy

**Debug paste link:** https://hastebin.com/ipohepusoy 
**Server Type:** Spigot
**Server Version:** git-Spigot-518206a-c4a67ee
**Minecraft Version:** 1.13.2

**Description of the problem:** /plot debugroadregen regenerates merged plots to single plots, but the plot is still merged(only the ways are there). I think this is the same with /plot regenallroads.

**How to replicate:** 
/plot merge (i had an 2x2 plot) and /plot debugroadgen

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Update p2 https://ci.athion.net/job/PlotSquared-Breaking/lastSuccessfulBuild/artifact/target/PlotSquared-Bukkit-4.89.jar

<blockquote></blockquote>

**Comment by DeepRobin** [comment]
@N0tMyFaultOG in the last version its not working, too

**Comment by N0tMyFaultOG** [comment]
Please visit us on our discord to assist you further  https://discord.gg/ebreupz/

**Comment by dordsor21** [comment]
don't use debugroadregen in the corner of your plot such that it regenerates roads in the middle of the plot.
