### ISSUE TITLE
/p leave does not work

### ISSUE THREAD

**Issue by UnexMC** [IntellectualSites/PlotSquared#2236]
I have a Nukkit Server on 1.8.0 and /p leave is not working. Also theres no error shown in console

**Comment by N0tMyFaultOG** [comment]
It looks like the bug appears under spigot as well.

**Comment by Sauilitired** [comment]
Is it also present in version 4, @N0tMyFaultOG?

**Comment by N0tMyFaultOG** [comment]
Yeah, legacy and v4

**Comment by Sauilitired** [comment]
Then I have reason to care. Thanks for reporting the issue :cow:

**Comment by dordsor21** [comment]
/plot leave works fine. It does not teleport you from the plot, but rather removes you from the members/trusted list.

**Comment by UnexMC** [comment]
What Command I'm using as a normal player to delete a plot??

**Comment by AeSix** [comment]
@unexmc there is a wiki. there is a help command. there is basic usage posted on the spigotmc/sponge/nukkit plugin pages.

but because you asked nicely,
/p delete  or /p remove
