### ISSUE TITLE
/p claim does not work

### ISSUE THREAD

**Issue by UnexMC** [IntellectualSites/PlotSquared#2237]
/p claim does not work on my Nukkit Server. I 'can't claim more plots' Also an Error message isn't in my console

**Comment by dordsor21** [comment]
@UnexMC Please don't ignore the checklist for opening issues, it's there for a reason. Please provide a debugpaste and ensure you are using the latest P2.

Also, make sure you have the plots.plot.# permission within the config setting of `limits.max-plots` in settings.yml.
