### ISSUE TITLE
Nukkit | Water can run outside the plots

### ISSUE THREAD

**Issue by UnexMC** [IntellectualSites/PlotSquared#2240]
Here's a Screenshot of it
[https://picload.org/view/dcilcdwl/screenshot_20190118-185832.jpg.html](url)

**Comment by dordsor21** [comment]
The image doesn't work, no debugpaste provided and checklist not completed. Please provide the required information.

**Comment by UnexMC** [comment]
copy the link and paste in your browser..

**Comment by dordsor21** [comment]
Please provide a debugpaste as well.
