### ISSUE TITLE
Prices for claim, sell and merge dont work

### ISSUE THREAD

**Issue by Padaru** [IntellectualSites/PlotSquared#2242]
**Debug paste link:** 
https://incendo.org/paste/view/4f42f02ef5e54655a6144c29397b4aa2

**Description of the problem:** 
i would like set up prices for selling, claiming and for merge a plot with this lines in the settings.yml:
  # Allow economy to be used
   economy:
      use: true
      prices:
        claim: 100.0
        sell: 75.0
        merge: 100.0
# Send anonymous usage statistics. Bukkit only setting.

if i now give me money ( used pugin is essentials ) and try to claim a plot, so i become the plot, but dont pay money - you can see it in pic1.png.

**How to replicate:** 
1. change the settings.yml to my settings.yml with the economy lines
2. setup a default plot world
3. check your money - /money
4. claim a plot
5. you become the plot, but you have the same money as before 
6 check the money with /money

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] - last report is from 2015 i think a newer one is ok :P I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] --> if i sell a plot and buy it then, the economy works I made sure the bug/error is not caused by any other plugin

[settingsyml.txt](https://github.com/IntellectualSites/PlotSquared/files/2775445/settingsyml.txt)
![pic1](https://user-images.githubusercontent.com/17899477/51425768-bb450e00-1be0-11e9-9321-0949dccdeeef.png)

**Comment by dordsor21** [comment]
```
    economy:
      prices:
        merge: 100
        sell: 100
        claim: 100
      use: false
```

**Comment by Padaru** [comment]
thx very much
