### ISSUE TITLE
Better Price Flag

### ISSUE THREAD

**Issue by UnioDex** [IntellectualSites/PlotSquared#2244]
Price flag are now looking like that:
http://prntscr.com/m9o0cs

Players don't know how to read scientific notations and they got scammed so frequently. So can you please  show that value without scientific notations? Thanks.

**Comment by N0tMyFaultOG** [comment]
Can you attach a `/plot debugpaste` please like the template told you to do.

**Comment by dordsor21** [comment]
Use the latest build for your version, and ensure that `General.scentific` is set to false (it should be by default)
