### ISSUE TITLE
Players who dont have plot permission can still spawn mobs in water

### ISSUE THREAD

**Issue by RealmportalMC** [IntellectualSites/PlotSquared#2245]
Plot debug paste: https://hastebin.com/vokodudahi

**Description of the problem:** 

People who are not added or trusted on a plot can still spawn mobs if they spawn them in water.

**How to replicate:** 
try to spawn a mob in water on a plot you shouldn't have permission to access. It doesn't work on land. seems to only work in water.
**Checklist**:

- [x] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by x1p** [comment]
I have to confirm sadly.
My findings: It only works in 2 blocks deep and from a small distance, so not too close to the pool.

Any progress so far?

**Comment by MattBDev** [comment]
@x1p no progress has been made so far. unfortunately it's not as high on the todo list as api work and null pointer fixes.
