### ISSUE TITLE
Plotsquared Flag permission item with subid bypass blocked item flags

### ISSUE THREAD

**Issue by xion87** [IntellectualSites/PlotSquared#2248]
**Description of the problem:** 
When you want prevent some item to be used, for example i negate this permission plots.set.flag.use.0, users are still able to use the banned item on flags by typing "/p flag add use 0:0" Using any subid it bypass the permission negation (air:0 dirt:0 ecc...)

**Comment by Sauilitired** [comment]
Fixed!
`plots.set.flag.use.<material>`, uses Minecraft material names ([list](https://www.digminecraft.com/lists/item_id_list_pc.php))
