### ISSUE TITLE
Bypassing the world border

### ISSUE THREAD

**Issue by theJ3H** [IntellectualSites/PlotSquared#2249]
# Bug report template 

**Debug paste link:** 

https://incendo.org/paste/view/294b0057704d4c7fba19c7c73e3ab639
**Description of the problem:** 
A player can get past the world border by not running directly at it. Instead you have to fly agains the border with a certain angle or move forward while also moving to the side.

https://youtu.be/g63wq1iNfTw

**How to replicate:** 

Look at the video.
You can also attempt to get past the border by looking directly at the border and pressing W and A at the same time.
**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
I feel like this is related to one of those old directional issues minecraft use to have with certain things like redstone.

**Comment by AeSix** [comment]
Your debugpaste has been removed from hastebin.  This is why the devs have moved debugpaste to a new site, which they control.  Please update P2, test again.  If the issue perissts, update your original post with a new debugpaste and any additional info you can provide. 

If for some reason, an update manages to fix this issue, please update and close :)

**Comment by AeSix** [comment]
I suggest using a newer build from https://ci.athion.net/view/Everything/job/PlotSquared/
Test. If it's still an issue, update the ticket so the devs can have more accurate information. 
Create a new debugpaste as well, please. 

If this fixes the issue, update and close the ticket please.

Be aware that the devs may not be able to resolve this issue as it may be a core issue with Minecraft 1.8.8.  You may want to test older builds, in the event that something changed with newer versions of Minecraft which had to be accounted for in newer builds of P2.

**Comment by theJ3H** [comment]
This is still a problem in the latest dev build. I've updated the OP with the new debug paste.

In addition to the issue described in the OP it is also possible to bypass the border using enderpearls.

**Comment by theJ3H** [comment]
https://github.com/theJ3H/PlotSquared/commit/48596dd7e2bf5b7843bd7f5d5dec35e1fa993220

Something like this seems to fix the issue shown in the video. But I can't figure out how to fix the enderpearl issue. A player can throw a pearl so that it will always land on a plot, but apparently the border is only checked if a player is moving over a road.

**Comment by AeSix** [comment]
I've tested with Spigot 1.13.2 and P2 4 build 136. 
I had a staff assist me as well.  We cannot bypass the border with elytras, however there are areas near plot corners where we can fly right through in creative flight (not using an elytra), coupled with being in flight speed 9 and 10.  Flight speed 8 does not seem capable of passing the barrier. 

Even then, the player is pushed back to the plot several times before a brute-force attempt is made and successful at reaching the next plot over. 

Perhaps changing the players speed once they reach the barrier to 0 could be an option.  There's obviously a trigger, for the message to the player, piggybacking that to either set the players velocity to 0 (not their fly/walk speed, but as if they hit a stone wall) or to teleport the player to their /p home or back several blocks.  The problem with this is that the message does not fire when the brutefoce attempt is successful. 

Another thought is perhaps to have a plugin (or PR) which replaces P2's barriers with WorldGuard regions, and disallow exiting the region, or perhaps disallow entering the __global__ region, and then allow that player full access to the region of their plot.  This seems really redundant however.  

(I am not a developer, I just have silly ideas that sometimes helps to solve problems)
