### ISSUE TITLE
Condense Database Problem

### ISSUE THREAD

**Issue by UnioDex** [IntellectualSites/PlotSquared#2252]
# Bug report template 

**Debug paste link:** 

https://incendo.org/paste/view/449b430ec0974feba5b1f1745af47d7f

**Description of the problem:** 
When i try to condense my world i get database error spammed in my console and its trying to move plots to same location over again.
Message that spams:
https://pastebin.com/NPk2E1nA

**How to replicate:** 

No idea. But i can provide my database by request.

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
Can you confirm that this issue happens with any version of Minecraft? 
Shutdown your 1.8.8 server, copy the directory, update it to 1.12.2 - server and plugins, and test again.
You may also want to use a file based system as another tests, to make sure it's not your SQL setup. 

This will help the devs know if it is a mc1.8.8 specific issue or if it's more base than that. There's been a lot of changes to the server code in a lot of areas over the last 3 years.
