### ISSUE TITLE
Placeholderapi placeholders are broken.

### ISSUE THREAD

**Issue by cloakfox** [IntellectualSites/PlotSquared#2255]
As the title says, this is the case on the latest version.

**Comment by N0tMyFaultOG** [comment]
Papi is a third party service, they need to update their placrholders to the new api version.

**Comment by cloakfox** [comment]
Guess what the guys at placeholderapi github said, when users reported the bug there.

**Comment by N0tMyFaultOG** [comment]
It's their plugin and their placeholders, if they want to offer PlotSquared they need to update it.
Neither they directly said that we need to update it:
> At the moment can we not fix this issue, since the main maintainer of the expansion (Clip) is busy with real life stuff.

:P

**Comment by cloakfox** [comment]
Perhaps you could submit a pull request, it's kinda a big issue when none of the placeholders work on 1.13.2

Unless you know of any alternatives that do work.

**Comment by Sauilitired** [comment]
They haven't released the source code for the original extension, so we cannot update that. Anyone is free to do create their own extension, but that would be separate from PlotSquared. *We* won't do it, however. We're busy on making version 4 as stable as possible in our limited spare time.
