### ISSUE TITLE
PlotSquared 4.0 errors (FastAsyncWorldEdit) [1.13.2]

### ISSUE THREAD

**Issue by cloakfox** [IntellectualSites/PlotSquared#2256]
Latest version of PlotSquared doesn't seem to be compatible with the latest version of FastAsyncWorldEdit.

Some errors from console: https://pastebin.com/DcwSzPXP https://pastebin.com/yrKNCTuk

Errors when joining server: https://pastebin.com/nm8YwRYu

Using FastAsyncWorldedit version: FastAsyncWorldEdit-bukkit-1.13.134
And PlotSquared version: 4.0
Running on PaperSpigot 1.13.2 (build 509)

**Comment by N0tMyFaultOG** [comment]
FAWE cannot be used with p2 v4 yet, use WorldEdit in the meantime.

**Comment by cloakfox** [comment]
What a great solution.

**Comment by N0tMyFaultOG** [comment]
Well, it's currently in the process of being updated, you can either use WorldEdit or nothing.
