### ISSUE TITLE
I can't create a Plot with a schematic

### ISSUE THREAD

**Issue by LeoPotter** [IntellectualSites/PlotSquared#2257]
Hi, few days ago I asked to you how to create a plotworld with the same schematic in all plots (the old post: https://github.com/IntellectualSites/PlotSquared/issues/2254), but the plugin doesn't create a plotworld with that schematic, and if I try to do /p claim (after set in the world.yml the on_claim option true), it says "Failed to past the schematic". Why??

**Comment by Sauilitired** [comment]
Please don’t ignore the issue template. It’s there for a reason. Attach a /plot debugpaste

**Comment by LeoPotter** [comment]
https://incendo.org/paste/view/e3da11413a80471db7c530dcebafd850

**Comment by N0tMyFaultOG** [comment]
`[16:48:52] [Server thread/INFO]: [0;31;1m[DynamicSigns] [0;31;22mCracked by t0R[m`
lmao

**Comment by LeoPotter** [comment]
Emh lol I don't know who t0r is

**Comment by LeoPotter** [comment]
Founded something to help me?

**Comment by AeSix** [comment]
His point, @LeoPotter, is that you are using a pirated plugin, which could have been maliciously tampered with.  It could potentially be stealing secure data from you.  Anything from any text input through the server to user tokens. It could also be interfering with other plugins, causing them to break - including P2. 

You should probably remove that plugin, and inform all of your players of the potential security breach. 

And then you should remove every .jar you have, including the server, and re-download to make sure there was no malicious code inserted into those programs and plugins. 

Of course, it could be completely benign.  But, do you really want to risk it?

**Comment by AeSix** [comment]
Also, this:
Check your PlotSquared/config/settings.yml for 
# Schematic Settings
schematics:
  # Whether schematic based generation should paste schematic on top of plots, or from Y=1
  paste-on-top: true

if this is set to "false" it would be pasting the schematic at y=1, not atop of the plot.

**Comment by dordsor21** [comment]
https://github.com/IntellectualSites/PlotSquared/wiki/Schematic-Generation
