### ISSUE TITLE
Error in Console

### ISSUE THREAD

**Issue by DeadIntermediate** [IntellectualSites/PlotSquared#2259]
# Bug report template 

**Debug paste link: https://incendo.org/paste/view/1f71762d803548c9a454ac4d1b13469c** 

**Description of the problem:** 
Just displays this error: https://pastebin.com/py0jACny
Not sure if I should be concerned or not.

**How to replicate:** 

When the server starts up or restarts.

**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
Is this still an issue with the new build?
https://ci.athion.net/view/Everything/job/PlotSquared-Breaking/

**Comment by dordsor21** [comment]
Yep, this is fixed. 4 duplicate issues... ((:
