### ISSUE TITLE
/p auto doesnt expand world border

### ISSUE THREAD

**Issue by theJ3H** [IntellectualSites/PlotSquared#2264]
# Bug report template 

**Debug paste link:** 

Won't do, as the new debugpaste contains logs and I don't want to leak data from production.
**Description of the problem:** 
A player can get a plot that is outside the world border using /p auto. The world border is not expanded. I think this was not a big problem before #2263 but now the player gets teleported to the edge of the border and has no way to access his plot.

**How to replicate:** 

Not sure how easy this is to replicate, we ran into this issue in production, where we had /p auto give us a plot outside the border every time. Should also be possible by just creating a new world and using /p auto until the issue occures.

I tried to fix it doing this: https://github.com/theJ3H/PlotSquared/commit/a9a8f5674d493079fe930da0a88d35f8812dcf4d

Now it works on our production system, but it might also be due to some other reason, like a restart or a manual /p claim by a player somewhere.

**Checklist**:

- [] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
Border expansion was never something I've seen in P2. Is this a bug, or a feature request?

Since you don't want to give us a debugpaste, and I respect that,
please copy the start of your latest.log, redacting your IP address, port, etc - from first line to the last of the load up.  That will help.

**Comment by MattBDev** [comment]
Border expansion is a feature but looks like it broke long before #2263

**Comment by AeSix** [comment]
@theJ3H  If this is still an issue, and you have tested your code to be working properly, do a PR so the devs can maybe incorporate it into P2. 

If it's still an issue and your code isn't working, we'll re-open the ticket.
