### ISSUE TITLE
Bug in regenallroads

### ISSUE THREAD

**Issue by CrashyTop** [IntellectualSites/PlotSquared#2265]
Anyone have any idea what the error that is giving in the plotsquared can be when it puts the paths. I tested just by putting some normal blocks like stone, wood and it worked. When I put these of this chunk bug. 
Print-> https://prnt.sc/mims2e

As soon as I type regenallroads in the console, the error appears -> https://pastebin.com/UaumHVDG
I already took many blocks that could give a problem and did not work.

Sorry my english, i using google translate for this message

**Comment by CrashyTop** [comment]
Link in hastebin-> https://hastebin.com/osozegizej

**Comment by MattBDev** [comment]
Patched.
