### ISSUE TITLE
Repeating chunk glitch

### ISSUE THREAD

**Issue by braceyourself07** [IntellectualSites/PlotSquared#2266]
**Debug paste link:** 
Info: https://hastebin.com/uyepukufut.bash
Startup: https://hastebin.com/iwugipihob.sql
Config: https://hastebin.com/ireyotogur.bash
Worlds: https://hastebin.com/zeruzeyeje.sql (this happened on world plot35)
P2_usethis:  https://hastebin.com/bavofagoko.pl

**Description of the problem:** 

This is an interesting observation. A while back I was talking with dords about chunk glitches / ghost blocks but we've  always thought it was a problem with FAWE.  However, I'm running a 'just for fun' build contest where no editing plugins are allowed--only hand placed blocks.  And it's still happening.  Interestingly though since blocks are hand-placed, you can actually see the repeating ghost chunk changing as the person builds:

https://brdv.coffee/storage/uploads/4/ApplicationFrameHost_2019-02-08_23-58-58.png
https://brdv.coffee/storage/uploads/4/ApplicationFrameHost_2019-02-09_00-22-02.png

The ghost chunk appears to be coming from this players' plot:
https://brdv.coffee/storage/uploads/4/ApplicationFrameHost_2019-02-09_00-22-15.png

We are using P2 version 19.1.26 (build 687) on paperspigot 1.12.2.  I'm curious if anyone else has run into this issue.
A restart fixes it, but it will happen again within 2 hours or so.
Upon restarting, the chunk is overwritten.  Notice in these screencaps it's the portion of the mushroom:
https://i.imgur.com/cfKeVf9.png
https://i.imgur.com/ZfzUAK1.png

Anything that seems to trigger chunk updates (e.g. /plot clear, //fixlighting, using a sphere brush, etc) will cause the repeating chunks to appear once this phenomenon happens.

**How to replicate:** 
The most difficult and frustrating thing about this glitch is that it's difficult to reproduce intentionally. It seems to only happen when there are a lot of players online (20-30+).  For example, even though the glitch happened twice even after a server restart... after a third restart it has yet to happen and it's been over 8 hours now. 

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin <-- I've tried a number of times to isolate this and it doesn't seem to be related to any other plugin.  I also removed the VoxelightPlace plugin since it was causing errors (which seemed to be unrelated) but have made no other changes to the server since submitting this bug report.

**Comment by AeSix** [comment]
Try updating Java.  You're using a relatively old update (151) I vaguely recall seeing similar years ago, however I believe this should be resolved with 1.8_181 (The current is 1.8_202)

You also appear to running several other plugins that could potentially be causing the issue, including one which is throwing an error on startup (VoxelLight-Place) though the error *should* be unrelated and un-causative, it's still an issue you should address if possible. 

For testing purposes, I would consider:
Update Java to 1.8_191 or newer
- test this first, as it may be the complete cause
If the issue continues:
Make a duplicate of your server for possible intrusive testing (So your production server is unaffected)
Remove any plugin which may affect building, schematics, etc other than FAWE/WE & P2
Update all remaining plugins
- test again
If the issue still continues, update your post with a debugpaste 

If you truly believe it is FAWE causing the issue, replace it with WorldEdit 6 for testing.

**Comment by braceyourself07** [comment]
Thanks for the ideas to try.  I will try updating java on a test dedi and see if that helps.

**Comment by dordsor21** [comment]
And hastebin has already deleted your stuff >.>

**Comment by braceyourself07** [comment]
:man_facepalming: hastebin has become increasingly unreliable :(

Yes FAWE was installed, but since our contest was hand-placed blocks only, no one had perms to use it. But I imagine P2 uses it to change block borders on claim, etc. 

I am going to update to Java 8_191 this weekend and we will eventually host another contest. Since the hand-placed blocks contest was popular, we will do another one at some point and this time I'll just use regular WorldEdit instead of FAWE and see if the chunk glitches persist.

Regarding what AeSix said, I did remove VoxelLight-Place and the issues persisted. 

As I said before, the issue, while common, is difficult to reproduce on demand because it requires a lot of players to be on at the same time.  It's never occurred on a server with only a handful of people on it.

**Comment by dordsor21** [comment]
On an off-topic note, I think BuildersUtilities has the functionality of voxelight place, but less buggy?

**Comment by braceyourself07** [comment]
Day 1 after java update to java 8_191 and everything seems fine.  Won't really know for sure until we run another contest and get a large group of people using worldedit simultaneously. 

BuildersUtilities has the secretblocks menu, yes, for items that can't be found in player creative inventory but the person requesting it needed it for other block types that weren't in the secretblocks menu. But that was one of the first things I removed after our last build contest with the chunk error.

I'll report back to this thread to see if the chunk glitches come back.  Sundays are usually our busiest days and if the chunk glitch will reappear, it will do it then.  If not, we may be home free.

**Comment by dordsor21** [comment]
I've picked around in the code of it before because I didn't like how it worked sometimes. It wouldn't affect chunks. It would be logical that either P2 or FAWE would be the cause. I know P2 had some chunk listeners but I've never really looked at them. When I get the time I'll have a look.

**Comment by dordsor21** [comment]
Could you re-upload your settings.yml? It would be quite useful to see your settings regarding chunk trimming/managing

**Comment by braceyourself07** [comment]
Sure thing,
This is the settings.yml from the contest server where we were holding the "no plugin" challenge
https://pastebin.com/ZGBWidK6

This is the settings.yml from our public plots server where the repeating chunk ghost block glitch usually occurs.
https://pastebin.com/JUisPCCs

Though I don't use the chunk processor on either.  I do use plot expiry on the public plots server, though, to delete blank plots after 14 days.  So far so good, I still haven't had any glitches yet 👍

**Comment by braceyourself07** [comment]
So far today we've had a fairly consistent 120-130 players online with about 50% of them being on our public plot server.  It may be a few weeks until we have our next contest, but I'd say the java update seemed to have fixed the issue.

**Comment by braceyourself07** [comment]
Welp, too good to be true.  The ghost chunks are back.  This is after a /plot merge and the road area disappeared as usual during the merge, but left behind ghost blocks:
https://brdv.coffee/storage/uploads/4/ApplicationFrameHost_2019-02-18_19-50-14.png

After doing //fixlighting:
https://brdv.coffee/storage/uploads/4/ApplicationFrameHost_2019-02-18_19-51-17.png

Back to the ol drawing board I guess.  Keep in mind this isn't the same chunk error as the one we had during our contest.  These ghost blocks are harmless and disappear when a player flys away a few chunks and returns to the area, or relogs.  The errors we had during the contest was an actual broken chunk that was replaced with another chunk somewhere in the world.

**Comment by dordsor21** [comment]
P2 doesn't use FAWE anymore as far I can tell. Did you remove FAWE for that latest stuff?

**Comment by braceyourself07** [comment]
I am using the latest (at the time) P2 for minecraft 1.12.2, not the PlotSquared that doesn't use FAWE.

**Comment by dordsor21** [comment]
Yeah 1.12 P2 doesn't use FAWE, at least I can find nowhere that it does - no FAWE dependencies etc

**Comment by braceyourself07** [comment]
Just to update anyone following this thread.  Dordsor and I did some more testing including a version of P2 that allows you to disable FAWE optimizations.  We've come to this conclusion:

1) 1.12 PlotSquared does indeed use FAWE by default
2) With FAWE-P2 integration **disabled** and ghost blocks present, FAWE commands (such as //fixlighting) will produce the ghost blocks, but P2 commands (such as /plot clear or /plot merge) will not produce ghost blocks.
3) With FAWE-P2 integration **enabled** and ghost locks present, both FAWE and P2 commands will produce ghost blocks.
4) Our conclusion is that the ghost blocks are coming from FAWE and further testing is needed.

So I'll go ahead and close this thread since it's not P2 related and I'll resurrect my old thread in the FAWE 1.12.2 github (if I can find it).

**Comment by meteovio** [comment]
Hi @braceyourself07; Did you ever get around this bug? I cannot find reference for the old thread you are talking about in the other github and I'm experiencing a very similar problem using both PlotSquared and FAWE.

I happen to be using 1.8.9, which is worrying cause you are using 1.12 and still encounter this bug.
I'd love to hear back if you fixed it for yourself.
Thanks

**Comment by AeSix** [comment]
@meteovio you're replying to a closed issue ticket that is over a year old, for a version of minecraft that is no longer supported.  Just a heads up.

**Comment by meteovio** [comment]
@AeSix I'm aware, unfortunately I have no workaround except fixing the bug itself, so contacting @braceyourself07 is my only luck here, as I can't seem to be able to message him anywhere else.

**Comment by braceyourself07** [comment]
> Hi @braceyourself07; Did you ever get around this bug? I cannot find reference for the old thread you are talking about in the other github and I'm experiencing a very similar problem using both PlotSquared and FAWE.
> 
> I happen to be using 1.8.9, which is worrying cause you are using 1.12 and still encounter this bug.
> Unlike you though, I'm able to consistently reproduce the bug on a plot, by filling it with water using FAWE, and then building on the water. The ghost block will instantly place in every relative chunk and disconnnecting/reconnecting or reloading the chunks will show the blocks and they are permanent.
> 
> (for reference: https://i.imgur.com/Vuejx62.jpg)
> I'd love to hear back if you fixed it for yourself.
> Thanks

Hey I am sorry to say this is still an issue. I've worked with a number of devs including Jesse and dordser even offering a $500 USD bug bounty to anyone who could fix it but no success. I assume it has to do with how chunks are sent to the client. 

I've never encountered this issue with 1.13 and higher, so it will eventually be a self solving problem. However my server is remaining on 1.12.2 because of the issues surrounding FAWE ever since the changes incorporated in 1.13.

So yeah we just deal with it.

**Comment by meteovio** [comment]
@braceyourself07 Many thanks for taking the time to answer <3
It was a hopeless shot, but it worked out. 

I'll just drop PlotSquared altogether and use something else, I can't seem to wrap my mind around this bug either and since it's consistent in my case, I just cannot afford to deal with it. It's too bad cause P2 was a really neat plugin.

Well, thanks Java, but mostly thank you for reaching back.
