### ISSUE TITLE
All of a sudden Endless errors

### ISSUE THREAD

**Issue by x1p** [IntellectualSites/PlotSquared#2267]
# Bug report template 

**Debug paste link:** 

https://incendo.org/paste/view/3f0286c862fa4427bb1b4c5a39637a08
PlotSquared-19.2.7-b39ea1b-150

**Description of the problem:** 
https://pastebin.com/beiLHbmp
And this `java.lang.ClassCastException` error continues endlessly every second until restart. It stops after about 64 minutes. (That is roughly 4100 lines of errors)

**How to replicate:** 
wish I knew. No plot action was performed before this happened.

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
Try without AsyncWorldEdit & Multiverse.
I only get this when using non-WorldEdit 7 betas. 

And MV has issues w/ P2 & 1.13.  You can use P2 to handle multiple *plot* worlds, otherwise remove mv *for testing*

**Comment by x1p** [comment]
Other plugins, like CMI won't recognize a jail made in a non existent "plot" world. I'm afraid this wil be a challenge.
As far as AWE: you are right: this is not entirely stable. But no WE/Plot commands were executed before this happened.

**Comment by dordsor21** [comment]
Try using the latest build

**Comment by x1p** [comment]
I hope so. It's probably not so easy to replicate.
If it occurs again, I'll let it know.
I'll close this for now.
