### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by TheDutchMC04** [IntellectualSites/PlotSquared#2268]
# Bug report template 

**Debug paste link:** 

**Description of the problem:** 
Getting NullPointerException: https://pastebin.com/bUczbmAf

**Checklist**:

- [x] I included a `/plot debugpaste` link: https://incendo.org/paste/view/a2a94a91dfb3429593fd4f50833014a8
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Can you please fill out the template given?

**Comment by TheDutchMC04** [comment]
The /plot debugpaste command failed earleier, it works now: https://incendo.org/paste/view/a2a94a91dfb3429593fd4f50833014a8

**Comment by N0tMyFaultOG** [comment]
Try [updating](https://ci.athion.net/job/PlotSquared-Breaking/lastSuccessfulBuild/artifact/target/PlotSquared-Bukkit-4.152.jar) p2, you are ~20 version behind

**Comment by TheDutchMC04** [comment]
that fixed it. thanks!
