### ISSUE TITLE
PlotSquare wont work

### ISSUE THREAD

**Issue by Cobzer** [IntellectualSites/PlotSquared#2270]
I got World edit 7, whish was said in a youtube video, was required in order to make this plugin to work.

Had some trouble in that the plotSquare didn't read my commands. and now, it only work half. 

When i type: /plot setup it says: usage /plot setup <value>

When I try to do /plot setup PlotSquare -> An internal error occurred while attemping to peform this command.

What should happen, is that the plugins should ask me questions in order to setup a new world, with plots.

What I am doing wrong? 

And now, now action is taken in chat, when typing the commands.

**Comment by N0tMyFaultOG** [comment]
Can you please fill out the template given?

**Comment by N0tMyFaultOG** [comment]
Issue solved on discord.
