### ISSUE TITLE
Plotsquared Placeholder Issue

### ISSUE THREAD

**Issue by BlackestSheap** [IntellectualSites/PlotSquared#2272]
Hello and have a nice day dear dev, 

Linking the Plotsquared Placeholder via PlaceholderAPI the placeholder %currentplot% is showing Alphabet Spaghetti When standing on Roads and unoccupied Plots. 

Example 

Leaving the Plot from Player Minecrafter123 to Roads and Free Plots the Placeholder Outputs a very messy 
Feedback like „rafter123“ until the Player Enters the next occupied Plot. 

Hope you can fix that. 
Greetings,

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by N0tMyFaultOG** [comment]
PlaceholderAPI is a third party plugin, if they offer PlotSquared placeholders, they are responsible for them.
Unfortunately their author is currently busy with irl stuff so it won't be updated that soon.
