### ISSUE TITLE
Creating a plot world with a schematic for all plots

### ISSUE THREAD

**Issue by LeoPotter** [IntellectualSites/PlotSquared#2274]
Hi, emh okay I know it's strange but I already created anothers posts for this thing but I can't do it, I created others posts for the creation of a plot world with the same schematic for all plots, people sent me plotsquared wiki pages links where this thing it's explained, but after one million of attempts still I can't do it. So, can someone tell me exactly what I have to do? Thanks.

**Comment by MattBDev** [comment]
https://github.com/IntellectualSites/PlotSquared/wiki/Schematic-Generation
