### ISSUE TITLE
The removal of stands in other people's rafts

### ISSUE THREAD

**Issue by Sanyasp** [IntellectualSites/PlotSquared#2275]
Not so long ago fixed a bug with the removal of stands with the help of salute and elite. But the thing is, it's still possible if you do this operation outside the raft. Then the stands closest to the raft boundaries are removed.

https://github.com/IntellectualSites/PlotSquared/issues/1751

Tried the latest version of the plugin, the problem is relevant. If necessary, I will send a video playback bug.

**Comment by MattBDev** [comment]
Can you please send a video showing the issue because I have no idea what you are talking about.

**Comment by Sanyasp** [comment]
> Can you please send a video showing the issue because I have no idea what you are talking about.

https://youtu.be/bmco6wbc0cw

**Comment by AeSix** [comment]
Apparently fireworks destroy armor stands in plots when the explosion happens in the road, presumably from a user not added/trusted to the plot where the stands are located.
