### ISSUE TITLE
Merged plots should complete plot walls (very low priority 

### ISSUE THREAD

**Issue by Dad3** [IntellectualSites/PlotSquared#2276]
This is not a bug, but just a small thing that kills my ocd
http://prntscr.com/mob9y1
when merging plots, there are a few blocks in the walls under the middle plot road that remain, and I think they should be turned into the plot walls block. 
please ignore this issue for now because it isn't important

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
Which P2 version? (Legacy or 1.13 - that seems like an interesting bug with road schematics)

**Comment by Dad3** [comment]
I am using 1.12.2 I am sure this also happens on 1.13 if no one reported it
