### ISSUE TITLE
Errors about the inability to search the world

### ISSUE THREAD

**Issue by 2032704270** [IntellectualSites/PlotSquared#2278]
minecraft Version 1.7.10 and plotsquared version Bukkit-19.02.13-3646492-691.

Suddenly found plot world can not be searched. You must use Multiverse-Core plug-in to uninstall and reload plot world to work properly. Otherwise, plotsquarered plug-in will not detect plot world. Instructions such as input / PS h will show that your search query has not found the land.No error message was found.

Here is the background information for reloading plot maps。

> mv unload dp
> [10:23:32 INFO]: [Multiverse-Core] World 'dp' was unloaded from memory.
> [10:23:32 INFO]: Unloading dimension 6
> [10:23:32 INFO]: [Multiverse-Core] World 'dp' was unloaded from memory.
> [10:23:32 INFO]: CONSOLE: Uninstall the world 'dp'!
> mv load dp
> [10:23:36 INFO]: Loading dimension 6 (dp) (net.minecraft.server.dedicated.DedicatedServer@55b8d30b)
> [10:23:36 INFO]: [P2] Detected world load for 'dp'
> [10:23:36 INFO]: [P2]  - generator: PlotSquared>PlotSquared
> [10:23:36 INFO]: [P2]  - plotworld: com.intellectualcrafters.plot.generator.HybridPlotWorld
> [10:23:36 INFO]: [P2]  - manager: com.intellectualcrafters.plot.generator.HybridPlotManager
> [10:23:36 INFO]: [P2]  - schematic: false
> [10:23:36 WARN]: Project Zulu : Death Rules are DISABLED.
> [10:23:36 INFO]: Adding world access to world net.minecraft.world.WorldServerMulti@1efb9c19
> [10:23:36 INFO]: GroupManager - INFO - New world detected...
> [10:23:36 INFO]: GroupManager - INFO - Creating data for: dp
> [10:23:36 INFO]: GroupManager - INFO - Don't forget to configure/mirror this world in config.yml.
> [10:23:36 INFO]: World possibly already loaded: dp
> [10:23:36 INFO]: Preparing start region for level 7 (Dimension: 6, Seed: 7062011517208174137)
> [10:23:36 INFO]: CONSOLE: Loaded World 'dp'!

The following is the worlds.yml configuration file

worlds:
  dp:
    plot:
      height: 64
      size: 100
      filling:
      - '1:0'
      floor:
      - '80:0'
      bedrock: true
      biome: FOREST
      auto_merge: true
      create_signs: true
    wall:
      block: '44:0'
      block_claimed: '44:7'
      filling: '155:1'
      height: 64
    road:
      width: 13
      height: 64
      block: '155:1'
    misc_spawn_unowned: false
    home:
      nonmembers: side
      default: side
    schematic:
      specify_on_claim: false
      on_claim: false
      file: 'null'
      schematics: []
    economy:
      prices:
        merge: 100
        sell: 100
        claim: 100
      use: false
    chat:
      enabled: false
    limits:
      max-members: 128
    world:
      max_height: 256
      gamemode: creative
      min_height: 1
      border: false
    event:
      spawn:
        egg: true
        breeding: false
        custom: true
    natural_mob_spawning: false
    mob_spawner_spawning: false
    flags: {}

**Comment by MattBDev** [comment]
You are running an old server likely with a lot of old plugins. Since 1.7.10 is 5 years old we will not offer support for that version beyond an occasional patch when we find a bug that can be backported.
