### ISSUE TITLE
1.12.2 bug> Random warns with /plot home

### ISSUE THREAD

**Issue by Dad3** [IntellectualSites/PlotSquared#2281]
**Debug paste link:** 
https://incendo.org/paste/view/25e2bef9c67744cab15ef70592ba8661
**Description of the problem:** 
Sometimes when players do /plot home, or when I do other commands like /plot claim, usually 1/20th of the time it gives them an error in chat and in console. 
 Error in console: http://prntscr.com/mpd3hh
this is player's error in chat http://prntscr.com/mp2xbu (doesnt execute the command, and then they type it again and its fine usually)
Here the error occurred in older version of plotsquared (still 1.12.2) https://pastebin.com/BJ6rU5Pr
**How to replicate:** 
I am not too sure how to replicate because I've only experienced this bug on my server. I guess at random times a command doesn't execute and sends that error, hopefully the error is enough info.
**Checklist**:

- [X] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
Thanks for the report and providing detailed information. I'll take a look at this soon.

**Comment by Dad3** [comment]
Here is the same error that occured randomly on /plot claim command.
https://pastebin.com/rX2D5CT1
It claims the plot, but does not change the border of the plot or tp you to the plot. No error in chat, just console warn

**Comment by Dad3** [comment]
random error on /plot swap command:
console: http://prntscr.com/mu0231
chat: http://prntscr.com/mu02hr "[P2] An error occured %s"

**Comment by dordsor21** [comment]
The "%s" in "[P2] An error occurred %s" is due to there being to error message to replace the %s with. I don't see that there's much need to change the behaviour if you now know what it means. With regards to the numerous NPEs you seem to get, I've not noticed this from anywhere else, and there should be absolutely no reason for them from what I can see in the code, unless you've got a partial-plot world and maybe you're claiming a plot at the edge of it?

**Comment by MattBDev** [comment]
I modified the behavior of one of the getRegions() method in the Plot class to always return something instead of being null. The errors should stop but I am not sure what the new resulting behavior would be.
