### ISSUE TITLE
Player Events

### ISSUE THREAD

**Issue by DesperoKF** [IntellectualSites/PlotSquared#2283]
DEBUG LINK:
https://incendo.org/paste/view/02b146c6c6e24887bdd1beab6904df2b
I code a little bit for the PlotSquared API a Fly Perk in the own Plot.

Now I have the problem that if I trust or add a player on the plot, he can not fly. Although he has rights with the code to fly.

I test it with this

if (e.getPlot().getTrusted().contains(uuid)
                    || e.getPlot().isAdded(uuid))  {
 e.getPlayer().sendMessage("I am trusted/added")
}

but dont works. No Message onEnter or onLeave the Plot

https://pastebin.com/V9HH4nNd

**Comment by DesperoKF** [comment]
I have check my Code and i found the problem.:

**Comment by AeSix** [comment]
Since you've resolved the issue, please close the ticket
