### ISSUE TITLE
Console spam (Plot je null)

### ISSUE THREAD

**Issue by Sikatsu** [IntellectualSites/PlotSquared#2284]
**Debug paste link:** 
https://incendo.org/paste/view/b6d55dff8dc740c78308812efb398101

**Description of the problem:** 
The console keeps saying ''Plot je null'' every now and then.  (Looks like it's using a translation?)

https://pastebin.com/rsKdwQTX

This occurs since a commit later then 27th of January.

**How to replicate:** 
I am not sure how to replicate or which information I could provide further.

The world and files are generated on 1.12.2, but the plugin is up-to-date with the latest commit.

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
I don't think that's p2 debug, as it does not have the P2 prefix/etc. Do any other plugins use "plots" or are linked with P2?

**Comment by Sikatsu** [comment]
Not sure why it doesn't show a prefix, but it doesn't with any plugin. Another developer mentioned the same a while back. I don't have any plugins that use plots or are linked to plotsquared.

**Comment by AeSix** [comment]
probably an artifact of world conversion.

Try running paper with  --forceUpgrade

**Comment by Sikatsu** [comment]
And without paper?

**Comment by AeSix** [comment]
Spigot & offshoots have force upgrade.

Give it as much ram as you can spare. 
```java -Xmx20G -Xms1G -Xmn512M -jar server.jar --forceUpgrade```
replace components as needed.

*** assuming your last q was regarding this :)

**Comment by Sikatsu** [comment]
Unfortunatly it's not on a dedicated server. I'm hosting at AnvilNode. Would also like to mention this error was not there on builds before 27th of January and rolling back the spam no longer shows either.

**Comment by AeSix** [comment]
Contact AnvilNode and ask them to give you an up-to-date dev build.  See if it's resolved in newer builds as well.  If it is resolved, then the ticket can be closed.  If it's not, generate a new debugpaste with it for the devs :)

**Comment by Sikatsu** [comment]
Up-to-date devbuild? From spigot? I build it myself and it's only 6 versions behind.

**Comment by AeSix** [comment]
No, P2

**Comment by Sikatsu** [comment]
Well, using the latest breaking branch update doesn't have it fixed

**Comment by AeSix** [comment]
Try updating the rest of your plugins.
I know CoreProtect, you're on 2.15.x, but 2.16 has been released for MC 1.13.  I'm not going through each plugin for you :)

**Comment by Sikatsu** [comment]
I appreciate your help, but I update my plugins nearly every night. I've participated in the coreprotect beta's and updated to the final as soon as possible.

Using a build older then 27th of January the issue isn't here aswell. Only newer versions of plotquared this random spam pops up.

**Comment by MattBDev** [comment]
I just did a search through the project files and there is no message that contains "je null" or any close matching english translations. Do you have any plugins that you know work with plotsquared? it's likely one of those is causing the issue. I did notice that whenever your players are using `/vote` or `/warp vote` the message starts popping up.

**Comment by AeSix** [comment]
And does this continue when plugins/PlotSquared/config/settings.yml > debug: false is set?

**Comment by Sikatsu** [comment]
I think the ''je'' is dutch perhaps, since i'm running a dutch server. 
But I can't find any plugin which has ''plot je null''.

I don't have any plugins using plotsquared. Is there a plugin to find out from which plugin the string is?

**Comment by AeSix** [comment]
If any of the string is a parsed variable, you won't find the full string. 

Did you try setting debug to false in your settings.yml?

**Comment by AeSix** [comment]
@Sikatsu is this still an issue with newer builds? (184+)
And is this still an issue if you disable PlotSquare debug, as I suggested in a previous reply?

**Comment by Sikatsu** [comment]
It is still an issue with the newer builds, and setting debug to false did not solve it, sadly.

**Comment by AeSix** [comment]
can you give me the url for a /timings paste please

**Comment by Sikatsu** [comment]
From this morning: 

https://timings.spigotmc.org/?url=xehaxarohu

Also the spam went crazy a couple of days ago: https://pastebin.com/iyTaWLYV

**Comment by MattBDev** [comment]
You need to go through your plugins one by one and make sure this is PlotSquared spamming this message. I am confident it isn't and I want to close this issue.

**Comment by Sauilitired** [comment]
I'll assume this isn't a PlotSquared issue. If you can confirm this is, then please re-open.

**Comment by wasder** [comment]
It was BuildBattle's spam.
https://www.spigotmc.org/resources/weekend-sale-%E2%AD%90pro%E2%AD%90-buildbattle-1-8-8-1-14-x-unique-building-gamemode.49587/update?update=269490
