### ISSUE TITLE
road regen problems 1.13.2

### ISSUE THREAD

**Issue by jerzean** [IntellectualSites/PlotSquared#2286]
https://incendo.org/paste/view/4d33adb652bd48e2b23549e0b1fdb869
using these plugins
https://gyazo.com/1c3041b6a6dc57fcaf94d04e64a29456

tried to regen the roads but failed  and creating the road schem fails aswell
 console command (/plot regenallroads) throws unknown command

**Comment by Dad3** [comment]
You're using older version of plotsquared, also recommended to switch to PaperMC, also if you have any more issues just join the discord.

**Comment by dordsor21** [comment]
Could we see a screenshot of the road you're trying to use & your startup log?

**Comment by jerzean** [comment]
that is the latest release on spigot   the download  button takes me here 
[https://ci.athion.net/job/PlotSquared-Breaking/](url)
im using the latest build from there

schem with the roads i was trying to use
[Creative.zip](https://github.com/IntellectualSites/PlotSquared/files/2921528/Creative.zip)

**Comment by AeSix** [comment]
Using P2 4.179 and WorldEdit 7 Beta 5, I was able to properly regen my roads:
https://incendo.org/paste/view/ab1cb8384dd44e429ed5e0159259fc16

**Comment by MattBDev** [comment]
Looks like this isn't an issue but I'll reopen it if needed.
