### ISSUE TITLE
/p delete and /plot delete dont work

### ISSUE THREAD

**Issue by ImOnlyALittleArtistic** [IntellectualSites/PlotSquared#2287]
# Bug report template 

**Debug paste link:** 

https://incendo.org/paste/view/7ccca5e352b04fe6946d400ff98b61e0
**Description of the problem:** 
Can not delete plots once claimed.

**How to replicate:** 

I dont think i can reproduce this issue.
**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
Sponge is not actively maintained. This issue will be merged with #1814. Feel free to contribute to the project if you need support for sponge.
