### ISSUE TITLE
Feature to specifically designate a world as non plot?

### ISSUE THREAD

**Issue by semmeess** [IntellectualSites/PlotSquared#2292]
Spigot version 1.8.8. plugin version PlotSquared-Bukkit-19.02.05-d27ead5-688.
I have one world with its generator set to plotsquared, which functions just fine as a plot world. I have worldedit and fast async worldedit installed, with the correct settings such that players can use worldedit only in their plots/trusted plots. All is well.

I've allowed world_the_end to generate, with no custom generator specified. I've given a group of players ownership of worldguards __global__ region within it, however they cannot use worldedit in the world, as they're 'not in their own plot'.

Is there any way around this? 

Otherwise: new feature request, allow a world to be totally ignored by plotsquared, such that players could use worldedit in a whole world.

**Comment by AeSix** [comment]
This sounds like a config issue.  give us a /p debugpaste

**Comment by semmeess** [comment]
https://incendo.org/paste/view/d7eea24296244a08a2e2111c89d2f997

There you go, thanks!

**Comment by AeSix** [comment]
Do you have WorldGuard in your FAWE config?

I believe that needs to be.  
Other than that, I'm confused - but this could be an issue with such an old version of Minecraft.

**Comment by semmeess** [comment]
Thanks, I'll try that.
https://i.imgur.com/axxE7cQ.png
Do you mean here?

**Comment by AeSix** [comment]
That'd be the place. lol
Yeah, I don't know.  We'll have to wait for someone smarter than me to help.  Sorry :(

**Comment by semmeess** [comment]
That's fine bro, thanks for helping!
