### ISSUE TITLE
How to set "auto-clear" to remove ONLY COMPLETELY empty rafts?

### ISSUE THREAD

**Issue by Sanyasp** [IntellectualSites/PlotSquared#2293]
Sorry please, if such question already was, I unfortunately not found. And it seems as here it is possible not only to write reports, but also to ask questions. Even such elementary (probably, heh).

How to" auto-clear " to configure so that rafts were removed only those that are completely empty? Not having not one block.

**Comment by dordsor21** [comment]
See https://github.com/IntellectualSites/PlotSquared/wiki/Plot-analysis if you set the mean number of changes per column to zero and the other numbers to what they would be given what your plot's unchanged state is, then it ought to work.
