### ISSUE TITLE
Skywelt

### ISSUE THREAD

**Issue by Bluecube88** [IntellectualSites/PlotSquared#2294]
Hallo Zusammen, wie kann ich bei PlotSquared eine Skywelt erstellen??

**Comment by dordsor21** [comment]
We'll need more information, but I don't think P2 is the correct plugin for what you're wanting to achieve

**Comment by AeSix** [comment]
No, P2 is not good for skyblock, but you can create plots with air for walls, plot, roads, etc. But you won't get any of the stuff a skyworld plugin gives you. Check out IslandWorld.

Nein, P2 ist nicht gut für Skyblock, aber Sie können Plots mit Air für Wände, Plot, Straßen usw. erstellen. Besuche IslandWorld.
