### ISSUE TITLE
Use flag not working

### ISSUE THREAD

**Issue by psrcek** [IntellectualSites/PlotSquared#2296]
# Use flag not working

**Debug paste link:** 
https://incendo.org/paste/view/1980ef1977614851baf22ee0656c42cf

**Description of the problem:** 
The use flag does not work. I cannot use buttons, levers or pressure plates on other people's plots. The main problem I am trying to fix is that users can interact with repeaters on other people's plots, we do not want that.

**How to replicate:** 

set the use flag of a plot or world to:
"64,71,96,167,193,194,195,196,197,77,143,69,70,72,147,148,107,183,184,185,186,187,132"

**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
Why are you using legacy block ids on a 1.13 server?

**Comment by AeSix** [comment]
You need to convert all item id numbers to item strings, @psrcek 
You can find a list of all of the items for 1.13 here:
https://minecraftitemids.com/

Alternatively, you can take your chances with this:
https://www.spigotmc.org/resources/id-converter.52099/
Phoenix616 is a trusted developer in the Minecraft community.

**Comment by psrcek** [comment]
Okay... Why is this not mentioned anywhere in the documentation? In fact the example there leads me to conclude using ids is recommended. [link](https://github.com/IntellectualSites/PlotSquared/wiki/Usage:-Plot-flags#default-flags) It's even stated that both ids and item strings are supported [here](https://github.com/IntellectualSites/PlotSquared/wiki/Usage:-Plot-flags#--blocklist) :rofl:

**Comment by AeSix** [comment]
Because it is well documented by Mojang, Spigot, and a hundred other places that 1.13 changed from Item ID numbers to item strings.  This is not something that affects only PlotSquared and is something you will need to fix for ALL of your plugins - worldedit, worldguard, logblock, coreprotect, etc.  Some plugins handle it internally, and some rely on the operator to understand that 1.13 has changes and that it is the operators responsibility to ensure that all of his configs are updated and working properly with 1.13+

**Comment by RedstoneFuture** [comment]
@psrcek Right. We will update the wiki If we have time. :)

**Comment by AeSix** [comment]
I've confirmed that in 1.13.2 with P2 4.184, the use flags are working correctly when using item names. 

ADDITIONALLY:
I have added a notification to both the wiki front page and to the Default flags section telling users that 1.13 requires Item ID Names now.  I added a link to an item id list for manual conversion, as most of the sites I checked do not have all of the numbers available, or do not have the 1.13 names associated.  With this, I duplicated the example flag config section and updated with some of the names. 

This ticket can be closed on both accounts (the use flags not working, as it was not an issue; and the notification of changes for users in the wiki)

**Comment by Sauilitired** [comment]
While yes, it is highly recommend that you move to string based material names, legacy IDs should work. We implemented a system that would internally convert these IDs, but it seems that it fails when it comes to flags. Thanks for reporting the issue. We'll try to resolve it as soon as possible.
