### ISSUE TITLE
Plot unlink

### ISSUE THREAD

**Issue by Huntermaster0** [IntellectualSites/PlotSquared#2298]
I want to cut off 1 plot from my mega plot (12 plot), but as I know it's impossible, if I try this the whole thing get unlinked. Please, can you solve this issue?

**Comment by dordsor21** [comment]
That is not currently supported. If doing so makes you lose build, then you can use WE to copy then paste it back/etc.

**Comment by Huntermaster0** [comment]
Okay, but will it be supperted later?

**Comment by AeSix** [comment]
As the question was answered and the issue closed, I would suggest going over to the feature request issue tracker and check for a similar feature request before putting in your own, @Huntermaster0

**Comment by Huntermaster0** [comment]
This?
https://github.com/IntellectualSites/PlotSquaredSuggestions

**Comment by AeSix** [comment]
Yes.
