### ISSUE TITLE
/plot buy Funktioniert nicht

### ISSUE THREAD

**Issue by Bluecube88** [IntellectualSites/PlotSquared#2300]
Hallo Zusammen, habe da ein kleines Problem.

Ich habe erfolgreich eine Plotwelt erstellt. Mit dem befehll /plot auto kann man sich grundstücke kaufen, aber mit /plot buy kommt da immer:

**The Current plot must have an owner to perform this action**

Permiss. sind vergeben und alle andere gehen ohne Probleme.

Liebe grüße
Michael

**Comment by AeSix** [comment]
Hello everybody, I have a little problem.

I have successfully created a plot world. With the infestation / plot you can buy land, but with / buy plot comes there always:

The current diagram must have an owner to perform this action

Permiss. are forgiven and all go without problems.

Best regards
Michael
---------------------------------------------------------

https://github.com/IntellectualSites/PlotSquared/wiki/Commands-and-Permissions

Please ensure all permissions are correctly assigned

**Comment by Bluecube88** [comment]
- plots.permpack.basic
    - plots.list
    - plots.clear
    - plots.home
    - plots.auto
    - plots.claim
    - plots.info
    - plots.buy
    - plots.plot.4
    - plots.use

**Comment by Bluecube88** [comment]
Pls Closed Thx
