### ISSUE TITLE
[15:54:28 ERROR]: Could not pass event EntityChangeBlockEvent to PlotSquared v4.187

### ISSUE THREAD

**Issue by SushiKarasumori** [IntellectualSites/PlotSquared#2301]
**Debug paste link:** 
https://pastebin.com/egVeRWWx

**Description of the problem:** 
**Plugin List:**
- DeluxeChat-1.13.2
- DeluxeMenus-1.10.5
- DummyFawe
- EssentialsX-2.16.1.0
- EssentialsXGeoIP-2.16.1.0
- FastAsyncWorldEdit-bukkit-1.13.135
- MessageAnnouncer-1.9.1
- PermissionsEx-1.23.4
- PlaceholderAPI-2.9.2
- PlotSquared-Bukkit-4.187
- Vault

When running Plot² with Vault on CraftBukkit version git-Spigot-cf694d8-5259d80 (MC: 1.13.2), only Vault appears to load, and when Plot² is ran by itself no plugins appear.

**How to replicate:** 
You can get the console spam by running Plot² with other plugins, it loads but will not work.
You can stop Plot² from loading by placing it by itself in the plugins directory.

**Checklist**:
- [*] I included a `/plot debugpaste` link
- [*] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [*] I made sure I am using an up-to-date version of PlotSquared.
- [*] I Made sure the bug/error is not caused by any other plugin. The plugin only loads with other plugins, and it doesn't load at all when it is by itself.

**Comment by N0tMyFaultOG** [comment]
Remove Fawe/DummyFawe and use [regular WorldEdit](https://dev.bukkit.org/projects/worldedit/files/2663452/download) for the time being FAWE is in the update process.

**Comment by MattBDev** [comment]
FAWE is not compatible with PlotSquared at the moment. Use Worldedit
