### ISSUE TITLE
Error with worldguard-legacy-7.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by Renezoros** [IntellectualSites/PlotSquared#2304]
19.03 14:33:06 [Server] ERROR Could not pass event PlayerJoinEvent to PlotSquared v4.189
19.03 14:33:06 [Server] INFO org.bukkit.event.EventException: null
19.03 14:33:06 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-8b1588e]
19.03 14:33:06 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-8b1588e]
19.03 14:33:06 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-8b1588e]
19.03 14:33:06 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-8b1588e]
19.03 14:33:06 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerList.onPlayerJoin(PlayerList.java:343) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-8b1588e]
19.03 14:33:06 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:162) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-8b1588e]
19.03 14:33:06 [Server] INFO at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:149) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-8b1588e]
19.03 14:33:06 [Server] INFO at net.minecraft.server.v1_13_R2.LoginListener.tick(LoginListener.java:53) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-8b1588e]
19.03 14:33:06 [Server] INFO at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:230) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-8b1588e]
19.03 14:33:06 [Server] INFO at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:119) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-8b1588e]
19.03 14:33:06 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:994) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-8b1588e]
19.03 14:33:06 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-8b1588e]
19.03 14:33:06 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-8b1588e]
19.03 14:33:06 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-3cb9dcb-8b1588e]
19.03 14:33:06 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
19.03 14:33:06 [Server] INFO Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldedit/math/BlockVector3
19.03 14:33:06 [Server] INFO at com.github.intellectualsites.plotsquared.plot.object.Location.<init>(Location.java:26) ~[?:?]
19.03 14:33:06 [Server] INFO at com.github.intellectualsites.plotsquared.bukkit.util.BukkitUtil.getLocationFull(BukkitUtil.java:232) ~[?:?]
19.03 14:33:06 [Server] INFO at com.github.intellectualsites.plotsquared.bukkit.object.BukkitPlayer.getLocationFull(BukkitPlayer.java:190) ~[?:?]
19.03 14:33:06 [Server] INFO at com.github.intellectualsites.plotsquared.plot.object.PlotPlayer.getLocation(PlotPlayer.java:306) ~[?:?]
19.03 14:33:06 [Server] INFO at com.github.intellectualsites.plotsquared.bukkit.object.BukkitPlayer.getLocation(BukkitPlayer.java:53) ~[?:?]
19.03 14:33:06 [Server] INFO at com.github.intellectualsites.plotsquared.bukkit.listeners.PlayerEvents.onConnect(PlayerEvents.java:617) ~[?:?]
19.03 14:33:06 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
19.03 14:33:06 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
19.03 14:33:06 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
19.03 14:33:06 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
19.03 14:33:06 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot-1.13.2.jar:git-Spigot-3cb9dcb-8b1588e]

**Comment by MattBDev** [comment]
1. Don't delete the template.
2. This is not a PlotSquared issue you have the wrong version of WorldEdit installed.
3. I'm closing this.
