### ISSUE TITLE
plot unlink does not regen road between plots

### ISSUE THREAD

**Issue by AeSix** [IntellectualSites/PlotSquared#2306]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support.*__
# Bug report template 

**Debug paste link:** 
 
 https://incendo.org/paste/view/4bd52e2e771244558d6887badbbd472f
**Description of the problem:** NOTE: This *may* be related to using FAWE-NVS 165.
I had two plots merged for a while.  I was going to test /plot setowner none, and wanted to use only one of the pair of plots.  I unlinked the plots, however the road was not generated between the two plots.
https://puu.sh/D3gkz/6bf119ddaa.png

**How to replicate:** 
 Merge two plots.  Unlink merged plots. Witness as all of your hopes and dreams fall and shatter on the bedrock below.

I re-merged the plots and unlinked them again, with the same result. 
**Checklist**:

- [x] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [!] I Made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
We thought you wanted the road completely gone!  Your telling us you didn't want a giant hole where your road was?  You're asking for too much.

**Comment by Sauilitired** [comment]
Cannot replicate using WorldEdit 7. Will test with FAWE-NVS

**Comment by Sauilitired** [comment]
Cannot replicate with latest FAWE either :cow:

**Comment by RedstoneFuture** [comment]
![2019-04-25_18 43 29](https://user-images.githubusercontent.com/4140635/56753095-1a8b5f00-678a-11e9-80bd-6c918bd4e7d2.png)


Maybe the same problem:

1. Claim two plots in a north-south direction
2. Merge this plots.
3. Go to the south-directed plot and use "/p delete"


tested with FAWE 19.4.23-c6ce0c7-13 and PlotSquared-19.4.6-5d515b3-221


(I would like send a debud report but I get a timeout on my local server  ^^ )

**Comment by TNTUP** [comment]
Same issue here, deleted a 4-plot and the road didn't regen properly. Using Worldedit 7.0.0-SNAPSHOT on Paper 1.13.2. I don't use FAWE.

**Comment by AeSix** [comment]
@TNTUP Try using WorldEdit 7 beta 5 instead of the snapshots.  Also, use WorldGuard 7 beta 3 to ensure it works right with WE7b5... if you're using WG that is.

WHat build of P2 are you using?  
/p version

**Comment by TNTUP** [comment]
@AeSix I prefer running from snapshots rather than beta ones, always using them since 1.12.2 and no issues whatsoever :/ but on 1.13.2 I guess I'll be forced to use beta for the meantime WE stabilizes with 1.13.2. Thanks for answer, will try the beta one^^

**Comment by AeSix** [comment]
FYI, Betas are, in most of the world of programming, more stable than snapshots.

**Comment by AeSix** [comment]
CLosing this ticket as a duplicate of https://github.com/IntellectualSites/PlotSquared/issues/2375
(even though this is the older ticket, the newer one has more apt information)
