### ISSUE TITLE
PlotSquard Delete Plot and walls dissapear 

### ISSUE THREAD

**Issue by Golicraft** [IntellectualSites/PlotSquared#2307]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support.*__
# Bug report template 

**Debug paste link:** 

Won't send because of private plugin list
**Description of the problem:** 
So if I do /plot delete the plot deletes but the wall block that is slab won't show. 

**How to replicate:** 

Just do /plot delete on a plot and check if the wall slab block is there or not
**Checklist**:

- [] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

I got asked to report this even it isn't so important for me because it won't be fixed (im using spigot 1.12) so in the Legacy version this won't be added..

Here's a gyazo GIF showing the conversation I had with one of the devs. 
https://gyazo.com/4c9d33d204fa0eecfaae48e39c272776

Sorry for not following all the steps but I need to go like really soon. Have a nice day PlotSquard Devs tho and thanks for creating this wonderful plugin.

**Comment by AeSix** [comment]
Where;s the debugpaste?

**Comment by Golicraft** [comment]
But I don't want to share my plugin list to the public.

**Comment by AeSix** [comment]
Then do as I said and give all the info it would otherwise provide.

I had no issue with spigot or paper 1.12.2 or 1.13.2 with this - so you're either using a broken p2, or one of your plugins is interfering.

You could duplicate your server, remove all non-pertanent plugins & test. If you still have the issue, the since your plugins aren't loaded, you can safely do a debugpaste

**Comment by Golicraft** [comment]
Alright I can send a debugpaste sorry :c 
https://incendo.org/paste/view/39963ebb8acd4c279aac4b8ebb06985a

**Comment by AeSix** [comment]
Ok. Thank you.

You have an NPE in GoliJoin.  It's not causing issues with this (at least, I don't believe it is - but you should look into fixing it)

Can you try reverting back to a build from January and seeing if the issue persists please?

**Comment by MattBDev** [comment]
We haven't heard back in 21 days so I am closing this issue. Please ask to re-open if the issue still persists.
