### ISSUE TITLE
Plot not saving

### ISSUE THREAD

**Issue by Bfs2003** [IntellectualSites/PlotSquared#2309]
Everyday i come to the server to check my plots the same bug happening with me and i fix it everytime i save the plot and the world and the same thing happening to me the blocks removed from the plot Please help
i am using up to date version and my server version is spigot 
![2019-03-24_18 20 19](https://user-images.githubusercontent.com/48887685/54882414-7ba9d500-4e62-11e9-8799-43a453dfc253.png)
1.12.2

**Comment by MattBDev** [comment]
Since you deleted the bug template report, this report will be closed. We do not have enough information to help. Please try to explain your issue better and ask for help on our discord server.
