### ISSUE TITLE
Major performance impact from PlotSquared EntitySpawn Listener (VehicleEntityCollisionEvent)

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/PlotSquared#2313]
Paper dev 599 (Spigot 1.13.2)
PlotSquared-Breaking dev 209
FAWE 1.13 dev 145

![link](https://i.imgur.com/EjgQu9i.png)

Any way to optimize this check or disable it entirely in plots?

Found the assumed plot causing the lag. Assuming lag is from spamming checks since they're all pushing each other.
![link2](https://cdn.discordapp.com/attachments/119102811421147138/563121872321904645/2019-04-03_23.04.53.png)

**Comment by MattBDev** [comment]
Please follow the issue template in the future. The code for that check is all necessary and can't be simplified any further. That many minecarts will cause performance issues because it has collisions triggering more collisions.

**Comment by boy0001** [comment]
It may not be able to be simplified, but it can be optimized. 
I substituted a check on chunk load instead of move/collision. Then all the other checks can return early if it's not the nether.
