### ISSUE TITLE
Import template bridge have error in 1.13.2

### ISSUE THREAD

**Issue by yww999** [IntellectualSites/PlotSquared#2315]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support.*__
# Bug report template 

**Debug paste link:** 

https://incendo.org/paste/view/92c0f665cdf948a19efbf6d8818da803
**Description of the problem:** 
use command plot template import worldtest bridge have error in 1.13.2

**How to replicate:** 

just use use command plot template import worldtest bridge in paper server 1.13.2
**Checklist**:

- [X] I included a `/plot debugpaste` link
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
You provided no information. All you did was tell us you have an error. If you decide to follow the bug report template and share more information I'll reopen this.

**Comment by yww999** [comment]
@MattBDev yes.I'm edited to add debug paste link

**Comment by yww999** [comment]
@MattBDev Please reopen this.

**Comment by MattBDev** [comment]
Fixed by @N0tMyFaultOG
