### ISSUE TITLE
Land consolidation, data loss and road problems

### ISSUE THREAD

**Issue by 2032704270** [IntellectualSites/PlotSquared#2317]
The server side is 1.7.10 and the plug-in version is PlotSquared-Bukkit-19.04.08-200ca51-737.jar.
When MySQL data is converted to SQLite data, the plot information is lost.
![QQ图片20190409181926](https://user-images.githubusercontent.com/47876134/55792842-160d4800-5af4-11e9-9104-30d0100b9a6b.png)

![QQ图片20190409182034](https://user-images.githubusercontent.com/47876134/55792916-3c32e800-5af4-11e9-9db2-80f9971bb58f.jpg)
The merge data is lost, but the player's plot has been merged before. If merged again, the road block will be reset. We hope to add an open/close to decide whether the merged plot resets the road function.
Thank you.

**Comment by MattBDev** [comment]
1.7.10 is no longer supported due to the very small number of users

**Comment by boy0001** [comment]
Already supported, use `/plot merge <direction> false` to merge without changing the roads.
