### ISSUE TITLE
Cannot genorate road schematic (FAWE)

### ISSUE THREAD

**Issue by GNUGradyn** [IntellectualSites/PlotSquared#2318]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support.*__
# Bug report template 

**Debug paste link:** 

https://incendo.org/paste/view/8006f3a538d54c7bbd4db11fc50dc66b
**Description of the problem:** 
Can't generate road schematics, throws error:

> `[22:44:40 INFO]: GNUGradyn issued server command: /plots createroadschematic                                                                                                         [22:44:40 WARN]: com.sk89q.worldedit.regions.CuboidRegion$3$1: End of iterator                                                                                                       [22:44:40 WARN]: com.sk89q.worldedit.regions.CuboidRegion$3$1: End of iterator                                                                                                       [22:44:40 WARN]: [WorldEdit] Plugin WorldEdit vunspecified generated an exception while executing task 72                                                                            java.lang.NullPointerException: null                                                                                                                                                         at com.github.intellectualsites.plotsquared.plot.generator.HybridPlotWorld.setupSchematics(HybridPlotWorld.java:153) ~[?:?]                                                          at com.github.intellectualsites.plotsquared.plot.generator.HybridUtils$3$1.run(HybridUtils.java:252) ~[?:?]                                                                          at com.github.intellectualsites.plotsquared.plot.generator.HybridUtils$3$1.run(HybridUtils.java:247) ~[?:?]                                                                          at com.boydti.fawe.regions.general.plot.FaweSchematicHandler$1.run(FaweSchematicHandler.java:82) ~[?:?]                                                                              at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]                                                        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]                                                                                     at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]`

--

Spigot: 1.13.2
FAWE: unknown (litterally what it says in chat when running /fawe version)
PlotSquared: 19.4.6
Server: Ubuntu server 18.04

**How to replicate:** 

1: Build a fancy road around a plot
2: Issue command /plots createroadschematic
(Possibly related to FAWE?)
**Checklist**:

- [i] I included a `/plot debugpaste` link
- [i] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [i] I made sure I am using an up-to-date version of PlotSquared
- [i] I Made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
1.13.2 requires PlotSquared 4.  
incendo.org/download

You can update FAWE from there as well, I believe "breaking" may give better results than the dev - however, try which ever one you'd like first, and then the other.  There's no release version of FAWE as of yet.  It's still better to use WorldEdit 7 Beta 5, for the time being.

**Comment by MattBDev** [comment]
Already fixed. You need to update PlotSquared
