### ISSUE TITLE
Players Not Able to Build Or Break Stuff

### ISSUE THREAD

**Issue by XnO-Revo** [IntellectualSites/PlotSquared#2323]
Players are not able to build or break stuff on their plots?

What's the permission!

**Comment by N0tMyFaultOG** [comment]
a) Follow the format given if you open an issue
b) Look in the chat, it tells you the node they are lacking

**Comment by XnO-Revo** [comment]
It doesn't... when a player tried to break it nothing is said.. so what are the permissions?!?!?!

**Comment by MattBDev** [comment]
You're not providing information for us to help you. Send us a debugpaste link or I will close this issue in 2 days

**Comment by XnO-Revo** [comment]
...all I'm asking is for the permission to build.

**Comment by XnO-Revo** [comment]
How do I get a "debugpaste" ?

**Comment by AeSix** [comment]
Wiki https://github.com/IntellectualSites/PlotSquared/wiki

all info is here.
