### ISSUE TITLE
PlotSquared "You're not in plot issue"

### ISSUE THREAD

**Issue by AntoanBG** [IntellectualSites/PlotSquared#2324]
When i try to claim a plot it says "You're not in a plot"
debugpaste - https://incendo.org/paste/view/6c96475be036403b9d4db78575a03eba

**Comment by MattBDev** [comment]
PlotSquared is the least of your problems. You have several plugins that are missing dependencies and none of them can establish a link to a database. The database issues with all your other plugins is likely the reason nothing is working.
