### ISSUE TITLE
plugin.yml issue

### ISSUE THREAD

**Issue by OpticFusion1** [IntellectualSites/PlotSquared#2325]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support.*__
# Bug report template 

**Debug paste link:** 

**Description of the problem:** 

**How to replicate:** 

**Checklist**:

- [] I included a `/plot debugpaste` link
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I Made sure the bug/error is not caused by any other plugin

https://github.com/IntellectualSites/PlotSquared/blob/breaking/Bukkit/src/main/resources/plugin.yml

It seems like the following
"  plotme.admin.home.other:
    children:
     plots.plot.: true"
breaks yaml (most likely due to the plot.: bit)
This is due to it trying to set to an empty path.
Although it does not log with spigot (for whatever reason).

**Comment by AeSix** [comment]
@MattBDev perhaps this https://github.com/IntellectualSites/PlotSquared/blob/breaking/Bukkit/src/main/resources/plugin.yml#L256
should be 
```
plots.plot.*: true
```
As many other similar perms end in .*
