### ISSUE TITLE
[1.12] Plugin does not modify blocks (except signs)

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [IntellectualSites/PlotSquared#2326]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support.*__
# Bug report template 

**Debug paste link:** 
https://incendo.org/paste/view/8f1f2f59afe74950891b740126109c16

**Description of the problem:** 
On my Server, PlotSquared does not change any block by merging (road stays), clearing (nothing changes) or even claiming (slabs don´t change).

**How to replicate:** 
Do something that modifies blocks (ex. /plot clear)

**Checklist**:

- [X] I included a `/plot debugpaste` link 
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [ ] I Made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
If nothing is changing then there is an issue with the server setup. Because our debugpaste system is down I will be closing this issue but I encourage you to join our discord server so we can help you further.
