### ISSUE TITLE
The plugin will print class casting exceptions at random times to the console.

### ISSUE THREAD

**Issue by LogalDeveloper** [IntellectualSites/PlotSquared#2328]
# Debug Paste Link
I am not using the plugin's built in debug paste upload command because it uploads too much information, particularly the latest log file with no sensitive information redacted. I have instead manually uploaded what files I think are necessary for this issue. If any additional files are required, please ask and I will be glad to provide it.

https://cloud.logal.dev/s/yZxZFJ0YJ3Iak4N

# Description of the Problem
**(1)** The plugin will at random times start printing out the string `java.lang.ClassCastException` every second.

**(2)** In a recent build of PlotSquared, it will also sometimes randomly print full stack traces of the same type of exception.

Log snippets from our production server showing both of these issues can be found in the debug paste link, named figures 1 & 2.

# How to Replicate the Issue
We currently cannot identify any pattern on how to replicate this issue. We were initially thinking it was caused by running a PlotSquared command, but over time we have observed doing so isn't required.

# Checklist
- [x] I included a `/plot debugpaste` link
  - See the note at the beginning of the issue about this.
- [x] I made sure there are no duplicates of this report.
- [x] I made sure I am using an up-to-date version of PlotSquared.
- [x] I made sure the bug/error is not caused by any other plugin.

**Comment by Pepich** [comment]
@N0tMyFaultOG I am sorry to inform you that we are legally not allowed to run the command you require. Please tell me how I can provide the information requested in a way that I will no longer be required to release data that is considered PII as of GDPR to a third party service, and without changing our ToS and Privacy Policy.
Last but not least (not related directly to this bug, but I could not determine a different place to ask this): @Sauilitired The description of the debug command in the wiki is wrong. We were tricked into uploading user PII to a service that we did not consent to and that our users did not consent to. How can I request immediate deletion of the data on your servers? I could not find a contact email, contact form, or even a privacy policy on the websharing host used, but as it is obviously linked to this project, please indicate how I would go about making sure the illegally obtained/shared information is removed?

**Comment by MattBDev** [comment]
@Pepich you were not tricked. Even if it didn't upload to hastebin like it described, you still needed to execute the command on purpose. Plus if the information was uploaded to hastebin the following privacy statement is provided on their website:
While the contents of hastebin.com are not directly crawled by any search robot that obeys "robots.txt", there should be no great expectation of privacy.  Post things at your own risk. Not responsible for any loss of data or removed pastes.

**Comment by Pepich** [comment]
Sorry, the wording was wrong. We were not tricked, that is correct. Nothing done on your end was illegal, that is also correct. Running the command was a mistake by one of our devs that did put us in a spot where we broke our own privacy policy. We have talked about this on Discord though, and I think it has been resolved, so let's get back to the issue at hand:
How do we provide you with the required information without breaking our own Privacy Policy? Straight up uploading the entire logfile is not an option as this will inevidebly contain tons of userdata, and even PII. We provided you with the snippets where the bug occured, but that appears not to be enough, please tell us what more info you need (installed plugins? Boot sequence logs? JVM dump? ...)
And finally: As the filesharing service used in the plugin doesn't exist anymore, it is now actually not possible anymore to use the debugpaste command to provide you with the necessary info, which alternative would you suggest?

**Comment by Pepich** [comment]
https://redstoner.com/downloads/logs

I have compiled a full set of all relevant logs, stripped all sensitive data from it though. It contains a startup log for all plugin info and versions, a log from one day where roughly 4.5k exceptions of the type mentioned above occured, and it also contains a full jvm dump captured during one of those events. If you need more info let me know.

**Comment by LogalDeveloper** [comment]
Just a heads up on the link Pepich posted in their previous comment: That folder is no longer going to be available due to some host migrations. I have reuploaded the files to the link I referenced in the original issue so they can continue to be available.
