### ISSUE TITLE
Unable to remove owner from plot

### ISSUE THREAD

**Issue by burdoto** [IntellectualSites/PlotSquared#2330]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support.*__
# Bug report template 

**Debug paste link:** 
Currently unable to post a paste link; see #2332

**Description of the problem:** 
Currently I am not able to remove myself as the owner from a userplot:
![grafik](https://user-images.githubusercontent.com/42473485/56456253-fc78c580-6369-11e9-8e80-bd5cd1f04d5d.png)

**How to replicate:** 
- Be OP
- Go on any plot that has multiple owners
- Use `/p remove <OWNER>` to try to remove one owner from the plot

**Checklist**:

- [] I included a `/plot debugpaste` link (-> Unable to do so)
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
`/plot remove` removes added/trusted/banned players from plots, not the plot owner. I'm not sure if there is a command to remove an owner

**Comment by burdoto** [comment]
Thanks for the quick response @N0tMyFaultOG, although your response does not help me in any way, as I need to be able to remove owners from plots.

**Comment by N0tMyFaultOG** [comment]
>Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support

Howsoever, you can try using `/plot setowner`

**Comment by burdoto** [comment]
- I am running Spigot ["Paper" fork] on version 1.13
- `/p setowner Kaleidox` causes the following output:
![grafik](https://user-images.githubusercontent.com/42473485/56456438-bf620280-636c-11e9-863f-f53e8bbe90b3.png)

**Comment by RedstoneFuture** [comment]
@N0tMyFaultOG Was this a planed feature or a bug, that a plot can have more than one owners? I like this function, but PlotSquared have problems with this currently I think. For example this situation or the API (I down't know).

**Comment by dordsor21** [comment]
You may need to use it on the other plot(s) that are technically owned by him. Otherwise, there's no way to remove owners from a plot.

**Comment by MattBDev** [comment]
@RedstoneFuture There is no proper documentation on how a plot can get multiple owners. That is the main issue.

**Comment by RedstoneFuture** [comment]
@MattBDev I know only the situation in there you merge more plots with different owners. Than you have more than one owners.

**Comment by burdoto** [comment]
@RedstoneFuture @MattBDev That is exactly the situation I was talking about.

**Comment by MattBDev** [comment]
The issue needs to be discussed thoroughly and documented to proceed.

**Comment by AeSix** [comment]
```5:19 PM] AeSix: Obviously I don't steer the direction of progress with P2.  However, I'll state my opinion anyways.
Regarding multi-owner plots: 
I think it's a bad idea to officially support them, or to even allow it to happen.  I have, what I believe are valid reasons.  First, if a plot or merged plot is to have multiple owners, there is risk that the two players will have a falling out.  At this point, they both claim ownership of the plot.  They both have built on it, potentially over the entire area.  There's no fair way to remove one owner, or to unlink such a plot where both (or potentially multiple people) can claim ownership.  This is compounded when two previously built upon plots are merged. Unlinking a merged plot may provide for an even split, however what about chests, items, builds which one player left/built on the other owner's plot.

No matter how it's discussed, it's an unforseen nightmare for players and server owners.

The sane method, imho, is to have one person be the owner, and trust the other person.  If two friends are to merge plots, one of them should be required to give up ownership to the other.  This should be reflected in each player's plot limit count.  This would allow one person alone to claim 100% ownership of the plot.

The less sane, but still more sane than assigning multiple players as owner, is to create a co-owner level of trust, where both players are then shown as owner, but there would be a primary owner for each plot, and the other player would be co-owner.  If the plots are unlinked, the ownership reverts to the original owner.  Any build in the road is NOT regenerated.  This would require someone with permissions to move those items to which ever plot they chose (or not to do so) and then run a special command to regen just those section of road which need it.  It's still a manual mess to deal with, but at least it's a bit more fair.
```
```
[6:17 PM] zombachu: I think it would be good to support the feature as enableable in a config and let server owners figure out whether they want to deal with any drama

I believe it’s the business of plugin developers to make the best plugin they can, not be opinionated about what they think is the best way for owners to run their servers
[6:17 PM] zombachu: I think your ideas are valid but would be better addressed to any servers you play on, not the plugin developers
```
```
[9:56 PM] AeSix: That's a fine option too!  But there should be a warning not to complain when things go tits up.
```
```
[12:52 AM] Jesse: it's a permission plots.merge.other
[12:52 AM] Jesse: revoke it and you should be fine
```

so, to allow multi-owner plots, the person merging the plots needs plots.merge.other
To disallow this, the person needs to not have this permission.

This breaks the ability for staff to be able to merge a single owner's two plots upon request if there is any fear that staff may merge multiple players' plots.  This would move plot merging up to a higher level staff.  

I guess this is the absolute solution to this issue.

**Comment by AeSix** [comment]
@burdoto  I know you tried to set the owner to one of the current owners of the plot, however, did you try to set the owner to a third party?  If that works, you can then set the owner to the player who should own the plots.  If that's not working, let us know.  

Also, make sure you're updated on paper/wg/fawe(or w/e)/p2

Thank you.

**Comment by AeSix** [comment]
Closing ticket as answered.  There's many much more important issues for the devs to tackle.
