### ISSUE TITLE
Potion throwing

### ISSUE THREAD

**Issue by OtakusAreNEET** [IntellectualSites/PlotSquared#2333]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support.*__
# Bug report template 

**Debug paste link:** 

**Description of the problem:** 

**How to replicate:** 

**Checklist**:

- [] I included a `/plot debugpaste` link
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [] I Made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
You've not really said anything?

**Comment by OtakusAreNEET** [comment]
How do I allow untrusted people to throw potions?
