### ISSUE TITLE
/p set border and /p set wall make problems on merged plots

### ISSUE THREAD

**Issue by Resi23** [IntellectualSites/PlotSquared#2335]
**Debug paste link:**
/plot debugpaste do nothing. This is latest.log
https://pastebin.com/Yut4FPXr

**Description of the problem:**
PaperMC 621, FastAsyncWorldEdit-bukkit-1.13.86, PlotSquared-Bukkit-4.244
/p set border and /p set wall make problems on merged plots
https://i.imgur.com/AQZmacp.jpg

**How to replicate:** 
Merge Plots and make /p set border diamond_block or /p set wall diamond_block

**Comment by Resi23** [comment]
Try PlotSquared-Bukkit-4.247.jar with same Problem

**Comment by RedstoneFuture** [comment]
![2019-04-25_19 02 17](https://user-images.githubusercontent.com/4140635/56754321-01d07880-678d-11e9-93df-3afe65ac07a8.png)

Right. I can replay this issue in east-west-direction.

**Comment by MattBDev** [comment]
@RedstoneFuture is it a visual glitch or are the blocks actually gone?

**Comment by RedstoneFuture** [comment]
@MattBDev The stone blocks are not replaced to wool. No, this is not a visual glitch.

**Comment by Resi23** [comment]
Same Problem with
Spigot-8043ebc-f690957 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)
PlotSquared-Bukkit-4.286
WorldEdit v7.0.0-SNAPSHOT;4275-71df371

**Comment by Resi23** [comment]
Fixed for me in Version PlotSquared-Bukkit-4.288
