### ISSUE TITLE
java.lang.NullPointerException at boot already reported in 2056

### ISSUE THREAD

**Issue by FrozenBeard** [IntellectualSites/PlotSquared#2341]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support.*__
# Bug report template 

**Debug paste link:** 

/plot debugpaste does nothing, no output at all.

Paper: This server is running Paper version git-Paper-1613 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
PlotSquared version 19.04.20-347c6fd-753

**Description of the problem:** 
When I boot there is a NullPointerException that spams console, its been happening for a while as I opened it in #2056 but it was just closed, I updated to the latest legacy version for 1.12.2 today and this issue still exists, so ive opened a new ticket.
Here is the output from console https://gist.github.com/FrozenBeard/8bb41f0454cdad10ee064e84ee28eb63

**How to replicate:** 

Just run on latest paper 1.12.2.

**Checklist**:

- [x] I included a `/plot debugpaste` link - no the plugin does not do anything when you run this.
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue) There is at #2341 
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
You don't need to create a new issue if the old one was closed. Just ask for it to be reopened.
