### ISSUE TITLE
setComponent for the wall

### ISSUE THREAD

**Issue by TheRealDomm** [IntellectualSites/PlotSquared#2347]
Hey everyone,

I wanted to ask if there is an option to set the plot wall with setCompenent.

I've done it with "border" for the plot border but "wall" doesn't seen to work.

Thanks in advance.

**Comment by RedstoneFuture** [comment]
Do you define the plot-blocks with commands or with the config?


Maybe use "/config/worlds.yml":

>    plotworld:
>     [...]
>     wall:
>       filling: stone
>       block_claimed: sandstone_slab
>       height: 62
>       block: stone_slab
>     [...]


If the commands are not working

**Comment by TheRealDomm** [comment]
> Do you define the plot-blocks with commands or with the config?
> 
> Maybe use "/config/worlds.yml":
> 
> > plotworld:
> > [...]
> > wall:
> > filling: stone
> > block_claimed: sandstone_slab
> > height: 62
> > block: stone_slab
> > [...]

Okay I should have that explained better next time. 

So you can do with the API someting like this (is working for borders on top e.g. Quarz Slabs)

`for (Plot plots : plot.getConnectedPlots()) {
		        Main.api.getPlotManager(p.getWorld()).setComponent(plots.getArea(), plots.getId(), "border", pb);
		      }`

My question is would it be possible todo that the same way like

`for (Plot plots : plot.getConnectedPlots()) {
		        Main.api.getPlotManager(p.getWorld()).setComponent(plots.getArea(), plots.getId(), "wall(dont know this value or what it should be didnt find anything in docs / api-docu)", pb);
		      }`

**Comment by dordsor21** [comment]
PlotManager#getComponents, i.e. "main", "floor", "air", "all", "border", "wall", "outline", "middle" for a normal plot world
