### ISSUE TITLE
Pasting a plot schematic resulting in empty plot

### ISSUE THREAD

**Issue by ItsAZZA** [IntellectualSites/PlotSquared#2349]
**[REQUIRED] PlotSquared Version Number:**
```
> plot version
[13:12:10 INFO]: [P2] >> PlotSquared (Version: PlotSquared-19.4.29-299fac9-265)
[13:12:10 INFO]: [P2] >> Authors: Citymonstret & Empire92 & MattBDev & dordsor21
[13:12:10 INFO]: [P2] >> Wiki: https://github.com/IntellectualCrafters/PlotSquared/wiki
[13:12:10 INFO]: [P2] >> Newest Version: development-builds
```

**[REQUIRED] Spigot/Paper Version Number:**
```
> version
[13:12:49 INFO]: This server is running Paper version git-Paper-621 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[13:12:49 INFO]: Checking version, please wait...
[13:12:49 INFO]: You are 3 version(s) behind
``` 

**[REQUIRED] Minecraft Version Number:** 1.13.2

**Links to worlds.yml file and settings.yml file:** 
worlds.yml: https://pastebin.com/tqzMb0uL
settings.yml: https://pastebin.com/7raeeegU

**[REQUIRED] Description of the problem:** 
When pasting a plot schematic on the plot or by claiming a plot with schematic on claim enabled, it results in an empty plot. It's either a plot with bedrock at the bottom or nothing at all. The P2 plugin gives a successful paste message and no errors on console or chat.

The schematics are the plot size and go from bedrock to build limit.

Pasting the schematics with FAWE alone works fine. We have tested various schematics.

**Any relevant console output or screenshots:**
Plot before paste: https://i.imgur.com/3VaY0gU.png
Plot after paste: https://i.imgur.com/JWj1xwz.png

What it should be: https://i.imgur.com/oEGd3cm.png

**Plugins being used on the server:**
FAWE, version 1.13-19.4.29-ea07b54-104

**How to replicate:** 

1. Paste a schematic on a plot with /plot schematic paste <schematic> **OR** claim a plot with a ready set schematic.
2. Results in an empty plot

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
You are using the wrong PlotSquared version. Download from https://ci.athion.net/job/PlotSquared-Breaking/.

**Comment by ItsAZZA** [comment]
Updating to this version didn't fix the issue.
```
> p2 version
[17:02:33 INFO]: [BuildCraftia] >> PlotSquared (Version: PlotSquared-19.5.1-2ec13e4-269)
[17:02:33 INFO]: [BuildCraftia] >> Authors: Citymonstret & Empire92 & MattBDev & dordsor21
[17:02:33 INFO]: [BuildCraftia] >> Wiki: https://github.com/IntellectualCrafters/PlotSquared/wiki
[17:02:34 INFO]: [BuildCraftia] >> Newest Version: development-builds
```

**Comment by DDuart** [comment]
I can confirm this issue.

**Comment by ItsAZZA** [comment]
Apparently works when using WorldEdit 7 beta 5.

**Comment by MattBDev** [comment]
Someone messed up when changing our versioning scheme. You were on the right version of P2

**Comment by dordsor21** [comment]
I believe this is thus an issue with the FAWE implementation of SchematicHandler for P2

**Comment by AbgezocktYT** [comment]
I can confirm we have the same issue. MC 1.13.2.
FAWE 1.13.105 and Plotsquared 19.4.8-e0bd9e3-226

**Comment by AeSix** [comment]
@AbgezocktYT but did you try it with FAWE build 108?

**Comment by ItsAZZA** [comment]
Can confirm the issue occurs in build 108. The `/fawe version` still says build 104 but it is most definitely the 108 build from Jenkins.

**Comment by AeSix** [comment]
https://i.imgur.com/vMfuVbD.png

try getting it from the page linked on the spigotmc forums.

**Comment by ItsAZZA** [comment]
I did that @AeSix but still getting the same message.

**Comment by AeSix** [comment]
The message that you're using build 104 after having installed 108?  The image I provided is from the build from https://ci.athion.net/view/Everything/job/FastAsyncWorldEdit-Breaking/  (build 108), and as you can see, it shows that I am indeed using build 108.  

I don't know if this has any affect on the original problem.  However, if you did indeed get the file from the ci, and it says it's 104, then something is messed up with your set up, at least in that way. 

There's nothing in recent changes which suggest that the devs have even attempted to resolve the issue with the original issue. You can follow the changes here:  https://ci.athion.net/view/Everything/job/FastAsyncWorldEdit-Breaking/changes

Keep an eye out as there may be changes to the way schematics, clipboards of copy/paste is handled.  Those will be the builds you will want to try.

**Comment by AeSix** [comment]
Is this still an issue when using:
Paper build 626 https://papermc.io/api/v1/paper/1.13.2/626/download
WorldGuard 7 beta 3 https://dev.bukkit.org/projects/worldguard/files/2663455  (I understand there are new versions available, including an RC)
FAWE build 110 https://ci.athion.net/job/FastAsyncWorldEdit-Breaking/
PlotSquared-breaking build 286 https://ci.athion.net/view/Everything/job/PlotSquared-Breaking/

Please test using a fresh server install, with fresh config folders/files for each of these.  Try with a) a new schematic build with this setup, and b) the schematic which is failing from your post.  

Let us know the results.

**Comment by AbgezocktYT** [comment]
Hi AeSix,

I downloaded all the versions you suggested and created an empty plotsquared world. Then I build a very simply thing on a claimed plot and saved it as schematic. The schematic is saved without any error messages in chat or console. I edited the worlds.yml and settings.yml as described in the wiki to make P2 load the file on claiming.

Result is still the same as you can see in the image link below. I get an empty plot. In the backround you can see the very nice sculpture I tried it with.

Again this is a new setup without any plugins and with empty configs as mentioned. Because it even failed with a new created schematic I didn't try the one I wanted to use for my server.

https://ibb.co/NC8xsLr

**Comment by AeSix** [comment]
Awesome! Thank you @AbgezocktYT  - I mean, not good that it's not working, but at least the devs have certainty that it's not some other plugin causing the issue.  

p.s. Brilliant artwork there! It should be on display in The Louvre! 🥇

**Comment by AbgezocktYT** [comment]
Well, AeSix,

I don't know if any clarification on this point was necessary. ItsAZZA also did all this before. So I don't think it needed any more confirmation for the devs to be sure this issue is in place. 

Thanks for the comments on my artwork. 👍 

I hope some of the devs will get in touch with this soon as it is one thing I really miss on my server. I would even spend an extra donation for that problem to be fixed. :D :D

**Comment by AbgezocktYT** [comment]
Is there anything someone can do in this process to support the devs to fix this? Can someone get in touch and give a hint if this is still in scope or when a fix could be published?

**Comment by AeSix** [comment]
I've had very little spare time recently, hopefully I'll be able to start testing again and work with the devs. 
I don't even have my servers updated.  But, been getting things done, so hopefully this weekend I'll be able to get some testing and updating done and work with the devs next week. 

Of course, nothing stopping anyone else from doing this too :)

**Comment by AeSix** [comment]
Using WorldEdit 7 (release) and PlotSquared 4.305 on Spigot 1.13.2,
```/plot saveplot```
does not work.  As such, I cannot create a plot schematic to test /pasting/ a plot schematic.

**Comment by AeSix** [comment]
https://github.com/IntellectualSites/PlotSquared/issues/2396  is a similar issue, pointing out that *plot* schematics cannot be created.  All in all, Plot and Road schematics cannot be created, and pasting/using either is not functioning.  This is apparently true for WorldEdit as well as FAWE being installed.  Unknown if having neither WE or FAWE installed will work, presumably not as P2 requires one or the other to be installed.

**Comment by MattBDev** [comment]
One thing that needs to be worked on with the code is making sure that all these methods have a boolean return value and that they are being checked before they send out a success or failure message. If they don't send a message at all, then it needs to be added to the commands.

**Comment by N0tMyFaultOG** [comment]
@ItsAZZA Can you update Fawe and [PlotSquared](https://ci.athion.net/job/PlotSquared-Breaking/lastSuccessfulBuild/artifact/target/PlotSquared-Bukkit-4.398.jar) and test if the issue persists still? According to Jesse this is a Fawe issue that is now resolved.

**Comment by AbgezocktYT** [comment]
@N0tMyFaultOG I will test this asap and give a response.

**Comment by AbgezocktYT** [comment]
@N0tMyFaultOG : 

For me it is working now with PS 4.399 and FAWE 1.13.195. 

![ps_schematic](https://user-images.githubusercontent.com/47848614/68790443-9f1acd80-0647-11ea-97f8-4d9cece94cd6.png)

Thanks a lot to everyone for the fix. 👍

**Comment by ItsAZZA** [comment]
I still get an empty plot with FAWE 1.13.201 and PS 4.400. The versions listed above didn't work either. Tried with a newly generated schematic and one of my old schematics.

**Comment by AeSix** [comment]
There's a config option in P2 for using the top of the plot... I think you'll want to find and set that.  Not sure about which setting is which, but I think it's in the wiki.
