### ISSUE TITLE
NullPointerException on Startup

### ISSUE THREAD

**Issue by sTiN55** [IntellectualSites/PlotSquared#2355]
**[REQUIRED] PlotSquared Version Number:** Cant run Commands with /plot.  PlotSquared v4.282

**[REQUIRED] Spigot/Paper Version Number:** This server is running CraftBukkit version git-Spigot-1eece4f-8879c31 (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)

**[REQUIRED] Minecraft Version Number:** 1.14

**Links to worlds.yml file and settings.yml file:** 

worlds.yml: https://hastebin.com/ujoviqakat.cs
settings.yml: https://hastebin.com/wuhejagohe.bash

**[REQUIRED] Description of the problem:** 
The server doesnt Start.

**Any relevant console output or screenshots:**
https://i.gyazo.com/53c7fe7469ff95426766a5bd787af325.png

**Plugins being used on the server:**
Worldedit and PermissionsEx

**How to replicate:** 

-/-

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
please provide log output in text, either using a paste service or markdown code section. 

additionally, both spigot and p2 for 1.14 are in-development, it's quite possible for a newer spigot build to break p2, and other plugins. 

Please test using p2 build 277, if it also does not start, then we'll need the full start section of your latest.log.

**Comment by sTiN55** [comment]
Okay it works but why i cant use the API in my own Plugin ?
In the Version 1.12.2 works my Code.
`Plot plot = api.getPlot(p.getLocation());`

But in 1.14 the Function "getPlot" doesnt exist.

**Comment by AeSix** [comment]
@MattBDev  this is a bit beyond me at this point.  Pls halp :D
