### ISSUE TITLE
Plot Analysis tools throw NPE

### ISSUE THREAD

**Issue by HeroCC** [IntellectualSites/PlotSquared#2356]
# Bug report template 

**[REQUIRED] PlotSquared Version Number:** 4.277

**[REQUIRED] Spigot/Paper Version Number:** git-Paper-624 (MC: 1.13.2)

**[REQUIRED] Minecraft Version Number:** 1.13.2

**Links to worlds.yml file and settings.yml file:** 
Worlds.yml: https://pastebin.com/issFtKfs
Settings.yml: https://pastebin.com/tUZZjuHC

**[REQUIRED] Description of the problem:** 
Running analysis tools generates Null Pointer Exception, fails to complete.

**Any relevant console output or screenshots:**
![image](https://user-images.githubusercontent.com/2124489/57586823-6992fd00-74c9-11e9-828f-bff9b86576e3.png)

**Plugins being used on the server:**
![image](https://user-images.githubusercontent.com/2124489/57586827-8f200680-74c9-11e9-936c-fcba5afa0196.png)

**How to replicate:** 
* Rate several plots (to get data)
* run `/plot debugexec generate-analysis 7` (same as in docs) or `/plot debugexec analyze`
* Command output will claim process is starting, console will print Null Pointer Exception

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
@HeroCC is this still an issue with build 290?

**Comment by RedstoneFuture** [comment]
@AeSix Yes.

Testet with:
> PaperSpigot-632
> PlotSquared-Bukkit-4.292

**Comment by AeSix** [comment]
closing due to https://github.com/IntellectualSites/PlotSquared/issues/2424 being resolved. 
If it's still an issue, reopen the ticket and update with current information.
