### ISSUE TITLE
Claiming plots creates a broken border

### ISSUE THREAD

**Issue by KaratekHD** [IntellectualSites/PlotSquared#2359]
**PlotSquared Version Number:** PlotSquared-18.7.27-cd9d22c-2026

**Spigot/Paper Version Number:** git-Spigot-550ebace-7019900e (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)

**Minecraft Version Number:** 1.8

**Links to worlds.yml file and settings.yml file:** 

<a href=https://gist.github.com/KaratekHD/eb5bc5e9600f4b08e78e3f41e76d9936>Link</a>

**Description of the problem:** If I claim a Plot, it looks "bad", like in the picture

**Any relevant console output or screenshots:**
![2019-05-15_14 55 21](https://user-images.githubusercontent.com/38097062/57777172-7d38a080-7721-11e9-8e58-397adcef4c6e.png)

**Plugins being used on the server:**
WorldEdit, ClearLag, sTablist, PlugMan, AdvancedBan, KaratekCore, IDBanSystem, SignPlugin, UberEnchant, iDisguise, BlocksHub, PermissionsEx, ViaVersion, Vault, ColoredAnvils, Essentials, PlotSquared, Multiverse-Core, ProtocolLib, NoCheatPlus, EssentialsXMPP, EssentialsProtect, EssentialsChat, EssentialsGeoIP, EssentialsAntiBuild, Multiverse-Portals, EssentialsSpawn, HolographicDisplays

**How to replicate:** 
 I just have to claim a plot. Happends in all plotworlds and with multiple versions of P2.

**Comment by MattBDev** [comment]
1.8 doesn't work well. If you need 1.8 you should be using a MC 1.8.8

**Comment by MattBDev** [comment]
Also the build you are using is from LAST YEAR. You need to update and tell us if the plugin still isn't working in the next few days or we will have to close this issue.

**Comment by KaratekHD** [comment]
@MattBDev I tried newer versions as well, But the error came up too. I am going to try Version 1.8.8 in combination with the latest PlotSquared an tell you if it works.

**Comment by KaratekHD** [comment]
Works with Spigot 1.8.8 just fine. Sorry for wasting your time.
