### ISSUE TITLE
Sand is not a valid block

### ISSUE THREAD

**Issue by fabien91** [IntellectualSites/PlotSquared#2360]
# Bug report template 

**[REQUIRED] PlotSquared Version Number:** 4.286

**[REQUIRED] Spigot/Paper Version Number:** git-Paper-625 (MC: 1.13.2)

**[REQUIRED] Minecraft Version Number:** 1.13.2

**Links to worlds.yml file and settings.yml file:** 
worlds.yml : https://pastebin.com/47b9UF38
settings.yml : https://pastebin.com/kpddrDSL

**[REQUIRED] Description of the problem:** 

Currently, I'm doing some tests to update my server from 1.12.2 to 1.13.2, and i have this error (available in next section in pastebin)

**Any relevant console output or screenshots:**

Error in console : https://pastebin.com/aJHVaMUc

**How to replicate:** 

Create world with sand:100 for road blocks in 1.12.2 and migrate your server in 1.13.2

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
i don't know what :100 on sand would dom but its not something that made it into 1.13, with the materials name changes.

**Comment by AeSix** [comment]
Assuming this is a non-issue with P2/FAWE. Closing.  

Reopen if you can provide additonal information. 

100 is an invalid data value for sand, and so it working at all on 1.12.2 is surprising.

**Comment by xXSchrandXx** [comment]
I got the same Issue with gravel and PlotSquared v4.301.
But at the moment there is no save [FastAsyncWorldEdit for 1.14](https://ci.athion.net/job/FastAsyncWorldEdit-1.14/)...

How can I fix it?

**Comment by xXSchrandXx** [comment]
> I got the same Issue with gravel and PlotSquared v4.301.
> But at the moment there is no save [FastAsyncWorldEdit for 1.14](https://ci.athion.net/job/FastAsyncWorldEdit-1.14/)...
> 
> How can I fix it?

Only happens if PlotSquared loads the world on it's own.
Loading with Multiverse works.

**Comment by AeSix** [comment]
Are you using some silly data addon to gravel like with the sand in the above log?
sand:100 is invalid.  As would be gravel:100
Use proper values, or none at all.

**Comment by UtechtDustin** [comment]
Edit the option `prevent-unsafe` in the konfig `settings.yml` to `false`.
@xXSchrandXx
