### ISSUE TITLE
1.14.1 Random "Wandering Trader" spawning in plotworld

### ISSUE THREAD

**Issue by Resi23** [IntellectualSites/PlotSquared#2361]
**Description of the problem:**
Spigot-8043ebc-f690957 (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT)
PlotSquared-Bukkit-4.286
`    natural_mob_spawning: false`
Random "Wandering Trader" spawning in plotworld

**How to replicate:** 
Install Server with P² and wait ^^

**Comment by AeSix** [comment]
Does this occur with "spawn-npcs" set to false in the server.properties?
Also, try with Paper 626? 

Granted, the above is not a solution, but would be good to test if it's actually a P2 issue or a mojang idiocy.  Not ideal fill mix-world servers however.  

Interim band-aid, possibly use worldguard to prevent mobs from spawning?

**Comment by Resi23** [comment]
`spawn-npcs=true`

Paper 626 is 1.13.2 Server i use 1.14.1 Server

**Comment by AeSix** [comment]
I'm sorry.  It was very late for me when I wrote that.  I intended to get the last build of paper 1.14.1.

Anyways, it may be a server issue rather than a P2 issue, as there may not be code to handle the wandering trader properly yet, in the server.

**Comment by MattBDev** [comment]
@AeSix its likely a valid issue. It's possible a few mobs were missing when updating some of our checks.

**Comment by AeSix** [comment]
Yeah.  I've seen some other people complaining about random mobs spawning when they shouldn't, outside of the P2 scope of discussions. But yeah, totally could be P2 not controlling them too :P

**Comment by AeSix** [comment]
@Resi23 is this an issue with Spigot 1.14.2 still? 
I don't have hard proof at my disposal atm, but I'm certain the wandering trader issue is a Spigot issue, and one which I believe has recently been fixed on the server, though may still be an issue with P2. 

I'm not even about to update any of my servers to 1.14, and have a lot of other work to do so I will not be testing this out myself.

**Comment by Resi23** [comment]
At the moment no one seems to spawn anymore, I will watch it and report back if necessary. Can be closed first.
