### ISSUE TITLE
Material cannot be found

### ISSUE THREAD

**Issue by HgeX** [IntellectualSites/PlotSquared#2362]
**PlotSquared Version Number:** `PlotSquared v4.286`

**Spigot/Paper Version Number:**  `git-Paper-26 (MC: 1.14.1)`

**Minecraft Version Number:** `Minecraft 1.14.1`

**Description of the problem:** When the server starts, I get the following error message for every material: `[17:35:56] [Server thread/ERROR]: Error creating legacy block: yellow_wall_banner. Possibly a new block.`

**Plugins being used on the server:**
I've tested this only on a testserver, so only a few plugins were installed: **Mutliverse-Core (3.0.0-Snapshot), PlotSquared (4.286), ProtocolLib (4.5.0 - Snapshot), Vault (1.7.2-b107), WorldEdit (7.0.0 rc-2), WorldGuard (7.0.0 rc-1)**

**Here's a link with the full log:** https://pastebin.com/emsLbgP7

**Comment by AeSix** [comment]
Possibly related to https://github.com/IntellectualSites/PlotSquared/issues/2364

**Comment by MattBDev** [comment]
Known issue since 1.14.1 is not fully supported yet.
