### ISSUE TITLE
1.14 block reg (new blocks / names issue)

### ISSUE THREAD

**Issue by AJFire14** [IntellectualSites/PlotSquared#2364]
**[REQUIRED] PlotSquared Version Number:** PlotSquared-4.286

**[REQUIRED] Spigot/Paper Version Number:** Latest build for 1.14

**[REQUIRED] Minecraft Version Number:** 1.14.1

**[REQUIRED] Description of the problem:** The 1.14 blocks such as "smooth_stone_slab" or "smooth_quartz_slab" do not work yet when entering these names for the plot borders. The issue is known and was elaborated in the Discord support server.

**Comment by MattBDev** [comment]
Fixed by @dordsor21
