### ISSUE TITLE
{Legacy Build} Schematic not pasting on clear

### ISSUE THREAD

**Issue by DaRiches** [IntellectualSites/PlotSquared#2366]
http://prntscr.com/ns0zoj

**Comment by AeSix** [comment]
Well, I was gonna yell at you for not filling out the form properly, but you're just doing as @MattBDev told you to. 
Also, posting this so other issue moderators know and don't yell at you :)

**Comment by DaRiches** [comment]
👌

**Comment by AeSix** [comment]
@MattBDev  could this be related to https://github.com/IntellectualSites/PlotSquared/issues/2349 as well?

**Comment by AeSix** [comment]
Without full information, this sounds like yet another duplicate of https://github.com/IntellectualSites/PlotSquared/issues/2375
closing.
