### ISSUE TITLE
cannot use plotupload

### ISSUE THREAD

**Issue by mmuziek** [IntellectualSites/PlotSquared#2368]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number:** 
plotsquared-4.277

**[REQUIRED] Spigot/Paper Version Number:** 
paper 42
**[REQUIRED] Minecraft Version Number:** 
1.14.1

**Links to worlds.yml file and settings.yml file:** 

**[REQUIRED] Description of the problem:** 

im using the Plot upload site.
Stange enough it states failed to generate download link
strange enough it adds a weirt uuid at the end of the url causing the 403

**Any relevant console output or screenshots:**
java.io.IOException: Server returned HTTP response code: 403 for URL: http://biccplotdb.bitcubes.eu/upload.php5e2d395-0219-4dc7-96db-16fb0dd5eda6

**Plugins being used on the server:**

**How to replicate:** 
do /plot download

note that my webserver runs on IIS thus so uses web.config and not htaccess files. if thats a solution

**Comment by AeSix** [comment]
I didn't realize PHP runs on IIS?  (then again, it's been over a decade since I played with IIS)

Make sure your PHP settings are right.

**Comment by mmuziek** [comment]
What settings they are correct

**Comment by AeSix** [comment]
IIS/PHP pathing/config issue. 

Perhaps try with nginx/php or apache/php.
Make sure PHP is updated. Check if newer versions of PHO broke compatibility.

If you still have issues, ask in #ps-support i  discord.

This is a user configuration issue best solved in chat.

**Comment by mmuziek** [comment]
i wanna agree on that IF someone would finally reply..
i asked my question and in 8 hours still no reply from nobody.

**Comment by MattBDev** [comment]
8 hours ago I was asleep and I can't help people while I sleep.
