### ISSUE TITLE
road problem

### ISSUE THREAD

**Issue by UnityD3ss** [IntellectualSites/PlotSquared#2370]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number:** 

**[REQUIRED] Spigot/Paper Version Number:** 

**[REQUIRED] Minecraft Version Number:** 

**Links to worlds.yml file and settings.yml file:** 

**[REQUIRED] Description of the problem:** 

**Any relevant console output or screenshots:**

**Plugins being used on the server:**

**How to replicate:** 

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
form not filled out.  wasted bits. closing.
