### ISSUE TITLE
Road Problem Regenerate in corner

### ISSUE THREAD

**Issue by UnityD3ss** [IntellectualSites/PlotSquared#2371]
I have a Road Problem!!!
When i claim a Plot and than delete,clear,reset the plot. Spawn outside in the corner of the plot Block of Quarz!!!

Before when i Claim a Plot:
https://i.imgur.com/JNSUzOl.jpg
After when i Delete,clear,reset a Plot:
https://imgur.com/NVBA6Aq

Sry for my Bad englisch :/

**Comment by AeSix** [comment]
form not filled out. Closing. 

Open a new ticket, or provided the previously requested information.
