### ISSUE TITLE
Road Regen

### ISSUE THREAD

**Issue by Chris982** [IntellectualSites/PlotSquared#2372]
Hello,

I have a problem with "/plot createroadschematic" and "/plot debugroadregen"
When i do "createroadschematic" everything is good. But when i "debugroadregen" it doesn't paste the whole thing.

The road should look like this : http://prntscr.com/nu0fcp
When i paste it i get this : http://prntscr.com/nu0fmu

My Spigot version is 1.12.2
Plugin version : (https://ci.athion.net/job/PlotSquared-Legacy/ - LATEST)
My worlds.yml : https://pastebin.com/yanukgY4

Same thing happens with PlotSquared 4.277 with spigot and paperspigot 1.13.3

Thanks

**Comment by MattBDev** [comment]
We need a latest.log to help any further.

**Comment by Chris982** [comment]
https://pastebin.com/8n0AtHG1

**Comment by Chris982** [comment]
Issue has been fixed.
Problem was Road Height
