### ISSUE TITLE
How to create a roadschematic that goes more into the deep than the road

### ISSUE THREAD

**Issue by PinkfluffyGodofWar** [IntellectualSites/PlotSquared#2373]
Hello there,

I wanted to create a road that goes one block deeper than the road itself but I saw that it doesn't copy the block that goes beneath the street is there possibly either a way to set the road block to another or that it copies that part too
The help is very important.!!

Pinky

**Comment by MattBDev** [comment]
If it is so important you should be using the discord instead of a bug report tracker. https://discord.gg/ngZCzbU
