### ISSUE TITLE
Road Bug Spawn blocks on the Corner!

### ISSUE THREAD

**Issue by UnityD3ss** [IntellectualSites/PlotSquared#2374]
Spigot Version:1584

Mc Version: 1.8.8

Plotsquared Version: 4.277

Plugins being used on the server:
WorldGuard,Worldedit,Wildskript,votingplugin,Vault,troll,Supertrails,sTablist,Skript,Serverlist MOTD,Plotsquared,Permissionex,packetlistener,Onlyproxyjoin,Nocheatplus,Multiverse,jail,iDisguise,GG features,gamemode manager,FastAsyncWorldedit,Essentials,Echopet,EazyNick,CustomTab,Crashfix,Clearlag,Chatmanager,Chatex,Blockparticles,Antilagsystem,

Latest Log:
https://www.mediafire.com/file/cp033ibaxl1cpu0/latest.log/file

World.yml:
https://www.mediafire.com/file/a8e3bkznl1otl4x/worlds.yml/file

I have a Road Problem!!!
When i claim a Plot and than delete,clear,reset the plot. Spawn outside in the corner of the plot Block of Quarz!!!

Before when i Claim a Plot:
https://i.imgur.com/JNSUzOl.jpg
After when i Delete,clear,reset a Plot:
https://imgur.com/NVBA6Aq

Sry for my Bad englisch :/

**Comment by MattBDev** [comment]
You can't use PlotSquared 4 on 1.8.8!!
