### ISSUE TITLE
reload bug

### ISSUE THREAD

**Issue by xbxymax** [IntellectualSites/PlotSquared#2376]
This server is running Paper version git-Paper-1613 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

PlotSquared-Bukkit-19.05.28-18e7f15-768

 http://haste.athion.net/oxuyumohig.md
@MattBDev

**Comment by MattBDev** [comment]
Next time format the error logs with markdown or use http://haste.athion.net

**Comment by xbxymax** [comment]
ok!

**Comment by MattBDev** [comment]
Fixed
