### ISSUE TITLE
When I run the /plot auto command comes an error "An error occurred: %s"

### ISSUE THREAD

**Issue by CuzImWeed** [IntellectualSites/PlotSquared#2379]
When I run the command /p Auto it don't create an plot, but /p Claim, /p h and all others work.

PlotSquared debugpastelink:

https://www.athion.net/ISPaster/paste/view/6dba01db8e3b402aa73dc9d5e47df17e

**Comment by MattBDev** [comment]
We can't help until you fix all the errors with your other plugins

**Comment by CuzImWeed** [comment]
Okay, but when I run the command /p auto comes this error in the console "java.lang.ArrayIndexOutOfBoundsException" and this error in chat "An error occurred: %s"

**Comment by MattBDev** [comment]
We can't see that from your logs because you have more than one plugin giving an error
