### ISSUE TITLE
PlotSquared Nukkit Updating

### ISSUE THREAD

**Issue by DueKay** [IntellectualSites/PlotSquared#2381]
[REQUIRED] Ich hoffe es ist nicht schlimm, dass ich lediglich meine Frage schildere. Ich bin nicht gut in English und für die Frage ist keine Version ect von Nöten :D

Ich wollte PlotSquared aktualisieren, da ich bei Nukkit noch auf der v19.03.17-fd32fbe-725 bin und es scheinbar eine neuere gibt. Allerdings finde ich bei https://ci.athion.net/job/PlotSquared-Legacy/ 2 Dateien. Eine .jar und eine .jar.MD5

Meine Frage ist ob ich beide brauch und in den Plugin Ordner laden muss oder ob die normale .jar Datei zum aktualisieren ausreicht?

Zudem währe noch eine Frage von mir, ob ich die Aktualisierungen auch bei https://nukkitx.com/resources/plotsquared.31/ reinsetzen könnt, da ich dort am ehesten wegen Aktualisierungen nach schaue.

Vielen dank im voraus.

Lg DueKay

---------------------------------------------------------------------

[REQUIRED] I hope it's not bad that I'm just telling my question. I am not good at English and for the question no version ect is needed: D

I wanted to update PlotSquared, because I'm still on Nukkit on the v19.03.17-fd32fbe -725 and there seems to be a newer one. However, I find at https://ci.athion.net/job/PlotSquared-Legacy/ 2 files. A .jar and a .jar.MD5

My question is whether I both need and load into the plugin folder or if the normal .jar file to update sufficient?

In addition, I would have a question if I can reinsetzen the updates at https://nukkitx.com/resources/plotsquared.31/, since I look there most likely for updates.

Thanks in advance.

Lg DueKay

**Comment by MattBDev** [comment]
All you need is a .jar file in the plugins folder
