### ISSUE TITLE
希望不要放弃sponge

### ISSUE THREAD

**Issue by taomrp** [IntellectualSites/PlotSquared#2385]
Plotsquared still has many problems running sponge

Goods discarded in the corridor disappear directly

Water/Fluid from Passive Source in Passage Caused by Buckets Used on Steps

Unable to delete already received p2 Home

Execution of commands such as / P2 home after one death cannot be transmitted and prompts have been transmitted

sponge7.1.5

**Comment by AeSix** [comment]
As of at least March 2nd (and well before), Sponge support is not maintained for P2.  
If you would like to contribute to the project, that would be wonderful.  The devs actively take PRs and merge code.

**Comment by MattBDev** [comment]
Sponge is not actively worked on because the API is going to break when they update to 1.14. We rather not waste time writing code that won't work later on
