### ISSUE TITLE
No plots after update

### ISSUE THREAD

**Issue by Zaphara94** [IntellectualSites/PlotSquared#2386]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number:**  
PlotSquared Version Number: 4.277
**[REQUIRED] Spigot/Paper Version Number:** 
Paper Version git-paper-59 version 1.14.2
**[REQUIRED] Minecraft Version Number:** 
minecraft 1.14.2
**Links to worlds.yml file and settings.yml file:** 

Worlds.yml- https://pastebin.com/kd2wm89c
Settings.yml- https://pastebin.com/cBDpYAfr
**[REQUIRED] Description of the problem:** 
Just updated from 1.13.2 to 1.14.2, didn't expect any issues as it seemed like nothing really changed. Of course I turned out to be wrong, when my plot world didn't load. Using plot info or any other command in my previously plot world "Plotworld" no longer registers as a plot. 
**Any relevant console output or screenshots:**
https://pastebin.com/J9JeJYd7
https://athion.net/ISPaster/paste/view/0e13f89f91d449a0acb4a95ce9bb5d09
**Plugins being used on the server:**

https://cdn.discordapp.com/attachments/553208329204400138/584963109593153536/unknown.png
**How to replicate:** 

Literally its just turning on my server. Is there something I don't know about that you have to do between minecraft versions? Like a convert script or something? Because this isn't the first time ive updated PlotSquared or minecraft version and my plot worlds disappear from the database. I really don't want to have to tell my players that they have to redo it all AGAIN.

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
Minecraft is not stable. Spigot & Paper are not stsble. PlotSquared is not ready for 1.14. 
You'll want to revert to your backups.

**Comment by Zaphara94** [comment]
> 
> 
> Minecraft is not stable. Spigot & Paper are not stsble. PlotSquared is not ready for 1.14.
> You'll want to revert to your backups.

I can't very well just revert to 1.13.2 just because. So i guess ill just have to re-do the plots as i did last time and hope that P2 actually does what its supposed to do after i make the world(s) again. But then i fear for updating the plugin, because every time I do, it doesn't register the plots again.

So, maybe ill just maybe look into another plugin that does something similar? Because its getting a little ridiculous, especially if that's all the support you have to give lol.

**Comment by MattBDev** [comment]
@Zaphara94 Please set "prevent-unsafe" to false in the settings.yml and reload. Let me know what happens.

**Comment by MattBDev** [comment]
@Zaphara94 Also, join our discord if you need more help.

**Comment by Zaphara94** [comment]
> 
> 
> @Zaphara94 Also, join our discord if you need more help.

Could you please send me a link? The one on spigotmc is invalid

**Comment by MattBDev** [comment]
@Zaphara94 the link is in our readme file on this website but here is another link anyways: https://discord.gg/ycTuNpB

**Comment by Zaphara94** [comment]
Ok thank you so much! It still throws errors on startup, but the plots are back!

**Comment by MattBDev** [comment]
@Zaphara94 Join the discord. I'll dm you to help you further.

**Comment by KleeSup** [comment]
I've get the same problem with my Plotworld after an reload :/

**Comment by MattBDev** [comment]
@KleeSup run /plots debugpaste and provide us the link here

**Comment by KleeSup** [comment]
ok: https://athion.net/ISPaster/paste/view/cea2e8ed7e2049aab9948388aa95f53d

**Comment by MattBDev** [comment]
The issue is that people are using uppercase world names which doesn't work anymore.

**Comment by KleeSup** [comment]
Sorry for my late review. I have a Question. Why does Uppercase works from 1.8-1.13 but not in 1.14? And how can I convert the old Uppercase named World in a New World? I cant rename the World because if I Do so the World wouldn't be renamed.

**Comment by MattBDev** [comment]
It doesn't work in 1.13 either (at least it shouldn't). It's a Mojang issue. You just need an nbt editor and  a file manager to rename the world files.

**Comment by KleeSup** [comment]
OK I will try it tomorrow. In 1.13 it works perfectly.
