### ISSUE TITLE
PlotAPI in 1.14

### ISSUE THREAD

**Issue by iTzCeddy** [IntellectualSites/PlotSquared#2387]
Hi,

with the 1.14 the PlotAPI was editing and i have the following problems now...

1)` if(new PlotAPI().isInPlot(Player)) {` exists no more. What can I use now?

2) `new PlotAPI().getPlot(p)` can't find too. 

Many thanks for help and sorry for my english, I'm from Germany ^^
- Ceddy

**Comment by Resi23** [comment]
Try
`import com.github.intellectualsites.plotsquared.plot.object.Location;
import com.github.intellectualsites.plotsquared.plot.object.Plot;

    public boolean isInPlot(Player p){
        Location loc = new Location(p.getLocation().getWorld().getName(),
                (int) p.getLocation().getX(),
                (int) p.getLocation().getY(),
                (int) p.getLocation().getZ(),
                p.getLocation().getYaw(),
                p.getLocation().getPitch());
        Plot plot = loc.getPlot();

        return plot != null;
    }`

**Comment by Resi23** [comment]
Try this
`    public boolean isInPlot(Player p){
        Location loc = new Location(p.getLocation().getWorld().getName(),
                (int) p.getLocation().getX(),
                (int) p.getLocation().getY(),
                (int) p.getLocation().getZ(),
                p.getLocation().getYaw(),
                p.getLocation().getPitch());
        Plot plot = loc.getPlot();

        return plot != null;
    }`

**Comment by Resi23** [comment]
Englisch:
does it help?

German:
hilft es?

**Comment by iTzCeddy** [comment]
Yes, it helps. Many thanks!

Ja, das hat mir geholfen. Vielen Dank!
