### ISSUE TITLE
Error using schematics created with WE 7.0.0 rc3

### ISSUE THREAD

**Issue by pablolop002** [IntellectualSites/PlotSquared#2388]
**[REQUIRED] PlotSquared Version Number:** 
PlotSquared (Version: PlotSquared-4.277)

**[REQUIRED] Spigot/Paper Version Number:** 
Spigot git-Spigot-baafee9-17543ec (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)
*and*
Paper git-Paper-76 (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)

**[REQUIRED] Minecraft Version Number:** 
1.14.2

**Links to worlds.yml file and settings.yml file:** 
wolds.yml: https://mega.nz/#!4QZEBarK!-iaIaAS7ydLjswW9NocWCabhY5uJ-A_edUgpcjr98z8
settings.yml: https://mega.nz/#!RRJQSYzT!3TMAnSyZRSw10qYEvoq7sO0xHa-3bA3dF42SZHVTA0Y

**[REQUIRED] Description of the problem:** 
I'm getting this errors with road schemes generated with WorldEdit 7.0 rc3 on minecraft 1.14.2. This causes that roads are generated as the config file specifics.

**Any relevant console output or screenshots:**

> [14:19:43] [Server thread/WARN]: java.io.IOException: Invalid BlockState in palette: minecraft:stone. Are you missing a mod or using a schematic made in a newer version of Minecraft?
> [14:19:43] [Server thread/WARN]:        at com.sk89q.worldedit.extent.clipboard.io.SpongeSchematicReader.readVersion1(SpongeSchematicReader.java:180)
> [14:19:43] [Server thread/WARN]:        at com.sk89q.worldedit.extent.clipboard.io.SpongeSchematicReader.read(SpongeSchematicReader.java:105)
> [14:19:43] [Server thread/WARN]:        at com.github.intellectualsites.plotsquared.plot.util.SchematicHandler.getSchematic(SchematicHandler.java:301)
> [14:19:43] [Server thread/WARN]:        at com.github.intellectualsites.plotsquared.plot.generator.HybridPlotWorld.setupSchematics(HybridPlotWorld.java:148)
> [14:19:43] [Server thread/WARN]:        at com.github.intellectualsites.plotsquared.plot.generator.HybridPlotWorld.loadConfiguration(HybridPlotWorld.java:121)
> [14:19:43] [Server thread/WARN]:        at com.github.intellectualsites.plotsquared.plot.object.PlotArea.loadDefaultConfiguration(PlotArea.java:339)
> [14:19:43] [Server thread/WARN]:        at com.github.intellectualsites.plotsquared.plot.PlotSquared.loadWorld(PlotSquared.java:1104)
> [14:19:43] [Server thread/WARN]:        at com.github.intellectualsites.plotsquared.bukkit.generator.BukkitPlotGenerator.getDefaultPopulators(BukkitPlotGenerator.java:80)
> [14:19:43] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.initWorld(MinecraftServer.java:452)
> [14:19:43] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:424)
> [14:19:43] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258)
> [14:19:43] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:761)
> [14:19:43] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:748)
> [14:19:43] [Server thread/WARN]: java.io.IOException: Invalid BlockState in palette: minecraft:prismarine. Are you missing a mod or using a schematic made in a newer version of Minecraft?
> [14:19:43] [Server thread/WARN]:        at com.sk89q.worldedit.extent.clipboard.io.SpongeSchematicReader.readVersion1(SpongeSchematicReader.java:180)
> [14:19:43] [Server thread/WARN]:        at com.sk89q.worldedit.extent.clipboard.io.SpongeSchematicReader.read(SpongeSchematicReader.java:105)
> [14:19:43] [Server thread/WARN]:        at com.github.intellectualsites.plotsquared.plot.util.SchematicHandler.getSchematic(SchematicHandler.java:301)
> [14:19:43] [Server thread/WARN]:        at com.github.intellectualsites.plotsquared.plot.generator.HybridPlotWorld.setupSchematics(HybridPlotWorld.java:149)
> [14:19:43] [Server thread/WARN]:        at com.github.intellectualsites.plotsquared.plot.generator.HybridPlotWorld.loadConfiguration(HybridPlotWorld.java:121)
> [14:19:43] [Server thread/WARN]:        at com.github.intellectualsites.plotsquared.plot.object.PlotArea.loadDefaultConfiguration(PlotArea.java:339)
> [14:19:43] [Server thread/WARN]:        at com.github.intellectualsites.plotsquared.plot.PlotSquared.loadWorld(PlotSquared.java:1104)
> [14:19:43] [Server thread/WARN]:        at com.github.intellectualsites.plotsquared.bukkit.generator.BukkitPlotGenerator.getDefaultPopulators(BukkitPlotGenerator.java:80)
> [14:19:43] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.initWorld(MinecraftServer.java:452)
> [14:19:43] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:424)
> [14:19:43] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258)
> [14:19:43] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:761)
> [14:19:43] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:748)
> 

**Plugins being used on the server:**
[14:48:24] [Server thread/INFO]: Plugins (14): ServerRestart, AdvancedPortals, LuckPerms, SkinsRestorer, WorldEdit, PlaceholderAPI, Vault, BungeeTabListPlus, ProtocolLib, WorldGuard, WorldEditSelectionVisualizer, VentureChat, AuthMe, PlotSquared

**How to replicate:** 
Using this schemes: https://mega.nz/#F!BRRB3ATI!mMyQrwSICVcVUvhHRS_hUw

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
The plugin can't be used with 1.14 yet or even 1.14 worldedit.

**Comment by dordsor21** [comment]
This is a worldedit issue
