### ISSUE TITLE
PLotSquared Crashes Server?

### ISSUE THREAD

**Issue by MineBomberLP** [IntellectualSites/PlotSquared#2389]
As soon as i put the PlotSquared Plugin on my Server it Crashes instantly as soon as i reload or restart .-.

[latest.log](https://github.com/IntellectualSites/PlotSquared/files/3266966/latest.log)

(Im using it on 1.8.8 by the way)

**Comment by N0tMyFaultOG** [comment]
>You can't use this version of PlotSquared on a server less than Minecraft 1.13.2

You should analyze your log better before raising an issue, [downgrade PlotSquared](https://ci.athion.net/job/PlotSquared-Legacy/lastSuccessfulBuild/artifact/target/PlotSquared-Bukkit-19.05.28-e4fbc23-769.jar)
