### ISSUE TITLE
Renamed server (Not world) and plotsquared plots stopped working?

### ISSUE THREAD

**Issue by FrozenBeard** [IntellectualSites/PlotSquared#2390]
I had my plot world (creative) and Hub on the same server, but I don't need the hub, so I re-branded the Bungee server from hub to creative, so players will do /server creative, and bypass having to go into the hub first.
To go with this, I re-named the folder on the server that encased the entire server from Hub to Creative, so that it was concise, at no point have I re-named the creative world, its always been called Creative where the plots are.
I also re-named the server in server.properties to PirateCraft_Creative from PirteCraft_Hub as it were.

One of these changes upset plotsquared, when I go into the plots world none of the plots are registered as plots.

Im using the SQLite database and have opened it with http://sqlitebrowser.org/ but I can see no mention of the server name in here or in the YAML setting files.

What do I need to change to fix plots being registered as plots.

Again the Plot world (creative) was never re-named, so im not sure why this has happened.

Im using paper 1.12.2 and plotsquared legacy for 1.12.2

Edit: I found out its when I edited my server.properties level-name=Hub to level-name=creative.
This does need to be creative, why is this breaking the plots? The plot world is the creative world, not the hub one.
So I cant change my level worlds in my server properties or remove my old world that I no longer need to use my creative world that has never, ever changed? Why is this a thing? how do I change it?

**Comment by RedstoneFuture** [comment]
The "level-name" ist the default world for a minecraft server with all playerdata, rendered navigation-maps and more. Its based on the default minecraft server concept and not the more-worlds concepts by bukkit.

This default world have a other priorisation at the serverstart inclusive the used generator. I do not know if you can use this world as plot-world currently (I must test it), but by default I have a world like "world" as default dummy-world (level-name=world) and a other (normal) player-world for the plots. This works.

**Comment by AeSix** [comment]
Yeah, you can't just change the name of level-name.  That will wreck any server, regardless of plotsquared or not.  If you need a public name change for the server, do so in bungeecord's config. 

I'm closing this as it is NOT a PlotSquared issue.  This is a user error issue from not understanding how Minecraft servers function.

**Comment by FrozenBeard** [comment]
Well, it is really as I'm now stuck having to have an additional world for no other reason than somehow plot squared is using it even though it has s database? The database has everything it needs to have cliams on a world, why is having this level-name world s dependency?

**Comment by AeSix** [comment]
It's not an issue with the plugin.  You built your plot world on your main world.  You changed your main world name in server.properties.  THAT BREAKS THE WORLD EVERY TIME.  It is NOT a PlotSquared issue.  It is how Mojang designed Minecraft to function.  

Like I said, this is an admin issue, NOT a server or plugin issue.  Learn how to admin your server.  Blaming other people and plugins is neither responsible nor correct.

**Comment by FrozenBeard** [comment]
I didn't build my plot world on my main world, I have said this specificly in the ticket, that is the entire point I am making.
How on earth are you not able to read, I very clearly described the issue, I'm not going to repeat the issue because you cannot understand.

**Comment by AeSix** [comment]
I understand fully.  
You renamed your primary world.  THAT RUINS ALL OF YOUR WORLDS.

**Comment by FrozenBeard** [comment]
Let me try another approval, a visual instead of text.
If you **actually LOOK** at the data for plots (Like I said in the initial ticket) You can clearly see all information needed for plots is inside the database:
![Screenshot 2019-06-11 at 11 48 13](https://user-images.githubusercontent.com/144046/59266146-e2a78080-8c3e-11e9-81c4-f5d3b251a404.png)

You have the plot ID, where it starts and ends, the owner, the **WORLD IT IS IN**, and the timestamp.
As all information is stored inside the database there should not be a dependency on the playerdata folder in the initial level-name.

You have yet to explain what information is needed from this dependency when it is all in the database.
