### ISSUE TITLE
smooth_stone_slab Not work on Claiming wall

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#2391]
the block smooth_stone_slab do not work on claiming wall

**Comment by alexschrod** [comment]
Well done! You ignored the whole bug report template!

**Comment by AeSix** [comment]
@DevJoey You'll need to give us all of the information requested of you in the template which you deleted.  This ticket will be closed until such time as the information is furnished.

**Comment by MattBDev** [comment]
Also, the plugin is not compatible with 1.14
