### ISSUE TITLE
Plot Signs Not Working?

### ISSUE THREAD

**Issue by dqnielle** [IntellectualSites/PlotSquared#2394]
PlotSquared Version Number: PlotSquared-18.12.12-be48507-2053
 Minecraft Version Number: 1.8.9

**Links to worlds.yml file and settings.yml file: 
[settings.txt](https://github.com/IntellectualSites/PlotSquared/files/3283362/settings.txt)

[worlds.txt](https://github.com/IntellectualSites/PlotSquared/files/3283365/worlds.txt)

**[REQUIRED] Description of the problem:** When I claim a plot the sign doesn't show its claimed

**Any relevant console output or screenshots:**
![image](https://user-images.githubusercontent.com/51765291/59390269-c7bc3580-8d3e-11e9-8948-ab37f2074a24.png)

**Plugins being used on the server:**
![image](https://user-images.githubusercontent.com/51765291/59390289-d571bb00-8d3e-11e9-9a03-e1e8c7b807fd.png)

**Comment by MattBDev** [comment]
Version is a year old and there was no log provided. If the reporter updates the plugin and then provides a startup log after claiming another plot I will consider reopening.

**Comment by AeSix** [comment]
just a note:  I've had issue with sign text with certain resource packs.  @dqnielle should test with no resource pack as well, or provide an image with a correctly displayed sign next to the broken plot signs.
