### ISSUE TITLE
Last row of plot corner section not copied to schematic

### ISSUE THREAD

**Issue by spotlightishere** [IntellectualSites/PlotSquared#2395]
**PlotSquared Version Number:** 
```
[P2] >> PlotSquared (Version: PlotSquared-4.291)
[P2] >> Authors: Citymonstret & Empire92 & MattBDev & dordsor21
[P2] >> Wiki: https://github.com/IntellectualCrafters/PlotSquared/wiki
[P2] >> Newest Version: development-builds
```
This same issue was also reproduced under `4.277`, which at this time is the current release on Spigot.

**Spigot/Paper Version Number:** 
```
This server is running Paper version git-Paper-"d5f24c6a" (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
```

**Minecraft Version Number:** 
1.13.2, 1.12.2, and etc due to ProtocolSupport and so forth

**Links to worlds.yml file and settings.yml file:** 

You can find them both here: [worlds.yml](https://pastebin.com/HYUgX7VG) and [settings.yml](https://pastebin.com/h81Hey1S). These are both from http://ci.athion.net/job/PlotSquared-Breaking/291/.

**Description of the problem:** 
Despite all attempts, the last corner rows of any square intersection has a lapse of item.

**Any relevant console output or screenshots:**

`/plot debugpaste`: https://athion.net/ISPaster/paste/view/84d81ee4c19c418a8805934d9e63636a

A visual of this issue can be seen below:
<img width="966" alt="Visual of this issue" src="https://user-images.githubusercontent.com/10055256/59402657-02d15f80-8d65-11e9-8d36-4a74d77a5388.png">

**Plugins being used on the server:**

Nothing that would interfere. Of note is that this was reproduced with both FAWE and normal WorldEdit.

**How to replicate:** 

Follow https://github.com/IntellectualSites/PlotSquared/wiki/Installation#adding-road-schematics using stone.

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)

However, related: #1819.

- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
Provide the **SERVER VERSION**. I don't care about ProtocolSupport or ViaVersion. The **SERVER VERSION** is important if you want the issue fixed or I will be closing this.

**Comment by spotlightishere** [comment]
The server's running Paper with 1.13.2, I now realize that wasn't immediately made clear.

**Comment by MattBDev** [comment]
Those air blocks exist there because the schematic wasn't filled in on that part of the road. One section of road extends to those 6 blocks.

**Comment by Artuto** [comment]
Not sure if you mean that in the original schematic that part was missing? if yes, no, we built the road completely in all the 4 roads including the intersection 
![image](https://artuto.s-ul.eu/2eMEhkRQ)

**Comment by MattBDev** [comment]
That's not enough. if you look at the original picture you can see several endstone blocks because there was only air in those spots when you build the schematic. The road didn't extend far enough. You need to add blocks to those sides of the road and the schematic will generate just fine.
