### ISSUE TITLE
Roads not generating after unlinking / unmerging

### ISSUE THREAD

**Issue by AnimeDrache** [IntellectualSites/PlotSquared#2397]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number:** 4.287 

**[REQUIRED] Spigot/Paper Version Number:** 1.14.2

**[REQUIRED] Minecraft Version Number:** 1.14.2 (?)

**[REQUIRED] Description of the problem:** After unlinking a merged plot, the roads won't regenerate again. I found some posts about this issue but there was no solution for me. "boy0001" closed this topic ( https://github.com/IntellectualSites/PlotSquared/issues/214 ) and pasted a link to this but I have no idea what to do with that: https://github.com/IntellectualSites/PlotSquared/commit/aa74a0faddc9bf3447488647a4a01df96777da1d

**Any relevant console output or screenshots:**

**Plugins being used on the server:**
ChatEx
DailyRewards
Essentials-X-2.16.1.183-mc114-b98
EssentialsXSpawn-2.16.1.0
images-1.0.6-SNAPSHOT
LeadTheWay
Multiverse-Core-3.0.0-SNAPSHOT
MyPet-3.2
PermissionsEx-1.23.4
PlaceholderAPI-2.10.2.jar
PlotSquared-Bukkit-4.287.jar
ProtocolLib.jar
RifleChairs.jar
Scoreboard-revision.jar
Vault.jar
WarpPortals-5.6.5-SNAPSHOT.jar
worldedit-bukkit-7.0.0-rc-2.jar
worldguard-legacy-7.0.0-rc-1.jar

**How to replicate:** 
1. /p claim 2 plots
2. /p merge them
3 /p unlink them

**Checklist**:

- [X] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
update. You're 4 versions behind, and the next version fixes road regens. 
https://ci.athion.net/view/Everything/job/PlotSquared-Breaking/changes

If it's still an issue, it may be 1.14.2.   Test with 1.13.2.  
If it's still an issue, update the ticket as such and we'll re-open it.

**Comment by AnimeDrache** [comment]
Thank you very much, the new version fixed it.
