### ISSUE TITLE
NPE with checkModified method in HybridUtils

### ISSUE THREAD

**Issue by fabien91** [IntellectualSites/PlotSquared#2399]
# Bug report template 

**[REQUIRED] PlotSquared Version Number:** Version PlotSquared-4.292

**[REQUIRED] Spigot/Paper Version Number:** git-Paper-609 (MC: 1.13.2)

**[REQUIRED] Minecraft Version Number:** 1.13.2

**[REQUIRED] Description of the problem:** 
NPE with checkModified method in HybridUtils

**Any relevant console output or screenshots:**
Error : https://pastebin.com/jLBbfceT

**How to replicate:** 
Hello,
I'm using this method (deleted in new PlotSquared version), but i reused for custom version of PlotRankUp after plot done command (i need to check minimal block updated): 
https://pastebin.com/g4EV31Pp

Could you help me please ?

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
Programming help should be asked on discord, not here.
