### ISSUE TITLE
Error creating legacy block

### ISSUE THREAD

**Issue by FatherWh0** [IntellectualSites/PlotSquared#2400]
When loading Plotsquared with paper 1.14.2 the following errors occur. 
https://pastebin.com/RjUkAPcU
This happens with 4.277 and the latest dev build 4.292.

**Comment by MattBDev** [comment]
Duplicate of several others.

**Comment by FatherWh0** [comment]
Please link to duplicate. I cannot locate any.

**Comment by MattBDev** [comment]
https://github.com/IntellectualSites/PlotSquared/issues/2364

**Comment by MattBDev** [comment]
https://github.com/IntellectualSites/PlotSquared/issues/2362

**Comment by MattBDev** [comment]
This is the reason you should FOLLOW THE TEMPLATE instead of deleting it.
