### ISSUE TITLE
Regenerate Roaads with more created than the first block

### ISSUE THREAD

**Issue by calgia** [IntellectualSites/PlotSquared#2405]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number:** PlotSquared-4.277 

**[REQUIRED] Bukkit 1.14.2 Server:** 

**[REQUIRED] 1.14.2:** 

**Links to worlds.yml file and settings.yml file:** 

**[REQUIRED] Roads are not regenerated correctly:** 

**-**

**PlotSquared, WorldEdit:**

**How to replicate:** 
/p createroadschematic

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**description**

When i make a Road, where not only the top-Blok is changed, he show me by the pastet command (/p createroadschematic) that he has worked but he dosen't really do every detail correct. he does only the first block right AND some of the items aren't correct of full when i test it out.
![ps2bug1](https://user-images.githubusercontent.com/50338956/60052357-559c0700-96d5-11e9-9738-0beefb5371b2.png)
![ps2bug2](https://user-images.githubusercontent.com/50338956/60052358-56349d80-96d5-11e9-8cbd-079a49ecf608.png)
![ps2bug3](https://user-images.githubusercontent.com/50338956/60052534-cfcc8b80-96d5-11e9-9835-3822c2adfe11.png)

**Comment by MattBDev** [comment]
Poor description. Checked off all the boxes without actually providing the right information. That version of PlotSquared doesn't support 1.14.2
I would go on but I think I made my point.
