### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Jg747** [IntellectualSites/PlotSquared#2406]
If i grant to a group worldedit.* and fawe.* WITHOUT plots.worldedit.bypass does it work or not?

Because i don't want to search all worldedit permissions and i don't want to permit to grief the server!

**Comment by AeSix** [comment]
If you don't want to take the security of your server seriously, you'll have a hard time keeping the world in order.  Chaos will reign, and all your players will leave.  

Either set up permissions properly, or don't bother running a server.

There is a wiki for both of these plugins, as well as your choice of permission management systems.  Read. Understand. Follow.
