### ISSUE TITLE
Claiming deletes upper Roadshematic

### ISSUE THREAD

**Issue by AnimeDrache** [IntellectualSites/PlotSquared#2408]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number:** 4.297

**[REQUIRED] Spigot/Paper Version Number:** 1.14.2

**[REQUIRED] Minecraft Version Number:** 1.14.2

**Links to worlds.yml file and settings.yml file:** 

**[REQUIRED] Description of the problem:** When someone claims or deletes a plot, it now does effect the area above the border. Normally if you claim a plot, it will only affect the border on the ground and change nothing above. Tried this with version 4.291 which works correclty and won't remove anything. The current version deletes it as you can see on the both "before and after" screenshots.

![2019-06-27_10 20 26](https://user-images.githubusercontent.com/51856826/60250377-d110da80-98c6-11e9-9f59-1ca1e4b6dc98.png)
![2019-06-27_10 20 42](https://user-images.githubusercontent.com/51856826/60250400-dcfc9c80-98c6-11e9-8e5a-17d59a2d2059.png)

**Any relevant console output or screenshots:**

**Plugins being used on the server:**

**How to replicate:** 

**Checklist**:

- [x] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by jewome62** [comment]
I confirm the same problem
![image](https://user-images.githubusercontent.com/472429/60260964-117a5380-98db-11e9-85a1-c2603c151b8a.png)

**Comment by jewome62** [comment]
Origin of this bug : https://github.com/IntellectualSites/PlotSquared/pull/2383

**Comment by AeSix** [comment]
Honestly, this seems like expected behavior.  
You should probably make the roads 2 blocks wider to use the schematic you have.  Blocks can be either road or plot wall... I don't see how they can be both.  The columns of blocks above the plot wall are plot wall.  

The only other thing I can think, which may not work, is to regen all roads. 

If ilyvion thinks this shouldn't be, then perhaps he can PR a proper fix.
