### ISSUE TITLE
dark_prismarine_slab id missing

### ISSUE THREAD

**Issue by AJFire14** [IntellectualSites/PlotSquared#2409]
**[REQUIRED] PlotSquared Version Number:** Build 297 

**[REQUIRED] Spigot/Paper Version Number:** 1.14.2

**[REQUIRED] Minecraft Version Number:** 1.14.2

**[REQUIRED] Description of the problem:** The dark_prismarine_slab id seems to be missing. Some other new slabs work, but "dark_prismarine_slab" doesn't seem to have been added yet. 

**How to replicate:** Type "dark_prismarine_slab" when setting the claimed plots border. It will just set it as sandstone slab, and when editing in config, it'll change to "dark_prismarine_block" instead of the actual slab.

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
Fixed in 2468456
