### ISSUE TITLE
Permission Issue for Deny-Exit

### ISSUE THREAD

**Issue by falceso** [IntellectualSites/PlotSquared#2411]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number:**  PlotSquared-4.298

**[REQUIRED] Spigot/Paper Version Number:** 1.13 - Paper 626

**[REQUIRED] Minecraft Version Number:**  1.13.2

**Links to worlds.yml file and settings.yml file:** 

https://gist.github.com/falceso/bf95b03d8644dfaa6561fdf581ad5d17
https://gist.github.com/falceso/a53ba76abd408f090f2d8f4c72348d8a

**[REQUIRED] Description of the problem:** 
Unable to leave plot with flag `deny-exit`, even though I have the permission node listed in the no permission message.
**Any relevant console output or screenshots:**
![Screenshot](https://img.falceso.me/9037b468444daba.png)
[Short Discord Discussion](https://canary.discordapp.com/channels/268444645527126017/344128265075556353/595071039533350912)

**Plugins being used on the server:** Not Relevant?

**How to replicate:** 

When the flag `deny-exit` is placed on a plot. And you leave you receive the usual permission deny message with the node `plots.admin.exit.denied`. Now, you give yourself that permission, and try again. It doesn't appear to work.

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
Confirmed this to be the case using Spigot 1.13.2 (final build), P2 4.318, and PEX.

The prescribed permission node does not exist in the bukkit plugin.yml.
https://github.com/IntellectualSites/PlotSquared/blob/breaking/Bukkit/src/main/resources/plugin.yml

I do not know where in code to see if there is any other outpoints for this function.
