### ISSUE TITLE
Time stuck when switching Worlds

### ISSUE THREAD

**Issue by zachrocks22** [IntellectualSites/PlotSquared#2412]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number:** v4.298

**[REQUIRED] Spigot/Paper Version Number:**  Paper Build #119

**[REQUIRED] Minecraft Version Number:** 1.14.4

**[REQUIRED] Description of the problem:** When setting a time flag in a plot, then switching worlds while still in that plot, the time of day gets stuck.

**Any relevant console output or screenshots:** None! There are no stack-traces thrown. :(

**Plugins being used on the server:** Using Plotsquared (Latest Release) with Multiverse (v3.0.0 from jekins), PerWorldInventories (Latest), GriefPrevention (Latest), WorldEdit (Latest Beta from Bukkit), and WorldGuard (Latest Beta from Bukkit).

**How to replicate:** 
1) Claim a plot
2) Set a time flag (/plot flag set time 500)
3) Switch worlds or teleport to a different world while in the plot.
4) Time is now stuck until the player goes back to the plotworld and exits the plot or relogs.

**Checklist**:
- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
    ( I did find this issue: https://github.com/IntellectualSites/PlotSquared/issues/2357, but could not find a conclusive fix)
- [X]  I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
Did you test this situation before the 1.14 update?

**Comment by zachrocks22** [comment]
Yes. The same issue occurred on 1.13 paper spigot.

**Comment by AeSix** [comment]
https://github.com/IntellectualSites/PlotSquared/issues/2357

**Comment by zachrocks22** [comment]
Just wanted to reconfirm for latest 1.14.4 paper (Build 160) and latest PlotSquared (Build 317)

Also would like to add that it appears that when you enter a plot with the time flag, then change worlds, the world you changed to actually lets time pass but is reset to the value of the time flag in the plot you were just on every 20 or so ticks.

**Comment by AeSix** [comment]
I confirm this is an issue with Spigot 1.13.2 and P2 4.318
Appears "plot time" is actually stored on the player, and is not removed on /all/ occurrences of the player exiting the plot.
