### ISSUE TITLE
Merge bug (hole in plot)

### ISSUE THREAD

**Issue by Lusteroth** [IntellectualSites/PlotSquared#2420]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template

**[REQUIRED] PlotSquared Version Number:**  
PlotSquared (Version: PlotSquared-4.299) 
**[REQUIRED] Spigot/Paper Version Number:**  
Paper 1.14.3 is a build 126 
**[REQUIRED] Minecraft Version Number:** 
1.14.3
**Links to worlds.yml file and settings.yml file:**
https://pastebin.com/wCJ3An49
https://pastebin.com/1dN5Ypwk 
**[REQUIRED] Description of the problem:** 
 
I want to create a dungeon/hole below/under the roads. So I set the road-height to 55 and the other heights (wall, plot) to 64. Then the road-schematic correctly generates on top of the existing road (at 55). (Road is 64 blocks high after pasting the road-schematic)
 
But there's now a problem with the merge command. If you're merging four plots, a hole is generated in the middle of the merged plot. 
 
http://prnt.sc/oc42ny 
 
(Merging two plots works fine: https://prnt.sc/oc422o) 
 
I think there's a bug at pasting the intersection schematic, because the hole has exactly the sizes of it. The "old" streets are generated correctly 64 blocks high. 
 
Hope you can fix the bug soon.
 
**Any relevant console output or screenshots:** 
http://prnt.sc/oc42ny 
**Plugins being used on the server:**
 
**How to replicate:**
 
 
Create a plotworld (with my worlds.yml)
Create a road-schematic (9 blocks high)
Regenallroads
Merge four plots 
 
**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by Lusteroth** [comment]
Still happening in #300

**Comment by MattBDev** [comment]
Please share the commands that you ran to merge the plots

**Comment by AeSix** [comment]
@Lusteroth I think Matt wants the full command...
/p merge north 1, etc. 
In the order you did them, if you possibly remember them. 

Order matters, due to Minecraft's weirdness.

**Comment by Lusteroth** [comment]
I only used /p merge...

(Not just one time:
1. Flyed to unmerged plots which should be connected
2. Look at the merged plot(s)
3. Typed in /p merge
4. Repeat that until four plots are merged)

**Comment by AeSix** [comment]
Does this happen in breaking build 298?
https://ci.athion.net/view/Everything/job/PlotSquared-Breaking/

Build 299 changed intersection stuff...

**Comment by Lusteroth** [comment]
> Does this happen in breaking build 298?
> https://ci.athion.net/view/Everything/job/PlotSquared-Breaking/
> 
> Build 299 changed intersection stuff...

Yes...

**Comment by AeSix** [comment]
ultimately, a duplicate of https://github.com/IntellectualSites/PlotSquared/issues/2375
Closing.
