### ISSUE TITLE
Problem in Y coordinates

### ISSUE THREAD

**Issue by Leomixer17** [IntellectualSites/PlotSquared#2421]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number:** 
INFO [P2] >> PlotSquared (Version: PlotSquared-4.299)
INFO [P2] >> Authors: Citymonstret & Empire92 & MattBDev & dordsor21
INFO [P2] >> Wiki: https://github.com/IntellectualCrafters/PlotSquared/wiki
INFO [P2] >> Newest Version: development-builds

**[REQUIRED] Spigot/Paper Version Number:** 
git-Paper-126 (MC: 1.14.3)

**[REQUIRED] Description of the problem:** 
PlotSquared treats Y coordinates as if they were one block upper.

**How to replicate:** 
Configure a world and set height to X: the real height will be X+1

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
Is this still an issue with newer builds of Paper and P2? (Breaking builds)?
https://ci.athion.net/view/Everything/job/PlotSquared-Breaking/

**Comment by Leomixer17** [comment]
@AeSix Yes

**Comment by AeSix** [comment]
@Leomixer17 are you using the Y in the F3 screen?
The information provided in F3 is the block space location of the player's feet.  At least up to 1.13.2.

When selecting the top block of a fresh plot with worldedit, is it at X or X+1?

I'll be installing P2 on 1.14.4 sometime soon, but I'm not ready for that yet and cannot test until then.

**Comment by Leomixer17** [comment]
@AeSix when selecting with WorldEdit it gives me the right block

**Comment by AeSix** [comment]
Then there's no issue with the coordinates.  If your plot height is 64, and WE selects the top block of your plot as y=64, then there's no issue.  

I'm closing this.  If I mis-understood you, please explain in much more detail as if I'm as dense as bedrock and as intelligent as Microsoft and i'll re-open the ticket.
