### ISSUE TITLE
API 1.14

### ISSUE THREAD

**Issue by BlackTen** [IntellectualSites/PlotSquared#2425]
How get owner of plot in PlotAPI 1.14 and check isInPlot?

**Comment by Resi23** [comment]
Try this own method. Maybe not the best, but it works for my purposes

import com.github.intellectualsites.plotsquared.plot.object.Location;
import com.github.intellectualsites.plotsquared.plot.object.Plot;

public boolean isInPlot(Player p){
    Location loc = new Location(p.getLocation().getWorld().getName(),
            (int) p.getLocation().getX(),
            (int) p.getLocation().getY(),
            (int) p.getLocation().getZ(),
            p.getLocation().getYaw(),
            p.getLocation().getPitch());
    Plot plot = loc.getPlot();
    return plot != null;
}

**Comment by MattBDev** [comment]
Don't ask these questions here.
