### ISSUE TITLE
PlotSquared Error-Message

### ISSUE THREAD

**Issue by JH220** [IntellectualSites/PlotSquared#2428]
After installation of PlotSquared from 
https://www.spigotmc.org/resources/1177/
I received the following message:

https://pastebin.com/3vgjANq0
How can help me to fix the problem?

Best regards
Jan-Hendrik aka. JH220

**Comment by MattBDev** [comment]
You deleted the template and didn't even provide relevant information. This isn't a chat, if you want to get help immediately you should ask on discord.
