### ISSUE TITLE
Players can break blocks they aren't supposed to

### ISSUE THREAD

**Issue by xNitrate** [IntellectualSites/PlotSquared#2429]
**[REQUIRED] PlotSquared Version Number:** 4.298

**[REQUIRED] Spigot/Paper Version Number:** git-Paper-134

**[REQUIRED] Minecraft Version Number:** 1.14.3

**Links to worlds.yml file and settings.yml file:** 
https://athion.net/ISPaster/paste/view/e84df7c5b6f54902a68167c9797a2a14

**[REQUIRED] Description of the problem:** 
I just set it up and players are able to break blocks that they aren't supposed to. I don't have PlotMe installed like most other issues did.

**Any relevant console output or screenshots:** None.

**Plugins being used on the server:**
https://athion.net/ISPaster/paste/view/e84df7c5b6f54902a68167c9797a2a14

**How to replicate:** 
Download it. Put in plugin folder. Restart world. Do /plots setup. Set it up. Make that world your default world. Then, restart server. And wallah.

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
No. It's not a bug. It's you and your permissions plugin.
