### ISSUE TITLE
Please add lectern remove protection if enabled use flag for read (1.14)

### ISSUE THREAD

**Issue by andris155** [IntellectualSites/PlotSquared#2432]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number:** 
```
20.07 14:23:24 [Server] INFO [P2] >> PlotSquared (Version: PlotSquared-4.299)
20.07 14:23:24 [Server] INFO [P2] >> Authors: Citymonstret & Empire92 & MattBDev & dordsor21
20.07 14:23:24 [Server] INFO [P2] >> Wiki: https://github.com/IntellectualCrafters/PlotSquared/wiki
20.07 14:23:25 [Server] INFO [P2] >> Newest Version: development-builds
```

**[REQUIRED] Spigot/Paper Version Number:** 
This server is running Paper version git-Paper-134 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)

**[REQUIRED] Minecraft Version Number:** 
1.14.3

**Links to worlds.yml file and settings.yml file:** 

**[REQUIRED] Description of the problem:** 
Please add lectern remove protection if enabled use flag for read (1.14)

**Any relevant console output or screenshots:**

**Plugins being used on the server:**

**How to replicate:** 

1. Enable use flag for lectern.
2. Lectern removable.

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
https://ci.athion.net/view/Everything/job/PlotSquared-Breaking/

**Comment by AeSix** [comment]
Closing due to this being a feature request, not a bug report, and no response in 9 days.
