### ISSUE TITLE
Error while enabeling plugin

### ISSUE THREAD

**Issue by JoshuaPvP** [IntellectualSites/PlotSquared#2433]
**[REQUIRED] PlotSquared Version Number:** P² does not start

**[REQUIRED] Spigot/Paper Version Number:** Spigot -> 1.8.8

**[REQUIRED] Minecraft Version Number:** 1.8.8

**Links to worlds.yml file and settings.yml file:** P² does not start

**[REQUIRED] Description of the problem:** 

I want to install P² on my 1.8.8 server. I had installed Multiverse Core this works.
When i put the P² jar file in the plugins folder i will get this error:
https://hastebin.com/awasusaval.sql

**Any relevant console output or screenshots:**
https://hastebin.com/awasusaval.sql

**Plugins being used on the server:**
Multiverse Core -> v2.5.0-b727

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
"P² does not start" is not a version.  If you don't know what version you downloaded, then you need to reconsider running a server.  

Closing.  
Once you figure out which version you need to use (hint: a LEGACY version) you can edit your original post and re-open the ticket IF the issue continues.

**Comment by JoshuaPvP** [comment]
i downloaded the newest version of p²

**Comment by AeSix** [comment]
P2 4.x is NOT for 1.8 through 1.12.2.  P2 4.x is ONLY for 1.13+
If you had bothered reading the console / log, there is a message which specifically tells you this.
