### ISSUE TITLE
Crashes server

### ISSUE THREAD

**Issue by iTwitchTV** [IntellectualSites/PlotSquared#2434]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number:**  4.298

**[REQUIRED] Spigot/Paper Version Number:** 1.8.8

**[REQUIRED] Minecraft Version Number:** 1.8 - 1.14

**Links to worlds.yml file and settings.yml file:** 
 n/a

**[REQUIRED] Description of the problem:** 
I updated to the newest version of plotsquared on my server and it immediately crashes it before fully starting. But if I use a old version of plotsquared such as version 3.5.0u2 it will start the server fine.
**Any relevant console output or screenshots:**
n/a
**Plugins being used on the server:**

too many to list
**How to replicate:** 
 install spigot 1.8.8, install via version, install latest version of plot squared start up server

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
You're using the wrong version of P2 for your server.
Either update to 1.13.2+ or use the right version of P2.
https://ci.athion.net/view/Everything/job/PlotSquared-Legacy/

**Comment by iTwitchTV** [comment]
so what you're telling me is if I want my server to be 1.8 with 1.14 compatible I have to use plot squared from 2015

**Comment by AeSix** [comment]
What I am telling you is that PlotSquared 4.xxx is NOT going to work on anything older than 1.13.
Plain and simple.  If you would have bothered to load and read the page for which I linked, you would see that there are newer builds of PlotSquared for 1.8-1.12.2
