### ISSUE TITLE
Error while enabeling Plot²

### ISSUE THREAD

**Issue by JoshuaPvP** [IntellectualSites/PlotSquared#2436]
[REQUIRED] PlotSquared Version Number: 4.298

[REQUIRED] Spigot/Paper Version Number: Spigot -> 1.8.8

[REQUIRED] Minecraft Version Number: 1.8.8

Links to worlds.yml file and settings.yml file: P² does not start

[REQUIRED] Description of the problem:

I want to install P² on my 1.8.8 server. I had installed Multiverse Core this works.
When i put the P² jar file in the plugins folder i will get this error:
https://hastebin.com/awasusaval.sql

Any relevant console output or screenshots:
https://hastebin.com/awasusaval.sql

Plugins being used on the server:
Multiverse Core -> v2.5.0-b727

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
Wrong version.  Go read.  P2 version 4.x will NOT work on 1.8-1.12.2, it is ONLY for 1.13.2+
