### ISSUE TITLE
Null Spaming at a Road Generation 1.14.3

### ISSUE THREAD

**Issue by KleeSup** [IntellectualSites/PlotSquared#2437]
Hey Guys!

I want to Generate a new Roadschematic for my Plotworld. If I do /p createroadschematic and /p regenallroads, the plugins spams me many null's in my console (If I try to generate the roads). The error looks like: 

( null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null )

and this again and again and again. If the Plugin loads its's says to me: cant regenerate roadsschematics for this world!

My Spigot: latest 1.14.3 PaperSpigot
PlotSquared: PlotSquared-Bukkit-4.298.jar

I don't know what's happen but I hope you can help me!
Excuse me for my bad english 

Have a good day :D

**Comment by AeSix** [comment]
First, "latest" is not a version or build. 
Second; you're using an older build of PlotSquared.

Additionally, Spigot and Paper (which has not been called PaperSpigot in a long time) has 1.14.4 builds available.  

Please update and ensure you are following the instructions for creating road schematics properly.

**Comment by KleeSup** [comment]
So now I've updatet to latest Paper Version and PlotSquared from the builds, but:

( null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null )

(Error occurs while generate new roads via /p regenallroads. I wait until the road generation is ready and look if the roads was generatet)

**Comment by AeSix** [comment]
Post your log? 
From start to end of road regen, excluding any public IP addresses. 
gist.github.com :)

**Comment by MattBDev** [comment]
I :heart: null

**Comment by MattBDev** [comment]
Without any logs, this issue will be closed in 24 hours

**Comment by KleeSup** [comment]
Ive Postet the "error". It's spaming null in my console despite the fact that it works :/
It's no error like NullPointerException but just:

( null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null )

But in the end it works, the roads were generated :-)

**Comment by AeSix** [comment]
Good, then you'll have a gist full of the word null surrounded by other valid log entries.

**Comment by MattBDev** [comment]
24 hours have passed and no log was submitted. This issue is now closed.
