### ISSUE TITLE
schematic Inoperation

### ISSUE THREAD

**Issue by Eas-zhaoyixuan** [IntellectualSites/PlotSquared#2440]
https://athion.net/ISPaster/paste/view/f5a8e6952bfe4f0e974e0c99b90747ad

When I /p2 auto, everything looks normal, but schematic architecture won't come into being.

**Comment by AeSix** [comment]
You need to be more specific with your problem. 
"it don't work" isn't being specific, or helpful at all.

**Comment by AeSix** [comment]
it's been 5 days with no response. closing ticket.
