### ISSUE TITLE
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled

### ISSUE THREAD

**Issue by kaniesha** [IntellectualSites/PlotSquared#2446]
**[REQUIRED] PlotSquared Version Number:** 
4.298

**[REQUIRED] Spigot/Paper Version Number:** 
git-paper-147

**[REQUIRED] Minecraft Version Number:** 
1.14.4

**Links to worlds.yml file and settings.yml file:** 
worlds: https://gist.github.com/kaniesha/078d55a63b22030a895cf3702f8f15a9
settings: https://gist.github.com/kaniesha/d95d180455d9b8ea8de81aa68c854b38

**[REQUIRED] Description of the problem:** 
I was going through logs when I saw this big chunk of error text:
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
https://gist.github.com/kaniesha/10fd3b6ad5e72f50802f5e684eea1b4d

**Any relevant console output or screenshots:**

**Plugins being used on the server:**
BetterRTP, CMI, Chestsort, CoreProtect, DeluxeChat, DiscordMinecraft, GriefPrevention, GPFlags, Illegalstack, Jobs, LuckPerms, MCMMO, WorldEdit, etc

**How to replicate:** 
I'm not sure how I would replicate the issue besides simply restarting the server.

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by noahkrause** [comment]
Having this issue as well, been having it for years. Seems like this error is tied with plot ownership being changed to a random player or nobody at all, and some unmerging.
https://gist.github.com/noahkrause/8af0d2c612cc4ece664139670035b959

**Comment by AeSix** [comment]
1.12.2 (noahkrause) and 1.14.4 (kaniesha) - updating tag to reflect this.

**Comment by AeSix** [comment]
This is related to the older ticket here:
https://github.com/IntellectualSites/PlotSquared/issues/2047

**Comment by Sauilitired** [comment]
To be clear, this is still an issue in 1.12, but the issues were merged in a funny way. I'll re-open and remove the 1.14 label.

**Comment by AeSix** [comment]
To be additionally more clearer:
PlotSquared for 1.12.2 and older, and for non-bukkit lineage servers are considered legacy and will have minimal to no support.  Issues relating to these versions may still be resolved in the future, however developer time and effort is currently focused on current versions of Spigot and Paper.   Anyone who is capable and willing is welcome to PR fixes for legacy versions of PS.  As such, this issue will remain open for now, but is a low priority for the PlotSquared developers.

**Comment by Sauilitired** [comment]
This is fixed in v4 (1.13+).
