### ISSUE TITLE
Specific player cant mine specific 3x3 area on their plot

### ISSUE THREAD

**Issue by JoeDon16** [IntellectualSites/PlotSquared#2447]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number:**  PlotSquared-19.3.12-2f882b5-724

**[REQUIRED] Spigot/Paper Version Number:** Spigot 1.9.4

**[REQUIRED] Minecraft Version Number:** 1.9.4 with some players on ViaVersion/ViaRewind

**Links to worlds.yml file and settings.yml file:** 
 Worlds: https://paste.md-5.net/zawurafuca.cs Settings: https://paste.md-5.net/udimebewor.bash

**[REQUIRED] Description of the problem:** A random 3x3x(skylimit/groundlimit) section of blocks on this one player's plot is unbreakable by them.

**Any relevant console output or screenshots:** [![Screenshot from Gyazo](https://gyazo.com/f2ee186ce956c452fa8e4579d130c112/raw)](https://gyazo.com/f2ee186ce956c452fa8e4579d130c112) The dark green clay or anything above/below it cant be broken, and blocks cant be placed on it either.

**Plugins being used on the server:**
---

**How to replicate:** 
No idea, but I believe on this same plot another different player had the same issue.

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
using FAWE or WE, select the area and //regen
This happens on non-plotsquared servers for me as well.  

I believe there's an invalid entity or something that had been placed there, or something. 

Anyways, this isn't a plotsquared issue per se. 
I'll leave this open for time being though.  If regen don't work, one of the devs may need to take a look.

**Comment by JoeDon16** [comment]
> using FAWE or WE, select the area and //regen
> This happens on non-plotsquared servers for me as well.
> 
> I believe there's an invalid entity or something that had been placed there, or something.
> 
> Anyways, this isn't a plotsquared issue per se.
> I'll leave this open for time being though. If regen don't work, one of the devs may need to take a look.

Did not work, very weird. I don't know what else could have caused this, especially only on one plot.

**Comment by AeSix** [comment]
I've done a bit more research into this.  It seems it may be a partially corrupt chunk. You may be able to resolve this with https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-tools/1261480-minecraft-region-fixer

**CAUTION: USE A COPY OF YOUR SERVER!!!**  This tool can remove portions of your region/world in order to resolve issues.  

I'm closing this issue now, as it is not a P2 specific issue.  If the above still does not work for you, You may have to replace the region file. be careful if you have to save builds as schematics to replace into the new file, as you may inadvertently re-introduce the issue.
