### ISSUE TITLE
Activate PVE with PVP in False

### ISSUE THREAD

**Issue by JavituRec** [IntellectualSites/PlotSquared#2448]
**PlotSquared Version Number:**
![plottt](https://user-images.githubusercontent.com/10663192/62146656-22f9b580-b2f6-11e9-8736-6d393789f03b.png)

**Spigot/Paper Version Number:** 
1.14.4

**Description of the problem:** 

I try activate PVE in all world of plots but I only found how add flag to a one plot.

Sincerely.

**Comment by N0tMyFaultOG** [comment]
Follow the template given
