### ISSUE TITLE
PVE ins plots with PVP in False

### ISSUE THREAD

**Issue by JavituRec** [IntellectualSites/PlotSquared#2449]
**PlotSquared Version Number:**
![plottt](https://user-images.githubusercontent.com/10663192/62146656-22f9b580-b2f6-11e9-8736-6d393789f03b.png)

**Spigot/Paper Version Number:** 
1.14.4

**Description of the problem:** 

I try activate PVE in all world of plots but I only found how add flag to a one plot.

Sincerely.

**Links to worlds.yml file and settings.yml file:** 
Settings: https://pastebin.com/260X6uhn
Worlds: https://pastebin.com/HrcjwwPH

**Checklist**:
- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
If you want to enable PvE and/or PvP for the server, you do it through server config files.  If you want to enable PvE/PvP for each plot, use the flags: section at the very bottom of your PlotSquared Worlds file. Note that anyone with permission to change plot flags can remove this, also note that PvP has to be enabled through the server as well.  

If you're using a single server for mixed worlds, where one world is not to have PvE/PvP - then you will need to use WorldGuard for that world to disable PvE/PvP.  

Closing ticket.  Please read the wiki for how to use the Worlds files, other PlotSquared features, and the wikis for your server, WorldGuard, etc.
