### ISSUE TITLE
PVE only for owner of the plot

### ISSUE THREAD

**Issue by JavituRec** [IntellectualSites/PlotSquared#2454]
**PlotSquared Version Number:**
![plottt](https://user-images.githubusercontent.com/10663192/62146656-22f9b580-b2f6-11e9-8736-6d393789f03b.png)

**Spigot/Paper Version Number:** 
1.14.4

**Description of the problem:** 

The pve is active in entire world of plots. I negate permission "plots.admin.pve.unowned" for kills animals

Sincerely.

**Links to worlds.yml file and settings.yml file:** 
Settings: https://pastebin.com/cEXxsBBL
Worlds: https://pastebin.com/Vvv0X6TD

**Checklist**:
- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Do not delete the format if you want to gather support.
