### ISSUE TITLE
PVE only for owner of the plot

### ISSUE THREAD

**Issue by JavituRec** [IntellectualSites/PlotSquared#2455]
**[REQUIRED] PlotSquared Version Number:**  ![plottt](https://user-images.githubusercontent.com/10663192/62146656-22f9b580-b2f6-11e9-8736-6d393789f03b.png)

**[REQUIRED] Spigot/Paper Version Number:** 
 1.14.4

**[REQUIRED] Minecraft Version Number:** 
1.14.4

**Links to worlds.yml file and settings.yml file:** 
 Settings: https://pastebin.com/cEXxsBBL
Worlds: https://pastebin.com/Vvv0X6TD

**[REQUIRED] Description of the problem:** 

My users can kill animals in plots claimed for other users but not in road or unowned. The pve is active in entire world of plots. I negate permission "plots.admin.pve.unowned" and "plots.admin.pve.other" but the user can kill animals in other plots.

Sincerely.

**Any relevant console output or screenshots:**

**Plugins being used on the server:**

**How to replicate:** 

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
User error. Flags are meant for plots only. Flags don't work on roads and won't work on roads.

**Comment by JavituRec** [comment]
That is not my question. With the pve activated in plots, users can kill animals in plots that are not their property, how can I solve this?

**Comment by AeSix** [comment]
"not their property" - afaik PlotSquared does not have a concept of animal ownership.  Unless you mean nametagged mobs? 

If you want help, you need to be specific and stop making people guess what you mean.
