### ISSUE TITLE
 /plot toggle titles is not considered to show the titles

### ISSUE THREAD

**Issue by jewome62** [IntellectualSites/PlotSquared#2456]
# Bug report template 
**[REQUIRED] PlotSquared Version Number:** Plotsquared-4.309

**[REQUIRED] Spigot/Paper Version Number:** Paper 1.13.2 Build 641

**[REQUIRED] Minecraft Version Number:**  1.13.2

**Links to worlds.yml file and settings.yml file:** 
[worlds.yml](https://hastebin.com/dalaweyegi.sql)
[settings.yml](https://hastebin.com/abolopajog.bash)

**[REQUIRED] Description of the problem:** 
`/plot toggle titles` is not considered to show the titles

**Plugins being used on the server:**
 Plugins (30): AdvancedPortals, AntiBuild*, BestViewDistance*, BKCommonLib, BuildersUtilities, BungeeTabListPlus*, CreativeNbtControl, DisableJoinMessage*, dynmap*, FastAsyncVoxelSniper, FastAsyncWorldEdit, FlySpeed*, ForceField*, goBrush, goPaint, LightCleaner, LOTM-ForceGameMode*, LuckPerms, Multiverse-Core, NoDamage, PermBridge*, PlaceholderAPI*, PlotSquared, PremiumVanish, ProtocolLib*, SpawnJoin*, Vault, ViaVersion*, VIPJoinSlots*, WorldEdit

**How to replicate:** 

- Create plot world
- Claim some plot
- See the title
- try `/plot toggle titles` the command say 'disabled'
- the title is show

**Checklist**:
- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
just testing, and what is reported happens for me as well.
```
/plot toggle titles 
```
results in the holographic on-screen plot titles being shown, regardless if the command says disabled or enabled.

**Comment by AeSix** [comment]
This is still an issue with P2 4.318 with  Paper 1.13.2 build 626

In the PlotSquared/config/settings.yml file I disabled titles,  the command now has no effect to enable the titles (as expected, just making sure something didn't get flipped /there/)

**Comment by jewome62** [comment]
@Sauilitired Why do you close issue ? This is fixed ?

**Comment by N0tMyFaultOG** [comment]
Yep, it's fixed in https://github.com/IntellectualSites/PlotSquared/commit/8ab10de4ad3cd39debcd8f9d620f4b88c1761ef3, give PlotSquared an [update](https://ci.athion.net/job/PlotSquared-Breaking/lastSuccessfulBuild/artifact/target/PlotSquared-Bukkit-4.319.jar) to receive the latest patch...

**Comment by jewome62** [comment]
Ok, Thanks :+1:
