### ISSUE TITLE
Performance problem with PlotSquared::Task: com.github.intellectualsites.plotsquared.plot.commands.Auto$1

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/PlotSquared#2457]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number:**  PlotSquared-4.298

**[REQUIRED] Spigot/Paper Version Number:** Paper Build 639

**[REQUIRED] Minecraft Version Number:** 1.13.2

**Links to worlds.yml file and settings.yml file:** 
worlds.yml: https://pastebin.com/4QUjDJHn
settings.yml https://pastebin.com/JQu1Vraj

**[REQUIRED] Description of the problem:** 
This task in particular "PlotSquared::Task: com.github.intellectualsites.plotsquared.plot.commands.Auto$1 (Single)" seems very heavy and shows up in timings often. I was wondering on if it was possible to optimize this?
Timings with 170 players online: https://timings.aikar.co/?id=d47a5766959f4cd3bdf80c4633185a78#timings
Timings with 100 players online: https://timings.aikar.co/?id=14e5803f0f324aca8cc4fbbe7493c754
Maybe this is because PlotSquared is not using the paper async chunk loading? I see sync chunk loads being caused by this task in the timings.

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
Out of curiosity, does using WorldEdit 7 result in the same/similar/better/worse?

**Comment by SecretlyJealous** [comment]
I can't actually use normal worldedit on my server, it's not efficient enough for my player count. I use fastasyncworldedit and it also seems to have had a performance regression when I moved to 1.13.2.

Here's an example of my server on 1.12.2 using fastasyncworldedit and plotsquared: https://timings.aikar.co/?id=517efdac42604732bebd40552c0b195b. I'll probably be creating a seperate ticket with information about how fastasyncworldedit is not efficient on 1.13 in a few days too.
