### ISSUE TITLE
Unordered Flags

### ISSUE THREAD

**Issue by N0tMyFaultOG** [IntellectualSites/PlotSquared#2462]
# Bug report template

**[REQUIRED] PlotSquared Version Number:**  4.324

**[REQUIRED] Spigot/Paper Version Number:** Paper 153

**[REQUIRED] Minecraft Version Number:** 1.14.4

**Links to worlds.yml file and settings.yml file:** //
 

**[REQUIRED] Description of the problem:** 
Some flags are not assigned to a sub category

**Any relevant console output or screenshots:**
![](https://i.imgur.com/CTYgV2e.png)

**Plugins being used on the server:** //

**How to replicate:** 
Run `/plot flag list` and look at the top of the list
The `keep` flag is actually not assigned to any category, I'm not sure what i actually does, since it accepts boolean, ints and other values. https://github.com/IntellectualSites/PlotSquared/blob/6d0849eb6635c5487571abe62e45768fda7d4f1f/Core/src/main/java/com/github/intellectualsites/plotsquared/plot/flag/Flags.java#L98

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
The keep flag was designed to have its own category since it can accept more than one value. It can set an expiration time for a plot, set it to already be expired, or not be expired. I don't know why the price flag is like that.

**Comment by N0tMyFaultOG** [comment]
The price flag is the only DoubleFlag, I'm not quiet familiar how flags are registered, but it should create their own category 🤔
