### ISSUE TITLE
PlotSquare FAWE/AWE API Usage Problem

### ISSUE THREAD

**Issue by Legendbender** [IntellectualSites/PlotSquared#2466]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number:PlotSquared-Legacy 19.08.12-aee4ebc-778** 

**[REQUIRED] Spigot/Paper Version Number:Paper 1.12.2**

**[REQUIRED] Minecraft Version Number:** 

**Links to worlds.yml file and settings.yml file:** 

**[REQUIRED] Description of the problem: Have a new plugin that saves a place as a schematic and reloads the schematic but while PlotSquare is loaded and enabled on the server, i get that log and the new plugin doesnt work so author told me to report that. **

**Any relevant console output or screenshots:https://file.properties/paste/radinabote.bash**

**Plugins being used on the server:**

**How to replicate:AWE or FAWE the new plugin works with, while PlotSquared is loaded, the command usage gives the error log** 

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Seems like an improper usage of schematics, report it to the author of `BendingArenaManager `, it has nothing to do with PlotSquared.

**Comment by Legendbender** [comment]
I need to know if PlotSquared changes WE methods and stuff because the author tried some things and said it has something to do with `BukkitWorld (world edit)`

**Comment by AeSix** [comment]
https://github.com/IntellectualSites/PlotSquared/wiki/Developer-Documentation
Yes, there is a discord. https://i.imgur.com/eupHfht.png

You can try using WorldEdit instead of FAWE, but honestly, the dev needs to fix the plugin.

**Comment by MattBDev** [comment]
@Legendbender I'll keep it simple, no.
