### ISSUE TITLE
Changing name allows for more plots than allowed

### ISSUE THREAD

**Issue by Zaph-x** [IntellectualSites/PlotSquared#2467]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number:** 
`17.08 11:36:52 [Server] Craft Scheduler Thread - 4612/INFO [P2] >> PlotSquared (Version: PlotSquared-4.306)`

**[REQUIRED] Spigot/Paper Version Number:** 

`17.08 11:36:07 [Server] Server thread/INFO This server is running CraftBukkit version git-Spigot-ea7e48b-368f4e9 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)` 

**[REQUIRED] Minecraft Version Number:** 
1.14.4

**Links to worlds.yml file and settings.yml file:** 

Worlds.yml: https://hastebin.com/enuguramon.yaml
Settings.yml: https://hastebin.com/wilonumixa.yaml

**[REQUIRED] Description of the problem:** 
Recently it was reported by one of the players on the server I represent, that if you change your in-game name on Mojang's end, you're able to claim additional plots. Running `/plot i` on the current plot, shows the updated name. The sign on the plot shows the old name and the player is able to claim a new plot.

**Any relevant console output or screenshots:**

**Plugins being used on the server:**

`17.08 11:43:43 [Server] Server thread/INFO Plugins (41): FlyingCarpet, CoreProtect, LuckPerms, RedstoneCore, OinkPatch, FastAsyncWorldEdit, WorldEdit, RocketBow, MineableSpawners, WorldBorder, OinkUtils, Votifier, WorldGuard, ProtocolLib, OinkVotifier, LibsDisguises, OinkChannels, OinkDonationClaim, OfflineTP, Dizcord, BlocksHub, LagMonitor, mcMMO, PreventItems, ServerListPlus, Vault, BanLog, OinkTrade, Essentials, Matrix, PerWorldInventory, HeadDatabase, PlotSquared, Multiverse-Core, EssentialsChat, Multiverse-Portals, EssentialsSpawn, EnjinMinecraftPlugin, Holograms, Factions, ChatControl`

**How to replicate:** 

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
If this is true, which it absolutely shouldn't be since we test this all the time, it may be a server configuration issue.

**Comment by AeSix** [comment]
If your users have an offline UUID on the game, it needs to be managed appropriately. 
This is the only way *I* see for this to happen.  

If you are positive that your users are not being assigned offline UUIDs please provide the startup section of the server log. 

I will be building my 1.14.4 PlotSquared server sometime in the near future and will also be changing the name on one of my accounts and may be able to test this, if you confirm that the players are using authentic UUIDs.

**Comment by Zaph-x** [comment]
I'll get a larger test sample for this, however as I don't have multiple accounts I'm relying on some of the players on the server to change their name.

When I get back to my pc I'll get the startup log and post it here as well

**Comment by N0tMyFaultOG** [comment]
Unable to reproduce with LuckPerms.
