### ISSUE TITLE
Error when trying to generate chunk

### ISSUE THREAD

**Issue by ChimpGamer** [IntellectualSites/PlotSquared#2468]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number:**
17.08 21:59:44 [Server] INFO [P2] >> PlotSquared (Version: PlotSquared-4.329)
17.08 21:59:44 [Server] INFO [P2] >> Authors: Citymonstret & Empire92 & MattBDev & dordsor21
17.08 21:59:44 [Server] INFO [P2] >> Wiki: https://github.com/IntellectualSites/PlotSquared/wiki
17.08 21:59:44 [Server] INFO [P2] >> Newest Version: development-builds

**[REQUIRED] Spigot/Paper Version Number:** 
17.08 22:00:16 [Server] INFO This server is running Paper version git-Paper-642 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
17.08 22:00:16 [Server] INFO Previous version: git-Paper-641 (MC: 1.13.2)
17.08 22:00:16 [Server] INFO Checking version, please wait...
17.08 22:00:17 [Server] INFO You are running the latest version

**[REQUIRED] Minecraft Version Number:**
1.13.2

**Links to worlds.yml file and settings.yml file:** 
Settings: https://pastebin.com/UkJASqip
Worlds: https://pastebin.com/FmU75a2a

**[REQUIRED] Description of the problem:** 
The error is my problem. It's spamming too much and is causing massive log files.

**Any relevant console output or screenshots:**
N/A

**Plugins being used on the server:**
N/A

**How to replicate:** 
Yea, I've no idea. These error's occurred since I updated to the latest build of PlotSquared.

Error: https://pastebin.com/raw/b1rVZuU8

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
How is **_Any relevant console output or screenshots:_** not applicable? You linked to the error in the _**How to replicate**_ section.
Anyways, you took the risk of using the breaking branch which is considered unstable. If you use this branch you need to keep up with updates. Build 326 was removed for breaking compatibility with other plugins. Please update.

**Comment by ChimpGamer** [comment]
Build 329 is the latest build... And I'm using that build...

**Comment by MattBDev** [comment]
Use the next build.

**Comment by ChimpGamer** [comment]
I'll try this. Thanks for the quick respond!
