### ISSUE TITLE
Item Frames Bug

### ISSUE THREAD

**Issue by Hajatoby** [IntellectualSites/PlotSquared#2471]
All players can take the items from Allen Item Frames. Please fix. That only plot owners and helpers can remove them. Nukkit

**Comment by Hajatoby** [comment]
Nice Support ... Tzzzz

**Comment by N0tMyFaultOG** [comment]
If you want support, open a ticket and fill out the template properly

**Comment by Hajatoby** [comment]
Findest du dass nicht Peinlich? Alle Infos sind vorhanden und der Bug besteht seit 8 Monaten und ist mehrfach gemeldet worden.

**Comment by N0tMyFaultOG** [comment]
If you don't care to fill out a simple template, which allows us to reproduce issues, we don't care to bother with you too.
