### ISSUE TITLE
Random Crash When Leaving Vanished Mode

### ISSUE THREAD

**Issue by zachrocks22** [IntellectualSites/PlotSquared#2472]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number:**  PlotSquared 4.329

**[REQUIRED] Spigot/Paper Version Number:**  Paper Build 172

**[REQUIRED] Minecraft Version Number:** 1.14.4

**[REQUIRED] Description of the problem:**  Randomly, after exiting vanished mode with Essentials in the plotworld, a stack trace was thrown and the server crashed. 

**Any relevant console output or screenshots:**
[https://pastebin.com/raw/RmT7sHdS](url)

**May relate to Issue:** #2468 
This issue was fixed the latest version, and I have since updated, but I'm not 100% sure if that issue is the exact same or not.

**Settings.yml File:** https://pastebin.com/raw/1ue2rjZr
**Worlds.yml File:** https://pastebin.com/raw/ffRQWWic

**Plugins being used on the server:** EssentialsX, VoidGenerator, Citizens, HolographicDisplays, ProtocolLib, CoreProtect, WorldEdit, WorldGuard.

**How to replicate:**  I myself am unable to replicate this issue.

**Checklist**:
- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report (Use Search)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
This issue is already fixed. You need to make sure you are up to date on breaking builds if you are submitting an issue about them.
