### ISSUE TITLE
Item Frame Bug

### ISSUE THREAD

**Issue by Hajatoby** [IntellectualSites/PlotSquared#2473]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number:**  PlotSquared-19.7.11-ec789da-772 

**[REQUIRED] Nukkit Version Number:** Nukkit git-6e72c37

**[REQUIRED] Minecraft Version Number:** 1.12.0 

**Link World.yml:** https://pastebin.com/cFikW56V
**Link Settings.yml:** https://pastebin.com/4KXmUqra

**[REQUIRED] Description of the problem:** All players can take the items from all Item Frames. Please fix. That only plot owners and helpers can remove them. Nukkit 

**How to replicate:** 
Put an item frame on a plot and insert an item. As another player go to the GS and take that item out.

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
Please clarify what an "Allen item frame" is. 
Is this from another plugin?  A bad translation?

**Comment by Hajatoby** [comment]
Sorry Google translate.

**Comment by Hajatoby** [comment]
push?

**Comment by Zeanon** [comment]
I know I'm no Dev of PS, but if I find the time, I'll make a pull request and try to fix it.

**Comment by Hajatoby** [comment]
Thanks

**Comment by Hajatoby** [comment]
The bug has been around for 7 months, but the developers of PS are not shit about it

**Comment by N0tMyFaultOG** [comment]
> The bug has been around for 7 months, but the developers of PS are not shit about it

You reported the issue on August the 19th. So 2 months and a bit passed by, if you encountered the issue previously and did not report them, there is not much anyone can help you with.

Nukkit issues are generally labeled as Low Priority, our focus lays on bukkit versions. Nukkit issues are either community fixed or done if someone is really bored and has lots of spare time, since the platform is marked as legacy and not actively developed by us.

**Comment by MattBDev** [comment]
I would also like to mention that Nukkit has a very poor API so some issues just can't be fixed. This one doesn't apply but I felt like mentioning it anyways.

**Comment by AeSix** [comment]
@Zeanon - a fix would be wonderful!  I'm sure once you get it done, tested and PR'd, the devs will look at it and merge if they feel comfortable that it won't break other things.  

All of the devs are volunteers, so simply developing for PlotSquared would make you a dev :)

These are the more pertinent previous tickets related to item frames:
https://github.com/IntellectualSites/PlotSquared/issues/220
#432
#1761 #1766
#1798 / #1799
#2050 & #2169

All similar issues. There's probably notes in each and every one.  The more relevant ones are 2050 and 2169 I think, but the older ones may also give insight into the issue.
