### ISSUE TITLE
RoadSchematic doesn't work

### ISSUE THREAD

**Issue by NoFace851** [IntellectualSites/PlotSquared#2475]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number: PlotSquared-4.298) 

**[REQUIRED] [20:53:40 INFO]: This server is running Paper version git-Paper-171 (MC: 1.14.4)
 (Implementing API version 1.14.4-R0.1-SNAPSHOT) 

**[REQUIRED] Minecraft Version Number:1.14.4 

**Links to worlds.yml file and settings.yml file:** 
world.yml https://pastebin.com/Mu8X3a0R
settings.yml https://pastebin.com/ARACHsMh

**[REQUIRED] Description of the problem:

After i lost my template i was doing for more than 3 hours, i deleted that world and tried to do a simple one, just changing the blocks on the road and the sidewalk but apparently i can't even do that since it doesn't work. Just did this template: https://imgur.com/a/UC5ozqA and after that i did /p createroadschematic and went to another claim and did /p debugroadregen plot and THAT is what happened on the plot i did it: https://imgur.com/a/8ODcUwa

Now, WTF?

**Any relevant console output or screenshots:**

**Plugins being used on the server:**
Plugins (52): AutoMessager, Autorank, ChatControl, ChestShop, C
laimFly, ClearLag, ColoredSigns*, CommandSigns, CompatNoCheatPlus*, ConditionalC
ommands*, DeathMessagesPrime, DragonSlayer, DragonTimer, EditableSign, Essential
s, GetSpawners, GriefPrevention, HolographicDisplays, IllegalStack, JukeBox, Las
tHolo*, mcMMO, Minepacks, MobHeads, Multiverse-Core, NametagEdit*, NoCheatPlus,
NoteBlockAPI, OldCombatMechanics, OreAnnouncer, PermissionsEx*, PixelVip*, Place
holderAPI*, PlotSquared, PluginLibrary*, ProtocolLib, PvPToggle, RankGrantPlus,
SecurityVillagers, SetTheSpawn, Statz, UltimateChat, UltimateStacker, Vault, Via
Version*, VoidGenerator, WorldBorder, WorldEdit, WorldEditSUI, WorldGuard, World
GuardExtraFlags, XPBoost* --->

**How to replicate:** 
just create a template and try to debug it to other plots

**Checklist**:

- [x] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Go a bit over the edges with your schematic and run `/plor crs` again. You made it too small

**Comment by NoFace851** [comment]
yeah that just broke the world

https://imgur.com/a/8ivp3wD

**Comment by N0tMyFaultOG** [comment]
You regenned it too high

**Comment by AeSix** [comment]
This is another symptom of https://github.com/IntellectualSites/PlotSquared/issues/2349 at worse, and a user error at best. 
Tagged previous ticket for developer reference.  Closing ticket.
