### ISSUE TITLE
Question about merged plot ids

### ISSUE THREAD

**Issue by Leomixer17** [IntellectualSites/PlotSquared#2477]
I need to have the plot 0;0 with all plots around it merged, and this plot should still have the id 0;0, I tried all ways to merge these plots, but in any case the mega-plot id is 0;-1.
In which way merged plot ids are determinated?

**Comment by AeSix** [comment]
Even though you're not reporting a bug, per se`, it would still help to have the proper information, in case there were changes between versions or arch types. 

@Leomixer17 Please provide the information from the template.

**Comment by Leomixer17** [comment]
@AeSix 
Previous version: git-Paper-167 (MC: 1.14.4)
PlotSquared (Version: PlotSquared-4.301)

**Comment by AeSix** [comment]
I'm fairly certain the behavior is to always use the ID of the north east most (+x/-y) plot for the merged plot ID. However, it's always the furthest corner from block grid 0x/0y in NE, NW, SE or SW direction (which ever it is) In 1.13.2, at least, each individual plot can be accessed by it's ID, meaning you can still do ```/p visit 0;0``` even if the info says that's a different ID.  I do not believe this has been changed for 1.14.4.

Alternatively, you can merge the plots around 0;0, then remove the road between that doughnut shaped plot and the center plot, effectively giving you a single large merged plot. 

@Leomixer17  If you would like to request a change in this behavior, it should be done using the PlotSquaredSuggestions issue tracker.  Closing issue.
