### ISSUE TITLE
Regenallroads not regenerating all roads

### ISSUE THREAD

**Issue by NoFace851** [IntellectualSites/PlotSquared#2478]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number:**  
[16:18:05 INFO]: [P2] >> PlotSquared (Version: PlotSquared-4.298)

**[REQUIRED] Spigot/Paper Version Number:** 
 
[16:18:54 INFO]: This server is running Paper version git-Paper-174 (MC: 1.14.4)
 (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**[REQUIRED] Minecraft Version Number:** 
1.14.4

**Links to worlds.yml file and settings.yml file:** 

https://pastebin.com/C3MDF9AA and https://pastebin.com/p2yc8BBi

**[REQUIRED] Description of the problem:** 
After i do "p regenallroads" in the cmd it should regen all roads in the world, but it doesn't, there's a couple of claims that don't regenerate. I did p regenallroads 2 times already
The road i did /p createroadschematic: https://imgur.com/a/KSmBlDr
A couple of roads around this one: https://imgur.com/a/lTY2dHO (there's a lot more)
The rest of the world: https://imgur.com/a/ndRMUIK

**Any relevant console output or screenshots: No Errors

**Plugins being used on the server:**

**How to replicate:** 

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by NoFace851** [comment]
if i go to one of these empty plots and do "/p debugroadregen plot" it says "success" but nothing happens

**Comment by AeSix** [comment]
https://github.com/IntellectualSites/PlotSquared/issues/2349

Another symptom of schematics not working properly.  Closing ticket, tagging conglomerate issue.
