### ISSUE TITLE
Changes/column analysys problem

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [IntellectualSites/PlotSquared#2480]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number:**  4.298

**[REQUIRED] Spigot/Paper Version Number:** 
paper b500

**[REQUIRED] Minecraft Version Number:** 
1.13.2
**Links to worlds.yml file and settings.yml file:** 
https://pastebin.com/rTcb5jUw
https://pastebin.com/mLqna9Tr

**[REQUIRED] Description of the problem:** 
If im using /plot debugexec analyze it always says 25600,0 on every plot
**Any relevant console output or screenshots:**

**Plugins being used on the server:**

**How to replicate:** 

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
Please update Paper and use the PlotSquared-breaking branch to see if this has already been resolved.  You're using old versions of these.

**Comment by Sauilitired** [comment]
This hasn't been updated in nearly a year. We'll have to assume it has been fixed.
