### ISSUE TITLE
the "/plot swap" command doesn't seem to work but still gives the "plots were swapped successfully" message.

### ISSUE THREAD

**Issue by MothGirlMusic** [IntellectualSites/PlotSquared#2481]
**[REQUIRED] PlotSquared Version Number:** PlotSquared (Version: PlotSquared-4.298)

**[REQUIRED] Spigot/Paper Version Number:** 
This server is running CraftBukkit version git-Spigot-798ea6a-368f4e9 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**[REQUIRED] Minecraft Version Number:** 
1.14.4

**Links to worlds.yml file and settings.yml file:** 
https://paste.mothnet.xyz/?e7536d9f5055fe4c#vk94v8u+fyN7Op9VVe7+Hl+6LmPUB+V+SA/YD4dkppM=

and 

https://paste.mothnet.xyz/?49c908d8eae87b72#aeGcnxlRXAVGsmenOR5C+pSKWGXtcyTTS8YaUUxans8=

**[REQUIRED] Description of the problem:** 
the "/plot swap" command doesn't seem to work but still gives the "plots were swapped successfully" message. [it does say the two regions are overlapping but they aren't. they're two small plots that haven't been merged or anything. so they should be able to swap just fine.]

**Any relevant console output or screenshots:**
![Screen Shot 2019-08-25 at 03 50 29](https://user-images.githubusercontent.com/1746550/63647199-a6d37180-c6eb-11e9-83c8-0dc1db3db90b.png)

**Plugins being used on the server:**
CMI, Plots, WorldEdit, DiscordSRV, BossShopPro, Vault, PlaceholderAPI, Votifier, VotingPlugin

**How to replicate:** 
figure out which plot you want to swap.. then go to another plot and do /plot swap [plotID] and watch it not work but say its working.

**Checklist**:
- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by MothGirlMusic** [comment]
just want to make clear that the plots are NOT merged. just two 1x1 plots trying to be swapped. doesn't matter how close or far they are from each other, the "the proposed areas are not allowed to overlap" messages ALWAYS pops up. and then it ALWAYS says its been successfully swapped. no matter if the plots are actually overlapping or not.

**Comment by AeSix** [comment]
Duplicate. Closing. Please ensure you search the issues before posting.
https://github.com/IntellectualSites/PlotSquared/issues/2282

**Comment by MothGirlMusic** [comment]
@AeSix this is not a duplicate of that bug. in that bug the plots swap but the original owners' accounts still owned the swapped plots.. 

my bug, nothing happens. the plots aren't swapped and nothing happens to the owners.

completely different bug.
