### ISSUE TITLE
Over 7,000 minecarts

### ISSUE THREAD

**Issue by LoXR** [IntellectualSites/PlotSquared#2482]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number:** 
PlotSquared version 4.321
**[REQUIRED] Spigot/Paper Version Number:** 

git-Paper-642 (MC: 1.13.2)
**[REQUIRED] Minecraft Version Number:** 
1.12.2
**Links to worlds.yml file and settings.yml file:** 

**[REQUIRED] Description of the problem:** 
Someone has put over 7,000 minecarts in their plot which always crashes players.
**Any relevant console output or screenshots:**
Thought to report this aswell: https://pastebin.com/SwsArJ6G
Minecart timings report: https://timings.aikar.co/?id=fc813fd9ce804be587e2b54c4910be8e
**Plugins being used on the server:**

**How to replicate:** 

Please dont replicate, but wondering if there is a way to limit carts in claims.
**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
This is an administrative issue.  Please check your configuration files.  
Additionally, you've stated two different versions, suggesting you're using 1.12.2 clients on 1.13.2 servers, which itself has known issues. 

If you need assistance with configuration, join the discord and ask there.  Wait patiently.  People have lives.
