### ISSUE TITLE
Conflict with Parties 

### ISSUE THREAD

**Issue by fmohican** [IntellectualSites/PlotSquared#2485]
**[REQUIRED] PlotSquared Version Number:** [P2] >> PlotSquared-4.298

**[REQUIRED] Spigot/Paper Version Number:** git-Paper-175 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**[REQUIRED] Minecraft Version Number:** 1.14.4

**Links to worlds.yml file and settings.yml file:** - 

**[REQUIRED] Description of the problem:** Parties overwrite only `/p` commands and plotsquared get completely overwirited on any alias `/p2`,`/plotsauqred` `/plotme`, please check this issues https://github.com/AlessioDP/Parties/issues/47

**Any relevant console output or screenshots:** - isn't relevant

**Plugins being used on the server:** - isn't relevant

**How to replicate:** Yes, can be replicated, made any server out of paper/spigot/bukkit, grab last versions of P^2 and Parties, and voaila, the P^2 isn't work at all. 

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [ ] I made sure I am using an up-to-date version of PlotSquared
- [?] I made sure the bug/error is not caused by any other plugin

https://github.com/AlessioDP/Parties/issues/47

**Comment by N0tMyFaultOG** [comment]
https://github.com/AlessioDP/Parties/issues/47#issuecomment-524868242
