### ISSUE TITLE
crash report paper 1.14.4 build 175

### ISSUE THREAD

**Issue by leoncp9** [IntellectualSites/PlotSquared#2491]
Hello i use PlotSquared bild #753 on paperspigot 1.14.4

log
https://pastebin.com/EdpBCuhB
server version paper spigot 1.14.4 build 175

crash
https://drive.google.com/open?id=1pOJSMDjMgUsDIOz1fUUgiE4u22p1wNtD

paper say me 
The world generator plugin you're using for the world "plotworld" (presumably PlotSquared) isn't compatible with 1.14.4, you should look for an update of that plugin.

**Comment by N0tMyFaultOG** [comment]
May use the correct version and follow the template if you still need support.
