### ISSUE TITLE
PlotSquared automatically overwrites worlds when loading

### ISSUE THREAD

**Issue by GamerDaniel3000** [IntellectualSites/PlotSquared#2492]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number:** 

**[REQUIRED] Spigot/Paper Version Number: Nukkit git-2c7ce40** 

**[REQUIRED] Minecraft Version Number: 1.12.0** 

**Links to worlds.yml file and settings.yml file:https://drive.google.com/open?id=1jVfzTv58tEgyHDPU-yr4sjOTrGNgdc9f
https://drive.google.com/open?id=1pKcGIjVLtDLM7nScWgCk4qu9xUvBrTf8** 

**[REQUIRED] Description of the problem: I create a plot world and create a street schematic.
Then I load with MultiWorld another world with / mw load (name).
I'm going into this world and at this moment PlotSquraed is doing this world no plot world is also in the worlds.yml one.
Then I go back into the Plot world and fly into the not yet loaded Chunks and there the Plot template is displayed because Plotsquared thinks that the other template is the new Road schmatic.** 

**Any relevant console output or screenshots: [36m10:52:17[m [[m[34mINFO [m[m] DragonBuild »Detected world load for 'Farm-2'

[36m10:52:17[m [[m[34mINFO [m[m] DragonBuild » - generator: PlotSquared>PlotSquared

[36m10:52:17[m [[m[34mINFO [m[m] DragonBuild » - plotworld: com.intellectualcrafters.plot.generator.HybridPlotWorld

[36m10:52:17[m [[m[34mINFO [m[m] DragonBuild » - manager: com.plotsquared.nukkit.NukkitMain

[36m10:52:17[m [[m[34mINFO [m[m] DragonBuild » - schematic: false

[36m10:52:17[m [[m[34mINFO [m[m] World possibly already loaded: Farm-2

https://drive.google.com/open?id=151YWPDQkQFylfF-FcPtIBCZWdWTKWi5K**

**Plugins being used on the server:**

**How to replicate: Look at the Discription of zhe issue** 

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
I won't be looking at the files as they are on (what I consider to be) an untrusted host. 
Please copy the text to a paste service, such as termbin.com and any images to a public image hosting service.

Or wait for others to assist you.

Additionally, you failed to say what other plugins you are using, and regardless if you think they are interfering or not, having a record of these things helps the developers and helpers spot potential issues. 

After reading the description of your problem for the 3rd time, it sounds like you're not setting up multiworld properly.

**Comment by MattBDev** [comment]
Don't link us to Google drive please.

**Comment by MattBDev** [comment]
I am closing this because the issue was described poorly the template was not properly followed.
