### ISSUE TITLE
Plot Squared /p clear does not work right

### ISSUE THREAD

**Issue by leon47331** [IntellectualSites/PlotSquared#2494]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number: 3.3.0 

**[REQUIRED] Spigot/Paper Version Number: Bukkit Version 1.8.8 R.01 Snapshot

**[REQUIRED] Minecraft Version Number: 1.8.8

**Links to worlds.yml file and settings.yml file:** 

**[REQUIRED] Description of the problem: When I type /p clear in the chat, the plot will clear just an area from 16x16 blocks. 

**Any relevant console output or screenshots:**

**Plugins being used on the server:**

**How to replicate:** 

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
[Update](https://ci.athion.net/job/PlotSquared-Legacy/lastSuccessfulBuild/artifact/target/PlotSquared-Bukkit-19.08.23-1fbb9b5-780.jar) PlotSquared first if you are too lazy to even fill out the template and provide useful information.

**Comment by leon47331** [comment]
Hello,
I'm sorry that I don't fill out the template.
I think these are already useful information.

(Wir können auch auf Deutsch schreiben!)

**Comment by AeSix** [comment]
Closing ticket as the requester refuses to provide the additional information needed to help diagnose the issue. 

@leon47331 if you feel like actually giving us the information you've left out of the template, we'll reopen the ticket.  Until then, read the wiki and instructions.  Try generating new configs.
