### ISSUE TITLE
Plot Squared 1.14.4 Issues

### ISSUE THREAD

**Issue by Ifriedmonkey** [IntellectualSites/PlotSquared#2496]
**[REQUIRED] PlotSquared Version Number:**  Version: PlotSquared -4.347

**[REQUIRED] Spigot/Paper Version Number:** 
 
![image](https://user-images.githubusercontent.com/36404187/64486793-af6a9280-d229-11e9-8a8c-20ce8601525a.png)

**[REQUIRED] Minecraft Version Number:** 
1.14.4
**Links to worlds.yml file and settings.yml file:** 
https://athion.net/ISPaster/paste/view/3e7a4d02851a4b8190dfcd70f0c34fde

world.yml --> https://pastebin.com/QbGPv78E
settings.yml --> https://pastebin.com/DpumvUNd
**[REQUIRED] Description of the problem:** 
Basically when I do /plot delete it does this https://cdn.discordapp.com/attachments/344128265075556353/620198301613948928/unknown.png and when I claim a plot it's still stone slabs https://cdn.discordapp.com/attachments/344128265075556353/620197580730793985/unknown.png
**Any relevant console output or screenshots:**
https://pastebin.com/RFgyCLCq
https://pastebin.com/GLeQpSAH
**Plugins being used on the server:**

![image](https://user-images.githubusercontent.com/36404187/64486839-5818f200-d22a-11e9-9e93-48fb62ecaf1e.png)

**How to replicate:** 

I literally just used the setup feature.
**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [] I made sure I am using an up-to-date version of PlotSquared
- [] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
In the future please name the title of the issue something more relevant or specific because "Plot Squared 1.14.4 Issues" could mean anything.

**Comment by Ifriedmonkey** [comment]
Well the whole plugin was literally broken lmao

**Comment by AeSix** [comment]
WorldEdit 7.0.1 rc1?  Go use the release version.
Update or remove the plugins that aren't updated for 1.14.4. 
All of the plugins in your list with an asterisk are not properly updated for 1.13 much les for 1.14.4 - the asterisk means they are using internal server transforms, and causing increased server load - and potentially additional vectors of error with compatibility with properly 1.14.4 plugins. 

Remove those plugins, test. 

If you still have issue, open a new ticket with appropriate, accurate and detailed information.
