### ISSUE TITLE
mvm placeholders don't work!

### ISSUE THREAD

**Issue by leoncp9** [IntellectualSites/PlotSquared#2497]
Hello, my server is paper 1.14.4
i have latest version of plugin plotsquared build #343
https://ci.athion.net/job/PlotSquared-Breaking/343/
i have mvm placeholders and latest version of featherboard
i have follow this guide
https://prnt.sc/p0ustv
but in game i can't see them
https://prnt.sc/p0ut5y
how can i fix this?
the problem is by plotsqaured or by your mvmplaceholders?

**Comment by N0tMyFaultOG** [comment]
Update PlotSquared, follow the template and open a new issue. Ty

**Comment by leoncp9** [comment]
i have pm dev 7 days ago, so i give him review
Hello, my server is paper 1.14.4
i have latest version of plugin plotsquared (4.353)
https://www.spigotmc.org/resources/plotsquared.1177/
i have mvm placeholders and latest version of featherboard
i have follow this guide
https://prnt.sc/p0ustv
but in game i can't see them
https://prnt.sc/p0ut5y
how can i fix this?
the problem is by plotsqaured or by your mvmplaceholders?
