### ISSUE TITLE
mvmplaceholders don't work

### ISSUE THREAD

**Issue by leoncp9** [IntellectualSites/PlotSquared#2498]
Hello, my server is paper 1.14.4
i have latest version of plugin plotsquared (4.353)
https://www.spigotmc.org/resources/plotsquared.1177/
i have mvm placeholders and latest version of featherboard
i have follow this guide
https://prnt.sc/p0ustv
but in game i can't see them
https://prnt.sc/p0ut5y
how can i fix this?
the problem is by plotsqaured or by your mvmplaceholders?

**Comment by MattBDev** [comment]
1. You created a duplicate issue when you could have commented on the old one saying it wasn't resolved.
2. You deleted the issue template which is required.
3. You provided little to no information.
4. We don't control placeholders so it isn't an issue PlotSquared.
5. We don't control placeholders so I have no clue why you are referring to "your mvmplaceholders"

If you file a duplicate issue again, it will be deleted. Use discord if you need further assistance.
