### ISSUE TITLE
Crops stop growing randomly

### ISSUE THREAD

**Issue by 83y** [IntellectualSites/PlotSquared#2503]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**Debug paste link:https://www.athion.net/ISPaster/paste/view/6b62d320a15b4a9581b2a06289b019da** 

**[REQUIRED] Spigot/Paper Version Number:1.12.2** 

**[REQUIRED] Minecraft Version Number:1.12.2** 

**[REQUIRED] Description of the problem: i have a farming server and sometimes in the plots the crops wont grow eg. Sugar Cane, Cactus randomly they will just stop growing in certain chunks for certain people** 

**Any relevant console output or screenshots:**

**Plugins being used on the server:**

**[REQUIRED] How to replicate:** 

**[REQUIRED] Checklist**:

- [x] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by 83y** [comment]
Clear Lag is essential on my server is there any other way to fix it?

**Comment by MattBDev** [comment]
If you don't want to remove clearlag to check if it's the problem then it's likely the cause of the issue because that section of code has been in use for more than a year without any issues.

**Comment by 83y** [comment]
ok i uninstalled it
