### ISSUE TITLE
Flag deny-teleport incorrect for negative groups (nonmenbers, nontrusted, nonowners)

### ISSUE THREAD

**Issue by mindw0rm** [IntellectualSites/PlotSquared#2504]
**Debug paste link:** 
https://athion.net/ISPaster/paste/view/889bc9fe37a547abae1ad20db142f43a

**[REQUIRED] Spigot/Paper Version Number:** 
git-Spigot-94af569-6ddeb98 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**[REQUIRED] Minecraft Version Number:**  1.14.4

**PlotSquared Version:** 4.385 / github build (branch _breaking_) 

**[REQUIRED] Description of the problem:** 
When setting the flag deny-teleport to a negative group, e.g. 'nontrusted', it does prevent teleport only for players that are _not_ in that group (in case of 'nontrusted', trusted members and the owner(s) can't teleport).
This does (because of #2505) _only_ apply if the player is in another world, i.e. it works if you are located in the same world as the plot. 

The reason is obvious when you look in the code: 
https://github.com/IntellectualSites/PlotSquared/blob/breaking/Core/src/main/java/com/github/intellectualsites/plotsquared/plot/flag/TeleportDenyFlag.java#L28
result should be true if teleport is okay, but returns false for owners/trusted/members.

Disclaimer: it is possible that is misunderstood how deny-teleport works, and setting it to 'nontrusted' means that only nontrusted are allowed to teleport. However, in that case the implementation for 'trusted' and 'members' is wrong (and also the name deny-teleport would be misleading). 

**Any relevant console output or screenshots:**
n/a

**Plugins being used on the server:**
see debugpaste link above.

**[REQUIRED] How to replicate:** 
- set deny-teleport on your plot to nontrusted
- go to another world, e.g. nether
- use /plot home
You get a message telling you that you need the permission plots.admin.entry.denied.

**[REQUIRED] Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

[edited to refer to #2505]

**Comment by MattBDev** [comment]
@RedstoneFuture you are more familiar than the flags than I am. What are your thoughts on this?

**Comment by RedstoneFuture** [comment]
I've never used this flag in every time. In my tests today the entry-deny feature doesn't work. Maybe I have any wrong. ...

The biggest problem is in my case the many options to teleport:
- minecraft vanilla command (/teleport or gm3-teleport function)
- minecraft vanilla functions with items
- plotsquared commands
- WorldEdit commands
- any teleport plugins
... every option with other event prioritisations.

By the may @mindw0rm  I see your debug paste link: did it works with both plugins? ^^
`  FastAsyncWorldEdit:
    version: '1.0'
    enabled: true
  AsyncWorldEdit:
    version: '3.6.10'
    enabled: true`

**Comment by mindw0rm** [comment]
> 
> 
> I've never used this flag in every time and blocked it for my player a long time ago. In my tests today the entry-deny feature doesn't work. Maybe I have any wrong. ... (With 1.13 and with 1.14)
> 
> The biggest problem is in my opinion the many options to teleport:
>     * minecraft vanilla command (/teleport or gm3-teleport function)
>     * minecraft vanilla functions with items
>     * PlotSquared commands
>     * WorldEdit commands
>     * any teleport / home plugins (!)

After my bugfixes (#2506), every means of teleportation that normal players can do were blocked as intended. 
* did not test `/teleport`, since it is only possible for op, and those bypass deny-teleport anyway.
* Ender Pearl and Chorus Fruit are blocked.
* `/plot home/visit`  and `/plot middle` are all blocked.
* `/home`, `/tp`, `/warp` and `/back` and portals from CMI are blocked. 
* Worldedit commands from [here](https://worldedit.enginehub.org/en/latest/commands/#navigation-commands) are all blocked, most with the same error as above (missing permission `plots.admin.entry.denied`*), but `/up` for some reason gives the message that you need  `plots.admin.build.other` (which sounds like a bug in itself, since `/up` is not a build command).
* it does _not_ block `/zh here` from ZHorse, which is understandable since it is not a player that is teleported. 

These are all possibilities that I am aware of (on our server), except transportation by minigames (like Bedwars or Mobarena). I guess there is a good chance that those are blocked, too, but imho having a minigame in plots that are protected by deny-teleport is a rather unlikely scenario ;)

(*) Maybe a more fitting error message, like 'You are not allowed to teleport here' would be better?

> By the may @mindw0rm I see your debug paste link: did it works with both plugins? ^^
>   FastAsyncWorldEdit:
>     version: '1.0'
>     enabled: true
>   AsyncWorldEdit:
>     version: '3.6.10'
>     enabled: true
> ```

We encountered no problems so far, but FastAsyncWorldEdit is a DummyFAWE.jar, which sounds as if it does nothing. I haven't installed this myself, and haven't gotten a reply yet why it exists, but imho DummyFAWE is some relict from earlier that can be removed ;) 
The server was originally 1.13.2, and afaik the plugin collection came from an even earlier server, which was before I got involved.

**Comment by AeSix** [comment]
@mindw0rm @RedstoneFuture 

The Vanilla commands can be negated with any permissions management system. This page includes Mojang's commands, which were made permissible by Bukkit:  https://bukkit.gamepedia.com/CraftBukkit_Commands#Bukkit_Commands_and_Permissions

I use WorldGuard, WorldBorder, and some other plugins in conjunction with PlotSquared to ensure that certain things are controlled the way I'd like.  

DummyFAWE is only 1 of 2 jar files that is loaded. The DummyFAWE provides a WorldEdit version for plugins which aren't FAWE aware.  You need this along with the FAWE jar.

You should not install AsyncWorldEdit or WorldEdit when FAWE is installed.  You probably should not use FAWE in production servers on 1.14.4 right now, more testing and fixes are needed.  Issues will arise. 

Also, AFAIK, There's only 5 levels of access to plots:
Owner
Trusted
Member
non-added (so, should have no permissions)
denied (actively has no ability to enter/use the plot)

I don't know where your "negative groups" is coming from?  If that's a PMS issue, then you need to ensure that your weights and inheritances are correct. You need to decide if explicit deny will take precedence over  explicit allow permissions, and then keep with that for the entirety of your PMS setup.

**Comment by AeSix** [comment]
And for the love of the bits and bytes, please stop using ClearLag and configure your spigot.yml instead. Yes, it takes time and effort to learn what configuration works best for your server, but as ClearLag breaks things and causes other minor issues, it's worth it.

**Comment by mindw0rm** [comment]
Well, thanks for the tipps regarding FAWE (which is _not_  running on the server) and ClearLag, I'll forward it to those in charge. But those are not the issue of this bug, and I'm pretty sure they don't influence it. If you insist I can remove them (I can even remove all plugins except plotsquared if you still believe it is some other plugin and not the obvious thing in the [code](https://github.com/IntellectualSites/PlotSquared/blob/breaking/Core/src/main/java/com/github/intellectualsites/plotsquared/plot/flag/TeleportDenyFlag.java#L18)) and test again. I'm pretty sure the result will be the same. 

Regarding
> I don't know where your "negative groups" is coming from? 

They come directly from the [code](https://github.com/IntellectualSites/PlotSquared/blob/breaking/Core/src/main/java/com/github/intellectualsites/plotsquared/plot/flag/TeleportDenyFlag.java#L8): valid values for deny-teleport are "trusted", "members", "nonmembers", "nontrusted", "nonowners". 
"negative" groups are those beginning with "non". Guess I haven't emphasized this enough, I thought it was obvious :/
If you again look into the code, you'll see that there _obviously_ is a bug, because "trusted" and "untrusted" return the _very same result_ (member of trusted can't teleport, others can) for all except the owner (who is allowed to teleport with "trusted" (imho okay), but not allowed with "untrusted" (which is imho wrong)). 
As I said in the original report, there might be a misunderstand from my side, that deny-teleport does _not_ specify those which are _denied_ teleportation, but those which are _allowed_ - which would make the flag name very misleading - but that **two flag values which by their name should be _opposites_ have (almost) the _same_ result can't be right**. 

> If that's a PMS issue, 

No it is not. Permissions are not the issue here. Teleportation works fine, but deny-teleport does not. I don't see that there is a special permission involved (except plots.flag.set.deny-teleport and plots.set.flag.deny-teleport.* - but those are given (or the flag was set by an admin), and those only control the right to _set_ the flag, not its effects - and plots.admin.entry.denied - but that is an admin right that bypasses deny-teleport, and also works as intended).
The only issue here is the deny-teleport flag, and the differences between plots without it and those who have it set it to one of the values. I want to deny teleportation to all non-trusted (the 4th of your access groups, the 5th is no issue since they can't enter anyway), and that is not possible atm.

**Comment by AeSix** [comment]
I apologize, I had no idea non* groups were added to PS.

As for ClearLag, it has a use for small servers where the server owner has no clue how to configure their server.  It brute-force removes things, which those things could be configured to never go above those thresholds.  It cannot in any other way improve CPU/RAM/disk or network I/O, or network latency.  I've had cases where CL actually /causes/ more latency because of improperly configured servers.  

That's beside the point, and a complete tangent rant. 

As for the obvious issues with the code, did you PR a fix?  Matt and City would be greatful :)

As for the PMS issue, I, again didn't know about the non* groups, and was basing my statements on that those groups were in your PMS.  As I was mistaken, that too can be ignored.  (Though, what I said is still accurate, I'm sure you could agree)

**Comment by mindw0rm** [comment]
> As for the obvious issues with the code, did you PR a fix? Matt and City would be greatful :)

Yes I did: #2506 - it also fixes #2505, which might be a more delicate issue, but the fix works for us.
You even added a tag to it ;)

**Comment by MattBDev** [comment]
I never said I didn't want it. I just have to question all the suggestions before we accept them. Otherwise the plugin gets more cluttered than it already is.
