### ISSUE TITLE
Flag deny-teleport does not prevent all teleports.

### ISSUE THREAD

**Issue by mindw0rm** [IntellectualSites/PlotSquared#2505]
**Debug paste link:** 
https://athion.net/ISPaster/paste/view/889bc9fe37a547abae1ad20db142f43a

**[REQUIRED] Spigot/Paper Version Number:** 
git-Spigot-94af569-6ddeb98 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**[REQUIRED] Minecraft Version Number:**  1.14.4

**PlotSquared Version:** 4.385 / github build (branch _breaking_) 

**[REQUIRED] Description of the problem:** 
Some teleports are still possible  when the flag deny-teleport is set:
* if you start in the same world as the plot
* ender pearls
* chorus fruits

This prevents me from creating a dungeon labyrinth with a prece at the end; ender pearls can be used to teleport through closed doors, chorus fruits can get you in maintenance areas (for redstone mechanics) or in parts that are protected by a riddle, and setting a home point directly before the end would allow to fetch the price numerous times without effort ...

**Any relevant console output or screenshots:**
n/a

**Plugins being used on the server:**
see debugpaste link above.

**[REQUIRED] How to replicate:** 
- set deny-teleport on your plot to nontrusted
- change to another player that is not trusted
- go to the plot in question
- teleport to your own plot
- use the CMI command /back to go back (alternatively, you could use /sethome on the plot and go there with /home (both also CMI commands))
-> you can go back. If you try the same with teleporting to another world and then using /back or /home, the teleport is denied. 

Or throw an ender pearl or eat a chorus fruit on the plot - you will get teleported (in-plot, but that's also a problem for me, see above). 

I think the bug is in https://github.com/IntellectualSites/PlotSquared/blob/68a5166d2f2ad342436f4683afac04dc18f70888/Bukkit/src/main/java/com/github/intellectualsites/plotsquared/bukkit/listeners/PlayerEvents.java#L682
If both from and to are != null and the world is the same, the code is not triggered. Imho that condition can be removed without substitution. 

**[REQUIRED] Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
FIX via new flag: https://github.com/IntellectualSites/PlotSquared/pull/2506
