### ISSUE TITLE
/p auto not working with the latest build 4.360

### ISSUE THREAD

**Issue by GTA5Racer** [IntellectualSites/PlotSquared#2507]
**Debug paste link:**  https://athion.net/ISPaster/paste/view/0f97ae55f4a04cb49de3b998348223e8

**[REQUIRED] Spigot/Paper Version Number:** Paper-187 (1.14.4)

**[REQUIRED] Minecraft Version Number:** 1.14.4

**[REQUIRED] Description of the problem:** Build 4.360 update breaks **/p auto** with an error shown in debug paste. I tried removing FAWE and replacing it with normal Worldedit but the problem still exists. I also tried making a fresh world to see if it would work, but it didn't.

**Any relevant console output or screenshots:** https://i.imgur.com/3f7lfff.png [Thats the error you get ingame]

**Plugins being used on the server:** Included in the debug paste

**[REQUIRED] How to replicate:** Just do /p auto and it will be returned with an error instead of creating a new plot

**[REQUIRED] Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
Remove Fawe/DummyFawe and give WorldEdit a try

**Comment by GTA5Racer** [comment]
Okay that works, weird it didn't work when i tried to test before, I probably forgot to remove the DummyFawe.

**Comment by MattBDev** [comment]
I'd also like to mention that plot auto may feel slower because it is now performing a few operations asynchronously. I'm eventually going to add an indicator somewhere to show that it is working.
