### ISSUE TITLE
World entirely reset w/ new biome structure after server reset.

### ISSUE THREAD

**Issue by EisbarGFX** [IntellectualSites/PlotSquared#2509]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**Debug paste link:** 
https://athion.net/ISPaster/paste/view/dcbf27020a344e8f9f1de6219e35e8c0

**[REQUIRED] Spigot/Paper Version Number:** 
CraftBukkit [Unknown, Server host does not show specific version numbers]

**[REQUIRED] Minecraft Version Number:** 
Java 1.14.4
**[REQUIRED] Description of the problem:** 
After restarting my server for something changed that in no way affects PlotSquared, the plugin **completely** regenerated the world I had built on. All plots were reset and a new biome structure is visible. 

**Any relevant console output or screenshots:**

**Plugins being used on the server:**

**How to replicate:** 

Host PlotSquared on a 1.14.4 CraftBukkit server.
Build something in a PlotSquared generated world.
Restart server.

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
This sounds like an issue with your host, or your server not saving data to disk. 
This is not a plugin issue.  Closing ticket.
