### ISSUE TITLE
Plot deleting not working

### ISSUE THREAD

**Issue by Redemption2033** [IntellectualSites/PlotSquared#2510]
**Debug paste link:** https://athion.net/ISPaster/paste/view/900153a0d3584cbf85d5f2dd52af31b5

**[REQUIRED] Spigot/Paper Version Number:** git-Paper-642 (MC: 1.13.2)

**[REQUIRED] Minecraft Version Number:** 1.13.2

**[REQUIRED] Description of the problem:** Player's can't delete plots. When you type /plot delete, nothing happens at all, no message or anything. If you type it again you get sent the message below.

**Any relevant console output or screenshots:** https://gyazo.com/47b5489a01daead4bc07d58e7aec4dba

**Plugins being used on the server:**
In debug paste.

**[REQUIRED] How to replicate:** I type /plot delete and nothing happens, no message. When I type it again, it sends the message in the screenshot above.

**[REQUIRED] Checklist**:
- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [] I made sure the bug/error is not caused by any other plugin
Unable to verify what is the cause of the issue, which is why I'm making a report for help.

**Comment by MattBDev** [comment]
Update FAWE
