### ISSUE TITLE
BROKE API in 1.14.4

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#2513]
Plotsquared has destroyed my selfcodet /rand Plugin.
Debug paste link:
    Debugpaste: https://athion.net/ISPaster/paste/view/b8b9dcb1051c4156b3de2a59803aa7ce
    Spigot/Paper Version Number:
    Version: Spigot-1.14.4
    This server is running CraftBukkit version git-Spigot-94af569-a3fdef8 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
    [11:17:10] [Server thread/INFO]: Checking version, please wait...
    [11:17:11] [Thread-10/INFO]: You are running the latest version
Minecraft Version Number:
    1.14.4

Description of the problem:
if i use the api to change the plotborder to beacon or whatever it dosent work
the plugin dont knows beacon or cobweb or every block. USELESS PLUGIN

Any relevant console output or screenshots:
-> Hastebin Error: https://hasteb.in/iwafopex.pl
-> Hastebin My Code: https://hasteb.in/adowocaf.java

Plugins being used on the server:
WorldEdit, PlotSquared

How to replicate:
Make a /rand plugin with P2 API

**Comment by AeSix** [comment]
Please join the discord to discuss how to properly use the API. 
Be aware that there may be issues with using old names, as names have changed. 
Also be aware that the P2 API has changed and the documentation may not be up to date.

discord.gg/cSMxtGn

closing ticket as this is more than likely a third party developer issue with not knowing how to properly use the P2 API, or for unimplemented / unsupported functions.  Again, discuss this with the developers in person on Discord.
