### ISSUE TITLE
/Plot Auto Error

### ISSUE THREAD

**Issue by LoXR** [IntellectualSites/PlotSquared#2514]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**Debug paste link:** 
https://athion.net/ISPaster/paste/view/0db60119b7434315aa8d06182a2e5186
**[REQUIRED] Spigot/Paper Version Number:** 
Paper version git-Paper-647 (MC: 1.13.2)

**[REQUIRED] Minecraft Version Number:** 
1.12.2

**[REQUIRED] Description of the problem:** 
Player tried to go /plot auto, prints error.

**Any relevant console output or screenshots:**
https://pastebin.com/nS2HR8pT
http://prnt.sc/pa2qli

**Plugins being used on the server:**

**[REQUIRED] How to replicate:** 
Type /plot auto on build 359 or higher.

**[REQUIRED] Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
This is a FAWE issue

**Comment by LoXR** [comment]
But why does the command work if I went back to build 358?

**Comment by MattBDev** [comment]
Again it's a fawe issue. We are having troubles getting the API's to sync properly.

**Comment by LoXR** [comment]
Alright, and want to put this here aswell.
https://timings.aikar.co/?id=57cb2b21a09d4e9d821f9947e17f5b05#timings
With those timings my CPU is always idling at 50 - 60%, it seems some task in plotsquared is causing this.

**Comment by AeSix** [comment]
Yet again, those functions look like they're calling on FAWE. 
Use WorldEdit 7.0.1 or revert back down to the last working build of P2 until FAWE is updated.
