### ISSUE TITLE
PlotSquared dont regen all roads

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#2515]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**Debug paste link:** 
https://athion.net/ISPaster/paste/view/b80d0c45fb7941868ac5ee92527cb425
**[REQUIRED] Spigot/Paper Version Number:** 
This server is running CraftBukkit version git-Spigot-94af569-a3fdef8 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**[REQUIRED] Minecraft Version Number:** 
1.14.4
**[REQUIRED] Description of the problem:** 
if i regen all roads not all roads will be regen. it looks ugly and i can no longer use my server because i have citybuild and this plugin is important
**Any relevant console output or screenshots:**
Screenshot: https://i.imgur.com/xEdx0S7.png
**Plugins being used on the server:**
http://prntscr.com/paf7ce

**[REQUIRED] How to replicate:** 
Make a Plotworld with /p setup and build a road and regen all roads with /p regenallroads than wait to complete after that teleport you to /tp 29999999 128 29999999

**[REQUIRED] Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
https://www.quora.com/How-much-disk-space-is-needed-to-store-a-fully-generated-Minecraft-world

With this, I find it extremely difficult to believe you have a fully working server with a completely full world, as suggested by the coordinates you provided. 

I would like to see more of your setup if you are indeed using a 60-million block square world. Or even a 15m^2 world.

**Comment by DevJoey** [comment]
My Server works perfectly. If i generate this world with a Special plotgenerator written by one of my developers all 
Its generated perfectly. You have missinformations. The world with this coordinates are only 19,45 
MB. The people on the forum you have send to me, talks the biggest crap. PlotSquared 
Is simply sayed not able to regenerate the street correcly. This is because you do not want to fix it. instead you push it on coordinates. you simply are not able to fix the error of your generator or just simply too lazy.

Thanks for nothing.

**Comment by DevJoey** [comment]
My Server works perfectly. If i generate this world with a Special plotgenerator written by one of my developers all
Its generated perfectly. You have missinformations. The world with this coordinates are only 19,45
MB. The people on the forum you have send to me, talks the biggest crap. PlotSquared
Is simply sayed not able to regenerate the street correcly.

The world works perfect. It is the normal worldborder

**Comment by DevJoey** [comment]
I have a same World generated with my own generator and i teleportet me to the same 
Coords all is perfectly.

**Comment by AeSix** [comment]
I've done the math multiple times. 
Using 4.5 MBs average for a file size for each region file.  Which is probably much lower than the average for a creative server. 

60,000,000 block squared world (30 million radius, as given by your coordinates), Divide that by 512, the number of blocks wide each region file is.  We're left with 177,188 files.  Square that, and you get 13,733,027,344 files, for the full world.  Assuming you will be generating the full world, you will have 13.7 billion files.  At 4.5 MBs per file, with 13.7 billion, you are well into the 50-60 Petabyte range for storage. 

Ok, so, there's compression.  Let's say compression can achieve a 50% reduction in storage use.  You're still at 30 PBs.  Let's go 80%.  That's still 12 PBs.  

Unless you've spent NASA's entire R&D budget on servers and storage, you cannot have a world that large.  

Ok, so, let's assume you're only using a small portion of the total available world.  Let's say you're only using 10240 radius area of the total possible blocks.  Which is still an absolutely huge world, at 419,430,400 total blocks (20480x20480), is still 1600 files, at 4.5 MBs each is 7.2 GBs.  Double the radius to 20480, you'll get 4 times as many files at 28.8 GBs.  

So, no, the article is not "crap"

And with that, you're either lying about the world size (being 60mx60m) or you need to not use the edges of the world for your play area.  There is no need to have your plot area in that portion of the world.  Move your plot are to the center of the world, or at least within the first million blocks from 0/0.  This is literally an edge case scenario where the solution is to not use the edge of the possible world limitations.  If you want to create your plot area in a sane area of the world (i.e, around 0/0) and still have this issue, then we can re-open the issue.  And doing so without the use of some other generator, which itself could be the root of this issue. 

Until then, this is a user error cause by configuration. 

Recreate the issue:
Without the "special" generator you're using
WITH using much more sane areas of the world, NOT the edge! 

Road regeneration takes a long time.  This is compounded by the size of the world.

**Comment by DevJoey** [comment]
The world is 19 mb.

**Comment by AeSix** [comment]
And what happens when people build on it, use it, make it grow? Get yoru head out of your ass.

**Comment by DevJoey** [comment]
The people can normally build. Not happens can you be a little friendlier? You are really not able to deal with people sensible. you are bad developers. shame you.

**Comment by DevJoey** [comment]
I have reported you because of your unfrendlyness and you are blocked now!

**Comment by Draycia** [comment]
no shame u

**Comment by MisterFixx** [comment]
> I have reported you because of your unfrendlyness and you are blocked now!

Oh NoOoOoOoOOo

**Comment by Draycia** [comment]
Dude he's gonna report you to the cyber police too you better watch it, fix.

**Comment by MisterFixx** [comment]
> Dude he's gonna report you to the cyber police too you better watch it, fix.

report deez nutz

**Comment by AeSix** [comment]
You know, you're right.  I should had been reported.  I was in the wrong to tell you to "get your head out of your ass"  - That is unbecoming of a civilized person.  

@MattBDev can you lock this? #NoPerms.

**Comment by Sauilitired** [comment]
Not if I do it first!!!
