### ISSUE TITLE
"/p flag set ..." don't check the material

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquared#2519]
**[REQUIRED] Minecraft Version Number:** 
1.13.2

**[REQUIRED] Plugin Version Number:** 
PlotSquared 4.365

**[REQUIRED] Description of the problem:** 
The `/p flag set ...` command with block-lists down't filter a invalid block input. (see "How to replicate")

**[REQUIRED] How to replicate:** 

`/p flag set use ttttt` --> "successfully added flag" [X]
`/p flag add use ttttt` --> "The flag could not be added" [correctly]
`/p flag set break ttttt` --> "successfully added flag" [X]
`/p flag add break ttttt` --> "The flag could not be added" [correctly]
`/p flag set place ttttt` --> "successfully added flag" [X]
`/p flag add place ttttt` --> "The flag could not be added" [correctly]

**[REQUIRED] Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
Wow. I can't believe we missed this. I blame myself.
