### ISSUE TITLE
Weird lighting issue with deleting and creating plots

### ISSUE THREAD

**Issue by johncsuti** [IntellectualSites/PlotSquared#2522]
**Debug paste link:** 
Can't .. keep getting either a 400 bad request or a 413 request entity too large
![2019-10-05_02 16 58](https://user-images.githubusercontent.com/22971404/66250870-9b299080-e716-11e9-984f-a914ed78045f.png)
**[REQUIRED] Spigot/Paper Version Number:** 
Git-Paper-631
Mc api version 1.13.2-R0.1-snapshot

**[REQUIRED] Minecraft Version Number:** 
1.13.2

**[REQUIRED] Description of the problem:** 
![2019-10-05_02 14 55](https://user-images.githubusercontent.com/22971404/66250881-aaa8d980-e716-11e9-80b6-9727167c2407.png)
Weird lighting issue when creating and deleting plots
**Any relevant console output or screenshots:**
N/A
**Plugins being used on the server:**
![2019-10-05_02 20 56](https://user-images.githubusercontent.com/22971404/66250893-cb712f00-e716-11e9-985e-aedd83c18d89.png)
**[REQUIRED] How to replicate:** 
Not sure claim a plot using /plot auto
delete plot using /plot delete and it appears during that a block update removes it not sure how i can fix it??
**[REQUIRED] Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by johncsuti** [comment]
Going to issue it under fawe as //fixlighting fixes it

**Comment by AeSix** [comment]
THe issue lays with the server, not the plugins.  It's just more prominent with certain actions.  This happens on Mojang's server as well, because it's their lighting code that is messed up.
