### ISSUE TITLE
FAWE is spamming console when trying to create a road schematic

### ISSUE THREAD

**Issue by johncsuti** [IntellectualSites/PlotSquared#2523]
**Debug paste link:** 
Doesn't work error 400 or 413
![2019-10-05_02 16 58](https://user-images.githubusercontent.com/22971404/66251556-61a95300-e71f-11e9-8269-09cbb0a23532.png)

**[REQUIRED] Spigot/Paper Version Number:** 
This server is running Paper version git-Paper-631 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**[REQUIRED] Minecraft Version Number:** 
1.13.2

**[REQUIRED] Description of the problem:** 
fawe errors when using /plots createroadschematic

**Any relevant console output or screenshots:**
https://athion.net/ISPaster/paste/view/95fb8e006bee438bad97e6c47d94b3e3

**Plugins being used on the server:**
 - LuckPerms: 4.4.27
 - FastAsyncWorldEdit: 1.13-breaking
 - WorldEdit: 1.13.184
 - FastAsyncVoxelSniper: 1.13.184
 - PreventPortBypass: 1.0
 - Vault: 1.7.1-b91
 - MyCommand: 5.5.1
 - WorldGuard: 7.0.0-beta-03;e51a220
 - ProtocolLib: 4.4.0
 - Essentials: 2.16.1.0
 - EssentialsChat: 2.16.1.0
 - HolographicDisplays: 2.3.2
 - PlotSquared: 4.353
 - SuperVanish: 6.1.1
 - BuycraftX: 12.0.2
 - Multiverse-Core: 3.0.0-SNAPSHOT-b761
 - DiscordSRV: 1.17.1

**[REQUIRED] How to replicate:** 
issue /plot createroadschematic and wait

**[REQUIRED] Checklist**:
- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by johncsuti** [comment]
Updated and tried a fresh install of all plugins to get this
[Sun, 6. Oct 2019 01:07:08 EDT INFO] johncsuti issued server command: /plots auto
[Sun, 6. Oct 2019 01:07:08 EDT WARN] java.lang.AbstractMethodError: com.github.intellectualsites.plotsquared.plot.util.ChunkManager.loadChunk(Ljava/lang/String;Lcom/github/intellectualsites/plotsquared/plot/object/ChunkLoc;Z)Z
[Sun, 6. Oct 2019 01:07:08 EDT WARN]     at com.github.intellectualsites.plotsquared.plot.object.Plot$6.run(Plot.java:2145)
[Sun, 6. Oct 2019 01:07:08 EDT WARN]     at com.github.intellectualsites.plotsquared.plot.object.Plot$6.run(Plot.java:2142)
[Sun, 6. Oct 2019 01:07:08 EDT WARN]     at com.github.intellectualsites.plotsquared.plot.object.RunnableVal.run(RunnableVal.java:14)
[Sun, 6. Oct 2019 01:07:08 EDT WARN]     at com.github.intellectualsites.plotsquared.plot.util.TaskManager.sync(TaskManager.java:119)
[Sun, 6. Oct 2019 01:07:08 EDT WARN]     at com.github.intellectualsites.plotsquared.plot.util.TaskManager.sync(TaskManager.java:114)
[Sun, 6. Oct 2019 01:07:08 EDT WARN]     at com.github.intellectualsites.plotsquared.plot.object.Plot.guessOwner(Plot.java:2142)
[Sun, 6. Oct 2019 01:07:08 EDT WARN]     at com.github.intellectualsites.plotsquared.plot.object.Plot.canClaim(Plot.java:2124)
[Sun, 6. Oct 2019 01:07:08 EDT WARN]     at com.github.intellectualsites.plotsquared.plot.object.PlotArea.getNextFreePlot(PlotArea.java:722)
[Sun, 6. Oct 2019 01:07:08 EDT WARN]     at com.github.intellectualsites.plotsquared.plot.commands.Auto.autoClaimFromDatabase(Auto.java:135)
[Sun, 6. Oct 2019 01:07:08 EDT WARN]     at com.github.intellectualsites.plotsquared.plot.commands.Auto.autoClaimSafe(Auto.java:111)
[Sun, 6. Oct 2019 01:07:08 EDT WARN]     at com.github.intellectualsites.plotsquared.plot.commands.Auto.onCommand(Auto.java:236)
[Sun, 6. Oct 2019 01:07:08 EDT WARN]     at com.github.intellectualsites.plotsquared.plot.commands.SubCommand.execute(SubCommand.java:36)
[Sun, 6. Oct 2019 01:07:08 EDT WARN]     at com.github.intellectualsites.plotsquared.commands.Command.execute(Command.java:335)
[Sun, 6. Oct 2019 01:07:08 EDT WARN]     at com.github.intellectualsites.plotsquared.plot.commands.MainCommand.execute(MainCommand.java:251)
[Sun, 6. Oct 2019 01:07:08 EDT WARN]     at com.github.intellectualsites.plotsquared.plot.commands.MainCommand.onCommand(MainCommand.java:134)
[Sun, 6. Oct 2019 01:07:08 EDT WARN]     at com.github.intellectualsites.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:25)
[Sun, 6. Oct 2019 01:07:08 EDT WARN]     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
[Sun, 6. Oct 2019 01:07:08 EDT WARN]     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[Sun, 6. Oct 2019 01:07:08 EDT WARN]     at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734)
[Sun, 6. Oct 2019 01:07:08 EDT WARN]     at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1783)
[Sun, 6. Oct 2019 01:07:08 EDT WARN]     at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1591)
[Sun, 6. Oct 2019 01:07:08 EDT WARN]     at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[Sun, 6. Oct 2019 01:07:08 EDT WARN]     at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
[Sun, 6. Oct 2019 01:07:08 EDT WARN]     at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15)
[Sun, 6. Oct 2019 01:07:08 EDT WARN]     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[Sun, 6. Oct 2019 01:07:08 EDT WARN]     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[Sun, 6. Oct 2019 01:07:08 EDT WARN]     at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108)
[Sun, 6. Oct 2019 01:07:08 EDT WARN]     at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018)
[Sun, 6. Oct 2019 01:07:08 EDT WARN]     at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[Sun, 6. Oct 2019 01:07:08 EDT WARN]     at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
[Sun, 6. Oct 2019 01:07:08 EDT WARN]     at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837)
[Sun, 6. Oct 2019 01:07:08 EDT WARN]     at java.lang.Thread.run(Thread.java:748)

Im now going to move to 1.14.4 to see if that helps

**Comment by AeSix** [comment]
P2 and FAWE aren't working properly together. 
This is an issue that should be posted to the FAWE issue tracker. 

Use WorldEdit 7.0.1 with 1.14.4 for production servers.
Use FAWE breaking for 1.14.4 for testing, to help the developers.
