### ISSUE TITLE
Issue with Companions Plugin

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#2526]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**Debug paste link:** 

https://athion.net/ISPaster/paste/view/c4e4261e63e74590be19678bb334996e
**[REQUIRED] Spigot/Paper Version Number:** 

This server is running Paper version git-Paper-209 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[15:37:19 INFO]: Checking version, please wait...
[15:37:19 INFO]: You are running the latest version

**[REQUIRED] Minecraft Version Number:** 
1.14.4

**[REQUIRED] Description of the problem:** 
The Companions Reborn plugin do not work on PlotSquared because on the road can not spawn armorstands.
Can you please make an option to allow armorstand spawning on roads?
**Any relevant console output or screenshots:**
No
**Plugins being used on the server:**

Companions Reborn
**[REQUIRED] How to replicate:** 

Spawn a companion via /c on the road.

**[REQUIRED] Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by DevJoey** [comment]
#Fixed. Disable natural-mobsspawning and do /gamerule doMobSpawn false

**Comment by DevJoey** [comment]
But a little suggestioin i have. Please add, that natural mobspawning not affect armorstands.

**Comment by MattBDev** [comment]
I believe we have explored this option in the past and determined that this type of check would be too expensive for the server to perform.

**Comment by AeSix** [comment]
The solution has been posted.  The way to handle this is to use the built-in mob spawning game rule to disallow mobs (which is more efficient than any plugin anyways) which does NOT restrict the use of armor stands.  

If using Multiverse, gamerules can be applied per-world, even for PlotSquared managed worlds.
