### ISSUE TITLE
Flag "sleep" doesn't do anything

### ISSUE THREAD

**Issue by mindw0rm** [IntellectualSites/PlotSquared#2541]
The "sleep" flag is not used anywhere in the code. 

I _guess_ its intention is to prevent players from sleeping, but since as far as I can tell it was never used, it might be something different ...

It was introduced here https://github.com/IntellectualSites/PlotSquared/commit/465f7f4504b3fa2ce1b41395c7a43a13cc5a19ed#diff-b8133beb4c975e0df7492832ffc01c2eR116
As you can see, the flag is only introduced, but not used in that commit. The commit message ("Tweaks and doc updates.") also isn't helpful for finding out what it should do ;)

I deem it rather unlikely that a usage was added later and then removed again, but I haven't checked all commits since then.

Perhaps if it is set to false, interaction with beds ([here](../blob/breaking/Bukkit/src/main/java/com/github/intellectualsites/plotsquared/bukkit/listeners/PlayerEvents.java#L1902)) should be prevented?

**Comment by Sauilitired** [comment]
Indeed, it does seem that there's missing functionality.

**Comment by N0tMyFaultOG** [comment]
Sleep, Fire_Spread and Hanging_Interact are not in use (or never were).

**Comment by AeSix** [comment]
The only thing there that concerns me, is what were these supposed to do, and was that functionality counted on for other functions?

Either way, they've not been in use, and shouldn't have a whole lot of focus put on them right now.  They're failed feature implementations that should go back to feature requests, discussed thoroughly as to what they should actually do, and be implemented properly as such.  If at all.  Unless someone really feels the urge to do the work and PR the changes. 

Until then, I suggest the code be @deprecated or removed entirely for now.

But this is just my 2 cents.  :)
