### ISSUE TITLE
[last version] /p claim didn't work

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquared#2543]
**Debug paste link:** 
https://athion.net/ISPaster/paste/view/8c0ff5988f2d48609d7b76ba0fa7d612

**[REQUIRED] Spigot/Paper Version Number:** 
Paper version git-Paper-624 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**[REQUIRED] Minecraft Version Number:** 
1.13.2

**[REQUIRED] Description of the problem:** 

WARN after /p claim
https://pastebin.com/iLJXG50t

**Any relevant console output or screenshots:**
-

**Plugins being used on the server:**
see debugpaste for all

> PlotSquared-Bukkit-4.353
> FastAsyncWorldEdit-bukkit-1.13.192

**[REQUIRED] How to replicate:** 
/p claim

**[REQUIRED] Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
Update to the latest breaking PlotSquared. This is an FAWE issue.
