### ISSUE TITLE
Border problem

### ISSUE THREAD

**Issue by ExticDev** [IntellectualSites/PlotSquared#2545]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**Debug paste link:** 
https://www.athion.net/ISPaster/paste/view/90c5dbfd542c4ac2b6285c7852bbce7c ***Version Number:** 
Nukkit git-23adeaa

**[REQUIRED] Minecraft Version Number:** 
Minecraft:BE v1.12.0

**[REQUIRED] Description of the problem:** 
If I do an adhesive piston against a border, I can drag and drop the item on my plot.

**Any relevant console output or screenshots:**
Nothing...

**Plugins being used on the server:**

**[REQUIRED] How to replicate:** 

1. You place a piston against the border

2. you put a lever against Piston

3. Activate it and then you can drag and drop the block onto your plot

**Comment by AeSix** [comment]
This is a known issue with legacy builds (for Spigot, Nukkit, etc)
#2103 #2442 & #1484 as well as #613 & #285 

Please change this option to true and re-test
https://i.imgur.com/nqXcbUL.png

**Comment by MattBDev** [comment]
We can't modify the behavior of pistons on Nukkit since there is no API for us to use. Please file an issue with the Nukkit developers.

**Comment by Hajatoby** [comment]
https://ci.nukkitx.com/job/NukkitX/job/Nukkit/job/redstone/

**Comment by Hajatoby** [comment]
Here the Nukkit Redstone Version & API

**Comment by MattBDev** [comment]
@Hajatoby Why give me a link I already have?  The plugin is already compiled against that version. Sharing that link here after the issue is closed isn't really doing anything.

**Comment by Hajatoby** [comment]
Plugin? Its not a Plugin LuL it´s a Server Software XD

**Comment by N0tMyFaultOG** [comment]
Replacing plugin with software wouldn't make much sense here, anyway, Matt stated already everything.

**Comment by MattBDev** [comment]
I was clearly referring to PlotSquared as the plugin being compiled against the version of Nukkit you shared for no reason. Attempting to make me look dumb by sharing stupid details and misunderstanding what I say only makes me look smarter.
