### ISSUE TITLE
/plot clear performance problem

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/PlotSquared#2546]
__*NOTICE: Bukkit/Spigot versions 1.7.10 to 1.12.2 are considered legacy and will receive limited support. Please consider upgrading to 1.13 for future support. Plugins exist for 1.13+ that bring back old behaviors found in 1.8*__
# Bug report template 

**[REQUIRED] PlotSquared Version Number:**  PlotSquared-4.375

**[REQUIRED] Spigot/Paper Version Number:** Paper Build 221

**[REQUIRED] Minecraft Version Number:** 1.14.4

**Links to worlds.yml file and settings.yml file:** 
worlds.yml: https://pastebin.com/4QUjDJHn
settings.yml https://pastebin.com/JQu1Vraj

**[REQUIRED] Description of the problem:** 
When doing /plot clear there is a huge amount of tps loss, this is what I got with only 1 player online which was myself: https://timings.aikar.co/?id=a7d70c5b4dc1468d98fad7feff208021#timings

![Untitled](https://user-images.githubusercontent.com/10485646/67623242-cd607680-f81a-11e9-9bd4-bf888c1d79cc.png)

PlotSquared on 1.13.2 does not have this issue: https://timings.aikar.co/?id=2f77e7f832984a439f8137896eb9fd79

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
The main problem is 1.14.4 and how it handles saving data to disk. cpw (dev on MinecraftForge) wrote a bit about this on twitter. Make sure async chunk loading is on. Not much can be done about this at the moment without a major rewrite.
My hope is to merge the new FAWE code (when it is finished) into PlotSquared to improve performance. 
What are your server specs? I've already done a little bit of work on performance and it has actually improved compared to how it was a few months ago.

**Comment by SecretlyJealous** [comment]
> The main problem is 1.14.4 and how it handles saving data to disk. cpw (dev on MinecraftForge) wrote a bit about this on twitter. Make sure async chunk loading is on. Not much can be done about this at the moment without a major rewrite.
> My hope is to merge the new FAWE code (when it is finished) into PlotSquared to improve performance.
> What are your server specs? I've already done a little bit of work on performance and it has actually improved compared to how it was a few months ago.

This is a pretty big deal though since doing a plot clear can now effectively crash a server, I've got an i9-9900k and a m.2 NVMe drive. Surely this must be a priority.

**Comment by AeSix** [comment]
So, you have 505x256x505 block plots... 
That's a lot of data to move, regardless of your CPU/RAM/storage.  
That's 4 to 9 region files worth of data that has to be manipulated. 

Nothing says you can't have plots that large, but with sane limits, there's no issue with clearing plots.  I'm admittedly using an older build of P2, and it clears my plots with no tps loss, no latency increase, and does so with WorldEdit in under 2 seconds on ~100^2 plots.  Of course, I'm dealing with 1/26th of the data you are. 

If everything that negatively affected every server were a priority, the term would be meaningless.  I believe there are higher priorities, which affect more than a few edge case scenarios.  I may be wrong.  But like Matt said, it's being worked on.  That takes time, and the devs spend as much time as they have and can spare to developing P2 and FAWE.

**Comment by SecretlyJealous** [comment]
I'm trying to understand what could cause such a horrible performance regression when it worked just fine in 1.12.2 and 1.13.2 (as shown in timings link). I'm going to assume that having FAWE installed made plot clears fast. Regardless, I find it very strange that there is so much tps loss with just 1 person clearing a plot. I understand that the plot size is large, but anything that can cause a server crash (when it never used to) is concerning to me. I'll try to do some investigation on how /plot clear works in general.

**Comment by AeSix** [comment]
Two things affect your performance differences here.
1) Mojang's method of storing data has changed, for the worse, in 1.14 (works better for Vanilla though)
2) FAWE was using methods to improve upon the old storage system in Minecraft, which is no longer compatible with the new storage methods from Mjoang.  The FAWE devs are working to solve that, afaik. 

Yes, it is concerning.  And yes, if you were having no issue previously with the same configurations and setup with older versions, then you are right to be upset.  But patience is the key here, unless you can give a hand with developing FAWE.  1.13 broke sooooo much, and the devs are still playing catch-up with that, as well as trying to fix the things broken in 1.14.

**Comment by Sauilitired** [comment]
Plot clearing performs well in version 5 and no performance issues has been reported lately.
