### ISSUE TITLE
Not working/Crashes server

### ISSUE THREAD

**Issue by Miniller** [IntellectualSites/PlotSquared#2549]
First time I installed the latest version, it simply crashed the server...
Now, I downloaded an older version (server version 1.8.8), and it is not working.
This is the error:
`27.10 13:07:55 [Server] ERROR Could not load 'plugins/PlotSquared-Bukkit-4.196.jar' in folder 'plugins'
27.10 13:07:55 [Server] INFO org.bukkit.plugin.InvalidPluginException: java.lang.NoSuchMethodError: org.bukkit.Material.getMaterial(Ljava/lang/String;Z)Lorg/bukkit/Material;
27.10 13:07:55 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot_1.8.8.jar:git-Spigot-21fe707-e1ebe52]
27.10 13:07:55 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot_1.8.8.jar:git-Spigot-21fe707-e1ebe52]
27.10 13:07:55 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot_1.8.8.jar:git-Spigot-21fe707-e1ebe52]
27.10 13:07:55 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot_1.8.8.jar:git-Spigot-21fe707-e1ebe52]
27.10 13:07:55 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:739) [spigot_1.8.8.jar:git-Spigot-21fe707-e1ebe52]
27.10 13:07:55 [Server] INFO at org.bukkit.Bukkit.reload(Bukkit.java:535) [spigot_1.8.8.jar:git-Spigot-21fe707-e1ebe52]
27.10 13:07:55 [Server] INFO at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot_1.8.8.jar:git-Spigot-21fe707-e1ebe52]
27.10 13:07:55 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot_1.8.8.jar:git-Spigot-21fe707-e1ebe52]
27.10 13:07:55 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot_1.8.8.jar:git-Spigot-21fe707-e1ebe52]
27.10 13:07:55 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot_1.8.8.jar:git-Spigot-21fe707-e1ebe52]
27.10 13:07:55 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot_1.8.8.jar:git-Spigot-21fe707-e1ebe52]
27.10 13:07:55 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot_1.8.8.jar:git-Spigot-21fe707-e1ebe52]
27.10 13:07:55 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot_1.8.8.jar:git-Spigot-21fe707-e1ebe52]
27.10 13:07:55 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot_1.8.8.jar:git-Spigot-21fe707-e1ebe52]
27.10 13:07:55 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
27.10 13:07:55 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
27.10 13:07:55 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot_1.8.8.jar:git-Spigot-21fe707-e1ebe52]
27.10 13:07:55 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot_1.8.8.jar:git-Spigot-21fe707-e1ebe52]
27.10 13:07:55 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot_1.8.8.jar:git-Spigot-21fe707-e1ebe52]
27.10 13:07:55 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot_1.8.8.jar:git-Spigot-21fe707-e1ebe52]
27.10 13:07:55 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot_1.8.8.jar:git-Spigot-21fe707-e1ebe52]
27.10 13:07:55 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
27.10 13:07:55 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.Material.getMaterial(Ljava/lang/String;Z)Lorg/bukkit/Material;
27.10 13:07:55 [Server] INFO at com.github.intellectualsites.plotsquared.bukkit.util.BukkitLegacyMappings.addAll(BukkitLegacyMappings.java:699) ~[?:?]
27.10 13:07:55 [Server] INFO at com.github.intellectualsites.plotsquared.bukkit.util.BukkitLegacyMappings.<init>(BukkitLegacyMappings.java:672) ~[?:?]
27.10 13:07:55 [Server] INFO at com.github.intellectualsites.plotsquared.bukkit.BukkitMain.<init>(BukkitMain.java:82) ~[?:?]
27.10 13:07:55 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
27.10 13:07:55 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
27.10 13:07:55 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
27.10 13:07:55 [Server] INFO at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
27.10 13:07:55 [Server] INFO at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_191]
27.10 13:07:55 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot_1.8.8.jar:git-Spigot-21fe707-e1ebe52]
27.10 13:07:55 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot_1.8.8.jar:git-Spigot-21fe707-e1ebe52]
27.10 13:07:55 [Server] INFO ... 21 more`

**Comment by N0tMyFaultOG** [comment]
Please read the page properly and download the correct version https://www.spigotmc.org/resources/plotsquared.1177/
