### ISSUE TITLE
Plot clearing visual bug

### ISSUE THREAD

**Issue by Theepwner** [IntellectualSites/PlotSquared#255]
Often times when a plot is cleared when the building has some height to it, there will be a remainder of blocks. The blocks left over are of course visual, not really there. Also, I've noticed that it is normally blocks a bit above the surface that may experience this visual glitch.

Example: http://i.imgur.com/Vkw8X42.png

**Comment by Theepwner** [comment]
Is this fixed? I just deleted a plot that was full of fences (created lag) and they were all removed.

Might need to confirm if you don't remember fixing this.

**Comment by boy0001** [comment]
This has been fixed.
