### ISSUE TITLE
NoClassDefFound thrown on Startup

### ISSUE THREAD

**Issue by zachrocks22** [IntellectualSites/PlotSquared#2550]
**Debug paste link:** https://athion.net/ISPaster/paste/view/6405bb818a89495ca48fd9416f0ba703

**Spigot/Paper Version Number:** Paper-223

**Minecraft Version Number:**  1.14.4

**Description of the problem:** On startup, PlotSquared throws a(n) "NoClassDefFoundError: retrofit2/Retrofit$Builder" error. This version of plotsquared was recently updated to the latest breaking build from Jenkins, in addition to updating ProtocolLib, PaperSpigot, and WorldEdit/WorldGuard.

**Any relevant console output or screenshots:** https://pastebin.com/raw/Z0RaS7DX

**How to replicate:** 
After updating to the latest breaking build, I noticed the large stack-trace error shown above being thrown.
It appears on every startup. However, I just updated ProtocolLib (latest dev build), Paper Spigot (updated from build 221 to 223), and WorldEdit (latest build from enginehub). I'm wondering if one of these newly updated resources could be influencing this PlotSquared stacktrace? 

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by AeSix** [comment]
@N0tMyFaultOG Thanks for the clean up.  I was being a bit silly with all the labels 😜 

@zachrocks22 - Thank you for the report, this will be handled in the next release! WOOO HOO!!!
