### ISSUE TITLE
Missing bukkit module in api

### ISSUE THREAD

**Issue by N0tMyFaultOG** [IntellectualSites/PlotSquared#2551]
Just leaving a small note here; the bukkit module is missing in the api. It contains only the core module, yet I've seen a lot of people who wanted to access it thru maven recently or needed/wanted to work with the bukkit events and had to import it locally (which shouldn't be the aim when providing an api). I think it's worth including the module, which makes things easier.

**Comment by MattBDev** [comment]
What specific functionality is missing from the Core module that is present in the Bukkit one? If I knew what was missing I can fill in the gaps in Core and document them to make it easier for people.

**Comment by N0tMyFaultOG** [comment]
Certain events like `PlayerEnterPlotEvent` e.g only exist in the bukkit module.

**Comment by Sauilitired** [comment]
Also Bukkit utility classes, and other platform specific code. It makes sense to allow people to access the Bukkit jar directly as there’s a demand for it (even more so, considering we only publish v4 for Bukkit).

However, some effort was made last year to move certain API components back to Core, although it doesn’t seem to be enough.
