### ISSUE TITLE
NPE when trying to create Plots in current world

### ISSUE THREAD

**Issue by bloggy** [IntellectualSites/PlotSquared#2562]
# NOTICE: 
```diff
! PlotSquared for Minecraft Java Edition versions between 1.7 through to 1.12.2 are considered
! legacy, and will receive limited to no support. Please consider upgrading to 1.13+ for
! future support.  Plugins exist for 1.13+ which bring back behaviors found in 1.8.8
! All versions of PlotSquared for Sponge and Nukkit(X) will recieve limited to no support
! due to lack of developer interest and time. Additionally, NukkitX has not had feature
! updates since the Better Together, which prevents some PlotSquared features from ever
! functioning.  Contributions are always welcome however!
```

**Feature requests & Suggestions are to be submitted at the [PlotSquared Suggestions tracker](https://github.com/IntellectualSites/PlotSquaredSuggestions)**

**Code contributions are to be done through [PRs](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request), tagging the specific issue ticket(s) if applicable.**

**[DISCORD INVITE LINK](https://discord.gg/cSMxtGn)** and please, for the love of the little sanity we have left, use the correct channels!

# BUG REPORT TEMPLATE:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server type:
**select one**

- [ X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [ ] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [ ] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**select one**

- [ ] Minecraft 1.14.4 ***This is the ONLY actively maintained target for PlotSquared***
- [ X] Minecraft 1.13.2
- [ ] Minecraft Java Edition *other versions, please specify*:
- [ ] Minecraft Bedrock Edition *speicify version*:

### Server build info: 

``` This server is running Paper version git-Paper-617 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT) ```

### WorldEdit/FAWE versions:

- [X ] FAWE *version*: 	FastAsyncWorldEdit-bukkit-1.13.193.jar	
- [ ] WorldEdit *version*: 

### Description of the problem:

I was trying to create a plot within an existing world as per manual / wiki. You can see the commands I have entered in the log:
NPE log:
https://pastebin.com/MgMxcx5g

### How to replicate:

Enter the commands as provided in the log

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Other plugins being used on the server:

Essentials, EssentialsSpawn, FastAsyncWorldEdit, Fe*, Multiverse-Core, PermissionsEx*, PlotSquared, ProtocolLib*, Vault, WorldEdit, WorldGuard

### Relevant console output, log lines, and/or screenshots:

https://pastebin.com/MgMxcx5g

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [x ] I included all information required in the sections above
- [x ] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x ] I made sure I am using an up-to-date version of PlotSquared
- [x ] I made sure the bug/error is not caused by any other plugin
- [ ] I didn't read but checked everything above.

**Comment by N0tMyFaultOG** [comment]
Remove Fawe/DummyFawe and give it a try with WorldEdit please.

**Comment by bloggy** [comment]
Thanks, it works without FAWE. But we need FAWE (or a similar plugin) for performance reasons. Maybe you can recommend me a version of Fawe that works fine together with PlotSquared?

**Comment by N0tMyFaultOG** [comment]
The 1.14 snapshots do. There's no ETA to backport the changes
