### ISSUE TITLE
Road schematics remove plot owner signs

### ISSUE THREAD

**Issue by Theepwner** [IntellectualSites/PlotSquared#257]
I have found that using road schematics will remove the plot signs of all current plots. To get the sign back, you must re-claim the plot.

Note: This isn't an issue of a block from the road schematic blocking where the sign should be. (well, air counts I guess).

Is there a way to preserve the plot signs?
Edit: I'm talking about these: http://i.imgur.com/YFqnuK1.png

**Comment by boy0001** [comment]
There's now a script to fix all signs:
https://github.com/IntellectualSites/PlotSquared/wiki/Scripting#example-scripts
