### ISSUE TITLE
Blocklist flags (use, place, break) are broken

### ISSUE THREAD

**Issue by mindw0rm** [IntellectualSites/PlotSquared#2573]
# NOTICE: 
```diff
! PlotSquared for Minecraft Java Edition versions between 1.7 through to 1.12.2 are considered
! legacy, and will receive limited to no support. Please consider upgrading to 1.13+ for
! future support.  Plugins exist for 1.13+ which bring back behaviors found in 1.8.8
! All versions of PlotSquared for Sponge and Nukkit(X) will recieve limited to no support
! due to lack of developer interest and time. Additionally, NukkitX has not had feature
! updates since the Better Together, which prevents some PlotSquared features from ever
! functioning.  Contributions are always welcome however!
```

**Feature requests & Suggestions are to be submitted at the [PlotSquared Suggestions tracker](https://github.com/IntellectualSites/PlotSquaredSuggestions)**

**Code contributions are to be done through [PRs](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request), tagging the specific issue ticket(s) if applicable.**

**[DISCORD INVITE LINK](https://discord.gg/cSMxtGn)** and please, for the love of the little sanity we have left, use the correct channels!

# BUG REPORT TEMPLATE:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (Debug/file paste links):

https://athion.net/ISPaster/paste/view/cbe3b54357654ea7b931a6b1ed9a6a69

### Server type:
**select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**select one**

- [X] Minecraft 1.14.4 ***This is the ONLY actively maintained target for PlotSquared***
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

``` 
[17:32:42] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-56f8471-56118c6 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[17:32:42] [Server thread/INFO]: Checking version, please wait...
[17:32:43] [Thread-9/INFO]: You are running the latest version
 ```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [X] WorldEdit *version*: 7.0.1;61bc012

### Description of the problem:

The blocklist flags, i.e. use, break and place, stopped working with the newest version (4.390). This means that you cannot place/break/use blocks which are in those flags. 

I tracked the issue down to [this commit](https://github.com/IntellectualSites/PlotSquared/commit/37f608258fcbc016e5603414d41cf698a1bba9a1#diff-f138b9e605e5a88f9576255bcb34a93dL103), where a Supplier<**BlockState**> is provided to EventUtil::checkPlayerBlockEvent, but the flags values are of type Set<**BlockType**>. Obviously the call to `contains` must fail. 

### How to replicate:

* Add some block types to the flags (in my test I used `/p flag add use lever`, `/p flag add place sand` and `/p flag add break sand`) of some plot. Put those blocks on the plot (e.g. a lever and some sand).
* Log in as a different user that is not added to the plot
* try to use, break or place the blocks

## Additional Information:
I already made a [bugfix](https://github.com/mindw0rm/PlotSquared/commit/35bbc45ac511cdf1dc2a41f9b345b66462edd7bc), you'll get a pull request soon. 

### Other plugins being used on the server:
none (except WorldEdit) - this is only a test server

### Relevant console output, log lines, and/or screenshots:

n/a

### Additional relevant comments/remarks:

I kept the preamble of the bug template, since it says that I should not remove it, but do you really want it? Imho everything above "Server config info" could be removed and the bug would be easier to read ... 

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by mindw0rm** [comment]
PR needs some time, I just realized that I forgot some flag usages which were not relevant to my testing :/

**Comment by N0tMyFaultOG** [comment]
Fixed in https://github.com/IntellectualSites/PlotSquared/commit/765a021ecdbf86ad3996546ec9d5a67a04d8550d, sorry but Jesse didn't see this one.
