### ISSUE TITLE
WorldGenerator of p2 complete broke

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#2576]
# NOTICE: 
```diff
! PlotSquared for Minecraft Java Edition versions between 1.7 through to 1.12.2 are considered
! legacy, and will receive limited to no support. Please consider upgrading to 1.13+ for
! future support.  Plugins exist for 1.13+ which bring back behaviors found in 1.8.8
! All versions of PlotSquared for Sponge and Nukkit(X) will recieve limited to no support
! due to lack of developer interest and time. Additionally, NukkitX has not had feature
! updates since the Better Together, which prevents some PlotSquared features from ever
! functioning.  Contributions are always welcome however!
```

**Feature requests & Suggestions are to be submitted at the [PlotSquared Suggestions tracker](https://github.com/IntellectualSites/PlotSquaredSuggestions)**

**Code contributions are to be done through [PRs](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request), tagging the specific issue ticket(s) if applicable.**

**[DISCORD INVITE LINK](https://discord.gg/cSMxtGn)** and please, for the love of the little sanity we have left, use the correct channels!

# BUG REPORT TEMPLATE:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server type:
**select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**select one**

- [X] Minecraft 1.14.4 ***This is the ONLY actively maintained target for PlotSquared***
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```This server is running Paper version git-Paper-224 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[19:59:37 INFO]: Checking version, please wait...
[19:59:38 INFO]: Previous version: git-Paper-209 (MC: 1.14.4)
[19:59:38 INFO]: You are 2 version(s) behind
```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [X] WorldEdit *version*: WorldEdit 7.0.1 (1.13.2 - 1.14.4)

### Description of the problem:

Look at the screen. the complete Plotworld is broke. All my Players lost thier gamestate http://prntscr.com/pwjg5c

### How to replicate:

Generate a world and run to random coordinates. this chunkerrors apperar random. and can be the result of the /p trim function. I dont know how to replicate this but i think its the /p trim function.

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.
I think it is /p trim or the plotsquared generator

### Other plugins being used on the server:

WordEdit and p2 and essentials and a self codet scoreboard system and a citybuild system all selfcode and dont affect the word

### Relevant console output, log lines, and/or screenshots:

https://pastebin.com/kCNTJbSf

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [x] I didn't read but checked everything above.

**Comment by N0tMyFaultOG** [comment]
Debugpaste and/or links to the required files are missing.
