### ISSUE TITLE
Plot trim issue

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#2577]
# NOTICE: 
```diff
! PlotSquared for Minecraft Java Edition versions between 1.7 through to 1.12.2 are considered
! legacy, and will receive limited to no support. Please consider upgrading to 1.13+ for
! future support.  Plugins exist for 1.13+ which bring back behaviors found in 1.8.8
! All versions of PlotSquared for Sponge and Nukkit(X) will recieve limited to no support
! due to lack of developer interest and time. Additionally, NukkitX has not had feature
! updates since the Better Together, which prevents some PlotSquared features from ever
! functioning.  Contributions are always welcome however!
```

**Feature requests & Suggestions are to be submitted at the [PlotSquared Suggestions tracker](https://github.com/IntellectualSites/PlotSquaredSuggestions)**

**Code contributions are to be done through [PRs](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request), tagging the specific issue ticket(s) if applicable.**

**[DISCORD INVITE LINK](https://discord.gg/cSMxtGn)** and please, for the love of the little sanity we have left, use the correct channels!

# BUG REPORT TEMPLATE:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (Debug/file paste links):

https://athion.net/ISPaster/paste/view/00188be1f40b4e0ba7c802475f91bf2f

### Server type:
**select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**select one**

- [X] Minecraft 1.14.4 ***This is the ONLY actively maintained target for PlotSquared***
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

``` This server is running Paper version git-Paper-224 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[20:20:55 INFO]: Checking version, please wait...
[20:20:55 INFO]: Previous version: git-Paper-209 (MC: 1.14.4)
[20:20:55 INFO]: You are 2 version(s) behind 
```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [X] WorldEdit *version*: WorldEdit 7.0.1 (1.13.2 - 1.14.4)

### Description of the problem:

The Problem is that my PlotWorld on some regions are complete broke. All my players lost thier Plots. I think that is the /plot trim command that i use ab und zu or your generator is broke.

### How to replicate:

I dont know how to replicate but here is a way that is possible.
Generate a plotworld and look on the complete world. fly throught the world eg.

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.
I think it is the generator or /p trim

### Other plugins being used on the server:

Only WorldEdit CityBuildSystem and P2

### Relevant console output, log lines, and/or screenshots:

```https://pastebin.com/kCNTJbSf````

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [x] I didn't read but checked everything above.

**Comment by N0tMyFaultOG** [comment]
That has nothing to do with the plot generator. The name may be misleading, it does not generate plots, it just tells your server how to do that. Also, your version is not up to date, so [update](https://ci.athion.net/job/PlotSquared-Breaking/lastSuccessfulBuild/artifact/target/PlotSquared-Bukkit-4.399.jar) it first.

**Comment by DevJoey** [comment]
I have the newest spigot build

**Comment by N0tMyFaultOG** [comment]
> I have the newest spigot build

That is not what I said, I was talking about your PlotSquared version, hence I linked you a newer build and not a newer spigot build.

**Comment by mnjg123** [comment]
He has the latest version available on SpigotMC

**Comment by AeSix** [comment]
Update to PlotSquared 4.40.
Closing ticket.
If the issue persists, re-open.
