### ISSUE TITLE
World module flag bypass (per world permissions)

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquared#2579]
I think it's a bug, and not a feature request: https://github.com/IntellectualSites/PlotSquaredSuggestions/issues/16

--> `plots.gamemode.bypass` for a specifically world not work. (After the world-join the bypass down't work.)

I've not tested it currently.

**Comment by AeSix** [comment]
Please follow the template. I have questions that would have been answered if you had. 
Closing.

**Comment by RedstoneFuture** [comment]
I can't transfer an issue. So I open a question ticket.
I have not more info, because I've not tested it. - But I think it's not a feature request. That's why I added the "testing required" label. And I think the point is understandable.


> Description of the suggestion:
Currently if you have the world module enabled, and give a specific player the plots.gamemode.bypass permission only on a specific world (using e.g. /lp user [user] permission set plots.gamemode.bypass true world=[world] it will not actually allow the player to bypass the gamemode change when they enter the world. It will however work if you set the permission globally, but that's not preferred as it will also bypass all other world gamemodes.
Preferably make it so that when this permission is set in this specific world, the player will bypass in this world only.

issue by GuusLieben

**Comment by AeSix** [comment]
So, you're opening a bug report for something you have not tested?
You don't know what permission manager is in use, or brand or version of Minecraft server, much less the PlotSquared version?

If you want to open a bug report, follow the template.
