### ISSUE TITLE
Cool idea / prepare for construction

### ISSUE THREAD

**Issue by DustKing5** [IntellectualSites/PlotSquared#2580]
Very cool plugin. There's a lot of cool stuff in it.

But I miss one thing. When someone gets a plot, you can use it all. It would be cooler to first get only a part of the plot. For example, a center of the plot and each ring should be bought separately as if you were cleaning the plot (you prepare it for construction).
I think that would be very cool.

Best wishes!

**Comment by AeSix** [comment]
Failure to read instructions.
Failure to follow instructions.
Failure to use appropriate issue tracker.
Closing ticket.

**Comment by MattBDev** [comment]
@AeSix just transfer the issue to the PS suggestions repo.
