### ISSUE TITLE
Bug caused by wall_sign(s)

### ISSUE THREAD

**Issue by Lusteroth** [IntellectualSites/PlotSquared#2588]
# NOTICE:
```diff
! PlotSquared for Minecraft Java Edition versions between 1.7 through to 1.12.2 are considered
! legacy, and will receive limited to no support. Please consider upgrading to 1.13+ for
! future support.  Plugins exist for 1.13+ which bring back behaviors found in 1.8.8
! All versions of PlotSquared for Sponge and Nukkit(X) will recieve limited to no support
! due to lack of developer interest and time. Additionally, NukkitX has not had feature
! updates since the Better Together, which prevents some PlotSquared features from ever
! functioning.  Contributions are always welcome however!
```
 
**Feature requests & Suggestions are to be submitted at the [PlotSquared Suggestions tracker](https://github.com/IntellectualSites/PlotSquaredSuggestions)**
 
**Code contributions are to be done through [PRs](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request), tagging the specific issue ticket(s) if applicable.**
 
**[DISCORD INVITE LINK](https://discord.gg/cSMxtGn)** and please, for the love of the little sanity we have left, use the correct channels!
 
# BUG REPORT TEMPLATE:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (Debug/file paste links):

 https://athion.net/ISPaster/paste/view/25246bb7b2934954870e8c6f19f9b4a3

 

 
 
 
### Server type:
**select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*
 
### Minecraft Version:
**select one**

- [X] Minecraft 1.14.4 ***This is the ONLY actively maintained target for PlotSquared***
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:
 
### Server build info:

``` Paper 1.14.4 Build 226 ```
 
### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [X] WorldEdit *version*:  WorldEdit 7.0.1 (1.13.2 - 1.14.4)
 
### Description of the problem:

 
Clicking on a _wall_sign causes an error; wall_signs aren't accepted/useable in flags like "use" anymore. "Normal" signs aren't affected.
 
### How to replicate:

 
Place a sign at a block and click the sign (for example, signs are often used as a shop sign of ChestShop)
 
## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.
 
 
### Other plugins being used on the server:

 
WorldEdit, WorldGuard
 
### Relevant console output, log lines, and/or screenshots:

 
https://pastebin.com/RC2Z7RdF
 
### Additional relevant comments/remarks:

 
# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by AeSix** [comment]
should be spruce_wall_sign oak_wall_sign etc.

**Comment by Lusteroth** [comment]
What do you mean? "oak_wall_sign" is used; not "wall_sign" or something else

**Comment by AeSix** [comment]
You failed to be specific. 
https://minecraft.gamepedia.com/Sign#ID
These are the current sign ids from 1.13+

**Comment by Lusteroth** [comment]
The bug is caused by the following ids:

oak_wall_sign, spruce_wall_sign, birch_wall_sign, jungle_wall_sign, acacia_wall_sign and dark_oak_wall_sign 

https://pastebin.com/HA0R7Vtr

**Comment by N0tMyFaultOG** [comment]
I was able to reproduce the described behavior. If you set the `use` flag e.g and add signs as material and click on a `*_wall_sign` the named stacktrace is fired.

**Comment by Lusteroth** [comment]
Looks like it's fixed in Build 419 :)

**Comment by N0tMyFaultOG** [comment]
Fixed in https://github.com/IntellectualSites/PlotSquared/commit/9925a320f54a2aed2048f5c97d02ba6115cad62f
Tested on build 420
