### ISSUE TITLE
java.lang.NoClassDefFoundError: com/sk89q/worldedit/math/BlockVector2

### ISSUE THREAD

**Issue by swerck** [IntellectualSites/PlotSquared#2589]
# NOTICE: 
```diff
! PlotSquared for Minecraft Java Edition versions between 1.7 through to 1.12.2 are considered
! legacy, and will receive limited to no support. Please consider upgrading to 1.13+ for
! future support.  Plugins exist for 1.13+ which bring back behaviors found in 1.8.8
! All versions of PlotSquared for Sponge and Nukkit(X) will recieve limited to no support
! due to lack of developer interest and time. Additionally, NukkitX has not had feature
! updates since the Better Together, which prevents some PlotSquared features from ever
! functioning.  Contributions are always welcome however!
```

**Feature requests & Suggestions are to be submitted at the [PlotSquared Suggestions tracker](https://github.com/IntellectualSites/PlotSquaredSuggestions)**

**Code contributions are to be done through [PRs](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request), tagging the specific issue ticket(s) if applicable.**

**[DISCORD INVITE LINK](https://discord.gg/cSMxtGn)** and please, for the love of the little sanity we have left, use the correct channels!

# BUG REPORT TEMPLATE:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server type:
**select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**select one**

- [x] Minecraft 1.14.4 ***This is the ONLY actively maintained target for PlotSquared***
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

``` paste here, between the tick marks, replacing this text ```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [] WorldEdit *version*: 

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [] I made sure the bug/error is not caused by any other plugin
- [x] I didn't read but checked everything above.

https://athion.net/ISPaster/paste/view/fbc60a564bac49d69255fc31fe406fcb

**Comment by N0tMyFaultOG** [comment]
Update [WorldEdit](https://dev.bukkit.org/projects/worldedit/files). Also, please make sure to fill out the template if you want enhanced support.

**Comment by swerck** [comment]
i have WE 7.0.1 installed

**Comment by swerck** [comment]
after plots trim [World] in console and restart the error is gone.

Can I trim the world automatically?

**Comment by AeSix** [comment]
There's nothing in P2 to do such, but you can add the command to your start script.  I would wrap that with a whitelist on and whitelist off commands as well though, so no players will be able to log on while the trim is happening.  To do it properly, you'll need to tail the logs/latest.log file to watch for the completion.  If you're restarting every day, the trim shouldn't take too long, and you can just delay the whitelist off by 2-3 times the duration of the trim - to be on the same side.  

Of course, I personally wouldn't do a trim on every start, and handle it only on error - of course, you can do that with your start script as well.  This is provided you're using gnu screen or tmux, and are able to push commands from your shell into the screen/tmux session (It's possible, but don't know the access you have)

If that's not viable, you might be able to look at doing a commandhelper script which will run the command on startup.  Personally, I prefer to use the bash script for things like that though. 

Anyways, problem solved, closing ticket. 

And yes, next time you have to report an issue on github, regardless if it's for PlotSquared or not, please follow the template and give as much information as possible.  It helps greatly for the devs and helpers to figure out what's going on, what the prescribed solution should be, etc.
