### ISSUE TITLE
Cant set plot Biome and no message on unknown biome

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#2599]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (Debug/file paste links):

https://athion.net/ISPaster/paste/view/62f2f977f4f2436a82c44da699bc2a0f

### Server type:
**select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**select one**

- [x] Minecraft 1.14.4 ***This is the ONLY actively maintained target for PlotSquared***
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
This server is running Paper version git-Paper-226 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [x] WorldEdit *version*: 

### Description of the problem:

I cant set the Plot biome. and i get a random error message in console.

### How to replicate:

Bug 1: Go to a owned plot and type /plot setbiome FOREST you will get the Message, a timer was bound to you or the plot. (Ein zeitgeber wurde an dich gebunden.)
Bug 2: Go to the Plot and type /plot setbiome THISBIOMECANTEXISTS -> You get no Unknown Biome message, you get A Timer was bound to you or the plot.
## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Other plugins being used on the server:

CityBuildSystem by JoeyPlayzTV, PlotSquared, WorldEdit
### Relevant console output, log lines, and/or screenshots:

```[PlotSquared] Task #274408 for PlotSquared v4.408 generated an exception
java.lang.NullPointerException: biomeType is marked non-null but is null
	at com.github.intellectualsites.plotsquared.bukkit.util.BukkitUtil.setBiomes(BukkitUtil.java:422) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.util.MainUtil.setBiome(MainUtil.java:575) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.object.Plot$2$1.run(Plot.java:950) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.object.Plot$2$1.run(Plot.java:946) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.object.RunnableVal.run(RunnableVal.java:14) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.util.ChunkManager$3.run(ChunkManager.java:190) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-226]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-226]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-226]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-226]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-226]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-226]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]```
### Additional relevant comments/remarks:
<!--- Use this space to give us any additional information which may be relevant to this issue, such as: if you are using a Minecraft hosting provider; unusual installation environment; etc -->

# AFFIRMATION OF COMPLETION:
<!-- Make sure you have completed the following steps (put an "X" between of brackets): -->
- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [x] I didn't read but checked everything above.

**Comment by Resi23** [comment]
same here paper 226 und Plotsquared v4.400

**Comment by N0tMyFaultOG** [comment]
The named stacktrace above occurs if you attempt to set an invalid biome. Yet it tries to perform the action still, even if the biome does not exist. Hence it calls the setblock timer.

**Comment by AeSix** [comment]
seems "forest" /is/ a legit biome. 
Also seems that a list of biomes should be checked and invalid biomes invalidated and the time halted. 

@DevJoey add the version of WorldEdit you're using as well, please.  This could potentially be of consequences.

**Comment by Resi23** [comment]
i have Bukkit-Official (7.1.0-SNAPSHOT;4738-89bc664)

**Comment by DevJoey** [comment]
My worldedit version is: 7.0.1

**Comment by AeSix** [comment]
The summary:
1) "forest" biome won't set, which it seemingly /is/ a valid biome
2) Attempting to set an invalid biome is not halted properly in code

Is this correct?
Does this happen when using FAWE? Does this happen if using Spigot in stead of Paper?

**Comment by N0tMyFaultOG** [comment]
Tested on build 420, issue persists still.
Note for further reference: It appears you need to type `/plot setbiome minecraft:<biome>` now. Maybe it'd be worth to slice the biome part, so people don't need to type it all

**Comment by AeSix** [comment]
This could be manipulated as the end result of checking if the biome actually exists, right?
on command, check if the biome /is actually/ a biome (if it's not, halt the function and report an error), otherwise add "minecraft:" to the command, and finish the process.  I don't know though, just a thought (and question)
