### ISSUE TITLE
Inventory menu to teleport to a player plot Example /plot menu

### ISSUE THREAD

**Issue by thu2468** [IntellectualSites/PlotSquared#26]
If you can add a menu GUI to click a player head and you would teleport to his or her plot. 
- when you do the command /plot menu it would bring up a inventory of player head that currently own a plot. 
- You click on a head it would open up another inventory where there paper for w.e many plot they have with the chunk cord and/or plot alias. 
- Also in the main inventory (player heads), There should be a arrow on bottom left and right for next page. 
- There should also be a item at the bottom some where to search for a player head name. If they do a partial of a name then it would show couple of player head to select from. So if i type D then it would show me all the player with a plot with the name begin with D. 
- Also your player head at the bottom to teleport to your own plots

Related plugins:
- http://dev.bukkit.org/bukkit-plugins/plotmenpc/

**Comment by boy0001** [comment]
*Also inventory menu to choose schematics on claim.

**Comment by boy0001** [comment]
Note to self:
 - Use new PlotInventory class as it makes things easier
 - Refer to MusicSubcommand for example
