### ISSUE TITLE
Clearing the Plot Causes Issues

### ISSUE THREAD

**Issue by zachrocks22** [IntellectualSites/PlotSquared#2600]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (Debug/file paste links):
https://athion.net/ISPaster/paste/view/7b9b3fba1d174347a40b8f3080caa907

### Server type:

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*

### Minecraft Version:
- [X] Minecraft 1.14.4 ***This is the ONLY actively maintained target for PlotSquared***

### Server build info: 

```
Paper-230 (MC: 1.14.4)
```

### WorldEdit/FAWE versions:

- FAWE *N/A*
- [X] WorldEdit *7.1.0-SNAPSHOT;4701-21f3d96*: 

### Description of the problem:

When clearing any plot that has a form of container on it, it seems to throw a few errors in console describing what sounds like world corruption. I can confirm the clear is successful, and the world is not corrupted, but it does throw a spooky disclaimer in the console. 

### How to replicate:

1. Claim a Plot
2. Place a Chest
3. Clear the Plot

### Relevant console output, log lines, and/or screenshots:
https://pastebin.com/raw/HAhUXeY0
<img width="952" alt="Screen Shot 2019-11-24 at 12 06 56 PM" src="https://user-images.githubusercontent.com/10857265/69498192-ef4d2780-0eb2-11ea-89d9-684becedc23a.png">

### Additional relevant comments/remarks:
Issue has only appeared recently. Other than that, I really have no clue.

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
That is not a PlotSquared issue, set `remove-corrupt-tile-entities` in the paper.yml to true.

**Comment by zachrocks22** [comment]
Alright! Thank you. :)
