### ISSUE TITLE
Animal-Cap not working on merged plots

### ISSUE THREAD

**Issue by Resi23** [IntellectualSites/PlotSquared#2602]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (Debug/file paste links):
Debugpaste: https://athion.net/ISPaster/paste/view/b86b05ab65cf4c9fae538d1c836c5aae

### Server type:
**select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**select one**

- [X] Minecraft 1.14.4 ***This is the ONLY actively maintained target for PlotSquared***
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
Paper-230 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [X] WorldEdit *version*: Bukkit-Official (7.1.0-SNAPSHOT;4738-89bc664)

### Description of the problem:

Animal-Cap not working on merged plots

### How to replicate:

Merge 2 or more Plots set Animal-Cap and spawn Chickens with egg. 
![Image](https://i.imgur.com/DPZhVDy.png)

## Additional Information:

Singleplots dont have the Problem.
![Image](https://i.imgur.com/RKZjmZo.png)

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by RedstoneFuture** [comment]
@N0tMyFaultOG Was this a bug for all restriction flags on merged plots?

**Comment by Sauilitired** [comment]
Cannot replicate in version 5. Checked using `/plot caps` and it applied across the entire mega-plot.
