### ISSUE TITLE
Tile entity content not moved over

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#2603]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (Debug/file paste links):

https://athion.net/ISPaster/paste/view/1d4d53f293a34d09b189791b15da41e2

### Server type:
**select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**select one**

- [x] Minecraft 1.14.4 ***This is the ONLY actively maintained target for PlotSquared***
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
This server is running Paper version git-Paper-226 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [x] WorldEdit *version*:  WorldEdit version 7.0.1;61bc012

### Description of the problem:

If i move a plot then this error occurs and contents of barrels are not moved. the barrel on the moved plot are empty. the old moved plot get not be cleared. Iam use a older version on my server but the bug is still present in the newest dev build of p2 (Testet)

### How to replicate:

Move a plot with barrels that are filled with items. generally move plots. 

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Other plugins being used on the server:

Only P2, WE and MULTIVERSE

### Relevant console output, log lines, and/or screenshots:

https://hasteb.in/pezixifu.md

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [ ] I didn't read but checked everything above.

**Comment by MattBDev** [comment]
You didn't read but check every box anyways. 🤔

**Comment by DevJoey** [comment]
Iam sorry, i dont know what the last box exacly mean. Iam from Germany

**Comment by AeSix** [comment]
it's there for you to understand that you have to read and follow the previous 4 check-box lines. 
"I did not read" (pertaining to the 4 previous lines) "but checked everything above" (indicating the 4 previous lines)

It is a litmus test to tell us if the person who filed the ticket actually followed the instructions:
that it's a unique issue ticket, that no other plugins are causing the issue, that they're using the latest build of PS, and that all the information we require has been provided... If these 4 lines are checked off, and the fifth line as well, then we can take it to mean that the user did not read or follow these four things.  Or conversely, if the fifth line is unchecked, then we can reasonably assume that the person /has/ actually read and followed these requirements.   That's all it is, and nothing more important than that.  Oh, and gives us fodder for making fun of regular reporters :P

**Comment by N0tMyFaultOG** [comment]
Can reproduce with Paper 234 and P2 417

**Comment by Sauilitired** [comment]
The plot is copied over. The old plot remains exactly the same, except it's unclaimed. The borders are not moved over. 

Expected behaviour would be that `/plot move` would behave the same as if the following sequence of commands was executed:
`/plot copy x;z` <-- Copies the plot, including the borders
`/plot delete`  <-- Clears the plot

**Comment by AeSix** [comment]
This may just be me, but I would expect there to be a compare in there to make sure the duplicate plot is identical to the one it was copied from?  Or is that handled with the copy command?

**Comment by Sauilitired** [comment]
That would result in a lot of block comparisons. I think that's up to the user, to be honest.

**Comment by AeSix** [comment]
You... can't compare a plot to a plot that's been deleted?

**Comment by Sauilitired** [comment]
I thought you meant to prevent unnecessary copying. This operation is by default a dangerous one, if you don't want to risk your plot being removed  then use copy instead.

**Comment by Sauilitired** [comment]
In v5 plot moving has been fixed, but the barrel content (or any other chest content) won't be transferred, so half of the issue remains.
