### ISSUE TITLE
An error comes up each time I try to create plots. Yes, I tried the alternative plot creation strategies.

### ISSUE THREAD

**Issue by RoblokazPlays** [IntellectualSites/PlotSquared#2605]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server type:
**select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**select one**

- [X] Minecraft 1.14.4 ***This is the ONLY actively maintained target for PlotSquared***
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
![image](https://user-images.githubusercontent.com/56515875/69591927-f0b54780-0fb9-11ea-933d-7dcb9c6d0e7e.png)

```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [x] WorldEdit 
![image](https://user-images.githubusercontent.com/56515875/69591964-0dea1600-0fba-11ea-89de-26404b598083.png)
: 

### Description of the problem:

When I was on the server, I was trying to use /plot setup. I got through 1 question, and then it comes up with an error. When I tried to execute it again, it just says: An error occurred: %s. how do I fix this?
## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Other plugins being used on the server:

![image](https://user-images.githubusercontent.com/56515875/69592133-9ec0f180-0fba-11ea-9e92-b261b956a2f0.png)

### Relevant console output, log lines, and/or screenshots:

![image](https://user-images.githubusercontent.com/56515875/69592166-be581a00-0fba-11ea-95bb-fac43b1e4de7.png)

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [x] I didn't read but checked everything above.

**Comment by N0tMyFaultOG** [comment]
Follow the template if you want support.
