### ISSUE TITLE
Plot info showing the wrong biome

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/PlotSquared#2607]
# NOTICE: 
```diff
! PlotSquared for Minecraft Java Edition versions between 1.7 through to 1.12.2 are considered
! legacy, and will receive limited to no support. Please consider upgrading to 1.13+ for
! future support.  Plugins exist for 1.13+ which bring back behaviors found in 1.8.8
! All versions of PlotSquared for Sponge and Nukkit(X) will recieve limited to no support
! due to lack of developer interest and time. Additionally, NukkitX has not had feature
! updates since the Better Together, which prevents some PlotSquared features from ever
! functioning.  Contributions are always welcome however!
```

**Feature requests & Suggestions are to be submitted at the [PlotSquared Suggestions tracker](https://github.com/IntellectualSites/PlotSquaredSuggestions)**

**Code contributions are to be done through [PRs](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request), tagging the specific issue ticket(s) if applicable.**

**[DISCORD INVITE LINK](https://discord.gg/cSMxtGn)** and please, for the love of the little sanity we have left, use the correct channels!

# BUG REPORT TEMPLATE:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (Debug/file paste links):
worlds.yml: https://pastebin.com/4QUjDJHn
settings.yml https://pastebin.com/JQu1Vraj
PlotSquared version: PlotSquared-4.411

### Server type:
**select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**select one**

- [X] Minecraft 1.14.4 ***This is the ONLY actively maintained target for PlotSquared***
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

``` git-Paper-226 (MC: 1.14.4) ```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [X] WorldEdit *version*: worldedit-bukkit-7.0.1

### Description of the problem:
I've actually had this issue for a while now but finally decided to make a ticket for it. For some reason the plot biome in /plot info doesn't give me the correct biome of the plot. I'm not really sure where it is getting these biomes from either. It will always give a random biome.

Example, it says this is warm ocean but it's not. Every plot in this world is using the forest biome.
![Untitled](https://user-images.githubusercontent.com/10485646/69666862-de541000-1084-11ea-96e4-2cf7683d75e7.png)

I also found this old ticket which mentions the problem I have: https://github.com/IntellectualSites/PlotSquared/issues/455 - there was uncertainty as to whether the issue had actually been fixed or not so I decided to create my own ticket.

### How to replicate:
Not entirely sure, every plot in my world shows the incorrect biome and I'm not even sure where it's getting that information from.

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by MattBDev** [comment]
I believe the issue lies somewhere with WorldEdit and Spigot. Not sure which.

**Comment by traksag** [comment]
The incorrect biome seems to be displayed when the plot centre—the place where the biome info comes from—is not in a loaded chunk.

**Comment by MattBDev** [comment]
@traksag thanks for that info. Looks like we need to update the command to mention that biome information won't always be available or force the chunk to load before fetching the information.

**Comment by Sauilitired** [comment]
This should be fixed now that we wait for the chunk to be loaded before sending the info message. If it still doesn't work, there's nothing we can do about it.
