### ISSUE TITLE
Plots stop generating

### ISSUE THREAD

**Issue by VorteXNation** [IntellectualSites/PlotSquared#2608]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server type:
**select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**select one**

- [X] Minecraft 1.14.4 ***This is the ONLY actively maintained target for PlotSquared***
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
This server is running Paper version git-Paper-230 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [X] WorldEdit *version*:  7.0.1

### Description of the problem:

Plots stop generating:

![image](https://user-images.githubusercontent.com/57765841/69674307-832e1780-109c-11ea-8fbc-ebd7345cfc70.png)

### How to replicate:

I'm not sure how it happened but I used fawe on my spawn (just for a few blocks) and it gave me a error, then PS started throwing lots of errors and stopped generating plots (/plot clear doesn't work).

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Other plugins being used on the server:

AdvancedLogin*, ArmorStandTools, CustomKnockback*, DivineDrop*, Elevator*, Essentials, IPWhitelist*, LiteBans, Multiverse-Core*, OldCombatMechanics, PermissionsEx*, PlaceholderAPI, PlotSquared, PlugMan*, PocketGames, ProtocolLib*, ProtocolSupport, Quests, SkinsRestorer, TAB, Vault*, VorteXCore, WorldEdit, WorldGuard, XChat*, XCosmetics, ZMarriage*, ZMenus

Part of them are my own plugins, but they do nothing with terrain.

### Additional relevant comments/remarks:

https://athion.net/ISPaster/paste/view/df98e1b3fe4740c79c05eb252b6f355f

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by AeSix** [comment]
Did this behavior continue after stopping and then starting your server again?

**Comment by VorteXNation** [comment]
Yes.

**Comment by MattBDev** [comment]
@VorteXNation You have two words in your worlds.yml file. Which one the one giving the error?

**Comment by VorteXNation** [comment]
Forget this, just realized it was an old world from 1.12, sorry ^^"
