### ISSUE TITLE
Another problems while using "/plot leave" command

### ISSUE THREAD

**Issue by MorkaZ** [IntellectualSites/PlotSquared#2610]
Continuing https://github.com/IntellectualSites/PlotSquared/issues/2595  
There is no error in console anymore but player is getting bad message.  
Instead of something like "You have left plot bla bla..", player is getting message of yaml key "errors.invalid_player" and he gets removed from plot.

**Comment by N0tMyFaultOG** [comment]
Do not delete the template.

**Comment by MorkaZ** [comment]
Well, everything is in previous issue so you expecting me to copy & paste everything?

**Comment by N0tMyFaultOG** [comment]
No? The previous issue does not specify anything regarding `"errors.invalid_player" and he gets removed from plot.` so adding a follow up with out anything that really "follows up", is not very helpful.
