### ISSUE TITLE
Problem with FAWE

### ISSUE THREAD

**Issue by Raphy123** [IntellectualSites/PlotSquared#2611]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server type:
**select one**

- [] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)* PAPER 226

### Minecraft Version:

- [] Minecraft 1.14.4 ***This is the ONLY actively maintained target for PlotSquared***

### Server build info: 

```
git-paper-226 (MC: 1.14.4)
```

### WorldEdit/FAWE versions:

- [] FAWE *version*: 1.14 

### Description of the problem:

Since the last update 1.14.4, administrators can use worldedit as usual. On the other hand, players have access to commands, but when they make one as the cut of their parcel, there is no physical change.
If I remove the restriction by region in the configuration, the worldedit works for them but it can destroy the roads and other parcels thanks to the expand

### How to replicate:

1) Permission permpack basic, with plotsquared2
2) Test //cut in a plot

### Other plugins being used on the server:

[20:04:33 INFO]: Plugins (44): Anonymous-Broadcaster*, AutoMessage*, BungeePorta|
ls*, ChestCommands, ClearLag, CrazyCrates, CustomParticleEffects*, EntityDetecti|
on*, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsS|
pawn, FastAsyncWorldEdit, FlySpeed*, HeadDatabase*, HideAndCustomPlugins*, Holog|
raphicDisplays, ItemFixer*, JSONAPI-RELOADED, LuckPerms, Microblocks*, Miniature|
Pets*, ModReq*, Multiverse-Core*, PermissionsEx*, PlotSquared, PluginList*, Plug|
inManagerReloaded*, ProCosmetics, ProtocolLib, RainStop*, RedstoneClockDetector*|
, SharpSK*, SK-NBeeT*, SkQuery, skRayFall*, Skript, VanishNoPacket*, Vault*, Vox|
elSniper, WorldBorder*, WorldEdit, WorldGuard    

### Relevant console output, log lines, and/or screenshots:

no error
### Additional relevant comments/remarks:

With the 1.13, all work.

**Comment by Raphy123** [comment]
With add permission fawe.bypass, this work, but the player can brush or expand outside the plot

**Comment by MattBDev** [comment]
You realize that you were supposed to put an x between the brackets? Deleting half the template doesn't help us.
So a few things I found wrong here. First, you are using PEX which we no longer support. We recommend LuckPerms. Second, you have a lot of plugin errors including with PlotSquared and your schematic file. Third, this is an issue for FAWE and not PlotSquared.
