### ISSUE TITLE
Redstone on server plot dosent work

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#2613]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (Debug/file paste links):

https://athion.net/ISPaster/paste/view/8f0a5f4f2aa2414b8f9d92319d2c1bb2

### Server type:
**select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**select one**

- [x] Minecraft 1.14.4 ***This is the ONLY actively maintained target for PlotSquared***
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
Paper version git-Paper-226 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [x] WorldEdit *version*: 7.0.1;61bc012

### Description of the problem:

If i enable "redstone.disable-unoccupied" and set the flag server-plot i cant use redstone.

### How to replicate:

Make a plot with server-plot flag enable redstone.disable-unoccupied and try to use redstone

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Other plugins being used on the server:

WorldEdit, MultiVerse, PlotSquared
### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by AeSix** [comment]
Does this include if the original owner of the plot attempts to use redstone, or just other players?
I'm thinking that it may not see other players as occupying the plot if they're not added.

**Comment by DevJoey** [comment]
Yea all players and the owner. I Think that the plugin think that the owner is not only.

**Comment by N0tMyFaultOG** [comment]
Server plots are just a flag. It does not updated the database entry, the plots belong to the original creator still.

**Comment by Sauilitired** [comment]
@DevJoey Do you mean `redstone.disable-offline`? This would indeed fail as the owner would not be online. 

`disable-unoccupied` only disables redstone if there are no players in the plot, and does not consider the plot owner.
