### ISSUE TITLE
Chorusfruit Steal BUG

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#2615]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (Debug/file paste links):

https://athion.net/ISPaster/paste/view/426f01896400476d979e953f3a6a8843

### Server type:
**select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**select one**

- [x] Minecraft 1.14.4 ***This is the ONLY actively maintained target for PlotSquared***
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
Paper version git-Paper-226 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [x] WorldEdit *version*: 7.0.1;61bc012

### Description of the problem:

Other players can shoot at my chorus plants using a bow and the chorus plant gets dropped. players can destroy chorusplants on my plot with a bow
### How to replicate:

Let player1 claim a plot and plant a chorusplant. player2 (NO ADMIN PERMISSIONS) shoot with a bow at the chorus plant from player 1

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Other plugins being used on the server:

WorldEdit, P2, Multiverse
### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by N0tMyFaultOG** [comment]
Can reproduce with Paper 234 and P2 417. Simply stand on the plot and the item will drop if you shoot them.

**Comment by DevJoey** [comment]
Yea on armorstands the same bug

**Comment by DevJoey** [comment]
It is still present in newest build. if i go on a plot i can shoot chorusplats. Can someone please fix it all my players plants gets griefed

**Comment by AeSix** [comment]
Perhaps you can set a worldguard flag to prevent them from being destroyed?

**Comment by DevJoey** [comment]
Yea but i dont find a flag that prevents that. Have you an idea?

**Comment by AeSix** [comment]
not off hand.  I'd research, but am... well, honestly, I've had a long weekend and am being lazy this evening.  But, I'm fairly certain there is something that can be set in the global region to prevent arrows from breaking things.  Maybe not.

**Comment by N0tMyFaultOG** [comment]
I don't think there is a way to prevent arrows from hitting chorus fruits, last time I checked there was no api for it.

**Comment by DevJoey** [comment]
Oh doch! There is an API for that. I have coded my own protection for that. It is so easy to fix if you know how to do it. But that is my secret :)

**Comment by N0tMyFaultOG** [comment]
You could provide it via a pull request rather than making something own locking out everyone who wants it fixed. That is generally not how you treat open source plugins.

**Comment by AeSix** [comment]
@DevJoey That's considerably hostile towards PlotSquare and the FOSS community as a whole.  Either keep it to yourself, or share the code.  We (I personally, and the developers) have done a lot to help you with issues.  

If you're going to just complain and not PR fixes which you've made, then I see no reason for us to continue to assist you.  

On the other hand, it would be immensely wonderful to have you contribute to the project, even small fixes.  You would have the gratitude of myself, the developers and many server operators.

**Comment by DevJoey** [comment]
Yea i can provide you the fix.

**Comment by AeSix** [comment]
Thank you! :)

**Comment by DevJoey** [comment]
Nothing to thanks. But i will enjoy if the devs add a golem interact flag :)
My npc plugin uses a "Vote" golem. And players cant rightclick them :)

I don’t think it’s bad when I ask if you can add a golem flag, right? Because I don't want to fork PlotSquared and show up there :)
I think it's a fair exchange, fix for golem flag :)

Fix -> https://hasteb.in/qiyugagu.cs 
Its a part of my anticheat called BetaboAC its prevents destroing of chorus fruits completely.
