### ISSUE TITLE
PlotSquared error on shutdown "java.lang.NoClassDefFoundError: com/sk89q/worldedit/math/BlockVector2"

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/PlotSquared#2622]
# NOTICE: 
```diff
! PlotSquared for Minecraft Java Edition versions between 1.7 through to 1.12.2 are considered
! legacy, and will receive limited to no support. Please consider upgrading to 1.13+ for
! future support.  Plugins exist for 1.13+ which bring back behaviors found in 1.8.8
! All versions of PlotSquared for Sponge and Nukkit(X) will recieve limited to no support
! due to lack of developer interest and time. Additionally, NukkitX has not had feature
! updates since the Better Together, which prevents some PlotSquared features from ever
! functioning.  Contributions are always welcome however!
```

**Feature requests & Suggestions are to be submitted at the [PlotSquared Suggestions tracker](https://github.com/IntellectualSites/PlotSquaredSuggestions)**

**Code contributions are to be done through [PRs](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request), tagging the specific issue ticket(s) if applicable.**

**[DISCORD INVITE LINK](https://discord.gg/cSMxtGn)** and please, for the love of the little sanity we have left, use the correct channels!

# BUG REPORT TEMPLATE:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (Debug/file paste links):
worlds.yml: https://pastebin.com/4QUjDJHn
settings.yml https://pastebin.com/JQu1Vraj
PlotSquared version: PlotSquared-4.411

### Server type:
**select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**select one**

- [X] Minecraft 1.14.4 ***This is the ONLY actively maintained target for PlotSquared***
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

``` git-Paper-226 (MC: 1.14.4) ```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [X] WorldEdit *version*: worldedit-bukkit-7.0.1

### Description of the problem:
Not sure why but when I shutdown my server I got this error: https://pastebin.com/LEN81RqS
I'm not sure how much of a problem this is but I wanted to report it anyway since it looks concerning.

### How to replicate:
Not sure.

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by MattBDev** [comment]
It's not a serious issue. WorldEdit should be unloaded after PlotSquared, not before it. It looks like the server attempted to generate chunk data during shutdown for some reason.

**Comment by dordsor21** [comment]
This to me seems more like a fringe case in Spigot's generation code from at the time. Since no-one else has reported I think this isn't an issue with P2//any current versions
