### ISSUE TITLE
NumberFormatException on /plot visit

### ISSUE THREAD

**Issue by emanondev** [IntellectualSites/PlotSquared#2626]
**Debug paste link:** 
not needed, might be fixed with [IntellectualSites/PlotSquared/pull/2625](https://github.com/IntellectualSites/PlotSquared/pull/2625)

**[REQUIRED] Spigot/Paper Version Number:** 
any
**[REQUIRED] Minecraft Version Number:** 
1.14.4
**[REQUIRED] Description of the problem:** 
NumberFormatException
**Any relevant console output or screenshots:**

> [19:58:02 WARN]: java.lang.NumberFormatException: For input string: "a"
> [19:58:02 WARN]: at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
> [19:58:02 WARN]: at java.lang.Integer.parseInt(Integer.java:580)
> [19:58:02 WARN]: at java.lang.Integer.parseInt(Integer.java:615)
> [19:58:02 WARN]: at com.github.intellectualsites.plotsquared.plot.commands.Visit.execute(Visit.java:46)
> [19:58:02 WARN]: at com.github.intellectualsites.plotsquared.commands.Command.execute(Command.java:323)
> [19:58:02 WARN]: at com.github.intellectualsites.plotsquared.plot.commands.MainCommand.execute(MainCommand.java:253)
> [19:58:02 WARN]: at com.github.intellectualsites.plotsquared.plot.commands.MainCommand.onCommand(MainCommand.java:133)
> [19:58:02 WARN]: at com.github.intellectualsites.plotsquared.bukkit.util.BukkitCommand.onCommand(BukkitCommand.java:25)
> [19:58:02 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
> [19:58:02 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
> [19:58:02 WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734)
> [19:58:02 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1783)
> [19:58:02 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1591)
> [19:58:02 WARN]: at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
> [19:58:02 WARN]: at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
> [19:58:02 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15)
> [19:58:02 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [19:58:02 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [19:58:02 WARN]: at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108)
> [19:58:02 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018)
> [19:58:02 WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
> [19:58:02 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
> [19:58:02 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837)
> [19:58:02 WARN]: at java.lang.Thread.run(Thread.java:748) 

**Plugins being used on the server:**
not relevant

**How to replicate:** 
issue /plot visit \<anyname\> \<any int number\> \<any not number value\>

**Checklist**:
- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
He never asked you to open a ticket. You could have just followed the template in the PR so this wasn't needed at all.
