### ISSUE TITLE
Enchants get removed from items on plot move

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#2627]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (Debug/file paste links):

https://athion.net/ISPaster/paste/view/e2a6e7d9b5b9416cb424a450ca5d9dd5

### Server type:
**select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**select one**

- [x] Minecraft 1.14.4 ***This is the ONLY actively maintained target for PlotSquared***
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
git-Paper-224 (MC: 1.14.4)
```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [x] WorldEdit *version*: 7.0.1;61bc012

### Description of the problem:

1. If i move a plot, enchantments from items in chests will be removed.
2. If i place a head and move the plot, the head gets default steve texture
### How to replicate:

1. Enchant some Items put in chest and move plot
2. Make a head of a player place on a plot and move the plot
## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Other plugins being used on the server:

WorldEdit, MultiVerse
### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by AeSix** [comment]
Is this happening on 1.15.1 as well?

**Comment by DevJoey** [comment]
I dont have an 1.15.1 server i have a citybuild network with 1.14 only.

**Comment by Sauilitired** [comment]
PlotSquared will only move simple items. FastAsyncWorldEdit may handle this better, but this is not something we are going to deal with in vanilla PlotSquared.
