### ISSUE TITLE
PlotSquared obsolete Nukkit 1.14

### ISSUE THREAD

**Issue by GBprojekte** [IntellectualSites/PlotSquared#2628]
PlotSquared geht nicht mehr ab Nukkit version 1.14

**Comment by AeSix** [comment]
PlotSquared wird nur für Bukkit-Lineage-Server für 1.14 entwickelt. Derzeit gibt es keine Nukkit-Plugin-Entwickler für PlotSquared, die Entwickler würden sich jedoch über eines freuen. Da wäre ein Großteil der Gemeinde.

Nukkit hat selbst keine richtigen Updates erhalten. Ein Großteil von PlotSquared hängt von Funktionen ab, die in Nukkit entweder nicht vorhanden oder fehlerhaft sind. Diese müssen behoben werden, bevor PlotSquared ordnungsgemäß funktioniert.

Wenn Sie wissen, wie Sie PlotSquared richtig auf Nukkit anwenden können, sind die Entwickler bereit, gut geschriebene PRs zu überprüfen und zu akzeptieren.


Nun zum Löschen der Issue-Vorlage. TU das nicht. Die Tatsache, dass ich mir sogar die Zeit und Mühe nehme, auf Sie zu antworten und Google Translate zu verwenden, um dies auf Deutsch zu tun, sollte Sie sehr glücklich machen.

Ticket schließen.

PlotSquared is being developed only for Bukkit-lineage servers for 1.14 only.  There are currently no Nukkit plugin developers for PlotSquared, however, the developers would be pleased to have one.  As would much of the community.

Nukkit has not had proper updates itself.  Much of PlotSquared depends on functions which either do not exist or are broken in Nukkit.  These must be addressed before PlotSquared will work properly.  

If you know a way to make PlotSquared work on Nukkit properly, the developers are willing to review and accept well written PRs. 


Now, about deleting the issue template.  Do not do that.  The fact I am even taking the time and effort to respond to you, and use Google Translate to do so in German, you should feel very lucky.

Closing the ticket.
