### ISSUE TITLE
Big Error on Water Place

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#2636]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):

https://athion.net/ISPaster/paste/view/f0891b38e00e419a81b8dfe730211b2c
### Server type:
**Select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [] Minecraft 1.15
- [x] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
This server is running Paper version git-Paper-226 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [x] WorldEdit *version*: 7.0.1;61bc012

### Description of the problem:

Error on place of water Bucket spams console

### How to replicate:

Place a couple water Bukkets on a plot inside other water

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Other plugins being used on the server:

MultiVerse, WorldEdit
### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by MattBDev** [comment]
This should already be fixed on the latest breaking builds.
