### ISSUE TITLE
Can't destroy blocks at position y=0

### ISSUE THREAD

**Issue by Grabsky** [IntellectualSites/PlotSquared#2637]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):
**/version PlotSquared**:
```
PlotSquared version 4.400
Easy, yet powerful Plot World generation and management.
Website: https://github.com/IntellectualSites/
Authors: Citymonstret, Empire92, MattBDev and dordsor21
```
**worlds.yml**: https://pastebin.com/uYCCAGWC
**settings.yml**: https://pastebin.com/HWf1d6Rz

### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [] Minecraft 1.15
- [] Minecraft 1.14.4
- [X] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
This server is running Paper version git-Paper-652 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Checking version, please wait...
You are running the latest version
```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [X] WorldEdit *7.0.1*: 

### Description of the problem:
Players without permission `plots.admin.destroy.groundlevel.*` can't break blocks at y=0 even though there is `worlds.<world>.plot.bedrock` set to `false`. 
I **CAN** place blocks at this level, but **CAN'T** break them.

### How to replicate:
1. Add new world to worlds.yml and change its plot settings to:
```
plot:
  height: 62
  biome: FOREST
  size: 101
  filling: AIR:100
  auto_merge: false
  bedrock: false
  create_signs: false
  floor: AIR:100
```
2. Place a block at the lowest possible level.
2. Deop yourself and break the placed block

## Additional Information:
none

### Other plugins being used on the server:
```
Plugins (44): AdvancedBan*, ArmorEquipEvent*, AuthMe, AWD*, Chatty*, Citizens, CrazyAuctions, CrazyCrates, DropPickup, FastLogin, Gatekeeper*, HolographicDisplays, Horizon, IllegalStack, JupiterCore, LuckPerms, McListpl*, Multiverse-Core, PlaceholderAPI, PlotSquared, ProtocolLib*, ProtocolSupport, QuantumShop, RPGHealthIndicator*, SDTMotd*, SimpleSit*, SkinsRestorer, SkQuery, Skript, skript-mirror*, skript-placeholders*, SQLibrary*, SuggestionManipulator*, SunLight-Core, SunLight-Core_Economy*, SuperVanish, TAB, Vault, ViaVersion*, WildStacker, WorldBorderAPI*, WorldEdit, WorldGuard, WorldGuardEvents
```

### Relevant console output, log lines, and/or screenshots:
none

### Additional relevant comments/remarks:
none

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by MattBDev** [comment]
Not a bug. This is intentional. There is a setting in one of the config files to set this behavior. It has the word bedrock in it. That's all I can remember.

**Comment by Grabsky** [comment]
@MattBDev I can't see anything except `worlds.<world>.plot.bedrock` which define if the bedrock at the bottom of plot is generated or not. I just went through all config files and didn't see any option which could change whether I can destroy the bedrock layer or not.
