### ISSUE TITLE
Bee nests and beehives can be harvested indefinitely

### ISSUE THREAD

**Issue by Resi23** [IntellectualSites/PlotSquared#2638]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):

https://athion.net/ISPaster/paste/view/7eb3bdcc079f42229ff2d683d78daac8

### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [X] Minecraft 1.15
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
Paper 1.15.1 Build 25
```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [X] WorldEdit *version*: Bukkit-Offical(7.1.0-Snapshot;4798)

### Description of the problem:

The bee nests and beehives can be harvested infinitely (during the day). The honey_level drops briefly to 0 but immediately rises again to 5. At night it seems to work normally. You harvest with a bottle or scissors once and the honey_level sinks and stays at 0 until the bees fill it up again.

Oki i think i have the problem. The bees in the nest or hive are not taken into account in the animal cap. If, for example, the animal cap is set to 20 and you bring new animals onto the plot while the 20 bees are in the nest or hive, the bees cannot leave the nest / hive when the cap is reached. But you can harvest endless honey and / or honey warts.
### How to replicate:

Place a bee nest or beehive on a plot and let bees fill it with honey. Then harvest it during the day

### Other plugins being used on the server:

only Worldedit
### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by Resi23** [comment]
it is really strange now it seems to be going understand one. I close it until I have more information

**Comment by Resi23** [comment]
Oki i think i have the problem. The bees in the nest or hive are not taken into account in the animal cap. If, for example, the animal cap is set to 20 and you bring new animals onto the plot while the 20 bees are in the nest or hive, the bees cannot leave the nest / hive when the cap is reached. But you can harvest endless honey and / or honey warts.

**Comment by MattBDev** [comment]
We will not be addressing this.
