### ISSUE TITLE
[1.15.1] NbtFactory, unable to find method createTag

### ISSUE THREAD

**Issue by voodootje0** [IntellectualSites/PlotSquared#2641]
https://haste.jartexnetwork.com/uzegevaqew.bash for the full exception.

PlotSquared version: 4.432 (most recent version as of today)
Using paper 1.15.1 build 27 (most recent version as of today)

**Comment by N0tMyFaultOG** [comment]
Duplicate of https://github.com/IntellectualSites/PlotSquared/issues/2629
