### ISSUE TITLE
Leaf decay on PlotWorld roads

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#2645]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):

I can not create a debug paste i have fresh installed the server and run /p debugpaste and it says Failed to create the debug paste: you need to wait 3 minutes before creating a new paste
I use the newest dev build
### Server type:
**Select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [] Minecraft 1.15
- [x] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
git-Paper-237 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [x] WorldEdit *version*: 7.0.1;61bc012

### Description of the problem:

Leaves despawning on Roads and i cant create a debugpaste

### How to replicate:

1. Use latest dev build and build leaves on the road
2. Install a fresh p2 Version restart the server and run /p debugpaste

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Other plugins being used on the server:

WorldEditd, MultiVerse

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by MattBDev** [comment]
Are these leaves ones that are hand placed, created from trees, or placed with worldedit?

**Comment by DevJoey** [comment]
My Buildteam build a plotroad on a 1.12 server and saving the roads as worldedit schematic. than i copy the worldedit schematic from the 1.12 build server to the 1.14 development server. and i pasted the worldedit schematic and all leaves despawn.

**Comment by DevJoey** [comment]
Im not sure if this is a bug or not. It can be an blockdata issue with 1.12 to 1.14. hand placed blocks are not despawning. i think that is not a bug from plotsquared. i think its a worldedit issue.

**Comment by AeSix** [comment]
If the debugpaste is still an issue, that should be a separate ticket. There is a timer built into the paste site to prevent excessive use/abuse.

**Comment by AeSix** [comment]
So, I'm going to suggest that you need to either --forceUpgrade the 1.12 build server, then create a new schemtic containing the leaves - or paste the schematic in a new 1.12.2 server, and upgrade that. 
It would probably be best to have a modern build server, for compatibility and item accessibility reasons. 

There were changes to schematic formats, and at this point, there shouldn't need to be any legacy version conversions written in plugins for this.  

One of the devs may choose to override me on this, but I honestly feel this is such a low priority issue that it's a non-issue.  Closing ticket. 

p.s.
I just tested debugpaste with build 439, it works.  My previous statement is more than likely what happened.
