### ISSUE TITLE
Error on Generating world

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#2646]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):

https://athion.net/ISPaster/paste/view/91767df5dcc84452804b5c8c523835e2
### Server type:
**Select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [] Minecraft 1.15
- [x] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
git-Paper-237 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE *version*: 7.0.1;61bc012
- [x] WorldEdit *version*: 

### Description of the problem:

I got an error on creating a world. The world was correctly created but a error is shown in console and errors are not so good on a productive server.

### How to replicate:

Create a plotworld with /p setup on a fresh installed server with the plugins MultiVerse, WorldEdit, P2

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Other plugins being used on the server:

MultiVerse, WorldEdit
### Relevant console output, log lines, and/or screenshots:

https://pastebin.com/L21rXX9Y

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by AeSix** [comment]
fiarly certain that's actually from multiverse, but I'm not 100% positive.

**Comment by N0tMyFaultOG** [comment]
Can you pastebin the stacktrace please?

**Comment by DevJoey** [comment]
Yea it was already in the report but market out. here the link https://pastebin.com/L21rXX9Y

**Comment by N0tMyFaultOG** [comment]
That's your server lagging out, so it created a thread dump. You can try allocating more ram or increase the delay of the watchdog. This is not a P2 issue.
