### ISSUE TITLE
Biomes and wall materials not correct

### ISSUE THREAD

**Issue by Bobcat00** [IntellectualSites/PlotSquared#2647]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):

settings.yml - https://pastebin.com/y73PZQmx
worlds.yml - https://pastebin.com/PBiaCXuG

### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [X] Minecraft 1.15
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
20:40:25 [INFO] This server is running CraftBukkit version git-Spigot-492a779-731e819 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
20:40:25 [INFO] Checking version, please wait...
20:40:25 [INFO] You are running the latest version
```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [X] WorldEdit *version*: 7.1.0-SNAPSHOT;4787-aeb8935

### Description of the problem:

When generating new plots, PlotSquared is not respecting the biome nor the wall material specified in worlds.yml:
1. I specify a PLAINS biome, but new plots are generated with the FOREST biome.
2. /p claim sets the biome to PLAINS, but /p delete sets the biome to FOREST (which is wrong).
3. It appears that wall.block_claimed is being used for the walls for newly-generated plots, instead of wall.block

Note that /plot claim and /plot delete correctly set the wall material.  Also note that I generated a custom road schematic and that also appears to be working.

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Other plugins being used on the server:

Plugins (36): LuckPerms, WorldEdit, WhoWas, AutoBot, AltDetector, GriefPreventionBlockedCommands, FarmLimiter, MinecartCollisions, ProtocolLib, WorldGuard, ImageMaps, Vault, xInventories, Prism, ProtocolSupport, Orebfuscator4, SignURLs, Essentials, ViaVersionStatus, Matrix, PwnFilter, PlotSquared, TabListPing, SilkSpawners, Multiverse-Core, SilkSpawnersShopAddon, MemCheck, EssentialsChat, EssentialsGeoIP, Multiverse-Portals, EssentialsSpawn, GriefPrevention, WorldGuardExtraFlags, MobArena, MobArenaStatus, Multiverse-NetherPortals
### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by Bobcat00** [comment]
Here is the startup log info with debug: true
https://pastebin.com/S12mB4cw

**Comment by AeSix** [comment]
I believe the biome setting requires minecraft: pre-pended to the biome name.  Please test this.
This should resolve the issue with the world being generated with the wrong biome, and prevent the plots from reverting to forest biome on /p delete.

AFAIK the wall code hasn't been touched, and so the issue indicated as such does not make sense.  Perhaps it is a byproduct of the incorrect biome setting.   This should be in a separate ticket however, as it is unrelated to biomes.

**Comment by Bobcat00** [comment]
I had to use `biome: minecraft:plains` in all lower case for it to work.  The default world.yml simply has FOREST in upper case, so you should probably correct the format.

The wall top blocks are still wrong on newly-generated chunks.  I can make a new issue, but can you point me to the code?  I can't find it.

**Comment by AeSix** [comment]
The biome name changes is an issue the developers area already aware of, and presumably working on. 

https://github.com/IntellectualSites/PlotSquared/issues/2599

Presumably, there will be a new build with these fixes, and hopefully they'll actually work. 

Closing ticket.

**Comment by Bobcat00** [comment]
Mystery solved!  When creating the built-in road schematic, it needs to be done with the _unclaimed_ wall tops.  I had done `/plot createroadschematic` in a claimed plot.  The Wiki should be updated to reflect this.  Also, the Wiki should explain the required parameter for `/plot debugroadregen` as that apparently has changed since the Wiki was written

**Comment by Sauilitired** [comment]
> I had to use biome: minecraft:plains in all lower case for it to work. The default world.yml simply has FOREST in upper case, so you should probably correct the format.

Yeah, the format changed when we switched to WorldEdit biomes
