### ISSUE TITLE
Revert teleportation behavior to pre-4.400

### ISSUE THREAD

**Issue by zombachu** [IntellectualSites/PlotSquared#2651]
# Bug Report Template:

### Server type:

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*

### Minecraft Version:
- [X] Minecraft 1.15

### Server build info: 

```
This server is running Paper version git-Paper-31 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
```

### PlotSquared Version:
PlotSquared-4.436

### Description of the problem:

Since [these](https://github.com/IntellectualSites/PlotSquared/commit/20dd98d3b9686fcd29586219f77397f588a3710e#diff-43d7174f7dd247049a836b624807d29dR194) [commits](https://github.com/IntellectualSites/PlotSquared/commit/68a5166d2f2ad342436f4683afac04dc18f70888#diff-43d7174f7dd247049a836b624807d29dR192), some teleports performed by PS have had their TeleportCause changed. This has created some unexpected behavior in plugins listening to the teleport event and expecting the old COMMAND cause.

# AFFIRMATION OF COMPLETION:

- [] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
I'm very against reverting these code changes. I will look into this but I can't promise anything.

**Comment by zombachu** [comment]
See my latest commit and comment in #2652
