### ISSUE TITLE
Plot comment does not work

### ISSUE THREAD

**Issue by Azriael2** [IntellectualSites/PlotSquared#2654]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):

https://athion.net/ISPaster/paste/view/512851f36ca7452e90baaf622a7d5e30

### Server type:
**Select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [] Minecraft 1.15
- [x] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
This server is running Paper version git-Paper-209 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [x] WorldEdit *7.0.1-rc1-dist*: 

### Description of the problem:

Command /plot comment does not work, always responds with "Use /plot comment [X;Z] <owner|public|report> <comment>". Tried with [] and without, with : and with ; - nothing works.
## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by AeSix** [comment]
I confirm this is an issue with build 439.

**Comment by MattBDev** [comment]
I hate plot comment.
Just thought I would share my opinion even though it doesn't matter.

**Comment by AeSix** [comment]
To be honest, I never use them except to test for ticket issues.

**Comment by Azriael2** [comment]
Any idea when we can expect a fix? :)
