### ISSUE TITLE
Setting Border VIA Api cause error in console

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#2658]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):

https://athion.net/ISPaster/paste/view/489737d9c83b4087ab62c20d2f59cc09

### Server type:
**Select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [] Minecraft 1.15
- [x] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
This server is running Paper version git-Paper-226 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [x] WorldEdit *version*: 7.0.1;61bc012

### Description of the problem:

If i set the Border via API to beacon and change it to a other material i getting my console spammed with errors
### How to replicate:

Write a plugin that replaces the border and change to beacon and than back zu a other material
## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Other plugins being used on the server:

ProxySockeSystem, WorldGuard, WorldEdit
### Relevant console output, log lines, and/or screenshots:

https://hasteb.in/ragudeza.css

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by MattBDev** [comment]
If you are using the API we need to see the code you used so we can actually fix this issue. Also, the version of the plugin you are using is a dev version and very out of date.

**Comment by DevJoey** [comment]
Yea iam afraid of to update my p2 version because i have fear that a newer p2 version broke my plotworld.

Here my Code:
https://hasteb.in/apedudew.java

**Comment by N0tMyFaultOG** [comment]
Hastebin has expired and not renewed by the submitter, assume problem solved.
