### ISSUE TITLE
Loading/Pasting with asymmetrical Plots is resulting in ArrayOutOfBounds

### ISSUE THREAD

**Issue by Peda1996** [IntellectualSites/PlotSquared#2659]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):

https://athion.net/ISPaster/paste/view/251be4a6311e44688308a8c300a8e399

### Server type:
**Select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [] Minecraft 1.15
- [x] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
Paper version git-Paper-230 (MC: 1.14.4)
```

### WorldEdit/FAWE versions:

- [x] FAWE: 1.15 - v28
- [] WorldEdit *version*: 

### Description of the problem:

Loading and pasting asymmetrical the same merged plots results in errors.. (Fawe is used in this case, as in this issue: https://github.com/IntellectualSites/PlotSquared/issues/2569 it is stated that fawe is already working)

### How to replicate:

1. Claim 3 plots asymmetrical (not in line)
2. Merge these plots
3. type: /p schematic save
4. afterwards paste the saved schematic with /p schematic paste <name>

Now the Exception should appear in the terminal, and the plot is then bound to a timer.

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Relevant console output, log lines, and/or screenshots:
I tried this out at the newest dev and the currently working build. On both builds the error occured.

```
[PlotSquared] Plugin PlotSquared v4.440 generated an exception while executing task 6166
java.lang.ArrayIndexOutOfBoundsException: -1
	at com.sk89q.worldedit.extent.clipboard.io.FastSchematicReader.getBlockState(FastSchematicReader.java:190) ~[?:?]
	at com.sk89q.worldedit.extent.clipboard.io.FastSchematicReader.read(FastSchematicReader.java:223) ~[?:?]
	at com.sk89q.worldedit.extent.clipboard.io.ClipboardReader.read(ClipboardReader.java:58) ~[?:?]
	at com.sk89q.worldedit.extent.clipboard.io.ClipboardReader.read(ClipboardReader.java:45) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.util.SchematicHandler.getSchematic(SchematicHandler.java:333) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.util.SchematicHandler.getSchematic(SchematicHandler.java:294) ~[?:?]
	at com.github.intellectualsites.plotsquared.plot.commands.SchematicCmd.lambda$onCommand$0(SchematicCmd.java:87) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-230]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-230]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-230]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by N0tMyFaultOG** [comment]
Can you retest it with regular WorldEdit please?

**Comment by Peda1996** [comment]
Yea no problem. 

I also added the error log in the 1st post. (i somehow placed the log inside the comments..)

**Comment by AeSix** [comment]
failure to read, understand and follow instructions is probably one of your issues.  You gave us a debug paste, but stated you did not know where to put it.  Reading from the top of the template, it was the first thing you would have read which instructed you to do a thing.  

Please confirm you are following the instructions properly to resolve your issue. Are you pasting the schematic into 3 claimed/merged plots in the same orientation? This might not be something that FAWE/P2 is capable of doing at all if not without very specific circumstances being replicated.

**Comment by Peda1996** [comment]
Sorry, it was not my intention not to follow the template.

And yes the error occurs only for plots that are merged in a non-rectangular way. In my case I used three plots with are ordered as followed:
x x
x empty

I also retested the thing with Worldedit:
There the console doesn't output any errors, but instead, the player receives the message, that the paste failed.

**Comment by AeSix** [comment]
@Peda1996 first, I re-read what I had said to you, and it was overly harsh.  I apologize for that. 

And yeah, I seem to remember a conversation with @boy0001 about plot schems not being too intellegient, and requiring square plots - but that would had been from 2-3 years ago.  

Maybe some different perspectives from the new devs will be able to figure out a way to make it happen in a future release.  Until then, you should be able to use worldedit/fawe to make the selection with ```//sel poly``` - ensuring you note your position and orientation, and ensure the new plots line up with the old plots in orientation, then pasting the shematic.  You can play with your cipboard rotation if the new plots aren't in the same orientation with each other.  (example: x = claimed, o = open:
Original:
xx
xo

mis-oriented new plot:
xo
xx

You'd have to rotate the plot in order for the schematic shape to line up with the new plots. 

It's a manual process, but until NMF or some other dev figures out a way to make non-rectangular plot schems work on paste, that's the only answer.  

Though, thinking on this as I was writing, had you tried ```//paste -a``` when attempting?

**Comment by Peda1996** [comment]
Is pasting with -a, not only pasting the schematic without air? Why should this prevent the error (haven't tried it btw)?

Actually, I am currently programming a minigames framework, based on the PlotSquared API. Therefore I am/was only using the build-in schematic feature, for saving and restoring plots. (Before the game starts -> plot is saved. After the game was finished -> plot is pasted.)

**Comment by AeSix** [comment]
I see.  I have a theory that the schematic, being square, is reading access information for the 4th plot.  As there is nothing in that area within the schematic, other than air, then pasting without air may not require the access to be granted for the fourth plot, thus not denying the paste. 

It's a long shot, and I have no idea if it's accurate or not, or if you can do that with the API.

**Comment by Peda1996** [comment]
I think one of the easiest ways of solving this problem would be to split the merged plot into multiple cuboid schematics. To be more precise, compose the plot of multiple cuboids. For instance, we have the plot:
x x
x o

Then the upper part is saved in an extra schematic, wheres the lower x is saved in an additional schematic.

**Comment by AeSix** [comment]
The only problem with that is determining boundries.  Though, it's possible, the easiest way would preclude copying the blocks previously marked as road.  Extending a buffer around the plot could cause additional issues, such as "it overwrote my new road! FIX IT! Hrmmmph!" and overlapping schematics (not as big an issue, just not efficient)  Obviously, there is a way to do it, but it would be less than ideal.  

Being you're writing your own thing, you could probably use P2 for the space assignments, then get the plot location, and feed that into FAWE, and have FAWE paste the schematic.  That would allow you to over-write anything there, without the access checks for the plot.  I honestly feel, in the interim, until a developer figures out how to solve the reported issue, that this is the best method for you to continue forward with your work. 

I hope this helps.

**Comment by Sauilitired** [comment]
This could be re-opened as a suggestion in the suggestions repo. However, we are not currently going to support pasting schematics into merged plots.
