### ISSUE TITLE
Plot merge permissions not working as it should

### ISSUE THREAD

**Issue by Sikatsu** [IntellectualSites/PlotSquared#2662]
### Server config info (/plot debugpaste / file paste links):
https://athion.net/ISPaster/paste/view/f242381cd7144689a48b40f3f691a181

### Server type:
**Select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [x] Minecraft 1.15
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
This server is running Paper version git-Paper-45 (MC: 1.15.1)
```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [x] WorldEdit *7.1.0*: 

### Description of the problem:

I gave my users the permission pack ''plots.permpack.basic'' however they are not able to merge plots. As soon as I gave them the permission ''plots.merge.*'' it works fine however.

That means there is probably something within the ''plots.merge.*'' permission that is not properly listed elsewhere, or there is an issue in the plugin.

### How to replicate:

Actually explained in the upper section.

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by N0tMyFaultOG** [comment]
The permission works fine. You declare the maximum amount of plots a user can merge via `plots.merge.<amount>`. Not assigning leads to users not being able to merge plots.

**Comment by Sikatsu** [comment]
But the default is plots.merge.4 within the permission pack, yet they can't merge at all.

**Comment by AeSix** [comment]
@Sikatsu try this https://github.com/LuckPerms/extension-legacy-api  - and let us know if it resolves your issue, or not. 

@N0tMyFaultOG - he's using LP 5... there's been major API changes.  Has P2 been udpated to use the new API?  If not, that's a serious issues which will need to be addressed sooner rather than later.

**Comment by Sikatsu** [comment]
Hey, I can test that, but my issue was also there with LuckPerms 4.. so I doubt that's the issue.

**Comment by AeSix** [comment]
Ahh, I see.  Thank you for the update.  But yeah, test it anyways, just for completeness.

**Comment by N0tMyFaultOG** [comment]
> @N0tMyFaultOG - he's using LP 5... there's been major API changes. Has P2 been udpated to use the new API? If not, that's a serious issues which will need to be addressed sooner rather than later.
> 
> > <img alt="" width="48" src="https://avatars2.githubusercontent.com/u/22246894?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/4908d9947135e4536ef61d61512ee575f869bf6f/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e2e69636f"> GitHub**[LuckPerms/extension-legacy-api](https://github.com/LuckPerms/extension-legacy-api)**An extension for LuckPerms v5, which implements the legacy v4 API. - LuckPerms/extension-legacy-api

That doesn't affect it. PlotSquared supports the bukkit permission API and is not limited to a permission plugin. So as long as LP or any other plugin follows the permission API, PlotSquared will work fine with it. The issue sounds more like a configuration/inheritance issue on the user's end.
