### ISSUE TITLE
Cannot disable updater

### ISSUE THREAD

**Issue by TheKinrar** [IntellectualSites/PlotSquared#2663]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):
https://athion.net/ISPaster/paste/view/4f75a7c9ed79469b9e5ec28637d06b85

### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [ ] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [ ] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [X] Minecraft 1.15
- [ ] Minecraft 1.14.4
- [ ] Minecraft 1.13.2
- [ ] Minecraft Java Edition *other versions, please specify*:
- [ ] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
Papyrus version git-Papyrus-16 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [ ] FAWE *version*:
- [X] WorldEdit *version*: 7.1.0-beta-1;7039dc8

### Description of the problem:

Setting `enabled-components.updater` to `false` in config.yml does not disable updater, or, at least, does not prevent the "You appear to be running the latest version" message from appearing.

### How to replicate:

Set `enabled-components.updater` to `false` and start server.

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Other plugins being used on the server:
```
Plugins (18): CoreProtect., DiscordLink, Essentials., InventoryApi.*, Matrix., Multiverse-Core., Multiverse-Inventories., OpenInv., PermissionsEx.*, PlotSquared., PremiumVanish., ProtocolLib., ProtocolSupport., ProtocolSupportStuff., Temparia, VoidGenerator., WorldEdit., WorldGuard.
```

### Relevant console output, log lines, and/or screenshots:
```
[08:36:36 INFO]: [PlotSquared] -------- PlotSquared Update Check --------
[08:36:36 INFO]: [PlotSquared] You appear to be running the latest version of PlotSquared. Congratulations!
[08:36:36 INFO]: [PlotSquared] -------- PlotSquared Update Check --------
```

### Additional relevant comments/remarks:
Version info and paste are from my server running *Papyrus* which is my modified version of Paper, based on latest upstream version. Anyway, I've tested on the latest "pure" Paper build (git-Paper-50 at the time of writing) and behaviour was the same.

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [ ] I didn't read but checked everything above.

**Comment by AeSix** [comment]
This is by design. 

If you'd like to write a patch to replace "You appear to be~~" to "You have disabled update checking. Be warned" and PR it, tagging this ticket, they devs may choose to merge it.  

Other than that, the answer is it's 3 lines on start up.  You've disabled update checking, and so should know it may not be the latest.

**Comment by Sauilitired** [comment]
There is a separate properties file where the update checker can be toggled on or off. Check your PlotSquared folder.
