### ISSUE TITLE
Missing flag for Golems and utility mobs

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#2665]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):

https://athion.net/ISPaster/paste/view/48db45751e7e4b01b19b5a877d4bc53a
### Server type:
**Select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [] Minecraft 1.15
- [x] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
version git-Paper-238 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [x] WorldEdit *version*: 7.0.1;61bc012

### Description of the problem:

I set the flag hostile-interact but Players cant interact with golems!
### How to replicate:

Place a Golem set the hostile-interact flag and right click on the mob. you will get a no perms message!
## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Other plugins being used on the server:

Cityzenz
### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by AeSix** [comment]
https://minecraft.gamepedia.com/Mob#Hostile_mobs

Golems (Iron and Snow) are considered utility mobs, not hostile mobs. 
As golems are not naturally aggressive towards players, this would be accurate. 

Perhaps there is another flag to set for these mobs?

**Comment by DevJoey** [comment]
Yea but i dont know the flag name! Under the wiki there is no flag for other mob types!

**Comment by AeSix** [comment]
Understood.  I'm in the middle of a bunch of other things already and can't go look it up, but you might be able to find it if you're comfortable searching the code base.  If there isn't one, then the ticket needs to be more of a missing-flag bug

**Comment by DevJoey** [comment]
But i not able to search in 500 classes of code for one flag. people using plotsquared thier not knowing anything about java code :(

**Comment by DevJoey** [comment]
I have searched in the code but they are no flags for that 

https://hasteb.in/udizigeh.js

**Comment by N0tMyFaultOG** [comment]
You cannot interact with golems at all, viewing them from the vanilla minecraft side. The only purpose I can see for a flag like that would allow third party plugins doing certain actions. But therefore, I don't see much of a need that PlotSquared provides billions of flags just that people can "interact" with mobs they are not meant to interact with.
The better option would be certain third party plugins adding P2 compatibility and registering custom flags, e.g. PlotSquared provides flags for mobs like Villagers, where you can actually interact with them, doing trades and so, but everything else shouldn't need to be covered by PlotSquared.
