### ISSUE TITLE
Schematic based World Generation is not working correctly 

### ISSUE THREAD

**Issue by x-gaming** [IntellectualSites/PlotSquared#2671]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):

I atteached the files because the first thing doesnt worked:
[latest.log](https://github.com/IntellectualSites/PlotSquared/files/4109359/latest.log)
[2020-01-23-9.log.gz](https://github.com/IntellectualSites/PlotSquared/files/4109363/2020-01-23-9.log.gz)
[2020-01-23-10.log.gz](https://github.com/IntellectualSites/PlotSquared/files/4109364/2020-01-23-10.log.gz)
[yml.zip](https://github.com/IntellectualSites/PlotSquared/files/4109371/yml.zip)

### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [] Minecraft 1.15
- [X] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
This server is running CraftBukkit version git-Spigot-cbd1a1b-009d8af (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[16:31:29] [Server thread/INFO]: This is a final build for 1.14.4. Please see https://www.spigotmc.org/go/1.14.4 for details about upgrading.
```

### WorldEdit/FAWE versions:

- [X] FAWE *FastAsyncWorldEdit-1.15-45*:
- [] WorldEdit *version*: 

### Description of the problem:

If I want to use the schematic based world gen. with the plot.schem in the right folder for creating a new world, an Error occurs. After the Server has been loaded completely, the world is genarated and I can also enter it, but then there are always half or broken plots. 

### How to replicate:

I have done everything like it is described in the wiki, but than this Error occurs. The marked space for the plot schematic is about 200 Blocks in booth x and y direction. Maybe its too big? I also checked the worlds.yml but the Plot size is set to 200.

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.
Sometimes the schematic isn´t placed completely if I use FAWE, mostly if I dont use //paste -a. Than I have to paste it again, before it works. 

### Other plugins being used on the server:

Plugins (19): NightVision, LuckPerms, WorldEdit, Spawntp, FastAsyncWorldEdit, SuperTrails, VoxelSniper, ClearLag, Vault, F3NPerm, Citizens, Essentials, ChatEx, CommandPanels, PlotSquared, Multiverse-Core, Multiverse-Inventories, Multiverse-SignPortals, ItemJoin

### Relevant console output, log lines, and/or screenshots:

https://pastebin.com/Q5NqC5Ey
### Additional relevant comments/remarks:

At the moment the Server is running on localhost

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by AeSix** [comment]
Have you tried using WorldEdit in lieu of FAWE?

**Comment by x-gaming** [comment]
Yeah I have tried it with the latest version of world edit and it still throws the same Error
