### ISSUE TITLE
Furnace,Beacon,Spawners stopping work

### ISSUE THREAD

**Issue by alexpdmg** [IntellectualSites/PlotSquared#2672]
PaperSpigot 1.8.8
- WorldEdit: 6.1

Debug paste: https://www.athion.net/ISPaster/paste/view/4cd03094936c4e3ea49f496deb250b34

The problem:
https://www.youtube.com/watch?v=9D7inwYYXiw&feature=youtu.be

I am using the latest legacy version, this problem occurs many versions ago until today. Besides that sometimes the spawners, beacons, etc. stop working, I don't know if it is due to this bug like the video but this also happens.

**Comment by N0tMyFaultOG** [comment]
a) Do not delete the template.
b) 1.8 is no longer supported.
c) You are using a hack client.
d) There is no d).
