### ISSUE TITLE
All Plot Information Lost After Server Restart (Plot Area, owned plots, existence of plots, etc.)

### ISSUE THREAD

**Issue by BeckettOBrien** [IntellectualSites/PlotSquared#2677]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):

https://athion.net/ISPaster/paste/view/5b03bd7d06c548549ccd220b3d487189

### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [X] Minecraft 1.15
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
[18:21:24 INFO]: This server is running Paper version git-Paper-86 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

[18:21:24 INFO]: Checking version, please wait...

[18:21:25 INFO]: Previous version: git-Paper-84 (MC: 1.15.2)

[18:21:25 INFO]: You are running the latest version
```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [X] WorldEdit *version*: 7.0.1

### Description of the problem:

Whenever I restart the server for mantinence, the plot world still has all the structures and plots in it, but PlotSquared does not recognize them or the plot area. I can fix it using `/mv regen creative` but it clears all structures. I don't want to have to fix this issue every time I need to restart the server and I can't find any info about this problem.
### How to replicate:

Create a new PlotSquared world using the config command and set it up with multiverse and LobbyAPI. Build something and use the plots, then restart the server. `/p claim` will now say you are not in a plot.
## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Other plugins being used on the server:

EssentialsX
LobbyAPI
Multiverse-Core
WorldEdit
WorldGuard
CoreProtect
GroupManager
### Relevant console output, log lines, and/or screenshots:
`[P2] You're not in a plot`

### Additional relevant comments/remarks:

We use multiverse as our main world manager, but lobbyapi for user navigation.
# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by TheMisterWolf** [comment]
having the exact same issue

**Comment by N0tMyFaultOG** [comment]
Make sure you registered your world in the bukkit.yml correctly:
```yaml
worlds:
  <name of the plotworld>:
    generator: PlotSquared
```

**Comment by TheMisterWolf** [comment]
I dont have "worlds:" in my bukkit.yml, im using multiverse for my worlds


> Make sure you registered your world in the bukkit.yml correctly:
> 
> ```yaml
> worlds:
>   <name of the plotworld>:
>     generator: PlotSquared
> ```

**Comment by N0tMyFaultOG** [comment]
> I dont have "worlds:" in my bukkit.yml, im using multiverse for my worlds
> 
> > Make sure you registered your world in the bukkit.yml correctly:
> > ```yaml
> > worlds:
> >   <name of the plotworld>:
> >     generator: PlotSquared
> > ```

Then you need to add it. Multiverse is optional.

**Comment by TheMisterWolf** [comment]
So like this?

`# This is the main configuration file for Bukkit.
# As you can see, there's actually not that much to configure without any plugins.
# For a reference for any variable inside this file, check out the Bukkit Wiki at
# https://www.spigotmc.org/go/bukkit-yml
# 
# If you need help on this file, feel free to join us on irc or leave a message
# on the forums asking for advice.
# 
# IRC: #spigot @ irc.spi.gt
#    (If this means nothing to you, just go to https://www.spigotmc.org/go/irc )
# Forums: https://www.spigotmc.org/
# Bug tracker: https://www.spigotmc.org/go/bugs


settings:
  allow-end: true
  warn-on-overload: true
  permissions-file: permissions.yml
  update-folder: update
  plugin-profiling: false
  connection-throttle: 4000
  query-plugins: true
  deprecated-verbose: default
  shutdown-message: Server closed
  minimum-api: none
spawn-limits:
  monsters: 70
  animals: 10
  water-animals: 15
  ambient: 15
chunk-gc:
  period-in-ticks: 600
ticks-per:
  animal-spawns: 400
  monster-spawns: 1
  autosave: 6000
aliases: now-in-commands.yml
worlds:
  creativity:
    generator: PlotSquared`

**Comment by N0tMyFaultOG** [comment]
No? I just told you how to do it. You can literally copy it over and exchange the placeholder with the name of your plotworld.

**Comment by BeckettOBrien** [comment]
Thank you for the response but I tried copying exactly what you put (I did put the proper world name) but I still get the same problem. I don't see why adding a generator to the bukkit/spigot/paper.yml would fix this when it is being loaded and managed by multiverse.

**Comment by N0tMyFaultOG** [comment]
> Thank you for the response but I tried copying exactly what you put (I did put the proper world name) but I still get the same problem. I don't see why adding a generator to the bukkit/spigot/paper.yml would fix this when it is being loaded and managed by multiverse.

Because mv can screw up easily. Yet I never mentioned to add it to any other files but bukkit.yml. Adding it there will inevitably work, unless you have alarming deep issues on your server, far out the range of ps.

**Comment by BeckettOBrien** [comment]
Thank you so much! It works properly now. Is there any way in a future version you can add the generator to the bukkit.yml when running the `/p setup` command? Or at least make the wiki more clear on this subject as It only tells you to do this if:
> You used /plot setup, and you DO NOT have Multiverse or MultiWorld installed

But I do have multiverse installed and I still needed to do this Thank you!
