### ISSUE TITLE
/plot claim not working

### ISSUE THREAD

**Issue by PatBoi** [IntellectualSites/PlotSquared#2678]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):

https://athion.net/ISPaster/paste/view/9d7a7537fc9443b0a6e01495bad6a3bf

### Server type:
**Select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [x] Minecraft 1.15
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
This server is running Paper version git-Paper-87 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE *version*:
- [x] WorldEdit *7.1.0;8e55131*: 

### Description of the problem:

I generated the world using the /plot setup command, after I was done I tried command /plot claim while I was standing on the plot and the plugin just told me:  _You're not in a plot_ even /plot auto does not work.
### How to replicate:

Upload PlotSquared to plugins folder, restart the server. Then run /plot setup commands, mine height was set to 62 for all of them and plot sizes were 100. Road size was default 7 too. After the setup stand on one of the plots and try claiming.. does not work.
## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Other plugins being used on the server:

Plugins (18): Citizens, Essentials, EssentialsChat, EssentialsSpawn, Holograms*, LuckPerms, PlotSquared, PremiumVanish, ProtocolLib, SimplePortals, Skellett, SkQuery, skRayFall*, Skript, ViaBackwards, ViaVersion, WorldEdit, WorldGuard
### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by MattBDev** [comment]
Did any message show up when you used plot auto?

**Comment by PatBoi** [comment]
> Did any message show up when you used plot auto?

![/plot auto](https://i.imgur.com/a29LcOf.png)

**Comment by N0tMyFaultOG** [comment]
Since you aren't using Multiverse, you need to register your plot world manually.
You can do so by adding the following to your bukkit.yml
```yml
worlds:
  <name of the plotworld>:
    generator: PlotSquared
```
