### ISSUE TITLE
Command "/p home" "/p sethome" do not work properly

### ISSUE THREAD

**Issue by nicostrebel** [IntellectualSites/PlotSquared#2680]
# Bug report template 

**Debug paste link:** 

**[REQUIRED] Spigot/Paper Version Number: git-Paper-86 (MC: 1.15.2)** 

**[REQUIRED] Minecraft Version Number: 1.15.2** 

**[REQUIRED] Description of the problem: When i buy Plot A my "/p home" teleports me as expected to Plot A. When i then buy Plot B an i use "/p home" it teleports me as expected to Plot A. When i now stand on Plot B and type "/p sethome" it then says in the chat "Home position set to your current location" as expected. But when i then type "/p home" it  then unexpected teleports me to Plot A instead to Plot B** 

**Any relevant console output or screenshots: No console outputs made by this plugin**

**Plugins being used on the server: https://athion.net/ISPaster/paste/view/91d6d880205d4f5caf3c1fd877e3f902**

**How to replicate: Yes it is possible to recreate**
Use the newest Plotsquared.jar from Spigot or build the newest Plotsquared.jar from github. (Both are having this issue)

- Create a new 1.15.2 PaperMC Server
- Put worldedit, worldguard and plotsquared in Plugin Folder
- Start up Server to create all files and then stop it
- Delete the new generated world
- Edit bukkit.yml to add  PlotSquared Worldgenerator to our world 'plotsquaredcb1'
- Edit server.properties and name our new world "plotsquaredcb1"
- Set PlotSquared/config/settings.yml as in pastebin linked below
- Set PlotSquared/config/commands.yml as in pastebin linked below
- Set PlotSquared/config/worlds.yml as in pastebin linked below
- Use MySQL as storage with Flag useSSL=false
- Start Server which now generates our new World "plotsquaredcb1"
- Claim Plot A
- Claim Plot B
- Use "/p home" -> Get teleportet to Plot A
- Go inside of Plot B and use "/p sethome"
- Walk to road
- Use "/p home" and you get teleportet to Plot A instead of Plot B

Pastebins:
settings.yml: https://pastebin.com/irp9JZVZ
commands.yml: https://pastebin.com/xsT6yN8r
worlds.yml: https://pastebin.com/G7XTDsS3

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by N0tMyFaultOG** [comment]
`sethome` sets the location of the home spot per plot, e.g in that case /p h 2. Sethome doesn't change the order of p h.

**Comment by MattBDev** [comment]
Oh okay. I misunderstood earlier. Sorry!

**Comment by zori4004** [comment]
Okay but is there any way to change the Plot order?

**Comment by MattBDev** [comment]
There is no way to change plot order. That would require a new entry in the database which we don't have. It is possible with an add on but it would have to be written in Java.
