### ISSUE TITLE
Global disable creative flag

### ISSUE THREAD

**Issue by dayofpay** [IntellectualSites/PlotSquared#2687]
How to disable creative flag from the server ?

**Comment by owenselles** [comment]
gamemode in server.properties or in the worlds.yml under 'world'

**Comment by RedstoneFuture** [comment]
You can remove the flag permission of the game-mode flag of PlotSquared. And If you would like define your gamemode in a specifically world, you can use plugins like multiverse.

**Comment by RedstoneFuture** [comment]
And in the world.yml of PlotSquared you can define the gamemode too:
`world.yml -> world.<worldname>.world.gamemode: <game-mode>`
