### ISSUE TITLE
Chestshop flags not working

### ISSUE THREAD

**Issue by Woeben** [IntellectualSites/PlotSquared#2690]
### Server config info (/plot debugpaste / file paste links):
https://athion.net/ISPaster/paste/view/6308d82485df43acb8662978abce9b44 

Worlds.yml: https://pastebin.com/wTGuzeSk

### Server type:
**Select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [x] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
This server is running Paper version git-Paper-62 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [x] WorldEdit version: Bukkit-Official(7.1.0-rc-1;05cc7aa)

### Description of the problem:
The global use flags for plots don't work when I try to give people access to use chestshops. No errors.

### How to replicate:
Install the latest version of Chestshop, link it and add these flags: use: ACACIA_SIGN, ACACIA_WALL_SIGN, BIRCH_SIGN, BIRCH_WALL_SIGN, DARK_OAK_SIGN, DARK_OAK_WALL_SIGN, JUNGLE_SIGN, JUNGLE_WALL_SIGN, LEGACY_SIGN, LEGACY_SIGN_POST, OAK_SIGN, OAK_WALL_SIGN, SPRUCE_SIGN, SPRUCE_WALL_SIGN. All in worlds.yml

### Other plugins being used on the server:
Chestshop

### Relevant console output, log lines, and/or screenshots:
```
Players get the message that they are not allowed to edit the plot
```

**Comment by N0tMyFaultOG** [comment]
With the release of PlotSquared v5 you are able to use `#sign` as use parameter to cover all signs. I just gave it a quick test and it works fine.
