### ISSUE TITLE
PlayerClaimPlotEvent is not being cancelled

### ISSUE THREAD

**Issue by Grabsky** [IntellectualSites/PlotSquared#2691]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):

```
[23:02:38] [Server thread/INFO]: PlotSquared version 4.453
[23:02:38] [Server thread/INFO]: Easy, yet powerful Plot World generation and management.
[23:02:38] [Server thread/INFO]: Website: https://github.com/IntellectualSites/
[23:02:38] [Server thread/INFO]: Authors: Citymonstret, Empire92, MattBDev and dordsor21
```
Found more info irrevelant, however I will attach link if needed.

### Server type:
**Select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [ ] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [ ] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [ ] Minecraft 1.15.2
- [ ] Minecraft 1.14.4
- [x] Minecraft 1.13.2
- [ ] Minecraft Java Edition *other versions, please specify*:
- [ ] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
[22:50:16] [Server thread/INFO]: This server is running Paper version git-Paper-655 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[22:50:16] [Server thread/INFO]: You are running the latest version
```

### WorldEdit/FAWE versions:

- [ ] FAWE version:
- [x] WorldEdit version: 7.1.0;8e55131

### Description of the problem:

PlayerClaimPlotEvent is not being cancelled. Example code:
```java
@EventHandler
public void onIslandClaim(PlayerClaimPlotEvent event) {
    PlotPlayer player = BukkitUtil.getPlayer(event.getPlayer());
    if(player.getPlots().size() >= 1) {
        event.setCancelled(true);
        player.sendMessage("You can't have more than one plot.");
    }
}
```

### How to replicate:

1. Add code above to a listener class.
2. Claim one plot.
3. Try to claim second plot.

As you can see (or at least I do), second plot is being claimed even though the condition is met and message is sent to player.
![image](https://user-images.githubusercontent.com/44530932/74781835-9539e380-52a2-11ea-9504-5937648a5a83.png)

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.
none

### Other plugins being used on the server:

```
Chatty*, ChestShop, ChestShopConfirmation, FastAsyncWorldEdit, FogusCore, LuckPerms, Multiverse-Core, OreoCore, PlaceholderAPI, PlotSquared, ProtocolLib, ProtocolSupport, SDLib, SkyIslands, SQLiteLib*, SunLight, SunLight_Economy*, Vault, ViaVersion*, WorldBorderAPI*, WorldEdit, WorldGuard
```

### Relevant console output, log lines, and/or screenshots:

No console errors.

### Additional relevant comments/remarks:

None, it's all explained above.

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [ ] I didn't read but checked everything above.

**Comment by dordsor21** [comment]
This will be fixed in v5 ( See #2706 )
