### ISSUE TITLE
//regen broken in plots

### ISSUE THREAD

**Issue by Sauilitired** [IntellectualSites/PlotSquared#2692]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [] Minecraft 1.15.2
- [X] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
This server is running Paper version git-Paper-243 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [X] WorldEdit version: 
```
[17:29:59 INFO]: WorldEdit version (unknown)
[17:29:59 INFO]: https://github.com/EngineHub/WorldEdit/
[17:29:59 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(7.1.0;8e55131)

[17:29:59 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official
```

### Description of the problem:

`//regen` just creates an empty plot with a bedrock layer.

### How to replicate:

Use `//regen`

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Relevant console output, log lines, and/or screenshots:

https://pastie.io/hrfidx.md

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by braceyourself07** [comment]
Can confirm in 1.15.2 as well.  

P2 v4.472 / WorldEdit 7.1.1

https://brdv.coffee/storage/uploads/4/oRLGGnxF5aUn.txt

**Comment by Sauilitired** [comment]
Fixed in v5.
