### ISSUE TITLE
Destroy plots without any permission

### ISSUE THREAD

**Issue by NorwegianStudio** [IntellectualSites/PlotSquared#2695]
Hello! 

I had a small problem with the PlotSquared plugin.
Every time I destroy a block in an unclaimed plot, I get this message: plots.admin.destroy.unowned.
And that's normal. But I can destroy, even if I don't have perms.

It can be a problem with my server, or it can be a problem with the plugin. 
And I also got this message in console:
> [17:58:08] [Server-Worker-194/WARN]: at com.github.intellectualsites.plotsquared.plot.generator.HybridGen.generateChunk(HybridGen.java:40)
> [17:58:08] [Server-Worker-194/WARN]: at com.github.intellectualsites.plotsquared.bukkit.generator.BukkitPlotGenerator.generate(BukkitPlotGenerator.java:173)
> [17:58:08] [Server-Worker-194/WARN]: at com.github.intellectualsites.plotsquared.bukkit.generator.BukkitPlotGenerator.generateChunkData(BukkitPlotGenerator.java:151)
> [17:58:08] [Server-Worker-194/WARN]: at org.bukkit.craftbukkit.v1_15_R1.generator.CustomChunkGenerator.buildBase(CustomChunkGenerator.java:137)

Mvh NorwegianStudio

**Comment by MattBDev** [comment]
You didn't fill out the template (you deleted it) and provided only part of an error message. We can't help you without the information asked for in the template. Please fill out a new report or reply to this one with the required information and we can look into your issue.
