### ISSUE TITLE
plot home error

### ISSUE THREAD

**Issue by AlexandruSAN2** [IntellectualSites/PlotSquared#2703]
https://www.athion.net/ISPaster/paste/view/3313f5e44efc4c6bb16548b5fa712925

Paper 1.12.2
Minecraft 1.12,2

![image](https://user-images.githubusercontent.com/57284528/75605004-459bb900-5ae7-11ea-848d-6c46f1fc9f56.png)

![image](https://user-images.githubusercontent.com/57284528/75605031-9c08f780-5ae7-11ea-8060-7621616fade5.png)

Type /p home or /p h

**Comment by Sauilitired** [comment]
Is it only for this specific plot? The default plot home in your config is `side`, but this plot seems to have a custom home location set. If it's only for that plot, use `/plot set home` in another location to see if it fixes it. If it happens in other plots as well, it's most likely a bug.

**Comment by AlexandruSAN2** [comment]
I try to set home in another plot location with /plot sethome, but don't work, don't work in any plot

**Comment by RedstoneFuture** [comment]
Do you have more problems with PlotSquared? I don't know how I can replicate this.

**Comment by N0tMyFaultOG** [comment]
Please retest the issue on v5.

**Comment by RedstoneFuture** [comment]
If you have still this problem, reopen it on https://issues.intellectualsites.com/issues?q=project:%20PlotSquared ,please.
