### ISSUE TITLE
Permissions Bug

### ISSUE THREAD

**Issue by 83y** [IntellectualSites/PlotSquared#2704]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server type:
**Select one**

- [git-Spigot-c574e08-37f32da] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [X] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
Paste the output here, between the tick marks, replacing this text
```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [7.1.0] WorldEdit version: 

### Description of the problem: I am struggling to give all the players plots access to open / use everything, I started of by trying to read this and fix the problem https://github.com/IntellectualSites/PlotSquared/wiki/Plot-flags
but it did not work. Here is the screenshot of what it says
https://ibb.co/9pXqqVP
So i tried to give the player the all the necessary permissions to add the flag themselves and sudo them to do add it. However when i gave them all these permissions it still wouldnt work. These are the permissions i gave:

plots.flag
plots.set.flag.other
plots.set.flag.use.oak_door (I used oak door as an example)

so I gave my alt all the permissions needed
https://ibb.co/F6MmJnf

and when i tried to add it by sudoing the player this is what it said:
https://ibb.co/mT57ZYj

It said i needed the permission even though i gave my alt it!

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [x] I didn't read but checked everything above.

**Comment by N0tMyFaultOG** [comment]
If you want people to interact with everything, set the use flag to 0 as global flag in your worlds.yml. 
Flags must be applied to the plot to work, not to the user as permission node
