### ISSUE TITLE
/p auto [number] results in error

### ISSUE THREAD

**Issue by kemmeo** [IntellectualSites/PlotSquared#2707]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server type:
**Select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [x] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
[11:16:54 INFO]: This server is running Purpur version git-Purpur-462 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[11:16:54 INFO]: Checking version, please wait...
[11:16:55 INFO]: Previous version: git-Purpur-461 (MC: 1.15.2)
[11:16:55 INFO]: You are running the latest version
```

### WorldEdit/FAWE versions:

- [x] FAWE version: Build #113
- [] WorldEdit version: 

### Description of the problem:

Running the command `/p auto 4` as a player with and without OP, results in an error and does not automatically claim 4 plots. The number specified is arbitrary, any number I've tried results in the same error message.

### How to replicate:

Replicate by running `/P auto 4` as a player with or without OP.

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Other plugins being used on the server:

`Plugins (20): CraftingStore, Essentials, EssentialsChat, EssentialsSpawn, FarmLimiter, FastAsyncWorldEdit, HorseTpWithMe, IllegalStack, Matrix, PermissionsEx*, PlotSquared, ProtocolLib, Regionerator, SuggestionManipulator*, SuperbVote, TitleManager, Vault, Votifier, Wild, WorldEdit`

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [x] I didn't read but checked everything above.

**Comment by MattBDev** [comment]
I am pretty sure that entering a number after plot auto isn't supposed to claim a certain number of plots.

**Comment by kemmeo** [comment]
Really? That was my impression, but I am totally open to the possibility that I might be very wrong.

But what are they for then?

**Comment by kemmeo** [comment]
`/plot auto [length,width]`

Taken from the wiki it seems like you're meant to be able to specify a length and width as arguments after running the `/p auto` command. However, trying to run for example `/p auto 2 2` gives me the same error as posted above.

**Comment by SirYwell** [comment]
Try `/plot auto 2,2` instead. If that does not work, you‘ll need to supply a debugpaste as you should have already done initially.

**Comment by kemmeo** [comment]
Thank you so much @SirYwell that fixed my issue.
