### ISSUE TITLE
Bug with the use flag

### ISSUE THREAD

**Issue by AggerTV** [IntellectualSites/PlotSquared#2710]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):

https://www.athion.net/ISPaster/paste/view/d6e5c16de4dd4667becfae64acc7444f

latest.log https://pastebin.com/cnX8EPK9
settings.yml https://pastebin.com/qgqf5Hdf
worlds.yml https://pastebin.com/8UiM39ek

### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:
- [X] Paper Version 1.12.2 https://gyazo.com/5844612d28fde2feb7b7eacec0a6adf6

### Server build info: 

```
12.03 17:54:08 [Server] INFO This server is running Paper version git-Paper-1617 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
12.03 17:54:08 [Server] INFO You are 1 version(s) behind
```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [X] WorldEdit version: 6.1.9;caf0ad9 https://gyazo.com/fd87154039f426993b217206d268ed80

### Description of the problem:

I set the flag
    flags:
      use: "sign"
So players could use shops created with the plugin https://www.spigotmc.org/resources/shop-a-simple-intuitive-shop-plugin.9628/
But when trying to use a shop (click the shop), it just says https://gyazo.com/b6b87d3bdb1a83e70d8262b1fa64c74f
even though the flag (to use signs) is applied to all plots
https://gyazo.com/c2b0a273b7b8d15640a7ac8df82ee5b6

### How to replicate:

https://youtu.be/o4RK1nWh2MU

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.
I don't know if it is usefull, but here's an paste of my dialogue with my server host
https://pastebin.com/i3BaknAh

### Other plugins being used on the server:

`12.03 18:02:30 [Server] INFO Plugins (56): AntiExplode, AuctionHouse, AutoLamp, AutoSell, BanItem, Banknotes, BukkitHiddenSyntaxBlocker, BuycraftX, Citizens, CleanroomGenerator, ClearLag, CommandCooldowns, DecoHeads, DIYspy, EpicRename, Essentials, EssentialsChat, EssentialsSpawn, HideMyPlugins, HolographicDisplays, LevelTools, LiteBans, MineBomb, Multiverse-Core, NightVisionReloaded, NoCheatPlus, NoPluginViewer, OldCombatMechanics, OreToBlock, PermissionsEx, PlaceholderAPI, PlayerReport, PlayerVaults, PlotMines, PlotSquared, PrisonMines, ProtocolLib, ProtocolSupport, Shop, ShopGUIPlus, skDragon, Skellett, SkQuery, skRayFall, Skript, Skungee, skUnity, skUtilities, SuperTrails, TAB, Vault, VoxelSniper, WarpPortals, WorldEdit, WorldGuard, WorldGuardFlyStop`

### Additional relevant comments/remarks:

I am using a miecraft server hosting site, https://apexminecrafthosting.com/

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above (I think I included all necessary information, but if not just say so, and I will correct it)
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared (I downloaded the latest file, I think, for 1.12.2 PlotSquared version 20.01.24-62a9a22-794 )
- [X] I made sure the bug/error is not caused by any other plugin (the shop plugin works fine, in the non plotsquared world)
- [x] I didn't read but checked everything above.

**Comment by SirYwell** [comment]
1.12.2 isn't supported anymore, but you could try to add `standing_sign` and `wall_sign` instead.

**Comment by AggerTV** [comment]
I know you closed this, but is there an way to just give full "use" acces?

**Comment by SirYwell** [comment]
I don't know what you mean

**Comment by AggerTV** [comment]
I mean, is there any way to just give full interaction access to the plots?

**Comment by Sauilitired** [comment]
Yes. Allow them to use ID 0 (air).

**Comment by AggerTV** [comment]
> Yes. Allow them to use ID 0 (air).

Okay, but I'm really confused as to how the flags works in the config, would it be something like this?
`flags: {use 0}`

**Comment by AggerTV** [comment]
??

**Comment by Sauilitired** [comment]
Look at the wiki.

**Comment by AggerTV** [comment]
Either I'm blind, or it doesn't say in the wiki, but how would I in the worlds.yml give full interaction access to all plots?

I would really, really, really appreciate if you would help me out on this one :)

**Comment by Sauilitired** [comment]
https://github.com/IntellectualSites/PlotSquared/wiki/Plot-flags#default-flags
You're on a severly outdated version, so the information won't be tailored for your specific setup. However, as mentioned in the wiki:
```yml
worlds:
  <world>:
    flags:
      use: '0'
```
in `worlds.yml` should do the trick.

**Comment by AggerTV** [comment]
Is it possible, to hire you for making plotsquared completely compatable with 1.12.2 ?

**Comment by Sauilitired** [comment]
It already is compatible with 1.12.2. We have moved on, however, and future work won’t target 1.12.

**Comment by AggerTV** [comment]
It's just, I set the flag so players can use signs, but it just doesn't work.
https://gyazo.com/4fff243e2be36afca00fdd4df7c69da5

The only way I found so that players can use signs, is if '0' is set, but then players can see other players chest ect.

**Comment by AggerTV** [comment]
nevermind, I found out you could do
use: '323,68,63'
where "68" and "63" is standing/wall sign

**Comment by ithr0n** [comment]
I can confirm that this is still a bug.
Following commands does not work:

`/p flag set use #signs`
[P2] Flag konnte nicht gesetzt werden.

`/p flag set use sign`
[P2] Flag konnte nicht gesetzt werden.
`/p flag set use minecraft:sign`
[P2] Flag konnte nicht gesetzt werden.
`/p flag set use 323`
[P2] Flag konnte nicht gesetzt werden.
`/p flag set use 63`
[P2] Flag konnte nicht gesetzt werden.
`/p flag set use 68`
[P2] Flag konnte nicht gesetzt werden.
`/p flag set use 323,68`
[P2] Flag konnte nicht gesetzt werden.

But these commands are different and it looks to work in the first second:

`/p flag set use 323,63`
[P2] Flag erfolgreich hinzugefügt.
`/p flag set use 323,63,68`
[P2] Flag erfolgreich hinzugefügt.
`/p flag set use 323,63`
[P2] Flag erfolgreich hinzugefügt.

However, my wall signs are not working and in all of the above (three successful) cases this is the result:

`/p info -f`
Flags: use:[minecraft:oak_sign]

**Comment by RedstoneFuture** [comment]
Short-Tags e.g. #signs was added in the internal v.5:
https://github.com/IntellectualSites/PlotSquaredSuggestions/issues/65

**Comment by ithr0n** [comment]
Thanks, solved my issue and enabled all signs with this command:
`/p flag set use oak_sign,spruce_sign,birch_sign,jungle_sign,acacia_sign,dark_oak_sign,crimson_sign,warped_sign,oak_wall_sign,spruce_wall_sign,birch_wall_sign,birch_wall_sign,jungle_wall_sign,acacia_wall_sign,dark_oak_wall_sign,crimson_wall_sign,warped_wall_sign`

Reference: https://minecraft.gamepedia.com/Sign#ID
