### ISSUE TITLE
Can't delete/modify a plot shaped like an L on expiration

### ISSUE THREAD

**Issue by JasonHorkles** [IntellectualSites/PlotSquared#2712]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [X] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
>.... [16:29:44 INFO]: This server is running Paper version git-Paper-122 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
>.... [16:29:44 INFO]: Checking version, please wait...
>.... [16:29:44 INFO]: Previous version: git-Paper-112 (MC: 1.15.2)
>.... [16:29:44 INFO]: You are 13 version(s) behind
```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [X] WorldEdit version: WorldEdit version 7.1.0-SNAPSHOT;4822-a27ade5

### Description of the problem:

I can't delete [the plot shaped like an L](https://cdn.discordapp.com/attachments/344128265075556353/683705908747960320/unknown.png) when it expires because it just teleports me to the center of where 4 plots would be (as shown in the picture). I have to manually disable the world in the expiration checks so I can either delete it or set it to stay for longer.

### How to replicate:

Make a plot that looks like an L
Let the plot expire
Make sure everything's set so it teleports you to manually delete it / save it for later

### Other plugins being used on the server:

AdvancedWarn, AsyncWorldEdit, AsyncWorldEdit-BountifulAPI*, AuctionHouse, BountifulAPI, BungeeTabListPlus, BuycraftX, Citizens, ClearLag, CommandDoesNotExist, CommandHook, CoreProtect, CraftBook, CrazyCrates, EditableSign, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, GameModeInventories, GriefPrevention, GSit, Harbor, HolographicDisplays, KeepDeathDrop, LibsDisguises, LimitPillagers, LuckPerms, Matrix, mcMMO, Multiverse-Core, Multiverse-NetherPortals, PlayerParticles, PlotSquared, PremiumVanish, ProtocolLib, SkQuery, Skript, Skungee*, skUtilities*, TimeIsMoney*, UltimateTimber, Vault, VeinMiner, Votifier, VotingPlugin, Wild, WildStacker, WorldEdit, WorldEditSUI, WorldGuard, WorldGuardExtraFlags

### Relevant console output, log lines, and/or screenshots:

https://cdn.discordapp.com/attachments/344128265075556353/683705908747960320/unknown.png

### Additional relevant comments/remarks:

PlotSquared version 4.453

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by N0tMyFaultOG** [comment]
Please retest the issue on v5.

**Comment by RedstoneFuture** [comment]
If you have still this problem, reopen it on https://issues.intellectualsites.com/issues?q=project:%20PlotSquared ,please.
