### ISSUE TITLE
Player or Op cannot claimed deleted plot

### ISSUE THREAD

**Issue by waiching514** [IntellectualSites/PlotSquared#2713]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [X] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
![image](https://user-images.githubusercontent.com/29138111/76703945-8fec7f00-6710-11ea-9f6c-560c27d71a45.png)

```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [X] WorldEdit version: 

### Description of the problem:

My problems not player cannot claim unclaim plot
When player claimed plot do nothing, and delete it
no anyone can claim that plot and show message "plot no claimed"

but when player claimed and builded something to delete plot
the problems gone

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Other plugins being used on the server:

![image](https://user-images.githubusercontent.com/29138111/76703959-a98dc680-6710-11ea-87f7-fadfd9bf78ea.png)

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [x] I didn't read but checked everything above.

**Comment by RedstoneFuture** [comment]
`Server config info (/plot debugpaste / file paste links):` ?

**Comment by RedstoneFuture** [comment]
The 1.15 PS version isn't stable at this time.

**Comment by Sauilitired** [comment]
Issues like these are almost always because of database problems, i.e. setup dependent. Please join the Discord if you need further assistance.
