### ISSUE TITLE
Error with road schematics (Generator maybe)

### ISSUE THREAD

**Issue by PocketMiner82** [IntellectualSites/PlotSquared#2717]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server type:
**Select one**

- [ ] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [ ] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [X] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [ ] Minecraft 1.15.2
- [ ] Minecraft 1.14.4
- [ ] Minecraft 1.13.2
- [ ] Minecraft Java Edition *other versions, please specify*:
- [X] Minecraft Bedrock Edition *1.14*:

### Server build info: 

```
Dieser Server läuft unter der Version Nukkit git-e4c0f7f 「」und nutzt die Version 1.0.9 der API für Minecraft:BE v1.14.0 (Protokoll Version 389)
```

### WorldEdit/FAWE versions:

- [X] FAWE version: FAWE 19.3.29-d13b946-1257
- [ ] WorldEdit version: 

### Description of the problem:

When editing the road-schematic, the generator isn't working correctly. This only happens on new created chunks: 
![2020-03-21_18h09_41](https://user-images.githubusercontent.com/44708000/77232239-1afdc700-6ba0-11ea-86c5-43f040d7e748.png)

### How to replicate:

Create a road-schematic using /p create roadschematic and then regen all roads using in the console /p regenallroads. Wait for finish it, restart the server, join it, fly to load new chunks, restart the server again and then this happens, if new chunks are generated.

### Other plugins being used on the server:

Plugins (31): LoveDiguise v1, FastAsyncWorldEdit v19.03.29-d13b946-1257-22.0.14, EssentialsNK v2.0, ScoreboardPlugin v1.0, SimpleScoreboards v3.1, MaxEnchants v1.1-SNAPSHOT, PlotSquaredPlusListener v1.0.0, DisableMovementCheck v1.0.0, KotlinLib v1.1, PlaceholderAPI v1.3.1, SimpleAnnouncer v0.5, NPC v2.2.4, EconomySystem v1.2, CloudNet-Bridge v1.0, PocketVote v2.0.1-bDEV, Plan v5.0 build 415, ZChat v1.0.16-Beta, MobPlugin v1.11.1.2, CustomHeads v1.0, PmChair v2.0.1, DbLib v0.2.4, MultiWorld v1.0, FDevTools v{pom.version}, Holograms v3.1.3, P2Fix v1.0.0, LuckPerms v4.4.19, PlugMan v1.0, AutoLagClear v1, PlotSquared v19.09.07-f27e556-781, AdvancedCraftCore v0.3, Residence v1.2

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)] (https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [ ] I didn't read but checked everything above.

**Comment by RedstoneFuture** [comment]
Would like you try the latest stabile version of PlotSquared?
https://www.spigotmc.org/resources/plotsquared.1177/updates

**Comment by PocketMiner82** [comment]
I try it, the generator task is running right now.

**Comment by PocketMiner82** [comment]
@RedstoneFuture it stucks at the second .mcr since half an hour... The last time I executed this, it worked. I think it crashed

**Comment by PocketMiner82** [comment]
@RedstoneFuture It is not working. It hasn't done anything since I've written the last comment. I stopped the task. I hadn't had this behaviour before.

**Comment by PocketMiner82** [comment]
Works now, i'll close this.
