### ISSUE TITLE
Fly Flag: Toggle issue

### ISSUE THREAD

**Issue by xWavePlayzx** [IntellectualSites/PlotSquared#2718]
**Description of the problem:**
If I set the fly flag to false and then remove it, I can't fly until I leave the server or switch my gamemode twice. Probably the gamemode with the fly flag don't get checked after the flag remove.

**How to replicate:**

1.

`/p flag set fly false`

2.

`/p flag remove fly`

**Tested with:**

> Paper-1.15.2
> PlotSquared-Bukkit-4.489.jar

**Checklist:**
 

- [x] I made sure there are no duplicates of this report (Use Search)

 

- [x] I made sure I am using an up-to-date version of PlotSquared

 

- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by RedstoneFuture** [comment]
Still with 1.13.2.

**Comment by RedstoneFuture** [comment]
With v.5 currently the flag was removed.

**Comment by Sauilitired** [comment]
@RedstoneFuture Good catch, it's not gone, it's just renamed to "flight". I'll change it back to fly. T

he issue is that having no flight flag is equivalent to having the flight flag set to false. I'll look into a way to fix this.

**Comment by Sauilitired** [comment]
In v5 the fly flag will not be disabled by default, but will just inherit the gamemode flight values. Setting the flag to false will disable flight for everyone, including creative players, and setting it to true will enable flight for survival and adventure mode players.
