### ISSUE TITLE
missed argument check for gamemode and guest-gamemode flag

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquared#2720]
### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [X] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
This server is running CraftBukkit version git-Spigot-518206a-a5b9c7b (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [] WorldEdit version: 

### Description of the problem:

PS hasn't a argument check for the correctly gamemode-type and so he didn't send warnings if the gamemode invalid. In my case than he set the gamemode "survival".

### How to replicate:

Use commands like `/p flag set gamemode ccc` -> you get the message "Successfully added flag", but he added the "survival" gamemode at me (`/p info`).

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Relevant console output, log lines, and/or screenshots:

![2020-03-22_11 45 41](https://user-images.githubusercontent.com/4140635/77247657-6c0acb00-6c33-11ea-9e4e-72685b357f2d.png)

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by Sauilitired** [comment]
Fixed in v5. It will now disable the gamemode flag (set it to default) if an invalid value is supplied.

**Comment by RedstoneFuture** [comment]
Good! :) Or you send a message like "wrong gamemode".
