### ISSUE TITLE
feed and heal flag down't work

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquared#2721]
### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [X] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
This server is running CraftBukkit version git-Spigot-518206a-a5b9c7b (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [] WorldEdit version: 
- [X] PlotSquared version: **5.515**

### Description of the problem:

If you use the feed or heal flag the plot-info get - I think - invalid infos and the vanilla-regeneration didn't overridden too. Did minecraft changes the feed and heal function with 1.14?

### How to replicate:

Use e.g. `/p flag set feed 3` and `/p flag set heal 2`. If I fall and jump I don't regenerate any value in my defined size.

![2020-03-22_13 40 59](https://user-images.githubusercontent.com/4140635/77251507-fd3b6b00-6c4e-11ea-87bf-ecdf9399178d.png)

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by MattBDev** [comment]
😮

**Comment by RedstoneFuture** [comment]
Yes, it works in version 5.537!

Only the plot-info have a strange value: I defined feed:5 and heal:5, yes - but the "1" I don't understand.

![2020-04-08_20 06 17](https://user-images.githubusercontent.com/4140635/78818580-2b51d680-79d5-11ea-9286-03742b065123.png)

**Comment by AeSix** [comment]
It's "feed 5 every 1 tick/second/minute"  (not sure which)

**Comment by RedstoneFuture** [comment]
Seconds.

**Comment by RedstoneFuture** [comment]
Ok, but I think only `feed:5` / `heal:5` is needed. The flag-value define the amount of seconds every time. Or we write `feed:5 / 1 sec.` But it's not possible.

**Comment by SirYwell** [comment]
You should also be able to use `/p flag set feed 3 3` or similar, but the first argument is the interval and the second one the amount currently. 1 is simply the default value used when no second argument is provided
