### ISSUE TITLE
Chunk generating errors

### ISSUE THREAD

**Issue by thecenters** [IntellectualSites/PlotSquared#2722]
### Server config info (/plot debugpaste / file paste links):
https://athion.net/ISPaster/paste/view/6ca6d87a914b4d00a8429d41c86afa7b

### Server type:
**Select one**
Paper

### Minecraft Version:
- [] Minecraft 1.15.2

### Server build info: 

 This server is running Paper version git-Paper-137 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

### WorldEdit/FAWE versions:

- [] WorldEdit version:  7.1.0;8e55131

### Description of the problem:
Massive empty areas with world generation

### How to replicate:
I'm not sure

### Relevant console output, log lines, and/or screenshots:
https://i.imgur.com/GxictsO.png

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:
- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by thecenters** [comment]
I want to add that I can go in a blank space that is a plot, do /plot claim and then /plot delete and it will re-gen the plot. but not the road

**Comment by MattBDev** [comment]
Please remove AsyncWorldEdit and try again with regular WorldEdit. Errors when using a fork/alternative for WorldEdit typically cause bugs in PlotSquared.

**Comment by thecenters** [comment]
It's an add-on to WorldEdit that runs the same commands in Async. It looks like the chunk error happened in a giant circle around the plots. Is there nothing that can fix this?

**Comment by MattBDev** [comment]
I know what AsyncWorldEdit is. It frequently interferes with PlotSquared and your entire log was filled with messages regarding that plugin having an error. The first step for me to help you is for you to remove AsyncWorldEdit and try PlotSquared again. If there are no bugs then we know that AsyncWorldEdit caused the problem.

**Comment by thecenters** [comment]
The problem is I've generated this world and it's used on an active server. I didn't know about the chunk errors until some time after, as people started claiming plots furthest away

**Comment by MattBDev** [comment]
@thecenters At one point a few weeks ago, Spigot and Paper published an update that broke chunk generation entirely. It wasn't fixed until a few weeks later. It likely happened during that period of time. PlotSquared has no way of fixing this unless you remove the chunks and have the game regenerate them.
