### ISSUE TITLE
flag "untrusted-visit" down't work

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquared#2727]
### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [X] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
This server is running CraftBukkit version git-Spigot-518206a-a5b9c7b (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [] WorldEdit version: 
- [X] PlotSquared version: **5.515**

### Description of the problem:

With the deactivated "untrusted-visit" flag my testuser (without trust / add) can still join the plot or teleport to the plot (/p v). In difference the "leave" restriction of the "deny-exit" flag works great.

### How to replicate:

1. `/p flag set untrusted-visit false`
2. User 2 (not plot-member or trusted) can go to the plot
3. User 2 (not plot-member or trusted) can use the `/p visit <coordinate> command`
4. `/p flag set untrusted-visit true`
5. User 2 (not plot-member or trusted) can go to the plot
6. User 2 (not plot-member or trusted) can use the `/p visit <coordinate> command`

Same with trusted users. No difference.

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by MattBDev** [comment]
You seem to be testing a lot of versions.

**Comment by RedstoneFuture** [comment]
I hope It's useful. :D
