### ISSUE TITLE
flag "vehicle-break" vs. "vehicle-place"

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquared#2728]
### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [X] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
This server is running CraftBukkit version git-Spigot-518206a-a5b9c7b (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [] WorldEdit version: 
- [X] PlotSquared version: **5.515**

### Description of the problem:

In the v.5 the "vehicle-place" flag are removed. Was this planned? Additionally, If I activate the "vehicle-break" flag, my testuser can break and place vehicles.

### How to replicate:

1. `/p flag set vehicle-break`
==> User can break and place vehicles as non-member
2. `/p flag set vehicle-place`
==> Command not found.

![2020-03-25_02 44 52](https://user-images.githubusercontent.com/4140635/77493158-aa2a0980-6e42-11ea-9499-8c9c85077617.png)

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by RedstoneFuture** [comment]
With this fix a consistency check of the code for "misc-place", "misc-break" and the "hanging-place" and "hanging-break" flag are useful.

**Comment by Sauilitired** [comment]
Turns out we had forgotten to register the vehicle place flag.
