### ISSUE TITLE
Border Removal with Headless Pistons

### ISSUE THREAD

**Issue by Xadzkon** [IntellectualSites/PlotSquared#2729]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):

https://athion.net/ISPaster/paste/view/38cac4845938453c97a4d140fbb30473

### Server type:
**Select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [X] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
This server is running CraftBukkit version git-Spigot-a03b1fd-fc318cc (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [X] WorldEdit version: Bukkit-Official(7.1.0;8e55131)

### Description of the problem:

Headless pistons can remove plot borders and bedrock at level 0. Servers which give access to WorldEdit to their players can suffer from this issue a lot, but it is also possible to get headless pistons without WorldEdit (even in survival) if you spend a little bit of time.

### How to replicate:

`//set piston[extended=true]` on the side of borders. You might need to rotate the pistons to the right direction.

### Other plugins being used on the server:

WorldEdit

### Relevant console output, log lines, and/or screenshots:
Video: https://www.youtube.com/watch?v=D3ypFRhnKWI

### Additional relevant comments/remarks:

I'm running the server on my personal computer.
Windows 10 x64
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by MattBDev** [comment]
I have an idea on how to fix this but it may be a bit of a hack and it may not block this from happening with WorldEdit. The problem with this issue is that it is a bug in vanilla behavior of pistons.

**Comment by RedstoneFuture** [comment]
Have we theoretically a fix in FAWE for that?

**Comment by Sauilitired** [comment]
This is a Minecraft issue and there's not a lot we can do. You can limit the use of extended pistons using whatever WorldEdit implementation you use.
