### ISSUE TITLE
problem with permissions (claim maximum)

### ISSUE THREAD

**Issue by KillerWolf37** [IntellectualSites/PlotSquared#2732]
So, when i was configuring plot squared for my mine hut server i went through the commands and when i put plots.plot to 1 it still let me claim more than one plot and all of the youtube videos are not helping anyone that can help?

**Comment by RedstoneFuture** [comment]
```
        - plots.use
        - plots.visit
        - plots.visit.other
        - plots.visit.owned
        - plots.visit.shared
        - plots.info
        - plots.auto
        - plots.claim
        - plots.continue
        - plots.plot.5
```

Check the permission. Do you have OP or *-perms? ... Use the bug report template, please!

**Comment by KillerWolf37** [comment]
What do you mean do you have op or -*perms?

**Comment by Sauilitired** [comment]
Are you a server operator, or do you have the wildcard '*' permission, and/or PlotSquared admin permissions? If so, you'll be able to exceed the maximum plot count.

**Comment by RedstoneFuture** [comment]
Status? @KillerWolf37

**Comment by KillerWolf37** [comment]
Yes i am a server operator and have '*' permissions but default still can get more plots than what i put how do i do i fix that?

**Comment by KillerWolf37** [comment]
sorry for being idle for a while

**Comment by chowder3907** [comment]
I've been having the exact same problem, the default group gets the permission set and they can still claim as many plots as they like

**Comment by KillerWolf37** [comment]
I know! Honestly plotsquared needs to be updated by the devs

**Comment by Sauilitired** [comment]
What permission nodes does the default group have, and what does your settings look like? We can't help you if you don't provide any information.

**Comment by KillerWolf37** [comment]
How do i find the permission nodes?

**Comment by KillerWolf37** [comment]
Status? @Sauilitired

**Comment by AeSix** [comment]
You'll need to install luckperms, permissionex, etc.  Then, you need to look on the wiki, read it until you understand it.  Finally, you need to assign appropriate permissions to the players through your permission system of choice.  

It would really help, if the next you your file a ticket, that you actually follow the template set forth when creating the ticket - on here or any other project.

**Comment by KillerWolf37** [comment]
I have luckperms i read the wiki i still don't understand
(Sorry im new to github)

**Comment by KillerWolf37** [comment]
ill pastebin my luckperms config file

**Comment by KillerWolf37** [comment]
https://pastebin.com/hFkkGA3C

**Comment by RedstoneFuture** [comment]
@KillerWolf37 The Config is unuseful. In this data the permissions aren't saved.

**Comment by KillerWolf37** [comment]
What can i upload?? to help you??

**Comment by KillerWolf37** [comment]
What is something to upload so I can get help?

**Comment by RedstoneFuture** [comment]
The full permission list are great. Maybe the SQLite data with the permissions.

**Comment by KillerWolf37** [comment]
Ok

**Comment by KillerWolf37** [comment]
Can i give you the permissions.yml file?
Would that work?

**Comment by KillerWolf37** [comment]
Awaiting response

**Comment by KillerWolf37** [comment]
My permissions.yml is empty.

**Comment by KillerWolf37** [comment]
What do I do?

**Comment by KillerWolf37** [comment]
Luckperms is missing

**Comment by KillerWolf37** [comment]
I am going to start my own server

**Comment by KillerWolf37** [comment]
I am on a minehut server, it is 1.15.2, Plotsquared does not work, my permissions.yml file is empty, please help

**Comment by Sauilitired** [comment]
I tested with the latest version of LuckPerms and the permission limits are working as intended. Please read the documentation for the permission plugin you're using, we can't help you with that.

**Comment by KillerWolf37** [comment]
I was trying to say my permissions.yml file was empty!

**Comment by MattBDev** [comment]
@KillerWolf37 If you don't understand how permissions work I suggest using google or youtube because there are some excellent tutorials. The only problem with the plugin is that you don't know how to use it because you lack the knowledge to set the permissions up properly. LuckPerms has good support and the Spigot Forums are very useful too.
