### ISSUE TITLE
WorldEdit //copy can copy from other plots

### ISSUE THREAD

**Issue by ItsGJK** [IntellectualSites/PlotSquared#2733]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):

https://athion.net/ISPaster/paste/view/835b32552b8f470bb13c741568f0525f
### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [X] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
This server is running Paper version git-Paper-143 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [X] WorldEdit version: 7.10.8;8e55131

### Description of the problem:

BazookaMan_93 selected one corner of a plot adjacent to his, then selected another block on his own plot and performed //copy and //paste to paste the contents of the *other* plot that he is not shared with onto his own.

### How to replicate:

1. Select a part of another plot that you are not trusted on using //wand 
2. Select any part of your own plot
3. Run //copy
4. Run //paste on your own plot
5. Result: The other plot's contents will be copied onto your own.
## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.
N/A - This is a recently created server and BazookaMan_93 has no outlying permissions. He shouldn't be able to outright copy other plots.
### Other plugins being used on the server:

This is in the debugpaste. 'HungerCore' is my own custom plugin using the PlotSquared API for /done functionality (plot submission to judges) - it should not interfere with this. All other features of PlotSquared are functional.
### Relevant console output, log lines, and/or screenshots:

```No relevant console information, no errors/messages from PlotSquared when he performs //copy or //paste. He was able to copy another plot onto his own that was diagonal to his own.```
### Additional relevant comments/remarks:

I'm using Meloncube as a host, 1GB of RAM server
# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by RedstoneFuture** [comment]
In the debugpaste link I see :

```
  FastAsyncWorldEdit:
    version: '1.15.2'
    enabled: true
```

FAWE 1.15.2 isn't stabile currently. Check the github site of fawe.

**Comment by ItsGJK** [comment]
I had DummyFAWE installed (I originally had FAWE then removed the jar, I guess I forgot to remove DummyFAWE as well)

It still works without FAWE.

**Comment by N0tMyFaultOG** [comment]
Please reproduce the issue when using v5 and reopen the issue if it persits.

**Comment by RedstoneFuture** [comment]
In this case reopen it on https://issues.intellectualsites.com/issues , please.
