### ISSUE TITLE
Chunk generation errors after 1.15 upgrade

### ISSUE THREAD

**Issue by Mikgreg** [IntellectualSites/PlotSquared#2734]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):
worlds.yml https://hastebin.com/ahogoxafiw.sql
settings.yml https://hastebin.com/jucusowiyo.bash
latest.log https://gist.githubusercontent.com/Mikgreg/7f2bb7ca64bb0cdf6497a1b8ca192abe/raw/ed2dccdd0fe8070afb98407b553d689e93d69888/gistfile1.txt

### Server type:
**Select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [x] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
git-Paper-145 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [x] WorldEdit version: v7.1.0;8e55131

### Description of the problem:

We've decided to upgrade our (old af) Creative server to 1.15, the steps we took to do this was to download the latest build from Spigot, replace our old jar with it, and do the same thing for PaperSpigot. When starting our server back up the server spits out errors relating to chunk generation and then hangs. 
### How to replicate:

After completing the steps mentioned above I can crash the server by running /plot auto
## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

Relevant stack produced on /plot auto:
https://hastebin.com/ucusumerib.md

### Additional relevant comments/remarks:

There are other broken plugin issues in the latest.log however none of these are related to PlotSquared, many of our other plugins hadn't been upgraded yet as we stumbled into this issue in the first stage of us upgrading the server.

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by Sauilitired** [comment]
Use PlotSquared v4+, v3 is a legacy version.
