### ISSUE TITLE
Sponge 1.12.2 PlotSquared Bugs

### ISSUE THREAD

**Issue by ivandelp** [IntellectualSites/PlotSquared#2737]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server type:
**Select one**

- [] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [X] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [X 1.12.2] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
Sponge 1.12.2 | In sponge that command not work
```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [] WorldEdit version: 

### Description of the problem:

Some users have plots and his slab are not changed when claim it. 

In some plots, the owners are Unknowed and are chunks bugged with air blocks.

Some times if a player would teleport to his plot and worldborder is active, that player are killed and teleported to the barrier.

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

Slabs Problem: https://imgur.com/a/LsJaJIR

Unknown owner and air blocks bug: https://imgur.com/a/U76pTDL

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by MattBDev** [comment]
No information was provided

**Comment by ivandelp** [comment]
Description of the problem:
Some users have plots and his slab are not changed when claim it.

In some plots, the owners are Unknowed and are chunks bugged with air blocks.

Some times if a player would teleport to his plot and worldborder is active, that player are killed and teleported to the barrier.

**Comment by MattBDev** [comment]
You still chose to ignore parts of the template. We need a `/plot debugpaste` link.

**Comment by ivandelp** [comment]
It's difficult to read all the templete, sorry for that.

Here it is
https://www.athion.net/ISPaster/paste/view/6becd0165b4d48e8a75154f8a5338b08
