### ISSUE TITLE
Sync load on Plot.getHome

### ISSUE THREAD

**Issue by iLemon** [IntellectualSites/PlotSquared#2738]
https://spark.lucko.me/#MRR7XCoQXc

Running on a 1.15.2 paper fork.

Running PlotSquared-Breaking 491 (latest)

**Comment by MattBDev** [comment]
Although you didn't fill out the template, I know this is a valid issue because I've seen it before. I told all the other guys on who also work on the plugin and they didn't believe me. Maybe now they will.

**Comment by Sauilitired** [comment]
This has been resolved in version 5.
