### ISSUE TITLE
commands.yml translations do not apply

### ISSUE THREAD

**Issue by workonfire** [IntellectualSites/PlotSquared#2739]
### Server config info (/plot debugpaste / file paste links):
https://athion.net/ISPaster/paste/view/33964d9bba6e4eab8ca86cabd913d7f3

### Server type:
- [X] Spigot / Paper

### Minecraft Version:
- [x] Minecraft 1.14.4

### Server build info: 
```
This server is running Paper version git-Paper-242 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:
- [X] WorldEdit version: Bukkit-Official(7.1.0-rc-1;05cc7aa)

### Description of the problem:

The translations from `PlotSquared/config/commands.yml` do not apply **at all**. I reloaded the plugin, of course, using `/plots reload`. Still nothing. The translations are STILL in the original language. [Here](https://pastebin.com/TspTb6VX) is my `commands.yml` file.

### How to replicate:
Change the `description` values in `commands.yml`.

# AFFIRMATION OF COMPLETION:
- [X] I included all information required in the sections above
- [ ] I made sure there are no duplicates of this report - no. There are duplicates, but as I see - none of them appear to contain a fix for the issue.
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin.

**Comment by RedstoneFuture** [comment]
With v.5 and v.453 at me it works:

![2020-04-04_16 33 29](https://user-images.githubusercontent.com/4140635/78453467-28cc4580-7692-11ea-9075-9197efac86a7.png)

**Comment by RedstoneFuture** [comment]
I hope you restarted the server after this translation.

**Comment by workonfire** [comment]
Oh. I really forgot about restarting the server, because there were players online. I thought `/plot reload` should just do its job and reapply the translations.

Thank you, and sorry for not checking everything again.
