### ISSUE TITLE
permission problem (destory permission)

### ISSUE THREAD

**Issue by MafiaBossTTR** [IntellectualSites/PlotSquared#2740]
Server Logs: https://athion.net/ISPaster/paste/view/86b4b37deade4cac9fc188fffb47b884

### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [X] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
This server is running CraftBukkit version git-Spigot-a03b1fd-95bd423 (MC: 1.15.2)
You are 2 versions(s) behind
```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [X] WorldEdit version: 

### Description of the problem:

When i created the PlotSqaured Default world it didn't set the default gamemode to creative but survival. So i checked in the config file and found it was set to creative. So then i used /mvm set mode creative To then change the world gamemode to creative and then my users could start breaking plots that were not claimed and were claimed without the permision. My permissions are setup and working in survival but not creative. Please help!

### How to replicate:
Create a PlotSquared world and the default gamemode will be survival. Use /mvm set mode creative to change the worlds default gamemode and deop yourself with no permissions and then try to destroy an unclaimed plot. In theory you should not be able to do so. However players can destroy them but not build

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.
When you destroy the block the plugin states you do not have that permission the break but it still breaks
### Other plugins being used on the server:
 LuckPerms Multiverse-core, 

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [] I made sure the bug/error is not caused by any other plugin
- [x] I didn't read but checked everything above.

**Comment by MafiaBossTTR** [comment]
![evidence](https://user-images.githubusercontent.com/59403870/78443346-82237d00-7670-11ea-9642-4f6ce7a4d0aa.png)
This is the luckperms prermissions that are set for normal players

**Comment by RedstoneFuture** [comment]
Have you restarted the server?

**Comment by RedstoneFuture** [comment]
![Unbenannt](https://user-images.githubusercontent.com/4140635/78453105-ef92d600-768f-11ea-9f1c-80a5dadbb876.png)

Nice! ^^

**Comment by MafiaBossTTR** [comment]
Yes i have restarted the Server  many times to try and fix but nothing. The PlotSquared world when created puts the defualt gamemode into survival even thought the config states its creative. I used /mvm set mode creative for the world but now players can destroy the unlclaimed and claimed plots.
@RedstoneFuture

**Comment by MafiaBossTTR** [comment]
@RedstoneFuture The players Can't build on unclaimed plot becuase they don't have the perm which is great! but they can still destory :(

**Comment by MafiaBossTTR** [comment]
@RedstoneFuture I have restarted server and no luck. Any way i can fix this?

**Comment by MafiaBossTTR** [comment]
I have taken a short video of what happens to show you. https://youtu.be/J-KXvec86qw
@RedstoneFuture

**Comment by MafiaBossTTR** [comment]
Bump

**Comment by MafiaBossTTR** [comment]
Bump

**Comment by RedstoneFuture** [comment]
Please stop this "Bump" messages. If anyone can help you, or have a fix, they will write at here.
