### ISSUE TITLE
Could not pass event ChunkLoadEvent to PlotSquared v4.453

### ISSUE THREAD

**Issue by makemp1997** [IntellectualSites/PlotSquared#2742]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [X] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
version git-Paper-162 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [X] WorldEdit version: 7.1.0

### Description of the problem:

Well firstly I am aware that I had reported some issues in the past, but this time I have changed and updated the server to new version and setup. Though to our needs we have in the specific game-mode / server several normal creative world and also several plots worlds. For starers when doing /mv tp creative I can tp normally to that world. Although when I do "/openplots" and "/back" to that world I got tped back to the world I tp'ed from or to another plot world, I got the following console message: "Could not pass event ChunkLoadEvent to PlotSquared v4.453". I also use at least CMI and with HomeSpawnPlus I made it possible that players can use "/openplots" or "/void" to go to those worlds. Is there a way to solve this or I can do differently .

### How to replicate:

1. From any other world: /openworld or /back

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Additional relevant comments/remarks:

I add also add a "/plot debugpaste"report: https://athion.net/ISPaster/paste/view/dea94fd023f94de0b99a0f4061006837

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)], Well I saw some old topics but I am not sure it is related to mine. (https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin, well I am nor sure I do not think so
- [x] I didn't read but checked everything above.

**Comment by makemp1997** [comment]
Hello,
Thank you for the comment but I do not exactly what you comment is referring about the comment 

> Don't try to remove players

Greetings

makemp1997
aka makemp2014

**Comment by N0tMyFaultOG** [comment]
He fixed your issue for PlotSquared v5, the next upcoming release.
