### ISSUE TITLE
Bed turn Grass_Path into Dirt

### ISSUE THREAD

**Issue by Resi23** [IntellectualSites/PlotSquared#2744]
# Bug Report Template:

## Required Information section:
https://athion.net/ISPaster/paste/view/cc48eb29db3c49f2bb254a75ee433585

### Server type:
**Select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [x] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
git-Paper-162 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [x] WorldEdit version: Bukkit-Official(7.1.0;8e55131)

### Description of the problem:
Players without rights on a plot can turn Grass_path into dirt by placing a bed

### How to replicate:
Place a bed on a plot on which you have no rights

### Relevant console output, log lines, and/or screenshots:
```
[10:50:53 ERROR]: POI data mismatch: never registered at BlockPosition{x=74, y=65, z=-160}
[10:50:53 ERROR]: POI data mismatch: never registered at BlockPosition{x=75, y=65, z=-160}
[10:50:53 ERROR]: POI data mismatch: never registered at BlockPosition{x=76, y=65, z=-160}
[10:50:53 ERROR]: POI data mismatch: never registered at BlockPosition{x=76, y=65, z=-160}
[10:50:54 ERROR]: POI data mismatch: never registered at BlockPosition{x=77, y=65, z=-160}
[10:50:54 ERROR]: POI data mismatch: never registered at BlockPosition{x=78, y=65, z=-160}
```

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by RedstoneFuture** [comment]
Right.

PS cancel the place-event, but MC update the one block under the bed.

![2020-05-19_03 20 59](https://user-images.githubusercontent.com/4140635/82274284-095a5500-9980-11ea-8a64-baa7570d25da.png)

**Comment by RedstoneFuture** [comment]
moved to: https://issues.intellectualsites.com/issue/PS-16
