### ISSUE TITLE
flag "misc-cap" - leash_knot and end_crystal not blocked

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquared#2747]
### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [X] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
This server is running CraftBukkit version git-Spigot-518206a-a5b9c7b (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [] WorldEdit version: 
- [X] PlotSquared version: **5.537**

### Description of the problem:

I checked the misc-cap flag and I found 2 miscellaneous entities there aren't supported in this flag:

- leash_knot
- end_crystal

I think it's better to add this 2 miscellaneous entities.

### How to replicate:

1. `/p f s misc-cap 0`
2. `/summon leash_knot`
3. `/summon end_crystal`

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by Sauilitired** [comment]
They are covered by entity cap. Misc cap is just armor stands, item frames and paintings. Although I do agree that they would probably do better in misc cap, we have decided not to change flag behaviors. 

So essentially, all entities are affected by entity cap, only certain (in this case, special tile entities) are covered by the misc cap.
