### ISSUE TITLE
problems with flag "misc-interact", "misc-break" and "misc-place"

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquared#2748]
### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [X] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
This server is running CraftBukkit version git-Spigot-518206a-a5b9c7b (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [] WorldEdit version: 
- [X] PlotSquared version: **5.537**

### Description of the problem:

1. With a misc-interact event I get this error:

https://pastebin.com/kD6zynme

2. PS don't find the "misc-place" flag.

3. With `/p f s misc-break true` the user can't break an Item_frame (with and without an item-frame item) and a painting, but he can break an armor_stand.

### How to replicate:

1. Right-Click on armor_stand and item_frame. -> I get this error.
2. `/p f s misc-break true` -> User can't break a item_frame and a painting.
3. Try to set a "misc-place" flag.

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by RedstoneFuture** [comment]
In the best case a other player can't edit an armor_stand too If the flag is disabled.

**Comment by SirYwell** [comment]
Item Frames should aren't `misc` but `hanging`, so you'd need to set the flag `hanging-break` to true. The other two problems are fixed (would be nice if you could test it again to verify that), and if I get it right, the third one should be solved too when using the correct flags
