### ISSUE TITLE
flag "hostile-attack" and "hostile-interact" don't include slimes

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquared#2749]
### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [X] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
This server is running CraftBukkit version git-Spigot-518206a-a5b9c7b (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [] WorldEdit version: 
- [X] PlotSquared version: **5.537**

### Description of the problem:

If I set the flag "hostile-attack" and "hostile-interact" to true the player can interact and attack e.g. creeper or other hostile mobs, but only slimes aren't include in this flag.

### How to replicate:

1. `/p f set hostile-attack true`
2. `/p f set hostile-interact true`

=> An other player haven't the permission to attack and interact with slimes.

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by SirYwell** [comment]
Probably fixed in 4a24984, wasn't able to test for now. Would be nice if you could do that :)
