### ISSUE TITLE
Road schematics' problem

### ISSUE THREAD

**Issue by Mr-Notch** [IntellectualSites/PlotSquared#2750]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [X] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

This server is running Paper version git-Paper-164 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Paste the output here, between the tick marks, replacing this text
none

### WorldEdit/FAWE versions:

- [] FAWE version:
- [X] WorldEdit version: * Bukkit-Official(7.1.0;8e55131)

### Description of the problem:

The road of the town template that I generated using the "/ plot template" command is misaligned.
Like this:
![图片](https://user-images.githubusercontent.com/55701169/78905890-37ab6180-7ab1-11ea-8377-a12ed290b0d9.png)

Player(opped), To generate Town template. On Paper 1.15.2. Why? I dont know.., Use /plot template import plotworld town.
### How to replicate:

First, use "/plot template import plotworld town" to create a world named plotworld
Second, shut down the server. And delete the world, go to "./plugins/PlotSquared/config/world.yml, and delete this:

before:
![图片](https://user-images.githubusercontent.com/55701169/78906391-dc2da380-7ab1-11ea-8b54-1dbc27d3d43e.png)
after:
![图片](https://user-images.githubusercontent.com/55701169/78906446-eea7dd00-7ab1-11ea-9938-cde6f69a1e7f.png)

Third, turn on the server, go to the server and use /mv tp plotworld to teleport the player to plotworld.

Then, the problem appeared
## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Other plugins being used on the server:

![图片](https://user-images.githubusercontent.com/55701169/78906730-4cd4c000-7ab2-11ea-8644-98ba6369518a.png)

### Relevant console output, log lines, and/or screenshots:

My server is running on my own computer.
JDK version:
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin

ps:I am not sure if the problem is caused by Paper Core

- [x] I didn't read but checked everything above.

**Comment by dordsor21** [comment]
Not misaligned. You've made a road schematic that can't be rotated. Look at the top and bottom of your own screenshots; 2 instead of 3 blocks.
