### ISSUE TITLE
flag "animal-attack" include villager and shulker

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquared#2752]
### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [X] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
This server is running CraftBukkit version git-Spigot-518206a-a5b9c7b (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [] WorldEdit version: 
- [X] PlotSquared version: **5.536**

### Description of the problem:

In v.5 the "animal-attack include the villager and shulker. If I activate this flag a non-member can attack this 2 mobs too. In difference the "animal-interact" flag don't include this 2 mobs.

### How to replicate:

1. `/p flag set animal-attack true`
2. spawn mobs and test it with a player without permissions in the plot:
- creeper = no permission | OK
- zombie villager = no permission | OK
- **villager = player can attack it | X**
- **shulker = player can attack it | X**

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by Sauilitired** [comment]
Villager is controlled using the `villager-interact` flag. Shulkers (and iron golems)  are golems, and belong to the Golem category (they're both Mobs).

The most fitting solution would therefore be to add a golem-interact flag.

**Comment by RedstoneFuture** [comment]
@Sauilitired Based on the [minecraft-wiki](https://minecraft.gamepedia.com/Mob#Hostile_mobs) shulkers are hostile-mobs. So the "animal-attack" flag can ignore it. And that the villager are included in this flag too is ok for me.
