### ISSUE TITLE
PVE flag  blocking EVE damage

### ISSUE THREAD

**Issue by TauCubed** [IntellectualSites/PlotSquared#2762]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):
https://athion.net/ISPaster/paste/view/8b4556c0b90c4ee381580052413988e9
^ On a test server, version and plugins may be different to production server, I will not paste the production server here as it reveals personal information about our players (such as IP addresses) and it will be a pain to remove all of the spam from some of our debugging plugins

### Server type:
**Select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [o] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [o] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [x] Minecraft 1.15.2
- [o] Minecraft 1.14.4
- [o] Minecraft 1.13.2
- [o] Minecraft Java Edition *other versions, please specify*:
- [o] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
[10:12:34 INFO]: This server is running Tuinity version git-Tuinity-"8499889" (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[10:12:34 INFO]: Previous version: git-Tuinity-"c2ad42c" (MC: 1.15.2)
[10:12:34 INFO]: You are 20 version(s) behind
```

### WorldEdit/FAWE versions:

- [x] FAWE version: commit fa3385f7 (bukkit)
- [] WorldEdit version: 

### Description of the problem:

PVE flag blocks EVE damage when set to false, expected EVE to be untouched as PVE is Player vs. Entity, not Entity vs. Entity; Considering hostile-interact is a flag and the fact that PVE means Player vs. Entity I think this to be a bug.

### How to replicate:

1) Create server with stock PS (doesn't matter if you have FAWE or normal WE)
2) Create a plot world (Anything you'd like)
3) Enable entities in the configurations required.
4) Spawn a hostile entity that can (and will) be attacked by an Iron Golem. 
5) spawn an iron golem near the hostile.
6) Observe results
7) Set PVE to true in flags
8) Observe results

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x (I think)] I made sure the bug/error is not caused by any other plugin
- [x] I HAVE read AND checked needed everything above.

**Comment by RedstoneFuture** [comment]
No, in the last days I checked this flag and saw the correctly definition of "PvE"; it mean "Player vs. Environment" (https://de.wikipedia.org/wiki/Player_versus_Environment).

With this definition Its understandable that this flag are include Entity vs. Entity and  Environment vs. Entity too.

**Comment by TauCubed** [comment]
Then how would it be possible to allow only entity v entity, and not player v entity.
Even if it was Player vs. Environment there is no player between two entities attacking one another, so that is very counter intuitive.
