### ISSUE TITLE
Players lose tridents when cast on plotworld

### ISSUE THREAD

**Issue by LocarMarc** [IntellectualSites/PlotSquared#2770]
**Debug paste link:** 

**[REQUIRED] Spigot/Paper Version Number:** 
git-Paper-164 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**[REQUIRED] Minecraft Version Number:** 
1.15.2

**[REQUIRED] Description of the problem:** 
Players lose tridents when cast on plotworld, when they do it just disappears from inventory

**Comment by N0tMyFaultOG** [comment]
Please follow the template when reporting an issue.
