### ISSUE TITLE
Plotsquared not loading, Json Parser error

### ISSUE THREAD

**Issue by mnjg123** [IntellectualSites/PlotSquared#2773]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server type:
**Select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge *- NOTE: NOT ACTIVELY MAINTAINED*
- [] NukkitX *- NOTE: NOT ACTIVELY MAINTAINED*

### Minecraft Version:
**Select one**

- [x] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:

### Server build info: 

```
[15:01:13 INFO]: This server is running Paper version git-Paper-194 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[15:01:13 INFO]: Checking version, please wait...
[15:01:13 INFO]: You are running the latest version

```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [x] WorldEdit version: WorldEdit version 7.1.0;8e55131

### How to replicate:

Start server with the plugin

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Other plugins being used on the server:

 Plugins (3): Multiverse-Core, PlotSquared, WorldEdit

### Relevant console output, log lines, and/or screenshots:

https://hastebin.com/rukejagixe.md
https://hastebin.com/zucifefaso.pl 

for short (20 lines or less) text blobs, or a paste service for large blobs -->

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [ ] I didn't read but checked everything above.

**Comment by Sauilitired** [comment]
Update to the latest build. This has been fixed.
