### ISSUE TITLE
/plot download being restricted to .schematics and zip files only

### ISSUE THREAD

**Issue by N0tMyFaultOG** [IntellectualSites/PlotSquared#2775]
With the recent change to schematic v2 in ps v5, plot downloading does no longer work, because the plot interface is bound to schematics and zips, see https://github.com/IntellectualSites/plotupload/blob/2c503429145ee4c141571c43acebcb9d8209dc0d/plotupload/upload.php#L46
![](https://i.imgur.com/FkICUwq.png)

Tagging you here @dordsor21 because you're kindly running the plot interface :)

**Comment by dordsor21** [comment]
Try now

**Comment by N0tMyFaultOG** [comment]
Fixed
