### ISSUE TITLE
Wrong PlotSquared Link

### ISSUE THREAD

**Issue by DieProgrammIDE** [IntellectualSites/PlotSquared#2791]
<img width="763" alt="Screenshot 2020-04-23 at 14 29 36" src="https://user-images.githubusercontent.com/39222199/80117883-01c5ad00-8588-11ea-86aa-b39d0986e37a.png">
Link in Console to Update Plotsquared is Wrong. P^2 5

**Comment by N0tMyFaultOG** [comment]
You are running an outdated version.
