### ISSUE TITLE
/p download failed to generate download link

### ISSUE THREAD

**Issue by MADS0LADEN** [IntellectualSites/PlotSquared#2792]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):

https://athion.net/ISPaster/paste/view/287203fc02844fd3993e1156af9b9942

### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge
- [] NukkitX

### PlotSquared version:

```
[17:38:11 INFO]: [Plots] >> PlotSquared (Version: PlotSquared-5.10)
[17:38:11 INFO]: [Plots] >> Authors: Citymonstret & Empire92 & MattBDev & dordsor21 & NotMyFault & SirYwell
[17:38:11 INFO]: [Plots] >> Wiki: https://github.com/IntellectualSites/PlotSquared/wiki
[17:38:11 INFO]: [Plots] >> Premium: true
```

### Minecraft Version:
**Select one**

- [X] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft 1.12.2
- [] Minecraft 1.11.2
- [] Minecraft 1.10.2
- [] Minecraft 1.9.4
- [] Minecraft 1.8.8
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:
- [] Minecraft Sponge *specify version*:

### Server build info: 

```
[17:38:33 INFO]: This server is running Paper version git-Paper-211 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[17:38:33 INFO]: Checking version, please wait...
[17:38:33 INFO]: Previous version: git-Paper-208 (MC: 1.15.2)
[17:38:33 INFO]: You are running the latest version
```

### WorldEdit/FAWE versions:

- [x] FAWE version: Build 176 Commit f6ea05a1
- [] WorldEdit version: 

### Description of the problem:

Does not give you a download link when using /p download

### How to replicate:

Type /p download

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by N0tMyFaultOG** [comment]
Replace `https://empcraft.com/plots/` with `https://athion.net/plots/` in your settings.yml.
