### ISSUE TITLE
DenyTeleportFlag missing fields or a public constructor

### ISSUE THREAD

**Issue by MeFisto94** [IntellectualSites/PlotSquared#2794]
Sorry for leaving out the issue template completely on this one, but since my concern is a purely API/Programming perspective, it's not about actual versions causing problems:

https://github.com/IntellectualSites/PlotSquared/blob/591eb60a718b254bfc33d8fac18a3d45a0e2a1ae/Core/src/main/java/com/plotsquared/core/plot/flag/implementations/DenyTeleportFlag.java#L41

I'm missing static variables for all the potential DenyTeleportFlags (one per DeniedGroup).

**Comment by Sauilitired** [comment]
Get an instance of the flag, preferably via the GlobalFlagContainer (or DenyTeleportFlag.DENY_TELEPORT_FLAG_NONE) and use flagOf. Flags instances are not meant to be constructed.

So, you could do 

```java
DenyTeleportFlag parsedFlag = GlobalFlagContainer.getInstance().getFlag(DenyTeleportFlag.class).flagOf(yourValue);
```

**Comment by MeFisto94** [comment]
Okay, thanks!
I was just confused by the Flags for things like PveFlags etc, should I change that to the GlobalFlagContainer there as well?
