### ISSUE TITLE
Problem with /plot chat

### ISSUE THREAD

**Issue by aurel85** [IntellectualSites/PlotSquared#2797]
Hi,

# Bug Report Template:
https://athion.net/ISPaster/paste/view/846dcb46b8ab489d8a77e40109325906

### Server type:
- [X] Spigot / Paper

### PlotSquared version:
PlotSquared (Version: PlotSquared-5.10)

### Minecraft Version:
**Select one**
- [X] Minecraft 1.15.2

### Server build info: 
Paper 220

### WorldEdit/FAWE versions:
- [X] WorldEdit version:  7.2.0-SNAPSHOT+4990-ba91dff

### Description of the problem:
Since V5 the /plot chat no longer reacts, it activates/deactivates well for everyone but when we talk with it is displayed in the general chat.

### How to replicate:
![Capture](https://user-images.githubusercontent.com/24486147/80365387-cbd64080-8887-11ea-9d75-aca2b65a6327.PNG)

## Additional Information:
My players have permissions plots.chat with plots.permpack.basic

### Other plugins being used on the server:
Plugins (72): ActionBar*, AdvancedAchievements, afkTerminator*, AnimatedNames*, ArmorStandSaver*, Bank, BannerBoard*, BottledExp, BreakOwnBedrock*, BuycraftX, BuyRegion, ChatNotif*, ChestShop, ChopTree, Citizens, CitizensCMD, ClaimRemover, CoralStay, Core, CoreProtect, Craftconomy3*, CrateReloaded, DeluxeChat, DiscordMinecraft*, dynmap*, EchoPet, EditableSign, EnchantableBlocks, EntityTrackerFixer, Essentials, EssentialsSpawn, FlowerMeal, FlyingCarpet, GlobalMarketChest, HeadDatabase*, HideAndCustomPlugins*, HolographicDisplays, LibsDisguises, LiteBans, MagicalEvents*, MessageAnnouncer, MineableSpawners, MineResetLite, MobFarmManager, Multiverse-Core, MVdWPlaceholderAPI*, MyCommand, OreBroadcaster, PermissionsEx*, PerWorldInventory, PlaceholderAPI, PlayerJoin, PlayerParticles, PlotSquared, PowerlessLamps*, ProtocolLib, RedProtect, RFChairs, ScalaLoader, ServerSigns, ShopGUIPlus, ShutUp*, SimplePortals, Tab*, TimeIsMoney*, VanishNoPacket*, Vault, Vehicles, Vote, WorldBorder, WorldEdit, WorldGuard

### Relevant console output, log lines, and/or screenshots:
no error in console

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

Thank you in advance.

**Comment by SirYwell** [comment]
Make sure that chat is enabled in your plot area. It's in your `worlds.yml`.

**Comment by aurel85** [comment]
Indeed it was that, strange that between v4 and v5 it changed. Thank you !

**Comment by SirYwell** [comment]
This setting was broken in v4 ^^
