### ISSUE TITLE
Issue with /plot swap

### ISSUE THREAD

**Issue by fhebuterne** [IntellectualSites/PlotSquared#2803]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):

Worlds.yml : https://pastebin.com/5BVD15jp
Settings.yml : https://pastebin.com/QSanwgnE

### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge
- [] NukkitX

### PlotSquared version:

```
[!] >> PlotSquared (Version: PlotSquared-5.10.5)
[!] >> Authors: Citymonstret & Empire92 & MattBDev & dordsor21 & NotMyFault & SirYwell
[!] >> Wiki: https://github.com/IntellectualSites/PlotSquared/wiki
[!] >> Premium: false
```

### Minecraft Version:
**Select one**

- [X] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft 1.12.2
- [] Minecraft 1.11.2
- [] Minecraft 1.10.2
- [] Minecraft 1.9.4
- [] Minecraft 1.8.8
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:
- [] Minecraft Sponge *specify version*:

### Server build info: 

```
This server is running Paper version git-Paper-239 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Checking version, please wait...
Previous version: git-Paper-132 (MC: 1.15.2)
You are running the latest version
```

### WorldEdit/FAWE versions:

- [X] FAWE version: 
(FAWE) FastAsyncWorldEdit-192 created by Empire92
(FAWE) FAWE version:
- Date 30 avr. 2020 00:00:00
- Commit fa04e7db
- Build 192
- Platform Bukkit
(FAWE) Wiki: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
(FAWE) ------------------ Platforms ------------------
* Bukkit-Official(1.15-192;5fb1825)
(FAWE) ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official
- [] WorldEdit version: 

### Description of the problem:

When i do a /plot swap, there are still building from the old plot.

### How to replicate:

Do a **/plot swap** between two plots (Including an plot having one big building like tower).

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Relevant console output, log lines, and/or screenshots:

```
Screenshort before : https://i.fabien-hebuterne.fr/gCubElp0_03-05-2020_17-56-49.jpg

Screenshot after : https://i.fabien-hebuterne.fr/OtI3ro90_03-05-2020_17-57-28.png
```

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [x] I didn't read but checked everything above.

**Comment by dordsor21** [comment]
Issue with FAWE's P2 hook.
