### ISSUE TITLE
Plot Alias not shown in Placeholder and /p info

### ISSUE THREAD

**Issue by DieProgrammIDE** [IntellectualSites/PlotSquared#2810]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge
- [] NukkitX

### PlotSquared version:

```
[20:47:39 INFO]: [P2] >> PlotSquared (Version: PlotSquared-5.10.5)
[20:47:39 INFO]: [P2] >> Authors: Citymonstret & Empire92 & MattBDev & dordsor21 & NotMyFault & SirYwell
[20:47:39 INFO]: [P2] >> Wiki: https://github.com/IntellectualSites/PlotSquared/wiki
[20:47:39 INFO]: [P2] >> Premium: false
```

### Minecraft Version:
**Select one**

- [x] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft 1.12.2
- [] Minecraft 1.11.2
- [] Minecraft 1.10.2
- [] Minecraft 1.9.4
- [] Minecraft 1.8.8
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:
- [] Minecraft Sponge *specify version*:

### Server build info: 

```
[20:47:57 INFO]: This server is running Paper version git-Paper-212 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[20:47:57 INFO]: Previous version: git-Paper-205 (MC: 1.15.2)
[20:47:57 INFO]: You are 42 version(s) behind
```

### WorldEdit/FAWE versions:

- [X] FAWE version:
- [] WorldEdit version: 
```
[20:48:27 INFO]: FastAsyncWorldEdit-173 created by Empire92
[20:48:27 INFO]: FAWE version:
 - Date 21.04.2020 00:00:00
 - Commit f6ad5508
 - Build 173
 - Platform Bukkit
[20:48:27 INFO]: Wiki: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
[20:48:27 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(1.15-173;952aaf8)

[20:48:27 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official
```
### Description of the problem:

Setting the Alias doesn't really work.
Afterwards it is possible to tp with /p tp test, but "None" shows up in /p info and the Welcome Message set Globally with the %alias" Placeholder.
If i needed to guess i would think this has something to do with MySQL, although i am not quite sure this didn't happen before i migrated

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Other plugins being used on the server:

```
[21:02:18 INFO]: Plugins (29): BanManager*, ChatEx*, Citizens, CoreProtect, CreativeItemControl, DiscordSRV, dynmap*, Ersatz*, FastAsyncWorldEdit, HolographicDisplays, HoloPlots, ImageOnMap, LuckPerms, Multiverse-Core, PlaceholderAPI, Plot2Dynmap, PlotSquared, ProtocolLib, SignEditor, Skellett, skLib*, SkQuery, skRayFall*, Skript, SkUniversal*, Vault, WorldEdit, WorldGuard, XConomy*
```
### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by DieProgrammIDE** [comment]
?

**Comment by RedstoneFuture** [comment]
Basically it works at my test server.

`Alias: $2%alias%`

![2020-05-19_02 48 52](https://user-images.githubusercontent.com/4140635/82272826-fba2d080-997b-11ea-8f2a-c1862734eb4d.png)

_tested with PlotSquared (premium) 5.11.1 + 1.15.2 PaperSpigot 300_

**Comment by DieProgrammIDE** [comment]
I also keep getting NullPointerExeptions https://github.com/IntellectualSites/PlotSquared/issues/2842

**Comment by dordsor21** [comment]
the placeholder is `%alias%` not `%alias`

**Comment by DieProgrammIDE** [comment]
https://youtu.be/-tnbXRFAHZ0 I didn't misspell it, i made a video to show you the problem

**Comment by RedstoneFuture** [comment]
Can you test the last version?

**Comment by DieProgrammIDE** [comment]
I'll do that tomorrow. Should i compile it from source?

**Comment by RedstoneFuture** [comment]
Download the [last version at Spigot](https://www.spigotmc.org/resources/plotsquared-v5.77506/history) if you bought the premium version of PS. Then you are up to date with the official compilation.

**Comment by RedstoneFuture** [comment]
moved to: https://issues.intellectualsites.com/issue/PS-3

**Comment by DieProgrammIDE** [comment]
> Download the [last version at Spigot](https://www.spigotmc.org/resources/plotsquared-v5.77506/history) if you bought the premium version of PS. Then you are up to date with the official compilation.

I don‘t own Premium. From which commit should I compile instead?

**Comment by RedstoneFuture** [comment]
Pls use the new thread: https://issues.intellectualsites.com/issue/PS-3
I can't replicate it with the last version.
