### ISSUE TITLE
Players can attack others animals

### ISSUE THREAD

**Issue by QQ9966** [IntellectualSites/PlotSquared#2812]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server type:

- [] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*

### PlotSquared version:

```
PlotSquared-4.4
```

### Minecraft Version:

- [] Minecraft 1.15.2

### Server build info: 

```
This server is running Paper version git-Paper-239 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Previous version: git-Paper-176 (MC: 1.15.2)
You are 22 version(s) behind
```

### WorldEdit/FAWE versions:
-->
- [] WorldEdit version: 7.1.0

### Description of the problem:
Im building survival server with PlotSquared but I have a huge problem

all plots have pve flag : true so mobs can deal damage to players
but that allows everyone to kill others animals

I did use the flag animal-attack : false but it did not work

how can I make it work ?

### How to replicate:

claim 2 plots use /plot flag set pve true
now u can damage others animals and mobs
to fix that i used /plot flag set animal-attack false and hostile-attack false but it didnt work

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by MattBDev** [comment]
You forgot to check the box "I didn't read but checked everything above". You filled out the template wrong and this isn't even a bug, it's a question. Also, your version of the plugin is out of date. The latest version is PlotSquared 5.10.x
