### ISSUE TITLE
entity-pathing enabled breaks slimes and magma slimes from jumping.

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/PlotSquared#2815]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):
Default generated new configs.

### Server type:
**Select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge
- [] NukkitX

### PlotSquared version:

```
PlotSquared v5.10.6 
```
(https://github.com/IntellectualSites/PlotSquared/commit/55fc963673a1c913f1beb1a37bea00fcfe0b1e00)

### Minecraft Version:
**Select one**

- [x] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft 1.12.2
- [] Minecraft 1.11.2
- [] Minecraft 1.10.2
- [] Minecraft 1.9.4
- [] Minecraft 1.8.8
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:
- [] Minecraft Sponge *specify version*:

### Server build info: 

```
Paper version git-Paper-271 (MC: 1.15.2)
```

### WorldEdit/FAWE versions:

Occurs with both on testing.
- [x] FAWE version: dev 217
- [x] WorldEdit version: dev 4997

### Description of the problem:
Slimes and magma slimes do not jump.

### How to replicate:
* Generate default PlotSquared configs and start the server.
* Spawn in slimes with a spawn egg in the overworld.
* Slimes do not jump. They stand still but can still attack you.

## Additional Information:
Turning `` entity-pathing: false`` fixes the issue, allowing slimes and magma slimes to jump again in other (non-plot) worlds.

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by lewisflude** [comment]
I am also having this issue! Fixed by disabling entity-pathing. IMO entity-pathing changes should only affect worlds present in worlds.yml.
