### ISSUE TITLE
Default Flags not working

### ISSUE THREAD

**Issue by Lusteroth** [IntellectualSites/PlotSquared#2817]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):

worlds.yml: https://pastebin.com/kBNZzkD3
settings.yml: https://pastebin.com/BVsreabj

### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge
- [] NukkitX

### PlotSquared version:

```
PlotSquared (Version: PlotSquared-5.10.6)
```

### Minecraft Version:
**Select one**

- [X] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft 1.12.2
- [] Minecraft 1.11.2
- [] Minecraft 1.10.2
- [] Minecraft 1.9.4
- [] Minecraft 1.8.8
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:
- [] Minecraft Sponge *specify version*:

### Server build info: 

```
[17:29:01 INFO]: This server is running Paper version git-Paper-273 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[17:29:01 INFO]: Checking version, please wait...
[17:29:01 INFO]: Previous version: git-Paper-268 (MC: 1.15.2)
[17:29:01 INFO]: You are running the latest version
```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [X] WorldEdit version: Bukkit-Official(7.1.0;8e55131)

### Description of the problem:

Default flags settings (worlds.yml) don't work - P2 doesn't use them as if they were not set

### How to replicate:

Add flags in worlds.yml -> claim a new plot -> check if flags are set (/p i)

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Relevant console output, log lines, and/or screenshots:

```
[17:16:42 INFO]: PlotSquared | Detected world load for 'PlotWorld'
[17:16:42 INFO]: PlotSquared | - generator: PlotSquared>PlotSquared
[17:16:42 INFO]: PlotSquared | - plotworld: com.plotsquared.core.generator.HybridPlotWorld
[17:16:42 INFO]: PlotSquared | - plotAreaManager: com.plotsquared.core.generator.HybridPlotManager
[17:16:42 INFO]: PlotSquared | - default flags: use:oak_door,iron_trapdoor,lever,acacia_fence_gate,light_weighted_pressure_plate,oak_button,tripwire 
```

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by dordsor21** [comment]
Default flags don't show in /ps i

**Comment by Sauilitired** [comment]
You can see if the value parsed correctly by checking the default value in `/plot flag info <flag>`, this is the "default" flag value.

**Comment by Lusteroth** [comment]
> 
> 
> Default flags don't show in /ps i

Maybe you should put this on the wiki, because the default flags are visible in the "older" P2 versions 4/3
