### ISSUE TITLE
World border expansion bug

### ISSUE THREAD

**Issue by eUipKh** [IntellectualSites/PlotSquared#2818]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):

https://athion.net/ISPaster/paste/view/5496c00984e246969433deac8036e355
### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge
- [] NukkitX

### PlotSquared version:

```
[P2] >> PlotSquared (Version: PlotSquared-5.10.5-Premium)
[P2] >> Authors: Citymonstret & Empire92 & MattBDev & dordsor21 & NotMyFault & SirYwell
[P2] >> Wiki: https://github.com/IntellectualSites/PlotSquared/wiki
[P2] >> Premium: true
```

### Minecraft Version:
**Select one**

- [X] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft 1.12.2
- [] Minecraft 1.11.2
- [] Minecraft 1.10.2
- [] Minecraft 1.9.4
- [] Minecraft 1.8.8
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:
- [] Minecraft Sponge *specify version*:

### Server build info: 

```
This server is running Paper version git-Paper-264 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Checking version, please wait...
Previous version: git-Paper-233 (MC: 1.15.2)
You are 9 version(s) behind
```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [X] WorldEdit version: Bukkit-Official(7.1.0;8e55131)

### Description of the problem:

We set the world border auto-expansion in our world and it not working, the border does not update when someone get a plot outside this. The border only updates is someone get a plot outside the border and the server restart.

### How to replicate:

- Create a world using the /plot setup
- Stop the server and set the  border config option under worlds.yml to true
- Start the server and use /plot auto command until you get a plot outside the border
- Done, you can not go to your new plot because is outside the border

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.
- The border just update when the server restart.

### Relevant console output, log lines, and/or screenshots:

That plot is mine (sandstone slab) but I can not go because is outside the borde (test world)r:
- https://imgur.com/K9BKhB1
EDIT: Chat message is > border.border

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by RedstoneFuture** [comment]
moved to: https://issues.intellectualsites.com/issue/PS-13
