### ISSUE TITLE
Plot Chat not working

### ISSUE THREAD

**Issue by JavoxDub** [IntellectualSites/PlotSquared#2819]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge
- [] NukkitX

### PlotSquared version:

```
[00:52:37 INFO]: SurvivalDub | >> PlotSquared (Version: PlotSquared-5.10.5-Premium)
[00:52:37 INFO]: SurvivalDub | >> Authors: Citymonstret & Empire92 & MattBDev & dordsor21 & NotMyFault & SirYwell
[00:52:37 INFO]: SurvivalDub | >> Wiki: https://github.com/IntellectualSites/PlotSquared/wiki
[00:52:37 INFO]: SurvivalDub | >> Premium: true

```

### Minecraft Version:
**Select one**

- [X] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft 1.12.2
- [] Minecraft 1.11.2
- [] Minecraft 1.10.2
- [] Minecraft 1.9.4
- [] Minecraft 1.8.8
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:
- [] Minecraft Sponge *specify version*:

### Server build info: 

```
[00:53:02 INFO]: This server is running Paper version git-Paper-273 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT
```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [X] WorldEdit version: 7.1.0

### Description of the problem:

Plot chat isn't working and flags weren't converted as they should.
### How to replicate:

Just enabling plot chat and then writing.
## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [x] I didn't read but checked everything above.

**Comment by dordsor21** [comment]
Just gonna go ahead and close this. Glad to see that you read the checkboxes, provided all relevant information, and actually looked at your config files.
