### ISSUE TITLE
ChunkUnloadEvent Error When Disabling Paper Listeners

### ISSUE THREAD

**Issue by mercurialmusic** [IntellectualSites/PlotSquared#2822]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*

### PlotSquared version:

```
5.11.0 (today's release)
```

### Minecraft Version:
**Select one**

- [X] Minecraft 1.15.2

### Server build info: 

```
CraftBukkit version git-Spigot-2f5d615-d07a78b (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [X] WorldEdit version: worldedit-bukkit-7.1.0

### Description of the problem:

Massive console spam upon disabling the Paper listeners after updating to 5.11.0. This was the first time trying it and even first time checking the configs after the v5 update so it might not be specific to this version. Using Spigot so I didn't think those were needed. Reenabling them solved the spam:
https://gist.github.com/mercurialmusic/c90f55eefdbbd9d0e729ff13ffa845f7

# AFFIRMATION OF COMPLETION:

- [X] I included most of the information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by dordsor21** [comment]
I can't see any way that enabling or disabling the paper listeners will have any effect on this. Did you update spigot/switch between paper and spigot at the same time, either time?

**Comment by mercurialmusic** [comment]
No, nothing else was updated and I've never used Paper.

**Comment by RedstoneFuture** [comment]
moved to: https://issues.intellectualsites.com/issue/PS-12
