### ISSUE TITLE
PlotSquared not loading

### ISSUE THREAD

**Issue by Elric02** [IntellectualSites/PlotSquared#2826]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):
All configs are unedited, I tried in a new server. Loading logs are provided down here.

### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge
- [] NukkitX

### PlotSquared version:

```
PlotSquared Bukkit 5.10.2
```

### Minecraft Version:
**Select one**

- [X] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft 1.12.2
- [] Minecraft 1.11.2
- [] Minecraft 1.10.2
- [] Minecraft 1.9.4
- [] Minecraft 1.8.8
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:
- [] Minecraft Sponge *specify version*:

### Server build info: 

```
git-Paper-254 (MC: 1.15.2)
```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [X] WorldEdit version: 7.1.0

### Description of the problem:

On server startup, plugin fails to load.

### How to replicate:

Put the plugin in a server plugins folder, load server, watch console.

### Other plugins being used on the server:

None except WE

### Relevant console output, log lines, and/or screenshots:

https://pastebin.com/0b1YLZ8R

### Additional relevant comments/remarks:

Must have installed the plugin wrongly, all the other plugins I try work well :/

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above. (lol)

**Comment by james090500** [comment]
Looks like a corrupt plugin. Try the latest version

https://www.spigotmc.org/resources/plotsquared-v5.77506/

**Comment by Elric02** [comment]
Worked on latest version, sorry for the disturbance
