### ISSUE TITLE
Permissions not listening, players able to do anything until when server first starts

### ISSUE THREAD

**Issue by ablac** [IntellectualSites/PlotSquared#2828]
# Bug Report Template:

[23:29:39 INFO]: [P2] Skipping Multiverse worlds.yml because the plugin is not in use
[23:29:41 INFO]: Uploaded a full debug to: https://athion.net/ISPaster/paste/view/f1f389a630264daeb5a12e65dcc98b39

### Server type:
**Select one**
- [X] Spigot / **Paper** *(CraftBukkit should not be used, re-test with Spigot first!)*

### PlotSquared version:
```
[23:12:13 INFO]: [P2] >> PlotSquared (Version: PlotSquared-5.11.0-Premium)
[23:12:13 INFO]: [P2] >> Authors: Citymonstret & Empire92 & MattBDev & dordsor21 & NotMyFault & SirYwell
[23:12:13 INFO]: [P2] >> Wiki: https://wiki.intellectualsites.com/plotsquared/home
[23:12:13 INFO]: [P2] >> Premium: true
```

### Minecraft Version:

- [X] **Minecraft 1.15.2**

### Server build info: 
```
Paste the output here, between the tick marks, replacing this text
[23:12:52 INFO]: This server is running Paper version git-Paper-246 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [X] **WorldEdit version:** 
[23:13:56 INFO]: WorldEdit version 7.2.0-SNAPSHOT

### Description of the problem:

Using LuckPerms, I Do Not have any permissions set for Plots what so ever, I made Plots my Main World and setup the generator. I am using a Proxy Waterfall. After teleporting from our Lobby to the PlotSquared Server I was able to build in the street but not destroy blocks. I was also able to build and destroy any plot. Issuing a command like /plot claim informed me I did not have permissions, and then updated my permissions across the server, to deny me the ability to build in the street and any unclaimed plots.

### How to replicate:

This has happened to me every time I reboot the server, and Prior to issuing any plot commands in the server. It is not a Permissions issue, because WorldEdit works perfectly for me, and demoting myself to rank without world edit, does work correctly.

## Additional Information:

After getting the permissions to listen to me by doing a command I don't have access to I Teleported another user to test of the permissions worked for him, and again he was able to build anywhere until trying to claim a plot at which point it said he had no permission to build anywhere.

### Other plugins being used on the server:
BungeeTabListPlus, BuycraftX, Essentials, LuckPerms, MaSuiteChat, MaSuiteCore, MaSuiteHomes, MaSuitePortals, MaSuiteTeleports, MaSuiteWarps, MineSync*, PlotSquared, Spartan, Vault, WorldEdit

### Additional relevant comments/remarks:
RackNerd VPN, WaterFall Proxy, Paper. If unable to re-produce please contact me, my sever is available for testing this issue.

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by RedstoneFuture** [comment]
moved to: https://issues.intellectualsites.com/issue/PS-11
