### ISSUE TITLE
Wrong biome is used on roads

### ISSUE THREAD

**Issue by Lusteroth** [IntellectualSites/PlotSquared#2832]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):

worlds.yml: https://pastebin.com/kBNZzkD3
settings.yml: https://pastebin.com/BVsreabj

**/plot debugpaste:** 

### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge
- [] NukkitX

### PlotSquared version:

```
PlotSquared (Version: PlotSquared-5.11.2)
```

### Minecraft Version:
**Select one**

- [X] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft 1.12.2
- [] Minecraft 1.11.2
- [] Minecraft 1.10.2
- [] Minecraft 1.9.4
- [] Minecraft 1.8.8
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:
- [] Minecraft Sponge *specify version*:

### Server build info: 

```
[19:46:45 INFO]: This server is running Paper version git-Paper-284 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[19:46:45 INFO]: Checking version, please wait...
[19:46:46 INFO]: Previous version: git-Paper-283 (MC: 1.15.2)
[19:46:46 INFO]: You are running the latest version
```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [X] WorldEdit version:  WorldEdit version: Bukkit-Official(7.1.0;8e55131)

### Description of the problem:

If you're using a road schematic the biome of the road will be "ocean" and not the biome defined in worlds.yml; plot biome is correct (in my case "forest")
### How to replicate:

Create a new road schematic using /p createroadschematic -> let the world generate-> check the biome of plot/road using F3 
## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Relevant console output, log lines, and/or screenshots:

```
Plot biome: https://prnt.sc/shi9l3
Road biome: https://prnt.sc/shi9x5
```

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by dordsor21** [comment]
That's how it's supposed to work. Just create a schematic with the correct biome.

**Comment by Lusteroth** [comment]
I created a new world without a schematic. So the plot biome and road biome is "forest". After using /p createroadschematic the biome of the new roads is "ocean" - not "forest". How is it possible to create a schematic with the correct biome?

**Comment by dordsor21** [comment]
That's a separate issue then, please open a new issue regarding the schematic save

**Comment by Lusteroth** [comment]
Why it's a separate issue? The used biome of the road is still wrong

**Comment by dordsor21** [comment]
Because it's correct to the schematic.... It's the schematic save that's the issue. I'm locking this so you don't try to argue further.
