### ISSUE TITLE
Staff member can't see own plot chat message (chatspy)

### ISSUE THREAD

**Issue by x1p** [IntellectualSites/PlotSquared#2833]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):

**/plot debugpaste:** 
https://athion.net/ISPaster/paste/view/7d50cee53cd145d3887dae7d1ac4f522

### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge
- [] NukkitX

### PlotSquared version:

```
[P2] >> PlotSquared (Version: PlotSquared-5.11.2)
[P2] >> Authors: Citymonstret & Empire92 & MattBDev & dordsor21 & NotMyFault & SirYwell
[P2] >> Wiki: https://wiki.intellectualsites.com/plotsquared/home
[P2] >> Premium: false
```

### Minecraft Version:
**Select one**

- [X] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft 1.12.2
- [] Minecraft 1.11.2
- [] Minecraft 1.10.2
- [] Minecraft 1.9.4
- [] Minecraft 1.8.8
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:
- [] Minecraft Sponge *specify version*:

### Server build info: 

```
Purpur version git-Purpur-578 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [X] WorldEdit version: 7.1.0 (stable)

### Description of the problem:

When staff member has `chatspy` turned on, he cannot see his own `plot chat` message.
When staff member has `chatspy` turned off, he can see his own `plot chat` message again.

### How to replicate:

Players use plot chat. Works fine.
Staff member has chatspy on. Staff can see all chats.
Staff members talks back in chat but chat is not visible for staff. 
Player on this plot sees message from staff correctly.
Staff member turns off chatspy. Talks in chat and chat is visible for both staff member as well as players.

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.
Reproduced on test server.

### Other plugins being used on the server:

Plugins (22): BungeeGuard, ChestShop, CMI, CMIPaperLib, LuckPerms, MineResetLite, NightVision*, Panilla, PlaceholderAPI, PlotSquared, PlugMan, ProtocolLib, spark, TradePlus, Vault, ViewDistanceTweaks, VillagerOptimiser, WorldBorder, WorldEdit, WorldEditSUI, WorldGuard, WorldGuardExtraFlags

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by N0tMyFaultOG** [comment]
That is intended, why would they need to see their message twice? There is no reason for that.

**Comment by x1p** [comment]
Normally you can see your own message.
They don't see their own message. Not once, not twice. Just nothing.
Like typing on a dead keyboard.

**Comment by N0tMyFaultOG** [comment]
> Normally you can see your own message.
> They don't see their own message. Not once, not twice. Just nothing.
> Like typing on a dead keyboard.

Yeah, that was changed last version because the previous state was ridiculous stupid.

**Comment by x1p** [comment]
Call me stupid, but I like to see what I just typed. That's normal chat behavior for any player.

**Comment by Sauilitired** [comment]
![img](https://i.imgur.com/PTdF6q7.png)

I can see my own chat messages, and I don't see my own message using ChatSpy, so it works like intended. 

I cannot reproduce the issue.

**Comment by x1p** [comment]
I don't see the logic of typing blind into a black hole.
I'll explain it to a word blindness owner.
Thanks tho for investigating. I was convinced I had a real bug. Otherwise I wouldn't have filed this issue cuz I'm not premium (yet).
