### ISSUE TITLE
Flags missing after updating P2

### ISSUE THREAD

**Issue by Lusteroth** [IntellectualSites/PlotSquared#2838]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):
worlds.yml: https://pastebin.com/kBNZzkD3
settings.yml: https://pastebin.com/BVsreabj

**/plot debugpaste:** 

### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge
- [] NukkitX

### PlotSquared version:

```
PlotSquared (Version: PlotSquared-5.11.2)
```

### Minecraft Version:
**Select one**

- [X] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft 1.12.2
- [] Minecraft 1.11.2
- [] Minecraft 1.10.2
- [] Minecraft 1.9.4
- [] Minecraft 1.8.8
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:
- [] Minecraft Sponge *specify version*:

### Server build info: 

```
This server is running Paper version git-Paper-284 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [X] WorldEdit version: Bukkit-Official(7.1.0;8e55131)

### Description of the problem:

There's an issue with flags while updating PlotSquared v4 to v5. All "old" flags of a plot - which were set in P2 v4 - are gone after switching to v5; the flags are deleted. 
### How to replicate:

Claim a plot and set a flag (v4) -> switch to PlotSquared v5 -> check if the flag is still there
## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by RedstoneFuture** [comment]
Which flags do you used for this test?

**Comment by Lusteroth** [comment]
Flags like redstone, hide-info, ice-melt, snow-melt and so on - all flags are gone after switching to v5

**Comment by RedstoneFuture** [comment]
moved to: https://issues.intellectualsites.com/issue/PS-6
