### ISSUE TITLE
Plot Errors

### ISSUE THREAD

**Issue by CatsCraft** [IntellectualSites/PlotSquared#2839]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):

**/plot debugpaste: https://athion.net/ISPaster/paste/view/ddc55b5310dc420796531198e8754253** 

### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge
- [] NukkitX

### PlotSquared version:

```
>....=>.... [20:55:38 INFO]: [P2] >> PlotSquared (Version: PlotSquared-5.11.1-Premium)
>.... [20:55:38 INFO]: [P2] >> Authors: Citymonstret & Empire92 & MattBDev & dordsor21 & NotMyFault & SirYwell
>.... [20:55:38 INFO]: [P2] >> Wiki: https://wiki.intellectualsites.com/plotsquared/home
>.... [20:55:38 INFO]: [P2] >> Premium: true
```

### Minecraft Version:
**Select one**

- [X] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft 1.12.2
- [] Minecraft 1.11.2
- [] Minecraft 1.10.2
- [] Minecraft 1.9.4
- [] Minecraft 1.8.8
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:
- [] Minecraft Sponge *specify version*:

### Server build info: 

```
>....=>.... [20:56:14 INFO]: This server is running Paper version git-Paper-193 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
>.... [20:56:14 INFO]: Checking version, please wait...
>.... [20:56:15 INFO]: You are 91 version(s) behind
```

### WorldEdit/FAWE versions:

- [] FAWE version: >....=>.... [20:57:57 INFO]: FastAsyncWorldEdit-235 created by Empire92
>.... [20:57:57 INFO]: FAWE version:
- Date May 14, 2020 12:00:00 AM
- Commit fa41ee3b
- Build 235
- Platform Bukkit
>.... [20:57:57 INFO]: Wiki: https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki
>.... [20:57:57 INFO]: ------------------ Platforms ------------------
* Bukkit-Official(1.15-235;5be11c5)
>.... [20:57:57 INFO]: ---------------- Capabilities ----------------
GAME_HOOKS: Bukkit-Official
CONFIGURATION: Bukkit-Official
USER_COMMANDS: Bukkit-Official
PERMISSIONS: Bukkit-Official
WORLDEDIT_CUI: Bukkit-Official
WORLD_EDITING: Bukkit-Official

- [] WorldEdit version: 

## Additional Information: A little over a week before this error started, my dev edited the storage.db. He removed a duplicated name from the database since there was a plot that listed a player twice under the trust and add sections. This duplicated name resulted in the player not having access to the trust permissions on the plot. I'm not sure if this has anything to do with the error but I figured I'd mention this just in case. 
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by RedstoneFuture** [comment]
moved to: https://issues.intellectualsites.com/issue/PS-10
