### ISSUE TITLE
The crops protected on my owned plot and trample not work

### ISSUE THREAD

**Issue by andris155** [IntellectualSites/PlotSquared#2840]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):

**/plot debugpaste:** https://athion.net/ISPaster/paste/view/072df45c6d0b4be293d1e146d7acee1f

### Server type:
**Select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge
- [] NukkitX

### PlotSquared version:

```
[20:03:47 INFO]: [P2] >> PlotSquared (Version: PlotSquared-5.11.1-Premium)
[20:03:47 INFO]: [P2] >> Authors: Citymonstret & Empire92 & MattBDev & dordsor21 & NotMyFault & SirYwell
[20:03:47 INFO]: [P2] >> Wiki: https://wiki.intellectualsites.com/plotsquared/home
[20:03:47 INFO]: [P2] >> Premium: true
```

### Minecraft Version:
**Select one**

- [x] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft 1.12.2
- [] Minecraft 1.11.2
- [] Minecraft 1.10.2
- [] Minecraft 1.9.4
- [] Minecraft 1.8.8
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:
- [] Minecraft Sponge *specify version*:

### Server build info: 

```
This server is running Paper version git-Paper-260 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [x] WorldEdit version: WorldEdit version 7.1.0-SNAPSHOT;4822-a27ade5

### Description of the problem:

The crops protected on my owned plot and trample not work.

### How to replicate:

1. Place or create farmland with hoe on my owned plot.
2. Try jumping on the farmland.
3. The farmland protected. Trample not work.

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Other plugins being used on the server:

Plugins (12): CS-CoreLib, Essentials, EssentialsChat, LuckPerms, Multiverse-Core, PlotSquared, PlugMan, ProtocolLib, Slimefun, Vault, WorldEdit, WorldGuard

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by RedstoneFuture** [comment]
moved to: https://issues.intellectualsites.com/issue/PS-9
