### ISSUE TITLE
Snow Golems do not leave snow trails

### ISSUE THREAD

**Issue by c0wg0d** [IntellectualSites/PlotSquared#2849]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server config info (/plot debugpaste / file paste links):

**/plot debugpaste:** 

https://athion.net/ISPaster/paste/view/946afa7871c44f62adf8e124c28ba5e0

### Server type:
**Select one**

- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge
- [] NukkitX

### PlotSquared version:

```
[13:49:28 INFO]: [Plot] >> PlotSquared (Version: PlotSquared-5.11.1-Premium)
[13:49:28 INFO]: [Plot] >> Authors: Citymonstret & Empire92 & MattBDev & dordsor21 & NotMyFault & SirYwell
[13:49:28 INFO]: [Plot] >> Wiki: https://wiki.intellectualsites.com/plotsquared/home
[13:49:28 INFO]: [Plot] >> Premium: true
```

### Minecraft Version:
**Select one**

- [X] Minecraft 1.15.2
- [] Minecraft 1.14.4
- [] Minecraft 1.13.2
- [] Minecraft 1.12.2
- [] Minecraft 1.11.2
- [] Minecraft 1.10.2
- [] Minecraft 1.9.4
- [] Minecraft 1.8.8
- [] Minecraft Java Edition *other versions, please specify*:
- [] Minecraft Bedrock Edition *specify version*:
- [] Minecraft Sponge *specify version*:

### Server build info: 

```
This server is running Paper version git-Paper-264 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
```

### WorldEdit/FAWE versions:

- [] FAWE version:
- [X] WorldEdit version:  Bukkit-Official(7.1.0;8e55131)

### How to replicate:

/plot biome snowy_taiga

spawn snow golem on plot

/plot flag set snow-form true

If it's snowing, the snow will collect on the plot, but the snow golem does not leave snow trails as expected.

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by RedstoneFuture** [comment]
moved to: https://issues.intellectualsites.com/issue/PS-4
