### ISSUE TITLE
Map generates over roads

### ISSUE THREAD

**Issue by kangarko** [IntellectualSites/PlotSquared#293]
Hello,

the road generation is almost perfect, but I notices sometimes the terrain generates over the road at height y=80.
https://i.imgur.com/mboptnW.jpg

**Comment by boy0001** [comment]
I'll have the generator place air if it has a null section rather than skip

**Comment by EvilOlaf** [comment]
Hm somehow I like that. The only issue is that without merging the user would be unable to build on the road strip....

Make it toggleable and call it a feature :D

**Comment by boy0001** [comment]
Are you considering having a world with underground tunnels?

**Comment by EvilOlaf** [comment]
I probably not but we don't know what in future will happen :P

Maybe other people like it too.
Give very low priority.

**Comment by boy0001** [comment]
Okay. I created a new label just for you :P

**Comment by EvilOlaf** [comment]
Yes, my own label xD

**Comment by kangarko** [comment]
Allright I did not clearly understand if you are going to fix it or make it toogleable?

**Comment by EvilOlaf** [comment]
It is fixed for now but in future this may become a feature :).
