### ISSUE TITLE
Forcegamemode option

### ISSUE THREAD

**Issue by david160596** [IntellectualSites/PlotSquared#2955]
Hello PS team.

Congratulations on your great work with the plugin.

I've been checking the flags and I don't think there are any for what I'm looking for.

I would like to force the gamemode and not being able to change it while on the plot. That is, when you enter a plot the gamemode is changed with the flag guest-gamemode or gamemode, but you cannot return to the gamemode you had while you are in the plot.

It would be a great help. I hope you take me into account. Thanks in advance.

**Checklist**:

- [X] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [X] I made sure my suggestion does not exist yet [(Check the wiki)](https://wiki.intellectualsites.com/plotsquared/home)
- [X] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by NotMyFault** [comment]
Changing the gamemode requires the usage of commands. You can disallow your commands to change the gamemode via a global `deny-cmds` flag.
