### ISSUE TITLE
Wrap world border around furthest plot + 1

### ISSUE THREAD

**Issue by MCAlagaesia** [IntellectualSites/PlotSquared#2962]
**PlotSquared Feature Suggestion:**
Currently, the world border wraps around the furthest plot. Players who own plots on the border are unable to "take a step back" and look at their plot from a distance because they can't fly beyond the border.

A solution to this problem is to wrap the border around the furthest plot, plus 1, allowing unobstructed movement around the edge of the entire world.

**How should it be implemented?**
In each direction, the world border should wrap around the furthest plot + 1.
The outermost ring of plots should be unclaimable* as in the current system. This prevents users from expanding the world border arbitrarily by abusing this change. The only difference should be that users are now able to fly a short distance beyond the world border.

**Additional context**
\* As an additional feature, the outermost ring of "unclaimable" plots could be made claimable by users with a certain admin permission. This allows the creation of merged/megaplots at the world border, which was not possible before.

**Checklist**:

- [X] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [X] I made sure my suggestion does not exist yet [(Check the wiki)](https://wiki.intellectualsites.com/plotsquared/home)
- [X] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by dordsor21** [comment]
Once merged and the update released, this will be `<world>.world.extra_border` in worlds.yml
