### ISSUE TITLE
Projectile usage in the whole world

### ISSUE THREAD

**Issue by unholymac** [IntellectualSites/PlotSquared#2965]
**PlotSquared Feature Suggestion:**
Please add a option to use misc projectiles like tridents/ender pearls ect... in the plots world!  Since when players throw a trident in the plot world it gets deleted

**How should it be implemented?**
either by default or as a option in the config

**Checklist**:

- [x] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [x] I made sure my suggestion does not exist yet [(Check the wiki)](https://wiki.intellectualsites.com/plotsquared/home)
- [x] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by RedstoneFuture** [comment]
https://github.com/IntellectualSites/PlotSquared/pull/3581
