### ISSUE TITLE
Improvement / additional feature to auto command

### ISSUE THREAD

**Issue by BotteledCacti** [IntellectualSites/PlotSquared#2974]
**PlotSquared Feature Suggestion:**

On my server I grant players permissions for additional plots as they "level up" (Up to 4 max). A problem I have is that often when they get access to claim another plot (from 1 to 2 plots), the neighboring plots are all claimed. I would love a command where a player moves their current plot (or merged plots) to the closest free plot where a neighboring one is available as well, and automatically merges them together. I've tried making this "manually" countless times with other plugins, commandblocks etc, but I can't get it to work. This is my last resort for this problem, and I feel bad for asking for it. I believe other servers would appreciate a feature like this if they knew it existed!

**Additional context**

**Checklist**:

- [X] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [X] I made sure my suggestion does not exist yet [(Check the wiki)](https://github.com/IntellectualSites/PlotSquared/wiki)
- [X] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by NotMyFault** [comment]
`/plot auto` claims the closest free plot. Moving plots is available under administrative commands and will not be added to player commands in any way.
