### ISSUE TITLE
flag for Lectern Permissions

### ISSUE THREAD

**Issue by macaronianddev** [IntellectualSites/PlotSquared#2980]
**PlotSquared Feature Suggestion:**

Lectern permissions should be changed so that displays can be made more easily without people having to be added/trusted to plots, while not being able to take books from the lectern when reading.
**How should it be implemented?**

I think that everyone should be able to interact with lecterns in a reading fashion, so that they can read the book that is on the lectern. However, they should only be able to take the book from the lectern if they are added to the plot. I don't exactly know if this is possible, but it's just something that would be useful for player creations and museums and such.
**Additional context**

**Checklist**:

- [x] I made sure there are no duplicates of my suggestion [(Use search)](https://github.com/IntellectualSites/PlotSquaredSuggestions/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+)
- [x] I made sure my suggestion does not exist yet [(Check the wiki)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/wiki)
- [x] I made sure my suggestion is useful for the majority of PlotSquared users

**Comment by NotMyFault** [comment]
Added in https://github.com/IntellectualSites/PlotSquared/commit/0341111f8f9b01388f0ac938a5892cc07f8030f6
