### ISSUE TITLE
Respect org.bukkit.entity.Player#canSee() in Plot#isAdded()

### ISSUE THREAD

**Issue by zombachu** [IntellectualSites/PlotSquared#2985]
At the moment, various functionality in PlotSquared can expose players set as vanished from other plugins due to not checking the result of Player#canSee().

**Comment by NotMyFault** [comment]
> At the moment, various functionality in PlotSquared can expose players set as vanished from other plugins due to not checking the result of Player#canSee().

If this is still somewhat of up to date, if so, do you mind listing the cases where this happens?
Last time I checked, this was covered in `PlotPlayer#canSee()`
