### ISSUE TITLE
storage: mysql: 172.17.0.1 being changed to 172.18.0.5

### ISSUE THREAD

**Issue by TauCubed** [IntellectualSites/PlotSquared#3000]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Hey there, we're running our server in docker container(s) thus we need to use dockers internal host IP to access the database.

That IP being `172.17.0.1`

However when this is used in the config the plugin prints the following stacktrace:
https://pastebin.com/1p6MdhcM

MYSQL Config:
`https://pastebin.com/Cv1D3Quq`

This indicates that it ignored the IP in the config for some reason. (Yes I've tried using the machines external IP to no prevail (same thing happens))

### To Reproduce

1. Create docker container for the server
2. Ensure your network configs have the bridge for 172.17.0.1
3. Install some mysql server.
4. Spinup a server running plotsquared on the docker container.
5. Ensure mysql server & user allows connections from the required IP's 
6. Change the storage.yml to use MySQL and set the IP to 172.17.0.1
7. Restart the server

### Expected behaviour

The IP in the config to be the IP the plugin uses.

### Error log (if applicable)

https://pastebin.com/1p6MdhcM

### Plot Debugpaste

command will not execute: Plugin Not Enabled

### PlotSquared Version

5.13.12

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by TauCubed** [comment]
got it to work by hardcoding the connection string into MySQL.java
`    @Override public Connection forceConnection() throws SQLException {
        this.connection = DriverManager.getConnection("jdbc:mysql://"+"172.17.0.1:3306/creative_plots", "external", "");
        return this.connection;
    }`

I'll do some more fooling around later & see if I can be of better help later.

**Comment by AeSix** [comment]
https://cloud.google.com/sql/docs/sqlserver/configure-private-ip#private_services_access

not sure if you're using gcloud or if this applies to all of docker. Good
place to start.

If possible rerun your test outside of docker.

**Comment by TauCubed** [comment]
Solved. It was a password encoding issue with YAML.
