### ISSUE TITLE
With set 'use' flag players can place liquids despite restriction

### ISSUE THREAD

**Issue by ByteExceptionM** [IntellectualSites/PlotSquared#3001]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Our plots have the USE flag set by default for signs, so players can interact with them. Despite the fact that they are not trusted or added, they can then place liquids such as water and lava while sneaking.

### To Reproduce

1. Set use flag for example for 'oak_sign'
2. Get a bucket of water or lava 
3. Sneak and right click on the sign.

### Expected behaviour

Actually nothing should happen here because the players are not trusted and not added

### Screenshots / Videos

https://user-images.githubusercontent.com/47250043/116387359-0700ac00-a81b-11eb-9acf-bd29fdf21ace.mp4

### Plot Debugpaste

http://athion.net/ISPaster/paste/view/babfe2f9730b47dfb406e936c8c26b19

### PlotSquared Version

PlotSquared-5.13.12

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
That is the correct behavior. The `use` flag allows the interaction with the material listed. E.g. if you set the the use flag with `oak_sign`, all interaction, at oak signs will be allowed.
