### ISSUE TITLE
Auto tab

### ISSUE THREAD

**Issue by Shucai99** [IntellectualSites/PlotSquared#3003]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

how i can  give user Permissions to auto  tab plot visit  Username and my second problem i cant more drop items on  my plot  world

### To Reproduce

i look  every perm and my second problem  ist i only edit some settings 

### Expected behaviour

i  wan to fixit

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/53802813a5724c87a44c0956f31d6095

### PlotSquared Version

5.13.11

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
For support and questions please use our discord server: https://discord.gg/intellectualsites
