### ISSUE TITLE
Problem deleting plots with unknown seen users

### ISSUE THREAD

**Issue by Espantonius** [IntellectualSites/PlotSquared#3004]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

When there is no user information, they don't delete plots that expire.

I have set up auto-remove but it doesn't work.
It seems that since there is no user date when it expires, it never deletes them.

If the user information is deleted before the plot, the last connection appears as "unknown".

When configuring a time to delete it seems that being "unknown" it never deletes them. 

### To Reproduce

1. Claim a plot.
2. Delete user information before it expires in plotsquared.
3. When the user information is displayed, it appears "seen: unknown" and never removes it. 

### Expected behaviour

As it doesn't have an expiration date or is "unknown", i expected the plots to be deleted.

### Screenshots / Videos

In the following screenshot you can see (On the left) a user with his user data deleted and (On the right) the other with the last visit date: https://prnt.sc/12fboxu

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/fcda7c08d5674374860ebe16328ca469

### PlotSquared Version

PlotSquared version 5.13.11

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

I use a database to store the plots. The data that i mention that i delete is that of the world itself.
Files like playerdata, data (from the world) or essentials (plugins).

**Comment by NotMyFault** [comment]
Let PlotSquared handle the expiration. If you mess with its data don't be surprised if it doesn't work.

**Comment by Espantonius** [comment]
I think it is not so difficult to add an option in the code to check if there is a date or not and delete it, but okay...

**Comment by Espantonius** [comment]
> 
> 
> Let PlotSquared handle the expiration. If you mess with its data don't be surprised if it doesn't work.

Are you sure you have read the report correctly?
Does Plotsquared depend on other plugins to handle information?

**Comment by NotMyFault** [comment]
> 2. Delete user information before it expires in plotsquared.


I am sure I can read, yes.
