### ISSUE TITLE
Setting empty string in messages produces empty line in the chat

### ISSUE THREAD

**Issue by nikitushu2** [IntellectualSites/PlotSquared#3005]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

In /plugins/PlotSquared/translations/PlotSquared.use_THIS.yml I set event_denied to '' to disable the message (pic attached).

Instead of disabling it completely, p2 creates an empty line instead (pic attached).

### To Reproduce

1. In PlotSquared.use_THIS.yml set event_denied to ''.
2. Cause any situation where this message would appear.
(In my case I was using a PlotClearAddon plugin, that produced "Canceled by external plugin" message)

### Expected behaviour

The message should have been disabled like it gets disabled when you set no_permission to '' (in the same PlotSquared.use_THIS.yml). In this case, for some reason, p2 correctly disables the message and does not create an empty line in the chat.

### Screenshots / Videos

![Montserrat - Google Sheets — Mozilla Firefox 04_05_2021 10 23 52](https://user-images.githubusercontent.com/32280863/116972422-a7dfe300-acc3-11eb-94b3-f5ce4171b909.png)
![Minecraft_ 1 16 5 - Multiplayer (3rd-party Server) 04_05_2021 10 22 18](https://user-images.githubusercontent.com/32280863/116972424-a8787980-acc3-11eb-8914-48db816d9a21.png)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/01b6ba331aaf4f7c9219cd161459f5a7

### PlotSquared Version

Plotsquared-Bukkit-5.3.11-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
That has been taken care of with v6.

**Comment by nikitushu2** [comment]
To not create a separate ticket, does v6 fix the breaking of p2 when hex colors are used in the messages?

**Comment by NotMyFault** [comment]
> To not create a separate ticket, does v6 fix the breaking of p2 when hex colors are used in the messages?

v6 uses a complete different, platform agnostic caption system capable to offer more control in regards of styling, color grading or any other kind of text decorations.
