### ISSUE TITLE
Tool tree can bypass region restrictions

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/PlotSquared#3009]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

I'm creating this issue on the plotsquared page instead of worldledit because I am personally not really familiar with how PlotSquared uses the worldedit api, if this is indeed a worldedit api problem it would be better if someone with more knowledge about the code would be able to forward this issue, that would be greatly appreciated.

When using `/tool tree` on a plot you are not added to it prevents you from using the tool which is correct:
![2021-05-09_15 13 00](https://user-images.githubusercontent.com/10485646/117575336-4069cf00-b0d9-11eb-9eb5-772bdd7a2672.png)

But if you hold down right click on a block and then move your mouse to the next block it will place the tree:
![2021-05-09_15 13 12](https://user-images.githubusercontent.com/10485646/117575369-5e373400-b0d9-11eb-8ff8-49c2bbe0b2e6.png)

This is problematic because it allows users to place trees in plots they do not own.

### To Reproduce

1. Do /tool tree
2. Hold right click and move your mouse to the next block

### Expected behaviour

You should not be able to use tool tree on plots you are not added to.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/9a862441a77344b4b99ee22f0887a808

### PlotSquared Version

PlotSquared-Bukkit-5.13.11-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by Anonymio** [comment]
Hello
Same problem with /br forest sphere oak
- /br forest sphere oak
- use close the road/edge of the plot
- trees are generated out of the plot (branches and leaves that expands)
Good luck

**Comment by dordsor21** [comment]
This is fixed in latest FAWE builds. It is not possible for P2 to do anything about it with normal WE
