### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by Shucai99** [IntellectualSites/PlotSquared#3012]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

hello i got and problem my ist a plot like copy it https://i.imgur.com/betPDOh.png https://i.imgur.com/gN6Rppu.png and do every time a sing with  the name etc how i fixt dat?
https://i.imgur.com/YfgCTUH.png

### To Reproduce

hello i got and problem my ist a plot like copy it https://i.imgur.com/betPDOh.png https://i.imgur.com/gN6Rppu.png and do every time a sing with  the name etc how i fixt dat?
https://i.imgur.com/YfgCTUH.png

### Expected behaviour

all new plots have like have from a  user but eh has a it copy it how i can fixt it?

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/f9ef3523dc7d4af6ac5970fe48bb0ffb

### PlotSquared Version

5.13.11

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
![](https://i.imgur.com/kOvBbjy.png)
That version does not exist. Grab the newest version from https://www.spigotmc.org/resources/77506/ and you are welcome to reopen the issue providing the proper information.

**Comment by Shucai99** [comment]
i  got 5 5.13.11 exisit wtf? https://i.imgur.com/h68ZAgc.png
