### ISSUE TITLE
Shulker boxes don't keep inventory when using plot move

### ISSUE THREAD

**Issue by DuckyProgrammer** [IntellectualSites/PlotSquared#3015]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

When moving a plot with the command /plot move, the inventory of shulker boxes are cleared.

### To Reproduce

Claim a plot
Place down a shulker box and put items into it
Use /plot move and move the plot to any other plot
Shulker box is empty

### Expected behaviour

The items remain in the shulker box

### Screenshots / Videos

https://www.youtube.com/watch?v=DDBz-yvRxz4

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/e4c4a08d67bc44819522d2a69b0ba337

### PlotSquared Version

5.13.12

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

It's on a Minehut server, so I'm not sure if that will affect anything with this bug report.

**Comment by NotMyFault** [comment]
Likely related to https://github.com/IntellectualSites/PlotSquared/issues/3030

**Comment by OneLiteFeather** [comment]
Can't reproduce it anymore with v6.11.1, it works as intended with all the items in that moved shulker box.
![grafik](https://user-images.githubusercontent.com/77929075/233807056-5972b97e-c2fc-4548-9b7e-2f295383c060.png)
Moved the plot with a shulker in it containing the items I put into.
The result:
![grafik](https://user-images.githubusercontent.com/77929075/233807096-819e995c-5bf1-4409-a66a-12c506528b3a.png)

Not 100% sure if there is an edge case, but I tried it twice in different directions
