### ISSUE TITLE
`/plot reload` doesn't take changes from worlds.yml into consideration and reverts them to the default from last startup

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/PlotSquared#3017]

**Comment by SirYwell** [comment]
Works for me

**Comment by NotMyFault** [comment]
> Works for me


https://user-images.githubusercontent.com/13383509/121162864-98b5fd00-c84e-11eb-892d-7f7cc8bfb84a.mp4

**Comment by SirYwell** [comment]
Uh lol not sure what I did before

**Comment by NotMyFault** [comment]
Fixed in https://github.com/IntellectualSites/PlotSquared/commit/66e12e2a0ca2e56a353ac94913291fe25bb42796
