### ISSUE TITLE
Many commands don't get initialized if Nashorn engine is missing (Java 16 issue)

### ISSUE THREAD

**Issue by mindw0rm** [IntellectualSites/PlotSquared#3031]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

As you might be aware, [Paper will soon demand Java 16](https://papermc.io/forums/t/java-16-mc-1-17-and-paper/5615), so we are already testing for it. 

Unfortunately the long deprecated Nashorn engine is no longer present in Java 16, and this leads to many commands (all after DebugExec in https://github.com/IntellectualSites/PlotSquared/blob/v5/Core/src/main/java/com/plotsquared/core/command/MainCommand.java#L110) not being initialized, since the handling of the missing engine is rather poor, see https://github.com/IntellectualSites/PlotSquared/blob/v5/Core/src/main/java/com/plotsquared/core/command/DebugExec.java#L129. 
Namely, engine is not checked != null before it is used (the check, and the creation of an alternate engine is done later, when it is already too late). Also, only ScriptExceptions are catched, but not the NullPointerException that is happening.
That one is catched in https://github.com/IntellectualSites/PlotSquared/blob/v5/Core/src/main/java/com/plotsquared/core/PlotSquared.java#L310, where a message regarding an incompatible WorldEdit version is shown, _but only if debug is enabled!_ If debug is false (which is the default), you are not made aware that many commands won't work at all. Also, the message is completely wrong. 

I am aware that in 2018 you wrote that PlotSquared is developed for Java 8 only (#2130), but some time has passed since then, and if you still stick to it, PlotSqaured won't be compatible with Paper as soon as Minecraft 1.17 is released. 

### To Reproduce

1. start Paper with Java 16
2. join the server
3. go on your plot and run one of the missing commands, e.g. `/p middle` or `/p alias`

### Expected behaviour

I would expect that a missing engine would only disable the scripting engine, and not that many commands won't work without any error message during startup. 

In-game you get the error message "That is not a valid subcommand".

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/b22b5f91ab5044e0ae871ccdc0911aa7

### PlotSquared Version

5.13.12 (v5 branch at https://github.com/IntellectualSites/PlotSquared/commit/5cdb7e76fd44776aea4ffe65c721bf9c72f46078)

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
That has been addressed on our [discord server](https://discord.gg/intellectualsites) -> `#announcements`
