### ISSUE TITLE
Burning player can decrease water level of cauldron by extinguishing themselves with it without having interaction permissions

### ISSUE THREAD

**Issue by ThisIsIPat** [IntellectualSites/PlotSquared#3034]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

If a player is on fire, it may jump into a cauldron on any plot, specifically the ones it doesn't own or is trusted on, and modify its water level by extinguishing themselves

### To Reproduce

Prerequisites: Two players

1. Player A claims a plot
2. Player A places a cauldron
3. Player A fills the cauldron with water
(3.5) Player A does NOT trust Player B
4. Player B sets itself on fire
5. Player B jumps into the cauldron filled with water on Player As plot

### Expected behaviour

The cauldrons water level does not change as long as the player doesn't have permissions to interact with the plot.
It may or may not extinguish the fire on the player.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/0c59391058b9403a94b320c4db3f95f1

### PlotSquared Version

PlotSquared-6.0.0-SNAPSHOT (Private Fork, bug reproducible in Vanilla)

### Checklist

- [X] I have included a Plot debugpaste.
- [ ] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Fixed in https://github.com/IntellectualSites/PlotSquared/commit/7c4a85325c6781cce503c6f7a67b40dbd6b3fd94
