### ISSUE TITLE
Aggregate Javadocs

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/PlotSquared#3037]
Currently we're building javadocs per-module stored in `docs/javadoc/$project.name`, however, for hosted javadocs we should preferably aggregate them during generation like we do for v5, allowing you to browse javadocs for all modules not just one:
https://github.com/IntellectualSites/PlotSquared/blob/5cdb7e76fd44776aea4ffe65c721bf9c72f46078/build.gradle#L137-L154

**Comment by NotMyFault** [comment]
Edit: It appears this task vanished when merging https://github.com/IntellectualSites/PlotSquared/pull/2922

**Comment by Proximyst** [comment]
this is stupid and I discourage it

/closed

in all seriousness, assign me and I'll have a look tomorrow

**Comment by NotMyFault** [comment]
Added in https://github.com/IntellectualSites/PlotSquared/commit/a6b3e97cda29dd42e1395d7cb23c952b66103241
