### ISSUE TITLE
Loose Trident on Plot

### ISSUE THREAD

**Issue by supermem99** [IntellectualSites/PlotSquared#3038]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

My Users loses their trident if they throw it outside their plots

### To Reproduce

1. Go to your Plots with a enchanted loyality trident
2. Throw it from your plot outside the plot.
3. You dont get it back
4. (if you get it back, try to go outside your plot when you have thrown it.)

### Expected behaviour

If i throw my trident, i should get it back everywhere on Plots.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/ea221d40c724458f8a897bbd0dba279e

### PlotSquared Version

5.13.11-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

Yes, i wanted to ask you if this version of plotsquared will be updated anymore.
The Issues were fixed very slowly (NoFront)
Example: The Bee Bug or Animals despawn on Plots

+ Fireworks dont works outside plots on roads

**Comment by NotMyFault** [comment]
Superseded by https://github.com/IntellectualSites/PlotSquared/issues/3038
