### ISSUE TITLE
Endcrystal does not damage blocks 

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquared#3039]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

**Copy of https://issues.intellectualsites.com/issue/PS-112 by DevJoey**

If I enable explosion (p flag set explosion true) end crystals does not make damage.

EXPLOSION = true and PVE = true

- I get health damage
- but no block-break
- no error or warn
- in different with TNT it works great

### To Reproduce

- Claim a Plot
- Run /p flag set explosion true
- Place endcrystal
- Break the crystal.

### Expected behaviour

-

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/f48c4b7c86bb42f9a83e41dae14fa779

### PlotSquared Version

last tested with PS 5.13.8

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
Well it breaks the blocks on the same block height but not under the end crystal
![grafik](https://user-images.githubusercontent.com/77929075/233805579-ae505300-07a4-4876-8892-9ab131f800ad.png)
![grafik](https://user-images.githubusercontent.com/77929075/233805587-cd5a836e-9caf-42c4-9445-bea4f3bcb73c.png)

I used Plotsquared v6.11.1 and did your steps above. You may not tried to set them as I did. I get what you want - I guess, so I tried "almost vanilla", it's on a flatworld with multiverse and paper and nothing special:

![grafik](https://user-images.githubusercontent.com/77929075/233805681-faca1cd8-739e-43ce-9e4d-140a9add72d4.png)
![grafik](https://user-images.githubusercontent.com/77929075/233805695-08c4d91a-573a-49ee-b9a6-f965db406da9.png)

I wish vanilla wouldn't be that weird (singleplayer 1.19.4):
![grafik](https://user-images.githubusercontent.com/77929075/233805831-3f4db07e-1ab5-48c0-bc72-8e81e39a8706.png)
![grafik](https://user-images.githubusercontent.com/77929075/233805843-d929fede-7808-4f95-9732-c937032554cd.png)
