### ISSUE TITLE
Road schematics not working in augmented worlds

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquared#3040]
### Server Implementation

Paper

### Server Version

1.15.2

### Describe the bug

**Copy of https://issues.intellectualsites.com/issue/PS-24 by ISN**

What is the expected result?
It would be expected that it applies the road schematic to either the plot or the world depending on which command.

Please provide any additional information below.
Running PaperSpigot-313 on 1.15.2 and PlotSquared version 5.11.1. Tried with both FAWE and normal WE

Provide a screenshot if possible

### To Reproduce

- Create an augmented world with as far as I can tell any road height (specifically used 100 road height, 99 wall height)
- Create/Import a new road schematic (tried both)
- Try to apply it with either /plot debugroadregen plot or /plot regenallroads

### Expected behaviour

It resets to the default road schematic for that world either with or without the top wall block, and a whole bunch of console spam.

### Screenshots / Videos

![grafik](https://user-images.githubusercontent.com/4140635/118872583-fce93f00-b8e8-11eb-8465-d9ad5ea93f17.png)
![grafik](https://user-images.githubusercontent.com/4140635/118872559-f65ac780-b8e8-11eb-8298-c190fcea54c1.png)

### Plot Debugpaste

- 

### PlotSquared Version

PlotSquared version 5.11.1.

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Can't replicate on v6.
