### ISSUE TITLE
Alias on Plots

### ISSUE THREAD

**Issue by supermem99** [IntellectualSites/PlotSquared#3041]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

If i set a alias for my plot.
Example. 
/plots alias set Owner
It tells me.. No this Alias exists
But its not with every word. Its 50/50 percent if your alias works

### To Reproduce

1. Go to your Plots
2. /plots alias set Owner
3. "Alias exists"

### Expected behaviour

i want to have an alias for my plot

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/ea221d40c724458f8a897bbd0dba279e

### PlotSquared Version

5.13.11-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

If i use the alias placeholder in title of plots
  title_entered_plot_sub: '%alias%'
It should be show me the alias or nothing if i dont have a alias.
The number of the plots is not looking nice. "world;x;y"

**Comment by NotMyFault** [comment]
An alias cannot be the name of a player existing, afaik.
