### ISSUE TITLE
Plot schematic paste error || /plot clear command not working

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquared#3042]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

**Copy of https://issues.intellectualsites.com/issue/PS-221 by FabricSoftener** (I have the same problem!)

- On schematic paste it creates air from bottom to top.
- The /plot clear and the /plot reset commands doing nothing, the plot got not cleared.

### To Reproduce

-> https://www.youtube.com/watch?v=_Zowx3mcRPE

### Expected behaviour

-

### Screenshots / Videos

see "To Reproduce"

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/5fabfdb0a51e4f999a3c01600c5cd4a3

### PlotSquared Version

last tested with 5.13.11

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by RedstoneFuture** [comment]
In my last test the plot schematic generation works fine. But in different with "//regen" the "/p clear" and "/p delete" command the schematic position is wrong.

Maybe the following error comes from the plot-schematic load process: https://pastebin.com/Ds0S2eQA

    PS 5.13.11
    FAWE 1.16-600
    PaperMC 1.16.5



![grafik](https://user-images.githubusercontent.com/4140635/118874704-7c780d80-b8eb-11eb-9457-b52ed04064eb.png)

**Comment by RedstoneFuture** [comment]
![grafik](https://user-images.githubusercontent.com/4140635/118874882-b0ebc980-b8eb-11eb-8b41-1ffeb0dde8c7.png)

**Comment by SavranDE** [comment]
how do you paste schematics into the plots without claiming them?

**Comment by RedstoneFuture** [comment]
> 
> 
> how do you paste schematics into the plots without claiming them?

https://github.com/IntellectualSites/PlotSquared-Documentation/wiki/Schematic-Generation

**Comment by SavranDE** [comment]
> > how do you paste schematics into the plots without claiming them?
> 
> https://github.com/IntellectualSites/PlotSquared-Documentation/wiki/Schematic-Generation
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/e86305e9e6bc25fd7be41183f027bdc9a378ed2f4608bb02807aa61a4d390218/68747470733a2f2f6f70656e67726170682e6769746875626173736574732e636f6d2f326462313965626637633937343831313232343038626461383264393861376664366663396132373661303034373938633961343533373030326436356433372f496e74656c6c65637475616c53697465732f506c6f74537175617265642d446f63756d656e746174696f6e"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[IntellectualSites/PlotSquared-Documentation](https://github.com/IntellectualSites/PlotSquared-Documentation)**Contribute to IntellectualSites/PlotSquared-Documentation development by creating an account on GitHub.

Thank you very much!

**Comment by dordsor21** [comment]
This has been fixed now
