### ISSUE TITLE
Some stairs not generating correctly in the center of a road intersection 

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquared#3045]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

**Copy of https://issues.intellectualsites.com/issue/PS-92 by BitterSweet**

In the center of my pattern's road intersections I have a pillar, with two vertically opposing stairblocks on each side ( image: https://media.discordapp.net/attachments/699650993377378394/738771744546095185/2020-07-30_10.png ). When creating a road schematic and doing a road regen, these sets of stairs get generated incorrectly ( https://media.discordapp.net/attachments/699650993377378394/738771785654337667/2020-07-30_10.png ). Attempting to fix the pattern and redo making a new road pattern and regening it again results in stairs that are still broken. All surrounding stairs seem to act normally.

### To Reproduce

I've only managed to reproduce the issue on that map with that specific road. If necessary, I can upload the world somewhere (please give preferred method if necessary) or someone can join my server to test it.
But, on the same world, having the same stair blocks as shown in the first image, doing /plot createroadschematic , then /plot debugroadregen or generating new roads, the stairs would generate in that way.

### Expected behaviour

-

### Screenshots / Videos

Screenshots:
Desired/original schematic: https://media.discordapp.net/attachments/699650993377378394/738771744546095185/2020-07-30_10.png
What generates: https://media.discordapp.net/attachments/699650993377378394/738771785654337667/2020-07-30_10.png

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/70f1a0eff6354039bb11d5afab41de57

### PlotSquared Version

5.13.0

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

I'm hosting on pebblehost, was previously self-hosting, the world was previously on PlotSquared v4 but due to it not supporting stairs, glass panes, etc., I switched to V5. But the schematic was created in V5
The roads themselves are relatively complex, I had the thought that that might be related? As when I was placing the same two stair blocks in a world with the same config but without other road elements, it wasn't replicating the same results. Also, no other stairs seem to be affected.

**Comment by NotMyFault** [comment]
PlotSquared does only take two roads and one intersection into consideration when creating the road schematic, therefore non square-symmetric shapes will always look odd, tho, this looks more like an outdated WE version not saving the block state properly.
