### ISSUE TITLE
Alias as Title

### ISSUE THREAD

**Issue by supermem99** [IntellectualSites/PlotSquared#3048]
### What feature do you want to see added?

If i use the alias placeholder in title of plots
title_entered_plot_sub: '%alias%'
It should be show me the alias or nothing if i dont have a alias.
The number of the plots is not looking nice. "world;x;y"

### Are there any alternatives?

maybe a new placeholder without the number of the plot

### Anything else?

it will be great :

**Comment by NotMyFault** [comment]
That has been taken care of in v6.
