### ISSUE TITLE
(Augmented plot) plot kick does not work on flat worlds with "worlds:true"

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquared#3057]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

**Copy of https://issues.intellectualsites.com/issue/PS-220 by mikedmd**

When using the command /plot kick <player> when in a flatworld (worlds: true) controlled by PlotSquared, the player receives the message "You got kicked!" but nothing happens. Would be great if the player could be forced to return to the server spawnpoint, etc. 

### To Reproduce

- 

### Expected behaviour

-

### Error log (if applicable)

No error in latest.log.

### Plot Debugpaste

https://brew.brdv.coffee/lobuvabuva.hs

### PlotSquared Version

5.13.11

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Fixed in https://github.com/IntellectualSites/PlotSquared/commit/cc48f273c00f84205cc2042262b519127d2d0ae0
