### ISSUE TITLE
New Flag for Farms on Plot

### ISSUE THREAD

**Issue by supermem99** [IntellectualSites/PlotSquared#3061]
### What feature do you want to see added?

I wish a feature to set an maximal amount of blocks on a plot.

I have many users, which uses cactus-farms. For that it will be pretty nice if there is a flag which maximize the amount of blocks per plot. 

max-block-cap
Example: 1000 Cactus
So you can only put max. 1000 cactus on a plot

### Are there any alternatives?

If it will be not easy with some blocks (example planted wheats).. you can use the tab funktion to tab wheat-7 in example

**Comment by NotMyFault** [comment]
Tracking blocks, especially on larger plots, requires chunks to be loaded to access the data in a sane way. Not speaking of this method being very inefficient if you have 30k 501x501 plots, it would also be resource intensive.
