### ISSUE TITLE
/p h (name) doesnt work

### ISSUE THREAD

**Issue by supermem99** [IntellectualSites/PlotSquared#3062]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

If you want to visit other plots, you have to use /plot v (name). But in the alias commands file there is /plot home (name) to visit other user.

This is currently not working.

Maybe i did anything wrong?!

### To Reproduce

1. On Plotworld
2. p home (name)
3. nothing happens

### Expected behaviour

p home (name) should bring me to other players like /p visit (name)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/11ce98807cdd4b21949ebf90a448f42c

### PlotSquared Version

5.13.11-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Using `/plot home <name>` was an ancient bug now being fixed. To visit plots, use the visit command, that's its purpose.
