### ISSUE TITLE
Shift `/plot rate` GUI one slot to the left

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/PlotSquared#3063]
![](https://i.imgur.com/2kSH24f.png)

**Comment by AeSix** [comment]
can you add one of the 🛇 items to the left to remove the rating?

Also, wouldn't be bad to use number block heads instead.  Just a thought :P

**Comment by NotMyFault** [comment]
> can you add one of the 🛇 items to the left to remove the rating?
> 
> Also, wouldn't be bad to use number block heads instead. Just a thought :P

Purging ratings can be done thru `/plot rate purge`. If you have multiple rate GUIs, you'd have the item redundantly on every GUI.
Within my last commit, you can specify the blocks to use for the GUI. Default are wool blocks like before.

**Comment by AeSix** [comment]
Don't this allow multiple people to rate a plot?  If so, and if one of those people would like to remove their rating only, can that be done?

I'm sorry if my question is ignorant, I've not used the plot rating system in a long time.

**Comment by NotMyFault** [comment]
> Don't this allow multiple people to rate a plot? If so, and if one of those people would like to remove their rating only, can that be done?
> 
> I'm sorry if my question is ignorant, I've not used the plot rating system in a long time.

That is intended, multiple people can rate plots.

**Comment by AeSix** [comment]
So, what if someone wants to remove just their rating from a specific plot? 
My understanding is that the /p rate purge is all ratings for that plot?

**Comment by NotMyFault** [comment]
Individual ratings are not stored. They calculate up/downwards based on past ratings, hence removing individual ratings is not possible.

**Comment by AeSix** [comment]
ahhhh, got ya.  Thanks :)

**Comment by NotMyFault** [comment]
Fixed in https://github.com/IntellectualSites/PlotSquared/commit/5a5d1f5e620c231f5b94a088442e1be93b525295
