### ISSUE TITLE
v6 Merge and Clear Bug

### ISSUE THREAD

**Issue by zOIDAdaJulian** [IntellectualSites/PlotSquared#3065]
### Server Implementation

Tuinity

### Server Version

1.16.5

### Describe the bug

The Roads aren't generating in the right way in some situations like /p merge and /p clear.

Screens:
Merge: https://gyazo.com/a7a27e2ff9a299c43d97fcb54d509dfa
Clear: https://gyazo.com/65125b66790b699f5549daf7882a3954

### To Reproduce

Merge Bug
- Claim enough Plots (in my case 16)
- try to merge them with /p merge auto

Clear Bug
- Try to clear the "failed" Plot merges.

### Expected behaviour

The Road should generate as expected ;D

### Screenshots / Videos

Merge: https://gyazo.com/a7a27e2ff9a299c43d97fcb54d509dfa
Clear: https://gyazo.com/65125b66790b699f5549daf7882a3954

### Error log (if applicable)

No Errors in the console

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/97d12eb4f7fb4ddfba833f6ee8c15f6a

### PlotSquared Version

Plotsquared v6.0.0 Snapshot

### Checklist

- [x] I have included a Plot debugpaste.
- [x] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

If you can't reproduce it just try it a few times ;D

**Comment by NotMyFault** [comment]
Fixed in https://github.com/IntellectualSites/PlotSquared/compare/955341ff9f36c2808e358c3d3dc1211315d7ebe4...ea0342f1008db1909c40f8670adfa18a87e912f7
