### ISSUE TITLE
The use flag allows players to place liquids

### ISSUE THREAD

**Issue by Xaver106** [IntellectualSites/PlotSquared#3069]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Setting the use flag on a plot allows not trusted/added players to place lava on it or waterlock it. This can cause major damage on plots, as the water can wash away redstone or lava could burn blocks.

It only happens, when the `use` flag for the block is set on the plot.

### To Reproduce

1. Place blocks from the list above on a plot.
2. Allow to "use" the block via the *use* flag. (`/p flag add use <block name/category>`)
3. Another player (not added/trusted) can now `shift` + `right click` the block to place liquids or waterlock the block.

### Expected behaviour

Plotsquared should block this action, as placing lava or water can damage a plot (Redstone or flamable blocks)

### Screenshots / Videos

https://user-images.githubusercontent.com/46501008/119239736-420cab80-bb4b-11eb-8a7f-6069d8fec61b.mp4

***_IchbinIch_* was not added/trusted!**

The flags were:
```
Flags: use:#fence_gates,#fence_gates,#signs,#walls,#fences,note_block,#fence_gates,#trapdoors,trapped_chest,#slabs,iron_trapdoor
```

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/9662928261434b7da86e4e32d1988218

### PlotSquared Version

PlotSquared-5.13.11-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
You can set the `liquid-flow` flag to false to stop liquids from flowing. General gist is to not set the use flag to blocks you don't want to be interacted with as its explicit purpose is to be interactable with any kind of blocks.

**Comment by Xaver106** [comment]
@NotMyFault Yes it works, but you can still destroy redstone around the block.
![grafik](https://user-images.githubusercontent.com/46501008/119241108-64ef8d80-bb54-11eb-96c8-a7449a47922c.png)
I think this is generally a temporary solution. I understand why it is like that, but it is not ideal.

**Comment by RedstoneFuture** [comment]
After the last test (see screenshot) I'm not sure if it's full intended as it is. Another player (not owner/added/trusted) can destroy blocks, because it generates a water cross.
