### ISSUE TITLE
Players that are denied from a plot when they are offline can rejoin to bypass

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/PlotSquared#3070]
### Server Implementation

Tuinity

### Server Version

1.16.5

### Describe the bug

This is a bug discovered by some players that I was able to reproduce, if you have two accounts online on the same plot (One account being the plot owner, the second account being a normal user) the normal user can leave the server and then the plot owner can use /plot deny on that user. When the normal user joins the server again they will be on the plot even though they got denied from the plot while they were offline:
![2021-05-23_15 17 04](https://user-images.githubusercontent.com/10485646/119264369-c9edc680-bbda-11eb-81f4-ebc505d4bf96.png)

I'm not sure about how this could be fixed but I'm hoping someone has an idea

### To Reproduce

1. Have two accounts online on the same plot, a plot owner and a normal user
2. Log out on the normal user and have the plot owner run /plot deny on the normal user
3. Log on to the server with the normal user and you will be on the plot even though you got denied

### Expected behaviour

The player should be sent to spawn

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/3883ba7cd0764cf7bbb6202321f936ca

### PlotSquared Version

PlotSquared-Bukkit-5.13.11-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
That's how Minecraft works. You (typically) join at the same location you left a world. Them using standardized commands like `/spawn` will mitigated the situation.
