### ISSUE TITLE
`/plot alias remove` sending wrong message

### ISSUE THREAD

**Issue by Ashracx** [IntellectualSites/PlotSquared#3073]
### Server Implementation

Purpur

### Server Version

1.16.5

### Describe the bug

I can't remove Aliases from my Plot. I get the message: You are lacking the permission node: plots.alias.remove
I have thge Permission * and also if ich set the required permission it dont works.

### To Reproduce

Type /p alias remove

### Expected behaviour

I think Plotsquared should remove the Plot-Alias

### Screenshots / Videos

![alias](https://user-images.githubusercontent.com/83310351/119841222-ebfe8600-bf05-11eb-8ff8-509dd2999125.PNG)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/1dedf6792c5f4ac48a7ffe8a430c387f

### PlotSquared Version

6.0.0-Snapshot

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Fixed in https://github.com/IntellectualSites/PlotSquared/commit/dc7e6010cb6cb7cccef78bd1075a82c865aa747d.
Thanks for reporting!
