### ISSUE TITLE
Dragon eggs can be teleported onto the road

### ISSUE THREAD

**Issue by ThisIsIPat** [IntellectualSites/PlotSquared#3074]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

When interacting with a dragon egg on a plot on which the respective player has permission to interact, the dragon eggs position may reach out of permitted bounds.

The target teleport location of a dragon egg is not controlled at all (Block teleportation is being handled like liquid flow events, isLiquid() check prevents cancellation for dragon egg)

### To Reproduce

Prerequisites: Have access to a plot, don't have the ``plots.admin.interact.road`` permission

1. Place a dragon egg in your plot
2. Interact with it. If it is still is in your plot, repeat this step.
3. The egg is likely to have been teleported onto the road, perhaps a neighboring plot.

### Expected behaviour

The dragon egg does **not** get teleported out of its origins bounds

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/9ddd80f607bb4dc99e1dd728a7461fe1

### PlotSquared Version

PlotSquared-6.0.0-SNAPSHOT (Private Fork, bug reproducible in Vanilla)

### Checklist

- [X] I have included a Plot debugpaste.
- [ ] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

Pull Request in development.

**Comment by NotMyFault** [comment]
Fixed in https://github.com/IntellectualSites/PlotSquared/commit/2045a4988dd5083c9bff0f4db5cb53f3a5928c66
