### ISSUE TITLE
Dragon eggs can be left-clicked to interact with them, without trust

### ISSUE THREAD

**Issue by ThisIsIPat** [IntellectualSites/PlotSquared#3076]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Right-clicking dragon eggs triggers expected behaviour of an interact error message if the permissions aren't given to the interacting user, however, a left-click works just fine in the case of dragon eggs.

Further cases don't come to mind at the moment, this issue specifically handles dragon eggs.

### To Reproduce

Prerequisite: Player A, a plot Player A isn't trusted on, Dragon Egg on that plot

1. Player A left-clicks the dragon egg to interact with it. (Not right-click!)
2. The egg disappears. (Does not work in Creative, will simply trigger destroy attempt instead)

### Expected behaviour

Require Player A in the given example to be allowed to interact with the plot before causing the dragon egg to jump around

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/723af81dc6ee48cda72f00471fcbbaed

### PlotSquared Version

PlotSquared-6.0.0-SNAPSHOT (Private Fork, bug reproducible in Vanilla)

### Checklist

- [X] I have included a Plot debugpaste.
- [ ] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

PR for dragon eggs already exists, added a commit there. ([This one](https://github.com/IntellectualSites/PlotSquared/pull/3075))

**Comment by NotMyFault** [comment]
Fixed in https://github.com/IntellectualSites/PlotSquared/commit/2045a4988dd5083c9bff0f4db5cb53f3a5928c66
