### ISSUE TITLE
If the P2 info command （V6）

### ISSUE THREAD

**Issue by shiqutong** [IntellectualSites/PlotSquared#3082]
### What feature do you want to see added?

If the P2 info command is entered in the background, it is necessary to prompt that this command cannot be used in the background, not that you are not on the plot.

### Are there any alternatives?

If the P2 info command is entered in the background, it is necessary to prompt that this command cannot be used in the background, not that you are not on the plot.

### Anything else?

If the P2 info command is entered in the background, it is necessary to prompt that this command cannot be used in the background, not that you are not on the plot.

**Comment by shiqutong** [comment]
If the P2 info command is entered in the background, it is necessary to prompt that this command cannot be used in the background, not that you are not on the plot.

**Comment by NotMyFault** [comment]
Posting the same message 4 times in a row doesn't make it sound any better.

**Comment by shiqutong** [comment]
我只是更改了问题描述，英文表达不是太好。
