### ISSUE TITLE
PlotPlayerTeleport Event Doesn't Fire During AutoClaimPlot

### ISSUE THREAD

**Issue by ArctoranDev** [IntellectualSites/PlotSquared#3087]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

PlotPlayerTeleportEvent is triggered during the PlotClaimEvent teleportation but not the PlotAutoEvent.

### To Reproduce

1) Trigger Task on Plot Player Teleport e.g. Send Message
2) Test with /plot claim
3) Test with /plot auto

### Expected behaviour

Ideally it would fire either way.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/0e0583eb47784d6ea8ba8918363b5982

### PlotSquared Version

PlotSquared Version 5.13.12-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

N/A

**Comment by dordsor21** [comment]
Cannot replicate this issue.
Code:
```        new PlotAPI().registerListener(new Object(){
            @Subscribe
            public void onPlayerTeleport(PlayerTeleportToPlotEvent e) {
                System.out.println("aaa");
            }
        });```

**Comment by dordsor21** [comment]
No response for two weeks, assume a non-issue.
