### ISSUE TITLE
Unable to paste schematic

### ISSUE THREAD

**Issue by SheerYin** [IntellectualSites/PlotSquared#3089]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Unable to paste schematic
The template will not be pasted even if the default skyblock.template is used

### To Reproduce

execute /plot template import plot skyblock
execute /plot auto

[Render thread/INFO]: [CHAT] [P2] You successfully claimed the plot
[Render thread/INFO]: [CHAT] [P2] Failed to paste the schematic
[Render thread/INFO]: [CHAT] [P2] You have been teleported

Unable to paste schematic

### Expected behaviour

Paste schematic
Use plot to make a custom empty island
Not limited to the default skyblock.template 

### Screenshots / Videos

n

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/561902b3e1a245f39d669c7a980a0a45

### PlotSquared Version

[16:30:14 INFO]: PlotSquared version 5.13.12 [16:30:14 INFO]: Easy, yet powerful Plot World generation and management. [16:30:14 INFO]: Website: https://www.spigotmc.org/resources/77506/ [16:30:14 INFO]: Authors: Citymonstret, Empire92, MattBDev, dordsor21, NotMyFault and SirYwell

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
That can be ignored for now, I've addressed that within v6.
