### ISSUE TITLE
Round decimal values for placeholders

### ISSUE THREAD

**Issue by Skizzles** [IntellectualSites/PlotSquared#3091]
### What feature do you want to see added?

I would like if the plot rating and other decimal values were rounded using placeholders as it can display massive decimals for no real reason.

### Are there any alternatives?

Not that I am aware of, I looked through files and such for any sort of rounding or formatting changes and this is not present.

### Anything else?

![image](https://user-images.githubusercontent.com/30563757/122034792-b91e1400-cd86-11eb-9737-0c6152bcfbd4.png)

**Comment by NotMyFault** [comment]
Which placeholder is being used in the screenshot? I'm not able to return a number notated scientific.

**Comment by Skizzles** [comment]
This is the %plotsquared_currentplot_rating%

**Comment by NotMyFault** [comment]
Please query all ratings of the plot from your db.

**Comment by Skizzles** [comment]
7, 3, 3
![image](https://user-images.githubusercontent.com/30563757/122041173-862b4e80-cd8d-11eb-92f0-545e298d7bda.png)

**Comment by NotMyFault** [comment]
Oic, I only tested it with two ratings where this doesn't occur. Manually inserting more than 2 leads to the result described.

**Comment by Skizzles** [comment]
Is it possible to only display a certain amount of places after the decimal instead of rounding?

**Comment by NotMyFault** [comment]
Yes.

**Comment by Skizzles** [comment]
That would be good too

**Comment by NotMyFault** [comment]
Labeling this as low priority for now. If someone wants to add named feature, the logic can be abstracted with ease from our scientific notation rendering for plot ratings thru the info component.
