### ISSUE TITLE
Can't clear and can't make roads

### ISSUE THREAD

**Issue by MoTastisch** [IntellectualSites/PlotSquared#3093]
### Server Implementation

Paper

### Server Version

1.14.4

### Describe the bug

Cant clear plots. It gives me an error. 
Cant createroadschematics. it gives me an error
Sorry for my bad English

### To Reproduce

1. Try to clear
2. Error and the plot wont be cleared

1. Try to create a road schematic
2. Error and nothing happens
3.  try to paste 
4.  its not working

### Expected behaviour

Working without Errors

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/324d1d0b0ce94a3fbc7dd0c794f30aea

### PlotSquared Version

newest v4

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
PlotSquared v4 is unsupported.
