### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by TheosisOfficial** [IntellectualSites/PlotSquared#3097]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

I can't really describe the bug or how to replicate it, but upon one of my worlds (NOT a plot world) loading via Hyperverse, I _sometimes_ get the following exception: https://pastebin.com/u35qdBkP

### To Reproduce

N/A

### Expected behaviour

N/A

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/3ecb0cdd637945e6abca44bafd905475

### PlotSquared Version

5.13.12

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
I found nothing about this issue and it's unlikely it would happen again - it's even hard to track down what happened and can't be replicated. I close this for now. If you find something like this again, feel free to reopen it and add replication steps/log or more information if possible.
