### ISSUE TITLE
Could not pass event PlayerTeleportEvent

### ISSUE THREAD

**Issue by PikaMug** [IntellectualSites/PlotSquared#3105]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

Immediately after server startup, the following error occurs:
> 21.06 21:12:15 [Server] ERROR Could not pass event PlayerTeleportEvent to PlotSquared v6.0.1-SNAPSHOT
21.06 21:12:15 [Server] INFO com.plotsquared.core.util.PlayerManager$NoSuchPlayerException: There is no online player with UUID '67ac8a4a-45bd-20f2-b977-84fe146d1bae'

### To Reproduce

1. Build and install PlotSquared ca9e37106740d0dfb4a1bd8b71957da3b415faeb
2. Download and install Citizens2 i.e. https://ci.citizensnpcs.co/job/Citizens2/2328/
3. Start server and create a few Citizens NPCs in any world, even non-plot ones
4. Restart, after loading get one error per NPC

### Expected behaviour

The event should be ignored for NPCs.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/237a3f52467349b29c08e2af1775dd71

### PlotSquared Version

PlotSquared version 6.0.1-SNAPSHOT

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by PikaMug** [comment]
@NotMyFault Was this re-opened on accident? Issue appears to be resolved.

**Comment by SirYwell** [comment]
Yes, the mentioned issue is a different one.
