### ISSUE TITLE
Make the "pvp" flag apply to the road scope

### ISSUE THREAD

**Issue by TheosisOfficial** [IntellectualSites/PlotSquared#3111]
### What feature do you want to see added?

When the "pvp" flag is set to "true" as a road flag, it doesn't seem to do anything. It should.

### Are there any alternatives?

N/A

**Comment by dordsor21** [comment]
Please provide a debugpaste.

**Comment by TheosisOfficial** [comment]
> Please provide a debugpaste.

https://athion.net/ISPaster/paste/view/3ccd3ecceffa48b5ba593e7262cb3412

**Comment by TheosisOfficial** [comment]
Hello, it still seems to be the case that setting the "pvp" flag to `true` on the road does not allow PvP. Using 6.5.1.
