### ISSUE TITLE
ps beta not working

### ISSUE THREAD

**Issue by dragonringki** [IntellectualSites/PlotSquared#3113]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

try to use /plot setup and it gives an error
unable to create 'plot world'
ignore the background of the image. this was from pre 1.17

![unknown](https://user-images.githubusercontent.com/79207612/122957271-aeacdd00-d379-11eb-9638-01bdeebfbeaf.png)

### To Reproduce

1. add plugin
2. load plugin
3. start server
4. type /plot setup 'any option'
5. gives error

### Expected behaviour

to create plot world

### Screenshots / Videos

![unknown](https://user-images.githubusercontent.com/79207612/122957649-0c412980-d37a-11eb-8d61-0ced44972782.png)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/0d72a29964624d79b9d5be1753e26a88

### PlotSquared Version

6.0.0-BETA

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Update Paper, and paste (https://paste.gg/) your full latest.log after attempting to create a plot world.
You also have an invalid worlds.yml, you may want to address that as well.

**Comment by NotMyFault** [comment]
No response, assume no longer relevant.
