### ISSUE TITLE
Parrots stuck on shoulders

### ISSUE THREAD

**Issue by roopekoo** [IntellectualSites/PlotSquared#3114]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

When a tamed parrot hops on your shoulder, it cannot leave there. If the player jumps, the parrot(s) go invisible but still sty on the shoulders and screech. Jumping, teleportation or even death does not force these parrots to jump off the shoulders.

### To Reproduce

1. Have PlotSquared installed
2. Go to a PlotWorld
3. Tame a parrot and let it hop on your shoulder.
4. Start flying
5. The parrots disappear

### Expected behaviour

The parrots should hop off from the shoulders when the player starts flying.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/fcad0c70ea374b489890ccaa4ab542a7

### PlotSquared Version

PlotSquared version 6.0.0-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

When teleporting to non-Plot-world the parrot that was stuck on the Plot-world hops off in this another world.
The player who has the invisible parrots on the shoulders does not see the parrots but other players can.
This bug has been around since v5 and this behavior does not happen on the v4 versions. So plugin/server version/type should not affect on the reproduce-ability on this issue.

**Comment by NotMyFault** [comment]
Enable natural mob spawning in the worlds.yml.
