### ISSUE TITLE
Some plot owner are incorrect since v6

### ISSUE THREAD

**Issue by crafter23456** [IntellectualSites/PlotSquared#3117]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

For some people /p h &  /p v [ID & Name] doesnt teleport to their plot, they get teleported to another plot even if they are not owner or trusted there.

### To Reproduce

1. Upgrade from v5 to v6
2. For some plots it doesnt teleport right
3. Downgrade to v5
4. It works fine, so its an v6 problem

### Expected behaviour

/p h & /p v should teleport to the right plot.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/3a2020dab79547b6a66d811faed60f18

### PlotSquared Version

6.0.1 Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by 23Luzi23** [comment]
Yes the same problem on the 1.17. A /plot sethome on the right lot solves the problem for now.

**Comment by alekso56** [comment]
Same problem, 1.17, issue with merged plots only, 
I've tracked this issue down to https://github.com/IntellectualSites/PlotSquared/blob/72c0021306d354d11d0def00c73001c4a75c401f/Core/src/main/java/com/plotsquared/core/plot/Plot.java#L2843

if this.IsMerged return false, it works properly, if the plots are merged, they return bogus data, especially with large merged plots.

i think to recreate the issue, just walk a fair bit away from spawn so the differential gets large enough, around 1000 will do, claim a bunch of plots and merge them together. then try teleporting

relevant debug log with the plot data https://pastebin.com/raw/xPbs6cVm
