### ISSUE TITLE
can't import maven

### ISSUE THREAD

**Issue by LouisDerEchte** [IntellectualSites/PlotSquared#3118]
### Server Implementation

Spigot

### Server Version

1.16.5

### Describe the bug

i can't import the maven dependency! Bug?

### To Reproduce

Wiki, api then maven without bukkit

### Expected behaviour

Dependency 'com.plotsquared:PlotSquared-Core:6.0.1-SNAPSHOT' not found

### Plot Debugpaste

no debugpaste

### PlotSquared Version

PlotSquared v6 6.0.1-BETA

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
You want to provide some information like your pom or exceptions.

**Comment by 23Luzi23** [comment]
https://mvn.intellectualsites.com/content/repositories/snapshots/ is offline

**Comment by Score2** [comment]
I also encountered the same problem,
No matter how I try, https://mvn.intellectualsites.com/content/repositories/snapshots/ is offline.

**Comment by byquanton** [comment]
Also, for me. It looks like the Server is down
(I'm getting timeouts)

**Comment by NotMyFault** [comment]
It's back online now
