### ISSUE TITLE
Item duplication when I use /plot merge

### ISSUE THREAD

**Issue by bripalow** [IntellectualSites/PlotSquared#3120]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Hello! Yesterday, an user told me that when he used /plot merge. His inventory had duplicated and other again when he left the server or died.
Some solution for that?
Thank you

### To Reproduce

1. use /plot merge
2. left the server or died

### Expected behaviour

I believe that the glitch will be solved

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/e4a421934d174eba8b9688e44221d50a

### PlotSquared Version

4.4.495

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
PlotSquared v4 is unsupported.
