### ISSUE TITLE
6.0.3 & 1.17.0 does not load  (6.0.0 -> loads and is ok)

### ISSUE THREAD

**Issue by OnlyPW** [IntellectualSites/PlotSquared#3122]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

I switched everything to 1.17 tonight, since the first tests with 6.0.0 worked fine. Everything works until I updated to the current 6.0.3. With the version P2 does not load at all.

1.17.0 Paper
FaWe 1.17-11 and 1.17-17 tested
https://paste.gg/p/anonymous/7182cfafd446435386eafb0a1ff0f03b
""debugpaste only worked with 6.0.0, because 6.0.3 does not load""

### To Reproduce

1. 6.0.0 restart OK
2. 6.0.3 does not load

### Expected behaviour

Please check, so that the next update works again.

### Error log (if applicable)

https://paste.gg/p/anonymous/7182cfafd446435386eafb0a1ff0f03b

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/ce72b241fc434cf5b404f1183c16833f

### PlotSquared Version

6.0.3

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by dordsor21** [comment]
You've set the default locale to "de" but do not have a `messages_de.json` file present in the lang folder. Either change the lang to "en" or other file that exists, or create a translations file for de. See https://intellectualsites.crowdin.com/plotsquared for a partially completed german translation
