### ISSUE TITLE
1.16.5 Support with v6 and v4 (PaperSpigot)

### ISSUE THREAD

**Issue by ElektrodemonNl** [IntellectualSites/PlotSquared#3123]
### What feature do you want to see added?

Support 1.16 PaperSpigot would me nice.

### Are there any alternatives?

Normal spigot 1.16 is it working but not PaperMC. 

### Anything else?

Oh and I can t spawn animals on my plot. I already changed it in settings. But still doesn’t work. Does it need to be claimed?

**Comment by NotMyFault** [comment]
- There is no paperspigot but paper
- Plotsquared v6 works well with Paper 1.16.5
