### ISSUE TITLE
PlotSquared doesn't accept any Commands.

### ISSUE THREAD

**Issue by ElektrodemonNl** [IntellectualSites/PlotSquared#3129]
### What feature do you want to see added?

it installed but doesn't accept any commands. It just says nothing. 

https://user-images.githubusercontent.com/84673882/123849988-bd673700-d919-11eb-91a5-608a3bd12b2d.mp4

### Are there any alternatives?

Installing other Vesion of PlotSquared.

### Anything else?

Can't send it as bug because i can't make a debug.

**Comment by NotMyFault** [comment]
Stop raising redundant issues. Use our [support discord](https://discord.gg/intellectualsites) for questions and setup help.
