### ISSUE TITLE
1.16.5 Spigot it does not recognize the plugin

### ISSUE THREAD

**Issue by RoboRobi2** [IntellectualSites/PlotSquared#3134]
### Server Implementation

Spigot

### Server Version

1.16.5

### Describe the bug

it does not recognize the plugin

### To Reproduce

1 install the plugin
2 it does not recognize the plugin

### Expected behaviour

it does not recognize the plugin

### Plot Debugpaste

unknown command

### PlotSquared Version

6.0.5 premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Based on the information provided it's not possible to determine what's going on. Please provide a little more information if you actually want us to understand what's going on.
