### ISSUE TITLE
PlotAPI moved since v5

### ISSUE THREAD

**Issue by RomainStorai** [IntellectualSites/PlotSquared#3139]
### What feature do you want to see added?

Your plugin page claims: "100% Compatibility with PlotSquared version 5". However PlotAPI class moved from com.plotsquared.core.api to com.plotsquared.core -> This doesn't allow hook plugins to support both versions at the same time.
Any possibilities to move this class or create an interface?

### Are there any alternatives?

Using two versions at the same time...

**Comment by NotMyFault** [comment]
You can listen for both classpaths and do your stuff later on.

**Comment by SirYwell** [comment]
Compatibility means feature and data wise in this case. Compatibility on API/ABI level would defeat the reason for a major update.
