### ISSUE TITLE
PlotSquared Lag Problem

### ISSUE THREAD

**Issue by Epolision** [IntellectualSites/PlotSquared#3145]
### Server Implementation

Paper

### Server Version

1.13.2

### Describe the bug

There are some lag events in the Plots world on my server, it happens thanks to lag plotsquared, I left the picture in the timings report below, what should I do to fix this problem?

### To Reproduce

Fix

### Expected behaviour

Fix

### Screenshots / Videos

https://prnt.sc/194ug9h

### Plot Debugpaste

https://www.athion.net/ISPaster/paste/view/57e940c23af44a5d8df2adaecc9e0422

### PlotSquared Version

PlotSquared 19.09.07-f27e556-781

### Checklist

- [X] I have included a Plot debugpaste.
- [ ] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

Someone is doing the lag, it needs a solution.

**Comment by MattBDev** [comment]
Minecraft 1.8.8 IS **NOT** supported. Especially not a version of PlotSquared that is 2 years old.

**Comment by NotMyFault** [comment]
Use a supported version like Paper 1.16.5 and PlotSquared v6.

**Comment by Epolision** [comment]
> Minecraft 1.8.8 **DESTEKLENMEZ** . Özellikle PlotSquared'in 2 yıllık versiyonu değil.

It is not possible for me to change the server infrastructure, so I need to fix this problem with another solution.

I need to nap to fix this problem.

**Comment by Epolision** [comment]
> Use a supported version like Paper 1.16.5 and PlotSquared v6.

It is not possible for me to change the server infrastructure, so I need to fix this problem with another solution.

I need to nap to fix this problem.

**Comment by NotMyFault** [comment]
Read our responses.
