### ISSUE TITLE
Players cannot use /plot auto within the world border boundaries

### ISSUE THREAD

**Issue by jhefersongambet** [IntellectualSites/PlotSquared#3150]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

I have a plot area in the vanilla world , the area has about 900 plots and only about 10% of it is occupied , and players before could give 
![unknown](https://user-images.githubusercontent.com/23065725/125169097-10918300-e17f-11eb-9c69-97a56b60d3e5.png)
the /plot auto command without problems , but now they can no longer , display this message in the print below

### To Reproduce

I just make a vannilla world plot area and thats rappend

### Expected behaviour

That players could get plots automatically

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/e2148ea293a145299d071bd9eb35056b

### PlotSquared Version

PlotSquared-5.13.12

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by jhefersongambet** [comment]
Any fix ?

**Comment by NotMyFault** [comment]
I was not able to reproduce named behavior.

**Comment by jhefersongambet** [comment]
Would you like to login to my server to test?

**Comment by jhefersongambet** [comment]
SOLUTION = APPLY AGAIN TO THE EDGE OF THE WORLD AFTER CREATING THE PLOT AREA
