### ISSUE TITLE
`FlagCommand#checkPermValue` not covering all flag types' permissions

### ISSUE THREAD

**Issue by Malachiel87** [IntellectualSites/PlotSquared#3151]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

When you add the permission plots.permpack.basicflags, it don't actually add the subpermission of the flags, example for allow user to set time, farewell message or set flag usage of all items i have to set the permissions
plots.set.flag.time.*
plots.set.flag.farewell.*
plots.set.flag.use.*

My lp verbose: https://luckperms.net/verbose/IezgY8zVl5

### To Reproduce

add the plots.permpack.basicflags and try to use  /p flag set time 100 for example

### Expected behaviour

it should work without adding extra permissions

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/6296585436a842b58a7735de82f49743

### PlotSquared Version

 PlotSquared version 6.0.5-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
@traksag Putting that here from internal channels;
Taking a quick look over https://github.com/IntellectualSites/PlotSquared/issues/3151, appears that FlagCommand#checkPermValue only covers integer and list flags
Other flag types aren't checked so using asterisks in perm packs fail to resolve cuz we simply don't go there; adding an instanceof LongFlag to the integer flag will likely make timed flags work again but others need to be handled properly

**Comment by Malachiel87** [comment]
Any news about it? Is pretty critical issue I think because permissions are not work propely
