### ISSUE TITLE
Missing flags from 6.0.0 change log

### ISSUE THREAD

**Issue by traksag** [IntellectualSites/PlotSquared#3156]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

In the 6.0.0 change log found [here](https://github.com/IntellectualSites/PlotSquared-Documentation/wiki/Changelog#additions-3) the flags 'fall-damage' and 'no-portals' are mentioned but neither is present in the latest version of PlotSquared. I'm guessing 'no-portals' = 'deny-portals'? Not sure what happened to the fall-damage flag; I can implement it if you still want it in PlotSquared.

### To Reproduce

The flags don't show up when tab completing `/p flag info …`.

### Expected behaviour

That the two flags are present.

### Plot Debugpaste

Not applicable

### PlotSquared Version

Built 635e18e7ed47029992ec59cf32429275d904c49c from source

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

Can't find those two flags in the source code either, except that deny-portals seems very similar to no-portals ;)

**Comment by NotMyFault** [comment]
Indeed, I changed stuff quite often when I added them originally. no portals -> deny portals, I've addressed that. In fact, I'm sure I somewhere have a branch with a no fall damage flag, but at this time I'm not sure whether something like that is actually needed.
If you don't want to receive damage, set the plot gamemode to adventure, elsewise I'd need to add flags for all kinds of damage.

**Comment by traksag** [comment]
Oh is the gamemode flag supposed to disable all damage when it is set to adventure? Doesn't seem to be the case in the latest version. The main use for no fall damage is parkour maps. Although doing parkour in gamemode creative with the fly flag set to false, works as well.

**Comment by NotMyFault** [comment]
The game mode flags are supposed to simulate a gamemode. Third party edge cases aren't considered here.
