### ISSUE TITLE
Duplicate list flag entries

### ISSUE THREAD

**Issue by traksag** [IntellectualSites/PlotSquared#3157]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

After adding the same entry multiple times to a list flag, it appears multiple times in `/p i`.

### To Reproduce

1. Do `/p flag add use stone`.
2. Do `/p flag add use stone`.
3. Do `/p flag add use stone`.
4. You'll see see 3 instances of 'stone' when doing `/p i`.

The process is similar for the other list flags.

### Expected behaviour

Only 1 instance of stone when doing `/p i`.

### Plot Debugpaste

Not needed.

### PlotSquared Version

Built a797d748eaff421f15c5a5928ddcb1758418f4d5 from source

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

Honestly this isn't anything serious, it just looks a bit funny. If you do `/p flag remove use stone` it'll remove all instances of 'stone'. Furthermore, after rebooting the server only 1 instance of 'stone' appears when doing `/p i`.

**Comment by NotMyFault** [comment]
That appears to be the intended behavior. `add` is supposed to add up flag entries, for whatever unholy goal, where `set` is supposed to set a single entry.

**Comment by traksag** [comment]
Yeah I understand that `add` is supposed to add values to the 'use' flag. But if you execute `/p flag add use stone` a bunch of times, you'll end up with this in `/p i`:
<img width="664" alt="Screenshot 2021-07-13 at 00 45 24" src="https://user-images.githubusercontent.com/58818927/125364907-9ece5a80-e373-11eb-9276-e5d6761ba5d5.png">
I expected to end up with
<img width="659" alt="Screenshot 2021-07-13 at 00 46 23" src="https://user-images.githubusercontent.com/58818927/125364986-c1607380-e373-11eb-832a-9c10d6c2e368.png">
I guess this issue can be closed if the first picture is intended behaviour.

**Comment by NotMyFault** [comment]
Out of my mind I see no use case where you would want duplicated entries for a single flag instance.

**Comment by SirYwell** [comment]
It should probably do a contains check before adding them and either silently ignore it if it's already in there or tell the user.

**Comment by NotMyFault** [comment]
> It should probably do a contains check before adding them and either silently ignore it if it's already in there or tell the user.

Sounds like add can be considered as alias of set.

**Comment by SirYwell** [comment]
No, `set` replaces the previous values while `add` merges the previous with the new values. I think merging should not produce duplicates, although we need to check if that is required somewhere.

**Comment by traksag** [comment]
Still an issue. Probably got marked as stale because this issue is marked as "Works as intended".
