### ISSUE TITLE
Odd messages for flag remove command

### ISSUE THREAD

**Issue by traksag** [IntellectualSites/PlotSquared#3158]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

The command `/p flag remove` sometimes outputs odd messages.

### To Reproduce

Run `/p flag add use stone` and then `/p flag remove use`. You'll see:
<img width="658" alt="Screenshot 2021-07-13 at 00 59 01" src="https://user-images.githubusercontent.com/58818927/125365984-85c6a900-e375-11eb-8af3-1e8f3494c5d1.png">
There's something missing between 'value' and 'has' in the second message.

Run `/p flag set lectern-read-book true` and then `/p flag remove lectern-read-book`. You'll see:
<img width="654" alt="Screenshot 2021-07-13 at 01 02 00" src="https://user-images.githubusercontent.com/58818927/125366202-efdf4e00-e375-11eb-967b-0b0e3f7c5b1b.png">
In the second message it should say 'with the value true' instead of 'with the value false'.

### Expected behaviour

See above.

### Screenshots / Videos

See above.

### Plot Debugpaste

Not needed.

### PlotSquared Version

Built a797d748eaff421f15c5a5928ddcb1758418f4d5 from source

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
It appears that flag values are no longer available when sending the removal message leading to empty or incorrect messages.
