### ISSUE TITLE
Loading a plot backup deletes part of plot border

### ISSUE THREAD

**Issue by traksag** [IntellectualSites/PlotSquared#3159]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

Loading a plot backup deletes the +Z border of the plot. See the video below.

### To Reproduce

1. `/p backup save`
2. `/p backup load 1`
3. `/p confirm`

### Expected behaviour

I expected the plot border to remain in tact.

### Screenshots / Videos

https://user-images.githubusercontent.com/58818927/125601052-0808dda8-3e35-4e36-a0e9-2fbcb13a6d31.mov

### Plot Debugpaste

Not needed.

### PlotSquared Version

Built cc60d50dd29cce352ed81a7faa0627b11bcf0906 from source

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by traksag** [comment]
My bad, it seems this is essentially the same issue as https://github.com/IntellectualSites/PlotSquared/issues/3131.

**Comment by NotMyFault** [comment]
Could you confirm that your pr resolves named issue as well? The issues appear have the same outcome. If so, I'd close this one and change the reference on your pr.

**Comment by traksag** [comment]
My PR fixes both this issue and the other one. I updated my PR to reflect that.
