### ISSUE TITLE
Missing light update around light sources on schematic paste (road schematic for example)

### ISSUE THREAD

**Issue by ofunny** [IntellectualSites/PlotSquared#3164]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

I did create a schematic for the road generation (as explained in the PS wiki), I also added street lamps (tested with redstone lamp, sea lantern …). The creation of the road schematic works well, new chunks use it as intended, but: blocks around light sources like redstone lamp, sea lantern … do not receive a light update, they behave as if there were no light sources next to them.

Short version: PS uses the road schematic, pastes it as intended. Block with light will be placed, but block around them stay dark until you perform an build action what also updates the light. 

I did not test it with other schematic im/exporting features of PS6 (like backup), might also affect them.

### To Reproduce

1. Create a road schematic.
2. Make sure to place light sources like redstone lamps or sea lanterns.
3. Create new chunks using this schematic.
4. Now the bug should appear.

### Expected behaviour

After pasting/creating from a schematic blocks around light sources should have the correct light value/update!

### Error log (if applicable)

No errors

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/af85ea2b1e7743e8aa6257f75ee9bd1f

### PlotSquared Version

PlotSquared-Bukkit-6.0.5-Premium.jar

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by dordsor21** [comment]
This is an issue with spigot generation - nothing we can do about it. You can use plugins (LightCleaner) (and/or possibly tuinity might work?) to fix lighting during generation
