### ISSUE TITLE
/p clear /p delete ERROR

### ISSUE THREAD

**Issue by MarkusKSBg** [IntellectualSites/PlotSquared#3165]
### Server Implementation

Spigot

### Server Version

1.17.1

### Describe the bug

If i want to delete or clear a plot, there is a error in the console and nothing happend, in one case the plugin make a Backup from the plot???? in one case not.... 

### To Reproduce

/p h <name>
/p delete  --> ERROR
/p clear --> ERROR

### Expected behaviour

If i want to delete or clear a plot, there is a error in the console and nothing happend, in one case the plugin make a Backup from the plot???? in one case not.... 

### Error log (if applicable)

https://paste.gg/p/anonymous/b37379610c17451d9dd660f8bd95ded1

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/8e622166dbed4f5f961c76c719aaa9e6

### PlotSquared Version

6.0.6-Premium Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

I don´t know what happens, i worked so long with your plugin, and since the 1.17.x there are only errors....
:-( 

Plotsquared setup is classic flat, plotsquare generator....

**Comment by NotMyFault** [comment]
Some plugin is shading (parts of) PlotSquared leading to it not working properly.
