### ISSUE TITLE
<prefix> is not displayed if i type /p help <any category>

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#3169]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

If i type /p help the <prefix> in help header is displayed correctly. But if i type /p help claiming it does not display the prefix

### To Reproduce

Type /p help claiming

### Expected behaviour

Correct replacement of the placeholder

### Screenshots / Videos

![grafik](https://user-images.githubusercontent.com/38475631/126383526-8a428ac5-c491-4901-8b8c-bd33103e00f6.png)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/8fdd867e880a4cbc8ba5aaf64b271e83

### PlotSquared Version

6.0.6

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
The help menu does not use a prefix, so it wont resolve it here.
