### ISSUE TITLE
Variable <creationdate> is not replaced

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#3170]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

If i use the variable <creationdate> he will not replaced in info

### To Reproduce

use the <creationdate> variable

### Expected behaviour

The date of the plot creation

### Screenshots / Videos

![grafik](https://user-images.githubusercontent.com/38475631/126386419-e7fafc37-d7de-454d-9e8e-6a8069e443dd.png)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/8fdd867e880a4cbc8ba5aaf64b271e83

### PlotSquared Version

6.0.6

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
In which caption at which spot did you use named placeholder?

**Comment by DevJoey** [comment]
In /p info

**Comment by DevJoey** [comment]
Named placeholders?

**Comment by NotMyFault** [comment]
Can't replicate
![](https://i.imgur.com/MRaASBW.png)
![](https://i.imgur.com/pXg25Vb.png)

**Comment by DevJoey** [comment]
I have escaped all correctly. I will send my message.

This does not work and i dont know why ;(
`<gray>Erstellt<dark_gray>:</dark_gray> <aqua><creationdate></aqua>\nID<dark_gray>:</dark_gray> <aqua><id></aqua>\nSpitzname<dark_gray>:</dark_gray> <alias>\nBesitzer<dark_gray>:</dark_gray> <owner>\nVertraut<dark_gray>:</dark_gray> <trusted>\nMitglieder<dark_gray>:</dark_gray> <members>\nHausverbot<dark_gray>:</dark_gray> <denied>\nFlags<dark_gray>:</dark_gray> <flags></gray>`

**Comment by NotMyFault** [comment]
What does the actual timestamp of named plot look like? Check the `plot´ table.
