### ISSUE TITLE
Colour codes in greeting/farewell no longer work

### ISSUE THREAD

**Issue by traksag** [IntellectualSites/PlotSquared#3172]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

Colour codes, such as &a, &b, &c, in plot greeting and farewell messages don't work anymore in v6.

### To Reproduce

1. Execute `/p set flag greeting &ahi` and `/p set flag farewell &abye`.
2. Move in and out of the plot.
3. The messages "&ahi" and "&abye" appear in chat.

### Expected behaviour

I expected lime coloured messages "hi" and "bye" to appear in chat, as was the case in v5.

### Screenshots / Videos

<img width="654" alt="Screenshot 2021-07-22 at 13 26 41" src="https://user-images.githubusercontent.com/58818927/126632154-db0c4d40-b62e-45cb-9105-6f4b8a02cd78.png">

### Plot Debugpaste

Not needed

### PlotSquared Version

Built fbde60fcf958c1b9d6fe9a34bc0182525b5bf1a8 from source

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

I think players can use `<green>hi</green>` now, but I don't think players should be required to rewrite their greeting/farewell messages. Not to mention that greeting/farewell messages on plots of inactive players are still broken, unless staff goes through all plots and converts them to the new format (a lot of pointless work). Other plugins also use the traditional colour codes, so it's convenient for users if those worked in PlotSquared as well.

**Comment by NotMyFault** [comment]
Legacy color codes are nowhere used anymore. We are now using Components via MiniMessage to style messages, see https://docs.adventure.kyori.net/minimessage.html for an example.

**Comment by traksag** [comment]
This is a feature request then. I don't see any reason to break colours of plot greeting/farewell messages from v5. See also the "Anything else?" part above.

**Comment by NotMyFault** [comment]
The breakage happened when the decision has been made to use MiniMessage to style our messages over using ampersands, which was more than a year ago. Bringing back legacy features is undesired at this point, since we have a system in place that offers better capability with modern mc and offers backwards compatibility.
