### ISSUE TITLE
plots getting deleted

### ISSUE THREAD

**Issue by skfdsksd** [IntellectualSites/PlotSquared#3174]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Players plots just randomly get wiped for no reason has happened to multiple players on my server repetively

### To Reproduce

1. Use plot squared v5
2. Play for a little
3. Log off
4. Log Back In
5. Whole plot is deleted

### Expected behaviour

Plot should not get deleted

### Screenshots / Videos

d

### Error log (if applicable)

w

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/f8fa20d793634b738eb05624462dbe84

### PlotSquared Version

v5.13.12 minehut

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
PlotSquared does not save the content of the plots. That is down to your server. Also v5 is unsupported and so is not filling out issue templates properly.

**Comment by skfdsksd** [comment]
So what can I do to fix the issue
