### ISSUE TITLE
UNKNOW entity type can't be adapted => error

### ISSUE THREAD

**Issue by Aurelien30000** [IntellectualSites/PlotSquared#3179]
### Server Implementation

Tuinity

### Server Version

1.17.1

### Describe the bug

Unexpected error interacting with the named ``UNKNOWN`` entity type.

### To Reproduce

No real idea, try to interact with the named ``UNKNOWN`` entity type.

### Expected behaviour

No error.

### Error log (if applicable)

https://paste.domicraft.fr/horecuwise.properties

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/be2e7bb2ea6343a1ba1c65be895b7cb9

### PlotSquared Version

PlotSquared v6.0.7-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

**2 fix ideas I may implement later, but I would like your opinion about first!**

---

1) - Getting adapted entity type, PS should check null value: https://github.com/IntellectualSites/PlotSquared/blob/v6/Bukkit/src/main/java/com/plotsquared/bukkit/listener/PlayerEventListener.java#L1470 
    - On WE/FAWE, adaptater should return null in case entity type is ``UNKNOWN``, since WE doesn't implement this Bukkit entity type: https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/main/worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/adapter/IBukkitAdapter.java#L339

---

2) - Implement an ``UNKNOWN`` entity type to replicate Bukkit behavior.

---

**Comment by SirYwell** [comment]
Do you have any plugins that introduce custom entities (pets or something like that)? While we should fix that in PlotSquared, I'd be interested how it is actually triggered.

**Comment by Aurelien30000** [comment]
GadgetsMenu indeed, I'll try to reproduce the issue spawning pets.

**Comment by Aurelien30000** [comment]
Confirmed, can reproduce using GadgetsMenu _Premium_ pets in a claimed plot (you must be a guest in this plot).

Those custom entities directly extends ``EntityInsentient``, which is considered as a default LivingEntity by Bukkit API, whose type is ``EntityType.UNKNOWN``.
```java
public static CraftEntity getEntity(CraftServer server, net.minecraft.world.entity.Entity entity) {
...
            return new CraftLivingEntity(server, (EntityLiving)entity);
```
```java
public EntityType getType() {
    return EntityType.UNKNOWN;
}
```

**Comment by SirYwell** [comment]
Thanks for looking into it. I guess it's fine to ignore them? If a plugin provides custom entities, it should deal with protecting them and limiting interactions based on regions if needed I think.

**Comment by Aurelien30000** [comment]
Fine to ignore them indeed, custom entities are especially handled to avoid protections and implement their own.
_Among the solutions I've considered, which one do you think would be most appropriate?_

**Comment by SirYwell** [comment]
A 
```java
if (event.getRichtClicked().getType() == EntityType.UNKNOWN) {
    return;
}
```
at the beginning of the method should be fine

**Comment by Citymonstret** [comment]
We should honestly just emit a `PlotPlayerInteractEntityEvent` or something there, and then the plugin implementing the entity could easily decide whether or not to approve it (if it's cancelled, we cancel the main event)

**Comment by SirYwell** [comment]
That would be a platform dependent event then. I'm not sure if this wouldn't make things messier more than it helps.

**Comment by Citymonstret** [comment]
The problem right now is that people need to do the same chain of calls to get the current plot, etc, that we're doing in our event, to get the same results. We've already reached a point where we're sure there's a plot there.

I am not really against the idea of adding more events in general, we could also do this using _our_ event bus, but then passing the native entity would become quite awkward.

**Comment by SirYwell** [comment]
Making this a consistent feature that can be used properly sounds awful to me. I'm not necessarily against it but I'd pefer to just fix that bug with the said check for now.

**Comment by Citymonstret** [comment]
Yes, a hot-fix for this specific issue is fine. This looks like a missing piece of almost-crucial API to me though

**Comment by Citymonstret** [comment]
Also just realized that we've had a discussion about GadgetsMenu in the past: https://github.com/IntellectualSites/PlotSquared/issues/2971

**Comment by Aurelien30000** [comment]
Great idea for an event specific to the plot entities! This will allow a better management of them. I'll let you create a feature request, or I can do it picking up your posts, if you want.
