### ISSUE TITLE
expired plot clearing not working

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#318]
old plots dont seem to be deleted, at least there is no console output

**Comment by boy0001** [comment]
Possibly fixed with latest version

**Comment by Sauilitired** [comment]
Still an issue?

**Comment by boy0001** [comment]
*It will be assumed that this has been fixed. This bug shouldn't be relevant anymore since the switch to the new expiry system anyway, so if there's issues we can create a new ticket.

**Comment by PhanaticD** [comment]
yes sorry this was fixed
