### ISSUE TITLE
Permission for /p plugin

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#3182]
### What feature do you want to see added?

I want to hide my plotsquared version from users without permissions. If users know what version i currently running they have server intern informations. So it would be nice if a permission for /p plugin would be added

### Are there any alternatives?

An option to disable /p plugin in config or a completly customizable message for /p plugin output

**Comment by NotMyFault** [comment]
`/plot plugin` is the only spot crediting authors and note worthy contributors. Hiding/moving said information is undesired and blatantly unfair.
