### ISSUE TITLE
P2 does not send correct message on merge request

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#3183]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

If i send a merge request, the message: `confirm.requires_confirm` is sended to the other plots owner. Normally the message `merge.merge_request_confirm` must be sendet

This in an addition to: https://github.com/IntellectualSites/PlotSquared/issues/3180

### To Reproduce

1. Grap two accounts
2. Claim a plot pro account
3. Go to one account look to plot oth other account and do /p merge

You must have only the permissions plots.merge and plots.merge.others

### Expected behaviour

The message `merge.merge_request_confirm` must be sendet and not message: `confirm.requires_confirm`

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/8fdd867e880a4cbc8ba5aaf64b271e83

### PlotSquared Version

6.0.7

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
That is the correct behavior. Both captions are send but unified under the hood.
