### ISSUE TITLE
WorldEdit `//repl` tool can edit plot border and road

### ISSUE THREAD

**Issue by braceyourself07** [IntellectualSites/PlotSquared#3193]
### Server Implementation

Tuinity

### Server Version

1.16.5

### Describe the bug

Using the `//repl` tool from WorldEdit, a player can edit the plot border and plot road.  They can't edit other players' plots because they don't have the interact/use permission.

### To Reproduce

1. Equip stick or other tool item
2. `//repl 1`
3. Left click to set a block
4. Right click to replace that block where you right click and then start right clicking on the plot border and roads

### Expected behaviour

P2 should prevent road and border from being changed.

### Screenshots / Videos

https://brdv.coffee/storage/uploads/4/gwVvk2DyytjB.jpg

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/9cbc1eead8c349e4b362bcc32c506464

### PlotSquared Version

6.0.7

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Without `plots.admin.interact.road` that wont be possible.

**Comment by braceyourself07** [comment]
Ah ok, I just remove that perm.  I used to have it a while back so players could interact with a right-click sign/button menu in a plot spawn.  But I can do without it.
