### ISSUE TITLE
Players can not ignite fire with flint and steel

### ISSUE THREAD

**Issue by LeJosplayy** [IntellectualSites/PlotSquared#3194]
### Server Implementation

Spigot

### Server Version

1.16.5

### Describe the bug

Hello I am using the last PlotSquared v6 on 1.16.5
the player can not ignite blocks with flint and steel

### To Reproduce

1. Claim a block
2. get flint and steel
3. try to ignite

### Expected behaviour

The block should be ignite by fire

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/223455a2971b410fa422222b86f063bd

### PlotSquared Version

PlotSquared-6.0.8-SNAPSHOT

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Missing ignition flag, docs.

**Comment by LeJosplayy** [comment]
thanks it works but why is it described as default true but it is not?
