### ISSUE TITLE
PlayerLeavePlotEvent is called on PlotFlag changes

### ISSUE THREAD

**Issue by Riku32** [IntellectualSites/PlotSquared#3195]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

`PlayerLeavePlotEvent` listeners are called when any plot flag is changed on any plot

### To Reproduce

Create a `PlayerLeavePlotEvent` listener that logs leave events
Go into the plot
Set a plot flag
Check console

### Expected behaviour

`PlayerLeavePlotEvent` is called ONLY when leaving the plot and ignores flag changes

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/9451f9000f374dabbac8f8a6e56e92bd

### PlotSquared Version

6.0.6-BETA

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
That is outline within the javadocs, see Plot#reEnter()

**Comment by Riku32** [comment]
Still is there a way to prevent those events from being called when the players did not in fact leave the plot

**Comment by SirYwell** [comment]
I don't know why it is implemented that way, it might be better to have a PlotRefreshEvent or something like that

**Comment by Riku32** [comment]
Yeah, or at least maybe something like `PlayerLeavePlotEvent#isUpdate` which returns true if the player actually left or if it was a flag/setting update

**Comment by Riku32** [comment]
:neutral_face: this is not being reopened lmao
