### ISSUE TITLE
You should repair the warehouse, which will be good

### ISSUE THREAD

**Issue by damemod** [IntellectualSites/PlotSquared#3196]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Two important libraries failed, such as snapshot and release

### To Reproduce

Simple construction process 

### Expected behaviour

Repair now

### Screenshots / Videos

![image]（https://user-images.githubusercontent.com/85817502/128345731-f760e27d-bb33-43ac-a72b-324d16ba3461.png）

![image](https://user-images.githubusercontent.com/85817502/128345810-2cc1af30-c03d-4dbd-90de-78736b95579a.png)

### Plot Debugpaste

no run

### PlotSquared Version

6.0.8

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
https://github.com/IntellectualSites/PlotSquared-Documentation/wiki/API-Documentation
The index is not meant to be browsable, you don't need it.

**Comment by damemod** [comment]
First of all, I would like to express my thanks. I will finish my work
