### ISSUE TITLE
Big memory leaks?

### ISSUE THREAD

**Issue by traksag** [IntellectualSites/PlotSquared#3197]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

Recently our plots server has been running short of memory a couple of times, so I had to reboot it a few times. I decided to take a heap dump this time. After analysing the ~3GB heap dump with VisualVM, it *seems* PlotSquared is leaking memory (see the "Retained" column).
<img width="1155" alt="Screenshot 2021-08-06 at 03 35 06" src="https://user-images.githubusercontent.com/58818927/128442567-4390981a-b718-492a-aee0-973c627de0e8.png">

I can provide more screenshots of the VisualVM session. Not sure if I can share the heap dump itself, as it may contain sensitive data.

It looks as if there are a couple of `BukkitQueueCoordinator`s of which the `blockChunks` field holds a bunch of  `LocalChunk`s with tons of WorldEdit `BaseBlock`s and `BiomeType`s. At the moment, I have no guesses as to what the cause of this could be, because I don't know what the queue coordinator system is used for.

Another issue is that there are ~299K `FlagContainer` objects even though there are 'only' ~22K `Plot` objects. Looking through the heap dump, it seems these `FlagContainer` objects are retained by `updateSubscribers` in the global flag container https://github.com/IntellectualSites/PlotSquared/blob/391476ba268f337768058258afcf932723b44199/Core/src/main/java/com/plotsquared/core/plot/flag/FlagContainer.java#L52
These `FlagContainer` instances are added here (the lambda retains the encompassing `FlagContainer` instance)
https://github.com/IntellectualSites/PlotSquared/blob/391476ba268f337768058258afcf932723b44199/Core/src/main/java/com/plotsquared/core/plot/flag/FlagContainer.java#L67-L75
and never removed. This is consistent with the fact that there are exactly as many `FlagContainer$$Lambda$5527+0x0000000801cc94c8` objects as `FlagContainer` objects in the image above.

### To Reproduce

Not sure. Took the memory dump 2-3 days after a server restart.

### Expected behaviour

Less memory usage.

### Plot Debugpaste

Doesn't seem relevant.

### PlotSquared Version

My branch that got merged in fbde60fcf958c1b9d6fe9a34bc0182525b5bf1a8

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by Aurelien30000** [comment]
Hey, please provide a debug paste anyway, even if you think it isn’t relevant. You’ve also checked the box.

**Comment by traksag** [comment]
@Aurelien30000 No I won't because it contains a lot of data we're hesitant to share publicly, such as server setup, player chat and executed commands. As in my other bug reports, I'm investing significants amounts of time to provide more useful information instead.

I did some testing on a test server with WorldEdit and 200x200 plots using VisualVM. Each time you run `/p set floor …` or `/p set main …` or `/p clear`, it looks like PlotSquared creates a `BukkitQueueCoordinator` that never gets cleaned up. These retain a number of `LocalChunk`s with WorldEdit `BaseBlock`s and `BiomeType`s arrays.

The `BukkitQueueCoordinator`s are retained by `BukkitQueueCoordinator$$Lambda$6302+0x0000000801decf08` objects stored in the `chunkConsumer` field in `BukkitChunkCoordinator`. I think it's referring to this lambda:
https://github.com/IntellectualSites/PlotSquared/blob/391476ba268f337768058258afcf932723b44199/Bukkit/src/main/java/com/plotsquared/bukkit/queue/BukkitQueueCoordinator.java#L120
The `BukkitChunkCoordinator`s are in turn retained by the `runnable` in `BukkitPlotSquaredTask`. I think it's the repeating runnable created here:
https://github.com/IntellectualSites/PlotSquared/blob/391476ba268f337768058258afcf932723b44199/Bukkit/src/main/java/com/plotsquared/bukkit/queue/BukkitChunkCoordinator.java#L107-L112
The `BukkitQueueCoordinator`s are also retained by the `activeQueues` field in `GlobalBlockQueue`.

Looking through the code, it seems cancelled `PlotSquaredTask`s (i.e. `BukkitChunkCoordinator`s) on a timer, are never removed from the Bukkit scheduler.

It also seems `BukkitQueueCoordinator`s are enqueued in the `GlobalBlockQueue`'s `activeQueues` here
https://github.com/IntellectualSites/PlotSquared/blob/391476ba268f337768058258afcf932723b44199/Core/src/main/java/com/plotsquared/core/queue/QueueCoordinator.java#L323-L325
However, enqueued items are never removed from the `activeQueues` since the dequeue method doesn't have any uses:
https://github.com/IntellectualSites/PlotSquared/blob/v6/Core/src/main/java/com/plotsquared/core/queue/GlobalBlockQueue.java#L83-L86

So I believe the `BukkitQueueCoordinator` memory leak can be resolved removing cancelled/finished tasks from the Bukkit scheduler and also removing cancelled/finished items from the `GlobalBlockQueue`.

**Comment by Aurelien30000** [comment]
> @Aurelien30000 No I won't because it contains a lot of data we're hesitant to share publicly, such as server setup, player chat and executed commands. As in my other bug reports, I'm investing significants amounts of time to provide more useful information instead.

Np, a debug paste is just always informative ;) _Note: You can send sensitive data/links to the discord bot ``Sheriff`` if you don't expect your data to be shared. Admins only will be able to read it then!_

**Comment by traksag** [comment]
The linked pull request resolves 1 of the 2 issues listed here. See my latest comment above for more details on the second issue. Could you reopen this issue, or would you prefer it if I make a 2nd issue report for the unresolved issue?

**Comment by dordsor21** [comment]
Fixed by #3208
