### ISSUE TITLE
"/p toggle clear-confirmation" has no effect

### ISSUE THREAD

**Issue by MCAlagaesia** [IntellectualSites/PlotSquared#3203]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

`/p toggle clear-confirmation` has no effect.

### To Reproduce

1. Toggle `/p toggle clear-confirmation`
2. Run `/p clear`
3. Note that `/p confirm` is required
4. Toggle `/p toggle clear-confirmation`
5. Run `/p clear` again
6. Note that `/p confirm` is still required

### Expected behaviour

When `clear-confirmation` is disabled, the user is able to clear/delete plots instantly without confirmation via `/p confirm`

### Screenshots / Videos

[https://youtu.be/9sVT6gZQUWo](https://youtu.be/9sVT6gZQUWo)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/90755693f829457e896f459a38798ef0

### PlotSquared Version

6.0.8-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

I'm hoping `/p toggle clear-confirmation` will work for deleting as well - that's what I was trying to do when I encountered this issue! :-)

**Comment by NotMyFault** [comment]
Clear-confirmation is not intended to have any effect on whether the actor can clear or delete plots without typing `/plot confirm` but whether the expire manager should notify you before starting to purge plots if you set it up.
