### ISSUE TITLE
Using /p info or /p visit on a merged plot at high coordinates may cause issues if caching is unsuccessful

### ISSUE THREAD

**Issue by Malachiel87** [IntellectualSites/PlotSquared#3204]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

Using /p info or /p visit on a a merged plot (also with only 2 plots) will lag the whole server, if repeated/spammed it will crash

### To Reproduce

1. Merge a plot using at least 2 default size plots on high coordinates like 250000000 50 5050500
2. Doing /p info to that plot will lag the server and /p visit too, it can crash too if used 2-3 times in row

### Expected behaviour

Should no lag? 

### Screenshots / Videos

https://timings.aikar.co/?id=53251a65592e4844aa031175968ab93f (check the 2 drops at end
https://spark.lucko.me/yLb8289AdY

### Error log (if applicable)

https://bin.byreqz.de/?7f94e8fa42b78c0f#6f36zqF8MxWurvB6vTvEG2MszZR2AFGdPjK9vP7sPk4N

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/2f1dacbddb29419ead1d796b8062efc1

### PlotSquared Version

6.0.7 but i tested 6.0.8 too, same issue

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

Fix it is urgent please

**Comment by NotMyFault** [comment]
Nobody has plots at such high coordinates, not speaking of the issues teleporting to those coordinates caused many issues in the past that forced Mojang to implement a boundary catch that prevents that. Play the game within the bounds and you wont face those issues.
