### ISSUE TITLE
PlotSquared - NoSuchPlayerException

### ISSUE THREAD

**Issue by Blocky38** [IntellectualSites/PlotSquared#3205]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

SOMETIMES, when joining my server with an client with join commands (Executes directly after joining commands) with the command `/ptime @4000` from EssentialsX the server prints out an Exception. 

### To Reproduce

1. Install PlotSquared (not EssentialsX)
2. Join with a client with Join-Commands (`/ptime @4000`)

### Expected behaviour

No Exception in the console.

### Error log (if applicable)

https://gist.github.com/Blocky38/299df7d2644df9b9b7ba2d48eb4ee19f

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/c2dedeb7ca4843f6971757e2ac4ded66

### PlotSquared Version

6.0.8-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Don't use such a mod then, it appears it's sending commands to the server without the server registering said player yet, thus it throws a NoSuchPlayerException

**Comment by Blocky38** [comment]
It is sending the command 5 seconds after succesfull joined.

**Comment by NotMyFault** [comment]
> It is sending the command 5 seconds after succesfull joined.

> Executes directly after joining commands

If your login process takes 5 seconds you have issues located deeper. Anyway, using the PlayerCommandPreprocessEvent to dispatch commands is not what it's designed for, as outlined within the docs. But that is something you should take up with the mod creator.
