### ISSUE TITLE
Can't clear plot due to Set Block Timer

### ISSUE THREAD

**Issue by strahil211** [IntellectualSites/PlotSquared#3207]
### Server Implementation

Tuinity

### Server Version

1.17.1

### Describe the bug

I keep getting a Set Block Timer message when I try to clear my plot.

### To Reproduce

Clear a plot, then go to another one and clear it as well, Should receive Set Block Timer message that denies you.

### Expected behaviour

Let me clear plots at any time without any issues

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/3ba210fa2c794a578a980e49e05a8443

### PlotSquared Version

6.0.8 Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

Not 100% its a bug so if it's something on my end I can change via configuration please let me know. I haven't been able to figure it out

**Comment by NotMyFault** [comment]
> Server Version: git-Airplane-"36c9bc8" (MC: 1.17.1)
> Server Implementation
Tuinity

If your platform is not listed, it's unsupported.
