### ISSUE TITLE
Could not pass event InventoryCloseEvent to PlotSquared v6.0.8-Premium

### ISSUE THREAD

**Issue by TheosisOfficial** [IntellectualSites/PlotSquared#3209]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

I use a plugin called [Crate Reloaded](https://www.spigotmc.org/resources/pro-crate-reloaded-mystery-crate-1-8-1-17-x.3663/). If a player is awaiting a GUI-based crate animation to finish but logs out before it can, when the animation _would_ have finished, this exception occurs: https://pastebin.com/VrhCxXH2

I'm pretty certain this is due to Crate Reloaded's GUI-based animation finishing, and therefore its GUI closing, when the player is offline. It would be nice if PlotSquared could handle this scenario, despite it being an improbable one.

### To Reproduce

1. Install [Crate Reloaded](https://www.spigotmc.org/resources/pro-crate-reloaded-mystery-crate-1-8-1-17-x.3663/) (the [free version](https://www.spigotmc.org/resources/free-crate-reloaded-mystery-crate-1-8-1-16-x.861/) will probably work for this too).
2. Install PlotSquared
3. Set up a key crate with Crate Reloaded and make it so that it has an animation.
4. Open the crate with a key and during the animation, close your game client using the X or Alt + F4.
5. Watch for the exception in your console.

### Expected behaviour

PlotSquared should anticipate this possibility of an inventory closing but the player being offline, preventing the exception from happening.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/cf4347c1cc384a938a529d89751a868a

### PlotSquared Version

6.0.8-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
My motivation to look into issues caused by obfuscated plugins goes bar null.

**Comment by TheosisOfficial** [comment]
> My motivation to look into issues caused by obfuscated plugins goes bar null.

Couldn't any plugin, obfuscated or not, cause this type of issue if it closes an inventory when the associated player is offline?

**Comment by NotMyFault** [comment]
That's up to the plugins to handle that properly. We don't need to add a failsafe catch, because plugins don't clean up after them properly addressing scenarios like the actor getting kicked or closes the game for whatever reason.

**Comment by TheosisOfficial** [comment]
> That's up to the plugins to handle that properly. We don't need to add a failsafe catch, because plugins don't clean up after them properly addressing scenarios like the actor getting kicked or closes the game for whatever reason.

That makes sense. I'll speak to the CR dev then, thanks!
