### ISSUE TITLE
/Plot Clear doesn't remove Armorstands

### ISSUE THREAD

**Issue by Strahilchu** [IntellectualSites/PlotSquared#3210]
### Server Implementation

Tuinity

### Server Version

1.17.1

### Describe the bug

/Plot Clear should clear the plot of entities as well. However armorstands remain

### To Reproduce

Place armorstands, execute /plot clear

### Expected behaviour

Clear the plot without anything remaining including all entity types

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/913048a0e59b435cbbfbd1cc87ca3bea

### PlotSquared Version

6.0.8 Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

There are also light bugs remaining on the plot after clearing, dark spots all over from shadows and such.

**Comment by NotMyFault** [comment]
I'm unable to reproduce named behavior based on the information provided. Try to replicate it in a clean environment with no plugins but WorldEdit and PlotSquared.

**Comment by strahil211** [comment]
I will try, it also didn't remove End Crystals. Here's the light bug as well, will report back after testing with no other plugins.

![2021-08-13_15 38 16](https://user-images.githubusercontent.com/69178324/129416013-dc19f30c-232d-4783-830b-9ac853279b61.png)

**Comment by NotMyFault** [comment]
Earlier I gave it a test on Paper v 176 with WorldEdit version 7.2.6-SNAPSHOT+5905-4277cb5 and PlotSquared version 6.0.8-Premium working out flawless.
