### ISSUE TITLE
Wrong Rotate Road Schematics

### ISSUE THREAD

**Issue by DevSnx** [IntellectualSites/PlotSquared#3211]
### Server Implementation

Spigot

### Server Version

1.16.5

### Describe the bug

I have create a Road for my Server and the plugin is Rotate it wrong

### To Reproduce

...

### Expected behaviour

...

### Screenshots / Videos

FROM THIS
![2021-08-17_12 45 49](https://user-images.githubusercontent.com/59105899/129712761-6afa916e-8128-4fce-a5f8-c9c63f5fb9ff.png)

TO THIS
![2021-08-17_12 42 42](https://user-images.githubusercontent.com/59105899/129712559-e375b982-1485-44df-850a-771bc6013fda.png)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/f3be583974a044329958b26a0dbeef84

### PlotSquared Version

PlotSquared-Bukkit-4.4.495

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
PlotSquared v4 is no longer supported. You should consider updating to v6.

**Comment by DevSnx** [comment]
> PlotSquared v4 is no longer supported. You should consider updating to v6.

This not for free or?

**Comment by NotMyFault** [comment]
As "free to use" as any other version https://www.spigotmc.org/resources/77506/
