### ISSUE TITLE
PlotSquared - Bug - NoSuchPlayerException

### ISSUE THREAD

**Issue by ElDapo** [IntellectualSites/PlotSquared#3214]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Sometimes after executing a command the PlotSquared is throwing an Exception. I have talked to several server developers and all said, that it is a bug coming from PlotSquared.

### To Reproduce

1. Join the server
2. Execute a command

### Expected behaviour

No exception.

### Error log (if applicable)

https://gist.github.com/ElDapo/7d042acb12353c7456e850a8fb43e3ab

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/3418e29d59c344dca03f11514d590145

### PlotSquared Version

6.0.9-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by Blocky38** [comment]
I have seen the same Exception with Vanilla Client in PlotSquared 6.0.9-Premium and 6.0.8-Premium.

**Comment by Blocky38** [comment]
On my Private Testing Server i don't have ViaVersion installed.

**Comment by ElDapo** [comment]
I haven't intalled ViaVersion and I connected with the same version the server is running on.

**Comment by dordsor21** [comment]
> I haven't intalled ViaVersion and I connected with the same version the server is running on.

You do have ViaVersion installed based on the provided debugpaste

**Comment by Blocky38** [comment]
> > I haven't intalled ViaVersion and I connected with the same version the server is running on.
> 
> You do have ViaVersion installed based on the provided debugpaste

He has edited his post.

**Comment by RobinZockt** [comment]
i have the same problem

**Comment by dordsor21** [comment]
This cannot be a P2 issue. We check the `Player#isOnline` method which would only return false if something has gone wrong with the server. See https://github.com/IntellectualSites/PlotSquared/blob/v6/Bukkit/src/main/java/com/plotsquared/bukkit/player/BukkitPlayerManager.java#L68-L70 for where the exception is thrown. This method delegates ultimately to `server.getPlayer(getUniqueId()) != null;`.

**Comment by Blocky38** [comment]
But why is there than an exception, on my test servers and servers from others?

**Comment by SirYwell** [comment]
Well either provide proper information that helps to look into the issue or check what's wrong with your server setup yourself.

**Comment by Blocky38** [comment]
We are friends and had the same issue on our  (test) servers in the last days. So we reported it in one issue post.
