### ISSUE TITLE
Don't append bedrock layer under road if `bedrock: false`

### ISSUE THREAD

**Issue by ItsMCB** [IntellectualSites/PlotSquared#3216]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

Bedrock is added after you deleted merged plots even if you have bedrock generation set to false.

### To Reproduce

World Settings:
    - plot setup
    - plot setup PlotSquared
    - plot setup normal
    - plot setup 62
    - plot setup 101
    - plot setup air
    - plot setup true
    - plot setup grass_block
    - plot setup stone_slab
    - plot setup smooth_stone_slab
    - plot setup 30
    - plot setup 62
    - plot setup air
    - plot setup air
    - plot setup 62
    - plot setup false

Then:
- Claim a plot (/plot claim)
- Claim a plot next to it (/plot claim)
- Merge the plots (/plot merge)
- Delete plot (/plot delete)

### Expected behaviour

The bedrock should not appear.

### Screenshots / Videos

Here's a 1 minute video showing off the issue: h[ttps://www.youtube.com/watch?v=iCZ__6LVhd8](https://www.youtube.com/watch?v=iCZ__6LVhd8)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/348e0c3521eb4a8e8ebb8a4528a8dbcb

### PlotSquared Version

6.0.9-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

N/A

**Comment by NotMyFault** [comment]
The setting is only for plots, turning this into a feature request.

**Comment by resi23** [comment]
I have a similar problem. I upgraded from 1.17 to 1.18. If I now merge 2 plots, there is no bedrock under the road. I have bedrock set to true. Here Screenshots before and after merge. PlotSquared-Version 6.7.1
![before](https://user-images.githubusercontent.com/1244755/168760879-50dff6fc-e5c1-4c42-bd41-3361979012b4.jpg)
![after](https://user-images.githubusercontent.com/1244755/168761027-7f97f129-7be2-4eef-973e-f9eaf81854b7.jpg)
