### ISSUE TITLE
Watchdog crash

### ISSUE THREAD

**Issue by tommasobenatti** [IntellectualSites/PlotSquared#3219]
### Server Implementation

Airplane

### Server Version

1.17.1

### Describe the bug

Sometimes when players do /p auto it happens a crash and the server lags for 20 secs

### To Reproduce

1. Have some players
2. Players do /p auto
3. The crash happens

### Expected behaviour

The server should not print the crashlog and it should not stop for 20 seconds

### Error log (if applicable)

https://paste.gg/p/anonymous/be64a531d6304778942621532c3202f2

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/f6c97dc0562044ff8d84c778a5b20b8a

### PlotSquared Version

6.0.9-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Unlisted server implementations are unsupported.

**Comment by tommasobenatti** [comment]
@NotMyFault it happens with latest paper too.....

**Comment by NotMyFault** [comment]
Then use paper and tick paper.

**Comment by tommasobenatti** [comment]
ok... u closed my issue
