### ISSUE TITLE
plot added limit

### ISSUE THREAD

**Issue by boy0001** [IntellectualSites/PlotSquared#322]
- limit number of plots a user can be added to
- limit number of users can be added to a single plot

**Comment by Sauilitired** [comment]
Limit the amount of users one can add, or limit the amount of plots one can be added to? Cause then a command to... "remove" yourself would be needed. It'd be smarter to limit the amount of people that can be added to a plot, but that might not be what we're looking for :)

**Comment by boy0001** [comment]
Having a leave command would be fine
