### ISSUE TITLE
Use WarpSystem API for teleports if installed

### ISSUE THREAD

**Issue by TheosisOfficial** [IntellectualSites/PlotSquared#3220]
### What feature do you want to see added?

This is probably quite a niche suggestion, but I think it would be extremely simple to add.

There's a plugin called [WarpSystem](https://www.spigotmc.org/resources/premium-warps-portals-and-more-warp-teleport-system-1-8-1-17.66035/) which is a general warp plugin but has cooldowns and particle effects etc. It also has [an API](https://github.com/CodingAir/WarpSystem-API) that can be used to handle teleports as an alternative to Spigot's [Entity#teleport](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Entity.html#teleport(org.bukkit.entity.Entity)) method which uses the cooldowns and particle effects.

My suggestion is for PlotSquared to hook into this API and use its teleport method for things like "/plot home", "/plot visit", etc. for servers which use this plugin and want consistency regarding teleports. Here's a snippet of code showing how this is done: https://pastebin.com/6N6AYPL1

### Are there any alternatives?

N/A

**Comment by NotMyFault** [comment]
Support for closed source software wont be considered.
