### ISSUE TITLE
"queue.lighting-mode" and "queue.update-edges" settings not working

### ISSUE THREAD

**Issue by TheosisOfficial** [IntellectualSites/PlotSquared#3221]
### Server Implementation

Spigot

### Server Version

1.17.1

### Describe the bug

These settings just do not work for me. I have tried all valid lighting-mode values and it doesn't make a difference, and setting update-edges to "true" doesn't either. I've brought this up in the Discord but apparently the settings worked fine in testing, which I don't understand because no matter what I try they don't work for me.

I've created a completely fresh test server to make certain that nothing was interfering, but no luck.

These screenshots show part of a plot before and after I used "/plot clear" and relogged, with lighting-mode set to "3" and update-edges set to "true":

Before:
![before](https://user-images.githubusercontent.com/26799016/132027580-6d8c3401-ed5c-43d1-92a1-ae7dee6de429.png)
After:
![after](https://user-images.githubusercontent.com/26799016/132027596-8addc3f3-f915-4b09-8d09-d43ffda925a1.png)

### To Reproduce

First, I would appreciate it if someone could download my test server. I don't want to post it here since it's public and obviously contains the PlotSquared plugin, so please either message me on Discord (Theosis#0001) or suggest another way I can get the test server to someone.

Once you download the test server...

1. Claim a plot
2. Place some blocks on the inside of it near the iron bar walls so that they "attach" to them
3. Use "/plot clear" and observe as the iron bars don't go back to their original block state
4. Relog and observe as lighting also did not update where the blocks were placed and cleared

### Expected behaviour

The block state of the iron bars should update, and lighting should update.

### Screenshots / Videos

Already in the "describe the bug" section.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/aab547c676b1459d817afb9eb005cf6d

### PlotSquared Version

6.0.9-Premium

### Checklist

- [x] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by dordsor21** [comment]
Still can't replicate this. Can you provide a log of a plot clear with this issue occurring? Also could you provide your worldedit configuration?

**Comment by TheosisOfficial** [comment]
My WorldEdit configuration is completely default - it hasn't been touched at all, but here it is anyway:
[WorldEdit.zip](https://github.com/IntellectualSites/PlotSquared/files/7129033/WorldEdit.zip)
I'm not sure what you mean by "a log of plot clear". Do I need to enable debug messages or something?

If you want I can send you my test server, because I know it can be replicated on there - perhaps it's because it is using a schematic?

**Comment by TheosisOfficial** [comment]
This issue is still present and can be reproduced.

**Comment by NotMyFault** [comment]
If someone else but the reporter can reproduce the issue, we will reopen it.
