### ISSUE TITLE
Pattern may not be null

### ISSUE THREAD

**Issue by SuperRonanCraft** [IntellectualSites/PlotSquared#3224]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

Every time the server starts up, this error just spews out and fill my entire console. Error log was attached below

### To Reproduce

Just start the server and once everything loads, this error spams the console

### Expected behaviour

I would like to not have these start up errors.

### Error log (if applicable)

https://bin.bloom.host/xexexasemo

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/e34fc325504544239118c98970b61293

### PlotSquared Version

6.0.9-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

Please let me know what causes this, I would like to not have to reset my world :)
Thank you in advance!

**Comment by NotMyFault** [comment]
You have lots of invalid material entries in your worlds.yml. Material fields like floor or filling take a material as input, not a percentage. See https://papermc.io/javadocs/paper/1.17/org/bukkit/Material.html for a list of valid materials.
