### ISSUE TITLE
/Plot clear getting stuck at x % (97.96)

### ISSUE THREAD

**Issue by ILikeOrangeJuice** [IntellectualSites/PlotSquared#3228]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

When trying to clear a plot it does get stuck at 97.96%, can not do new tasks on the plot until server restart. Server needs to be restarted, then I can clear it again and it if lucky works, but not always, same thing happens again basically.

### To Reproduce

No direct way since it is randomly happening.

### Expected behaviour

I expect the plot to be fully cleared and it being usable again.

### Screenshots / Videos

![](https://i.imgur.com/KbDKfmM.png)

### Error log (if applicable)

https://paste.gg/p/anonymous/f50cb4f5b5464737b0a87a7dfa8a0ef9

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/11a4d3e34b234ff5ade77648fc773f93

### PlotSquared Version

Latest from SpigotMC (Premium resource) - PlotSquared v6 6.0.9-BETA

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

A guess related to the issue, as stacked in the error log paste, is that lwc chests got removed and protections still persist due to whatever reason(prolly plot clear and not manually breaking to remove protections) and it bugs somehow like this, because I found 2 grass_block's at said locations, which I know were chests there and it being stated in the error ofc, so maybe it prevented it to finish the clearing process, cause the world/paper/we/p2 still thinks due to the protection that there are chests instead of the now set grass blocks? Idk if it makes sense, just trying to guess at this point and pin down anything I notice.
Sometimes it does help deleting the backup files of the Plot, while I doubt this has anything to do with it honestly.

I am running Java 16 on Paper 1.16.5 ([11:46:46 INFO]: This server is running Paper version git-Paper-788 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT) with the latest versions of Plotsquared V6 and (if this is the troublemaker in combination) LWC Extended latest version ( https://www.spigotmc.org/resources/lwc-extended.69551/ )

**Comment by NotMyFault** [comment]
Can you try that without LWC and regular WorldEdit instead of Awe?

**Comment by ILikeOrangeJuice** [comment]
I can remove said plugins for now and see if it still occurs, I update you if it does. As described I can not forcefully reproduce it, it happens giga randomly, I tried to reproduce every step as in above, but it worked fine, so there must be a special case when it happens, if that is what happens!

**Comment by ILikeOrangeJuice** [comment]
Hey,

so it seems like it happened again, even tho I MANUALLY removed all chests and protected blocks, so it can not be related to that, I did however remove AWE first, same result:
https://athion.net/ISPaster/paste/view/20005ffcf7b3429ba5d5a5c24ecdaf82
then I went further and removed LWC(X) and got the same result
https://athion.net/ISPaster/paste/view/46c3454c4b6c4b01a668988549d32f05

Also same % stuck, not a different one, just to mention it. But seems like neither 3rd source r related to it.

**Comment by NotMyFault** [comment]
Looking back on the screenshot you attached
![](https://i.imgur.com/KbDKfmM.png)
It doesn't look being stuck but being out of place? This appears to be the timer of the backup action which already reported itself as done.

**Comment by ILikeOrangeJuice** [comment]
Could be, would make also more sense for me not being able to perform any else clearing command, such as p clear, p delete and what not. 
So I suppose the timer is disfunctioning somewhere, atleast we/you can narrow it down more I guess?

Best regards

**Comment by NotMyFault** [comment]
If I remember correctly, I once encountered the same when working on v6 before its release, however, I neither now, nor back then I could reproduce the issue in a replicatable manner.

**Comment by ILikeOrangeJuice** [comment]
Since switching to 1.17.1 I have not encountered it anymore either, so far at least, so idk what has fixed it, if it is fixed, maybe some issue with 1.16.5
