### ISSUE TITLE
A collection of issues with plot world plots

### ISSUE THREAD

**Issue by nikitushu2** [IntellectualSites/PlotSquared#3231]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

During the `/plot setup ...` process only two questions are being asked (`void` and `name`), and then an empty world is being created (even if I set `false` to the `void` question), and an error appears:  [ https://paste.gg/p/anonymous/77c920036ac148feab597b958b2bdfea](https://paste.gg/p/anonymous/77c920036ac148feab597b958b2bdfea).

### To Reproduce

Follow the instructions to setup a plot world via `/plot setup` in the official wiki.

### Expected behaviour

1. More questions asked in `/plot setup ...`.
2. Working plot world created.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/4a4b9121f3dd462fa8f8dce0e8227dd6

### PlotSquared Version

Plotsquared 6.0.9-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by nikitushu2** [comment]
Not the plot world plot*

Just a usual world with plots because the plot world plot is created with a separate command afterward.

**Comment by NotMyFault** [comment]
Enabling plot world plots changes the setup generator to only create those plots, other options are no longer available at that time, hence I changed the title.

Tho, atm you can't create plot world plots thru the setup wizard at all. The settings I made can be obtained from my log: https://paste.gg/p/anonymous/ef6f8030cfc74586a06149735d2bf40b
This was supposed to create a non void plot world plot but I had to pull a -9 to actually make it stop.

**Comment by nikitushu2** [comment]
How do I create them then, if  Multiverse breaks their behavior too?

**Comment by NotMyFault** [comment]
> How do I create them then, if Multiverse breaks their behavior too?

Within the next update you can use the setup wizard again.
