### ISSUE TITLE
Plot claim price formula is not working

### ISSUE THREAD

**Issue by ILikeOrangeJuice** [IntellectualSites/PlotSquared#3234]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Using the claim price formatings for calculations do not work and error

### To Reproduce

Set the economy>Prices>Claim value to '{plots} <= 1 ? 0.0 : 50000.0' 

### Expected behaviour

to calculate it the right way and not throw a parsing error with it not recognizing the elements it does literally recommend me to use

### Error log (if applicable)

https://paste.gg/p/anonymous/5e5711ade65b459888509a1647cc974f

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/4f15091f9b4e4e45a20ce640b846ea8a

### PlotSquared Version

Latest from SpigotMC (Premium resource) - PlotSquared v6 6.0.9-BETA

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

If resolving the issue please be kind enough to post me a functioning version for the following schema: first plot = free, the ones after cost amount of plots * 50000 * amount of plots which would be 1 * 50000 * 1 then 2 * 50000 * 2 etc. 
Best regards

**Comment by NotMyFault** [comment]
Resolved on discord.
