### ISSUE TITLE
Make the "enabled-components.kill-road-mobs" setting not kill pets from SimplePets

### ISSUE THREAD

**Issue by TheosisOfficial** [IntellectualSites/PlotSquared#3240]
### What feature do you want to see added?

The title pretty much says it all. [SimplePets](https://www.spigotmc.org/resources/simplepets.14124/) is a plugin where players can summon their own pets to follow them around. For those who use this plugin but don't want regular mobs wandering around the road in their plot world(s), this would be a nice addition.

### Are there any alternatives?

N/A

**Comment by NotMyFault** [comment]
Named plugin already supports PlotSquared, they solely need to update their integration.
