### ISSUE TITLE
language configuration: "core.prefix" need "§" key for color codes

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquared#3242]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

Only the "core.prefix" message need the "§" key for color codes instead of "&".

### To Reproduce

lang.json:

```
[...]
  "core.prefix": "&6test prefix &4with color &2codes",
[...]
```

### Expected behaviour

prefix with colors

### Screenshots / Videos

![Screenshot 2021-09-11 224021](https://user-images.githubusercontent.com/4140635/132961093-7a6eb57b-4413-4847-8114-7d562c2432e2.png)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/b529b0ec713043dbaed55da02bf8a215

### PlotSquared Version

6.1.1

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

In other messages, the "&" codes works fine.

**Comment by NotMyFault** [comment]
Tested with `"core.prefix": "<gold>[<rainbow:2>P2</rainbow>] </gold>",`, can't replicate.
![](https://i.imgur.com/umylcn7.png)
Working as expected.
