### ISSUE TITLE
Unable to edit the max amount of players that can be trusted/added to a plot

### ISSUE THREAD

**Issue by SecretarySami** [IntellectualSites/PlotSquared#3248]
### Server Implementation

Purpur

### Server Version

1.17.1

### Describe the bug

When you have 1 person trusted to your plot already you are unable to do /plot trust (user) again as it says you've hit the limt
This is the same with having players added to the plot 

### To Reproduce

1. Trust/add someone to your plot 
2. Attempt to trust/add a second user to your plot  

### Expected behaviour

I would assume that you would be able to trust more than one person per plot 
As I can not find any of this in a config in order to change it either ?

### Screenshots / Videos

https://youtu.be/5JQIdo4I2SY

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/3c38994eca724406b87f85c41e239077

### PlotSquared Version

PlotSquared-Bukkit-6.1.1-Premium.jar

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Limits are controlled in the same way like plots are; check the wiki for more instructions.

**Comment by SecretarySami** [comment]
> Limits are controlled in the same way like plots are; check the wiki for more instructions.

honestly thank you xD I couldnt find it before and kept thinking it was in a config
much appreciated

**Comment by KhrysAK47** [comment]
> Limits are controlled in the same way like plots are; check the wiki for more instructions.



> > Limits are controlled in the same way like plots are; check the wiki for more instructions.
> 
> honestly thank you xD I couldnt find it before and kept thinking it was in a config much appreciated

I am having the same issue, is there a way for you to link the page where it talks specifically about that? Can't seem to locate it.

**Comment by GitPixelCode** [comment]
Currently found under: https://intellectualsites.github.io/plotsquared-documentation/commands.html#_trust

plots.trust.<amount> - Specifying the amount of people the plot owner can trust
