### ISSUE TITLE
Zombie horse and skeleton horse eggs still spawn mobs despite mob spawning being off

### ISSUE THREAD

**Issue by marvjosh1** [IntellectualSites/PlotSquared#3249]
### Server Implementation

Purpur

### Server Version

1.17.1

### Describe the bug

Although mob spawning from spawneggs is off, zombie and skeleton horses are still being able to be spawned

### To Reproduce

1 Go to a plot with mob spawning off
2 Try spawning any mob with a spawn egg and they dont spawn
3 Try spawning zombie & skeleton horses with spawn eggs and watch them spawn

### Expected behaviour

Zombie horses and Skeleton will not spawn just like other mobs

### Screenshots / Videos

https://youtu.be/QJkzVswF9fM

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/f02a4a3d49b843648aa109592b361cac

### PlotSquared Version

PlotSquared version 6.1.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
> 1 Go to a plot with mob spawning off

PlotSquared has no such flag.
