### ISSUE TITLE
Cannot place entities on road

### ISSUE THREAD

**Issue by Mr-Zeuro** [IntellectualSites/PlotSquared#3255]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

When you try to place entities on roads or unclaimed plots (for examle item frames) it is not possible. Altought al roadkill options in the settings.yml are disabled.

### To Reproduce

Try to place an item frame on the road or on unclaimed plots.

### Expected behaviour

The entity should spawn.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/27709a7a21714e7da7ebf23c03e7e507

### PlotSquared Version

PlotSquared-6.1.2-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Unclaimed terrain is not meant to be touched and therefore immutable to certain edits.

**Comment by PaBox** [comment]
There are flags for roads and as they are not documented well, one has to conclude they have to be the same for both roads and plots. Why can't all people be treated like guests on roads and server owners get the ability to use their rivers in their road schematic for boat travel - it is always possible to use caps and auto-entity-cleaning to kill entities on roads in the aftermath. 

How could it be intended, that with **every** permission given, an Admin can't even test boat travel and has to visit a plot - what is the point in having roads, if you cant ride them (for example with horses). Summon command is also not working so a lot of vanilla tactics are broken here. This may be easy to fix by modifying the `public void onVehicleCreate(VehicleCreateEvent event)` function in the [EntityEventlistener ](https://github.com/IntellectualSites/PlotSquared/blob/b43d08f4aa310982b8c83d725fba7323846fb4c0/Bukkit/src/main/java/com/plotsquared/bukkit/listener/EntityEventListener.java) - this would give the users more freedom and this is especially useful for worlds, where the roads are the only thing generated by PlotSquared (with normal terrain around them) and players might want to spawn in their horse or use their elytra, which is straightup impossible with plotsquared installed and standing on a road.

This problem can be mitigated by setting the road to a width of 0, killing most of the other features. So please explain in which way it is a feature to straightup suppress manual entity spawning for **everyone**.

**Comment by PaBox** [comment]
I have an upcoming holidy, so I might implement the solution and test it myself, as I am really hooked onto the topic of plotsquared's century old bugs.
