### ISSUE TITLE
/plot schematic paste not working

### ISSUE THREAD

**Issue by Xen0Xys** [IntellectualSites/PlotSquared#3256]
### Server Implementation

Purpur

### Server Version

1.17.1

### Describe the bug

When I try to execute command in my plot "/plot schematic paste", this display command usage and do nothing

### To Reproduce

Type /plot schematic paste
Wait command usage response

### Expected behaviour

Paste an existing saved shematic in the plot

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/d51ea62e42ca48ce8d6ad3ff6508770a

### PlotSquared Version

4.1.2-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
This has been resolved by now.
