### ISSUE TITLE
Error when buying a plot of land

### ISSUE THREAD

**Issue by 1Pootis1** [IntellectualSites/PlotSquared#3262]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

economy isn't initialized. make sure Vault and an economy service plugin are installed
I enter the command /p buy

### To Reproduce

1. enter /p f set price 1000
2. I am writing a command under another account with a balance of 1000: /p buy
3. see error

### Expected behaviour

Successful purchase

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/73141732/135000418-ca2cb492-1bdb-4049-a730-c396393da8cc.png)
![image](https://user-images.githubusercontent.com/73141732/135000909-ede3d512-9c04-42d9-a70d-dbc2ca7a84d4.png)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/a6ef9e92e67f44dc9a6104269432e0e8

### PlotSquared Version

PlotSquared version 6.1.3-SNAPSHOT

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

I have the Economy and Vault plugin

**Comment by NotMyFault** [comment]
Your economy settings aren't set up at all. You want to do so if you want to use economy features.
