### ISSUE TITLE
Hide vanished players from tab completion on disabled usercache

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#3263]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

If i go in vanish, players can see my name on /p v so players can see that iam online

### To Reproduce

1. Go in vanish Using some vanish plugin or player.hide()
2. Use 2th acc with no perms to check /p v

### Expected behaviour

Vanished players should be not visible in the tab complete

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/5d599ac2170542699edb7b59f1fbf983

### PlotSquared Version

6.1.2

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

It would be nice if support for vanish plugins can be added like PremiumVanish

**Comment by NotMyFault** [comment]
Vanish doesn't matter here, PlotSquared grabs the player name from the platform provided usercaches. You can tab complete names of players who are offline as well.

**Comment by DevJoey** [comment]
No, i have disabled "extended-username-completion" in config. It only shows players that are online
