### ISSUE TITLE
Roads Schematic Error (No decoration blocks)

### ISSUE THREAD

**Issue by Envqu** [IntellectualSites/PlotSquared#3269]
### Server Implementation

Purpur

### Server Version

1.16.5

### Describe the bug

When i want to create schematic for road with command 
`/plot createroadschematic`
i getting error in console:
`[PlotSquared/HybridPlotWorld] Error adding overlay block. `y > height``

When I do debugroadregen road doesn't contains any decoration blocks like pot, lantern etc.

### To Reproduce

Use command: /plot createroadschematic

### Expected behaviour

Beautiful roads.

### Screenshots / Videos

Expectation:
![image](https://user-images.githubusercontent.com/70281617/135692135-74d7f4fa-ee2b-46f2-a14f-9a03541b337a.png)

Reality:
![image](https://user-images.githubusercontent.com/70281617/135692153-959205c7-77a8-4c61-9159-b0c1bea8af1d.png)

### Error log (if applicable)

[PlotSquared/HybridPlotWorld] Error adding overlay block. `y > height`

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/fac4a1af7a954d99988a79d29da1804c

### PlotSquared Version

6.1.3

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by PierreSchwang** [comment]
Try to update FAWE

**Comment by Envqu** [comment]
Nah, still not working.
I even replaced FAWE with World Edit and there is the same situation when I trying to regen all roads.

**Comment by PierreSchwang** [comment]
Can you share your road schematic?

**Comment by Envqu** [comment]
https://drive.google.com/file/d/12eneIp7A1Ey8ADtLn7Ggcpp_7mL-XAxj
