### ISSUE TITLE
/p flag add use anvil dont respekt cracked/damaged anvils

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#3270]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

If i set the use flag to anvil, i cant use anvils anymore if they are damaged

### To Reproduce

1. Go gm 0
2. Place anvil on plot
3. Set use anvil
4. use the anvil until its damaged

### Expected behaviour

Anvils should still work if they are damaged because anvil is anvil

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/9c87a114ac6146bdaeeb543117a3c6d8

### PlotSquared Version

6.1.2

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
That's how Minecraft works, chipped and damaged anvils are separate blocks. If you want to cover those as well, either list them separately or use a block tag.
