### ISSUE TITLE
Toggle global chat

### ISSUE THREAD

**Issue by edyyy** [IntellectualSites/PlotSquared#328]
It would be amazing if there was a possibility to disable global chat. A lot of players dislike getting spammed while in plot chat. 

Or even making a GUI menu, this is what I used on plotme 
http://dev.bukkit.org/bukkit-plugins/plotme-chat

Simple GUI that let's you toggle both global chat and plot chat.

**Comment by boy0001** [comment]
note to self: use new attribute system for chat

**Comment by boy0001** [comment]
Added a while ago:
`/plot toggle chatspy`
