### ISSUE TITLE
"/plot download" returns error 400

### ISSUE THREAD

**Issue by MADS0LADEN** [IntellectualSites/PlotSquared#3296]
### Server Implementation

Purpur

### Server Version

1.17.1

### Describe the bug

Returns bad request when trying to download plot

### To Reproduce

Issue command /p download

### Expected behaviour

Return link to download the schematic file

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/c71c87874b5e4c73be3bd7becf33c3a3

### PlotSquared Version

PlotSquared-6.1.3-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Duplicate of https://github.com/IntellectualSites/Arkitektonika/issues/12
