### ISSUE TITLE
Teleportation to spawn when denied in plot

### ISSUE THREAD

**Issue by Theepwner** [IntellectualSites/PlotSquared#330]
Can you please make it so you teleport to the exact location of spawn? It's tping me in the middle of 4 blocks, and facing south when spawn is faced north.

This is what I mean by in the middle of 4 blocks: http://i.imgur.com/V9KLjbL.png

**Comment by boy0001** [comment]
note to self:
 - offset of 0.5x,z
 - use full location for teleportation

**Comment by boy0001** [comment]
Should have been fixed.
