### ISSUE TITLE
Container behavior with Instabreak

### ISSUE THREAD

**Issue by zOIDAdaJulian** [IntellectualSites/PlotSquared#3307]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

Chests, trapped chests and some other Containers doesn't drop the Items, when they are broken with the Instabreak Flag.
So, only the Container itself will drop and all of the items in there are gone.

### To Reproduce

1. Place A chest on cour Plot
2. Put some stuff in there
3. Activate the Instabreak Flag on your Plot
4. Break the Chest with Instabreak
5. Only the Chest will drop, all Items in there are gone

### Expected behaviour

In my Opinion the Items in the Chest should also be dropped.

### Screenshots / Videos

https://youtu.be/NF0WWEynMXk

### Error log (if applicable)

There are no Errors ;D

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/a8c6bec4b04e4b249f81a4ecb80a8860

### PlotSquared Version

PlotSquared version 6.1.3-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
This appears to be a Spigot bug. PlotSquared calls natural break if the instabreak flag is set.

**Comment by NotMyFault** [comment]
For the record, that has been resolved in https://github.com/PaperMC/Paper/commit/db0bff9c6ad42eefa22b094bb92df9bf3bc8ec66
