### ISSUE TITLE
Method of checking if the user is in a plot is laggy

### ISSUE THREAD

**Issue by JHarris12345** [IntellectualSites/PlotSquared#3311]
### Server Implementation

Invalid Airplane

### Server Version

1.16.5

### Describe the bug

With about 100 players online, the method for checking if an area is in a plot is extremely laggy 
![image](https://user-images.githubusercontent.com/46936647/139593670-fb58b213-25ab-4145-bc03-33c2a52b27af.png)

### To Reproduce

Have players
Lag

### Expected behaviour

No lag

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/45fef9d03b42439f986b5debd6241106

### PlotSquared Version

6.1.3-premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
You'll want to link the spark.

**Comment by JHarris12345** [comment]
https://spark.lucko.me/2imSCNzMdi
