### ISSUE TITLE
Flag untrusted-visit not working and superfluous permission

### ISSUE THREAD

**Issue by mindw0rm** [IntellectualSites/PlotSquared#3317]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

There are actually two issues, which are closely related and have the same reason:
1. untrusted-visit does not work anymore (if set to true, untrusted players can't teleport to the plot)
2. the permission plot.admin.visit.untrusted is superfluous, since plot.visit.other has been introduced

The problem is located here: https://github.com/IntellectualSites/PlotSquared/blob/v6/Core/src/main/java/com/plotsquared/core/command/Visit.java#L143
plot.visit.other is checked first, and if not given (which is usual for normal players, at least on our servers) the visit is denied, the checks for untrusted-visit and plot.admin.visit.untrusted will not be made. 

Note that for both plot.admin.visit.untrusted and plot.visit.other this is the only location where they are checked, so they obviously have the same usage, so there is no need to have them both. 

### To Reproduce

1. set untrusted-visit to true on an owned plot.
2. try to visit that plot with the `/plot visit` command with a second player that is not trusted on the plot -> visit is denied
3. give the second player the permission plot.admin.visit.untrusted
4. try to visit the plot -> still denied

### Expected behaviour

When untrusted-visit is set, untrusted players should be able to visit the plot. 

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/53f2e12f466148d3b215f33a23fedae4

### PlotSquared Version

tested with 5.13.12-premium, 6.1.3-premium and 6.1.4-snapshot

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

The two if clauses in https://github.com/IntellectualSites/PlotSquared/blob/v6/Core/src/main/java/com/plotsquared/core/command/Visit.java#L143 and https://github.com/IntellectualSites/PlotSquared/blob/v6/Core/src/main/java/com/plotsquared/core/command/Visit.java#L150 can be merged into a single clause, then the flag will work again (I tested this on my local test server, which is also the one who created the debugpaste above. On our online servers, we use the premium version, currently still 5.x for unrelated reasons).
I still have both permissions in my modification, but obviously you don't need both. However, I think it's up to you to decide which one you want to keep (I would keep plot.visit.other).

**Comment by NotMyFault** [comment]
Keeping the administrative permissions is redundant by now. Do you mind raising a pull request, since you already came up with a working solution?
