### ISSUE TITLE
Default teleport height should be plot height, not 0

### ISSUE THREAD

**Issue by TeddMC** [IntellectualSites/PlotSquared#3321]
### What feature do you want to see added?

Currently (in v6.4.1) when I do `/p home` it will teleport me to y=0 which is almost always inside of a solid block. The default teleport position height should be set at the height of the plot surface set in the worlds.yml config file instead.

### Are there any alternatives?

The alternative is to keep it how it is, where players are teleported to y=0 by default, which is super annoying as that is many (solid) blocks below the surface and is almost never useful.

**Comment by dordsor21** [comment]
Seeing a debugpaste would be useful. Either you have poorly configured P2, or this is a bug.

**Comment by NotMyFault** [comment]
This is a regression introduced in https://github.com/IntellectualSites/PlotSquared/commit/804228fa6cd2843864597f88317cbd3b7880dfa2

**Comment by NotMyFault** [comment]
Resolved in tagged commit.
