### ISSUE TITLE
Plot clear not working

### ISSUE THREAD

**Issue by Sckaletz** [IntellectualSites/PlotSquared#3323]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

Plot clear doesn't work. It returns this error:

https://pastebin.com/q0rBJ4xd

Using this version of FAWE: 

[16:47:21 INFO]: FAWE version:
 - Date Oct 21, 2021, 12:00:00 AM
 - Commit f7a8f6f5
 - Build 370
 - Platform Bukkit

And this version of Plotsquared:

[16:48:01 INFO]: >> PlotSquared (Version: PlotSquared-6.1.3-Premium)

Server versions:

[16:48:34 INFO]: This server is running Paper version git-Paper-349 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9472d38)

### To Reproduce

Just try to clear a plot with /plot clear

### Expected behaviour

Plot being cleared.

### Error log (if applicable)

https://pastebin.com/q0rBJ4xd

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/eeccae3bec3440269011078d0209da31

### PlotSquared Version

PlotSquared-6.1.3-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by PierreSchwang** [comment]
Update FAWE - Fixed in https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/3d70d9e496b1bfb5ba5e5ad1b4684466b69f10e4

**Comment by NotMyFault** [comment]
Also update Paper
