### ISSUE TITLE
Light Bug on Plot Delete

### ISSUE THREAD

**Issue by Strahilchu** [IntellectualSites/PlotSquared#3325]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

After deleting a plot, the lighting is messed up, this has been happening for a while and I am posting here to see if anyone has a solution or if this is a plugin thing?

### To Reproduce

Build house with lights or anything creating light or causing a shadow.

Run /plot delete

Observe plot lighting

### Expected behaviour

Clean plot with no trace of build ever being there

### Screenshots / Videos

![2021-11-08_07 11 17](https://user-images.githubusercontent.com/69178324/140748420-1184700f-7d27-41aa-b839-9789aaa2ba04.png)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/4610f989fb454fc3b0ea0d3c0d702537

### PlotSquared Version

PlotSquared (Version: PlotSquared-6.1.3-Premium)

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

Just want to know if this is an issue on my setup or if its a known plugin bug. As well as if anyone has any solutions or anything I should try?

Thanks in advance!

**Comment by InfectedCatBite** [comment]
> Just want to know if this is an issue on my setup or if its a known plugin bug.

Reported two weeks ago, and promptly closed - #3306 

> As well as if anyone has any solutions or anything I should try?

This plugin will fix up the lighting - https://www.spigotmc.org/resources/light-cleaner.42469/

**Comment by NotMyFault** [comment]
Which light sources did you have there?

**Comment by Strahilchu** [comment]
> Which light sources did you have there?

It doesn't seem to matter it does it even when there is no light source, just any blocks that were on the floor end up leaving shadows or anything that was floating and casting a shadow seems to remain. 

Very odd

**Comment by InfectedCatBite** [comment]
![2021-12-21_08 59 03](https://user-images.githubusercontent.com/93386304/146942895-d10f7667-b51b-4a0a-9d5a-37b20ded31d1.png)

**Comment by NotMyFault** [comment]
> ![2021-12-21_08 59 03](https://user-images.githubusercontent.com/93386304/146942895-d10f7667-b51b-4a0a-9d5a-37b20ded31d1.png)

It would help if you can provide the issue template instructions as well.

**Comment by InfectedCatBite** [comment]
git-Paper-408 (MC: 1.17.1)
PlotSquared 6.3.0
WorldEdit 7.2.8+6008-1246d61
AsyncWorldEdit 3.9.4
AsyncWorldEdit-ActionBarAPI 3.9.4
ProtocolLib 4.7.0
(no FAWE)

Before /p delete
![2022-01-19_10 40 02](https://user-images.githubusercontent.com/93386304/150184476-753c72f7-6c75-4edb-90de-9e694d109806.png)

After /p delete
![2022-01-19_10 40 13](https://user-images.githubusercontent.com/93386304/150184508-78351b93-402d-415b-a92b-c654c997aa3b.png)

**Comment by NotMyFault** [comment]
Can you replicate that with an [up to date version of WorldEdit](https://builds.enginehub.org/job/worldedit/19521) instead of AWE? Would be nice to have a `/plot debugpaste`, if it occurs, as well.

**Comment by InfectedCatBite** [comment]
I suppose I can try it on my test server (which is Win10, not Ubuntu), but this is generally hard to reproduce. I'll try to use a backup and find the same plot.

Why does PlotSquared care about WE/AWE for /plot delete?

**Comment by NotMyFault** [comment]
> Why does PlotSquared care about WE/AWE for /plot delete?

PlotSquared does not, we rely on what WorldEdit provides. However, AWE injects its stuff which caused issues in the past as well.
You can give it a try with FAWE as well if you like. FAWE has integrated support for Paper's native light engine.

**Comment by InfectedCatBite** [comment]
I think the problem occurs with Paper but not with Spigot. If I can reliably reproduce this, I'll try Spigot, too.

**Comment by InfectedCatBite** [comment]
OK, I tried removing AWE, using the WE snapshot you linked to, trying Spigot, then back to Paper with FAWE and Java 17, then Paper + WE snapshot with Java 17, then back to AWE.

The only combination that _worked properly_ was Paper + FAWE + Java 17.

I'm willing to send you the region/entity files if you want to use this as a test case. I guess you'd need the PlotSquared worlds.yml file so the plots would generate in the right places. If you're interested, let me know how I can send them to you.

**Comment by InfectedCatBite** [comment]
I just realized I can upload large files right to this issue. So here you go - The attached ZIP file should have everything you need to reproduce the problem. Let me know if you need anything else. Remember, do NOT use FAWE.

[Lighting bug.zip](https://github.com/IntellectualSites/PlotSquared/files/7907376/Lighting.bug.zip)
