### ISSUE TITLE
I cant use worldedit (/plot wea not working)

### ISSUE THREAD

**Issue by TangledWiresYT** [IntellectualSites/PlotSquared#3327]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

So I was trying to make a spawn area for my server, I tried using worldedit but I gto a message saying: "[P2] To bypass your restrictions use /plot wea" but when I use /plot wea it says its not a valid sub-command.

### To Reproduce

1. Create a world of plots.
2. Go to a different world and try to use worldedit.
3. Type /plot wea
4. It doesnt work

### Expected behaviour

I expected to be able to use worldedit and for /plot wea to be a sub-command

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/1763a2c6d6194161b080c576a3ab501f

### PlotSquared Version

5.13.13

### Checklist

- [X] I have included a Plot debugpaste.
- [x] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

I am using a minehut server. Not sure if that makes a difference.

**Comment by NotMyFault** [comment]
PlotSquared v5 is no longer supported.
