### ISSUE TITLE
Loading Problem

### ISSUE THREAD

**Issue by SkyShadowFlexX** [IntellectualSites/PlotSquared#3328]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

When i use a PSv6 Command its not Working.
Its send many, many Messages

### To Reproduce

Use a Command or Start the Server.

### Expected behaviour

Thats the Plugin loads and i can use Commands

### Error log (if applicable)

14.11 00:26:44 [Server] INFO unter java.lang.Thread.run(Thread.java:831) [?:?] 14.11 00:26:44 [Server] INFO bei net.minecraft.server.v1_16_R3. MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-788] 14.11 00:26:44 [Server] INFO at net.minecraft.server.v1_16_R3. MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-788] 14.11 00:26:44 [Server] INFO bei net.minecraft.server.v1_16_R3. MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-788] 14.11 00:26:44 [Server] INFO at net.minecraft.server.v1_16_R3. DedicatedServer.b(DedicatedServer.java:437) ~[patched_1.16.5.jar:git-Paper-788] 14.11 00:26:44 [Server] INFO at net.minecraft.server.v1_16_R3. DedicatedServer.handleCommandQueue(DedicatedServer.java:470) ~[patched_1.16.5.jar:git-Paper-788] 14.11 00:26:44 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3. CraftServer.dispatchServerCommand(CraftServer.java:788) ~[patched_1.16.5.jar:git-Paper-788] 14.11 00:26:44 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3. CraftServer.dispatchCommand(CraftServer.java:826) ~[patched_1.16.5.jar:git-Paper-788]14.11 00:26:44 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-788] 14.11 00:26:44 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.16.5.jar:git-Paper-788] 14.11 00:26:44 [Server] INFO org.bukkit.command.CommandException: Befehl 'p' kann im Plugin PlotSquared v6.1.5-SNAPSHOT nicht ausgeführt werden - Plugin ist deaktiviert.

### Plot Debugpaste

I cant use the Command

### PlotSquared Version

Newest V6 - I cant use the Command

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by dordsor21** [comment]
You haven't included a debugpaste and the log you _have_ pasted is undecipherable. Please follow the instructions properly.

**Comment by NotMyFault** [comment]
For questions, please use the [discord server](https://discord.gg/intellectualsites)
