### ISSUE TITLE
Mobs don't spawn on my Plot world!

### ISSUE THREAD

**Issue by midearthgamer** [IntellectualSites/PlotSquared#3329]
### Server Implementation

Spigot

### Server Version

1.17.1

### Describe the bug

I am using PlotSquared v6 and Monsters don't spawn on any plots.

### To Reproduce

I don't know how to reproduce the error

### Expected behaviour

I though monsters would spawn on everything in the Plot world and enabled it in the server config but nothing.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/93051912/141701802-6bb8200f-7451-437b-b9e8-cf4f4259c96b.png)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/3852e18c56ac4b66ab0b27026d009207

### PlotSquared Version

PlotSquared v5

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

the server is being hosted on Minehut so at posting date I cant get PlotSquared V6

**Comment by NotMyFault** [comment]
You're using PlotSquared v5 which is no longer supported. If you're updating to v6, you can use our [discord server](https://discord.gg/intellectualsites) for general questions.
