### ISSUE TITLE
PlotSquared not retaining names after server restart (BungeeCord server)

### ISSUE THREAD

**Issue by Holden92** [IntellectualSites/PlotSquared#333]
Hi, after each restart of a BungeeCord setup running a server with PlotSquared loses all names from each plot. 
I am using SQL for the database storage and it retains the UUIDs so when the player logs back in the plot recognises them as the owner and updates the name. However at next restart the name is then lost again. 

Is there a way I can fix this, what am I doing wrong?

Information:

Bungee config.yml = online_mode: true, ip_forward: true

Spigot.yml = bungeecord: true

server.properties = online-mode=false

PlotSquared settings.yml = 
UUID:
  offline: false
  force-lowercase: false
uuid:
  read-from-disk: true
plotme-convert: (not sure if relevant)
  enabled: true
  cache-uuids: false

(Sorry if I missed something crucial)

**Comment by Holden92** [comment]
Hiding the owners name from the hologram on entry has been a good temporary fix however I'd still really like to get it working. Thanks!

**Comment by boy0001** [comment]
PlotSquared depends on the playerdata being existent. If you delete the player data files for the server, then it will not remember the username.

**Comment by Holden92** [comment]
Hi boy0001, thanks for the response!

The playerdata is existent and hasn't been deleted.

I have set "read-from-disk: false" however it doesn't seem to be any different?

**Comment by boy0001** [comment]
It's possible that the UUIDs in the DB are stored in offline-mode, and that PlotSquared is thinking they are online-mode UUIDs. 

If you could check this, or send me a few UUIDs in the database that would help. If it turns out to be the case, you will need to configure PlotSquared to be offline-mode, and then use the uuidconvert command to switch to online-mode (if you desire)

**Comment by Holden92** [comment]
The UUIDs logged in the database are in online-mode, when searching them through an online searcher it is the correct UUID.

Everything about the plugin functions as it should, however when the server restarts it seems to forget the players Names attached to each UUID and sets the name back to Unknown. Then when the player comes back online, it replaces Unknown with their name.

**Comment by boy0001** [comment]
Can you post your startup log + full settings.yml please?

**Comment by Sauilitired** [comment]
@Holden92 I'll give this a day or so, but unless more information is provided I'll have to assume that it's fixed.

**Comment by Sauilitired** [comment]
I'm closing this, as more information is needed.
