### ISSUE TITLE
A couple of placeholders at `/plot info` are not replaced on manual entry

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#3339]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

If i use /p i size, the <size> variable is not replaced with the plot size

### To Reproduce

1. Type /p i size

### Expected behaviour

It must show the size of the plot. On unmerged plot it has to be show 1 and on merges the amount of plots

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/3e3fda787b4443519c0019a21c43a57a

### PlotSquared Version

6.1.4

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
The same applies to `likes`, `creationdate` and `inv`, though the latter just misses components.

**Comment by DevJoey** [comment]
> 
> 
> The same applies to `likes`, `creationdate` and `inv`, though the latter just misses components.

Yes, on creation date this is also be the case
