### ISSUE TITLE
/p i seen not working

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#3340]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

If i type /p i seen it shows "Nie" but the player is offline

### To Reproduce

1. Type /p i seen

### Expected behaviour

It must show the date the owner of the plot was last seen on the server

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/3e3fda787b4443519c0019a21c43a57a

### PlotSquared Version

6.1.4

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
`/plot info seen` is only available if you setup plot expiry, otherwise it will always default to "Never", like seen in `/plot info`.
