### ISSUE TITLE
/plot unclaim 

### ISSUE THREAD

**Issue by Tabletopcheese** [IntellectualSites/PlotSquared#3341]
### What feature do you want to see added?

A way for users to forfeit, giveup, and unclaim their plot. And then claim another. 

Almost like delete or set owner, but only valid for non-admins for their own plot. 

### Are there any alternatives?

I have been doing delete, but that is an admin command, as well as set owner 

### Anything else?

I just want them to be able to remove ownership of a plot, and then it deletes. But only for their plots

/plot unclaim

[System]: Are you sure you want to do this, this will erase the plot permanently.

/plot confirm

**Comment by NotMyFault** [comment]
> I have been doing delete, but that is an admin command, as well as set owner

`/plot delete` is not an administrative command, hence there are a bunch of dedicated permission nodes. Take a look at the wiki how to set it up properly: https://github.com/IntellectualSites/PlotSquared-Documentation/wiki/Commands#delete
