### ISSUE TITLE
Road gets placed one block further down than it should

### ISSUE THREAD

**Issue by EscolarProgramming** [IntellectualSites/PlotSquared#3346]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

After updating from PlotSquared 6.1.3 to 6.1.4, the road gets placed one block futher down than it should, when an interaction with the road happens (e.g. plot unmerge). Even "/debug roadregen" doesn't help. We haven't changed the road schematic. After downgrading back to 6.1.3, it works as it should.

### To Reproduce

1. Create a merge
2. Unlink or delete it
3. There you go

### Expected behaviour

The road should be generated on the same level than the other ones

### Screenshots / Videos

![Image](https://user-images.githubusercontent.com/6965961/143273493-a411656c-ce27-4795-bda2-c852ed93e807.jpeg)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/f6be46aaab1446f6a8392add90ff8924

### PlotSquared Version

6.1.4-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Take a look at your worlds.yml: the plot and road height are 62 blocks, the wall height are 61 blocks.

**Comment by EscolarProgramming** [comment]
But it's only with version 6.1.4, when we use the exact same files with 6.1.3, it doesn't happen!

**Comment by EscolarProgramming** [comment]
Thank you for re-opening this ticket! Should I provide you our PlotSquared and world files, so you can replicate it?

**Comment by EscolarProgramming** [comment]
With a little testing we found out the following: Since the 6.1.4 update, PS seems to use the edge height as the street height. If we set the border to height 62, the road is at the correct height, but the border is one block higher than the road.

**Comment by EscolarProgramming** [comment]
The problem seems to be in #3300. With that pull request, the calucaltion of the road height has been changed. See here https://github.com/IntellectualSites/PlotSquared/pull/3300/commits/658d5f9326e16e41a7295e23f44e8c0bf7944c5d#diff-cd31969ae49cbf1071b2053db320c9ef683c006623f40305d7704d3b258b64c9

**Comment by NotMyFault** [comment]
cc @dordsor21 Can you take a look? Works fine based on my prior testing.

**Comment by dordsor21** [comment]
This is/*was* an issue specifically when the road and wall are at different heights. The PR fixed issues where the schematic was cut off by the number of blocks difference if the schematic height was greater than 1. It technically now takes the lower of the two heights to start schematic creation. Remaking the road schematic will fix this, else I will quickly add a config option to force road schematics to be set from the road height, rather than the lower of road and wall.

**Comment by PierreSchwang** [comment]
> A config option would be very nice! Thanks in advance.

A config option was already added in the pull request
