### ISSUE TITLE
Plotz To Plotsquared Converter

### ISSUE THREAD

**Issue by wilsondc15** [IntellectualSites/PlotSquared#335]
I, along with other server admins with Plotz installed, would like to migrate to Plotsquared just like Plotme users have, but we cannot because there is not a converter available. I cannot lose my players by deleting all plots and starting all over again with Plotsquared, so this is the only possibility.

I am requesting a Plotz To Plotsquared converter.

Thank you!

**Comment by boy0001** [comment]
Plotz is closed source / paid.

**Comment by wilsondc15** [comment]
He has an extensive api available for the public here:
http://www.spigotmc.org/wiki/plotz-api/

**Comment by boy0001** [comment]
I'm aware of that, seeing those words on a page doesn't change that it's closed source.

Anyway, I'll see what I can do, you never know what you can find lying about on the internet. ;)

**Comment by wilsondc15** [comment]
Thank you for your support! ;)

**Comment by boy0001** [comment]
Would you be willing to test conversion sometime soon?

**Comment by boy0001** [comment]
Done:
https://www.spigotmc.org/resources/plotzsux.9563/

**Comment by wilsondc15** [comment]
You are a godsend! Thank you so much for making this. I would be happy to
test conversion out for you. Again, you do not know how thankful I am for
this.

**Comment by EvilOlaf** [comment]
Well, if ya gotta go, ya gotta go ^^
