### ISSUE TITLE
plot purge with optional unknown: argument doesn't work

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/PlotSquared#3353]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

When using `/plot purge world:plotsquared unknown:true clear:true` the command doesn't work and just prints the command usage again

![Untitled](https://user-images.githubusercontent.com/10485646/144450239-2d14cf79-0e41-413b-86b8-4e1dd0edeb1a.png)

By removing the optional unknown argument the purge command works. I'm not sure if the `unknown:` argument is no longer supported or if it just doesn't work but if it's no longer supported then removing it from the command usage would be helpful

### To Reproduce

1. Use `/plot purge world:[worldname] unknown:true clear:true`

### Expected behaviour

Command usage shouldn't show `unknown:` as a valid optional argument if it is no longer supported

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/a3f2db337da341f2968b6f6f00e84f97

### PlotSquared Version

PlotSquared-Bukkit-6.1.4-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
`unknown` is not implemented. Looking thru the history back to early 2020, it doesn't exist there either.

**Comment by yannicklamprecht** [comment]
It was removed in 8efc78e1c95c1114b4f56fb1ed4e5619b72028e4

Functionality was:
- if unknown is active, all plots that doesn't have an owner with a name are added to the purge list. In other words owner where the name isn't cached.

Triggered part of the UUIDHandler at that time.
https://gist.github.com/yannicklamprecht/b4f8e7dae53440681c1693d324d3c24b
