### ISSUE TITLE
Parked thread on world generation

### ISSUE THREAD

**Issue by PalmTamino** [IntellectualSites/PlotSquared#3376]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

The server just crashes when it generates new terrain. 

Video will explain everything

### To Reproduce

Dont know if it is reproducable on your side, but for us everytime:

1: Go to citybuild
2: Generate new chunkes
3: Server hangs, and then crashes.

### Expected behaviour

NO CRASH

### Screenshots / Videos

https://streamable.com/ghvcl4

### Error log (if applicable)

https://paste.gg/p/anonymous/15c967c8af944ecc91a2650645322370/files/2f3a9725d3744bc5a4265079b838e833/raw

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/9a79e6197522493d9582456d77f972f4

### PlotSquared Version

PlotSquared-Bukkit-6.2.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Your server didn't react fast enough to generate new chunks so the thread has been parked. General gist is to pregenerate a world and setting up a world borlder, chunk generation is a resource intensive task you don't do if anything goes on the server.

**Comment by PalmTamino** [comment]
> Your server didn't react fast enough to generate new chunks so the thread has been parked. General gist is to pregenerate a world and setting up a world borlder, chunk generation is a resource intensive task you don't do if anything goes on the server.

This is not true!! I have lands on another server, that runs on the same VM, and it just works! This crash is a bug on your side, not on ours. The Servers we use are fast enough to handle world generation by one player, and it also crashes even if one new chunk is only generated.

+ But then i made /spawn, so the server would normally just stop to generate new terrain, this is a proof that this is not our issue.

**Comment by Whitescan** [comment]
> > Your server didn't react fast enough to generate new chunks so the thread has been parked. General gist is to pregenerate a world and setting up a world borlder, chunk generation is a resource intensive task you don't do if anything goes on the server.
> 
> This is not true!! I have lands on another server, that runs on the same VM, and it just works! This crash is a bug on your side, not on ours. The Servers we use are fast enough to handle world generation by one player, and it also crashes even if one new chunk is only generated.
> 
> But then i made /spawn, so the server would normally just stop to generate new terrain, this is a proof that this is not our issue.

I agree. It still should not crash when generating just one chunk. It's not "that heavy" for the latest Paper 1.17.1 Build on a decent CPU to generate chunks around one single player.

**Comment by NotMyFault** [comment]
I suggest you read what I recommended.
