### ISSUE TITLE
Sell PlotSquared on more sites than just spigotmc.

### ISSUE THREAD

**Issue by JasonTable** [IntellectualSites/PlotSquared#3379]
### What feature do you want to see added?

I have no problem paying for this plugin. I compiled it from source code to test it out and I think its a great plugin. However I don't like the spigotmc website. They deceive users into signing up BEFORE telling them that a plugin is paid. This may mislead a user into believing that all they have to do to download the plugin is create an account. It wastes the time of users who would not be willing to pay. That makes me want to avoid supporting them out of principle.

### Are there any alternatives?

One alternative website i recommend selling on is itch.io. It's a video game marketplace however people can also sell game mods, game assets, and other stuff on there. I think this plugin would go in the game mods category. A minimum price can be set and uses can choose to pay more if they want. The page can be customized with HTML and images and potential customers will get to see that page BEFORE signing up. So you can sell them on the features before their time is wasted.

**Comment by NotMyFault** [comment]
PlotSquared does not wrap around being sold across many platforms but to support the people behind it.
Yet I use itch.io personally from time to time, we have no plans to start using different services actively.
SpigotMC is totally fine for our needs.

**Comment by MattBDev** [comment]
Hopefully, Hangar will be ready sometime early next year so we can explore using that too.
