### ISSUE TITLE
Getting kicken when attempting to do any /p command that has an arg

### ISSUE THREAD

**Issue by Chaoshero5567** [IntellectualSites/PlotSquared#3380]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

When i want to type /p a or any plotsquared command that has an arg i am getting kicked from the server, idk if the plugin has problems with cloudnet or paper or viaversion because when i break the cloudnet perms system on the citybuild server plotsquared functions without problems

### To Reproduce

1.Join server
2.type /p [any arg or just space]
3. gett kicked

### Expected behaviour

Not getting kicked

### Screenshots / Videos

https://user-images.githubusercontent.com/79978761/146635485-b833ed8d-8201-4276-9dbc-0a9e12ca6224.mp4

### Error log (if applicable)

none

### Plot Debugpaste

none

### PlotSquared Version

PlotSquared version 6.2.1-Premium

### Checklist

- [ ] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

I cant proviede any debug because you know, i cant tpy any args

**Comment by NotMyFault** [comment]
Please don't tick checkboxes you didn't follow. Reverting for now, until the debugpaste has been provided.

**Comment by Chaoshero5567** [comment]
[09:53:17] [Server thread/INFO]: [P2] Usage: /plot debug <loadedchunks | player | debug-players | entitytypes | msg>
[09:53:17] [Server thread/INFO]: [P2]  Debug Information

>> PlotArea
>> Plot Worlds: 

>> Owned Plots: 0

>> Messages
>> Total Messages: 711
 Here you go

**Comment by NotMyFault** [comment]
The command is `/plot debugpaste`

**Comment by Chaoshero5567** [comment]
> /plot debugpaste

Oh ok, sry I am on mobile Right now

**Comment by Chaoshero5567** [comment]
Going to do it when I am back home

**Comment by Chaoshero5567** [comment]
This comment does not exist lol

**Comment by NotMyFault** [comment]
If you are unable to execute that command, https://paste.gg/ your latest log you can find in the `logs/latest.log` location.

**Comment by Chaoshero5567** [comment]
https://paste.gg/p/anonymous/e632730942ab4d9aa6feedd55f2eb09d

**Comment by NotMyFault** [comment]
That is only a part of it. Update WorldEdit, execute the command and provide the full log.

**Comment by Chaoshero5567** [comment]
That is the full log

**Comment by NotMyFault** [comment]
Please read again what I said and provide the requested information.

**Comment by Chaoshero5567** [comment]
i am updating it, but when you said thats only a part of it, and later provide the full log i felt like you meant that i didnt give you the full log

**Comment by NotMyFault** [comment]
I was referring to you stating that named command doesn't exist, but your log does not indicate that you executed named command, so I asked for the full log implying that are only parts of it.

**Comment by Chaoshero5567** [comment]
because the log is even newer, then the one where i tpyed the command into the console

**Comment by Chaoshero5567** [comment]
Ahh ok i think i had an typing error, here you go: https://athion.net/ISPaster/paste/view/80aa9559bb8d4fc5bc510207d3c54e18

**Comment by NotMyFault** [comment]
Take a look at your worlds.yml, according to the paste, there's only 1 entry present. Whether that is relevant to the origin issue, I can't say for sure, but I can guarantee it leads to unwanted side effects. Maybe something went wrong during its initial generation.
Once you got that sorted, you can try removing all plugins but PlotSquared and Fawe and see if you can replicate it in a clean environment.

**Comment by Chaoshero5567** [comment]
but when i remove all plugins my permissions are gone

**Comment by Chaoshero5567** [comment]
ahh op command yeah, one moment

**Comment by Chaoshero5567** [comment]
Still same problem... there are only three plugins, worldEdit plotsquared and cloudnet bridge what i cant remove because thats littelery the plugin that is needed to use it with the cloud and the cloud puts it in automaticly

**Comment by Chaoshero5567** [comment]
![image](https://user-images.githubusercontent.com/79978761/146643160-abd0a9cf-6a2f-47b8-8e00-d216ccb610e3.png)

**Comment by NotMyFault** [comment]
Then setup a local server without it please, I'm unable to replicate it in a clean environment.

**Comment by Chaoshero5567** [comment]
one moment then

**Comment by Chaoshero5567** [comment]
yeah its the cloudnet bridge plugin....

**Comment by Chaoshero5567** [comment]
i am going to seek support there then
