### ISSUE TITLE
Clear, reset not working.

### ISSUE THREAD

**Issue by download042** [IntellectualSites/PlotSquared#3396]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

Hi!
My players can't reset or clear their plots:
"A set block timer is bound to either the current plot or you. Please wait for it to finish"
After this message nothing happens.
What causes this problem, and how to fix this?
Pls @mention me when answering.
Paper version git-Paper-400 (MC: 1.17.1), without bungee.
PS: 6.2.1-Premium
WE: 7.2.8+6008-1246d61 

### To Reproduce

...

### Expected behaviour

...

### Error log (if applicable)

Sadly there is no error in console.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/6c441513ecc94d28b2cb82840506e17d

### PlotSquared Version

 6.2.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Moved to discord.
