### ISSUE TITLE
light of the torques is not generated in road schematics

### ISSUE THREAD

**Issue by F-TownGaming** [IntellectualSites/PlotSquared#3408]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

when I set up torches on my streets, they make a normal cone of light but when I then have the streets made in plotsquared, the torches have no cone of light

### To Reproduce

when I set up torches on my streets, they make a normal cone of light but when I then have the streets made in plotsquared, the torches have no cone of light

### Expected behaviour

I expected that all the torches in the streets would generate a cone of light

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/e55f2d011b954b77b0256514c3647a78

### PlotSquared Version

6.2.1

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by dordsor21** [comment]
This is not something we are able to control and is a limitation of the spigot generation engine.
