### ISSUE TITLE
GriefPrevention Support?

### ISSUE THREAD

**Issue by wattywatty14** [IntellectualSites/PlotSquared#3415]
### What feature do you want to see added?

It turns out that players can claim plots using GriefPrevention. I was wondering if GriefPrevention support could be added to prevent this?

### Are there any alternatives?

No...

**Comment by NotMyFault** [comment]
Which goal does that actually target? Commonly you don't run several claiming plugins alongside, especially not in the same world.

**Comment by joex92** [comment]
@wattywatty14  you can set the plot world as not claimable by GP on GP settings file... that's what i did... on my normal survival world I set GP and on PS I disabled GP... makes no sense to add support to use it...
