### ISSUE TITLE
Force roads to be generated in the plot

### ISSUE THREAD

**Issue by TheIntelloBox** [IntellectualSites/PlotSquared#3416]
### What feature do you want to see added?

Here is the example of my feature request:

What I built:
https://zupimages.net/up/21/52/j2f0.jpg

When I generate it by using commands:
https://zupimages.net/up/21/52/483i.jpg

As you can see, a road with a non-common shape will not generate correctly. I suggested adding the possibility to make custom plot shapes but you said that it isn't a priority.

### Are there any alternatives?

No

**Comment by dordsor21** [comment]
This can be achieved using plot schematics (though the player will obviously be able to remove any road that is on their plot)

**Comment by TheIntelloBox** [comment]
> This can be achieved using plot schematics (though the player will obviously be able to remove any road that is on their plot)
![image](https://user-images.githubusercontent.com/16572147/147770932-a5da8327-f7bb-47cb-b92a-69891a6feb05.png)
![image](https://user-images.githubusercontent.com/16572147/147770946-09fa378e-3122-4ae0-932a-7fe5cfe417a8.png)

**Comment by TheIntelloBox** [comment]
Anyone can help me ?

**Comment by dordsor21** [comment]
This is already possible. For support on how to do it, visit the Discord
