### ISSUE TITLE
Plot Music should not be a pain with stereo audio

### ISSUE THREAD

**Issue by downloadpizza** [IntellectualSites/PlotSquared#3422]
### What feature do you want to see added?

Plot music is placed at the point where the player enters the plot.
This makes it so that with headphones, one side can be louder than the other (total loudness stays the same).
[relevant line of code](https://github.com/IntellectualSites/PlotSquared/blob/47ae79e1231dcbe12be354759d7ca02f36bfae0d/Core/src/main/java/com/plotsquared/core/listener/PlotListener.java#L281)

Now, this can actually be fixed by placing the sound source far above the player (at the center of the plot).
What I did notice is that bukkit is weirdly missing the `minimumVolume` argument for playSound. But im sure there is a distance where it doesnt go quiter. Maybe someone can go whine to the bukkit people.

### Are there any alternatives?

No

### Anything else?

https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Player.html#playSound(org.bukkit.Location,java.lang.String,float,float)
^ source for my claims about bukkit

**Comment by downloadpizza** [comment]
Ok I tried this: `/playsound music_disc.pigstep master @p ~ ~100000 ~  340282300000000000000000000000000000000 1.0` (340... is about float max value, so just keep using that) and its hearable for a looooooooooooong distance (at last 7500 blocks). So if you just set the position to the center of the plot and as far high up as is reasonable you should be good.

**Comment by downloadpizza** [comment]
Ok there is basically no limit to this. Im at one corner of the world (postive, positive) and I ran: `/playsound music_disc.pigstep master @p 29999999 340282300000000000000000000000000000000  29999999  340282300000000000000000000000000000000 1.0` which has the same volume as everything else and there is **barely** a change in direction when spinning.
I may do a PR, but im too tired for today, should be a simple fix.

**Comment by downloadpizza** [comment]
Oh also apparently the y coordinate still goes way higher? I need to find the max for that

**Comment by downloadpizza** [comment]
Also an interesting thing: it looks at least semi correct in this commit: `https://github.com/IntellectualSites/PlotSquared/blob/289527b8e51fe0326202e8c86f88e60dc043b24a/PlotSquared/src/main/java/com/intellectualcrafters/plot/listeners/PlotListener.java` where it plays at a y of at least 240, or higher if the player enters higher. Ima write a PR to set it to max height

**Comment by NotMyFault** [comment]
The example steps to reproduce and plot music sound the same for me for different sound profiles. I quite don't understand the actual goal either, this RFE is blocked and needs major clarification and justification.

**Comment by StealWonders** [comment]
I can confirm this. Whenever you enter a plot with music the music location is set to the entry location.
This means that with stereo headphones if you go to the other side of the plot and turn your head (in-game) you will hear the music very loud on one ear and if you turn your head 180 degrees in the other direction on the other ear. This is very unpleasant.
