### ISSUE TITLE
`notify-enter` and `notify-leave` send three messages when teleporting to plot from different world

### ISSUE THREAD

**Issue by Xaver106** [IntellectualSites/PlotSquared#3424]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

On a Plot that has both `notify-enter` and `notify-leave` set to true, three messages instead of one.
`notify-leave` seems to remove a player from a plot again and then teleporting them back on. `notify-enter` does not have that problem.

### To Reproduce

1. Set both `notify-enter` and `notify-leave` to true on a plot.
2. teleport a player to another world! (player shouldn't have bypass permissions)
3. teleport player back on the plot.
4. three messages appear, instead of one.
5. repeat same process with only `notify-enter`, and everything works as intended.

### Expected behaviour

only the `notify-enter` message should be send.

### Screenshots / Videos

The three messages when teleporting player from different world to the plot:
![image](https://user-images.githubusercontent.com/46501008/147884418-73f18325-edcc-4b0b-9599-d1e51f2fd78a.png)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/4a2b6c24924845bd82fd5bc1258fa639

### PlotSquared Version

PlotSquared version 6.2.2-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
I can replicate that, I'll label it as "Bug" for now, but I can't tell out of my mind if we actually refresh the player meta on world teleports.

**Comment by RedstoneFuture** [comment]
I got the info, that the bug is happened too, if you are in another world and teleport you to the plot with a Warp or e.g. "/p v" (not tested).

**Comment by QuickWrite** [comment]
This is also the case with the `greeting` and `farewell` flag.
