### ISSUE TITLE
the colors & in the greeting stopped working

### ISSUE THREAD

**Issue by 1Pootis1** [IntellectualSites/PlotSquared#3439]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

![image](https://user-images.githubusercontent.com/73141732/148662878-06715c48-dcc9-4a00-b1ed-3b735dd0b03c.png)
I put a greeting with &7 - does not work

it only works like this:
![image](https://user-images.githubusercontent.com/73141732/148662902-1846e71c-40ee-4333-9598-f3679a0836c4.png)
it's inconvenient for my players

**and so with ALL the colors**

### To Reproduce

1. /p f set greeting &7text
2. watch the chat

### Expected behaviour

grey text

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/73141732/148662926-9b1bcfb0-7b4e-49f1-8129-7ade74d9e05d.png)
![image](https://user-images.githubusercontent.com/73141732/148662927-da61f18c-b92f-4dc6-aa2c-f1643962c007.png)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/80d377bd8ba64c569d526003a5b6722a

### PlotSquared Version

PlotSquared version 6.2.3-SNAPSHOT

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
PlotSquared doesn't use legacy color codes to style its messages, you need to use [MiniMessage](https://docs.adventure.kyori.net/minimessage#color).
