### ISSUE TITLE
Augmented World Gen Generates Terrain Over Roads

### ISSUE THREAD

**Issue by kwilson7770** [IntellectualSites/PlotSquared#344]
I tried creating a plot world with some instructions I found here (http://www.spigotmc.org/threads/plotsquared.29970/page-37)

I ran these commands in my console (first world)

plot setup
plot setup PlotSquared
plot setup AUGMENTED
plot setup ROAD
plot setup 64
plot setup 150
plot setup 1
plot setup 2
plot setup 44
plot setup 44:1
plot setup 19
plot setup 64
plot setup 173
plot setup 1
plot setup 64
plot setup true
plot setup Plots

after world gen before loggin in:
plot regenallroads Plots

I ran these commands in my console (second world)

plot setup
plot setup PlotSquared
plot setup AUGMENTED
plot setup ROAD
plot setup 64
plot setup 150
plot setup 1
plot setup 2
plot setup 44
plot setup 44:1
plot setup 19
plot setup 64
plot setup 173
plot setup 1
plot setup 64
plot setup true
plot setup Plots

after world gen before loggin in:
plot regenallroads Plots

The problem is that (while not always the case) some parts of  the roads will have natural terrain that was generated over them

http://i.imgur.com/T8P3Kb9.jpg
http://i.imgur.com/SCw7lUu.jpg
http://i.imgur.com/W1MznUn.jpg
http://i.imgur.com/pgbGcmV.jpg

Which is fine all things considering, but it will be annoying deleting it when people complain about it (it is bit ugly). World being over the road was near spawn (0.0) leaves was everywhere

**Comment by Sauilitired** [comment]
I think it is pretty safe to close this as it's been more than 3 years since it got submitted.

**Comment by chedadmin** [comment]
I am having this exact problem and came across this thread whilst searching for answers.
