### ISSUE TITLE
nicknames in small letters

### ISSUE THREAD

**Issue by 1Pootis1** [IntellectualSites/PlotSquared#3440]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

my admin nickname is written in capital letters, or else the player's nickname has capital letters, but for some reason ALL the letters are written in small

**There was no such thing on version 6.1.3, I installed a new 6.2.3 and I have such a problem**

### To Reproduce

1. /plot info

### Expected behaviour

ADMIN 
TimeLike
![image](https://user-images.githubusercontent.com/73141732/148663061-883ce9b1-4f88-4389-aca9-66cf4656d7a7.png)

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/73141732/148663061-883ce9b1-4f88-4389-aca9-66cf4656d7a7.png)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/000939a3db9e43b6aa8c92c7f14bbb1e

### PlotSquared Version

PlotSquared version 6.2.3-SNAPSHOT

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
PlotSquared does not list nicknames but the actual player name. This looks like typical offline mode shenanigans.
