### ISSUE TITLE
Unknown plots not responding to any commands

### ISSUE THREAD

**Issue by iLemon** [IntellectualSites/PlotSquared#3443]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

I have a strange problem with an old plotworld (many years old), where hundreds of plots on the world are empty, in claimed state and have 'Owner: unknown'.

If I type commands such as `/plot info` while standing on the plot, nothing happens, no error in the console. If I type a command like `/plot claim` while standing on a broken plot, it will say "This plot is already claimed".

I have tried running the plugin with `uuid-cache-size: 0` and `uuid-cache-size: 100000`

I also tried disabling all UUID services except luckperms (in case one of them was giving bad data?):
``` 
  # Whether the PaperMC service is enabled
  service-paper: false
  # Whether the LuckPerms service is enabled
  service-luckperms: true
  # Whether the Bukkit service is enabled
  service-bukkit: false
  # Whether the EssentialsX service is enabled
  service-essentialsx: false
```

### To Reproduce

Not exactly sure how to suggest reproducing this. I'm happy to assist in trying different fixes on the live server.

Here are the database files:
**storage.db**
https://www.dropbox.com/s/w6yzi07hcbz3plc/storage.db?dl=0
**user_cache.db**
https://www.dropbox.com/s/rrku5ymlv4tgr4b/user_cache.db?dl=0

### Expected behaviour

The plot should recognize it's owner and be loaded in properly.

Most of these plots are empty and by inactive players, so this bug is stopping them from being purged for inactivity.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/18317307/148795951-73fb6541-50f4-4259-9d33-c4d65ef48064.png)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/9d6f87b791a34424bea841ccca6812d3

### PlotSquared Version

PlotSquared version 6.2.2-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by iLemon** [comment]
I'm wondering if this might happen because the player who owns the plot has never joined the server? We've reset player data previously but kept their plots and some players never rejoined.

If this is the case, could we add a way to expire the unknown plots?

**Comment by dordsor21** [comment]
> I'm wondering if this might happen because the player who owns the plot has never joined the server? We've reset player data previously but kept their plots and some players never rejoined.
> 
> If this is the case, could we add a way to expire the unknown plots?

This may be an issue with the UUID attempting to be resolved but failing silently. (perhaps use of the wrong UUID service?).

RE: expiring unknown plots, you should be able to use `/plot purge unknown` upon release of 6.2.3

**Comment by PierreSchwang** [comment]
> This may be an issue with the UUID attempting to be resolved but failing/timing out silently. (perhaps use of the wrong UUID service?).

The linked owner in the database should be resolved by the user cache nevertheless 
![grafik](https://user-images.githubusercontent.com/27054324/148814670-a6ca6855-1c7f-4747-a604-05526915111f.png)
![grafik](https://user-images.githubusercontent.com/27054324/148814710-199d9f9a-ebe2-4784-b6d6-c7419514c0ae.png)


And shouldn't a timeout of the UUIDPipeline throw an exception or at least print an error?

**Comment by PierreSchwang** [comment]
I can confirm this issue now with setowner. The underlying UUIDService responds well. `UUIDPipeline#getUUIDs(Collection)` completes as well using `CompletableFuture.completedFuture(mappings)` (L397)

The `CompletableFuture#whenComplete` in `UUIDPipeline#getSingle(String, BiConsumer)` doesn't seem to be called.
