### ISSUE TITLE
NPE when trying to use /plot music

### ISSUE THREAD

**Issue by ILikeOrangeJuice** [IntellectualSites/PlotSquared#3454]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

When using /plot music you get an internal error message ingame and a NPE in the console.
Once this happened any other try of /plot music results in nothing happening at all until you relog.

### To Reproduce

Log on,
Typ /plot music,
Error.

### Expected behaviour

I expect it to open a music selection interface and to play some music in the plot.

### Screenshots / Videos

-

### Error log (if applicable)

https://pastebin.com/F8jYM2ny

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/320daa712822401aa94acd4f96acdc00

### PlotSquared Version

6.3.0

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
This is a regression of https://github.com/IntellectualSites/PlotSquared/pull/3446
Though said, similar stuff may happen for other music discs on older versions.
