### ISSUE TITLE
Add fishing flag

### ISSUE THREAD

**Issue by EscolarProgramming** [IntellectualSites/PlotSquared#3455]
### What feature do you want to see added?

It would be very good if there was a flag to control whether people who are not trusted can fish on the Plot. 

### Are there any alternatives?

Currently, players must be trusted to fish

**Comment by NotMyFault** [comment]
That sounds like a good idea, to note if someone looks forward to work on it, the flag addition needs a proper handling with the `.projectile.` permissions to not cause conflicts.
