### ISSUE TITLE
PlaceholderAPI integration does not work for flags

### ISSUE THREAD

**Issue by mrcoffee1026** [IntellectualSites/PlotSquared#3465]
As described [on the wiki][https://github.com/IntellectualSites/PlotSquared-Documentation/wiki/Placeholders#overview], the PlaceholderAPI integration does currently not work for flag parsing.
Testing with PlotSquared 6.3.0 and PlaceholderAPI 2.11.1, `/plot flag set greeting Welcome %player_name%` doesn't resolve the player name.
The necessary `Player` expansion has been downloaded via `/papi ecloud download Player`, version 2.0.2.

**Comment by NotMyFault** [comment]
Apparently this is a regression from https://github.com/IntellectualSites/PlotSquared/commit/6528c60f4d8a8c31f850d71170b0667748a650c7
