### ISSUE TITLE
Using lead to move mobs to others plots

### ISSUE THREAD

**Issue by KyGuy2002** [IntellectualSites/PlotSquared#3477]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

Mobs are killed on the road, but if the mob goes fast enough they aren't.  A mob on a lead can go fast enough when a player flies.

### To Reproduce

1. Spawn mob in your plot
2. Attach the lead to mob and player
3. Fly up so the mob is off the ground
4. Fly quickly across the road
5. Slowly go down to drop the mob
6. Detach the mob from the player by breaking the lead (Cannot just click since plot flags disallow it)the 

### Expected behaviour

The mob is killed as soon as it's over the road.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/9463add142a64e86a78d19dff7c74d7b

### PlotSquared Version

6.3.0-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by RedstoneFuture** [comment]
It's a known problem, but it seems impossible to fix it for 100%.

https://github.com/IntellectualSites/PlotSquared/issues/2848

![grafik](https://user-images.githubusercontent.com/4140635/151661428-d146931d-7919-4c93-8478-cd2ea426540f.png)
