### ISSUE TITLE
Improve max/min build height option

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/PlotSquared#3488]
Observed in https://github.com/IntellectualSites/PlotSquared/pull/3487/files#r799848874

The max/min build height option in the worlds.yml doesn't handle a bunch of interactions well, which then leads to blocks being out of the reach of players.
Based on my quick test, that applies to items like armor stands or horizontally placed item frames, which you can still place and remove, but also to saplings being grown with bone meal.
The latter places blocks the player is no longer able to edit.

**Comment by dordsor21** [comment]
This should now be addressed?
