### ISSUE TITLE
Shulkers can teleport on roads

### ISSUE THREAD

**Issue by Aurelien30000** [IntellectualSites/PlotSquared#3491]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

Shulkers can teleport on roads and generate errors.

### To Reproduce

Spawn shulkers on a plot border and break the block below us, until one decides to teleport on the road.

### Expected behaviour

Shulkers should not be able to teleport on roads or should be killed.

### Screenshots / Videos

https://youtu.be/Ax-PftKBuUs

### Error log (if applicable)

https://paste.domicraft.fr/otevupuzoj.md

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/095b65c356754f058679d0890a0a8127

### PlotSquared Version

6.4.0-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Surprisingly nobody reported that ever before, because shulkers were added in 1.12.

Labeling as good first issue, because we can reuse the same logic like for dragon eggs, I guess?

**Comment by Aurelien30000** [comment]
I can't reproduce it with a dragon egg and the code seems to handle it: herehttps://github.com/IntellectualSites/PlotSquared/blob/v6/Bukkit/src/main/java/com/plotsquared/bukkit/listener/BlockEventListener.java#L769
