### ISSUE TITLE
No one can take books with the lectern-read-book flag

### ISSUE THREAD

**Issue by QuickWrite** [IntellectualSites/PlotSquared#3492]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

When the flag `lectern-read-book` is `true` no one has the ability to take books from the lectern.

### To Reproduce

1. Create a plot
2. Add a lectern
3. Add a book
4. Invoke the command `/p flag set lectern-read-book true`
5. Now no one can take the book

### Expected behaviour

The plot owner and the trusted/ added players should have the ability to take books from the lectern.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/f07fda675219486fafd320f59e589ab3

### PlotSquared Version

6.4.1-SNAPSHOT

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

This is also the case with older versions like `6.1.3-PREMIUM`.

**Comment by NotMyFault** [comment]
That is how the flag is supposed to work. It's a protection to not take books by accident. If you want to take books nevertheless, you can disable and enable the flag.

**Comment by QuickWrite** [comment]
> That is how the flag is supposed to work. It's a protection to not take books by accident. If you want to take books nevertheless, you can disable and enable the flag.

You normally don't do that by accident. It is quite a hassle if you always need to break the lectern or change the flag.

And you can build when you are trusted, while others can't do that. You could also destroy things by accident. (I don't understand the reasoning)

**Comment by NotMyFault** [comment]
Neither do I, but it has been a major concern for many people that bugged us for, hence it was added like that.
