### ISSUE TITLE
PlotMe Convertor to PlotSquared v6

### ISSUE THREAD

**Issue by FiloooSK** [IntellectualSites/PlotSquared#3498]
### What feature do you want to see added?

Hi I have suggest. Add to plugin PlotMe convertor on PlotSquared v6.
I would need to somehow upgrade from PlotMe to PlotSquared if possible. Server version is 1.16.5

### Are there any alternatives?

Probably not.

**Comment by NotMyFault** [comment]
Older versions have the converter build in, which you need to go thru anyway, if you're updating. See here: https://intellectualsites.github.io/plotsquared-documentation/installation/migrating-from-an-older-major-release.html#_migrating_from_plotme

**Comment by FiloooSK** [comment]
Is PS v3 on 1.16.5 version?

**Comment by NotMyFault** [comment]
No, I recommend you read the guide I sent carefully.

**Comment by FiloooSK** [comment]
I read and there is a progression from v3 to the most recent.

**Comment by NotMyFault** [comment]
You have to go thru every version, like the document outlines.

**Comment by NotMyFault** [comment]
The currently maintained version v6 is, anything older is not.

**Comment by FiloooSK** [comment]
We probably don't understand. I need to do the convert already on version 1.16.5, because my server is running on this version.

**Comment by FiloooSK** [comment]
You have very low support on a discord where no one answers me. That's why I'd rather ask here.
I need to somehow get rid of Plotme and switch to another plugin without losing data, but it looks like it won't work: /

**Comment by dordsor21** [comment]
PlotMe doesn't support past 1.12 so what's the issue..? Just drop in v3 on 1.12 and follow the instructions

**Comment by NotMyFault** [comment]
> You have very low support on a discord where no one answers me. That's why I'd rather ask here.

Then you asked in the wrong channels. If you are using v6 or want to upgrade to v6, visit #ps-spigot-verification and follow the steps there. Any other channel is either the wrong spot or just for community support.
