### ISSUE TITLE
Road Schematics are not properly created

### ISSUE THREAD

**Issue by PaBox** [IntellectualSites/PlotSquared#3504]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

When creating road(only replicated with roads) schematics with the setting "paste-on-top: false" will not only paste the respective schematic one block higher then it should, it also cuts away the most upper block layer. This might be due to a misconfiguration, as the bedrock is included in each schematic and it should therefore be pasted at y=0 and not y=1 as stated in multiple settings. 

Why you want to rise the road from y=0 to your street height is obvious: Signs and Hologramms will otherwise  generate at y=0 and the schematic WILL be pasted in the right way, but it is not the right way to do things.

Right now you are expected to set the road height to the wall height, so signs (and holos) generate properly. The Road blocks are set to air and "paste-on-top" must be disabled. Then we generate a world, paste the roads and intersections in as described in the documentation, select EVERYTHING and move it one block down. Next we place a Block on each road and intersection, forming a highest block layer consisting of ONLY this block and are now able to select ALL important blocks with FAWE (selecting plots as well doesnt matter, as long as you copy the walls as well as they are part of the schematics as well). Next, we move everything one block down.

NOW, you are able to make a proper schematic with properly aligned signs and holos. This took me almost a week to figure out.

As suggested, the paste level should either be put to y=0, or the schematic should be copied at the respective level and with its full height (which might be an even better solution). Another solution would be an extra option for the sign height, but there may be other solutions as well.

This is just a suggestion after all, but something must be done about the current system - it is not working as expected.

### To Reproduce

1. Create a World with `/p2 setup`, with a road height of 0.
2. Create road schematics as usual with standard settings.
3. Try out worldgen and see signs being shifted, but roads being as expected.
4. Change the setting `paste-on-top` to `false` and change the height of the road to wall-height in `worlds.yml`.
5. Reload PlotSquared and execute just `createroadschematic` on the same model as before.
6. Fly into newly generated chunks and enjoy the choped and 1-Block-too-high roads!

### Expected behaviour

No chopped roads!

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/41142093e1994cffab8bd8e9cb18c11a

### PlotSquared Version

PlotSquared-6.5.0

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

As I am just a developer, I am personally interested in this topic, but not affected. As I built this project from source, I do not insist neither push for this change, but I consider it as a valuable bug report nobody else has seen yet. Hope I can help in some way.

**Comment by FireController1847** [comment]
I can confirm this bug, having the same issue myself. Makes road generation for any roads that go below the flat-level impossible to generate correctly. I hope this can be fixed soon. I also made the following comments on the Discord if this helps anyone:
```
Hey guys, quick question. Is there any way to include the Y-axis in road schematic creation and generation? We have a road design that goes deeper into the ground and we'd like that portion to be copied over alongside the higher layers

I've noticed that quite a few other people have asked this issue and have not gotten a response, after searching through the Discord. I hope somebody is able to help at least explain why heights below the top layer are not being copied. For reference, when disabling "paste-road-on-top", it does copy the lower layers, but it pastes one block too high unfortunately.
```

**Comment by NotMyFault** [comment]
It would be helpful if you can provide your road schematic for testing purposes. Additionally I would like to ask if you could sum your first comment up, because I quite can't follow the goal you achieve vs the goal you want to achieve.
Thanks in advance.

**Comment by PaBox** [comment]
The goal is the normal use of the plugin. The signs should generate at the height of the wall and not the height of the road, as this is self-explanatory for using schematics. Since this is not directly possible, one has to use the ``paste-on-top'' setting, and set it to off. This way, one can use the road height to properly align the signs to the wall height, so they stick to the top-wall-blocks, and use air instead of road-blocks, so the road schematic is not overriden - though the signs are placed. 

This would be the intended way I think, but the problem is, that with the ``paste-on-top'' setting, the most upper block layer is NOT copied into each schematic and the temporary solution is to add an extra block on top of the road AND crossing schematics when setting them up, but this might lead to problems when this bug is fixed, as the current solution will break and the extra block WILL generate.

Hope this sums it up - as the world has been built with a lot of effort, I will send you the templates via DC - Same name there.

**Comment by PaBox** [comment]
Seems like I cant send you the template there, I will try it here.
[Plots - Kopie.template.txt](https://github.com/IntellectualSites/PlotSquared/files/8258043/Plots.-.Kopie.template.txt)

The fixed version for Git Issue #3504, has an added block when creating the schematic, so it is pasted in correctly.
 This version is the one, where paste-on-top is disabled. 
 
[plots - Kopie - notfixed.template.txt](https://github.com/IntellectualSites/PlotSquared/files/8258064/plots.-.Kopie.-.notfixed.template.txt)

 The following one has it enabled, with the signs generating under the road.
 
 Please convert the files by removing the .txt part of each file name.

**Comment by FireController1847** [comment]
This issue still occurs

**Comment by PaBox** [comment]
Yes, still reproducible for me. 2 ways to do it, but only one, where the signs are properly aligned - so the current fix is still to create the template with an extra block layer on the top, but as the fix will come, that template will be unusable again. 

*Bump*

**Comment by LouisDerEchte** [comment]
I got the same issue
