### ISSUE TITLE
Crop-Grow flag doesn't work both on global and plot flags.

### ISSUE THREAD

**Issue by serhatkotan** [IntellectualSites/PlotSquared#3508]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

So i was told to post this here as an issue by NotMyFault.

I can't stop crops from growing by setting crop-grow to false.

### To Reproduce

Set crop-grow to false either on worlds.yml or in game while standing on the plot.

### Expected behaviour

Crops such as sugar cane to stop growing.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/25782eac890641afadcafe0166daddfe

### PlotSquared Version

Plotsquared-6.5.0-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
I'm unable to replicate that based on the information and steps provided, crop growing is cancelled perfectly fine for me:
![](https://i.imgur.com/D4ploDu.png)
