### ISSUE TITLE
Turtles do not lay eggs

### ISSUE THREAD

**Issue by PaciorJr** [IntellectualSites/PlotSquared#3513]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

Turtles do not lay eggs, they perform digging animations, but do not drop eggs

### To Reproduce

1. put the turtles on the plot
2. Feed them with water grass
3. expect the digging animation
4. Wait until you die, until nothing happens…

### Expected behaviour

I would like it to work as it should.

### Plot Debugpaste

Not now

### PlotSquared Version

6.5.0

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

the problem is not fixed since v5

**Comment by dordsor21** [comment]
Not enough information. This is likely a configuration issue with a flag or configuration entry not set/set incorrectly. It should be noted the event falls similar to events such as endermen picking up blocks, and other physical interactions between entities and the world, thus unintended consequences are possible

**Comment by PierreSchwang** [comment]
Enable debug mode and see what flag cancels the block placement: `/plot toggle debug`
![grafik](https://user-images.githubusercontent.com/27054324/155389987-b30ed42b-915f-4dfa-982b-f3425d6bfb85.png)

After setting the flags it works.
