### ISSUE TITLE
Weird bug with the tab completion of player names

### ISSUE THREAD

**Issue by TheosisOfficial** [IntellectualSites/PlotSquared#3515]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

If I execute a player-targeting PlotSquared command, but only type part of their name for the player argument, whatever I typed there will now become a tab completion suggestion forever.

For example, if there is a player called "Theosis" and someone adds them to their plot using `/plot add Theo` instead of `/plot add Theosis`, Theosis will still be added to the plot, but now "Theo", the name of a player who has never joined the server before, will now become a tab completion suggestion for all player-targeting PlotSquared commands forever (until storage.db and/or user_cache.db are deleted I guess).

### To Reproduce

Reproduction steps are in the "Describe the bug" section as an example.

### Expected behaviour

The partial player name should not become a tab completion suggestion.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/7e8856fc3ff540a7be5a93413409f025

### PlotSquared Version

6.5.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by TheosisOfficial** [comment]
This happens in 1.17.1 too btw, so not a compatibility issue with 1.18.1.

**Comment by NotMyFault** [comment]
That is the intended behavior. You can add players to the plot who didn't join the server (yet) but do exist.
