### ISSUE TITLE
Creepers Grief With Explosion Flag = False

### ISSUE THREAD

**Issue by ArZorMC** [IntellectualSites/PlotSquared#3516]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

Even with explosions flag set to false creepers still  explode and cause damage to the ground.

### To Reproduce

Claim a plot
Set explosions flag to false
Ignite a creeper with flint & steel or wait for one to explode
Be perplexed at the new hole in the ground

### Expected behaviour

A beautiful plot with no holes

### Screenshots / Videos

https://gyazo.com/615d9f472d6ef76b3acf450d73ccdafa
https://gyazo.com/8452c15751434192d49942b7fa917242

### Error log (if applicable)

N/A

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/d71728e737f947f38a69380e800b241a

### PlotSquared Version

PlotSquared version 6.5.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
I'm unable to replicate that:

https://user-images.githubusercontent.com/13383509/155785519-042c9d9f-eda2-45ce-8a44-a07e3e35238e.mp4
