### ISSUE TITLE
Async catcher kicks on static home variables with teleport.on-clear/on-delete enabled

### ISSUE THREAD

**Issue by TheosisOfficial** [IntellectualSites/PlotSquared#3517]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

When a non-opped player tries to clear or delete a plot when using static `home` values in worlds.yml...
![image](https://user-images.githubusercontent.com/26799016/155516269-d5bc2cdd-7d22-4c9f-ae21-a96e0630de1c.png)
... the plot does not get cleared or deleted, and these errors appear in the console: https://pastebin.com/Nu4dc4ac

This only happens when the respective `teleport.on-clear` and `teleport.on-delete` settings are set to `true` in settings.yml.

Reproduced in 1.17.1.

### To Reproduce

1. Set up a plot world
2. Set `teleport.on-clear` and `teleport.on-delete` to `true` in settings.yml.
3. Set `worlds.<worldname>.home.nonmembers` and `worlds.<worldname>.home.nonmembers` to static coordinates in worlds.yml (an example screenshot is shown in the "Describe the bug" section).
4. Have a non-opped player claim a plot
5. Have the same player attempt to clear and/or delete the plot they just claimed

### Expected behaviour

The plot should clear as normal and the player should be teleported as normal. The correct behaviour occurs with opped players for some reason.

### Error log (if applicable)

https://pastebin.com/Nu4dc4ac

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/5ae0ff2ede644adb9c8449da5cb81a24

### PlotSquared Version

6.5.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by dordsor21** [comment]
Honesty looks like a paper bug

**Comment by TheosisOfficial** [comment]
> Honestly looks like a paper bug

If I were to report the bug to their issue tracker, how would I do so without relating it to PS?
