### ISSUE TITLE
PlotSquared doesn't load on 1.18.2

### ISSUE THREAD

**Issue by josephjthomas** [IntellectualSites/PlotSquared#3525]
### Server Implementation

Spigot

### Server Version

1.18.1

### Describe the bug

PlotSquared doesn't load on 1.18.2

### To Reproduce

1. Download PlotSquared 6.5.1
2. Build Spigot
3. Launch the server with PlotSquared

### Expected behaviour

It should load

### Error log (if applicable)

https://pastebin.com/raw/QanVLEui

### Plot Debugpaste

I can't do that because the plugin doesn't load

### PlotSquared Version

6.5.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

Additional information because I the debugpaste command doesn't work:
- WorldEdit version 7.2.10-SNAPSHOT+6102-9ea569e
- This server is running CraftBukkit version 3447-Spigot-fb0dd5f-86292d3 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)

**Comment by SirYwell** [comment]
I opened an issue on the spigot bug tracker: https://hub.spigotmc.org/jira/browse/SPIGOT-6957. I'll leave this open until the problem is resolved.

**Comment by yannicklamprecht** [comment]
> I opened an issue on the spigot bug tracker: https://hub.spigotmc.org/jira/browse/SPIGOT-6957. I'll leave this open until the problem is resolved.

Md_5 resolved it and a commit with a diff at that location is present.
