### ISSUE TITLE
`/plot set wall` generates the wall on three of four sides of the plot

### ISSUE THREAD

**Issue by resi23** [IntellectualSites/PlotSquared#3531]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

If I set the wall with /plot set wall copper_block it only does it in the west east and south but not in the north

### To Reproduce

Go to a plot and do /plot set wall copper_block. He will only generate the wall to the east, south and west

### Expected behaviour

that he sets the wall on all edges

### Screenshots / Videos

![Screenshot 2022-03-08 084310](https://user-images.githubusercontent.com/1244755/157189951-d1a9bf1c-6c24-40ef-b3eb-f8a91f30548a.jpg)
![Screenshot 2022-03-08 084319](https://user-images.githubusercontent.com/1244755/157189961-2d35b5cd-2a40-4675-ae6a-7cc10b9a1dc5.jpg)

### Error log (if applicable)

no errors

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/2f2f12a9bcef4c609c6d8af7d3b30b49

### PlotSquared Version

Build from Source

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by resi23** [comment]
He does it even if I clear an old plot he generates the new chance up to -64 but not the north wall

**Comment by ofunny** [comment]
Confirmed in version 6.6.1

**Comment by KxmischerLasse** [comment]
I have about the same error /p set wall https://youtu.be/sV4iqpzlmVc
