### ISSUE TITLE
WEManager#getMask now depends on Fawe (regression of 6.6.0)

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/PlotSquared#3532]
In 6.6.0, the method WEManager#getMask has been changed to utilize the RegionWrapper: https://github.com/IntellectualSites/PlotSquared/commit/9f632af0aeda71ac7d806da72eb32932329535d0#diff-9d9460de05368cdcf8e4b39f67b94cd627a2beb91248889d3d9b6413003475f5L94-R95
However, that is a Fawe class and should fire a ClassNotFoundException when using regular WorldEdit (untested, but does from the look like).

**Comment by NotMyFault** [comment]
Thanks for quickly taking care of it. I'd look forward to push a new release in a bit, considering this is somewhat of a major impact for WE users, if nobody is opposed to it.

**Comment by NotMyFault** [comment]
I've pushed an update, Discord doesn't work for me atm, would be nice if someone else can push out an announcement on Discord.

**Comment by dordsor21** [comment]
https://discordstatus.com/
