### ISSUE TITLE
Thread dump any time server tries to enter plot world

### ISSUE THREAD

**Issue by mrcoffee1026** [IntellectualSites/PlotSquared#3545]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

Player types /plot home... moments later the server locks up, they cannot leave the plot world via any means and the server is completely nonresposnsive throughout the thread dump.  A restart is required.  If a a hard restart is not performed before the console stops responding, a more aggressive power cycle is the only way to aquire server control again as a fresh login will no longer accept the system password.

### To Reproduce

Have any player attempt a visit to a plot world via any means.

### Expected behaviour

Players should be able to visit plot homes or fly around plot worlds at their leisure.

### Error log (if applicable)

https://pastebin.com/JkFM7aVx

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/57ad93e63d2e4846802acfe380d6ed59

### PlotSquared Version

[14:23:04 INFO]: PlotSquared version 6.6.1-Premium [14:23:04 INFO]: Easy, yet powerful Plot World generation and management. [14:23:04 INFO]: Website: https://www.spigotmc.org/resources/77506/ [14:23:04 INFO]: Authors: Citymonstret, Empire92, MattBDev, dordsor21, NotMyFault and SirYwell

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

Tried accessing a plot world with my alt using an essentials warp instead of a plot home and got the same result.

**Comment by NotMyFault** [comment]
Update Paper and Fawe first. Both deliver critical updates specific P2 components depend on

**Comment by mrcoffee1026** [comment]
is there not a version of fawe and plotsquared that work on 1.18.1?

**Comment by NotMyFault** [comment]
Both work fine on 1.18.x, however, treating expanded heights sanely with P2 requires an up to date version of Fawe which requires an up to date version of Paper.

**Comment by mrcoffee1026** [comment]
well none of our crative worlds utilize the expanded y  heights that I am aware of.  But MANY plugins will fail to run in 1.18.2 so I can't roll that out yet... so again, which version of your plugins will operate in 1.18.1

**Comment by NotMyFault** [comment]
Both newest versions worked fine for me a couple of days ago on 1.18.1. However, the stacktrace looks like the generic chunk holder one. I'll need to take a closer look at a later point.

**Comment by mrcoffee1026** [comment]
well from what you just told me, it won't work on 1.18.1 since that's what you're telling me to upgrade to 1.18.2 in order to make it work.  If it worked in 1.18.1, I wouldn't need to do that.  But yes, let me know what you find out.
