### ISSUE TITLE
CloudNet Perms

### ISSUE THREAD

**Issue by LuisKanze** [IntellectualSites/PlotSquared#3547]
### What feature do you want to see added?

I would love it if Cloud Perms is added for the permission setting of Plotsquared because these currently do not work

### Are there any alternatives?

Nothing

**Comment by NotMyFault** [comment]
PlotSquared doesn't support individual permission plugins but honors the bukkit permission API. If a consumer plugin, like the industry standard, LuckPerms, treats the bukkit API well, PlotSquared works with named example, LuckPerms.
If permissions don't work with a specific permission plugin, there's nothing we can do about it.
We provide permissions via the bukkit-like way, the implementation details are up to the permission plugins.
