### ISSUE TITLE
Biome changing drops server TPS since version 6.6.1

### ISSUE THREAD

**Issue by AnonymioD** [IntellectualSites/PlotSquared#3549]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

Hello
Since version 6.6.1
Changing the biome by /plot setbiome <biome> => Drop TPS (check screenshot)
Lasts for few minutes.. Pretty annoying

Tested different biomes on different plots (old height and new height doesn't matter)

### To Reproduce

1. /plot setbiome <anybiome>
2. TPS going crazy 8D

### Expected behaviour

Change the biome in few seconds

### Screenshots / Videos

![2022-03-17 19_23_13-Window](https://user-images.githubusercontent.com/101605363/158870399-005882c8-4737-472f-9375-c3eb60c3af50.png)

### Error log (if applicable)

https://paste.gg/p/anonymous/cc2358a20c5f4f37a3afd5fe752fc1f4

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/42820f5a70ed41579e5d7f374b6582d4

### PlotSquared Version

PlotSquared-6.6.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

Before 6.6.1, it was Ok

**Comment by SirYwell** [comment]
A [spark](https://www.spigotmc.org/resources/spark.57242/) profiling result would be appreciated.

Does "since 6.6.1" mean you had 6.6.0 before and it was working fine there?

**Comment by AnonymioD** [comment]
Version before was 6.5.1 ( /plot download was not working too )
We're gonna test server performance later night (friday evening, many players..)
Test with "/timings" (included with spigot) or you want specific "spark perf testing" ?

**Comment by SirYwell** [comment]
spark would be preferred as it by far more precise

**Comment by AnonymioD** [comment]
Results:
- timings merged: https://timings.aikar.co/?id=f2bc0ae0dcb14417b3898e740430b81a#timings
- spark: https://spark.lucko.me/l4BYgzHj5m

**Comment by dordsor21** [comment]
![image](https://user-images.githubusercontent.com/10080017/159097689-b4d4fc9c-3409-4fae-809a-810485fbec9f.png)

**Comment by TNTUP** [comment]
Can confirm. A player attempted /p setbiome <biome> and it brought TPS down to 0.26, lol 

https://timings.aikar.co/?id=b28eb7b867764894acc93d4457a6b813

I don't have a spark profiler. If needed I will provide it while changing the biome

**Comment by dordsor21** [comment]
Paper issue: https://github.com/PaperMC/Paper/issues/7630

**Comment by NotMyFault** [comment]
The fix has been released in Paper 1.18.2 build 277, closing the issue.

**Comment by traksag** [comment]
Setting the plot biome is still very laggy on the latest version of Paper 1.18.2. Created a plot world with 101x101 plots and got these results:
- https://athion.net/ISPaster/paste/view/068e10cfe16a4ff48f71d0932fcbe020
- https://spark.lucko.me/FsWYKodFAm

The average MSPT increases from 1 to ~200 over a period of 20 seconds (see the logs in the debug paste). With larger plot sizes it'll probably lag for even longer.
