### ISSUE TITLE
"Could not pass event PlayerCommandPreprocessEvent to PlotSquared v6.6.1-Premium"

### ISSUE THREAD

**Issue by TheosisOfficial** [IntellectualSites/PlotSquared#3550]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

I got this error when a player joined the server and ran a command extremely quickly after it starting up. I'm guessing PlotSquared hadn't registered the player yet or something?

EDIT: Here is the actual exception lol: https://pastebin.com/zPU9YWTe

### To Reproduce

1. Start up server with PlotSquared installed
2. Have a player join the server as quickly as possible and run any command

### Expected behaviour

The error should not occur (?)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/494a2788a61844ce9a9918e94e6b8e07

### PlotSquared Version

6.6.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
It appears that you forgot to include the actual exception.

**Comment by TheosisOfficial** [comment]
> It appears that you forgot to include the actual exception.

My bad, I've added it now

**Comment by SirYwell** [comment]
That's basically triggered if the bukkit API returns `false` for `Player#isOnline()`. Not sure if we *want* to handle that differently, because that's really rather a server issue. We could probably ignore the event in such case, but that's not really a sophisticating, future-proof solution.

**Comment by TheosisOfficial** [comment]
> That's basically triggered if the bukkit API returns `false` for `Player#isOnline()`. Not sure if we _want_ to handle that differently, because that's really rather a server issue. We could probably ignore the event in such case, but that's not really a sophisticating, future-proof solution.

A server issue as in something wrong with Bukkit/Spigot/Paper? Or my setup?

**Comment by NotMyFault** [comment]
That's likely not something we should take care of. We rely on what the API reports, we shouldn't alter or intercept that.
