### ISSUE TITLE
Border is not working

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#3559]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

Normally i have enabled the border so the plotworld is limited. But after updating to 1.18.2 the border is no longer working.

### To Reproduce

IDK

### Expected behaviour

1. As an admin, getting a warning that iam out of the border

2. As player not able to bypass the border

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/0762b1028faf4f388b4e040246ac5114

### PlotSquared Version

6.6.1

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
I'm not able to replicate that.
