### ISSUE TITLE
Buggy Plot world or Fawe

### ISSUE THREAD

**Issue by DevCrewDev** [IntellectualSites/PlotSquared#3566]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

My worlds are buggy when i create a new world and then i execute on a plot "/plot clear " or "/plot delete" the world is buggy. 

![image](https://user-images.githubusercontent.com/88801977/162010187-da566618-b6e1-45f8-ab8f-0ff3a606e149.png)

when i select the empty place and execute "//set 1"

![image](https://user-images.githubusercontent.com/88801977/162010582-c2341a1b-c966-4e5d-bbad-30ca8f929b2d.png)

and when i execute "//undo"

![image](https://user-images.githubusercontent.com/88801977/162010659-8d4184d7-11a1-495c-a4a2-d0875c3fda0f.png)

### To Reproduce

1. i execute "//plot clear" or "//plot delete"
2. I select the empty place via Fawe and execute //set 1
3. I execute "//undo"
4. and all is normal 

### Expected behaviour

clear or delete the plot

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/c6909456227940cca97649bbd3cc7f61

### PlotSquared Version

PlotSquared 6.6.2-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
This is tracked here https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1666
