### ISSUE TITLE
Plot clearing outside of plot borders

### ISSUE THREAD

**Issue by macjuul** [IntellectualSites/PlotSquared#357]
Whenever I clear a plot in my plot world. It also clears parts of the plots around it. This seems to not always clear plots in a certain direction. And if it clears those plots only for about 4 blocks from the side. This is still a huge bug so I will have to disable the clear command until its fixed :(

Thanks,
macjuul

**Comment by EvilOlaf** [comment]
Did you try debugclear instead?

**Comment by macjuul** [comment]
Sorry for the late reponse but yes, debugclear also indeed clears outside of its borders

**Comment by macjuul** [comment]
And as far as I know, it always seems to clear a part of the plot on the north and east of the plot you are clearing

**Comment by boy0001** [comment]
Has been fixed for 2.12.13 which will be updated shortly

**Comment by boy0001** [comment]
*If this is not the case, please let me know as there could be other test cases which were missed.
