### ISSUE TITLE
Plot protection - moss blocks and lava/water

### ISSUE THREAD

**Issue by Myszku** [IntellectualSites/PlotSquared#3582]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

If roads in plot world have small width (for me 1), moss blocks can replace blocks (grass, dirt, stone) on other plots when player uses bone meal on it.

And, if plot world have min_height set e.g. 0 and filling of claimed plots is set to minecraft:air, lava and water can create cobblestone under plot region (where player can't build)

### To Reproduce

plot:
      filling: minecraft:air
world:
      max_gen_height: 255
      max_height: 256
      gamemode: creative
      min_gen_height: 1
      min_height: 2
      border: false

### Expected behaviour

---

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/0c8d89ef70664594a66bec887117f1f6

### PlotSquared Version

PlotSquared-6.6.2-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by Xaver106** [comment]
I can't recreate the moss growing over into another plot. Even with a road with of 1 and placing the moss block in between the lots. Maybe post a video if it is still an issue on the newest version.
The cobblestone generating underneath the build limit was an issue for me as well, but this is an easy fix so I might fix it myself.
Everything tested on fc9fe146
