### ISSUE TITLE
First plot Free setting

### ISSUE THREAD

**Issue by byNixo** [IntellectualSites/PlotSquared#3583]
### What feature do you want to see added?

A setting that allows players to get the first plot for free

### Are there any alternatives?

Not that I know of. Apparently scripts, but these don't work properly.

**Comment by dordsor21** [comment]
You've not offered any information of it "not working". `plots < ` ? 0.0 : "price"` has worked for everyone else.

**Comment by byNixo** [comment]
But further plots should cost money.

**Comment by dordsor21** [comment]
I corrected the expression.

**Comment by byNixo** [comment]
In which file do I have to make this setting?

**Comment by byNixo** [comment]
> 

Where do I have to make this change?

**Comment by NotMyFault** [comment]
Take a look at the documentation or use our support channel on Discord.
