### ISSUE TITLE
core features fail to work

### ISSUE THREAD

**Issue by MythicGhoul** [IntellectualSites/PlotSquared#3587]
### Server Implementation

Spigot

### Server Version

1.18.2

### Describe the bug

The latest release has broken my server, this is what i am getting on server boot up.

`24.04 11:09:01 [Server] Server thread/INFO Enabling PlotSquared v6.6.3-Premium
24.04 11:09:01 [Server] Server thread/INFO Loaded caption map for namespace 'plotsquared': com.plotsquared.core.configuration.caption.LocalizedCaptionMap
24.04 11:09:01 [Server] Server thread/WARN Loaded class com.plotsquared.core.queue.QueueCoordinator from PlotSquared v6.6.3-Premium which is not a depend or softdepend of this plugin.
24.04 11:09:01 [Server] Server thread/ERROR Error occurred while enabling PlotSquared v6.6.3-Premium (Is it up to date?)
24.04 11:09:01 [Server] INFO java.lang.LinkageError: loader constraint violation for class com.fastasyncworldedit.bukkit.regions.plotsquared.FaweQueueCoordinator: when selecting overriding method 'com.sk89q.worldedit.world.World com.fastasyncworldedit.bukkit.regions.plotsquared.FaweQueueCoordinator.getWorld()' the class loader org.bukkit.plugin.java.PluginClassLoader @603ed8d9 of the selected method's type com.fastasyncworldedit.bukkit.regions.plotsquared.FaweQueueCoordinator, and the class loader org.bukkit.plugin.java.PluginClassLoader @51f520c9 for its super type com.plotsquared.core.queue.QueueCoordinator have different Class objects for the type com.sk89q.worldedit.world.World used in the signature (com.fastasyncworldedit.bukkit.regions.plotsquared.FaweQueueCoordinator is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @603ed8d9, parent loader java.net.URLClassLoader @2e5d6d97; com.plotsquared.core.queue.QueueCoordinator is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @51f520c9, parent loader java.net.URLClassLoader @2e5d6d97)
24.04 11:09:01 [Server] INFO at java.lang.Class.forName0(Native Method) ~[?:?]
24.04 11:09:01 [Server] INFO at java.lang.Class.forName(Class.java:375) ~[?:?]
24.04 11:09:01 [Server] INFO at com.plotsquared.bukkit.BukkitPlatform.onEnable(BukkitPlatform.java:278) ~[?:?]
24.04 11:09:01 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
24.04 11:09:01 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
24.04 11:09:01 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
24.04 11:09:01 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:517) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3451-Spigot-fb0dd5f-808cb7c]
24.04 11:09:01 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:431) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3451-Spigot-fb0dd5f-808cb7c]
24.04 11:09:01 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:233) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3451-Spigot-fb0dd5f-808cb7c]
24.04 11:09:01 [Server] INFO at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1009) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3451-Spigot-fb0dd5f-808cb7c]
24.04 11:09:01 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:306) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3451-Spigot-fb0dd5f-808cb7c]
24.04 11:09:01 [Server] INFO at java.lang.Thread.run(Thread.java:833) [?:?]
24.04 11:09:01 [Server] Server thread/INFO Preparing level "Twitch"
24.04 11:09:01 [Server] Server thread/ERROR Could not set generator for default world 'Twitch': Plugin 'PlotSquared v6.6.3-Premium
24.04 11:09:01 [Server] INFO java.lang.NullPointerException: Cannot invoke "com.plotsquared.google.Injector.getInstance(com.plotsquared.google.Key)" because the return value of "com.plotsquared.bukkit.BukkitPlatform.injector()" is null
24.04 11:09:01 [Server] INFO at com.plotsquared.bukkit.BukkitPlatform.getDefaultWorldGenerator(BukkitPlatform.java:1018) ~[?:?]
24.04 11:09:01 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.CraftServer.getGenerator(CraftServer.java:1474) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3451-Spigot-fb0dd5f-808cb7c]
24.04 11:09:01 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:522) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3451-Spigot-fb0dd5f-808cb7c]
24.04 11:09:01 [Server] INFO at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:416) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3451-Spigot-fb0dd5f-808cb7c]
24.04 11:09:01 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:263) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3451-Spigot-fb0dd5f-808cb7c]
24.04 11:09:01 [Server] INFO at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1009) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3451-Spigot-fb0dd5f-808cb7c]
24.04 11:09:01 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:306) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3451-Spigot-fb0dd5f-808cb7c]`

Players are now able to grief each other and its causing common users to leave.. please fix or give me a solution aha

Thanks,
Ghoul

### To Reproduce

install the latest update

### Expected behaviour

/plot doesnt return anything in chat o console

### Plot Debugpaste

doesnt return naything

### PlotSquared Version

6.6.3 premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
You've modified the namespace to something that is invalid:
> erver thread/INFO Loaded caption map for namespace 'plotsquared':
Revert it to what you had before or hop on our [https://discord.gg/intellectualsites](discord) -> #ps-spigot-verification if you need further assistance.
