### ISSUE TITLE
Player view all toggle

### ISSUE THREAD

**Issue by NoltoxGit** [IntellectualSites/PlotSquared#3593]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

Hello,

I just observed that the players see all the subcommands after the `/ps toggle`.

### To Reproduce

1. Connect a double account with no op permissions.
2. This player has the following [permissions](https://prnt.sc/qH0JqlLi14La).
3. Mark in the chat `/ps toggle` and the subcommands will appear while it only has *chat* permission.

### Expected behaviour

The player is only supposed to see `/ps toggle chat` and not everything else (chatspy; clear-confirmation; debug; time; titles; worldedit)

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/75265787/165783231-5fe1021a-f9b5-4ed2-9cec-2078dc479e25.png)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/2c67199a188048e3aeca5e6de174f41c

### PlotSquared Version

PlotSquared version 6.6.3-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
I'm unable to replicate that based on the steps provided. Using the three permission nodes mentioned, I can view the three associated commands fine, and only them:
![](https://i.imgur.com/TKWzXqi.png)

**Comment by NoltoxGit** [comment]
Mhh, strange :/
