### ISSUE TITLE
Price scale

### ISSUE THREAD

**Issue by JaTiTV** [IntellectualSites/PlotSquared#3603]
### What feature do you want to see added?

Would it be possible to introduce a price scale for the plots?

For example:
The first 10 plots: 1000
Each further one: 5000

or:

The first plot: 1000
Each further one: 5000

### Are there any alternatives?

no

**Comment by PierreSchwang** [comment]
As stated in the documentation (https://intellectualsites.github.io/plotsquared-documentation/configuration/worlds.yml.html) you can use
> ANTLR's lexer tokens for dynamic prices

As a quick example, the first plot costs 100, all further plots cost 500:
`claim: plots == 0 ? 100 : 500`
