### ISSUE TITLE
teleport

### ISSUE THREAD

**Issue by afdsgihfjl** [IntellectualSites/PlotSquared#3625]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

when im using the command to teleport and create plots they do not teleporting me or creating plots for me

/plot auto -> youre not in a plot area

how can i teleport to plot area?

### To Reproduce

idk

### Expected behaviour

teleport / create me a plot

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/521ef2b05a6741d4b4d12500b856d242

### PlotSquared Version

6.0.6-snapshot

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by dordsor21** [comment]
Teleport to the plot world using any number of plugins/commands. Including `/ps area` which offers the ability to teleport to plot areas.
