### ISSUE TITLE
Cant use /p clear (Worldedit problem?)

### ISSUE THREAD

**Issue by luis996** [IntellectualSites/PlotSquared#3628]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

/p clear doesnt work and Drops errors

### To Reproduce

1.- Go to minecraft
2.- type /p clear
3.- Go to the console and see the errors

### Expected behaviour

The plot blocks erased

### Error log (if applicable)

https://paste.gg/p/anonymous/ddf2a8c754e44f4d987751bf14743526

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/e15cd0793b8745bc8c147bae228474da

### PlotSquared Version

PlotSquared version 6.8.0

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
I'm unable to replicate that on Paper 339 and WE 7.2.11-SNAPSHOT+6155-3eefaa2, you should start with updating both.

**Comment by luis996** [comment]
Ok i will try

**Comment by luis996** [comment]
It has sense beacuse in the logs it say something idk it says unsupported version

**Comment by luis996** [comment]
... Try replicating it Installing ViaVersion, ViaBackwards,ViaRewind and doing it with 1.16.5 client and 1.18.2 server

**Comment by luis996** [comment]
[WARNING] .... java.lang.RuntimeException: com.sk89q.worldedit.bukkit.adapter.UnsupportedVersionEditException: Editing on unsupported versions is disabled.

**Comment by luis996** [comment]
> I'm unable to replicate that on Paper 339 and WE 7.2.11-SNAPSHOT+6155-3eefaa2, you should start with updating both.

The problem persists

**Comment by luis996** [comment]
This happens since 6.8.0, 6.7.0 worked fine

**Comment by PierreSchwang** [comment]
That sounds like a WE issue,  you have the wrong WE version for your server version

> [WARNING] .... java.lang.RuntimeException: com.sk89q.worldedit.bukkit.adapter.UnsupportedVersionEditException: Editing on unsupported versions is disabled.

Install WE 7.2.11 and provide a new log if the issue persists.

**Comment by luis996** [comment]
> That sounds like a WE issue, you have the wrong WE version for your server version
> 
> > [WARNING] .... java.lang.RuntimeException: com.sk89q.worldedit.bukkit.adapter.UnsupportedVersionEditException: Editing on unsupported versions is disabled.
> 
> Install WE 7.2.11 and provide a new log if the issue persists.

Okay

**Comment by luis996** [comment]
> That sounds like a WE issue, you have the wrong WE version for your server version
> 
> > [WARNING] .... java.lang.RuntimeException: com.sk89q.worldedit.bukkit.adapter.UnsupportedVersionEditException: Editing on unsupported versions is disabled.
> 
> Install WE 7.2.11 and provide a new log if the issue persists.

https://paste.gg/p/anonymous/eff00b73fa1841839b37b8aad98db2bc

**Comment by luis996** [comment]
> That sounds like a WE issue, you have the wrong WE version for your server version
> 
> > [WARNING] .... java.lang.RuntimeException: com.sk89q.worldedit.bukkit.adapter.UnsupportedVersionEditException: Editing on unsupported versions is disabled.
> 
> Install WE 7.2.11 and provide a new log if the issue persists.

i did send it

**Comment by luis996** [comment]
bruh

**Comment by luis996** [comment]
> I'm unable to replicate that on Paper 339 and WE 7.2.11-SNAPSHOT+6155-3eefaa2, you should start with updating both.

i did update both and it didnt work, i did send new log up

**Comment by luis996** [comment]
I will try Rebuilding worldedit with UnsupportedVersionEdit enabled and lets see what happens
