### ISSUE TITLE
Change GAV to intellectualsites domain

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/PlotSquared#3630]
For v7, I'd like to propose a GAV change from `com.plotsquared:PlotSquared-<module>` to `com.intellectualsites.plotsquared:plotsquared-<module>`.

TODO:
- [ ] Request the creation of a new staging and production database from the OSSRH.
  - [ ] Request to turn of sync of com.plotsquared for this repository
- [x] Update PlotSquared to use and publish the new GAV
  - ~~[ ] Update package names? No objections from my side, but feels a bit unneeded to me too, opinions are welcome.~~
- [ ] Update documentation and highlight change in the v7 release notes.

**Comment by Citymonstret** [comment]
I'm fine with this, as long as the package names remain the same. We've already switched out package names once, and it's a very unnecessary (completely) breaking change.

**Comment by NotMyFault** [comment]
Postponing this to future releases, I already paid the domain for this year.
