### ISSUE TITLE
A GUI for Plotsquared v6

### ISSUE THREAD

**Issue by Atten007** [IntellectualSites/PlotSquared#3634]
### What feature do you want to see added?

Hi folks,

I‘m using Plotsquared v6 free on my server (I’ve compiled it myself). I’m currently playing in my plotworld and I thought about a GUI for Plotsquared v6, where you can claim, backup, add, delete, remove, trust etc. the GUI should have all features from Plotsquared v6 that are executable with /p. Can you pls add a gui to Plotsquared v6 ASAP?

Sincerely yours,
Atten007😊

### Are there any alternatives?

No, I haven’t tried some alternatives yet…

### Anything else?

Nothing else…

**Comment by NotMyFault** [comment]
This seems to be covered by https://github.com/IntellectualSites/PlotSquared/issues/3631
