### ISSUE TITLE
Feature request: New placeholder

### ISSUE THREAD

**Issue by NoltoxGit** [IntellectualSites/PlotSquared#3649]
### What feature do you want to see added?

Hello !
Here is my suggestion:

Looking at the placeholders proposed by PS and for my use, I thought of adding a placeholder equivalent to `%plotsquared_allowed_plot_count%` but in which we could specify the world, which would give for example: `%plotsquared_allowed_plot_count_(World)%`.

### Are there any alternatives?

_No existing alternative._

**Comment by RedstoneFuture** [comment]
![grafik](https://user-images.githubusercontent.com/4140635/172066783-0b2ba65f-1a5f-4f55-8572-617d3aa0fac0.png)

Good idea.

**Comment by NoltoxGit** [comment]
> ### What feature do you want to see added?
> 
> Hello ! Here is my suggestion:
> 
> Looking at the placeholders proposed by PS and for my use, I thought of adding a placeholder equivalent to `%plotsquared_allowed_plot_count%` but in which we could specify the world, which would give for example: `%plotsquared_allowed_plot_count_(World)%`.
> ### Are there any alternatives?
> 
> _No existing alternative._

I am looking forward to this placeholder to make my plot shop with DeluxeMenus :)

**Comment by Xaver106** [comment]
This is not possible!
PlotSquared does not know how many plots you are allowed to own on every possible world, only on the current world, as this is handled through permissions. Plotsquared can't easily request permissions with different context.
