### ISSUE TITLE
Alias Bug

### ISSUE THREAD

**Issue by Yalerius-Games** [IntellectualSites/PlotSquared#3675]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

I mean good plugin but the plotsquared aliases don't work properly. It always tells me that this alias exists. And then executing the command: /p visit Megalovania it says: "This user has no claimed plots"... or so bc im using the geman translation of THIS plugin.

### To Reproduce

1. Open InGame chat
2. Type: /p alias set Megalovania
3. See error
4. Type: /p visit Megalovania
5. See error

### Expected behaviour

The Plot alias should be Megalovania.

### Screenshots / Videos

![2022-06-12_15 52 46](https://user-images.githubusercontent.com/107355797/173236796-a127af88-3192-45ad-bb15-8d2cb1f46a01.png)
![2022-06-12_15 52 57](https://user-images.githubusercontent.com/107355797/173236799-188bf9ef-117a-477e-b59f-97abd581d71d.png)
![2022-06-12_15 53 11](https://user-images.githubusercontent.com/107355797/173236800-57490636-eee6-41c7-9b9a-58032d1ed9d9.png)
![2022-06-12_15 53 15](https://user-images.githubusercontent.com/107355797/173236802-098ca3eb-4d3b-4d58-9460-dd12b61e4fbe.png)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/714e4f273ab3497fa6b500e7e7b59599

### PlotSquared Version

PlotSquared version 6.8.1-premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
A plot alias can't be a claimed username.
