### ISSUE TITLE
I can't load the PlotSquared Plugin's map.Plsssssssssss help me!

### ISSUE THREAD

**Issue by Guyao146** [IntellectualSites/PlotSquared#3682]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

Hi. The PlotSquared plugin maybe have a bug.
When I was loading or create a plot world.
Always jump a bug.

### To Reproduce

1.Entering plot create/sche/load world normal
2.Jumping bug

### Expected behaviour

Loading/Create or sche world can be nomal loading.

### Error log (if applicable)

https://paste.gg/p/anonymous/1e08311140d24023b5f48e81bc6e2397

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/8851436c3bcd47dc947d6aaedfa6917a

### PlotSquared Version

PlotSquared-Bukkit-6.9.0-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Update WorldEdit and Paper.
