### ISSUE TITLE
Output jar size increased by ~500kb while the content remains the same

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/PlotSquared#3685]
Bisecting the commit history from the latest commit as bad input, stepping down to  https://github.com/IntellectualSites/PlotSquared/pull/3676 -1 as good commit, shows a difference of 500kb in file size, from 3.5M to 4M, in file size, while the file content remains the same, as obtained by [diffoscope](https://try.diffoscope.org/przyrzrxrfzc.html).

This is a regression caused by https://github.com/IntellectualSites/PlotSquared/pull/3676.

**Comment by dordsor21** [comment]
I'd assume it's something to do with minimize() only being in the Bukkit module

**Comment by NotMyFault** [comment]
> I'd assume it's something to do with minimize() only being in the Bukkit module

That'd be odd, because Core doesn't shade anything and it remained the same in size 🤔

**Comment by NotMyFault** [comment]
![Bildschirmfoto 2022-06-16 um 00 46 22](https://user-images.githubusercontent.com/13383509/173954680-64df0df0-d213-425c-aa6c-5272fc59d570.png)

Ok, looks like everything is fine still? But apparently a "human readable" output rounds weird, looks like I should stick to awk to keep up with _proper_ arithmetic operations.
