### ISSUE TITLE
gradlew build failed

### ISSUE THREAD

**Issue by IveMalfunctioned** [IntellectualSites/PlotSquared#3687]
### Server Implementation

Spigot

### Server Version

1.18.1

### Describe the bug

Build failed, bunch of errors

`gradlew build`: https://pastebin.com/uxddrbKX
`gradlew build --stacktrace`: https://pastebin.com/KnBdSN83

### To Reproduce

1. try to build

### Expected behaviour

build would succeed, but it failed

### Plot Debugpaste

im not even there yet

### PlotSquared Version

6.9.0

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

naaahhh

**Comment by NotMyFault** [comment]
https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository

**Comment by qtqgyt** [comment]
I have the same issue and cannot figure it out
