### ISSUE TITLE
PermissionsEX Nodes Not Working

### ISSUE THREAD

**Issue by XGNRen** [IntellectualSites/PlotSquared#3689]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

Players do not have access to any plot commands when using PermissionsEX, even when given the correct permissions.

### To Reproduce

Attempt running any plot commands using PEX.

### Expected behaviour

Commands should work if given the proper permission node.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/9f4b749543084a8d881922b55871b91d

### PlotSquared Version

6.9.0 Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

No, I will not be switching to LuckPerms.

**Comment by NotMyFault** [comment]
PEx is abandoned and unmaintained for many years, not much we can do about it not working. You should consider switching to the industry standard, LuckPerms, if you want to use a maintained and supported permission management software.
