### ISSUE TITLE
PlotSquared V6 needs Java 17 but I will install it on 1.16.5 Server

### ISSUE THREAD

**Issue by CuzImFl4mer** [IntellectualSites/PlotSquared#3690]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

If I want to Install PlotSquared V6 to my 1.16.5 Server the Plugin can be not used, because my 1.16.5 Server needs Java 16 and if I will change it to Java 17 for PlotSquared my Server will not start up..

### To Reproduce

There are no steps because I cannot use 2 Java versions..

### Expected behaviour

I expected that my Server can start up with Java 17, this is what P² needs but my Server needs Java 16 this means the Plugin cannot be activated.. So I cannot do anything rn.

### Plot Debugpaste

none

### PlotSquared Version

PlotSquared Version: V6 6.9.0

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by dordsor21** [comment]
We're following Mojang's policy and require modern Java versions for our plugins too. Currently, all our plugins require Java 17. If you are unsure how to update your Java version, checkout this guide: https://docs.papermc.io/java-install-update.
If you are using a version prior to 1.17, add -DPaper.IgnoreJavaVersion=true to your JVM flags (before -jar) and your server skips the Java version check, and use Java 17.
