### ISSUE TITLE
/Plot is giving some errors and /plot wea doesn't exist..

### ISSUE THREAD

**Issue by CuzImFl4mer** [IntellectualSites/PlotSquared#3693]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

When I write /plot or /p or /p2 all of them will give me a error message.. And /plot wea doesn't exist idk why.. there is no message when I write it into the chat..

### To Reproduce

-> Chat: /plot
-> Chat: Cannot invok "com.plotsquared.core.command.Help.displayHelp(com.plotsquared.core.player.PlotPlayer, String, int)" because "com.plotsquared.core.command.MainCommand.getInstance().help" is null

-> Chat: /plot wea
-> Chat: This is not a valid parameter

### Expected behaviour

I thought to see the help menu with /plot
I thought to copy a Plot with worldedit but I cant because it is not a valid parameter..

### Screenshots / Videos

https://imgur.com/a/HpvRe28

### Error log (if applicable)

https://paste.gg/p/anonymous/f8e3179e6d0e4ab1aa06e48b9b2be149

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/f782498f398044a19f0bf7f13d65dd31

### PlotSquared Version

PlotSquared Version: 5.13.12

### Checklist

- [X] I have included a Plot debugpaste.
- [ ] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by dordsor21** [comment]
Use an up to date version of P2. v5 is superseded by v6 as of a long time ago.

**Comment by CuzImFl4mer** [comment]
But I want to play on a 1.16.5 Server so I need Java 16 but when I use Java 17 the server wont work

**Comment by dordsor21** [comment]
We're following Mojang's policy and require modern Java versions for our plugins too. Currently, all our plugins require Java 17. If you are unsure how to update your Java version, checkout this guide: [docs.papermc.io/java-install-update](https://docs.papermc.io/java-install-update).
If you are using a version prior to 1.17, add -DPaper.IgnoreJavaVersion=true to your JVM flags (before -jar) and your server skips the Java version check, and use Java 17 on a [paper](https://papermc.io/) server.

**Comment by CuzImFl4mer** [comment]
Okay, so I use CloudNet where can I paste this in? :o
