### ISSUE TITLE
Cannot invoke "com.plotsquared.core.configuration.ConfigurationSection.getString

### ISSUE THREAD

**Issue by ErythroCraft** [IntellectualSites/PlotSquared#3694]
### Server Implementation

Spigot

### Server Version

1.19

### Describe the bug

[PlotSquared] Task #50 for PlotSquared v6.9.0-Premium generated an exception
java.lang.NullPointerException: Cannot invoke "com.plotsquared.core.configuration.ConfigurationSection.getString(String, String)" because "<local3>" is null

null is not exeptable since 1.18

[bug_long.txt](https://github.com/IntellectualSites/PlotSquared/files/8934310/bug_long.txt)

### To Reproduce

1. installing Nova plugin
2. Ask to Nova creators (it is not a bug of Nova)
3. Ask you

### Expected behaviour

Starting server without bug.

I don't know what is the misstake. I think it is a compatibelity problem of Nova and Plotsquared.

Please Watch out and say, if I can fix this by my self without uninstalling your plugin.
Maybe you must fix this.

Only I know that [NULL] is not exepted since version 1.18

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/838ddfe45c574990ae49efdebc5c5d89

### PlotSquared Version

PlotSquared v6.9.0-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by ErythroCraft** [comment]
Maybe I must delete the cinfig file form the last version of 1.18.2 ??

**Comment by dordsor21** [comment]
When you mention nova, is it specifically with nova that the error occurs?

**Comment by ErythroCraft** [comment]
Yes.

Because the world "world" (watch out latest log) was not set to plotsquared.
Nova is creating the world "world" by self and player can not use the world.

But I've seen the file bug_long.txt is empty.
I uploaded the file again. There can you see the bug lines.

**Comment by ErythroCraft** [comment]
[bug_long.txt](https://github.com/IntellectualSites/PlotSquared/files/8992890/bug_long.txt)

**Comment by NotMyFault** [comment]
I'm not able to replicate the issue based on the steps provided using your provided setup through the debugpaste to obtain named stacktrace.
