### ISSUE TITLE
PlotSquared /p delete is not working because of 'block timer'

### ISSUE THREAD

**Issue by IpanXBread** [IntellectualSites/PlotSquared#3696]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

After /plot delete, i need to /plot confirm.

Then the message of "a set block timer is bound to either the current plot of you. Please wait for it to finish" appears.

and nothing happen, /plot delete doesnt work.

### To Reproduce

1. Install PlotSquared
2. Install FAWE
3. Create plot world
4. /plot auto
5. /plot delete
6. /plot confirm

### Expected behaviour

The plot is deleted, and other players can /p claim it.

### Screenshots / Videos

![211212](https://user-images.githubusercontent.com/107781428/174464373-91440503-a1f4-4bdf-9e2b-4205155548bb.png)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/c6ae0d6396dc4037b0680563e0d3523d

### PlotSquared Version

PlotSquared-Bukkit-6.0.6-SNAPSHOT

### Checklist

- [X] I have included a Plot debugpaste.
- [x] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

no

**Comment by dordsor21** [comment]
This is a heavily outdated version. Please use the latest version(s) of P2.

**Comment by IpanXBread** [comment]
i have download the latest, now it doesnt work at all, no /plot command will give any output because "Error occured while enabling PlotSquared v4.4.495 (Is it up to date?)

https://www.spigotmc.org/resources/plotsquared-v4-v6-out-now.1177/history

**Comment by NotMyFault** [comment]
As dordsor said, the latest version is not v4 but v6: https://www.spigotmc.org/resources/plotsquared-v6.77506/

**Comment by IpanXBread** [comment]
ok, but the problem is FAWE, not really PlotSquared.
1. Remove FAWE
2. Get World Edit
3. /mv create a new plot world
4. it works fine, until i put FAWE plugin again, it becomes the same error
