### ISSUE TITLE
Biome "custom" recognised as valid biome

### ISSUE THREAD

**Issue by traksag** [IntellectualSites/PlotSquared#3697]
### Server Implementation

Paper

### Server Version

1.19

### Describe the bug

Players can run `/p set biome custom` and PlotSquared will think "custom" is a valid biome. The biome "custom" also appears in tab completions. After running the command, console gets spammed with errors as can be seen in the debug paste.

Note that this also happens on 1.18.2.

### To Reproduce

Simply run `/p set biome custom` or view the tab completions of `/p set biome <tab>`.

### Expected behaviour

I would expect PlotSquared to treat `/p set biome custom` as if the player ran `/p set biome test` (or any other invalid biome). It also shouldn't appear in tab completions.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/6e75c3e17e07418b858f2e529b109240

### PlotSquared Version

6.6.3-SNAPSHOT

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by dordsor21** [comment]
This is effectively a WorldEdit issue

See EngineHub/WorldEdit#1856 and EngineHub/WorldEdit#1538
