### ISSUE TITLE
Roads and under plots are not fully removed/generated with merge/unlink/delete

### ISSUE THREAD

**Issue by AnonymioD** [IntellectualSites/PlotSquared#3710]
### Server Implementation

Spigot

### Server Version

1.18.2

### Describe the bug

Hello

Blocks of road not fully removed after /plot merge or /plot unlink or /plot delete
Blocs underneath plot not fully generated

### To Reproduce

/plot claim (x2 or more)
/plot merge
(randomly some part of roads not removed)

OR

/plot delete
(randomly some part of roads not generated correctly

OR

/plot unlink
(randomly some part of roads not generated correctly

### Expected behaviour

Roads and plots (underneath) should be full

### Screenshots / Videos

![2022-06-24_16 45 39](https://user-images.githubusercontent.com/101605363/175561061-17ee1e18-ca97-4df6-9a85-a1830e42b867.png)
![2022-06-24_16 43 40](https://user-images.githubusercontent.com/101605363/175561064-a88d27bc-9112-4a3e-b048-d453176c0f37.png)
![2022-06-24_16 43 15](https://user-images.githubusercontent.com/101605363/175561068-57f4bb2c-93c0-4302-b2e1-8f72f24fefe6.png)
![2022-06-24_16 32 56](https://user-images.githubusercontent.com/101605363/175561071-7745c56d-8321-4944-857e-24b76a65cd60.png)
![2022-06-24_16 32 34](https://user-images.githubusercontent.com/101605363/175561074-a857be1e-3376-4f2b-9ec3-8438f121df3b.png)
![2022-06-24_16 32 29](https://user-images.githubusercontent.com/101605363/175561076-7a0ed35c-541d-4d77-89f6-56fbacd823a4.png)
![2022-06-24_16 32 21](https://user-images.githubusercontent.com/101605363/175561079-464fb154-bdab-47f0-bc2c-4fc8b96b2b59.png)
![2022-06-24_16 32 11](https://user-images.githubusercontent.com/101605363/175561083-0b072885-c312-423b-b8dd-b08720056b55.png)
![2022-06-24_16 26 52](https://user-images.githubusercontent.com/101605363/175561085-4d326f02-fbb8-418f-99be-f608ea10e748.png)
![2022-06-24_16 26 15](https://user-images.githubusercontent.com/101605363/175561087-b87ea0f6-d3f7-446a-96d1-28c32a34fda7.png)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/a233620895594b4ba20f9b38260c2540

### PlotSquared Version

PlotSquared-6.8.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [ ] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

WorldEdit 7.2.10

**Comment by NotMyFault** [comment]
Unticking the last checkbox as it doesn't apply. Please correct that, additionally, try to use an up to date version of WorldEdit only or FAWE.

**Comment by AnonymioD** [comment]
Hello, with Plotsquared-6.9.2-Premium its fixed
