### ISSUE TITLE
Spam error?

### ISSUE THREAD

**Issue by Monsiieur** [IntellectualSites/PlotSquared#3712]
### Server Implementation

Paper

### Server Version

1.19

### Describe the bug

For some reason when I load plotsquared o I do "/plotsquared reload" this error spams in the console. https://mclo.gs/7TWsf2b also I can't create a road higher than 70 blocks.

### To Reproduce

1. I start the server 
2. The plugin works but the errors still spamming the console
3. It spams when I do /plotsquared reload.

### Expected behaviour

I was hoping that the schematic roads I made would be applied correctly but because of this error I can't.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/77248719/175834336-6d9de073-c9cf-4e3a-8838-1a3ce7f1868e.png)

### Error log (if applicable)

https://mclo.gs/7TWsf2b

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/23cd9dcd8d3445c08356cc24a264255d

### PlotSquared Version

PlotSquared version 6.9.1-SNAPSHOT

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by dordsor21** [comment]
Would you be able to provide the schematic(s) you're using?

**Comment by Monsiieur** [comment]
> Would you be able to provide the schematic(s) you're using?

I was testing and only happen when the height of the road is from 70 or higher, also when I execute /plotsquared reload

**Comment by NotMyFault** [comment]
Does that happen with 6.9.1 only? Is 6.9.0 fine?

**Comment by NotMyFault** [comment]
Resolved in https://github.com/IntellectualSites/PlotSquared/pull/3722
