### ISSUE TITLE
Multiples plots bug

### ISSUE THREAD

**Issue by Wiktorr0** [IntellectualSites/PlotSquared#3715]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

Hi, I've got a bug.

A player can have only 1 plot, but there is a bug that allows him to bypass this permission. Player X creates a plot and gives the ownership to player Y. 
Later, player X creates a new plot and gives the ownership to player Y. This way player Y can have an infinite number of plots. 
Is there any way to to fix it? Its a really important bug ;V. 

### To Reproduce

Claim a plot, change ownership to other player and repeat.

### Expected behaviour

Any help to fix it!

### Screenshots / Videos

[](url

https://user-images.githubusercontent.com/108430285/176520556-de42a042-6fdb-4f03-b217-6bc8acf2b405.mp4

)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/cb970f436981454cb2969fea56a8d6e2

### PlotSquared Version

PlotSquared v6 6.9.1

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by SirYwell** [comment]
`/plot setowner` is an admin command. It ist not meant to be accessible to normal players.
