### ISSUE TITLE
Cannot build in middle of merged plots

### ISSUE THREAD

**Issue by Phantom-development** [IntellectualSites/PlotSquared#372]
When a User merge his plot with another plot, e can't build on the middle of the plots!

Need help! Sorry for my bad English (i'm German)

**Comment by EvilOlaf** [comment]
AFAIR this has been fixed quite a while ago. Do you use the latest version? Also what version of CB/Spigot U R running?

**Comment by Phantom-development** [comment]
Iam running spigot 1.8.7

**Comment by Phantom-development** [comment]
And version 2.11.27

**Comment by Phantom-development** [comment]
Of plotsquared

**Comment by boy0001** [comment]
Could you attempt to unlink, then merge one set of affected plots to see if it fixes the issue?

**Comment by diecode** [comment]
Maybe spawn-protection in server.properties? Set it 0 and try it again.

**Comment by Sauilitired** [comment]
@Phantom-development Any updates on this? Otherwise I'd assume that it's solved.

**Comment by Phantom-development** [comment]
Yes ITA solved
