### ISSUE TITLE
Mangrove trees grow into the plot road

### ISSUE THREAD

**Issue by Elioby** [IntellectualSites/PlotSquared#3721]
### Server Implementation

Paper

### Server Version

1.19

### Describe the bug

When Mangrove Propagules grow naturally, they grow into the road. Note that this does not happen when they are bonemealed.

### To Reproduce

Put a Mangrove Propagule right on the edge of a plot border and wait for it to grow naturally.

### Expected behaviour

The tree is cut off at the edge of the plot, like other trees.

### Screenshots / Videos

A naturally grown Mangrove tree.
![image](https://user-images.githubusercontent.com/7284033/177145596-f5bea559-e9d1-4726-8089-f6cb41eac6ea.png)

A Mangrove tree grown with bonemeal.
![image](https://user-images.githubusercontent.com/7284033/177145655-b864b2cc-1f9c-4c28-b107-088d955f0522.png)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/fc3e7be643464dcfbd81e4cae45d31e2

### PlotSquared Version

6.9.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
If this applies to mangrove trees only, this is probably an upstream issue.

**Comment by NotMyFault** [comment]
Labeling as CB/B/S/P issue for now, testing on Paper build 46 doesn't fire `StructureGrowEvent` when it should, I assume? I'm not really up to date with 1.19 yet, API wise.

**Comment by Elioby** [comment]
I've managed to find a report of this here: https://github.com/PaperMC/Paper/issues/8022

And a PR to fix it here: https://github.com/PaperMC/Paper/pull/8023

I guess you're right, it is an upstream issue sadly.
