### ISSUE TITLE
Generating new plots far away causes chunk generation exceptions

### ISSUE THREAD

**Issue by Elioby** [IntellectualSites/PlotSquared#3724]
### Server Implementation

Paper

### Server Version

1.19

### Describe the bug

When teleporting to plots really far away (`/p v 6969696;696969`), exceptions are generated. This seems to be related to 1.19 generation.

Disabling structure generation in the BukkitPlotGenerator [here](https://github.com/IntellectualSites/PlotSquared/blob/c446a95b0751dab9f6946100dd775c89a7a6fdd1/Bukkit/src/main/java/com/plotsquared/bukkit/generator/BukkitPlotGenerator.java#L253) by returning false seems to fix the issue completely. I can't see why structures would need to be generated anyway?

I've recreated the issue on the latest 6.9.2-Premium, but we still run 6.9.1-Premium on production right now.

### To Reproduce

1. Go to plot world
2. Run /p v 6969696;696969

### Expected behaviour

You teleport to the expected plot without exceptions

### Error log (if applicable)

https://gist.githubusercontent.com/Elioby/b33041c5f94392524d664313f3419f60/raw/c7de0c488fd9214116d08b53b445634f41f3ff88/gistfile1.txt

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/fc3e7be643464dcfbd81e4cae45d31e2

### PlotSquared Version

6.9.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Which coordinates are you at there? Such high numbers often hit inbuilt game limitations.

**Comment by Elioby** [comment]
On my fixed version, I actually can't even teleport there, it just refuses to teleport. But, it doesn't show any errors. We've also had this issue crash our servers with the same exception.

**Comment by NotMyFault** [comment]
> On my fixed version, I actually can't even teleport there

There are quite a bunch of hardcoded limits, BaseBlockPosition#isValidLocation() would be one of these limits I'm aware of used for teleportation, there are a few more, though I have no server code at hand atm.

This is generally not something worth to bother with, if you play the game within its bounds.

**Comment by Elioby** [comment]
Not sure I understand, players are crashing our server with this. We can't simply ask them to play within the bounds of the game, they will abuse it to crash the server.

**Comment by NotMyFault** [comment]
If you use your own server version, you are likely able to patch that yourself and expand the build in boundaries.

If you are not able to do that, you can always trim the world, setup a world border, clear edge plots or implement other safety measures.
