### ISSUE TITLE
Admin gamemode flag bypass

### ISSUE THREAD

**Issue by boy0001** [IntellectualSites/PlotSquared#373]
> Is there a way for admins to not be set into gamemode 0 (survival) even if the plot has that flag set?
> cowgod

**Comment by Sauilitired** [comment]
Additionally, we could send them a message saying that their gamemode wasn't changed, just... cause!

**Comment by EvilOlaf** [comment]
...cause people could ask stupid question why the gamemode flag did not work for them :D
