### ISSUE TITLE
Newlines in flags keep the backslash in the confirmation message

### ISSUE THREAD

**Issue by Elioby** [IntellectualSites/PlotSquared#3730]
### Server Implementation

Paper

### Server Version

1.19

### Describe the bug

When using \n in flags, the backslash stays.

### To Reproduce

1. Run `/plot flag set greeting hi\nhi2\nhi3`

### Expected behaviour

The greeting should be set to:
hi1
hi2
hi3

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/7284033/179375094-44556f22-c5b4-454d-bcc7-630f5976064e.png)

### Error log (if applicable)

N/A

### Plot Debugpaste

N/A

### PlotSquared Version

6.9.2-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
I'm unable to replicate that:
![](https://i.imgur.com/2nblNin.png)
Please provide a debugpaste and we will reopen the issue.

**Comment by Elioby** [comment]
Here is the debugpaste: https://athion.net/ISPaster/paste/view/8226c073743e449996073ccce4dff8eb

**Comment by Elioby** [comment]
Requesting this to be reopened
