### ISSUE TITLE
Add Mob/Villager Interact

### ISSUE THREAD

**Issue by JamesBach93** [IntellectualSites/PlotSquared#3731]
### What feature do you want to see added?

Hey,
some Users want to make an Automaticly Sheep Farm, Villager Breeding Station and Ofcurse Fox Farm that Farms Berries.

Now my Request, is there any chance to add an Flag to allow this on Plots ?

### Are there any alternatives?

There are no Alternatives.. :/

### Anything else?

It would be a pleasure for me to implement this Flag.
So my Users can have more fun on her Plots.

**Comment by resi23** [comment]
villager-interact
Set to true to allow guests to interact with villagers in the plot.
default: False
