### ISSUE TITLE
PlotArea.getId() is null

### ISSUE THREAD

**Issue by Teyir** [IntellectualSites/PlotSquared#3732]
### Server Implementation

Paper

### Server Version

1.19

### Describe the bug

When I try to create a single area  (I follow this guide → https://intellectualsites.github.io/plotsquared-documentation/customization/single-plot-area.html )

And when I execute the command I have this error
![image](https://user-images.githubusercontent.com/60007549/179848607-3dac5f9f-679d-45c4-b718-d47092e17340.png)

### To Reproduce

Follow this guide → https://intellectualsites.github.io/plotsquared-documentation/customization/single-plot-area.html

### Expected behaviour

I just want to create a single area for my plot

### Error log (if applicable)

https://paste.gg/p/anonymous/7fab175c322e45499ad7b77ac92ad876

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/52e5cf8b20fa4acf80ff4efc0c15fd3d

### PlotSquared Version

6.9.2-premium

### Checklist

- [x] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
> I'm not on the default world
> 

Which world are you in then? More information is needed.

**Comment by Teyir** [comment]
World skyblock and it's a 'normal' world

**Comment by Teyir** [comment]
I create this world with the command : `plot template import skyblock skyblock`

**Comment by NotMyFault** [comment]
Then you are already in a plot world and don't need to create an area. This inevitbly leads to unwanted side effects. If the template doesn't work or is not up to date, that would be a different issue then.
