### ISSUE TITLE
PlotSquared doesn't work with Paper's mini message

### ISSUE THREAD

**Issue by josephjthomas** [IntellectualSites/PlotSquared#3736]
### Server Implementation

Paper

### Server Version

1.19

### Describe the bug

PlotSquared doesn't work with mini message from Paper. I have to use 1.19 in my build files, if I add PlotSquared, mini message stops working in my plugin.

### To Reproduce

1. Import PlotSquared into your project, I use https://intellectualsites.github.io/plotsquared-documentation/api/api-documentation.html#_maven_plotsquared_core
2. I added Paper 1.19
3. Use Mini message, I used the following example https://docs.adventure.kyori.net/minimessage/api.html#builder

### Expected behaviour

PlotSquared and the API works with the mini message version provided by Paper.

### Plot Debugpaste

N/A, API related question

### PlotSquared Version

6.9.2

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
PlotSquared uses an older release of MiniMessage, 4.1 if I'm not mistaken. Paper bundles a newer version with various changes that are not compatible with prior versions of MiniMessage.

**Comment by NotMyFault** [comment]
> What is your recommendation to sort the mess out?

v7 uses the up to date version of MM
