### ISSUE TITLE
New Weather Flag Suggestion

### ISSUE THREAD

**Issue by RocketManKian** [IntellectualSites/PlotSquared#3737]
### What feature do you want to see added?

Add a new ‘Thunder’ option for the weather plot flag.

### Are there any alternatives?

Nope, the only weather options currently are: rain and clear.

### Anything else?

N/A

**Comment by NotMyFault** [comment]
Bukkit only exposes rainy and clear as API. While some packet shanigans exist nowadays, this is not feasible to achive by using the API.
