### ISSUE TITLE
p alias Problem and villager Farm Problem

### ISSUE THREAD

**Issue by UBSMentis** [IntellectualSites/PlotSquared#3738]
### Server Implementation

Paper

### Server Version

1.19

### Describe the bug

p alias are already taken although never used. p alias remove does not work. it means this alias is already in use.
Please insert a yml with all set aliases for manual deletion.

Villagers don't plant anything as soon as plotsquared is active. gamerule mobgriefeing is active. but the villagers do nothing.

### To Reproduce

yml with all set aliases for manual deletion or a command alias list and alias delete for existing deletion aliases for op.
Villager must place items.

### Expected behaviour

p alias commands must work set and remove but many aliases are already used although never used
the villagers plant seeds

### Screenshots / Videos

![Unbenannt](https://user-images.githubusercontent.com/98167775/181003289-a12af21c-1315-4f6a-a1ec-6d15fad3c4e6.JPG)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/eac2ad0ffb1b4c1697c262e9eb7e6c4c

### PlotSquared Version

6.9.3

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

pls make a alias yml ore mysql and a Operator command to delete any alias they is set.

**Comment by NotMyFault** [comment]
An alias can't be an username. For villagers, see the open enhancement proposal.
