### ISSUE TITLE
p alias set and remove

### ISSUE THREAD

**Issue by UBSMentis** [IntellectualSites/PlotSquared#3740]
### Server Implementation

Paper

### Server Version

1.19

### Describe the bug

p alias set and remove does not work correctly. If you want to set an alias, the message that alias is already taken appears. However, this name was not assigned as an alias or does a player with this name exist. please help
p alias set und remove funktioniert nicht richtig., nach dem mergen ist der alias des plots verschwunden und kann weder neu gesetzt noch entfernt werden. sihe Bild. Hilfe wäre schön deswegen bitte nicht schließen, wäre gut zu wissen wo die aliase gespeichert werden oder das ihr da bitte einen blick drauf werft. wie am bild zu erkennen kann man den alias weder setzten noch entfernen und wenn man /p v alias name macht existiert es nicht. und nein der alias ist kein spielername der auf unserem server existiert ebenso wie hogwarts und viel andere aliase die nicht benutz werden können weil sie angeblich schon benutzt werden, was nicht der fall ist. bitte dringend um hilfe mit diesem problem.

### To Reproduce

help with this issui what can i do ? 

### Expected behaviour

that it works to delete and reassign aliases

### Screenshots / Videos

![Unbenannt](https://user-images.githubusercontent.com/98167775/181086896-d06b9773-23f1-4605-bd91-0acdcfbd5dc4.JPG)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/8eb4d3b881f1443aa104433b15005149

### PlotSquared Version

6.9.3

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Duplicate of #3738
