### ISSUE TITLE
Plot Height bug

### ISSUE THREAD

**Issue by iPlexy** [IntellectualSites/PlotSquared#3747]
### Server Implementation

Paper

### Server Version

1.19

### Describe the bug

We moved to 1.19 and the roads broke. new generated roads were too low. now we created a new road schematic and started the regen of all roads and now this
![image](https://user-images.githubusercontent.com/61617739/181582391-a55518f9-2466-4e0b-83ef-3e2c9ac5183a.png)
 

### To Reproduce

Upload from 1.18 to 1.19 in ver 6.9.2
Update to 6.9.3
create road schematic
paste road schematic
BOOM

### Expected behaviour

A normal road

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/61617739/181582714-d45fef5f-1989-430d-a7f8-6e082776f944.png)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/eb1ce5a5ebcf4d6888ff2c93899c23a1

### PlotSquared Version

6.9.3

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Take a look at your worlds.yml.
Your plot height is set to 62, your wall height to 61 and your road height to 63. Adjusting the latter to your plot height restores it. Keep in mind to regenerate affected areas.
