### ISSUE TITLE
Compatibility issue with Paradise Land Plugin

### ISSUE THREAD

**Issue by Firetop** [IntellectualSites/PlotSquared#3751]
### Server Implementation

Paper

### Server Version

1.19

### Describe the bug

[ParadiseLand] Missing ParadiseLand generator for CheckingPlotSquaredGenerator world.
[18:37:24 WARN]: [ParadiseLand] Make sure that when you create the world, your generator type is ParadiseLand:generator.yml
[18:37:24 WARN]: [ParadiseLand] where 'generator.yml' is one of the available generators:
[18:37:24 WARN]: [ParadiseLand] 1) ParadiseLand:eden.yml
[18:37:24 WARN]: [ParadiseLand] If your world management plugin says that it cannot find the generator, send to gamerover98 (plugin's author) a personal message on SpigotMC.org
[18:37:24 WARN]: java.lang.IllegalStateException: The world generator ID is empty. Try with "ParadiseLand:eden.yml"
[18:37:24 WARN]: at ParadiseLand-Reworked-BETA-1.1.7.jar//it.gamerover.paradise.ParadiseLand.getDefaultWorldGenerator(SourceFile:200)
[18:37:24 WARN]: at PlotSquared-Bukkit-6.9.3-Premium.jar//com.plotsquared.bukkit.util.BukkitSetupUtils.updateGenerators(BukkitSetupUtils.java:79)
[18:37:24 WARN]: at PlotSquared-Bukkit-6.9.3-Premium.jar//com.plotsquared.bukkit.BukkitPlatform.lambda$onEnable$1(BukkitPlatform.java:429)
[18:37:24 WARN]: at PlotSquared-Bukkit-6.9.3-Premium.jar//com.plotsquared.bukkit.util.task.BukkitPlotSquaredTask.runTask(BukkitPlotSquaredTask.java:39)
[18:37:24 WARN]: at PlotSquared-Bukkit-6.9.3-Premium.jar//com.plotsquared.core.util.task.PlotSquaredTask.run(PlotSquaredTask.java:44)
[18:37:24 WARN]: at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[18:37:24 WARN]: at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[18:37:24 WARN]: at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1138)
[18:37:24 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[18:37:24 WARN]: at java.base/java.lang.Thread.run(Thread.java:833)

### To Reproduce

1. Create a world with Paradise Land's Command: /mv create paradise NORMAL -g ParadiseLand:eden.yml -t FLAT
2. Create a world with PlotMe Squard.
3. Reboot Server.

### Expected behaviour

For both plugins to work on their respective worlds together.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/70effec4e07e4a00b63dafc1e6fde87f

### PlotSquared Version

PlotSquared-Bukkit-6.9.3-Premium.jar

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
I recommend you do what the message tells you to do:
> [18:37:24 WARN]: [ParadiseLand] 1) ParadiseLand:eden.yml
[18:37:24 WARN]: [ParadiseLand] If your world management plugin says that it cannot find the generator, send to gamerover98 (plugin's author) a personal message on SpigotMC.org

"Paradise Land Plugin" is a closed source premium plugin nobody can help you with but the plugin author.

**Comment by Firetop** [comment]
> I recommend you do what the message tells you to do:
> 
> > [18:37:24 WARN]: [ParadiseLand] 1) ParadiseLand:eden.yml
> > [18:37:24 WARN]: [ParadiseLand] If your world management plugin says that it cannot find the generator, send to gamerover98 (plugin's author) a personal message on SpigotMC.org
> 
> "Paradise Land Plugin" is a closed source premium plugin nobody can help you with but the plugin author.

I recommend you speak to the author yourself instead of closing the issue without any dudiligence.

![image](https://user-images.githubusercontent.com/1971404/182028715-c287cbb2-2654-4da5-bf35-54467f502200.png)

Issue is being re-opened.

**Comment by SirYwell** [comment]
The plugin should return null instead of throwing an exception.

**Comment by Firetop** [comment]
> The plugin should return null instead of throwing an exception.

Not my problem, I'm not a developer. I reported it to both of you; so you are both aware it's coming.

If you need anymore info from a server with the issue; please let me know.

**Comment by NotMyFault** [comment]
> I recommend you speak to the author yourself instead of closing the issue without any due diligence.

I have no motivation in involving myself into closed source plugins. The more bullet proof solution is proper error handling and catching those errors.

**Comment by Firetop** [comment]
> > I recommend you speak to the author yourself instead of closing the issue without any due diligence.
> 
> I have no motivation in involving myself into closed source plugins. The more bullet proof solution is proper error handling and catching those errors.

Thanks. If you don't care about the issue so be it; but just goes to show the kind of work you do. "I don't care; let him fix it".
That that kinda attitude; I think it's best I remove PlotSquard if this is how you guys deal with bug reports.

**Comment by PierreSchwang** [comment]
> > > I recommend you speak to the author yourself instead of closing the issue without any due diligence.
> > 
> > I have no motivation in involving myself into closed source plugins. The more bullet proof solution is proper error handling and catching those errors.
> 
> Thanks. If you don't care about the issue so be it; but just goes to show the kind of work you do. "I don't care; let him fix it".
> That that kinda attitude; I think it's best I remove PlotSquard if this is how you guys deal with bug reports.

Should we buy a 12 Euro plugin which we don't need at all instead?

**Comment by Firetop** [comment]
> > > > I recommend you speak to the author yourself instead of closing the issue without any due diligence.
> > > 
> > > 
> > > I have no motivation in involving myself into closed source plugins. The more bullet proof solution is proper error handling and catching those errors.
> > 
> > 
> > Thanks. If you don't care about the issue so be it; but just goes to show the kind of work you do. "I don't care; let him fix it".
> > That that kinda attitude; I think it's best I remove PlotSquard if this is how you guys deal with bug reports.
> 
> Should we buy a 12 Euro plugin which we don't need at all instead?

You can ask the developer above? The one saying they will message you? Man I guess sending a message is so tricky right?

**Comment by Firetop** [comment]
In case you haven't noticed; that developer is very receptive to look into it since it involves another plugin except his own; you guys are the only ones closing the door and throwing a wrench in the gears for nothing.

I I'll remove the plugin and stop reporting any bugs; thanks again! Easy peasy.

**Comment by NotMyFault** [comment]
> Thanks. If you don't care about the issue so be it; but just goes to show the kind of work you do.

Nobody ever said they do not care about the issue, you just walked up with the wrong expecations.
We can't add support for all kinds of plugins, especially not for closed soure & premium plugins, unless they provide a public API licensed under an approved open source license on a standard maven3 repository, like the central repository, which this plugin doesn't.

Asking the developer of a plugin for their jar doesn't help us in any way to add support for that plugin, because we would need to make their jar publicly accessible on our GitHub repository, which likely goes against the goals of a plugin developer, if they've chosen not to do so in the past.

PlotSquared contains support for closed source third party plugins, like FeatherBoard, by consuming its API and adding third party features, but it's unrealistic to expect support to read a file of a specific plugin for certain information.
These kinds of informations need to be accessible through an API with the standarsd named above, if you want third parties to consider to use it.

**Comment by Firetop** [comment]
Thank you @gamerover98 .

At least your willing to work with any other dev team to identify the issue.

**Comment by SirYwell** [comment]
> I will fix the issue by returning null. In any case, I suggest you to handle any Exception to avoid future issues.

Thanks. We already catch exceptions but we only print them without other handling. Maybe we can improve that in future.

**Comment by Firetop** [comment]
> > Thanks. If you don't care about the issue so be it; but just goes to show the kind of work you do.
> 
> Nobody ever said they do not care about the issue, you just walked up with the wrong expecations. We can't add support for all kinds of plugins, especially not for closed soure & premium plugins, unless they provide a public API licensed under an approved open source license on a standard maven3 repository, like the central repository, which this plugin doesn't.
> 
> Asking the developer of a plugin for their jar doesn't help us in any way to add support for that plugin, because we would need to make their jar publicly accessible on our GitHub repository, which likely goes against the goals of a plugin developer, if they've chosen not to do so in the past.
> 
> PlotSquared contains support for closed source third party plugins, like FeatherBoard, by consuming its API and adding third party features, but it's unrealistic to expect support to read a file of a specific plugin for certain information. These kinds of informations need to be accessible through an API with the standarsd named above, if you want third parties to consider to use it.

As I client of both your plugins; if you point the finger at him; and he points it at you; it's not my job to figure out whos lying.
Truth is mo one is lying; everyone just has a different view point of how it should work.

Maybe you guys should of just taken the FYI and looked into it a bit more or at least messaged @gamerover98 before closing the issue. Just a simply "Thanks for letting us know." before closing it would of been better than the above.

I am only trying to help here by reporting issues to related devs. You guys need to work together and stop point the fingers at eachother; as a client of both plugins; I shouldn't need to be bounced around between both of you; you two should come together identify the best way forwards seeing you have different methods of dealing with exceptions.

Luckily it seems like this coming together and working it out did end up happening in this thread without it being open; but the point still stands that the thread needed to happen for a communication platform between the both of you; and it's best to not simply just close stuff without thinking.
