### ISSUE TITLE
Roads wont genarate

### ISSUE THREAD

**Issue by Josh-65** [IntellectualSites/PlotSquared#3755]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

When i use the `/plot createroadschematic` command it says it successful. using the `/plot debugroadregen` command loads nothing. The schematic show in the folder and world edit can load.paste them fine.

### To Reproduce

1. go into a world
2. create a road
3. use /plot createroadschematic
4. go to blank/old road area
5. use /plot debugroadregen

### Expected behaviour

Roads should show

### Error log (if applicable)

https://gist.github.com/Josh-65/a5a37096ace88d8a979eeb9adbb47acc

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/d052077ea13444c4b3a35064d8cacc9c

### PlotSquared Version

6.9.4 snapshot

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by PierreSchwang** [comment]
Can't reproduce that - Can you upload your road schematic(s)?

**Comment by Josh-65** [comment]
[road.zip](https://github.com/IntellectualSites/PlotSquared/files/9245258/road.zip)

**Comment by PierreSchwang** [comment]
I mean, my world height is not the same, but it pastes without any errors tho 
![grafik](https://user-images.githubusercontent.com/27054324/182463457-9fe11660-9d61-43b2-9c53-aae05dc2c8cd.png)
![grafik](https://user-images.githubusercontent.com/27054324/182463486-f90e6298-6e52-48c6-a52a-53f325fcb336.png)

**Comment by Josh-65** [comment]
Works fine for me using 6.9.2 but i get the error i listed when using the updated version

**Comment by PierreSchwang** [comment]
Share your whole plotsquared configuration then please (complete plugins/PlotSquared folder)
Can't reproduce that issue with the steps you provided.

**Comment by Josh-65** [comment]
[Uploading PlotSquared.zip…]()

**Comment by Josh-65** [comment]
[PlotSquared.zip](https://github.com/IntellectualSites/PlotSquared/files/9277335/PlotSquared.zip)

**Comment by PierreSchwang** [comment]
[PlotSquared.zip](https://github.com/IntellectualSites/PlotSquared/files/9277422/PlotSquared.zip)

Issue was a configuration issue, which I fixed for you. Please test those changes and give a little response, if that fixed your issue (at least it does for me :D)

**Comment by Josh-65** [comment]
The road genarates but does it not allow using 0 to -64 arenas. as i would like to the top of the road to be at y=0 if possible

**Comment by PierreSchwang** [comment]
with that configuration the plots are generated from -64 to 0, the top of the road is at 0
![grafik](https://user-images.githubusercontent.com/27054324/183473191-5a0418b2-43e2-42f5-adc2-c24909500e96.png)

This is not the right place for help with configuration, rather join the discord.

**Comment by Josh-65** [comment]
Thanks for the help. deleted the world and had it regen now fixed it.
