### ISSUE TITLE
Granting/Adding a Plot to a player is inoperable

### ISSUE THREAD

**Issue by Wastinqs** [IntellectualSites/PlotSquared#3756]
### Server Implementation

Spigot

### Server Version

1.17.1

### Describe the bug

As I tried to grant/add a normal player another plot, typing /plot grant add player doesn't seem to do anything in response, as there happens nothing. /plot grant check player does also seem to not be working. 

As I can't make a use of the plot.plots.max permission I'm really in need of the plot grant function. Users on my server have the chance to individually upgrade their plots if they want. This can't be only a rank-perk.

My console looks as clean as never before and shows up zero errors.

Please fix this as soon as possible.

Using ps v 6.9.3 on spigot java17 mc 1.17.1

### To Reproduce

1. Go ingame
2. Type /plot grant add player
3. See that nothing happens

### Expected behaviour

I expected this command to grant/add a single player another plot. I don't know how many plots a players has already unlocked, so I needed to make a use of /plot grant add player to grant players another plot, for example via an commandtoitem or commandsign. Both aswell as the normal way through chat or console do not work.

### Screenshots / Videos

A video I made to show the bug:

[PlotSquared v 6.9.3 /P GRANT is BROKEN](https://youtu.be/jPZqphveZa0)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/b935fa9073a7460f88241898156507bc

### PlotSquared Version

PlotSquared bukkit 6.9.3-PREMIUM

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

Thank you for your fast and immidiate help!

Best regards,
Wastinqs

**Comment by Wastinqs** [comment]
Any news on this so far?

**Comment by NotMyFault** [comment]
> Any news on this so far?

See https://github.com/IntellectualSites/PlotSquared/pull/3759
