### ISSUE TITLE
Signs in schematic files is not paste correct

### ISSUE THREAD

**Issue by Rocologo** [IntellectualSites/PlotSquared#376]
1 ) I design a plot with signs in the plot and save the schematic as plot.schematic
2) When PlotSquared paste the schematic later,  all signs are blank???? 
3) I have tried both "/plot clear" , "plot delete" and "regerating the world" nometter what the signs are empty.
4) I have tried to load the schemtic file back with worldedit and the paste in the plot,  and then the sign was okay. So the bug is in PlotSquared.

**Comment by boy0001** [comment]
The world generator was never intended to generate signs with text

**Comment by Rocologo** [comment]
Well, Im not sure about how to read your answer? 

But to me it is strange that you support Schematic files, not not all information in the files? 

On my server I tried to make a small house with information-signs to the users in the schematic files, unfortunately all signs does not have any text on the signs wh er n the new plots are generated.

**Comment by dordsor21** [comment]
probably fixed when using FAWE
