### ISSUE TITLE
Impossible to click on the messages

### ISSUE THREAD

**Issue by NoltoxGit** [IntellectualSites/PlotSquared#3763]
### Server Implementation

Paper

### Server Version

1.19.1

### Describe the bug

Hi!
I just found out that it's impossible to click on the clickable commands in the chat such as `/plot list all` ...

### To Reproduce

1. Reset the languages files,
2. Do a command like `/plot list all, World` [...]

### Expected behaviour

When you click on the plot number or the nickname or the nickname of the player, you are supposed to either teleport and get information about the selected player.

### Screenshots / Videos

https://user-images.githubusercontent.com/75265787/183294621-69d60ce3-d82f-4ff8-b86c-54adc27f5007.mp4

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/84efd085f2794983a26863f6513c0558

### PlotSquared Version

PlotSquared version 6.9.3-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by PierreSchwang** [comment]
Not able to reproduce that issue with PS 6.9.4-SNAPSHOT.
Most likely due to a modded client and / or server.
