### ISSUE TITLE
Update snow tag shenanigans

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/PlotSquared#3765]
I personally would be a bigger fan of something like 
```
private static final Set<Material> SNOW_BLOCKS = Stream.of(Material.values())
            .filter(material -> material.name().contains("SNOW"))
            .filter(Material::isBlock)
            .collect(Collectors.toSet());
```
Maintainability would be better in that case, as static collections like that might get lost and forgot on updates. The only problems I've found on my testing is, that the cauldron filled with powedered snow ([SNOW_BLOCK, **POWDER_SNOW_CAULDRON**, POWDER_SNOW, SNOW]) is present in that set as well. But I don't think that's that big of an issue, as that block wouldn't call the BlockFormEvent.

_Originally posted by @PierreSchwang in https://github.com/IntellectualSites/PlotSquared/pull/3758#discussion_r939708900_

**Comment by NotMyFault** [comment]
cc @PierreSchwang @SirYwell outsourced as issue, because non blocking feedback.

**Comment by SirYwell** [comment]
Missed that the last few days. I'm not opposed to use the stream approach instead, but it might make sense to use `Collectors.toUnmodifiableSet()`. If you want, you can open a PR for it @PierreSchwang.
