### ISSUE TITLE
Road-Schematics not working with 'paste-road-on-top' enabled

### ISSUE THREAD

**Issue by PaBox** [IntellectualSites/PlotSquared#3772]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

With my current setup, I am only able to use road schematics when setting the road to a height of 0 and disabling this option. But I want to use the signs and put them on the slabs... 

When I flip this option, the schematic is not being used and instead an ArrayIndexOutOfBoundsException happens, before the world settings are displayed in the console (They are still displayed). It sometimes refers to the number '-63' if that can help.

### To Reproduce

1. Use a road schematic via templates (my setup)
2. Check, that the schematic is generating with the option set to 'true'
3. Change the option to 'false'
4. Check, that the schematic stopped generating with the option set to 'false'

### Expected behaviour

The Schematic should be used and override road blocks (instead of otherwise, where the street has to be non-existent to make the schematic appear)

### Error log (if applicable)

java.lang.ArrayIndexOutOfBoundsException

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/0777f02097a44786bbcea1882d73edc8

### PlotSquared Version

Plotsquared Version 6.9.4

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by dordsor21** [comment]
This may now be resolved in the latest P2 versions, please check this. If not, it would be useful to see the full error stacktrace

**Comment by PaBox** [comment]
This should be fixed - Signs now generate correctly and paste-on-top is working as it should. At least in 1.18.2 :)
