### ISSUE TITLE
Allow override to merge with other player's plot, even if they are offline

### ISSUE THREAD

**Issue by BensaTV** [IntellectualSites/PlotSquared#3779]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

Merging plots of two different players doesn’t work, even with OP and * permissions.

### To Reproduce

Try to merge two plots of two different players

### Expected behaviour

Plots of two players should be able to get merged again like it used to before.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/656a90d02fda48c6a94a3a8b6b043860

### PlotSquared Version

PlotSquared version 6.9.4-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by dordsor21** [comment]
The other player must be online for the merge to be completed currently.
