### ISSUE TITLE
plot list output is not clickable

### ISSUE THREAD

**Issue by InfectedCatBite** [IntellectualSites/PlotSquared#3781]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

The output of `/plot list all` is not clickable (for teleporting) and hovering does not show information about the plot. `Back | Next (interactive)` is not clickable, either.

### To Reproduce

1. Claim a plot (/plot claim)
2. List the plots (/plot list all)
3. Hover over the output and/or attempt to click on the plot number or `Back | Next (interactive)`

### Expected behaviour

You should be able to teleport by clicking on the plot number, find out information about the plot by hovering over the plot ID, and click on the Back | Next text. None of these actions work.

### Screenshots / Videos

N/A

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/6840a7272ec147a2af1acfa2f782cc70

### PlotSquared Version

PlotSquared version 6.9.4

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

This is a virgin test server, with only PlotSquared and WorldEdit plugins, on a brand new world. I followed the setup instructions in the Wiki. The player is op'ed.

**Comment by dordsor21** [comment]
I believe this is most likely a MiniMessage issue with 1.19 game version. It works fine on all versions 1.18.2 and below

**Comment by NotMyFault** [comment]
I verified this is fixed in v7.
