### ISSUE TITLE
Bypass plot deny bug

### ISSUE THREAD

**Issue by SciathGH** [IntellectualSites/PlotSquared#3782]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

The bug allows you to teleport into plots using multiple worlds.

### To Reproduce

If you go to 1000 & 1000 of one world, and you then teleport to your friend who's in another world and has denied you from their plot.
You can bypass the plot denial of any plot at 1000 & 1000.

### Expected behaviour

I'd expect that you'd be teleported to the world spawn instead of 1000 & 1000 of that world.

### Plot Debugpaste

Dont have access to the command

### PlotSquared Version

PlotSquared-6.9.4-SNAPSHOT

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
I'm unable to replicate the issue on Paper 1.19.2 build 246 and PlotSquared 6.10.3. The teleport is properly cancelled before entering the world.
