### ISSUE TITLE
Cannot invoke "com.plotsquared.core.plot.Plot.getId()" because the return value of "com.plotsquared.core.plot.PlotArea.getPlotAbs(com.plotsquared.core.location.Location)" is null

### ISSUE THREAD

**Issue by SpeastTV** [IntellectualSites/PlotSquared#3789]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

when I go to a specific plot comes this error and spam the hole console full.

`Cannot invoke "com.plotsquared.core.plot.Plot.getId()" because the return value of "com.plotsquared.core.plot.PlotArea.getPlotAbs(com.plotsquared.core.location.Location)" is null`
_More of the error in the pastebin._

### To Reproduce

Its hard to Reproduce its really specific. when i join on my cb server and go to a plot with the id -6;-4 the error comes. and spam the console full of this.

### Expected behaviour

No error or console spam.

### Error log (if applicable)

https://pastebin.com/HLWbhafm

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/94e51a9909eb4e0ea5e7244d77c915c0

### PlotSquared Version

Version: PlotSquared-6.9.4-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [x] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by SirYwell** [comment]
Can be reproduced by enabling `kill-road-mobs` and summoning a shulker on a road. The code at this place looks odd, the obvious fix does not remove shulkers at all. I need more time to figure out why the code was written like that.
