### ISSUE TITLE
My server crashes every time I try to use /plot createroadschematic - /plot regenallroads - /plot template

### ISSUE THREAD

**Issue by LostTM** [IntellectualSites/PlotSquared#3791]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

I am trying to use PlotSquared (Latest version) with Paper 1.17.1 (Latest available version of this version) to customize the paths of the plots but it is impossible for me because every time I use the following commands and explore the world a little my console it fills with errors continuously and ends up shutting down my server almost instantly.

The paths that I have created are really very basic, and I have even tried to test it by creating a new world and making minor changes to the plots but I always have problems with this.

Used commands:
/plot createroadschematic
/plot regenallroads
/plot template 
[error_plot.txt](https://github.com/IntellectualSites/PlotSquared/files/9481733/error_plot.txt)

### To Reproduce

I guess the only way to test it is using the commands I have left above using the latest available version of 1.17.1 from the official PAPER page and using the latest version of plotSquared from Spigot.

### Expected behaviour

I want to solve the problem and be able to have custom paths.

### Plot Debugpaste

It is impossible for me to execute this command, my server is closed before I can use it.

### PlotSquared Version

PlotSquared v6 6.9.4

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
I'm unable to replicate the issue with the steps provided.

**Comment by LostTM** [comment]
I've been testing versions of the plugin. And version 6.3.0 and it doesn't give me an error

Do you think it is very risky to use this version?

**Comment by SirYwell** [comment]
Closing this in favor of #3801 as those are duplicates and the other one has proper information.
