### ISSUE TITLE
New flag: block-updates

### ISSUE THREAD

**Issue by NoltoxGit** [IntellectualSites/PlotSquared#3792]
### What feature do you want to see added?

Hellow !!
 I come here to propose you my new idea which could enjoy more than one Builder, I explain :

It would be to add a flag that would allow to Enable/Disable the updates of the blocks, which is used for example not to break the flowers, doors and other placed with FAWE that break when you put a block next to it that updates it.

### Are there any alternatives?

The only alternative is to use [Builder-Utilites](https://ci.athion.net/view/Everything/job/Builders-Utilities/lastSuccessfulBuild/) and activate "`disable-physics: true`".

**Comment by dordsor21** [comment]
The `disable-physics` flag already exists
