### ISSUE TITLE
PlotSquared boot time takes long on server with a lot of plots in db

### ISSUE THREAD

**Issue by Xayanix** [IntellectualSites/PlotSquared#3796]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

If you have a lot of plots then PlotSquared takes ages to boot.
It hangs after this message:
![image](https://user-images.githubusercontent.com/12672902/188975818-c66f1dc6-e568-4cf6-9050-92afa478064d.png)
![image](https://user-images.githubusercontent.com/12672902/188976454-fd83dd82-0dcf-4016-81d1-7b844cfa91d7.png)

### To Reproduce

-

### Expected behaviour

Boot faster?

### Screenshots / Videos

Up

### Plot Debugpaste

-

### PlotSquared Version

latest

### Checklist

- [] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by PierreSchwang** [comment]
Dont check "I have included a Plot debugpaste." if you haven't added a debug paste. Otherwise we can't verify that you're running the latest version etc. Otherwise I have to close this Issue.

**Comment by Xayanix** [comment]
Was running outdated version.
