### ISSUE TITLE
plotsquared make a voidworld

### ISSUE THREAD

**Issue by elpalomomlg** [IntellectualSites/PlotSquared#3798]
### Server Implementation

Spigot

### Server Version

1.16.5

### Describe the bug

when i make a plotworld the plugin makes a vanilla world or a voidworld
![imagen_2022-09-10_173254614](https://user-images.githubusercontent.com/63897677/189502457-d3492771-f2db-412f-a9e6-a6044843e01a.png)

### To Reproduce

see

### Expected behaviour

i need a solution

### Error log (if applicable)

dont have errors

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/a40e19f023ce416c872d868b2a356736

### PlotSquared Version

PlotSquared v6 6.9.4

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by PierreSchwang** [comment]
Hybrids including Magma are not supported.
