### ISSUE TITLE
Road schematic only paste´s top blocks not blocks under the top layer

### ISSUE THREAD

**Issue by cynicalmax** [IntellectualSites/PlotSquared#3802]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

Hey there,
I´m trying to build a proper road schematic.
I built it around the plot but not only did I modify the top layer.
There are blocks beneath the top layer because I want to put beacons into the intersections with diamonds beneath.
When I create the road schematic and try it out, only the top layer is put onto roads.
Is this intended?

Sincerely cynicalmax

### To Reproduce

1. Create plotworld
2. Modify road with blocks beneath toplayer
3. Create road schematic
4. Debugpaste the road schematic
5. done

### Expected behaviour

Paste the whole road from Y:1 between the plots

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/21a47b95c5764a2589496e861cd28564

### PlotSquared Version

6.9.4 Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by cynicalmax** [comment]
Can someone please recreate this or confirm it?

**Comment by dordsor21** [comment]
This will likely be fixed by #3840
