### ISSUE TITLE
Error on regenallroads with fawe spamming the console!

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#3805]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

Console Spam: https://pastebin.com/nJSK4HWh

### To Reproduce

1. Install PS and fawe
2. Build Road (Use Slabs, Trapdoors, Walls, Flowerpots, Banners)
3. Regen

### Expected behaviour

No Errors!

### Error log (if applicable)

https://pastebin.com/nJSK4HWh

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/0eb9346e791e4511bac4dbc11f78ae97

### PlotSquared Version

6.9.4-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
It would help to provide a minimum viable product, to replicate your case.

**Comment by NotMyFault** [comment]
No response in over a month, assuming the issue has been resolved.
