### ISSUE TITLE
Custom tick speed for crops

### ISSUE THREAD

**Issue by aaron12312312** [IntellectualSites/PlotSquared#3806]
### What feature do you want to see added?

Ik my other post got closed for asking this but you said it can only be set world wide put you could try make your own method you could take a look at superiorskyblock does for a idea.

### Are there any alternatives?

Not that I can see

### Anything else?

Nope

**Comment by SirYwell** [comment]
It is not possible to modify this behavior via supported API, therefore it isn't suitable for PlotSquared. Anyone can write a third-party plugin with the required interaction with non-api code to support something like that, but such feature won't be added to PlotSquared directly as long as there isn't an official API for it.
