### ISSUE TITLE
It is not possible to remove the Villager interact flag with the correct permissions

### ISSUE THREAD

**Issue by Plattio** [IntellectualSites/PlotSquared#3810]
### Server Implementation

Paper

### Server Version

1.19

### Describe the bug

Players have no permission to remove the villager-interact flag with /plot flag remove villager-interact, despite having the correct permission.

Permission: plots.set.flag.villager-interact.*

With other flags it works without problems.

### To Reproduce

Give a player the permission plots.set.flag.villager-interact.* and try to remove the villager-interact flag.

### Expected behaviour

You can remove the flag.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/e1708b8335954d319a813ea08468d4c8

### PlotSquared Version

PlotSquared 6.9.2-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by resi23** [comment]
try plots.flag.remove.villager-interact

**Comment by Plattio** [comment]
> try plots.flag.remove.villager-interact

Not working also

**Comment by NotMyFault** [comment]
Remove the asterisk, this flag has no wildcard types.
