### ISSUE TITLE
Is it possible to remove a banned player from the /p v list ?

### ISSUE THREAD

**Issue by Razorxd1993** [IntellectualSites/PlotSquared#3811]
### What feature do you want to see added?

Is it possible to remove a banned player from the /p v list ?

All plots are removed and the player data from Essentials too

It's about a very inappropriate name and it should not really be seen in the list for younger players

Kind regards

### Are there any alternatives?

-

**Comment by NotMyFault** [comment]
You'd need to edit the database by hand.
