### ISSUE TITLE
Chunk failed to load

### ISSUE THREAD

**Issue by LordVardus** [IntellectualSites/PlotSquared#3817]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

29.09 18:56:35 [Server] INFO [com.fastasyncworldedit.bukkit.regions.plotsquared.PlotSquaredFeature] Optimizing PlotSquared
29.09 18:56:35 [Server] INFO [com.fastasyncworldedit.bukkit.FaweBukkit] Plugin 'PlotSquared' v6 found. Using it now.
29.09 18:56:35 [Server] WARN [PlotSquared/BukkitPlatform] `cb1` was not properly loaded - PlotSquared will now try to load it properly
29.09 18:56:35 [Server] WARN [PlotSquared/BukkitPlatform] - Are you trying to delete this world? Remember to remove it from the worlds.yml, bukkit.yml and multiverse worlds.yml
29.09 18:56:35 [Server] WARN [PlotSquared/BukkitPlatform] - Your world management plugin may be faulty (or non existent)
29.09 18:56:35 [Server] WARN [PlotSquared/BukkitPlatform] - The named world is not a plot world
29.09 18:56:35 [Server] WARN [PlotSquared/BukkitPlatform] This message may also be a false positive and could be ignored.
29.09 18:56:35 [Server] INFO [PlotSquared/PlotSquared] Detected world load for 'cb1'
29.09 18:56:35 [Server] INFO [PlotSquared/PlotSquared] - generator: PlotSquared>PlotSquared
29.09 18:56:35 [Server] INFO [PlotSquared/PlotSquared] - plot world: com.plotsquared.core.generator.HybridPlotWorld
29.09 18:56:35 [Server] INFO [PlotSquared/PlotSquared] - plot area manager: com.plotsquared.core.generator.HybridPlotManager
29.09 18:56:35 [Server] INFO [P2] Bereichs-Flags: []
29.09 18:56:35 [Server] INFO [P2] Straßen-Flags: []
29.09 18:56:35 [Server] INFO [PlotSquared/HybridPlotWorld] - Dumping settings for ClassicPlotWorld with name cb1
29.09 18:56:35 [Server] INFO [PlotSquared/HybridPlotWorld] -- road_schematic_enabled = true
29.09 18:56:35 [Server] INFO [PlotSquared/HybridPlotWorld] -- plot_schematic = false
29.09 18:56:35 [Server] INFO [PlotSquared/HybridPlotWorld] -- plot_schematic_height = -1
29.09 18:56:36 [Multicraft] Skipped 20 lines due to rate limit (30/s)
29.09 18:56:36 [Server] INFO UUID of player LordVardus is 0410e33c-35f5-422f-af9c-6c62c5222bc9
29.09 18:56:36 [Server] INFO Time elapsed: 460 ms
29.09 18:56:36 [Server] Startup Done (6.207s)! For help, type "help"
29.09 18:56:36 [Server] INFO Timings Reset
29.09 18:56:37 [Server] INFO LordVardus joined the game
29.09 18:56:37 [Connect] User LordVardus, IP 178.24.235.217
29.09 18:56:37 [Multicraft] LordVardus ran command Nachricht des Tages
29.09 18:56:43 [Server] FATAL Failed to light chunk [-26, 9]
29.09 18:56:43 [Server] INFO java.util.concurrent.CompletionException: net.minecraft.ReportedException: Exception generating new chunk
29.09 18:56:43 [Server] INFO at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
29.09 18:56:43 [Server] INFO at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
29.09 18:56:43 [Server] INFO at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) ~[?:?]
29.09 18:56:43 [Server] INFO at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
29.09 18:56:43 [Server] INFO at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.lambda$message$1(ChunkTaskPriorityQueueSorter.java:58) ~[app:?]
29.09 18:56:43 [Server] INFO at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:87) ~[app:?]
29.09 18:56:43 [Server] INFO at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:141) ~[app:?]
29.09 18:56:43 [Server] INFO at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:96) ~[app:?]
29.09 18:56:43 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
29.09 18:56:43 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
29.09 18:56:43 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
29.09 18:56:43 [Server] INFO Caused by: net.minecraft.ReportedException: Exception generating new chunk
29.09 18:56:43 [Server] INFO at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$38(ChunkMap.java:1340) ~[patched_1.17.1.jar:git-Paper-408]
29.09 18:56:43 [Server] INFO at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[patched_1.17.1.jar:git-Paper-408]
29.09 18:56:43 [Server] INFO at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$40(ChunkMap.java:1324) ~[patched_1.17.1.jar:git-Paper-408]
29.09 18:56:43 [Server] INFO at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
29.09 18:56:43 [Server] INFO ... 8 more
29.09 18:56:43 [Server] INFO Caused by: java.lang.IllegalStateException: The blockState must be placed to call this method
29.09 18:56:43 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockState.requirePlaced(CraftBlockState.java:324) ~[patched_1.17.1.jar:git-Paper-408]
29.09 18:56:43 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockState.getBlock(CraftBlockState.java:187) ~[patched_1.17.1.jar:git-Paper-408]
29.09 18:56:43 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockState.getBlock(CraftBlockState.java:24) ~[patched_1.17.1.jar:git-Paper-408]
29.09 18:56:43 [Server] INFO at com.plotsquared.bukkit.queue.LimitedRegionWrapperQueue.setBlock(LimitedRegionWrapperQueue.java:68) ~[PlotSquared-Bukkit-6.10.0-Premium.jar:?]
29.09 18:56:43 [Server] INFO at com.plotsquared.core.queue.DelegateQueueCoordinator.setBlock(DelegateQueueCoordinator.java:87) ~[PlotSquared-Bukkit-6.10.0-Premium.jar:?]
29.09 18:56:43 [Server] INFO at com.plotsquared.core.queue.ScopedQueueCoordinator.setBlock(ScopedQueueCoordinator.java:89) ~[PlotSquared-Bukkit-6.10.0-Premium.jar:?]
29.09 18:56:43 [Server] INFO at com.plotsquared.core.generator.HybridGen.placeSchem(HybridGen.java:81) ~[PlotSquared-Bukkit-6.10.0-Premium.jar:?]
29.09 18:56:43 [Server] INFO at com.plotsquared.core.generator.HybridGen.populateChunk(HybridGen.java:316) ~[PlotSquared-Bukkit-6.10.0-Premium.jar:?]
29.09 18:56:43 [Server] INFO at com.plotsquared.bukkit.generator.BlockStatePopulator.populate(BlockStatePopulator.java:84) ~[PlotSquared-Bukkit-6.10.0-Premium.jar:?]
29.09 18:56:43 [Server] INFO at net.minecraft.world.level.chunk.ChunkGenerator.addDecorations(ChunkGenerator.java:274) ~[patched_1.17.1.jar:git-Paper-408]
29.09 18:56:44 [Multicraft] Skipped 127 lines due to rate limit (30/s)
29.09 18:56:44 [Server] INFO Saving players
29.09 18:56:44 [Disconnect] User LordVardus has disconnected, reason: Server closed
29.09 18:56:44 [Server] ERROR Remove callback for map threw exception
29.09 18:56:44 [Server] INFO java.util.concurrent.CompletionException: net.minecraft.ReportedException: Exception generating new chunk
29.09 18:56:44 [Server] INFO at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
29.09 18:56:44 [Server] INFO at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
29.09 18:56:44 [Server] INFO at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) ~[?:?]
29.09 18:56:44 [Server] INFO at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
29.09 18:56:44 [Server] INFO at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.lambda$message$1(ChunkTaskPriorityQueueSorter.java:58) ~[app:?]
29.09 18:56:44 [Server] INFO at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:87) ~[app:?]
29.09 18:56:44 [Server] INFO at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:141) ~[app:?]
29.09 18:56:44 [Server] INFO at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:96) ~[app:?]
29.09 18:56:44 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
29.09 18:56:44 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
29.09 18:56:44 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
29.09 18:56:44 [Server] INFO Caused by: net.minecraft.ReportedException: Exception generating new chunk
29.09 18:56:44 [Server] INFO at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$38(ChunkTracker.java:1340) ~[app:?]
29.09 18:56:44 [Server] INFO at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[patched_1.17.1.jar:git-Paper-408]
29.09 18:56:44 [Server] INFO at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$40(ChunkTracker.java:1324) ~[app:?]
29.09 18:56:44 [Server] INFO at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
29.09 18:56:44 [Server] INFO ... 8 more
29.09 18:56:44 [Server] INFO Caused by: java.lang.IllegalStateException: The blockState must be placed to call this method
29.09 18:56:44 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockState.requirePlaced(CraftBlockState.java:324) ~[patched_1.17.1.jar:git-Paper-408]
29.09 18:56:44 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockState.getBlock(CraftBlockState.java:187) ~[patched_1.17.1.jar:git-Paper-408]
29.09 18:56:44 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockState.getBlock(CraftBlockState.java:24) ~[patched_1.17.1.jar:git-Paper-408]
29.09 18:56:44 [Server] INFO at com.plotsquared.bukkit.queue.LimitedRegionWrapperQueue.setBlock(LimitedRegionWrapperQueue.java:68) ~[PlotSquared-Bukkit-6.10.0-Premium.jar:?]
29.09 18:56:44 [Server] INFO at com.plotsquared.core.queue.DelegateQueueCoordinator.setBlock(DelegateQueueCoordinator.java:87) ~[PlotSquared-Bukkit-6.10.0-Premium.jar:?]
29.09 18:56:44 [Server] INFO at com.plotsquared.core.queue.ScopedQueueCoordinator.setBlock(ScopedQueueCoordinator.java:89) ~[PlotSquared-Bukkit-6.10.0-Premium.jar:?]
29.09 18:56:44 [Server] INFO at com.plotsquared.core.generator.HybridGen.placeSchem(HybridGen.java:81) ~[PlotSquared-Bukkit-6.10.0-Premium.jar:?]
29.09 18:56:44 [Server] INFO at com.plotsquared.core.generator.HybridGen.populateChunk(HybridGen.java:316) ~[PlotSquared-Bukkit-6.10.0-Premium.jar:?]
29.09 18:56:45 [Multicraft] Skipped 14 lines due to rate limit (30/s)
29.09 18:56:45 [Server] INFO Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
29.09 18:56:45 [Server] INFO Saving chunks for level 'ServerLevel[cb1]'/minecraft:cb1
29.09 18:56:46 [Server] FATAL Failed to light chunk [-25, 10]
29.09 18:56:46 [Server] INFO java.util.concurrent.CompletionException: net.minecraft.ReportedException: Exception generating new chunk
29.09 18:56:46 [Server] INFO at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
29.09 18:56:46 [Server] INFO at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
29.09 18:56:46 [Server] INFO at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) ~[?:?]
29.09 18:56:46 [Server] INFO at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
29.09 18:56:46 [Server] INFO at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.lambda$message$1(ChunkTaskPriorityQueueSorter.java:58) ~[app:?]
29.09 18:56:46 [Server] INFO at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:87) ~[app:?]
29.09 18:56:46 [Server] INFO at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:141) ~[app:?]
29.09 18:56:46 [Server] INFO at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:96) ~[app:?]
29.09 18:56:46 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
29.09 18:56:46 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
29.09 18:56:46 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
29.09 18:56:46 [Server] INFO Caused by: net.minecraft.ReportedException: Exception generating new chunk
29.09 18:56:46 [Server] INFO at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$38(ChunkTracker.java:1340) ~[app:?]
29.09 18:56:46 [Server] INFO at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[patched_1.17.1.jar:git-Paper-408]
29.09 18:56:46 [Server] INFO at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$40(ChunkTracker.java:1324) ~[app:?]
29.09 18:56:46 [Server] INFO at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
29.09 18:56:46 [Server] INFO ... 8 more
29.09 18:56:46 [Server] INFO Caused by: java.lang.IllegalStateException: The blockState must be placed to call this method
29.09 18:56:46 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockState.requirePlaced(CraftBlockState.java:324) ~[patched_1.17.1.jar:git-Paper-408]
29.09 18:56:46 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockState.getBlock(CraftBlockState.java:187) ~[patched_1.17.1.jar:git-Paper-408]
29.09 18:56:46 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockState.getBlock(CraftBlockState.java:24) ~[patched_1.17.1.jar:git-Paper-408]
29.09 18:56:46 [Server] INFO at com.plotsquared.bukkit.queue.LimitedRegionWrapperQueue.setBlock(LimitedRegionWrapperQueue.java:68) ~[PlotSquared-Bukkit-6.10.0-Premium.jar:?]
29.09 18:56:46 [Server] INFO at com.plotsquared.core.queue.DelegateQueueCoordinator.setBlock(DelegateQueueCoordinator.java:87) ~[PlotSquared-Bukkit-6.10.0-Premium.jar:?]
29.09 18:56:46 [Server] INFO at com.plotsquared.core.queue.ScopedQueueCoordinator.setBlock(ScopedQueueCoordinator.java:89) ~[PlotSquared-Bukkit-6.10.0-Premium.jar:?]
29.09 18:56:46 [Server] INFO at com.plotsquared.core.generator.HybridGen.placeSchem(HybridGen.java:81) ~[PlotSquared-Bukkit-6.10.0-Premium.jar:?]
29.09 18:56:46 [Server] INFO at com.plotsquared.core.generator.HybridGen.populateChunk(HybridGen.java:316) ~[PlotSquared-Bukkit-6.10.0-Premium.jar:?]
29.09 18:56:48 [Multicraft] Skipped 33 lines due to rate limit (30/s)
29.09 18:56:48 [Server] INFO at com.plotsquared.bukkit.queue.LimitedRegionWrapperQueue.setBlock(LimitedRegionWrapperQueue.java:68) ~[PlotSquared-Bukkit-6.10.0-Premium.jar:?]
29.09 18:56:48 [Server] INFO at com.plotsquared.core.queue.DelegateQueueCoordinator.setBlock(DelegateQueueCoordinator.java:87) ~[PlotSquared-Bukkit-6.10.0-Premium.jar:?]
29.09 18:56:48 [Server] INFO at com.plotsquared.core.queue.ScopedQueueCoordinator.setBlock(ScopedQueueCoordinator.java:89) ~[PlotSquared-Bukkit-6.10.0-Premium.jar:?]
29.09 18:56:48 [Server] INFO at com.plotsquared.core.generator.HybridGen.placeSchem(HybridGen.java:81) ~[PlotSquared-Bukkit-6.10.0-Premium.jar:?]
29.09 18:56:48 [Server] INFO at com.plotsquared.core.generator.HybridGen.populateChunk(HybridGen.java:316) ~[PlotSquared-Bukkit-6.10.0-Premium.jar:?]
29.09 18:56:48 [Server] INFO at com.plotsquared.bukkit.generator.BlockStatePopulator.populate(BlockStatePopulator.java:84) ~[PlotSquared-Bukkit-6.10.0-Premium.jar:?]
29.09 18:56:48 [Server] INFO at net.minecraft.world.level.chunk.ChunkGenerator.addDecorations(ChunkGenerator.java:274) ~[patched_1.17.1.jar:git-Paper-408]
29.09 18:56:48 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.generator.CustomChunkGenerator.applyBiomeDecoration(CustomChunkGenerator.java:272) ~[patched_1.17.1.jar:git-Paper-408]
29.09 18:56:48 [Server] INFO at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$10(ChunkStatus.java:93) ~[patched_1.17.1.jar:git-Paper-408]
29.09 18:56:48 [Server] INFO at net.minecraft.world.level.chunk.ChunkStatus.generate(ChunkStatus.java:212) ~[patched_1.17.1.jar:git-Paper-408]
29.09 18:56:48 [Server] INFO at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$38(ChunkTracker.java:1326) ~[app:?]
29.09 18:56:48 [Server] INFO at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[patched_1.17.1.jar:git-Paper-408]
29.09 18:56:48 [Server] INFO at net.minecraft.server.level.ChunkTracker.lambda$scheduleChunkGeneration$40(ChunkTracker.java:1324) ~[app:?]
29.09 18:56:48 [Server] INFO at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
29.09 18:56:48 [Server] INFO ... 8 more

### To Reproduce

get these errors when i keep walking on the street and step out of the chunk area

### Expected behaviour

the problem occurs when i connect to my server

### Screenshots / Videos

no

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/e282289e02f0468cb496eb3c1b652460

### PlotSquared Version

PlotSquared v6 6.10.0

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by SirYwell** [comment]
You already opened an issue for this problem: #3801
