### ISSUE TITLE
No resource for locale 'de' found

### ISSUE THREAD

**Issue by LordVardus** [IntellectualSites/PlotSquared#3820]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

I have now changed the language in the config file from en to de but now I get this
WARN [PlotSquared/ClassLoaderCaptionProvider] No resource for locale 'de' found
warning message why does this come when I have specified it correctly?

### To Reproduce

 I downloaded the file and put it in the lang folder
https://s20.directupload.net/images/221002/49pg883v.png

### Expected behaviour

yes, what can I say, I expected that there would be no more errors. The language is in German, but this error message comes up
It would be nice if there were a PlotSquared version where there were no more errors

### Error log (if applicable)

https://athion.net/ISPaster/paste/view/87dd95ce75df45ffbbc3a8f0f77a1744

### Plot Debugpaste

https://s20.directupload.net/images/221002/b8bqpzlx.png

### PlotSquared Version

PlotSquared v6 6.10.0

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by SirYwell** [comment]
This warning is probably a bit misleading. What it means is that there is no language file for `de` embedded in the PlotSquared jar. The only case this is relevant is after updating PlotSquared, as newly added messages cannot pulled from the file in the given language. It will instead put the english default entries in your message file.

Maybe we can improve the wording of the warning or make it an info instead, but it should not affect functionality.
