### ISSUE TITLE
Plots can't be deleted in dimensions other than the Overworld

### ISSUE THREAD

**Issue by mov51** [IntellectualSites/PlotSquared#3828]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

Plots can't be deleted in dimensions other than the Overworld. They don't get cleared or deleted and an error is thrown in console. 

### To Reproduce

1. Create a standard Nether World.
2. Go through the steps to turn it into a plot world using the name of one of the vanilla dimension worlds like the Nether or end.
3. Restart the server and delete the region files the world contains.
4. Claim a plot.
5. place blocks inside the plot.
6. run /plot delete.
7. the blocks will not be removed.

### Expected behaviour

The plot and it's contents are deleted.

### Screenshots / Videos

https://streamable.com/kb075r

### Error log (if applicable)

https://pastebin.com/Z392nrnp

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/7bf486c3898e4f32a446f81963550b0e

### PlotSquared Version

PlotSquared-6.10.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Other dimensions are not yet implemented, see https://github.com/IntellectualSites/PlotSquared/issues/2969

**Comment by mov51** [comment]
It's really just not supported? Worlds were able to be created normally by going through the plot world creation command. Is there any method I could use to delete plots at all?
