### ISSUE TITLE
Add "hasOwner" method to PlotQuery

### ISSUE THREAD

**Issue by TheosisOfficial** [IntellectualSites/PlotSquared#3831]
### What feature do you want to see added?

Title says it all really. Would be nice to be able to filter plots that either are or aren't owned.

### Are there any alternatives?

Currently using `Plot#hasOwner` on every plot returned from my current query to check if it has an owner. I'm not sure if having this method in the query itself would affect performance at all, but it would certainly be neater.

**Comment by PierreSchwang** [comment]
> I'm not sure if having this method in the query itself would affect performance at all, but it would certainly be neater.

Generally not. The different queries check the existence on owners on the plot objects itself as well. If you want a neater way to do that, you could use PlotQuery#thatPasses, e.g.
```java
PlotQuery.newQuery().thatPasses(Plot::hasOwner)
```
