### ISSUE TITLE
Nether-Portal BUG

### ISSUE THREAD

**Issue by AnimeDrache** [IntellectualSites/PlotSquared#3833]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

My friend used the nether portal on his plot. Then I noticed the error (see attachment) in my console. I can't say for sure if it was when he enters the nether portal on his plot OR if the error came after he used the ALREADY EXISTING portal inside the nether to get back to the normal world again (when he used his portal on his plot he did spawn inside the already exisiting portal inside the nether). But I can say for sure that the error must have a connection to the nether portal on his plot.

### To Reproduce

1. MAKE SURE you have already a manual / regular created portal from the normal world to the nether
2. Now create a nether portal on your plot & go trough it
3. use (an already existing!) portal inside the nether to get back to the normal world
4. The error should appear in the console

### Expected behaviour

No error should appear.

### Screenshots / Videos

![Screenshot_27](https://user-images.githubusercontent.com/51856826/194615087-e17e6a90-5488-45ff-823c-186a497c3a8a.png)
![Screenshot_28](https://user-images.githubusercontent.com/51856826/194615110-b438a2a6-7726-44b1-9de9-f03234893bfb.png)

### Error log (if applicable)

https://paste.gg/p/anonymous/71dca8345f304669b04c63249bd3e6b9

### Plot Debugpaste

It said "Failed to create the debugpaste: request must contain a file list" so "Pierre" from Discord told me to paste the debug this time

### PlotSquared Version

6.10.0-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by PierreSchwang** [comment]
For reference: Caused by the Set.of call in https://github.com/IntellectualSites/PlotSquared/blob/v6/Bukkit/src/main/java/com/plotsquared/bukkit/listener/PlayerEventListener.java#L1759 with potentially identically X and Z coordinates. Set.of does not allow duplicates (https://docs.oracle.com/javase/9/docs/api/java/util/Set.html#of-E...-)
