### ISSUE TITLE
You can drive a boat on other plots and destroy Lily Pads

### ISSUE THREAD

**Issue by FMS25** [IntellectualSites/PlotSquared#3836]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

Pretty much the title. You can use a boat in creative, drive over the slabs into your plot and/or get the height to land on someone else's plot. You can then go and grief other players' plots.  (my tester found this bug by the way)

### To Reproduce

1. Spawn a boat in your plot
2. build a way to get over the slabs
3. move the boat onto the pathways
4. find a way to get onto someones else's plot
5. destroy lily pads

### Expected behaviour

the boats not get on other players' plots and destroy lilypads

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/e010046177f7483da1d17056e6134c59

### PlotSquared Version

PlotSquared version 6.10.0-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Check the documentation how to configure such behavior: https://intellectualsites.github.io/plotsquared-documentation/
