### ISSUE TITLE
Freshly created plot schematic pastes one block lower

### ISSUE THREAD

**Issue by iCrashMix0** [IntellectualSites/PlotSquared#3846]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

https://youtu.be/7xWiep9T91k

### To Reproduce

https://youtu.be/7xWiep9T91k

### Expected behaviour

The object is spawned too deep or you should watch the video to better understand this.

### Screenshots / Videos

https://youtu.be/7xWiep9T91k

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/4973daa2c8464921987998c9de8e1374

### PlotSquared Version

6.10.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by PierreSchwang** [comment]
When following the official guide for plot schematics - and using `/p save` instead of `//schem save`, that issue does not occur: https://intellectualsites.github.io/plotsquared-documentation/schematics/schematic-generation.html
