### ISSUE TITLE
Sculk Sensor not working on Server-Plot flags

### ISSUE THREAD

**Issue by AnimeDrache** [IntellectualSites/PlotSquared#3848]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

I've created a cool redstone lamp that turns on when you walk closer. However this needs the usage of sculk sensors. I moved them from my private plot on the server-plot and noticed that the sensor isnt working anymore (the range goes from around 8 blocks down to 1. that means, the sculk sensor only triggers when you step directly onto it and not just close by).

I've created a fresh server for such tests and had to notice that its that flag which causes the issue.

### To Reproduce

1. Claim 2 plots
2. add **/p flag set server-plot** to one of it
3. place a sculk sensor on each plot
4. walk / run close to the sculk sensors and notice the different (on a regular plot it triggers normal. on a server plot just when you step directly onto it)

### Expected behaviour

Sculk sensor should have the same behavior on any plots (a far / normal range)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/41a912d137b749b1adba15aa5e5900c2

### PlotSquared Version

PlotSquared-Bukkit-6.10.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
On the plot with the server-plot flag set, enable `misc-interact`.
