### ISSUE TITLE
Roads render broken (even on a brand new server)

### ISSUE THREAD

**Issue by AnimeDrache** [IntellectualSites/PlotSquared#3849]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

I've noticed a very strange bug which did cost me a lot of nerves. Even the support on Discord didn't really know what's going on. It might be hard to recognize but let me explain:

After you've created a new plot world, placed a street and saved the road (**/plot createroadschematic**) you might recognize that if you fly far away, the street is already rendering even without the **/plot debugroadregen** command. So far so good, that is still not the issue. Now:

KEEP flying around. If you fly like 10 - 20 plots far away, you can see that the roads get broken! They are destroyed. The **/plot regenallroads NAME** command won't fix that issue. The roads are just terribly broken. The only way I found to fix it was by deleting the entire content inside the **regions**-folder of the plot-world. It will then create the roads new again and fixed.

I can't tell you why this happens but I can tell you it's definitely a BUG! Because I do create fresh new paper servers when I notice such huge issues because they trigger me a LOT! So please try it with my entire setting in the **"To Reproduce** section.

### To Reproduce

1. Create a new fresh plot world with my setup: 1. normal, 2. -1 (height - don't worry about the -1, I've tried it with 1 and even 62 - still same issue), 3. 39 (plot size), 4. stone, 5. true (top layer), 6. grass_block, 7. purpur_slab (unclaimed), 8. quartz_slab (claimed), 9. 13 (street), 10. -1, 11. quartz_block (street), 12. bedrock (street wall), 13. -1, 14. true (bedrock), 15. NAME OF THE WORLD
2. Paste (worldedit) a nice road on the west side of the plot
3. do **/plot createroadschematic**
4. either use or not use the **/plot debugroadregen plot** command on another plot
5. keep flying into one direction till you see all the already created roads
6. still keep flying into the same direction and keep your eyes open. you will see (as on my attachment files) that the road is totally broken

### Expected behaviour

Roads to render fine and not broken.

### Screenshots / Videos

![road1](https://user-images.githubusercontent.com/51856826/195739071-78e19f5c-0923-40cb-bd1c-57754167eceb.png)
![road2](https://user-images.githubusercontent.com/51856826/195739082-a9e480cd-f853-424a-908f-6c8e1ebad343.png)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/41a912d137b749b1adba15aa5e5900c2

### PlotSquared Version

PlotSquared-Bukkit-6.10.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NiclasJohn** [comment]
Same is happening for me i want to use my road schematics but its not working like you showewd in the screenshots... i dont want to use single block road but i need to use it when this is not fixed soon

**Comment by NotMyFault** [comment]
Can you attach the road schematics please? They are located in `/PlotSquared/schematics/GEN_ROAD_SCHEMATIC/<world>/intersection.schem` and sideroad.schem

**Comment by dordsor21** [comment]
How "fast" does the generation seem to be for you? Pretty subjective question but I wonder if somehow P2 is just not keeping up..? I also wonder if the generation changes made targeting v7 (using the new API) could stop this issue

**Comment by OneLiteFeather** [comment]
Does anyone else still have this bug?

**Comment by OneLiteFeather** [comment]
![grafik](https://user-images.githubusercontent.com/77929075/233848878-026ced59-a33c-40bb-bcb9-ad3bd86ae4e5.png)
Ignore the white road blocks - my bad while building, I didn't replace all of them. I flew far away from where the road schematics origin is.
The plot setup sizes/blocks varied a little bit, but this should not matter.
![grafik](https://user-images.githubusercontent.com/77929075/233848987-616c6d90-1b29-4ac9-9402-bad48df5cd23.png)
The trees might look "cut" but it was built like that. In addition, I have one more different server where it didn't break too.

Tested with Plotsquared v6.11.1, FAWE-401, Paper 1.19.4 (516) and I didn't claim the plot where the road schematic was saved (the edge is part of road)

I think we're done with this issue.
