### ISSUE TITLE
Admin can not place minecard

### ISSUE THREAD

**Issue by TruaYT** [IntellectualSites/PlotSquared#3850]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

WWhen I try to use a minecrad with * permission I have to truss myself and then I can place it first, would be good if they would fix that.

### To Reproduce

Go to the plot
Pick up minecard
Try to set minecard...
See

### Expected behaviour

When i can with * permssion or any permission like:
"plot.admin.plot.set.vihacl"

### Screenshots / Videos

d

### Error log (if applicable)

d

### Plot Debugpaste

not important

### PlotSquared Version

PlotSquared 6.10.1-premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

d

**Comment by DevJoey** [comment]
Can confirm
