### ISSUE TITLE
Plotsquared Schematic Bug

### ISSUE THREAD

**Issue by iCrashMix0** [IntellectualSites/PlotSquared#3859]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

The object (Schematic) and the plot edge does not work please see the video on Youtube. Video: https://youtu.be/WorLKfcV5FE

### To Reproduce

Please watch the video: https://youtu.be/WorLKfcV5FE

### Expected behaviour

-

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/29773c702f0945868289a5f33c205656

### PlotSquared Version

PlotSquared version 6.9.3-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Please provide a step-by-step guide how this issue can be replicated. I watched the video, but didn't understand, what you are trying to show us with it.

**Comment by iCrashMix0** [comment]
Ok here is the step by step guide:

1. set up a fresh 1.19.2 Paper Minecraft server and then start the server logically.
2. Perform setup of PlotSquared. Commands I have entered:
**- /plot setup
- /plot setup PlotSquared
- /plot setup normal
- /plot setup 62
- /plot setup 200
- /plot setup stone
- /plot setup true
- /plot setup stone
- /plot setup red_wool
- /plot setup green_wool
- /plot setup 140
- /plot setup 62
- /plot setup stone
- /plot setup 61
- /plot setup true
- /plot setup (World Name)
- The world is created.**
3. Then remember exactly what the plot edge looks like or take a screenshot so you can see differences afterwards.
4. Then insert the object(Schematic) on the plot or build something on the plot and then enter "/plot backup save". (Of course you still have to set the plot owner to you).
5. then stop the server.
6. Then take the schematic file you created with "/plot backup save" and rename it to "plot.schem".
7. Move the file "plot.schem" to "\plugins\PlotSquared\schematics\GEN_ROAD_SCHEMATIC\(World Name)".
8. Delete the world of (World Name) that you created with "/plot setup...".
9. Then start server and see the plot edge and with it you can see a difference.
10. Go to any plot and type "/plot claim" and then "/plot delete" and you will see that the border is suddenly there AND the Schematic object has somehow been sunk a block.

**Comment by dordsor21** [comment]
I think this will have been fixed in recent (in the last year) fixes to the heights used in generation and schematic placing
