### ISSUE TITLE
Unable to create an augmented plot world

### ISSUE THREAD

**Issue by Shizufuzu** [IntellectualSites/PlotSquared#3860]
### Server Implementation

Spigot

### Server Version

1.17.1

### Describe the bug

Getting a NULL_INJECTED_INTO_NON_NULLABLE error on /p2 setup augmented (and all other)

### To Reproduce

I created a localhost Server on 1.17.1 with BuildTools
FAWE 2.4.9 SNAPSHOT 296
PlotSquared 6.10.2

All Plugins I use: LuckPerms, FAWE, NoDrop, PlotSquared, Multiverse-Core, WorldGuard, Drop2Inventory

### Expected behaviour

setup a PlotWorld

### Plot Debugpaste

https://paste.gg/p/anonymous/2321831091ac46a98ce6d124e45e63de

### PlotSquared Version

PlotSquared 6.10.2-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
I'm currently not able to set up a 1.17.1 Spigot server, but I'm unable to replicate this issue on Paper 1.19.2 build 246, running on Java 19.0.1+10
