### ISSUE TITLE
Plotsquared sag Du bist nicht auf einem Plot

### ISSUE THREAD

**Issue by Multi1237372** [IntellectualSites/PlotSquared#3863]
### Server Implementation

Spigot

### Server Version

1.18.2

### Describe the bug

Ich habe eine Plotwelt erstellt und der Server sagt wenn ich /p claim mache you  are not at a plot. Was kann ich tuhen 

### To Reproduce

Kann ich nicjt sagen  

### Expected behaviour

Kann ich nicjt sagen  

### Screenshots / Videos

Gibt keinen

### Plot Debugpaste

/Plot debugpaste

### PlotSquared Version

6.10.1 Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

Nein

**Comment by iCrashMix0** [comment]
english

**Comment by dordsor21** [comment]
Not enough information, no further information provided after asked
