### ISSUE TITLE
Players cannot claim plots on PlotSquared-Bukkit-6.10.4-Premium, if no merge permissions are set

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/PlotSquared#3875]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

I noticed that new players couldn't claim a plot when I updated to PlotSquared-Bukkit-6.10.4-Premium, it just gives the error "You are lacking the permission node plots.merge.1" For some reason the plugin thinks claiming a new plot means you're trying to perform a plot merge?

![2022-11-18_12 38 14](https://user-images.githubusercontent.com/10485646/202706770-e4260f37-1574-487f-b8d8-ca7e7c708640.png)

I think this commit is causing the issue but I could be wrong: https://github.com/IntellectualSites/PlotSquared/commit/25ce7a83f134921c1fc2c69f5d92ecb23edf1761

### To Reproduce

1. Give players the permission for plots.auto
2. Try to claim a plot with /plot auto

### Expected behaviour

A new plot should be claimed by the user

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/907a608b7f1549378468c275c8f51bb8

### PlotSquared Version

PlotSquared version 6.10.4-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by TruaYT** [comment]
PLEASE FIX!!!!!!!!
