### ISSUE TITLE
Greetings can't use legacy colors.

### ISSUE THREAD

**Issue by untuned** [IntellectualSites/PlotSquared#3877]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

When setting a greeting, color codes aren't applied.

### To Reproduce

1. Go to your plot
2. Set a greeting with `/plot flag set greeting &6Hello world!`
3. Observe no colors are present in the greeting, only plaintext color codes.

### Expected behaviour

Colors should be applied to the greeting and shown to players (with an optional permission attached?).

### Screenshots / Videos

![example](https://untnd.me/Tns26Xb5y)

### Error log (if applicable)

N/A

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/776a4eec2d3e468087b5b2c0b2481c9b

### PlotSquared Version

PlotSquared version 6.10.4-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Legacy color codes are no longer supported. Use MiniMessage: https://docs.adventure.kyori.net/minimessage/format.html
