### ISSUE TITLE
Blocks start to burn but will not destroyed

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#3879]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

On plots (if i place lava near vines) the vides will start to ignite!

If i deny the block-ignite flag for all plots playes cannot light up thier nether rack

### To Reproduce

Place lava near burable blocks

### Expected behaviour

Blocks like nether-rack should still be able to ignite with flint-and-steel but should not ignite surrounding blocks by itself

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/38475631/204014601-5329a513-bc54-4570-8cd6-f0391c52ce52.png)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/9bebf05dc3da4cf08cc7f22d89034b57

### PlotSquared Version

6.10.4-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
> Blocks like nether-rack should still be able to ignite with flint-and-steel but should not ignite surrounding blocks by itself

This is a very complex and niche case, I am afraid we can't maintain.
