### ISSUE TITLE
'/plot auto' command no permission

### ISSUE THREAD

**Issue by fadfhkdfga** [IntellectualSites/PlotSquared#3881]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

After updating the plugin version, if you use the '/plot auto' command, a message indicating that you do not have permission is displayed. ('plots.auto' and 'plots.plot.1' have been added in LuckPerm and remain unchanged)

### To Reproduce

.

### Expected behaviour

..

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/9753841c03db4ef2ae4e0eac2237cb14

### PlotSquared Version

PlotSquared-6.10.4-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Fixed in https://github.com/IntellectualSites/PlotSquared/pull/3876
