### ISSUE TITLE
pay for corupt world

### ISSUE THREAD

**Issue by jokbon** [IntellectualSites/PlotSquared#3884]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

beats yatopia in world coruption feature

### To Reproduce

vid/gif

### Expected behaviour

lol

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/29400409/204843578-78fcd1ff-3b73-43ee-9939-29fcfdc7cff8.png)
https://imgur.com/a/5KVC806

### Plot Debugpaste

meh

### PlotSquared Version

latest build

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

spam console (sign corruption)
prety big plots
sorry iam quite angry

**Comment by jokbon** [comment]
world edit STABLE 1.19.2

**Comment by jokbon** [comment]
meh need more? https://i.imgur.com/nwGcZpp.jpg

**Comment by SirYwell** [comment]
The instructions to report an issue exist for a reason.
