### ISSUE TITLE
10mil block edits not completing properly

### ISSUE THREAD

**Issue by FETXU** [IntellectualSites/PlotSquared#3885]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

When doing edits of 10mil or more in plots (or server with PS loaded in) it will not correctly complete the edit. This includes edits like `/set stone`, `/undo` and `/paste`. It works fine if we use `/wea` add `fawe.bypass` perm to player, but this breaks the usage in the plots (regions not respected).

The error as follows shows:
> Your worldEdit action was cancelled. Too many blocks changed.

We have found through tests that the above message starts showing around 16.7mil blocks or above this message will start showing and the edits will start corrupting. _Eg. The `/set stone` command will fill only part of the selection area up (between 7.5mil and 10mil blocks), and will corrupt when attempting undo_ 

The config has `max-changes: 50000000`
![imagea](https://user-images.githubusercontent.com/56762410/205068263-7527846b-fd30-4799-87cd-4158585431a6.png)
![imageb](https://user-images.githubusercontent.com/56762410/205068267-c8f8e8a8-a1a1-495b-9cfa-84333c5a63f0.png)

### To Reproduce

1. Load a server with FAWE and PS (with 256x plots) in it and use default settings.
2. Make a selection with 16.8mil blocks or more.
3. Use /set command to change selection to stone `/set stone`
4. See that the error `Your worldEdit action was cancelled. Too many blocks changed.` shows.
5. Watch as only approx 7.5-10mil blocks are loaded in.
6. Try undo and watch as it further currupts.
7. Set /wea or fawe.bypass perm and try above again.
8. See that it now works with no errors, but now Plots and regions are unsecured.

### Expected behaviour

We should be able to edit blocks up to the amount set in FAWE config settings.

### Screenshots / Videos

Added above in description :)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/f85de0ad07ec440ab1691e37d38fdbc2

### PlotSquared Version

PlotSquared Version 6.10.4-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

We found a late kind of fix.

If you set max blocks limit (in config) to 50 billion blocks then 50 million blocks (or more) works. However if set to 50 million, then only less than 16.6 million works.

**Comment by FETXU** [comment]
CORRECTION - We did all testing on 6.10.5 after seeing update. Problem still the same.

**Comment by dordsor21** [comment]
Tracked by https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1874
