### ISSUE TITLE
IllegalArgumentException: Cannot set the biome to CUSTOM

### ISSUE THREAD

**Issue by x1p** [IntellectualSites/PlotSquared#3888]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

Error when executing `/plot setbiome custom`
I don't know where this custom comes from. I didn't specify this.

### To Reproduce

Player executed `plot setbiome custom`

### Expected behaviour

No error but simply ignore faulty arguments

### Error log (if applicable)

https://pastebin.com/raw/L6SsbXKc

### Plot Debugpaste

Irrelevant at this point

### PlotSquared Version

PlotSquared-Bukkit-6.10.5-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

The original error is 6185 lines. The error repeats itself over and over again before it stops. So that is about 309 times the same error.

**Comment by NotMyFault** [comment]
That's a default biome type in the game, brought to tab completion by WorldEdit.
