### ISSUE TITLE
Use the template to create a plot world, and you will be prompted that you have no permission: plots. admin

### ISSUE THREAD

**Issue by 3269199948** [IntellectualSites/PlotSquared#3899]
### Server Implementation

Spigot

### Server Version

1.19.2

### Describe the bug

Use the template to create a plot world, and you will be prompted that you have no permission: plots. admin

join game

input:  /plot template import testworld town

console report errors

### To Reproduce

join game

input:  /plot template import testworld town

console report errors

### Expected behaviour

Create the world successfully

### Error log (if applicable)

server no error log

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/ef6dd161ef904f5ab188d55e83a26831

### PlotSquared Version

 PlotSquared version 6.10.5-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
It would help, if you include the debugpaste _after_ executing the template command, to include the error. Rebooting the server is not helpful.

**Comment by 3269199948** [comment]
> executing the template command

new debug page: https://athion.net/ISPaster/paste/view/5d258b5b9df84ed4b71fc5257b2f3ad8
 

The only thing you get from executing the template command is the client error: [P2] You are locking the permission node: plots. admin

**Comment by NotMyFault** [comment]
That's not an error but an improper permission setup on your end. Take a look at the wiki of your permissionm plugin how to assign nodes.

**Comment by 3269199948** [comment]
> That's not an error but an improper permission setup on your end. Take a look at the wiki of your permissionm plugin how to assign nodes.

I'll try

I'm OP

I have to say that I use other plug-ins, such as CMI, No need to manually assign permissions

I don't think the OP should assign permissions manually!
