### ISSUE TITLE
Version fuckery.

### ISSUE THREAD

**Issue by SilverCory** [IntellectualSites/PlotSquared#390]
Pls. Halp.

Your versions are out of sync? Really screwing me over here...

The latest versions...
...via current Jar on spigotmc says 2.12.2, 
...via maven (http://ci.nixium.com/plugin/repository/everything/) it says 2.12.0

So I take it the one on SpigotMC is from the future.
It has no com.intellectualcrafters.plot.PlotSquared class. And I'd rather not rely on a system scope to use PlotSquared via maven.

**Comment by Sauilitired** [comment]
The PlotSquared class is renamed to PS, why...? Ask @boy0001 :tongue:

**Comment by acecheese** [comment]
Well I don't mind it changing... Every now and then... (defo not as bad a PlotMe), but it's the different versions.. The maven says that PlotSquared still exists. -.-

**Comment by boy0001** [comment]
Yeah, you can blame me for renaming PlotSquared to PS. 

We changed it to a singleton, so it became PlotSquared.getInstance(). Since that broke everything anyway I decided to change it to PS.get() which is easier on my fingers.

As for maven on the build server... I don't even know how it is spitting out those malformed jars, it somehow has a mix of old and new classes in those...

**Comment by acecheese** [comment]
Please fix! It hurts!

**Comment by boy0001** [comment]
Okay, but you can try ignoring the old classes for now if it's urgent :p

**Comment by boy0001** [comment]
You can thank citymonstret: 
http://ci.intellectualsites.com/job/PlotSquared/
```
        <dependency>
            <groupId>com.intellectualcrafters</groupId>
            <artifactId>PlotSquared</artifactId>
            <version>2.12.9</version>
        </dependency>
```

**Comment by acecheese** [comment]
Changed maven repos... I cri.

**Comment by Sauilitired** [comment]
@acecheese You are extremely welcome :heart:

**Comment by acecheese** [comment]
:heart: I'll leave you free of notifications... For now.. ;)

**Comment by boy0001** [comment]
@Sauilitired 
http://mvn.intellectualsites.com/ is only listing the smallest jar, which happens to be PlotSquared-Null, which when removed will then use PlotSquared-Sponge.

**Comment by acecheese** [comment]
Throwing this here just for reference. 2a3c6ab

**Comment by Sauilitired** [comment]
**Outdated Issue:** Was resolved in one way or another
