### ISSUE TITLE
PlotSquared API does not Work

### ISSUE THREAD

**Issue by TerrorV300** [IntellectualSites/PlotSquared#3900]
### Server Implementation

Spigot

### Server Version

1.19.2

### Describe the bug

The PlotSquared API does not work with Spigot 1.19.2 or atleast it does not for me. I added the repository and depency to my pom.xml file and it does not throw an error but i cannot use it in my Project.

### To Reproduce

1. Insert this code into your pom.xml file in a Project in InteliJ with the Minecraft version Spigot-1.19.2.

```
<repositories>
        <repository>
            <id>plotsquared-repo</id>
            <url>https://github.com/IntellectualSites/PlotSquared/wiki/incendo-mvn</url>
        </repository>
</repositories>

<dependencies>
        <dependency>
            <groupId>com.plotsquared</groupId>
            <artifactId>PlotSquared</artifactId>
            <version>6.9.0</version>
        </dependency>
</dependencies>
```

### Expected behaviour

I expected to use the PlotAPI in my Project to alter the behaviour of PlotSquared and extend it to my needs.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/bc22dd9c704d45e48f6e35964dc611f3

### PlotSquared Version

PlotSquared version 6.10.5-SNAPSHOT

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
This is not what the wiki outlines, I recommend you give it a read again: https://intellectualsites.github.io/plotsquared-documentation/api/api-documentation.html
