### ISSUE TITLE
Deleted Entities use the `entity-cap` for a short time

### ISSUE THREAD

**Issue by QuickWrite** [IntellectualSites/PlotSquared#3904]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

When entities are getting deleted they still take up the `entity-cap` for some time.

### To Reproduce

1. Spawn a lot of entities
2. Kill them all
3. Place entities

### Expected behaviour

When entities are getting deleted other entities should directly have the ability to be spawned.

### Screenshots / Videos

![machine that can take up the entire mob-cap](https://user-images.githubusercontent.com/54590845/210251423-b5b13f20-ef06-4b34-b5b2-12c5af304dd9.png)

https://user-images.githubusercontent.com/54590845/210250880-09430488-d00c-4ed5-8a86-17661debdf16.mp4

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/4f561c76ee1e4c7da6587be158e98a35

### PlotSquared Version

6.10.6-SNAPSHOT

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
> entities should directly have the ability to be spawned.

'direct' likely is the wrong term you're looking for. Minecraft uses ticks to perform tasks, you need to wait until the next scan takes place, to determine the amount of living entities within a plot.

This doesn't happen every tick, for obvious performance reasons.
