### ISSUE TITLE
Can't negate permission plots.plot.9

### ISSUE THREAD

**Issue by MrClean1337** [IntellectualSites/PlotSquared#3905]
### Server Implementation

Paper

### Server Version

1.19.2

### Hello,

so I ran into a problem with negating plot permissions and I think the problem is more likely from Plotsquared.
I use LuckPerms as permissions plugin and I got two groups, which one of them is parenting the other.

### Example:
Group TrialEpic -> Weight 251
Group Epic -> Weight 250
The parent group from TrialEpic is Epic ... so **TrialEpic has all the permissions from Epic**

**TrialEpic has `plots.plot.9` negated**
**Epic has `plots.plot.9` as normal permission**
**TrialEpic inherits all permissions from Epic**

Player has TrialEpic but Plotsquared tells me he has still the permission to claim 9 plots.
But he shouldn't have the permission, because the default is 4 plots!

Here are some screenshots

### TrialEpic
![3f6QNPN](https://user-images.githubusercontent.com/58367170/210281773-bbd1d65b-be0d-4c4a-8a59-53cdab153a1e.png)

### Epic
![6HF5If5](https://user-images.githubusercontent.com/58367170/210281852-d75cdc95-672f-479a-ac0a-5b61edda39e2.png)

I personally think the whole thing has something to do with this function, because it just gets the highest number from a Permissonnode but skips the negated permissions somehow:
https://github.com/IntellectualSites/PlotSquared/blob/v6/Core/src/main/java/com/plotsquared/core/permissions/PermissionHolder.java#L67

I also tested it with the latest paper version.

### To Reproduce

1. Create with any permission plugin two groups
2. Give group 1 `plots.plot.9` permission
3. Give group 2 `plots.plot.9` negated permission
4. Type `/p auto` with group 2

### Expected behaviour

Players with `plots.plot.9` negated permission shouldn't claim 9 plots

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/797ceaabc72e4fb29ccf05edb678adae

### PlotSquared Version

PlotSquared (Version: PlotSquared-6.10.6-SNAPSHOT)

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
I fail to understand the situation.

> TrialEpic has plots.plot.9 negated
> Epic has plots.plot.9 as normal permission

Why would you negate the permission, if the player inherits the same from a different group?

**Comment by MrClean1337** [comment]
> I fail to understand the situation.
> 
> > TrialEpic has plots.plot.9 negated
> > Epic has plots.plot.9 as normal permission
> 
> Why would you negate the permission, if the player inherits the same from a different group?

Epic is a paid group, which only Epic users should claim 9 plots.
TrialEpic is a free/test group, which inherits the permissions from Epic.

But TrialEpic shouldn't claim 9 plots, because it's a test group for the players.

**Comment by NotMyFault** [comment]
This sounds like a pretty specific use case for LuckPerms. I don't know how weights work, nor how negation works on non-string-based permission nodes.

**Comment by MrClean1337** [comment]
The thing is ... I've coded recently a own plugin, with a similar function like [yours...](https://github.com/IntellectualSites/PlotSquared/blob/v6/Core/src/main/java/com/plotsquared/core/permissions/PermissionHolder.java#L67)

My code:

```
for(PermissionAttachmentInfo permissionInfo : player.getEffectivePermissions()){
    String perm = permissionInfo.getPermission().toLowerCase();

    if (!tpTimeBypass && perm.startsWith(AllPermissions.teleport_cooldown)){
        double found = Double.parseDouble(perm.substring(AllPermissions.teleport_cooldown.length())) / 10D;
        if(tpTime > found) tpTime = found;
    }
}
```

It gets the highest value from the permissions and it works! .. why not with Plotsquared ... ?
Its the same inheritance.

**Comment by MrClean1337** [comment]
> This sounds like a pretty specific use case for LuckPerms. I don't know how weights work, nor how negation works on non-string-based permission nodes.

I reached out to the LuckPerms community and we came to the result that it has nothing to do with LuckPerms.
So i tested alot with this issue ... and I found the problemsource and its a PS problem....

### If a player is inheriting these permissions:
> plots.plot.4 **TRUE**
> plots.plot.9 **FALSE**
... FALSE means permissions are negated
Plotsquares tells me, he will have the permissions to claim **9 plots**
*Same result, if `plots.plot.9` is set to TRUE ..*

### If a player is inheriting these permissions:
> plots.plot.4 **TRUE**
Plotsquares tells me, he will have the permissions to claim **4 plots**

### Conclusion after tests:
**PS ignores negated checks somehow [here ](https://github.com/IntellectualSites/PlotSquared/blob/v6/Core/src/main/java/com/plotsquared/core/permissions/PermissionHolder.java#L67)**

....
Other tests:
> -> /p auto
Here are the verbose viewer infos https://luckperms.net/verbose/W5ZHkn4ER9
**It looks like Plotsquared isn't even scanning for** `plots.plot.9`

> -> Joining the server
https://luckperms.net/verbose/e2eiq3bM3h

**Comment by MrClean1337** [comment]
@NotMyFault I did some debug, tracked the problem down and fixed it in a fork, you can watch that out and fix it in the future

https://github.com/MrClean1337/PlotSquared/commit/a5de2f685f82414ed63817c614e796e56c090426
