### ISSUE TITLE
Cleanup deprecated methods to improve code maturity

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/PlotSquared#3908]
Below, I've assembled a non-exhaustive list of methods we can switch away from, others may be kept for Spigot and backwards compatibility.

- https://github.com/IntellectualSites/PlotSquared/blob/339ca8e30fda26f2f1fa2522d692872cd02ad701/Core/src/main/java/com/plotsquared/core/command/Area.java#L232-L235 is deprecated in favor of `EditSessionBuilder#newEditSessionBuilder()`
- https://github.com/IntellectualSites/PlotSquared/blob/339ca8e30fda26f2f1fa2522d692872cd02ad701/Core/src/main/java/com/plotsquared/core/generator/HybridPlotWorld.java#L207 is deprecated in favor of `#canAccess`

**Comment by NavinKumarBarnwal** [comment]
Hi @NotMyFault ,
Can you confirm above 2 piece of code mentioned is only deprecated? I want to contribute here.
Thanks

**Comment by NotMyFault** [comment]
Yes, both snippets mentioned are deprecated.
