### ISSUE TITLE
Road Regen doesn't work properly and crashes server

### ISSUE THREAD

**Issue by GammaPotato** [IntellectualSites/PlotSquared#3920]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

First thing that i want to say: my english is bad. Im half Italy and half german

my friends and i built new roads. after testing the new roads with "/p debugroadregen Plot", the roads were regenerated without any problems.

with the command "/p regenallroads Plot" does the server server spam the message "
[01:36:27] [Server thread/WARN]: [PlotSquared] Plugin is adding a faraway chunk ticket at (1875049, 1875041), this might cause issues.
[01:36:27] [Server thread/WARN]: [PlotSquared] Plugin is getting a faraway chunk at (1875049, 1875041), this might cause issues.
 for several seconds every few seconds in consol.
The streets are only partially generated correctly and on the screenshot you can see that the streets and edges have been generated strangely. is it my server or the plugin? Or even me?

Claimed plot: stone bricks
Unclaimed: Quarz 

before the server crashes after 2 minutes. if I use command. After a restart, the plugin starts to work again on its own and the message mentioned above is displayed (or screenshot) The paths are generated incorrectly

the road regen problems can be seen here:

http://galaxy-gaming.tk:8100/#plot:0:44:0:198:0.24:0.64:0:0:perspective

plugin Version: 6.10.5-Premium

### To Reproduce

this problem occurs when i run "p regenallraods" in consol

### Expected behaviour

normaly regen roads and not server crashing?

### Screenshots / Videos

![2023-01-09_03 03 42](https://user-images.githubusercontent.com/69405733/211474879-3969200f-6ea6-416a-af18-1403e2164d8e.png)
![Screenshot_2023-01-09_030753](https://user-images.githubusercontent.com/69405733/211474885-13eb20c2-e73e-48fd-a0a6-75332c27c4cc.png)

### Error log (if applicable)

https://paste.gg/p/anonymous/d207b18c52cf4176a4ac79fab4edcb35

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/3d9fe18556f94f05a6c176dcacaaa501

### PlotSquared Version

PlotSquared-Bukkit-6.10.6-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by SirYwell** [comment]
Roads are regenerated chunk-wise, so weird in-between states are somewhat common. What I'm confused about is the faraway chunk warning. PlotSquared only regenerates chunks in existing chunks, which indicates that there is a chunk somewhere far away.

Do you have a `r.58591.58593.mca` file (or similar high numbers) in the region folder of your world? If so, does the server still crash if you remove them from the folder? (backup the world before doing anything to be on the safe side)

**Comment by GammaPotato** [comment]
already tested. problem persists

**Comment by SirYwell** [comment]
Does the warning still appear in that case?

**Comment by GammaPotato** [comment]
after a few chunks have been generated yes and it crashes too

**Comment by SirYwell** [comment]
That sounds like such far away chunk is loaded again for some reason, but PlotSquared definitely doesn't touches chunks that do not exist when regenerating roads. Does the server create an mca file for those chunks again?

**Comment by GammaPotato** [comment]
No. only those where generated by a user

**Comment by GammaPotato** [comment]
Blue map does not cresting this problem i turn bluemap off and an the problem still apears

**Comment by GammaPotato** [comment]
I looked through the log again because the message comes with several files. all files exist. after deleting new ones are generated where the message comes back

**Comment by GammaPotato** [comment]
it now looks like the error message would be gone but the crash remains

**Comment by SirYwell** [comment]
I assume this is some issue with another plugin (or e.g., command block), as I can't reproduce the issue locally.

**Comment by GammaPotato** [comment]
Commandblocks are disabled

**Comment by GammaPotato** [comment]
I'm also on your discord. If you can help me in any way I would be very grateful

**Comment by SirYwell** [comment]
Feel free to ping me (`@SirYwell` should work), so we can figure out what's going on.
