### ISSUE TITLE
Unable to load MYSQL PlotSquared correctly

### ISSUE THREAD

**Issue by qwe938775** [IntellectualSites/PlotSquared#3925]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

The newer version I was using couldn't load correctly, everyone's territory on the map disappeared, but the PlotSquared v6 command did work.

### To Reproduce

used
DATABASE
Convert/Backup Storage
Usage: /plots database [area] <sqlite | mysql | import>
and
DEBUGLOADTEST
This debug command will force the reload of all plots in the DB
Usage: /plot debugloadtest
It loads but doesn't work at all.

### Expected behaviour

Revert to normal loading behavior

### Error log (if applicable)

https://paste.gg/p/anonymous/4d5433b1a3c04278af4aed80e1c56383

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/348d1f2a9f1e47fcb1c202d8383e171e

### PlotSquared Version

PlotSquared-Bukkit-6.10.6-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
I'm unable to replicate the issue based on the information provided. Conversion from MySQL to SQLite worked out of the box for me.

**Comment by qwe938775** [comment]
Please tell me if there is any companion that can save the players' land, thank you

**Comment by OneLiteFeather** [comment]
Can you update your plotsquared to 6.11.1 and try again if still possible?

**Comment by NotMyFault** [comment]
Closing due to lack of response.
