### ISSUE TITLE
Plot damaged moved

### ISSUE THREAD

**Issue by Luke2206** [IntellectualSites/PlotSquared#3927]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

When we tried to move a player plot, half of the plot disappeared.

Command: /p move

PS | Worldedit version is the latest one
![image](https://user-images.githubusercontent.com/102369468/212471012-151aef1f-7b91-4c32-a4dd-04b6b5f66872.png)

### To Reproduce

1. Go on a plot
2. enter command /p move id
3. Plot was moved damaged

### Expected behaviour

That the plot is moved undamaged

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/102369468/212471024-01d52874-7791-4938-9db7-fb74bad01f31.png)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/dd8e72d0501843b9921b4c55fbf9953c

### PlotSquared Version

PlotSquared-6.10.5-Premium  (Meanwhile already upgraded to the latest version)

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Please reproduce that on PaperMC and attach a schematic of the plot allowing others to replicate your setup.

**Comment by NotMyFault** [comment]
No response, assume no longer an issue.
