### ISSUE TITLE
Position from database not working

### ISSUE THREAD

**Issue by vBrian72** [IntellectualSites/PlotSquared#3943]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

When changing an position in the database after claiming new plot, the previous value is retrieved when I type /plot home, not the changed one. Only after a restart is the new value retrieved in /plot home command from the database.

### To Reproduce

1. Claim new plot.
2. Change position in the database.
3. Try go home to the plot (I was teleported to old position which is default)
4. Restart server
5. Try go home again, and I was teleported to new position from database

### Expected behaviour

I want change default teleportation position which is (y = 256, and z = ex. -352 when I want y = 64, z = -343). after claiming new plot without need to set manually home.
It would be great if the values ​​from the database were updated without restarting the server.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/e873b77da7434697b2ecd075769cb1be

### PlotSquared Version

PlotSquared-6.10.9-SNAPSHOT

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by PierreSchwang** [comment]
I don't think there is any valid use case. Changing that to reflect database changes immediately has quite a few performance trade offs, as fewer plot data will be cached and more data will be fetched from the database itself. I don't think that's a good idea imo - but I'm open for any input.

**Comment by NotMyFault** [comment]
Agreed with Pierre, uncached values don't sound like a great idea.
