### ISSUE TITLE
Quick Player Join then Quit Throws Exception

### ISSUE THREAD

**Issue by zachduda** [IntellectualSites/PlotSquared#3951]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

When the player quickly joins and exits the server (prior to even being loaded into the world), the following exception is thrown. I didn't get this error on previous PlotSquared versions and have updated to the latest 6.10.9 as of this morning. Nothing earth shattering or functionally depreciating, just a cosmetic error it seems.

Using PlotSquared-6.10.9-Premium on a Pufferfish (PaperMC Fork / latest build) server running 1.19.3.

Error:
**[View Full PasteBin Exception](https://pastebin.com/raw/hQmeAcsT)**

### To Reproduce

1. Install latest version of PS6
2. Join the server and quickly leave after seeing the "Generating Chunks..." or join and receive a "Connection Throttled" message on the client.
3. PlotSquared will produce this error only OCCASIONALLY. This error has been difficult to replicate since.

### Expected behaviour

The exception should be caught

### Error log (if applicable)

https://pastebin.com/raw/hQmeAcsT

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/77f814b28d594dc4a28904da54c87951

### PlotSquared Version

6.10.9-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
We do not support platforms that are not listed on the platform dropdown.
