### ISSUE TITLE
Ghost blocks

### ISSUE THREAD

**Issue by Xayanix** [IntellectualSites/PlotSquared#3953]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

Blocks are disappearing when block break event is cancelled by PlotSquared

### To Reproduce

On video

### Expected behaviour

.

### Screenshots / Videos

https://user-images.githubusercontent.com/12672902/215482605-27046da9-77e3-4af9-9de7-12ae95549a22.mp4

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/885abc81728f4379b96103a962da242c

### PlotSquared Version

6.10.9 Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Please replicate that without any plugins installed but WorldEdit and PlotSquared first.

**Comment by Xayanix** [comment]
I did, nothing changes

**Comment by NotMyFault** [comment]
Please provide a new plot debugpaste of that then.

**Comment by NotMyFault** [comment]
No response, assume no longer an issue.

**Comment by Xayanix** [comment]
Issue still exists

**Comment by NotMyFault** [comment]
Please provide the requested information to reopen the issue.

**Comment by Xayanix** [comment]
https://athion.net/ISPaster/paste/view/63451c0b0ee84e7f829913bfe3c62345

**Comment by NotMyFault** [comment]
> Please replicate that without any plugins installed but WorldEdit and PlotSquared first.
