### ISSUE TITLE
Plot Merge Bug

### ISSUE THREAD

**Issue by ByToxiii** [IntellectualSites/PlotSquared#3954]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

If I want to merge many plots, this will be noted but it remains large road parts on this plot with on it

### To Reproduce

1. 10 Plots mergen
2. /p merge or /p merge all
3. Merge confirm = Bug

### Expected behaviour

That all the plots are connected without the road parts are on it

### Screenshots / Videos

![2022-11-23_20 02 36](https://user-images.githubusercontent.com/123496883/215582115-1de8e5c4-e68c-4ac6-977c-9d5b07e9807c.png)

### Plot Debugpaste

Please let me know which debug you need

### PlotSquared Version

PlotSquared 6.10.9-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

I ask for quick fix.

**Comment by NotMyFault** [comment]
> Please let me know which debug you need

The output URL of `/plot debugpaste`

**Comment by NotMyFault** [comment]
No response, assume no longer an issue.
