### ISSUE TITLE
3rd party flags arew not set when claiming a plot

### ISSUE THREAD

**Issue by EscolarProgramming** [IntellectualSites/PlotSquared#3956]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

We use the plugin "QuickShop" (https://www.spigotmc.org/resources/quickshop-reremake-1-19-ready-multi-currency.62575/) to provide stores on our plots. This plugin has also implemented PlotSquared flags (quickshop-create, quickshop-trade). We have now entered in worlds.yml that these flags are set to false by default. The flags are also attached at startup, but when you claim a plot these flags are not set. 

### To Reproduce

1. Install PlotSuqared and QuickShop
2. Set quickshop-create and quickshop-trade to false in worlds.yml
3. Start server and claim a plot
4. See that all flags are set, but 3rd party flags

### Expected behaviour

Plots should have that flags set in worlds.yml

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/9cbff0cdb3504556a6f45a58e62d613f

### PlotSquared Version

PlotSquared version 6.10.9-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by dordsor21** [comment]
It would be useful to see the log at startup as well (there could/should be some useful output)

**Comment by Leahcimkrob** [comment]
[latest.log](https://github.com/IntellectualSites/PlotSquared/files/11004971/latest.log)
I'am from the same server

**Comment by Leahcimkrob** [comment]
with quickhop Hikari we have the same issue.

**Comment by NotMyFault** [comment]
(Likely) Fixed in https://github.com/IntellectualSites/PlotSquared/pull/4114
