### ISSUE TITLE
PlayerQuitEvent

### ISSUE THREAD

**Issue by GregKW** [IntellectualSites/PlotSquared#3958]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

When you kick / ban / disconnect a player, it will show this error in console.

https://pastebin.com/QLPPVP3L
https://pastebin.com/W1t1yNY5

### To Reproduce

By kicking / banning / disconnecting, the error happens
https://pastebin.com/W1t1yNY5

### Expected behaviour

Not getting errors

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/ce9e7089de1843fa9ba026cb9ec94c14

### PlotSquared Version

6.10.9-premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
`00000000-0000-0000-0009-01fa340cf3df` is an invalid UUID. PlotSquared does not add invalid UUIDs.
