### ISSUE TITLE
1.19.3 NOT WORK

### ISSUE THREAD

**Issue by Grizzlybln** [IntellectualSites/PlotSquared#3962]
### Server Implementation

Spigot

### Server Version

1.19.3

### Describe the bug

Not generate config not started in console :/

### To Reproduce

1. Buy Server In G-Portal (SpigotMC 1/19/3)
2. Install Plotsquard V 6.11.0
3. Start Server
4. System Not Started And Not Generate An Config Data

### Expected behaviour

i Dont Know How It not work

### Screenshots / Videos

![Screenshot_2023-02-12-18-05-56](https://user-images.githubusercontent.com/123985584/218326535-862117ff-3aeb-4258-952f-7e940e16ff7b.png)
![Screenshot_2023-02-12-18-06-06](https://user-images.githubusercontent.com/123985584/218326550-7d1087ea-bb39-4bd3-a057-d18e86253fcb.png)

### Error log (if applicable)

https://paste.gg/p/anonymous/9aac1dafffc7495ab1b763cdb9238652

### Plot Debugpaste

Not work

### PlotSquared Version

PlotSquard Version 6.11.0 Premium

### Checklist

- [x] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

Please Help Me , my server idea not work when plotsquard not worked

**Comment by NotMyFault** [comment]
According to the log provided, PlotSquared is not installed on the server. Given you're installing the plugin through a portal provided by your hoster, it's best to ask them for support.

**Comment by Grizzlybln** [comment]
Sorry But It Is Installed See The Screenshots o.O

**Comment by NotMyFault** [comment]
> Sorry But It Is Installed See The Screenshots o.O

Please read my last response carefully. We cannot provide support for your hoster's plugin portal.

**Comment by Grizzlybln** [comment]
Ok sadly i wanted plotsquard support :(

**Comment by NotMyFault** [comment]
Yet again, this is nothing related to PlotSquared. You are using a custom plugin portal working differently to what it shows.
My original recommendation still stands.
