### ISSUE TITLE
/p i and other commands

### ISSUE THREAD

**Issue by LCBG1Pixel** [IntellectualSites/PlotSquared#3968]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

Can anyone help me with Plotsquared? I'm using Plotsquared-Bukkit-6.11.0, Fawe and more Plugins (all plugins: https://pastebin.com/GFWcbpSd). When i type /p i or /p help or something in chat nothing happens not in console not in chat and it give's me no errors.

### To Reproduce

It's only on my server with Citybuild Plugins on my localhost it works

### Expected behaviour

I wan't to see infos about the plot and the other commands

### Screenshots / Videos

https://youtu.be/3_NnsqAszIY

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/68989e599cec47e6a876548d231af8ff

### PlotSquared Version

PlotSquared-Bukkit-6.11.0-Premium.jar

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

It works on my localhost and on a server tha is not connected with the Velocity proxy

**Comment by NotMyFault** [comment]
This issue tracker is for issues, not for support. Please consider using our [discords server](https://discord.gg/intellectualsites) for support. Navigate to `#ps-spigot-verification`.
