### ISSUE TITLE
Optimize BukkitMain$1

### ISSUE THREAD

**Issue by Log1x** [IntellectualSites/PlotSquared#398]
Not sure if anything can be done here, but I thought I'd suggest any possible improvements/optimizations that can be made to "BukkitMain$1"

You can see its CPU usage here in an empty server using Top:

![Top](http://log1x.com/screenshots/2015-07-14_02-49-06.png)
![PlotSquared](http://log1x.com/screenshots/2015-07-14_02-48-55.png)

Honestly, the performance isn't bad whatsoever, especially when compared to PlotMe-- but I thought I'd mention it anyway in case anything can be tweaked. :)

Feel free to close this if deemed impossible/unnecessary.

**Comment by boy0001** [comment]
That's the task for killing road mobs, you can disable it in the settings.yml, but I'll see if I can optimize it.

**Comment by boy0001** [comment]
Optimized
