### ISSUE TITLE
[Feature Request] Postgresql support

### ISSUE THREAD

**Issue by GNUGradyn** [IntellectualSites/PlotSquared#3984]
### What feature do you want to see added?

Support for postgresql for data storage in addition to MySQL and sqlite. Many existing servers use Postgresql and don't want to install an entire mysql server alongside their postgres server 

### Are there any alternatives?

sqlite is not a valid alternative for many applications as it is single client. Installing a MySQL server alongside postgres is possible, but not ideal.

**Comment by GNUGradyn** [comment]
Probably should have mentioned I am taking a stab at this. This FR is more of a formality lol

**Comment by SirYwell** [comment]
Note there is ongoing work on databases (<https://github.com/IntellectualSites/PlotSquared/pull/3609>). It will be far less headache to support different database systems with that.

**Comment by GNUGradyn** [comment]
Thanks. I will wait for this so we aren't doing this twice lol
