### ISSUE TITLE
Blocks above 255 are not removed when a plot is cleared

### ISSUE THREAD

**Issue by iLemon** [IntellectualSites/PlotSquared#3985]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

When you do a /plot clear, it doesn't clear blocks above 255.

### To Reproduce

https://pastes.dev/WY9kThu8KK

Use these world settings.

### Expected behaviour

@PierreSchwang in discord said "Seems like the max_gen_height is used. Create an issue for that" so I assume clearing needs to use max_height instead.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/d154f3e8d89f4e89bfe6d1291f265577

### PlotSquared Version

6.11.0-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by iLemon** [comment]
![image](https://user-images.githubusercontent.com/18317307/224391531-b44357db-dc82-40a8-af06-f94e5c3f54e4.png)

**Comment by QuickWrite** [comment]
I've tested a little bit around and it seems like it isn't an issue with the plot flags and protection methods. They all work above `255` while the clearing doesn't.

So it seems like it is just an issue with the clearing of blocks.
