### ISSUE TITLE
Allow players to use coreprotect for rollback on their own plot

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/PlotSquared#3990]
### What feature do you want to see added?

I'm using CoreProtect with PlotSquared. If Player1 griefs Player2, Player2 has to report it to an Admin and wait for the Admin to log on and use the rollback command, It would be a lot more time efficient and convenient if the owner of a plot was able to fix grief by having permission to use the rollback command on their own plots. I made a suggestion to CoreProtect for this but they said that PlotSquared would need to add support for this: https://github.com/PlayPro/CoreProtect/issues/324

### Are there any alternatives?

No

**Comment by dordsor21** [comment]
As P2 is the land-ownership-handling plugin in this situation, it is logical that other plugins should add support for P2, not the other way round. There are countless thousands of plugins for which P2 integration would be beneficial, but there are very few commonly-used land-ownership plugins. This would not be something on us to integrate.

**Comment by PierreSchwang** [comment]
Phew, absolutely not a fan of CoreProtect but either way - should be possible. Little bit scared about the performance impact as CP does their stuff "interesting" most of the time.
