### ISSUE TITLE
Stone edges are no longer generated after "Schematic generation" setup.

### ISSUE THREAD

**Issue by iCrashMix0** [IntellectualSites/PlotSquared#3999]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

Hello, I have downloaded the plugin PlotSquared and Fawe the latest version for 1.19.2 Paper Server and put them in plugin folder. I then started the server and everything ran without errors. First I did a setup to create a plotworld and used the default values in setup. Then first the plotworld was created with empty green area with stone borders. After that I wanted to add/activate this "Schematic generation" [https://intellectualsites.github.io/plotsquared-documentation/schematics/schematic-generation.html](https://intellectualsites.github.io/plotsquared-documentation/schematics/schematic-generation.html) and I followed the instructions exactly and properly and did not change anything else in the settings and so on. I followed the instructions exactly. Then stopped server and deleted the plotworld so that the plotworld can regenerate. After that server started and then the image **no. 1** looked like this and suddenly without stone borders, why? Then I went some plot and executed with /plot claim and first nothing happened except that I took the plot in my possession. Then I executed the command /plot delete and again /plot claim and suddenly this stone border is there, see picture **no. 2**, why is that? And but it is still generated without stone borders like on the picture **no. 1**.

![Screenshot 2023-03-21 171218](https://user-images.githubusercontent.com/110557043/226670826-b7729da7-ac46-4d31-a7d7-a27f87e9e386.png)
![Screenshot 2023-03-21 171224](https://user-images.githubusercontent.com/110557043/226670851-9fc92b12-74b5-446e-b76c-da1a844f6f65.png)

### To Reproduce

1. Rebuild Minecraft Server **1.19.2 Paper**.
2. Download the plugin [PlotSquared v6](https://www.spigotmc.org/resources/plotsquared-v6.77506/) and [FAWE](https://intellectualsites.github.io/download/fawe.html) and put them into the plugins folder.
3. Launch Minecraft Server.
4. Create plot world with default values:
    - /ps setup PlotSquared
    - /ps setup normal
    - /ps setup 62
    - /ps setup 42
    - /ps setup stone
    - /ps setup true
    - /ps setup grass_block
    - /ps setup stone_slab
    - /ps setup sandstone_slab
    - /ps setup 7
    - /ps setup 62
    - /ps setup quartz_block
    - /ps setup stone
    - /ps setup 62
    - /ps setup true
    - /ps setup (World name)
5. Take some empty plot and build something on it for test purposes.
6. Perform setup "[Schematic generation](https://intellectualsites.github.io/plotsquared-documentation/schematics/schematic-generation.html)".
7. Minecraft server stop.
8. Delete plot world so that it can generate completely.
9. Launch Minecraft Server.
10. Then you see that all plots are generated without stone borders, but if you take on free plots with **/ps claim** and then delete **/ps delete** plot, then the stone border is suddenly there and the whole thing must be fixed so that the stone borders are generated at the beginning.

### Expected behaviour

That the stone edges after "[Schematic generation](https://intellectualsites.github.io/plotsquared-documentation/schematics/schematic-generation.html)" setup will no longer generate.

### Screenshots / Videos

![Screenshot 2023-03-21 171218](https://user-images.githubusercontent.com/110557043/226693969-50a00584-d754-4134-af93-84ee842cf15e.png)
![Screenshot 2023-03-21 171224](https://user-images.githubusercontent.com/110557043/226693991-f4566382-4225-457d-b0f8-d688e3aa0b73.png)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/e7d3be5af0524ffb9d08a5cb29a3c163

### PlotSquared Version

PlotSquared-6.11.1-Premium

### Checklist

- [x] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by dordsor21** [comment]
Could you provide the schematic used for the plot? From what I can tell, the schematic is "oversized" causing P2 to believe that you're providing part of the road with the schematic.

**Comment by iCrashMix0** [comment]
> Could you provide the schematic used for the plot? From what I can tell, the schematic is "oversized" causing P2 to believe that you're providing part of the road with the schematic.

https://easyupload.io/pvops3

**Comment by dordsor21** [comment]
Interesting. The schematic is indeed only 42x42 🤔

**Comment by iCrashMix0** [comment]
> Interesting. The schematic is indeed only 42x42 🤔

Yes, that has to be fixed.

**Comment by iCrashMix0** [comment]
Why is the ticket now closed again?

**Comment by iCrashMix0** [comment]
Ah I was a little confused, I thought they have not been a team member. :D And also saw that they have fixed the bug and where can you download the plugin? Do I have to wait until the new update comes out from V7 PlotSquared?
