### ISSUE TITLE
Placeholder or Command

### ISSUE THREAD

**Issue by Leahcimkrob** [IntellectualSites/PlotSquared#4004]
### What feature do you want to see added?

Is there a placeholder or command to show the plot limit and already claimed plots from other players?
If not, it would be my wish that something like this would be implemented.

%plotsquared_plot_count_<player>%

### Are there any alternatives?

no alternative

**Comment by NotMyFault** [comment]
That does already exist.

**Comment by Leahcimkrob** [comment]
There is a placeholder for your own plots, that's correct, but there is no placeholder for displaying how many plots another player has.
Or what is the placeholder for the number of plots of other players?
