### ISSUE TITLE
Commands dont work at all when compiling

### ISSUE THREAD

**Issue by fhores** [IntellectualSites/PlotSquared#4007]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

it just dosent owrk i dowloaded it and i did shadowjar but nothin maynnn

### To Reproduce

nothin config files dont show up too

### Expected behaviour

commands to work

### Plot Debugpaste

dosent work

### PlotSquared Version

dosent work

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Follow the issue template if you want to report an issue.
