### ISSUE TITLE
Plotsquared for 1.19

### ISSUE THREAD

**Issue by Nesokk** [IntellectualSites/PlotSquared#4008]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

hello, 

In the 1.19,2 version of minecraft is the plugin broken, the server not even register the plugin.
I hope you can help me and thanks for your work.
Your Sincerly
Nesokk

### To Reproduce

Just load the plugin in the server and use /pl and the plugin isnt there

### Expected behaviour

I expectet that it would work.

### Plot Debugpaste

the plugin isnt loading

### PlotSquared Version

plotsquared-6.10.3

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Follow the issue template if you want to report an issue.
