### ISSUE TITLE
Stone edge and custom road is no longer generated

### ISSUE THREAD

**Issue by iCrashMix0** [IntellectualSites/PlotSquared#4013]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

The stone edge and custom road is no longer generated by creating custom road (/plot createroadschematic) beforehand for the first time.

### To Reproduce

1. [Paper 1.19.2](https://papermc.io/downloads/all) is required.
2. PlotSquared here [download](https://github.com/IntellectualSites/PlotSquared).
3. FAWE here [download](https://ci.athion.net/job/FastAsyncWorldEdit/lastSuccessfulBuild/artifact/artifacts).
4. Multiverse Core here [download](https://dev.bukkit.org/projects/multiverse-core/files).
5. put all plugins in plugin folder and start server or accept EULA before.
6. create plot world with following commands:

    ![grafik](https://user-images.githubusercontent.com/110557043/231024637-62687ec8-1d30-4c6e-be02-aad025051e79.png)
    Then it looks like this without custom road **(See picture number 1)**
    But what's **_important_** is they still need to get a plot and test install it and then do [Schematic generation](https://intellectualsites.github.io/plotsquared-documentation/schematics/schematic-generation.html) setup.

8. Take a plot and install it all around the road as a test. **(See picture number 2)**
9. On the plot on it and enter /plot createroadschematic.
10. Fly a little further away and at the end you will see that it is generated with gobbledygook. **(See picture number 3)**

### Expected behaviour

Last time error of **Stone edges are no longer generated after "Schematic generation" setup.** was fixed here you can see it: [Link](https://github.com/IntellectualSites/PlotSquared/issues/3999#issuecomment-1484141732), but I found another problem. When I activate Schematic generation so to speak without Custom road I then created with /plot createroadschematic and then suddenly is generated again without stone edge.

### Screenshots / Videos

Here you can see that it worked with the Schematic generation or that it is generated with stone edge, but was fixed last time. But here was not yet created a custom road, so with the command /plot createroadschematic:
![1](https://user-images.githubusercontent.com/110557043/231021522-a4751543-4e5d-4880-9a1d-eed9ea51bf4f.png)

Then I wanted to create custom road with /plot createroadschematic and it should look like this:
![2](https://user-images.githubusercontent.com/110557043/231027815-602d0fe0-8541-4802-ab48-ef202e96a613.png)

End result (No custom road and border is generated here, which is actually what the two things are supposed to be generated.) (But I still deleted extra world before, so I can determine if the bug still exists.):
![3](https://user-images.githubusercontent.com/110557043/231021531-aa44ce73-42e7-48a0-bb1c-5f4920eeaa9a.png)

### Error log (if applicable)

https://paste.gg/p/anonymous/82f7cec6801e4bb69e1818786bd0ff0d

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/ed382a89164b44f780db78844dff1319

### PlotSquared Version

7.0.0-SNAPSHOT

### Checklist

- [X] I have included a Plot debugpaste.
- [x] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
![grafik](https://user-images.githubusercontent.com/77929075/233656499-f0afe0be-1a53-46ba-b3f7-fb2f541f9bae.png)
Could not reproduce your issue in a way it is intended to work. I saw that you stopped the server after writing /plot regenallroads after 2 minutes in game. You have to use this command in your console and patiently wait till the process is done.

In addition: Please do NOT use Plotsquared v7 in production (a server where player use plotsquared) yet, it's not released yet. You might use it in development (aka test server) at your own risk.

**Comment by iCrashMix0** [comment]
@OneLiteFeather make street width 21 instead of 7 because last time I left it at 7 looked workable.

**Comment by iCrashMix0** [comment]
![grafik](https://user-images.githubusercontent.com/110557043/233748205-0536097c-a59c-4a38-9587-b0ff8d18664f.png)

**Comment by OneLiteFeather** [comment]
Please use /plot regenallroads in **your console** and show us the result. It might take a while.

**Comment by OneLiteFeather** [comment]
Please use /plot regenallroads in **your console** and show us the result. It might take a while.

**Comment by iCrashMix0** [comment]
Oops it has nothing to do with street width sorry. I meant you also have to do the setup of "Schematic generation", because without that it works.

Schematic generation -> https://intellectualsites.github.io/plotsquared-documentation/schematics/schematic-generation.html

**Comment by OneLiteFeather** [comment]
Well I could reproduce it but it is not clearly a bug. Plotsquared uses the edge as part of the road, as you might can find out if counting the road width + the edge width on setup. The edge can be generated using the road schematic, so it won't be "cut off". This should be added in **documentation** instead. If you generate the road schematic and do /plot regenallroads in console, you should be fine.
