### ISSUE TITLE
[v7] multi languages ​​support

### ISSUE THREAD

**Issue by IT-EXPRESS-Munich** [IntellectualSites/PlotSquared#4021]
### What feature do you want to see added?

multi language support but on the basis of a command, so that configs and all texts can be directly integrated with some languages ​​(I'm happy to help translate languages)

/p lang [de,en,ru,it, usw.]

### Are there any alternatives?

N/A

**Comment by SirYwell** [comment]
PlotSquared already supports per-player locales. Set `per-user-locale` to true in the settings.yml and add message files to the `lang` folder (e.g. from <https://intellectualsites.crowdin.com/plotsquared>). The language is automatically picked based on the client settings.

**Comment by OneLiteFeather** [comment]
Not sure if you can do this without a server restart `/p lang [de,en,ru,it, usw.]` in Plotsquared language "system". It would make it possible to choose languages more freely as a player, independent on client settings. Do you know if it's possible to add anyways without rewrite @SirYwell ?

**Comment by NotMyFault** [comment]
> It would make it possible to choose languages more freely as a player

I fail to see a net benefit in that. Why would I want to play the game in dutch, if my client locale points to estonian?

The current system is fine as-is and provides enough flexibility for the player.

**Comment by PierreSchwang** [comment]
> > It would make it possible to choose languages more freely as a player
> 
> I fail to see a net benefit in that. Why would I want to use PlotSquared only in dutch, if my client locale points to estonian and everything else is estonian?
> 
> The current system is fine as-is and provides enough flexibility for the player.

As much as I see your point - I must admit that I'm using MC in english but select german most of the time as a server locale itself - same goes for my firefox instance (tho that was by accident lol)

**Comment by SirYwell** [comment]
I think the current support for this is sufficient in PlotSquared.
Other needs may vary a lot and therefore should be implemented as a third-party plugin interacting with the PlotSquared API. This also allows for e.g. inventory-based GUIs, network-wide per-player locales, probably synchronized between plugins, and much more.
