### ISSUE TITLE
[v7]  2 Build Errors (Git Clone and Build)

### ISSUE THREAD

**Issue by IT-EXPRESS-Munich** [IntellectualSites/PlotSquared#4023]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

i get 2 error messages but i can't find the time jump of the error in the code, i downloaded the code with git and then tried to build directly

### To Reproduce

-

### Expected behaviour

ERROR 1-Caused by: com.google.googlejavaformat.java.FormatterException: 972:72: error: ')' expected
ERROR2 -Execution failed for task ':PlotSquared-Bukkit:spotlessJava'.
> Issue processing file: C:\Users\goc24\IdeaProjects\PlotSquared\Bukkit\src\main\java\com\plotsquared\bukkit\BukkitPlatform.java

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

Additional:
Cause: java.lang.reflect.InvocationTargetException

### Plot Debugpaste

N/A

### PlotSquared Version

7.0 DEV BUILD (git repo download and build)

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by PierreSchwang** [comment]
spotless indicates there is a formatting issue in your codebase. I can't tell you exactly what and where as the full log is missing.

**Comment by IT-EXPRESS-Munich** [comment]
> spotless indicates there is a formatting issue in your codebase. I can't tell you exactly what and where as the full log is missing.

this is the only error it shows, i cloned the code 1 to 1 from git and tried to build

**Comment by PierreSchwang** [comment]
> > spotless indicates there is a formatting issue in your codebase. I can't tell you exactly what and where as the full log is missing.
> 
> 
> 
> this is the only error it shows, i cloned the code 1 to 1 from git and tried to build

That's not the full error, no - IntelliJ just trims the error based on your selection on the left side navigation. Either select the top level entry or run gradlew from your command line manually.

**Comment by NotMyFault** [comment]
As we can see in a recent PR, the codebase is spotless: https://github.com/IntellectualSites/PlotSquared/actions/runs/4737843101/jobs/8411071796?pr=4018

Any failure is down to modifications or OS shenanigans, P2 is not accountable for. I recommend reaching out to the spotless maintainers if you encounter issues with spotless.
