### ISSUE TITLE
Plot Area Create - No Fallback if no PlotAreaType is set by user

### ISSUE THREAD

**Issue by PierreSchwang** [IntellectualSites/PlotSquared#4024]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

When executing `/plot area create <name>` an error is thrown, that the PlotAreaType (<local4>) is null.
That's due to PlotAreaBuilder#plotAreaType not having a default value.

When running `/plot area create <name> type=normal` (forcefully setting the PlotAreaType) that works.

### To Reproduce

-

### Expected behaviour

Either the PlotAreaType must be a required parameter or have a default value (NORMAL)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/ddac2180e702470aa3a22f203a19c3d9

### PlotSquared Version

PlotSquared-6.11.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
https://github.com/IntellectualSites/PlotSquared/issues/3023
