### ISSUE TITLE
Plot claim not use economy 

### ISSUE THREAD

**Issue by saschafrei996** [IntellectualSites/PlotSquared#4027]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

When we try to buy or claim a plot it comes the chat message:" no ecnonomy plugin is initialized..."
We have the Sunlight Economy Plugin installed and it works for jobs and shops. Only in Plotssquared it doesnt work.

### To Reproduce

1. Use Sunlight Economy
2. Buy or claim a Plot 
3. look at your bankaccount

### Expected behaviour

The money should be reduced

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/6475626/233844939-e0d87a94-58f5-4244-be78-b41ace8e0e92.png)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/a9c871fdf7ee4802bfe1caa21c2df34a

### PlotSquared Version

6.11.1 premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by TheMeinerLP** [comment]
Can you please provide a link this Economy Plugin ?

**Comment by saschafrei996** [comment]
https://www.spigotmc.org/resources/sunlight-server-management-plugin-essentials-update-part-vii.67733/

**Comment by TheMeinerLP** [comment]
The issue is economy it self... The developer of that plugin don't register a service or to late for hook into plotsquared.

**Comment by saschafrei996** [comment]
Ok thanks for the very fast answer

**Comment by saschafrei996** [comment]
So i have to ask the dev of sunlight?

**Comment by TheMeinerLP** [comment]
Yeah that on there point

**Comment by saschafrei996** [comment]
OK thanks, have a nice sunday
