### ISSUE TITLE
/p set biome not working near roads

### ISSUE THREAD

**Issue by Log1x** [IntellectualSites/PlotSquared#404]
After converting from PlotMe 0.17 (which default biome is PLAINS)-- I appear to have PLAINS biomes near my roads sporadically through out the world that can not be altered with /p set biome.

This Plains biome also appears a vast majority of the time when merging a plot (i.e. beneath the road).

![PLAINS](http://log1x.com/screenshots/2015-07-14_17-19-50.png)
In the screenshot above, you can see I had just executed /p set biome JUNGLE which worked perfectly fine everywhere in the plot but where I'm standing, of which you can see in the Debug text is still Plains.

I have also confirmed that this persists after relog or reloading the chunk.

<3

**Comment by EvilOlaf** [comment]
Did you try to relog after using ´/p set biome´?
There are already a few closed issue reports about biome problems: https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+biome

**Comment by Log1x** [comment]
Yes, it persists after relog. I had that added to my ticket but I must've not updated it.

**Comment by boy0001** [comment]
Merging with #455
