### ISSUE TITLE
Spawn smth on plot road

### ISSUE THREAD

**Issue by Quoboo** [IntellectualSites/PlotSquared#4041]
### Server Implementation

Spigot

### Server Version

1.19.3

### Describe the bug

My developer has coded a plugin that puts you in a boat as soon as you enter the water for plot reasons, but you can't spawn anything for plot reasons. how do i change that?

### To Reproduce

Can i change it in config??!!

### Expected behaviour

My developer has coded a plugin that puts you in a boat as soon as you enter the water for plot reasons, but you can't spawn anything for plot reasons. how do i change that?

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/2777e85e53bb41dd856526bcd14dbc85

### PlotSquared Version

6.11-1

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by TheMeinerLP** [comment]
Thats looks like more a question and not like a bug

**Comment by OneLiteFeather** [comment]
@Quoboo Do you mean in the claimed plot, unclaimed plot or on the road? These links could be helpful for your developer:
https://github.com/IntellectualSites/PlotSquared/issues/3255
About road flags:
https://github.com/IntellectualSites/PlotSquared/issues/3047

**Comment by NotMyFault** [comment]
For questions, please use the community discord.
