### ISSUE TITLE
Permpacks not working (LuckPerms)

### ISSUE THREAD

**Issue by Mas-o** [IntellectualSites/PlotSquared#4042]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

Hello, I am trying to use the permpacks with LuckPerms for my server, and it seems that they didn't work (note: permissions are set up correctly, no special flags either as PlotSquared is only enabled on the creative plotworld). Is there something that I need to check in the config, it'd be a pain to have to add all the permissions seperately. Thank you in advance.

### To Reproduce

Using LuckPerms, add the permission flags for the permpacks: plots.permpack.basic, plots.permpack.basicflags, plots.permpack.basicinbox

LuckPerms Ver: 5.4.67

### Expected behaviour

Permissions working on select roles.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/e41fb80a8fab48b099036cf4830151d3

### PlotSquared Version

6.11.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

If this is not a P2 issue I apologize and will redirect questions to the correct sources.

**Comment by NotMyFault** [comment]
I'm unable to replicate the issue based on the information provided.
