### ISSUE TITLE
FAWE world edit protection is not working properly 

### ISSUE THREAD

**Issue by LowIQWithAutism** [IntellectualSites/PlotSquared#4043]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

You can use your wand to pos1 the road then walk back into your plot to pos2
Then if you are standing in your plot it will allow you to worldedit the road or other plots that you do not own

### To Reproduce

Use wand to pos1 road
pos2 in plot
stand in plot and type world edit command

### Expected behaviour

You should not be able to worldedit anything outside of your plot

### Screenshots / Videos

https://i.gyazo.com/fbb9e61fd572dae6dcbb64c36195b24e.mp4

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/d4375b8f603a466a95ed415d8a972d18

### PlotSquared Version

PlotSquared-Bukkit-6.11.1-Premium.jar

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by SirYwell** [comment]
FAWE issue: https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/2227

Update to build 421 where it should work properly again.
