### ISSUE TITLE
Wither can destroy plot border and blocks will drop resulting in dupe glitch

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#4049]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

If you spawn a wither in the plot, and hit them to the border with a sword, he will destroy the border

### To Reproduce

1. Spawn wither in plot
2. Hit them in the direction of the border with a sword
3. Enjoy the bug

### Expected behaviour

Wither should not be able to destroy the border. This is also a dupe bug because the border blocks are dropping as item

### Screenshots / Videos

![image](https://github.com/IntellectualSites/PlotSquared/assets/38475631/8b583c22-5c1e-4267-9765-0e03394c1700)
![image](https://github.com/IntellectualSites/PlotSquared/assets/38475631/9e92f9e6-cac8-4ff9-9a0c-6a31f2d28a49)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/52f78b1cb0f54a1e94afd5c8bd0bdd33

### PlotSquared Version

6.11.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
![grafik](https://github.com/IntellectualSites/PlotSquared/assets/77929075/baf82f6c-bc44-4884-a977-e8c58c16f9a0)
Can reproduce it

**Comment by OneLiteFeather** [comment]
The description might be misleading, that can be used for duping if you can change the edge of the plot, but it's plot edge destruction with the withers bottom in the first place.

**Comment by Link0Darck** [comment]
it does the same thing on spigot i had to put a worlguard rule and dispawn the mob on the roads

**Comment by NotMyFault** [comment]
Spawning mobs known to cause environmental damage is not something PlotSquared can or should control. I recommend fighting these mobs in an adequate place, like a survival world.

**Comment by Link0Darck** [comment]
> Spawning mobs known to cause environmental damage is not something PlotSquared can or should control. I recommend fighting these mobs in an adequate place, like a survival world.

I think it's not a reason, it's true that the mobs must be in a survival world, but the best thing would be to use worldguard to avoid damage, because in any case there will always be people trying to destroy the server, and a server without worldguard protection is strange.
