### ISSUE TITLE
Improve the PVP Flag

### ISSUE THREAD

**Issue by Log1x** [IntellectualSites/PlotSquared#405]
I have a few suggestions for the PVP flag.

Right now, for PVP to work within' PlotSquared, you need server.properties and Multiverse's world config both set to pvp: true.

This is completely sane, and should stay working like above.

The downside currently is with Multiverse's PVP enabled, is it allows world PVP as a whole in any plot, despite if the flag is set or not (including when False, if the player is added to your plot)

I'd like to suggest since PlotSquared is conceptualized around building/creative, that if Multiverse PVP is enabled, PVP continues to be disabled world-wide in PlotSquared.

If a user sets their PVP flag to true, PVP will ONLY be enabled in that plot. If you leave that plot, the PVP flag is gone; the same as you'd see with leaving a plot with a gamemode flag. Seamless.

If deemed sane, a solution for those servers who do indeed require world PVP on their plot world, provide them with a configuration option to force-enable PVP in the entire world, otherwise PlotSquared will always fall back to the plots current flag settings.

PVP on the roads would obviously continue to be disabled at all times. I'd assume it'd be ideal to make pvp deny respect that plots flags even when force-enable-pvp is enabled.

In my screenshot below, you can see an example of PlotSquared current operation with PVP as I kill another player in a plot that is pvp deny and set to gamemode creative.

![Screenshot](http://log1x.com/screenshots/2015-07-14_18-57-46.png)

I'm sure this could be implemented better than above (i.e. the config options for PVP, could maybe do a permission instead), so feel free to elaborate on it. I think the overall functionality is sane though, and a definitely improvement over the current implementation.

**Comment by boy0001** [comment]
New behaviour
 - if pvp is false, pvp is prevented regardless of ownership
 - if pvp is true pvp is allowed
 - If pvp is unset, pvp is allowed (this can be changed if a third behavior is required)

See here for setting global flags:
https://github.com/IntellectualSites/PlotSquared/wiki/Usage:-Plot-flags#default-flags
