### ISSUE TITLE
Plot schematics are placed incorrectly after /plot delete 

### ISSUE THREAD

**Issue by BakiDance** [IntellectualSites/PlotSquared#4050]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

I have a plot schematic that generates with the world perfectly. However, when a plot is claimed, then deleted, the original schematic is pasted incorrectly (with a large void under the schematic).

I'm not sure why this is happening. The blank.schem pastes correctly, and so does the plot.schem in naturally generated chunks. The plot height ordinarily goes up to y=62; I'm also unsure as to why the void is at y=50.

### To Reproduce

1. Have a plot.schem saved and set up for your world.
2. Claim a plot (I also have a blank.schem set up. Not sure if this is related?), then delete the plot again.
3. The original plot schematic will load, but there is a large gap of air under it where there was not previously one present.

### Expected behaviour

The plot schematic should paste without a large gap of air under it.

### Screenshots / Videos

https://youtu.be/j0j6QnglSl8

![Screenshot from 2023-05-28 20-34-17](https://github.com/IntellectualSites/PlotSquared/assets/43658058/3fed8f73-99a7-4af4-b839-b689e91596bc)
![Screenshot from 2023-05-28 20-34-05](https://github.com/IntellectualSites/PlotSquared/assets/43658058/4a374697-6322-4d42-b831-cdcc7a8b24a7)
![Screenshot from 2023-05-28 20-34-26](https://github.com/IntellectualSites/PlotSquared/assets/43658058/e146ca05-160e-4144-8842-fa54026cc8bc)
![2023-05-27_23 50 07](https://github.com/IntellectualSites/PlotSquared/assets/43658058/815ed638-57a9-4310-8cdc-ea41ab48b161)

![Screenshot from 2023-05-28 20-41-50](https://github.com/IntellectualSites/PlotSquared/assets/43658058/7a27531e-1274-4c5a-88df-8a197f073638)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/77e8bb64effb4384bd37eac062d7ac1c

### PlotSquared Version

6.11.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by BakiDance** [comment]
Also happening on plotsquared-bukkit-7.0.0-RC.2-Premium

**Comment by dordsor21** [comment]
I believe this is due to the road schematic height being lower, and therefore the plugin pastes air where the plot was in order to "paste the schematic properly without existing blocks" but it does it wrong clearly
