### ISSUE TITLE
Not working - Errors in console

### ISSUE THREAD

**Issue by ItzMaroYT** [IntellectualSites/PlotSquared#4051]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

When the server starts it shows some errors
and  I can't do any command from PlotSquared

can someone help me?

### To Reproduce

downloaded the latest version of PlotSquared
updated server version to 1.19.3

### Expected behaviour

When the server starts it shows some errors
and  I can't do any command from PlotSquared

can someone help me?

### Screenshots / Videos

When the server starts it shows some errors
and  I can't do any command from PlotSquared

can someone help me?

### Error log (if applicable)

https://gist.githubusercontent.com/ItzMaroYT/47f063cb647acb180e7586a59ce8172e/raw/354cb0936237eb04ca56051c0bda2f7f43dd3abf/gistfile1.txt

### Plot Debugpaste

Can't commands

### PlotSquared Version

4.4.495

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by ItzMaroYT** [comment]
can someone help me?

**Comment by OneLiteFeather** [comment]
Please update Plotsquared, we're on v6 right now

**Comment by ItzMaroYT** [comment]
its premium?

**Comment by ItzMaroYT** [comment]
but its paid...

**Comment by OneLiteFeather** [comment]
You can either build it on your own or use the download feature on spigot when you have premium. Building on your own is free, you can find out how to build a jar with github clone and gradle on the internet.

**Comment by ItzMaroYT** [comment]
k ty
