### ISSUE TITLE
Plotsquared with Battlepass error passing Event

### ISSUE THREAD

**Issue by valeriorobert** [IntellectualSites/PlotSquared#4058]
### Server Implementation

Paper

### Server Version

1.19.3

### Describe the bug

This is the error I got when Battlepass try to pass the event.

### To Reproduce

- Have battlepass with plotsquared
- Have pass that has quests with plotsquared  : plotsquared_claim, plotsquared_visit, plotsquared_rate

### Expected behaviour

I don't know that precisely should do. I only know that I got this error every time a player joins Battlepass.

### Error log (if applicable)

https://pastebin.com/LumsKkrZ

### Plot Debugpaste

 https://athion.net/ISPaster/paste/view/d95f09a7d672488c8f9d93ad948a7f7c

### PlotSquared Version

PlotSquared version 6.11.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

The only difference is that I have 1.19.4 Paper instead of 1.19.3 but on Spigot there is no update, there is only this 

"This is the last release of the v6. The next major version, v7, will be released this week, too. Stay tuned!
In case of questions, don't hesitate to ask on our Discord server: https://discord.gg/intellectualsites

From March 6.

**Comment by dordsor21** [comment]
Not sure how this is a PlotSquared issue?

**Comment by NotMyFault** [comment]
Issues with third party plugin integrations should be reported to their author(s).
