### ISSUE TITLE
add a function to disable /p merge all

### ISSUE THREAD

**Issue by Luke2206** [IntellectualSites/PlotSquared#4059]
### What feature do you want to see added?

Several times a week I see users using /p merge all instead of /p merge. 
This results in many large but unused plots at very low prices. 

That's why I would like to see a function that allows you to deactivate /p merge all.

### Are there any alternatives?

deactivate merge
overwrite command with another plugin

**Comment by NotMyFault** [comment]
This command is regulated by permission. Remove the permission if you don't want users to use the command.

**Comment by Luke2206** [comment]
oh okay. how is the perm that i can disable p merge all?

**Comment by Luke2206** [comment]
@NotMyFault  can you tell me the perm to disable /p merge all?

**Comment by NotMyFault** [comment]
https://intellectualsites.github.io/plotsquared-documentation/commands.html#_merge
