### ISSUE TITLE
ArmorStands

### ISSUE THREAD

**Issue by JugadorNinja** [IntellectualSites/PlotSquared#406]
The armor stands seems to not be fully protected in the plots, any user can break someone else's armor stands without permissions, as for now i have to tell them to cover the armor stands with glass for the mean time. The fallowing version is the ones i'm using:
spigot 1.8.7
Plotsqured: 2.12.8

**Comment by dextonanderson** [comment]
Can confirm this

**Comment by boy0001** [comment]
Some recent changes in spigot meant it was reclassified as normal entity interaction which would be allowed if you enable pve. This should be corrected for the next version as of: f471a05dcd47a6a8f67fdc2c1ca5d2f1840ce5d7
