### ISSUE TITLE
Nukkit support again (maybe PowerNukkit_X_)

### ISSUE THREAD

**Issue by IndianBartonka** [IntellectualSites/PlotSquared#4065]
### What feature do you want to see added?

I like this plugin and i usually using nukkit

### Are there any alternatives?

Idk

**Comment by Scot-Survivor** [comment]
Doesn't the Nukkit API almost completely mirror the bukkit api?

**Comment by NotMyFault** [comment]
Duplicate of https://github.com/IntellectualSites/PlotSquared/issues/3326
