### ISSUE TITLE
PlayerMoveEvent

### ISSUE THREAD

**Issue by dextonanderson** [IntellectualSites/PlotSquared#407]
Spigot version: 1.8.7 latest
PS version: 2.12.8
My console has been spamming this http://paste.ubuntu.com/11881129/

**Comment by boy0001** [comment]
Update to 2.12.9

**Comment by dextonanderson** [comment]
This seems to have been fixed.

**Comment by boy0001** [comment]
Eh.. looks like I named it wrong on spigot... Anyway, here it is:
https://www.spigotmc.org/resources/plotsquared.1177/download?version=34178
