### ISSUE TITLE
Plotsquared does not want to start with § in message

### ISSUE THREAD

**Issue by NurFabi** [IntellectualSites/PlotSquared#4076]
### Server Implementation

Paper

### Server Version

1.20

### Describe the bug

Plotsquared does not want to load when in the greeting and farewell flag are "§".

### To Reproduce

Update to the newest version from Github
Have "§" in the greeting and farewell flag 

### Expected behaviour

Plotsquared shuld start

### Error log (if applicable)

https://paste.gg/p/anonymous/77f996453558495ca5c20769afdfb453

### Plot Debugpaste

plugin is disabled

### PlotSquared Version

PlotSquared version 7.0.0-SNAPSHOT (GitHub commit cbb284b)

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Thanks so much for filing this issue!

I'm not entirely sure, how you ended up with these characters, given you can't type them ingame.
Maybe we should remove them at all if a conversion is not possible, @IntellectualSites/plotsquared-team thoughts?

**Comment by NurFabi** [comment]
Geyser 
PE player can write it in the chat
