### ISSUE TITLE
Error in console after a block placed

### ISSUE THREAD

**Issue by ZeTProF** [IntellectualSites/PlotSquared#4088]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

I created a /plot area single
I went to change the maximum height of this area from the config file, and as soon as I placed a block above this limit where everyone could place all these errors appeared, of course they reappear every time I place another block.

I also want to point out another bug where the /plot area is single
needs a reload or a restart as it does not make the claim

### To Reproduce

/plot area single 
another person has to claim it, I haven't tested if it works for me
create an area and change the the height limit
placing a cube above the limit where everyone can build will give this error repeating with each block placed

### Expected behaviour

i dont know, i think no error in console

### Screenshots / Videos

![NfCoGUG](https://github.com/IntellectualSites/PlotSquared/assets/136644589/3dfaf781-92e1-47cf-9519-9f3db4de11a1)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/9d6798dd9fd542c9afa7a9d2942a11ae

### PlotSquared Version

PlotSquared v7.0.0-RC.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

I also want to point out another bug where the /plot area is single
needs a reload or a restart as it does not make the claim

**Comment by NotMyFault** [comment]
I already fixed that in https://github.com/IntellectualSites/PlotSquared/commit/e2ba93dab9b7ccbb46686f0f7d43ff9074d0e1cd
