### ISSUE TITLE
[Suggestion] No edit sign although "use: #signs".

### ISSUE THREAD

**Issue by Luke2206** [IntellectualSites/PlotSquared#4089]
### What feature do you want to see added?

Hello, I use a Chestshop plugin and Plotsquared on my server.
For the Chestshop plugin, I need to have the flag "use: #signs" set.
But now in 1.20 you can edit signs by clicking on them.
Now anyone can edit signs on any plot, which I don't like.
 That's why I would suggest adding a setting where you can decide what you can do with the flag "use: #signs", e.g. "click on it, change text, change colour, glowing..." or add another flag that is called "edit: signs", for example, with which you can then decide whether you can colour, edit etc. signs. 

I think many people also use a Chestshop plugin and PS and are currently confronted with the same problem.

### Are there any alternatives?

Disable sign edit through another plugin -> But many players want to edit signs

remove "use: #signs" -> many players cannot use the Chestshop plugin

Write to the dev of Chestshop Plugin so that he adds PS support -> could take a long time and in the meantime I lose players, because a) I can't use any shops or b) you can't edit any signs.

### Anything else?

-

**Comment by NotMyFault** [comment]
> But now in 1.20 you can edit signs by clicking on them.
Now anyone can edit signs on any plot, which I don't like.

Given the information provided, I'm unable to replicate that. Signs have been protected perfectly fine in my test case.

**Comment by DevJoey** [comment]
Signs are not protected if use #signs flag is set.
