### ISSUE TITLE
I cant create a plotworld

### ISSUE THREAD

**Issue by janbedplasser** [IntellectualSites/PlotSquared#409]
If i try to create a plotworld i cant, i spawn in a normal overworld. I did try this with MultiVerse. Can you help me? I cant find other topics or something about this problem.

**Comment by EvilOlaf** [comment]
Without any further information no.
Bukkit/Spigot version?
PS version?
Configuration files?
Used commands?
Console output?

We need this stuff to investigate your issue further. Most likely related to misconfiguration.

**Comment by LaxWasHere** [comment]
You are probably trying to make the main world a plot world, please follow these steps https://github.com/IntellectualSites/PlotSquared/wiki/Manual-generator-setting

**Comment by boy0001** [comment]
As stated by the gentlemen :
> Bukkit/Spigot version?
> PS version?
> Configuration files?
> Used commands?
> Console output?

Also try:
> https://github.com/IntellectualSites/PlotSquared/wiki/Manual-generator-setting

This will be closed unless more information is provided.
