### ISSUE TITLE
cannot claim plot if you are deoped

### ISSUE THREAD

**Issue by 1mIz** [IntellectualSites/PlotSquared#4091]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

When someone who does not have op commands does /p claim, it says you have reached your maximum amount of plots: 0. is there something in the config about this? i dont think that i have changed anything major in the config.

### To Reproduce

/p claim

### Expected behaviour

When i do /p claim it should say i claimed a plot but instead it says i reached my maximum amount of plots 0

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/de30d536e66a49e2bd5826c24135d26d

### PlotSquared Version

7.0.0-RC.2-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by dordsor21** [comment]
Read the wiki for commands https://intellectualsites.github.io/plotsquared-documentation/commands.html
