### ISSUE TITLE
flag error spigot 1.8.7

### ISSUE THREAD

**Issue by yzz17** [IntellectualSites/PlotSquared#410]
15.07 18:26:53 [Server] INFO ... 15 more
15.07 18:26:53 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[custom.jar:git-Spigot-f928e7a-e91aed8]
15.07 18:26:53 [Server] INFO at com.intellectualcrafters.plot.commands.BukkitCommand.onCommand(BukkitCommand.java:27) ~[?:?]
15.07 18:26:53 [Server] INFO at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:171) ~[?:?]
15.07 18:26:53 [Server] INFO at com.intellectualcrafters.plot.commands.FlagCmd.execute(FlagCmd.java:211) ~[?:?]
15.07 18:26:53 [Server] INFO at com.intellectualcrafters.plot.listeners.PlotListener.plotEntry(PlotListener.java:123) ~[?:?]
15.07 18:26:53 [Server] INFO Caused by: java.lang.NullPointerException
15.07 18:26:53 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
15.07 18:26:53 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [custom.jar:git-Spigot-f928e7a-e91aed8]
15.07 18:26:53 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [custom.jar:git-Spigot-f928e7a-e91aed8]
15.07 18:26:53 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [custom.jar:git-Spigot-f928e7a-e91aed8]
15.07 18:26:53 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [custom.jar:git-Spigot-f928e7a-e91aed8]
15.07 18:26:53 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [custom.jar:git-Spigot-f928e7a-e91aed8]
15.07 18:26:53 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_75]
15.07 18:26:53 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_75]
15.07 18:26:53 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [custom.jar:git-Spigot-f928e7a-e91aed8]
15.07 18:26:53 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [custom.jar:git-Spigot-f928e7a-e91aed8]
15.07 18:26:53 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [custom.jar:git-Spigot-f928e7a-e91aed8]
15.07 18:26:53 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970) [custom.jar:git-Spigot-f928e7a-e91aed8]
15.07 18:26:53 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135) [custom.jar:git-Spigot-f928e7a-e91aed8]
15.07 18:26:53 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642) ~[custom.jar:git-Spigot-f928e7a-e91aed8]
15.07 18:26:53 [Server] INFO at us.Myles.PWP.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:95) ~[?:?]
15.07 18:26:53 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[custom.jar:git-Spigot-f928e7a-e91aed8]
15.07 18:26:53 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'p' in plugin PlotSquared v2.12.8
15.07 18:26:53 [Server] INFO [18:26:53 ERROR]: null
15.07 18:26:48 [Multicraft] Skipped 26 lines due to rate limit (30/s)
15.07 18:26:30 [Server] INFO Could not pass event PlayerMoveEvent to PlotSquared v2.12.8
15.07 18:26:30 [Server] INFO [18:26:30 ERROR]: **** THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS ****
15.07 18:26:29 [Server] INFO ... 17 more
15.07 18:26:29 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[custom.jar:git-Spigot-f928e7a-e91aed8]
15.07 18:26:29 [Server] INFO at com.intellectualcrafters.plot.commands.BukkitCommand.onCommand(BukkitCommand.java:27) ~[?:?]
15.07 18:26:29 [Server] INFO at com.intellectualcrafters.plot.commands.MainCommand.onCommand(MainCommand.java:171) ~[?:?]
15.07 18:26:29 [Server] INFO at com.intellectualcrafters.plot.commands.FlagCmd.execute(FlagCmd.java:211) ~[?:?]
15.07 18:26:29 [Server] INFO at com.intellectualcrafters.plot.listeners.PlotListener.plotEntry(PlotListener.java:123) ~[?:?]
15.07 18:26:29 [Server] INFO Caused by: java.lang.NullPointerException
15.07 18:26:29 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
15.07 18:26:29 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [custom.jar:git-Spigot-f928e7a-e91aed8]
15.07 18:26:29 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [custom.jar:git-Spigot-f928e7a-e91aed8]
15.07 18:26:29 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [custom.jar:git-Spigot-f928e7a-e91aed8]
15.07 18:26:29 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726) [custom.jar:git-Spigot-f928e7a-e91aed8]
15.07 18:26:29 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [custom.jar:git-Spigot-f928e7a-e91aed8]
15.07 18:26:29 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [custom.jar:git-Spigot-f928e7a-e91aed8]
15.07 18:26:29 [Server] INFO at com.gmail.filoghost.chestcommands.task.ExecuteCommandsTask.run(ExecuteCommandsTask.java:21) [ChestCommands.jar:?]
15.07 18:26:29 [Server] INFO at com.gmail.filoghost.chestcommands.internal.icon.ExtendedIcon.onClick(ExtendedIcon.java:244) [ChestCommands.jar:?]
15.07 18:26:29 [Server] INFO at com.gmail.filoghost.chestcommands.api.Icon.onClick(Icon.java:319) [ChestCommands.jar:?]
15.07 18:26:29 [Server] INFO at com.gmail.filoghost.chestcommands.internal.CommandsClickHandler.onClick(CommandsClickHandler.java:34) [ChestCommands.jar:?]
15.07 18:26:29 [Server] INFO at com.gmail.filoghost.chestcommands.internal.icon.command.OpIconCommand.execute(OpIconCommand.java:17) [ChestCommands.jar:?]
15.07 18:26:29 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.chat(CraftPlayer.java:242) [custom.jar:git-Spigot-f928e7a-e91aed8]
15.07 18:26:29 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1051) [custom.jar:git-Spigot-f928e7a-e91aed8]

**Comment by yzz17** [comment]
don´t work in new plots

**Comment by boy0001** [comment]
Fixed, please update to the latest version on spigot.
