### ISSUE TITLE
Error on PlayerQuitEvent

### ISSUE THREAD

**Issue by JasonHorkles** [IntellectualSites/PlotSquared#4101]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

When a player leaves the server, an error pops up on newer versions of Paper

### To Reproduce

1. Ensure Paper is up to date
2. Join the server
3. Leave the server

### Expected behaviour

There shouldn't be an error

### Error log (if applicable)

Last lines in debug paste

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/75c7bef8bafd4a969f47472db17b5319

### PlotSquared Version

7.0.0-RC.2-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

git-Paper-64 (MC: 1.20.1)

**Comment by SirYwell** [comment]
As this happens in Paper code, I assume there's a bug in that Paper build

**Comment by JasonHorkles** [comment]
Yep looks like you're right, thanks
