### ISSUE TITLE
Introduction of a Plot Entity Limit

### ISSUE THREAD

**Issue by Luke2206** [IntellectualSites/PlotSquared#4103]
### What feature do you want to see added?

**Introduction of a Plot Entity Limit**
A Plot Entity Limit is an important feature that should be implemented in PlotSquared to address various issues related to entities. Here are reasons why such a limit should be introduced:

1. Lag Reduction: Players often cause significant lag by placing too many entities in a confined area. This can greatly impact server performance and negatively affect the gameplay experience. By introducing a Plot Entity Limit, server administrators can set the maximum number of entities allowed on a specific plot. This ensures that the number of entities remains at an acceptable level, avoiding unnecessary lag.

2. Avoidance of Third-Party Plugins: Without an integrated entity limit, server administrators would have to rely on third-party plugins to restrict the number of entities. This can lead to compatibility issues, security risks, and additional maintenance. By providing a built-in function for limiting entities, the need for such plugins is eliminated, simplifying server administration and enabling better control over the game environment.

3. Configurability through PlotSquared's Config: To minimize administrative effort, the entity limit should be adjustable through the Config. This allows for easy customization of the limits to meet the specific requirements of the server, offering a more flexible solution compared to using flags or other cumbersome methods. Configurability ensures that the entity limit aligns with the server's individual needs and can be easily adjusted as required.
 
Additionally, it is beneficial to introduce a command that allows players to check the number of entities on a plot. An example of such a command would be "/plot entities". This command would display to players the current number of entities on their plot, as well as the maximum number set in the Config. This provides transparency to players and allows them to plan and manage their building projects in accordance with the applicable limits.

Overall, the introduction of a Plot Entity Limit would be advantageous as it improves server performance, reduces the need for third-party plugins, and enables user-friendly configuration. By combining this feature with a command to check entity count, both server administrators and players can benefit from a smoother and optimized gameplay experience.

Also, it would be good if the limit per merge expands. 

And this system should replace the current plot caps system. This currently only works with plot flags.

### Are there any alternatives?

Already tried the P Caps via the flags. But this is stupid because the entitys remain the same, e.g. with a 10x10 merge. This is a disadvantage for large plots, so to speak.

**Comment by NotMyFault** [comment]
A likewise functionality already exists with the entity cap flag. Adding another functionality superseding the existing flag is not planned.
