### ISSUE TITLE
TagResolver / sendMessage problem

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/PlotSquared#4104]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

With using `/p trust <same player = plot owner>` on my own plot, I down't get a message.

[/Core/src/main/java/com/plotsquared/core/command/Trust.java#L115-L121](https://github.com/RedstoneFuture/PlotSquared/blob/587a286d05dad11e4d2a1a2280819e62ee258627/Core/src/main/java/com/plotsquared/core/command/Trust.java#L115-L121)
```java
                        player.sendMessage(
                                TranslatableCaption.of("member.already_added"),
                                TagResolver.resolver(
                                        "value",
                                        Tag.inserting(PlayerManager.resolveName(uuid).toComponent(player))
                                )
                        );
```

Maybe the TagResolver has a problem.

Same with `/p trust <same player = plot owner>` and `/p add <already added player>`, `/p trust <already trusted player>`, `/p ban <already banned player>`.

### To Reproduce

1. Get a plot.
2. `/p trust <your name>`

### Expected behaviour

Message: "member.already_added"

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/9dcdad83acbb44e8820ad964447bbbd0

### PlotSquared Version

PlotSquared v7.0.0-SNAPSHOT

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
#resolveName(uuid).toComponent(player) can't be used like that, if you want to file a PR.
