### ISSUE TITLE
CMI IC (Interactive Commands) asFakeOp! blocked by Plotsquared

### ISSUE THREAD

**Issue by AnimeDrache** [IntellectualSites/PlotSquared#4107]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

(AWARE: I use a previous version but I doubt the new version will fix it. please correct me if I am wrong. sorry for the circumstances)

When you create an interactive sign of the plugin CMI, it WON'T work if you try to make it a "asFakeOP!" command (so the command thinks you are an OP). Normally it does work. It also does work "asconsole!" or "asPlayer!".

Please check the attachment (screenshot)

### To Reproduce

1. Install Plotsquared
2. Install CMI (Premium Plugin)
3. Place a sign
4. Look at it
5. use "/cmi ic new NAME" to create a new interactive sign
6. Click "!" to add a new command
7. add for example "asFakeOp! weather sun world" to it
8. right click the sign to use the command
9. No result but a huge error message in the console

### Expected behaviour

Interactive signs should work

### Screenshots / Videos

https://prnt.sc/2z5GNUFfy2jI

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/74ca3cd481bf46e9b777bf10d33e6f41

### PlotSquared Version

plotsquared-bukkit-7.0.0-RC.2-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by TheMeinerLP** [comment]
Nothing is blocked from plotsquared but `ffffffff-ffff-ffff-ffff-fffffffffff0` isn't a real UUID

**Comment by TheMeinerLP** [comment]
For ref: https://github.com/Zrips/CMI/issues/7950 and duplicated

**Comment by NotMyFault** [comment]
PlotSquared supports the same UUID formats Mojang supports. Plugins using arbitrary syntax diverging from the standard are advised to use Mojang's pattern.

**Comment by AnimeDrache** [comment]
The latest CMI update did fix it! I still don't really understand the half of the things you said guys, but as a user I can clearly say: I can use CMI IC on plotsquared and everywhere else with fakeop command now without an error message plus it does work! ♥ Case closed hehe!
