### ISSUE TITLE
Basic permission pack: plots.permpack.basic does not work?

### ISSUE THREAD

**Issue by justLxy** [IntellectualSites/PlotSquared#4109]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

I added the permissions plots.permpack.basic, but it says I'm missing the permissions node within this package, even as a OP.
<img width="657" alt="image" src="https://github.com/IntellectualSites/PlotSquared/assets/66059161/f2c8edd6-4ddb-40b6-8ad0-46ef800aea8d">

### To Reproduce

Use Groupmanager to add the permission to the group.
input /plot info or /plot home or /plot visit or something.

### Expected behaviour

it works.

### Screenshots / Videos

<img width="657" alt="image" src="https://github.com/IntellectualSites/PlotSquared/assets/66059161/c2fe4b06-5040-42d7-885c-71b1e11ad521">

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/30a6e357e98d416f9dc45f4cfb684683

### PlotSquared Version

PlotSquared 7.0.0 RC.2

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
> even as a OP.

Either you use a permission management plugin _or_ op levels, you don't use both at the same time. Also, use LuckPerms.
