### ISSUE TITLE
File too big?

### ISSUE THREAD

**Issue by Cronuside12** [IntellectualSites/PlotSquared#411]
![screenshot_5](https://cloud.githubusercontent.com/assets/13354368/8706317/1a3d4c5a-2b27-11e5-944c-ef9ce647b1a8.png)

**Comment by Cronuside12** [comment]
It says that the max file size that can be uploaded is 2mb, And the "PlotSquared" file is only 1.08mb.

**Comment by boy0001** [comment]
Um, context? What are you trying to do exactly and how is this something we can fix?

**Comment by Sauilitired** [comment]
This is not caused by us, but rather your nginx settings.
