### ISSUE TITLE
Redstone flag does not take redstone blocks and pistons into consideration

### ISSUE THREAD

**Issue by Folas1337** [IntellectualSites/PlotSquared#4115]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

If I turn off redstone in a plot by using `/plot flag set redstone false` I can still use a contraption like the following to make redstone kind of work:
![image](https://github.com/IntellectualSites/PlotSquared/assets/39222968/3682bb94-12ff-4cc7-bf65-5e120739ee51)
 

### To Reproduce

1. Get on a plot
2. Use `/plot flag set redstone false`
3. Build the following contraption: ![image](https://github.com/IntellectualSites/PlotSquared/assets/39222968/03f955ad-10d9-42eb-bdc5-923dd80344c5)
4. Place down the lowest redstone block or remove it to cause the pistons to extend and unextend.

### Expected behaviour

The pistons should simply ignore the redstone input from the redstone blocks.

### Screenshots / Videos

![image](https://github.com/IntellectualSites/PlotSquared/assets/39222968/e90d8eff-bf85-4629-9a1d-d267a68062dd)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/3c17557b7a2b43d394887707bebf5253

### PlotSquared Version

7.0.0-RC.2-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
The redstone flag covers repeates only.
