### ISSUE TITLE
Unable to place armorstands after updating to 7.0.0 RC.3

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/PlotSquared#4120]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

I have no plot flags set for this test

In 7.0.0 RC.2 I'm able to place armorstands:
![2023-07-23_10 29 33](https://github.com/IntellectualSites/PlotSquared/assets/10485646/b12b052e-fbf5-4f94-aaed-e934e189cc9e)
Debugpaste: https://athion.net/ISPaster/paste/view/ba059996a2b74769bc61ad4e42dfbace

After updating to 7.0.0 RC.3 I'm no longer able to place armorstands, there is no feedback in chat: 
![2023-07-23_10 31 22](https://github.com/IntellectualSites/PlotSquared/assets/10485646/ea226fc6-4aef-4d86-8a35-5e9e541d17b2)
Debugpaste: https://athion.net/ISPaster/paste/view/bb1d351988d1447a9c21a3ca44478547

### To Reproduce

1. Update to 7.0.0 RC.3 and try to place armorstands

### Expected behaviour

Armorstands should be placed

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/bb1d351988d1447a9c21a3ca44478547

### PlotSquared Version

7.0.0 RC.3

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Is caused by https://github.com/IntellectualSites/PlotSquared/pull/4110
