### ISSUE TITLE
PlotSquared 7.0.0 not working on 1.16.5

### ISSUE THREAD

**Issue by Sebasee009** [IntellectualSites/PlotSquared#4122]
### Server Implementation

Paper

### Server Version

1.16.5

### Describe the bug

This version 7.0.0 cannot start on MC Version 1.16.5.

### To Reproduce

1. Start server
2. see error in console and not started

### Expected behaviour

This version 7.0.0 no problem started in MC version 1.16.5.

### Screenshots / Videos

![image](https://github.com/IntellectualSites/PlotSquared/assets/14842479/27f63eb0-b7eb-4aa7-8966-df083e586f3d)

### Error log (if applicable)

https://gist.github.com/Sebasee009/6a4570ae2f03966be8ccd4cf048caae9

### Plot Debugpaste

internal error

### PlotSquared Version

PlotSquared-7.0.0-rc.3-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
PlotSquared didn't load, because FAWE didn't load, but FAWE doesn't support 1.16.5 anymore. You should update.
