### ISSUE TITLE
PostPlotMerveEvent does not return list of merged plots

### ISSUE THREAD

**Issue by Ciph3r-Zer0** [IntellectualSites/PlotSquared#4125]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

When Using the API I noticed out of 3 possible merge events only PlotAutoMergeEvent has a list of merged plots, but that event does not fire when you merge plots with invites.

### To Reproduce

Just import the API and try the 3 possible merge events "PlotAutoMergeEvent", "PlotMergeEvent" and  "PostPlotMergeEvent".
None of them exept for the Auto merge event has the list plot merged plots.

### Expected behaviour

PostPlotMergeEvent and/or PlotMergeEvent should contain the list of plots that are getting merged together

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/554b1efd8ec74b5cad94d2b642f57346

### PlotSquared Version

PlotSquared-Core version 1.34

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by dordsor21** [comment]
post merge is after the merge. Giving a list of plots would suggest that an operation can be completed on each individually. All the plots in a merge can be obtained by getting a plot's connected plots through Plot#getConnectedPlots
