### ISSUE TITLE
%plotsquared_currentplot_owner% Placeholder is gray

### ISSUE THREAD

**Issue by GBrayJ** [IntellectualSites/PlotSquared#4135]
### Server Implementation

Spigot

### Server Version

1.20.1

### Describe the bug

The placeholder '%plotsquared_currentplot_owner%' is gray even when used with §f. No other placeholder exerts this behavior.

### To Reproduce

1) Use Placeholder '%plotsquared_currentplot_owner%'

### Expected behaviour

'§f%plotsquared_currentplot_owner%' Should make the owner white.

### Screenshots / Videos

![issueA](https://github.com/IntellectualSites/PlotSquared/assets/39144059/2a3a6008-297b-48be-9786-558b2bfe1b5d)
![issueB](https://github.com/IntellectualSites/PlotSquared/assets/39144059/bea69467-c015-4565-af6d-df717d5a2d3d)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/bb74725df129453f8b6021efe323a85c

### PlotSquared Version

PlotSquared version 7.0.0-rc.4-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

I added the newest build, I don't know why it says RC-3.

**Comment by NotMyFault** [comment]
You can customize the style and colors of messages in the messages_%.json using MiniMessage: https://docs.advntr.dev/minimessage/format.html
