### ISSUE TITLE
ChestShop use sign flag allows griefing (editing) of signs on all plots

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#4137]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

If i have a ChestShop plugin, plotsquared cancels sign clicks. So i have to set the use sign flag. But setting this will also allow all players to edit any sign. 

### To Reproduce

1. Claim a plot
2. PLace a chestshop
3. Set use-sign flag

### Expected behaviour

Signs should be clickable but not editable on plots where you dont have trust/add

Solution:
Add a possibility to make signs clickable who have a PersistentDataContainer tag e.g. "plotsquared_clickable". So i as a chestshop developer can add this PersistentDataTag to my chestshop-signs allowing them to be clickable. But other signs (normal signs) do not have this tag, so there are not clickable/editable.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/d4376a52478549b5a97923b73bf07dee

### PlotSquared Version

7.0.0-rc.4-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by DevJoey** [comment]
Signs are not protected if i set the sign use flag 

Please reopen!

**Comment by NotMyFault** [comment]
> Signs are not protected if i set the sign use flag
> 
> Please reopen!

More information is needed to replicate the issue.

**Comment by DevJoey** [comment]
Claim a plot
Write a sign
Set /p flag set use #signs
Use a player with no perms at all an right-click a sign
Now the sign-editor opens (Minecraft built-in feature) and you can edit every players signs

**Comment by SirYwell** [comment]
I think the problem is that *unrelated* signs aren't protected. Chest signs are protected by the chest shop plugin, but others aren't.

**Comment by NotMyFault** [comment]
> I think the problem is that _unrelated_ signs aren't protected. Chest signs are protected by the chest shop plugin, but others aren't.

Why would you think so? `ChestShop use sign flag allows griefing (editing) of signs on all plots` clearly implies this issue covers [the official](https://dev.bukkit.org/projects/chestshop) ChestShop plugin only.

Anything else would be a separate issue, requiring a much more detailed setup to reproduce.

**Comment by DevJoey** [comment]
No i mean normal signs. The signs of the shop are protected by the interact event of the shop plugin. I mean normal signs placed by a player.

**Comment by DevJoey** [comment]
Place a normal sign on the plot with the shop. And then a normal player can edit this sign

**Comment by DevJoey** [comment]
Ich schreib das jetzt auf Deutsch, da kann ich mich besser ausdrücken.

Damit Spieler auf fremden Plots in einem ChestShop einkaufen können, muss die use #signs Flag aktiviert sein. Aktiviere ich jedoch diese Flag, kann jeder Spieler alle Schilder die sonst noch auf meinem Plot rumstehen bearbeiten.

**Comment by DevJoey** [comment]
Gibt es schon Neuigkeiten hierzu?
