### ISSUE TITLE
Plot merge road bug

### ISSUE THREAD

**Issue by Theepwner** [IntellectualSites/PlotSquared#414]
After merging 4 plots to create a big square, the original areas where the roads were are still clearing mobs. (kill_road_mobs feature).

**Comment by Sauilitired** [comment]
Does the big only exist when there are 4 plots in the merge, or even with 2?

**Comment by Theepwner** [comment]
Haven't been able to test that yet. But just looking at my spawn with 4 merged plots, it happens.

**Comment by Theepwner** [comment]
Tried out with 2, issue still exists.

**Comment by Theepwner** [comment]
And I feel this issue is somewhat new; I don't remember this bug always existing.
