### ISSUE TITLE
plot clear not working, "A set block timer is bound to either the current plot or you. Please wait for it to finish."

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/PlotSquared#4141]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

Players have been complaining that `/plot clear` is not working so I tried it myself and got the error: "A set block timer is bound to either the current plot or you. Please wait for it to finish."

Server thread dump: https://www.dropbox.com/scl/fi/swrgf93jz2883vss301fr/plot-clear.tdump?rlkey=z35tl8fkw8ekalbc8t1odl2xp&dl=1

Fawe threads: https://pastebin.com/hhAwGzFL

### To Reproduce

1. Not sure

### Expected behaviour

Plot clear should work

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/ece93b6e4ec445559a4b572e8bb13777

### PlotSquared Version

plotsquared-bukkit-7.0.0-rc.4-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
@SecretlyJealous Your plot debugpaste shows rc3, but you told it's rc4, please update Plotsquared and if possible, it would be nice to see how you got the error / or the error message in game.

**Comment by SecretlyJealous** [comment]
> @SecretlyJealous Your plot debugpaste shows rc3, but you told it's rc4, please update Plotsquared and if possible, it would be nice to see how you got the error / or the error message in game.

I am on rc4 but debugpaste says it's rc3, you can also see this with new issues - for example: https://github.com/IntellectualSites/PlotSquared/issues/4143

This is the error after using `/plot clear`: ![Untitled](https://github.com/IntellectualSites/PlotSquared/assets/10485646/50840106-57a2-4d95-b25d-bd8b59c72887)

**Comment by RedstoneFuture** [comment]
"Plot clear should work"
It basically works in the latest version. It should not cause any problems after a restart at the latest.
Tested with `PlotSquared v7 7.2.0`.

Maybe there was a particular situation that caused a problem for you, but that is very difficult to replicate. If you find a way to replicate this clearly, you are welcome to describe it here.

**Comment by SecretlyJealous** [comment]
I have not had this issue come up for a couple of months now so I will close this issue
