### ISSUE TITLE
/plot delete Command resets 1 Block to low when a plot.schem is in use

### ISSUE THREAD

**Issue by justin0-0** [IntellectualSites/PlotSquared#4142]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

/plot delete Command resets 1 Block to low when a plot.schem is in use.

### To Reproduce

Create a fresh Plotworld. With Plot width 84 and set a plot.schem.
<img width="389" alt="image" src="https://github.com/IntellectualSites/PlotSquared/assets/61631935/d991c864-ec30-4286-9cd0-8341c8577904">

Claim a Plot that generated with the new Schematic and then user /plot delete

Then the Plot gets deleted and the Schematic replaced but one block to low. But it gets generated normaly
![2023-08-13_16 24 39](https://github.com/IntellectualSites/PlotSquared/assets/61631935/9833f59f-6267-4c29-ba84-77150e995ba5)
![2023-08-13_16 25 02](https://github.com/IntellectualSites/PlotSquared/assets/61631935/32859505-7bfb-4db3-b858-41b2deadb3aa)

### Expected behaviour

Generate 1 Block higher like normal

### Screenshots / Videos

Heres the Bug shown in a Youtube Video
https://www.youtube.com/watch?v=u-iJt0pv6bk

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/14df13299b5e474faa429aa065c927d3

### PlotSquared Version

Plotsquared 7.0.0

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by dordsor21** [comment]
This should be fixed
