### ISSUE TITLE
Cannot assign plot after setting default world

### ISSUE THREAD

**Issue by docimin** [IntellectualSites/PlotSquared#4143]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

After you create a plotworld using /plot setup, /plot auto works fine.
However, after you stop the server, set the server.properties & bukkit.yml so the plotworld is the default world, /plot auto does not work anymore.

### To Reproduce

1. Create a plotworld using /plot setup
2. Stop Server
3. Change server.properties & bukkit.yml so it's a default world
4. Start Server
5. do /plot auto

### Expected behaviour

It's able to assign you a plot using /plot auto

### Error log (if applicable)

N/A

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/27526e2fd41242b6b0962b574c66db64

### PlotSquared Version

7.0.0-rc.4-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

Discord context: https://canary.discord.com/channels/268444645527126017/699650993377378394/1140335409528848494

## Additional info:
You can make it work again by creating a vanilla world and making that the default world, it's almost like plotsquared does not work correctly when being the default world.

**Comment by OneLiteFeather** [comment]
@docimin Not sure if you can use a different permission plugin such as Luckperms or use the console to /plot auto yourself instead. There are some errors on your permission plugin and it would be good to look sort out if that might be related to your problem.

**Comment by docimin** [comment]
> @docimin Not sure if you can use a different permission plugin such as Luckperms or use the console to /plot auto yourself instead. There are some errors on your permission plugin and it would be good to look sort out if that might be related to your problem.

Hey,

As I said before, it works fine when the world **is not set as default**. The moment you set it as default, /plot auto does not work anymore.

**Comment by SirYwell** [comment]
I cannot reproduce this at the moment. Can you try reproducing it with only FAWE and PlotSquared?

**Comment by RedstoneFuture** [comment]
I have no problems with the correct configuration in `bukkit.yml`. `/p auto` teleport me to a new plot in the world `PS_Test-2`, if I am already in it.

Tested with `PlotSquared v7 7.2.0`.

**server.properties**
```
level-name=PS_Test-2
```

**bukkit.yml**
```
worlds:
  PS_Test-2:
    generator: PlotSquared
```

**Comment by RedstoneFuture** [comment]
@docimin Would you like to re-test it with the newest version of FAWE & PS and without `UltraCustomizer.jar`, please?

It sends an exception:
```
[19:26:48] [Server thread/WARN]: java.lang.IllegalArgumentException: location.world
[19:26:48] [Server thread/WARN]: 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
[19:26:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.teleport(CraftPlayer.java:1321)
[19:26:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.teleport(CraftPlayer.java:1253)
[19:26:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.entity.CraftEntity.teleport(CraftEntity.java:568)
[19:26:48] [Server thread/WARN]: 	at com.eazyftw.ucplayeraddon.elements.PlayerTeleport.run(PlayerTeleport.java:71)
[19:26:48] [Server thread/WARN]: 	at UltraCustomizer.jar//me.TechsCode.UltraCustomizer.scriptSystem.objects.Child.run(Child.java:46)
[...]
```

**Comment by docimin** [comment]
I'm currently very busy with a lot of projects, so it might be a while. Sorry for the wait.

**Comment by PierreSchwang** [comment]
No response for over half a year - closing
