### ISSUE TITLE
Unhandled exception executing command 'p' in plugin PlotSquared v2.11.26

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/PlotSquared#415]
Pastebin error: http://pastebin.com/MPrEEpJ0

**Comment by EvilOlaf** [comment]
You added a `\` at the end of the nick which caused the exception:
`Caused by: java.lang.IllegalArgumentException: character to be escaped is missing`
Could be catched anyways.

**Comment by boy0001** [comment]
Could you please update the plugin and verify if it's still an issue?

**Comment by boy0001** [comment]
Fixed for next version
