### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by LordVardus** [IntellectualSites/PlotSquared#4150]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

24.08 01:17:47 [Server] INFO [PlotSquared] Enabling PlotSquared v7.0.0-Premium
24.08 01:17:48 [Server] ERROR Error occurred while enabling PlotSquared v7.0.0-Premium (Is it up to date?)
24.08 01:17:48 [Server] INFO java.lang.NoSuchMethodError: 'com.google.common.collect.ImmutableMap com.google.common.collect.ImmutableMap$Builder.buildOrThrow()'
24.08 01:17:48 [Server] INFO at com.plotsquared.google.internal.MoreTypes.<clinit>(MoreTypes.java:61) ~[PlotSquared-7.0.0.jar:?]
24.08 01:17:48 [Server] INFO at com.plotsquared.google.TypeLiteral.getSuperclassTypeParameter(TypeLiteral.java:98) ~[PlotSquared-7.0.0.jar:?]
24.08 01:17:48 [Server] INFO at com.plotsquared.google.TypeLiteral.<init>(TypeLiteral.java:75) ~[PlotSquared-7.0.0.jar:?]
24.08 01:17:48 [Server] INFO at com.plotsquared.core.player.PlayerMetaDataKeys$1.<init>(PlayerMetaDataKeys.java:34) ~[PlotSquared-7.0.0.jar:?]
24.08 01:17:48 [Server] INFO at com.plotsquared.core.player.PlayerMetaDataKeys.<clinit>(PlayerMetaDataKeys.java:34) ~[PlotSquared-7.0.0.jar:?]
24.08 01:17:48 [Server] INFO at com.plotsquared.core.PlotSquared.<init>(PlotSquared.java:174) ~[PlotSquared-7.0.0.jar:?]
24.08 01:17:48 [Server] INFO at com.plotsquared.bukkit.BukkitPlatform.onEnable(BukkitPlatform.java:269) ~[PlotSquared-7.0.0.jar:?]
24.08 01:17:48 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-411]
24.08 01:17:48 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-411]
24.08 01:17:48 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-411]
24.08 01:17:48 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-411]
24.08 01:17:48 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-411]
24.08 01:17:48 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[patched_1.17.1.jar:git-Paper-411]
24.08 01:17:48 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-411]
24.08 01:17:48 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]
24.08 01:17:48 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
24.08 01:17:48 [Server] INFO [PlotSquared] Disabling PlotSquared v7.0.0-Premium
24.08 01:17:48 [Server] ERROR [PlotSquared/PlotSquared] Could not close database connection
24.08 01:17:48 [Server] INFO java.lang.NullPointerException: Cannot invoke "com.plotsquared.core.util.EventDispatcher.unregisterAll()" because "this.eventDispatcher" is null
24.08 01:17:48 [Server] INFO at com.plotsquared.core.PlotSquared.disable(PlotSquared.java:1227) ~[PlotSquared-7.0.0.jar:?]
24.08 01:17:48 [Server] INFO at com.plotsquared.bukkit.BukkitPlatform.onDisable(BukkitPlatform.java:730) ~[PlotSquared-7.0.0.jar:?]
24.08 01:17:48 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.17.1.jar:git-Paper-411]
24.08 01:17:48 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[patched_1.17.1.jar:git-Paper-411]
24.08 01:17:48 [Server] INFO at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[patched_1.17.1.jar:git-Paper-411]

### To Reproduce

error

### Expected behaviour

error 

### Screenshots / Videos

error

### Plot Debugpaste

error

### PlotSquared Version

PlotSquared v7.0.0-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

r

**Comment by NotMyFault** [comment]
If you are looking forward to reporting an issue, please fill out the issue form properly. A stacktrace without any steps to replicate or information about your setup is not beneficial.

**Comment by NotMyFault** [comment]
Can you try to replicate that on 1.20.1, please? 1.17.1 is more than two years old and considered end of life by Mojang.

**Comment by OneLiteFeather** [comment]
Please feel free opening an issue again if you were able to replicate this on 1.20.1 or higher. As there was no more conversation, I'll close this for now.
