### ISSUE TITLE
Add event to prevent concrete powder + water -> concrete

### ISSUE THREAD

**Issue by aurel85** [IntellectualSites/PlotSquared#4156]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

Hi,

When the entity-change-block flag is false, concrete powder blocks should not change to concrete but this is currently this is what is happening.

Thanks in advance.

### To Reproduce

1. /plot auto
2. /plot flag set entity-change-block false
3. Place concrete_powder with water

### Expected behaviour

Concrete powder must remain concrete powder.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/72a8f346945b4f4295aa474d922decf3

### PlotSquared Version

PlotSquared-7.0.0-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

I tested on a server with only PlotSquared, FAWE and EssentialsX. The same thing is happening.

**Comment by dordsor21** [comment]
This would be better suited to its own flag, like copper oxidation, ice/snow form, etc.
