### ISSUE TITLE
/p music not working?

### ISSUE THREAD

**Issue by Theepwner** [IntellectualSites/PlotSquared#416]
I use /p music and it opens the gui, yet when I click a disc nothing happens; the gui is just closed.

Edit: Errors
http://hastebin.com/muxazoxowo.avrasm

**Comment by Sauilitired** [comment]
`java.lang.NoSuchMethodError: com.intellectualcrafters.plot.listeners.APlotListener.plotEntry`

Are you using an updated version of the plugin?

**Comment by boy0001** [comment]
Please update to the latest version on spigot. The dev builds (which do not always compile correctly) are there for testing, unless we specifically point you towards a build.
