### ISSUE TITLE
Update `#setAgeLock()` and `#getAgeLock` deprecation in `ReplicatingEntityWrapper`

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/PlotSquared#4164]
https://github.com/IntellectualSites/PlotSquared/blob/b7c9453a1ad3bad8cce37487607854e4db535f17/Bukkit/src/main/java/com/plotsquared/bukkit/entity/ReplicatingEntityWrapper.java#L384

instead of calling `Ageable` class, `Breedable` should be used in this method. Make sure to check update casts, if necessary.

https://github.com/IntellectualSites/PlotSquared/blob/b7c9453a1ad3bad8cce37487607854e4db535f17/Bukkit/src/main/java/com/plotsquared/bukkit/entity/ReplicatingEntityWrapper.java#L394

this method requires attention. Given it's public, we can't just change it without causing a breaking API change, which is undesired.
Rather, the method should be deprecated for removal and a new method calling the proper class has to be introduced.
The new introduced method has to replace the deprecated calls in the same class.

**Comment by farukhfrk** [comment]
I'm interested in working on this issue!
