### ISSUE TITLE
Auto update

### ISSUE THREAD

**Issue by boy0001** [IntellectualSites/PlotSquared#417]
Current issue:
 - Reload is unstable
 - Reloading can take long enough to kick all players, 

Other options:
 - Delayed upating (update P^2 when the server is next restarted)
 - Just reload PlotSquared (This requires code to re-register commands)
 - Optimize shut down / initialization of P^2 to speed up reload
 - Do a hard restart
 - Depend on a plugin manager to load P^2 again

**Comment by Sauilitired** [comment]
Best option would be to wait until the server is restarted. Could cause issues if methods are changed and alike (and if stuff aren't loaded into memory).

**Comment by EvilOlaf** [comment]
Agreed with @Sauilitired. Wait for restart is the best option I think.

PlotMe for example catches `/reload` and disables itself. See https://www.spigotmc.org/resources/plotme-official.2131/ under `I am getting an errors after using /reload:`

**Comment by boy0001** [comment]
Well I got to the point where PlotSquared was loadable / unloadble with a plugin manager, it just wasn't too stable.

Oh well, we'll just go with the easier solution of waiting until the next restart.
