### ISSUE TITLE
Plot Auto

### ISSUE THREAD

**Issue by ManoCheating** [IntellectualSites/PlotSquared#4170]
### Server Implementation

Spigot

### Server Version

1.16.5

### Describe the bug

eu fiz a instalação dos plots, coloquei os mapas etc etc.... mas quando vou dar /plot auto no spawn diz me que preciso estar num mundo terrnos e eu queria saber como desativa isso e que dê para dar /plot auto no spawn... podem me ajudar pfv

### To Reproduce

/plot auto, diz que preciso estar num mundo terrenos para executar esse comando

### Expected behaviour

dar /plot auto no spawn ou em qualquer lado sem necessitar de ir para o mundo plots

### Screenshots / Videos

![Captura de ecrã 2023-09-23 125849](https://github.com/IntellectualSites/PlotSquared/assets/85691511/28d58a0d-15a8-4fac-91d0-168af69bd98f)

### Plot Debugpaste

https://www.athion.net/ISPaster/paste/view/480002d9f2e2433291ce813a72153532

### PlotSquared Version

PlotSquared version 19.10.31-7539f6d-783

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

nao

**Comment by SirYwell** [comment]
1.8.8 is not supported.

**Comment by ManoCheating** [comment]
o servidor é na 1.8 mas como ali emcima nas opções nao tem 1.8... qual jar coloco para a 1.8 entao ?

**Comment by PierreSchwang** [comment]
Your only option is to use an up2date and supported version as listed in the bug report template. Any other versions or outdated software by us is not support nor will it ever.
