### ISSUE TITLE
FlightStatus cannot be changed in PlayerLeavePlot.

### ISSUE THREAD

**Issue by ch4ika** [IntellectualSites/PlotSquared#4171]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

With the PlayerLeavePlotEvent, the flight status cannot be changed except for one tick, which means that the player then loses his flight status again.

### To Reproduce

```
  @Subscribe
  public void onPlayerLeavePlotEvent(PlayerLeavePlotEvent event) {
      PlotPlayer<?> player = event.getPlotPlayer();
      player.setFlight(true);
      /*if (PlotAdditions.getInstance().getBoosterManager().isTaskRunning(BoosterType.FLY)) {
          Bukkit.getScheduler().runTask(PlotAdditions.getInstance(), () -> player.setFlight(true));
      }*/
  }
```

### Expected behaviour

With the PlotListener, the event is called first and then all the checks are carried out. The event is called and after it has been called, the flight status of the listener is changed again from PlotSquared.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/9cf64ec3ad774b45a0ba62475ee4077f

### PlotSquared Version

PlotSquared -7.0.0-rc.3

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
Can you replicate this issue with Paper? Also can you update FAWE to 2.7.2 latest and Plotsquared to 7.0.0 Release?

**Comment by ch4ika** [comment]
Yes, it's the same.

**Comment by NotMyFault** [comment]
Would you be interested in filing a pull request to alter the behavior, given you have already identified the issue?
