### ISSUE TITLE
Road templates reset randomly

### ISSUE THREAD

**Issue by stefanJ2BVB** [IntellectualSites/PlotSquared#4172]
### Server Implementation

Paper

### Server Version

1.20

### Describe the bug

For years I have had the same issue with this plugin where at random moments it will reset the road templates and generate new ones, taking from a random plot around spawn.
This causes issues because the plots around spawn do not look like the way the roads do. 

This issue has been plaguing my server for years and has happened with every version of the plugin in recent times. 

![2023-09-23_19 27 42](https://github.com/IntellectualSites/PlotSquared/assets/80390033/f7a7cc56-e0b0-4038-9cbb-d4c0b8854add)
![2023-09-23_19 27 12](https://github.com/IntellectualSites/PlotSquared/assets/80390033/00eba04b-20eb-4c70-95da-5e7500708373)

### To Reproduce

1. generate a world
2. play on the world for a while
3. wait for the road templates to randomly reset
4. have your world ruined

### Expected behaviour

for the road files to never reset. 

### Screenshots / Videos

![2023-09-23_19 27 42](https://github.com/IntellectualSites/PlotSquared/assets/80390033/3f68b620-b14c-4a13-82ed-0f8818e6de25)
![2023-09-23_19 27 12](https://github.com/IntellectualSites/PlotSquared/assets/80390033/a26e980d-5d03-4087-8170-9423aa410c52)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/e4b3d7ba73ae4dbba71e0a5fc7600727

### PlotSquared Version

7.0.0

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
Please update Plotsquared to 7.0.0 Release

**Comment by dordsor21** [comment]
is this using normal road schematics (`/plot createroadschematic`) or from using a plot template to create the world? This has never been reported by anyone else before

**Comment by stefanJ2BVB** [comment]
I made the roads using the normal setup for the plugin. It seems to randomly rewrite the schematic files though causing them to bug out. This issue has happened for at least 2/3 years on 3 different setups with the plugin and on 3 different server hosts so it's not a world specific issue.

**Comment by dordsor21** [comment]
There is only one place that writes those schematics, and it's only called from the `/plot createroadschematic` command. I can't see any way this is possibly something that P2 is doing

**Comment by stefanJ2BVB** [comment]
I can tell you I am not running said command. However maybe members are somehow able to do so, I will investigate that
