### ISSUE TITLE
Disabling PlotSquared takes a while

### ISSUE THREAD

**Issue by boy0001** [IntellectualSites/PlotSquared#418]
Reasons:
 - Code related to making PlotSquared manageable by plugin managers

Possible fixes:
 - Detect when PlotSquared is individually being disabled versus the server stopping and selectively execute only the required logic corresponding to the reason for disable.

**Comment by PhanaticD** [comment]
oh it was plotsquared.. I was going crazy trying to figure out why my server was so slow to stop

**Comment by Sauilitired** [comment]
Is this really noticeable? Haven't experienced any issues related to this on the test server :confused:

**Comment by PhanaticD** [comment]
its been better recently, but yea a week or two ago would take up to two minutes to shut down
