### ISSUE TITLE
Potential Memory Leak

### ISSUE THREAD

**Issue by Technofied** [IntellectualSites/PlotSquared#4203]
### Server Implementation

Paper

### Server Version

1.20.1

### Describe the bug

Using Eclipse Memory Analyzer it seems there is a memory leak

### To Reproduce

I'm not sure how

### Expected behaviour

For memory to not leak if it is 

### Screenshots / Videos

![image](https://github.com/IntellectualSites/PlotSquared/assets/40795318/5ef8b875-3e24-4e0a-b043-4eb7dca2e5a8)
![image](https://github.com/IntellectualSites/PlotSquared/assets/40795318/022cf825-e951-43e6-986e-20bbca6a3671)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/a1c16de1a3534549b0efd8dfb4971127

### PlotSquared Version

PlotSquared version 7.0.0-rc.4-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by SirYwell** [comment]
Without the actual heap dump, it's hard to say whether this is an actual memory leak or a false positive. Please provide the heap dump (make sure it does not contain sensitive information) so we can look into it.

Also, your PlotSquared version seems to be outdated.
