### ISSUE TITLE
Problem with biome plot after /plot delete

### ISSUE THREAD

**Issue by aurel85** [IntellectualSites/PlotSquared#4204]
### Server Implementation

Paper

### Server Version

1.20.2

### Describe the bug

Hi,

When I delete a plot it does not return to the biome defined in the config.

### To Reproduce

1. Define a base biome in the config (forest for me)
2. /plot claim
3. /plot setbiome desert
4. /plot delete

### Expected behaviour

When I delete the plot it should return to the basic defined biome, therefore forest in my case.

### Screenshots / Videos

Step 2 :
![Step 2](https://github.com/IntellectualSites/PlotSquared/assets/24486147/df911873-711c-4ba8-880a-bce45f45708b)

Step 3 :
![Step 3](https://github.com/IntellectualSites/PlotSquared/assets/24486147/46e9cf1b-7e12-433d-a5c1-9d9aa48dc23a)

Step 4 :
![Step 4](https://github.com/IntellectualSites/PlotSquared/assets/24486147/df50f49a-2737-4097-9b70-f51ac802afb6)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/d88b86f390a744899b4f790d8adaa90b

### PlotSquared Version

PlotSquared version 7.1.0-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by RedstoneFuture** [comment]
https://github.com/IntellectualSites/PlotSquared/issues/4080

**Comment by RedstoneFuture** [comment]
> I actually never know that this is a possible bug, because you can always /p setbiome, but it would be an enhancement to do so because player can't clean it up afterwards when they aren't owner of the plot anymore (also replicated that in v6 and v7)
> 
> @IntellectualSites/core-team does anyone know if setting back plot biomes to their default config biome after plot deletion was a feature in earlier versions? If yes, it is a bug, if not, it is an enhancement.

Since the player has changed the biome, this should also be undone during the delete.
