### ISSUE TITLE
use: #signs flag allows editing signs anywhere

### ISSUE THREAD

**Issue by 500gHackfleisch** [IntellectualSites/PlotSquared#4205]
### Server Implementation

Paper

### Server Version

1.20.2

### Describe the bug

Players can edit and save signs on other plots without having permissions there.

This is possible because the use: #signs flag seems to allow them to do so.

### To Reproduce

1. add flag use: #signs
2. edit signs as you like and save

### Expected behaviour

Shouldn't be able to edit signs or save it.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/c71cab563c9047d7b42d67e799ac6ed2

### PlotSquared Version

PlotSquared Version 7.1.0 Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
I can't reproduce it with only Plotsquared and FAWE. Can you retry without BKCommonLib? It might be an issue with their plugin as it modifies NBT data.

**Comment by 500gHackfleisch** [comment]
Hey there, I tested it with only PlotSquared and FAWE and the issue still persist.

**Comment by Noobieswat** [comment]
Same Problem here.

**Comment by Noobieswat** [comment]
@500gHackfleisch Short time fix use honeycomb on the sign to Prevent all Editing.

**Comment by Incluuu** [comment]
same

**Comment by Incluuu** [comment]
same problem in 1.20 the ability to edit signs was added

**Comment by Girollplay** [comment]
So habe mich jetzt selber drum gekümmert und mir ein PLugin dafür geschrieben wenn jemand interesse hat lade das später auf Spigot mc hoch könnt ja mal schauen ob das auch was für euch ist :)
