### ISSUE TITLE
Could not pass event InventoryCloseEvent 

### ISSUE THREAD

**Issue by Dweezy750** [IntellectualSites/PlotSquared#4206]
### Server Implementation

Paper

### Server Version

1.20.2

### Describe the bug

15.10 09:18:19 [Disconnect] User IMDANK has disconnected, reason: lobby
15.10 09:18:19 [Server] ERROR Could not pass event InventoryCloseEvent to PlotSquared v7.1.0-Premium
15.10 09:18:19 [Server] INFO com.plotsquared.core.util.PlayerManager$NoSuchPlayerException: There is no online player with UUID 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
15.10 09:18:19 [Server] INFO at com.plotsquared.bukkit.player.BukkitPlayerManager.getPlayer(BukkitPlayerManager.java:62) ~[plotsquared-bukkit-7.1.0-Premium.jar:?]
15.10 09:18:19 [Server] INFO at com.plotsquared.bukkit.util.BukkitUtil.adapt(BukkitUtil.java:123) ~[plotsquared-bukkit-7.1.0-Premium.jar:?]

### To Reproduce

Since 7.0.0, if a player gets kicked via player.kickPlayer("reason")

### Expected behaviour

No error.

### Plot Debugpaste

asd

### PlotSquared Version

7.1.0

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
There's no such UUID named "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", and therefore no inventory exists, nullifying the issue.

Please reopen the issue once a full stacktrace including a debugpaste containing the stacktrace has been attached.

**Comment by Dweezy750** [comment]
i wont paste all server info here, thats for sure.
just add a iscancel() check of if null check. so it stops spamming our logs.

**Comment by PierreSchwang** [comment]
You provided as many useful informations, as if you didn't create an issue at all. You did not provide anything of value to make this issue reproducible nor identifiable. Create a new issue following the template or live with the error.
