### ISSUE TITLE
disabling not working?

### ISSUE THREAD

**Issue by 8972legand** [IntellectualSites/PlotSquared#421]
Hey I dont want it to crash with the Plotworld because Plotworld is in OPPrison and Creative is coming soon but we try PlotSquared and its using the PlotWold and the Creative world! Even though i disabled it? am i doing it right? CONFIG: http://pastebin.com/Hqqak7fm
It adds plotworld in there after a restart even if i remove it.

Regards,
- Legend

**Comment by boy0001** [comment]
If it is using the generator, then it will be registered to P^2. This would be configured in either the multiverse worlds.yml or the bukkit.yml.

If you want a standalone PlotSquared generator without the protection system, try out PlotSquaredSG:
 - https://www.spigotmc.org/resources/plotsquared-sg.3736/

And set the generator accordingly

**Comment by 8972legand** [comment]
im not using the plotme generator im using plotsquared i done /mvc Creative normal -g PlotsSquared or whatever the generators called i forgot and disabled plotme in config of plotsquared still used the creative world and plotme

**Comment by 8972legand** [comment]
All the generators are fine creative is using PlotSquared generator and plotworld is using Plotme generator like i want it to but PlotSquared is also using the plotworld even if i remove it from config

**Comment by 8972legand** [comment]
I just dont want PlotSquared doing ANYTHING to plotworld since thats using plotme and i dont want PlotSquared to do ANYTHING to plotme as you can see if i remove plotme from the config and disable plotme conversion it just auto adds plotworld back to the config

**Comment by boy0001** [comment]
Like I said before, if the generator is set to PlotSquared in multiverse or bukkit.yml it will register to PlotSquared. 

If you need some further assistance I will need the following:
 - bukkit.yml
 - Multiverse worlds.yml
 - startup log (these are found in the logs folder)

Please use a paste service e.g. http://hastebin.com

**Comment by 8972legand** [comment]
Ah thanks lol i was stupid and missed creative in the multiverse world.yml :)
