### ISSUE TITLE
Essentials Back [+]

### ISSUE THREAD

**Issue by portapipe** [IntellectualSites/PlotSquared#422]
There's a way to register the location of a plot in essentials to make the /back work properly?

If any player make "/plots home" , the /back will teleport the player in the second last place the player was.

Thanks

**Comment by boy0001** [comment]
Nice description.

**Comment by portapipe** [comment]
Sorry, my mouse clicked the enter key =P Edited.

**Comment by Sauilitired** [comment]
You want use to override the default essentials behavior?

**Comment by portapipe** [comment]
I want that on "/plot home" your teleport location (the plot) will be registered on essentials, like every "tpa/warp/spawn" does.

**Comment by Sauilitired** [comment]
Doesn't essentials already listen to the teleportation event? :s

**Comment by portapipe** [comment]
There is a "register EVERY teleport" but since the player lag, they're teleported to the last location of the lag and that's registered too (very odd). There is a way to hook into essentials and force it like the native one?

**Comment by Sauilitired** [comment]
I'll see what we can do :)

**Comment by portapipe** [comment]
:D thanks

**Comment by manuelgu** [comment]
Essentials uses the "lastlocation" value stored in the player file generated by Essentials to determine the /back location.

https://github.com/essentials/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/IUser.java#L38

**Comment by MattBDev** [comment]
I am confused about this. Is the request asking for PlotSquared to override the /back command to teleport to the home location of the last plot they were on?

**Comment by manuelgu** [comment]
If I understood the OP correctly he wants PlotSquared to hook into the /back command so when you teleport to a plot you can go back to the recent location with /back.

**Comment by manuelgu** [comment]
Set `register-back-in-listener` to `true` in the Essentials config.yml to make this work.
