### ISSUE TITLE
Economy isn't initialized. Make sure Vault and an economy service plugin are installed.

### ISSUE THREAD

**Issue by justLxy** [IntellectualSites/PlotSquared#4224]
### Server Implementation

Paper

### Server Version

1.20.2

### Describe the bug

Economy isn't initialized. Make sure Vault and an economy service plugin are installed.

### To Reproduce

/plot auto

### Expected behaviour

successfully get the plot

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/84cfc070c12843e9a947ef986e5af79e

### PlotSquared Version

PlotSquared 7.1.0

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by PierreSchwang** [comment]
Will be fixed in the next release by https://github.com/IntellectualSites/PlotSquared/commit/1c3776b605ad17f8a3dd00b1a51bc050ddc48563
