### ISSUE TITLE
Plot Clamining & Merging does not charge Economy

### ISSUE THREAD

**Issue by mathemaciel** [IntellectualSites/PlotSquared#4225]
### Server Implementation

Paper

### Server Version

1.20.2

### Describe the bug

I'm having problems with the plotsquared economy , it does not charge the player when using the /plot claim or /plot auto command, it only gives the money to the player when using the /plot delete command , I contacted them via discord, and they told me to open an issue

### To Reproduce

/plot claim (does not discount the value of the player)
/plot auto (does not discount the value of the player)

### Expected behaviour

does not deduct the value of the player on claim

### Screenshots / Videos

![Captura de tela 2023-11-02 144922](https://github.com/IntellectualSites/PlotSquared/assets/68457323/95cf29d0-5ae8-4bec-81b2-0fbdd2ccb2b7)
![Captura de tela 2023-11-02 144838](https://github.com/IntellectualSites/PlotSquared/assets/68457323/1bcbf0da-b15b-4f2b-b5f9-313c62afc9a8)
![Captura de tela 2023-11-02 144727](https://github.com/IntellectualSites/PlotSquared/assets/68457323/c3b3537a-4689-4921-abf3-8db13
![Captura de tela 2023-11-02 144247](https://github.com/IntellectualSites/PlotSquared/assets/68457323/704ecb1e-8178-4103-b211-b3d8b872c591)
79dda3e)

### Error log (if applicable)

no errors in console

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/9035e3e6bcb34cb48301a9bf3c5ee53a

### PlotSquared Version

PlotSquared-7.1.0-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by mathemaciel** [comment]
dont work after atualization , 
![image](https://github.com/IntellectualSites/PlotSquared/assets/68457323/f492fe40-59c5-48b7-bd92-f4449be95b36)

**Comment by mathemaciel** [comment]
![image](https://github.com/IntellectualSites/PlotSquared/assets/68457323/e3984e04-2c4a-4fcf-ac78-2fc0d9cf39a5)

**Comment by mathemaciel** [comment]
![image](https://github.com/IntellectualSites/PlotSquared/assets/68457323/ad767b26-3344-4b8e-a8df-bfcbeffd343f)

**Comment by SirYwell** [comment]
Send a fresh debugpaste please

**Comment by mathemaciel** [comment]
https://athion.net/ISPaster/paste/view/8b16fc5c021949cc8ac57bf7b38d6213

**Comment by mathemaciel** [comment]
not work

**Comment by mathemaciel** [comment]
https://athion.net/ISPaster/paste/view/85d957d20fcf4aca863326862b4ce17d

**Comment by SirYwell** [comment]
I assume this comes down to your economy plugin. It works fine with EssentialsX.

**Comment by httpKaua** [comment]
How do I enable PvP on roads for the default group? I read all the documentation about the flag world plot and tried adding it but was unsuccessful. The goal is to have PvP at night in the plot
It only works within the plot, on the road it doesn't

**Comment by mathemaciel** [comment]
Is there any place to change the command that sends money?

**Comment by mathemaciel** [comment]
because I'm sure it's the integration of plotsquared with the economy plugin, there isn't much to do in the economy plugin but I think it would be possible to change it in plotsquared, essentials I won't use as it doesn't have the functions I need, I already bought it a better and more updated plugin, which is cmi and my economy plugin, wouldn't there be another way to charge a player? because if it were using commands instead of just putting the value, I'm sure it would work

**Comment by mathemaciel** [comment]
all other plugins are working correctly with the economy, only plotsquared is not working correctly

**Comment by NotMyFault** [comment]
We cannot guarantee compatibility for every plugin out there providing an economy, therefore our testing and reproducing covers the industry standard - EssentialsX - only.

**Comment by mathemaciel** [comment]
https://drive.google.com/drive/folders/1xfsRmn9uS7O7upyPt1VlGlwltcDW10Y8?usp=drive_link


I tested with Essentials and not even with Essentials is it sending the command, something is missing with plotsquared
Follow the video of the tests with essentials

**Comment by mathemaciel** [comment]
https://drive.google.com/file/d/1OPnCMjBfDD1H6S6THVWoVTL1TP1X4gI-/view?usp=drive_link

the same problem

**Comment by TheMeinerLP** [comment]
Can you provide the videos via Youtube or direct upload?
Github has a function to embed videos 😄

**Comment by mathemaciel** [comment]
very big video

**Comment by mathemaciel** [comment]
https://github.com/IntellectualSites/PlotSquared/assets/68457323/9bc9bedb-95e1-4d5d-bf5b-ef93a5161d72

**Comment by mathemaciel** [comment]
that was

**Comment by TheMeinerLP** [comment]
Still the same Economy(MiyukiEconomy) ?

**Comment by mathemaciel** [comment]
nooo , economy essentials

**Comment by TheMeinerLP** [comment]
The screenshot is not loading. Maybe provide another debug paste to hold the informations up-to 
date

**Comment by mathemaciel** [comment]
Since you said that it would only work with essentials, I created a test server with only the necessary plugins to test and check if it is really working or not, from what I detected it is not working, plotsquares is not sending any request to ask for money or to give the money

**Comment by mathemaciel** [comment]
![Captura de tela 2023-11-26 200800](https://github.com/IntellectualSites/PlotSquared/assets/68457323/9ec4c58c-3962-42f2-ab8d-d2a624cf5a6d)

**Comment by TheMeinerLP** [comment]
> Since you said that it would only work with essentials.  

I never said that. But ok

**Comment by mathemaciel** [comment]
> We cannot guarantee compatibility for every plugin out there providing an economy, therefore our testing and reproducing covers the industry standard - EssentialsX - only.

here

**Comment by TheMeinerLP** [comment]
> > We cannot guarantee compatibility for every plugin out there providing an economy, therefore our testing and reproducing covers the industry standard - EssentialsX - only.
> 
> here

Different person, you know. But back to the main topic. Provide a up-to date debugpaste maybe i found something

**Comment by mathemaciel** [comment]
> > We cannot guarantee compatibility for every plugin out there providing an economy, therefore our testing and reproducing covers the industry standard - EssentialsX - only.
> 
> here

No, you're not guys, okay? plotsquared support team in general, nothing personal

**Comment by mathemaciel** [comment]
> > Since you said that it would only work with essentials.
> 
> I never said that. But ok

No, you're not guys, okay? plotsquared support team in general, nothing personal

**Comment by mathemaciel** [comment]
https://athion.net/ISPaster/paste/view/43bc9469a82a44c3bcd08380f2d4c524

**Comment by TheMeinerLP** [comment]
<img width="1436" alt="image" src="https://github.com/IntellectualSites/PlotSquared/assets/6745190/589708be-0d79-4586-9f5f-5f2da289dd55">
Here some small news. That can be a issue.
Also purpur have sometimes unexpected behaviors

**Comment by mathemaciel** [comment]
![image](https://github.com/IntellectualSites/PlotSquared/assets/68457323/7323e021-c50f-4ba1-9d64-0cf98a37f624)

worlds.yml is correct

![image](https://github.com/IntellectualSites/PlotSquared/assets/68457323/0a329b9b-de24-470c-9de1-cd15371e037b)

bukkit.yml is correct

**Comment by mathemaciel** [comment]
I'm switching to paper to perform the test

**Comment by TheMeinerLP** [comment]
<img width="887" alt="image" src="https://github.com/IntellectualSites/PlotSquared/assets/6745190/311d20cc-bed6-429d-84e2-06a3ee2e4f2f">
Works so far on my setup with Paper and up-to date plugins

**Comment by mathemaciel** [comment]
part 1   https://youtu.be/zAsAFsLhUuA

part 2 https://www.youtube.com/2cGdgQblzvY

part 3 https://youtu.be/io21mSNwQOQ

**Comment by TheMeinerLP** [comment]
I can't replicated with a fresh setup of paper. I will not invest more time here.

**Comment by mathemaciel** [comment]
I'm sending you the test server folder here, try to solve the problem and send me the clean server with only the plotsquared functionality, as it's not working at all, neither on a local host nor on paid hosting, I don't want to be annoying but I paid for the plugin and everyone is abandoning support and doesn't want to fix the problem, I'm sure it's something related to the plotsquared plugin, and I'm very sad to know that the plugin is paid and the support is inefficient, because I paid and for me in my country's currency it wasn't cheap, it was very expensive for me 

https://drive.google.com/file/d/1zH9zLlVCAPbd8iV0JDftokZI1Ja6hrmH/view?usp=drive_link

I just want to charge someone when creating the plot, that's all I'm asking for nothing more and they're not being able to help me
the system does not pull the vault, does not send any commands to the vault, it seems that the vault is just for decoration
I was told that it would only work with essentials, I changed plugins and it doesn't work the same way

**Comment by TheMeinerLP** [comment]
<img width="903" alt="image" src="https://github.com/IntellectualSites/PlotSquared/assets/6745190/cf850a5a-337c-491e-babc-240d759bf8a2">
Works with my setup. I don't have OP and just use some normal commands. You can get everything from the screenshots.
<img width="1055" alt="image" src="https://github.com/IntellectualSites/PlotSquared/assets/6745190/e1dc42cc-eef6-4e51-bb6c-ba8cb7f27f22">

**Comment by mathemaciel** [comment]
I managed to make it work, from what I saw in its configuration in the folder there, the permission was wrong. plots.permpack.basic was missing. After applying this permission it started working, I don't know if that was really what made it work but it's working now. I will continue testing
