### ISSUE TITLE
Players can use Frost Walker on other plots.

### ISSUE THREAD

**Issue by ch4ika** [IntellectualSites/PlotSquared#4228]
### Server Implementation

Paper

### Server Version

1.20.2

### Describe the bug

Players can use Frost Walker on other plots to turn water into ice.

### To Reproduce

frostwalker enchantment 
move on water on other empty

### Expected behaviour

enchantment should not work on not trusted plots.

With the EntityBlockFormEvent we can cancel the FrostWalker event:
```
    @EventHandler(priority = EventPriority.HIGHEST)
    public void onEntityBlockFormEvent(EntityBlockFormEvent event) {
        if(event.getEntity() instanceof Player player) {
            ItemStack item = player.getInventory().getBoots();
            if(item != null && item.containsEnchantment(Enchantment.FROST_WALKER)) {
                Block block = event.getBlock();
                Plot plot = BukkitUtil.adapt(block.getLocation()).getPlot();
                if(plot != null && !plot.isAdded(player.getUniqueId())) {
                    event.setCancelled(true);
                }
            } 
        }
    }
```

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/40aa7de785bb4963a9169c4061c2e9f3

### PlotSquared Version

7.1.0-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Given you have already analyzed the problem, you're welcome to file a pull request :)

**Comment by ch4ika** [comment]
https://github.com/IntellectualSites/PlotSquared/pull/4230
