### ISSUE TITLE
Boat with Chest can be pushed on roads

### ISSUE THREAD

**Issue by Tamikaschu** [IntellectualSites/PlotSquared#4229]
### Server Implementation

Paper

### Server Version

1.20.2

### Describe the bug

Boats with Chests can be pushed off plots without them despawning on roads. (When you drive them on roads they despawn normally like other vehicles)

### To Reproduce

Place a Boat with Chest on a plot
Push the boat off the plot onto roads

### Expected behaviour

Boats with Chest should also despawn on roads when getting pushed off a plot onto roads

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/40aa7de785bb4963a9169c4061c2e9f3

### PlotSquared Version

7.1.0-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
You're not using Paper, nullifying the issue.

**Comment by ch4ika** [comment]
can verify on paper latest 1.20.1

**Comment by Tamikaschu** [comment]
Issue ist still present in latest paper version with PlotSquared version 7.2.0-Premium
Debugpaste: https://athion.net/ISPaster/paste/view/4ef2fb0df1144f6ebabe16cbdc7c59ce
