### ISSUE TITLE
IntellectualServer web interface

### ISSUE THREAD

**Issue by boy0001** [IntellectualSites/PlotSquared#423]
Use city's thingo for plot shizzle

**Comment by Sauilitired** [comment]
YAS. I just need to get working on it again, at least we have a maven repo now :yellow_heart:

**Comment by Sauilitired** [comment]
http://mc.plotsquared.com/plot/creative/2;-3 Things are moving forward.

**Comment by EvilOlaf** [comment]
#shutupandgimmethattranslationfilesoIcantranslatetogerman :P

**Comment by Sauilitired** [comment]
This will not be handled by PlotSquared itself, so closing the ticket as it's not related.
