### ISSUE TITLE
Sheep Regrowth Wool / Sheeps dont Eat on Plotworld

### ISSUE THREAD

**Issue by rpsrv** [IntellectualSites/PlotSquared#4233]
### Server Implementation

Paper

### Server Version

1.20.2

### Describe the bug

Since i updated completely to 1.20.2 

Sheeps on a Plot dont eat Grass or dont Regrowth Wool 

Mob-griefing is set to true

Same on Bees.
after they joined the Hive they dont get out again

### To Reproduce

Unknown

### Expected behaviour

Sheeps should Eat and Regrowth Wool
Bees dont get out of Hives and dont make Honey

### PlotSquared Version

7.2.0-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [x] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by rpsrv** [comment]
done - is fixed

**Comment by RedstoneFuture** [comment]
@rpsrv The problem no longer occurs? Then we can close the ticket again?

**Comment by rpsrv** [comment]
Yes u can close it

RedstoneFuture ***@***.***> schrieb am Sa., 11. Nov. 2023,
22:55:

**Comment by cerus** [comment]
> done - is fixed

Hey @rpsrv, how did you resolve this issue? I'm experiencing the same problem

**Comment by resi23** [comment]
@cerus I have the same problem. For me it's a PaperBug. https://github.com/PaperMC/Paper/issues/9945

This event in the PaperListener ensures that the sheep do not eat grass

```
    @EventHandler
    public void onPlayerNaturallySpawnCreaturesEvent(PlayerNaturallySpawnCreaturesEvent event) {
        if (Settings.Paper_Components.CANCEL_CHUNK_SPAWN) {
            Location location = BukkitUtil.adapt(event.getPlayer().getLocation());
            PlotArea area = location.getPlotArea();
            if (area != null && !area.isMobSpawning()) {
                event.setCancelled(true);
            }
        }
    }
    ```
