### ISSUE TITLE
Plotsquare error in the economy to buy plots

### ISSUE THREAD

**Issue by Mazekeeen** [IntellectualSites/PlotSquared#4237]
### Server Implementation

Paper

### Server Version

1.20

### Describe the bug

When someone wants to buy a plot the following message appears:; economy is not initialized, make sure vault and an economy plugin is installed.

### To Reproduce

/plot buy

message appears:; economy is not initialized, make sure vault and an economy plugin is installed.

### Expected behaviour

that recognizes the installed economy

### Screenshots / Videos

![image](https://github.com/IntellectualSites/PlotSquared/assets/151408476/293f5dd6-cf7d-4046-84fa-708b39365144)
![imagen_2023-11-18_170730991](https://github.com/IntellectualSites/PlotSquared/assets/151408476/3f53910e-ce94-4935-aebc-0f7a5f2285b2)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/7b1f3bc6ded84e8aa1c2bd08614dcc58

### PlotSquared Version

Plotsquare 7.2.0 premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Economy is disabled in your settings.

**Comment by Mazekeeen** [comment]
> Economy is disabled in your settings.

omg my bad, thank u so much we already solved the problem, and I have another question, is it possible to delete plots of the world individually? I mean deleting the record so that no one can claim it
