### ISSUE TITLE
Biome "snake" in the middle of plot >:[

### ISSUE THREAD

**Issue by Sauilitired** [IntellectualSites/PlotSquared#424]
![WAT](http://i.imgur.com/anT3RBA.png)

See? No wörking. Plot clear doesn't fix it :angry:

**Comment by Log1x** [comment]
Related to the problem I discussed with Empire. Looks to be a side effect of a post-converted PlotMe world.

It's very common to see it scattered among plots, near roads, and underneath roads upon /plot merge

You can see the Biome in debug is PLAINS while standing on it, but the plot its self is JUNGLE.

![Bug](http://log1x.com/screenshots/2015-07-19_03-34-15.png)

**Comment by Sauilitired** [comment]
My world is a freshly generated world, with a schematic.

**Comment by Log1x** [comment]
![https://media1.giphy.com/media/r1HGFou3mUwMw/200_s.gif](https://media1.giphy.com/media/r1HGFou3mUwMw/200_s.gif)

**Comment by boy0001** [comment]
Merging with #455
