### ISSUE TITLE
Permission for certain blocks as border

### ISSUE THREAD

**Issue by Leahcimkrob** [IntellectualSites/PlotSquared#4241]
### What feature do you want to see added?

It would be nice if you could specify which block you can set as a border in addition to the permission plots.set.border.
You could therefore allow/forbid certain edges to players using a permission system.

### Are there any alternatives?

outdated Plotborder-Plugins, that will not working with MC 1.20.2

**Comment by NotMyFault** [comment]
That functionality is already built in. You can predefine borders and other components via plot components: https://intellectualsites.gitbook.io/plotsquared/customization/plot-component-presets
