### ISSUE TITLE
Alias

### ISSUE THREAD

**Issue by forsakenliquid** [IntellectualSites/PlotSquared#4242]
### Server Implementation

Paper

### Server Version

1.20.2

### Describe the bug

If you have an merge, and you try to set an alias, it will not work. It only works on one plot (So if its an 4er merge it works on 1/4 of the plot) 

### To Reproduce

/p claim 2x
/p merge
go to the merge
/p alias set ..., will only work on one plot side

### Expected behaviour

You should be able to change the alias on the whole plot.

### Screenshots / Videos

![image](https://github.com/IntellectualSites/PlotSquared/assets/151550029/cf32f8df-1b0b-4c93-b817-381957fc9623)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/df3ea0f4a2094665a8541e2dd1effb5c

### PlotSquared Version

Plotsquared Version: 7.2.0 - Permium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by RedstoneFuture** [comment]
https://github.com/IntellectualSites/PlotSquared/issues/3573
