### ISSUE TITLE
Could'nt Find Generator

### ISSUE THREAD

**Issue by Grizzlybln** [IntellectualSites/PlotSquared#4244]
### Server Implementation

Paper

### Server Version

1.20.2

### Describe the bug

Create an world with plotssquared and load it, restart the Server and get "com.plotsquared.google.injector.getinstance(.com.plotsqared.google.key) Return Error while can't invoke '0' Cant Return value is "null"

### To Reproduce

1. Create world with Setup
2. Take Server offline
3. Take Server online
4. See the Error in console

### Expected behaviour

Multiverse Said an Error and give me the answer your system have the Bug NOT the worldcreator(Multiverse) so i contact YOU

### Screenshots / Videos

![17011075848712537858789811369882](https://github.com/IntellectualSites/PlotSquared/assets/123985584/c99bb095-9763-413c-bc37-021ded454940)

### Plot Debugpaste

Not answered (Too Many Arguments)

### PlotSquared Version

V 7.2.0

### Checklist

- [x] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by TheMeinerLP** [comment]
@Grizzlybln Plotsquared Debug and full log is missing

**Comment by Grizzlybln** [comment]
I cant give the Log while i cant generate it , i usw /p debugpaste and the plotsquared Nobody Work Not doing anything i Not know why

**Comment by Grizzlybln** [comment]
Ah but i cant give It i can read but Not downloading

**Comment by TheMeinerLP** [comment]
Try it or ask your hoster.

**Comment by Grizzlybln** [comment]
I have the Datafile 
[latest.log.txt](https://github.com/IntellectualSites/PlotSquared/files/13478763/latest.log.txt)

**Comment by TheMeinerLP** [comment]
<img width="1456" alt="image" src="https://github.com/IntellectualSites/PlotSquared/assets/6745190/3e092979-6d8c-446c-a222-e6b5107455db">
You have installed 3 Version of FAWE. That can't be work!
Also you have installed worldedit!
<img width="1212" alt="image" src="https://github.com/IntellectualSites/PlotSquared/assets/6745190/b172e106-3029-438e-a941-6fd4bfb774bb">
Because of this reason PlotSquared cannot be load!
Please fix the errors inside of your uploaded log and the listed from me before you come back

**Comment by Grizzlybln** [comment]
Which worldedit and fastsync i Download ? I have only the Bukkit Site all another worldedit Version are outdated and Not kompatibel eith 1.20 or 1.19. so what fastsync anf worldedit i must installed can you give ne a Name ? Or a Pagelink , i Not know how to find

**Comment by TheMeinerLP** [comment]
In my screentshots are listet some jar file that duplicated or already loaded
