### ISSUE TITLE
Unlink to clear?

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualSites/PlotSquared#425]
> [22:15:33] <LaxWasHere> Why do I have to unlink to clear? :|

Actually thats a pretty loud question.

**Comment by Sauilitired** [comment]
You should also quote the noob who said it, so everyone can laugh at him...

**Comment by LaxWasHere** [comment]
Ye! pls fix! This has caused me a great deal of stress having to type a lot of letters just to clear a plot!!1!!1!

**Comment by boy0001** [comment]
The world generation in PlotSquared is abstract, and there are multiple generators (take a look at the P^2 page). Plot clearing is based on world generation, custom generators don't need to provide their own plot clearing code (although some do as it allows for further optimization).

How should PlotSquared handle plot clearing such that it will work with existing generators? Specifically with regard to what happens to where the road used to be?

With a schematic based generator, even considering that the generator bundled with PlotSquared supports plot and road schemaitcs, you have the issue of not having a schematic built for mega plots, and so if you were to clear you would get roads.

Of course it also gets more complicated when dealing with augmented plot worlds.

Possible solutions:
 * Force custom generators to implement plot clearing for mega plots
 * Force plots to unlink upon clear
 * Just allow it and live with the messed up roads or whatever in cleared merged plots

**Comment by boy0001** [comment]
*Currently testing a potential fix, open a new ticket if this causes other problems
