### ISSUE TITLE
Entities are not counted correctly on merged plots

### ISSUE THREAD

**Issue by Tamikaschu** [IntellectualSites/PlotSquared#4269]
### Server Implementation

Paper

### Server Version

1.20

### Describe the bug

Entities will not get counted correctly on merged plots resulting in never reaching the plot cap limit and overflowing the plot.

### To Reproduce

1. Merge a few plots
2. Set a Spawner (e.g Villager Spawner)
3. Check if the entities are being counted correctly (/p caps)

### Expected behaviour

Entities should be counted correctly 

### Screenshots / Videos

Merged plot: 
![image](https://github.com/IntellectualSites/PlotSquared/assets/98806122/83074876-38a3-41cf-a9f7-6306cdb59bba)
![image](https://github.com/IntellectualSites/PlotSquared/assets/98806122/ae99459f-fc31-46f4-8b49-241f975d3a34)

Single plot:
![image](https://github.com/IntellectualSites/PlotSquared/assets/98806122/930b7b26-8436-449f-b456-ac2542a413e1)
![image](https://github.com/IntellectualSites/PlotSquared/assets/98806122/ef78f8d5-793e-45ed-b7f5-c0109ad663f6)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/1dc97f594f544d79ae8f6d9e68a8f485

### PlotSquared Version

PlotSquared version 7.2.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by Tamikaschu** [comment]
Quite similar to #3050 the problem is not resolved for me though

**Comment by ch4ika** [comment]
I have the same problem, my players have over 1000 entities even though the cap is 75 for me.

**Comment by OneLiteFeather** [comment]
Villagers don't really count as mobs or animals in plotsquared. You could implement a third party flag for villagers for your own or suggest the flag as a feature. I've seen this happening with villagers for like 3 years on different servers.

**Comment by Tamikaschu** [comment]
Actually the villagers are counted as cap type mobs. On a single plot they will get counted correctly and therefore reach the cap and stop spawning from there on. On a merged plot though this is not the case. They will surpass the mobs cap on a merged plot.

**Comment by ch4ika** [comment]
The problem here is that the caps constantly reset as soon as an entity crosses a merged plot.

**Comment by Tamikaschu** [comment]
Problem is caused by the same issue as it was described in https://github.com/IntellectualSites/PlotSquared/issues/4338. Though i don't know why this one was accepted and the other marked as invalid.
