### ISSUE TITLE
Add compatibility with WorldTool and make WorldEdit a optional dependency

### ISSUE THREAD

**Issue by Atten007** [IntellectualSites/PlotSquared#4277]
### What feature do you want to see added?

Hello folks,

I want to install "PlotSquared v7" on my server. I self-compiled it with git clone and gradlew build. Unfortunately, it's disabling because I don't have installed WorldEdit on my server. Instead of WorldEdit, I'm using WorldTool, which can be found [here](https://www.planetminecraft.com/data-pack/worldtool/). WorldTool is a world-editing data pack which is better than WorldEdit, I have this on my server installed. If PlotSquared can get support for the WorldTool data pack, it may be really nice!

Greetings,
Atten007 😊

### Are there any alternatives?

None.

**Comment by SirYwell** [comment]
You are misunderstanding that WorldEdit isn't just a tool for builders, but in the case of PlotSquared it provides a rich API independent from the server software that allows us to efficiently deal with regions and blocks. This is something WorldTool cannot offer. So even if you think WorldTool does a better job for what you're using it for, it definitely doesn't the job we use WorldEdit to at all.
