### ISSUE TITLE
PlotSquared 7.3.0 not loading world and crashes instantly (Cannot generate chunk that does not belong to a plot area)

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/PlotSquared#4279]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

After updating from plotsquared-bukkit-7.2.1-Premium to plotsquared 7.3.0 the plugin no longer functions correctly, all plot related commands don't work and there is no feedback in chat. Trying to take a plotsquared debugpaste triggers an error and after joining the server and trying to use a command the server will crash a couple of seconds later.

Crash report: https://pastebin.com/uz3B5yYL

Error when trying to run ps debugpaste: https://pastebin.com/C6Z2cjUu

### To Reproduce

1. Update from plotsquared 7.2.1 to plotsquared 7.3.0

### Expected behaviour

Plugin should work without crashes

### Plot Debugpaste

Triggers an error

### PlotSquared Version

plotsquared-bukkit-7.3.0-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by PierreSchwang** [comment]
Share the full log from startup to crash.

**Comment by SecretlyJealous** [comment]
> Share the full log from startup to crash.

Log: https://pastebin.com/Cp5YdWYc

**Comment by PierreSchwang** [comment]
Could you try Paper 1.20.4 Build 243 perhaps? (https://api.papermc.io/v2/projects/paper/versions/1.20.4/builds/342/downloads/paper-1.20.4-342.jar)

**Comment by SecretlyJealous** [comment]
> Could you try Paper 1.20.4 Build 342 perhaps? (https://api.papermc.io/v2/projects/paper/versions/1.20.4/builds/342/downloads/paper-1.20.4-342.jar)

Still not working and causes crash: https://pastebin.com/Qdu7nXxd

**Comment by PierreSchwang** [comment]
I mean, one error seems to be solved for now at least. 
As the debugpaste does not work, could you upload your worlds.yml at least?

**Comment by SecretlyJealous** [comment]
> I mean, one error seems to be solved for now at least. As the debugpaste does not work, could you upload your worlds.yml at least?

worlds.yml: https://pastebin.com/0i4tDDGQ

**Comment by PierreSchwang** [comment]
Please set "debug" to true in the configuration file and send the new log containing the debug output (if not set to true already, which would be weird, as quite a bit of logging is missing)

**Comment by SecretlyJealous** [comment]
> Please set "debug" to true in the configuration file and send the new log containing the debug output (if not set to true already, which would be weird, as quite a bit of logging is missing)

Debug was set to false, I've set it to true now and here is the log: https://pastebin.com/7pSU0hzq
My settings file: https://pastebin.com/Tt2JxkGy

**Comment by PierreSchwang** [comment]
As there is no dump of the plotworld's flags, I think the world load fails somewhere between the save of the default configuration and the loading of the actual configuration.

Please contact us in the Discord so that we can get to the bottom of the problem more easily

**Comment by SecretlyJealous** [comment]
I have traced the issue to this commit: https://github.com/IntellectualSites/PlotSquared/commit/945a8ad306ca6e99181838a55108b77c59afbf32 If you compile the plugin and revert that file the plugin works as normal again - Just putting this out there since some people may run into this bug now that paper 1.20.4 is stable and people are updating plugins

**Comment by ShayBox** [comment]
I had to revert to before that commit and use [FAWE 2.8.3](https://ci.athion.net/job/FastAsyncWorldEdit/620/artifact/artifacts/FastAsyncWorldEdit-Bukkit-2.8.3.jar)

**Comment by PierreSchwang** [comment]
Can anyone provide me their data (world, PlotSquared JAR and configuration) before migration which produces the error? Maybe that makes it possible for reproduction and possible fix

**Comment by SecretlyJealous** [comment]
I'm no longer experiencing this issue so I'll close this issue
