### ISSUE TITLE
Bug with "prevent-creative-copy" flag

### ISSUE THREAD

**Issue by NoltoxGit** [IntellectualSites/PlotSquared#4281]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

Hello,
When you set the `prevent-creative-copy` flag on a plot, it interferes with the textures of the player heads when it is moved in the inventory. 

### To Reproduce

1. Active the `prevent-creative-copy` on a plots
2. Test with a player with default permissions
3. Giving yourself a head with texture
4. Move this head in your inventory

### Expected behaviour

Make sure that when a player's head is moved in the inventory, either texture is kept.

### Screenshots / Videos

https://github.com/IntellectualSites/PlotSquared/assets/75265787/f5ec334a-7895-4ecc-a8c9-a6ade82c7bf5

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/7ed2091dd87b4488a11749d00dc4f7f2

### PlotSquared Version

PlotSquared 7.3.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
Take a look at your debugpaste and headdatabase, your plugin was disabled and therefore could not load the heads. Please forward your issue to Arcaniax.
