### ISSUE TITLE
Flag server-plot

### ISSUE THREAD

**Issue by JuergenUniVie** [IntellectualSites/PlotSquared#4282]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

/plot list all aborts as soon as a plot with the flag server-plot true exists.

### To Reproduce

create a plot with flag server-plot true

### Expected behaviour

only to mark a plot as server-plot

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/2fe70e393def44a8b82cbc7b755dc50b

### PlotSquared Version

7.3.1 Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
I could reproduce it with the server plot, looks like it also happens on 7.2.1 Snapshot too.
