### ISSUE TITLE
PlotClearEvent Result is always null

### ISSUE THREAD

**Issue by Ste3et** [IntellectualSites/PlotSquared#4288]
### Server Implementation

Spigot

### Server Version

1.20.4

### Describe the bug

For my ProtectionLib plugin i listen to the **PlotClearEvent** and i have seen the event implements the interface CancellablePlotEvent.
The **EventResult** an enum is always null, i don't know how to handle if a non owner player try to usage `/plot clear` then the event is always triggerd by the player It doesn't matter whether he is the owner or whether he has the rights to do so.

### To Reproduce

I have written an debug output inside my protectionlib plugin i know these is not the right way to reproduce it.
But here is it:

```Java
@Subscribe
public void onPlotClear(PlotClearEvent clearEvent) {
	Bukkit.broadcastMessage("PlotClearEvent: #getEventResult -> " + (Objects.isNull(clearEvent.getEventResult()) ? "null" : clearEvent.getEventResult().name()));
	if(Result.DENY == clearEvent.getEventResult()) return;
        //do something
}
```

### Expected behaviour

The PlotClearEvent should not be triggered then the player have no permissions for it or use the Result enum as expacted

- DENY(0) Player is not the owner of the Plot
- ACCEPT(1) Player have confirmed the Clearing proccess or the toggle of the clear-confirmation
- FORCE(2) Player have forced the deletion

The null resulot should be avoidet here to avoid confusing.

### Screenshots / Videos

https://www.youtube.com/watch?v=4RxtKsnJUkg

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/6c0efd6a58eb4c949553fe75fe1be21e

### PlotSquared Version

 PlotSquared v7 7.3.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by Ste3et** [comment]
https://github.com/Ste3et/ProtectionLib/blob/master/PlotSquaredV7/src/main/java/de/Ste3et_C0st/ProtectionLib/main/plugins/fPlotSquaredV7.java#L34

**Comment by Ste3et** [comment]
You can find my public code here -> https://github.com/Ste3et/ProtectionLib/blob/master/PlotSquaredV7/src/main/java/de/Ste3et_C0st/ProtectionLib/main/plugins/fPlotSquaredV7.java#L34

**Comment by PierreSchwang** [comment]
The results are generally `null` by default. That just indicates, that no other addon listening on that event already set / modified the result. 
The player check will only be ignored if the result is set to `FORCE`. Generally that event does not seem to be quite suitable for your needs - https://github.com/IntellectualSites/PlotSquared/pull/4268 might be worthwhile waiting for.

**Comment by Ste3et** [comment]
Thank you @PierreSchwang that was exactly that what i think how it works and i already see https://github.com/IntellectualSites/PlotSquared/pull/4268 thank you
