### ISSUE TITLE
plot music tp from another world bug

### ISSUE THREAD

**Issue by Theepwner** [IntellectualSites/PlotSquared#429]
If a player has music activated in his/her plot, and you tp to the plot from another world; you won't be able to hear the music.

If you tp from the same world to the plot you will be able to hear however.

**Comment by boy0001** [comment]
I have confirmed that PlotSquared does tell the client to play music, so the problem appears the be client side. Unfortunately since there is no way to check if the client is playing the music, I am unable to fix this.

If you believe there may be a workaround, please let us know.
