### ISSUE TITLE
Setting Component

### ISSUE THREAD

**Issue by Uzuark** [IntellectualSites/PlotSquared#4293]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

PlotManager#setComponent

### To Reproduce

plot.getManager().setComponent(plot.getId(), "FLOOR", blockType.getDefaultState(), null, null);

### Expected behaviour

It should create a QueueCoordinator by itself, but it doesn't and throws an exception

### Error log (if applicable)

https://pastebin.com/TSPe5GCZ

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/3c1c93f0054f45ec9059197ac14293b9

### PlotSquared Version

7.3.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
Well you should not reload plugins, you'll run into issues that way. Can you try without Plugman and restarting the server?
