### ISSUE TITLE
/plot sethome none doesnt reset to default location

### ISSUE THREAD

**Issue by Tamikaschu** [IntellectualSites/PlotSquared#4294]
### Server Implementation

Paper

### Server Version

1.20

### Describe the bug

Resetting the plothome with /plot sethome none doesnt reset the home to the default location

### To Reproduce

- claim a plot
- set plothome (/p sethome)
- reset plothome (/p sethome none)

### Expected behaviour

Home position should be reset to default location.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/a7fcb735f056463b9aca86f128562df5

### PlotSquared Version

7.2.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
Can replicate. Interesting the fact this hasn't been found earlier
