### ISSUE TITLE
Admins cannot write signs on plots they are not trustet

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#4296]
### Server Implementation

Paper

### Server Version

1.20

### Describe the bug

If i have admin perms and trie to place a sign on a plot on which iam not trusted the sign menu will not be opened

### To Reproduce

1. Use an 2nd account to claim a plot
2. Use your admin account to place a sign
3. The sign will be placed but the menu to write the text will not be opened

### Expected behaviour

Menu to enter the text should be opened

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/d3824f2ef850411ca928af163b45fe69

### PlotSquared Version

7.3.0-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by PierreSchwang** [comment]
https://github.com/IntellectualSites/PlotSquared/commit/449af2f3a4ae3f88b6ce9830aeb90c2ab3e6c740

Fixed in next release
