### ISSUE TITLE
plotsquared /p delete / /p clear doesn't work

### ISSUE THREAD

**Issue by EinfxchNanu** [IntellectualSites/PlotSquared#4298]
### Server Implementation

Spigot

### Server Version

1.20

### Describe the bug

Hello,
At the beginning I want to say that my server is running on 1.14 and I have the Plotsquared version
4.494 because that's the only one. Well, it definitely works. /p delete doesn't. Every time I type that I always get "A set block timer is bound to either the current plot or you please wait for it to finish"
What can I do? bdw My server hoster is aternos I know it's not the best but it works
![Bild_2024-01-19_093436827](https://github.com/IntellectualSites/PlotSquared/assets/157104976/26768e1f-6023-40b8-8bb7-ec64706b9d79)

### To Reproduce

/p delete

### Expected behaviour

I write in the chat /p delete and then the error message comes up "A set block timer is bound to either the current plot or you please wait for it to finish"

### Screenshots / Videos

![Unbenannt](https://github.com/IntellectualSites/PlotSquared/assets/157104976/6a87d116-045c-46be-9050-fa3b6e500086)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/a9ef9c98929e43b1a39b32b8fa9096fe

### PlotSquared Version

4.494

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by TheMeinerLP** [comment]
We don't support outdated versions like 1.14. Also we are already on PS7. Please update

**Comment by PierreSchwang** [comment]
Apart from the outdated versions, seems like PSv4 expects 3D Biomes introduced in 1.18. 
I really recommend you to update. In the end, nothing we can change as the code is not maintained (nor does it exist anymore I think)

**Comment by EinfxchNanu** [comment]
I can't update the version because aternos only has the one for 1.14
