### ISSUE TITLE
/plot setborder [block_id]

### ISSUE THREAD

**Issue by LittlePotatooo** [IntellectualSites/PlotSquared#4299]
### What feature do you want to see added?

I believe "/plot setborder [block_id]" would be an amazing addition to PlotSquared. This command allows a plot owner to change the border block (typically slab) that surrounds their plot.  

### Are there any alternatives?

No

**Comment by SirYwell** [comment]
Already exists, see <https://intellectualsites.gitbook.io/plotsquared/features/commands#set>. You can run e.g. `/plot set border stone`.
