### ISSUE TITLE
plot music on/off bug for players not plot owner

### ISSUE THREAD

**Issue by Theepwner** [IntellectualSites/PlotSquared#430]
When you are plot owner, turning music on/off will be instantly in effect. If you aren't the plot owner, yet you are inside the plot - when the plot owner activates the music, you won't be able to hear it unless you re-enter the plot. This also goes for when the plot owner stops the music.

**Comment by boy0001** [comment]
Issue seems to apply to all flags, it's just only relevant / evident with a few.
