### ISSUE TITLE
[Feature Request] Add support for Paper's AsyncChat

### ISSUE THREAD

**Issue by NoltoxGit** [IntellectualSites/PlotSquared#4304]
### What feature do you want to see added?

Hello,
Can you add the support for the Paper `AsyncChatEvent` and/or `AsyncChatDecorateEvent` in the configuration of your plugin please?
Because you're currently using an old listener: `org.bukkit.event.player.AsyncPlayerChatEvent`. 

Example for a new configuration:
```yml
# Use Paper's async Chat Event
use-async-chat: true/false
```

Thank you so much if you add this! :)

**Comment by SirYwell** [comment]
What would be the benefit of adding it? What exactly is the problem with the current code?

Just note, we can't just switch to paper events for several reasons:
- we still need to support spigot, so we need to maintain two very similar code paths
- we can't reference adventure types in our code (not even implicitly) as they would be remapped to our relocated adventure versions. This is a limitation of the way adventure is designed/distributed/provided.

**Comment by OneLiteFeather** [comment]
I hope this enhancement is really meant seriously, it is the third repo with the exact same issue from the same user. The main reason someone would prefer this option is a console output that suggests using it.

**Comment by NoltoxGit** [comment]
> What would be the benefit of adding it? What exactly is the problem with the current code?
> 
> Just note, we can't just switch to paper events for several reasons:
> 
> * we still need to support spigot, so we need to maintain two very similar code paths
> * we can't reference adventure types in our code (not even implicitly) as they would be remapped to our relocated adventure versions. This is a limitation of the way adventure is designed/distributed/provided.

Hello,
That's why I suggested a toggle, as is already the case for this :
```yml
  # Use Paper's async tab completion
  async-tab-completion: true
 ```

**Comment by NoltoxGit** [comment]
> I hope this enhancement is really meant seriously, it is the third repo with the exact same issue from the same user. The main reason someone would prefer this option is a console output that suggests using it.

Yes, I take it seriously,
And it's the [SignedVelocity](https://github.com/4drian3d/SignedVelocity) plugin that recommends using it.

**Comment by NotMyFault** [comment]
No response, assume no longer relevant.
