### ISSUE TITLE
Link not clickable when doing /plot download using legacy downloader

### ISSUE THREAD

**Issue by braceyourself07** [IntellectualSites/PlotSquared#4306]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

When using `/plot download` it will successfully make a schematic and send to the downloader, but the link is not clickable.  I had to switch to the a legacy downloader because of the "Bad Gateway" errors on arkitektonika seem to be happening more frequently.

### To Reproduce

In `/plugins/PlotSquared/config/settings.yml` change url: to a legacy uploader and set legacy-webinterface: true

In-game, go to a plot and type `/plot download`  It will produce a link, but you will not be able to click on it.

### Expected behaviour

Should be able to click on the download link.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/7e6b402a99504151b12be50b596c78d2

### PlotSquared Version

7.3.2

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by jvstinxz** [comment]
I just tested this, when you run /p download, the same link is sent twice, the first one is clickable and the second one is not, in principle it should only be removed that the same link is sent twice but that is nothing important.
![Screenshot 2024-02-15 171257](https://github.com/IntellectualSites/PlotSquared/assets/95958782/58405a10-7db4-41e5-9943-19dedf99a661)

**Comment by braceyourself07** [comment]
Is there any difference in the two messages? I only see one, so I'm assuming our chat plugin is canceling the other one.

**Comment by jvstinxz** [comment]
Both links are the same, only the second one is not clickable, the first one is.

**Comment by braceyourself07** [comment]
I mean, on the plugin level are the two lines of text broadcasted in different ways.
