### ISSUE TITLE
The permission issue I found in Minecraft 1.20.1.

### ISSUE THREAD

**Issue by lsz3399747433** [IntellectualSites/PlotSquared#4307]
### Server Implementation

Mohist

### Server Version

1.20.1

### Describe the bug

Hello, this plugin is great. I've been using it since Minecraft 1.7.10. However, in version 1.20.1, I encountered an issue. While the plugin successfully protects vanilla items in claimed territories, it fails to protect mod items. Even though destruction and placement are prohibited, players can still open and interact with these items.

### To Reproduce

This is the ID of my regular permission group for testing, and it has no permissions.
![b4e93f7c8c8e62e369a1db1296530c21](https://github.com/IntellectualSites/PlotSquared/assets/154571421/3503f171-58ec-42f8-8659-e350f5609ce4)
However, when I use mod items, it appears to ignore the restrictions, and I can open, take, and manipulate items freely.
![image](https://github.com/IntellectualSites/PlotSquared/assets/154571421/fef55352-9657-4092-8f7c-58bbaf916042)
![image](https://github.com/IntellectualSites/PlotSquared/assets/154571421/128b3b9e-9377-47b2-91aa-c30a9d135ad6)
![image](https://github.com/IntellectualSites/PlotSquared/assets/154571421/7ad6243c-00bd-4b47-9279-413d3b2febb5)
![image](https://github.com/IntellectualSites/PlotSquared/assets/154571421/9a5d5b04-7b97-47e5-bfad-4d7d2ef79bec)

### Expected behaviour

I hope to protect players' belongings.
Perhaps I have a configuration issue?

### Screenshots / Videos

![d6f6e380f86a4c0327dda554b00eb733](https://github.com/IntellectualSites/PlotSquared/assets/154571421/5f1fbb6d-84ff-4f05-8e23-72e1ed65aa91)
![1d2e65ee1e9988bcd43fb5f480c8c168](https://github.com/IntellectualSites/PlotSquared/assets/154571421/6bc575a4-7bd8-487a-bc8a-99b47d40deda)
![f01ebf810735cd34f0f18cbdaa5d469c](https://github.com/IntellectualSites/PlotSquared/assets/154571421/16a56e45-5197-4d5f-89ce-93d75f9ddf33)

### Error log (if applicable)

It runs perfectly fine without any error messages.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/975735a3b8b64ae5bad42d0c37db61db

### PlotSquared Version

plotsquared-bukkit-7.3.2-SNAPSHOT

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by SirYwell** [comment]
[Hybrids](https://madelinemiller.dev/blog/minecraft-hybrid-servers/) are not supported.
