### ISSUE TITLE
Armor stand doesn't count in entity-cap or don't get destroyed while kill-road-mobs: true

### ISSUE THREAD

**Issue by thatnickisgeek** [IntellectualSites/PlotSquared#4313]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

I'm using the latest Plotsquared V7 version on Paper 1.19.4 with config options kill-road-mobs (kill-road-items, kill-owned-road-mobs, etc), but they while armor stand appears on the road via /ast or you can push them with slime blocks without this plugin, they won't kill. 

Also armor stand doesn't count in entity-cap, they can be placed even if they're more than limit provided by this flag.

### To Reproduce

1. Set kill-road-mobs to true in config
2. Push armor stands on road
3. Set entity-cap plot flag to 5 and you can place more than 5 armor stands on plot even with this flag

### Expected behaviour

Armor stands getting killed on the road and entity-cap limiting armor stand entities

### Screenshots / Videos

Video: https://imgur.com/a/kH1Ct5F

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/680ca9432b3a4d378e3ee001726eb581

### PlotSquared Version

Plotsquared-7.3.2-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
That is not something we can control actually AST has to implement a better solution to their Plotsquared Support. You can open this issue there. You can retry with a different Armorstand tool like Armorstandeditor Reborn by Wolfieheart (that's just personal suggestion) if he did it slightly different, it should have a Plotsquared Support too by now.

Also, if you manage to replicate it without these Armorstand Plugins, feel free to open an issue again.

**Comment by thatnickisgeek** [comment]
I've tested another methods of pushing armor stands into the road and they're getting killed. Thank you for this suggestion. 

But I have another problem with misc-cap and entity-cap, because I can spawn armor stands even if the limit is reached, but not any other entities. So the problem is that armor stand count in entity-cap and misc-cap, but they can be spawned anyway.
![2024-02-05_05 05 54](https://github.com/IntellectualSites/PlotSquared/assets/158232986/31108e45-ed81-47bf-8721-a8fb6c495f20)
![2024-02-05_05 08 01](https://github.com/IntellectualSites/PlotSquared/assets/158232986/3d91644e-f96f-4354-86c6-e340f34de89c)

**Comment by OneLiteFeather** [comment]
We found out that the armorstands can be set in an unlimited way which isn't about the AST plugin this creator of this issue had, but is part of this issue, so we can track it here
