### ISSUE TITLE
correct plot count placeholder

### ISSUE THREAD

**Issue by Xmike24** [IntellectualSites/PlotSquared#4314]
### What feature do you want to see added?

Hey guys, my idea is a new placeholder that shows the number of plots by a player. 
I know there is already this placeholder: `%plotsquared_plot_count%` 

But merged plots are not observed. The new placeholder should do that. 
So what I mean by that is, if I have, for example, 2 plots and merge them into one plot, I only have 1 large plot and not 2.

For example, the new placeholder could be like this: `%plotsquared_correct_plot_count%`

Here are a two more examples:

```
Example 1

Permission for 12 Plots: 
- 5 Plots not merged 
- 2 times a two merge
- one threesome merge
     - %plotsquared_plot_count% = 12
     - %plotsquared_correct_plot_count% = 8
```

```
Example 2

Permission for 15 Plots: 
- a ten plot merge 
- 5 not claimed plots
     - %plotsquared_plot_count% = 10
     - %plotsquared_correct_plot_count% = 1
```

### Are there any alternatives?

Unfortunately there is no alternative because the placeholder %plotsquared_plot_count% unfortunately does not take this into account.

### Anything else?

Thanks for the attention. 
I hope that I can use these placeholders at some point.

**Comment by NotMyFault** [comment]
Your assumption is incorrect. Merged plots do count as separate plots nonetheless.
