### ISSUE TITLE
%plotsquared_currentplot_flag_fly% 

### ISSUE THREAD

**Issue by fadfhkdfga** [IntellectualSites/PlotSquared#4315]
### What feature do you want to see added?

%plotsquared_currentplot_flag_fly%

It is not output as 'true' or 'false.
(Currently output as 'ENABLED' and 'DISABLED)

### Are there any alternatives?

.

**Comment by NotMyFault** [comment]
> It is not output as 'true' or 'false.
(Currently output as 'ENABLED' and 'DISABLED)

That is intended and sufficient for the user case to represent a boolean.
