### ISSUE TITLE
Allays cannot be breaded

### ISSUE THREAD

**Issue by Tamikaschu** [IntellectualSites/PlotSquared#4317]
### Server Implementation

Paper

### Server Version

1.20

### Describe the bug

Since 1.19.1 Allays can be breaded. However they do not return the SpawnReason.BREADING since no other allay is needed to produce a new one. The Allay is the only mob returning SpawnReason.DUPLICATION when breaded. Unfortunately is that SpawnReason counted as natural Mobspawning at the moment, which makes no sense since the Allay is not able to duplicate on its own or randomly.

### To Reproduce

1. Spawn Allay
2. Play a music disk
3. Give the allay a amethyst shard

### Expected behaviour

Allays should be breaded when Breading is enabled

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/b98c0722fa824fd08f18cedd51a6ff6b

### PlotSquared Version

PlotSquared version 7.2.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
Can reproduce with paper 1.20.4 latest (409) and Plotsquared 7.3.4 Snapshot with breeding enabled
