### ISSUE TITLE
lectern-read-book flag prevents the removal of a book from lectern for all players

### ISSUE THREAD

**Issue by TheJonstone** [IntellectualSites/PlotSquared#4323]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

According to the wiki, the new `lectern-read-book` flag is intended to prevent players from removing books from the lectern ([Wiki Plot flag link](https://intellectualsites.gitbook.io/plotsquared/features/plot-flags#:~:text=True-,lectern%2Dread%2Dbook,-Prevent%20players%20taking)).

However, it also prevents trust/add players and plot owners from removing the book from the lectern.

As soon as a book has been added, it remains permanently in the lectern and the book can no longer be removed using the button. The only solution is to break the lectern.

Apparently the "Take Book" button/event is intercepted and terminated for all players, regardless of their authorization.

### To Reproduce

1. set `lectern-read-book flag` to `true`
2. place lectern
3. place book into lectern
4. open book in lectern
5. try to remove the book with the "Take Book" button

### Expected behaviour

I would expect that as an add/trust/owner player you can still take the book out of the lectern and this flag only applies to other players who don't have permission on the plot.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/4da2f0cb4f48480889ee49fa3a6da29e

### PlotSquared Version

7.3.2-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
I could reproduce this behaviour, but the question in detail is if the documented behaviour should stay the wanted behaviour or if the documentation lacks detail about your expected behaviour. So is it a bug or a feature? I tend to say it is a feature if it seperates trusted/owner players from those without membership/ownership.

**Comment by TheJonstone** [comment]
Hi @OneLiteFeather. I understand your thinking. But according to the documentation for the membership tiers ([wiki](https://intellectualsites.gitbook.io/plotsquared/features/plot-membership-tiers)), it says that at least the owner has "full control over the plot". This is no longer the case with this flag. The owner cannot fully use the block functions (as mentioned, the same applies to trusted and member (add) users.). For this reason, in my opinion, it is a error/bug.
