### ISSUE TITLE
WorldEdit masking issues (unknown cause / cannot replicate)

### ISSUE THREAD

**Issue by WilliamEstrela** [IntellectualSites/PlotSquared#433]
I'm hum problem , players with WorldEdit can USE sphere of command and accentuate as Streets

**Comment by EvilOlaf** [comment]
http://hastebin.com/momibayocu
from IRC

**Comment by boy0001** [comment]
WorldEdit version is 6.1?

**Comment by WilliamEstrela** [comment]
Yes

**Comment by logicalPolaris** [comment]
I'm having the same issue on WorldEdit 6.0 (and 6.1).

**Comment by boy0001** [comment]
Can you post your startup log, and instructions on how to bypass WorldEdit restriction?

If you were previously op, can you verify that you have since reconnected since being deopped?
Can you also verify that you do not have permission for `/plot wea` as if you do, then that would be the reason for bypassing worldedit.

**Comment by logicalPolaris** [comment]
http://hastebin.com/saxugukuyo.js

WorldEdit restriction can be bypassed by giving the permission, "plots.worldedit.bypass".

My players do not have permission to /plot wea. They have never been opped.

**Comment by WilliamEstrela** [comment]
What should I give permission ?

**Comment by boy0001** [comment]
In your startup log:
```
**********************************************
** This WorldEdit version does not fully support your version of Bukkit.
**
** When working with blocks or undoing, chests will be empty, signs
** will be blank, and so on. There will be no support for entity
** and biome-related functions.
**
** Please see http://wiki.sk89q.com/wiki/WorldEdit/Bukkit_adapters
**********************************************
```

**Comment by logicalPolaris** [comment]
That could be. I updated back to 6.1. I will get back to you with an update as to whether this fixed or not.

**Comment by Sauilitired** [comment]
@logicalPolaris Any updates?

**Comment by Sauilitired** [comment]
No further information was provided, and thus I've decided to close this ticket. It can be reopened if more information is provided.

**Comment by logicalPolaris** [comment]
Hello! I just found out (the hard way) that the problem still exists! I'm running the latest of WorldEdit, WorldGuard, and PlotSquared.

**Comment by MattBDev** [comment]
Is this issue still relevant?

**Comment by MattBDev** [comment]
Assuming to be no longer relevant and a resolved issue.
