### ISSUE TITLE
Individual plots are deleted or reset after server restart without error in the console

### ISSUE THREAD

**Issue by Bachmann111** [IntellectualSites/PlotSquared#4331]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

  I have a local database at Plotquared and after a server restart individual plots were reset.   However, I cannot find an error in the logs.  

### To Reproduce

Use /stop on server.

### Expected behaviour

I hope you can help me so that no more plots are deleted. And i have tried the newest Version and its not work.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/0315ab1fe11b4204b9953d4d775954b1

### PlotSquared Version

PlotSquared Version 6.11.1.Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
Please retry with FastAsyncWorldedit and update paper to the latest patch of a version if not done yet. Also you can try Plotsquared as well with the latest version.

**Comment by OneLiteFeather** [comment]
<img width="408" alt="grafik" src="https://github.com/IntellectualSites/PlotSquared/assets/77929075/ecc0afe4-d435-434f-b0ea-f7c312096c93">
That remind me to look for your database purger and yes, the clearing of your plots is an enabled feature. Looks like your plots are somehow invalid and then purged
