### ISSUE TITLE
Incorrect plot spawn teleportation

### ISSUE THREAD

**Issue by Tamikaschu** [IntellectualSites/PlotSquared#4349]
### Server Implementation

Paper

### Server Version

1.20

### Describe the bug

(Everything is shown in the video)
If you set the plots spawn on top of any block which isn't a full block (carpet, slab, etc.) and there is another block on the same x and z coordinate with a higher y coordinate you will always be teleported to the highest block instead of the plotspawn. However spawning on top of any block which isn't a full block wont cause any issue if there is no block anywhere above the plotspawn. 

### To Reproduce

- Place a carpet on your plot
- Set your plotspawn on the carpet
- Put a block somewhere above on the same x and z coordinate (e.g. 10 blocks higher)

### Expected behaviour

You should also be teleported to the correct plotspawn if there is a block anywhere above 

### Screenshots / Videos

https://www.youtube.com/watch?v=xNd22bAS8rk

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/7a31259fe5594e9ca76387b91515704f

### PlotSquared Version

PlotSquared version 7.3.5-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by Tamikaschu** [comment]
Apparently this is due to that the player will always be teleported to the highest block if the plotspawn is blocked. May it be worth creating a new Method getNextHighestBlock and teleport the player to the next highest block which is air?

**Comment by OneLiteFeather** [comment]
This is not bug just a preventation for home trapping. You can easily override that behavior with the `PlayerTeleportToPlotEvent` and set the origin home position at the event. 
PlotSquared use the same mechanic checks to prevent teleporting into a block. And carpet and slab is counted in minecraft as non air.

**Comment by Tamikaschu** [comment]
Every player who wants to build some kind of basement with carpets in it won't be able to set their plotspawn there (see picture). Replacing the getHighestBlock method with a getNextHighestBlock method would keep up the safty of not getting trapped and still teleport the players to the desired location or atleast not to the highest block available. I can see how you are not open for that though.
![image](https://github.com/IntellectualSites/PlotSquared/assets/98806122/72057aa1-309f-454f-95ef-1c877500a53f)
