### ISSUE TITLE
error when doing "plot unlink"

### ISSUE THREAD

**Issue by Misjudgments** [IntellectualSites/PlotSquared#4350]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

after a player merges a plot, he can't unmerge it because of an error when executing "/p unlink".

### To Reproduce

1. plot merge between two plots.
2. run "./plot unlink"

### Expected behaviour

unlink the plot without error.

### Error log (if applicable)

https://paste.gg/p/anonymous/15e6578a53a94ea995d1d8c231781d3b

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/007f7288375d4b389074968c36ee6523

### PlotSquared Version

5.13.13

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
Update PlotSquared, v5 is two major versions behind.
