### ISSUE TITLE
Silk Touch enchantment does not work with instabreak flag

### ISSUE THREAD

**Issue by jvstinxz** [IntellectualSites/PlotSquared#4358]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

The enchantment Silk Touch cannot be used with the instabreak flag

### To Reproduce

1. Enchant a tool with silk touch
2. Set instabreak flag to true
3. Break a block (e.g. stone) with the tool

### Expected behaviour

A clean stone block should drop instead of a cobblestone

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/861ed71f0e034f50b1e06a8219e498a8

### PlotSquared Version

7.3.5-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
Hello there, you can break blocks with your hand instantly, it ignores the tool you have in your hand completely. That is rather a not implemented feature to consider the tool with the enchantment than a bug.
