### ISSUE TITLE
/p sethome

### ISSUE THREAD

**Issue by LordVardus** [IntellectualSites/PlotSquared#4360]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

Hello, I hope I'm in the right place, I wanted to ask some questions. If I am on a plot and go to the plot and do /p sethome, I move the spawn pucks but when other players go to the plot with /p h Kingkonzu 2 the spawn that are on the edge of the plot and not to the new one / p sethome spawn point
What do I have to do to get to the new chip pucks or is it not possible?

### To Reproduce

/p sethome

### Expected behaviour

hope that's not a mistake

### Plot Debugpaste

no

### PlotSquared Version

7

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by Tamikaschu** [comment]
Similar to https://github.com/IntellectualSites/PlotSquared/pull/4348 ?

**Comment by OneLiteFeather** [comment]
@LordVardus Your issue lacks details about the right plotsquared and fawe/worldedit version and therefore it is invalid. Please consider opening a valid issue and use the template. Also a picture of the plothome location could be useful.

**Comment by OneLiteFeather** [comment]
> FastAsyncWorldEdit 2.8.4 WorldEdit 7.2.20 PlotSquared 7.3.5
> 
> worlds.yml
> 
> home: default: side allow-nonmembers: false

Thanks for the quick reply. Why do you have worldedit and FastAsyncWorldedit? Also do you have a /plot debugpaste link for us?
