### ISSUE TITLE
Kgenerators placing in other plots

### ISSUE THREAD

**Issue by Kristupas122** [IntellectualSites/PlotSquared#4361]
### Server Implementation

Spigot

### Server Version

1.20

### Describe the bug

Kgenerator plugins gens placing and duping  and thats what i found on their dc thats what they said before

It’s at most using some of worldguards logic in their code, it’s not using wg in entirety at all.
Kgens places blocks without using the block place function as you already know. The bug happens because plotsquared does not “look for” kgens placing function in their logic of restricting players. Tell them to add support to kgens 

### To Reproduce

“look for” kgens placing function in  logic

### Expected behaviour

not allowing people placing gens not in their plots

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/837aacb977aa45f499c4523274cd6c98

### PlotSquared Version

7.3.5 Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by PierreSchwang** [comment]
That's on their plugin to support PlotSquared and check for plot boundaries.
