### ISSUE TITLE
MAJOR ISSUE - crash servers

### ISSUE THREAD

**Issue by GogleSiteBank** [IntellectualSites/PlotSquared#4363]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

Doing /p 10000000;10 claim or /p v 10000000;10 on any server will allow you to crash it, this is likely because its loading too far or crossing a limit, also while were here please tell me which permission will disable /p <x:y> claim

### To Reproduce

1. Join a server
2. /p 10000000;10 claim
3. crash

### Expected behaviour

For the server not to crash

### Screenshots / Videos

![image](https://github.com/IntellectualSites/PlotSquared/assets/125816677/f53d77f5-a38e-47a1-95c0-3052db85852d)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/fdfa899433c24d109264365cb35f4215

### PlotSquared Version

7.3.6

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by PierreSchwang** [comment]
Duplicate #4340

**Comment by rmalca** [comment]
This also happens with swap and move.
