### ISSUE TITLE
Plotsquared - First Plot Price

### ISSUE THREAD

**Issue by LordVardus** [IntellectualSites/PlotSquared#4364]
### What feature do you want to see added?

Hello, I have a problem with Plotsquared and I can't find a solution anywhere. But somehow I can't imagine that I'm the only one... maybe I'm the only stupid one :)

### Are there any alternatives?

My problem
I entered a price for the plot claim at Plotquared, but how can I enter that the first plot is free?

I look forward to your answer

It should be like this that I can get 4 properties for $0 and each additional one should cost $500, something like that is possible

**Comment by SirYwell** [comment]
You can use the [WorldEdit expression syntax](https://worldedit.enginehub.org/en/latest/usage/other/expressions/)  and use `plots` as a variable. For example `plots < 4 ? 0 : 500` should result in the first 4 plots being free and all others 500.
