### ISSUE TITLE
Plots belong to Unknown

### ISSUE THREAD

**Issue by WsupPanda** [IntellectualSites/PlotSquared#437]
Can't teleport to plots, all /plot info returns owner: unknown, but the sign says the owner's name

**Comment by Sauilitired** [comment]
Did you recently clear the player files?

**Comment by boy0001** [comment]
Can you provide the following:
 - Startup log
 - Settings.yml
 - Offline or online mode?

Screenshot of `/plot debugexec seen <player>` - Where the player is some user that has `unknown` for the plot.

**Comment by Sauilitired** [comment]
@WsupPanda are you using online or offline mode uuids?

**Comment by boy0001** [comment]
@WsupPanda 
@Sauilitired Has made a new UUID caching system, which you could try out. Could you still please provide the information requested above?

**Comment by Sauilitired** [comment]
Closing due to insufficient information. Can be re-opened if more information is provided.
