### ISSUE TITLE
/p deny bug

### ISSUE THREAD

**Issue by Theepwner** [IntellectualSites/PlotSquared#438]
If you deny a person from your plot, even if they aren't in your plot, they will still be moved to spawn or glitch under the world somehow.

I'd say this is an urgent bug since it's being abused on my server as we speak. I believe this bug (or a similar one) existed a few months ago.

**Comment by boy0001** [comment]
@Sauilitired

**Comment by boy0001** [comment]
ci.intellectualsites.com/job/PlotSquared/
