### ISSUE TITLE
Sheeps not grow back wool and dont eat grass

### ISSUE THREAD

**Issue by DevJoey** [IntellectualSites/PlotSquared#4385]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

If i shear a sheep on a plot it dont grow back wool and dont eat grass. I tested this for hours. If i do it in a normal (non plot world) it works just fine

### To Reproduce

Place sheep
shear it
see that the sheep not eat grass and so also not grow wool

### Expected behaviour

Sheeps should be able to eat grass. I set mob-break and entity-change-block flag to true and it still not works

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/d6a537a128ca4d7ebb9f4d5617919ba2

### PlotSquared Version

7.3.6-Premiun

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by dordsor21** [comment]
It's an issue in Paper PaperMC/Paper#9945
