### ISSUE TITLE
Plot clearing not removing full border

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/PlotSquared#439]
Here's my plotsquared config: http://pastebin.com/JgCNnSya (Using version 2.12.8/13)
I've got a picture of what happens after clearing a plot (/plot clear) which has a custom border: http://i.cubeupload.com/7iocoy.png
It's very strange but it also clears the custom border of other plots, as you can see in the picture the plot opposite me also had some wooden slabs leftover but it shouldn't have been affected because I didn't clear that plot. Here's a screenshot of the plot opposite with wooden slabs having some slabs set back to default while there is still some that are wooden even though it shouldn't have been affected.
(http://i.cubeupload.com/a4zlyQ.png)
If it helps, you can join my server and see what I'm talking about. Feel free to visit my plot as it's the one used in the picture (/plot visit SuperMonis)
IP: creativefun.eu (Make sure you use /server creative2)

**Comment by boy0001** [comment]
Disable fastmode clearing for the time being.

**Comment by boy0001** [comment]
The following issues with fastmode clearing have been fixed:
 - block data being set to 0 in plot chunks which are also set to the road if the chunks unload whilst plot clearing is taking place
 - block ids not being set correctly if the plot/road chunks have not been generated previously
