### ISSUE TITLE
Plot biome displaying incorrectly

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/PlotSquared#440]
Here's my plotsquared config: http://pastebin.com/JgCNnSya (Using version 2.12.8/13)
Not exactly sure what's wrong here, the actual plots show up as forest biome (Set in config) but when using /plot info it displays the plot as using something different, my users don't have access to set the biomes of their plot.
Screenshot 1:
![savanna](https://cloud.githubusercontent.com/assets/10485646/8824182/724acc08-306b-11e5-99ea-e77569e9dcc3.png)

Screenshot 2:
![desert](https://cloud.githubusercontent.com/assets/10485646/8824198/99ce8e68-306b-11e5-8981-63884a48b8b0.png)

Screenshot 3:
![deep_ocean](https://cloud.githubusercontent.com/assets/10485646/8824187/7eaa3cc2-306b-11e5-8e39-ec58d8c701dd.png)

**Comment by Sauilitired** [comment]
Looks like it's using the biomes from some other world, with the same coordinates. Are you running more than one world on the server? Cause if so, then you could possibly confirm or deny this claim :dancer:

**Comment by SecretlyJealous** [comment]
I'm not running more than one world.

**Comment by boy0001** [comment]
Merging with #455
