### ISSUE TITLE
Cyclic plugin loading

### ISSUE THREAD

**Issue by Leahcimkrob** [IntellectualSites/PlotSquared#4405]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

Hello, since the new Lands version the server keeps crashing.
The dev from Lands said there is a bug with you. since it's only ever when I want Plotsquard in addition to Lands. Only Lands works and only Plotsuqared too.

### To Reproduce

Start server with Plotsquared  7.3.7 or  7.3.8 and Lands 7.0.8 final (same Issue)

### Expected behaviour

Server Start without any issue

### Error log (if applicable)

https://mclo.gs/F8rhnBu

### Plot Debugpaste

 https://athion.net/ISPaster/paste/view/9f0751ec7fee465d80eb18ca8d23b111

### PlotSquared Version

 7.3.7-Premium /  7.3.8-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by PierreSchwang** [comment]
PlotSquared does not depend on any of the listed plugins in the cyclic loop - so that's up to the other plugins.

> Please report this to the plugin authors of the first plugin of each loop or join the PaperMC Discord server for further help
Which would be CMI in that case I guess. Based on https://github.com/Zrips/CMI/issues/8447 that should be fixed already.
