### ISSUE TITLE
/plot flag set heal <value>

### ISSUE THREAD

**Issue by jay171717** [IntellectualSites/PlotSquared#4406]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

server version: 1.20.2 paper
server name: synergy

so when u do /plot flag set heal with value it changes thing entirely

>>Bug happens when you set spawn in my plot and die in my plot(i.e where u changed the heal flag)

>>When u die there are 3 phases where u can go:
      
1.You go in gltched death state and u still have your items(even if keepinv off) and you can respawn in the same place where u died.....(fixes when relog)
2.You can in a Plane blank white void, you can hear ur surroundings, others dont know your presence, you cant read chat, but cant send a message/command.....(fixes when relog)

3.(this depends on second phase and is rare)  You go in black void going down(f3) same as what happens in second...(MAYBE fixes when relog)
if you threw a lingering kill pot right next to your bed and die, then u come here, when u go in this phase the chunks are unloaded! so that means your kill plot is unloaded and when u try to relog, YOU KEEP GETTING IN THIS PHASE, no escape except someone comes and loads the chunks for you, and thats your only escape

I can change the other values of /plot flag set heal, but it doesnt affect the side effects of it.
It says the default value is "0" but when i try to put 0, it says "the input must be a whole number"

### To Reproduce

GO to your plot
do /plot flag set heal <value> (number value like 4)
set your spawn in same plot and die
that's it

### Expected behaviour

it should have only changed the natural regen instead of changing natural regen AND THIS BUG

### Screenshots / Videos

![2024-04-20_18 39 22](https://github.com/IntellectualSites/PlotSquared/assets/97662632/3c46d697-4e8a-4497-8905-64adbca63590)
![2024-
![2024-04-06_12 29 19](https://github.com/IntellectualSites/PlotSquared/assets/97662632/36d1c9f8-a4b0-49a0-9c73-9da1deb
![2024-04-01_22 48 46](https://github.com/IntellectualSites/PlotSquared/assets/97662632/e360c0ba-ca1b-42dd-ad2b-eda5ab1afaf0)
5e93f)
04-20_18 40 08](https://github.com/IntellectualSites/PlotSquared/assets/97662632/c0f487d6-5c50-4353-93ac-c440e698c782)

### Plot Debugpaste

i am not the admin so idk

### PlotSquared Version

PlotSquared-7.3.6-Premium

### Checklist

- [ ] I have included a Plot debugpaste.
- [ ] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

Yeah sorry about ticking those 2 options but cant really help with it

**Comment by jay171717** [comment]
i sent 2 more ss and 1 video but didn't showed

**Comment by PierreSchwang** [comment]
I can reproduce that somehow, as I can't click on respawn whatsoever. So I guess that's kinda the same outcome

**Comment by jay171717** [comment]
> I can reproduce that somehow, as I can't click on respawn whatsoever. So I guess that's kinda the same outcome
> 
> ~That is only sometimes tho~ It's just depending on the duration and current tick

**Comment by jay171717** [comment]
No u cant respawn normally, but when u go "tittle screen" wait few seconds, u will be able to hit respawn and then go in f5, now try this process multiple times and u will find other phases as well

**Comment by jay171717** [comment]
we can get in a call n explain properly, its a big issue and the ones changed the values of it, cant undo it in the plot

**Comment by jay171717** [comment]
![2024-03-17_16 37 42](https://github.com/IntellectualSites/PlotSquared/assets/97662632/4a91e7a5-2f58-405e-9173-67a5c28bbe67)
![2024-04-01_22 48 46](https://github.com/IntellectualSites/PlotSquared/assets/97662632/318eddf9-6273-4147-8ada-fd853eb89689)

**Comment by jay171717** [comment]
Uploading 2024-04-20 17-55-31.mp4…

**Comment by jay171717** [comment]
https://github.com/IntellectualSites/PlotSquared/assets/97662632/b849fea8-8e2c-48da-a4a0-c3952f835422

**Comment by jay171717** [comment]
these are the 2 ss and the video which didn't uploaded last time

**Comment by jay171717** [comment]
is this fixed or smt? as u closed the post?
