### ISSUE TITLE
bug or not a bug?

### ISSUE THREAD

**Issue by rimrimat** [IntellectualSites/PlotSquared#442]
![2015-07-22_08 30 38](https://cloud.githubusercontent.com/assets/4743662/8830891/5e875680-30d1-11e5-833a-2168c8d2f818.png)

Vardengalaxy Network  Prison Server :play.vardengalaxy.us.to
warpname :plots2 or vgplots2

plugin was fine and working well but i have no idea what caused it or when: i have scanned our server logs but i have found nothing. we are using spigot 1.8 for the prison server.

tnx for your time.
note: plot commands has been disabled to all players

**Comment by Sauilitired** [comment]
Try `/plot debugroadregen`, to see if the road generates properly. And please use `/plot debugpaste` to generate a file which can help us track the issue down.

**Comment by Sauilitired** [comment]
Closing due to insufficient information. Can be re-opened if more information is provided.
