### ISSUE TITLE
Latest Update Not Working

### ISSUE THREAD

**Issue by Clarkcj12** [IntellectualSites/PlotSquared#4422]
### Server Implementation

Paper

### Server Version

1.20

### Describe the bug

Upon upgrading PlotSquared to the latest version that just released getting an error saying Plugin isn't up to date and then won't load.

### To Reproduce

1. Upgrade PlotSquared Plugin to latest version
2.  Start Server

### Expected behaviour

Plugin should load successfully.

### Error log (if applicable)

https://paste.gg/p/anonymous/1a2f427eaf8f40dda4d640328ae9eabd

### Plot Debugpaste

d

### PlotSquared Version

7.3.8-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

Can't put plot debug paste since plugin isn't loading.

**Comment by SirYwell** [comment]
That's a problem of your server software, not PlotSquared.
