### ISSUE TITLE
Expired Command Request

### ISSUE THREAD

**Issue by Nomizak** [IntellectualSites/PlotSquared#443]
I'm a server owner and have been using PlotMe for a while (about 3 years now!). PlotMe has a command called /plotme expired, which lists all plots that have expired so that our staff can tp to them and take a look before clearing. In our case, we set them to expire in 10 days. After 10 days, the plot would appear in the expired list. 

I was wondering if PlotSquared has a similar command? I understand there is an expiry system that autoclears old plots, but our server is set up in such a way that we want to check the plot before clearing it manually. Sometimes we want to save the good ones.

I searched through PlotSquared's wiki and haven't found a command or feature for this. I've reviewed your plot analysis feature, which I find to be pretty unique, but isn't quite what we're looking for. If a feature like /plotme expired doesn't exist, I would like to post this as a suggestion. Thank you for your time and I appreciate all the wonderful work you guys have done to make this amazing plugin!

**Comment by boy0001** [comment]
`/plot debugexec update-expired`
`/plot debugexec show-expired`
