### ISSUE TITLE
(missing feature/request ?) letting fly in your plot only

### ISSUE THREAD

**Issue by oDeathwingo** [IntellectualSites/PlotSquared#444]
A permission and/or auto flag to let yourself to fly in your plot only.. and maybe a flag to let other users/friends to fly in your plot aswell

**Comment by boy0001** [comment]
https://github.com/IntellectualSites/PlotSquared/wiki/Flag:-fly

**Comment by EvilOlaf** [comment]
I guess he wanted to have a flag to let everybody fly on a plot except added players.
It seems like the current fly flag allows only added players to fly.

**Comment by oDeathwingo** [comment]
well I was looking for a fly flag for all players "so even not added players can fly in the plot" and a fly flag that works as current one does

**Comment by MattBDev** [comment]
Players can fly in a plot with the fly flag even if they are not added to the plot. I am assuming this is what the request was for.
