### ISSUE TITLE
Unlinking/Unmerging Section of a Merged Plot

### ISSUE THREAD

**Issue by ghermm** [IntellectualSites/PlotSquared#4446]
### What feature do you want to see added?

Add the ability to unlink/unmerge one plot out of a merged group of plots. Currently, if you use /plot unlink, it unlinks the entire group of plots instead of the one you're standing in. This, in my eyes, is poor design. 

### Are there any alternatives?

Not that I know of. 

### Anything else?

Did I mention it's poor design?

**Comment by dordsor21** [comment]
Duplicate of #3733
