### ISSUE TITLE
Sheep and Bee

### ISSUE THREAD

**Issue by sanabee** [IntellectualSites/PlotSquared#4449]
### Server Implementation

Spigot

### Server Version

1.20.4

### Describe the bug

Sheep cannot eat after they have no wool left. The same is true of bees, once they are in their nest they cannot get out.

### To Reproduce

Sheep:
1. Build an enclosure with grass
2. Place sheep on the grass.
3. Remove wool.
4. Sheep don't eat.

Bees:
1. Place a bee nest on a tree
2. Place flowers around the bee nest.
3. Spawn bees with an egg.
4. Bees go into the nest and don't come out again

### Expected behaviour

Meine Erwartung ?
Das schafe grass fressen, damit die wolle nach wächst und das die Bienen wieder aus dem Nest kommen.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/37aa910899e84dd699842a7b5e932b3c

### PlotSquared Version

7.3.8-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by dordsor21** [comment]
Sheep is an issue with spigot/paper calling odd events due to weirdness within Minecraft itself, and bee hives is tracked by #3033

**Comment by sanabee** [comment]
Do I understand correctly that I can't do anything with the sheep?

thanks for the quick reply

**Comment by dordsor21** [comment]
I believe so yeah

**Comment by Tamikaschu** [comment]
> Do I understand correctly that I can't do anything with the sheep?
> 
> 
> 
> thanks for the quick reply

https://github.com/IntellectualSites/PlotSquared/issues/4233 i think u could just not cancel the event in the PaperListener manually. You would probably have to face other issues consequentially.

**Comment by sanabee** [comment]
I have set neutral mob spawning to on in the config and off in gamerule. Now the sheep are eating and getting wool. The bees are also coming out now but they are not giving any honey.
