### ISSUE TITLE
Titles not showing

### ISSUE THREAD

**Issue by GreenTeeDev** [IntellectualSites/PlotSquared#4453]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

When i go to plots no titles appear

### To Reproduce

go to a plot 

### Expected behaviour

seeing a plot title

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/a6917124056846ea9232e8f95b1dd11f

### PlotSquared Version

Plotsqueard V7

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by PierreSchwang** [comment]
Make sure you did haven't disabled titles for yourself (`/p toggle titles`)

Otherwise, does this affect all plots? Does the problem persist with just FAWE and PlotSquared?

**Comment by GreenTeeDev** [comment]
> Make sure you did haven't disabled titles for yourself (`/p toggle titles`)

i did still no title

 
> Otherwise, does this affect all plots? Does the problem persist with just FAWE and PlotSquared?

yes this problem is on all plots

**Comment by OneLiteFeather** [comment]
Can not replicate with Plotsquared 7.3.8 with a clean build and fresh setup with local server in 1.20.6. After that I claimed one plot and the title showed up. You have to take sure that none of your other plugins interacting with plotsquared are changing the behaviour if you want to see the plot titles. 

If I guess, it could be one of the command plugins or the citybuild plugin. It should work if you retry without them. If you find the plugin that does your issue, feel free to open an issue on their github repository instead
