### ISSUE TITLE
Entity Cap can be exceeded on merged plots

### ISSUE THREAD

**Issue by EpicJosch** [IntellectualSites/PlotSquared#4459]
### Server Implementation

Paper

### Server Version

1.20

### Describe the bug

When i plot is not merged everything works fine. But when a plot is merged players can exceed the entity-cap limit. For example i set a limit of 20 entities. But the player placed 28 entities and the cap still showed 18/20 entities. So there is something calculated wrong. Please fix this its a really big problem!

### To Reproduce

1. Merge a plot
2. Set a entity-cap
3. Place entities

### Expected behaviour

Once 20 entities are placed on the plot players are not able to place another one

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/c561ab6e46f5473ea3b3a8282e25d4b2

### PlotSquared Version

PlotSquared v7 7.3.8

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by Tamikaschu** [comment]
Consider taking a look into https://github.com/IntellectualSites/PlotSquared/issues/4339 and https://github.com/IntellectualSites/PlotSquared/pull/4356
