### ISSUE TITLE
plot trim possibly resetting valid plots

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#446]
I did plot trim for my donor world which has 500x500 plots, and I am now getting a few reports that portions or all of some peoples plots are deleted. Please double check this function to make sure its not deleting valid plots

**Comment by PhanaticD** [comment]
screenshot of one such case: http://gyazo.com/b20003d35b3ee05d061e9d147f2db8ff

**Comment by boy0001** [comment]
Could you do a `/plot debugpaste` and send that please?

**Comment by PhanaticD** [comment]
http://pastebin.com/5cixYCZ8

**Comment by boy0001** [comment]
@Sauilitired 
Your paste thing is broken it seems.

@PhanaticD 
Anyway, that would be the settings.yml please.

**Comment by Sauilitired** [comment]
@boy0001 Works fine for me. Must have been the file size or something :<

**Comment by PhanaticD** [comment]
here you go: http://hastebin.com/eqelurilej.sm
