### ISSUE TITLE
Upgrading to 1.20.6 breaks plot titles

### ISSUE THREAD

**Issue by Virologicbody** [IntellectualSites/PlotSquared#4465]
### Server Implementation

Paper

### Server Version

1.20.6

### Describe the bug

Server running Paper 1.19.2 - plot titles work as expected.
Upgarded the server one version at a time (while updating plugins to corresponding versions) - plot titles work as expected.

When server version gets to Paper 1.20.6 - plot titles stop working.

### To Reproduce

Run pre-existing server on version lower than 1.20.6

Upgrade server to version 1.20.6 - titles break

### Expected behaviour

Titles should continue to work after upgrading to 1.20.6 as there have been no user changes in any of the files or configs.

### Screenshots / Videos

![Paper-1 20-17 Plugins](https://github.com/user-attachments/assets/ef73a335-add0-4b0b-9a93-de7011560b71)

![Paper-1 20 6-148 Plugins](https://github.com/user-attachments/assets/851e77e8-e178-47d9-926c-47cc8387f0c7)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/c0a585329d5041d495d5cf600fd62b8d

### PlotSquared Version

plotsquared-bukkit-7.3.8-premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

debug paste from last Paper version I tried (1.20) with working titles:
https://athion.net/ISPaster/paste/view/93a107e0c53b4deea92bdd3f6339e869

**Comment by PierreSchwang** [comment]
Will most likely work when a new release is cut - when building PlotSquared based off the latest commit it should work.

(https://github.com/IntellectualSites/PlotSquared/pull/4440)

**Comment by PierreSchwang** [comment]
Should work now again with the latest release.
