### ISSUE TITLE
ways regen

### ISSUE THREAD

**Issue by Tamino112** [IntellectualSites/PlotSquared#4468]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

I generated the paths then there was an error with the generation then I fixed it and wanted to regenerate the paths but now when I enter plot regenallroads CB1 in the console I get this error

[P2] If no Schematic has been created, this action will not produce any results. To create a schematic, navigate to a plot and type //plot createroadschematic.
[09.08 09:11:37.006] INFO: [CB-1] [09:11:36 INFO]: [P2] PlotSquared will now try to generate the streets according to your input. Depending on the size of your world, this task may take a long time.
[09.08 09:11:37.007] INFO: [CB-1] [09:11:36 INFO]: [P2] You cannot perform another schematic update. (There may already be one in the works.)

### To Reproduce

![image](https://github.com/user-attachments/assets/dcc6efc1-716b-4df4-98cb-06be9a3cee43)

### Expected behaviour

I would like the generation to work again

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/8dfb29bc-dc61-4802-bbec-ba302d432cb7)

### Error log (if applicable)

https://paste.gg/p/anonymous/a3fbe8b36c934f8e9174b85c0a7f30b4

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/1752ee2b58a24b3eafd1593c84b6168a

### PlotSquared Version

plotsquared-bukkit-7.3.8-Premium.jar

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by PierreSchwang** [comment]
You may want to stop the server, delete the `persistent_regen_data_CB1` folder and then start the server. You should be able to trigger a new road update then.
