### ISSUE TITLE
Issue with Container Protection in PlotSquared 7.3.8-Premium

### ISSUE THREAD

**Issue by nanana90** [IntellectualSites/PlotSquared#4469]
### Server Implementation

Spigot

### Server Version

1.20.6

### Describe the bug

Dear PlotSquared development team,

I hope this message reaches you well.

I am contacting you to report a problem with the container protection feature in PlotSquared version 7.3.8-Premium. According to the documentation, this feature should automatically prevent players from accessing chests and barrels belonging to other players. However, I have noticed that this protection is not working as expected on my server.

By creating a new account on the server without any rights in normal survival mode, this account was able to access chests and barrels inside and outside the plots and steal items.

This should not be possible with the premium plugin.

Could you please help me with troubleshooting or give me some hints on how to make sure the container protection feature is working correctly?

Thank you for your support.

### To Reproduce

Create an empty 1.20.6 server on Bungeecord System

install yet:

2FAGuard
ArmorStandTools
BankPlus
BungeeGuard
BungeeTeleportManager
CleanroomGenerator
ColoredSigns
CratesPlusReloaded
CustomJoinAndQuitMessages
DiscordSRV
DiscordSRV-Staff-Chat
FarmingWorld
GFly
IPWhitelist
ItemEdit
LiteBans
lightEconomy
LuckPerms
Multiverse-Core
Multiverse-NetherPortals
Multiverse-Portals
PlaceholderAPI
PlotSquared
PowerBoard
RayzsAntiCrasher
RHSignItem
SimpleScore
SpawnProtect
SuperVanish
Vault
VotingPlugin
WorldEdit
WorldGuard

On "world" use /plotsquared setup to create a plotworld.

Now set "default" permission node in lp:

+-----------------------------------------------+-------+---------+-------+
|                  Permission                  | Value | Expires | Context |
+-----------------------------------------------+-------+---------+---------+
| plots.set.flag.animal-interact.*     | false | never   | none    |
| plots.set.flag.hostile-interact.*     | false | never   | none    |
| plots.set.flag.misc-interact.*        | false | never   | none    |
| plots.set.flag.player-interact.*      | false | never   | none    |
| plots.set.flag.tamed-interact.*     | false | never   | none    |
| plots.admin.interact.other           | false | never   | none    |
| plots.denied                                | true  | never   | none    |
| plots.home                                  | true  | never   | none    |
| plots.info                                     | true  | never   | none    |
| plots.remove                               | true  | never   | none    |
| plots.use                                     | false | never   | none    |
| plots.claim                                  | true  | never   | none    |
| plots.auto                                   | true  | never   | none    |
+-----------------------------------------------+-------+---------+---------+

sync all existing lp permissions, restart the server and try with an normal user to open chests on other players plots. It is possible.

Thanks in Advance.

### Expected behaviour

So i hope u have an idea, wich settings must be set aswell or hace alternative route to clear the issue.

### Error log (if applicable)

https://paste.gg/p/anonymous/bc7b8098852e467eb3744505c627d18c

### Plot Debugpaste

no bugs found

### PlotSquared Version

7.3.8-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by PierreSchwang** [comment]
Have you removed every plugin except PS + WorldEdit yet? If not, try that and see if the issue persists.

**Comment by nanana90** [comment]
> Have you removed every plugin except PS + WorldEdit yet? If not, try that and see if the issue persists.

i can try it later, so i would like aswell to get the limited PS Support on Discord, but can#t find andy dm button on the spigot webpage..... how can i verfy, that i#ve buyed the plugin?

**Comment by nanana90** [comment]
> Have you removed every plugin except PS + WorldEdit yet? If not, try that and see if the issue persists.

Issue with fresh install is still there:

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/6e0c7d44-776b-4b3e-92b8-c0032a0e93d8">

**Comment by nanana90** [comment]
@PierreSchwang Bist du da?

**Comment by PierreSchwang** [comment]
Can't reproduce 
![image](https://github.com/user-attachments/assets/8937d244-353c-4ebb-8b18-fc0587fde961)

**Comment by nanana90** [comment]
@PierreSchwang  

Spigot with problem and Paper without problem / same plugins. so the node: plots.admin.interact.unowned is not loaded or has no relevance for the plugin on Spigot......

can you check this with Spigot 1.20.6 version and Java 22?

Thanks in Advance

**Comment by PierreSchwang** [comment]
Can reproduce on plain spigot 1.20.6

**Comment by PierreSchwang** [comment]
That's an issue with Spigot: https://hub.spigotmc.org/jira/browse/SPIGOT-7813

@IntellectualSites/plotsquared-team Should a hot-fix be implemented for the named version?

**Comment by nanana90** [comment]
Hey @PierreSchwang ,

thanks for your feedback. 

I have already switched my community server to paper. 😁

So take your time 🤣

VG

BundleDog

**Comment by SirYwell** [comment]
> Should a hot-fix be implemented for the named version?

If there is a non-intrusive, simple fix, I guess that would be fine.

**Comment by PierreSchwang** [comment]
> > Should a hot-fix be implemented for the named version?
> 
> If there is a non-intrusive, simple fix, I guess that would be fine.

Not sure about that. One solution would be a set with all materials that are interactable - but not sure if that's a nice solution. CB does it via checking existing methods in the CraftMaterials (https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/a0d2d6a84540f3f2c73153876a0350237e0a8ddc)

**Comment by SirYwell** [comment]
Maybe it's good enough for us if we additionally check if the block has a container via WE Material. There might be other blocks where interaction is relevant, but that's probably less critical. Not sure though
