### ISSUE TITLE
Armor stand doesn't seem to be usable in the plot.

### ISSUE THREAD

**Issue by fadfhkdfga** [IntellectualSites/PlotSquared#4477]
### Server Implementation

Paper

### Server Version

1.21.1

### Describe the bug

Armor stand doesn't seem to be usable in the plot.

### To Reproduce

.

### Expected behaviour

.

### Plot Debugpaste

.

### PlotSquared Version

7.3.9-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by PierreSchwang** [comment]
What would be "usable"? And please fill the issue template accordingly.

**Comment by NotMyFault** [comment]
We cannot assist you with a blank issue.
