### ISSUE TITLE
Wither blowing up the plot wall

### ISSUE THREAD

**Issue by Teddyon** [IntellectualSites/PlotSquared#4479]
### Server Implementation

Paper

### Server Version

1.21.1

### Describe the bug

The Wither is able to break through the walls of a plot and damage the plot boundaries in the process.
No flags have been activated or deactivated on the plot. This is visible in the images below, the dirt inside the plot remains stationary and only the wall is damaged.

### To Reproduce

1. Spawn a Wither in a protected area (e.g. within a plot).
2. Have the Wither attack or explode near the plot walls.
3. Observe that the Wither destroys the walls of the plot.
![image](https://github.com/user-attachments/assets/eab9389e-a48c-4c88-9a06-4dd2b7d60771)

### Expected behaviour

Plot wall cannot be blown up by a wither

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/b5f006a9-db4f-4e2f-b5cf-46a213016cc8)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/b141067a747c40619d5431f82d33c1ff

### PlotSquared Version

PlotSquared-7.3.9-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
In the past, we did this https://github.com/IntellectualSites/PlotSquared/issues/1939#issuecomment-386931230 to prevent spawning a wither at all. But this one is known to me for a long time and can reproduce with a sword knockback-ing the wither to the wall.

**Comment by OneLiteFeather** [comment]
Can't really decide if that is a bug or a missing feature, as spawning a wither was never a thing you wanted in your plotworld in the past. But it can be used for griefing, which is bad.

**Comment by PierreSchwang** [comment]
> Can't really decide if that is a bug or a missing feature, as spawning a wither was never a thing you wanted in your plotworld in the past. But it can be used for griefing, which is bad.

Rather a bug. No entity should be able to destroy block out of the spawned plot.

**Comment by RedstoneFuture** [comment]
same issue: https://github.com/IntellectualSites/PlotSquared/issues/4524
