### ISSUE TITLE
Claimed block not reverting to unClaimed block when /plot unclaim is executed...

### ISSUE THREAD

**Issue by sammyg123** [IntellectualSites/PlotSquared#448]
Let me just explain the bug, when I stand on the plot and execute '/plot claim' or '/plot auto' then the slabs change to a different block (which I want) but then when I do '/plot unclaim' the slabs stay the same and don't revert back.

I was told I needed to provide a 'debugpaste' so here it is...
http://hastebin.com/eqadusoyiv

Thank you for your time, Sam.

**Comment by boy0001** [comment]
Use `/plot delete`
