### ISSUE TITLE
Plot Creation in an existing world

### ISSUE THREAD

**Issue by tantaf123** [IntellectualSites/PlotSquared#4489]
### What feature do you want to see added?

Please make it easier for users to create plots in an existing world. I was told to use **/plot area single** but according to the console, it is trying override the world folder with a new plot world which I do not want. There should also be an option to remove plot areas rather than constantly having to delete things in the config yourself, shut your server down or restart it. That is very time consuming.  

### Are there any alternatives?

.

### Anything else?

.

**Comment by NotMyFault** [comment]
Re-read the wiki, this is not how it works.
