### ISSUE TITLE
[Enhancement] Auto detect where player is facing when doing /p merge

### ISSUE THREAD

**Issue by oDeathwingo** [IntellectualSites/PlotSquared#450]
just like worldedit getting values for //stack automatically 
and probably a config for disabling it/default value?

**Comment by boy0001** [comment]
It tells you the direction if you just do /p merge

**Comment by Sauilitired** [comment]
I'd actually like this, but it's a very minor enhancement.

**Comment by EvilOlaf** [comment]
I think it is ok that it asks explicitly for a direction. It could be possible that you accidently merge the wrong plot... Yes i know, quite unlikely but possible. 

How about a confirmation? 
You enter plot merge, p2 checks if merge would be possible in the current direction (if the current looking direction is valid) and spits out to enter the same command (arrow up and enter) to confirm. 

Ya,  big effort for very little additional comfort...

**Comment by boy0001** [comment]
implemented
