### ISSUE TITLE
Server thread

### ISSUE THREAD

**Issue by AhFish2511148744** [IntellectualSites/PlotSquared#4505]
### Server Implementation

Spigot

### Server Version

1.20

### Describe the bug

The server paused suddenly, and only Bukkit and PlotSquared were visible

### To Reproduce

Unable to reproduce, failed to discover how it was triggered

### Expected behaviour

The server gets stuck in the thread and can't respond

### Error log (if applicable)

https://paste.gg/p/anonymous/45675345462d4b3d883e2ff5de935079

### Plot Debugpaste

none

### PlotSquared Version

plotsquared-bukkit-7.3.9-SNAPSHOT

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by NotMyFault** [comment]
> forge@47.3.5

PlotSquared supports Bukkit-based servers only, no hybrids.
