### ISSUE TITLE
/p clear

### ISSUE THREAD

**Issue by P3ctax** [IntellectualSites/PlotSquared#4514]
### Server Implementation

Paper

### Server Version

1.21.1

### Describe the bug

When i type /p clear all players got this message in chat

PlotClearEvent: #getEventResult -> null

### To Reproduce

Type /p clear
 PlotClearEvent: #getEventResult -> null

### Expected behaviour

The Plot have to be cleared

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/41beb4ff37fe4856a56a816f23932747

### PlotSquared Version

PlotSquared version 7.3.11-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by SirYwell** [comment]
This message comes from `ProtectionLib`. Make sure you're running the latest version of that plugin.
