### ISSUE TITLE
road-flags doesn't work

### ISSUE THREAD

**Issue by ZuRiKanHD** [IntellectualSites/PlotSquared#4524]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

Players who spawn a Wither on the wall on their plot can destroy the wall and the road behind it with the Wither.
The Wither must touch the blocks to destroy them.

The set flags do not work on the road.
Therefore, the Wither can destroy the road.

#    road:
      width: 11
      height: 62
      block: gray_concrete
      flags:
        block-burn: false
        explosion: false
        mob-break: false
        hostile-attack: false

### To Reproduce

1. Spawn a wither on the plot wall.
2. Push the Wither against the wall and hit the Wither.
3. When the Wither tries to free itself, the blocks are broken.

### Expected behaviour

The Wither should not be able to break the wall.

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/d7a720338e414d69b0c3b088b74eab45

### PlotSquared Version

PlotSquared version 7.3.11-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by RedstoneFuture** [comment]
I can replicate this.
![grafik](https://github.com/user-attachments/assets/62200d82-4bfe-4d1f-9d78-924bcbe25bd1)
