### ISSUE TITLE
Plot setowner with IDS

### ISSUE THREAD

**Issue by pinguulein** [IntellectualSites/PlotSquared#4529]
### What feature do you want to see added?

Please reintroduce, that you can set the owner of an plot even if ur not standing on it, (its for a skript).

### Are there any alternatives?

No alternative sadly

**Comment by RedstoneFuture** [comment]
You can use the expanded syntax: `/plot [[world;]X;Z] setowner <player>`

**Comment by pinguulein** [comment]
Nope u cannot as this was removed i guess. Even in the java class there is no location argument anymore

**Comment by dordsor21** [comment]
`/plot <I'd> setowner` all commands have this functionality.

**Comment by pinguulein** [comment]
still doesnt work
