### ISSUE TITLE
Не удаляются/не очищаются плоты

### ISSUE THREAD

**Issue by Sqw6qq** [IntellectualSites/PlotSquared#4542]
### Server Implementation

Paper

### Server Version

1.19.4

### Describe the bug

(версия сервера 1.16.5, стоит виавершин)
Раньше плагин отлично работал, но, вдруг начали не удаляться плоты. Это довольно большая проблема для нашего сервера. Как я заметил, плоты удаляются со временем, это тоже не хорошо.

### To Reproduce

1. Зайти на сервер 2. Зайти на плот 3. Написать /plot delete | /plot clear 3. Получить ошибку про время удаления плота

### Expected behaviour

При команде /plot delete плот должен был удалиться сразу. При команде /plot clear плот должен был очиститься сразу.

### Screenshots / Videos

![2024-11-17_17-08-36](https://github.com/user-attachments/assets/72c129e4-11f4-48e9-a63d-6349837a14ad)

### Error log (if applicable)

https://pastes.dev/HyRde96Llh

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/861696c1ae664a2da89db809c842d485

### PlotSquared Version

PlotSquared-Bukkit-6.11.1-Premium

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by dordsor21** [comment]
1.16 is not supported.

**Comment by Sqw6qq** [comment]
тогда, условно я могу поменять версию сервера на 1.17.1, и всё заработает?
