### ISSUE TITLE
Plot biome gets reset when merging a plot

### ISSUE THREAD

**Issue by EpicJosch** [IntellectualSites/PlotSquared#4548]
### Server Implementation

Paper

### Server Version

1.20

### Describe the bug

When i set a plot biome to snowy_taiga (or any other) and then merge the plot with another plot the biome gets reset to forest. The biome still remains on snowy_taiga (can be seen on the grass color) but in the plot settings (/p i) it sais forest and the new plot (with got merged into the first plot) has forest grass color

### To Reproduce

1. Change biome of plot
2. Merge plot

### Expected behaviour

- Both plots should have snowy_taiga grass color after merging and /p i should show snowy_taiga

### Plot Debugpaste
NONE

### PlotSquared Version

7.4.0-Premium

### Checklist

- [ ] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

**Comment by dordsor21** [comment]
Do both plots have snowy_taiga as their biome?

**Comment by EpicJosch** [comment]
> Do both plots have snowy_taiga as their biome before merging?

No - one is snowy Taiga and one is default (forest) because players claim a new plot and then want to add it to their merge keeping the settings of their main merge which is more than understandable
