### ISSUE TITLE
biome, Biomes, BIOMES!

### ISSUE THREAD

**Issue by boy0001** [IntellectualSites/PlotSquared#455]
```
Here's my plotsquared config: http://pastebin.com/JgCNnSya (Using version 2.12.8/13)
Not exactly sure what's wrong here, the actual plots show up as forest biome (Set in config) but when using /plot info it displays the plot as using something different, my users don't have access to set the biomes of their plot.
Screenshot 1:
```
Notes:
 - Plot info asks Bukkit what the biome is at the center of the plot
 - #440

#### Fixed:

```
After converting from PlotMe 0.17 (which default biome is PLAINS)-- I appear to have PLAINS biomes near my roads sporadically through out the world that can not be altered with /p set biome.

This Plains biome also appears a vast majority of the time when merging a plot (i.e. beneath the road).
```
Notes:
 - Possible coincidence that it's near the road?
 - Appears to be whole chunks rather than individual blocks
 - #404

```
Biome "snake" in the middle of plot >:[
```
Notes:
 - Also cannot be changed, but not near the road
 - Possibly same reason as #404
 - #424

**Comment by boy0001** [comment]
TODO:
 - Find out how to replicate this easily
 - Add some debug stuff to ensure that P^2 actually sets the biome of the whole plot
 - Add some debug stuff to see if telling bukkit to change the biome actually changes the biome
 - Add some debug stuff to see if bukkit thinks the biome has changed even if it hasn't
 - rage / smash keyboard, or possibly the wall since the base of my keyboard is solid metal.

**Comment by boy0001** [comment]
Partially fixed.

**Comment by MattBDev** [comment]
@boy0001 this issue still relevant?

**Comment by boy0001** [comment]
Well the issue that wasn't fixed was `/plot info` displaying the wrong biome sometimes. No idea if it's since been fixed. Can probably close until someone reports it again.
