### ISSUE TITLE
Plot generate roads under the ground

### ISSUE THREAD

**Issue by Sytrexofficial** [IntellectualSites/PlotSquared#4560]
### Server Implementation

Paper

### Server Version

1.21.1

### Describe the bug

Plusquardt streets now had a bug that when I build down and generate the streets, they are not generated and I don't know why but when I build up and generate today, everything works, I just can't go down into the depths

### To Reproduce

I don't know what is meant by that but it's just a bug that I can't generate below at the streets Platz Straussen I mean exactly um well I can't say anything about it so

### Expected behaviour

sorry I'm German I don't know um what it means but I just found this bug and I really want to have it fixed now so that's how it works with the plot roads

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/e56189a7-ac8d-4170-9295-6bf5a6460437)
![image](https://github.com/user-attachments/assets/d087a4aa-99dc-426b-8e0a-d3275c6eccbb)
![image](https://github.com/user-attachments/assets/30b937ac-3230-4512-a268-938264669be4)

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/6a4cd03fb7fd4f22a68c9772770bbba7

### PlotSquared Version

plotsquared-bukkit-7.4.0-Premium, MC-Version 1.21.1

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/77506/ and the issue still persists.

### Anything else?

no thank u

**Comment by dordsor21** [comment]
Set paste-road-on-top to false. Always read through a plugin's documentation and configuration files to avoid reporting bugs when it is misconfiguration on your part.
