### ISSUE TITLE
Plot Sell!

### ISSUE THREAD

**Issue by MuhammetBoz** [IntellectualSites/PlotSquared#457]
Land Trading closed , 
For example > /p sell amount not found!
For example > /p buy not found!
Players will buy the land How?!

**Comment by boy0001** [comment]
You need to first enable economy for the world and have vault / a vault complient economy plugin.
Then:
 - `/plot set price <value>`
 - `/plot list forsale`    
(go to that plot)    
 - `/plot buy`

**Comment by MuhammetBoz** [comment]
/plot set price <value>
not found. /plot flag set price <value> .
okey ...
/plot buy not found.

**Comment by EvilOlaf** [comment]
Do you have a recent version of P2? Did you enable economy?

**Comment by boy0001** [comment]
Hmm, well `/plot set price` should redirect to `/plot flag set price`, I will check this out now quickly.

**Comment by boy0001** [comment]
Try this:
https://www.spigotmc.org/resources/plotsquared.1177/download?version=36026

**Comment by MuhammetBoz** [comment]
Iconomy enable , P2 enable.
