### ISSUE TITLE
Console Command Added

### ISSUE THREAD

**Issue by MuhammetBoz** [IntellectualSites/PlotSquared#458]
Please Added Console Command;
For example > /p flag add fly true 1;-2

**Comment by boy0001** [comment]
Other ideas:
 - `/plot claim`
 - `/plot set`
 - `/plot setowner`
 - `/plot <add|trust|deny|remove>`
 - `/plot move`
 - `/plot swap`
 - `/plot copy`
 - `/plot download`
 - `/plot cluster`

**Comment by EvilOlaf** [comment]
Ya, might be useful for command blocks or stuff like that.

**Comment by boy0001** [comment]
Added for the next version:
http://i.imgur.com/jVo9Bhy.png

To specify a specific plot, commands can be prefixed like so:
`/plot 3;-6 info`    
or
`/plot plotworld;3;-6 info`

**Comment by MuhammetBoz** [comment]
which version ?

**Comment by boy0001** [comment]
The next one we upload to spigot. You could try a development build out if you want to test, just be warned that it may be unstable:
http://ci.intellectualsites.com/job/PlotSquared/

**Comment by EvilOlaf** [comment]
Uuhhh that looks nice.
