### ISSUE TITLE
Unclaimed plots remain claimed after reboot

### ISSUE THREAD

**Issue by Joannou1** [IntellectualSites/PlotSquared#459]
I installed PlotSquared 2.12.15 a few days ago and set it up to use MySQL.
So far I'm loving it! (Apart from this issue)

According to players, unclaiming a plot will not actually remove it from them, because come the next reboot it is still registered to them.

Here's what one of my players said:
http://chatformat.com/oRbNkQv6/

Here's what the DB table looks like:
https://gld.bz/c/41e00.png

He is in a group that only allows 1 plot, but he has 3.

Leme know if you need me to try a jenkins build or anything like that. Thanks!

**Comment by boy0001** [comment]
This has been fixed, however you should be using `/plot delete` instead.
