### ISSUE TITLE
Modify plot limits

### ISSUE THREAD

**Issue by boy0001** [IntellectualSites/PlotSquared#461]
> I was thinking that p2 should be in charge of how many plots a player can have instead of permissions. so I could just do /p setlimit PLAYER 2 or /p addlimit PLAYER 1.

**Comment by Sauilitired** [comment]
This should not be handled by us, as this can be done with permission plugins as of now. If this was added by us, then it should be added by a separate plugin.

**Comment by voigtman** [comment]
Yes we know it can be set with permissions, but its a royal pain to have to manage 100 players perms individually when plot sizes COULD be done automatically with a command to grant greater flexibility. Hate to bring up the dragon, but according to the authors of the eula, additional plots can't be added into a bought rank (group) so it would be handy to have a way to give them as a vote reward without changing a players rank or permissions node each time. Creative servers have no use for currency so the built in buy a plot is useless on these servers.

**Comment by Sauilitired** [comment]
Hm, I didn't think of that part of it all. 

A temporary solution would be to allow the console to claim plots for others (simply add the ability to auto-claim plots for others), then have the vote execute a console command.

**Comment by boy0001** [comment]
Added in the form of a script: https://github.com/IntellectualSites/PlotSquared/wiki/Scripting
