### ISSUE TITLE
delete on unclaim

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualSites/PlotSquared#462]
We recently had this discussion in IRC.
Just posting here so it won't be forgotten.

Add an option to the config to forcefully clear a plot when unclaiming.
In most cases users or server owners want their plots cleared before giving them up.

**Comment by LaxWasHere** [comment]
Why not /plot clear then /plot unclaim for users?
/plot delete for server owners?

**Comment by EvilOlaf** [comment]
Because users could unclaim their plots without clearing them first which might be not wanted in most cases.

**Comment by boy0001** [comment]
Or `/plot delete` for players, and `/plot unclaim` for server owners?

**Comment by EvilOlaf** [comment]
Hm true story...
