### ISSUE TITLE
Need Help Understanding

### ISSUE THREAD

**Issue by Gurp1272** [IntellectualSites/PlotSquared#464]
So I have a spigot server running 1.8.7. I want to be able to create plots for shops, and etc. The videos and tutorials that I have watched, changed the whole entire world into plots. I just want a small area to be used for plots, and maybe be able to add on to a group of plots, as time goes along. Is there a way to do this? I want to limit the amount of plots that are created, maybe only make 4 to start out with. Is this possible?

Thanks, 
Gurp

**Comment by Sauilitired** [comment]
https://github.com/IntellectualSites/PlotSquared/wiki/Augmented-Plot-Worlds

Clusters will allow you to generate a specified amount of plots within any normal world :smile:

**Comment by Gurp1272** [comment]
Ok. Clusters might be cool. I feared no one would answer so I backed up my world and started playing around. I created a plot world, and it didn't override my original world. Instead it looked as a parallel world, and you can move in between them which I thought was really cool. Now I need help understanding how that works? How do you have a parallel world that you can transfer in between? I guess that's how the mini games work on other servers? I see that the plot world directory got created side by side with my original world file. So how is it that I transfer in between them. Hooks? Vault?

**Comment by Sauilitired** [comment]
Look into [MultiVerse](http://dev.bukkit.org/bukkit-plugins/multiverse-core/)

**Comment by Gurp1272** [comment]
Awesome thanks. Now does PlotSquared need to have multiverse to work? Or does it use some core elements of multiverse?

**Comment by boy0001** [comment]
Multiverse makes it a lot easier. If you don't, you need to define the generator settings manually in the bukkit.yml

**Comment by Gurp1272** [comment]
Also is this how we would do minigames? Take spleef for example. You break the floor blocks to try and kill your opponent. But after every game, you want to reset this game/world. Would this be the way to go?

**Comment by boy0001** [comment]
It's one way to do it. If the area is small enough, it is easy enough to regenerate the world while it's loaded. For example with plot clearing, there is no need to delete the entire world to clear just one persons plot.

**Comment by Gurp1272** [comment]
I created a plot world yesterday with PlotSquared, and without MultiVerse? I didn't edit any files, I installed the plugin and started playing with it.

**Comment by Gurp1272** [comment]
Also what's the best way to do/handle minigames on a server? Or the most common/simple way?

**Comment by boy0001** [comment]
I don't really make minigames, but there are different benefits and drawbacks to each:

Using a new server instance + bungee for each game:
 - large servers which need to balance a lot of players will deploy a new server for each instance of the minigame
 - This requires more resources than multiworld but means you don't need to worry as much about lag from having 20,000 players on your network at once

Using a seperate world for each game:
 - A game could be reset by deleting and regenerating the world
 - Bukkit doesn't do world loading / unloading async, so other worlds will lag when this happens

Managing each game in a section of a world:
 - Much harder to code, so possibly less common
 - if it's done properly then minigames can be reset asynchronously without interfering with other things happening on the server.

As for PlotSquared creating the world without multiverse, if you don't configure the Bukkit.yml, whenever you restart the server next, the world will be unloaded and you will need to run setup again to load it. (Multiverse makes it easier)

**Comment by Gurp1272** [comment]
Awesome thanks for the feedback!

**Comment by Gurp1272** [comment]
Another question. When I use PlotSquared, and I create a plot world, it creates a directory with the name I assign it. For Ex: Shops. A Shops directory will show up. To do a complete backup, would I backup the Shops directory, and my world file? Or does the Shops somehow tie into the world file?

**Comment by EvilOlaf** [comment]
To do a *complete* backup you should copy your entire server folder without exception :P

**Comment by Gurp1272** [comment]
That doesn't answer my question... I know how to back everything up, I'm curious how my Ex: Shops directory, created from PlotSquare ties in with the world file. If I were to backup just my world file, would it also backup my plot world? Or would I also need to backup the Shops directory.

**Comment by Gurp1272** [comment]
It obviously ties in somehow, because I can /tp in between worlds. But how much? To back my world I would backup the world file, does the world file include my plotworld? Or would I also need to backup my 'Shops' Directory?

**Comment by Gurp1272** [comment]
My plot world, when created, is like a subdirectory, right? The plot world isn't created on the actual world file. Is this correct? I'm just a little confused, and I don't like using things I don't understand.

**Comment by boy0001** [comment]
Each world folder stores the blocks and structures. All player data such as inventories etc are stored in the main world directory.
