### ISSUE TITLE
Problem with schematics

### ISSUE THREAD

**Issue by Raphy123** [IntellectualSites/PlotSquared#465]
Hello, I love this plugin but I have a bug..

I want to add schematic on plots, that : http://zupimages.net/up/15/31/dyq7.png

But all my schem are changed ! After I have that :
http://zupimages.net/up/15/31/5gao.png

.. Why ? :(

**Comment by Sauilitired** [comment]
I'm sorry, for this is incredibly funny :D Oh well, it's not intended behavior.

**Comment by Raphy123** [comment]
Yes.. but.. how I can resolveee XD ?

**Comment by boy0001** [comment]
If you want to test, there are some dev builds:
ci.intellectualsites.com/job/PlotSquared/

**Comment by Raphy123** [comment]
The correct version is PlotSquared-Bukkit.jar ? Or the third on dev builds ?

**Comment by boy0001** [comment]
PlotSquared-Bukkit.jar is for bukkit / spigot.

**Comment by Raphy123** [comment]
Ok thanks Boy :) I test that !

**Comment by Raphy123** [comment]
latest dev build is ok.. but she is stable ?

**Comment by boy0001** [comment]
We don't know, there's not enough time to test each time we commit.

**Comment by boy0001** [comment]
Fixed as of latest version.
