### ISSUE TITLE
Plot World always unloading when server restarts

### ISSUE THREAD

**Issue by Exemption** [IntellectualSites/PlotSquared#466]
Everytime my server reboots or manually restarts by me, and I join the server, I see Console always unloading the world: Creative (My plot world) then it loads it back in. I saw it do this the first time for the conversion from PlotMe to PlotSquared but it keeps doing it and does make my NPCs dissapear when it unloads. Dont know if this is an error or is default but I would like it not to unload it as I see no need to.

**Comment by EvilOlaf** [comment]
P^2 version?
Console output?
Config files?

Insufficient information

**Comment by boy0001** [comment]
Disable PlotMe conversion
