### ISSUE TITLE
Expire Manager taking forever

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#469]
using 2.12.15 I just get [ExpireManager] Waiting on fetch... forever. Also the server has hit the mojang rate limit so that player heads do not appear they are just steve skins, and the /namehistory command I have just says the rate limit was reached. This never used to happen before, could they be related? perhaps the expiremanager is not making use of the uuid cache or something?

**Comment by PhanaticD** [comment]
confirmed practically instant now

**Comment by manuelgu** [comment]
This can probably be closed?
