### ISSUE TITLE
Permissions Problems

### ISSUE THREAD

**Issue by Gurp1272** [IntellectualSites/PlotSquared#470]
First of all, where does PlotSquared even store permissions? I don't see a config.yml. Is it settings.yml? Only opped users can build on plots. I claimed a plot, and set the owner as myself. I then de-opped myself, and I was unable to build on my own plot. Any feedback is greatly appreciated!

**Comment by EvilOlaf** [comment]
If there is no 3rd party permission plugin like GroupManager or PermissionsEx installed your permissions are stored in the permissions.yml in the CB/Spigot directory.
P^2 does not manage permissions itself, it just provides many of them to allow server owners individually use their plot world.

**Comment by samgillison** [comment]
Lol, giving the fact it's kinda self explanatory... I won't go there but yeah. What EvilOlaf said, you need to use a 3rd party plugin such as GroupManager, PermissionsEX, etc, etc.

**Comment by EvilOlaf** [comment]
Well there is actually no really need to do so, but it makes permission management significantly easier :P

**Comment by boy0001** [comment]
If you are op, you need to reconnect after being deopped.

**Comment by Gurp1272** [comment]
Wait, but once question. I've already checked the permissions folder. There are no permissions in there for plotsqaured. In fact there are hardly any at all. Do I have to put them in there myself? If that is so, where is is pulling permissions from to even let op build? Thanks again, Gurp

**Comment by samgillison** [comment]
Yes, you have to add them your self (god help us), use the wiki to find the permission nodes that are required for a certain task!

**Comment by Gurp1272** [comment]
Lol. Sorry.

**Comment by Gurp1272** [comment]
Ok I'm getting my permissions problems figured out. One more question. If I don't set a node to true or false, but simply leave it out, does it default to false?

**Comment by boy0001** [comment]
It will default to "op" which means you need to be an operator to have the permission.

**Comment by samgillison** [comment]
@Gurp1272 I'm sorry for being a bit mean, but do you not know how permissions work?, you add a permission node to a group or player to give them access to that command or action, if you leave it blank they won't have access to it!

**Comment by Gurp1272** [comment]
It's OK. I understand the frustration of trying to teach someone that's just wont get it, something. I know how they work now after some research, and a download of permissionsbukkit. Thanks for your help guys.

**Comment by samgillison** [comment]
@Gurp1272 PermissionsBukkit is outdated, use PermissionsEX instead!

**Comment by Gurp1272** [comment]
Are you serious. Please tell me that they are coming out with an update? Or are they just done with it? Cause I got it all setup.

Thanks again for the help.
Gurp

**Comment by Gurp1272** [comment]
Is that why permissionsbukkit gives me 'server returned http response code: 504 and 502

**Comment by Gurp1272** [comment]
Is PEX lightweight? I really wanted something light.

**Comment by samgillison** [comment]
@Gurp1272 its been abandoned for nearly 3 years now, and yes PEX is lightweight!
