### ISSUE TITLE
Road Schematic

### ISSUE THREAD

**Issue by voigtman** [IntellectualSites/PlotSquared#471]
Hello, I'm running the 2,12,15 version, and I'm setting up a new plot world for an upcoming server on my network. There seems to be an issue with certain blocks used in the road. 
It will not generate any prismarine or glass panes.

**Comment by boy0001** [comment]
We had this fixed in 2.12.17, however due to an issue with UUID fetching, we have temporarily reverted to 2.12.15 which has that bug.

If you want to test out a development build, see here: ci.intellectualsites.com/job/PlotSquared/
