### ISSUE TITLE
When plots merged sometimes players cant build where the roads used to be

### ISSUE THREAD

**Issue by BackSlashM** [IntellectualSites/PlotSquared#474]
It has happened a few times now on my server where players cant build where the roads used to be when the two or more plots are merged, linked is a picture of what happens
![2015-07-30_21 38 38](https://cloud.githubusercontent.com/assets/13497657/8994519/c8bf30c6-3703-11e5-8c90-551e013e54db.png)

**Comment by BackSlashM** [comment]
There is a way to fix this, unlink the plots, then re-linking them seems to fix it

**Comment by boy0001** [comment]
Can you do `/plot debugpaste` and send that?

**Comment by boy0001** [comment]
Multiple changes coming in the next release that should prevent or solve this:
 - Database verification on shutdown
 - An included script to remerge plots
 - changes to the merging code to reduce likelyhood of the above being necessary.
