### ISSUE TITLE
UUID Issues

### ISSUE THREAD

**Issue by CKGAR** [IntellectualSites/PlotSquared#478]
When updating to 3.0.1, my all plots in my world set the owner to "Unknown". If you enter the plot the title says "Owned by Unknown". The signs on the plot show the user who claimed it's name, and when the user logs in the issue is fixed, titles revert back to normal. This is a huge problem, as trusted users can't build in plots if their owner hasn't logged in yet. I can't set the plot owner back using ./plot set owner [user] either, it says "User hasn't logged in" even though they have -_-. I can't unclaim it, as that command is broken too. This is what was in my config when I restarted after the update http://pastebin.com/1r9bD98e. It lists a couple of users' UUIDs it couldn't retrieve, but over 50+ people's plots are now listed as "Owned by Unknown". This is quite a disaster. I didn't see anything in the update list you posted that would cause this. Is it really necessary to keep screwing around with UUIDs? This isn't the first time this has happened to me. I am running Spigot 1.8.8 and the latest BungeeCord.

**Comment by boy0001** [comment]
Would you like to come on IRC to discuss this issue?

**Comment by CKGAR** [comment]
I'm on right now, my username IRC name is Ideks

**Comment by boy0001** [comment]
Resolved apparently
