### ISSUE TITLE
Unable to spawn mobs in claimed plot. Unclaimed works.

### ISSUE THREAD

**Issue by TagCraftMC** [IntellectualSites/PlotSquared#479]
I have just started using this plugin so I am hoping that I have missed something obvious in my tired state :)

I haven't been able to get Mobs to spawn in claimed plots so far by natural, spawner or eggs. Mobs are spawning on unclaimed plots naturally as well as with spawners and eggs.

Plots version(config): 2.12.19
Spigot Version: 1.8.8-R0.1 - 6C9b0a1-de5c261
Relevant settings;
* Server Properties has Animal, Monster and NPC spawning enabled.
* WorldGuard has it enabled, the plot has a region that also has mob-spawning enabled.
* Plots config, Spawn: has breeding, egg and custom set to true.
* Plots config, natural_mob_spawning set to true.
* Plots config, default flags, mob-cap: 10
* The plot it's self has mob-cap: 10 animal-cap: 10 entity-cap: 10 mob-place: true

Let me know if you need any more info. Thanks!

**Comment by boy0001** [comment]
Hmm, I can't replicate this issue with the settings you described above. One thing I can tell you is that mob-cap and animal cap are redundant since you have the entity cap flag set at 10, and mobs and animals are both classified as entities.

Could you send me your full settings.yml so I can test with that?

**Comment by TagCraftMC** [comment]
Thanks for the reply boy0001, I am aware that Animal, Hostile and Mob cap become redundant when I set an Entity cap, but at that point I was essentially trying to cover all bases :D.
Something I forgot to mention in the first post, we're not running MultiverseCore. Instead using a single world and bukkit's built in generator.

Plot Settings: http://pastebin.com/Gdg9mc6d
Plot Info: http://i.gyazo.com/a498e10e72ad45ce25d7a2c8acc51220.png
Plugins(just in case): http://i.gyazo.com/00cf7b0a58e1758604e7daafd5e1ae40.png

Let me know if you require more info and thanks for looking into the issue.

**Comment by Sauilitired** [comment]
@TagCraftMC For future reference, using `/plot debugpaste` will upload the config files and other useful information for you :+1:

**Comment by TagCraftMC** [comment]
I appreciate the tip, Sauilitired.

**Comment by MattBDev** [comment]
Closed for being too old.
