### ISSUE TITLE
100x100 plots chunk 0,0 weird error

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#481]
for some reason the chunk at 0 0 gets partially set with tripwires, its very strange. Not sure what is causing it at all which is why I havent reported it earlier but in case it is plotsquared here are some pictures:

http://gyazo.com/614bf652d9cc3d5affc5566b4ccbc17d
http://gyazo.com/17dabb9f7177b0f4673e7afbf2d6a576

this only happens on the 100x100 plot world

**Comment by PhanaticD** [comment]
still not fixed, it is happening on all plot worlds actually

**Comment by MattBDev** [comment]
I tested and wasn't able to reproduce it on latest versions. Reply if it is still an issue or you can create a new one.
