### ISSUE TITLE
plot trim resetting plots (still)

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#482]
plot trim still is deleting valid plots, particularly noticeable on larger plot worlds (500x500)

example on my server a plot that had to be restored from backup after doing the trim command: /plot visit acphelps100 4

**Comment by PhanaticD** [comment]
how would that fix it o.O

**Comment by boy0001** [comment]
There was a typo, so it was only checking the chunks for every second plot. (Although this doesn't necessarily fix plot trim, it just means it's less broken)

**Comment by boy0001** [comment]
Seems to be fixed. This can be reopened if it's not.
