### ISSUE TITLE
Plot Claiming and Editing

### ISSUE THREAD

**Issue by Gurp1272** [IntellectualSites/PlotSquared#487]
Ok, so I have all my permissions setup, thanks to you guys. I have created a few plot worlds by /plots setup. Then I have deleted them using /mv delete, which should remove all data from all config files. After creating another plot world, this time with the right specs, I can walk on a plot, do /plot info. It will show it is owned by me. So that means it is pulling data from somewhere else. I can do /plot claim, but it will say plot is already claimed. There are no plot claimed blocks around the wall. So I do /plot unclaim, then /plot claim. That changes the blocks around to show that the plot is claimed. Then I do /plot unclaim, and the blocks around wall don't change to show that it is not claimed. Also, when I claim a plot, I cant build on it. I can't build on it even though, I have claimed it, setowner, in gamemode 1, and am opped. Something is definitely wrong. 

Also with teleportation, and multiverse permissions, I've given the average user: multiverse.access*, multiverse.help, multiverse.teleport.*. I have given them multiverse.teleport.* because thats the only way I could make so they could teleport self. I tried the other ones: multiverse.teleport.self.w. They didn't work. 

Any help would be greatly appreciated!

Edit: Ok, I have figured out how to change blocks after /plot unclaim, you do /plot clear. Now the only issue that stands is the owner of the plot being able to build inside the plot. I am still unable to do that as OP. AND the teleportation permission nodes.

EDIT #2: Ok I have fixed being able to edit a plot on /plot claim. I set the worldedit: require-selection-in-mask: false. 

I set that to false, but this means that the plots.worldedit.bypass, node that I set in PermissionEx didn't work. 

Issues now: Why doesn't plots.worldedit.bypass work? Also to teleport I am still using node: multiverse.teleport.* Even though I am using multiverse.teleport.*, the player still cant teleport others. I thought I read that, that node gives someone all teleportation rights? I would rather use: multiverse.teleport.self.

EDIT #3: Ok, I have fixed the being able to build on plot. I went back into the PlotSquared settings files, and set the worldedit: require-selection-in-mask: true. I set it true from false. I then went into the PermissionsEx permissions file and set: plots.worldedit.bypass:true. I set it to true from unset. then it worked. I haven't set any of the permissions nodes in my PermissionsEx file to true. Does that mean that none of them will work until I set them to true? Thanks. 

Issues now: Teleportation. I would rather not set multiverse.teleport.* for the average user. But instead multiverse.teleport.self.

EDIT #4: Ok so you can only edit a plot if you claim it, and are op. I have another account to test. I claimed a plot, but was unable to edit it, even though that test account was the owner. The test account is not OP.

EDIT #5: The previous issue still stands, unable to edit a plot even though I am owner. If I run /plot trust <username> the trusted can edit my plot. So I ran that as OP, and the nonOP user could edit the OP plot. The nonOP user is still unable to edit the plot that he owns. 
SERIOUS:a user can run /plot unclaim, and get the money from /plot unclaim over and over again. I tried to fix this by removing plots.admin from the permissions. Then I would do /sudo <username> plot unclaim. Because this runs the command as that user, it comes up and says that, that user does not have permission. How do you make so a user can only unclaim his own plot, and only do it once?

Thanks, 

Gurp

**Comment by boy0001** [comment]
For deleting worlds, PlotSquared also stores information in the settings.yml and the database file (probably plots.db).

For permissions, there are a few permission packs that will make setup easier:
https://github.com/IntellectualSites/PlotSquared/wiki/Commands-and-Permissions#base-permissions
(Just add one of these permission to a player and they will have all the permissions it contains)

Remember that you need to relog if you have recently deopped yourself for permissions to take effect.

Also, use `/plot delete` instead of unclaim.
