### ISSUE TITLE
Random Biomes - PlotSquared 

### ISSUE THREAD

**Issue by JuggaletteJazzy** [IntellectualSites/PlotSquared#489]
Hi, I want to see what I have to do to fix this issue with PlotSquared. 
I can't remember the version it is, but it is very recent.

There are random biomes just generating everywhere in the plot world. 
Also when someone /p delete or /p clear it would become a biome. 
I had to remove the delete / clear permission for now

How can I fix this? 
My goal is to NOT have to reset the plot world. Thankyou!

**Comment by boy0001** [comment]
What version of P^2?

**Comment by JuggaletteJazzy** [comment]
2.11.21

**Comment by Sauilitired** [comment]
@JuggaletteJazzy Update.

**Comment by JuggaletteJazzy** [comment]
Okay. The most recent version, how do I get rid of all those biomes after I update?

**Comment by JuggaletteJazzy** [comment]
And by biomes i mean the current biomes everywhere. Will i have to reset the plots?

**Comment by gameplayerhd** [comment]
I have the same issue

**Comment by boy0001** [comment]
Please update to the latest version on spigot. It should fix it for newly generated plots. You can also do the following to fix the biome in existing plots:
 - Plot condense
 - plot trim
 - run the set biomes script: https://github.com/IntellectualSites/PlotSquared/wiki/Scripting

Please respond with any questions, or requests
