### ISSUE TITLE
Using minecarts and using redstone buttons and levers on other players plots should have a permission node 

### ISSUE THREAD

**Issue by BackSlashM** [IntellectualSites/PlotSquared#492]

**Comment by boy0001** [comment]
The flag system should be what you want: https://github.com/IntellectualCrafters/PlotSquared/wiki/Usage:-Plot-flags

There's an example for setting default flags, but this can also be per plot. For blanket interact bypass, there are permissions: https://github.com/IntellectualCrafters/PlotSquared/wiki/Commands-and-Permissions#admin-bypass-permissions

Reply here if you need further assistance.
