### ISSUE TITLE
Plot2Dynmap helpers issue

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualSites/PlotSquared#495]
Got this with 3.0.6v2 of Plot2Dynmap:
http://www0.xup.in/exec/ximg.php?fid=64017074

Idea to fix helpers?
```
infowindow: <div class="infowindow"><span style="font-size:120%;">%id%</span><br>%alias%%owner%%helpers%%flags%</div>
infoelement: '%key% <span style="font-weight:bold;">%values%</span><br>'
```

**Comment by boy0001** [comment]
Helpers were removed in a previous version of PlotSquared. Change `infowindow` to the following:
> infowindow: "<div class=\"infowindow\"><span style=\"font-size:120%;\">%id%</span><br>%alias%%owner%%trusted%%members%%flags%</div>"
