### ISSUE TITLE
Economy not working 

### ISSUE THREAD

**Issue by donbubu** [IntellectualSites/PlotSquared#497]
hi,
i can claim a new plot, become the message that i lost 20 money but i have 0$.
i use essentials (2.x vTeamCity), vault (1.5.3-b37) and plotsquared (v3.0.6).
plotsquared ignored completly the eco system.
the config of the world for price:
    economy:
      prices:
        merge: 5.0
        sell: 7.0
        claim: 20.0
      use: true

**Comment by EvilOlaf** [comment]
Confirmed.
