### ISSUE TITLE
plot set home broken?

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualSites/PlotSquared#498]
When I try to set a plot home the location is not being saved.

3.0.6

**Comment by boy0001** [comment]
Can't replicate; unless you are referring to the facing direction, which is not currently saved

**Comment by EvilOlaf** [comment]
Hm I tried multiple plots and used `/plot set home` which seemed to work but when I used `/plot home` I get always to the same other spot teleported.
As users report that now after upgrading I think that should have been worked with 2.9.x
