### ISSUE TITLE
setowner on unclaimed plots?

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualSites/PlotSquared#499]
Some kind a enhancement.

When I want to give a player a plot for a reason I have to help myself for some cash, then do `plot claim` and then do `plot setowner` to give the player the plot he wants.

I would like to see that `setowner` works on unclaimed plots directly.

**Comment by boy0001** [comment]
What about /plot claim <player> ?

**Comment by EvilOlaf** [comment]
Hm...not really because claim is with cost associated already. I would prefer setowner.

**Comment by EvilOlaf** [comment]
Awesome!

**Comment by boy0001** [comment]
`/plot setowner <name>`
