### ISSUE TITLE
Error on PlayerTeleportEvent

### ISSUE THREAD

**Issue by logicalPolaris** [IntellectualSites/PlotSquared#502]
Dunno the cause, here's the log.

![screenshot_1](https://cloud.githubusercontent.com/assets/11083026/9046595/8a01d1ba-39e0-11e5-8715-e40dfa623839.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/11083026/9046594/89ff2aaa-39e0-11e5-85e1-3e24d221ad24.png)

**Comment by boy0001** [comment]
Duplicate of #490
