### ISSUE TITLE
Commands not working as expected?

### ISSUE THREAD

**Issue by oDeathwingo** [IntellectualSites/PlotSquared#508]
I was trying to get the 2nd page of plot claiming help command and got the following error:
p2 thats not a valid number within the range (0)

What was executed;
/p help claiming 2
what was expected;
showing me help about claiming page 2
What came up;
p2 thats not a valid number within the range (0)

**Comment by boy0001** [comment]
Temporary workaround: `/plot help <page>` or `/plot <page>`

**Comment by boy0001** [comment]
Edit: Page number is wrong, there is actually only 1 page.
