### ISSUE TITLE
[Bug] World generation bugs claimed plots

### ISSUE THREAD

**Issue by oDeathwingo** [IntellectualSites/PlotSquared#510]
If you claim a plot that is big enough to have uncreated parts
after claim the claimed(loaded) parts will have claimed slabs and new created ones will have stone slabs

How to reproduce
Make big sized plots
stand in a corner of an unloaded/newly generated/uncreated plot (new plot world or corner of the existing one)
and claim the plot
What was expected;
all plot borders changed
What happened;
Borders that were loaded got changed, newly created ones stayed the same

**Comment by MattBDev** [comment]
A possible solution to this would be to check if the chunks are loaded before claiming and force loading them so they can generate before the claim.

**Comment by MattBDev** [comment]
Fixed in a previous unknown update.

**Comment by PhanaticD** [comment]
this might be related? http://pastebin.com/raw/F6DjyWKQ

using build 342 however so there have been changes since that
