### ISSUE TITLE
Plotsquared Chat

### ISSUE THREAD

**Issue by wilsondc15** [IntellectualSites/PlotSquared#520]
The following ticket is a feature request. Similar to how this public, free plugin was made by a developer I know, I would like to request a "/p chat" command. This allows you to have a private chat that only involves people in the plot you are in, but staff can always see all chat by a certain permission, say "plotsquared.chat.all". the Global chat and the Plot chat. For example: The normal chat is the normal chat of the server, and the plot chat is the chat which only the players in the same plot can see. "/p chat" would also be given to players by permission and when executed, would toggle plot chat on and off.

Thank you for reading this!

**Comment by boy0001** [comment]
Use `/plot chat`
Permissions: `plots.chat`
Bypass: `plots.admin.command.chat`

**Comment by Sauilitired** [comment]
The question has been answered, and no further input has been provided.
