### ISSUE TITLE
Customised plot walls get removed at /plot clear

### ISSUE THREAD

**Issue by dvargas135** [IntellectualSites/PlotSquared#521]
Hello,

I've set a custom plot wall so my plot paths look fancier, however, a player did /plot clear and it cleared the walls aswell.

This is the original wall:
![2015-08-08_00 42 12](https://cloud.githubusercontent.com/assets/8147280/9149242/8b32c1f0-3d66-11e5-9547-679d4fc730a1.png)

This is when the player did /plot clear
![2015-08-08_00 38 43](https://cloud.githubusercontent.com/assets/8147280/9149234/5f4163ee-3d66-11e5-9352-e71915be3a7b.png)
![2015-08-08_00 38 55](https://cloud.githubusercontent.com/assets/8147280/9149243/9697338c-3d66-11e5-86c1-3f8fdb02bae1.png)

I'd suggest like an option when creating the world or to change it in config for both the unclaimed and claimed plot: "CUSTOM", so it doesn't get cleared at the command clear.

Thanks in advance,
Dvargas135

**Comment by boy0001** [comment]
Set the claimed and wall block to 0 in the settings.yml.

**Comment by dvargas135** [comment]
It was set when I created the world.
https://gyazo.com/560c6e8af98c1ff36bab463ad1fcfc63
