### ISSUE TITLE
Allow horse riding on roads

### ISSUE THREAD

**Issue by Azfaloth** [IntellectualSites/PlotSquared#522]
I would like to suggest that a feature be added that would allow horses on the road even when the kill road mobs option is on, if a player is riding the horse.

Simply put - Horse or any mob wanders onto the road, it gets despawned.

Horse wanders onto the road but it has a rider, then it doesn't get despawned. If the rider gets off the horse while on the road, then it can be despawned. But if he rides it onto another plot and gets off, it should remain.

Thank you for your time.
Azfaloth

**Comment by boy0001** [comment]
neat idea.
