### ISSUE TITLE
/plot auto grants pre-owned plots to people

### ISSUE THREAD

**Issue by Pangamma** [IntellectualSites/PlotSquared#523]
Not exactly sure WHY this is happening, but new players join in and do /plot auto only to receive plots with other peoples' builds on them. Keep in mind it shouldn't be possible for users to dispose of their plots on my current server setup. So people are getting plots they should not be getting. And it is scaring current members. Hopefully you can come up with the fix soon. If you need any access to the server to check it out, that can be arranged.

**Comment by boy0001** [comment]
Sure, come on IRC: http://webchat.esper.net/?nick=&channels=IntellectualCrafters&fg_color=000&fg_sec_color=000&bg_color=FFF

And let me know your IP on there.

**Comment by dextonanderson** [comment]
I can confirm this

**Comment by boy0001** [comment]
Fixed, please update.
