### ISSUE TITLE
Chinese.yml can't be use!

### ISSUE THREAD

**Issue by Antecer** [IntellectualSites/PlotSquared#525]
Because the PlotSquared.use_THIS.yml already Changed format！

Can you update the Chinese.yml ?

**Comment by boy0001** [comment]
If you replace the `PlotSquared.use_THIS.yml` with the chinese, it will populate any missing messages with english. I don't know chinese myself so I can't update it, someone from the community would need to.

Alternatively see here: http://plugins.915mc.com/resources/plotsquared-chinesever.14/
