### ISSUE TITLE
error with featherboard

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#528]
https://gyazo.com/6aed3809ef425d64356e3670ef6a3b94

I only updated plotsquared, havent touched featherboard

**Comment by Sauilitired** [comment]
@PhanaticD - Featherboard must be updated, nag the author about it :imp:

**Comment by boy0001** [comment]
Without any errors in console / or access to the source code, we are unable to figure out why it isn't working.

**Comment by PhanaticD** [comment]
well this is the error http://pastebin.com/ca9bg1aD

**Comment by boy0001** [comment]
It's an issue with featherboard. It's trying to iterate and get the next element of an empty set without first checking the size.
