### ISSUE TITLE
Issue with /plot home

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#529]
/plot home 1 and /plot home 2 both take me to the same plot (3.0.10)

**Comment by PhanaticD** [comment]
also the plot teleported to is different, on 3.0.7 /plot home brings me to a different plot than version 3.0.8

**Comment by EvilOlaf** [comment]
Confirmed.

**Comment by PhanaticD** [comment]
this is fixed now, however I can do /plot home 3 and /plot home 4 even though I only have two plots
