### ISSUE TITLE
Missing border block on merge

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualSites/PlotSquared#532]
When merging two or more plots the border blocks are missing on the spot where the street was before.

http://www0.xup.in/exec/ximg.php?fid=17151362

Using intersection and sideroad schematic. 
Probably not solvable easily.

3.0.8

**Comment by dextonanderson** [comment]
Any progress towards this?

**Comment by MattBDev** [comment]
@EvilOlaf can you let me know if this was fixed or not?

**Comment by EvilOlaf** [comment]
I think so. However I am still on 3.2.26, so I don't know if this is the case in 3.3.x.

**Comment by EvilOlaf** [comment]
Tried with 3.3.3 a couple of times and did not happen again. So as far for now I guess this is fixed.
