### ISSUE TITLE
PlotSquared shifted blocks

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/PlotSquared#536]
The plotsquared grid on my server has shifted 1 block to the east meaning the last line of blocks on the west is considered road and the slabs on the east are considered plot. My server ip in case you want to test this: creativefun.eu
Config: http://pastebin.com/WCGQCnNR

**Comment by boy0001** [comment]
I'll check this out.

**Comment by boy0001** [comment]
Can't replicate with latest version (3.0.12)

**Comment by SecretlyJealous** [comment]
What version am I using? I downloaded version 3.0.0 from the spigot page but the config shows "3.0.9"

**Comment by boy0001** [comment]
Okay, I managed to replicate the issue, so it's definitely fixed now. (try latest on spigot)
