### ISSUE TITLE
Merged plots road bug

### ISSUE THREAD

**Issue by janie177** [IntellectualSites/PlotSquared#537]
When people claim plots, sometimes the roads do not entirely dissapear. They are also sometimes unable to build where the road used to be.

I am on version 2.12.18. This seems like an important bug and I cannot find it reported on here yet. If it is already known, then excuse me for the unnecessary new issue ticket.

**Comment by boy0001** [comment]
If you want to try updating to 3.0.12 to see if that fixes anything:

There are a few closed issues
https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=merged+build+is%3Aclosed+

Let me know if it's still an issue and I'll reopen this ticket.

**Comment by janie177** [comment]
I updated and the problem persists, but I assume the plots affected will have to be unlinked and then be merged again. If the problem occurs in newly linked plots I will let you know.
