### ISSUE TITLE
Gamemode-based flag permissions

### ISSUE THREAD

**Issue by Log1x** [IntellectualSites/PlotSquared#540]
(11:09:16PM) * Edy (webchat@c8AC745C1.dhcp.as2116.net) has joined #IntellectualCrafters
(11:09:33PM) <Edy> Is there specific flag permissions for specific gamemode? 

This guy joined IRC and asked this question, not a bad idea I suppose.

plots.set.flag.gamemode.creative
plots.set.flag.gamemode.survival
plots.set.flag.gamemode.adventure

**Comment by boy0001** [comment]
Already permissions

**Comment by Log1x** [comment]
They exist for each individual gamemode? For example, can set gamemode survival in plot, but not adventure?

**Comment by boy0001** [comment]
My bad, didn't read fully.
