### ISSUE TITLE
How to modify the template file 

### ISSUE THREAD

**Issue by POSCKOO** [IntellectualSites/PlotSquared#544]
How do I modify the template bridge file? I also want to create my own template but do not know what program do.

**Comment by boy0001** [comment]
It's not really intended for modification, although you can open it up like you would a normal zip file (rename it to .zip if you need to). They are mostly to demonstrate a few things you can do with PlotSquared, and is useful if you want to share your world with others.

The templates can, and were all created by following standard installation: https://github.com/IntellectualSites/PlotSquared/wiki/Installation#initial-setup

Then after the world has been created: /plot template export <world>

**Comment by POSCKOO** [comment]
How do I return file .zip to .template?
