### ISSUE TITLE
Player loses ownership of plots

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualSites/PlotSquared#550]
I have a player that owns a two by two megaplot.

After restart (I guess as it happens once a day) the two of these plots are unclaimed and - to say - halfway not linked to the owned plots anymore.

Any idea how to debug this further?

3.0.16

**Comment by EvilOlaf** [comment]
Updated to 3.1.3. Player lost their ownership again.
Trying again with 3.1.3 already running. Last restart was still on 3.0.16

**Comment by EvilOlaf** [comment]
Solved in 3.1.3

**Comment by boy0001** [comment]
Still an issue?
