### ISSUE TITLE
plots.admin.destroy.other bug

### ISSUE THREAD

**Issue by diecode** [IntellectualSites/PlotSquared#552]
I cannot break block with "plots.admin.destroy.other" perm

I think this is the problem: 
```java
 if (Permissions.hasPermission(pp, C.PERMISSION_ADMIN_DESTROY_OTHER)) { 
   return; 
} 
MainUtil.sendMessage(pp, C.NO_PERMISSION_EVENT, C.PERMISSION_ADMIN_DESTROY_OTHER); 
 event.setCancelled(true); 
```

**Comment by boy0001** [comment]
That code is fine, if it's for unowned plots you would need plots.admin.destroy.unowned

**Comment by diecode** [comment]
I tried break block on other player's plot, but I cannot with plots.admin.destroy.other perm. I relogged too.

**Comment by boy0001** [comment]
Does it say you are lacking a permission?

**Comment by diecode** [comment]
https://youtu.be/7aBznTSUzas

**Comment by diecode** [comment]
I tested with 3.1.3 and it is working fine now.

**Comment by diecode** [comment]
Ok, so It is working with 3.1.3, but I need add to "plots.admin.interact.other" too, the "plots.admin.build.other" is not enough.

**Comment by boy0001** [comment]
This is not a bug.

**Comment by Anidam1** [comment]
Hi,i cann't break block and say i lack a permission. what should i do?
