### ISSUE TITLE
chunk update bug on plot clear?

### ISSUE THREAD

**Issue by diecode** [IntellectualSites/PlotSquared#554]
https://www.youtube.com/watch?v=IGD31Ly-d2A

**Comment by PhanaticD** [comment]
same issue

**Comment by boy0001** [comment]
Rendering issue, relog, walk away then back, or right click the blocks as a temporary workaround. Somewhat tedious to fix, but probably possible.

**Comment by PhanaticD** [comment]
btw this only happens on 3.1.0 have not seen it happen with 3.0.16

**Comment by boy0001** [comment]
Wait, it didn't happen on 3.0.16? I've known about the problem for a long time and thought everyone had it...

**Comment by diecode** [comment]
I tested it with 3.1.0 and 3.0.7. Same

**Comment by PhanaticD** [comment]
yea nevermind it does happen I just tested, never noticed it before

**Comment by PhanaticD** [comment]
I know the dev of asyncworldedit had the same issue and managed to fix it maybe ask him =P

**Comment by boy0001** [comment]
Okay, @SBPrime

**Comment by SBPrime** [comment]
If this is only a client side problem (disappears after relog) then this has probably something to do with the chunk update send. Could you send me a link to the code that is responsible for plot clear or provide a sniped how are you cleaning the plots. I had a similar issue, it was in the DirectChunk API update. The send package was malformed.

**Comment by boy0001** [comment]
It's adding it to the chunk send queue for the player. I would guess that because the top sections are air, it must skip sending them:

https://github.com/IntellectualSites/PlotSquared/blob/master/src/main/java/com/plotsquared/bukkit/util/SendChunk.java#L84-L86

**Comment by SBPrime** [comment]
I used the player queue but it did not work for me. I ended up using PacketPlayOutMapChunk.

**Comment by boy0001** [comment]
Thanks for the tip.

**Comment by boy0001** [comment]
Fixed as of: b06349495587455a2da18a86f0f81811206a3988

**Comment by boy0001** [comment]
https://www.youtube.com/watch?v=8XGfR5ctfqM&feature=youtu.be
