### ISSUE TITLE
Players can't build in a corner.

### ISSUE THREAD

**Issue by Endlessfog** [IntellectualSites/PlotSquared#555]
My players can't build in a certain corner. And its random. I just tested on many plots and I was able to build in the corner but when some players claim a plot and try to build in a corner it just doesn't work. the rest of the plot is fine they can do what ever but that one corner is broken or something.

Middle plot is issue plot.
![2015-08-19_18 34 16](https://cloud.githubusercontent.com/assets/6902544/9372162/012191f0-46a1-11e5-9247-fcadf8a73f4d.png)
![2015-08-19_18 34 23](https://cloud.githubusercontent.com/assets/6902544/9372163/012513b6-46a1-11e5-89c6-9bfc4b8e5247.png)
![2015-08-19_18 34 26](https://cloud.githubusercontent.com/assets/6902544/9372164/0128ef4a-46a1-11e5-9f54-fe9c8f95e149.png)
![2015-08-19_18 34 32](https://cloud.githubusercontent.com/assets/6902544/9372165/012d8d8e-46a1-11e5-81b9-b3e88de34640.png)

Edit: Okay So We found out the're able to build in that corner now but only if I deop myself. Weird.

**Comment by boy0001** [comment]
What version of PlotSquared?

**Comment by boy0001** [comment]
It is likely spawn protection. In your server.properties disable that.
