### ISSUE TITLE
WorldEdit can remove Y:0 bedrock

### ISSUE THREAD

**Issue by diecode** [IntellectualSites/PlotSquared#557]

**Comment by Log1x** [comment]
Eh, if you can stop this from happening I wouldn't mind this 'enhancement'. Players like to build things using Bedrock but them taking out Y:0 is annoying This goes for breaking it by hand, as well..

**Comment by Theepwner** [comment]
On the contrary, many players like being able to break the bedrock at y=0

**Comment by Log1x** [comment]
Possibly toggleable per-plot world basis or a flag.

**Comment by boy0001** [comment]
Set the 'min_height' in the settings.yml to 0.
