### ISSUE TITLE
Error on plugin disable

### ISSUE THREAD

**Issue by Theepwner** [IntellectualSites/PlotSquared#559]
http://hastebin.com/iradudigoz.rb

Not sure if this was fixed in 3.1.1, but this error showed when using 3.1.0.

**Comment by boy0001** [comment]
Could you try updating? I'm not too sure how to replicate the problem just yet.

**Comment by Theepwner** [comment]
Yeah, didn't happen again.

**Comment by boy0001** [comment]
Resolved.
