### ISSUE TITLE
Plot Info Optional Parameters

### ISSUE THREAD

**Issue by wilsondc15** [IntellectualSites/PlotSquared#561]
This is a feature Request.
Please add the option to get a player's plot info byt using /plot info [player] [player's plot number]

If the second optional parameter is not met, get the plot info for said player's first plot.

Also, having the option to do /plot infoid <X-Coord of a plot> <Z-coord of a plot> would be great.
So you could do /plot infoid 35 67

Thank you for your time and for reading this.

**Comment by boy0001** [comment]
Use /plot info [plotworld];<id>
e.g.
/plot info 5;-6
or
/plot info plotworld;5;-6

**Comment by wilsondc15** [comment]
Thank you for your response, but what about the first part of my original message about using /plot info [player] [player's plot number]? This would be very helpful to have and I do not always know the plot id number but I almost always know the target player's name. Is this possible too?

**Comment by boy0001** [comment]
./plot list <player>
Click on the player's plot to display info.
