### ISSUE TITLE
Plot Clear Optional Parameters

### ISSUE THREAD

**Issue by wilsondc15** [IntellectualSites/PlotSquared#562]
This is a feature Request.
Please add the option to clear a player's plot byt using /plot clear [player] [player's plot number]

If the second optional parameter is not met, clear the plot of said player's first plot.

Also, having the option to do /plot clearid <X-Coord of a plot> <Z-coord of a plot> would be great.
So to clear plot 35:67, you could do /plot clearid 35 67

Thank you for your time and for reading this.

**Comment by boy0001** [comment]
From console you can do:
/plot <plotworld>;<id> clear

**Comment by wilsondc15** [comment]
Thank you for your response, but what about the first part of my original message about using /plot clear [player] [player's plot number]? This would be very helpful to have and I do not always know the plot id number but I almost always know the target player's name. Is this possible too?

**Comment by boy0001** [comment]
As I said in the other issue, you can use `/plot list <player>`
Plot clearing doesn't need direct clearing by player name and index for two reasons:
 - You need to first use plot list to find the index anyway
 - The index may change if the player claims, or deletes a plot
