### ISSUE TITLE
Snowfall on plot?

### ISSUE THREAD

**Issue by diecode** [IntellectualSites/PlotSquared#564]
Hi,

I tried lots of snowy biomes with weather rain flag, but I cannot set snowfall. How can I do it?

**Comment by boy0001** [comment]
COLD_TAIGA

**Comment by diecode** [comment]
https://gyazo.com/4dda4d8274f53b69cf7fc0d090b9de72

**Comment by boy0001** [comment]
It's an issue with chunk sending, if you relog it should fix itself.
