### ISSUE TITLE
errors in console on teleporting to and from plotworld

### ISSUE THREAD

**Issue by Azfaloth** [IntellectualSites/PlotSquared#565]
I get these huge errors in the console when players teleport to the plotworld and from the plotworld to survival world. This has been happening since the latest 3.1.1 update I think

when running /spawn to go from plotworld to world.
http://pastebin.com/XgxGK0r7

when using /t spawn to go from pot world to world
http://pastebin.com/Le50vQAJ

Even when using the warp to teleport from world to plotworld
http://pastebin.com/P9rNmFze

**Comment by boy0001** [comment]
Please update to the latest version

**Comment by Azfaloth** [comment]
The latest version on spigot is 3.1.1? Is there somewhere I can get a newer version? The dev builds link goes to a page with seemingly old builds.
