### ISSUE TITLE
Generating World with mods

### ISSUE THREAD

**Issue by Giulio17** [IntellectualSites/PlotSquared#567]
Hi there, I'm creating a modded server.
I have an issue regarding the generation with some of my mods.
I used Multiverse to generate a world, but this is the result:
![image](https://cloud.githubusercontent.com/assets/4805145/9422078/860d2a7e-4885-11e5-8fd1-a01ada1e6120.png)

Is there a way to avoid the 'water' generation on roads? Or to disable mods from the world generation?

**Comment by boy0001** [comment]
I'm not 100% sure, but trying out a different world type might help. Could you send me your settings.yml for PlotSquared?

**Comment by Giulio17** [comment]
Of course, here it is:
http://pastebin.com/jeJEB0jc

**Comment by Giulio17** [comment]
Well, I "solved" the problem using desert as biome for my world.
The Ars Magica 2 water doesen't spawn in desert biome, so now my world is fixed. Obviously, this is a just a palliative and not a really solution, but for now it works.
