### ISSUE TITLE
PlotSquared Bug when Unclaiming the Plots

### ISSUE THREAD

**Issue by PinoyLifeCraft** [IntellectualSites/PlotSquared#569]
Player have a 1,000 money [ i set claiming is 1,000 ] and when they claim a plot in wolrd:SurvivalPlot they will lose 1,000 money but When they /plot unclaim - the money will be given back ....
I experement the plot squared when they type : /plot unclaim in multiple they will be given 1,000 and 1,000 and 1,000 w0w Player money will be 3,000
Please Fix this Developers :smiley:

**Comment by boy0001** [comment]
This has been fixed, however you should be using plot delete instead, as unclaim is generally an admin command.
