### ISSUE TITLE
Error messages at shutdown

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualSites/PlotSquared#570]
No idea if related to https://github.com/IntellectualSites/PlotSquared/issues/550

http://pastebin.com/pgmq01q0

**Comment by boy0001** [comment]
Can you update plz?

**Comment by EvilOlaf** [comment]
It is updated already. I'll update you tomorrow when the updated version restarts.

**Comment by EvilOlaf** [comment]
`[03:00:33 INFO]: All DB transactions during this session are being validated (This may take a while if corrections need to be made)`

Looks fine.
