### ISSUE TITLE
List not translated

### ISSUE THREAD

**Issue by Techy4198** [IntellectualSites/PlotSquared#572]
It appears that the plot list (as shown by /plot list all, /plot list mine etc.) does not use the entries in the translation files, and as such does not use colors from styles.yml. The header does, but not the list contents or navigation arrows. Not really much else to explain. 
![2015-08-22_18 04 03](https://cloud.githubusercontent.com/assets/9480839/9424997/92ed82f2-48f8-11e5-8642-f1e6be9a37cb.png)

**Comment by boy0001** [comment]
Temporary fix: disable `fancy` chat in the settings.yml

**Comment by Techy4198** [comment]
Thanks - ETA for a proper fix?

**Comment by boy0001** [comment]
Need to rewrite the interactive chat to support configurable colors.

**Comment by boy0001** [comment]
Added, will post an update on spigot shortly.
