### ISSUE TITLE
Converted PlotMe UUIDs are completely mangled

### ISSUE THREAD

**Issue by Techy4198** [IntellectualSites/PlotSquared#573]
The only way I can properly describe what's happening here is very long and in depth, so please take the time to read every sentence.

I have a rather large number of plots in PlotMe. I MANUALLY ensured that the UUID of any users who have ever changed their names are entirely correct.

The next thing I do is convert to PlotSquared, using EXACTLY the methods I should be, although afterwards retrying with every variation I can think of, and this happens.

When plotme-convert.cache-uuids is enabled, I log in to the server to find that only MY plots have issues - They are all displayed as owned by 'Unknown' - /plot list Unknown confirms this, listing only as many plots as I have, every single one is actually mine.

Somehow when I log in and the server caches my real UUID (d6810414-0919-4d13-b7d2-5b037fe26726), that breaks stuff. Upon inspection, the UUID that is stored in the database is bde3691f-9ef8-3cb1-800d-42b79b02bd25 - that is not a valid online UUID, and is certainly not my offline UUID.

When I try with plotme-convert.cache-uuids OFF, every single plot owner on the server gets changed to this wrong format. Attempting /plot list Unknown this time simply lists as many plots as there are on the server total.

When manually entering my correct UUID in the database, or creating NEW plots, the UUID is stored correctly. The issue is converting from PlotMe to PlotSquared.

What is going wrong, and can I fix it or does it require an in-code fix?

**Comment by Techy4198** [comment]
Sorry if this is simply my own error and not a bug, but given the extent to which I have tried to debug this myself I'm inclined to say it's very likely a bug.

**Comment by boy0001** [comment]
Are you able to come on IRC and I can help you resolve this?

**Comment by Techy4198** [comment]
Maybe tomorrow (GMT time zone - not sure how that works for you)

**Comment by boy0001** [comment]
Okay: http://webchat.esper.net/?nick=&channels=IntellectualCrafters&fg_color=000&fg_sec_color=000&bg_color=FFF

**Comment by Techy4198** [comment]
I'm on for a while from now, but will be available throughout most of the day.

**Comment by boy0001** [comment]
Okay.

**Comment by Techy4198** [comment]
What name will you be using on IRC?

**Comment by boy0001** [comment]
Empire92

**Comment by boy0001** [comment]
Resolved. Please comment if I am mistaken.
