### ISSUE TITLE
some plot bugs that have to do with merging/claiming

### ISSUE THREAD

**Issue by Theepwner** [IntellectualSites/PlotSquared#574]
http://i.imgur.com/tXj33kH.png

Looking at the image, the 2 smaller plots on the left are actually apart of the bigger plot on the right (merged), yet the roads remain. You can build on the roads however, just the roads weren't removed on merge.

Also, the plot border before claim (stone slab) is still there on the 2 plots to the right, when they should be quartz slabs when claimed (how we set it up).

We have multiple instances of this bug.

I've tried reproducing this issue, but it seems it's now fixed? Was this a recently resolved bug?

**Comment by boy0001** [comment]
There were some issues fixed with merging in recent updates, however that was database related. I will have to investigate the border issue further.
