### ISSUE TITLE
Plot merge limit

### ISSUE THREAD

**Issue by boy0001** [IntellectualSites/PlotSquared#577]

**Comment by Amli2011** [comment]
Hi!

Thank you for pointing me here. But it was empty.... Here is the case as a little reminder:

Hi!

Is there a way to limit the size of a merged plot? something like max size 4x4 or max 16 plots merged together?
I did give the players 127 plots, and limited the auto claim to 16. And kind of hoped for a lot of small plots.....

Is there something like plots.auto.mega.16 or plots.mega.16 or could anyone with more knowledge than me make this function?

Not currently, you can limit the plot auto claim size, but not merges after the plot was claimed. I will add this to the list of things to do:
https://github.com/IntellectualSites/PlotSquared/issues/577

**Comment by boy0001** [comment]
It was closed as it was added to the plugin: f2d56ec2316af0f83d376ea02fc17e3381b6ead2
plots.merge.#

**Comment by Amli2011** [comment]
To fast to belive ;)
Love the plugin and your work!
