### ISSUE TITLE
Plot "Done" Bugs

### ISSUE THREAD

**Issue by Log1x** [IntellectualSites/PlotSquared#580]
Few bugs with the new "Done" system.

1) **/p done** did a small lag spike for ~2 seconds.
2) **/p list done** returns nothing. (attempted it while standing in the plot I just marked as Done above)
3) **/p continue** generates this error: http://pastie.org/pastes/10378684/text?key=jqkbxehkcoxf2nzsilsmca

<3

**Comment by boy0001** [comment]
Fixed

**Comment by Log1x** [comment]
Looks good.

Few things:

1) Setting the plot as done doesn't seem to be preventing building.
2) Is the flag supposed to show up in /plot info? Doesn't appear to at the moment.

(10:25:30AM) <<a1m>> I tried the /plot done but I think it is not working correctly. Is this planned or bug?
(11:02:32AM) <<Log1x>> on the latest versin?
(11:02:34AM) <<Log1x>> version*
(11:21:49AM) <<a1m>> yes
(11:21:53AM) <<a1m>> 3.1.8
(11:22:40AM) <<a1m>> It said done successfully, but I can build / break, and I don't see done flag in /p info
(11:23:04AM) <<Log1x>> do you have op? because i dont think done will stop you if you have bypass perms
(11:23:07AM) <<Log1x>> also /p list done
(11:23:17AM) <<Log1x>> as far as the flag, i dnt see it on my end either despite the plots showing up as intended in /p list done
(11:23:19AM) <<Log1x>> so not sure on that one
(11:23:20AM) <<Log1x>> might be a hidden flag
(11:31:50AM) <<a1m>> I deopped my character
(11:32:13AM) <<Log1x>> ok ill mention it on the issue tracker
(11:32:19AM) <<a1m>> I cannot set done flag too. /p flag set done 444444
(11:32:46AM) <<a1m>> thanks

**Comment by boy0001** [comment]
`1) Setting the plot as done doesn't seem to be preventing building.1`

**Comment by boy0001** [comment]
``` yml
approval:
  done:
    required-for-download: false
    restrict-building: true <---
    counts-towards-limit: false
```
Works for me.

**Comment by Log1x** [comment]
Should have tested the restrict-building myself instead of listening to IRC. ;)

Thanks <3
