### ISSUE TITLE
Converting taking too long? (Is it done?!)

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [IntellectualSites/PlotSquared#582]
So I'm not sure I converted my plots correctly.
I started my server with plotme.jar and plotsquared.jar and PM locked the database. Then I deleted plotme.jar and started it again.
Here's the log: http://pastebin.com/hPExFrev
Is it done converting? (Mind the last line)

**Comment by boy0001** [comment]
Yes, it finished.

**Comment by boy0001** [comment]
*reminder to self to make it more obvious.
