### ISSUE TITLE
Bypassing plot border

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/PlotSquared#585]
I've recently been informed that it's possible to bypass the plot border.

Here are some pictures:
![plotborderglitch](https://cloud.githubusercontent.com/assets/10485646/9560971/c92855b4-4e29-11e5-973d-1a78c00d8d96.png)
![plotborderglitch](https://cloud.githubusercontent.com/assets/10485646/9560974/e4da989e-4e29-11e5-8e48-9fe4c7b7d115.png)

This seems to happen when a player uses bonemeal to grow a tree at the edge of a plot. I'm currently using version 3.1.6

**Comment by Vekseid** [comment]
In 3.1.10 I was also able to get falling sand entities to cross the road via tnt explosions.

**Comment by boy0001** [comment]
@Vekseid that was fixed already.
