### ISSUE TITLE
Conversion from PlotMe to PlotSquared not working.

### ISSUE THREAD

**Issue by nickthekidNL** [IntellectualSites/PlotSquared#586]
So it installs the plugin and it has all the world borders correctly but when doing /p2 info it doesn't show that the plot is claimed even though i was claimed in PlotMe. Also doing /p2 auto (something like that i can't remember the command right now) will send me into my survival world and then if u were to do /p2 in there it would say no plot found. I have setup all the generators i have deleted Plotme.jar and have setup all the stuff as said in directions. If someone can it would be really helpful to get this fixed as fast as possible. I have reinstalled PlotMe so at the moment the server is on white list but has PlotSquared and PlotMe on it.

**Comment by Maescool** [comment]
If you are using Multiverse, make sure the generator is only setup on the plot world, not on the server load world (that one should be null)

**Comment by nickthekidNL** [comment]
@Maescool i know that, I have it set up the right way but either way it still wouldnt have to do with that. The main problem is that it is not showing plots where claimed where in plotme it was claimed....The plugin is not moving the data from plot me to plots squared

**Comment by boy0001** [comment]
Can you send me your PlotMe + PlotSquared databases after conversion?

**Comment by nickthekidNL** [comment]
@boy0001 it works but if you go to my other problem u can see the other problem
https://github.com/IntellectualSites/PlotSquared/issues/596

**Comment by nickthekidNL** [comment]
@boy0001 The problem has been fixed I don't know how i did it but i did it. But i have found something elese i am having trouble with here it is
https://github.com/IntellectualSites/PlotSquared/issues/596

**Comment by Dreadonator** [comment]
The converting did not work for me and it messed up my Server! pls fix it!!

**Comment by MattBDev** [comment]
Merging with #583 since they both involve the converter getting something wrong.
