### ISSUE TITLE
Feature Request  - Add commandnames in config

### ISSUE THREAD

**Issue by Legoman99573** [IntellectualSites/PlotSquared#587]
I feel like this would be useful is so that a server owner can change the commandname, or spice it up. For example like this in the config

Commands:
        plotsquare main command: ps,plots,p
        claim command: claim, c, take
and so on.
This would be a good addition in 3.1.17 update. PlotMe and Plotz dont offer this, and buycraft does this as well

**Comment by manuelgu** [comment]
Implemented with recent versions, see `commands.yml`
