### ISSUE TITLE
PlotSquared Timings

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/PlotSquared#591]
![plotsquaredlag](https://cloud.githubusercontent.com/assets/10485646/9568555/f6b31656-4f44-11e5-9314-67481c469941.png)
I noticed that with 450 players on my creative server, plotsquared starts to cause lag. Each plot is 516x516 and I'm using version 3.1.6.

**Comment by boy0001** [comment]
That's plot expiry running. Want to send me your settings.yml and I'll see if I can optimize a few things for your specific setup?

**Comment by SecretlyJealous** [comment]
Thanks, I really appreciate this.
Settings: http://pastebin.com/ve4MQx9d

**Comment by boy0001** [comment]
I decreased the intensity of the task for the next version.
