### ISSUE TITLE
WorldEdit throwing strange exceptions

### ISSUE THREAD

**Issue by MatteCarra** [IntellectualSites/PlotSquared#598]
Exceptions: http://pastebin.com/LNVcK59t
tonight I will try to reboot, and I will update this issue.
Thank you very much for the work!

**Comment by boy0001** [comment]
Do not use `/reload` or a plugin manager to reload PlotSquared. It can result in instability. Would this be the cause?

**Comment by MatteCarra** [comment]
Yes it can ne.
Thanks
