### ISSUE TITLE
Getting this error when trying to convert from plotme

### ISSUE THREAD

**Issue by 2Fast08** [IntellectualSites/PlotSquared#599]
I just pulled the build from here and built it, it's still pulling 0 plots from plotme.

Here is a view of the db, the clusters located above the screenshot are 0.
https://gyazo.com/d433146463f0138ef06d3f5f058cde8e

**Comment by Maescool** [comment]
you have logs?
also, make sure you have plotme 0.16 loaded for the migration

**Comment by boy0001** [comment]
Clusters are something else, it's the `plots` database that you want to look at, which is populated.
