### ISSUE TITLE
Merged plots get unlinked after a time

### ISSUE THREAD

**Issue by overallwarf47** [IntellectualSites/PlotSquared#602]
There's a server that use P² as the plots plugin, whose before used PlotMe.
The prints of the bug is following:
http://imgur.com/OdnQY5k,BccGPtL,GlT4VgR,YntUWIc

As you can see there's a road inside of merged plots.

Have this bug fixed in an update? Is this a database bug?

**Comment by diecode** [comment]
What is your PlotSquared version?

**Comment by overallwarf47** [comment]
The last public one

**Comment by boy0001** [comment]
That should have been fixed a while ago. Just relink the plots and it should be fine.
