### ISSUE TITLE
Informational PlotSquared Timing

### ISSUE THREAD

**Issue by 2Fast08** [IntellectualSites/PlotSquared#603]
I was doing some timing of the events of the plugin and found these two which are very high. Just passing along.

https://gyazo.com/754c965055a9fa297186bd395aedd39e
https://gyazo.com/ecb6139794b6c57c62d713b6ee1bb6a5
https://gyazo.com/6c6a61298ceda30028da5538a6148b23

**Comment by boy0001** [comment]
It's probably normal:
 - Some chunk task is running, i.e. plot moving, expiry, world trimming etc

Out of context:
 - Those percentages are of the specific plugin and give no indication on the relation to the server as a whole.
