### ISSUE TITLE
ChestShop Issue

### ISSUE THREAD

**Issue by UltimateRag3r** [IntellectualSites/PlotSquared#606]
Great plugin, but when you left click the sign to sell, it sells AND it also says You are lacking permission node: plots.admin.interact.other and when I give him the permission ^, then it says plots.admin.destroy.other https://gyazo.com/874c23f7b70f8e8852ff1521967a3ccf
So this plugin can't be used for prison because there is no way for people to sell their items without saying that.

**Comment by boy0001** [comment]
Add signs to the global use flag: https://github.com/IntellectualSites/PlotSquared/wiki/Usage:-Plot-flags#default-flags

You will need to look up the item id.
