### ISSUE TITLE
Plot Home and Auto info a different world (BUG)

### ISSUE THREAD

**Issue by justin57754** [IntellectualSites/PlotSquared#608]
Hello! I have recently got PlotSquared and when ever I do /plot auto or /plot home I go to the default world but I really want to go into the plotworld. I have my settings.yml in the pastebin below! Please help!!
Settings.yml: http://pastebin.com/PMAHw7Br

**Comment by boy0001** [comment]
Restart the server after creating the world. I'll fix this for the next version
