### ISSUE TITLE
Plot between two plots?

### ISSUE THREAD

**Issue by Stampede2011** [IntellectualSites/PlotSquared#609]
Hello i recently installed the PlotSquared plugin and i'm having massive issues! first of all the config doesn't seem like its right to what i have in game. Second i made a new world generation using /plot setup and going through all the steps. After that when doing /plot auto it makes a plot in between another plot. Heres my config. http://pastebin.com/yTF79hL8 and heres a picture https://gyazo.com/7a6d7677402533aeab84e9739caed350

**Comment by Sauilitired** [comment]
Was most likely caused by a default configuration running on a pre-existent world. Closing, as it cannot possibly be relevant anymore.
