### ISSUE TITLE
Trouble creating plot clusters

### ISSUE THREAD

**Issue by obzidi4n** [IntellectualSites/PlotSquared#610]
Attempting to create a 10x10 cluster with coordinates 30;30 and 20;20 ... 

The following results in only a single plot created at 20;20 .. 

>[14:58:12 INFO]: obzidi4n issued server command: /plot cluster create testplot 30;30 20;20
>[14:58:12 INFO]: == NEW AUGMENTED POPULATOR FOR: world
>[14:58:12 WARN]: java.lang.NullPointerException
>[14:58:12 WARN]:        at com.mysql.jdbc.PreparedStatement.addBatch(PreparedStatement.java:1012)
>[14:58:12 WARN]:        at com.intellectualcrafters.plot.database.SQLManager$UniqueStatement.addBatch(SQLManager.java:354)
>[14:58:12 WARN]:        at com.intellectualcrafters.plot.database.SQLManager.sendBatch(SQLManager.java:315)
>[14:58:12 WARN]:        at com.intellectualcrafters.plot.database.SQLManager$2.run(SQLManager.java:206)
>[14:58:12 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
>[14:58:12 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
>[14:58:12 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>[14:58:12 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>[14:58:12 WARN]:        at java.lang.Thread.run(Thread.java:745)

![2015-09-06_15 04 21](https://cloud.githubusercontent.com/assets/14152234/9706100/9aaa2ca0-54a8-11e5-85e5-48c434e162ef.png)

**Comment by boy0001** [comment]
- 10x10 would be from `20 to 29`, as `20 to 30` is 11 plots.
 - The first id must be smaller than the second one, so instead try: `/plot cluster create testplot 20;20 29;29`

If it still doesn't work, could you do a `/plot debugpaste` and link that here please?

**Comment by obzidi4n** [comment]
OK that worked - thank you.
