### ISSUE TITLE
Trouble converting from plotme

### ISSUE THREAD

**Issue by Pandoroxus** [IntellectualSites/PlotSquared#611]
I've been trying to convert to p2 from plotme, every time it just says:

06.09 13:34:47 [Server] INFO Could not identify owner for plot: -54;-13 -> 'jdog_2000'
06.09 13:34:47 [Server] INFO Could not identify owner for plot: -54;-14 -> 'FS57'
06.09 13:34:47 [Server] INFO Could not identify owner for plot: -54;-15 -> 'Mulkz'
06.09 13:34:47 [Server] INFO Could not identify owner for plot: -54;-16 -> 'SpeedPvPz'
06.09 13:34:47 [Server] INFO Could not identify owner for plot: -54;-17 -> 'johnhumphries38'
06.09 13:34:47 [Server] INFO Could not identify owner for plot: -54;-18 -> 'TescoValueKills'
06.09 13:34:47 [Server] INFO Could not identify owner for plot: -54;-19 -> 'ZombiePotato69'
06.09 13:34:47 [Server] INFO Could not identify owner for plot: -54;-20 -> 'tucker134'
06.09 13:34:47 [Server] INFO Could not identify owner for plot: -54;-22 -> 'rogerfu8'
06.09 13:34:47 [Server] INFO Could not identify owner for plot: -54;-23 -> 'Simrac'
06.09 13:34:47 [Server] INFO Could not identify owner for plot: -54;-24 -> 'x_Height'
06.09 13:34:47 [Server] INFO Could not identify owner for plot: -54;-25 -> 'yipi30'

etc; plotme is using MySQL. In all it ends up being slightly more than half of the plots that aren't converted to plotme. I haven't been able to figure out what the difference between the names that converted and the names that didn't is. Any help would be greatly appreciated.

**Comment by boy0001** [comment]
Can you please provide a full log of the conversion so I can see what connector it is using etc. You can find a log in your `logs` folder.

**Comment by Pandoroxus** [comment]
Sure, the log is here: https://drive.google.com/file/d/0B7snwoXQtZ5zdlRrOHBNNjV5dTA/view?usp=sharing

**Comment by EvilOlaf** [comment]
Just as a sidenote. Your Protocollib is outdated. Get a newer build here: http://ci.shadowvolt.com/job/ProtocolLib/
Also you're still using WG5.9 in combination with WE6.0. That could also cause issues not compulsory with P^2.

**Comment by Pandoroxus** [comment]
Yeh, we're in the process of updating our server, and I haven't gotten around to updating all the plugins yet, thanks for the link though :D

**Comment by Maescool** [comment]
Can you run ````DESCRIBE plotmePlots;```` in your mysql database?
and post back the result

**Comment by Pandoroxus** [comment]
The results looks like https://gyazo.com/92225e73a884eca98e2aea665ea367e5

**Comment by Maescool** [comment]
Seems your plotme is older than 0.16, so it doesn't store uuid's that is the problem..

I think if somebody expands the migration module a bit, so it uses the uuid resolv/api on the ````owner == null```` error messaging part, it could handle this migration
Take note, this could give issues with people who changed their name

**Comment by Pandoroxus** [comment]
Oh, so if I were to switch the owner column from their names to their uuid's it would work correctly? That doesn't seem like it would take very long if that's all I need to do.

**Comment by Maescool** [comment]
No, you are missing the column ownerid, which has the uuid of that user stored in a byte format..
not that easy for a non-technical person to add that data in there..

it might be easier if p2 can handle this, but it should throw out warnings for names that might have been changed.. I guess it could refer to the local world-uuid cache

**Comment by Pandoroxus** [comment]
I'm fairly sure I could write a quick function to convert them all, I'm fairly competent at coding, and the api is pretty simple, my only question would be what's the actual data type of the column, binary(16), or something else?

**Comment by Maescool** [comment]
+-----------------+--------------+------+-----+---------+-------+
| Field           | Type         | Null | Key | Default | Extra |
+-----------------+--------------+------+-----+---------+-------+
| ownerId         | tinyblob     | YES  |     | NULL    |       |
+-----------------+--------------+------+-----+---------+-------+

https://github.com/WorldCretornica/PlotMe-Core/blob/0.16.1/src/main/java/com/worldcretornica/plotme_core/SqlManager.java#L385
and
https://github.com/WorldCretornica/PlotMe-Core/blob/0.16.1/src/main/java/com/worldcretornica/plotme_core/utils/UUIDFetcher.java#L75

for reference

**Comment by Pandoroxus** [comment]
Converted them, thanks for all the help :D
