### ISSUE TITLE
Permission won't load [ Group Manager ]

### ISSUE THREAD

**Issue by PinoyLifeCraft** [IntellectualSites/PlotSquared#612]
All permission are there and works fine :smile: 
But when i [ /manload ] PlotSquared Permission won't load and all default player will be lacking permission....
Please Help !!!!! :disappointed:

**Comment by Legoman99573** [comment]
clear the config out and insert the perm manually in-game like
/mangaddp <Group> <Permission> and it should work.

**Comment by PinoyLifeCraft** [comment]
ok i will try it
