### ISSUE TITLE
What kind of flags are there for a plot

### ISSUE THREAD

**Issue by TotalMM** [IntellectualSites/PlotSquared#616]
With /plot flag
I want to know what kind of flags there are, like gamemode, time and so on

HALP PLEZ

**Comment by dextonanderson** [comment]
The flags are located here: 
https://github.com/IntellectualSites/PlotSquared/wiki/Usage:-Plot-flags

**Comment by TotalMM** [comment]
More help, I can't get player-interact to work, it says it's not a valid flag

**Comment by EvilOlaf** [comment]
Do you use a current version of P^2?

**Comment by TotalMM** [comment]
I am not even sure xD
I don't own the server, I just need to know for a creative plot

**Comment by EvilOlaf** [comment]
Then you need to talk to your server administrator. Maybe you don't even have permission for this flag.

**Comment by TotalMM** [comment]
No it comes up with an error that it isn't a valid flag

**Comment by TotalMM** [comment]
I type /plot flag set player_interaction true

**Comment by EvilOlaf** [comment]
Try `player-interact`
https://github.com/IntellectualSites/PlotSquared/wiki/Flag:-player-interact

**Comment by TotalMM** [comment]
tried that, didn't work
