### ISSUE TITLE
Road Schematic Doesn't Generate | URGENT

### ISSUE THREAD

**Issue by Haoiscoll** [IntellectualSites/PlotSquared#625]
Hey There,
I just started to use PlotSquared since PlotMe was discontinued, and I have to say, the plugin is yes,better than PlotMe.
But lately, I hit a problem. Just as the title says, The road schematic doesn't generate.
I've built a road schematic around the plot 0;0, and ran the command /plot createroadschematic .
After that I tried /plot debugroadregen on a few other plots, and it worked perfectly.
And here comes the problem. When I try to do /plot regenallroads, it said it needs console to execute the command. So I headed over to the console and ran /plot regenallroads.
And so after I ran /plot regenallroads I opened Minecraft and waited for the roads to regenerate.
But after 1 HOUR the roads still don't regenerate,and nothing is up on the console.
I am 100% sure that I DID ran the command on console, because I tested executing the command /ban randomguy Testing before I did the /plot regenallroads on the console and it works.
I'm really confused about this bug and hope you can help me fix this.
PlotSquared Version: Latest 
Server Version: 1.8 Spigot
Online-Mode: Premium
P.S After I ran the command /plot regenallroads, nothing came up on the console either. So yeah.
P.P.S If you need more info about the server don't hesitate to ask, I'll be here to respond.

**Comment by boy0001** [comment]
Can you provide a log of it not working, as well as your full startup log?

**Comment by Haoiscoll** [comment]
Sure, heres the startup log:
Bukkit.jar
24.09 20:20:48 [Server] INFO - Use: /plot update
24.09 20:20:48 [Server] INFO PlotSquared v3.2.0 is available:
24.09 20:20:47 [Server] INFO Checking for the latest version of Skript...
24.09 20:20:47 [Server] INFO Post-enable finished.
24.09 20:20:47 [Server] INFO Post-enable running...
24.09 20:20:47 [Server] Startup Done (8.393s)! For help, type "help" or "?"
24.09 20:20:47 [Server] INFO Server permissions file permissions.yml is empty, ignoring it
24.09 20:20:47 [Server] INFO Enabling TitleManager v1.5.11
24.09 20:20:47 [Server] INFO 7 placeholder hooks have been registered and are enabled.
24.09 20:20:47 [Server] INFO Hooked into Vault for permissions placeholders!
24.09 20:20:47 [Server] INFO Hooked into Vault for economy placeholders!
24.09 20:20:47 [Server] INFO Hooked into PlotSquared for placeholders!
24.09 20:20:47 [Server] INFO Hooked into EZRanksLite for placeholders!
24.09 20:20:47 [Server] INFO Hooked into Essentials for placeholders!
24.09 20:20:47 [Server] INFO Hooked into AutoSell for placeholders!
24.09 20:20:47 [Server] INFO 1 formats loaded!
24.09 20:20:47 [Server] INFO Enabling DeluxeChat v1.4.9.1
24.09 20:20:47 [Server] INFO An update for EZRanksLite (EZRanksLite v2.1.2) is available at http://www.spigotmc.org/resources/ezrankslite.762/
24.09 20:20:47 [Server] INFO 1 rankup cost multipliers loaded!
24.09 20:20:47 [Server] INFO 1 rankup cost discounts loaded!
24.09 20:20:47 [Server] INFO 28 Ranks loaded with 27 unique RankUps!
24.09 20:20:47 [Server] INFO Loading EZRanksLite messages.yml
24.09 20:20:47 [Server] ERROR EZRanksLite hooked into Essentials!!
24.09 20:20:47 [Server] ERROR EZRanksLite hooked into AutoSell!!
24.09 20:20:47 [Server] INFO 1.8-R0.1-SNAPSHOT
24.09 20:20:47 [Server] INFO Enabling EZRanksLite v1.6.2.5
24.09 20:20:46 [Server] INFO 30 shop signs have been loaded!
24.09 20:20:46 [Server] INFO 1 permission based shop multipliers have been loaded!
24.09 20:20:46 [Server] INFO 1 permission based multipliers loaded!
24.09 20:20:46 [Server] INFO 1 saved multipliers have been loaded!
24.09 20:20:46 [Server] INFO BlockBreakEvent priority set to HIGHEST!
24.09 20:20:46 [Server] INFO PrisonMines was detected and shops will be set per mine!
24.09 20:20:46 [Server] INFO 4 auto smelt entries loaded!
24.09 20:20:46 [Server] INFO 27 shops loaded!
24.09 20:20:46 [Server] INFO Loading AutoSell messages.yml
24.09 20:20:46 [Server] INFO Enabling AutoSell v1.4.3
24.09 20:20:46 [Server] INFO Enabling PrisonMines v1.4.4
24.09 20:20:46 [Server] INFO Version 2.5-b691 (API v18) Enabled - By Rigby, fernferret, lithium3141 and main--
24.09 20:20:46 [Server] INFO 2 - World(s) loaded.
24.09 20:20:46 [Server] INFO Loaded configuration for world 'SlashPlot'
24.09 20:20:46 [Server] INFO (SlashPlot) Fire spread is UNRESTRICTED.
24.09 20:20:46 [Server] INFO (SlashPlot) Lava fire is blocked.
24.09 20:20:46 [Server] INFO (SlashPlot) Lighters are PERMITTED.
24.09 20:20:46 [Server] INFO (SlashPlot) TNT ignition is PERMITTED.
24.09 20:20:45 [Server] INFO Preparing start region for level 1 (Seed: 2115656137281911387)
24.09 20:20:45 [Server] INFO plugins/PlotSquared/schematics/GEN_ROAD_SCHEMATIC/SlashPlot/plot.schematic doesn't exist
24.09 20:20:45 [Server] INFO - manager: com.intellectualcrafters.plot.generator.HybridPlotManager
24.09 20:20:45 [Server] INFO - plotworld: com.intellectualcrafters.plot.generator.HybridPlotWorld
24.09 20:20:45 [Server] INFO - generator: com.plotsquared.bukkit.generator.BukkitGeneratorWrapper
24.09 20:20:45 [Server] INFO Detected world load for 'SlashPlot'
24.09 20:20:45 [Server] INFO Experience Merge Radius: 3.0
24.09 20:20:45 [Server] INFO Clear tick list: false
24.09 20:20:45 [Server] INFO Chunks to Grow per Tick: 650
24.09 20:20:45 [Server] INFO Zombie Aggressive Towards Villager: true
24.09 20:20:45 [Server] INFO Arrow Despawn Rate: 1200
24.09 20:20:45 [Server] INFO Item Despawn Rate: 6000
24.09 20:20:45 [Server] INFO Item Merge Radius: 2.5
24.09 20:20:45 [Server] INFO Allow Zombie Pigmen to spawn from portal blocks: true
24.09 20:20:45 [Server] INFO View Distance: 10
24.09 20:20:45 [Server] INFO Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
24.09 20:20:45 [Server] INFO Max TNT Explosions: 100
24.09 20:20:45 [Server] INFO Custom Map Seeds:  Village: 10387312 Feature: 14357617
24.09 20:20:45 [Server] INFO Max Entity Collisions: 8
24.09 20:20:45 [Server] INFO Sending up to 10 chunks per packet
24.09 20:20:45 [Server] INFO Structure Info Saving: true
24.09 20:20:45 [Server] INFO Random Lighting Updates: false
24.09 20:20:45 [Server] INFO Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
24.09 20:20:45 [Server] INFO Alternative Hopper Ticking: false
24.09 20:20:45 [Server] INFO Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
24.09 20:20:45 [Server] INFO Entity Activation Range: An 32 / Mo 32 / Mi 16
24.09 20:20:45 [Server] INFO Mob Spawn Range: 4
24.09 20:20:45 [Server] INFO Wheat Growth Modifier: 100%
24.09 20:20:45 [Server] INFO Sapling Growth Modifier: 100%
24.09 20:20:45 [Server] INFO Pumpkin Growth Modifier: 100%
24.09 20:20:45 [Server] INFO Mushroom Growth Modifier: 100%
24.09 20:20:45 [Server] INFO Melon Growth Modifier: 100%
24.09 20:20:45 [Server] INFO Cane Growth Modifier: 100%
24.09 20:20:45 [Server] INFO Cactus Growth Modifier: 100%
24.09 20:20:45 [Server] INFO Nerfing mobs spawned from spawners: false
24.09 20:20:45 [Server] INFO Replace Blocks: [1, 5]
24.09 20:20:45 [Server] INFO Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
24.09 20:20:45 [Server] INFO Engine Mode: 1
24.09 20:20:45 [Server] INFO Anti X-Ray: true
24.09 20:20:45 [Server] INFO No updates found!
24.09 20:20:45 [Server] INFO [AllPay] - Version 13.0 - hooked into Essentials Economy for Multiverse-Core v2.5-b691
24.09 20:20:45 [Server] INFO Enabling Multiverse-Core v2.5-b691
24.09 20:20:44 [Server] INFO Essentials: Using GroupManager based permissions.
24.09 20:20:44 [Server] INFO [Vault][Economy] Essentials Economy hooked.
24.09 20:20:44 [Server] INFO Using locale en_US
24.09 20:20:44 [Server] INFO Using locale en_US
24.09 20:20:44 [Server] INFO 1.8-R0.1-SNAPSHOT
24.09 20:20:44 [Server] INFO git-Spigot-c3c767f-33d5de3 (MC: 1.8)
24.09 20:20:44 [Server] INFO Bukkit version format changed. Version not checked.
24.09 20:20:44 [Server] INFO Enabling Essentials vTeamCity
24.09 20:20:44 [Server] INFO Loading region data...
24.09 20:20:44 [Server] INFO Loaded configuration for world 'world'
24.09 20:20:44 [Server] INFO (world) Fire spread is UNRESTRICTED.
24.09 20:20:44 [Server] INFO (world) Lava fire is blocked.
24.09 20:20:44 [Server] INFO (world) Lighters are PERMITTED.
24.09 20:20:44 [Server] INFO (world) TNT ignition is PERMITTED.
24.09 20:20:44 [Server] INFO Enabling WorldGuard v6.0.0-beta-03.1514-
24.09 20:20:44 [Server] INFO Enabling NametagEdit v3.0.3
24.09 20:20:44 [Server] INFO Out of 163 classes, 156 classes were loaded from SkQuery
24.09 20:20:43 [Server] INFO Beginning to process a total of 163 from SkQuery
24.09 20:20:43 [Server] INFO Finished snooping of SkQuery with 163 classes.
24.09 20:20:43 [Server] INFO Locating classes from SkQuery...
24.09 20:20:43 [Server] INFO Snooping enabled from com.w00tmast3r.skquery.SkQuery
24.09 20:20:43 [Server] INFO Enabling SkQuery v3.21.4
24.09 20:20:43 [Server] INFO Checking for updates...
24.09 20:20:43 [Server] INFO Clearlag is now enabled!
24.09 20:20:43 [Server] INFO Modules have been loaded!
24.09 20:20:43 [Server] INFO Loading modules...
24.09 20:20:43 [Server] INFO Enabling ClearLag v2.8.2
24.09 20:20:43 [Server] INFO Enabling BowTrails v1.2
24.09 20:20:43 [Server] INFO ServerListPlus v3.3.2 enabled.
24.09 20:20:43 [Server] INFO Successfully loaded!
24.09 20:20:43 [Server] ERROR ProtocolLib IS NOT INSTALLED! Most features will NOT work!
24.09 20:20:43 [Server] INFO [Core] Loaded configuration: CoreConf
24.09 20:20:43 [Server] INFO [Core] Loaded configuration: PluginConf
24.09 20:20:43 [Server] INFO [Core] Loaded configuration: ServerStatusConf
24.09 20:20:42 [Server] INFO [Core] Reloading configuration...
24.09 20:20:42 [Server] INFO Starting...
24.09 20:20:42 [Server] ERROR ProtocolLib IS NOT INSTALLED! Most features will NOT work!
24.09 20:20:42 [Server] INFO Enabling ServerListPlus v3.3.2
24.09 20:20:42 [Server] INFO ~ created by & © Peter Güttinger aka Njol ~
24.09 20:20:42 [Server] INFO Loaded a total of 11504 english aliases
24.09 20:20:41 [Server] INFO Enabling Skript v2.1.2
24.09 20:20:41 [Server] INFO Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_8_R1 as the Bukkit adapter
24.09 20:20:41 [Server] INFO WEPIF: GroupManager detected! Using GroupManager for permissions.
24.09 20:20:41 [Server] INFO Enabling WorldEdit v6.0;3342-78f975b9
24.09 20:20:41 [Server] INFO Version 3.12.0-BETA2-sASO-b813 is enabled.
24.09 20:20:41 [Server] INFO Packet level access: ProtocolLib is not available.
24.09 20:20:41 [Server] INFO Inventory checks: FastConsume is available, disabled InstantEat.
24.09 20:20:41 [Server] INFO Added block-info for Minecraft 1.8 blocks.
24.09 20:20:41 [Server] INFO Added block-info for Minecraft 1.7.2 blocks.
24.09 20:20:41 [Server] INFO Added block-info for Minecraft 1.6.1 blocks.
24.09 20:20:41 [Server] INFO Added block-info for Minecraft 1.5 blocks.
24.09 20:20:41 [Server] INFO McAccess set to: 1.8 / Spigot-CB-1.8
24.09 20:20:41 [Server] INFO Enabling NoCheatPlus v3.12.0-BETA2-sASO-b813
24.09 20:20:41 [Server] INFO [Vault][Chat] GroupManager - Chat hooked.
24.09 20:20:41 [Server] INFO [Vault][Permission] GroupManager hooked.
24.09 20:20:41 [Server] INFO GroupManager version 2.1.31 (Phoenix) is enabled!
24.09 20:20:41 [Server] INFO GroupManager - INFO - Backups will be retained for 24 hours!
24.09 20:20:41 [Server] INFO GroupManager - INFO - Scheduled Data Saving is set for every 10 minutes!
24.09 20:20:41 [Server] INFO GroupManager - INFO - Superperms support enabled.
24.09 20:20:41 [Server] INFO GroupManager - INFO - World Found: world
24.09 20:20:41 [Server] INFO Enabling GroupManager v2.1.31 (Phoenix)
24.09 20:20:40 [Server] INFO Preparing spawn area: 50%
24.09 20:20:39 [Server] INFO Preparing start region for level 0 (Seed: -5331467127444672103)
24.09 20:20:39 [Server] INFO Experience Merge Radius: 3.0
24.09 20:20:39 [Server] INFO Clear tick list: false
24.09 20:20:39 [Server] INFO Chunks to Grow per Tick: 650
24.09 20:20:39 [Server] INFO Zombie Aggressive Towards Villager: true
24.09 20:20:39 [Server] INFO Arrow Despawn Rate: 1200
24.09 20:20:39 [Server] INFO Item Despawn Rate: 6000
24.09 20:20:39 [Server] INFO Item Merge Radius: 2.5
24.09 20:20:39 [Server] INFO Allow Zombie Pigmen to spawn from portal blocks: true
24.09 20:20:39 [Server] INFO View Distance: 10
24.09 20:20:39 [Server] INFO Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
24.09 20:20:39 [Server] INFO Max TNT Explosions: 100
24.09 20:20:39 [Server] INFO Custom Map Seeds:  Village: 10387312 Feature: 14357617
24.09 20:20:39 [Server] INFO Max Entity Collisions: 8
24.09 20:20:39 [Server] INFO Sending up to 10 chunks per packet
24.09 20:20:39 [Server] INFO Structure Info Saving: true
24.09 20:20:39 [Server] INFO Random Lighting Updates: false
24.09 20:20:39 [Server] INFO Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
24.09 20:20:39 [Server] INFO Alternative Hopper Ticking: false
24.09 20:20:39 [Server] INFO Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
24.09 20:20:39 [Server] INFO Entity Activation Range: An 32 / Mo 32 / Mi 16
24.09 20:20:39 [Server] INFO Mob Spawn Range: 4
24.09 20:20:39 [Server] INFO Wheat Growth Modifier: 100%
24.09 20:20:39 [Server] INFO Sapling Growth Modifier: 100%
24.09 20:20:39 [Server] INFO Pumpkin Growth Modifier: 100%
24.09 20:20:39 [Server] INFO Mushroom Growth Modifier: 100%
24.09 20:20:39 [Server] INFO Melon Growth Modifier: 100%
24.09 20:20:39 [Server] INFO Cane Growth Modifier: 100%
24.09 20:20:39 [Server] INFO Cactus Growth Modifier: 100%
24.09 20:20:39 [Server] INFO Nerfing mobs spawned from spawners: false
24.09 20:20:39 [Server] INFO Replace Blocks: [1, 5]
24.09 20:20:39 [Server] INFO Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
24.09 20:20:39 [Server] INFO Engine Mode: 1
24.09 20:20:39 [Server] INFO Anti X-Ray: true
24.09 20:20:39 [Server] INFO -------- World Settings For [world] --------
24.09 20:20:39 [Server] INFO Preparing level "world"
24.09 20:20:39 [Server] INFO **** Beginning UUID conversion, this may take A LONG time ****
24.09 20:20:39 [Server] INFO Key: Auto Clear Days, Value: 365
24.09 20:20:39 [Server] INFO Key: Kill Road Mobs, Value: false
24.09 20:20:39 [Server] INFO Key: DB SQLite Enabled, Value: false
24.09 20:20:39 [Server] INFO Key: Use Metrics, Value: true
24.09 20:20:39 [Server] INFO Key: Auto Clear Enabled, Value: false
24.09 20:20:39 [Server] INFO Key: DB Mysql Enabled, Value: true
24.09 20:20:39 [Server] INFO Key: Schematics Save Path, Value: plugins/PlotSquared/schematics
24.09 20:20:39 [Server] INFO Key: Delete Plots On Ban, Value: false
24.09 20:20:39 [Server] INFO Key: Mob Pathfinding, Value: true
24.09 20:20:39 [Server] INFO Key: API Location, Value: http://www.intellectualsites.com/minecraft.php
24.09 20:20:39 [Server] INFO PlotSquared is using online UUIDs
24.09 20:20:39 [Server] INFO Metrics enabled.
24.09 20:20:39 [Server] INFO Metrics enabled.
24.09 20:20:32 [Server] INFO jdbc:mysql://66.85.144.162:3306/mcph313862
24.09 20:20:32 [Server] INFO - Adding flag: description
24.09 20:20:32 [Server] INFO - Adding flag: weather
24.09 20:20:32 [Server] INFO - Adding flag: time
24.09 20:20:32 [Server] INFO - Adding flag: price
24.09 20:20:32 [Server] INFO - Adding flag: gamemode
24.09 20:20:32 [Server] INFO - Adding flag: ice-met
24.09 20:20:32 [Server] INFO - Adding flag: blocked-cmds
24.09 20:20:32 [Server] INFO - Adding flag: use
24.09 20:20:32 [Server] INFO - Adding flag: break
24.09 20:20:32 [Server] INFO - Adding flag: place
24.09 20:20:32 [Server] INFO - Adding flag: device-interact
24.09 20:20:32 [Server] INFO - Adding flag: vehicle-break
24.09 20:20:32 [Server] INFO - Adding flag: vehicle-place
24.09 20:20:32 [Server] INFO - Adding flag: vehicle-use
24.09 20:20:32 [Server] INFO - Adding flag: hanging-break
24.09 20:20:32 [Server] INFO - Adding flag: hanging-place
24.09 20:20:32 [Server] INFO - Adding flag: hanging-interact
24.09 20:20:32 [Server] INFO - Adding flag: misc-break
24.09 20:20:32 [Server] INFO - Adding flag: misc-place
24.09 20:20:32 [Server] INFO - Adding flag: misc-interact
24.09 20:20:32 [Server] INFO - Adding flag: player-interact
24.09 20:20:32 [Server] INFO - Adding flag: tamed-attack
24.09 20:20:32 [Server] INFO - Adding flag: tamed-interact
24.09 20:20:32 [Server] INFO - Adding flag: animal-attack
24.09 20:20:32 [Server] INFO - Adding flag: animal-interact
24.09 20:20:32 [Server] INFO - Adding flag: hostile-attack
24.09 20:20:32 [Server] INFO - Adding flag: hostile-interact
24.09 20:20:32 [Server] INFO - Adding flag: mob-place
24.09 20:20:32 [Server] INFO - Adding flag: explosion
24.09 20:20:32 [Server] INFO - Adding flag: fly
24.09 20:20:32 [Server] INFO - Adding flag: disable-physics
24.09 20:20:32 [Server] INFO - Adding flag: analysis
24.09 20:20:32 [Server] INFO - Adding flag: done
24.09 20:20:32 [Server] INFO - Adding flag: cluster
24.09 20:20:32 [Server] INFO - Adding flag: music
24.09 20:20:32 [Server] INFO - Adding flag: vehicle-cap
24.09 20:20:32 [Server] INFO - Adding flag: hostile-cap
24.09 20:20:32 [Server] INFO - Adding flag: animal-cap
24.09 20:20:32 [Server] INFO - Adding flag: mob-cap
24.09 20:20:32 [Server] INFO - Adding flag: entity-cap
24.09 20:20:32 [Server] INFO - Adding flag: keep
24.09 20:20:32 [Server] INFO - Adding flag: redstone
24.09 20:20:32 [Server] INFO - Adding flag: no-worldedit
24.09 20:20:32 [Server] INFO - Adding flag: pvp
24.09 20:20:32 [Server] INFO - Adding flag: pve
24.09 20:20:32 [Server] INFO - Adding flag: titles
24.09 20:20:32 [Server] INFO - Adding flag: forcefield
24.09 20:20:32 [Server] INFO - Adding flag: drop-protection
24.09 20:20:32 [Server] INFO - Adding flag: instabreak
24.09 20:20:32 [Server] INFO - Adding flag: invincible
24.09 20:20:32 [Server] INFO - Adding flag: item-drop
24.09 20:20:32 [Server] INFO - Adding flag: notify-leave
24.09 20:20:32 [Server] INFO - Adding flag: notify-enter
24.09 20:20:32 [Server] INFO - Adding flag: heal
24.09 20:20:32 [Server] INFO - Adding flag: feed
24.09 20:20:32 [Server] INFO - Adding flag: farewell
24.09 20:20:32 [Server] INFO - Adding flag: greeting
24.09 20:20:32 [Server] INFO $3[$1P2$3] $2&6Debug Mode Enabled (Default). Edit the config to turn this off.
24.09 20:20:32 [Server] INFO $1PlotSquared is now enabled
24.09 20:20:32 [Server] INFO $3[$1P2$3] $2&cIt's really recommended to run Java 1.8, as it increases performance
24.09 20:20:32 [Server] INFO Enabling PlotSquared v3.1.10
24.09 20:20:32 [Server] INFO Enabled Version 1.5.3-b37
24.09 20:20:32 [Server] INFO [Chat] GroupManager found: Waiting
24.09 20:20:32 [Server] INFO [Permission] SuperPermissions loaded as backup permission system.
24.09 20:20:32 [Server] INFO [Permission] GroupManager found: Waiting
24.09 20:20:32 [Server] INFO [Economy] Essentials Economy found: Waiting
24.09 20:20:32 [Server] INFO Enabling Vault v1.5.3-b37
24.09 20:20:32 [Server] INFO Loading TitleManager v1.5.11
24.09 20:20:32 [Server] INFO Loading DeluxeChat v1.4.9.1
24.09 20:20:32 [Server] INFO Loading EZRanksLite v1.6.2.5
24.09 20:20:32 [Server] INFO Loading AutoSell v1.4.3
24.09 20:20:32 [Server] INFO Loading PrisonMines v1.4.4
24.09 20:20:32 [Server] INFO Loading Multiverse-Core v2.5-b691
24.09 20:20:32 [Server] INFO Loading PlotSquared v3.1.10
24.09 20:20:32 [Server] INFO Loading Essentials vTeamCity
24.09 20:20:32 [Server] INFO Loading WorldGuard v6.0.0-beta-03.1514-
24.09 20:20:32 [Server] INFO Loading NametagEdit v3.0.3
24.09 20:20:32 [Server] INFO Loading SkQuery v3.21.4
24.09 20:20:32 [Server] INFO Loading ClearLag v2.8.2
24.09 20:20:32 [Server] INFO Loading Vault v1.5.3-b37
24.09 20:20:32 [Server] INFO Loading BowTrails v1.2
24.09 20:20:32 [Server] INFO Loading ServerListPlus v3.3.2
24.09 20:20:32 [Server] INFO Loading Skript v2.1.2
24.09 20:20:32 [Server] INFO Loading WorldEdit v6.0;3342-78f975b9
24.09 20:20:32 [Server] INFO Detected Minecraft version: 1.8
24.09 20:20:32 [Server] INFO Logging system initialized.
24.09 20:20:32 [Server] INFO onLoad: Early set up of static API, configuration, logging.
24.09 20:20:32 [Server] INFO Loading NoCheatPlus v3.12.0-BETA2-sASO-b813
24.09 20:20:32 [Server] INFO Loading GroupManager v2.1.31 (Phoenix)
24.09 20:20:31 [Server] INFO Set PluginClassLoader as parallel capable
24.09 20:20:31 [Server] INFO Starting Minecraft server on 119.81.145.69:56007
24.09 20:20:30 [Server] INFO Generating keypair
24.09 20:20:30 [Server] INFO Using 4 threads for Netty based IO
24.09 20:20:30 [Server] INFO Server Ping Player Sample Count: 12
24.09 20:20:30 [Server] INFO Debug logging is disabled
24.09 20:20:30 [Server] INFO This server is running CraftBukkit version git-Spigot-c3c767f-33d5de3 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
24.09 20:20:30 [Server] INFO Default game type: SURVIVAL
24.09 20:20:30 [Server] INFO Loading properties
24.09 20:20:30 [Server] INFO Starting minecraft server version 1.8
24.09 20:20:23 [Server] INFO Loading libraries, please wait...
24.09 20:20:23 [Multicraft] Loaded config for "Spigot 1.8 (Bukkit Alternative)"
24.09 20:20:23 [Multicraft] Starting server!

**Comment by Haoiscoll** [comment]
Guess heres the problem 24.09 20:20:45 [Server] INFO plugins/PlotSquared/schematics/GEN_ROAD_SCHEMATIC/SlashPlot/plot.schematic doesn't exist
 24.09 20:20:45 [Server] INFO - manager: com.intellectualcrafters.plot.generator.HybridPlotManager
 24.09 20:20:45 [Server] INFO - plotworld: com.intellectualcrafters.plot.generator.HybridPlotWorld
 24.09 20:20:45 [Server] INFO - generator: com.plotsquared.bukkit.generator.BukkitGeneratorWrapper
And when I run the /plot regenallroads on console no messages pop up...any way to fix this?

**Comment by Haoiscoll** [comment]
Anyone could help me on this?

**Comment by MattBDev** [comment]
Since this has not received attention or a response, I will be closing this issue. If you are encountering the problem still then feel free to comment here to reopen or create a new issue.
