### ISSUE TITLE
Armor stands

### ISSUE THREAD

**Issue by zDrakon** [IntellectualSites/PlotSquared#627]
Players can place Armor stands in plots where they don't have permission to build. To fix this for our spawn plot we simply worldguarded it... however... that doesn't seem to fix all the other plots. Not sure if this was intended but is there a flag to disable this bug?

**Comment by boy0001** [comment]
Have you given them the perm: `plots.admin.interact.other`?

**Comment by zDrakon** [comment]
I do not believe so. I'll see if I can remove that perm and test if it works.

**Comment by boy0001** [comment]
Is this still a problem?

**Comment by zDrakon** [comment]
No.
