### ISSUE TITLE
Two Bugs Have Issues? 

### ISSUE THREAD

**Issue by Kazina** [IntellectualSites/PlotSquared#628]
I have Two Problems

1) Road Schematic Doesn't Generate - just what it said cant make owen plots .

2) When player claims land and then unclaim it does not re-put in the boarders and to information about the person is still on the plots . people cant tell if its unclaim or not. you can claim it but will not take off sign and boarders back to normal.

My mine craft is the highest that you can get . 1.8.10 i think it called

**Comment by boy0001** [comment]
Duplicate issue:
P.S After I ran the command /plot regenallroads, nothing came up on the console either. So yeah.
P.P.S If you need more info about the server don't hesitate to ask, I'll be here to respond.
