### ISSUE TITLE
Importing template will lose data value of blocks

### ISSUE THREAD

**Issue by CatMe0w** [IntellectualSites/PlotSquared#629]
I downloaded a template called "bridge" in official spigot page, but when I imported it in game, all grass(ID:31:1) became shrub(ID:31:0). Then I tried other templates, all of them have this problem.

This problem maybe PlotSquared's bug, please fixi it, thanks.

My server version: KCauldron 1.7.10-1481.143
PlotSquared version: 3.1.10

Excuse me, my English is not very good.

**Comment by danielmulvad** [comment]
https://www.spigotmc.org/resources/plotsquared.1177/


Support
Support for Bukkit 1.5 - 1.8 and Sponge (Forge)
No support for cauldron.
Even though cauldron is a combination of Spigot & Forge, there are still many changes that may not be compatible with plotsquared.

**Comment by boy0001** [comment]
Testing this now.
