### ISSUE TITLE
Maven repository not working

### ISSUE THREAD

**Issue by evan3334** [IntellectualSites/PlotSquared#630]
I'm trying to write a plugin that depends on PlotSquared to determine if the player has permission to build on a plot.
However, the Maven repository doesn't seem to be working properly for me.
I have my repository set up like so in pom.xml, just like the README.md file says:
![](http://evan.pw/i/9VolfLJq.png)
And dependency:
![](http://evan.pw/i/foiEWqQN.png)

However, the 2.12.9 shows an error in the dependency. The error is as follows:
![](http://evan.pw/i/PpefQbA6.png)
I have tried reloading and reimporting the maven dependencies several times. Is there something I'm doing wrong or did I spell something incorrectly?

My entire pom.xml:
![](http://evan.pw/i/dKDjMsAq.png)

Any help would be appreciated.

**Comment by Maescool** [comment]
Change version to 3.1.10
that should work

**Comment by evan3334** [comment]
Alright, I will try this when I get home

**Comment by evan3334** [comment]
This did not fix the problem, I am still getting the same error
![](http://evan.pw/i/2ouU4EP9.png)
![](http://evan.pw/i/kXtAKHyy.png)

**Comment by boy0001** [comment]
Temporary solution:
http://ci.ac3-servers.eu/plugin/repository/everything/
