### ISSUE TITLE
plot changed claimed to unclaimed,wall not change?

### ISSUE THREAD

**Issue by Antecer** [IntellectualSites/PlotSquared#631]
PlotWorld:
    plot:
      height: 64
      biome: FOREST
      size: 42
      filling:
      - '1:0'
      auto_merge: false
      bedrock: true
      create_signs: true
      floor:
      - '2:0'
    wall:
      filling: '1:0'
      block_claimed: '44:1'
      height: 64
      block: '44:0'
    event:
      pve: false
      pvp: false
      spawn:
        egg: false
        breeding: false
        custom: true
    road:
      block: '155:0'
      height: 64
      width: 7
    home:
      default: side
      allow-nonmembers: false
    schematic:
      specify_on_claim: false
      on_claim: false
      file: 'null'
    economy:
      prices:
        merge: 100.0
        sell: 75.0
        claim: 100.0
      use: false
    chat:
      enabled: false
    limits:
      max-members: 128
    world:
      max_height: 256
      gamemode: creative
      border: false
      min_height: 1
    natural_mob_spawning: false
    flags: {}

when i set /plot claim the wall will changed with 44:1;
but set /plot unclaim, the wall not changed with 44:0, it always show 44:1

**Comment by boy0001** [comment]
Not a bug, use `/plot delete` instead.
