### ISSUE TITLE
Plot World

### ISSUE THREAD

**Issue by capchon** [IntellectualSites/PlotSquared#632]
So this world I created with plotsquared worked at the beginning, I hadn't made a plot but today when I went to it said You aren't in a plot world and other people who had made a plot get this as well PLEASE HELP!

**Comment by boy0001** [comment]
Could you please provide your startup log?
using `/plot debugpaste` should give you a link that you can provide me instead.

**Comment by capchon** [comment]
http://hastebin.com/welujaruzo

**Comment by capchon** [comment]
Found this on a reload:
[ERROR] World 'Create' in settings.yml is not using PlotSquared generator! Please set the generator correctly or delete the world from the 'settings.yml'!

**Comment by boy0001** [comment]
Try setting the generator in the bukkit.yml
https://github.com/IntellectualSites/PlotSquared/wiki/Manual-generator-setting

**Comment by RocoWayne** [comment]
i have the same problem, i dont understand how set the generator in the bukkit.yml, can you help me?
