### ISSUE TITLE
Wireless Redstone and PlotSquared

### ISSUE THREAD

**Issue by DoraKlikOpDora** [IntellectualSites/PlotSquared#635]
Hi,
With the plugin PlotMe it was possible to use Wireless Redstone on plots, but since I downloaded PlotSquared, it won't work anymore.

Is there a possibility to fix this?

Thanks,

**Comment by Legoman99573** [comment]
I loved that feature, add this plz.

**Comment by MattBDev** [comment]
PlotMe never had wireless redstone.

**Comment by EvilOlaf** [comment]
AFAIK wireless redstone is a 3rd party plugin. It seems like that worked with plotme out of the box, but not with P^2.

**Comment by MattBDev** [comment]
I've heard of wireless redstone and plotme but that was always related to old bukkit bugs. I don't think this is worth keeping open. The complexity of it would be too much and unfit for this plugin.
