### ISSUE TITLE
plotme database conversion error

### ISSUE THREAD

**Issue by woolwind** [IntellectualSites/PlotSquared#638]
I've successfully gotten a conversion on my test server in the past, but when I tried to migrate production last night I got this error.

I recreated it on my test server with a fresh copy of the world and mysql database

[16:17:46] [Craft Scheduler Thread - 16/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'plotme.PlotMePlots' doesn't exist
[16:17:46] [Craft Scheduler Thread - 16/WARN]: 	at com.plotsquared.bukkit.database.plotme.ClassicPlotMeConnector.getPlotMePlots(ClassicPlotMeConnector.java:62)

I then naturally end up with no plots.   I looked in my database and found the actual table is named plotMePlots  (note capitalization) - there are also old tables with lowercase names that are just cruft from a previous world. 

| Tables_in_plotme |
+------------------+
| PlotMePlots      |     <- this is a copy I made to see if could get conversion to work
| plotmeAllowed    |
| plotmeComments   |
| plotmeDenied     |
| plotmeMetadata   |
| plotmePlots      |       <-- this is the actual plot table
| plotmeallowed    |
| plotmecomments   |
| plotmedenied     |
| plotmeplots      |
+------------------+
10 rows in set (0.00 sec)

I took a flyer and copied plotmePlots to PlotMePlots and reran the conversion. That seemed to go well,  and I had a suitable number of plots in my plotsquared database that looked normal, but when I entered the world, the locations seemed to be off.    /ps home took me to my next door neighbor's plot. I sampled several plots with 'plot info' or looking at the holo and they were all one plot over from where I know they should be from recognizing the builds.

**Comment by MattBDev** [comment]
What version of PlotMe were you using?

**Comment by woolwind** [comment]
[PlotMe] Loading PlotMe v0.16.3

**Comment by woolwind** [comment]
Aha.  I have two worlds - 'plotme' has plot size 75 and 'pw2' has size 150. The generated plotsquared settings.yml shows plotme world plots are 150 across. and pw2 are size 0.   Might have gotten thrown off by extra multiverse worlds that aren't plot worlds or some such, but I definitely didn't have that issue on previous test conversions.
