### ISSUE TITLE
Players can place armor stands everywhere

### ISSUE THREAD

**Issue by MatteCarra** [IntellectualSites/PlotSquared#645]
Players can place armor stands EVERYWHERE (only in PlotSquared worlds)
![senza nome](https://cloud.githubusercontent.com/assets/11074527/10141203/69154bec-660b-11e5-9375-375e6a67aa65.png)

**Comment by Legoman99573** [comment]
I dont see proof on roads or other plots, send more snapshots like a rollback plugin saying this user placed the armor stand there, and the plot owner. That will be more helpful

**Comment by boy0001** [comment]
Two likely reasons:
 - users have `plots.admin.interact.other`, `plots.admin.interact.unowned`, `plots.admin.interact.road`
 - using an old version of P^2

**Comment by MatteCarra** [comment]
How can I male players using pressure plate and button and do not able to place armor standard?

**Comment by boy0001** [comment]
Set the `use` flag:
https://github.com/IntellectualSites/PlotSquared/wiki/Usage:-Plot-flags#default-flags
And use: `70,72,147,148,77,143` for pressure plates and buttons.
