### ISSUE TITLE
explosion of universe

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#646]
tried to update to 3.2.4 and console went spammy crazy http://pastebin.com/pFPKwwHJ

**Comment by Legoman99573** [comment]
Delete the old plotsquared.jar file and go to spigot and install the new one manually

**Comment by PhanaticD** [comment]
Thats what I did....

**Comment by boy0001** [comment]
*will be home ~3-4 hours, I will fix it then.
