### ISSUE TITLE
Permissions problem

### ISSUE THREAD

**Issue by williambl** [IntellectualSites/PlotSquared#649]
There seems to be a problem with plotSquared and permissionsEx. Unless you have the '*' permission, PlotSquared says 'you do not have plots.use' even if you do. Note that it is Plotsquared saying this, not permissionsEx.

**Comment by boy0001** [comment]
Can you do the following?:
`/pex user <user> check <permission>`
(where `<permission>` is `plots.use`)
And also send a screenshot of PlotSquared saying you don't have plots.use.

**Comment by williambl** [comment]
I updated and it's fixed. Sorry for wasting your time.
