### ISSUE TITLE
world edit is not restricted to plots

### ISSUE THREAD

**Issue by andyisyoda** [IntellectualSites/PlotSquared#654]
players can world edit across roads and others plots

**Comment by Legoman99573** [comment]
I saw another server with the same issue, and even not giving them the permission node.

**Comment by boy0001** [comment]
@andyisyoda 
Could you provide your startup log? `/plot debugpaste`

@Legoman99573 
That's not even possible.

**Comment by andyisyoda** [comment]
solved - I updated my world edit jar

**Comment by Legoman99573** [comment]
@boy0001 The other server updated w/e and everything works now. Maybe make the description on spigot what version of worldedit is comparable with.

**Comment by boy0001** [comment]
@Legoman99573 
There should be a message during startup if the WorldEdit version is out of date.

**Comment by Legoman99573** [comment]
That would be easier to know.
