### ISSUE TITLE
Admin bypass does not work anymore

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualSites/PlotSquared#666]
I recently updated P^2 to the latest version and now users with the node `plots.*` can not build on the street or unclaimed/other plots anymore.
Does not work even with `*` as permission node. 
Being OP works though.

3.2.9

**Comment by sojiro7** [comment]
Latest P^2 version is bugged. It has other issues, not just that. I recommend you downgrade until the author fixes it. At least that's the route we took.

**Comment by EvilOlaf** [comment]
That's what I did ^^

**Comment by boy0001** [comment]
Did it say they were lacking a permission node in chat?

**Comment by EvilOlaf** [comment]
Actually there was no message at all for various commands.

**Comment by boy0001** [comment]
Duplicate #664
