### ISSUE TITLE
Console spam/plot home/plots keep un claiming 

### ISSUE THREAD

**Issue by IcecoldRunner** [IntellectualSites/PlotSquared#670]
The server was running on 80% with only 2 players. 
/plot home 
/plot auto 
Are not even working most times. 
Massive console spam just from the plugin even with debug off

http://pastebin.com/EsLGQFqw

**Comment by IcecoldRunner** [comment]
http://pastebin.com/ujj6TtTi

**Comment by boy0001** [comment]
Would you have the full stacktrace? Those are all cut short.

**Comment by IcecoldRunner** [comment]
http://pastebin.com/qMg3DcvS

**Comment by boy0001** [comment]
Oh, the plot size is 0. Check your settings.yml

**Comment by IcecoldRunner** [comment]
They keep remaking the worlds

**Comment by boy0001** [comment]
Please explain? If you want to provide a copy of your `settings.yml` that could help.

**Comment by MattBDev** [comment]
No response and links are now invalid. It is assumed that help is no longer needed. If help is still needed please comment or create a new ticket.
