### ISSUE TITLE
Size parameter broken

### ISSUE THREAD

**Issue by samr28** [IntellectualSites/PlotSquared#672]
Looks really good but the plot width/size parameter does NOT work. I have tried many times with the setup tool and with the normal world generation with multiverse. PLEASE FIX!

**Comment by EvilOlaf** [comment]
How do you noticed that it does not work? What did you see and what did you expect?
What version of P^2 do you use?
The output of  `plot debugpaste` might be helpful too.

**Comment by boy0001** [comment]
Issue is caused by the values already being present in the configuration.

Potential fixes:
 - Delete the world `/mv delete <world>`, set the value in the `settings.yml`, then `/plot reload`, then re-create: `/mv create <world> normal -g PlotSquared:s=<value>`
 - Wait for the fix.

**Comment by samr28** [comment]
I was able to fix it by downloading an older version, generating the world then updating the plugin.
