### ISSUE TITLE
WorldGuard flag Blocked-Cmds

### ISSUE THREAD

**Issue by AshourAziz** [IntellectualSites/PlotSquared#673]
Hello, if you plotme aliases enabled, it seems for some reason worldguard is NOT registering that someone is doing /plotme home and that it should be disabled, but yet for /p2 or /plot or /plots it is indeed disabling it. What could be causing this?

**Comment by AshourAziz** [comment]
So when I am disabling let's say "/plotme home" worldguard is saying "this command is not available in this area" but yet plotsquared is for some reason still performing the commands, but yet if I disable p2, 2, plotsquared, plot, plots it completely stops it. I'm assuming it's something because it's an alias? is there a way to fix this?

**Comment by boy0001** [comment]
I have some questions. It sounds like you might be disabling the command to solve a bigger problem. If you want to explain what you are doing, I have some ideas for a better solution.

 - You can have bukkit manage the aliases by using the `commands.yml` and disabling the plotme-alias in the `settings.yml`: http://wiki.bukkit.org/Commands.yml
 - There is a PlotSquared flag: https://github.com/IntellectualSites/PlotSquared/wiki/Flag:-blocked-cmds

A fix for this should be available shortly.
