### ISSUE TITLE
Plot Music won't work w/ ChestCommand Plugin

### ISSUE THREAD

**Issue by PinoyLifeCraft** [IntellectualSites/PlotSquared#674]
Plugins:
             ChestCommand
             PlotSquared
ChestCommand Files:
             https://www.dropbox.com/sh/f2wk6sxgukwf9k7/AADI4yOUkzUBvs6a8N3nJOX-a?dl=0
Description:
      I can't play Music in my Plot with the plugin ChestCommand but the GUI will popup but when clicking i can only move or change it Nothing happen !! :disappointed: 
                  cxx{}::::::::::::::::::::> I hope you can fix it owner :smile:

**Comment by Legoman99573** [comment]
Talk to the creator of that plugin to add support to plotsquared.

**Comment by MattBDev** [comment]
I agree that the owner of that plugin should fix this. I don't think we need to fix it on our end.
