### ISSUE TITLE
[Suggestion] Add plot protection.

### ISSUE THREAD

**Issue by Legoman99573** [IntellectualSites/PlotSquared#675]
Plot protection is where a plot is protected from expiring. PlotMe had this, and is wondering if you can add /plots protect command, and the /plots tempprotect <timediff> commands. Make sure you test it before releasing to avoid bugs.

the temp protect timediff parts would be like
1s, 1m, 1h, 1d, 1w, 1mo, 1y

**Comment by MattBDev** [comment]
I just found out that there was a flag unimplemented in the code that would allow plots from expiring. The flag is named "keep"

**Comment by MattBDev** [comment]
Completed with the keep flag.

**Comment by boy0001** [comment]
The `keep` flag is just a boolean value. The feature request asks for a timediff to be accepted as well.

**Comment by MattBDev** [comment]
@boy0001 I misunderstood the request then.

**Comment by boy0001** [comment]
Was added a while ago
