### ISSUE TITLE
Support for other plugins to use output

### ISSUE THREAD

**Issue by rlf** [IntellectualSites/PlotSquared#676]
Hi.

I'm developer of a simple, yet very versatile plugin called Holographic-Scoreboard.

It simply takes output (like `/plot list top`) and converts it into a hologram.

Extremely versatile for a lot of servers.

Unfortunately, it cannot capture the output of PlotSquared, becase the only way currently for capturing communication between a plugin, and a player/console, is to proxy the CommandSender object in Bukkit.

For HGS to be able to capture the output from PlotSquared, the `sendMessage` in `ConsolePlayer` needs to call `sendMessage`  on the provided CommandSender for invoking the command. And not direct the output directly to the plugin log.

Could you please adjust the plugin, so it communicates with the command-sender object supplied? or alternatively, help me to capture the output by other means?

**Comment by boy0001** [comment]
ConsolePlayer needs to be changed to a wrapper instead of a single instance then.
