### ISSUE TITLE
/p clear messes up plot

### ISSUE THREAD

**Issue by lilacorn** [IntellectualSites/PlotSquared#678]
Version 3.2.12
I did a /p clear and this has happened
![2015-10-18_12 37 04](https://github-cloud.s3.amazonaws.com/assets/6467895/10565803/e0c2b5f4-7596-11e5-802d-3c6da1236651.png)

**Comment by lilacorn** [comment]
It also messes up when someone does /p claim

**Comment by boy0001** [comment]
Can you provide a startup log as well as the settings.yml? `/plot debugpaste`

**Comment by lilacorn** [comment]
debug
http://hastebin.com/egiyuyutic
log
http://pastebin.com/rARS9EZe

**Comment by lilacorn** [comment]
and here is the settings http://pastebin.com/pdeTerDP

**Comment by boy0001** [comment]
Okay, so it looks like there is an offset to the plot compared to what was already there.

Did you previously use another generator such as AdvPlots or PlotZ?

Anywho, what you can do I suppose is play with the offset in the settings.yml for that world.
``` yml
worlds:
  <world>:
    road:
      offset:
        x: 0
        y: 0
```

Then you can use `/plot reload` and `/plot set border <block>` to see if the offset is correct.

**Comment by lilacorn** [comment]
i use multiverse and never used anything else and never touched the settings

**Comment by lilacorn** [comment]
fixed with 
    road:
      block: '155:0'
      height: 64
      width: 13
      offset:
        x: 5
        y: 5
        z: -5

**Comment by lilacorn** [comment]
the y doesnt do anything so the Z and X are important

**Comment by lilacorn** [comment]
sadly it doesnt take same affects for each plot.... it fixes it for one plot but not for the others

**Comment by boy0001** [comment]
Okay, it might be the road width then. Can you make sure the road width in the settings.yml is correct?

**Comment by lilacorn** [comment]
tried it its still off for other plots as well. I don;t get it, it was fine before the updates though.

**Comment by boy0001** [comment]
When you are free, want to come on [IRC](http://webchat.esper.net/?nick=&channels=IntellectualCrafters&fg_color=000&fg_sec_color=000&bg_color=FFF) and we can troubleshoot?

**Comment by MattBDev** [comment]
@boy0001 Still an active issue?

**Comment by boy0001** [comment]
Don't think so
