### ISSUE TITLE
Unable to load Schematics of plots

### ISSUE THREAD

**Issue by Porkchopseesu** [IntellectualSites/PlotSquared#683]
Hello,
On our server we are running with Centos6 along with BungeeCord and Spigot 1.8.8. We have a directory /plotschematics/ that the schematics are saving to corectly. However, when we try to load the schematic in game to a plot it gives us this error: That is not a valid schematic.Reason:non-exsistent or not in gzip format.
The directory has read/write access and I have also tried to gzip the schematic file and even rename the schematic to a different name. The error still shows. Just a note(There appears to be no error in the log and the files are saving correctly to that directory) Does it load from a different directory? Any suggestions?

Example schematic: ( -15;-16,plotworld,username.schematic)

**Comment by boy0001** [comment]
`/2 sch paste -15;-16,plotworld,username`?

Or try version 3.2.15
