### ISSUE TITLE
Plot Entity Support

### ISSUE THREAD

**Issue by manuelgu** [IntellectualSites/PlotSquared#686]
The other day I have been thinking about adding an entity support for plots. My idea wasn't that complicated.

###### Let me try to explain that a little further

* Category
  * There are different categories like `interior`, `animals`, `zombies` where you can set a custom maximum amount of them per plot. If a player reaches the limit of that category he won't be able to spawn any more in that category

* Single-Entity
  * There is a maximum amount of entities per plot, no matter what type they are. Once the limit is reached you won't be able to spawn new ones on the plot.

Any opinions on that?

**Comment by boy0001** [comment]
Already added:
https://github.com/IntellectualSites/PlotSquared/wiki/Usage:-Plot-flags#caps
