### ISSUE TITLE
/p unclaim isn't clearing plots -or- showing plots as unclaimed..

### ISSUE THREAD

**Issue by robertshady** [IntellectualSites/PlotSquared#688]
Not sure if either one of these is a bug, but IMHO they are.

When someone /p claim's a plot, it changes the border to a new block to show the plot has been claimed, and then you are allowed to build on it.

If someone digs around the plot and then does a /p unclaim, it does unclaim it - however it still looks as though it is claimed - the border block is still the 'claimed' block,  and the blocks that were dug up are still missing.

I'd look into fixing this myself and submitting a patch, but I can't even get the latest PlotSquared to compile.

**Comment by boy0001** [comment]
use `/plot delete`
