### ISSUE TITLE
Sand & TNT Cannons

### ISSUE THREAD

**Issue by BlockWorld** [IntellectualSites/PlotSquared#689]
Add the ability to use them, so you can have the graph full of checkmarks on <a href="http://plotsquared.com">the PlotSquared website</a> once and for all!

**Comment by boy0001** [comment]
That refers to sand/tnt cannon protection. i.e. sand/tnt can't be sent into the road or other plots.

**Comment by BlockWorld** [comment]
Oh. That makes sense.
