### ISSUE TITLE
Issues with custom road schematic

### ISSUE THREAD

**Issue by crysis992** [IntellectualSites/PlotSquared#690]
Running the latest version of PlotSquared.

I'm running a world with custom road schematics. Was working well on generation a few weeks ago. But now I'm unable to merge/clear or do anything which would regenerate the roads.

If i load the both schematics manually with WorldEdit, its working. These are the expected schematics which were created by /plot createroadschematic

Expected: 
![expected](https://cloud.githubusercontent.com/assets/5308174/10715303/0a6c89c2-7b12-11e5-8c49-b238331a1539.jpg)

Outcome on unlink/clear or whenever the road is regenerated. 
(This does NOT happen when new parts of the world are generated. On world generation the road is sucessfully pasted)
![outcome](https://cloud.githubusercontent.com/assets/5308174/10715309/37cb4a66-7b12-11e5-920e-3875639354a1.jpg)

**Comment by boy0001** [comment]
Isolated issue, redownload PlotSquared.
