### ISSUE TITLE
Fly in the Land

### ISSUE THREAD

**Issue by generalgert** [IntellectualSites/PlotSquared#692]
Hello there. I want to fly the players in the plot but did not set you help please . I am writing google translate

**Comment by boy0001** [comment]
I don't fully understand, but there's a fly flag you can set:
/Plot flag set fly true

**Comment by generalgert** [comment]
Thank you. But the players just want to get tips on their land . Without writing code. So players can fly with perm without writing code bearing automatic entrance into the land . Everyone should own at Land End .

**Comment by boy0001** [comment]
I don't understand the request...

Possibly relevant, you can set the fly flag globally:
https://github.com/IntellectualSites/PlotSquared/wiki/Usage:-Plot-flags#default-flags

Replace the `use` part in the example with `fly: true`

**Comment by boy0001** [comment]
Closing this issue. Please respond if you require further assistance.
