### ISSUE TITLE
Permission-based Info Command

### ISSUE THREAD

**Issue by manuelgu** [IntellectualSites/PlotSquared#693]
Hello,

while playing around with the plugin and setting up a server I figured that it might be quite cool to make the `/p info` command permission based.

# What does that mean?

Depending on the permissions a player has (or maybe even something to be set in the settings.yml)  certain things aren't displayed when doing `/p info`.

Example:
I don't want to use the rate system for my entire world so I just disable it in a settings yml. Whenever somebody enters `/p i` the [Rating Stats](https://github.com/IntellectualSites/PlotSquared/blob/master/src/main/java/com/intellectualcrafters/plot/commands/Info.java#L168-L169) won't show up.

I am sorry if something like that already exists.

**Comment by boy0001** [comment]
It's not currently permission based, but the info message is in the translations file, so you can modify the message for everyone.

https://github.com/IntellectualSites/PlotSquared/wiki/translations
`plot_info` - You can remove the ratings part. Ratings could still be viewed with `/plot info rating`

Other placeholders:
`%num%` The number of plots making up the mega plot

**Comment by manuelgu** [comment]
That absolutly does it! Thanks
