### ISSUE TITLE
Importing Stock Templates

### ISSUE THREAD

**Issue by c0mput3** [IntellectualSites/PlotSquared#694]
Hi Guys

When using the command /plot template import <worldname> <template> 
I receive the following error in game "[P2] Invalid template file town.template" and the following error in console http://pastebin.com/xZ1Z45jj

I'm using the stock template town that is bundled with your Plugin.

Please advise

**Comment by c0mput3** [comment]
errm......so....there's an updated coming? as the latest version published on Spigotmc, dated 18/10/15, has this bug.  Maybe a little explanation wouldn't go a miss.

**Comment by EvilOlaf** [comment]
There will probably soon be a new version. Stay tuned.

**Comment by c0mput3** [comment]
So the ticket shouldn't be closed until the release of the new version and we can see if it has been fixed.

**Comment by EvilOlaf** [comment]
If this still occurs after updating either reply on this ticket as it is still writable or create a new one. This is how git works ;)

**Comment by boy0001** [comment]
The commit also included the latest file:
https://github.com/IntellectualSites/PlotSquared/blob/master/target/PlotSquared-Bukkit.jar?raw=true
