### ISSUE TITLE
Major problems with merging and some other bugs

### ISSUE THREAD

**Issue by Pigums** [IntellectualSites/PlotSquared#695]
So I claimed a bunch of plots and pasted some terrain onto it. After, I did /plot merge and it broke my terrain into pieces. Anyway that I could bring it back to it's original state? 

Also, this keeps on happening: http://i.pigums.me/gI6b8r5.png

**Comment by boy0001** [comment]
Update P^2 to fix the last issue. You may need to do a world trim to delete those bad chunks. 

Could you show me what you mean by the terrain being broken into pieces?
