### ISSUE TITLE
Is this normal

### ISSUE THREAD

**Issue by Legoman99573** [IntellectualSites/PlotSquared#696]
I had this issue and was wondering if someone else had this issue
![2015-10-27_14 39 39](https://cloud.githubusercontent.com/assets/7460704/10771874/d62c3222-7cb8-11e5-87d7-40808a0c7435.png)

**Comment by boy0001** [comment]
Update PlotSquared. Possibly do a world trim to remove those bad chunks, or delete the world.

**Comment by Legoman99573** [comment]
An update broke the templates, reset world and updated. Fixed issue with templates.
