### ISSUE TITLE
Move Subcommand is broken

### ISSUE THREAD

**Issue by HeroCC** [IntellectualSites/PlotSquared#697]
The move subcommand currently appears to do nothing functionally, and displays {label} rather than the command you used. I am trying to relocate a plot from one place to another, but I am currently unable to do that. Thanks for the help!
Screenshot: https://gyazo.com/734a708477e072e2d194cedb51b95f22
Debug: http://hastebin.com/derabehilu

**Comment by boy0001** [comment]
It should read `/plot move <destination>` e.g. /plot move 5;3

Will test out shortly.
