### ISSUE TITLE
Update Notification Permission

### ISSUE THREAD

**Issue by manuelgu** [IntellectualSites/PlotSquared#698]
As of right now, everybody who has the [`PERMISSION_ADMIN`](https://github.com/IntellectualSites/PlotSquared/blob/215ed04754832121b132243a2c7c6b7a63d557ab/src/main/java/com/plotsquared/bukkit/listeners/PlayerEvents.java#L458) Permission will receive the message that an update for PlotSquared is available.

Would it be possible to add a `PERMISSION_UPDATENOTIFICATION` or something along these lines?

**Comment by BlockWorld** [comment]
+1

**Comment by boy0001** [comment]
Changed to `plots.admin.command.update` in the next version. `plots.admin` will however give you all plot related permissions.
