### ISSUE TITLE
Plotworlds don't generate properly

### ISSUE THREAD

**Issue by Properpeanut** [IntellectualSites/PlotSquared#699]
Hi.
I'm using Cauldron for 1.7.10 and I'm trying to use your plugin to make a Shop World. 

I've downloaded PlotSquared 3.2.16u2 along with some addons PlotRankup and HoloPlots. 
I'm using Multiverse 2.5 and I've tried creating a plotworld with both the /plot setup method and the /mv create method. But when I teleport to the world that is created, it's just a normal world with no visible plots created.
Then when I use the /plot auto command I can claim a plot and the borders become visible. But sometimes the plot is high up in the air and sometimes it's below ground.

Here's my multiverse\worlds.yml

plotworld:
==: MVWorld
hidden: 'false'
alias: ''
color: WHITE
style: NORMAL
pvp: 'true'
scale: '1.0'
respawnWorld: ''
allowWeather: 'true'
difficulty: EASY
spawning:
==: MVSpawnSettings
animals:
==: MVSpawnSubSettings
spawn: 'true'
spawnrate: '-1'
exceptions: []
monsters:
==: MVSpawnSubSettings
spawn: 'true'
spawnrate: '-1'
exceptions: []
entryfee:
==: MVEntryFee
amount: '0.0'
currency: '-1'
hunger: 'true'
autoHeal: 'true'
adjustSpawn: 'true'
portalForm: ALL
gameMode: SURVIVAL
keepSpawnInMemory: 'false'
spawnLocation:
==: MVSpawnLocation
x: 1106.0
y: 4.0
z: -103.0
pitch: 0.0
yaw: 0.0
autoLoad: 'true'
bedRespawn: 'true'
worldBlacklist: []
environment: NORMAL
seed: '2408785214189208137'
generator: PlotSquared
playerLimit: '-1'
allowFlight: 'true'

and here's my PlotSquared\config\settings.yml

plotworld:
plot:
height: 64
biome: FOREST
size: 42
filling:
- '1:0'
auto_merge: false
bedrock: true
create_signs: true
floor:
- '2:0'
wall:
filling: '1:0'
block_claimed: '44:1'
height: 64
block: '44:0'
event:
pve: false
pvp: false
spawn:
egg: false
breeding: false
custom: true
road:
block: '155:0'
height: 64
width: 7
home:
default: side
allow-nonmembers: false
schematic:
specify_on_claim: false
on_claim: false
file: 'null'
economy:
prices:
merge: 100.0
sell: 75.0
claim: 100.0
use: false
chat:
enabled: true
limits:
max-members: 128
world:
max_height: 256
gamemode: creative
min_height: 1
border: false
natural_mob_spawning: false
flags: {}
 
I really don't know what's wrong and hope someone can guide me in the right direction.
Thank you :)

**Comment by boy0001** [comment]
Cannot replicate.
