### ISSUE TITLE
Issues with custom road schematic

### ISSUE THREAD

**Issue by crysis992** [IntellectualSites/PlotSquared#701]
As described in another Issue #690 I'm running into problems with the road schematics.
The Issue #690 has been stated as fixed/closed. It's a way better now, except theres a layer bedrock generated above the east side (other directions are generating fine and as expected)

- Using the latest version (not dev build)
- Created a new road schematic after the update (/plot createroadschematic)
- Used /plot debugroadregen

Result:
![road](https://cloud.githubusercontent.com/assets/5308174/10908718/e789563c-8233-11e5-9e5e-a38ebea4dff8.png)

**Comment by boy0001** [comment]
Can you send the world template?    
`/plot template export <world>`    
The template will be in:
`plugins/PlotSquared/templates`

**Comment by crysis992** [comment]
Here it is:
http://crytec.net/downloads/creative.template
