### ISSUE TITLE
Plotsquared Flags effecting non-plotsquared worlds on client side

### ISSUE THREAD

**Issue by OsidianKingVIII** [IntellectualSites/PlotSquared#702]
We found a bug on the recent update when a player enters a plot with flag weather and flag time set. when a player teleports to a non plot squared world (survival) the client weather and time are being effected and are reset to sunny daytime. This results in the player experiencing hostile mobs spawning in the daytime. the client will be stuck in a time loop and the sun will not go down. as a temporary solution we are logging out of the server and back into the server.this problem only happens if a player enters a plot with one of these 2 flags: Weather and Time. otherwise the client is not effected if a player teleports to plot world and back to survival world.

**Comment by bolda500** [comment]
I confirm this bug. It also occurs on the same map. The only solution to fix the wrong time of day/night cycle in the client side is relog.

**Comment by logicalPolaris** [comment]
I'm running 3.2.24 and this problem still occurs.
