### ISSUE TITLE
Claiming

### ISSUE THREAD

**Issue by quack123456** [IntellectualSites/PlotSquared#710]
Is there anyway to claim a plot from a different world because I created the plot world with multiverse and for people to claim a plot they have to teleport to the world with /mv tp (name) Plots and then they can claim it. Is there anyway to switch that?

**Comment by lilacorn** [comment]
Set a warp to that world

On Monday, November 9, 2015, quack123456 <notifications@github.com> wrote:

> Is there anyway to claim a plot from a different world because I created
> the plot world with multiverse and for people to claim a plot they have to
> teleport to the world with /mv tp (name) Plots and then they can claim it.
> Is there anyway to switch that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IntellectualSites/PlotSquared/issues/710>.
>


-- 
Michelle
Web: http://lilacorn.net

**Comment by boy0001** [comment]
If you have more than one plotworld, no. Check your settings.yml and delete the other world if necessary.
