### ISSUE TITLE
"Could not find worlds folder" Error with regen all roads

### ISSUE THREAD

**Issue by Aberzhulan** [IntellectualSites/PlotSquared#713]
When trying to run plot regenallroads <world> from console, I'm getting this error: http://pastebin.com/RuMZABcL

And should you need it, here's the hastebin: http://hastebin.com/agirufomix

I'm using latest version of P2. The world folder for "cells2" exists and there's a listing in MV for the world as well.

**Comment by boy0001** [comment]
Possibilities:
 - It does not have read access to the directory
 - Logical error where it's not checking the correct directory.

The next update I'll have it print out the directory it is checking. If it's not a permission issue, what you can do is delete the world and it will have the correct schematic when you recreate it.

**Comment by Aberzhulan** [comment]
That's the strange part. Every time I've recreated the world, it ignores the road and intersection schematics and just uses the plot schematic. I'm starting to wonder if I set up something incorrectly, as this is the only time I've ever had this issue.

I may just copy/paste the road where it needs to be, and then leave it. I'm not expecting more than 30 or 40 players to use this world.

Thanks.
