### ISSUE TITLE
Road schematics that are lower

### ISSUE THREAD

**Issue by rlf** [IntellectualSites/PlotSquared#715]
Hi.

I wanted to change my road schematic.

The new one is 2 blocks lower than the previous one.
When I regenallroads, the top 2 blocks from the old schematic stays.

Any sensible workarounds? 
I haven't been able to find any config for the actual height of the schematic, only the base block-height.

**Comment by boy0001** [comment]
`/plot regenallroads [height]`
If it's 2 blocks lower, use 2 for the height.
