### ISSUE TITLE
Can't make any template

### ISSUE THREAD

**Issue by Zerkohh** [IntellectualSites/PlotSquared#716]
Hi,

Since few days, i'm trying to make custom plots so i made the custom plot, pasted it on few plots and then, i do /plot template export [world_name].

When I do /plot template import [world_name] [template_name], the template isn't load.

**Comment by boy0001** [comment]
Creating a template copies the world configuration into a new template file. Useful if you want to share a world with someone. Importing a template will then copy the configuration from the template file into your PlotSquared settings.yml.

Anywho, for road schematics:
https://github.com/IntellectualSites/PlotSquared/wiki/Installation#adding-road-schematics

**Comment by Zerkohh** [comment]
So there is no way to create custom plots ?

**Comment by boy0001** [comment]
> Anywho, for road schematics:
https://github.com/IntellectualSites/PlotSquared/wiki/Installation#adding-road-schematics
