### ISSUE TITLE
Redstone clocks

### ISSUE THREAD

**Issue by MrFrostmaul** [IntellectualSites/PlotSquared#718]
Hello, love this plugin and the redstone clock timers work perfect to disable them. But have come across a problem where if they user does a timer via two hoppers facing each other and comparators it does not cancel the redstone clock that is produced by them or by a redstone clock like:  http://prntscr.com/930wj3

Don't know if possible to add, but would be good :)

Thanks

**Comment by RoboMWM** [comment]
A better question is why do you allow hoppers?

**Comment by MattBDev** [comment]
We will not be adding anymore redstone control options in P2. We are a plot plugin and things like this are beyond the scope of the project.
