### ISSUE TITLE
Not able to add template to an existing plotworld

### ISSUE THREAD

**Issue by ericbarbwire** [IntellectualSites/PlotSquared#720]
"Add roads to your world...
Hybrid generator bundled with PlotSquared
Roads can be conveniently added to new or existing worlds
Supports larger plot sizes than pure schematic generation
(here's the template below /plot template import <world> bridge)"

Hello, I am trying to add roads to my existing plotworld. I have checked the Documentation and it doesn't say anything about existing worlds.
I added bridge.template to my templates folder. Then did /plot template import plotworld bridge.
Doing so prompts the message plotworld is already a registered plotworld.
Is there anyway to add road templates to existing worlds? Or am I just doing something wrong?

**Comment by boy0001** [comment]
https://github.com/IntellectualSites/PlotSquared/wiki/Installation#adding-road-schematics
