### ISSUE TITLE
World generation not working on sponge

### ISSUE THREAD

**Issue by i9hdkill** [IntellectualSites/PlotSquared#725]
Hi,

I am trying to set up a basic sponge server with plotsquared.

Unfortunaly it's not wokring like expected.

SpongeForge 688
Forge: 1.8 1563

fml server log:
http://pastebin.com/2rrb90Nu

settings:
http://pastebin.com/kPeWzEyG

When I join the server and type /plots auto the following error is being thrown:
http://pastebin.com/vuRbfv6E

Regarding this, there is another error about generation in the provided fml server log.

I don't know what I am doing wrong.

When I use /plot claim:
You are not in a plot

If you need more details, pls tell me

**Comment by boy0001** [comment]
Was fixed.
