### ISSUE TITLE
UUID Issues

### ISSUE THREAD

**Issue by johandrex** [IntellectualSites/PlotSquared#730]
Getting this console error spammed when trying to feth the players UUID - http://hastebin.com/ayiduduqem.avrasm

I'm also getting this error when a player that has gotten their UUID registered logs in again - http://hastebin.com/ayodedufuw.avrasm

**Comment by manuelgu** [comment]
Looks like `api.intellectualsites.com` or rather `intellectualsites.com` is down. That is what it's caused by.

**Comment by johandrex** [comment]
oh thanks, have it been down for a long time?

**Comment by manuelgu** [comment]
I don't know. @boy0001 or @Sauilitired probably know more about that

**Comment by Sauilitired** [comment]
IntellectualSites is down due to lack of funding and time. It was a private project of mine, which I'm unable to continue working on due to huge amount of school work (God bless the IB). 

I am sorry that I didn't get to remake the parts of PlotSquared it affects, but I've been quite inactive in this project as well.

**Comment by manuelgu** [comment]
Same for http://plotsquared.com I assume?
Would be sad to see such an aspiring project slowly going down because of lack of money/time.

**Comment by Sauilitired** [comment]
Indeed. I have no way to fund the project myself as of now, due to personal economical problems. Thing is, it doesn't require huge amounts - but even the smallest of fees can be high when you're broke :laughing:

**Comment by EvilOlaf** [comment]
I was hoping that my donation from a few month would have funded this a bit longer ^^

**Comment by Sauilitired** [comment]
@EvilOlaf, so did I :/

**Comment by johandrex** [comment]
How much does it cost for intellectualsites.com to get up?

**Comment by Sauilitired** [comment]
Well, I have a voucher for $50 for Digitalocean, that requires $25 be activated. With a lot of adjustments and really hardcore optimization I could possibly power the droplet for $10 a month. Which means that $25 could possibly power 7 months of runtime. Then there is the additional costs of domain names and such.

As of now? $50 could last us 7 months.
