### ISSUE TITLE
Plot Squared - Flag Use Issue

### ISSUE THREAD

**Issue by hellman501** [IntellectualSites/PlotSquared#734]
Hello,

I've been having this issue for a while now and I was wondering if you would be able to fix the issue.
The thread pretty much sums up the issue: http://www.vexalprison.net/forums/threads/128/
I want to allow players to right click signs and punch signs with out players having to have the admin interact permission.

**Comment by manuelgu** [comment]
In order to allowe non-added players to interact with certain blocks, you can add a `use` flag in the **settings.yml**

You would want to have something like [this](http://hastebin.com/hameyahipe.sm) at the bottom of your world configuration

**Comment by hellman501** [comment]
Thank you for your reply but sadly the issue is still occuring, here is a screenshot of the config: http://imgur.com/lPo0YAg

**Comment by manuelgu** [comment]
That is not how you use YAML. Please see [this](http://hastebin.com/hameyahipe.sm) link for a usage example. If you provide a "/p debugpaste" I could also edit your config so it allows using the signs.

**Comment by hellman501** [comment]
Ok so, I've fixed it and it works now but when a player trys to use the chest shop sign it doesn't work at all. I'm guessing the creators of the plugin did like the idea of prison servers using their plugin so why doesn't the most important plugin for plots not even work?

When the player goes to right click or punch the sign the sign doesn't do anything. When they right click the sign it just opens the chest which is not what I want. Players can open other players chests and edit their items frames, armor stands ect. I just want players to be able to buy/sell with their signs like normal prison servers. If this is to much of an issue I can reset plots and go use plotme.

**Comment by manuelgu** [comment]
Then this has nothing to do with PlotSquared but rather with a misconfiguration of the other plugin.

**Comment by hellman501** [comment]
Ok the chest shop signs work now but I had to give the players this permission: plots.admin.interact.other and they can access chests and armor stands ect
How do I block that

**Comment by manuelgu** [comment]
With giving them `plots.admin.interact.other ` they have interaction access with **ALL** plots. You shouldnt do that!

If you have set the correct flags in the settings.yml (for the signs), please do "/p debugpaste". You can check wheter it worked or not with executing `/p i flags` on any plot

**Comment by hellman501** [comment]
Ok I get this ingame when I do /p i flags
http://i.imgur.com/THCcAi2.png

Also settings_yml: http://hastebin.com/efiqukuped

**Comment by manuelgu** [comment]
You are using the wrong ID for the signs. You need to use `63` and `68`

**Comment by hellman501** [comment]
Ok, I've set it up in config but it still doesn't work when I type /p i flags it says none

This is config: http://hastebin.com/isalaragaz

**Comment by manuelgu** [comment]
Are you in world `vexalplots` and have you restarted the server?

**Comment by hellman501** [comment]
I reloaded the plugin and yes vexalplots

**Comment by manuelgu** [comment]
Try restarting.

**Comment by boy0001** [comment]
It's picky, don't have a space after the comma (there would have been an error during startup)
```YML
    flags:
      use: 63,68
```

Also, your current configuration only sets the default flag in the second world, so Vexalprison still has no default flags.
