### ISSUE TITLE
SQLException on shutdown

### ISSUE THREAD

**Issue by dextonanderson** [IntellectualSites/PlotSquared#736]
http://hastebin.com/ibevacokok.vbs

**Comment by boy0001** [comment]
(low priority)
The error is of a non critical function (i.e. validating the database transactions on shutdown), and doesn't lead to the failure of this.

I'll fix it if I replicate the stacktrace.

**Comment by dextonanderson** [comment]
Alright, thank you.

**Comment by MattBDev** [comment]
Is this still an issue?

**Comment by dextonanderson** [comment]
It isn't an issue anymore, thanks.
