### ISSUE TITLE
Prevent throwing things on other plots

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#737]
If you arent able to build in a plot, is it possible to block throwing of snowballs, xp bottles, splash potions as well?

**Comment by chamunks** [comment]
I wouldn't doubt it WorldGuard does it fine.

**Comment by dextonanderson** [comment]
It might be possible. There would have to be some thing to constantly check the entities in the world, like the road vehicle remover, for example.

**Comment by lilacorn** [comment]
Use clearlagg

On Monday, November 23, 2015, Dexton Anderson <notifications@github.com>
wrote:

> It might be possible. There would have to be some thing to constantly
> check the entities in the world, like the road vehicle remover, for
> example.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IntellectualSites/PlotSquared/issues/737#issuecomment-159171276>
> .
>


-- 
Michelle
Web: http://lilacorn.net

**Comment by PhanaticD** [comment]
the intention is to prevent players from going onto another players plot and spamming annoying things, i dont see how "use clearlagg" helps this

**Comment by lilacorn** [comment]
Look for flags list and there should be something about drop items page
three of /p 3

On Tuesday, November 24, 2015, Josh <notifications@github.com> wrote:

> the intention is to prevent players from going onto another players plot
> and spamming annoying things, i dont see how "use clearlagg" helps this
>
> Sent from my iPhone
>
> > On Nov 24, 2015, at 10:01 AM, lilacorn <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > Use clearlagg
> >
> > On Monday, November 23, 2015, Dexton Anderson <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> > > It might be possible. There would have to be some thing to constantly
> > > check the entities in the world, like the road vehicle remover, for
> > > example.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/IntellectualSites/PlotSquared/issues/737#issuecomment-159171276
> >
> > > .
> > >
> >
> >
> > --
> > Michelle
> > Web: http://lilacorn.net
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IntellectualSites/PlotSquared/issues/737#issuecomment-159307581>
> .
>


-- 
Michelle
Web: http://lilacorn.net

**Comment by RoboMWM** [comment]
@lilacorn he does not mention dropped items.

Not sure why you have XP bottles enabled but I think snowball "damage"/knockback could be canceled and probably splash potions as well. Due to the short range of splash potions it might be easier to block them only when inside another player's plot

**Comment by PhanaticD** [comment]
yea invisibility potions are extremely annoying for players

**Comment by chamunks** [comment]
With PlotSquared you should not require ClearLagg, if you require ClearLagg you're configuring it wrong.
