### ISSUE TITLE
Plot delete, and the automatic plot deletion, does not delete everything

### ISSUE THREAD

**Issue by jaboy** [IntellectualSites/PlotSquared#739]
Hello,

If a plot is rated using "/plot rate #" and then the plot is deleted with /plot delete, or it falls victim to the automatic plot cleaning, upon restarting the server, when plotsquared loads, it shows the message

[11:03:36] [Server thread/INFO]: PLOT 461 in plot_rating does not exist. Please create the plot or remove this entry.

This happens in version "PlotSquared v3.2.18" and older versions

**Comment by boy0001** [comment]
Fixed
