### ISSUE TITLE
Chestshop issue

### ISSUE THREAD

**Issue by Adambuhl** [IntellectualSites/PlotSquared#742]
Can someone make a tutorial for flags because i think this is outdated https://github.com/IntellectualSites/PlotSquared/wiki/Usage:-Plot-flags#default-flags

And the only thing i see is flags: {} 

Can someone make a tutorial a video and send me the link if not
Can you explain it to me?

**Comment by manuelgu** [comment]
The site is not outdated.
If you want to add a default flag (a flag that every plot automatically has) you have to do something like the following:

```
worlds:
  plotworld:
    flags:
      use: '1,2,3,4'
```
Where 1,2,3,4 needs to be replaced with the values you want.

**Comment by Adambuhl** [comment]
I cant find it in the config file

**Comment by manuelgu** [comment]
By default it says `flags: {}`

**Comment by Adambuhl** [comment]
Okay but when i type 63,68 in it just brokes the config

**Comment by manuelgu** [comment]
Care to elaborate? Please provide a "/p debugpaste"

**Comment by Adambuhl** [comment]
http://hastebin.com/lepenuteno

**Comment by manuelgu** [comment]
settings.yml Line 156 `    flags: {}`

That won't work ;) Please shut down the server, open the file, add the flag, save the file and start the server again.

You should also update your Spigot Version.

**Comment by Adambuhl** [comment]
How can i add the flag

**Comment by Adambuhl** [comment]
Can you just make a tutorial real quick on Youtube how to do that

**Comment by boy0001** [comment]
Quit being so incompetent. It's literally 5 characters. Change:
```YML
    flags: {}
```
to
```YML
flags: 63,68
```
Then use `/plot reload`
