### ISSUE TITLE
blocked-cmds does not allow wildcards/spaces

### ISSUE THREAD

**Issue by manuelgu** [IntellectualSites/PlotSquared#743]
As far as I saw the `blocked-cmds` does not allow spaces and/or wildcards in it. There is no way for me to e.g. block commands starting with `gm` nor can I add them manually (`gm 3` does not work because spaces are not allowed).

Could this get fixed?

**Comment by Sauilitired** [comment]
I implemented this feature mostly for fun, a while ago. I'm pretty sure `\s` are working for whitespace though?

I'll see if I can remake this during the weekend, as the overall implementation is pretty rubbish.

**Comment by Sauilitired** [comment]
** Reference to class **
https://github.com/IntellectualSites/PlotSquared/blob/master/src/main/java/com/plotsquared/bukkit/listeners/PlayerEvents.java#L319

**Comment by manuelgu** [comment]
Looks like `\s` works. But the system still needs revamping to allow blocking commands with all subcommands :-)

**Comment by Sauilitired** [comment]
`\S\s` as a lazy subcommand placeholder xD

**Comment by Sauilitired** [comment]
I'll close this as the revamp isn't really needed, using `\S\s` works fine :dancers:
