### ISSUE TITLE
Only part of plot can be built on

### ISSUE THREAD

**Issue by Al3xhamilt0n1** [IntellectualSites/PlotSquared#750]
I have members complaint that there is a big border around the edge so about 6 blocks from the wall block that they cannot build on, any ideas?

**Comment by manuelgu** [comment]
Is this the case for all plots? Please provide a "/p debugpaste"

**Comment by Al3xhamilt0n1** [comment]
http://hastebin.com/ayareyazaz

Here ya go

**Comment by manuelgu** [comment]
>  Is this the case for all plots?

Try to set the spawn-protection in your server.properties to `0`

**Comment by Al3xhamilt0n1** [comment]
Will give this a try it was set to 16. Thanks for the help!
