### ISSUE TITLE
[Idea] /plot middle

### ISSUE THREAD

**Issue by tivyhosting** [IntellectualSites/PlotSquared#752]
This command would center you on your plot, was present in PlotMe

**Comment by boy0001** [comment]
You can set the default home location to the center in the settings.yml. There's also `/plot set middle bedrock` (3.2.20+)

**Comment by manuelgu** [comment]
I've just released a [resource](https://www.spigotmc.org/resources/plotsquaredmiddle.16315/) that adds such a */p middle* command.


[Source](https://github.com/manuelgu/PlotSquaredMiddle)
@boy0001 Do you want to have that implemented in PS? I could make a PR for that..
