### ISSUE TITLE
Some entities not affected by `origin` metadata

### ISSUE THREAD

**Issue by manuelgu** [IntellectualSites/PlotSquared#754]
Most Entities are getting a metadata when they are spawned containing the origin plot. This is being used to kill entities that have been shot over with a slimeblock launcher or similiar.

Adding the metadata does not work for Iron Golems and Snow Golems. Therefore they can be shot over with a slimeblock launcher and bypass the mobcap.

**Comment by manuelgu** [comment]
This also affects Ghasts.

**Comment by MattBDev** [comment]
Is a bukkit limitation that metadata does not affect these mobs?

**Comment by manuelgu** [comment]
Don't currently have time to have a look much into detail but maybe it is missing in the switch-case or something https://github.com/IntellectualSites/PlotSquared/blob/4669f316581a0aeec32d3da8e451a1ec3fc8533c/Bukkit/src/main/java/com/plotsquared/bukkit/BukkitMain.java#L166

**Comment by dordsor21** [comment]
If you still have this issue, reopen.
