### ISSUE TITLE
BiomeGenerator bug

### ISSUE THREAD

**Issue by Orenthion** [IntellectualSites/PlotSquared#756]
When using the `/plot generatebiome <biome>`, i ran into a problem where using the `/plot generatebiome ice_mountains` command, it would affect blocks on the road.

**Comment by boy0001** [comment]
Could you describe how it effected the blocks on the road, and also provide a `/plot debugpaste`?

**Comment by Orenthion** [comment]
Can't seem to replicate, If i can get it to replicate, i'll re-open. 

It would replace some of the blocks with water, and also changes the biome on the roads and neighboring plots on the E,S,W sides.

[Debug Information](http://hastebin.com/ifivoqotak)

**Comment by MattBDev** [comment]
Ticket closed since it is super old.

**Comment by boy0001** [comment]
Note: Make sure the populater inset is at least 15
