### ISSUE TITLE
Players do not bypass entity-cap flag

### ISSUE THREAD

**Issue by manuelgu** [IntellectualSites/PlotSquared#759]
*Related to https://github.com/IntellectualSites/PlotSquared/pull/758*

`entity-cap` seems to count all entities, including players. This shouldnt be the case.

The video below shows an example.
[![Youtube Video](http://img.youtube.com/vi/cgC8qsU4f4s/0.jpg)](http://www.youtube.com/watch?v=cgC8qsU4f4s)

**Comment by boy0001** [comment]
If you say so. You should note that vehicles, mobs, animals and monsters already have their own category.

**Comment by manuelgu** [comment]
Do they add up on each other? So, would
`
vehicle-cap:20
mob-cap:20
animal-cap:20
hostile-cap:20
`

end up in max 80 entities per plot?

Still, I think players shouldnt get count for the entity-cap. It's getting bypassed by them either way (as you are not canceling the PlotEnterEvent when the entities on plot > entity-cap value)

**Comment by boy0001** [comment]
In that instance, hostile-cap and animal-cap are redundant, since the mob-cap is also 20. 

Entities includes things like paintings, armor stands, arrows, experience, items etc as well as all those categories.
