### ISSUE TITLE
 [Solution Included] Player not found when doing /plot setowner

### ISSUE THREAD

**Issue by Pangamma** [IntellectualSites/PlotSquared#762]
Did some digging in the source code, and I'm thinking you probably meant to use the UUID returned from other.getUUID(); 
http://puu.sh/lBXLt.png

Steps to reproduce:
Go to a plot. Claim it. Then try to set the owner of any member that is currently online. It doesn't work. It WILL work if that player is offline though.

**Comment by boy0001** [comment]
It should have worked if you used a different case to the online player's name. ie. instead of `Empire92` use `emPIre92`

Anyway, fixed in: 94b0fbb266a7a6d805de345485adc2c1fb22bbf4
