### ISSUE TITLE
Generator error?

### ISSUE THREAD

**Issue by gameplayerhd** [IntellectualSites/PlotSquared#765]
http://pastebin.com/R5XqAH8D
Any ideas?

PlotSquared v3.2.20

**Comment by boy0001** [comment]
Can you provide your settings.yml and multiverse configuration?

**Comment by gameplayerhd** [comment]
Settings.yml http://pastebin.com/dR3Lm3Rj
Multiverse http://pastebin.com/Wc0ePWQz

Only world in use is called creative.

Thanks for the quick response!

**Comment by boy0001** [comment]
You have two other worlds in the PlotSquared settings.yml, `plotworld` and `world2`.

`plotworld` is the one that is misconfigured. Various plot components are set to null, and the plot/road width are 0. Correct these values or delete these worlds.

World deletion must be done whilst the server is stopped. The settings must be removed the PlotSquared `settings.yml` and the Multiverse `worlds.yml`.

**Comment by gameplayerhd** [comment]
Thanks!
