### ISSUE TITLE
Plot clearing with given plot id not working

### ISSUE THREAD

**Issue by manuelgu** [IntellectualSites/PlotSquared#768]
You are not able to clear a plot when giving an id via command.

> `/p clear 2;-5`

This is related to the way it is [programmed](https://github.com/IntellectualSites/PlotSquared/blob/master/src/main/java/com/intellectualcrafters/plot/commands/Clear.java#L46-L61).

**Comment by boy0001** [comment]
From console you can do `/plot <id> clear`
