### ISSUE TITLE
Cant use PlotSquared commands

### ISSUE THREAD

**Issue by NakedSheepGaming** [IntellectualSites/PlotSquared#770]
So i'm having a problem, non-ops dont have permission to use any plot commands. I use group manager and these are my permissions: http://pastebin.com/GhC2z5Tt and my plotsquared config: http://pastebin.com/vvULTBNQ I hope you guys can help, i'm stuck with this problem for a few days now and dont know what to do.

**Comment by boy0001** [comment]
Verify that they actually have the permissions:    
`/manucheckp <player> <permission>`    

Make sure you don't have any dodgy plugins that block the use of any command starting with `/pl` (i.e. `/plugins` and `/plots` etc)

Determine what message, if any, is displayed when they attempt to use a command they do not have access to.

Respond to have this issue reopened.
