### ISSUE TITLE
Not generating the plot for cauldron server

### ISSUE THREAD

**Issue by runescapejon** [IntellectualSites/PlotSquared#771]
hey  i have a modpack server and i wanted a plot so i wanted to use your plugin for it i did everything right but the plots are just not generating i have quickly setup a normal minecraft server without mods and i did everything and the plots generated fine but it there a way to make it work on cauldron server ? or you can point me in the right direction please and thanks you

**Comment by tivyhosting** [comment]
Make sure you set the world generater in the Bukkit.yml or use multiverse to generate a world with the plotsquared generator

**Comment by runescapejon** [comment]
i did both nothing works

**Comment by chamunks** [comment]
Maybe try testing your configuration under a vanilla spigot instance to see if you're doing the base configuration correctly first.  Then feel free to make an attempt to run it in a Cauldron instance.

**Comment by runescapejon** [comment]
i did that and it started generating biomes as soon as i generate new chunks

**Comment by chamunks** [comment]
I'm not entirely certain that Cauldron is supported but I'll flag it as a bug and see what @boy0001 responds.  In the meantime I believe theres a /plot debugpaste command if you'd be so kind as to post its results here.  Along with any configurations and versions.  This will help make sure that he can replicate the issue and potentially fix it.

**Comment by boy0001** [comment]
It is some issue associated with your specific setup as you aren't able to get it to work on cauldron or spigot. I don't seem to be having any such issues on either platform.

> In the meantime I believe theres a /plot debugpaste command if you'd be so kind as to post its results here.

**Comment by runescapejon** [comment]
http://hastebin.com/ewosesizay
I'm so sorry for the late reply but in game it said https://gyazo.com/dc4b9ff38228c799e35e69cdb3e0963e  is this enough information or would you need more if so please let me know :)

**Comment by runescapejon** [comment]
i just use the old plotme and i use plotz still the same problem

**Comment by chamunks** [comment]
@runescapejon  Can you also try doing this map generation on a fresh copy of Cauldron running?

**Comment by runescapejon** [comment]
hmm i haven't tried that but ill give it a try ill let you know if anything okay thanks

**Comment by runescapejon** [comment]
okay i just ran a clean cauldron http://puu.sh/m0Gf8/ef5e1bfc52.png
that happen

**Comment by runescapejon** [comment]
I am just letting you know that i have found the problem with its BOP mod (biomes o plenty) once you have that mod in the server the plots will not regenerate

**Comment by runescapejon** [comment]
is there a chance of you to fix this problem?
