### ISSUE TITLE
Permissions per Plot

### ISSUE THREAD

**Issue by bossomeness** [IntellectualSites/PlotSquared#772]
Is there a way to give players certain permissions when they enter their own plot, but then remove then when they exit their plot? For example, I want to give players the option to create minigames in their own plot, but not in anyone else's. However, if given permission by another player, they could create minigames (or use certain commands, minigames are just an example) on that player's plot. I'm thinking it would be a flag such as "PermissionAllow" and the defaults would be whatever I set in the config. If it is already part of the plugin and I just overlooked it, that's awesome! But if it's not a part of the plugin, would it be possible to add it in in the future? And if not, do you know of any alternate way to do this?

**Comment by boy0001** [comment]
That's never going to be a reliable way to handle permissions. What minigame plugin are you trying to use anyway?

**Comment by bossomeness** [comment]
I was planning on using the Minigames plugin and possibly MobArena

**Comment by chamunks** [comment]
The only permissions plugin that does this is zPermissions but it only hooks into WorldGuard regions not PlotSquared regions.  That could be something that @boy0001 looks into but its likely going to be more of a hassle then you think.

**Comment by boy0001** [comment]
Definitely more hassle that way, as 1.) zPerms isn't exactly the most used permission plugin. 2.) Having something work properly would require PlotSquared to store the additional region related info, which isn't ideal for a niche feature.

With the next release you will need to do the following:
 - Set the `blocked-cmds` flag globally with the commands you want to prevent
 - Give players the permission `plots.admin.command.blocked-cmds.shared`
