### ISSUE TITLE
All players have been destroy all the plot's

### ISSUE THREAD

**Issue by WilliamEstrela** [IntellectualSites/PlotSquared#775]
I'm use plotSquared on my creative server, and all players have been destroy all plot's and permission dentry streets the plot's.

**Comment by lilacorn** [comment]
this is REALLY BAD and needs to be resolved ASAP...
My server tends to get griefers a lot and some of the noobs griefed the roads, other people's builds and much more.

**Comment by manuelgu** [comment]
Sounds like they have the wrong permissions. Please provide a "/p debugpaste" and upload your permissions file.

**Comment by lilacorn** [comment]
it happens when mobs are enabled on the roads and if that is on players can
destroy all blocks anywhere in the world including fire, TNT and mob
damages.

On Sun, Dec 6, 2015 at 1:31 AM, manuelgu <notifications@github.com> wrote:

> Sounds like they have the wrong permissions. Please provide a "/p
> debugpaste" and upload your permissions file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IntellectualSites/PlotSquared/issues/775#issuecomment-162286710>
> .
>



-- 
Michelle
Web: http://lilacorn.net

**Comment by boy0001** [comment]
@lilacorn 
> Please provide a "**/p debugpaste**" and upload your permissions file.

**Comment by WilliamEstrela** [comment]
http://hastebin.com/qekovirani

http://hastebin.com/vadalataca.sm

**Comment by WilliamEstrela** [comment]
hi?

**Comment by chamunks** [comment]
@WilliamEstrela I would suggest remove any unnecessary permissions from your file better safe than sorry.  You should also consider logging into your server with a player rank and try to replicate the issue yourself.  I see you still have a bunch of nodes remaining from PlotMe and such which makes me think that you don't clean up your permissions database.

**Comment by boy0001** [comment]
Sorry for taking a while to respond. 

The following worlds aren't configured correctly (As displayed in console during startup)
Eventos, plot_padrao - These worlds are not using the PlotSquared generator in multiverse worlds.yml and isn't configured to ignore this.
plot_normal - Plots exist in the database but the world doesn't exist (use `/plot purge` to delete these plots if you no longer want them)
test, plotworld, plot - These worlds do not exist in the multiverse configuration but do for PlotSquared (if you wanted to delete the world, also remove it from the settings.yml)

If you fix these issues and still can't get it to work, respond here.
