### ISSUE TITLE
ChestShop & PlotSquared

### ISSUE THREAD

**Issue by K3Feedz** [IntellectualSites/PlotSquared#776]
Hello Developer(s),

I have recently switched from Plotz to PlotSquared, but one issue I came across is ChestShop and PlotSquared.

So without using 
    flags:
      use: "323,54"
They cannot use ChestShop signs, but if I flag it/allow them to use it, they can start using signs, but random players can go inside someone's plot and take their items out. 
That's not the point, I would like it where you can use the player signs (323), but it prevents them from opening a chest.
I already tested it with 
    flags:
      use: "323"
, but sadly it did not work.
Hope to hear a response soon!

**Comment by boy0001** [comment]
Those are the wrong ids. Use 63,68
