### ISSUE TITLE
All worlds are randomly set to Creative

### ISSUE THREAD

**Issue by WonderNote18** [IntellectualSites/PlotSquared#779]
I've just recently installed PlotSquared and created a world under /plot setup, but when players switch between worlds, their creative gamemodes switch with them as well. Ill attach my config

[settings.txt](https://github.com/IntellectualSites/PlotSquared/files/57539/settings.txt)

**Comment by chamunks** [comment]
This sounds like something to do with either a world guard or multiverse configuration not a plot squared one. 

Your plot squared config is saying that the one world you do have configured is in survival.  

[ScreenShot](https://db.tt/nWLsbmyu)

You'll likely want to look over your WorldGuard configurations and regions or your server.properties or multiverse configurations.

**Comment by boy0001** [comment]
That setting is just related to resetting a player's gamemode when a player leaves a plot with the gamemode flag. Reason being that bukkit itself doesn't have any world specific gamemode options.
