### ISSUE TITLE
Losing player data while player login

### ISSUE THREAD

**Issue by EdenZ** [IntellectualSites/PlotSquared#780]
Server type:      Cauldron 1.7.10
Problem Detail: Player lose data when they login. Their inventories are cleared and their location is the spawn location of new player.
Command:       The reason why I think it is a issue from PlotSquared is that this problem is gone __ONLY__ if I remove this plugin. I do find something that may led to this error, however, I could not tell more since I am just a beginner for programming.

I personal think the problem comes from here:
```Java
 TaskManager.runTaskLaterAsync(new Runnable() {
            @Override
            public void run() {
                if (!player.hasPlayedBefore()) {
                    player.saveData();
                }
                ExpireManager.dates.put(uuid, System.currentTimeMillis());
                if (BukkitMain.worldEdit != null) {
                    if (pp.getAttribute("worldedit")) {
                        MainUtil.sendMessage(pp, C.WORLDEDIT_BYPASSED);
                    }
                }
                if ((PS.get().update != null) && Permissions.hasPermission(pp, C.PERMISSION_ADMIN_UPDATE) && Settings.UPDATE_NOTIFICATIONS) {
                    MainUtil.sendMessage(pp, "&6An update for PlotSquared is available: &7/plot update");
                }
                if (Settings.TELEPORT_ON_LOGIN && plot != null) {
                    MainUtil.teleportPlayer(pp, pp.getLocation(), plot);
                    MainUtil.sendMessage(pp, C.TELEPORTED_TO_ROAD);
                }
            }
        }, 20);
```
This is from [PlayerEvents] (https://github.com/IntellectualSites/PlotSquared/blob/35589dcc5fa56f55905d7d7083e0bcd2bad9054c/src/main/java/com/plotsquared/bukkit/listeners/PlayerEvents.java#L434) line 430.
__It listens to PlayerLoginEvent, which player data is not be loaded yet.__
Then it call saveData() in the schedule task. This may save an empty data into playerdata file.

* I heard that hasPlayedBefore() may be broken, but I did not test this myself.
* Most time when my players lose their data, most of them find that the connection quality to server is not so good.

```Java
@EventHandler (priority = EventPriority.LOWEST)
    public void onLogin(PlayerLoginEvent event) {
        event.getPlayer().loadData();
    }
```

I use this piece of code to fix the problem without changing anything in PlotSquared.jar.

I hope this help you. Please tell me if I made mistakes., thanks!

**Comment by EdenZ** [comment]
```Java
@EventHandler (priority = EventPriority.LOWEST)
    public void onLogin(PlayerLoginEvent event) {
        event.getPlayer().loadData();
    }
```
I use this piece of code to fix the problem without changing anything in PlotSquared.jar.

**Comment by donbubu** [comment]
hi,
we have the same problem here.
P2 Version: 3.2.23
New Player lose their inventory.

**Comment by i9hdkill** [comment]
Serious issue. Players are losing their inventories in version 3.2.23
Sigot 1.8.8
How to reproduce this:
plain 1.8.8 spigot
nocheatplus 3.14
plots 3.2.23

a player is an not plot world.

Players spams the chat, gets disconnected for it, logs back in=
Player file gets cleared  1 out of 3 times (not deleted)

**Comment by EdenZ** [comment]
@donbubu Wtihout reading through all related code I cannot say which is a better idea, however, it does solve the problem.
I add a piece of code in my plugin because I don't know how to modify the source code(while compling .java to .class I got errors).
