### ISSUE TITLE
PlotSquared UUID Problem

### ISSUE THREAD

**Issue by PinoyLifeCraft** [IntellectualSites/PlotSquared#781]
Server Version: 1.8.3
Plugin Version: 3.2.23
Server Mode: Offline Mode

-> My players plot will become Unknown some visitor can't visit due to a Unknown name of plot
------> but when the owner of the plot will online the plot work fine.
----------------[ What is the problem with this is this because of the UUID? ]---------------------------

**Comment by PinoyLifeCraft** [comment]
![2015-12-12_12 35 17](https://cloud.githubusercontent.com/assets/13610530/11760226/1d6bc008-a0ef-11e5-8804-6b0a1f550e24.png)
Here! is the Picture

**Comment by chamunks** [comment]
Thats actually something that I can confirm happens on @Athion as well in the BuildTeam server.  On occasion.

**Comment by PinoyLifeCraft** [comment]
Who have an idea to fix this?
My Player hate PlotSquared Now but for me PlotSquared is awesome :disappointed:

**Comment by chamunks** [comment]
My biggest problem is I've upgraded to a latest version and nothing has happened like this since so it may be fixed already but not be undo-able.

**Comment by PinoyLifeCraft** [comment]
I hope it will fix! :yum:

**Comment by MattBDev** [comment]
Is this still an issue? If I don't hear back, it will be assumed to be a fixed (or user resolved) issue.

**Comment by chamunks** [comment]
I haven't had really any crashes lately since upgrading to a recent build I will try to ask around if it's still been a problem.

**Comment by PinoyLifeCraft** [comment]
As my experiment when that player haven't online for how many days it will become **Unknown**

**Comment by MattBDev** [comment]
@PinoyLifeCraft can you provide a /plots debugpaste so I can further look into this issue?

**Comment by chamunks** [comment]
@MattBDev I can't exactly give you @PinoyLifeCraft's debugpaste but I can give you ours.  http://hastebin.com/uwoyumupuc  It seems to still be happening.

**Comment by frizzbee30** [comment]
We are now finding this to be an issue also (comment in discussion forum)

**Comment by chamunks** [comment]
What was done to remedy this and will it fix the current problems or simply stop them from happing further.

**Comment by MattBDev** [comment]
@chamunks nothing done yet. but I believe I have identified the issue.

**Comment by Pangamma** [comment]
Would it make sense to store last known usernames in the database on the player_meta table? That way it would be easy to do lookups by username, or partial username. 
SELECT * FROM player_meta WHERE `username` LIKE 'Panga%' ORDER BY len(`username`) ASC LIMIT 1

Then, when the players log in next time, if they have the same UUID but different username, you'd just update the username field in the DB.

**Comment by chamunks** [comment]
I don't think we've experienced this in a while was it patched? Can this be closed now?

**Comment by MattBDev** [comment]
I'm going to leave this open for 7 more days unless I get another reply saying it is still occurring.
@chamunks Not sure what could have stopped this from happening

**Comment by frizzbee30** [comment]
Hi we are still getting uknown plots? It's only a very minor issue though :)

![2016-05-27_10 42 06](https://cloud.githubusercontent.com/assets/8957914/15604434/43c789b2-23f8-11e6-9a49-abbe39832c9c.png)

**Comment by MattBDev** [comment]
The issue shall remain opened until fixed.

**Comment by Dakado** [comment]
This issue is known for more then 6 months and the developers are still unable to fix this simple bug ?

**Comment by MattBDev** [comment]
@Dakado I don't see you offering a fix. Empire and I have lives too. This plugin is **free**and open sourced. Don't complain because a fix isn't being worked on right away.

**Comment by frizzbee30** [comment]
@MattBDev agreed 1000% the quality and turn out rate from the dev's on this is second to none!

 I work for a global corporation, we have outstanding 'defects' over 10 years old!!!!  The dev team are NOT being paid for this, it is NOT a sponsored project. At the end of the day they can easily say 'stuff this for a game of soldiers' and walk away. We are beyond lucky that they have the commitment to produce such an outstanding plugin!

**Comment by MattBDev** [comment]
@frizzbee30 once the next dev build compiles, can you let me know if anything changes regarding this bug?

**Comment by frizzbee30** [comment]
@MattBDev will do :)

**Comment by manuelgu** [comment]
@frizzbee30 Make sure you have `debug: true` set in your settings.yml :)

**Comment by frizzbee30** [comment]
Hi tested build #184 and still some unknown plots, didn't notice anything in the changelog specifically referring to the UUID bit. I'm happy to test each successive one, or if you let me know if it's a specific build. Nothing showing with debug on :)

Thanks

**Comment by MattBDev** [comment]
@frizzbee30 thanks for the update. I'll let you know if there is any changes for you to try out in the future.

**Comment by MattBDev** [comment]
@frizzbee30 Try build 186

**Comment by chamunks** [comment]
We fixed this issue on play.Athion.net by switching to the sqluuid handler. Then let the uuid lookup happen over the next 24 hours. @mattbdev I believe there were a few patches that fixed a few reasons this was happening but ultimately switching was the real winner. Because the flat file local uuid cache was the problem.

**Comment by MattBDev** [comment]
Closed 👍
