### ISSUE TITLE
Clear plot after X days of inactivity

### ISSUE THREAD

**Issue by YepImRobbie** [IntellectualSites/PlotSquared#782]
The plot clear feature is so difficult to get to grips with, the analyse system makes no sense either, I scanned a completely empty plot and it claimed to have a 519 complexity, I have no idea what that means.

Can you please offer a feature which disposes of plots if the owner has been inactive for X amount of days.

Thank you.

**Comment by UltraX3** [comment]
Look at clear.auto in the PlotSquared config

**Comment by boy0001** [comment]
Set the threshold to `-1` and ignore the analysis then.
