### ISSUE TITLE
PlotSquared / ChestShop Issue.

### ISSUE THREAD

**Issue by YoloxPanda** [IntellectualSites/PlotSquared#784]
Hey!

Great work on PlotSquared! 

I ran into one problem with ChestShop

http://i.imgur.com/mM4NMJe.png this pretty much explains whats going on lol.

**Comment by UltraX3** [comment]
Either give them a flag (/plot set flag ) so they can interact with things, or give them the permission they need.

**Comment by YoloxPanda** [comment]
Well i tried that, same issue.

And when I gave the permission "plots.admin.interact.other" I was able to open chests on other plots, on a alt.

**Comment by boy0001** [comment]
In the PlotSquared settings.yml change:
```YML
    flags: {}
```
to
```YML
    flags: 
      use: 63,68
```
Then use `/plot reload`
