### ISSUE TITLE
/plot wea is not working for nonOPs

### ISSUE THREAD

**Issue by L4BORG** [IntellectualSites/PlotSquared#786]
It seems that /plot wea will not remove WE restrictions for nonOped players with 

```
plots.admin
plots.admin.*
plots.visit.other	true
plots.worldedit.bypass
```

permissions.

Any idea what seems to be the issue? Or it's plots.worldedit.bypass permission that is bugged?

Thanks!

Also yeah... latest WE, AWE and P^2.

**Comment by boy0001** [comment]
Try negating `plotsquared_user_attributes.worldedit`

**Comment by L4BORG** [comment]
"plotsquared_user_attributes.worldedit" permission? Negating didn't work... :(

**Comment by MattBDev** [comment]
I am pretty sure this is fixed
