### ISSUE TITLE
PlotWorld not working

### ISSUE THREAD

**Issue by Chompin** [IntellectualSites/PlotSquared#787]
My current setup is set for the plot world to be "plot world" but upon /plot home it teleports you to the world "world". And if I am in the plotworld world and do /plot info it tells me.

<addr>
worlds:
  plotworld:
    road:
      width: 9
      block: '98'
      height: 64
    plot:
      size: 80
      floor:
      - '2'
      filling:
      - '3'
      height: 64
      biome: FOREST
      auto_merge: false
      bedrock: true
      create_signs: true
    wall:
      block: '44:7'
      filling: '1:0'
      block_claimed: '44:1'
      height: 64
    event:
      pve: false
      pvp: false
      spawn:
        egg: false
        breeding: false
        custom: true
    home:
      default: side
      allow-nonmembers: false
    schematic:
      specify_on_claim: false
      on_claim: false
      file: 'null'
    economy:
      prices:
        merge: 100.0
        sell: 75.0
        claim: 100.0
      use: false
    chat:
      enabled: false
    limits:
      max-members: 128
    world:
      max_height: 256
      gamemode: creative
      min_height: 1
      border: false
    natural_mob_spawning: false
    flags: {}
</addr>

**Comment by boy0001** [comment]
Please provide a `/plot debugpaste`
Also make sure you are running the latest version of the plugin.

**Comment by MattBDev** [comment]
You can't have a space in the worldname.
