### ISSUE TITLE
In plotworld the plants do not grow

### ISSUE THREAD

**Issue by nathampa0909** [IntellectualSites/PlotSquared#788]
Hello, I have a bug with the PlotSquared (Last Version), the plants do not grow, nether wart, cactus, sugar cane, etc. only in plotworld because in the other world the plants grow correctly.

Best regards, Nathan.

#EDIT

The debugpaste: http://hastebin.com/cesofafihi

Plugins with initial N and Jairo are my plugins and don't have nothing to block the grow of plants.

And what is:

home:
      default: side

**Comment by nathampa0909** [comment]
Why you block the BlockGrowEvent?

https://github.com/IntellectualSites/PlotSquared/blob/master/src/main/java/com/plotsquared/bukkit/listeners/PlayerEvents.java#L923

**Comment by boy0001** [comment]
It's only blocked on the road. These blocks grow very slowly, so if you want to test properly, you might need to increase the growth modifier in the spigot.yml

"default: side" will teleport you to the side of the plot when you use `/plot home`
You can also use `center` or a coordinate e.g. `5,42`
