### ISSUE TITLE
Merge Mishap

### ISSUE THREAD

**Issue by EDamien** [IntellectualSites/PlotSquared#789]
I merged my plot with another plot, And my first plot was then unclaimed.

**Comment by MonkvanNederland** [comment]
We have a similar problem. After merging 4 plots, other player are able to claim 3 of them. Only 1 of the original 4 plots stays on the owners name. Unclear when this occurs. Merged plots gets unclaimed.

**Comment by MattBDev** [comment]
Merged with #801
