### ISSUE TITLE
Issues with scripting (add player plot permissions)

### ISSUE THREAD

**Issue by i9hdkill** [IntellectualSites/PlotSquared#791]
Hi,
I read your wiki sites and found your useful script to add permissions.
https://github.com/IntellectualSites/PlotSquared/wiki/Allowing-a-player-to-claim-more-plots

Unfortunately it isn't working for me.

Error:
http://pastebin.com/cT8GEYHv
He is complaining about a method that should be there, but is not.

Plots 3.2.24
Spigot: 1.8.8

Somewhere here I guess:
https://github.com/IntellectualSites/PlotSquared/blob/74a967b535767cb079be6c4a6cae1e6ab0802b4a/src/main/java/com/intellectualcrafters/plot/util/EconHandler.java

**Comment by boy0001** [comment]
Fixed.

**Comment by i9hdkill** [comment]
Thanks for the quiick response.
However, the fix didn't do that much:
http://pastebin.com/Qn8eW3fa
Same error
