### ISSUE TITLE
Lighting not updating on /plot clear.

### ISSUE THREAD

**Issue by JakeCB** [IntellectualSites/PlotSquared#798]
I made a lava tower and did /plot clear.
The results are https://imgur.com/a/CWuAj

This survives clear, delete, client restart, server restart. All with spigot random lighting refreshed turn on as well. 

Placing a glowstone and clearing seems to be sufficient to replicate at least on the plot world already having issues.
Let me know if there's any debug output you need or anywhere in the source I should look to breakpoint.

**Comment by boy0001** [comment]
Try setting fastmode to true in the settings.yml

**Comment by JakeCB** [comment]
That actually did clear up the plot itself. Now there it just some bleed over from the road back into the plot since the road had it's light level increased from the original lava. But that's not as noticeable.
