### ISSUE TITLE
Plot clear replaces signs on plots around

### ISSUE THREAD

**Issue by manuelgu** [IntellectualSites/PlotSquared#799]
When you clear a plot, the signs on the roads around and also the signs on the first row of the plots around get replaced with an empty sign.

**Reproduce**
1. Place signs on the first row of blocks around the plot that gets cleared.
2. Clear the plot next to it

![Image](http://i.imgur.com/zaeMwp2.png)
RED - Plot that gets cleared
BLUE - signs that get refreshed

**Comment by boy0001** [comment]
Tested, seems to be client side issue. Relogging or teleporting away/back will fix the signs.
