### ISSUE TITLE
WorldEdit

### ISSUE THREAD

**Issue by dangerORclose** [IntellectualSites/PlotSquared#800]
How can or what pers can i give me donators to get worldedit But not that they can crash the server down.

**Comment by boy0001** [comment]
Having WorldEdit async and doing some configuration is more important. If you configure things properly, you could get away with `worldedit.*`. You will need to do a bit of trial and error yourself. It depends how many people you have and how powerful the machine is.

Install FAWE or AWE
 - https://www.spigotmc.org/resources/free-fast-async-worldedit-%CE%B2.13932/ 
 - https://www.spigotmc.org/resources/asyncworldedit.327/

Then go over the WorldEdit config.yml, the PlotSquared settings.yml, and the config of FAWE or AWE.

More info:
https://github.com/IntellectualSites/PlotSquared/wiki/WorldEdit-processing
