### ISSUE TITLE
Username change would messup plots

### ISSUE THREAD

**Issue by L4BORG** [IntellectualSites/PlotSquared#803]
We're running latest PlotSquared with latest PaperSpigot in offline mode (behind BungeeCord) and I've started to noticing that username change would messup plots even tho UUID always stayed the same.

Plots would become owned by "unknown" person and that user could claim/create new plots (depending on permission).

Is this a bug or config issue?

Thanks!

**Comment by boy0001** [comment]
Is ip forward enabled in the spigot.yml?

**Comment by L4BORG** [comment]
Yes, on both BungeeCord and Spigot instance (as described here: https://www.spigotmc.org/wiki/bungeecord-ip-forwarding/ )

**Comment by L4BORG** [comment]
I'm just wondering how is P^2 generating/reading UUIDs?

**Comment by Sauilitired** [comment]
This doesn't seem like a relevant bug as of now (most likely user error), and it if is, then it could be re-opened.
