### ISSUE TITLE
block commands outside of plot

### ISSUE THREAD

**Issue by voigtman** [IntellectualSites/PlotSquared#804]
Is there a way to block specific (non /plots) commands when a player is not on their plot?
For instance - to block the /summon or /give commands when not on your own plot...

**Comment by boy0001** [comment]
You can do the following:
 - Set the blocked-cmds flag [globally](https://github.com/IntellectualSites/PlotSquared/wiki/Usage:-Plot-flags#default-flags) with the commands you want to prevent
 - Give players the permission` plots.admin.command.blocked-cmds.shared`

You might want to consider other solutions however.
