### ISSUE TITLE
Plots merging without command

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#806]
in my 500x500 plot world, I have two plots which are merged, -2;-2 and -2;-3

However just today my neighbor is complaining that I own her plot, I look and their plot at -2;-1 is now merged with my two merged plots, even though I never merged it, and neither has she. I confirmed by looking through the logs neither of us have done the merge command in the past month

I have auto-merge set to false for all the plot worlds

**Comment by PhanaticD** [comment]
this happened again

**Comment by Sauilitired** [comment]
@boy0001 What did you even do to plots? I mean, artificial intelligence is one thing, but having the plots roam around at free will? That's a step too far.

**Comment by MattBDev** [comment]
Cannot reproduce. Please refile the report if it is still an issue.
