### ISSUE TITLE
Plotsquared Flags Affecting Other Worlds

### ISSUE THREAD

**Issue by logicalPolaris** [IntellectualSites/PlotSquared#807]
Running the latest build (3.2.24). Upon going into a plot with either the Time or Weather flags, it will affect the other worlds that a player visits. If a plot is set to night, and a player teleports to another world (without plotsquared), the time will be stuck at night for the client.

**Comment by Legoman99573** [comment]
Are you using multiverse? I wouldn't use the plotsquared one. You can change weather/day cycle to true or false In config.

**Comment by boy0001** [comment]
Fixed in 3.2.25
