### ISSUE TITLE
Problem with trusted players and offline owners

### ISSUE THREAD

**Issue by Ferdzz** [IntellectualSites/PlotSquared#813]
Hi, on the server I'm currently working on players told us that they can't edit nor use `/p h [username]` on plots that the owner is disconnected, even if they are trusted on this specific plot. Did I miss a permission or something? I couldn't find any.

Maybe this issue is related to #315 ?

**Comment by manuelgu** [comment]
What version of PlotSquared are you using? Are you sure they are `trusted` and not `added`?

Players added via `/p add` are only able to build when the owner of the plot is online.
Players added via `/p trust` are always able to build on the plot.

**Comment by Ferdzz** [comment]
I am running version 3.2.24 and I am sure they are not added, as when I use `/p i` over their plots, the names of their trusted members appear next to `trusted: `

**Comment by boy0001** [comment]
If you updated from an old version, it's possible that the plot info is not reliable (deleting the translations file will reset it). Make sure you used `/plot trust <player>`

As for teleportation, you will need a permission for teleportation to shared plots:
`plots.home`, `plots.visit`, `plots.visit.shared`

More info: https://github.com/IntellectualSites/PlotSquared/wiki/Commands#visit
