### ISSUE TITLE
the command /p unclaim not work.

### ISSUE THREAD

**Issue by Andre601** [IntellectualSites/PlotSquared#814]
I found a BIG problem...
I can't unclaim a plot. I have the permissions (OP) but when i type /plot unclaim the message "successfully unclaimed the plot." but its still claimed...

**Comment by EvilOlaf** [comment]
Are you sure that it is still claimed? Check `p info`. `p unclaim` does not reset the plot, so all buildings will remain there. If you want to reset a plot and remove any set flags/members/owners use `p delete`.

**Comment by Andre601** [comment]
Im sure!

I looked with /p info
I was still the Owner of the Plot. And it was shown in the Title...
And the title only appears, when someone owned that plot.

**Comment by EvilOlaf** [comment]
Hm okey, then we may have a problem :P 
Are you running the latest version of P^2? Check Spigotmc.org for it.

**Comment by Andre601** [comment]
jep.

And I use it on a Spigot 1.8.8 Server

**Comment by manuelgu** [comment]
Use `/p dispose` for now.

**Comment by Ferdzz** [comment]
I'd like to add that the claim sign at the border of the plot still stays, even after using /p unclaim

**Comment by boy0001** [comment]
Fixed in the next version. `/plot delete` is still the preferred command.
