### ISSUE TITLE
Use flag issue

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualSites/PlotSquared#815]
I recently updated to 3.2.24 and noticed that ServerSigns now need the `interact.other` permission.
I tried to fix this by setting the `use` flag to `68,63` in the `settings.yml` which did not work.

Also tried setting this flag to `68,63` ingame which worked.
The weird thing is that it shows the globally set flags correctly at `p info` but they seem not to work....well, `use` at least.

Thanks for reading.

**Comment by boy0001** [comment]
Cannot replicate. Could you attach a copy of the settings.yml?

**Comment by EvilOlaf** [comment]
Yep, hold on.

http://pastebin.com/nFP5afKq

**Comment by JammMusic** [comment]
+1 on this. Same issue but with ChestShop. I've tried everything mentioned and more.

**Comment by Victor-Sun** [comment]
I was able to fix this with **use all** or **use 0:0**

**Comment by JammMusic** [comment]
You can set flags in your config that apply to all plots.

**Comment by EvilOlaf** [comment]
Yes, but as mentioned above this seems not  to work as expected.

**Comment by MattBDev** [comment]
@EvilOlaf Still an issue?

**Comment by EvilOlaf** [comment]
Not sure but I think so. Did not hear any complains recently.
