### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by WilliamEstrela** [IntellectualSites/PlotSquared#816]
: Invalid plot / road width in settings.yml for world: plotworld

**Comment by EvilOlaf** [comment]
Then you have an issue with your settings.

Use `plot debugpaste` and put the output here.

**Comment by WilliamEstrela** [comment]
http://hastebin.com/ebeqemajan

**Comment by WilliamEstrela** [comment]
http://prntscr.com/9obh0y

**Comment by EvilOlaf** [comment]
Road width cannot be 0

**Comment by WilliamEstrela** [comment]
I 've changed and configuação resets and returns 0

**Comment by EvilOlaf** [comment]
Did you try to remove your current settings and start over using the setup assistant?

**Comment by WilliamEstrela** [comment]
I converted the plotme for plotsquared

**Comment by EvilOlaf** [comment]
Try setting the correct width values for the roads and the plots and disable plotme conversion. Then try reloading your settings.

**Comment by WilliamEstrela** [comment]
http://prntscr.com/9oboxc

**Comment by WilliamEstrela** [comment]
Resolved, return plotme and convert plotsquared, before disable plot convertion in config tks ;)

**Comment by EvilOlaf** [comment]
:+1:
