### ISSUE TITLE
Create higher walls

### ISSUE THREAD

**Issue by Curtis3321** [IntellectualSites/PlotSquared#817]
Hello, I've been looking around and I am unable to find out how to create walls higher than 1 thick.

I want to make walls on a players plot to stack upto 256, since I plan to split plots up / you can't see other plots kinda thing.

Is this possible? if not, could you make it.

Awesome plugin, thanks.

**Comment by boy0001** [comment]
In the settings.yml, there is a road and wall height option. It should prompt you for this value during `/plot setup`
