### ISSUE TITLE
Permission to bypass plot expiry

### ISSUE THREAD

**Issue by teaearlgraycold** [IntellectualSites/PlotSquared#819]
Hey, this would be an excellent addition to the plugin so that some users (admins/donors) could be exempt from their plots being pruned based on inactivity.

**Comment by boy0001** [comment]
Set the `keep` flag to `true` to exempt a plot.

**Comment by EvilOlaf** [comment]
I think he wants this to be done kind a automatic by adding a permission node like `plots.autoclear.except` or so which has the same effect as setting the `keep` flag you suggested.

**Comment by teaearlgraycold** [comment]
Yes, that's what I'm looking for, Olaf
