### ISSUE TITLE
Plotworld Setup is Bugged

### ISSUE THREAD

**Issue by Czab1** [IntellectualSites/PlotSquared#822]
When setting up a plotworld, the steps only show numbers.
![te](https://cloud.githubusercontent.com/assets/13577273/12369746/feed6f7c-bbb1-11e5-80c1-130642d9bf87.png)

So Step 1 looks like:
[Plots] [Step 1] 1 - Expecting: 1 Default: 1

Debug Paste: http://hastebin.com/tiwojozame
Here is a short video showing it in more detail: https://youtu.be/zKM_nT4fFHg
I'm using version 3.2.26.

**Comment by boy0001** [comment]
Old issue, has been fixed
