### ISSUE TITLE
PlotSquared, Permission Notifications

### ISSUE THREAD

**Issue by YoloxPanda** [IntellectualSites/PlotSquared#825]
Hey!

Is there, any way I can disable the notifications for PlotSquared Lacking Permissions?

Here's what i'm talking about

http://i.imgur.com/b7UhgA3.png

**Comment by manuelgu** [comment]
Go to `translations/PlotSquared.use_THIS` and change `no_permission` as well as `no_permission_event` to `""`

**Comment by YoloxPanda** [comment]
thank you!
