### ISSUE TITLE
Notify-Enter bug

### ISSUE THREAD

**Issue by diecode** [IntellectualSites/PlotSquared#829]
When I set notify enter flag to on, then plugin notify the player, who entered in the plot, not the plot's owner.

**Comment by Sauilitired** [comment]
```java
if ((owner != null) && !owner.getUUID().equals(pp.getUUID())) {
  MainUtil.sendMessage(pp, C.NOTIFY_ENTER.s().replace("%player", pp.getName()).replace("%plot", plot.getId().toString()));
}
```
In https://github.com/IntellectualSites/PlotSquared/blob/master/src/main/java/com/plotsquared/listener/PlotListener.java

Yeah, that's an easy fix. I'm on a bus right now, so I can't do it right away
