### ISSUE TITLE
Plot Update issue

### ISSUE THREAD

**Issue by CoolLord22** [IntellectualSites/PlotSquared#835]
I don't know if the website http://ci.intellectualsites.com/job/PlotSquared/ is down or what but I can't seem to connect to it at all. The /p update command fails to update and I can't even open the website in my browsers. They all lead to a This webpage is not available ERR_CONNECTION_TIMED_OUT error. Is it just me or for everyone else?

**Comment by Sauilitired** [comment]
Yeah, that's my personal website; and it's been down for quite some while. Fortunately, I've gotten a hold of stable funding for that site alone, and therefore it will be back soon enough. Until then, use manual updating from the spigot page.

**Comment by boy0001** [comment]
Broken from: 51d2e378536ff540397721367c6a07c29c2e70ad

**Comment by manuelgu** [comment]
https://github.com/IntellectualSites/PlotSquared/pull/837

**Comment by CoolLord22** [comment]
Alrighty! Thanks!

**Comment by CoolLord22** [comment]
Another issue: I got the latest version (from Spigot) which was version 3.2.26, but it still says that there is an update available...what do I do?
