### ISSUE TITLE
Timings

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/PlotSquared#842]
![untitled](https://cloud.githubusercontent.com/assets/10485646/12536798/ec26e682-c2a7-11e5-9192-443c53980947.png)
Why is it so high?
Config: http://pastebin.com/531rzgYq

**Comment by boy0001** [comment]
Uh, I wouldn't say it's that high, given that you're clearing a plot. You could try enabling fastmode clearing in the settings.yml, or disable plot clearing until the SetBlockQueue is optimized for 1.8.8

**Comment by SecretlyJealous** [comment]
I've limited players to plot clearing once per hour in the picture above, I found an issue with fastmode clearing though, for some reason it doesn't clear the entire plot?

**Comment by SecretlyJealous** [comment]
Here's another timings:
![untitled](https://cloud.githubusercontent.com/assets/10485646/12621254/aac7270c-c517-11e5-8120-828b6fd09fb7.png)

**Comment by MattBDev** [comment]
Still an issue? @boy0001 @SecretlyJealous ?
