### ISSUE TITLE
Stop using permissions to set attributes.

### ISSUE THREAD

**Issue by aaomidi** [IntellectualSites/PlotSquared#843]
This is horrible practice for servers that use cross server permissions. You're forcing a ton of data to be written to and from database...

**Comment by edyyy** [comment]
:+1:

**Comment by aaomidi** [comment]
Sorry I have to jump and no time to PR.

https://gist.github.com/42f7403515ccefba8bf4

Using a HashSet is many times faster O(1) vs O(unknown). Also does not literally break permissions plugins.

If you HAVE to do it via permissions, create your own permissions attachment.

**Comment by Sauilitired** [comment]
The attribute system should be switched over to PersistentMeta, which is handled by us.

**Comment by Sauilitired** [comment]
Hlwever

**Comment by aaomidi** [comment]
Put the set on sql? Or whatever system used for storing. Permissions aren't really meant to be changed every second.

**Comment by Sauilitired** [comment]
```java
PlotPlayer#getPersistentMeta(String) 
PlotPlayer#setPersistentMeta(String, byte[]) 
PlotPlayer#hasPersistentMeta(String) 
```

The attribute system should be removed, and everything depending on it should use these methods instead.

**Comment by aaomidi** [comment]
Can't we do something like so:

    @Override
    public void setAttribute(String key) {
        setPersistentMeta(key, new byte[1]);
    }

    @Override
    public boolean getAttribute(String key) {
        return getPersistentMeta(key) != null;
    }

    @Override
    public void removeAttribute(String key) {
        removePersistentMeta(key);
    }
