### ISSUE TITLE
Downloaded Plot Schematics Not Working, with an error message in MCedit

### ISSUE THREAD

**Issue by TheAmazingSpy** [IntellectualSites/PlotSquared#848]
So I play on a server, and I am not staff, just a player, I can not use the downloaded schematics with MCedit or Worldedit. I get an error message saying: ValueError('plot.schematic is too small! (0) ',)
This has been an issue for ALL players, so please halp.

**Comment by TheAmazingSpy** [comment]
For some reason, it appears as 0 bytes, so that's why the error message is there, but the thing of why it's doing that, I do not know

**Comment by MattBDev** [comment]
If you are a player, you shouldn't be reporting this issue. You should be telling the server admins about it since it could just be that they didn't setup plot schematics properly.
