### ISSUE TITLE
Update Command Error

### ISSUE THREAD

**Issue by aviswing** [IntellectualSites/PlotSquared#850]
Whenever the server tells me theres a. update available, I do /plot update, nothing happens.

Then I try again and still nothing. Then when I log out and back into my server it says it again, "There's an update available"

**Comment by manuelgu** [comment]
Known. Apparently nobody got the time to push a new update.
https://github.com/IntellectualSites/PlotSquared/pull/837

**Comment by MattBDev** [comment]
Fixed.
