### ISSUE TITLE
World border

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/PlotSquared#851]
Is it possible to add an automatic world border that scales according to the furthest non-expired plot from 0;0? This will prevent people from flying too far and increasing the map size too much because I currently host 516x516 sized plots and I'm not really a large fan of the trim command because of how intensive it is. I just think an automatic border will be much better and efficient.

**Comment by manuelgu** [comment]
This is not in the scope of this plugin. Use [WorldBorder](http://dev.bukkit.org/bukkit-plugins/worldborder/) instead

**Comment by SecretlyJealous** [comment]
I've created my own plugin using the PlotSquared api to do this, thanks anyway.

**Comment by Sauilitired** [comment]
@SecretlyJealous https://github.com/IntellectualSites/PlotSquared/wiki/World-reduction#world-border ?

**Comment by SecretlyJealous** [comment]
I don't think it works in the way I want it to work, I made a border which stops players from entering half way past the road which contain unclaimed plots rather then a global radius from point 0;0.
![2016-01-31_14 38 55](https://cloud.githubusercontent.com/assets/10485646/12702720/6dde81be-c828-11e5-87bd-3eb0315c04cd.png)
