### ISSUE TITLE
Please set the generator correctly or delete the world from the 'settings.yml'

### ISSUE THREAD

**Issue by RocoWayne** [IntellectualSites/PlotSquared#857]
Hi! Im new in PlotSquared but yesterday i tested in my server.

Y do the /plot setup default, it works JUST great.

But when i reload the server, the PlotSquared world, in my server called "Creativo", stop working

> [ERROR] World 'Creativo' in settings.yml is not using PlotSquared generator! Please set the generator correctly or delete the world from the 'settings.yml'! (https://github.com/IntellectualSites/PlotSquared/wiki/Manual-generator-setting)

I try the Manual Generator Setting but i think im doing something wrong, can you help me please? The plotworld was full of people creating and now the world is no more a PlotSquared :S

**Comment by MattBDev** [comment]
you literally copy this into your bukkit.yml and edit it: 
`worlds:
    <world name>:
      generator: PlotSquared`
