### ISSUE TITLE
Not in a plotworld

### ISSUE THREAD

**Issue by dangerORclose** [IntellectualSites/PlotSquared#860]
All was working fine until today!
Notting changed and whoops /p h sais No plots found in your searsh querry...
When i do /p auto in the plotworld it says You are no in a plotworld..
Please i need asap help

play.wafmc.be

**Comment by boy0001** [comment]
Please provide a startup log and a `/plot debugpaste`

**Comment by dangerORclose** [comment]
This is verry late..
I reclaimed every single plot by /p setowner .. There is no time to wait a week. I also have a 2e issue that always is when it says do /p update it gives after doing that a error that it can't update it to do it manually

**Comment by MattBDev** [comment]
If you want immediate help you should have went to the IRC page. If this issue is resolved please let us know so we can close it.
You need to create a new issue if you want to discuss another bug. You need to do a manual update as the update command is down at the moment.
