### ISSUE TITLE
Spectator bypass bug

### ISSUE THREAD

**Issue by zombachu** [IntellectualSites/PlotSquared#861]
While a player is ~~riding~~ spectating another player using gm 3, they can enter plots that they are denied from.

**Comment by MattBDev** [comment]
Typically players shouldn't be able to ride players especially if they are in gamemode 3.

**Comment by zombachu** [comment]
@MattBDev I mean like spectating a player by left-clicking them. Poor choice of words on my part, sorry.

**Comment by EvilOlaf** [comment]
If you do not "ride" a player in gm 3 the deny works?

**Comment by MattBDev** [comment]
if you are in ["mob view"](http://minecraft.gamepedia.com/Spectator) I think it is fine for the deny not to work. Many servers leave spectator mode unavailable for regular users and it is mainly used by admins.

**Comment by zombachu** [comment]
@EvilOlaf Yes

**Comment by boy0001** [comment]
This could be a spigot bug. It does not call the PlayerMoveEvent even though they are technically moving.

**Comment by zombachu** [comment]
@boy0001 I think that you're right since I've encountered this problem when implementing afk detection. I've already submitted a [bug report](https://hub.spigotmc.org/jira/browse/SPIGOT-1480) but apparently it's a bug that can be traced back all the way to [vanilla](https://bugs.mojang.com/browse/MC-46445). 

In the meantime, would you consider making a temporary fix? Something ghetto can be done like checking all players in a radius of 0 around a player that enters a plot. 



Also another bug that I found is that it doesn't kick out players in mob view when denying them

**Comment by lilacorn** [comment]
just eliminate GMSP privilages from the permissions

**Comment by zombachu** [comment]
@lilacorn That's a solution to the problem (albeit by disabling a feature) but it doesn't fix what causes it

**Comment by MattBDev** [comment]
Closed. Let Mojang and Spigot take care of this.
