### ISSUE TITLE
Sky Islands

### ISSUE THREAD

**Issue by Darkool** [IntellectualSites/PlotSquared#862]
Hi, I would like creating a floating island like skyblock but with certain modifications 
http://pasteboard.co/1rhbdSTs.png
As you can see on the picture, the red lines limit the plot and the rest should be the road or something like that, How I can make that? Thank you in advance.

PS: I tried on void world with a island's schematic but it says "schematic too long" what is the limit of my schematic? thanks.

**Comment by RocoWayne** [comment]
This is a great idea

**Comment by Sauilitired** [comment]
You can just create a road schematc, where the road is the rest of the island; and the middle part of the plot schematic. It might require some fiddling around, but it's not impossible

**Comment by Darkool** [comment]
Ya, I tried that, but roads should be the same right? I mean My roads should be different on every side

**Comment by boy0001** [comment]
You can do the whole thing with the `plot.schematic`. The roads only supports one side, while a plot schematic can spill into the road area and have different blocks on each side.

**Comment by Darkool** [comment]
but on wiki says that our schematic shound't be more bigger than plot size, you mean that I can put for example: plot size:50x50 and my schematic can be 90x90 for example? and overlap roads?

I get too long schematic, what is the max size that I can use?

**Comment by boy0001** [comment]
That's for pasting a schematic on claim I believe.

I was referring to this `plot.schematic`: https://github.com/IntellectualSites/PlotSquared/wiki/Installation#optional-generate-a-world-with-a-schematic-already-in-the-plot
