### ISSUE TITLE
Help messages cannot be translated

### ISSUE THREAD

**Issue by ExtremoDuro** [IntellectualSites/PlotSquared#866]
There are no references in the plot squared translation YML to several strings in the plugin, such us /plot help (the command explanation is in english, for every command).

Is there any way this could be translated?

Thanks in advance.

**Comment by boy0001** [comment]
@Sauilitired Command descriptions are hardcoded in the annotations.

**Comment by Sauilitired** [comment]
That's incredibly easy to fix :)
