### ISSUE TITLE
Some entities can be placed on plot borders

### ISSUE THREAD

**Issue by manuelgu** [IntellectualSites/PlotSquared#870]
**PlotSquared Version**: 3.2.26
**Description**: Some Entities can be placed on plot borders and won't get killed (both kill vehicle and kill mobs enabled). These entities are _ArmorStand, Item Frame, Painting_.

This is an issue because players are able to place the entities on the plot border when they are facing a block on a plot they are allowed to build on.

They are also not counting towards the entity cap.

[http://i.imgur.com/LoYydAo.png](http://i.imgur.com/LoYydAo.png)

**Comment by boy0001** [comment]
Please provide a `/plot debugpaste`

My settings likely differ as I can't replicate with armor stands.

**Comment by manuelgu** [comment]
http://hastebin.com/rahunadoru

It also (kinda) makes sense, as neither _kill_road_vehicles_ nor _kill_road_mobs_ include ArmorStands, ItemFrames and Paintings.
