### ISSUE TITLE
/plot home brings me to wrong world

### ISSUE THREAD

**Issue by MrCullDog** [IntellectualSites/PlotSquared#872]
I am an admin for a large server and we recently had an issue where our plots world, All of the correct plots data/ownership works, but whenever a player does /plot auto or /plot home it claims a plot in plots world and then teleports them to the location of their plot in the main creative world. I read one suggestion to close the server and regen the world, however this is not an option as we have 9000+ claimed plots that we cannot loose. 

Thank you for your time

-MrCullDog

**Comment by boy0001** [comment]
Please provide a startup log and a `/plot debugpaste`

**Comment by dordsor21** [comment]
use /plot home [#] p2 will remember all plots across the server, not just in a world.

**Comment by MattBDev** [comment]
This issue will be closed if more details and a `/plot debugpaste` are not provided within the next 2 days
