### ISSUE TITLE
Users can't Worldedits in their claimed plots

### ISSUE THREAD

**Issue by systemacc** [IntellectualSites/PlotSquared#873]
Users cannot Worldedits in their claimed plotsquared Plots. They have worldedit permissions and can use //wand and select positions but when trying a command such as //replace or //set - it says you may have extended out your Worldedit region. How do I fix this issue and how do I make it so when players claim their plots, they can automatically use Worldedits if they have perms to w/e?

W/e= Worldedit

**Comment by dordsor21** [comment]
I found this issue when using P2's build in FastAsyncWorldEdit whilst stupidly having the plugin itself installed on the server. I would check whether you have this also @systemacc

**Comment by batchkrazy** [comment]
You can give your users access to world edit. as long as the do not have perms to admin interact on other plots it will work fine.

**Comment by boy0001** [comment]
Please provide a `/plot debugpaste`
