### ISSUE TITLE
Pathway/Road Copy Leaving Out 1 Block!

### ISSUE THREAD

**Issue by nicktrick92** [IntellectualSites/PlotSquared#875]
So I run the command /plot createroadschematic when standing inside of the plot in the first picture I have attached here... When I run the debug command, it looks like it just left out a line of blocks for copying (2nd picture)... Why is this happening?
![2016-02-15_06 32 28](https://cloud.githubusercontent.com/assets/4327302/13051415/f62888d6-d3ad-11e5-98c0-a59ccc622881.png)
![2016-02-15_06 32 50](https://cloud.githubusercontent.com/assets/4327302/13051414/f624ed70-d3ad-11e5-9d7c-f447000fa33a.png)

Does it not like that I am building something in the corners or something?

Thanks for the help,

-Nick

**Comment by MattBDev** [comment]
Not enough information
