### ISSUE TITLE
Teleport Task (not) on Primary Thread

### ISSUE THREAD

**Issue by Maxetto** [IntellectualSites/PlotSquared#876]
Hi, I'm reporting here a potential Bug that asofold reported on the [BukkitDev comments section](http://dev.bukkit.org/bukkit-plugins/plotsquared/?comment=66).
Since this bug is really annoying with error messages and since it seems you don't look anymore at the BukkitDev page, I'm reporting it here:

> Hey threre. I have a question about a teleport task running off primary thread:
> 
> https://github.com/IntellectualSites/PlotSquared/blob/master/src/main/java/com/plotsquared/bukkit/listeners/PlayerEvents.java#L454
> https://github.com/IntellectualSites/PlotSquared/blob/master/src/main/java/com/intellectualcrafters/plot/util/TaskManager.java#L45
> http://pastebin.com/C6ghaCue
> Is that intended?

**Comment by MattBDev** [comment]
@Maxetto It looks like you might not be running the latest version. Mind double checking and letting me know what version you are running.

**Comment by boy0001** [comment]
@MattBDev 
That part hasn't been changed either way.

@Maxetto 
It uses the built in bukkit scheduler for the task. I tested and do not have the same problem. Try updating PlotSquared / Spigot.

**Comment by boy0001** [comment]
Please make sure you are using a stable version of PlotSquared/Spigot.
