### ISSUE TITLE
database need fix?

### ISSUE THREAD

**Issue by SliderKP** [IntellectualSites/PlotSquared#877]
i'm getting this error:
[Server] INFO UUID of player BrandonxDD is 6e546c22-74f2-3bf6-9df5-004c7b8b1354
[Server] INFO Detected invalid UUID stored for (1): BrandonxDD
[Server] INFO - Did you recently switch to online-mode storage without running `uuidconvert`?
[Server] INFO PlotSquared will update incorrect entries when the user logs in, or you can reconstruct your database.

i have converted my database from plotme, what i can do to fix this? 
i use 1.8.8 version and offline mode

**Comment by MattBDev** [comment]
@SliderKP please run the command "/plot debugpaste" and reply with the link. If you don't provide anything within a few days this issue will be closed.

**Comment by SliderKP** [comment]
DebugPaste: http://hastebin.com/wujecofamo

**Comment by MattBDev** [comment]
@SliderKP You can ignore the message and the plugin should resolve the issue itself
