### ISSUE TITLE
/plot home bug

### ISSUE THREAD

**Issue by rErEaT** [IntellectualSites/PlotSquared#880]
I am using bridges as route and when player use /plot home its teleport him to up side of bridge.

Can you fix this?
maybe spawn to the plotside but not the route, maybe inside

**Comment by QUIQUELHAPPY** [comment]
there is an spawn option on the settings.yml. I don't know if in the wiki you can search for the flags you can use for it

**Comment by rErEaT** [comment]
yepp but only center and side.

I need a side opinion with someblock block close to the center

**Comment by MattBDev** [comment]
Please provide pictures and a better description.

**Comment by boy0001** [comment]
You can set coordinates
e.g.
```YAML
    home:
      default: "5,6"
```
