### ISSUE TITLE
PlotSquared and Redstone Clock Preventer 2 Issue

### ISSUE THREAD

**Issue by CoolLord22** [IntellectualSites/PlotSquared#885]
# Bug report template (clear for feature request)
**Debug paste link**:http://hastebin.com/awefapojok

**Description of the problem:** I have the plugins PlotSquare3d and RedstoneClockPreventer2 (An official addon) and I keep getting this error message in the console when a player activates redstone. http://pastebin.com/Aciv2Psq

**How to replicate**: Unsure. I just have the 2 plugins together. A player activates some sort of redstone (in this case a piston and pressure plate) and it sends that error.

Make sure you've completed the following steps (put X inside of brackets):
- [ X ] Include `/plot debugpaste`
- [ X ] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [ X ] Made sure you're using an updated version of PlotSquared
- [ ? ] Made sure the bug/error isn't caused by any other plugin (Unsure if this is the case but I am pretty sure it isn't. It's the two plugins maintained by the same author.)

**Comment by MattBDev** [comment]
You are using a dev build and those are typically not supported. The dev builds include some breaking API changes which requires addons to be updated. Please use the stable 3.2.26
