### ISSUE TITLE
Players in mob view in spectator mode are not kicked out of plots when they are denied

### ISSUE THREAD

**Issue by zombachu** [IntellectualSites/PlotSquared#886]
**Debug paste link**: http://hastebin.com/zeweqebubo

**Description of the problem:** See title

**How to replicate**:

1. Go into spectator mode and left click a player to go into mob view
2. Have the player you are spectating go into a plot
3. Have the plot owner deny you
4. The "You were denied from the plot you were previously on, and got teleported to spawn" message appears, but you're not teleported

Make sure you've completed the following steps (put X inside of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment]
I don't see why they need to be kicked off when only ops typically have spectator mode. Plus I thought this issue was closed because it was a Bukkit/Spigot issue?

**Comment by zombachu** [comment]
@MattBDev This is a different issue, the other one was for players entering plots (this is if they're already on the plot when the event happens)

I've actually been running [a fix](http://puu.sh/nfEtX/3c7e1820c4.png) for this on my server that takes into account whether or not the player has bypass permissions. Spectator mode is useful for builders and redstoners, which is why I've given it to lower ranked players. (after fixing all the issues that it causes, of course)
