### ISSUE TITLE
/p middle does not work

### ISSUE THREAD

**Issue by zombachu** [IntellectualSites/PlotSquared#888]
**Debug paste link**: http://hastebin.com/zeweqebubo

**Description of the problem:** Using /p middle gives the "Not a valid subcommand" error

**How to replicate**:

1. Go to a plot
2. Use /p middle
3. Receive the error message

Make sure you've completed the following steps (put X inside of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by CoolLord22** [comment]
I can do /p middle but I get teleported to the bottom of the plot in the corner.

**Comment by MattBDev** [comment]
@zombachu can you provide a new hastebin link? The current one isn't working and I would love to fix this issue.

**Comment by manuelgu** [comment]
https://github.com/IntellectualSites/PlotSquared/blob/master/Core/src/main/java/com/intellectualcrafters/plot/object/Plot.java#L1074-L1078

Not entirely sure, but isnt that formula wrong?
`
x = ((plot.maxX - plot.minX) / 2) + plot.minX
y = ((plot.maxZ - plot.minZ) / 2) + plot.minZ
`
This should work better (pseudocode)

**Comment by boy0001** [comment]
It's the same
= ((maxX - minX) / 2) + minX
=  ((maxX - minX) / 2) + (2 * minX) / 2
=  ((maxX - minX + 2 * minX) / 2)
= (maxX + minX) / 2

**Comment by zombachu** [comment]
@MattBDev Hastebin seems to be down for the moment (can't access the link anymore either, and doing /plot debugpaste returns a 503 error) so for the moment I made a [pastebin](http://pastebin.com/fWJJp1GL) containing all the information that I could gather for the moment.

**Comment by zombachu** [comment]
@MattBDev @boy0001 In [the code] for the command (https://github.com/IntellectualSites/PlotSquared/blob/1768651782c8fab37ae9d02de48283477ecfa872/Core/src/main/java/com/intellectualcrafters/plot/commands/Middle.java) there's no permission that's declared in the CommandDeclaration

**Comment by MattBDev** [comment]
@zombachu I noticed. that. I am adding that now. The permission should fix it.

**Comment by boy0001** [comment]
It has nothing to do with the permission node. It defaults to `plots.<command>` It's just from the top method returning the bottom, which I'll fix now.
