### ISSUE TITLE
Can't use my World Edit in Plot Squared 3.2.27

### ISSUE THREAD

**Issue by PinoyLifeCraft** [IntellectualSites/PlotSquared#889]
# Bug report template (clear for feature request)
**Debug paste link**:
http://pastebin.com/CgtrrCt8
**Description of the problem:**
I can't use my World Edit even i'm using /plot wea
I'm doing the First and Second Position!
![2016-02-20_18 52 52](https://cloud.githubusercontent.com/assets/13610530/13201404/7009f662-d8cc-11e5-9efb-29db6bef0138.png)
Then /plot wea to Unrestricted the plot
![2016-02-20_18 53 03](https://cloud.githubusercontent.com/assets/13610530/13201405/9758ceaa-d8cc-11e5-9a81-42b681cc62a2.png)
After that it's not working!
![2016-02-20_18 53 16](https://cloud.githubusercontent.com/assets/13610530/13201406/a59abbfe-d8cc-11e5-9e95-8740d6621421.png)

**Comment by LaxWasHere** [comment]
huh, didn't know there are filipino based servers. Kamusta!

**Comment by manuelgu** [comment]
Your debugpaste is not a real debugpaste (`/plot debugpaste`).
Seems like you are running 3.2.27, please try with the 3.2.26 version from the spigot page.

**Comment by MattBDev** [comment]
3.2.27 will not have an official release. Next version is 3.3.0 and is under heavy development. Things will be breaking until a stable version is released.
