### ISSUE TITLE
/plot done not working with PlotRankup

### ISSUE THREAD

**Issue by Smexybeest** [IntellectualSites/PlotSquared#890]
# Bug report template (clear for feature request)
**Debug paste link**:
http://hastebin.com/aqijahonup

**Description of the problem:**
Plot done doesn't work, gives no response in chat, gives an error in console
Issue doesn't occur without PlotRankup installed.

**How to replicate**:
/plot done on a plot that you're the owner of and isn't already on the done-list.

Make sure you've completed the following steps (put X inside of brackets):
- [X] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [X] Made sure you're using an updated version of PlotSquared
- [ ] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment]
You did not do the following: 

> Made sure the bug/error isn't caused by any other plugin.

This issue is caused by PlotRankup.

**Comment by Smexybeest** [comment]
I thought PlotRankup was an addon on plotsquared.

Also, plotrankup broke due to a plotsquared update, it works with outdated versions.

**Comment by MattBDev** [comment]
@Smexybeest That doesn't mean it is a PlotSquared issue. It means you report it to PlotRankup.

**Comment by Smexybeest** [comment]
Alright I'll do that then
