### ISSUE TITLE
How do I specify the permissions for each flag?

### ISSUE THREAD

**Issue by QUIQUELHAPPY** [IntellectualSites/PlotSquared#891]
Hi!
I need the permission node for each flag!

Thank you.

**Comment by MattBDev** [comment]
https://github.com/IntellectualSites/PlotSquared/wiki/plots.permpack.basicflags
In the future, this is an issue tracker. Not a question tracker. You should use the forums for questions like these.

**Comment by EvilOlaf** [comment]
It is a bit off-topic but I think it is not the worst idea to let users ask questions here as well.
In the forums you have one big thread with thousands of comments mixed with useless stuff and some questions also. It's kind a butthurt to rake up through these. Someone asks a question and gets his answer about four pages later. No clear view. Hard to find anything specific.

Here a user asks his question, it gets answered, issue closed, forget about.

Just my two cents.

**Comment by boy0001** [comment]
Well there is an issue label if that means anything.

**Comment by manuelgu** [comment]
Agree with EvilOlaf :)

**Comment by MattBDev** [comment]
Apologies, I guess I wasn't in a good mood when I wrote that.

**Comment by EvilOlaf** [comment]
No worries @MattBDev. Guess this can be a matter of dispute. I will open a seperate issue report to discuss about how to handle issues and questions. Kind a decision of general principle ;)
