### ISSUE TITLE
decision of general principle handling user questions

### ISSUE THREAD

**Issue by EvilOlaf** [IntellectualSites/PlotSquared#892]
Related to https://github.com/IntellectualSites/PlotSquared/issues/891

It is a matter of dispute how to handle user questions.
There a multiple ways to handle this:
- First is to tell users to post questions which are obviously not an issue with P^2 on the Spigot forums only.
- The other way is to allow user questions at github as well.
- The 3rd is to tell users to ask specific questions at Github only 'cause of the lack of a clear scheme at the forums

As for my taste I would prefer the 3rd variant. My arguments I already posted:
> In the forums you have one big thread with thousands of comments mixed with useless stuff and some questions also. It's kind a butthurt to rake up through these. Someone asks a question and gets his answer about four pages later. No clear view. Hard to find anything specific.

On the downside there will be more "issue" reports here mixed up with real issues. However some users either might not be able to distinguish if a special situation is an issue or not or at the bottom line it does not really matter where to answer a questions, in forums or at Git. Both needs probably the same amount of time.

@boy0001 @Sauilitired @MattBDev 
Your choice to create a standard for this situation.

Best regards
Olaf

**Comment by boy0001** [comment]
I don't want to encourage stupid questions or people just creating a ticket before checking the wiki. I also don't want people to expect that issues here are a way to get answers in a timely fashion, IRC would probably be better suited for that (if someone is available). 

The above however would also apply to the forums. I don't want stupid questions here or there. That being said, I have no problem with genuine questions, even if they aren't necessarily related to PlotSquared. Anything related to running a plot server should be allowed. 

So, if there has to be a distinction:
GitHub: Intelligent and relevant questions, Issues and feature requests which may or may not get a timely response.
Forums: Intelligent questions / general problems. Specific issues and feature requests belong on GitHub. Also no guarantee on a quick response.
IRC: Stupid questions and completely unrelated banter allowed. Complicated issues / features belong on GitHub. Quick response if someone is on.
