### ISSUE TITLE
Forum Feedback

### ISSUE THREAD

**Issue by Sauilitired** [IntellectualSites/PlotSquared#893]
Hello! I am setting up our new forum and I need feedback. Mostly on the horrendous theme that I've tried to fix up. Please comment on any findings, or if there's something you want me to clean up / remove. I'm trying to make the whole thing as clean as possible. 

URL: https://intellectualsites.com/forum/

**Comment by Sauilitired** [comment]
Updated both "plotsquared.org" and "plotsquared.com" to just point to serenitydev.com

**Comment by Sauilitired** [comment]
Nevermiiiiind, changes are coming lol

**Comment by manuelgu** [comment]
Looks pretty good so far!

You are loading from a non-SSL Location `http://files.enjin.com/265719/images/topMenu/logo_minecade.png` so Chrome marks the website as insecure.
