### ISSUE TITLE
Plot clearing confirmation

### ISSUE THREAD

**Issue by boy0001** [IntellectualSites/PlotSquared#895]
Give an admin a notification that there are {Number Of Plots} plots that could be cleared would you like to [ /autoclear (Potentially Dangerous) ] [ /manualclear (helps plot squared learn what to clear) ] [ /avoidthismessage ( do it later ) ]

**Comment by chamunks** [comment]
## User Story perspective.
As an Admin or Moderator when I log in:
I would like to be notified if PlotSquared's heuristic plot clearing system has detected plots that are eligible to be deleted.
I would like plot squared to offer me the option to do one of the following.

* /plot autoclear  [ Potentially dangerous if you haven't trained Plot Squared yet ]
* /plot manualclear [ let plot squared take you for a tour of plots marked for deletion and ask you if you think it should delete the plot or not ]
* /plot procrastinate [ Do this later if you want to just ignore the message ] (Maybe*)

## The reasoning
This would potentially be the inverse of /plot rate where plot rate is designed to point out what plots are acceptable plots.  This would train plot squared more specifically what are unacceptable plots.

**Comment by boy0001** [comment]
Added
