### ISSUE TITLE
Road Template stops generating

### ISSUE THREAD

**Issue by 685** [IntellectualSites/PlotSquared#896]
# Bug report template (clear for feature request)

http://hastebin.com/apocadetel

**Description of the problem:**
The "bridge" schematic loaded properly the first time I generated a plotworld.
When I changed something (placed some blocks on the bridge) I think the bridge didn't generate anymore so the bridge just stopped after about 300 blocks and loaded the default plots instead of the bridge template

Make sure you've completed the following steps (put X inside of brackets):
- [X] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [X] Made sure you're using an updated version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by boy0001** [comment]
Yep, it's broken on 3.2.27 (development build)
Please downgrade to 3.2.26:
https://www.spigotmc.org/resources/plotsquared.1177/download?version=62892

**Comment by boy0001** [comment]
Should have been fixed
