### ISSUE TITLE
Use (CodeTree or Waffle) for issue management 

### ISSUE THREAD

**Issue by Sauilitired** [IntellectualSites/PlotSquared#897]
https://github.com/integrations/codetree
https://github.com/integrations/waffle
 
What do you guys think? Both are rather awesome, imo.

**Comment by manuelgu** [comment]
They both look cool, not too sure if it is really necessary to move to another issue management than the one from GitHub though.

**Comment by EvilOlaf** [comment]
Same.

**Comment by Sauilitired** [comment]
I think it would allow for easier management of issues, and suggestions. And it would allow for easier separation between them.

**Comment by boy0001** [comment]
Due to the number of issues, I think a tile based organization would just make it worse. Waffle is only tile based, so I'd say no to that. Codetree has lists as well, but it seems the main appeal is supporting multiple repositories which I'm not really doing.

**Comment by boy0001** [comment]
Well I tried them both out and the integration is extremely disappointing. It's a separate website which is just a wrapper around the GitHub issue tracker which can only be viewed by a logged in GitHub account that has authorized the application. Viewing the project through the GitHub website doesn't do a thing.

CodeTree is also a 14 day trial.

**Comment by Sauilitired** [comment]
@boy0001 :/ Well, it was a good thought.

**Comment by MattBDev** [comment]
What about YouTack?

**Comment by Pangamma** [comment]
But I already have a github account... And so do most developers.
