### ISSUE TITLE
Update CommandAPI

### ISSUE THREAD

**Issue by Sauilitired** [IntellectualSites/PlotSquared#898]
The CommandAPI version is reallyyyyy outdated

CommandAPI Repo: https://github.com/IntellectualSites/CommandAPI/tree/master/src/main/java/com/intellectualsites/commands

**Comment by boy0001** [comment]
Should I wait on you to implement this before releasing the next version?

**Comment by Sauilitired** [comment]
@boy0001 I just needed to get my jenkins up and running again (as I'd rather shade the jar than manually copy the files). This will either be done tonight or tomorrow :pig:

**Comment by boy0001** [comment]
Bump?

**Comment by Sauilitired** [comment]
@boy0001 Sorry things got pretty messy due to the hackers (pfft, evil people) :///// I'll make sure to implement it as soon as I fix everything that got broken on minecade

**Comment by MattBDev** [comment]
If you can add this in the next 5 days, it will be extremely helpful so I can add #929

**Comment by MattBDev** [comment]
@Sauilitired I've tried messaging you on skype without hearing back from you. Are you able to complete this soon?
