### ISSUE TITLE
Chunk packet causes minor client side memory leak

### ISSUE THREAD

**Issue by boy0001** [IntellectualSites/PlotSquared#899]
Only really an issue with thousands of chunk updates e.g. exploring augmented world.

Also related:
Block changes hide entities temporarily

**Comment by MattBDev** [comment]
I really don't see what we can do about a client side issue?

**Comment by boy0001** [comment]
@MattBDev It has to do with the way block changes are sent to the client. Normal bukkit doesn't have this issue.

**Comment by Sauilitired** [comment]
Is this still an issue? In that case we've been torturing clients since 2016. That should be our slogan :cat:
