### ISSUE TITLE
World not expanding.

### ISSUE THREAD

**Issue by ExtremoDuro** [IntellectualSites/PlotSquared#901]
**Logs URL**: http://hastebin.com/afogoqojip

**Description of the problem:** World not expanding after several claims.

**How to replicate**: A world with       "border: true", players get their plots using /plot auto. After two days, all the players get their plots OUTSIDE the current border, and the border does not expand, causing them to get teleported back, with the error message "World border reached".

Make sure you've completed the following steps (put X inside of brackets):
- [X] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues). Didn't find any.
- [X] Made sure you're using an updated version of PlotSquared Using Spigot version, latest dev has several bugs.
- [X] Made sure the bug/error isn't caused by any other plugin. 90% sure it is P2.

Thanks in advance.

**Comment by boy0001** [comment]
Should be fixed in 3.3.1
