### ISSUE TITLE
ArmorStand falls in road

### ISSUE THREAD

**Issue by WebShark025** [IntellectualSites/PlotSquared#902]
**Hi.
There are 2 Serious bugs in all servers using PlotSquared.
Both are with ArmorStands.
First, Players can create a wall near the plot slabs, then it will fall on the slabs (Out of the plot)
Then, if they use Pistons & Slime Blocks, it will shot the armorstand into the roads.

And only admins can clear them (I use 'ClearLagg' myself.)

Thanks for fixing them.
Best Regards**

**Comment by manuelgu** [comment]
Probably related to #870 which should be fixed in `3.3.0` (not out yet).

**Comment by MattBDev** [comment]
Please use the bug reporting format in the future to help resolve issues faster.
