### ISSUE TITLE
Trying to run plotsquared for survival area protection

### ISSUE THREAD

**Issue by batchkrazy** [IntellectualSites/PlotSquared#903]
# Bug report template (clear for feature request)
**Debug paste link**:
27.02 19:13:17 [Server] INFO === Oh no! Please set the generator for the Survival === 
27.02 19:13:17 [Server] WARN java.lang.NullPointerException 
27.02 19:13:17 [Server] WARN at com.boydti.psmg.generator.MegaPlotWorld.loadConfiguration(MegaPlotWorld.java:65) 
27.02 19:13:17 [Server] WARN at com.intellectualcrafters.plot.object.PlotWorld.loadDefaultConfiguration(PlotWorld.java:221) 
27.02 19:13:17 [Server] WARN at com.intellectualcrafters.plot.PS.loadWorld(PS.java:1245) 
27.02 19:13:17 [Server] WARN at com.intellectualcrafters.plot.PS.loadWorld(PS.java:1226) 
27.02 19:13:17 [Server] WARN at com.plotsquared.bukkit.BukkitMain.setGenerator(BukkitMain.java:611) 27.02 19:13:17 [Server] WARN at com.intellectualcrafters.plot.PS$3.run(PS.java:287) 
27.02 19:13:17 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)

**Description of the problem:**
had done a world with plot set using the plotsquaredmg generator
setting it to vanilla generation with road widths to 0.
on reboot it keeps trying to force 
27.02 19:13:17 [Server] INFO - Your world management plugin may be faulty (or non existant) 
27.02 19:13:17 [Server] INFO plot.height : 64 27.02 19:13:17 [Server] INFO plot.biome : FOREST 
27.02 19:13:17 [Server] INFO plot.size : 32 
27.02 19:13:17 [Server] INFO plot.filling : [1:0] 
27.02 19:13:17 [Server] INFO plot.floor : [2:0] 
27.02 19:13:17 [Server] INFO wall.block : 44:0 
27.02 19:13:17 [Server] INFO wall.block_claimed : 44:1 
27.02 19:13:17 [Server] INFO wall.block_protected : 44:1 
27.02 19:13:17 [Server] INFO wall.block_forsale : 44:1 
27.02 19:13:17 [Server] INFO wall.block_auction : 44:1 
27.02 19:13:17 [Server] INFO road.width : 7 
27.02 19:13:17 [Server] INFO road.height : 64 
27.02 19:13:17 [Server] INFO road.block : 155:0 
27.02 19:13:17 [Server] INFO wall.filling : 1:0 
27.02 19:13:17 [Server] INFO wall.height : 64

**How to replicate**:
Make a predefined world a plots world.

is there a way to keep it from tryn to make walls n what not for a survival world.

Make sure you've completed the following steps (put X inside of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [ ] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by batchkrazy** [comment]
http://hastebin.com/vovuqumuge

**Comment by MattBDev** [comment]
Caused by megagenerator and not plotsquared

**Comment by boy0001** [comment]
When deleting the world, you need to make sure it's removed from the PlotSquared settings.yml, the bukkit.yml and the multiverse worlds.yml
