### ISSUE TITLE
Feature: Plots flag serialization 

### ISSUE THREAD

**Issue by Ksnz** [IntellectualSites/PlotSquared#906]
It would be nice if save/load to schem command also saved and loaded flags.

**Comment by boy0001** [comment]
Note: You can copy that information using `/plot copy` and `/plot move`

**Comment by MattBDev** [comment]
Wouldn't this require modifying the schematic format which is well established in the Minecraft Community? 
I'm not sure even adding the extra data would be good since it would require the schematic file to get larger. I do see the usefulness of this though.

**Comment by boy0001** [comment]
@MattBDev Nah, you can add tags for anything you want. WorldEdit will just ignore anything it doesn't understand.

**Comment by Ksnz** [comment]
> Note: You can copy that information using /plot copy and /plot move

I know but i want to use PSApi for my minigame plugin .
I found out that BO3 probably save tags but load `NOT IMPLEMENTED YET!`

**Comment by boy0001** [comment]
BO3 isn't what you want anyway. It's slow and used for exporting small objects on the plot (e.g. a tree) for world population rather than the whole plot itself: https://github.com/MCTCP/TerrainControl/wiki/BO3-objects
