### ISSUE TITLE
Armor Stands and Clearing Plots

### ISSUE THREAD

**Issue by Erictigerawr** [IntellectualSites/PlotSquared#908]
**Debug paste link**:
http://hastebin.com/imumelitov
**Description of the problem:**
Testing with staff if Armor Stands were limited per plots. Anyways, after placing a good 100/150 armor stands we did /plot clear and it seems not all the armor stands were cleared. I had to clear it a few more times -> then relogged and they reappeared. Most would turn invisible but would still be there/fixed by relogging to see them and breaking them hand by hand.
**How to replicate**:
Place tons of armor stands in a plot then clear it and see :) 
Make sure you've completed the following steps (put X inside of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by ItsAZZA** [comment]
Tried to replicated the problem and actually crashed the server. Some armor stands were removed, but some still were in place after server restarted itself.

**Crash Report**: http://hastebin.com/exabubivug.vbs

**Comment by RedstoneFuture** [comment]
On my server I havn't a problem with this.

![2017-11-19_00 34 28](https://user-images.githubusercontent.com/4140635/32985745-a2db06c2-ccc1-11e7-8e69-58bf492b2511.png)


After /p clear all armor stands was deleted. After a rejoin I can't see any amor stand too.

**Comment by RedstoneFuture** [comment]
Have you still this problem?

**Comment by boy0001** [comment]
Assumed fixed.
