### ISSUE TITLE
/p h:# <name> does not work

### ISSUE THREAD

**Issue by zombachu** [IntellectualSites/PlotSquared#910]
**Debug paste link**: http://hastebin.com/ibixevuvod

**Description of the problem:** Returns "That's not a valid number within the range: (1, ∞)" instead of teleporting to name's # plot. I'm 99% sure that this is caused by [lines 377 to 389](https://github.com/IntellectualSites/PlotSquared/blob/master/Core/src/main/java/com/intellectualcrafters/plot/commands/MainCommand.java#L377-L389) never being reached in MainCommand.java because the colon [is stripped out](https://github.com/IntellectualSites/PlotSquared/blob/master/Core/src/main/java/com/intellectualcrafters/plot/commands/MainCommand.java#L302-L304) before handle() is called.

**How to replicate**:
1. Do /p h:# <name> with the plot# and name of your choice
2. Receive the error message

Make sure you've completed the following steps (put X inside of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by boy0001** [comment]
Note: The correct syntax is `/plot visit [player] [#]`. The home command is an alias, and the colon is to accommodate those used to the PlotMe syntax.
