### ISSUE TITLE
Plot Visit for multiple owners.

### ISSUE THREAD

**Issue by ElmHoe** [IntellectualSites/PlotSquared#912]
# Bug report template (clear for feature request)
**Debug paste link**:
http://hastebin.com/mulepibema
**Description of the problem:**
The problem remains when multiple owners share a plot, ie in this circumstance where HyperSkill & Ling555 share a plot. When Ling wants to go to her plot shared with him, /p h and /p v Ling555, don't work. Instead she's forced to /p v HyperSkill. 
Plot Visit continues to TP to hyperskills plot, not in the middle point nor is there anyway of it to tp straight outside Lings plot. 

**How to replicate**:
/p merge <location>
/p v <owner1>
/p v <owner2>
Only one would work.

Make sure you've completed the following steps (put X inside of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by boy0001** [comment]
Possibly fixed, needs testing
