### ISSUE TITLE
Not a vaild Plot world

### ISSUE THREAD

**Issue by GoldyHD** [IntellectualSites/PlotSquared#914]
So im trying to make the road schematic work and i keep typing into my console "/p regenallroads Plots" Thats the name of the world that i created and yes i created it with a capital. But for some reason it says that is not a vaild plot world (case sensitive) 

Please can somebody help

**Comment by MattBDev** [comment]
Please reply with a '/plot debugpaste' within 24 hours or this issue will be closed. Please follow the issue template next time instead of deleting it.

**Comment by GoldyHD** [comment]
I dont undertsand what to do with the template. Im sorry about this im new to minecraft server making

**Comment by EvilOlaf** [comment]
This is not related to minecraft server making, this is just about having a proper format for all issue reports to make it easier for developers to fix/answer them.
So when you create a new issue report enter all information ask in the form, especially the output of `/plot debugpaste`.

No one here has a second sight to guess what CB/Spigot/Paper you are running, what version of P^2 you are running, what your config files look like. 
These information are important.

**Comment by boy0001** [comment]
f00ac79c91bb8daaabaa4f07aefeb16d6ced8981
