### ISSUE TITLE
1.9 Problem

### ISSUE THREAD

**Issue by MGD9000** [IntellectualSites/PlotSquared#917]
After deleting a plot It can't be reclaimed. Also can a plot be set to permanent? For a plot spawn?

**Comment by MattBDev** [comment]
If a '/plot debugpaste' is not produced within 24 hours, this issue will be closed.

**Comment by MGD9000** [comment]
I'll just wait for an update. Please close this and thank you for such a great plugin and hard work. I have total respect for you guys!
