### ISSUE TITLE
"That is not a valid plot area" Error when issuing <plots regenallroads> command...

### ISSUE THREAD

**Issue by dwelfman** [IntellectualSites/PlotSquared#918]
# Bug report template (clear for feature request)
**Debug paste link**:

**Description of the problem:**
I am running into the same issue as #914 opened by GoldyHD, which appears to be closed due to insufficient information.  I will try to provide the information requested in the template.  Upon issuing the <p regenallroads ...> command I get the error message "[Server] INFO [P2] That is not a valid plot area (case sensitive)."

**How to replicate**:
Go through the following steps and it always happens...
(1) Design a simple road to use as a template (I simply placed a grass stripe down the middle of the road on the west side of a plot).
(2) issue </plots createroadschematic> from the client plot where the road is on the west side.
(3) Going to another plot and issuing </plots debugroadregen>.  This appears to work as expected.
(4) Teleport to another non-plot world using </mvtp Wilderness>.  Not sure if this is necessary, but since it will try to regen all the roads I figured it was safest to not be in that world during the regen.
--->Problem<---
 (5) Go to the console (because this command must be executed from the console) and issue the <plots regenallroads Town> where "Town" is the name of the world I have created as my plotworld.  This command generates the error message: "" on the console.

Make sure you've completed the following steps (put X inside of brackets):

- [] Include `/plots debugpaste`  I tried, but couldn't figure out how to make this command work - nothing ever got pasted to my clipboard so I could include it here.

- [X] Made sure there aren't duplicates of this report [Another user started the same issue, but it was closed due to insufficient information.](https://github.com/IntellectualSites/PlotSquared/issues)

- [X] Made sure you're using an updated version of PlotSquared
It appears to be - /plots plugin shows it is 3.3.0 and the newest version is 3.3.0.

- [X] Made sure the bug/error isn't caused by any other plugin
I've reduced my Plugins to only the following, and the issue continues to happen.
1.) Spigot (CraftBukkit version git-Spigot-44c59bf-9f0f4ed (MC 1.8.7) implementing API version 1.8.7-R).1-SNAPSHOT).
2.) PlotsSquared (ver 3.3.0)
3.) PermissionsEx
4.) WorldEdit
5.) Vault
6.) Essentials
7.) ProtocolLib
8.) WorldGuard
9.) Multiverse-Core

**Comment by MattBDev** [comment]
@dwelfman I'd love to help and I appreciate you providing as much information as you did but we need the link that is shown to you in chat when you perform the command `/plot debugpaste`. Please provide the link ASAP or we will have to close the issue.

**Comment by boy0001** [comment]
f00ac79c91bb8daaabaa4f07aefeb16d6ced8981
