### ISSUE TITLE
How can i allow people to ride minecarts in all plots but stop griefing?

### ISSUE THREAD

**Issue by DannyPokemon** [IntellectualSites/PlotSquared#923]
Is there a way i can allow people  to ride mine carts but without allowing them to build? that would make it easier to build minecart tracks on the roads.

**Comment by manuelgu** [comment]
You can set the [vehicle-use](https://github.com/IntellectualSites/PlotSquared/wiki/Flag:-vehicle-use) Flag as a default one in the `settings.yml`

```
flags:
    vehicle-use: true
```

**Comment by DannyPokemon** [comment]
Thanks, proves i should read the wiki more often.
