### ISSUE TITLE
PlotSquared API Method Replacement

### ISSUE THREAD

**Issue by GiansCode** [IntellectualSites/PlotSquared#924]
Hello,

So, I've developed a PlotMine plugin that runs solely off the API you have provided with your plugin. However, since the recent update, there appears to be no .getWorld().worldname method anymore. I was wondering what the replacement was? I have left a snippet of the code below.

public PlotIdentity(Plot plot) {
		this(Bukkit.getWorld(plot.getWorld().worldname), plot.getId());
	}

Another thing. 

public Plot getPlot() {
		return Main.PLOT_API.getPlot(world, id.x, id.y);
	}

Appears to be deprecated now. What is the recommended replacement?

I am only asking here because I have searched the JavaDocs and can't find it

**Comment by boy0001** [comment]
After the introduction of multiple areas per world, the method was renamed. Otherwise it would have been confusing having multiple plot worlds per world.
`getArea().worldname`
