### ISSUE TITLE
Border of plots are not correct

### ISSUE THREAD

**Issue by xion87** [IntellectualSites/PlotSquared#926]
I just got this issue by updating plotsquared to 3.3.1
in config i got plot border:
      filling: '1:0'
      block_claimed: '171:14'
      height: 64
      block: '171:5'

and empy plots look all like this
http://i.imgur.com/EMahgBq.png

Instead if i claim it, it will stay with red carpet, but when i do /plot delet it will become green bordered... no errors

**Comment by boy0001** [comment]
The road schematic will override the standard plot generation.

**Comment by xion87** [comment]
is the schematic road that you gived to me (fixed on)
