### ISSUE TITLE
Frost Walker II enchantment bug

### ISSUE THREAD

**Issue by runescapejon** [IntellectualSites/PlotSquared#928]
# Bug report template (clear for feature request)
**Debug paste link**:
http://hastebin.com/xiresanota
**Description of the problem:**
When a player have Frost Walker II enchantment it bypassing the plot with water
**How to replicate**:
just have a plot with water and have a player with frost Walker II with boots and walk on it 
Make sure you've completed the following steps (put X inside of brackets):
- [ http://hastebin.com/xiresanota] Include `/plot debugpaste`
- [i have seen a few pages and nothing about this issue ] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [3.3.0 ] Made sure you're using an updated version of PlotSquared
- [im sure that its not cause by anything ] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment]
I'll check out NMS in craftbukkit to see if frostwalker triggers any event that we can listen to. If it doesn't then there may not be anything we can do until an event is added.

**Comment by MattBDev** [comment]
This bug extends into CraftBukkit/Spigot level.

**Comment by MattBDev** [comment]
@runescapejon Closing this issue. Please take up the issue with Spigot development since they feel this is a "minor" issue.

**Comment by Johandrex** [comment]
Could ya link me to the bug ticket you made to Spigot?

**Comment by manuelgu** [comment]
https://hub.spigotmc.org/jira/browse/SPIGOT-1849

**Comment by runescapejon** [comment]
xD i didnt know that the bug was reported i already reported it and it said its resolved https://hub.spigotmc.org/jira/projects/SPIGOT/issues/SPIGOT-1895?filter=allissues is there a way to fix this now ?@MattBDev

**Comment by MattBDev** [comment]
@runescapejon It can't be fixed. Your issue was marked as a duplicate. I'm submitting a patch later today with the fix

**Comment by manuelgu** [comment]
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/a09454032a06eeeb9e405167a9a4aff02b4ce0f9

http://hastebin.com/aduwigifis.coffee
