### ISSUE TITLE
Economy Support for  More Commands

### ISSUE THREAD

**Issue by cindyker** [IntellectualSites/PlotSquared#929]
Enhancement Request:
My current setup for PlotMe, I make my players pay with ingame money for Adding people to their plots and for clearing.  
I don't see any support for this PlotSquared. 
Can it be added?

**Comment by MattBDev** [comment]
I will certainly add that.

**Comment by boy0001** [comment]
Well if city is doing the commannd api (#898), it could have some mechanisms to simplify that. Maybe just some callback to confirm final execution of the command.

**Comment by boy0001** [comment]
Need to rework the commands to use the new API, but economy is now centralized to the MainCommand class. 

Note to @MattBDev : This isn't city's CommandAPI, no idea what's happening with that. I just reworked existing classes (so it's still backwards compatible and I won't need to update all addons). Won't be as clean as a complete rewrite. 

Note to self:
The commands will need to switch from SubCommand (deprecated) to Command and properly call the runnables. The first runnable before execution, the other after execution. Reason for doing it this way is that clear (and a good number of other commands) are executed asynchronously and won't have a result immediately. 

If calling the runnables seems like a pain for non-async commands, I should add async var to the command declaration class. Then add different handling of that in the MainCommand class.

**Comment by boy0001** [comment]
Done.
