### ISSUE TITLE
Plot chat is broken with  3.3.1

### ISSUE THREAD

**Issue by xion87** [IntellectualSites/PlotSquared#930]
I just upgraded plotsquared to 3.3.1 and seem plot chat don't work anymore it do nothing... i am using 1.8.8.

**Comment by MattBDev** [comment]
Do you have any other chat modifying plugins?

**Comment by xion87** [comment]
chatcontrol pro, and was all working before the plotsquared upgrade from 3.2.26 to  3.3.1

**Comment by EvilOlaf** [comment]
CHC pro using kind a chatroom thing which cancels the normal chatevent. Might be interesting.

**Comment by xion87** [comment]
I dont think is  a chc pro issue that was working fine in the old version, is a plotsquared change that break it...

**Comment by EvilOlaf** [comment]
I did not say that this is CHCs fault. Just wanted to mention this behavior ;)

**Comment by Johandrex** [comment]
Same issue here.

**Comment by Johandrex** [comment]
And ChatControl isn't modifying the chat.

**Comment by xion87** [comment]
i just reverted to old version of plotsquared and working fine and great

**Comment by Maxetto** [comment]
Same issue, using only EssentialsChat

**Comment by MattBDev** [comment]
I think this relates to persistent metadata since the code for the chat listener has not changed.

**Comment by Byteflux** [comment]
> I think this relates to persistent metadata since the code for the chat listener has not changed.

b95fdeccca76f42dc7b9a1338fc5eb4954bc22ba
