### ISSUE TITLE
/p h:[Alias] not work in other worlds

### ISSUE THREAD

**Issue by Andre601** [IntellectualSites/PlotSquared#931]
**Debug paste link**:http://hastebin.com/agesalohap

**Description of the problem**:
If I use /p h:[Alias] (For example: /p h:Plot1 in a world without the plot with that alias, I wont be teleportet and recieve this message:
"[P2] Found no plots with your Search Query
 [P2] Thats not a valid Plot id"

if I use it in the World, that have this plot with the alias, everything works fine...

**How to replicate**:
Simply use /p h:[Alias] in a world without a plot with that Alias

Make sure you've completed the following steps (put X inside of brackets):
- [X] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [X] Made sure you're using an updated version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by rErEaT** [comment]
sure!

**Comment by boy0001** [comment]
How many plot worlds do you have?

**Comment by Andre601** [comment]
3 Plotworlds.
Before I updatet plotSquared to te newest version the /p h:[Alias] worked.

is use Spigot 1.8.8 for my server

**Comment by MattBDev** [comment]
@boy0001 I think it broke when you tweaked the visit command in commit ff0ac79

**Comment by boy0001** [comment]
@MattBDev 
Not related to that. MainUtil#getPlotByString(...) was changed at some point to require you to either be in the world, or there to be only one plotworld. Aliases are a per world thing. Should be fixed in 66da71bc9ff18b016c908319fec98a0e520c9fc1
