### ISSUE TITLE
Clear does not clear the plot properly

### ISSUE THREAD

**Issue by manuelgu** [IntellectualSites/PlotSquared#932]
# Bug report template
**Debug paste link**: http://hastebin.com/oqekedonil.vala

**Description of the problem:**
`/plot clear` does not properly clear the plot and creates patches of other blocks
https://youtu.be/QoplSxA0m6Q

**How to replicate**:
`/plot clear` on a random plot
Make sure you've completed the following steps (put X inside of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by cindyker** [comment]
I am also having this issue with Spigot 1.9 , PlotSquared 1.3.3
Reset causes the same problem as clear.
http://puu.sh/nvGly/a6dbc2daf0.jpg

It took me restarting the server and clearing again to fix the plot.

**Comment by boy0001** [comment]
Seems to only be an issue with 1.9, are you running the latest version of spigot?

**Comment by manuelgu** [comment]
yes, running 1.9 with 3.3.0 from the Spigot Page.

**Comment by boy0001** [comment]
Does reconnecting fix the issue?

**Comment by rErEaT** [comment]
I got this issue on 1.8.8

generate air...

**Comment by manuelgu** [comment]
When I clear any plot, it does not clear the plot (for the client) but when you re-enter the chunks (teleport to spawn, then go back) it appears to be cleared.

**Comment by rErEaT** [comment]
@manuelgu Not working for me :(

**Comment by manuelgu** [comment]
Looks like it is not 100% reproducable. If you rightclick a block, it appears to be the correct one again.

**Comment by cindyker** [comment]
I am not getting any blocks in the middle of my plots. I can place blocks in the holes, leave the server and come back, still giant hole.
Only a restart after this issue, fixes it. Its as if the generator is confused as to what to place.

 If you are just getting invisible blocks, spigot did make an update for players not seeing chunk updates. I have that fix on my server and it has a fixed a worldedit regen issue I was having, but has not fixed this issue. :(

**Comment by manuelgu** [comment]
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/0cd671108591fd6f16696379280b235fdbb7dca8 This might also be related to the issue

**Comment by JKnetz** [comment]
Same issue here
