### ISSUE TITLE
/p clear is creating terrain

### ISSUE THREAD

**Issue by SpaceWeedMC** [IntellectualSites/PlotSquared#933]
# Bug report template (clear for feature request)
http://hastebin.com/etomudomeh:

/p clear for the bridge template:

Claim a plot and do /p clear:

Make sure you've completed the following steps (put X inside of brackets):
- [X] Include `/plot debugpaste`
- [ ] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [X] Made sure you're using an updated version of PlotSquared
- [ ] Made sure the bug/error isn't caused by any other plugin

**Comment by SpaceWeedMC** [comment]
Picture!

http://prntscr.com/abpftj

**Comment by manuelgu** [comment]
Might be related to or is a duplicate of #932

**Comment by boy0001** [comment]
Try: https://github.com/IntellectualSites/PlotSquared/wiki/Manual-generator-setting

**Comment by boy0001** [comment]
Will reopen if the above does not solve your issue.
