### ISSUE TITLE
plot unclaim

### ISSUE THREAD

**Issue by rErEaT** [IntellectualSites/PlotSquared#934]
# Bug report template (clear for feature request)
**Debug paste link**:
http://hastebin.com/izezumarus

**Description of the problem:**
/plot unclaim is not working in the newest version!

**How to replicate**:

Make sure you've completed the following steps (put X inside of brackets):
- [x] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [X] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by rErEaT** [comment]
Oh removed unclaim command.

So how I can unclaim the plots?

**Comment by boy0001** [comment]
`/plot delete`
`/plot setowner none`
`/plot purge`
