### ISSUE TITLE
Translate error

### ISSUE THREAD

**Issue by rErEaT** [IntellectualSites/PlotSquared#936]
# Bug report template (clear for feature request)
**Debug paste link**:
http://hastebin.com/izezumarus

**Description of the problem:**
I dont know but not working my translate!
http://pastebin.com/XjHgtjkG

**How to replicate**:

Make sure you've completed the following steps (put X inside of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by boy0001** [comment]
Not a bug, you just messed up the configuration:
http://hastebin.com/ajuvitugol.bash

**Comment by rErEaT** [comment]
whats wrong, then, can you fix my translate?
