### ISSUE TITLE
Unclaim command problem. Hole in the player plot

### ISSUE THREAD

**Issue by maxlehot1234** [IntellectualSites/PlotSquared#937]
# Bug report template (clear for feature request)
**Debug paste link**:
http://hastebin.com/yejutepobu
**Description of the problem:**
A player unclaim his plot and have this in the middle of it:
http://imgur.com/RyVh0YP

I don't know how this happen, because unclaim command doesn't exist on latest version...

I use Spigot 1.8.8 with Java 8

Make sure you've completed the following steps (put X inside of brackets):
- [ X] Include `/plot debugpaste`
- [ ] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [X ] Made sure you're using an updated version of PlotSquared
- [X ] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment]
upgrade to 3.3.1 because this bug has been fixed. the command is /plot delete
