### ISSUE TITLE
Explosion prevention is broken

### ISSUE THREAD

**Issue by zombachu** [IntellectualSites/PlotSquared#938]
**Debug paste link**: http://hastebin.com/zuqabibuca

**Description of the problem:** TNT explosions in claimed plots are allowed, no matter what the flag is set to. If the TNT is in an unclaimed plot or in a road, then explosions are cancelled as usual.

[Picture 1](http://puu.sh/nxlZH/54d808f236.png) The explosion flag is not set in the plot in the picture, yet damage is still done. Explosions are allowed away from the road as well.

[Picture 2](http://puu.sh/nxlyt/71ce8923d5.png) TNT that is lit in a road or unclaimed plot causes no damage.

[Picture 3](http://puu.sh/nxlEY/a8d9482ee7.png) TNT still causes damage in a plot where explosions are explicitly set to false.

**How to replicate**: Light TNT in the scenarios mentioned above

Make sure you've completed the following steps (put X inside of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by zombachu** [comment]
Just tried with beds and the hell biome, and while no damage is done I get some NPEs in console: http://hastebin.com/voxixepana

**Comment by boy0001** [comment]
Update the plugin.

**Comment by zombachu** [comment]
I'm currently using the latest available version from the spigot page and I'm still having the issue. /p version [tells](http://imgur.com/g6rSnw7) me I'm using the latest version, in addition to the message on startup. For some reason on the site it says that the latest version is 3.3.1, but the jar that it gives me says it's 3.3.0.

**Comment by boy0001** [comment]
Try: 
https://www.spigotmc.org/resources/plotsquared.1177/download?version=73678

**Comment by zombachu** [comment]
Now I'm having the opposite issue: Claimed plots work fine (whether I didn't set the flag or if I set explosions to false), but unclaimed plots and roads now explode
