### ISSUE TITLE
Problem with the claim command and border

### ISSUE THREAD

**Issue by maxlehot1234** [IntellectualSites/PlotSquared#939]
# Bug report template (clear for feature request)
**Debug paste link**:
http://hastebin.com/yejutepobu
**Description of the problem:**
When I claim a plot, (when they are large (200x200)) in my case, I get this:
http://imgur.com/6XRYbda
Redstone_block should replace stone_slab, but it was not put succesfully :(

When I dispose the plot, I get this: http://imgur.com/F0FCPSd
Redstone_block stay as border instead of being replace...

I need to disconnect and reconnect to fix this problem...

I use latest plotsquared version, spigot 1.8.8, java 8

Thank you, if you can find  away for this ;)

Make sure you've completed the following steps (put X inside of brackets):
- [X] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)]-(https://github.com/IntellectualSites/PlotSquared/issues)
- [X] Made sure you're using an updated version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment]
@maxlehot1234 Try updating and letting us know if it is fixed in 3.3.1

**Comment by Sauilitired** [comment]
@maxlehot1234 Was this issue ever resolved?
