### ISSUE TITLE
How to enable Killing of mobs in unclaimed areas

### ISSUE THREAD

**Issue by batchkrazy** [IntellectualSites/PlotSquared#942]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/xesihoyibi
**Description of the problem:**
how to enable killing of mobs in unclaimed area's
tryn to run as survival but not being able to kill hostiles in unclaimed areas
**How to replicate**:
try to kill mobs in an unclaimed area
Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by boy0001** [comment]
`plots.admin.pve.unowned`
`plots.admin.pve.road`
