### ISSUE TITLE
/plot auto IndexOutOfBounds

### ISSUE THREAD

**Issue by Maxetto** [IntellectualSites/PlotSquared#943]
After updating to [THIS](https://github.com/IntellectualSites/PlotSquared/commit/b59665b00b9b84f825bc9eecfeadf484719188f7) commit, ~~road regen doesn't count any custom roads made with "/p createroadschematic".~~

Also, whenever someone does /p auto it gives [THIS](http://pastebin.com/A6uGs4j1) error.

Hope for a prompt fix... Thanks.

~~EDIT: Seems to search for road schematics in "<root>/plugins/PlotSquared/plugins/PlotSquared/schematics/GEN_ROAD_SCHEMATIC/<world>"~~

~~EDIT2: Found to be an issue from Config not updating. Solved by manually changing the option~~

Using: Spigot 1.8.8

**Comment by Maxetto** [comment]
Still [not fixed](http://pastebin.com/PPbpbzUX). It happens when I use /p auto on my second Plot World (as I have a 32x Plot World and a 64x Plot World).
This also breaks /p clear and /p delete (and world generation (?)).

Also, "/p list" returns: "Possible values: [Ljava.lang.String;@7301fab"

Also, "/p rate next" sometimes sticks to a Plot, even if you already voted it.

**Comment by MattBDev** [comment]
We don't have a working build server at the moment. We haven't for awhile due to many issues. Anyways, did you build the jar with my commit? If you did, do you have a custom caption for OWNER_SIGN_LINE_* ?
Please file another issue report for the other things you mentioned.

**Comment by Maxetto** [comment]
Yes, I have those from Italian Language:
```
signs:
  owner_sign_line_4: '&3Claimato'
  owner_sign_line_3: '&2%plr%'
  owner_sign_line_2: '&1Proprietario:'
  owner_sign_line_1: '&1ID: $1%id%'
```
