### ISSUE TITLE
[Craft Scheduler Thread - 21/WARN]: Exception in thread "Craft Scheduler Thread - 21"

### ISSUE THREAD

**Issue by AuthMe** [IntellectualSites/PlotSquared#944]
**Debug paste link:**
http://hastebin.com/itusewevin

**Description of the problem:**
This problem only happend after a player going in a plot, and any other things are normal.
```
[19:48:55] [Craft Scheduler Thread - 21/WARN]: Exception in thread "Craft Scheduler Thread - 21" 
[19:48:55] [Craft Scheduler Thread - 21/WARN]: org.apache.commons.lang.UnhandledException: Plugin PlotSquared v3.3.0 generated an exception while executing task 109
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
```

**How to replicate**:
When a player going in a plot.

**Other:**
Server Version: KCauldron 1.7.10
PlotSquared Version: 3.3.1
Java Version: 8u74.
The old version of PlotSquared is no this problem.
So what should I do or this is a bug or... Thanks!
... And sorry for my bad English, oooooooh, I think I need to learn English WELL!...

`2016-03-10 10:19:19: Uploaded the debug paste.`

**Comment by MattBDev** [comment]
We can't help since there is no `/plot debugpaste` to show us any other details you may have left out. That error doesn't give us much to work on. In fact, it gives us nothing to work off of.

**Comment by AuthMe** [comment]
@MattBDev I uploaded the Debug Paste. Please take a look at it, I really can not find what is wrong ......(So I guess the question is KCauldron's, or ......)

**Comment by MattBDev** [comment]
@AuthMe Redownload the plugin from spigot's website and grab a new version of KCauldron. If the issue persists then let us know.

**Comment by AuthMe** [comment]
@MattBDev I use lasted KCauldron, and I try to use Thermos, but...
`http://hastebin.com/zoforetoke`
Always had this.

**Comment by sourcepowered** [comment]
I got this problem, too.
And I use KCauldron 200, I think this is a bug of server.

**Comment by MattBDev** [comment]
You guys may want to contact the developers of KCauldron and ask for feedback. Also ask them why the hell they aren't updated to 1.8 yet, lol.

**Comment by AuthMe** [comment]
@MattBDev Do not upgrade to 1.8, because the 1.7.10 has a lot of Mods. So what should we do, Abandon Mod server?...:(

**Comment by MattBDev** [comment]
@AuthMe I'm not telling you to upgrade. I'm just saying that there are plenty of 1.8 mods.

**Comment by boy0001** [comment]
Since there's no API for sending titles for that version PlotSquared has to use NMS. That's just the error from that and can be ignored.
