### ISSUE TITLE
Food can bypass protection

### ISSUE THREAD

**Issue by Rasre** [IntellectualSites/PlotSquared#945]
# Food can bypass protection

**Description of the problem:**
With food (e.g. bread) you can bypass the protection on other plots. By right click with sneaking you can open chests, furnaces or workbenchs.

You can use isSneaking() with if() to prevent it.

**Comment by MattBDev** [comment]
Please provide a `/plot debugpaste`
I will check this out though.

**Comment by Rasre** [comment]
Here is the link: http://hastebin.com/ecogiwihec

**Comment by MattBDev** [comment]
I wasn't able to reproduce this. Can you test to make sure that it isn't another plugin causing this issue?

**Comment by Rasre** [comment]
I dont know atm. I'll try it.

**Comment by Rasre** [comment]
I only use the plugins PlotSquared, PEX and Multiverse. The bug is still present...

**Comment by Rasre** [comment]
I can show you the bug on my server. Please send me your MCName. The IP is Atoxmine.de but i need to add you to the whitelist.

**Comment by MattBDev** [comment]
My username is the same as it is on here. I'll be on in 5 minutes (assuming you see this message during that time)

**Comment by Rasre** [comment]
Ok i added you.

**Comment by Rasre** [comment]
Hey, can you please provide a new version today?

**Comment by MattBDev** [comment]
I haven't been able to fix it yet. I need to talk to @boy0001 about it.

**Comment by Rasre** [comment]
Maybe i can help you. I also develop plugins. Please send me the source of
the protection.

Matt <notifications@github.com> schrieb am Sa., 12. Mär. 2016 17:37:

**Comment by MattBDev** [comment]
If you do need a quick fix, I recommend adding all the food items to the PlayerInteractEvent listener in the PlayerEvents class on the bukkit module. That's the quickest fix I can think of at the moment but it isn't the most reliable fix, which is why I haven't implemented it.

**Comment by Rasre** [comment]
Good idea! I'll do ut later. Thank you!

Matt <notifications@github.com> schrieb am Sa., 12. Mär. 2016 17:41:

**Comment by boy0001** [comment]
Should be fixed.
