### ISSUE TITLE
One of my merged plots continue to be over-claimed by some random person.

### ISSUE THREAD

**Issue by RenoLite** [IntellectualSites/PlotSquared#946]
# One of my merged plots continue to be over-claimed by some random person..)

**Description of the problem:** So I have a merged plot in the shape of an "L" and every now and then, someone manages to claim one of the plots that was previously mine.

**How to replicate**: Unknown.

**Comment by boy0001** [comment]
Could you let us know how you resolved this issue?

**Comment by RenoLite** [comment]
I didn't.

**Comment by manuelgu** [comment]
@RenoLite Why did you close the issue then?
