### ISSUE TITLE
Plot auto StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Claudio18** [IntellectualSites/PlotSquared#947]
**Debug paste link**: http://hastebin.com/umixutiwuv.avrasm

**Description of the problem**: We have different worlds for different builder ranks. The main world where you first spawn in can't run the command /plot auto. Other worlds you can.

**How to replicate**: Not exactly sure how to replicate.

Make sure you've completed the following steps (put an X between of brackets):
- [http://hastebin.com/koqorehobe] Include `/plot debugpaste`
- [Was never resolved] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment]
This was fixed. We just haven't released the version with the fix yet. You also did not properly fill out the issue template
