### ISSUE TITLE
Economy

### ISSUE THREAD

**Issue by AshourAziz** [IntellectualSites/PlotSquared#948]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
ONLY error found in logs:
http://pastebin.com/mVwCSPBu

**Description of the problem:**
Plots are not costing anyone money.

**How to replicate**:
Two worlds, plots via /plotme auto and /plotme claim the cost is not being added.

Make sure you've completed the following steps (put an X between of brackets):
No errors what so ever. Using latest 1.9 vault.

**Comment by MattBDev** [comment]
Please provide a `/plot debugpaste` or your issue will be closed tomorrow. Follow the issue template in the future if you require assistance.
