### ISSUE TITLE
/plot clear & /plot auto error in console

### ISSUE THREAD

**Issue by BloodyHarvest** [IntellectualSites/PlotSquared#949]
**Debug paste link**: http://hastebin.com/omaniwebad

**Description of the problem:** Upon running /plot auto or /plot clear it creates an error in the console, the claiming and clearing seem to work but it still doesn't give me a good feeling seeing the error. @Empire92 (MBon29 suggested tagging you)

Error: http://prntscr.com/ae39a2
          http://prntscr.com/ae16rq

**How to replicate**: Typing /plot clear or /plot auto 

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment]
Yeah I couldn't figure this out (probably overthinking this)

**Comment by boy0001** [comment]
Line 128 of your settings.yml
> `block_claimed: 'null'`

Set that to a valid block name or id
