### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by WilliamEstrela** [IntellectualSites/PlotSquared#950]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/okufagobay

**Description of the problem:**
Crash

**How to replicate**:

I use plotsquared in version 1.9 , created the worlds in vanilla mode with streets (http://prntscr.com/aeb1c0) , to walk the plots using fly the server crashes

Make sure you've completed the following steps (put an X between of brackets):
- [X] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [X] Made sure you're using an updated version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by manuelgu** [comment]
This crash is not caused by PlotSquared. Seems like SimpleClans is the reason for the crash

**Comment by boy0001** [comment]
@manuelgu Can't confirm either without the crash log. Those errors are before the crash, though it's the obvious culprit.

@WilliamEstrela 
Please provide the crash report and I can reopen this issue.

**Comment by boy0001** [comment]
Replicated:
http://hastebin.com/xatisoyowe.avrasm

**Comment by manuelgu** [comment]
@boy0001 Under which circumstances?

**Comment by manuelgu** [comment]
Might or might not be related.
http://hastebin.com/joticibahe.avrasm

PlotSquared v3.3.1

**Comment by WilliamEstrela** [comment]
I pulled the simplesclans and the crash continues

**Comment by WilliamEstrela** [comment]
crash report http://hastebin.com/donizewuxi.avrasm

**Comment by WilliamEstrela** [comment]
http://prntscr.com/aeygnu
