### ISSUE TITLE
Skull Horse on the road............

### ISSUE THREAD

**Issue by AuthMe** [IntellectualSites/PlotSquared#955]
Sometimes I find some Skull Horse on the plot world's road, and Skull on their back... and player killed by them... Oh my god what happend? Is this a hew feature for 1.9? This is... What the f**k...

Everything is ok, I can't find any problem on log or config.
What should I do? Thanks!

**Comment by boy0001** [comment]
It's a 1.9 feature. You can disable mob spawning for the world if you don't want them spawning.
