### ISSUE TITLE
Please add support for CBWrapper

### ISSUE THREAD

**Issue by ME1312** [IntellectualSites/PlotSquared#956]
### Description of the problem:
Theres an error with the combination of plugins CBWrapper and PlotSquared when using any worldedit command. It seems to be the same error each time and is caused by this plugin's WE listener so I'll post it below.

### The Error:
The error is available [here](http://pastebin.com/DkP1jGTS) for viewing.

### How to replicate:
Add the plugins PlotSquared and CBWrapper to a server and attempt to run any world edit command via the command block using command '/cw &lt;command&gt;'

**Comment by boy0001** [comment]
Yep. It's from WorldEdit saying it's a player, then PlotSquared trying to get a player object from it, which obviously doesn't exist.

Would it make sense for WorldEdit from command blocks to also be restricted to plots?

**Comment by ME1312** [comment]
Command blocks should probably be left unrestricted because only OPs can use them. (or otherwise a configuration option to toggle command block restriction)
