### ISSUE TITLE
Database Locked.

### ISSUE THREAD

**Issue by BoxmanCaleb** [IntellectualSites/PlotSquared#959]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/bavefugexi

**Description of the problem:**
Upon launch I get this error, "java.lang.UnsatisfiedLinkError: /tmp/sqlite-3.7.2-libsqlitejdbc.so: /tmp/sqlite-3.7.2-libsqlitejdbc.so: failed to map segment from shared object: Operation not permitted". And it says in chat when I try /plot home, "Found no plots with your search query" When just a few moments ago I had a plot, but after reboot and moving my server to my main users home directory this started happening.

**How to replicate**:
Seems that it only occurs after I move my files out of my users folder to his main /home directory.

Make sure you've completed the following steps (put an X between of brackets):
- [X] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [X] Made sure you're using an updated version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment]
The debug paste has expired and I can't reproduce this issue. Please resubmit if it is still an issue.
