### ISSUE TITLE
Sign is preventing claiming of plots.

### ISSUE THREAD

**Issue by jaboy** [IntellectualSites/PlotSquared#964]
**Debug paste link**:
http://hastebin.com/kebijigove

**Description of the problem:**
On an unclaimed plot, when an empty sign is placed where the plots "info" sign would normally be, ps2 makes an error when trying to use /plot auto, or /plot claim.

**How to replicate**:
on an unclaim plot, place an empty sign where the info sign would be.
Attempt to use /plot claim on the unclaimed plot

**extra info**
I have a lot of empty signs on unclaimed plots, because i accidentally created the road schematic with the sign in place.
I was not aware that i had to remove the sign, when creating the road schematic.

My server log contains:
Me logging in, doing /plot auto, and get an error
I attempt doing /plot claim, and get an error.
Then i removed the sign and did /plot claim, this time successful,
(unrelated) I then delete the plot with /plot delete, and do the debug paste 

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [x] Made sure you're using an updated version of PlotSquared
I am using the version 3.3.0, the release from spigot.org, not a dev build. 
- [x] Made sure the bug/error isn't caused by any other plugin.
As you see in my debugpaste, i only have 3 plugins enabled, permissions, vault, and p2

**Comment by MattBDev** [comment]
I believe this is linked to an issue that @boy0001 recently resolved.
