### ISSUE TITLE
Entire world as one plot

### ISSUE THREAD

**Issue by Quicksteve** [IntellectualSites/PlotSquared#970]
## Description

A feature that allows you to use an existing world as one plot, e.g. spanning the entire world.
## Use Cases

The protection system P2 offers is great and the plot flags system is phenomenal. It would be amazing to be able to use these to control access/permissions to an entire world.
## Possible Issues

Certain command will probably not work, such as /plot clear. When a player is kicked from the plot, he/she needs to be moved to server spawn, not to outside of the plot (as there is no outside). No plot borders can be generated for obvious reasons, as well as that, no roads exist.

**Comment by jaboy** [comment]
just of curiosity
Don't worldguard offer the same protection ?
afaik, Worldguard is good as protecting the world, or region.
while plot squared is (currently only) good at protecting the plots and road.

It seems like a lot of work to rewrite plotsquared, when there is already a plugin that already does what you asked for :P

**Comment by MattBDev** [comment]
i agree with @jaboy

**Comment by Quicksteve** [comment]
P2 is much more user friendly than WorldGuard, and also offers more features. Anyway, I have poured a few hours of work into it and got it working pretty much.

#### General changes

- added a new type of PlotManager, returning always returning 0,0 as PlotID, returning Integer.MAX/MIN_VALUE as the edge coordinates and except for claim always returns false for all the other methods
- added a corresponding new PlotWorld, which statically sets its default home to MAX_VALUE on x and z and type to augmented, terrain to all vanilla
- added a corresponding Generator, which processes the setup data and sets the type and terrain to the correct values
- live patched a few P2 classes, mainly MainUtil to prevent Integer overflows (ex. getLargestRegion, getDefaultHome), access to the plot sign (removeSign, setSign), plot clearing (sets it to a no-op if it detects it is one of these worlds) , and a few command classes, such as Download, Auto, Trim and SchematicCmd

If there is any demand for it I would be happy to create a PR.

**Comment by boy0001** [comment]
Minecraft worlds are +/- 30,000,000 so you could be returning a much smaller value to avoid integer overflow issues. If you change a couple methods, you could get a functional clear/download:
https://github.com/IntellectualSites/PlotSquared/blob/master/Core/src/main/java/com/intellectualcrafters/plot/commands/Area.java#L395-L417
https://github.com/IntellectualSites/PlotSquared/blob/master/Core/src/main/java/com/intellectualcrafters/plot/commands/Download.java#L79-L96

From my understanding WorldGuard is made specifically for this kind of thing if you just have global flags. Would you like to clarify what specific features PlotSquared has that makes it more ideal than WorldGuard? I could consider adding this if there are reasonable usage cases where WorldGuard is incapable.

**Comment by Quicksteve** [comment]
- Being able to use the same system that you use to manage your plot to manage your world is great from a player's perspective
- Also great is the plot tier system; difficult to implement that same level of granularity
- Other small, but useful features: inbuilt home system, chat, music, etc.

These are some major points on why this would be useful. Thanks for the info on clear and download, I'll be implementing them in a few.

**Comment by Quicksteve** [comment]
I implemented the features a few hours ago after I wrote that post, and after further testing with a few players everything seems to work great.

**Comment by dordsor21** [comment]
P2 does worlds
