### ISSUE TITLE
Problem with Player Rights in Plots

### ISSUE THREAD

**Issue by Elitania** [IntellectualSites/PlotSquared#971]
Hello out there
Wre installed Plotsquared on a 1.8.8 Spigot (AMP from MCMyadmin)
Everything seems to work quiet well, plots are there, and in PEX we gave the Standard Package for Members to claim and buy plots.
When a player claims a plot, he can see the claiming, other players can see the owner if they enter to the plot too, but the claimed player cant build in his plot.
On all other worlds, the player can build (we allow this in essentials, and disallow it only over global flags per world)
Only admins can build in the plots...
we do not have any idea, whats going wrong on our server...
(but we are not the great Pro´s on that too ;-)
Is there a simple idea to fix our problem?
Thanks for every idea.

We use the following plugins:
Essentials (complete and wellconfigured)
Worldguard,worldedit,PEX,craftconomy3,orebfuscator,Nocheatplus,vault, lockette,
essentials protect, multiverse core, essentials anti build, area shop, multiverse portals, 
sign shop..

**Comment by boy0001** [comment]
Try the following:
`/region flag __global__ build allow`

Also check in your permissions file that players have build permission (Not sure how to check this on pex, but groupmanager uses `build: true` in the permissions file)

If there's any message sent when players try to place blocks etc that could also help. PlotSquared by default should be sending a message if it is preventing an action.

**Comment by Elitania** [comment]
hello Boy0001
Thank you for your kind answer. 
We tryed everything from Flags (we have some mulitworld server) till to all other Plugins to fix this.
All Player can interact on all worlds as we want this, and even when a player claim a Plot, it seems to be his plot (there is a wonderful animation showing in full screen the ownership of every plot)

Well, we have PEX instaled and configured very proper (as we can see on all the other worlds)
and off course we gave all members the standard rights for Plotsquared as described here..
But on the end, nobody can interact on his plot without OP....
Thats spooky :-)
This weekend we will check every line of every Plugin to find a solution, because there are plenty of kids waiting for our Server :-)
So any good idea would be more than nice...
yours sincerely
Thomas
PS. Sorry for my bad english... I am grandfather, and my generation wasnt teached in English in my country :-)

**Comment by waterlubber** [comment]
I appear to be having the same issue and even with all permissions ("*" in PEX and with OP) I cannot place in the plot worlds.

I can confirm this happens.
Here is my debug paste:

http://hastebin.com/milarusose
