### ISSUE TITLE
Suggestion: Plot claim PER WORLD

### ISSUE THREAD

**Issue by maxlehot1234** [IntellectualSites/PlotSquared#973]
Hi, I just want to know if its possible to allow player to do ./p auto ONLY in the world he was.

Example, I have 2 plots world on my server. Plots and plotscrea
If player was in plots and do ./p auto, it autoclaim a plt in plots world not plotscrea.

Thanks  because now, if a player do: ./p auto in plots world, the plugin can give him a plots in plotscrea world :(

Thanks again

**Comment by boy0001** [comment]
This shouldn't be happening with two worlds.

**Comment by MattBDev** [comment]
Is this still an issue @boy0001 @maxlehot1234
