### ISSUE TITLE
Plot clear put plot broder claim (not supposed too do this)

### ISSUE THREAD

**Issue by maxlehot1234** [IntellectualSites/PlotSquared#974]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
http://hastebin.com/gerasumasu

**Description of the problem:**
When a plaot was not claim, I have a hole in it (CAUSED BY PREVIOUS VERSION). I want to remove the hole, so I do ./p clear

It remove the hole but put the plot border like if this plot was claimed by a player, but this is not true...

I need to claim it and do ./p dispose after.

This is bad....

I have Plotsquared (3.3.1), Spigot 1.8.8, Java 8

Make sure you've completed the following steps (put an X between of brackets):
- [X] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [X] Made sure you're using an updated version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

Thanks if you can fix it ;)

**Comment by Maxetto** [comment]
I think this is intended as it would be a command for owned plots. Yet a case to check if a plot is claimed or not in order to choose the right plot border, would be much appreciated :)

**Comment by MattBDev** [comment]
Works as Intended
