### ISSUE TITLE
PER WORLD purge plots

### ISSUE THREAD

**Issue by maxlehot1234** [IntellectualSites/PlotSquared#975]
Hi, is it possible to add in a later version something to setup which worldds plots can be purge and not?

So with this, my main plots world can be auto-purge non-logged players after xxxxx days, but my secondairy world never purge plots.

It can be useful for my server and maybe a lot more ;)

Thanks

**Comment by boy0001** [comment]
Purge command:
'/plot purge world:<world>'

Or for the automatic plot clearing, set the keep flag to true for that world (settings.yml)
