### ISSUE TITLE
Plot kicking clients upon entry

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#976]
Version compiled off github march 17

upon entry of a specific plot you get kicked from the server:
PhanaticD lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.

I manually deleted the flags for the plot in the database and it fixed the issue, so I am confident that that was the problem. I am sorry I cannot say specifically which flag caused it, as I do not want to restart my production creative server over and over removing one each time

here are the flags for the plot that was causing the trouble:
vehicle-use:true,player-interact:true,use:70,misc-interact:true,greeting:&4&lNo Elytras,description:&4&lWearing Elytra Gets You Banned,pvp:true,titles:true,gamemode:CREATIVE,feed:1 10,fly:true,music:0,time:0,hanging-place:false,pve:true,farewell:&4&lDont bring back that damn Elytra,notify-leave:true

**Comment by boy0001** [comment]
Tested, works fine on normal spigot. This is caused by PaperSpigot.
https://github.com/PaperMC/Paper/issues/83
https://github.com/PaperMC/Paper/pull/84

**Comment by PhanaticD** [comment]
okay thanks sorry to bother :)
