### ISSUE TITLE
Titles not showing up and disappearing with delay

### ISSUE THREAD

**Issue by QUIQUELHAPPY** [IntellectualSites/PlotSquared#978]
**DESCRIPTION:**
When I enter a plot, the title is showed, but, it just appear and **disappear without any transitions**.

Also, in 1.8 I was working with titleapi and with plotsquared and now (1.9) i**f I don't remove titleapi the titles don't appear**.

Is there any way to fix the **first** issue? The **second one is something I will talk with the titleapi developer**.

[Trello Link](https://trello.com/c/1z1TdFzt/47-plotsquared)

**Comment by MattBDev** [comment]
Can you provide a `/plots debugpaste` without that we have nothing to work off of.

**Comment by boy0001** [comment]
I was lazy when updating to 1.9 and didn't finish coding the transitions for titles.

**Comment by QUIQUELHAPPY** [comment]
I leave the debug info here, if some of you can help me to fix that the titles don't appear when entering (or appearing by very little time [5ms or so]) would be amazing.

http://hastebin.com/nipuwesoxa

**Comment by boy0001** [comment]
Oh, 5ms, that's not normal then. Try updating the plugin:
http://ci.xephi.fr/job/PlotSquared/

**Comment by QUIQUELHAPPY** [comment]
Fixed.
You need to disable welcome title if you want to use title-manager with plotsquared on 1.9.
