### ISSUE TITLE
schemetic and template bug

### ISSUE THREAD

**Issue by Twi5TeD** [IntellectualSites/PlotSquared#979]
so i created an template and a schematic awhile ago and used to work fine i updated plotsquare and they both broke when i claimed a plot it would say not a valid schematic so i moved back to an older version of plotsquared and it works fine again

**Comment by MattBDev** [comment]
@Twi5TeD If you do not reply within 12 hours with a `/plots debugpaste` then this issue will be closed. Please use the issue template in the future.

**Comment by Twi5TeD** [comment]
http://hastebin.com/hujenudire plotsquared version 3.2.26
http://hastebin.com/uleboheraf plotsquared version 3.3.1

**Comment by Twi5TeD** [comment]
did you find a fix?
