### ISSUE TITLE
Showerthought I had for a new feature (super low priority imo)

### ISSUE THREAD

**Issue by zombachu** [IntellectualSites/PlotSquared#981]
We have /p merge, which is awesome, but what about /p split to split a plot into fourths or something? I'm not sure how it would work if road width % 2 != plot width % 2, but this was just an idea I had.

Some uses of this might be:

* A player wishes to have different flags set in different parts of their plot, but they don't want to (or can't) claim another plot to do so
* Same situation as the above, but with building permissions instead
* A player would like native warp points to go to themed areas of their plot
* Extreme laziness with manually building roads through their plot

I would imagine that this would require reworking a decent portion of the plugin (and it's not exactly an important feature in the first place) so if you close this issue now then that's totally understandable.

**Comment by boy0001** [comment]
https://github.com/IntellectualSites/PlotSquared/issues/21

**Comment by zombachu** [comment]
Ah, sorry

**Comment by zombachu** [comment]
Duplicate of #21
