### ISSUE TITLE
Plot Schematic issue

### ISSUE THREAD

**Issue by elmasbv** [IntellectualSites/PlotSquared#982]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**: http://hastebin.com/ogadefasaw

**Description of the problem: I set anything following 
https://github.com/IntellectualSites/PlotSquared/wiki/Usage:-Schematic-on-claim
And i set " on_claim: false` " , because i want the player after claim the plot to change in a simple grass plot , and when i reload the map ( using Multiverse Core ) , the plots are not loading with schematics .

When i set " on_claim: true` " that works fine .

**How to replicate**: I write everything at description of the problem . 

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment]
`on_claim: true` is what should be in your config. That means whenever someone uses the command `/plot claim` the schematic will appear. The schematic won't generate when the plots aren't loaded nor will they replace existing plots.
