### ISSUE TITLE
Plot Clusters not Working in 1.9 update

### ISSUE THREAD

**Issue by Sabache** [IntellectualSites/PlotSquared#983]
Server Log File:
[latestlog.txt](https://github.com/IntellectualSites/PlotSquared/files/180910/latestlog.txt)

/plot debugpaste Link:
http://hastebin.com/towasoreno

Basically I can not get the Cluster Function to work at all.. I have a server running 1.8.8 bukkit that I want to update to 1.9, but it is running a cluster. I have tried to run a local server several times, but the cluster system appears to be broken every time I work with it. This log and paste are from a raw server with the new files installed as a test on my laptop. They are giving me the same responses as the copy of the server I am trying to update. I am willing to restart the cluster in a fresh world, but can not even get it to recognize the cluster system properly. 

When I create a new plot-world using /plot setup and the Partial option (for cluster creation) it simply creates a new world with no clusters or cluster support.

**How to replicate**: 

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment]
@Sabache 
Try using the version of the plugin from this link: http://ci.xephi.fr/job/PlotSquared/
Let me know if it fixes the issue.

**Comment by Sabache** [comment]
Did not fix the issue.. My server just rebooted and now it has a similar problem.. it is still running 1.8.8 so I don't know what happened to it.
