### ISSUE TITLE
Unable to use plot saving/downloading/schematics - /p save replies with "failed to save"

### ISSUE THREAD

**Issue by jtcressy** [IntellectualSites/PlotSquared#985]
**Debug paste link**: http://hastebin.com/arekijofev

**Description of the problem:**
Plotsquared does NOT save or use plot schematics

**How to replicate**:
/p save replies with "failed to save"

- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [x] Made sure you're using an updated version of PlotSquared
- [x] Made sure the bug/error isn't caused by any other plugin

I recently made a review on the spigotmc page for plotsquared, but I couldn't reply to the author's reply so i just made a post here.

**Comment by boy0001** [comment]
Invalid configuration. You have the web link pointing to a non-existent web interface (https://www.jtcressy.net/plot/). Please setup the interface correctly, or reset it back to it's default value:
https://www.empcraft.com/plot/

**Comment by jtcressy** [comment]
Were you able to visit https://www.jtcressy.net/plot? Should it be in the subfolder /plots instead? You guys offer the web front end as a distributable package to install on webservers, Is there a guide to properly setup the web interface?

**Comment by boy0001** [comment]
Doesn't matter which subfolder, but that's not the correct web interface for those commands.
PlotWebPHP is just for `/plot schematic`

You need to install PlotUpload:
https://github.com/IntellectualSites/PlotSquared/wiki/Plot-web-interface

**Comment by jtcressy** [comment]
Ok, I installed PlotUpload and saving/downloading works after i pointed the plugin to https://www.jtcressy.net/plotupload

Yay!

Now, i guess i could file another issue, but i'm unable to upload schematic files via either web interface and have the ability to access it ingame on the server. (and i have linked the plugins/PlotSquared/schematics to <webserver>/plots/schematics)

**Comment by boy0001** [comment]
With plotupload you need to enable uploading in the configuration.php, it's disabled by default. It'll prompt you to use the schematic paste command once it's uploaded.
