### ISSUE TITLE
Feature Request: Additional money deduct for plot buy

### ISSUE THREAD

**Issue by darknightcore** [IntellectualSites/PlotSquared#987]
Is there a way or yould you please add it ? 
To additional deduct money from a player(multiplier) when merging or buying a new plot in the world.
e.g.
Limit 9 Plots in the world
Plot Cost: 500
1. Plot 500
2. Plot 1000
3. Plot 1500
and so on.

**Comment by boy0001** [comment]
```
prices:
  claim: 100 * {arg} + 50
```
Note: Any javascript syntax is supported provided it returns a double.
