### ISSUE TITLE
URGENT! no longer protecting plots

### ISSUE THREAD

**Issue by DannyPokemon** [IntellectualSites/PlotSquared#988]
# Bug report template (Follow this template unless you are making a feature request.)
**Debug paste link**:
this problem has nothing that comes from the console log etc.
http://hastebin.com/esetebupul

**Description of the problem:**
after restoring the world from a backup, i restarted the server to find that the world had been unloaded. i loaded it up again and it was no longer protecting plots, nor allowing use of /plot h, saying it doesn't exist.
**How to replicate**:
idk!
Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [x] Made sure you're using an updated version of PlotSquared
i'm on the latest version
- [x] Made sure the bug/error isn't caused by any other plugin
as far is i know it is NOT Multiverse that is the issue.

**Comment by manuelgu** [comment]
> nor allowing use of /plot h, saying it doesn't exist.
Please elaborate.

Also, adding a `/plot debugpaste` would actually be quite helpful in this case.

**Comment by DannyPokemon** [comment]
added to OP.

**Comment by DannyPokemon** [comment]
elaborate? well when i do any command when i am standing in what would be a plot, like /plot info, it tells me i am not in a plot........ it's wiird.

**Comment by manuelgu** [comment]
Are you able to teleport to a plot in general?
`/plot tp 1;1`

**Comment by DannyPokemon** [comment]
nope. doesn't exist not in a valid plot world. i am in the plot world! AAH

**Comment by manuelgu** [comment]
I am assuming the world is called `Creative`? Please check your multiverse file if the generator for that world is set correctly.

**Comment by DannyPokemon** [comment]
oki gimme a sec

**Comment by DannyPokemon** [comment]
here is the `creative` entry in my `worlds.yml`:

`  Creative:
    ==: MVWorld
    hidden: 'false'
    alias: ''
    color: WHITE
    style: NORMAL
    pvp: 'true'
    scale: '1.0'
    respawnWorld: ''
    allowWeather: 'true'
    difficulty: EASY
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
    entryfee:
      ==: MVEntryFee
      amount: '0.0'
      currency: '-1'
    hunger: 'true'
    autoHeal: 'true'
    adjustSpawn: 'true'
    portalForm: ALL
    gameMode: SURVIVAL
    keepSpawnInMemory: 'true'
    spawnLocation:
      ==: MVSpawnLocation
      x: 33.0
      y: 40.0
      z: -22.0
      pitch: 0.0
      yaw: 0.0
    autoLoad: 'true'
    bedRespawn: 'true'
    worldBlacklist: []
    environment: NORMAL
    seed: '7695491139697299342'
    generator: 'null'
    playerLimit: '-1'
    allowFlight: 'true'
`

**Comment by DannyPokemon** [comment]
it says: `generator:null`; i'll change it to what exactly?

**Comment by DannyPokemon** [comment]
gonna close the world and sort it out in morning EST.

**Comment by manuelgu** [comment]
It should be the following:
`generator: PlotSquared`

**Comment by DannyPokemon** [comment]
Ok, will try.
