### ISSUE TITLE
/plot clear makes a giant hole

### ISSUE THREAD

**Issue by lasercar** [IntellectualSites/PlotSquared#991]
**Debug paste link**: http://hastebin.com/olivutarob

**Description of the problem**: When doing `/plot clear`, a hole is created in the plot. This happens for any plot. The hole does not go away when relogging, and you can build or destroy blocks in the hole.

![2016-03-20_20 25 04](https://cloud.githubusercontent.com/assets/6022168/13908902/09556c9c-eedb-11e5-9e7b-de5de157cb36.png)

**How to replicate**: `/plot clear`

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [x] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [x] Made sure you're using an updated version of PlotSquared
- [ ] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment]
Already fixed. See issue #953
