### ISSUE TITLE
Loading void broken chunks

### ISSUE THREAD

**Issue by WebShark025** [IntellectualSites/PlotSquared#993]
**http://hastebin.com/wolajojicu**:

Description:
Hi, I think this is a serious problem with PlotSquared v3.3.1.
Actually, It loads broken chunks. They are always void, but sometimes when we walk on them, it generates. Sometimes, we should Right click air blocks for the blocks to generate (we should right click each 1block  of that chunk.), Sometimes, It generates in wrong place. For example it generates bridges in the plot, it generates Grass and stone wrong, Or, it Generates full Air! We need to place blocks ourself! Nothing works, Clearlagg, Worldedit, Etc. 
![image](https://cloud.githubusercontent.com/assets/12953043/13944501/5b56daf0-f023-11e5-8802-8b06a449669b.png)
![image](https://cloud.githubusercontent.com/assets/12953043/13944558/bdbeaf56-f023-11e5-9c7d-f8b4428b9aac.png)

There is no way to fix this problem ourself. 
I Also found same thread, but not like this, and No answers on that.
Thanks for help!

**Comment by EvilOlaf** [comment]
When you click on a block and it disappears or you click on air and a block appears, this seems the the chunk update was not successful. Try teleporting to another world and then teleport back to refresh these chunks.

**Comment by WebShark025** [comment]
Thanks EvilOlaf for answer,
I did Restarted the server about 4 times, I teleported to some worlds and i came back to this world, I went to nether, I renamed the world, I tried to fix the world with Chunkster, etc.

Other problem is, WorldEdit does not works in theese places!!! it says '0 Blocks changed.' like im doing it under the bedrocks of the world.
Its not also for me, about 40-45 People have this problem in my server. (Totaly 994players had registered in my server.)

**Comment by WebShark025** [comment]
Update:

Pretty same as #953 , But this time it also breaks the roads. Using worldedit //regen makes it even worse.

**Comment by WebShark025** [comment]
Sorry for spamming,

Update: (Removed all plugins instead of P2,Essentials,Worldedit,MultiverseCore)

It replaces no blocks, But it does set blocks to AIR (and Undo works fine.)
When using //REGEN, It says the error in below image, and it sets everything to Stone & Andesite. Like a stone city...Phew
![image](https://cloud.githubusercontent.com/assets/12953043/13950347/090bc0c4-f048-11e5-98fe-c7154ba16333.png)

**Comment by MattBDev** [comment]
Probably something changed in NMS between 1.8 and 1.9 which either requires some extra code or breaks some existing code.

**Comment by WebShark025** [comment]
Fixed in new version of P2. Thanks alot ! <3
