### ISSUE TITLE
Send an user to a plot

### ISSUE THREAD

**Issue by QUIQUELHAPPY** [IntellectualSites/PlotSquared#994]
Hi!
I know this is the issues section, but I've looking for a while [here](https://github.com/IntellectualSites/PlotSquared/wiki/Commands) and I didn't find any command that let the console (or admin) send a player to a plot.

Is there any possible way to send somebody to a plot?

**Comment by manuelgu** [comment]
I think most servers have Essentials installed, so they can use `sudo` for it. However, it should be fairly simple to add a check for a third argument [here](https://github.com/IntellectualSites/PlotSquared/blob/master/Core/src/main/java/com/intellectualcrafters/plot/commands/Visit.java#L71).

**Comment by QUIQUELHAPPY** [comment]
Thanks!
