### ISSUE TITLE
Add CodeStyle to repo

### ISSUE THREAD

**Issue by MattBDev** [IntellectualSites/PlotSquared#996]
Add recommended code style to repo for Eclipse and IntelliJ. Best for when people want to contribute to the project.

**Comment by manuelgu** [comment]
https://google.github.io/styleguide/javaguide.html This one is the one used the most all over the web :)

**Comment by MattBDev** [comment]
@manuelgu I follow the Sponge Code Style because I like the small tweaks they made to it. Which one do you think we should go with?

**Comment by manuelgu** [comment]
I am totally fine with the changes Sponges Code Style has. The only thing I dislike is having an extra space between `class MyClass {` and the first member of a class.

The decision is up to you, I'm fine with both :+1:

**Comment by manuelgu** [comment]
Talking about code styling, running tests using [SonarQube](http://www.sonarqube.org/) could also be a fun thing to trial the code.

**Comment by Sauilitired** [comment]
Ey, I'll bump this. The sponge code style is great and all, though I don't like what they did to imports (though, that doesn't really matter to be honest).

**Comment by MattBDev** [comment]
Merged with #940
