### ISSUE TITLE
feature request: potion throw flag

### ISSUE THREAD

**Issue by PhanaticD** [IntellectualSites/PlotSquared#999]
by default anyone can throw potions anywhere. This can be annoying for players, so I am requesting a flag for players to be able to turn on potion throwing if they want it

**Comment by MattBDev** [comment]
I would think that potions would trigger a projectile event? Do they have their own event?

**Comment by MattBDev** [comment]
Answer to my own question: The plugin needs to listen to PotionSplashEvent and LingeringPotionSplashEvent

**Comment by boy0001** [comment]
Cancelling the event doesn't stop the splash.

**Comment by MattBDev** [comment]
@boy0001 No projectiles as far as I am aware have their animation canceled if the event is canceled. I tried with enderpearls.
